defmodule Jumble.ScowlDict.Size20.Length7.Dict do
  def get do
    %{"ceiprtu" => ["picture"], "deellry" => ["elderly"], "aelnpty" => ["penalty"],
      "abeoqru" => ["baroque"], "bgiknoo" => ["booking"], "ddeeirs" => ["desired"],
      "aegintv" => ["vintage"], "afgiiln" => ["failing"], "aflluwy" => ["awfully"],
      "deemorv" => ["removed"], "ciprsst" => ["scripts"], "cgiiknn" => ["nicking"],
      "abeehsv" => ["behaves"], "adepstu" => ["updates"],
      "adeelrt" => ["altered", "related"],
      "adegiln" => ["aligned", "dealing", "leading"], "aaenruw" => ["unaware"],
      "einnrsw" => ["winners"], "ginoprv" => ["proving"], "giillnw" => ["willing"],
      "cceeins" => ["science"], "ghinnop" => ["phoning"], "hlorsty" => ["shortly"],
      "aegorst" => ["storage"], "cgiknoo" => ["cooking"], "dggijnu" => ["judging"],
      "aeeelrs" => ["release"], "dgisstu" => ["disgust"], "adeefst" => ["defeats"],
      "mmopsty" => ["symptom"], "deloptt" => ["plotted"], "cdeenos" => ["encodes"],
      "aeiprtv" => ["private"], "ddeeinx" => ["indexed"], "elmosuv" => ["volumes"],
      "ehilost" => ["hostile"], "eiorrsw" => ["worries"], "cdeilpp" => ["clipped"],
      "accelno" => ["conceal"], "adilpry" => ["rapidly"], "aeginnr" => ["earning"],
      "acekpst" => ["packets"], "eghilnp" => ["helping"], "ddeippr" => ["dripped"],
      "cemootu" => ["outcome"], "eeefrsz" => ["freezes"], "enrrstu" => ["returns"],
      "ahilppy" => ["happily"], "aginprs" => ["parsing"], "adenpst" => ["pedants"],
      "eegikns" => ["seeking"], "deeirss" => ["resides", "desires"],
      "eorrttu" => ["torture"], "dginnou" => ["undoing"], "adegpru" => ["upgrade"],
      "addeopt" => ["adopted"], "celnoos" => ["console"], "eiorsst" => ["stories"],
      "dfgiinn" => ["finding"], "deioprs" => ["periods"], "aefgilr" => ["fragile"],
      "ainopss" => ["passion"], "defhist" => ["shifted"], "cemnooy" => ["economy"],
      "abborss" => ["absorbs"], "aeilrty" => ["reality"], "aceefpr" => ["preface"],
      "ginoppp" => ["popping"], "adiilnv" => ["invalid"], "eefinrs" => ["refines"],
      "degilnn" => ["lending"], "ailqtuy" => ["quality"], "aeinptt" => ["patient"],
      "aademnt" => ["mandate"], "abginsu" => ["abusing"], "cddeens" => ["descend"],
      "eginnop" => ["opening"], "eoopprs" => ["propose"], "eiknosv" => ["invokes"],
      "eelrstt" => ["letters"], "aaginst" => ["against"], "acejkst" => ["jackets"],
      "cgiklno" => ["locking"], "cdennoo" => ["condone"], "adeimrs" => ["misread"],
      "ceiosty" => ["society"], "ceegint" => ["genetic"], "ainrsst" => ["strains"],
      "acdeeln" => ["cleaned"], "aefginr" => ["fearing"], "beeentw" => ["between"],
      "eknortw" => ["network"], "aailmrt" => ["marital"], "aiorsuv" => ["various"],
      "egimnss" => ["messing"], "eefginr" => ["freeing"], "ceefnor" => ["enforce"],
      "adjsstu" => ["adjusts"], "deiilmp" => ["implied"], "afilquy" => ["qualify"],
      "agiilns" => ["sailing"], "abddenr" => ["branded"], "achmost" => ["stomach"],
      "imorrrs" => ["mirrors"], "addeemn" => ["amended"], "deelorw" => ["lowered"],
      "addegru" => ["guarded"], "gilnosw" => ["slowing"], "eggintt" => ["getting"],
      "gillnor" => ["rolling"], "adikmnn" => ["mankind"], "hiottuw" => ["without"],
      "einrssu" => ["sunrise"], "adilpsy" => ["display"],
      "aeeglnr" => ["enlarge", "general"], "deffnos" => ["offends"],
      "adeersv" => ["adverse"], "ddgiikn" => ["kidding"], "acffirt" => ["traffic"],
      "ginrsst" => ["strings"], "cdeeorv" => ["covered"], "deeeknw" => ["weekend"],
      "adenpps" => ["appends"], "giinnnw" => ["winning"], "deeiops" => ["episode"],
      "acgiknt" => ["tacking"], "cgiikkn" => ["kicking"], "efhilss" => ["selfish"],
      "adehknt" => ["thanked"], "eeirrtw" => ["rewrite"], "giinstu" => ["suiting"],
      "diprstu" => ["disrupt"], "ccesssu" => ["success"], "eeiqrru" => ["require"],
      "aerrstt" => ["starter", "restart"], "behorrt" => ["brother"],
      "aeilnst" => ["entails"], "aelttux" => ["textual"], "eegsssu" => ["guesses"],
      "eehhrtw" => ["whether"], "afissty" => ["satisfy"], "deisttw" => ["twisted"],
      "aadglru" => ["gradual"], "adeflot" => ["floated"], "cdeeitx" => ["excited"],
      "adegnrt" => ["granted"], "deelstt" => ["settled"], "abddeer" => ["bearded"],
      "dginorw" => ["wording"], "acforty" => ["factory"], "ccehios" => ["choices"],
      "ceglooy" => ["ecology"], "cehlost" => ["clothes"], "giiklnn" => ["linking"],
      "bginruy" => ["burying"], "ceeetux" => ["execute"], "aemrstt" => ["matters"],
      "adenstt" => ["attends"], "aeehrtw" => ["weather"], "ceiintz" => ["citizen"],
      "ceelrtu" => ["lecture"], "aderssu" => ["assured"], "ademnss" => ["madness"],
      "cdehkos" => ["shocked"], "bddelou" => ["doubled"], "aeiprrs" => ["repairs"],
      "aflmoru" => ["formula"], "acorrst" => ["carrots"], "eopprsu" => ["purpose"],
      "eilorrs" => ["lorries"], "adeirsv" => ["adviser"], "accehns" => ["chances"],
      "deeegmr" => ["emerged"], "cgilnoo" => ["cooling"], "deegimn" => ["deeming"],
      "egilntt" => ["letting"], "abssuwy" => ["subways"], "addeely" => ["delayed"],
      "ceinsst" => ["insects"], "addenot" => ["donated"], "allsuuy" => ["usually"],
      "defiinu" => ["unified"], "fgilnoo" => ["fooling"], "agmoprr" => ["program"],
      "aginrvy" => ["varying"], "aegilnv" => ["leaving"], "ceikoos" => ["cookies"],
      "aaagmnr" => ["anagram"], "eefhrrs" => ["refresh"], "ablnoty" => ["notably"],
      "einoprt" => ["pointer", "protein"], "adeeiss" => ["disease"],
      "ghhottu" => ["thought"], "eeginnu" => ["genuine"], "adeinst" => ["instead"],
      "ccilsty" => ["cyclist"], "belortu" => ["trouble"], "eeginrt" => ["integer"],
      "eilostt" => ["toilets"], "addefrt" => ["drafted"], "emmssuu" => ["museums"],
      "eghhist" => ["heights", "highest"], "aehnort" => ["another"],
      "deefrsu" => ["refused"], "aabdrst" => ["bastard"], "beefils" => ["beliefs"],
      "deiinot" => ["edition"], "adefhls" => ["flashed"], "erssuvy" => ["surveys"],
      "aelmnru" => ["numeral"], "dgiimnn" => ["minding"], "eloprtt" => ["plotter"],
      "cgiilns" => ["slicing"], "ginorst" => ["sorting", "storing"],
      "ceefprt" => ["perfect"], "acddees" => ["decades"], "agirtvy" => ["gravity"],
      "ehmorst" => ["mothers"], "elmopsy" => ["employs"], "glnoopr" => ["prolong"],
      "acinnot" => ["contain"], "dginott" => ["dotting"], "cginttu" => ["cutting"],
      "abceesu" => ["because"], "accdors" => ["accords"], "giklnoo" => ["looking"],
      "aamnprt" => ["rampant"], "emprttu" => ["trumpet"], "aeisttu" => ["situate"],
      "accistt" => ["tactics"], "eeginnv" => ["evening"], "efgorst" => ["forgets"],
      "giinnru" => ["ruining"], "iinrtty" => ["trinity"], "cdeeopr" => ["proceed"],
      "acdempr" => ["cramped"], "aeggglu" => ["luggage"], "ddeefns" => ["defends"],
      "allotty" => ["totally"], "agloopy" => ["apology"], "aegnntt" => ["tangent"],
      "cdehotu" => ["touched"], "aeelrsx" => ["relaxes"], "ainostt" => ["station"],
      "efilopr" => ["profile"], "ceiilnn" => ["incline"], "adehlnr" => ["handler"],
      "bdegirs" => ["bridges"], "ddginpu" => ["pudding"], "behiitx" => ["exhibit"],
      "aailrwy" => ["railway"], "ccehikn" => ["chicken"], "degopru" => ["grouped"],
      "abginnn" => ["banning"], "ceijstu" => ["justice"], "fgiilln" => ["filling"],
      "cginnnu" => ["cunning"], "eeemrtx" => ["extreme"], "adiknps" => ["kidnaps"],
      "belmopr" => ["problem"], "acforst" => ["factors"], "bbeilqu" => ["quibble"],
      "efhilms" => ["himself"], "gilnosv" => ["solving"], "eimnnot" => ["mention"],
      "inoopst" => ["options"], "ceilnst" => ["clients"], "abelnot" => ["notable"],
      "ceiorru" => ["courier"], "adehlns" => ["handles"], "eimprst" => ["permits"],
      "abeffls" => ["baffles"], "ccgilny" => ["cycling"], "aeinstv" => ["natives"],
      "cenrrtu" => ["current"], "efginrs" => ["fingers"], "aegnrst" => ["strange"],
      "gijmnpu" => ["jumping"], "bemnrsu" => ["numbers"], "delmosu" => ["modules"],
      "emrstyy" => ["mystery"], "cennott" => ["content"], "eeimnnt" => ["eminent"],
      "ahllosw" => ["shallow"], "deersss" => ["dresses"], "aehilvy" => ["heavily"],
      "iimnoss" => ["mission"], "egnoruy" => ["younger"], "giklnru" => ["lurking"],
      "acginst" => ["casting"], "aginstt" => ["tasting", "stating"],
      "aeglmns" => ["mangles"], "ceelmow" => ["welcome"], "acdimny" => ["dynamic"],
      "abcekrt" => ["bracket"], "deginnt" => ["tending"], "beggist" => ["biggest"],
      "eeopssx" => ["exposes"], "chipssy" => ["physics"], "adeprss" => ["spreads"],
      "adhiloy" => ["holiday"], "aiilmrs" => ["similar"], "adeilrt" => ["trailed"],
      "deghilt" => ["delight", "lighted"], "degglpu" => ["plugged"],
      "aclrsty" => ["crystal"], "beilrty" => ["liberty"], "ajlnoru" => ["journal"],
      "aehpprs" => ["perhaps"], "aeilprv" => ["prevail"], "cegnost" => ["congest"],
      "eeimprs" => ["premise"], "acdehmt" => ["matched"], "eilnovv" => ["involve"],
      "eeenpsx" => ["expense"], "bceorsu" => ["obscure"], "adehprs" => ["phrased"],
      "aegopst" => ["postage"], "deegssu" => ["guessed"], "ccilnou" => ["council"],
      "adeginr" => ["reading"], "adeekwy" => ["weekday"], "ceeenss" => ["essence"],
      "ilnsstu" => ["insults"], "ggiinnr" => ["ringing"], "adgiilt" => ["digital"],
      "cgiinpr" => ["pricing"], "addemns" => ["demands"], "hiorsty" => ["history"],
      "cfginor" => ["forcing"], "ccdnotu" => ["conduct"], "aegllly" => ["legally"],
      "abdnoyy" => ["anybody"], "cdeiprt" => ["predict"], "aefgorv" => ["forgave"],
      "acdehrs" => ["crashed"], "deefins" => ["defines"], "deimops" => ["imposed"],
      "accdesu" => ["accused"], "ggilnow" => ["glowing"], "ijlnoty" => ["jointly"],
      "dekopst" => ["desktop"], "cehrssu" => ["crushes"], "acgillo" => ["logical"],
      "agimnrs" => ["margins"], "cceinos" => ["concise"], "bgggino" => ["bogging"],
      "ddelmsu" => ["muddles"], "acinotu" => ["caution"], "aablmsy" => ["abysmal"],
      "ceessux" => ["excuses"], "ehnosty" => ["honesty"], "ddeiisv" => ["divides"],
      "aceiqru" => ["acquire"], "aadkrww" => ["awkward"], "acgikns" => ["sacking"],
      "aeirrsv" => ["arrives"], "ceiknss" => ["sickens"], "abdeglr" => ["garbled"],
      "aeilotv" => ["violate"], "agiilnn" => ["nailing"], "acehrrt" => ["charter"],
      "ainnost" => ["nations"], "eoppssu" => ["suppose"], "acfilry" => ["clarify"],
      "ginopst" => ["posting"], "adennoy" => ["annoyed"], "aeghrst" => ["gathers"],
      "eeiprsx" => ["expires"], "acelnru" => ["nuclear", "unclear"],
      "ainoppt" => ["appoint"], "eeeimns" => ["enemies"], "einosss" => ["session"],
      "cdeelux" => ["exclude"], "begilos" => ["obliges"], "dfginnu" => ["funding"],
      "accilru" => ["crucial"], "eglnost" => ["longest"], "cdeorrs" => ["records"],
      "acdenns" => ["scanned"], "agiintw" => ["waiting"], "ceekrrw" => ["wrecker"],
      "glorssy" => ["grossly"], "aghntuy" => ["naughty"], "fimnors" => ["informs"],
      "aeiprst" => ["parties"], "efhlssu" => ["flushes"], "adehmss" => ["smashed"],
      "eemrssu" => ["resumes"], "abdeffl" => ["baffled"], "ekooprv" => ["provoke"],
      "cemrruy" => ["mercury"], "eilqtuy" => ["quietly"], "afilnpu" => ["painful"],
      "bgiorty" => ["bigotry"], "aafnsty" => ["fantasy"], "ehmoosw" => ["somehow"],
      "abgiins" => ["biasing"], "ccdeesu" => ["succeed"], "adffhno" => ["offhand"],
      "acehstw" => ["watches"], "aeginrw" => ["wearing"], "beorssw" => ["browses"],
      "deeintv" => ["evident"], "deknnru" => ["drunken"], "ailorst" => ["tailors"],
      "dgimnoo" => ["dooming"], "acilpst" => ["plastic"], "ceeffst" => ["effects"],
      "cenrtuy" => ["century"], "deiostu" => ["outside", "tedious"],
      "cepsstu" => ["suspect"], "deeistx" => ["existed"], "addeptu" => ["updated"],
      "eginors" => ["regions", "ignores"], "iiprsst" => ["spirits"],
      "acelrsu" => ["secular"], "aginnrw" => ["warning"], "acehkrs" => ["hackers"],
      "ghinnot" => ["nothing"], "adeqrsu" => ["squared"], "cdehopp" => ["chopped"],
      "acllloy" => ["locally"], "abceens" => ["absence"], "degnoru" => ["undergo"],
      "beginoy" => ["obeying"], "eilmpsu" => ["impulse"], "achlloo" => ["alcohol"],
      "aeemnrs" => ["renames"], "gimmnsu" => ["summing"], "iprstuu" => ["pursuit"],
      "ceffisu" => ["suffice"], "agilnst" => ["lasting"], "deelovv" => ["evolved"],
      "deeppst" => ["stepped"], "ghinott" => ["tonight"], "abcehmr" => ["chamber"],
      "eilnotv" => ["violent"], "enoosst" => ["soonest"], "eefprrs" => ["prefers"],
      "dehmost" => ["methods"], "eeiqrtu" => ["quieter"], "aacegkp" => ["package"],
      "addeiov" => ["avoided"], "ceeipss" => ["species"], "ddenoru" => ["rounded"],
      "ddeoppr" => ["dropped"], "adginrt" => ["trading"], "deoppst" => ["stopped"],
      "abeglrs" => ["garbles"], "effosst" => ["offsets"], "afgilnw" => ["flawing"],
      "aeilpps" => ["applies"], "aefmrrs" => ["farmers"], "eghlnst" => ["lengths"],
      "eelsstt" => ["settles"], "adellow" => ["allowed"], "acchrst" => ["scratch"],
      "aemsssu" => ["assumes"], "eefhort" => ["thereof"], "begintt" => ["betting"],
      "deenost" => ["denotes"], "aacgilm" => ["magical"], "aehippr" => ["happier"],
      "deiistv" => ["visited"], "adeegnr" => ["derange"], "bdillny" => ["blindly"],
      "delpuzz" => ["puzzled"], "eelosvv" => ["evolves"], "aachnry" => ["anarchy"],
      "aelnpst" => ["planets"], "deemrsu" => ["resumed"], "adelmps" => ["sampled"],
      "acddist" => ["addicts"], "abinorw" => ["rainbow"], "deeelst" => ["deletes"],
      "deeiprv" => ["deprive"], "abdefor" => ["forbade"], "aegrstt" => ["targets"],
      "ceenrss" => ["screens"], "cdiiiot" => ["idiotic"], "eefrssu" => ["refuses"],
      "aehprss" => ["phrases"], "aenrssw" => ["answers"], "egorsss" => ["grosses"],
      "cdeestt" => ["detects"], "aeeoprt" => ["operate"], "aefilru" => ["failure"],
      "beggrsu" => ["buggers"], "aaffirs" => ["affairs"], "giinstt" => ["sitting"],
      "einsstw" => ["witness"], "diorstt" => ["distort"], "eirstuv" => ["virtues"],
      "aceffst" => ["affects"], "abdelst" => ["blasted"], "addeehr" => ["adhered"],
      "eehorvw" => ["however", "whoever"], "aeimnrs" => ["remains", "seminar"],
      "adgilno" => ["loading"], "aegimnn" => ["meaning"], "bgilooy" => ["biology"],
      "acdeirr" => ["carried"], "ceeglnt" => ["neglect"], "aeilost" => ["isolate"],
      "efiinsu" => ["unifies"], "eoprtvy" => ["poverty"], "ceeeirv" => ["receive"],
      "adeghin" => ["heading"], "eijnrsu" => ["injures"], "bdeeiss" => ["besides"],
      "acegoru" => ["courage"], "acefinn" => ["finance"], "hinoorz" => ["horizon"],
      "deffstu" => ["stuffed"], "aeeglls" => ["alleges"], "aginprw" => ["warping"],
      "eeilnnt" => ["lenient"], "einprrt" => ["printer"], "aceehiv" => ["achieve"],
      "elloosy" => ["loosely"], "agginnr" => ["ranging"], "abdeils" => ["disable"],
      "accilny" => ["cynical"], "aehrstt" => ["threats"], "adeghlu" => ["laughed"],
      "aceerrs" => ["careers"], "abghins" => ["bashing"], "ainsstu" => ["sustain"],
      "giknorw" => ["working"], "deipstt" => ["spitted"], "eghlnty" => ["lengthy"],
      "adepprw" => ["wrapped"], "amnqtuu" => ["quantum"], "abbirst" => ["rabbits"],
      "eefhlrs" => ["herself"], "aefsstt" => ["fastest"], "cenorrs" => ["corners"],
      "aloppru" => ["popular"], "celopsu" => ["couples"], "adepprt" => ["trapped"],
      "aerssst" => ["asserts"], "achmnor" => ["monarch"], "bbcelor" => ["cobbler"],
      "ceeistx" => ["excites"], "aeegilm" => ["mileage"], "eimoprv" => ["improve"],
      "ehorrst" => ["shorter"], "acemnor" => ["romance"], "bdegilo" => ["obliged"],
      "eginttw" => ["wetting"], "bioosuv" => ["obvious"], "ehorssw" => ["showers"],
      "cekopst" => ["pockets"], "aceklst" => ["tackles"], "cdeinsu" => ["induces"],
      "aorssst" => ["assorts"], "aiiilnt" => ["initial"], "aaegnrr" => ["arrange"],
      "adinstt" => ["distant"], "cnortuy" => ["country"], "beefint" => ["benefit"],
      "bgilnow" => ["blowing"], "eenrtuv" => ["venture"], "egrrsuy" => ["surgery"],
      "cdeeelt" => ["elected"], "acdekrt" => ["tracked"], "cdeeiln" => ["decline"],
      "abdeest" => ["debates"], "giiklln" => ["killing"], "deprsuu" => ["pursued"],
      "beelsss" => ["blesses"], "acehilt" => ["ethical"],
      "ceepstx" => ["excepts", "expects"], "ceeilns" => ["license", "silence"],
      "amnostu" => ["amounts"], "giinntu" => ["uniting"], "aadegms" => ["damages"],
      "aeelpss" => ["pleases"], "acinrtu" => ["curtain"], "aeqrssu" => ["squares"],
      "adghinn" => ["handing"], "aerrsst" => ["arrests"], "bceimno" => ["combine"],
      "aekmrrs" => ["markers", "remarks"], "defnorw" => ["frowned"],
      "aegilns" => ["sealing"], "cddeeru" => ["reduced"], "acfisst" => ["fascist"],
      "eehmort" => ["theorem"], "cdeersw" => ["screwed"], "deefinr" => ["refined"],
      "aaglnoy" => ["analogy"], "aghinrs" => ["sharing"], "dddefil" => ["fiddled"],
      "addeinv" => ["invaded"], "agilnss" => ["signals"], "deiikls" => ["dislike"],
      "aginsss" => ["assigns"], "abertty" => ["battery"], "eilnsst" => ["listens"],
      "aeopprv" => ["approve"], "ghilrty" => ["rightly"], "bdeelss" => ["blessed"],
      "deiopst" => ["deposit"], "acdeilm" => ["decimal", "claimed", "medical"],
      "cceelry" => ["recycle"], "cdeilnu" => ["include"], "cdoorst" => ["doctors"],
      "aeefllt" => ["leaflet"], "cegiiln" => ["ceiling"], "ceimnru" => ["numeric"],
      "aelmpss" => ["samples"], "cemoptu" => ["compute"], "efmoprr" => ["perform"],
      "acehirv" => ["archive"], "aailprt" => ["partial"], "aeghint" => ["heating"],
      "acgilns" => ["scaling"], "aefhlss" => ["flashes"], "eginnpu" => ["penguin"],
      "opprstu" => ["support"], "emmnost" => ["moments"], "ghiinns" => ["shining"],
      "ddeistu" => ["studied"], "eehlrst" => ["shelter"], "fghiins" => ["fishing"],
      "eeorrst" => ["restore"], "eiilmss" => ["missile"], "alnsuuu" => ["unusual"],
      "ccellot" => ["collect"], "acdelot" => ["located"], "acellry" => ["clearly"],
      "eegiknp" => ["keeping"], "dgimnpu" => ["dumping"], "deeiprx" => ["expired"],
      "acemopr" => ["compare"], "aghikns" => ["shaking"], "aemnpty" => ["payment"],
      "fhiorry" => ["horrify"], "egillnt" => ["telling"], "efginor" => ["foreign"],
      "deelopx" => ["explode"], "aginntw" => ["wanting"],
      "ceeiprs" => ["recipes", "precise"], "ddeginw" => ["wedding"],
      "emooprt" => ["promote"], "ehilstw" => ["whistle"], "aeeilrr" => ["earlier"],
      "acelsss" => ["classes"], "aginstw" => ["wasting"], "abdeehv" => ["behaved"],
      "egillns" => ["selling"], "efirrty" => ["terrify"], "ghinrsu" => ["rushing"],
      "eeiqrsu" => ["queries"], "celnosu" => ["counsel"], "aeloprv" => ["overlap"],
      "accelns" => ["cancels"], "deeirsv" => ["diverse", "revised", "derives"],
      "beeorsv" => ["verbose", "observe"], "deiosuv" => ["devious"],
      "bciistu" => ["biscuit"], "ghiltty" => ["tightly"], "eiisstx" => ["sixties"],
      "aaepprs" => ["appears"], "adeilry" => ["readily"],
      "eginstt" => ["setting", "testing"], "acdeetu" => ["educate"],
      "eenprst" => ["present"], "aaddept" => ["adapted"], "acdeeps" => ["escaped"],
      "abhilos" => ["abolish"], "adeelrs" => ["dealers", "leaders"],
      "agilnuv" => ["valuing"], "aeefrtu" => ["feature"], "adilnss" => ["islands"],
      "acdehtw" => ["watched"], "fijstuy" => ["justify"],
      "aderstv" => ["adverts", "starved"], "eehinrt" => ["therein", "neither"],
      "adegrrs" => ["regards"], "afillny" => ["finally"], "eehnstv" => ["seventh"],
      "aalsstu" => ["assault"], "aciprvy" => ["privacy"], "ademnnu" => ["mundane"],
      "aadeitw" => ["awaited"], "afgilln" => ["falling"], "ceffios" => ["offices"],
      "deghist" => ["sighted"], "eeinnst" => ["intense"], "eegrrst" => ["regrets"],
      "aeemrsu" => ["measure"], "cefipsy" => ["specify"], "ddeerss" => ["dressed"],
      "adfhlnu" => ["handful"], "adeeggn" => ["engaged"], "aeeglry" => ["eagerly"],
      "aefinrt" => ["fainter"], "acginps" => ["spacing"], "accehst" => ["catches"],
      "degiint" => ["editing"], "celmopx" => ["complex"], "aeeprst" => ["repeats"],
      "ehiinrt" => ["inherit"], "acdeelr" => ["cleared", "declare"],
      "adegnrs" => ["dangers", "gardens"], "deijnru" => ["injured"],
      "ceinpst" => ["inspect"], "aceghrs" => ["charges"], "dnnosuu" => ["unsound"],
      "aempttt" => ["attempt"], "cklnosu" => ["unlocks"], "aeiinrt" => ["inertia"],
      "aderrst" => ["starred"], "agimnnn" => ["manning"], "ghiprtu" => ["upright"],
      "aadelmr" => ["alarmed"], "cddeinu" => ["induced"], "ccdeehk" => ["checked"],
      "aersstv" => ["starves"], "eginnst" => ["nesting"], "allosww" => ["swallow"],
      "aaknors" => ["anoraks"], "adeelps" => ["pleased"], "aegginr" => ["gearing"],
      "eirsuvv" => ["survive"], "ahnppuy" => ["unhappy"], "aenrstv" => ["servant"],
      "abeilns" => ["lesbian"], "bceenos" => ["obscene"], "acehprt" => ["chapter"],
      "ceghinw" => ["chewing"], "aeehnsv" => ["heavens"], "aderrsw" => ["rewards"],
      "cdennot" => ["contend"], "ghinosw" => ["showing"], "aeggrst" => ["stagger"],
      "bcejost" => ["objects"], "beemmrs" => ["members"], "aellorv" => ["overall"],
      "deirrsv" => ["drivers"], "eimostv" => ["motives"], "nooprss" => ["sponsor"],
      "eeorrtw" => ["rewrote"], "aegillv" => ["village"], "dgnorsu" => ["grounds"],
      "bdfiors" => ["forbids"], "elnnstu" => ["tunnels"], "ahorstt" => ["throats"],
      "adeinrt" => ["trained"], "adderss" => ["address"], "afillpt" => ["pitfall"],
      "ceorstv" => ["vectors"], "befilry" => ["briefly"], "eeflnos" => ["oneself"],
      "egglooy" => ["geology"], "cehiknt" => ["kitchen"], "aacdlns" => ["scandal"],
      "cefnosu" => ["confuse"], "ceeorrv" => ["recover"], "aabbceg" => ["cabbage"],
      "aeirtvy" => ["variety"], "aenprtt" => ["pattern"], "beehrty" => ["thereby"],
      "abgilmn" => ["blaming"], "eeinrsv" => ["inverse"], "abdeilu" => ["audible"],
      "acefrsu" => ["surface"], "ghinntu" => ["hunting"],
      "adeerrs" => ["rereads", "readers"], "adgilnr" => ["darling"],
      "eimmpru" => ["premium"], "ddehnru" => ["hundred"], "eelopps" => ["peoples"],
      "defgiru" => ["figured"], "eirssuv" => ["viruses"], "dehopps" => ["shopped"],
      "achirtu" => ["haircut"], "aabeglr" => ["algebra"], "ceinosv" => ["novices"],
      "acdelrw" => ["crawled"], "giilnst" => ["listing"], "eillnss" => ["illness"],
      "emrsttu" => ["mutters"], "ccenopt" => ["concept"], "imnoort" => ["monitor"],
      "ceegllo" => ["college"], "adenost" => ["donates"],
      "ggiinns" => ["singing", "signing"], "cenottx" => ["context"],
      "bdemoor" => ["bedroom", "boredom"], "aelrstv" => ["travels"],
      "ekmnosy" => ["monkeys"], "ghinrtu" => ["hurting"], "gginorw" => ["growing"],
      "aceehrt" => ["teacher"], "cdoprtu" => ["product"], "cdenotu" => ["counted"],
      "eginrsv" => ["serving"], "aceehpr" => ["cheaper"], "inooprt" => ["portion"],
      "ciorsuu" => ["curious"], "deelnss" => ["endless"], "deirstv" => ["diverts"],
      "aaegmns" => ["manages"], "abiilty" => ["ability"], "beegill" => ["legible"],
      "accdekr" => ["cracked"], "acehlpy" => ["cheaply"], "abdhnsu" => ["husband"],
      "giknnow" => ["knowing"], "bdeorsw" => ["browsed"], "eegimnt" => ["meeting"],
      "adeimty" => ["daytime"], "acelssu" => ["clauses"], "beiilsv" => ["visible"],
      "ceenrsy" => ["scenery"], "aaemrtu" => ["amateur"], "ainnstt" => ["instant"],
      "eirrstw" => ["writers"], "acdeghn" => ["changed"], "eeilrst" => ["sterile"],
      "ginprss" => ["springs"], "eginrst" => ["resting"], "aeelnrt" => ["eternal"],
      "deeinsx" => ["indexes"], "cegnruy" => ["urgency"], "aghlsty" => ["ghastly"],
      "aegluvy" => ["vaguely"], "aeillrt" => ["literal"], "efllstu" => ["fullest"],
      "aacdenv" => ["advance"], "deenstx" => ["extends"], "abhiint" => ["inhabit"],
      "definrs" => ["friends"], "acelnrt" => ["central"], "deioprv" => ["provide"],
      "aadehms" => ["ashamed"], "deeersv" => ["deserve"],
      "deginns" => ["endings", "sending"], "acginor" => ["organic"],
      "cdisssu" => ["discuss"], "denoprs" => ["respond"], "deeenrt" => ["entered"],
      "egilnry" => ["relying"], "aillnst" => ["install"], "aanrrtw" => ["warrant"],
      "deginnp" => ["pending"], "bdegiot" => ["bigoted"], "cejoprt" => ["project"],
      "ccennor" => ["concern"], "eooppss" => ["opposes"], "acghipr" => ["graphic"],
      "adeortt" => ["rotated"], "deeinst" => ["destine"], "giiknns" => ["sinking"],
      "cehimst" => ["chemist"], "aiilrtv" => ["trivial"], "aehstux" => ["exhaust"],
      "deimott" => ["omitted"], "abeehrt" => ["breathe"], "deiilmt" => ["limited"],
      "elpsuzz" => ["puzzles"], "afhlmru" => ["harmful"], "abceint" => ["cabinet"],
      "ciklluy" => ["luckily"], "ghinosu" => ["housing"], "ceeirsv" => ["service"],
      "aagimnz" => ["amazing"], "adeelrx" => ["relaxed"], "cdehlot" => ["clothed"],
      "deirrst" => ["stirred"], "aelprsy" => ["players"], "aaabnns" => ["bananas"],
      "defilpp" => ["flipped"], "emsssty" => ["systems"], "accnotu" => ["account"],
      "beilrtu" => ["rebuilt"], "deeerst" => ["steered"], "deginor" => ["ignored"],
      "ddeeotv" => ["devoted"], "eeeqsuz" => ["squeeze"], "dennstu" => ["stunned"],
      "cdddeeu" => ["deduced"], "ceoprss" => ["corpses", "process"],
      "cdeiorv" => ["divorce"], "iinssst" => ["insists"], "abeisuv" => ["abusive"],
      "aefinrr" => ["refrain"], "aeeflrw" => ["welfare"], "abdegir" => ["brigade"],
      "acehpst" => ["patches"], "aginrst" => ["staring"], "aefhrst" => ["fathers"],
      "adenrsw" => ["wanders"], "afinors" => ["insofar"], "acellot" => ["collate"],
      "aiilnos" => ["liaison"], "cimmost" => ["commits"], "aginsty" => ["staying"],
      "cddeeis" => ["decides"], "aekmrst" => ["markets"], "aeghinr" => ["hearing"],
      "adeppsw" => ["swapped"], "bceemos" => ["becomes"], "eimrtux" => ["mixture"],
      "ddeeelt" => ["deleted"], "cdeiisu" => ["suicide"],
      "aceilmr" => ["miracle", "reclaim"], "eeimmns" => ["immense"],
      "cmmnoos" => ["commons"], "deeirrt" => ["retired"], "agimnno" => ["moaning"],
      "aeeisst" => ["easiest"], "eeilrsu" => ["leisure"], "accilss" => ["classic"],
      "abdeeln" => ["enabled"], "aalnrtu" => ["natural"], "eeegmrs" => ["emerges"],
      "demnotu" => ["mounted"], "agikmnr" => ["marking"], "ceilmop" => ["compile"],
      "acgiknp" => ["packing"], "acnoort" => ["cartoon"], "deipstu" => ["dispute"],
      "adeertt" => ["treated"], "eerrssv" => ["servers"], "celorsu" => ["closure"],
      "ccennot" => ["connect"], "abegint" => ["beating"],
      "eemprsu" => ["supreme", "presume"], "hioprsw" => ["worship"],
      "aeeimnx" => ["examine"], "acilntu" => ["lunatic"], "ceikqru" => ["quicker"],
      "bcdeilm" => ["climbed"], "aginpsu" => ["pausing"], "acdeitt" => ["dictate"],
      "ceinost" => ["notices", "section"], "efllosw" => ["fellows"],
      "abeehnt" => ["beneath"], "aaddegm" => ["damaged"], "aceinrt" => ["certain"],
      "acegins" => ["ceasing"], "bdirstu" => ["disturb"], "eimnstu" => ["minutes"],
      "bgiilno" => ["boiling"], "aadgimr" => ["diagram"], "aenopsw" => ["weapons"],
      "cginors" => ["scoring"], "mooppsu" => ["pompous"], "aceilmt" => ["climate"],
      "acelost" => ["locates"], "aggiinn" => ["gaining"], "ciilnos" => ["silicon"],
      "deeissv" => ["devises"], "adghins" => ["dashing"], "ddenorw" => ["drowned"],
      "eeinstx" => ["sixteen"], "aderstt" => ["started"], "accenst" => ["accents"],
      "aeipssv" => ["passive"], "bekloot" => ["booklet"], "cefinno" => ["confine"],
      "afmorst" => ["formats"], "aehprty" => ["therapy"], "adelrtt" => ["rattled"],
      "efghirt" => ["fighter"], "acemrss" => ["screams"], "adefltu" => ["default"],
      "aceghns" => ["changes"], "acddirs" => ["discard"], "acdehtt" => ["chatted"],
      "eehlssv" => ["shelves"], "acdrstu" => ["custard"], "clmnosu" => ["columns"],
      "acelrst" => ["scarlet"], "deflors" => ["folders"], "deopstt" => ["spotted"],
      "aelnrtu" => ["neutral"], "dddelmu" => ["muddled"], "cdeersu" => ["reduces"],
      "eemnoos" => ["someone"], "nnoopru" => ["pronoun"], "aailrrv" => ["arrival"],
      "clnostu" => ["consult"], "deersst" => ["deserts"], "ddenosu" => ["sounded"],
      "almorst" => ["mortals"], "aalmnsu" => ["manuals"], "aelmorv" => ["removal"],
      "ehinopx" => ["phoenix"], "aeikmst" => ["mistake"], "cdenoss" => ["seconds"],
      "elrsstu" => ["results"], "aceltxy" => ["exactly"], "adprsuw" => ["upwards"],
      "eeforrv" => ["forever"], "aeelmpx" => ["example"], "cehostu" => ["touches"],
      "eeprssx" => ["express"], "cenortu" => ["counter"], "aadhrsz" => ["hazards"],
      "aeeglnt" => ["elegant"], "aceelpr" => ["replace"], "aabceln" => ["balance"],
      "aeglrty" => ["greatly"], "cdeeisv" => ["devices"], "acdirst" => ["drastic"],
      "abeirrr" => ["barrier"], "dfgilno" => ["folding"], "ekorrsw" => ["workers"],
      "iorsttu" => ["tourist"], "agginru" => ["arguing"], "gikmnos" => ["smoking"],
      "cdeorss" => ["crossed"], "ceejrst" => ["rejects"], "efilrst" => ["filters"],
      "cehinps" => ["pinches"], "ghillty" => ["lightly"], "efgirsu" => ["figures"],
      "cddeesu" => ["deduces"], "aeflnru" => ["funeral"], "dersttu" => ["trusted"],
      "eiinprs" => ["inspire"], "aegortu" => ["outrage"], "deenrrs" => ["renders"],
      "eopprss" => ["oppress"], "lprssuu" => ["surplus"], "cdeinot" => ["noticed"],
      "aegimrt" => ["migrate"], "aadderw" => ["awarded"], "aoprrty" => ["portray"],
      "ahlprsy" => ["sharply"], "degioos" => ["goodies"], "eorrsst" => ["resorts"],
      "adgimnn" => ["damning"], "accmopt" => ["compact"], "acilmsu" => ["musical"],
      "adforrw" => ["forward"], "acdeilt" => ["dialect"], "bddgiin" => ["bidding"],
      "elnosss" => ["lessons"], "degilnu" => ["indulge"], "aabeggg" => ["baggage"],
      "adginrw" => ["drawing"], "ailrstu" => ["rituals"], "acellrs" => ["recalls"],
      "ginoprt" => ["porting"], "giiknrs" => ["risking"], "adefggl" => ["flagged"],
      "dgiinrv" => ["driving"], "eensttx" => ["extents"], "eoprsst" => ["posters"],
      "deeepst" => ["deepest"], "acerstt" => ["scatter"], "deeenrw" => ["renewed"],
      "aceprtu" => ["capture"], "aemrsst" => ["masters", "streams"],
      "ccenort" => ["concert"], "boorrsw" => ["borrows"], "chlooss" => ["schools"],
      "ainosux" => ["anxious"], "biillno" => ["billion"], "eeprsss" => ["presses"],
      "fgiilmn" => ["filming"], "addginp" => ["padding"], "ddeeorr" => ["ordered"],
      "emnorst" => ["monster"], "fimnoru" => ["uniform"], "ailrtuv" => ["virtual"],
      "aacfltu" => ["factual"], "aginnrt" => ["ranting"], "eeloprx" => ["explore"],
      "ceelnos" => ["enclose"], "eimnoot" => ["emotion"], "cefinst" => ["infects"],
      "adeegln" => ["gleaned"], "ddeefin" => ["defined"], "beglnos" => ["belongs"],
      "deoopps" => ["opposed"], "aersssu" => ["assures"], "deilors" => ["soldier"],
      "cenorss" => ["censors"], "cddeeno" => ["encoded"], "aamnoty" => ["anatomy"],
      "eoprstt" => ["protest"], "ahmnory" => ["harmony"], "deeimpt" => ["emptied"],
      "deeipst" => ["despite"], "abdlory" => ["broadly"], "aeglrst" => ["largest"],
      "abddeet" => ["debated"], "ceghino" => ["echoing"], "ceeflrt" => ["reflect"],
      "agimnrw" => ["warming"], "imnoost" => ["motions"], "eeenruv" => ["revenue"],
      "adelnnp" => ["planned"], "abeklnt" => ["blanket"], "acehrss" => ["crashes"],
      "acehlss" => ["clashes"], "cdehrsu" => ["crushed"], "abcgikn" => ["backing"],
      "gimnnor" => ["morning"], "ceikstt" => ["tickets"], "knnnouw" => ["unknown"],
      "deefnrs" => ["fenders"], "aacmrss" => ["sarcasm"], "cdekkno" => ["knocked"],
      "bcdeklo" => ["blocked"], "cenostt" => ["contest"], "cinosst" => ["consist"],
      "deimmsu" => ["mediums"], "iiorstv" => ["visitor"], "cciirtu" => ["circuit"],
      "eelsssu" => ["useless"], "aioprrt" => ["airport"], "deiintv" => ["invited"],
      "aceelnr" => ["cleaner"], "aceirrs" => ["carries"], "egnorsv" => ["governs"],
      "eimopss" => ["imposes"], "acdeehr" => ["reached"], "aeilnpx" => ["explain"],
      "bginnru" => ["burning"], "eflorsw" => ["flowers"], "eimoprs" => ["promise"],
      "abilmox" => ["mailbox"], "aejlosu" => ["jealous"], "gginnoo" => ["ongoing"],
      "bnosttu" => ["buttons"], "cnoortu" => ["contour"], "deeginn" => ["needing"],
      "eeprstx" => ["experts"], "eforsst" => ["forests"], "einnost" => ["tension"],
      "cginost" => ["costing"], "eiloptx" => ["exploit"], "acghins" => ["chasing"],
      "ginortu" => ["routing"], "ceirssu" => ["cruises"], "adempsw" => ["swamped"],
      "adgilnn" => ["landing"], "cmosstu" => ["customs"], "agiklnt" => ["talking"],
      "iimmmnu" => ["minimum"], "cfiilnt" => ["inflict"], "giinssu" => ["issuing"],
      "gggilno" => ["logging"], "ceeprst" => ["respect"], "ekmorss" => ["smokers"],
      "acdelss" => ["classed"], "cenortv" => ["convert"], "elrttuy" => ["utterly"],
      "aeorstt" => ["rotates"], "delostu" => ["loudest"], "cefnoss" => ["confess"],
      "aelprst" => ["plaster"], "ddefloo" => ["flooded"], "adeglpu" => ["plagued"],
      "cdeeesx" => ["exceeds"], "aeelrst" => ["relates"],
      "aghinps" => ["phasing", "shaping"], "deefmor" => ["freedom"],
      "cfmnoor" => ["conform"], "adeeflr" => ["federal"], "aehltwy" => ["wealthy"],
      "acginrs" => ["scaring"], "deimnrs" => ["reminds"], "cdddeeo" => ["decoded"],
      "bdeginn" => ["bending"], "enoprss" => ["persons"], "adeimrr" => ["married"],
      "beffrsu" => ["buffers"], "aablntt" => ["blatant"], "ginpttu" => ["putting"],
      "egiinvw" => ["viewing"], "acerrtt" => ["retract"], "gimnppu" => ["pumping"],
      "cefirty" => ["rectify"], "eeqrstu" => ["request"], "clnoort" => ["control"],
      "gillnpu" => ["pulling"], "eikrsst" => ["strikes"], "agiknpr" => ["parking"],
      "aeglotv" => ["voltage"], "agimnpp" => ["mapping"], "ghiinnt" => ["hinting"],
      "adeekns" => ["sneaked"], "belostt" => ["bottles"], "aadoprx" => ["paradox"],
      "addeggr" => ["dragged"], "deikpps" => ["skipped"], "ceeginr" => ["generic"],
      "aaegmnr" => ["manager"], "dinosww" => ["windows"], "deorsty" => ["destroy"],
      "cdeefst" => ["defects"], "bimsstu" => ["submits"],
      "eginrss" => ["resigns", "singers"], "ceknors" => ["reckons"],
      "addeegr" => ["degrade"], "ceenprt" => ["percent"], "aainrtv" => ["variant"],
      "aeeflms" => ["females"], "aenprrt" => ["partner"], "adeegll" => ["alleged"],
      "aeeggns" => ["engages"], "addeisv" => ["advised"], "ddeenps" => ["depends"],
      "eorrstu" => ["trouser"], "eenrssu" => ["ensures"],
      "aelrstt" => ["rattles", "startle"], "ailmnno" => ["nominal"],
      "eopssss" => ["possess"], "aeegrrt" => ["greater"], "bemnstu" => ["numbest"],
      "ginnrtu" => ["turning"], "deefgin" => ["feeding"], "deejnoy" => ["enjoyed"],
      "efgiorv" => ["forgive"], "eeilntt" => ["entitle"], "acfinrt" => ["frantic"],
      "giinors" => ["origins"], "ddgiinr" => ["ridding"], "airsstt" => ["artists"],
      "deeilrv" => ["deliver"], "ciiosuv" => ["vicious"], "filrsty" => ["firstly"],
      "aabcelp" => ["capable"], "aemnrsu" => ["surname"], "ddefnou" => ["founded"],
      "gilorty" => ["trilogy"], "cfmoort" => ["comfort"], "ikmoost" => ["mistook"],
      "adeinsv" => ["invades"], "giimnss" => ["missing"], "enorsuv" => ["nervous"],
      "agiinrs" => ["arising", "raising"], "aiilmmn" => ["minimal"],
      "aaccnvy" => ["vacancy"], "cfimnor" => ["confirm"], "aeqrrtu" => ["quarter"],
      "acennrs" => ["scanner"], "aalnsty" => ["analyst"], "ghiknoo" => ["hooking"],
      "abccoot" => ["tobacco"], "hlmnoty" => ["monthly"], "deiknov" => ["invoked"],
      "agimnsu" => ["amusing"], "acehlnn" => ["channel"], "mopprst" => ["prompts"],
      "cehirst" => ["richest"], "fgiintt" => ["fitting"], "eegrstu" => ["gesture"],
      "cennost" => ["consent"], "eegmnst" => ["segment"], "eiillrs" => ["sillier"],
      "cdeirsu" => ["cruised"], "eeeilrv" => ["relieve"], "ciimstv" => ["victims"],
      "giinrtw" => ["writing"], "aellmrs" => ["smaller"], "deeffor" => ["offered"],
      "acfltuy" => ["faculty"], "celrtuy" => ["cruelty"], "giilmns" => ["smiling"],
      "deeipss" => ["despise"], "dehlors" => ["holders"], "egimnrt" => ["terming"],
      "efhrrtu" => ["further"], "aeegmss" => ["message"], "ginopru" => ["pouring"],
      "aehhlty" => ["healthy"], "eeelmnt" => ["element"], "aeglrru" => ["regular"],
      "acdehpt" => ["patched"], "bcceily" => ["bicycle"], "aeehrsw" => ["whereas"],
      "bdgiinn" => ["binding"], "dgiinty" => ["dignity", "tidying"],
      "hrssttu" => ["thrusts"], "eeffint" => ["fifteen"], "eginquu" => ["queuing"],
      "acerttx" => ["extract"], "abeillr" => ["liberal"], "aabeggr" => ["garbage"],
      "aginssv" => ["savings"], "aceehnn" => ["enhance"], "deeelns" => ["needles"],
      "acellny" => ["cleanly"], "acehmst" => ["matches"], "deinsty" => ["density"],
      "aeefrwy" => ["freeway"], "aacflly" => ["fallacy"], "adllors" => ["dollars"],
      "aghilnt" => ["halting"], "aailpst" => ["spatial"], "celosst" => ["closest"],
      "agiilmn" => ["mailing"], "cceikrt" => ["cricket"], "abbdegr" => ["grabbed"],
      "cgilnos" => ["closing"], "ccdehku" => ["chucked"], "abginrr" => ["barring"],
      "eggimnr" => ["merging"], "innoost" => ["notions"], "elorstv" => ["revolts"],
      "adeinpt" => ["painted"], "aeelrsv" => ["reveals", "several"],
      "acdeert" => ["catered", "reacted", "created"], "agilnpy" => ["playing"],
      "adeiprs" => ["despair"], "aaegtwy" => ["gateway"], "aaeilss" => ["aliases"],
      "acdeeht" => ["cheated"], "afostuu" => ["fatuous"], "eeinnps" => ["pennies"],
      "einrsst" => ["inserts"], "flloosw" => ["follows"], "eeirssv" => ["revises"],
      "abeelns" => ["enables"], "cdehinp" => ["pinched"], "acdginn" => ["dancing"],
      "cemoops" => ["compose"], "afklnry" => ["frankly"], "aiimprs" => ["impairs"],
      "ghloruy" => ["roughly"], "effrssu" => ["suffers"], "deeoprw" => ["powered"],
      "adehnrs" => ["hardens"], "aabdnno" => ["abandon"], "ghiinst" => ["insight"],
      "efnortu" => ["fortune"], "coprrtu" => ["corrupt"], "eiimnrt" => ["interim"],
      "bellstu" => ["bullets"], "aeelssw" => ["weasels"], "dgikmno" => ["kingdom"],
      "dgiilns" => ["sliding"], "eeiprvw" => ["preview"], "aceelrr" => ["clearer"],
      "deinprt" => ["printed"], "adeilpp" => ["applied"], "bhiiint" => ["inhibit"],
      "acilpty" => ["typical"], "demrrsu" => ["murders"], "eggsstu" => ["suggest"],
      "imoprst" => ["imports"], "dehipps" => ["shipped"], "bdelosu" => ["doubles"],
      "aghinsw" => ["washing"], "ddeeisv" => ["devised"], "begglos" => ["boggles"],
      "cdelopu" => ["coupled"], "aceepss" => ["escapes"], "deeopsx" => ["exposed"],
      "aceirrr" => ["carrier"], "aceilrt" => ["article"], "agiklnw" => ["walking"],
      "ceirrtu" => ["recruit"], "cdeeepr" => ["precede"],
      "aeinrst" => ["nastier", "retains"], "iillmno" => ["million"],
      "aegikln" => ["linkage"], "bdinstu" => ["dustbin"], "bdegooy" => ["goodbye"],
      "egilnss" => ["singles"], "aaelpps" => ["appeals"],
      "cdeirst" => ["credits", "directs"], "cehooss" => ["chooses"],
      "aeeegnt" => ["teenage"], "adeilms" => ["mislead"], "aadelry" => ["already"],
      "eeerrsv" => ["reserve", "reverse"], "eenrstw" => ["western"],
      "ehnorst" => ["shorten"], "ceeinrs" => ["sincere"], "dgiinnw" => ["winding"],
      "cemnosu" => ["consume"], "acinost" => ["actions"], "aegilnn" => ["leaning"],
      "cfiinot" => ["fiction"], "giijnno" => ["joining"], "aeehirv" => ["heavier"],
      "acmnory" => ["acronym"], "adempst" => ["stamped"], "aadegmn" => ["managed"],
      "adehrst" => ["hardest"], "aceflru" => ["careful"], "deginnr" => ["rending"],
      "cgimmnu" => ["cumming"], "eimprss" => ["impress"], "cllorss" => ["scrolls"],
      "aeprrsy" => ["prayers"], "adegrty" => ["tragedy"], "fhiloos" => ["foolish"],
      "dehiosu" => ["hideous"], "fgiilnt" => ["lifting"], "aegllry" => ["largely"],
      "adeilst" => ["details"], "cginopy" => ["copying"], "aefhrrt" => ["farther"],
      "aceehst" => ["teaches"], "aabginr" => ["bargain"], "behorst" => ["bothers"],
      "dgggiin" => ["digging"], "bdeelov" => ["beloved"], "ailmopt" => ["optimal"],
      "einorsv" => ["version"], "adeglmn" => ["mangled"], "ghinpsu" => ["pushing"],
      "aeglsss" => ["glasses"], "aimprry" => ["primary"], "aeepprr" => ["prepare"],
      "eghinrr" => ["herring"], "accepst" => ["accepts"], "eooprst" => ["poorest"],
      "adelnpt" => ["planted"], "aenprst" => ["parents"], "aelrswy" => ["lawyers"],
      "celmops" => ["compels"], "denpssu" => ["suspend"], "ccdeeno" => ["concede"],
      "abilrry" => ["library"], "opsttuu" => ["outputs"], "aeehlrt" => ["leather"],
      "aeelmtu" => ["emulate"], "dddeiiv" => ["divided"], "eefgiln" => ["feeling"],
      "deisstu" => ["studies"], "cehnpsu" => ["punches"],
      "deeprss" => ["depress", "pressed"], "aacdilr" => ["radical"],
      "addenss" => ["saddens"], "abeginr" => ["bearing"], "deiopss" => ["dispose"],
      "aeginrs" => ["erasing"], "deeoruv" => ["overdue"], "deginss" => ["designs"],
      "deinopt" => ["pointed"], "aacchir" => ["archaic"], "ademssu" => ["assumed"],
      "denorsw" => ["wonders"], "addeinr" => ["drained"], "aaenpst" => ["peasant"],
      "acmnopy" => ["company"], "allmory" => ["morally"], "cdeekrw" => ["wrecked"],
      "aegilll" => ["illegal"], "abeimnt" => ["ambient"], "elnotvy" => ["novelty"],
      "afhinos" => ["fashion"], "aehimst" => ["atheism"], "acdmmno" => ["command"],
      "deimnps" => ["impends"], "ainrstt" => ["transit"], "eeilprs" => ["replies"],
      "beehrwy" => ["whereby"], "beeeilv" => ["believe"], "aeinqtu" => ["antique"],
      "aepprrw" => ["wrapper"], "eeijlls" => ["jellies"], "deeostv" => ["devotes"],
      "deiorrw" => ["worried"], "inoopss" => ["poisons"], "adorstw" => ["towards"],
      "fgimnor" => ["forming"], "aeglpsu" => ["plagues"], "densttu" => ["student"],
      "cddeorw" => ["crowded"], "deilpps" => ["slipped"], "acghikn" => ["hacking"],
      "einortu" => ["routine"], "einorst" => ["orients"], "cilprtu" => ["culprit"],
      "aceerst" => ["creates"], "efinnru" => ["funnier"], "cdemnno" => ["condemn"],
      "eenprtv" => ["prevent"], "eiprsst" => ["persist", "priests"],
      "cgikmnu" => ["mucking"], "aghinsu" => ["anguish"], "ammrsuy" => ["summary"],
      "eemorsv" => ["removes"], "einnstv" => ["invents"], "aaeegrv" => ["average"],
      "abgiknr" => ["barking"], "eiorssu" => ["serious"], "aefirst" => ["fairest"],
      "eeinrst" => ["entries"], "eoprrst" => ["porters", "reports"],
      "aacemrs" => ["cameras"], "acdertt" => ["detract"], "ailmmor" => ["immoral"],
      "acgilnp" => ["placing"], "eeirsvw" => ["reviews"], "aelnstt" => ["talents"],
      "aeginrt" => ["tearing"], "deelopv" => ["develop"], "agijmmn" => ["jamming"],
      "ellorty" => ["trolley"], "aacrttt" => ["attract"], "eprssuu" => ["pursues"],
      "achlors" => ["scholar"], "blmossy" => ["symbols"], "acgilln" => ["calling"],
      "adenpsx" => ["expands"], "aeenrst" => ["eastern", "nearest"],
      "aimmmux" => ["maximum"], "eehistv" => ["thieves"], "einrttw" => ["written"],
      "deenrsu" => ["ensured"], "achirty" => ["charity"], "deginny" => ["denying"],
      "glnorwy" => ["wrongly"], "egiintx" => ["exiting"], "aehmsss" => ["smashes"],
      "eilnotu" => ["outline"], "cciprty" => ["cryptic"], "acepsst" => ["aspects"],
      "cceilrs" => ["circles"], "adeemnr" => ["renamed"], "ddeeirv" => ["derived"],
      "ceersst" => ["secrets"], "fgilnow" => ["flowing"], "ghhortu" => ["through"],
      "dekorwy" => ["keyword"], "eeimpst" => ["empties"], "aceehrs" => ["reaches"],
      "aeimrtw" => ["wartime"], "aceilps" => ["special"], "einrstv" => ["inverts"],
      "adeehrs" => ["adheres", "headers"], "deffirs" => ["differs"],
      "aisssst" => ["assists"], "eiilstt" => ["elitist"], "dggiinu" => ["guiding"],
      "ccinotv" => ["convict"], "cellosy" => ["closely"], "eeginns" => ["engines"],
      "acdeghr" => ["charged"], "kloootu" => ["outlook"], "aacilpt" => ["capital"],
      "celmssu" => ["muscles"], "ceffior" => ["officer"], "bcejstu" => ["subject"],
      "efhllpu" => ["helpful"], "cdddeei" => ["decided"], "diimsss" => ["dismiss"],
      "deeilpr" => ["replied"], "acdehmr" => ["charmed"], "addehln" => ["handled"],
      "aellquy" => ["equally"], "cdeopru" => ["produce"], "aehnpps" => ["happens"],
      "aehistt" => ["atheist"], "celrtuu" => ["culture"], "accessu" => ["accuses"],
      "efforst" => ["efforts"], "eggirrt" => ["trigger"], "cklnuuy" => ["unlucky"],
      "cdeirtv" => ["verdict"], "acdenss" => ["ascends"], "acchiot" => ["chaotic"],
      "ceehmss" => ["schemes"], "degimnn" => ["mending"], "aeimrrs" => ["marries"],
      "bhilpsu" => ["publish"], "ceorssu" => ["courses", "sources"],
      "eehnorw" => ["nowhere"], "eelorsv" => ["resolve"], "adeilly" => ["ideally"],
      "cgiinno" => ["coining"], "abilort" => ["orbital"], "aegiimn" => ["imagine"],
      "bdeilru" => ["rebuild"], "aalmnoy" => ["anomaly"], "ciklquy" => ["quickly"],
      "abeirrz" => ["bizarre"], "abcgklo" => ["backlog"], "aenpstu" => ["peanuts"],
      "ahorstu" => ["authors"], "efhlopu" => ["hopeful"], "cdehnpu" => ["punched"],
      "adddeer" => ["dreaded"], "deinnst" => ["intends"], "eepstty" => ["typeset"],
      "ceemopt" => ["compete"], "aginpry" => ["praying"], "agghinn" => ["hanging"],
      "ceorsss" => ["crosses"], "ceeiprt" => ["receipt"], "aeimssv" => ["massive"],
      "dghilno" => ["holding"], "aeflrsu" => ["refusal"], "abinost" => ["obtains"],
      "agiinnr" => ["raining"], "deinstt" => ["dentist"], "bbhirsu" => ["rubbish"],
      "ghiinsw" => ["wishing"], "adeilmm" => ["dilemma"], "cekosst" => ["sockets"],
      "adeissv" => ["advises"], "fioprst" => ["profits"], "deemptt" => ["tempted"],
      "efmorrs" => ["reforms"], "eiilmps" => ["implies"], "aaegpss" => ["passage"],
      "dehostu" => ["shouted"], "ciortvy" => ["victory"], "cehrstt" => ["stretch"],
      "acdeklt" => ["tackled"], "acginrt" => ["tracing"], "aeekprs" => ["speaker"],
      "cgiiknp" => ["picking"], "elosstw" => ["slowest"], "defhlsu" => ["flushed"],
      "aailmns" => ["animals"], "bbgimno" => ["bombing"], "acehimn" => ["machine"],
      "iilttuy" => ["utility"], "ceelsst" => ["selects"], "ddefils" => ["fiddles"],
      "deeegrs" => ["degrees"], "ehopprt" => ["prophet"], "acgikln" => ["lacking"],
      "ginoqtu" => ["quoting"], "belmstu" => ["stumble"], "ejnoruy" => ["journey"],
      "cceehkr" => ["checker"], "deiklls" => ["skilled"], "giinppr" => ["ripping"],
      "aceinnt" => ["ancient"], "eghilrt" => ["lighter"], "bdiosuu" => ["dubious"],
      "adeirrv" => ["arrived"], "aacinpt" => ["captain"], "bghortu" => ["brought"],
      "eersstt" => ["streets"], "aillnpy" => ["plainly"], "ginnnru" => ["running"],
      "eilmprs" => ["simpler"], "immoptu" => ["optimum"], "iinnoop" => ["opinion"],
      "acginsu" => ["causing"], "abcgiln" => ["cabling"], "mnnosyy" => ["synonym"],
      "cddeeos" => ["decodes"], "ceoprtt" => ["protect"], "abdeort" => ["aborted"],
      "aghhiwy" => ["highway"], "deginnv" => ["vending"], "celrstu" => ["cluster"],
      "aginpss" => ["passing"], "eeirrst" => ["retires"], "himprtu" => ["triumph"],
      "ghiintt" => ["hitting"], "aackstt" => ["attacks"], "deiorst" => ["editors"],
      "cciirst" => ["critics"], "aceorrt" => ["creator", "reactor"],
      "cceorrt" => ["correct"], "accnott" => ["contact"], "eiinstv" => ["invites"],
      "acilrty" => ["clarity"], "aenorss" => ["reasons"], "deenprt" => ["pretend"],
      "acilopt" => ["optical", "topical"], "eegimns" => ["seeming"],
      "cemmnot" => ["comment"], "ceehilv" => ["vehicle"], "aagmmrr" => ["grammar"],
      "eeegnrv" => ["revenge"]}
  end
end
