defmodule Jumble.ScowlDict.Size60.Length3 do
  def get(string_id) do
    %{"abo" => ["boa"], "hot" => ["tho", "hot"], "oow" => ["woo"], "ctu" => ["cut"],
      "afr" => ["far"], "dgu" => ["dug"], "abd" => ["dab", "bad"],
      "hip" => ["phi", "hip"], "inu" => ["uni"], "bgi" => ["big"], "osy" => ["soy"],
      "imx" => ["mix"], "abf" => ["fab"], "ikl" => ["ilk"], "nru" => ["urn", "run"],
      "gmy" => ["gym"], "bde" => ["deb", "bed"], "lot" => ["lot"], "agj" => ["jag"],
      "muy" => ["yum"], "ehu" => ["hue"], "ehi" => ["hie"], "hnt" => ["nth"],
      "ajy" => ["jay"], "aey" => ["yea", "aye"], "eil" => ["lei", "lie"],
      "deu" => ["due"], "bil" => ["lib"], "ooz" => ["zoo"], "hop" => ["hop"],
      "nno" => ["non"], "ggi" => ["gig"], "acy" => ["cay"], "npw" => ["pwn"],
      "ahp" => ["hap", "pah"], "ivy" => ["ivy"], "aes" => ["sea"], "mmo" => ["mom"],
      "fnu" => ["fun"], "ewy" => ["yew"], "afn" => ["fan"], "ott" => ["tot"],
      "cgo" => ["cog"], "abl" => ["alb", "lab"], "aft" => ["aft", "fat"],
      "dop" => ["pod"], "bdo" => ["bod", "dob"], "cox" => ["cox"], "chi" => ["chi"],
      "flu" => ["flu"], "ops" => ["ops", "sop"], "epy" => ["yep"], "tux" => ["tux"],
      "eit" => ["tie"], "ehr" => ["her"], "now" => ["now", "own", "won"],
      "app" => ["pap"], "acm" => ["mac", "cam"], "ovw" => ["vow"], "bfi" => ["fib"],
      "amy" => ["yam", "may"], "atx" => ["tax"], "ept" => ["pet"], "psy" => ["spy"],
      "amt" => ["tam", "mat"], "aps" => ["asp", "pas", "sap", "spa"],
      "itt" => ["tit"], "aly" => ["lay"], "bow" => ["bow"], "ddo" => ["odd"],
      "akr" => ["ark"], "alx" => ["lax"], "ell" => ["ell"], "diy" => ["yid"],
      "eny" => ["yen"], "dim" => ["mid", "dim"], "beg" => ["beg"], "cno" => ["con"],
      "ajw" => ["jaw"], "opp" => ["pop"], "eeg" => ["gee"], "aot" => ["oat"],
      "est" => ["set"], "aet" => ["eta", "ate", "eat", "tea"], "imo" => ["moi"],
      "mru" => ["rum"], "orw" => ["row"], "dos" => ["dos", "sod"], "inn" => ["inn"],
      "etw" => ["wet"], "aqu" => ["qua"], "ill" => ["ill"], "dei" => ["die"],
      "oty" => ["toy"], "bio" => ["obi"], "fop" => ["fop"], "hmm" => ["hmm"],
      "hor" => ["rho"], "den" => ["den", "end"], "cit" => ["tic"], "aim" => ["aim"],
      "itz" => ["zit"], "iko" => ["oik"], "ilo" => ["oil"], "fgo" => ["fog"],
      "emn" => ["men"], "bbu" => ["bub"], "nsu" => ["nus", "sun"], "ilp" => ["lip"],
      "hss" => ["ssh"], "rty" => ["try"], "coo" => ["coo"], "oru" => ["our"],
      "fot" => ["oft"], "ipt" => ["pit", "tip"], "los" => ["sol"], "emu" => ["emu"],
      "egv" => ["veg"], "enp" => ["pen"], "alw" => ["awl", "law"], "bir" => ["rib"],
      "cei" => ["ice"], "ent" => ["net", "ten"], "mmu" => ["mum"], "eey" => ["eye"],
      "add" => ["dad", "add"], "pry" => ["pry"], "ady" => ["day"], "acp" => ["cap"],
      "ems" => ["ems", "mes"], "def" => ["fed"], "blo" => ["lob"], "ary" => ["ray"],
      "mow" => ["mow"], "bet" => ["bet"], "ads" => ["ads", "sad"], "ego" => ["ego"],
      "eht" => ["the"], "abp" => ["bap"], "esu" => ["sue", "use"], "eop" => ["ope"],
      "bfo" => ["fob"], "ahy" => ["hay"], "ast" => ["sat"], "abc" => ["cab"],
      "eru" => ["rue"], "guy" => ["guy"], "efo" => ["foe"], "anr" => ["ran"],
      "ipr" => ["rip"], "adw" => ["wad"], "iwz" => ["wiz"], "agr" => ["gar", "rag"],
      "cho" => ["och"], "dir" => ["rid"], "dpu" => ["pud"], "atu" => ["tau"],
      "efi" => ["fie"], "aor" => ["oar"], "egm" => ["meg", "gem"], "anv" => ["van"],
      "dis" => ["ids", "dis"], "del" => ["led"], "guv" => ["guv"], "ens" => ["ens"],
      "htu" => ["hut"], "acl" => ["lac"], "ehp" => ["hep"], "gju" => ["jug"],
      "aer" => ["ear", "era", "are"], "bjo" => ["job"], "ilt" => ["til", "lit"],
      "ffo" => ["off"], "aep" => ["ape", "pea"], "dry" => ["dry"], "ino" => ["ion"],
      "oww" => ["wow"], "efr" => ["fer", "ref"], "bmo" => ["mob"], "det" => ["ted"],
      "egg" => ["egg"], "bbi" => ["bib"], "boy" => ["yob", "boy"],
      "act" => ["act", "cat"], "dot" => ["dot"], "ahj" => ["haj"],
      "deo" => ["ode", "doe"], "bhu" => ["hub"], "glu" => ["lug"], "eno" => ["one"],
      "eip" => ["pie"], "lsy" => ["sly"], "eev" => ["eve"], "amp" => ["amp", "map"],
      "eow" => ["woe", "owe"], "bey" => ["bey", "bye"], "moo" => ["moo"],
      "adt" => ["tad"], "bdu" => ["bud", "dub"], "dnu" => ["dun"], "cop" => ["cop"],
      "ail" => ["ail"], "ekn" => ["ken"], "psu" => ["pus", "sup", "ups"],
      "dor" => ["rod"], "msy" => ["mys"], "ant" => ["ant", "tan"], "ajr" => ["jar"],
      "ikt" => ["kit"], "gjo" => ["jog"], "adl" => ["lad"], "dmo" => ["mod"],
      "bis" => ["bis"], "hos" => ["hos", "ohs"], "bor" => ["orb", "rob"],
      "bgo" => ["gob", "bog"], "epp" => ["pep"], "ehm" => ["meh", "hem"],
      "bcu" => ["cub"], "mpu" => ["ump"], "iss" => ["sis"], "enw" => ["wen", "new"],
      "aht" => ["hat"], "ist" => ["its", "sit"], "dno" => ["nod", "don"],
      "eho" => ["hoe"], "ams" => ["mas"], "hsy" => ["shy"], "anp" => ["nap", "pan"],
      "ahs" => ["ash", "has"], "osw" => ["sow"], "bru" => ["bur", "rub"],
      "ehs" => ["hes", "she"], "acr" => ["arc", "car"], "adh" => ["had"],
      "etv" => ["vet"], "cis" => ["sic"], "amm" => ["mam"], "dip" => ["dip"],
      "ako" => ["oak"], "ado" => ["ado"], "esy" => ["yes"], "ehx" => ["hex"],
      "imr" => ["rim"], "kuy" => ["yuk"], "emw" => ["mew"], "imv" => ["vim"],
      "aku" => ["auk"], "cip" => ["pic"], "adf" => ["fad"], "aby" => ["bay"],
      "abg" => ["gab", "bag"], "agw" => ["wag"], "bit" => ["bit"],
      "hoo" => ["ooh", "oho"], "noy" => ["yon"], "bnu" => ["nub", "bun"],
      "hhu" => ["huh"], "cdu" => ["cud"], "apy" => ["yap", "pay"],
      "abr" => ["bra", "bar"], "bbe" => ["ebb"], "ikn" => ["kin", "ink"],
      "git" => ["git"], "dlo" => ["old"], "all" => ["all"], "eet" => ["tee"],
      "coy" => ["coy"], "giw" => ["wig"], "mot" => ["mot", "tom"], "biz" => ["biz"],
      "eef" => ["fee"], "gru" => ["rug"], "efz" => ["fez"], "eky" => ["key"],
      "fix" => ["fix"], "gin" => ["gin"], "buy" => ["buy"], "ipz" => ["zip"],
      "bos" => ["sob"], "iks" => ["ski"], "hmu" => ["hum"], "got" => ["tog", "got"],
      "aeg" => ["age"], "imp" => ["imp"], "eor" => ["ore", "roe"], "ees" => ["see"],
      "ikp" => ["kip"], "adi" => ["aid"], "his" => ["his"], "eir" => ["ire"],
      "dez" => ["zed"], "dmu" => ["mud"], "ipy" => ["yip"], "bho" => ["hob"],
      "bbo" => ["bob"], "fir" => ["fir"], "iln" => ["nil"], "ost" => ["sot"],
      "agg" => ["gag"], "iny" => ["yin"], "puy" => ["yup"], "ael" => ["lea", "ale"],
      "emo" => ["emo"], "pxy" => ["pyx"], "fly" => ["fly"], "goo" => ["goo"],
      "int" => ["nit", "tin"], "air" => ["air"], "elm" => ["elm"], "cru" => ["cur"],
      "lop" => ["pol", "lop"], "kow" => ["wok"], "afo" => ["oaf"], "oop" => ["poo"],
      "not" => ["ton", "not"], "sty" => ["sty"], "any" => ["nay", "any"],
      "gij" => ["jig"], "ely" => ["lye"], "brr" => ["brr"], "abj" => ["jab"],
      "ehn" => ["hen"], "abh" => ["bah"], "cim" => ["mic"], "opr" => ["pro"],
      "fry" => ["fry"], "ekl" => ["elk"], "aks" => ["ska", "ask"],
      "apt" => ["apt", "pat", "tap"], "cor" => ["orc"],
      "alp" => ["alp", "lap", "pal"], "dhi" => ["hid"], "npu" => ["pun"],
      "art" => ["tar", "rat", "art"], "asy" => ["say"], "ceu" => ["ecu", "cue"],
      "ghu" => ["hug", "ugh"], "bew" => ["web"], "ips" => ["pis", "sip"],
      "cot" => ["cot"], "eot" => ["toe"], "loo" => ["loo"], "egk" => ["keg"],
      "agl" => ["gal", "lag"], "aab" => ["baa"], "efy" => ["fey"], "hty" => ["thy"],
      "ptu" => ["put"], "rwy" => ["wry"], "emt" => ["met"], "agh" => ["hag"],
      "ipx" => ["pix"], "asx" => ["sax"], "adn" => ["and"], "joy" => ["joy"],
      "low" => ["owl", "low"], "isx" => ["xis", "six"], "elt" => ["let"],
      "abt" => ["bat", "tab"], "fin" => ["fin"], "aew" => ["awe"], "ipp" => ["pip"],
      "hwy" => ["why"], "ddi" => ["did"], "ahr" => ["rah"],
      "opt" => ["opt", "pot", "top"], "itw" => ["wit"], "hit" => ["hit"],
      "bdi" => ["bid"], "agn" => ["nag"], "ins" => ["ins", "sin"], "efw" => ["few"],
      "irs" => ["sir"], "bpu" => ["pub"], "agy" => ["gay"], "jot" => ["jot"],
      "afg" => ["fag"], "att" => ["tat"], "rtu" => ["rut"], "otu" => ["out"],
      "awx" => ["wax"], "egl" => ["gel", "leg"], "fis" => ["ifs"], "acw" => ["caw"],
      "asw" => ["saw", "was"], "acd" => ["cad"], "fgu" => ["fug"],
      "aah" => ["aah", "aha"], "inx" => ["nix"], "dew" => ["dew", "wed"],
      "eer" => ["ere"], "nnu" => ["nun"], "mos" => ["oms"], "egr" => ["erg"],
      "dil" => ["lid"], "gho" => ["hog"], "afy" => ["fay"], "ouy" => ["you"],
      "din" => ["din"], "lpy" => ["ply"], "how" => ["how", "who"],
      "ery" => ["yer", "rye"], "ags" => ["sag", "gas"], "hmo" => ["ohm"],
      "ikr" => ["irk"], "egt" => ["get"], "amr" => ["mar", "ram", "arm"],
      "inp" => ["nip", "pin"], "dgo" => ["god", "dog"], "nos" => ["son"],
      "adp" => ["pad"], "ilm" => ["mil"], "der" => ["red"], "ehw" => ["hew"],
      "amw" => ["maw"], "bee" => ["bee"], "oot" => ["too"], "fit" => ["fit"],
      "apw" => ["paw"], "gir" => ["rig"], "gip" => ["pig"], "acv" => ["vac"],
      "ntu" => ["tun", "nut"], "abn" => ["nab", "ban"], "ort" => ["tor", "rot"],
      "ddu" => ["dud"], "cdo" => ["doc", "cod"], "ahn" => ["nah"], "amn" => ["man"],
      "cry" => ["cry"], "gmu" => ["gum", "mug"], "hhs" => ["shh"], "erv" => ["rev"],
      "eew" => ["ewe", "wee"], "cow" => ["cow"], "ciy" => ["icy"], "ttu" => ["tut"],
      "bij" => ["jib"], "arw" => ["raw", "war"], "mop" => ["pom", "mop"],
      "alm" => ["lam"], "esx" => ["sex"], "eep" => ["pee"], "egp" => ["peg"],
      "box" => ["box"], "aov" => ["ova"], "agp" => ["gap"], "mtu" => ["tum"],
      "cpu" => ["cup"], "osu" => ["sou"], "dho" => ["hod"], "opx" => ["pox"],
      "bmu" => ["bum"], "ago" => ["ago"], "adm" => ["dam", "mad"], "acn" => ["can"],
      "msu" => ["sum"], "dey" => ["dye"], "dgi" => ["dig"], "esw" => ["sew"],
      "epr" => ["rep", "per"], "lox" => ["lox"], "gow" => ["wog"],
      "awy" => ["yaw", "way"], "btu" => ["tub", "but"], "bno" => ["nob"],
      "dhu" => ["duh"], "aky" => ["yak"], "gpy" => ["gyp"], "acs" => ["sac"],
      "ety" => ["yet"], "gtu" => ["tug", "gut"], "eel" => ["eel", "lee"],
      "eiv" => ["vie"], "evx" => ["vex"], "ajm" => ["jam"], "aen" => ["nae"],
      "ksy" => ["sky"], "bop" => ["bop"], "ahm" => ["ham"], "iop" => ["poi"],
      "glo" => ["log"], "ejt" => ["jet"], "dik" => ["kid"], "gnu" => ["gnu", "gun"],
      "ppu" => ["pup"], "bgu" => ["bug"], "atv" => ["vat"], "ahw" => ["haw"],
      "nor" => ["nor"], "dou" => ["duo"], "apr" => ["rap", "par"], "fox" => ["fox"],
      "otw" => ["tow", "wot", "two"], "inw" => ["win"], "fgi" => ["fig"],
      "for" => ["fro", "for"], "jtu" => ["jut"], "eek" => ["eek", "eke"],
      "ass" => ["ass"], "bco" => ["cob"], "owy" => ["yow"], "ehy" => ["hey"],
      "fru" => ["fur"], "bin" => ["nib", "bin"], "opw" => ["pow", "wop"],
      "bsu" => ["sub", "bus"], "him" => ["him"], "apz" => ["zap"], "aiv" => ["via"],
      "efl" => ["elf"], "efn" => ["fen"], "err" => ["err"], "ims" => ["ism", "sim"],
      "ace" => ["ace"], "boo" => ["boo"], "gpu" => ["pug"], "adg" => ["gad"],
      "anw" => ["awn", "wan"], "afx" => ["fax"], "agt" => ["tag"], "epw" => ["pew"]}
    |> Map.get(string_id)
  end

  def valid_ids do
    ["abo", "hot", "oow", "ctu", "afr", "dgu", "abd", "hip", "inu", "bgi", "osy",
     "imx", "abf", "ikl", "nru", "gmy", "bde", "lot", "agj", "muy", "ehu", "ehi",
     "hnt", "ajy", "aey", "eil", "deu", "bil", "ooz", "hop", "nno", "ggi", "acy",
     "npw", "ahp", "ivy", "aes", "mmo", "fnu", "ewy", "afn", "ott", "cgo", "abl",
     "aft", "dop", "bdo", "cox", "chi", "flu", "ops", "epy", "tux", "eit", "ehr",
     "now", "app", "acm", "ovw", "bfi", "amy", "atx", "ept", "psy", "amt", "aps",
     "itt", "aly", "bow", "ddo", "akr", "alx", "ell", "diy", "eny", "dim", "beg",
     "cno", "ajw", "opp", "eeg", "aot", "est", "aet", "imo", "mru", "orw", "dos",
     "inn", "etw", "aqu", "ill", "dei", "oty", "bio", "fop", "hmm", "hor", "den",
     "cit", "aim", "itz", "iko", "ilo", "fgo", "emn", "bbu", "nsu", "ilp", "hss",
     "rty", "coo", "oru", "fot", "ipt", "los", "emu", "egv", "enp", "alw", "bir",
     "cei", "ent", "mmu", "eey", "add", "pry", "ady", "acp", "ems", "def", "blo",
     "ary", "mow", "bet", "ads", "ego", "eht", "abp", "esu", "eop", "bfo", "ahy",
     "ast", "abc", "eru", "guy", "efo", "anr", "ipr", "adw", "iwz", "agr", "cho",
     "dir", "dpu", "atu", "efi", "aor", "egm", "anv", "dis", "del", "guv", "ens",
     "htu", "acl", "ehp", "gju", "aer", "bjo", "ilt", "ffo", "aep", "dry", "ino",
     "oww", "efr", "bmo", "det", "egg", "bbi", "boy", "act", "dot", "ahj", "deo",
     "bhu", "glu", "eno", "eip", "lsy", "eev", "amp", "eow", "bey", "moo", "adt",
     "bdu", "dnu", "cop", "ail", "ekn", "psu", "dor", "msy", "ant", "ajr", "ikt",
     "gjo", "adl", "dmo", "bis", "hos", "bor", "bgo", "epp", "ehm", "bcu", "mpu",
     "iss", "enw", "aht", "ist", "dno", "eho", "ams", "hsy", "anp", "ahs", "osw",
     "bru", "ehs", "acr", "adh", "etv", "cis", "amm", "dip", "ako", "ado", "esy",
     "ehx", "imr", "kuy", "emw", "imv", "aku", "cip", "adf", "aby", "abg", "agw",
     "bit", "hoo", "noy", "bnu", "hhu", "cdu", "apy", "abr", "bbe", "ikn", "git",
     "dlo", "all", "eet", "coy", "giw", "mot", "biz", "eef", "gru", "efz", "eky",
     "fix", "gin", "buy", "ipz", "bos", "iks", "hmu", "got", "aeg", "imp", "eor",
     "ees", "ikp", "adi", "his", "eir", "dez", "dmu", "ipy", "bho", "bbo", "fir",
     "iln", "ost", "agg", "iny", "puy", "ael", "emo", "pxy", "fly", "goo", "int",
     "air", "elm", "cru", "lop", "kow", "afo", "oop", "not", "sty", "any", "gij",
     "ely", "brr", "abj", "ehn", "abh", "cim", "opr", "fry", "ekl", "aks", "apt",
     "cor", "alp", "dhi", "npu", "art", "asy", "ceu", "ghu", "bew", "ips", "cot",
     "eot", "loo", "egk", "agl", "aab", "efy", "hty", "ptu", "rwy", "emt", "agh",
     "ipx", "asx", "adn", "joy", "low", "isx", "elt", "abt", "fin", "aew", "ipp",
     "hwy", "ddi", "ahr", "opt", "itw", "hit", "bdi", "agn", "ins", "efw", "irs",
     "bpu", "agy", "jot", "afg", "att", "rtu", "otu", "awx", "egl", "fis", "acw",
     "asw", "acd", "fgu", "aah", "inx", "dew", "eer", "nnu", "mos", "egr", "dil",
     "gho", "afy", "ouy", "din", "lpy", "how", "ery", "ags", "hmo", "ikr", "egt",
     "amr", "inp", "dgo", "nos", "adp", "ilm", "der", "ehw", "amw", "bee", "oot",
     "fit", "apw", "gir", "gip", "acv", "ntu", "abn", "ort", "ddu", "cdo", "ahn",
     "amn", "cry", "gmu", "hhs", "erv", "eew", "cow", "ciy", "ttu", "bij", "arw",
     "mop", "alm", "esx", "eep", "egp", "box", "aov", "agp", "mtu", "cpu", "osu",
     "dho", "opx", "bmu", "ago", "adm", "acn", "msu", "dey", "dgi", "esw", "epr",
     "lox", "gow", "awy", "btu", "bno", "dhu", "aky", "gpy", "acs", "ety", "gtu",
     "eel", "eiv", "evx", "ajm", "aen", "ksy", "bop", "ahm", "iop", "glo", "ejt",
     "dik", "gnu", "ppu", "bgu", "atv", "ahw", "nor", "dou", "apr", "fox", "otw",
     "inw", "fgi", "for", "jtu", "eek", "ass", "bco", "owy", "ehy", "fru", "bin",
     "opw", "bsu", "him", "apz", "aiv", "efl", "efn", "err", "ims", "ace", "boo",
     "gpu", "adg", "anw", "afx", "agt", "epw"]
    |> Enum.into(HashSet.new)
  end
end
