defmodule Jumble.ScowlDict.Size60.Length14 do
  def get(string_id) do
    %{"aaceilnrtttuvy" => ["unattractively"],
      "aceeimmmnoottw" => ["committeewoman"],
      "cdeeinoprsstuv" => ["productiveness"],
      "aceeinoprrsssu" => ["precariousness"],
      "aeeiimnnorsttx" => ["exterminations"],
      "adeeehilnooprt" => ["radiotelephone"],
      "aacceillnorstu" => ["recalculations"],
      "aceghilllnooty" => ["ethnologically"],
      "aceiillnnooost" => ["neocolonialist"],
      "aadehnorrssttw" => ["northeastwards"],
      "acillmmnnootty" => ["noncommittally"],
      "aceeeglmnorstt" => ["electromagnets"],
      "abceeiiilrstvy" => ["serviceability"],
      "aaceiillnpstty" => ["antiseptically"],
      "accehhillnoprs" => ["chancellorship"],
      "abeeghiilnstux" => ["extinguishable"],
      "adeiiinnoorstt" => ["disorientation"],
      "agiillnoorsuvy" => ["vaingloriously"],
      "aaciiilmnoppst" => ["misapplication"],
      "aainnooprrsttt" => ["transportation"],
      "aeegiilnnnrtty" => ["entertainingly"],
      "eeeegggiinnnor" => ["geoengineering"],
      "ccdeeeinnnortt" => ["interconnected"],
      "ceeiinnoprsssu" => ["perniciousness"],
      "aegghinnooprtv" => ["photoengraving"],
      "aeghimmnooprst" => ["metamorphosing"],
      "cddeeilnnostty" => ["discontentedly"],
      "acdeegilnnoqru" => ["grandiloquence"],
      "ceefgiinnorttu" => ["counterfeiting"],
      "acegiillmnoort" => ["terminological"],
      "deegilmnnrsttu" => ["disgruntlement"],
      "aaeeiilllrttvy" => ["alliteratively"],
      "eeeiilmnopssst" => ["impolitenesses"],
      "elmopprsstuuuy" => ["presumptuously"],
      "aaaeglllmoprrs" => ["parallelograms"],
      "aceefmnnnooprr" => ["nonperformance"],
      "acceeilllopsty" => ["telescopically"],
      "adefgiimnorrst" => ["transmogrified"],
      "aeegiilmnorsss" => ["generalissimos"],
      "ccdehhillnoors" => ["schoolchildren"],
      "aeegginorrsssu" => ["gregariousness"],
      "aceeghilnorssu" => ["clearinghouses"],
      "aaceghiloorsst" => ["archaeologists"],
      "adeeginnopprrt" => ["preponderating"],
      "acegilmnnooort" => ["conglomeration"],
      "aabceillmorrty" => ["barometrically"],
      "elnoopssstuuuv" => ["voluptuousness"],
      "aceeghillnopry" => ["hypoallergenic"],
      "adeeehhllortwy" => ["wholeheartedly"],
      "abccginnorsttu" => ["subcontracting"],
      "aaceeeffhkklst" => ["kaffeeklatches"],
      "eeeilnorrssstu" => ["irresoluteness"],
      "aaeilmnrssstux" => ["transsexualism"],
      "ceeghinorrsttv" => ["overstretching"],
      "abccnoorrssttu" => ["subcontractors"],
      "aacgillloottuy" => ["tautologically"],
      "efhioopprrssss" => ["professorships"],
      "celmnoopsttuuy" => ["contemptuously"],
      "abdeeiilnnpsss" => ["indispensables"],
      "aceghopprrrsty" => ["cryptographers"],
      "acegghhinooprr" => ["choreographing"],
      "aaiillmnnosttu" => ["multinationals"],
      "aceilnnnnootuv" => ["unconventional"],
      "aabceeeghlnnss" => ["changeableness"],
      "aacegiillllsty" => ["legalistically"],
      "cceiimnnoopsst" => ["misconceptions"],
      "addeeeffiinrtt" => ["differentiated"],
      "eehiilmnnqrstu" => ["relinquishment"],
      "acegilllmootyy" => ["etymologically"],
      "acghiillnooort" => ["ornithological"],
      "aaeiillmnptuvy" => ["manipulatively"],
      "aacillmopsttyy" => ["asymptotically"],
      "abdeefiiilnntu" => ["unidentifiable"],
      "acfgiinnoorstu" => ["configurations"],
      "acghiiinopsstt" => ["sophisticating"],
      "aaaccillorttuy" => ["autocratically"],
      "accefiiinopsst" => ["specifications"],
      "eeeeinprrssssv" => ["repressiveness"],
      "eehinnoorssttw" => ["noteworthiness"],
      "ceeefgllnnsstu" => ["neglectfulness"],
      "aacdiilllmopty" => ["diplomatically"],
      "aceehimmnorssv" => ["servomechanism"],
      "aaddegghnrrstu" => ["granddaughters"],
      "aacghillloopty" => ["pathologically"],
      "ceeeioprrssttv" => ["retrospectives"],
      "acdeiinnoorsst" => ["considerations"],
      "abeeiilmnoprss" => ["impressionable"],
      "beelooprrsstuy" => ["obstreperously"],
      "cceeeeeflnnort" => ["teleconference"],
      "abdefiiillnort" => ["defibrillation"],
      "aabcillnooorst" => ["collaborations"],
      "bcdeegiimnnrsu" => ["disencumbering"],
      "adeeghhoopprrt" => ["rephotographed"],
      "adeffgiinorsst" => ["disafforesting"],
      "ceeeilmnnopsst" => ["incompleteness"],
      "beeinooqssssuu" => ["obsequiousness"],
      "aaceiinnnorrst" => ["reincarnations"],
      "aaeehiinorttwz" => ["weatherization"],
      "aceeimmnnorstu" => ["incommensurate"],
      "acdhhiioprrsst" => ["harpsichordist"],
      "aaccfiiilnorst" => ["clarifications"],
      "aaghiilmnorstt" => ["antilogarithms"],
      "accchloopsstuy" => ["staphylococcus"],
      "aeeefghhirsttw" => ["featherweights"],
      "ccdeeennooprrs" => ["correspondence"],
      "aegiinnoopprrt" => ["reapportioning"],
      "aaeilnnnoooprt" => ["nonoperational"],
      "adeeggiinnprst" => ["predesignating"],
      "adeeeimnrssttu" => ["underestimates"],
      "aadeeinnprsstt" => ["antidepressant"],
      "ceeefinorrsttu" => ["counterfeiters"],
      "acehilnorsssuv" => ["chivalrousness"],
      "aadiiilmnorstt" => ["traditionalism"],
      "aceillnnoosstt" => ["constellations"],
      "aaabdeemrsssss" => ["ambassadresses"],
      "bgiillmmnnoouu" => ["immunoglobulin"],
      "aacgilmnoopsst" => ["campanologists"],
      "aaceehilllptty" => ["telepathically"],
      "aeeilmorssttuv" => ["overstimulates"],
      "ccdegiimnnostu" => ["semiconducting"],
      "aachilnopsssyy" => ["psychoanalysis"],
      "aabcefiiinostt" => ["beatifications"],
      "aeegiimnorsttv" => ["overestimating"],
      "aaeiimoppprrst" => ["misappropriate"],
      "bhiiiinooprstt" => ["prohibitionist"],
      "aceeiilnnnrstt" => ["tricentennials"],
      "aacdeeimnnostt" => ["decontaminates"],
      "abcceiillnorry" => ["irreconcilably"],
      "aeginnorrsssst" => ["transgressions"],
      "ceilmnnoorstuy" => ["conterminously"],
      "aegiinnoorrstt" => ["interrogations"],
      "acceeginnorrst" => ["reconsecrating"],
      "bccdiiilnottuy" => ["conductibility"],
      "aacdeiinnoortv" => ["nonradioactive"],
      "dgghiiiinnsstu" => ["distinguishing"],
      "aadiiilnorsttt" => ["traditionalist"],
      "cceiillnnosuvy" => ["inconclusively"],
      "acchiilloprtyy" => ["hypocritically"],
      "aeeggiinorsstt" => ["segregationist"],
      "aaacehillmnpru" => ["alphanumerical"],
      "acceehhloorsst" => ["schoolteachers"],
      "efghhlnossttuu" => ["thoughtfulness"],
      "cegiinnorstttu" => ["reconstituting"],
      "abcelnosstuuuy" => ["subcutaneously"],
      "aachiilloprsty" => ["aphoristically"],
      "abceilnnnosttu" => ["subcontinental"],
      "aaeehimnrssstu" => ["amateurishness"],
      "aaeginnnprstuu" => ["superannuating"],
      "ccgiilnnnnouvy" => ["unconvincingly"],
      "aeefgilmnnnssu" => ["meaningfulness"],
      "bdeiiilrsttuvy" => ["distributively"],
      "ehiiooppprrrst" => ["proprietorship"],
      "adddeeeghnorty" => ["dehydrogenated"],
      "eeeinnoprssssv" => ["responsiveness"],
      "aaabcehlnoppru" => ["unapproachable"],
      "acdeiiinorsssy" => ["idiosyncrasies"],
      "abcinoooorrrst" => ["corroborations"],
      "ceeefimnnorrst" => ["reinforcements"],
      "aadiimnorrsstt" => ["administrators"],
      "aaaeiiilmprrst" => ["paramilitaries"],
      "aaaccehilmprtu" => ["pharmaceutical"],
      "cdeennooprrsst" => ["correspondents"],
      "aadehiioprrstt" => ["radiotherapist"],
      "aacllnnoprttuy" => ["contrapuntally"],
      "aabdiiiilnstvy" => ["inadvisability"],
      "aaadeillqrrstu" => ["quadrilaterals"],
      "abdefiillorrst" => ["defibrillators"],
      "aabbefggilnrst" => ["flabbergasting"],
      "abdeilmorstuxy" => ["ambidextrously"],
      "bceeemmnorsssu" => ["cumbersomeness"],
      "cehhinoopsttty" => ["photosynthetic"],
      "aceiilnoprstuy" => ["pertinaciously"],
      "aaacehiimmnstt" => ["mathematicians"],
      "cceginnorrsttu" => ["reconstructing"],
      "aeegiinorrsttv" => ["interrogatives"],
      "aeeiimnoorsttv" => ["overestimation"],
      "eghhinopprrtyy" => ["hypertrophying"],
      "aacciilmnrsttu" => ["circumstantial"],
      "acilrrssstttuu" => ["structuralists"],
      "acgiilrrssttuu" => ["agriculturists"],
      "aaimnnorsstttu" => ["transmutations"],
      "adgiiiilmnntty" => ["intimidatingly"],
      "beeiimnsssssuv" => ["submissiveness"],
      "bcdeiilnrsttuy" => ["indestructibly"],
      "aacdeeffgiinnt" => ["decaffeinating"],
      "acefiiilmnostu" => ["emulsification"],
      "aaabceiilnrstt" => ["antibacterials"],
      "acdeghillmooot" => ["methodological"],
      "aeeeggiorrssvv" => ["overaggressive"],
      "aeeiilmnnssttt" => ["sentimentalist"],
      "ceeeimmmnoottw" => ["committeewomen"],
      "aaceiilnoprttu" => ["recapitulation"],
      "abdeeeeilnrsst" => ["deliberateness"],
      "abceiilnoprstu" => ["republications"],
      "eeeiimnprssssv" => ["impressiveness", "permissiveness"],
      "ceeeegiilnnort" => ["electioneering"],
      "eeeellnnrsssst" => ["relentlessness"],
      "aacciiilmprtty" => ["impracticality"],
      "ccdenooprrstuu" => ["superconductor"],
      "aaadeiilnnrtuv" => ["valetudinarian"],
      "aacillmnoprtyy" => ["patronymically"],
      "bciiiloprrttuy" => ["corruptibility"],
      "aabeiiiillnnty" => ["inalienability"],
      "ceeilmnopsssuv" => ["compulsiveness"],
      "bdegiiinrrsttu" => ["redistributing"],
      "acceillmnnoouy" => ["uneconomically"],
      "acgghiklnosstu" => ["laughingstocks"],
      "aabddeelnnrstu" => ["understandable"],
      "aabeghiooprrtu" => ["autobiographer"],
      "acdiiimnorrsst" => ["discriminators"],
      "bceeehilmnoprs" => ["comprehensible"],
      "eefgillnnorttu" => ["fortunetelling"],
      "acginoooprrstt" => ["prognosticator"],
      "ceiilllnoosstv" => ["violoncellists"],
      "bceefiiilprtty" => ["perfectibility"],
      "aabcccghiknrst" => ["backscratching"],
      "acdefiiinoottx" => ["detoxification"],
      "adeeeggimnnsst" => ["disengagements"],
      "cdeeeiiinnsssv" => ["indecisiveness"],
      "ceehimmopsssty" => ["metempsychosis"],
      "aaceilnnoorstv" => ["conversational"],
      "ahiimnoprssstt" => ["misanthropists"],
      "abeegiinrssssu" => ["agribusinesses"],
      "aeeehinssstuvx" => ["exhaustiveness"],
      "aaaeeginnprstu" => ["septuagenarian"],
      "deeiiiilmrstuv" => ["verisimilitude"],
      "cceeinnoopprst" => ["preconceptions"],
      "aegiilnnnrstty" => ["intransigently"],
      "beegiiilllnntu" => ["unintelligible"],
      "abilmnnorstuuy" => ["insurmountably"],
      "deeenoprrssuux" => ["underexposures"],
      "cdeeiinrssssuv" => ["discursiveness"],
      "aeeiilmnnsttty" => ["sentimentality"],
      "aabehilnnnorst" => ["nontarnishable"],
      "acgiimmnoorrss" => ["microorganisms"],
      "accefiiinorstt" => ["rectifications", "certifications"],
      "eeehiinprsstvy" => ["hypersensitive"],
      "aceghillnoopty" => ["photogenically"],
      "aadddeeehhnrss" => ["hardheadedness"],
      "beeinoorsssstu" => ["boisterousness"],
      "aghhiiooprrsty" => ["historiography"],
      "giiinnooopprst" => ["propositioning"],
      "aefillnooprssy" => ["professionally"],
      "aacfinorssttuy" => ["unsatisfactory"],
      "abcilmnorstuuy" => ["rambunctiously"],
      "aaeilnoorstuvv" => ["overvaluations"],
      "aacchilllossty" => ["scholastically"],
      "aciinnoprrsstt" => ["transcriptions"],
      "adiilnoprssttu" => ["postindustrial"],
      "aadeiiimnrsttv" => ["administrative"],
      "aceeinoorrsstv" => ["conservatoires", "conservatories"],
      "aacdhimooprtyy" => ["cardiomyopathy"],
      "aaahiinorrsttu" => ["authoritarians"],
      "ceeeiimmoorrtt" => ["micrometeorite"],
      "aaceeinnprrsst" => ["transparencies"],
      "aaeeprrsssttuu" => ["supersaturates"],
      "eeinoopprsssss" => ["prepossessions"],
      "bdiiiiiilnstvy" => ["indivisibility"],
      "aabcdeginorrst" => ["rebroadcasting"],
      "aacegillloopty" => ["apologetically"],
      "acdeeinooprrrt" => ["reincorporated"],
      "acceinoopprstu" => ["preoccupations"],
      "aaabcehilnoppr" => ["inapproachable"],
      "aaiimnoopprstx" => ["approximations"],
      "cceghiklnosttu" => ["shuttlecocking"],
      "aeiiilnnrsttvy" => ["intransitively"],
      "aacgilllrrtuuy" => ["agriculturally"],
      "efggiiinnnprrt" => ["fingerprinting"],
      "aaaiinnossssst" => ["assassinations"],
      "beggiiilssttuy" => ["suggestibility"],
      "ddeehinnorrsuu" => ["undernourished"],
      "ceeehimnoprssv" => ["comprehensives"],
      "ceeehmmopsssty" => ["metempsychoses"],
      "aaceinoprrsstt" => ["procrastinates"],
      "aacfgiiimnnost" => ["magnifications"],
      "aaceghilllmpty" => ["phlegmatically"],
      "cceeeffiiiinns" => ["inefficiencies"],
      "abcchhiioprrss" => ["archbishoprics"],
      "aceeiilmnnrstt" => ["incrementalist"],
      "ceeilmnossstuu" => ["meticulousness"],
      "ceiiooprsssuuv" => ["oversuspicious"],
      "aeeiiilmnssttx" => ["existentialism"],
      "bdehiiloorrstt" => ["bloodthirstier"],
      "bbcdeeiorrssuv" => ["oversubscribed"],
      "aiinnooprssstt" => ["transpositions"],
      "acceegillnorty" => ["geocentrically", "egocentrically"],
      "aabeehiiilrttv" => ["rehabilitative"],
      "aeginorsssttuu" => ["gratuitousness"],
      "cceeinorrsttuv" => ["reconstructive"],
      "accehilmmnopst" => ["accomplishment"],
      "abenoorrssstuu" => ["brontosauruses"],
      "aadeeilnrrsttt" => ["transliterated"],
      "cceelnorrttuuu" => ["counterculture"],
      "ceiilnnnosstty" => ["inconsistently"],
      "cdeinoooprrtuv" => ["overproduction"],
      "eegilnooprrvwy" => ["overpoweringly"],
      "ccdeeeinopsssu" => ["pseudosciences"],
      "aeeegginrssssv" => ["aggressiveness"],
      "fghhiiinnoopst" => ["photofinishing"],
      "aaaccdilorrsuv" => ["cardiovascular"],
      "acdeeghiinnruv" => ["underachieving"],
      "aaeffiimnorrst" => ["reaffirmations"],
      "aeeeeinprrsttv" => ["representative"],
      "abdeggiknnorru" => ["groundbreaking"],
      "bdeegiiillnsvy" => ["disbelievingly"],
      "aeeikmrssssstt" => ["taskmistresses"],
      "aabeghiiilnrtt" => ["rehabilitating"],
      "beeinnoprssssu" => ["businessperson"],
      "cceeeiinnnnosv" => ["inconveniences"],
      "addeimnnrssstu" => ["misunderstands"],
      "agiiilllmnntuy" => ["illuminatingly"],
      "deeegilnooprvv" => ["overdeveloping"],
      "acdeefhiinnrss" => ["disenfranchise"],
      "adeeghhillrtty" => ["lightheartedly"],
      "aceiiiilnpprst" => ["principalities"],
      "acceemnorrsstt" => ["concertmasters"],
      "aadffiiiilnost" => ["disaffiliation"],
      "aaggiilnnosttu" => ["agglutinations"],
      "bceehilmnoprsy" => ["comprehensibly"],
      "aaceklnnorstuy" => ["cantankerously"],
      "aacfgilnnoorst" => ["conflagrations"],
      "abciiilnrsttuy" => ["inscrutability"],
      "aiijnoopssttux" => ["juxtapositions"],
      "aaceeinrsstttv" => ["attractiveness"],
      "acdiilnooorsst" => ["discolorations"],
      "abeeilnnssttuu" => ["sublieutenants"],
      "aacdeimnnnottu" => ["uncontaminated"],
      "bdhiilloorstty" => ["bloodthirstily"],
      "eegilmooorsstt" => ["meteorologists"],
      "aaelmnooppsstu" => ["postmenopausal"],
      "aeeiilmmnnoptt" => ["implementation"],
      "aceiiinopprstt" => ["precipitations"],
      "aacehiinnotttu" => ["authentication"],
      "aabceehilnrsst" => ["charitableness"],
      "bceeilnnnoortv" => ["nonconvertible"],
      "ceemopprrsstuu" => ["supercomputers"],
      "chiilorrstttuu" => ["horticulturist"],
      "addeeeeghlmmrs" => ["sledgehammered"],
      "deeefiiinnnsst" => ["indefiniteness"],
      "abdeeeghinrsst" => ["bigheartedness"],
      "acdeiiilnnortu" => ["unidirectional"],
      "aacdeiilnosttu" => ["educationalist"],
      "acdegimnnnortu" => ["countermanding"],
      "acghilllnooopy" => ["phonologically"],
      "aceiiillmpttuv" => ["multiplicative"],
      "aacdgiiinnosst" => ["diagnosticians"],
      "accdeeehhiknrt" => ["chickenhearted"],
      "acceeimmnostux" => ["excommunicates"],
      "aaceghimnoprty" => ["cinematography"],
      "ceeeefflnrstvy" => ["effervescently"],
      "ccciilmnoortuu" => ["circumlocution"],
      "ceeiimnnoopttv" => ["noncompetitive"],
      "aaiillnnorstty" => ["transitionally"],
      "aadeeilmnorttt" => ["tatterdemalion"],
      "eilmnnoosssuuv" => ["voluminousness"],
      "aaailnnnorsstt" => ["transnationals"],
      "aehimnnoorsssu" => ["harmoniousness"],
      "addeeeghnorsty" => ["dehydrogenates"],
      "aadeiimnnorssv" => ["animadversions"],
      "aehhiilnopprst" => ["philanthropies"],
      "abeeehlnrsssst" => ["breathlessness"],
      "aiiimnooprsstv" => ["improvisations"],
      "ceeehimorsstty" => ["hysterectomies"],
      "acccgiimnnrstu" => ["circumstancing"],
      "ddeiiiilmssstu" => ["dissimilitudes"],
      "adeggiiinnrstt" => ["disintegrating"],
      "ceeiilpprrstvy" => ["prescriptively"],
      "aaabellnnrsttu" => ["untranslatable"],
      "ccdeeefinnoorv" => ["overconfidence"],
      "eeeinopssssssv" => ["possessiveness"],
      "cddeeiinnooprt" => ["preconditioned"],
      "abcdeeehiilnpr" => ["indecipherable"],
      "aacdeiiilllsty" => ["idealistically"],
      "aeeilnoortttxy" => ["extortionately"],
      "deeeeghnnrrstt" => ["restrengthened"],
      "addeeehnnnopss" => ["openhandedness"],
      "aaceeffilnotty" => ["affectionately"],
      "ceiiiinossttvv" => ["vivisectionist"],
      "aehimoopppsstu" => ["hippopotamuses"],
      "aaeillllmrttuy" => ["multilaterally"],
      "aceginnoossstu" => ["contagiousness"],
      "aaceeimnnorstt" => ["recontaminates"],
      "aabcciilnottuy" => ["accountability"],
      "acceiinoprsssu" => ["capriciousness"],
      "ceemnnnooprstu" => ["pronouncements"],
      "addeeghhhinnss" => ["highhandedness"],
      "ceeegilnoprsst" => ["teleprocessing"],
      "acdeeimmnnoort" => ["recommendation"],
      "aacffiiilnosst" => ["falsifications"],
      "abdeehiilsssst" => ["disestablishes"],
      "aeiinoopprrstx" => ["expropriations"],
      "aeiilllrsttuvy" => ["illustratively"],
      "bdgggiillmnnoy" => ["mindbogglingly"],
      "acefinrrrsttuu" => ["infrastructure"],
      "achiioprssstty" => ["astrophysicist"],
      "aaccillnooptuy" => ["occupationally"],
      "aafimnnoorrstt" => ["transformation"],
      "diiiinnoopssst" => ["indispositions"],
      "aabdeeehhirrss" => ["haberdasheries"],
      "aeeemnorsstttv" => ["overstatements"],
      "aeehinpppprrsw" => ["whippersnapper"],
      "accdeiillnnoty" => ["coincidentally"],
      "aaceiinoprrstv" => ["prevarications"],
      "aceiiimmnoorss" => ["commissionaire"],
      "eeegiinnprrrtt" => ["reinterpreting"],
      "abeelnnnorrstu" => ["nonreturnables"],
      "aacdeinoprrstt" => ["procrastinated"],
      "accceimmnooors" => ["macroeconomics"],
      "adeeilmorsttuv" => ["overstimulated"],
      "cdelmnnoooosty" => ["monocotyledons"],
      "abdeeiilmnnrty" => ["indeterminably"],
      "cddeilnooostuy" => ["dicotyledonous"],
      "aeeghimoprrsss" => ["seismographers"],
      "acddeegklnnouw" => ["unacknowledged"],
      "ciinnooorssttt" => ["contortionists"],
      "aaaegiiilmnrst" => ["egalitarianism"],
      "aacdeeijkrsttt" => ["straitjacketed"],
      "aeeehnoprrsstw" => ["weatherpersons"],
      "aadehorsssttuw" => ["southeastwards"],
      "bceeilnoorrttv" => ["controvertible"],
      "acdeeeiosssttv" => ["videocassettes"],
      "abeeilmnnnostu" => ["unmentionables"],
      "aadiilnnnoortt" => ["nontraditional"],
      "adeeehimrsssst" => ["headmistresses"],
      "aaacceghilloor" => ["archaeological"],
      "aehiioorrssttt" => ["osteoarthritis"],
      "aaadeglnostuvy" => ["advantageously"],
      "eiilnoorssttuv" => ["revolutionists"],
      "aabbeiillosssu" => ["bouillabaisses"],
      "abcceelllnnoot" => ["noncollectable"],
      "acfiilnnossttu" => ["functionalists"],
      "bcdeeiilnrsttu" => ["indestructible"],
      "cehinooprsssuy" => ["psychoneurosis"],
      "cgiiilmnoorsst" => ["criminologists"],
      "acegiilnossttu" => ["gesticulations"],
      "cdeiiiilrsttuv" => ["diverticulitis"],
      "aceghlnnnoooty" => ["nanotechnology"],
      "aaeegilnprstxy" => ["exasperatingly"],
      "aeillmnosstuuy" => ["simultaneously"],
      "cceimoooprrrss" => ["microprocessor"],
      "abeeeinorrrstv" => ["reverberations"],
      "acdeeennopprrs" => ["preponderances"],
      "aeeginooprrstu" => ["supererogation"],
      "eiinnorsssttuu" => ["nutritiousness"],
      "aacdeglmnnorss" => ["scandalmongers"],
      "aaceghiinntttu" => ["authenticating"],
      "acceeiinnoorss" => ["concessionaire"],
      "beeehillmmnsst" => ["embellishments"],
      "aacdeillmopryy" => ["polyacrylamide"],
      "acfgiiiinnosst" => ["significations"],
      "aceginnnoossuu" => ["consanguineous"],
      "abcdenooorrrtu" => ["uncorroborated"],
      "aaacehimoopprs" => ["pharmacopoeias"],
      "achiiinoopsstt" => ["sophistication"],
      "aefiiiilmnnsst" => ["infinitesimals"],
      "cdeiiinnnssstt" => ["indistinctness"],
      "aceeiilmmnnrst" => ["incrementalism"],
      "abcegiiloorstt" => ["bacteriologist"],
      "ceeeiooprrttvv" => ["overprotective"],
      "aacehlnopsssyy" => ["psychoanalyses"],
      "adehorsssttuww" => ["southwestwards"],
      "aceeemnorrstuu" => ["countermeasure"],
      "aciimmnnossttu" => ["anticommunists"],
      "abddeeehllnssu" => ["bullheadedness"],
      "cceiinorssstuu" => ["circuitousness"],
      "cdeeiiinnsstvv" => ["vindictiveness"],
      "aadeellmnprtty" => ["departmentally"],
      "adeeiinnoprstt" => ["predestination"],
      "aeegooprrrstuy" => ["supererogatory"],
      "acdeegimnorstu" => ["discouragement"],
      "acegiillorssuy" => ["sacrilegiously"],
      "aadeeghinqrrtu" => ["headquartering"],
      "eefimnnoorrstw" => ["frontierswomen"],
      "bcceeikkknorrs" => ["knickerbockers"],
      "begilnorsssuuu" => ["lugubriousness"],
      "aadeegimnnrrst" => ["disarrangement"],
      "acdeeeimnoppst" => ["appendectomies"],
      "ceeeflnprssstu" => ["respectfulness"],
      "ccdeiinnnoosst" => ["disconnections"],
      "deeeeillmmosss" => ["mesdemoiselles"],
      "cegiinnooprstu" => ["counterpoising"],
      "bdeeeilmmnostw" => ["disembowelment"],
      "aefgiimnorrsst" => ["transmogrifies"],
      "adeeghilnnrrty" => ["heartrendingly"],
      "ghiilnooorsstt" => ["ornithologists"],
      "aceeggimnnorrs" => ["scaremongering"],
      "acdiiiilnnnost" => ["disinclination"],
      "aacceknorstttu" => ["counterattacks"],
      "ceiinoprsssstu" => ["percussionists"],
      "cegiiknnnorstu" => ["countersinking"],
      "aabceenrsssstt" => ["abstractnesses"],
      "aaehiiimnnsstt" => ["antihistamines"],
      "ceefiinnossstu" => ["infectiousness"],
      "acfinnnooorstt" => ["confrontations"],
      "acffiiinoorstt" => ["fortifications"],
      "aabcghiiooprtu" => ["autobiographic"],
      "aceillnnnorsty" => ["noncrystalline"],
      "ccefllnsssuuuy" => ["unsuccessfully"],
      "acceehilmoprst" => ["petrochemicals"],
      "accdhhinooprsy" => ["hypochondriacs"],
      "aacchilnopstyy" => ["psychoanalytic"],
      "aeffhilnnsstuu" => ["unfaithfulness"],
      "aaelnoprsttuuy" => ["polyunsaturate"],
      "aaeilnooprsttx" => ["extrapolations"],
      "aeeeinnoprrstt" => ["representation"],
      "beeeinrssssuvv" => ["subversiveness"],
      "aeeiilnnorrstt" => ["interrelations"],
      "accceillnnorty" => ["concentrically"],
      "aggiiilnnortvy" => ["invigoratingly"],
      "acdeeenrrrstuy" => ["undersecretary"],
      "ceefinoorsssuv" => ["vociferousness"],
      "aaiinooppprrst" => ["appropriations"],
      "aeiimnnooprsst" => ["impersonations"],
      "cceeiinnossttu" => ["constituencies"],
      "beeeimmnrrsstu" => ["reimbursements"],
      "abeeghiilnrsst" => ["reestablishing"],
      "abbeghiiiloprs" => ["bibliographies"],
      "deehhnorrsstuw" => ["thundershowers"],
      "aeegiimnnnortu" => ["mountaineering"],
      "acceinnnoorstt" => ["concentrations"],
      "aaccegiimnrtuv" => ["circumnavigate"],
      "aabcdeenrssstt" => ["abstractedness"],
      "acehiinnssttuu" => ["unenthusiastic"],
      "abdeeilmnnorst" => ["indemonstrable"],
      "abclllnnoortuy" => ["uncontrollably"],
      "aabcceeelnpsst" => ["acceptableness"],
      "acdehhiimoprrt" => ["hermaphroditic"],
      "eeeilnoprssssx" => ["expressionless"],
      "aceeeeinnrrstt" => ["tercentenaries"],
      "aabcdeennprsuu" => ["superabundance"],
      "aabcefgiinprrt" => ["prefabricating"],
      "accinprssttuuu" => ["acupuncturists"],
      "ceeinnosssstuu" => ["incestuousness"],
      "aaceeghnooprrs" => ["oceanographers"],
      "acdeehilmnosst" => ["methodicalness"],
      "adeeeffiinrstt" => ["differentiates"],
      "ceeiilmorrstuy" => ["meretriciously"],
      "acfiiilnostttu" => ["stultification"],
      "aabcefiiinottu" => ["beautification"],
      "aeegiiilrrrstu" => ["irregularities"],
      "aacinooprrrstt" => ["procrastinator"],
      "ceiiiillmpsttu" => ["multiplicities"],
      "ddeeeeinnnprtt" => ["interdependent"],
      "abcdeeehilnpru" => ["undecipherable"],
      "aadeeghiloprrt" => ["radiotelegraph"],
      "aaabdhimoprsss" => ["ambassadorship"],
      "adeeegoprrstuy" => ["daguerreotypes"],
      "aacghilmooprst" => ["pharmacologist"],
      "acfgiilmnnnotu" => ["malfunctioning"],
      "ceiinopprrsstu" => ["superscription"],
      "abbcdeilmoostu" => ["discombobulate"],
      "aabeilmnoprstu" => ["perambulations"],
      "aabegiillnosuv" => ["bougainvilleas"],
      "ceeilllnoorstu" => ["nitrocellulose"],
      "aefillooprrssy" => ["professorially"],
      "cfimnnnooorsst" => ["nonconformists"],
      "aciiiilprssttu" => ["spiritualistic"],
      "ccceeeiiinrstt" => ["eccentricities"],
      "addeeegoprrtuy" => ["daguerreotyped"],
      "aaccdeiinnortt" => ["contraindicate"],
      "aaciinnnopprtt" => ["nonparticipant"],
      "acceiiilmnorst" => ["cliometricians"],
      "aeeeiinprrtttv" => ["interpretative"],
      "eefiiilmoprssv" => ["oversimplifies"],
      "deefiiilmoprsv" => ["oversimplified"],
      "adeiimnnoppstt" => ["disappointment"],
      "aeeeiiinnprstt" => ["penitentiaries"],
      "aeeiinnoprrttt" => ["interpretation"],
      "aabdeiikmnorst" => ["disembarkation"],
      "aceillnnnootvy" => ["conventionally"],
      "ciiilrsstttuuv" => ["viticulturists"],
      "ceeghinorsttuw" => ["counterweights"],
      "dddeeeelnopruv" => ["underdeveloped"],
      "acdeefinnoorst" => ["confederations"],
      "aaccdeiimnortt" => ["antidemocratic"],
      "accefgiiiinnns" => ["insignificance"],
      "aacehiillnttty" => ["antithetically"],
      "aadeilnnortuuv" => ["undervaluation"],
      "ceilmooprrsstu" => ["multiprocessor"],
      "acdeehiiinnrst" => ["disinheritance"],
      "aeeeillmnprtxy" => ["experimentally"],
      "abcceilnnnoosu" => ["unconscionable"],
      "adeeeiilmnrtty" => ["intermediately"],
      "abceeelnnoorrv" => ["nonrecoverable"],
      "aadefgghinnrrt" => ["grandfathering"],
      "ceeinnoorssssu" => ["censoriousness"],
      "ceeeglnoopprss" => ["congresspeople"],
      "aabchilooprstu" => ["claustrophobia"],
      "aaabcehilllpty" => ["alphabetically"],
      "eehinnorssstww" => ["newsworthiness"],
      "aabcefiinoprrt" => ["prefabrication"],
      "aachlnopssstyy" => ["psychoanalysts"],
      "ccdeeeiinnnnov" => ["inconvenienced"],
      "aacglnoorrttuy" => ["congratulatory"],
      "aaciilllmorsty" => ["moralistically"],
      "aabeiiilnprsty" => ["inseparability"],
      "aeeehilnprttvy" => ["hyperventilate"],
      "ceeiinnorrsttv" => ["nonrestrictive"],
      "beiiiilmprssty" => ["impressibility"],
      "aacciillmnostu" => ["miscalculation"],
      "aillnooopprrty" => ["proportionally"],
      "aaeiilnnossstt" => ["sensationalist"],
      "aeeeghlnoprrss" => ["selenographers"],
      "aaeeilnnprrtty" => ["interplanetary"],
      "aabcfilnnoostu" => ["confabulations"],
      "ccceeeilnnosss" => ["conscienceless"],
      "cdeeinnorsttuv" => ["nondestructive"],
      "aeeghhlorsstuu" => ["slaughterhouse"],
      "aacegghillopry" => ["geographically"],
      "behiiiinossttx" => ["exhibitionists"],
      "afiiimmnnoorst" => ["misinformation"],
      "adeeeimnrssttv" => ["advertisements"],
      "abcdeeiilnnors" => ["inconsiderable"],
      "aaeiilmnnossst" => ["sensationalism"],
      "acegilllnooruy" => ["neurologically"],
      "beeeillnorsssu" => ["rebelliousness"],
      "aabcdeeinrrstt" => ["scatterbrained"],
      "eeefllnorrsttu" => ["fortunetellers"],
      "aacghiillprsst" => ["calligraphists"],
      "aacdeelnnnrstt" => ["transcendental"],
      "bccilnoosssuuy" => ["subconsciously"],
      "deegiiilmoopst" => ["epidemiologist"],
      "accdeeinnnostu" => ["discountenance"],
      "deeeelmnoprstv" => ["redevelopments"],
      "abcceiilmmnnou" => ["incommunicable"],
      "aacceghilloost" => ["eschatological"],
      "acccehiinorstt" => ["architectonics"],
      "acdeiiiimnnrst" => ["indiscriminate"],
      "eeilmnnoosssst" => ["motionlessness"],
      "eehiinoopssttv" => ["photosensitive"],
      "aceehiinppprst" => ["apprenticeship"],
      "eeegginsssstuv" => ["suggestiveness"],
      "accdeeeelnoprs" => ["preadolescence"],
      "aceinnnooooprt" => ["noncooperation"],
      "acdiilnnooosst" => ["consolidations"],
      "aceeghhooprrrs" => ["choreographers"],
      "achiiillnorsty" => ["histrionically"],
      "aaeiilnnnorstt" => ["internationals"],
      "aefimnnoorrstw" => ["frontierswoman"],
      "accdeeilnnnsty" => ["incandescently"],
      "aaciilnooprrst" => ["conspiratorial"],
      "adeelnnopprrty" => ["preponderantly"],
      "aaaiiimnnqrstu" => ["antiquarianism"],
      "aeilnooopprtuv" => ["overpopulation"],
      "adiiilnrsssttu" => ["industrialists"],
      "adegilmoorsstt" => ["dermatologists"],
      "aaceegiillmnsv" => ["evangelicalism"],
      "ceeegiinorrsvx" => ["overexercising"],
      "aciiilnopssuuy" => ["inauspiciously"],
      "acdeiijlnnopru" => ["nonprejudicial"],
      "acgiiilllnstuy" => ["linguistically"],
      "acfgilnnnottuu" => ["nonfluctuating"],
      "aabehiiilnortt" => ["rehabilitation"],
      "eeghillmnorvwy" => ["overwhelmingly"],
      "acehilmoprsstt" => ["thermoplastics"],
      "adeiilnosttuvy" => ["adventitiously"],
      "cdeiinnoorrttu" => ["reintroduction"],
      "eeeeiinprssttv" => ["repetitiveness"],
      "beefhimnrrsstu" => ["refurbishments"],
      "ccehhiinoprssz" => ["schizophrenics"],
      "aacceinnnoostt" => ["concatenations"],
      "aaceillmmrstyy" => ["asymmetrically"],
      "aaeemnnopprsww" => ["newspaperwoman"],
      "abefllnoopsstu" => ["tablespoonfuls"],
      "aaeeegmnnrrrst" => ["rearrangements"],
      "aeegillmnorrst" => ["steamrollering"],
      "ceiiimooprsttv" => ["overoptimistic"],
      "adfiiimnnoorst" => ["disinformation"],
      "aadefilmnnsttu" => ["fundamentalist"],
      "aacfiiinnoqttu" => ["quantification"],
      "aegiiinnossttv" => ["investigations"],
      "aeillmnnrsttuy" => ["instrumentally"],
      "acdggiilnorsuy" => ["discouragingly"],
      "aefilnooprsssw" => ["passionflowers"],
      "aabegilmnrrssy" => ["embarrassingly"],
      "aaceiloprrrtuv" => ["overparticular"],
      "ccceiimmnooors" => ["microeconomics"],
      "aacddeeimnnott" => ["decontaminated"],
      "abegiiilmnprty" => ["impregnability"],
      "aabhiiinpprsst" => ["bipartisanship"],
      "aaellnprrstuuy" => ["supernaturally"],
      "aciiillmnopttu" => ["multiplication"],
      "cgiimmnnooprsu" => ["uncompromising"],
      "addeeehimnpprs" => ["misapprehended"],
      "aeeiilmmnnsstt" => ["sentimentalism"],
      "aceegillnoprtt" => ["electroplating"],
      "cehilmoorsssst" => ["schoolmistress"],
      "deeegiimnnprrt" => ["predetermining"],
      "aaccfiiilnosst" => ["classification"],
      "acfiiijnossttu" => ["justifications"],
      "acceehiiilnstt" => ["technicalities"],
      "abcdeiiilprtty" => ["predictability"],
      "aabceeilllmmty" => ["emblematically"],
      "aabeghiklnrtty" => ["breathtakingly"],
      "ccdeimnoorsstu" => ["semiconductors"],
      "aefilnnooprssu" => ["unprofessional"],
      "acdiiijlnorstu" => ["jurisdictional"],
      "aeeemnooprstux" => ["extemporaneous"],
      "cdeiilnorsssuu" => ["ridiculousness"],
      "bceiiilpssttuy" => ["susceptibility"],
      "aaaaghimnoprst" => ["phantasmagoria"],
      "aeeiiilnopsttt" => ["potentialities"],
      "aeghiilnnsttuy" => ["unhesitatingly"],
      "accefiiillnsty" => ["scientifically"],
      "aceehmnopprrst" => ["rapprochements"],
      "deimnooprssstt" => ["postmodernists"],
      "eeeiopprrrssst" => ["proprietresses"],
      "acceeinnoorrst" => ["reconsecration"],
      "acfiiijllnoost" => ["jollifications"],
      "cddeeiimmnooss" => ["decommissioned"],
      "addeelnopprtuu" => ["underpopulated"],
      "adeeemnnrstttu" => ["understatement"],
      "ceffiiilnnstuy" => ["insufficiently"],
      "aaccfiiinnostt" => ["sanctification"],
      "accdeeilmnortu" => ["counterclaimed"],
      "bbciiilmosttuy" => ["combustibility"],
      "cghhiiloosstty" => ["ichthyologists"],
      "aadeinoppprrtu" => ["unappropriated"],
      "aaeelnnnpssstu" => ["unpleasantness"],
      "abdeeeiilmnnrt" => ["indeterminable"],
      "aacceimmnnopst" => ["accompaniments"],
      "aeeghnooprrstv" => ["photoengravers"],
      "bbceilmnnoostu" => ["noncombustible"],
      "ceghnnooorssuy" => ["geosynchronous"],
      "adgiilllnnotuy" => ["longitudinally"],
      "ceehnooprsssuy" => ["psychoneuroses"],
      "aceginooprsstt" => ["prognosticates"],
      "acdfiiiilnoost" => ["solidification"],
      "acceeilllnorty" => ["electronically"],
      "aacdiiinoossst" => ["disassociation"],
      "aaccceeiillsst" => ["ecclesiastical"],
      "acefiimnnoorrt" => ["reconfirmation"],
      "acdiiiimnnorst" => ["discrimination"],
      "acdefiillnnoty" => ["confidentially"],
      "aceeemnooprstv" => ["overcompensate"],
      "ceehhnoopprsst" => ["phosphorescent"],
      "aaceiimmossttu" => ["semiautomatics"],
      "aaabcelmmnnouw" => ["ambulancewoman"],
      "ddeeiilnorrsss" => ["disorderliness"],
      "eeghilnoprrstu" => ["reupholstering"],
      "ceeginooprrttv" => ["overprotecting"],
      "aagiimnnorrstt" => ["transmigration"],
      "accegiilnrtuxy" => ["excruciatingly"],
      "aaccdeillmorty" => ["democratically"],
      "accceeelnnossv" => ["convalescences"],
      "aacfiilorsstty" => ["satisfactorily"],
      "ccdeinnoorsttu" => ["deconstruction"],
      "aacfiiilnoqstu" => ["qualifications"],
      "bdeiiorrrssttu" => ["redistributors"],
      "cdeilnoprtuuvy" => ["unproductively"],
      "cccilmoorrtuuy" => ["circumlocutory"],
      "addeeeimnrsttu" => ["underestimated"],
      "aacegiilnprttu" => ["recapitulating"],
      "acceeilorssttt" => ["electrostatics"],
      "aceiiiilmnpstu" => ["municipalities"],
      "cegiinnnnooort" => ["nonrecognition"],
      "abiiiillmpstuy" => ["implausibility"],
      "acefiiilprstuy" => ["superficiality"],
      "aceiilnossssuv" => ["lasciviousness"],
      "aabfiiillmmnty" => ["inflammability"],
      "aciiilllmpssty" => ["simplistically"],
      "addeeeimnprttu" => ["unpremeditated"],
      "defgiiiimnnsty" => ["misidentifying"],
      "aeeinoqrsssttu" => ["sequestrations"],
      "aacehiillmrtty" => ["arithmetically"],
      "aceeelmnoprtux" => ["counterexample"],
      "abceeeefnrssst" => ["benefactresses"],
      "adeimnnoorsstt" => ["demonstrations"],
      "cdegiiinnnoort" => ["reconditioning"],
      "deeegknoprrssu" => ["groundskeepers"],
      "aaceeiilpprtvy" => ["appreciatively"],
      "aciilllmooqssu" => ["colloquialisms"],
      "aacillmnoorsty" => ["astronomically"],
      "aacehiiimnrstt" => ["arithmeticians"],
      "abceeeflnnnoor" => ["nonenforceable"],
      "bdeehlooorsttu" => ["troubleshooted"],
      "aaceggilnnoort" => ["congregational"],
      "aceiilnnopssst" => ["nonspecialists"],
      "acdeillnoossty" => ["disconsolately"],
      "ceiijnooprsstt" => ["projectionists"],
      "aaeinnnoprstuu" => ["superannuation"],
      "aabciiilnrttty" => ["intractability"],
      "ceegnnooprrsss" => ["congressperson"],
      "acceilmmnnoors" => ["noncommercials"],
      "ceeeehlnpsssss" => ["speechlessness"],
      "eeimnorsssstuy" => ["mysteriousness"],
      "abeeeikkrrrsst" => ["strikebreakers"],
      "eeeeinprssssvx" => ["expressiveness"],
      "acdehimmnorsty" => ["thermodynamics"],
      "aaaddggiinnstv" => ["disadvantaging"],
      "aabcegiknqrrtu" => ["quarterbacking"],
      "aaaccgiiinnptt" => ["incapacitating"],
      "aegilnoopprtuv" => ["overpopulating"],
      "acefhhiiinpsst" => ["chieftainships"],
      "ceehimnnooprss" => ["comprehensions"],
      "abeegiikknrrst" => ["strikebreaking"],
      "ddeeeimnnnortu" => ["undermentioned"],
      "aeeemnnopprsww" => ["newspaperwomen"],
      "aacdeeimnnortt" => ["recontaminated"],
      "addiiiilnsstuv" => ["individualists"],
      "aabceelmmnnouw" => ["ambulancewomen"],
      "accgiilllooosy" => ["sociologically"],
      "accdiinnoorstt" => ["contradictions"],
      "aefilmnoorrstu" => ["reformulations"],
      "beeegillnnnort" => ["nonbelligerent"],
      "eeefflnorsssst" => ["effortlessness"],
      "aacdeilpqrstuu" => ["quadruplicates"],
      "dhhiimooprstyy" => ["hypothyroidism"],
      "aacdgiillnosty" => ["diagnostically"],
      "aceinnnoorsttv" => ["contraventions"],
      "cdeiloorsstuuy" => ["discourteously"],
      "aaccennorsssst" => ["sacrosanctness"],
      "aeeegillnssttv" => ["televangelists"],
      "aeiilnnooprstt" => ["interpolations"],
      "aacdeiilnorstv" => ["valedictorians"],
      "ceeiilnnnnotvy" => ["inconveniently"],
      "ddeeiijnnossst" => ["disjointedness"],
      "ceginrrrssttuu" => ["restructurings"],
      "acgiillmoosstt" => ["climatologists"],
      "begiiilllnntuy" => ["unintelligibly"],
      "ahhiilnopprstt" => ["philanthropist"],
      "aaccehhiillrry" => ["hierarchically"],
      "deeeinnnprsttu" => ["superintendent"],
      "acdhillnoopryy" => ["hydroponically"],
      "aehhinopprstty" => ["hypnotherapist"],
      "cceeinooprsssu" => ["precociousness"],
      "eiiimnoprsssst" => ["impressionists"],
      "ceeeeinpprsstv" => ["perceptiveness"],
      "acdeeehinrrsuv" => ["underachievers"],
      "aiilmnooprssuy" => ["parsimoniously"],
      "acdeeilnpprrsu" => ["perpendiculars"],
      "deefgiimnrsstu" => ["disfigurements"],
      "aeeefillnprrty" => ["preferentially"],
      "ceiinnoorstttu" => ["reconstitution"],
      "acefgiiinnortt" => ["gentrification"],
      "emnnnoooossstu" => ["monotonousness"],
      "aghilnoooprstt" => ["anthropologist"],
      "aceeilmnopsttv" => ["contemplatives"],
      "aabcceelnnortu" => ["counterbalance"],
      "aaacehillmmtty" => ["mathematically"],
      "aeeilnnnoqstuv" => ["nonequivalents"],
      "aacilllnorstuy" => ["ultrasonically"],
      "aabfiillnpptuy" => ["unflappability"],
      "aacghhmooprrty" => ["chromatography"],
      "aeeiinnoqrsstu" => ["questionnaires"],
      "efinoorsssttuu" => ["fortuitousness"],
      "aadeeprrssttuu" => ["supersaturated"],
      "aaeeilnrrssttt" => ["transliterates"],
      "degiilnnossuuy" => ["disingenuously"],
      "aaccdimmnooost" => ["accommodations"],
      "ehiorrssttttuw" => ["trustworthiest"],
      "deiiinoopprsst" => ["predisposition"],
      "bdeeefginrrttu" => ["butterfingered"],
      "aaaehimoprrstt" => ["aromatherapist"],
      "ceeprrrssttuuu" => ["superstructure"],
      "abdeiiilnrstuy" => ["undesirability"],
      "aacdgiiinossst" => ["disassociating"],
      "aabddelnnrstuy" => ["understandably"],
      "abeehilmnssstt" => ["establishments"],
      "bcgiiilmooorst" => ["microbiologist"],
      "aeeiinnnoopttx" => ["exponentiation"],
      "deghhilorsstty" => ["shortsightedly"],
      "eeiinoprsssstx" => ["expressionists"],
      "aabcciiilprtty" => ["practicability"],
      "eegiilnnprrsty" => ["enterprisingly"],
      "adeeimnorssttv" => ["demonstratives"],
      "aaceeggilllnoy" => ["genealogically"],
      "aaabiiillntuvy" => ["unavailability"],
      "aadiiimnnorstt" => ["administration"],
      "deegiinnnprstu" => ["superintending"],
      "beiiilnoprssty" => ["responsibility"],
      "aabdeginorrstw" => ["waterboardings"],
      "adegiiinnorstt" => ["disorientating", "disintegration"],
      "aceiimmnoorsst" => ["commiserations"],
      "aaceeiinpprtuv" => ["unappreciative"],
      "afiillmorstuuy" => ["multifariously"],
      "ceggiinnnorstu" => ["countersigning"],
      "acdeehimnnnstt" => ["disenchantment"],
      "cllnoprssuuuuy" => ["unscrupulously"],
      "aegginoossttuu" => ["autosuggestion"],
      "aacceiinnorrst" => ["incarcerations"],
      "aaceilnnopsstu" => ["encapsulations"],
      "ceefiinoprsstt" => ["perfectionists"],
      "adeeiilnnnorst" => ["nonresidential"],
      "aceelmmnorstuy" => ["commensurately"],
      "cceilnorsttuvy" => ["constructively"],
      "aceeillllnttuy" => ["intellectually"],
      "aadeeiinorrrtx" => ["extraordinaire"],
      "befgillnooprtu" => ["bulletproofing"],
      "aeilnoopssttux" => ["expostulations"],
      "aacdiimnopssst" => ["antispasmodics"],
      "ccceeefimnrrsu" => ["circumferences"],
      "aacgillloorsty" => ["astrologically"],
      "eeilnnoprssuvy" => ["unresponsively"],
      "aabcehiloprrry" => ["irreproachably"],
      "aceggillnooort" => ["gerontological"],
      "acdeinnooprrtu" => ["unincorporated"],
      "aceeghiloprrsx" => ["lexicographers"],
      "abeilmnnorstuu" => ["insurmountable"],
      "adeeggimnnrrry" => ["gerrymandering"],
      "aeeiinnrsssttv" => ["transitiveness"],
      "aceggilmnnoort" => ["conglomerating"],
      "acefiiiinortvv" => ["revivification"],
      "aaeeiilmmnrsst" => ["immaterialness"],
      "aceimmmnooorst" => ["commemorations"],
      "aaccchlloopsty" => ["staphylococcal"],
      "bdeiiinorrsttu" => ["redistribution"],
      "acciimmnnoostu" => ["communications"],
      "dgiiiillnnossu" => ["disillusioning"],
      "acehinoorrsstt" => ["orchestrations"],
      "ceeeinoprssttv" => ["protectiveness"],
      "aceiinopssssuu" => ["auspiciousness"],
      "cdeekklnrsstuu" => ["knuckledusters"],
      "cdeeinnooprttu" => ["counterpointed"],
      "bceiiilnorttvy" => ["convertibility"],
      "aaacfiilllstty" => ["fatalistically"],
      "cciiijnnosttuv" => ["conjunctivitis"],
      "aaceeilmmnsstu" => ["immaculateness"],
      "bciimnoorssttu" => ["obstructionism"],
      "efghhinorrsstt" => ["forthrightness"],
      "aacdhimoosssst" => ["sadomasochists"],
      "acddeilnnoostu" => ["unconsolidated"],
      "bbceeiorrsssuv" => ["oversubscribes"],
      "abdeghinoorssu" => ["boardinghouses"],
      "eimnnooorsssuv" => ["omnivorousness"],
      "acceiiilnnoort" => ["reconciliation"],
      "aaceiillnrttuy" => ["inarticulately"],
      "abddeeefghinrt" => ["featherbedding"],
      "beehlooorrsttu" => ["troubleshooter"],
      "acfiiiilmnopst" => ["simplification"],
      "aaaefiilmprsst" => ["patresfamilias"],
      "cdeeegilnnoruv" => ["overindulgence"],
      "aacceeinnnorss" => ["reconnaissance"],
      "aacfiiinorsttt" => ["stratification"],
      "eiinooppprsstu" => ["presupposition"],
      "ccceiimnoprstu" => ["circumspection"],
      "aceeegmnnorstu" => ["encouragements"],
      "abeeiiilmmprty" => ["impermeability"],
      "acddeeimnosttu" => ["undomesticated"],
      "aabceilnorsstu" => ["constabularies"],
      "eeghilooprsstt" => ["herpetologists"],
      "adefiinosssstu" => ["fastidiousness"],
      "acdeeginoorrtv" => ["overdecorating"],
      "acciiillooopst" => ["sociopolitical"],
      "aacdiiiilnnprs" => ["disciplinarian"],
      "aabdeeefhinrrt" => ["featherbrained"],
      "aaeggilmnoorst" => ["agglomerations"],
      "accilmnoostuuy" => ["contumaciously"],
      "aacdeeginrrrsu" => ["undercarriages"],
      "eefghinnoorrst" => ["foreshortening"],
      "adeehhimoprrst" => ["hermaphrodites"],
      "aacfgiiinorstt" => ["gratifications"],
      "aadeiilmnnnoot" => ["denominational"],
      "adeeiimnnorstt" => ["determinations"],
      "aaaceennnopprs" => ["nonappearances"],
      "aceeeilnnnrstt" => ["tercentennials"],
      "acceenorsssuuv" => ["curvaceousness"],
      "eggilnooorsstt" => ["gerontologists"],
      "aciilnnoostttu" => ["constitutional"],
      "aaceehilrrtuvx" => ["extravehicular"],
      "eeflnopprsssuu" => ["purposefulness"],
      "aaiiiilmnrsttu" => ["utilitarianism"],
      "cgiimnnnooprsu" => ["mispronouncing"],
      "eiilnoqrssttuv" => ["ventriloquists"],
      "adgiilnopprsvy" => ["disapprovingly"],
      "ddeeeinnnnnopt" => ["nonindependent"],
      "bciinoorsstttu" => ["obstructionist"],
      "aaccehiilopprs" => ["archiepiscopal"],
      "aeggiiinnorrtv" => ["reinvigorating"],
      "aabeeelnnorsss" => ["reasonableness"],
      "aaeiinnpprrstt" => ["antiperspirant"],
      "aacehillmoprty" => ["metaphorically"],
      "aeegiiilllmtty" => ["illegitimately"],
      "aabeeeklmnrrss" => ["remarkableness"],
      "aacccehiirrstt" => ["characteristic"],
      "eennooprsssttu" => ["portentousness"],
      "ceiinooprssttt" => ["protectionists"],
      "cdeeiimmnoorss" => ["recommissioned"],
      "aaacdeeinpprss" => ["disappearances"],
      "aeeehilnpprsvy" => ["apprehensively"],
      "aciinnnooprstu" => ["pronunciations"],
      "cdeeimnnnosttt" => ["discontentment"],
      "cdeeeennpsstux" => ["unexpectedness"],
      "ceilnorrssssuu" => ["scurrilousness"],
      "adeeefimnnoort" => ["aforementioned"],
      "addeginnnrsstu" => ["understandings"],
      "adeefghinrssst" => ["farsightedness"],
      "aabceehiloprrr" => ["irreproachable"],
      "cceeilnoorsttu" => ["electrocutions"],
      "acdiiinnnoortt" => ["indoctrination"],
      "cceinnoorrsttu" => ["reconstruction"],
      "aaeegiimnrrrst" => ["intermarriages"],
      "aacgilnnoorttu" => ["congratulation"],
      "aaggiiilnnrtty" => ["ingratiatingly"],
      "aacdeilnnnootu" => ["noneducational"],
      "aceiillmnnooos" => ["neocolonialism"],
      "accdehilmnopsu" => ["unaccomplished"],
      "aeeiilnnqssttu" => ["quintessential"],
      "cegiiilnoorsst" => ["coreligionists"],
      "aciiillmopstty" => ["optimistically"],
      "efhlnnrssttuuu" => ["untruthfulness"],
      "acdiiimnorrsty" => ["discriminatory"],
      "aabdgiiimnostu" => ["disambiguation"],
      "adeeennpprrssu" => ["unpreparedness"],
      "adeeefhooprrtw" => ["weatherproofed"],
      "aeeeeinnprrttt" => ["interpenetrate"],
      "acdefiiiinnott" => ["identification"],
      "aaccgiillmnstu" => ["miscalculating"],
      "aaceeilnrssttu" => ["articulateness"],
      "acceeinoprsttv" => ["contraceptives"],
      "eeeggiinprrrst" => ["preregistering"],
      "aabiinnosstttu" => ["substantiation"],
      "aaeemqrrrssttu" => ["quartermasters"],
      "abeeimnosssstu" => ["abstemiousness"],
      "deefiilnnnrssu" => ["unfriendliness"],
      "aceeilnorstvvy" => ["conservatively"],
      "abddeeilmnnsty" => ["absentmindedly"],
      "aabeemmnrrssst" => ["embarrassments"],
      "aaaabcceelrstu" => ["baccalaureates"],
      "eeiilmnnrtttty" => ["intermittently"],
      "aaadiiilnnrttu" => ["latitudinarian"],
      "ceeiilnnossstu" => ["licentiousness"],
      "acceinnoorsttu" => ["counteractions"],
      "deeeeimnprrsst" => ["misrepresented"],
      "aaddeegnrrstuu" => ["undergraduates"],
      "aaeimnorsssttt" => ["stationmasters"],
      "adehilnnossstu" => ["outlandishness"],
      "acdgiiinnnortt" => ["indoctrinating"],
      "aaeeiimnnorstx" => ["reexaminations"],
      "accdeiinnnostu" => ["discontinuance"],
      "adehnorrssttww" => ["northwestwards"],
      "aaennnnoprrstt" => ["nontransparent"],
      "abddeehiilssst" => ["disestablished"],
      "ceegilloorsstt" => ["electrologists"],
      "aadffgiiiilnst" => ["disaffiliating"],
      "eeeghilnsssstw" => ["weightlessness"],
      "ceiilnoosssstu" => ["solicitousness"],
      "aabgiinnsstttu" => ["substantiating"],
      "abcceeiillnorr" => ["irreconcilable"],
      "deeeiimnprrstt" => ["misinterpreted"],
      "aeeghinnnnortt" => ["nonthreatening"],
      "celnoprssssuuu" => ["scrupulousness"],
      "aabcghiillopry" => ["biographically"],
      "aceilnooqsssuu" => ["loquaciousness"],
      "ccddeeilnnosty" => ["disconnectedly"],
      "aabdiinoopprst" => ["disapprobation"],
      "aacdegillmoort" => ["dermatological"],
      "acceghiillnnou" => ["hallucinogenic"],
      "aeefglnnrsstuu" => ["ungratefulness"],
      "ddeeghhinrstuw" => ["hundredweights"],
      "acdeginooprstt" => ["prognosticated"],
      "aaciilllrsttuy" => ["altruistically"],
      "aeegiiillnnstt" => ["intelligentsia"],
      "aceegillmooort" => ["meteorological"],
      "abcchilooprstu" => ["claustrophobic"],
      "eeeinopprssssv" => ["oppressiveness"],
      "cceimmooprrstu" => ["microcomputers"],
      "aachiillnnostu" => ["hallucinations"],
      "aaacgilnnosttu" => ["anticoagulants"],
      "ceiilloprssuuy" => ["superciliously"],
      "cceeeemmmnnort" => ["recommencement"],
      "acceilnnooprrs" => ["nonreciprocals"],
      "accilnnoorsttu" => ["constructional"],
      "aceiiimnnorrst" => ["recriminations"],
      "aeegiinnoprrst" => ["peregrinations"],
      "aeiiilorrrttty" => ["territoriality"],
      "aceegnoorsssuu" => ["courageousness"],
      "abccilnnnoosuy" => ["unconscionably"],
      "eehilloorssstt" => ["tortoiseshells"],
      "aaggiimnnrrstt" => ["transmigrating"],
      "abceeiilprstty" => ["respectability"],
      "aeilnoosstttuy" => ["ostentatiously"],
      "ccdeginnorsttu" => ["deconstructing"],
      "adiilopssttuuy" => ["disputatiously"],
      "eehiimmnoprstv" => ["impoverishment"],
      "deeeeimnprrrst" => ["predeterminers"],
      "bdeiiiilmqrsuu" => ["disequilibrium"],
      "acdfghiiinnrss" => ["disfranchising"],
      "egiiiinnoqrstu" => ["requisitioning"],
      "aabiiilnssttuy" => ["sustainability"],
      "eeginnoppssstt" => ["steppingstones"],
      "aaceillmssttyy" => ["systematically"],
      "aeeiiilnsstttx" => ["existentialist"],
      "eeeeilprrtttwy" => ["teletypewriter"],
      "achlnnoorssuyy" => ["asynchronously"],
      "aceeimnooprrst" => ["contemporaries"],
      "aceeiilmnopstx" => ["exceptionalism"],
      "aeeeimnnnrsttt" => ["entertainments"],
      "aceginnopsssuu" => ["pugnaciousness"],
      "ehhinoopssstty" => ["photosynthesis"],
      "aadefilmmnnstu" => ["fundamentalism"],
      "aaeiilnqtttuvy" => ["quantitatively"],
      "aaceiilnopprst" => ["reapplications"],
      "acdgiiiimnnrst" => ["discriminating"],
      "abeilnnoqstuuy" => ["unquestionably"],
      "cceeilnnosssuv" => ["conclusiveness"],
      "aacfiiilmnopst" => ["amplifications"],
      "aaefiimnnosstt" => ["manifestations"],
      "abbeghiiloprrs" => ["bibliographers"],
      "diinooopprrsst" => ["disproportions"],
      "adeeeiiimnrrst" => ["intermediaries"],
      "cegilnnpsstuuy" => ["unsuspectingly"],
      "aeeehllorstuxy" => ["heterosexually"],
      "abcelllnnoortu" => ["uncontrollable"],
      "cceilnnooprssu" => ["councilpersons"],
      "accdeeimmnotux" => ["excommunicated"],
      "giilnnprrssuuy" => ["unsurprisingly"],
      "aeeeinprssssuv" => ["persuasiveness"],
      "acehhillopttyy" => ["hypothetically"],
      "cceeinnnoostuv" => ["nonconsecutive"],
      "eeloopprrsstuy" => ["preposterously"],
      "aacggilnnorttu" => ["congratulating"],
      "eegiinnnprrstu" => ["unenterprising"],
      "ceeeinnnoorstv" => ["conventioneers"],
      "aefhiilnnoprty" => ["hyperinflation"],
      "aacceflnorttuu" => ["counterfactual"],
      "bceeeiimorrrsw" => ["microbreweries"],
      "acegiilnnortuv" => ["countervailing"],
      "acdfhiiiimnotu" => ["humidification"],
      "cegilmooossstt" => ["cosmetologists"],
      "abeeilnnoqstuu" => ["unquestionable"],
      "eeimoprssssstt" => ["postmistresses"],
      "aacceiiilprstt" => ["practicalities"],
      "aacddeilpqrtuu" => ["quadruplicated"],
      "acehhmmnrsstuy" => ["chrysanthemums"],
      "abdiiilnorsttu" => ["distributional"],
      "aacehillmpstyy" => ["metaphysically"],
      "aadgiiimnnrstt" => ["administrating"],
      "bcccgiiimnrrsu" => ["circumscribing"],
      "aceeinooprrrst" => ["reincorporates"],
      "aaeeegmnnprrrt" => ["prearrangement"],
      "aacghloopprsyy" => ["parapsychology"],
      "adeiillnoprtvy" => ["providentially"],
      "bccciimooprssu" => ["submicroscopic"]}
    |> Map.get(string_id)
  end

  def valid_ids do
    ["aaceilnrtttuvy", "aceeimmmnoottw", "cdeeinoprsstuv", "aceeinoprrsssu",
     "aeeiimnnorsttx", "adeeehilnooprt", "aacceillnorstu", "aceghilllnooty",
     "aceiillnnooost", "aadehnorrssttw", "acillmmnnootty", "aceeeglmnorstt",
     "abceeiiilrstvy", "aaceiillnpstty", "accehhillnoprs", "abeeghiilnstux",
     "adeiiinnoorstt", "agiillnoorsuvy", "aaciiilmnoppst", "aainnooprrsttt",
     "aeegiilnnnrtty", "eeeegggiinnnor", "ccdeeeinnnortt", "ceeiinnoprsssu",
     "aegghinnooprtv", "aeghimmnooprst", "cddeeilnnostty", "acdeegilnnoqru",
     "ceefgiinnorttu", "acegiillmnoort", "deegilmnnrsttu", "aaeeiilllrttvy",
     "eeeiilmnopssst", "elmopprsstuuuy", "aaaeglllmoprrs", "aceefmnnnooprr",
     "acceeilllopsty", "adefgiimnorrst", "aeegiilmnorsss", "ccdehhillnoors",
     "aeegginorrsssu", "aceeghilnorssu", "aaceghiloorsst", "adeeginnopprrt",
     "acegilmnnooort", "aabceillmorrty", "elnoopssstuuuv", "aceeghillnopry",
     "adeeehhllortwy", "abccginnorsttu", "aaceeeffhkklst", "eeeilnorrssstu",
     "aaeilmnrssstux", "ceeghinorrsttv", "abccnoorrssttu", "aacgillloottuy",
     "efhioopprrssss", "celmnoopsttuuy", "abdeeiilnnpsss", "aceghopprrrsty",
     "acegghhinooprr", "aaiillmnnosttu", "aceilnnnnootuv", "aabceeeghlnnss",
     "aacegiillllsty", "cceiimnnoopsst", "addeeeffiinrtt", "eehiilmnnqrstu",
     "acegilllmootyy", "acghiillnooort", "aaeiillmnptuvy", "aacillmopsttyy",
     "abdeefiiilnntu", "acfgiinnoorstu", "acghiiinopsstt", "aaaccillorttuy",
     "accefiiinopsst", "eeeeinprrssssv", "eehinnoorssttw", "ceeefgllnnsstu",
     "aacdiilllmopty", "aceehimmnorssv", "aaddegghnrrstu", "aacghillloopty",
     "ceeeioprrssttv", "acdeiinnoorsst", "abeeiilmnoprss", "beelooprrsstuy",
     "cceeeeeflnnort", "abdefiiillnort", "aabcillnooorst", "bcdeegiimnnrsu",
     "adeeghhoopprrt", "adeffgiinorsst", "ceeeilmnnopsst", "beeinooqssssuu",
     "aaceiinnnorrst", "aaeehiinorttwz", "aceeimmnnorstu", "acdhhiioprrsst",
     "aaccfiiilnorst", "aaghiilmnorstt", "accchloopsstuy", "aeeefghhirsttw",
     "ccdeeennooprrs", "aegiinnoopprrt", "aaeilnnnoooprt", "adeeggiinnprst",
     "adeeeimnrssttu", "aadeeinnprsstt", "ceeefinorrsttu", "acehilnorsssuv",
     "aadiiilmnorstt", "aceillnnoosstt", "aaabdeemrsssss", "bgiillmmnnoouu",
     "aacgilmnoopsst", "aaceehilllptty", "aeeilmorssttuv", "ccdegiimnnostu",
     "aachilnopsssyy", "aabcefiiinostt", "aeegiimnorsttv", "aaeiimoppprrst",
     "bhiiiinooprstt", "aceeiilnnnrstt", "aacdeeimnnostt", "abcceiillnorry",
     "aeginnorrsssst", "ceilmnnoorstuy", "aegiinnoorrstt", "acceeginnorrst",
     "bccdiiilnottuy", "aacdeiinnoortv", "dgghiiiinnsstu", "aadiiilnorsttt",
     "cceiillnnosuvy", "acchiilloprtyy", "aeeggiinorsstt", "aaacehillmnpru",
     "acceehhloorsst", "efghhlnossttuu", "cegiinnorstttu", "abcelnosstuuuy",
     "aachiilloprsty", "abceilnnnosttu", "aaeehimnrssstu", "aaeginnnprstuu",
     "ccgiilnnnnouvy", "aeefgilmnnnssu", "bdeiiilrsttuvy", "ehiiooppprrrst",
     "adddeeeghnorty", "eeeinnoprssssv", "aaabcehlnoppru", "acdeiiinorsssy",
     "abcinoooorrrst", "ceeefimnnorrst", "aadiimnorrsstt", "aaaeiiilmprrst",
     "aaaccehilmprtu", "cdeennooprrsst", "aadehiioprrstt", "aacllnnoprttuy",
     "aabdiiiilnstvy", "aaadeillqrrstu", "abdefiillorrst", "aabbefggilnrst",
     "abdeilmorstuxy", "bceeemmnorsssu", "cehhinoopsttty", "aceiilnoprstuy",
     "aaacehiimmnstt", "cceginnorrsttu", "aeegiinorrsttv", "aeeiimnoorsttv",
     "eghhinopprrtyy", "aacciilmnrsttu", "acilrrssstttuu", "acgiilrrssttuu",
     "aaimnnorsstttu", "adgiiiilmnntty", "beeiimnsssssuv", "bcdeiilnrsttuy",
     "aacdeeffgiinnt", "acefiiilmnostu", "aaabceiilnrstt", "acdeghillmooot",
     "aeeeggiorrssvv", "aeeiilmnnssttt", "ceeeimmmnoottw", "aaceiilnoprttu",
     "abdeeeeilnrsst", "abceiilnoprstu", "eeeiimnprssssv", "ceeeegiilnnort",
     "eeeellnnrsssst", "aacciiilmprtty", "ccdenooprrstuu", "aaadeiilnnrtuv",
     "aacillmnoprtyy", "bciiiloprrttuy", "aabeiiiillnnty", "ceeilmnopsssuv",
     "bdegiiinrrsttu", "acceillmnnoouy", "acgghiklnosstu", "aabddeelnnrstu",
     "aabeghiooprrtu", "acdiiimnorrsst", "bceeehilmnoprs", "eefgillnnorttu",
     "acginoooprrstt", "ceiilllnoosstv", "bceefiiilprtty", "aabcccghiknrst",
     "acdefiiinoottx", "adeeeggimnnsst", "cdeeeiiinnsssv", "ceehimmopsssty",
     "aaceilnnoorstv", "ahiimnoprssstt", "abeegiinrssssu", "aeeehinssstuvx",
     "aaaeeginnprstu", "deeiiiilmrstuv", "cceeinnoopprst", "aegiilnnnrstty",
     "beegiiilllnntu", "abilmnnorstuuy", "deeenoprrssuux", "cdeeiinrssssuv",
     "aeeiilmnnsttty", "aabehilnnnorst", "acgiimmnoorrss", "accefiiinorstt",
     "eeehiinprsstvy", "aceghillnoopty", "aadddeeehhnrss", "beeinoorsssstu",
     "aghhiiooprrsty", "giiinnooopprst", "aefillnooprssy", "aacfinorssttuy",
     "abcilmnorstuuy", "aaeilnoorstuvv", "aacchilllossty", "aciinnoprrsstt",
     "adiilnoprssttu", "aadeiiimnrsttv", "aceeinoorrsstv", "aacdhimooprtyy",
     "aaahiinorrsttu", "ceeeiimmoorrtt", "aaceeinnprrsst", "aaeeprrsssttuu",
     "eeinoopprsssss", "bdiiiiiilnstvy", "aabcdeginorrst", "aacegillloopty",
     "acdeeinooprrrt", "acceinoopprstu", "aaabcehilnoppr", "aaiimnoopprstx",
     "cceghiklnosttu", "aeiiilnnrsttvy", "aacgilllrrtuuy", "efggiiinnnprrt",
     "aaaiinnossssst", "beggiiilssttuy", "ddeehinnorrsuu", "ceeehimnoprssv",
     "ceeehmmopsssty", "aaceinoprrsstt", "aacfgiiimnnost", "aaceghilllmpty",
     "cceeeffiiiinns", "abcchhiioprrss", "aceeiilmnnrstt", "ceeilmnossstuu",
     "ceiiooprsssuuv", "aeeiiilmnssttx", "bdehiiloorrstt", "bbcdeeiorrssuv",
     "aiinnooprssstt", "acceegillnorty", "aabeehiiilrttv", "aeginorsssttuu",
     "cceeinorrsttuv", "accehilmmnopst", "abenoorrssstuu", "aadeeilnrrsttt",
     "cceelnorrttuuu", "ceiilnnnosstty", "cdeinoooprrtuv", "eegilnooprrvwy",
     "ccdeeeinopsssu", "aeeegginrssssv", "fghhiiinnoopst", "aaaccdilorrsuv",
     "acdeeghiinnruv", "aaeffiimnorrst", "aeeeeinprrsttv", "abdeggiknnorru",
     "bdeegiiillnsvy", "aeeikmrssssstt", "aabeghiiilnrtt", "beeinnoprssssu",
     "cceeeiinnnnosv", "addeimnnrssstu", "agiiilllmnntuy", "deeegilnooprvv",
     "acdeefhiinnrss", "adeeghhillrtty", "aceiiiilnpprst", "acceemnorrsstt",
     "aadffiiiilnost", "aaggiilnnosttu", "bceehilmnoprsy", "aaceklnnorstuy",
     "aacfgilnnoorst", "abciiilnrsttuy", "aiijnoopssttux", "aaceeinrsstttv",
     "acdiilnooorsst", "abeeilnnssttuu", "aacdeimnnnottu", "bdhiilloorstty",
     "eegilmooorsstt", "aaelmnooppsstu", "aeeiilmmnnoptt", "aceiiinopprstt",
     "aacehiinnotttu", "aabceehilnrsst", "bceeilnnnoortv", "ceemopprrsstuu",
     "chiilorrstttuu", "addeeeeghlmmrs", "deeefiiinnnsst", "abdeeeghinrsst",
     "acdeiiilnnortu", "aacdeiilnosttu", "acdegimnnnortu", "acghilllnooopy",
     "aceiiillmpttuv", "aacdgiiinnosst", "accdeeehhiknrt", "acceeimmnostux",
     "aaceghimnoprty", "ceeeefflnrstvy", "ccciilmnoortuu", "ceeiimnnoopttv",
     "aaiillnnorstty", "aadeeilmnorttt", "eilmnnoosssuuv", "aaailnnnorsstt",
     "aehimnnoorsssu", "addeeeghnorsty", "aadeiimnnorssv", "aehhiilnopprst",
     "abeeehlnrsssst", "aiiimnooprsstv", "ceeehimorsstty", "acccgiimnnrstu",
     "ddeiiiilmssstu", "adeggiiinnrstt", "ceeiilpprrstvy", "aaabellnnrsttu",
     "ccdeeefinnoorv", "eeeinopssssssv", "cddeeiinnooprt", "abcdeeehiilnpr",
     "aacdeiiilllsty", "aeeilnoortttxy", "deeeeghnnrrstt", "addeeehnnnopss",
     "aaceeffilnotty", "ceiiiinossttvv", "aehimoopppsstu", "aaeillllmrttuy",
     "aceginnoossstu", "aaceeimnnorstt", "aabcciilnottuy", "acceiinoprsssu",
     "ceemnnnooprstu", "addeeghhhinnss", "ceeegilnoprsst", "acdeeimmnnoort",
     "aacffiiilnosst", "abdeehiilsssst", "aeiinoopprrstx", "aeiilllrsttuvy",
     "bdgggiillmnnoy", "acefinrrrsttuu", "achiioprssstty", "aaccillnooptuy",
     "aafimnnoorrstt", "diiiinnoopssst", "aabdeeehhirrss", "aeeemnorsstttv",
     "aeehinpppprrsw", "accdeiillnnoty", "aaceiinoprrstv", "aceiiimmnoorss",
     "eeegiinnprrrtt", "abeelnnnorrstu", "aacdeinoprrstt", "accceimmnooors",
     "adeeilmorsttuv", "cdelmnnoooosty", "abdeeiilmnnrty", "cddeilnooostuy",
     "aeeghimoprrsss", "acddeegklnnouw", "ciinnooorssttt", "aaaegiiilmnrst",
     "aacdeeijkrsttt", "aeeehnoprrsstw", "aadehorsssttuw", "bceeilnoorrttv",
     "acdeeeiosssttv", "abeeilmnnnostu", "aadiilnnnoortt", "adeeehimrsssst",
     "aaacceghilloor", "aehiioorrssttt", "aaadeglnostuvy", "eiilnoorssttuv",
     "aabbeiillosssu", "abcceelllnnoot", "acfiilnnossttu", "bcdeeiilnrsttu",
     "cehinooprsssuy", "cgiiilmnoorsst", "acegiilnossttu", "cdeiiiilrsttuv",
     "aceghlnnnoooty", "aaeegilnprstxy", "aeillmnosstuuy", "cceimoooprrrss",
     "abeeeinorrrstv", "acdeeennopprrs", "aeeginooprrstu", "eiinnorsssttuu",
     "aacdeglmnnorss", "aaceghiinntttu", "acceeiinnoorss", "beeehillmmnsst",
     "aacdeillmopryy", "acfgiiiinnosst", "aceginnnoossuu", "abcdenooorrrtu",
     "aaacehimoopprs", "achiiinoopsstt", "aefiiiilmnnsst", "cdeiiinnnssstt",
     "aceeiilmmnnrst", "abcegiiloorstt", "ceeeiooprrttvv", "aacehlnopsssyy",
     "adehorsssttuww", "aceeemnorrstuu", "aciimmnnossttu", "abddeeehllnssu",
     "cceiinorssstuu", "cdeeiiinnsstvv", "aadeellmnprtty", "adeeiinnoprstt",
     "aeegooprrrstuy", "acdeegimnorstu", "acegiillorssuy", "aadeeghinqrrtu",
     "eefimnnoorrstw", "bcceeikkknorrs", "begilnorsssuuu", "aadeegimnnrrst",
     "acdeeeimnoppst", "ceeeflnprssstu", "ccdeiinnnoosst", "deeeeillmmosss",
     "cegiinnooprstu", "bdeeeilmmnostw", "aefgiimnorrsst", "adeeghilnnrrty",
     "ghiilnooorsstt", "aceeggimnnorrs", "acdiiiilnnnost", "aacceknorstttu",
     "ceiinoprsssstu", "cegiiknnnorstu", "aabceenrsssstt", "aaehiiimnnsstt",
     "ceefiinnossstu", "acfinnnooorstt", "acffiiinoorstt", "aabcghiiooprtu",
     "aceillnnnorsty", "ccefllnsssuuuy", "acceehilmoprst", "accdhhinooprsy",
     "aacchilnopstyy", "aeffhilnnsstuu", "aaelnoprsttuuy", "aaeilnooprsttx",
     "aeeeinnoprrstt", "beeeinrssssuvv", "aeeiilnnorrstt", "accceillnnorty",
     "aggiiilnnortvy", "acdeeenrrrstuy", "ceefinoorsssuv", "aaiinooppprrst",
     "aeiimnnooprsst", "cceeiinnossttu", "beeeimmnrrsstu", "abeeghiilnrsst",
     "abbeghiiiloprs", "deehhnorrsstuw", "aeegiimnnnortu", "acceinnnoorstt",
     "aaccegiimnrtuv", "aabcdeenrssstt", "acehiinnssttuu", "abdeeilmnnorst",
     "abclllnnoortuy", "aabcceeelnpsst", "acdehhiimoprrt", "eeeilnoprssssx",
     "aceeeeinnrrstt", "aabcdeennprsuu", "aabcefgiinprrt", "accinprssttuuu",
     "ceeinnosssstuu", "aaceeghnooprrs", "acdeehilmnosst", "adeeeffiinrstt",
     "ceeiilmorrstuy", "acfiiilnostttu", "aabcefiiinottu", "aeegiiilrrrstu",
     "aacinooprrrstt", "ceiiiillmpsttu", "ddeeeeinnnprtt", "abcdeeehilnpru",
     "aadeeghiloprrt", "aaabdhimoprsss", "adeeegoprrstuy", "aacghilmooprst",
     "acfgiilmnnnotu", "ceiinopprrsstu", "abbcdeilmoostu", "aabeilmnoprstu",
     "aabegiillnosuv", "ceeilllnoorstu", "aefillooprrssy", "cfimnnnooorsst",
     "aciiiilprssttu", "ccceeeiiinrstt", "addeeegoprrtuy", "aaccdeiinnortt",
     "aaciinnnopprtt", "acceiiilmnorst", "aeeeiinprrtttv", "eefiiilmoprssv",
     "deefiiilmoprsv", "adeiimnnoppstt", "aeeeiiinnprstt", "aeeiinnoprrttt",
     "aabdeiikmnorst", "aceillnnnootvy", "ciiilrsstttuuv", "ceeghinorsttuw",
     "dddeeeelnopruv", "acdeefinnoorst", "aaccdeiimnortt", "accefgiiiinnns",
     "aacehiillnttty", "aadeilnnortuuv", "ceilmooprrsstu", "acdeehiiinnrst",
     "aeeeillmnprtxy", "abcceilnnnoosu", "adeeeiilmnrtty", "abceeelnnoorrv",
     "aadefgghinnrrt", "ceeinnoorssssu", "ceeeglnoopprss", "aabchilooprstu",
     "aaabcehilllpty", "eehinnorssstww", "aabcefiinoprrt", "aachlnopssstyy",
     "ccdeeeiinnnnov", "aacglnoorrttuy", "aaciilllmorsty", "aabeiiilnprsty",
     "aeeehilnprttvy", "ceeiinnorrsttv", "beiiiilmprssty", "aacciillmnostu",
     "aillnooopprrty", "aaeiilnnossstt", "aeeeghlnoprrss", "aaeeilnnprrtty",
     "aabcfilnnoostu", "ccceeeilnnosss", "cdeeinnorsttuv", "aeeghhlorsstuu",
     "aacegghillopry", "behiiiinossttx", "afiiimmnnoorst", "adeeeimnrssttv",
     "abcdeeiilnnors", "aaeiilmnnossst", "acegilllnooruy", "beeeillnorsssu",
     "aabcdeeinrrstt", "eeefllnorrsttu", "aacghiillprsst", "aacdeelnnnrstt",
     "bccilnoosssuuy", "deegiiilmoopst", "accdeeinnnostu", "deeeelmnoprstv",
     "abcceiilmmnnou", "aacceghilloost", "acccehiinorstt", "acdeiiiimnnrst",
     "eeilmnnoosssst", "eehiinoopssttv", "aceehiinppprst", "eeegginsssstuv",
     "accdeeeelnoprs", "aceinnnooooprt", "acdiilnnooosst", "aceeghhooprrrs",
     "achiiillnorsty", "aaeiilnnnorstt", "aefimnnoorrstw", "accdeeilnnnsty",
     "aaciilnooprrst", "adeelnnopprrty", "aaaiiimnnqrstu", "aeilnooopprtuv",
     "adiiilnrsssttu", "adegilmoorsstt", "aaceegiillmnsv", "ceeegiinorrsvx",
     "aciiilnopssuuy", "acdeiijlnnopru", "acgiiilllnstuy", "acfgilnnnottuu",
     "aabehiiilnortt", "eeghillmnorvwy", "acehilmoprsstt", "adeiilnosttuvy",
     "cdeiinnoorrttu", "eeeeiinprssttv", "beefhimnrrsstu", "ccehhiinoprssz",
     "aacceinnnoostt", "aaceillmmrstyy", "aaeemnnopprsww", "abefllnoopsstu",
     "aaeeegmnnrrrst", "aeegillmnorrst", "ceiiimooprsttv", "adfiiimnnoorst",
     "aadefilmnnsttu", "aacfiiinnoqttu", "aegiiinnossttv", "aeillmnnrsttuy",
     "acdggiilnorsuy", "aefilnooprsssw", "aabegilmnrrssy", "aaceiloprrrtuv",
     "ccceiimmnooors", "aacddeeimnnott", "abegiiilmnprty", "aabhiiinpprsst",
     "aaellnprrstuuy", "aciiillmnopttu", "cgiimmnnooprsu", "addeeehimnpprs",
     "aeeiilmmnnsstt", "aceegillnoprtt", "cehilmoorsssst", "deeegiimnnprrt",
     "aaccfiiilnosst", "acfiiijnossttu", "acceehiiilnstt", "abcdeiiilprtty",
     "aabceeilllmmty", "aabeghiklnrtty", "ccdeimnoorsstu", "aefilnnooprssu",
     "acdiiijlnorstu", "aeeemnooprstux", "cdeiilnorsssuu", "bceiiilpssttuy",
     "aaaaghimnoprst", "aeeiiilnopsttt", "aeghiilnnsttuy", "accefiiillnsty",
     "aceehmnopprrst", "deimnooprssstt", "eeeiopprrrssst", "acceeinnoorrst",
     "acfiiijllnoost", "cddeeiimmnooss", "addeelnopprtuu", "adeeemnnrstttu",
     "ceffiiilnnstuy", "aaccfiiinnostt", "accdeeilmnortu", "bbciiilmosttuy",
     "cghhiiloosstty", "aadeinoppprrtu", "aaeelnnnpssstu", "abdeeeiilmnnrt",
     "aacceimmnnopst", "aeeghnooprrstv", "bbceilmnnoostu", "ceghnnooorssuy",
     "adgiilllnnotuy", "ceehnooprsssuy", "aceginooprsstt", "acdfiiiilnoost",
     "acceeilllnorty", "aacdiiinoossst", "aaccceeiillsst", "acefiimnnoorrt",
     "acdiiiimnnorst", "acdefiillnnoty", "aceeemnooprstv", "ceehhnoopprsst",
     "aaceiimmossttu", "aaabcelmmnnouw", "ddeeiilnorrsss", "eeghilnoprrstu",
     "ceeginooprrttv", "aagiimnnorrstt", "accegiilnrtuxy", "aaccdeillmorty",
     "accceeelnnossv", "aacfiilorsstty", "ccdeinnoorsttu", "aacfiiilnoqstu",
     "bdeiiorrrssttu", "cdeilnoprtuuvy", "cccilmoorrtuuy", "addeeeimnrsttu",
     "aacegiilnprttu", "acceeilorssttt", "aceiiiilmnpstu", "cegiinnnnooort",
     "abiiiillmpstuy", "acefiiilprstuy", "aceiilnossssuv", "aabfiiillmmnty",
     "aciiilllmpssty", "addeeeimnprttu", "defgiiiimnnsty", "aeeinoqrsssttu",
     "aacehiillmrtty", "aceeelmnoprtux", "abceeeefnrssst", "adeimnnoorsstt",
     "cdegiiinnnoort", "deeegknoprrssu", "aaceeiilpprtvy", "aciilllmooqssu",
     "aacillmnoorsty", "aacehiiimnrstt", "abceeeflnnnoor", "bdeehlooorsttu",
     "aaceggilnnoort", "aceiilnnopssst", "acdeillnoossty", "ceiijnooprsstt",
     "aaeinnnoprstuu", "aabciiilnrttty", "ceegnnooprrsss", "acceilmmnnoors",
     "ceeeehlnpsssss", "eeimnorsssstuy", "abeeeikkrrrsst", "eeeeinprssssvx",
     "acdehimmnorsty", "aaaddggiinnstv", "aabcegiknqrrtu", "aaaccgiiinnptt",
     "aegilnoopprtuv", "acefhhiiinpsst", "ceehimnnooprss", "abeegiikknrrst",
     "ddeeeimnnnortu", "aeeemnnopprsww", "aacdeeimnnortt", "addiiiilnsstuv",
     "aabceelmmnnouw", "accgiilllooosy", "accdiinnoorstt", "aefilmnoorrstu",
     "beeegillnnnort", "eeefflnorsssst", "aacdeilpqrstuu", "dhhiimooprstyy",
     "aacdgiillnosty", "aceinnnoorsttv", "cdeiloorsstuuy", "aaccennorsssst",
     "aeeegillnssttv", "aeiilnnooprstt", "aacdeiilnorstv", "ceeiilnnnnotvy",
     "ddeeiijnnossst", "ceginrrrssttuu", "acgiillmoosstt", "begiiilllnntuy",
     "ahhiilnopprstt", "aaccehhiillrry", "deeeinnnprsttu", "acdhillnoopryy",
     "aehhinopprstty", "cceeinooprsssu", "eiiimnoprsssst", "ceeeeinpprsstv",
     "acdeeehinrrsuv", "aiilmnooprssuy", "acdeeilnpprrsu", "deefgiimnrsstu",
     "aeeefillnprrty", "ceiinnoorstttu", "acefgiiinnortt", "emnnnoooossstu",
     "aghilnoooprstt", "aceeilmnopsttv", "aabcceelnnortu", "aaacehillmmtty",
     "aeeilnnnoqstuv", "aacilllnorstuy", "aabfiillnpptuy", "aacghhmooprrty",
     "aeeiinnoqrsstu", "efinoorsssttuu", "aadeeprrssttuu", "aaeeilnrrssttt",
     "degiilnnossuuy", "aaccdimmnooost", "ehiorrssttttuw", "deiiinoopprsst",
     "bdeeefginrrttu", "aaaehimoprrstt", "ceeprrrssttuuu", "abdeiiilnrstuy",
     "aacdgiiinossst", "aabddelnnrstuy", "abeehilmnssstt", "bcgiiilmooorst",
     "aeeiinnnoopttx", "deghhilorsstty", "eeiinoprsssstx", "aabcciiilprtty",
     "eegiilnnprrsty", "adeeimnorssttv", "aaceeggilllnoy", "aaabiiillntuvy",
     "aadiiimnnorstt", "deegiinnnprstu", "beiiilnoprssty", "aabdeginorrstw",
     "adegiiinnorstt", "aceiimmnoorsst", "aaceeiinpprtuv", "afiillmorstuuy",
     "ceggiinnnorstu", "acdeehimnnnstt", "cllnoprssuuuuy", "aegginoossttuu",
     "aacceiinnorrst", "aaceilnnopsstu", "ceefiinoprsstt", "adeeiilnnnorst",
     "aceelmmnorstuy", "cceilnorsttuvy", "aceeillllnttuy", "aadeeiinorrrtx",
     "befgillnooprtu", "aeilnoopssttux", "aacdiimnopssst", "ccceeefimnrrsu",
     "aacgillloorsty", "eeilnnoprssuvy", "aabcehiloprrry", "aceggillnooort",
     "acdeinnooprrtu", "aceeghiloprrsx", "abeilmnnorstuu", "adeeggimnnrrry",
     "aeeiinnrsssttv", "aceggilmnnoort", "acefiiiinortvv", "aaeeiilmmnrsst",
     "aceimmmnooorst", "aaccchlloopsty", "bdeiiinorrsttu", "acciimmnnoostu",
     "dgiiiillnnossu", "acehinoorrsstt", "ceeeinoprssttv", "aceiinopssssuu",
     "cdeekklnrsstuu", "cdeeinnooprttu", "bceiiilnorttvy", "aaacfiilllstty",
     "cciiijnnosttuv", "aaceeilmmnsstu", "bciimnoorssttu", "efghhinorrsstt",
     "aacdhimoosssst", "acddeilnnoostu", "bbceeiorrsssuv", "abdeghinoorssu",
     "eimnnooorsssuv", "acceiiilnnoort", "aaceiillnrttuy", "abddeeefghinrt",
     "beehlooorrsttu", "acfiiiilmnopst", "aaaefiilmprsst", "cdeeegilnnoruv",
     "aacceeinnnorss", "aacfiiinorsttt", "eiinooppprsstu", "ccceiimnoprstu",
     "aceeegmnnorstu", "abeeiiilmmprty", "acddeeimnosttu", "aabceilnorsstu",
     "eeghilooprsstt", "adefiinosssstu", "acdeeginoorrtv", "acciiillooopst",
     "aacdiiiilnnprs", "aabdeeefhinrrt", "aaeggilmnoorst", "accilmnoostuuy",
     "aacdeeginrrrsu", "eefghinnoorrst", "adeehhimoprrst", "aacfgiiinorstt",
     "aadeiilmnnnoot", "adeeiimnnorstt", "aaaceennnopprs", "aceeeilnnnrstt",
     "acceenorsssuuv", "eggilnooorsstt", "aciilnnoostttu", "aaceehilrrtuvx",
     "eeflnopprsssuu", "aaiiiilmnrsttu", "cgiimnnnooprsu", "eiilnoqrssttuv",
     "adgiilnopprsvy", "ddeeeinnnnnopt", "bciinoorsstttu", "aaccehiilopprs",
     "aeggiiinnorrtv", "aabeeelnnorsss", "aaeiinnpprrstt", "aacehillmoprty",
     "aeegiiilllmtty", "aabeeeklmnrrss", "aacccehiirrstt", "eennooprsssttu",
     "ceiinooprssttt", "cdeeiimmnoorss", "aaacdeeinpprss", "aeeehilnpprsvy",
     "aciinnnooprstu", "cdeeimnnnosttt", "cdeeeennpsstux", "ceilnorrssssuu",
     "adeeefimnnoort", "addeginnnrsstu", "adeefghinrssst", "aabceehiloprrr",
     "cceeilnoorsttu", "acdiiinnnoortt", "cceinnoorrsttu", "aaeegiimnrrrst",
     "aacgilnnoorttu", "aaggiiilnnrtty", "aacdeilnnnootu", "aceiillmnnooos",
     "accdehilmnopsu", "aeeiilnnqssttu", "cegiiilnoorsst", "aciiillmopstty",
     "efhlnnrssttuuu", "acdiiimnorrsty", "aabdgiiimnostu", "adeeennpprrssu",
     "adeeefhooprrtw", "aeeeeinnprrttt", "acdefiiiinnott", "aaccgiillmnstu",
     "aaceeilnrssttu", "acceeinoprsttv", "eeeggiinprrrst", "aabiinnosstttu",
     "aaeemqrrrssttu", "abeeimnosssstu", "deefiilnnnrssu", "aceeilnorstvvy",
     "abddeeilmnnsty", "aabeemmnrrssst", "aaaabcceelrstu", "eeiilmnnrtttty",
     "aaadiiilnnrttu", "ceeiilnnossstu", "acceinnoorsttu", "deeeeimnprrsst",
     "aaddeegnrrstuu", "aaeimnorsssttt", "adehilnnossstu", "acdgiiinnnortt",
     "aaeeiimnnorstx", "accdeiinnnostu", "adehnorrssttww", "aaennnnoprrstt",
     "abddeehiilssst", "ceegilloorsstt", "aadffgiiiilnst", "eeeghilnsssstw",
     "ceiilnoosssstu", "aabgiinnsstttu", "abcceeiillnorr", "deeeiimnprrstt",
     "aeeghinnnnortt", "celnoprssssuuu", "aabcghiillopry", "aceilnooqsssuu",
     "ccddeeilnnosty", "aabdiinoopprst", "aacdegillmoort", "acceghiillnnou",
     "aeefglnnrsstuu", "ddeeghhinrstuw", "acdeginooprstt", "aaciilllrsttuy",
     "aeegiiillnnstt", "aceegillmooort", "abcchilooprstu", "eeeinopprssssv",
     "cceimmooprrstu", "aachiillnnostu", "aaacgilnnosttu", "ceiilloprssuuy",
     "cceeeemmmnnort", "acceilnnooprrs", "accilnnoorsttu", "aceiiimnnorrst",
     "aeegiinnoprrst", "aeiiilorrrttty", "aceegnoorsssuu", "abccilnnnoosuy",
     "eehilloorssstt", "aaggiimnnrrstt", "abceeiilprstty", "aeilnoosstttuy",
     "ccdeginnorsttu", "adiilopssttuuy", "eehiimmnoprstv", "deeeeimnprrrst",
     "bdeiiiilmqrsuu", "acdfghiiinnrss", "egiiiinnoqrstu", "aabiiilnssttuy",
     "eeginnoppssstt", "aaceillmssttyy", "aeeiiilnsstttx", "eeeeilprrtttwy",
     "achlnnoorssuyy", "aceeimnooprrst", "aceeiilmnopstx", "aeeeimnnnrsttt",
     "aceginnopsssuu", "ehhinoopssstty", "aadefilmmnnstu", "aaeiilnqtttuvy",
     "aaceiilnopprst", "acdgiiiimnnrst", "abeilnnoqstuuy", "cceeilnnosssuv",
     "aacfiiilmnopst", "aaefiimnnosstt", "abbeghiiloprrs", "diinooopprrsst",
     "adeeeiiimnrrst", "cegilnnpsstuuy", "aeeehllorstuxy", "abcelllnnoortu",
     "cceilnnooprssu", "accdeeimmnotux", "giilnnprrssuuy", "aeeeinprssssuv",
     "acehhillopttyy", "cceeinnnoostuv", "eeloopprrsstuy", "aacggilnnorttu",
     "eegiinnnprrstu", "ceeeinnnoorstv", "aefhiilnnoprty", "aacceflnorttuu",
     "bceeeiimorrrsw", "acegiilnnortuv", "acdfhiiiimnotu", "cegilmooossstt",
     "abeeilnnoqstuu", "eeimoprssssstt", "aacceiiilprstt", "aacddeilpqrtuu",
     "acehhmmnrsstuy", "abdiiilnorsttu", "aacehillmpstyy", "aadgiiimnnrstt",
     "bcccgiiimnrrsu", "aceeinooprrrst", "aaeeegmnnprrrt", "aacghloopprsyy",
     "adeiillnoprtvy", "bccciimooprssu"]
    |> Enum.into(HashSet.new)
  end
end
