defmodule Jumble.ScowlDict.Size60.Length16 do
  def get(string_id) do
    %{"aeeghiilnnprttvy" => ["hyperventilating"],
      "deehimnnnorrstuu" => ["undernourishment"],
      "aceeiilnnnnorttt" => ["intercontinental"],
      "adeeiimnnorssttu" => ["underestimations"],
      "aacehillmorsttty" => ["thermostatically"],
      "acdefiiiimnnnost" => ["indemnifications"],
      "cdeegiillnooostu" => ["oligonucleotides"],
      "acdeeeehimnnrtuv" => ["underachievement"],
      "bceehiilmnnoprsy" => ["incomprehensibly"],
      "acdeeiilnpprrtuy" => ["perpendicularity"],
      "ceehilmoorssssst" => ["schoolmistresses"],
      "aceeeiilnnnqsstu" => ["sesquicentennial"],
      "aaeeeilrrrrstttx" => ["extraterrestrial"],
      "cciinnoorssstttu" => ["constructionists"],
      "eeeinnnoprssssuv" => ["unresponsiveness"],
      "aaeeeilnnoprrstt" => ["representational"],
      "aeeeiinnoprrrttt" => ["reinterpretation"],
      "aeeimnnorrrstttu" => ["neurotransmitter"],
      "aaaacghilmnoprst" => ["phantasmagorical"],
      "aabiiilnnnnotttu" => ["tintinnabulation"],
      "abeiiiiillmpsstu" => ["implausibilities"],
      "aabeeelnnnorsssu" => ["unreasonableness"],
      "aaccdgiiinnnortt" => ["contraindicating"],
      "aaacchilloprstty" => ["catastrophically"],
      "ccddeeeinnnossst" => ["disconnectedness"],
      "cciimnnoorsssttu" => ["misconstructions"],
      "cceeiilnnnosssuv" => ["inconclusiveness"],
      "aacghhillooprrty" => ["orthographically"],
      "accdegiinnnnostu" => ["discountenancing"],
      "bceiilnnoorrttvy" => ["incontrovertibly"],
      "abeeghiiilnnstux" => ["inextinguishable"],
      "aacghhiillloprty" => ["lithographically"],
      "abceimnnorssstuu" => ["rambunctiousness"],
      "aacccehiinrrsttu" => ["uncharacteristic"],
      "ddeeeelmnnoprtuv" => ["underdevelopment"],
      "aefilnnnoooprsss" => ["nonprofessionals"],
      "eeeehinnpprrrstu" => ["entrepreneurship"],
      "aadeiiilmnrsttvy" => ["administratively"],
      "aeeiinoprrsssttv" => ["preservationists"],
      "aaeiiilnnnorsttt" => ["internationalist"],
      "aaaaeiilmnnprrst" => ["parliamentarians"],
      "ccceeiilmnoorrst" => ["microelectronics"],
      "acdgiiiimnnnrstu" => ["undiscriminating"],
      "bceeiiiilpsssttu" => ["susceptibilities"],
      "aefillnnooprssuy" => ["unprofessionally"],
      "aeeegiinnnprrttt" => ["interpenetrating"],
      "aacciillmnrsttuy" => ["circumstantially"],
      "accefiiillnnstuy" => ["unscientifically"],
      "aeeiillnnqssttuy" => ["quintessentially"],
      "aaacdeilllmmorty" => ["melodramatically"],
      "abbcdgiilmnoostu" => ["discombobulating"],
      "acehhiopprssstty" => ["psychotherapists"],
      "aceefiiilmnopstx" => ["exemplifications"],
      "aaceilnnnnorsttt" => ["transcontinental"],
      "adeeegiknnprrrst" => ["prekindergartens"],
      "adeiinooopprrstt" => ["disproportionate"],
      "ahhmnoooopprrstu" => ["anthropomorphous"],
      "accegiinnnooprrt" => ["nonreciprocating"],
      "bbbbeefgiiilrstt" => ["flibbertigibbets"],
      "cdeehiinorrssttw" => ["creditworthiness"],
      "ahijlnoooprssttu" => ["photojournalists"],
      "eeiiinnnorsstttv" => ["interventionists"],
      "abcdeiiilnprttuy" => ["unpredictability"],
      "aacfiilnorssttuy" => ["unsatisfactorily"],
      "aceeilmmnnorstuy" => ["incommensurately"],
      "deeflnooprsssstu" => ["dessertspoonfuls"],
      "aceeginnorrsttuu" => ["countersignature"],
      "bcceinnoosssssuu" => ["subconsciousness"],
      "ceeiilnoprssssuu" => ["superciliousness"],
      "aaccefiiilnorsst" => ["reclassification"],
      "ceeeiimnorrssstu" => ["meretriciousness"],
      "abefilnooprssssu" => ["subprofessionals"],
      "aaacehilllmnpruy" => ["alphanumerically"],
      "aaaccehiinnpqstu" => ["acquaintanceship"],
      "aaceeiilnnrssttu" => ["inarticulateness"],
      "aaceiilllrrsstuy" => ["surrealistically"],
      "adeeeghhilnrsstt" => ["lightheartedness"],
      "aceeeinnoorsstvv" => ["neoconservatives"],
      "aehhiiopprssstty" => ["physiotherapists"],
      "bdehiilnoorssstt" => ["bloodthirstiness"],
      "aabbddegiiilorty" => ["biodegradability"],
      "achiillorrstttuu" => ["horticulturalist"],
      "bciiiilnoprrttuy" => ["incorruptibility"],
      "aeeeiinnnoprrttt" => ["interpenetration"],
      "addeeeffiinnrttu" => ["undifferentiated"],
      "aaiiimnooppprrst" => ["misappropriation"],
      "cceeeefgilnnnort" => ["teleconferencing"],
      "aaacchillnopstyy" => ["psychoanalytical"],
      "acefiiinnooprsst" => ["personifications"],
      "aaccegiknnortttu" => ["counterattacking"],
      "aaceghhillnoprty" => ["ethnographically"],
      "aacghhilloopprty" => ["photographically"],
      "cceeinnorsssttuv" => ["constructiveness"],
      "aciilnnnoostttuu" => ["unconstitutional"],
      "abceiiilnnosttty" => ["incontestability"],
      "adeeeehhlnorsstw" => ["wholeheartedness"],
      "aceegmnnorrsttuu" => ["counterarguments"],
      "ahhimmnooopprrst" => ["anthropomorphism"],
      "aaceeghimnoprrst" => ["cinematographers"],
      "aeeelmnooprstuxy" => ["extemporaneously"],
      "aeeghiinpprrsttw" => ["weatherstripping"],
      "aaeiilnnorrssttt" => ["transliterations"],
      "aacehiillnssttuy" => ["enthusiastically"],
      "aabciillnooorstt" => ["collaborationist"],
      "aaceillnnoorstvy" => ["conversationally"],
      "acgiinnoooprsstt" => ["prognostications"],
      "cdelmnnooooostuy" => ["monocotyledonous"],
      "aaccdefiiilnosst" => ["declassification"],
      "acdeeeeinrrrsstu" => ["undersecretaries"],
      "aaccggiiimnnrtuv" => ["circumnavigating"],
      "ddeeeeennprrrstu" => ["underrepresented"],
      "aachiillmnoprsty" => ["misanthropically"],
      "aeehiinoprrssstw" => ["praiseworthiness"],
      "adegiiiinoprsttt" => ["prestidigitation"],
      "aceeiiloorrrssst" => ["arteriosclerosis"],
      "acdeghilllmoooty" => ["methodologically"],
      "ceiiinnorrsssttu" => ["insurrectionists"],
      "aceeimnnoooprstv" => ["overcompensation"],
      "bceeiilnnoorrttv" => ["incontrovertible"],
      "aaabcghiilooprtu" => ["autobiographical"],
      "abdeehiilmnssstt" => ["disestablishment"],
      "acceeiimmnnorttu" => ["intercommunicate"],
      "aaacgiillnnostty" => ["antagonistically"],
      "cceeiinnnnoorstt" => ["interconnections"],
      "aaacciillorrstty" => ["aristocratically"],
      "ceeeffinnoorstuv" => ["counteroffensive"],
      "acciiimmmnnoostu" => ["miscommunication"],
      "acceiimmnnoostux" => ["excommunications"],
      "aceilnnnooorrstv" => ["noncontroversial"],
      "aaaacdgiillmmrty" => ["diagrammatically"],
      "aaceeknnnorssstu" => ["cantankerousness"],
      "aeeeehinnpprsssv" => ["apprehensiveness"],
      "aacgiillrrssttuu" => ["agriculturalists"],
      "ccceeiklnoorstuw" => ["counterclockwise"],
      "aceiinnoorsssttv" => ["conservationists"],
      "acdeiiiilmnnrsty" => ["indiscriminately"],
      "celnnoprssssuuuu" => ["unscrupulousness"],
      "addegiimnnnrsstu" => ["misunderstanding"],
      "aghhillmooopsstt" => ["ophthalmologists"],
      "aaciillnooprrsty" => ["conspiratorially"],
      "aaeeiilorrrrtttx" => ["extraterritorial"],
      "aaegiilnnorssttt" => ["gastrointestinal"],
      "aceehiinorssttuv" => ["overenthusiastic"],
      "aaaefilnoopprrss" => ["paraprofessional"],
      "aabdeeeegilnrsss" => ["disagreeableness"],
      "ccdeehiilorrttyy" => ["hydroelectricity"],
      "eemnopprsssstuuu" => ["presumptuousness"],
      "ccciiimnoprrsstu" => ["circumscriptions"],
      "abcceiiiilnnotvy" => ["inconceivability"],
      "aeiilmnnrssstttu" => ["instrumentalists"],
      "aabccegilnnnortu" => ["counterbalancing"],
      "aaaacchhillmsttw" => ["whatchamacallits"],
      "aaccghilloprrsty" => ["crystallographic"],
      "ccdeefiiimmnnouy" => ["immunodeficiency"],
      "ddeeeeilnnnprtty" => ["interdependently"],
      "aefiilmnorssstuu" => ["multifariousness"],
      "aceeeginnooprstu" => ["counterespionage"],
      "aceeegilmmnorstt" => ["electromagnetism"],
      "aeefiilmnooprsss" => ["semiprofessional"],
      "aaahiiimnorrsttu" => ["authoritarianism"],
      "aeehiimnnopprsss" => ["misapprehensions"],
      "aaabcceillrrtuuy" => ["bureaucratically"],
      "bdhiiioprrsssttu" => ["distributorships"],
      "aeeiilmnnnorsttv" => ["environmentalist"],
      "cdegiilnnooorsst" => ["endocrinologists"],
      "ceemnnoopsssttuu" => ["contemptuousness"],
      "aaccgiiimnnortuv" => ["circumnavigation"],
      "acdiiinnnoossttu" => ["discontinuations"],
      "eehiiinprssttvyy" => ["hypersensitivity"],
      "cgiilmmnnooprsuy" => ["uncompromisingly"],
      "aceeilllnnnosttu" => ["nonintellectuals"],
      "eeeillnoprssssxy" => ["expressionlessly"],
      "aadfghiorrrssttw" => ["straightforwards"],
      "beiiiilnoprrssty" => ["irresponsibility"],
      "abbeiiilmprrttuy" => ["imperturbability"],
      "aaacciiilllpstty" => ["capitalistically"],
      "aceegimnnooprstv" => ["overcompensating"],
      "acdeefhiimnnrsst" => ["disfranchisement"],
      "aceillnnnnootuvy" => ["unconventionally"],
      "aeghhiiooprrrsst" => ["historiographers"],
      "aaacceghillloory" => ["archaeologically"],
      "aaccdiiinnnoortt" => ["contraindication"],
      "aabcciiiilmprtty" => ["impracticability"],
      "aacghiloopprssty" => ["parapsychologist"],
      "aacchiiillnstuvy" => ["chauvinistically"],
      "abbcdiilmnooostu" => ["discombobulation"],
      "acdefghiiinnnrss" => ["disenfranchising"],
      "aaacehimpprsstty" => ["parasympathetics"],
      "eeghinooppstttty" => ["phototypesetting"],
      "aciillnnoostttuy" => ["constitutionally"],
      "bceeiiiilmpprtty" => ["imperceptibility"],
      "aeeiilmmnnnorstv" => ["environmentalism"],
      "aacghillnoopprry" => ["pornographically"],
      "aacdeellnnnrstty" => ["transcendentally"],
      "aaccceeiilllssty" => ["ecclesiastically"],
      "deeghhinorsssstt" => ["shortsightedness"],
      "aeeeeinnprrsttuv" => ["unrepresentative"],
      "aaeiiilmnnnorstt" => ["internationalism"],
      "aceeghillmnnooop" => ["phenomenological"],
      "bceeehiilmnnoprs" => ["incomprehensible"],
      "aefiilnnnoooprrt" => ["nonproliferation"],
      "aciilllmmrsttuuu" => ["multiculturalism"],
      "aeehiilnnoprttvy" => ["hyperventilation"],
      "abddeeeimnnnssst" => ["absentmindedness"],
      "abcceghiillnooot" => ["biotechnological"],
      "adeiiillmmnnostu" => ["multidimensional"],
      "acceeehhimoprttu" => ["chemotherapeutic"],
      "ceehhlnoopprssty" => ["phosphorescently"],
      "cdeeghimnnnnoopr" => ["noncomprehending"],
      "aeiiiilllmmnortu" => ["multimillionaire"],
      "aacgiiinnnopprtt" => ["nonparticipating"],
      "aagiiimnoppprrst" => ["misappropriating"],
      "aacdfiiiilnoqstu" => ["disqualification"],
      "acegiilllmnoorty" => ["terminologically"],
      "aabiiinnoorssttt" => ["antiabortionists"],
      "abdeiiiilnnpssty" => ["indispensability"],
      "beeehiiilnprrsty" => ["reprehensibility"],
      "beeiiiilnoprssst" => ["responsibilities"],
      "beeenooprrsssstu" => ["obstreperousness"],
      "aciiimnnnooprstu" => ["mispronunciation"],
      "adeeeiimnnoprrtt" => ["predetermination"]}
    |> Map.get(string_id)
  end

  def valid_ids do
    ["aeeghiilnnprttvy", "deehimnnnorrstuu", "aceeiilnnnnorttt", "adeeiimnnorssttu",
     "aacehillmorsttty", "acdefiiiimnnnost", "cdeegiillnooostu", "acdeeeehimnnrtuv",
     "bceehiilmnnoprsy", "acdeeiilnpprrtuy", "ceehilmoorssssst", "aceeeiilnnnqsstu",
     "aaeeeilrrrrstttx", "cciinnoorssstttu", "eeeinnnoprssssuv", "aaeeeilnnoprrstt",
     "aeeeiinnoprrrttt", "aeeimnnorrrstttu", "aaaacghilmnoprst", "aabiiilnnnnotttu",
     "abeiiiiillmpsstu", "aabeeelnnnorsssu", "aaccdgiiinnnortt", "aaacchilloprstty",
     "ccddeeeinnnossst", "cciimnnoorsssttu", "cceeiilnnnosssuv", "aacghhillooprrty",
     "accdegiinnnnostu", "bceiilnnoorrttvy", "abeeghiiilnnstux", "aacghhiillloprty",
     "abceimnnorssstuu", "aacccehiinrrsttu", "ddeeeelmnnoprtuv", "aefilnnnoooprsss",
     "eeeehinnpprrrstu", "aadeiiilmnrsttvy", "aeeiinoprrsssttv", "aaeiiilnnnorsttt",
     "aaaaeiilmnnprrst", "ccceeiilmnoorrst", "acdgiiiimnnnrstu", "bceeiiiilpsssttu",
     "aefillnnooprssuy", "aeeegiinnnprrttt", "aacciillmnrsttuy", "accefiiillnnstuy",
     "aeeiillnnqssttuy", "aaacdeilllmmorty", "abbcdgiilmnoostu", "acehhiopprssstty",
     "aceefiiilmnopstx", "aaceilnnnnorsttt", "adeeegiknnprrrst", "adeiinooopprrstt",
     "ahhmnoooopprrstu", "accegiinnnooprrt", "bbbbeefgiiilrstt", "cdeehiinorrssttw",
     "ahijlnoooprssttu", "eeiiinnnorsstttv", "abcdeiiilnprttuy", "aacfiilnorssttuy",
     "aceeilmmnnorstuy", "deeflnooprsssstu", "aceeginnorrsttuu", "bcceinnoosssssuu",
     "ceeiilnoprssssuu", "aaccefiiilnorsst", "ceeeiimnorrssstu", "abefilnooprssssu",
     "aaacehilllmnpruy", "aaaccehiinnpqstu", "aaceeiilnnrssttu", "aaceiilllrrsstuy",
     "adeeeghhilnrsstt", "aceeeinnoorsstvv", "aehhiiopprssstty", "bdehiilnoorssstt",
     "aabbddegiiilorty", "achiillorrstttuu", "bciiiilnoprrttuy", "aeeeiinnnoprrttt",
     "addeeeffiinnrttu", "aaiiimnooppprrst", "cceeeefgilnnnort", "aaacchillnopstyy",
     "acefiiinnooprsst", "aaccegiknnortttu", "aaceghhillnoprty", "aacghhilloopprty",
     "cceeinnorsssttuv", "aciilnnnoostttuu", "abceiiilnnosttty", "adeeeehhlnorsstw",
     "aceegmnnorrsttuu", "ahhimmnooopprrst", "aaceeghimnoprrst", "aeeelmnooprstuxy",
     "aeeghiinpprrsttw", "aaeiilnnorrssttt", "aacehiillnssttuy", "aabciillnooorstt",
     "aaceillnnoorstvy", "acgiinnoooprsstt", "cdelmnnooooostuy", "aaccdefiiilnosst",
     "acdeeeeinrrrsstu", "aaccggiiimnnrtuv", "ddeeeeennprrrstu", "aachiillmnoprsty",
     "aeehiinoprrssstw", "adegiiiinoprsttt", "aceeiiloorrrssst", "acdeghilllmoooty",
     "ceiiinnorrsssttu", "aceeimnnoooprstv", "bceeiilnnoorrttv", "aaabcghiilooprtu",
     "abdeehiilmnssstt", "acceeiimmnnorttu", "aaacgiillnnostty", "cceeiinnnnoorstt",
     "aaacciillorrstty", "ceeeffinnoorstuv", "acciiimmmnnoostu", "acceiimmnnoostux",
     "aceilnnnooorrstv", "aaaacdgiillmmrty", "aaceeknnnorssstu", "aeeeehinnpprsssv",
     "aacgiillrrssttuu", "ccceeiklnoorstuw", "aceiinnoorsssttv", "acdeiiiilmnnrsty",
     "celnnoprssssuuuu", "addegiimnnnrsstu", "aghhillmooopsstt", "aaciillnooprrsty",
     "aaeeiilorrrrtttx", "aaegiilnnorssttt", "aceehiinorssttuv", "aaaefilnoopprrss",
     "aabdeeeegilnrsss", "ccdeehiilorrttyy", "eemnopprsssstuuu", "ccciiimnoprrsstu",
     "abcceiiiilnnotvy", "aeiilmnnrssstttu", "aabccegilnnnortu", "aaaacchhillmsttw",
     "aaccghilloprrsty", "ccdeefiiimmnnouy", "ddeeeeilnnnprtty", "aefiilmnorssstuu",
     "aceeeginnooprstu", "aceeegilmmnorstt", "aeefiilmnooprsss", "aaahiiimnorrsttu",
     "aeehiimnnopprsss", "aaabcceillrrtuuy", "bdhiiioprrsssttu", "aeeiilmnnnorsttv",
     "cdegiilnnooorsst", "ceemnnoopsssttuu", "aaccgiiimnnortuv", "acdiiinnnoossttu",
     "eehiiinprssttvyy", "cgiilmmnnooprsuy", "aceeilllnnnosttu", "eeeillnoprssssxy",
     "aadfghiorrrssttw", "beiiiilnoprrssty", "abbeiiilmprrttuy", "aaacciiilllpstty",
     "aceegimnnooprstv", "acdeefhiimnnrsst", "aceillnnnnootuvy", "aeghhiiooprrrsst",
     "aaacceghillloory", "aaccdiiinnnoortt", "aabcciiiilmprtty", "aacghiloopprssty",
     "aacchiiillnstuvy", "abbcdiilmnooostu", "acdefghiiinnnrss", "aaacehimpprsstty",
     "eeghinooppstttty", "aciillnnoostttuy", "bceeiiiilmpprtty", "aeeiilmmnnnorstv",
     "aacghillnoopprry", "aacdeellnnnrstty", "aaccceeiilllssty", "deeghhinorsssstt",
     "aeeeeinnprrsttuv", "aaeiiilmnnnorstt", "aceeghillmnnooop", "bceeehiilmnnoprs",
     "aefiilnnnoooprrt", "aciilllmmrsttuuu", "aeehiilnnoprttvy", "abddeeeimnnnssst",
     "abcceghiillnooot", "adeiiillmmnnostu", "acceeehhimoprttu", "ceehhlnoopprssty",
     "cdeeghimnnnnoopr", "aeiiiilllmmnortu", "aacgiiinnnopprtt", "aagiiimnoppprrst",
     "aacdfiiiilnoqstu", "acegiilllmnoorty", "aabiiinnoorssttt", "abdeiiiilnnpssty",
     "beeehiiilnprrsty", "beeiiiilnoprssst", "beeenooprrsssstu", "aciiimnnnooprstu",
     "adeeeiimnnoprrtt"]
    |> Enum.into(HashSet.new)
  end
end
