defmodule Jumble.ScowlDict.Size10.Length6.Dict do
  def get do
    %{"agimnn" => ["naming"], "aefhrt" => ["father"], "adeirv" => ["varied"],
      "begins" => ["begins"], "gilnos" => ["losing"], "denrtu" => ["turned"],
      "adeelv" => ["leaved"], "bcilpu" => ["public"], "acdesu" => ["caused"],
      "aeirrv" => ["arrive"], "deffir" => ["differ"], "egnott" => ["gotten"],
      "aceert" => ["create"], "inoopt" => ["option"], "bdilsu" => ["builds"],
      "fimnor" => ["inform"], "agilns" => ["signal"], "aeilrs" => ["serial"],
      "cdgino" => ["coding"], "ceffio" => ["office"], "enrrtu" => ["return"],
      "acgint" => ["acting"], "aelmny" => ["namely"], "hnortw" => ["thrown"],
      "adiosv" => ["avoids"], "adegnr" => ["danger", "garden"],
      "lloswy" => ["slowly"], "cilopy" => ["policy"], "eopprr" => ["proper"],
      "aeelps" => ["asleep", "please"], "beirsu" => ["buries"],
      "adeelr" => ["leader"], "ddeilm" => ["middle"], "adffor" => ["afford"],
      "elostw" => ["lowest"], "dllouy" => ["loudly"], "eiklnu" => ["unlike"],
      "acorss" => ["across"], "efgiru" => ["figure"], "fgiinx" => ["fixing"],
      "abceem" => ["became"], "ehorty" => ["theory"], "aehnpp" => ["happen"],
      "bdnooy" => ["nobody"], "corrsu" => ["cursor"], "ceejrt" => ["reject"],
      "alprty" => ["partly"], "ddehin" => ["hidden"], "deirrv" => ["driver"],
      "abefhl" => ["behalf"], "eefprr" => ["prefer"], "aeenrr" => ["nearer"],
      "ackrst" => ["tracks"], "abinry" => ["binary"], "eisssu" => ["issues"],
      "einntv" => ["invent"], "ekorrw" => ["worker"], "aegint" => ["eating"],
      "aginsy" => ["saying"], "accept" => ["accept"], "celoss" => ["closes"],
      "dhlosu" => ["should"], "alstvy" => ["vastly"], "besstu" => ["subset"],
      "aacltu" => ["actual"], "amntuu" => ["autumn"], "aaeppr" => ["appear"],
      "abeeln" => ["enable"], "ciprst" => ["script"], "degglo" => ["logged"],
      "adeprs" => ["spread"], "dnossu" => ["sounds"], "deilms" => ["misled"],
      "abekrs" => ["breaks"], "beggir" => ["bigger"], "horstw" => ["throws"],
      "acilms" => ["claims"], "cgimno" => ["coming"], "blmosy" => ["symbol"],
      "defill" => ["filled"], "ceefft" => ["effect"], "eegrrt" => ["regret"],
      "ehpssu" => ["pushes"], "anstxy" => ["syntax"], "allosw" => ["allows"],
      "aenrtu" => ["nature"], "airstt" => ["artist"], "acepst" => ["aspect"],
      "ehmort" => ["mother"], "fhiins" => ["finish"], "deistw" => ["widest"],
      "cchhru" => ["church"], "eemorv" => ["remove"], "ginpty" => ["typing"],
      "elrsuy" => ["surely"], "adehln" => ["handle"], "aelsuv" => ["values"],
      "ainnot" => ["nation"], "deeems" => ["seemed"], "aenprt" => ["parent"],
      "ceilop" => ["police"], "efiint" => ["finite"], "bdehin" => ["behind"],
      "ggiinv" => ["giving"], "ghhotu" => ["though"], "addeln" => ["landed"],
      "ceeffo" => ["coffee"], "bdegtu" => ["budget"], "adeitw" => ["waited"],
      "ddeenp" => ["depend"], "eilnst" => ["listen"], "adhlry" => ["hardly"],
      "acekpt" => ["packet"], "eorrst" => ["resort"], "inpstu" => ["inputs"],
      "aelrtv" => ["travel"], "adllor" => ["dollar"], "eerssv" => ["serves"],
      "bmoott" => ["bottom"], "eflmsy" => ["myself"], "belstu" => ["subtle"],
      "giimnx" => ["mixing"], "ccopuy" => ["occupy"], "eefrrs" => ["refers"],
      "abelnu" => ["unable"], "eemort" => ["remote"], "adepss" => ["passed"],
      "afilry" => ["fairly"], "adeisv" => ["advise"], "delosv" => ["solved"],
      "annosy" => ["annoys"], "dinoww" => ["window"], "dekloo" => ["looked"],
      "adimno" => ["domain"], "deiort" => ["editor"], "ehnost" => ["honest"],
      "fhortu" => ["fourth"], "agiimn" => ["aiming"], "efilst" => ["itself"],
      "iinsst" => ["insist"], "aekmrr" => ["remark"], "eefstw" => ["fewest"],
      "emssty" => ["system"], "gnorst" => ["strong"], "epsstu" => ["upsets"],
      "beffru" => ["buffer"], "adnsst" => ["stands"], "ccorsu" => ["occurs"],
      "cdeeiv" => ["device"], "cddeeu" => ["deduce"], "lmosty" => ["mostly"],
      "deinrv" => ["driven"], "aeeirs" => ["easier"], "aeghrt" => ["gather"],
      "deeelt" => ["delete"], "celopu" => ["couple"], "chistw" => ["switch"],
      "eghnou" => ["enough"], "aehprs" => ["phrase"], "afmort" => ["format"],
      "cefors" => ["forces"], "depttu" => ["putted"], "fgoort" => ["forgot"],
      "ersuvy" => ["survey"], "aelrry" => ["rarely"], "eirrtw" => ["writer"],
      "arsstt" => ["starts"], "acdekl" => ["lacked"], "bcektu" => ["bucket"],
      "ceiops" => ["copies"], "finoty" => ["notify"], "acelps" => ["places"],
      "aeglrr" => ["larger"], "adeilt" => ["detail"], "giikln" => ["liking"],
      "beertt" => ["better"], "cehnos" => ["chosen"], "ccehks" => ["checks"],
      "ceersu" => ["secure"], "aekpss" => ["speaks"], "goprsu" => ["groups"],
      "acinot" => ["action"], "abeehv" => ["behave"], "adestt" => ["stated"],
      "defmor" => ["formed"], "eeltvw" => ["twelve"], "eknops" => ["spoken"],
      "aceeps" => ["escape"], "eisstx" => ["exists"], "eflsuu" => ["useful"],
      "ceorsu" => ["course", "source"], "acellr" => ["recall"],
      "abcehr" => ["breach"], "deeotv" => ["devote"], "aginsv" => ["saving"],
      "cmmnoo" => ["common"], "deorst" => ["sorted", "stored"],
      "aceghr" => ["charge"], "aefsty" => ["safety"], "deoqtu" => ["quoted"],
      "cenorr" => ["corner"], "aegrtt" => ["target"], "ddeiiv" => ["divide"],
      "hortwy" => ["worthy"], "aeelrv" => ["reveal"], "beehry" => ["hereby"],
      "eerstt" => ["street"], "enttwy" => ["twenty"], "acghtu" => ["caught"],
      "dehmot" => ["method"], "celors" => ["closer"], "eeflry" => ["freely"],
      "ceortv" => ["vector"], "aceghn" => ["change"], "eimprt" => ["permit"],
      "efrtuu" => ["future"], "aelnrs" => ["learns"], "ginrty" => ["trying"],
      "bemnru" => ["number"], "dnopsu" => ["pounds"], "acdell" => ["called"],
      "eeirvw" => ["review"], "aalswy" => ["always"], "aenopw" => ["weapon"],
      "amnotu" => ["amount"], "aeilnr" => ["linear"], "deopst" => ["posted"],
      "aceitv" => ["active"], "adeils" => ["ladies"], "ahknst" => ["thanks"],
      "einrtw" => ["winter"], "eelrss" => ["lesser"], "eeirss" => ["series"],
      "acehrs" => ["search"], "bdenoy" => ["beyond"], "ghortw" => ["growth"],
      "eoqstu" => ["quotes"], "agikmn" => ["making"], "dehisw" => ["wished"],
      "aeilsy" => ["easily"], "ciprss" => ["crisps"], "aeiprr" => ["repair"],
      "ceiktt" => ["ticket"], "aeelsv" => ["leaves"], "enoors" => ["sooner"],
      "aeflsy" => ["safely"], "ceessx" => ["excess"], "eoopps" => ["oppose"],
      "aeflln" => ["fallen"], "dehosw" => ["showed"], "aeinrt" => ["retain"],
      "ceeips" => ["pieces"], "eirtuv" => ["virtue"], "adeerr" => ["reader"],
      "ceehms" => ["scheme"], "fgilny" => ["flying"], "aelnpt" => ["planet"],
      "deissu" => ["issued"], "eorsst" => ["stores"], "dekorw" => ["worked"],
      "adestw" => ["wasted"], "eorrrs" => ["errors"], "defitt" => ["fitted"],
      "cefhnr" => ["french"], "clmnou" => ["column"], "abhist" => ["habits"],
      "elpruy" => ["purely"], "aegsst" => ["stages"], "effrsu" => ["suffer"],
      "deimnr" => ["remind"], "adeptu" => ["update"], "ellosy" => ["solely"],
      "accehn" => ["chance"], "ckknos" => ["knocks"], "ccelsy" => ["cycles"],
      "abgins" => ["basing"], "deiins" => ["inside"], "aelmps" => ["sample"],
      "bcejot" => ["object"], "abinot" => ["obtain"], "ellpss" => ["spells"],
      "adgnrs" => ["grands"], "deeirv" => ["derive"], "fgiiln" => ["filing"],
      "bceemo" => ["become"], "cceilr" => ["circle"], "aehrss" => ["shares"],
      "dginru" => ["during"], "diklny" => ["kindly"], "cdeorr" => ["record"],
      "deefin" => ["define"], "deikln" => ["linked"], "ddeein" => ["indeed"],
      "ddeeem" => ["deemed"], "giilnv" => ["living"], "eeersv" => ["severe"],
      "eirstw" => ["writes"], "efgort" => ["forget"], "deilst" => ["listed"],
      "abdors" => ["boards"], "beglno" => ["belong"], "denoow" => ["wooden"],
      "definr" => ["friend"], "ikllss" => ["skills"], "aekmrt" => ["market"],
      "adenpx" => ["expand"], "iinosv" => ["vision"], "aelstt" => ["latest"],
      "deorrs" => ["orders"], "afmosu" => ["famous"], "adnoru" => ["around"],
      "addehn" => ["handed"], "bginuy" => ["buying"], "ghirst" => ["rights"],
      "ehorss" => ["horses"], "cddeei" => ["decide"], "ciopst" => ["topics"],
      "ceesux" => ["excuse"], "acilos" => ["social"], "gimnov" => ["moving"],
      "aflost" => ["floats"], "access" => ["access"], "abgllo" => ["global"],
      "cehins" => ["inches"], "cdeklo" => ["locked"], "aesstw" => ["wastes"],
      "cdefor" => ["forced"], "deelpy" => ["deeply"], "ddensu" => ["sudden"],
      "inopst" => ["points"], "ceelst" => ["elects", "select"],
      "aerstt" => ["treats"], "cdeent" => ["decent"], "eglnor" => ["longer"],
      "acfort" => ["factor"], "aghinv" => ["having"], "deeirs" => ["desire"],
      "defils" => ["fields"], "deestt" => ["tested"], "eilmps" => ["simple"],
      "aepprs" => ["papers"], "aesstt" => ["states"], "eoprsv" => ["proves"],
      "aeimnr" => ["remain"], "adortw" => ["toward"], "ghostu" => ["sought"],
      "giinor" => ["origin"], "aeerrs" => ["eraser"], "aennoy" => ["anyone"],
      "cdeett" => ["detect"], "ailmny" => ["mainly"], "cdeeru" => ["reduce"],
      "ginprs" => ["spring"], "ddeeen" => ["needed"], "ceenrt" => ["recent"],
      "eilstt" => ["titles"], "eehirt" => ["either"], "ellowy" => ["yellow"],
      "eeinrt" => ["entire"], "aaelpp" => ["appeal"], "iiprst" => ["spirit"],
      "beintt" => ["bitten"], "adesty" => ["stayed"], "eeprtx" => ["expert"],
      "eiklly" => ["likely"], "beemmr" => ["member"], "efhiss" => ["fishes"],
      "deimmu" => ["medium"], "aadfir" => ["afraid"], "deoprv" => ["proved"],
      "einrst" => ["insert"], "eilltt" => ["little"], "ceorss" => ["scores"],
      "bghotu" => ["bought"], "acfils" => ["fiscal"], "lppsuy" => ["supply"],
      "inprst" => ["prints"], "opttuu" => ["output"], "ceimno" => ["income"],
      "deenop" => ["opened"], "ceiprs" => ["prices"], "aanwyy" => ["anyway"],
      "acepss" => ["spaces"], "eelopp" => ["people"], "deillw" => ["willed"],
      "eimssu" => ["misuse"], "hiintw" => ["within"], "almnor" => ["normal"],
      "deersv" => ["served"], "aacktt" => ["attack"], "aeirsv" => ["varies"],
      "eikrst" => ["strike"], "boorrw" => ["borrow"], "eelmry" => ["merely"],
      "eenttx" => ["extent"], "ginnot" => ["noting"], "bimstu" => ["submit"],
      "eenstv" => ["events"], "aelrtt" => ["latter"], "aailmn" => ["animal"],
      "eoprrt" => ["report"], "efginr" => ["finger"], "eefrsu" => ["refuse"],
      "adeegr" => ["agreed"], "aalnnu" => ["annual"], "rssttu" => ["trusts"],
      "addgin" => ["adding"], "eghitw" => ["weight"], "imnoot" => ["motion"],
      "deiopr" => ["period"], "cdeirt" => ["credit", "direct"],
      "aehrtt" => ["threat"], "elnpty" => ["plenty"], "belott" => ["bottle"],
      "adimst" => ["admits"], "eprtty" => ["pretty"], "dghiin" => ["hiding"],
      "aeqrsu" => ["square"], "cekopt" => ["pocket"], "eellsv" => ["levels"],
      "eimsss" => ["misses"], "ceinot" => ["notice"], "abdeet" => ["debate"],
      "adefil" => ["failed"], "denorw" => ["wonder"], "ilmpsy" => ["simply"],
      "bghirt" => ["bright"], "aegims" => ["images"], "agiknt" => ["taking"],
      "ghinst" => ["things"], "addelo" => ["loaded"], "elorsw" => ["slower"],
      "adeehr" => ["header"], "adegru" => ["argued"], "cnotuy" => ["county"],
      "deistu" => ["suited"], "ademsu" => ["amused"], "dgnoru" => ["ground"],
      "aeeprt" => ["repeat"], "ghhily" => ["highly"],
      "eginor" => ["ignore", "region"], "adentw" => ["wanted"],
      "ceelrv" => ["clever"], "einquu" => ["unique"], "agnrst" => ["grants"],
      "deinnr" => ["dinner"], "aelnry" => ["nearly"], "adehrr" => ["harder"],
      "ilpsst" => ["splits"], "bdeiru" => ["buried"], "cdeiop" => ["copied"],
      "filmry" => ["firmly"], "aadegm" => ["damage"], "effort" => ["effort"],
      "adeklw" => ["walked"], "hmoost" => ["smooth"], "enoprs" => ["person"],
      "eloprt" => ["petrol"], "aeegrs" => ["agrees"], "delmos" => ["models"],
      "ceehps" => ["speech"], "giimnt" => ["timing"], "acddee" => ["decade"],
      "chloos" => ["school"], "eintty" => ["entity"], "ceorsv" => ["covers"],
      "dfimoy" => ["modify"], "adekmr" => ["marked"], "elossv" => ["solves"],
      "aaffir" => ["affair"], "cdenos" => ["second"], "bginrs" => ["brings"],
      "deginn" => ["ending"], "elrstu" => ["result"], "agikns" => ["asking"],
      "eenrst" => ["enters"], "ceeptx" => ["except", "expect"],
      "dellpu" => ["pulled"], "abelst" => ["stable", "tables"],
      "ciirss" => ["crisis"], "aefsst" => ["safest"], "bdelou" => ["double"],
      "addemn" => ["demand"], "aerssu" => ["assure"], "acdelp" => ["placed"],
      "alotuy" => ["layout"], "cnostu" => ["counts"], "bdegir" => ["bridge"],
      "addeeh" => ["headed"], "ddeorw" => ["worded"], "aehhlt" => ["health"],
      "assttu" => ["status"], "aaegmn" => ["manage"], "hilstw" => ["whilst"],
      "ginrst" => ["string"], "effors" => ["offers"], "behort" => ["bother"],
      "abeill" => ["liable"], "iilmst" => ["limits"], "ciksst" => ["sticks"],
      "aellry" => ["really"], "efmorr" => ["former"], "cirstt" => ["strict"],
      "adeirs" => ["raised"], "beknor" => ["broken"], "aachtt" => ["attach"],
      "deijno" => ["joined"], "aefrst" => ["faster"], "eimntu" => ["minute"],
      "aeelrt" => ["relate"], "deimss" => ["missed"], "eiintv" => ["invite"],
      "dehpsu" => ["pushed"], "emmrsu" => ["summer"], "abchnr" => ["branch"],
      "deinnt" => ["intend"], "bgiint" => ["biting"], "adelpy" => ["played"],
      "fghilt" => ["flight"], "addeel" => ["leaded"], "ccehio" => ["choice"],
      "ckrstu" => ["struck", "trucks"], "elnssu" => ["unless"],
      "demnor" => ["modern"], "adentt" => ["attend"], "aegrsu" => ["argues"],
      "denosz" => ["dozens"], "eehlsw" => ["wheels"], "eimrst" => ["merits"],
      "deikll" => ["killed"], "abells" => ["labels"], "deeegr" => ["degree"],
      "aemssu" => ["amuses", "assume"], "emmnot" => ["moment"],
      "emmory" => ["memory"], "ehissw" => ["wishes"], "ceerst" => ["secret"],
      "ceinst" => ["nicest"], "acessu" => ["causes"], "adegin" => ["gained"],
      "acefft" => ["affect"], "adgint" => ["dating"], "bberru" => ["rubber"],
      "eghlnt" => ["length"], "adeghn" => ["hanged"], "abcdek" => ["backed"],
      "aghttu" => ["taught"], "admnor" => ["random"], "eelstt" => ["settle"],
      "bdeios" => ["bodies"], "ghilst" => ["lights", "slight"],
      "acnnot" => ["cannot"], "aeirss" => ["arises", "raises"],
      "elnoss" => ["lesson"], "ahortu" => ["author"], "adehrs" => ["shared"],
      "aenors" => ["reason"], "aemrtt" => ["matter"], "hiknst" => ["thinks"],
      "aepsss" => ["passes"], "aehrrt" => ["rather"], "dgiist" => ["digits"],
      "aflmor" => ["formal"], "ainrst" => ["trains"], "acdeiv" => ["advice"],
      "aalmnu" => ["manual"], "eghhir" => ["higher"], "enorsw" => ["owners"],
      "eerrsv" => ["server"], "egilns" => ["single"], "ehorst" => ["others"],
      "deeenv" => ["evened"], "almost" => ["almost"], "aemnnr" => ["manner"],
      "elmouv" => ["volume"], "aenoss" => ["season"], "aelrst" => ["alters"],
      "enosst" => ["stones"], "aenrsw" => ["answer"], "hmnost" => ["months"],
      "denpss" => ["spends"], "delost" => ["oldest"], "mopprt" => ["prompt"],
      "einors" => ["senior"], "eegins" => ["seeing"], "abenry" => ["nearby"],
      "acimpt" => ["impact"], "deilwy" => ["widely"],
      "aemrst" => ["master", "stream"], "beefor" => ["before"],
      "adopst" => ["adopts"], "eimops" => ["impose"], "adegrr" => ["regard"],
      "deentx" => ["extend"], "dipstu" => ["stupid"], "flloow" => ["follow"],
      "adjstu" => ["adjust"], "bnottu" => ["button"], "cdeikp" => ["picked"],
      "adeklt" => ["talked"], "cehoos" => ["choose"], "dginrs" => ["grinds"],
      "aginpy" => ["paying"], "adenrw" => ["warned"], "ddeimn" => ["minded"],
      "eoprsw" => ["powers"], "ghinop" => ["hoping"], "ddeeit" => ["edited"],
      "accdor" => ["accord"], "eelrtt" => ["letter"], "eenrsu" => ["ensure"],
      "ceenrs" => ["screen"], "degins" => ["design", "signed"],
      "deirsv" => ["drives"], "afilmy" => ["family"], "acelrs" => ["clears"],
      "cdelos" => ["closed"], "aflstu" => ["faults"], "acegny" => ["agency"],
      "deehlp" => ["helped"]}
  end
end
