defmodule Jumble.ScowlDict.Size40.Length13 do
  def get(string_id) do
    %{"aadiimnorrstt" => ["administrator"], "acilmnooopsst" => ["cosmopolitans"],
      "acdeiinnorstt" => ["indoctrinates"], "acefghiinnnrs" => ["enfranchising"],
      "abcflmnoortuy" => ["uncomfortably"], "acceehhloorst" => ["schoolteacher"],
      "abeiiiilnttvy" => ["inevitability"], "aceillmmrstyy" => ["symmetrically"],
      "aaccdimmnooot" => ["accommodation"], "cceiimnnoopst" => ["misconception"],
      "aiillnnortuvy" => ["involuntarily"], "aaccdeilnootu" => ["coeducational"],
      "ccdgiimnnostu" => ["misconducting"], "aeeinrssstttv" => ["transvestites"],
      "ccdegiinnorst" => ["disconcerting"], "adehnorrsttww" => ["northwestward"],
      "aeeimnnorrstu" => ["remunerations"], "egiimnopprssu" => ["superimposing"],
      "aaehiiimnnstt" => ["antihistamine"], "accdeeennnrst" => ["transcendence"],
      "acehhiinoprsz" => ["schizophrenia"], "aaccegiinnrrt" => ["incarcerating"],
      "aacfiiimnorst" => ["ramifications"], "aeeilnnoprrst" => ["interpersonal"],
      "cgiimnnorsstu" => ["misconstruing"], "aceeinorsstvv" => ["conservatives"],
      "aagilnnorsttu" => ["strangulation"], "ceegmnnoorssw" => ["congresswomen"],
      "aeeillnnoptxy" => ["exponentially"], "beeeimmnrrstu" => ["reimbursement"],
      "adeegmnnrrstu" => ["undergarments"], "eegilmooorstt" => ["meteorologist"],
      "aaagiilnorttv" => ["gravitational"], "aehilmoostuxy" => ["homosexuality"],
      "acfiiimnoortt" => ["mortification"], "ceeinoorrsstv" => ["controversies"],
      "hnorrstttuuwy" => ["untrustworthy"], "eegiinnnrsttu" => ["uninteresting"],
      "ceeinorsstttu" => ["reconstitutes"], "eiimnoorssstt" => ["monstrosities"],
      "aaahiimnnrstu" => ["humanitarians"], "bdeeiirrssttu" => ["redistributes"],
      "aeiilnoopprst" => ["prepositional"], "aaeffiilmrtvy" => ["affirmatively"],
      "deeeeimnprrst" => ["predetermines"], "aaiimnoopprtx" => ["approximation"],
      "aaeeiinnrrstv" => ["veterinarians"], "ddeeeiinrsstt" => ["disinterested"],
      "aceeiiilprstu" => ["peculiarities"], "cdeeinorstttu" => ["reconstituted"],
      "aabdegiknorst" => ["skateboarding"], "eegiinnprrsst" => ["interspersing"],
      "acdegiimnostt" => ["domesticating"], "addeeegmnrrry" => ["gerrymandered"],
      "acdefgillrsuy" => ["disgracefully"], "efgghiiilnttw" => ["weightlifting"],
      "acegiimmnorst" => ["commiserating"], "aaaiinnosssst" => ["assassination"],
      "cdeeiiimnrstt" => ["deterministic"], "aegiinorssttv" => ["investigators"],
      "aaceeiinorrst" => ["reactionaries"], "abbciiiloprst" => ["probabilistic"],
      "aacdeglnorttu" => ["congratulated"], "abcceiiilssty" => ["accessibility"],
      "aabcgillnoort" => ["collaborating"], "aegiinnoorrtt" => ["interrogation"],
      "eeknoopprssss" => ["spokespersons"], "cceeemmmnnost" => ["commencements"],
      "aacfiinossstt" => ["satisfactions"], "cdfghiilnoopr" => ["childproofing"],
      "adeejmnrssttu" => ["readjustments"], "acghiilloopsy" => ["physiological"],
      "cceiinnnossty" => ["inconsistency"], "aceeiloprstty" => ["stereotypical"],
      "ccdegiinnnost" => ["disconnecting"], "aceegiinnsstt" => ["necessitating"],
      "ceeiijnnorstt" => ["interjections"], "aceeilnnoqstu" => ["consequential"],
      "adeeeiimnnrtt" => ["indeterminate"], "aadefllmnntuy" => ["fundamentally"],
      "abeeeinorrrtv" => ["reverberation"], "aadeinorrrtxy" => ["extraordinary"],
      "cdeimnnooprsu" => ["mispronounced"], "ceiimmnoorsss" => ["commissioners"],
      "accdeeilnopsy" => ["encyclopedias"], "aaiilmnnopstu" => ["manipulations"],
      "abeeeginrrrtv" => ["reverberating"], "acgghiklnostu" => ["laughingstock"],
      "acdeeennopprr" => ["preponderance"], "acfgiiiinnnst" => ["insignificant"],
      "acdgiinnosttu" => ["outdistancing"], "eeffglnorsstu" => ["forgetfulness"],
      "abdeglnorsttu" => ["battlegrounds"], "aaadddeginstv" => ["disadvantaged"],
      "aeeeinrsssstv" => ["assertiveness"], "acdeeiinnorst" => ["inconsiderate"],
      "acegimmmnoort" => ["commemorating"], "aaegiimmnnrst" => ["mainstreaming"],
      "abdeiinnorstu" => ["insubordinate"], "adeefinoorstt" => ["deforestation"],
      "aaeinnnossttu" => ["instantaneous"], "aabbddeegilor" => ["biodegradable"],
      "eeiilmnpsssuv" => ["impulsiveness"], "eeeennprrrstu" => ["entrepreneurs"],
      "eiinoprsssttu" => ["superstitions"], "aeeiimnnorttx" => ["extermination"],
      "aaeegimmmnnst" => ["mismanagement"], "aceinnnoorstt" => ["consternation"],
      "cdeegiinorrsv" => ["rediscovering"], "aagiinoppprrt" => ["appropriating"],
      "aaeeelmmnprtt" => ["temperamental"], "adiiilnrssttu" => ["industrialist"],
      "ddeghiiinsstu" => ["distinguished"], "defgginnoorru" => ["foregrounding"],
      "adeeimnrsstuv" => ["misadventures"], "behiiiimnostx" => ["exhibitionism"],
      "aceiimmnoorst" => ["commiseration"], "aegiimnnoprst" => ["impersonating"],
      "adeehhiorrsss" => ["horseradishes"], "acgghhinnorst" => ["shortchanging"],
      "deeghilmooost" => ["methodologies"], "eeeellnpsssss" => ["sleeplessness"],
      "adeeiimnoprtt" => ["premeditation"], "aaciilnopsttu" => ["capitulations"],
      "aeeinnorsstuv" => ["intravenouses"], "cceeiinnossst" => ["consistencies"],
      "acfgiiilnoort" => ["glorification"], "aeiilnnnnottu" => ["unintentional"],
      "acfgiiilnnsty" => ["significantly"], "ceefiimnoprst" => ["imperfections"],
      "aaccciiilmntt" => ["anticlimactic"], "eegghinnnrstt" => ["strengthening"],
      "ccgiinorrssss" => ["crisscrossing"], "abelllmnoossy" => ["monosyllables"],
      "aefiiiilmnnst" => ["infinitesimal"], "aceiinoprrstt" => ["practitioners"],
      "cegiinnooprss" => ["processioning"], "aahiinopsstxy" => ["asphyxiations"],
      "aacceginnnott" => ["concatenating"], "ddeeeeimnprrt" => ["predetermined"],
      "cdeeiiorssstu" => ["discourtesies"], "ccdeehilorrty" => ["hydroelectric"],
      "aaciimnnnoott" => ["contamination"], "aiimnnorsssst" => ["transmissions"],
      "cdeennooprrst" => ["correspondent"], "cgiiimmnnooss" => ["commissioning"],
      "cdeefilprsstu" => ["disrespectful"], "ciinoopprsttu" => ["opportunistic"],
      "ciinoopprrsst" => ["proscriptions"], "acgiiillnnstt" => ["scintillating"],
      "aaeeegmnnrrrt" => ["rearrangement"], "cdeeefinorttu" => ["counterfeited"],
      "aegikllnorrst" => ["rollerskating"], "abeeghiknorsu" => ["housebreaking"],
      "aaaiilnorsttt" => ["totalitarians"], "aeeeimorssttv" => ["overestimates"],
      "acfiiijnosttu" => ["justification"], "behiiiinosttx" => ["exhibitionist"],
      "eeghiinrsstux" => ["extinguishers"], "accdgiinnortt" => ["contradicting"],
      "aacfgiiinortt" => ["gratification"], "deeiiinoqrstu" => ["requisitioned"],
      "aceilnoorrstv" => ["controversial"], "aiiilnnostttu" => ["institutional"],
      "adeeeghlmmrss" => ["sledgehammers"], "ddeginnrstuuy" => ["understudying"],
      "deeeegiprrrst" => ["preregistered"], "eehlorssttuwy" => ["southwesterly"],
      "abgiimnnorrst" => ["brainstorming"], "aafiilmnnoort" => ["informational"],
      "ccilmoorsstty" => ["motorcyclists"], "aaelnnprrstty" => ["transparently"],
      "ccdeimnoorstu" => ["semiconductor"], "aacgiimnnnott" => ["contaminating"],
      "accdiinnoortt" => ["contradiction"], "cdeiiilnsttvy" => ["distinctively"],
      "aabciiillppty" => ["applicability"], "achhiilloopps" => ["philosophical"],
      "acfinnnooortt" => ["confrontation"], "aaccegillorty" => ["categorically"],
      "aaiinooppprrt" => ["appropriation"], "aadegoprssttu" => ["postgraduates"],
      "aacceinnnoott" => ["concatenation"], "acdeghiinnnst" => ["disenchanting"],
      "eeehilmnnprst" => ["replenishment"], "aeeloopprstuv" => ["overpopulates"],
      "aagilnnnprstt" => ["transplanting"], "aaceehilnprtt" => ["parenthetical"],
      "abefiijlnstuu" => ["unjustifiable"], "aacdeeeffinst" => ["decaffeinates"],
      "ccddeeginnnos" => ["condescending"], "acdeeeilnssst" => ["delicatessens"],
      "eeegiimnnprtx" => ["experimenting"], "ceiiilnnsttvy" => ["instinctively"],
      "abbcghiiilopr" => ["bibliographic"], "adehorssttuww" => ["southwestward"],
      "aaehiiortttuv" => ["authoritative"], "abeiillnrtuvy" => ["vulnerability"],
      "deeeginnortvx" => ["overextending"], "aceeegillnrty" => ["energetically"],
      "adeeeffiinrtt" => ["differentiate"], "eegiilnnrstty" => ["interestingly"],
      "cefilnoprrtuy" => ["perfunctorily"], "behiiiloprtvy" => ["prohibitively"],
      "aaacdilloprxy" => ["paradoxically"], "aaefgimnnortt" => ["fragmentation"],
      "aabcillnooort" => ["collaboration"], "ghiilnooorstt" => ["ornithologist"],
      "aceeilorrttvy" => ["retroactively"], "deghiiinssstu" => ["distinguishes"],
      "aegiinorrsstt" => ["registrations"], "bceeeeghrrssu" => ["cheeseburgers"],
      "abeimnnosssuw" => ["businesswoman"], "adeeegginorst" => ["desegregation"],
      "aeggiinorrttu" => ["regurgitation"], "adefghinoorsw" => ["foreshadowing"],
      "accghillnooor" => ["chronological"], "acgiimmnoorrs" => ["microorganism"],
      "aeilnoorrtuvy" => ["revolutionary"], "aaeilmopprtxy" => ["approximately"],
      "aeefggiinrrrt" => ["refrigerating"], "aeeeiilnsttuv" => ["eventualities"],
      "deeeelmnoprtv" => ["redevelopment"], "ciinnoosstttu" => ["constitutions"],
      "agghhinoopprt" => ["photographing"], "aaaaehilnpprr" => ["paraphernalia"],
      "adeeeimnrsttv" => ["advertisement"], "acchiooprrrst" => ["chiropractors"],
      "beegloorrsttt" => ["globetrotters"], "beeeiilprrrss" => ["irrepressible"],
      "deeeghilnnntu" => ["unenlightened"], "ceeginoprrstt" => ["retrospecting"],
      "cdehknrrsttuu" => ["thunderstruck"], "aacceiiorrsst" => ["aristocracies"],
      "eegiloprrssvy" => ["progressively"], "bdiiinorssttu" => ["distributions"],
      "ceeelmmorsttu" => ["telecommuters"], "ddeiiillnossu" => ["disillusioned"],
      "adiiiilmrssty" => ["dissimilarity"], "cceeinnoopprt" => ["preconception"],
      "ceeinorrrsstu" => ["resurrections"], "cdeiiinnorsst" => ["indiscretions"],
      "cceeilnostuvy" => ["consecutively"], "acdeghiimnnrs" => ["merchandising"],
      "aegiiinnosttv" => ["investigation"], "aceiiinopprtt" => ["precipitation"],
      "aaagiinnsssst" => ["assassinating"], "abbceeijlnoot" => ["objectionable"],
      "aegggiinrrttu" => ["regurgitating"], "acceinnooprtt" => ["contraception"],
      "accghiilmnops" => ["accomplishing"], "cceeilnoorttu" => ["electrocution"],
      "cciinnoorsstt" => ["constrictions"], "acfiimnnoorst" => ["confirmations"],
      "aaefilnqrrstu" => ["quarterfinals"], "acdeimnnnoost" => ["condemnations"],
      "adeeghiinnrst" => ["disheartening"], "bddeeiirrsttu" => ["redistributed"],
      "abbbehlmorstu" => ["blabbermouths"], "ccceeefimnrru" => ["circumference"],
      "acdefilmnnotu" => ["malfunctioned"], "aegghiinnrstt" => ["straightening"],
      "adeeiinoorrtt" => ["deterioration"], "aabdeinsstttu" => ["substantiated"],
      "abdeegkllnowy" => ["knowledgeably"], "ceeeeffinsstv" => ["effectiveness"],
      "aaccfiiilnort" => ["clarification"], "eiilmnoqrstuv" => ["ventriloquism"],
      "adeimnnoorstt" => ["demonstration"], "addiiiilnstuv" => ["individualist"],
      "aghilnooortty" => ["orthogonality"], "aaaccillrssty" => ["sarcastically"],
      "ccilnoopssuuy" => ["conspicuously"], "aaciiinopprtt" => ["participation"],
      "aciinnoprrstt" => ["transcription"], "aciimnnoosstu" => ["sanctimonious"],
      "acceinnnoortt" => ["concentration"], "abciiilmoptty" => ["compatibility"],
      "aadehnorrsttw" => ["northeastward"], "aaddegghnrrtu" => ["granddaughter"],
      "aaeiloppprrty" => ["appropriately"], "aeefgiinorrrt" => ["refrigeration"],
      "aaaceegnrstvx" => ["extravagances"], "aaehimnpssstt" => ["statesmanship"],
      "acdeefginnort" => ["confederating"], "beiilnoprrssy" => ["irresponsibly"],
      "aeggiimnssttu" => ["guesstimating"], "cceegiinnoprv" => ["preconceiving"],
      "cdeginnooprrs" => ["corresponding"], "aaacehiimmntt" => ["mathematician"],
      "aeeinnoprsstt" => ["presentations"], "aaccdeimnnopu" => ["unaccompanied"],
      "eeknnoopssstu" => ["outspokenness"], "efgghiilnnrty" => ["frighteningly"],
      "abelnopprstuu" => ["unsupportable"], "acilllmrttuuu" => ["multicultural"],
      "aciinnoooprrt" => ["incorporation"], "aabghiooprtuy" => ["autobiography"],
      "aaiillnnosstt" => ["installations"], "ceghinorstttu" => ["outstretching"],
      "accegiinoprrt" => ["reciprocating"], "acdfilnnostuy" => ["dysfunctional"],
      "abgilmnosuuuy" => ["unambiguously"], "eiioprrssttuu" => ["surreptitious"],
      "cdeiimnooopst" => ["decomposition"], "adeeeimnrsttu" => ["underestimate"],
      "acgiiiimnnnrt" => ["incriminating"], "abdehhnosssuu" => ["househusbands"],
      "acegiiinpprtt" => ["precipitating"], "aeegiimnnrttx" => ["exterminating"],
      "aacdiiiorttvy" => ["radioactivity"], "aeiimnnooprst" => ["impersonation"],
      "adeeghprssttu" => ["stepdaughters"], "accefiiinortt" => ["certification"],
      "acdeeilmnpsst" => ["displacements"], "eeiiiinsssttv" => ["sensitivities"],
      "acegghiinnnrt" => ["interchanging"], "aabiilnnssttu" => ["insubstantial"],
      "acehhmmnrstuy" => ["chrysanthemum"], "achillorrttuu" => ["horticultural"],
      "acddeiinnortt" => ["indoctrinated"], "befiiiillntxy" => ["inflexibility"],
      "aceiinorssttu" => ["resuscitation"], "eeilnoprsttuy" => ["pretentiously"],
      "adeeeiimnrstt" => ["intermediates"], "acdeimmnnoost" => ["commendations"],
      "eeeimnprrssst" => ["misrepresents"], "aabelmmnosswy" => ["assemblywoman"],
      "aceelmmnoprty" => ["complementary"], "aeggimmnoprrr" => ["reprogramming"],
      "aeghhiprssuwy" => ["superhighways"], "aaceiilnprstt" => ["paternalistic"],
      "aaacceiinpstt" => ["incapacitates"], "aabcceeirrsuu" => ["bureaucracies"],
      "aaacillmottuy" => ["automatically"], "aegilmnorsstu" => ["somersaulting"],
      "cddeeiinnoort" => ["reconditioned"], "eiioprsssttuu" => ["superstitious"],
      "acdeegimmnnor" => ["commandeering"], "aaacdeeinpprs" => ["disappearance"],
      "adegiimmnnrst" => ["masterminding"], "adefillssttuy" => ["distastefully"],
      "aacceillmsstu" => ["miscalculates"], "aeehinnopprss" => ["apprehensions"],
      "adiiillnosstt" => ["distillations"], "aacegilnnpstu" => ["encapsulating"],
      "accgiimmnnotu" => ["communicating"], "accefgiiinrtt" => ["certificating"],
      "aadiillnortty" => ["traditionally"], "aacceknortttu" => ["counterattack"],
      "acdeeimnorstu" => ["documentaries"], "aiillnooprsvy" => ["provisionally"],
      "ceghhiiloprsy" => ["hieroglyphics"], "accdinoorrtty" => ["contradictory"],
      "aeiinnopssstx" => ["expansionists"], "acceehirrsttu" => ["architectures"],
      "aaacilnnrsttt" => ["transatlantic"], "abbcegiklnrry" => ["blackberrying"],
      "deefgiinnprrt" => ["fingerprinted"], "accefiiinopst" => ["specification"],
      "aaciiinnopstt" => ["anticipations"], "aaeilnooprttx" => ["extrapolation"],
      "acccdeimnrstu" => ["circumstanced"], "abeeiilrrrtvy" => ["irretrievably"],
      "deeginnorsuvz" => ["rendezvousing"], "beeeehilnprrs" => ["reprehensible"],
      "acehhopprstyy" => ["psychotherapy"], "eiiimnnorssst" => ["intermissions"],
      "afgiiilnnrtuy" => ["infuriatingly"], "aaacgilmmnrtu" => ["ungrammatical"],
      "aehimmooprsst" => ["metamorphosis"], "aabeeghiknrrt" => ["heartbreaking"],
      "aeinooopprrtt" => ["proportionate"], "acceeilorsttt" => ["electrostatic"],
      "aacghiillnntu" => ["hallucinating"], "aacefmnrrstuu" => ["manufacturers"],
      "deefiilnnrstu" => ["unfriendliest"], "aceimmmnooort" => ["commemoration"],
      "bciinoprssstu" => ["subscriptions"], "ceemopprrstuu" => ["supercomputer"],
      "abeelmmnosswy" => ["assemblywomen"], "acdeefhhiknrs" => ["handkerchiefs"],
      "aacdelmnnrssu" => ["underclassman"], "aegginnrrssst" => ["transgressing"],
      "acccdeeeinnns" => ["incandescence"], "acciimmnnootu" => ["communication"],
      "cdeinooprrstu" => ["reproductions"], "aceeglmnoorst" => ["conglomerates"],
      "cdeeeeiinnprx" => ["inexperienced"], "aceeiilnrttvy" => ["interactively"],
      "aacdeillnotuy" => ["educationally"], "aaeegginorstx" => ["exaggerations"],
      "aeeiilnoprsst" => ["personalities"], "efgimnooprrtu" => ["outperforming"],
      "ceeiinoprsttv" => ["introspective"], "egghiiinnstux" => ["extinguishing"],
      "aceehillortty" => ["theoretically"], "cdiiinnosttuy" => ["discontinuity"],
      "aabcllooorrst" => ["collaborators"], "abcdehiilnnrr" => ["brainchildren"],
      "acdeeghhooprr" => ["choreographed"], "ceegilmmnnopt" => ["complementing"],
      "acceinoopprtu" => ["preoccupation"], "cdeeeiilnnqsu" => ["delinquencies"],
      "aeeimnorrsttx" => ["exterminators"], "cdegiinnnostt" => ["discontenting"],
      "dhinooorssttt" => ["orthodontists"], "aabbeiinorstv" => ["abbreviations"],
      "cdeennrrrstuu" => ["undercurrents"], "acginoprssstt" => ["sportscasting"],
      "adeegiinrsstt" => ["disintegrates"], "aiillnorssttu" => ["illustrations"],
      "aeeghnoprrsst" => ["stenographers"], "aaciilmnorttu" => ["matriculation"],
      "ddeeeilnnnpty" => ["independently"], "aghhllmooopty" => ["ophthalmology"],
      "aceeegmnnortu" => ["encouragement"], "adeeellmorrst" => ["steamrollered"],
      "aabeehiilrstt" => ["rehabilitates"], "acceiimmnotuv" => ["communicative"],
      "acegginnoorst" => ["congregations"], "aaahiinorrttu" => ["authoritarian"],
      "ceeeioprrsttv" => ["retrospective"], "abeehiilnstux" => ["inexhaustible"],
      "aaeillnnossty" => ["sensationally"], "cceegilnorttu" => ["electrocuting"],
      "eegiilllnntty" => ["intelligently"], "adeilmnnoprty" => ["predominantly"],
      "adeeeimnnortu" => ["mountaineered"], "ceegilmmnottu" => ["telecommuting"],
      "agiiinnnorstt" => ["transitioning"], "abeefglnorttu" => ["unforgettable"],
      "aeilmnnrssttu" => ["instrumentals"], "aaefiimnnostt" => ["manifestation"],
      "adeegiinorrtt" => ["deteriorating"], "aceehmnopprrt" => ["rapprochement"],
      "cdeeefilnsstu" => ["deceitfulness"], "acdeeikloopss" => ["kaleidoscopes"],
      "ehiorrrstttuw" => ["trustworthier"], "achiimnnoopps" => ["companionship"],
      "adfgiiilnqsuy" => ["disqualifying"], "aaceglnorsttu" => ["congratulates"],
      "acdegiilllooy" => ["ideologically"], "cdfgiimnoorst" => ["discomforting"],
      "aabceinrrsstt" => ["scatterbrains"], "ademnoorrsstt" => ["demonstrators"],
      "eefgiimnnnrst" => ["infringements"], "acdeggiklnnow" => ["acknowledging"],
      "ceeefinorrttu" => ["counterfeiter"], "degiilnrsssty" => ["distressingly"],
      "abbcdeiilnrsy" => ["indescribably"], "adgiiinnoppst" => ["disappointing"],
      "bbcgghiilnntu" => ["nightclubbing"], "accdeeiinprss" => ["discrepancies"],
      "aaeillnooprty" => ["operationally"], "dfillrssttuuy" => ["distrustfully"],
      "aeghimnorssuw" => ["housewarmings"], "eiilnoqrsttuv" => ["ventriloquist"],
      "aceillnnoostt" => ["constellation"], "adeiinnopssst" => ["dispensations"],
      "aagiiklnnpsty" => ["painstakingly"], "cfghilmnooorr" => ["chloroforming"],
      "aacgilllnosty" => ["nostalgically"], "aaccehilrrttu" => ["architectural"],
      "eghiiimnoprsv" => ["impoverishing"], "aeeehlorsstux" => ["heterosexuals"],
      "adeiiimnnosst" => ["dissemination"], "acdeeeiossttv" => ["videocassette"],
      "aabbdeefglrst" => ["flabbergasted"], "ccciiimnorssu" => ["circumcisions"],
      "addeimnnrsstu" => ["misunderstand"], "aaceinoprrstt" => ["procrastinate"],
      "ceginrrrsttuu" => ["restructuring"], "ceehimnnooprs" => ["comprehension"],
      "ceiinnorrsstu" => ["insurrections"], "aacdeiilnortv" => ["valedictorian"],
      "abcinoooorrrt" => ["corroboration"], "acdeeglmnoort" => ["conglomerated"],
      "dehmnorrssttu" => ["thunderstorms"], "aaiillmnnottu" => ["multinational"],
      "aceinnoorsstv" => ["conversations"], "aabelnoprrstt" => ["transportable"],
      "eeeghilmnnntt" => ["enlightenment"], "aceeilllnsttu" => ["intellectuals"],
      "aadehorssttuw" => ["southeastward"], "aaelnprrsstuu" => ["supernaturals"],
      "aabceefiprrst" => ["prefabricates"], "aeimnooprrsst" => ["impersonators"],
      "acdeiinorrsty" => ["discretionary"], "acddeiiimnrst" => ["discriminated"],
      "cdeeiilnoprst" => ["predilections"], "aacfgimnnrtuu" => ["manufacturing"],
      "aaddgginnnrst" => ["grandstanding"], "acehiiprttvyy" => ["hyperactivity"],
      "adeeegimnrsst" => ["disagreements"], "giinnooopprrt" => ["proportioning"],
      "aegiimnnrrrty" => ["intermarrying"], "cdeeghimnnopr" => ["comprehending"],
      "acdefiinnsstt" => ["disinfectants"], "adegimnnorstt" => ["demonstrating"],
      "aehhiopprstyy" => ["physiotherapy"], "abdiinnoorstu" => ["subordination"],
      "aeehmmooprsst" => ["metamorphoses"], "cfimnnnooorst" => ["nonconformist"],
      "eghiiilnnqrsu" => ["relinquishing"], "aceegillmorty" => ["geometrically"],
      "abceeiilnnnst" => ["bicentennials"], "bdeeginnorruv" => ["overburdening"],
      "acceghillnoot" => ["technological"], "deghiiiinnrst" => ["disinheriting"],
      "aciinnnooprtu" => ["pronunciation"], "abbiiilmoprty" => ["improbability"],
      "aacegiinnnrrt" => ["reincarnating"], "aeeiiilmnprrs" => ["preliminaries"],
      "achhiimnoppss" => ["championships"], "beeehillmmnst" => ["embellishment"],
      "ailnooopprrst" => ["proportionals"], "acdeiinnoorst" => ["consideration"],
      "eefghiilrsttw" => ["weightlifters"], "ccdeenorrsttu" => ["reconstructed"],
      "cceiimnnortuv" => ["circumvention"], "aeginnorrssst" => ["transgression"],
      "aeefgiorrrrst" => ["refrigerators"], "eeeghimnosstu" => ["meetinghouses"],
      "acefgiilmnnty" => ["magnificently"], "befgiiilnrstu" => ["filibustering"],
      "abbcdeeiilnrs" => ["indescribable"], "ceeefimnnorrt" => ["reinforcement"],
      "aiilnooopprst" => ["propositional"], "aacgiiinpprtt" => ["participating"],
      "beeiilnoprrss" => ["irresponsible"], "ceeehimnoprsv" => ["comprehensive"],
      "aceeiinnrsttu" => ["uncertainties"], "aciilllmooqsu" => ["colloquialism"],
      "accdhhinoopry" => ["hypochondriac"], "biinossstttuu" => ["substitutions"],
      "adeegiknnrrst" => ["kindergartens"], "aefghhorstttu" => ["afterthoughts"],
      "cddeeeennprtu" => ["unprecedented"], "acdeimnnoottu" => ["documentation"],
      "acdiilnnnootu" => ["unconditional"], "acceiilmmmors" => ["commercialism"],
      "accfiinnoosst" => ["confiscations"], "aafiilmmnnost" => ["inflammations"],
      "aaddeegnrrtuu" => ["undergraduate"], "ahimnopprssst" => ["sportsmanship"],
      "aabceilloortv" => ["collaborative"], "acehiiopssstt" => ["sophisticates"],
      "aeiinoopprrtx" => ["expropriation"], "ceimnnooprssu" => ["mispronounces"],
      "eegilmnnppstu" => ["supplementing"], "eehlnorrsttwy" => ["northwesterly"],
      "aeiillnnnotty" => ["intentionally"], "aceghinorrstt" => ["orchestrating"],
      "adeehhimoprrt" => ["hermaphrodite"], "aefiilnooprrt" => ["proliferation"],
      "aacilmnooprst" => ["proclamations"], "adeeilnnrttvy" => ["inadvertently"],
      "eeiiimopprrst" => ["improprieties"], "bciinnoorsttu" => ["contributions"],
      "aaiiilnnoprst" => ["inspirational"], "eiiiinnssttvy" => ["insensitivity"],
      "aceehiinorstt" => ["theoreticians"], "adegiimnnoprt" => ["predominating"],
      "aeeeimnnnrttt" => ["entertainment"], "aefilnooprsss" => ["professionals"],
      "aabeemmnrrsst" => ["embarrassment"], "cghiloopsssty" => ["psychologists"],
      "adeiimnnosstu" => ["mountainsides"], "ceeghiilnoprt" => ["helicoptering"],
      "aaiiilnorrtty" => ["irrationality"], "abceiilmnopst" => ["incompatibles"],
      "behlooorssttu" => ["troubleshoots"], "ceemnnnooprtu" => ["pronouncement"],
      "aabdeekorrsst" => ["skateboarders"], "aeeiillnsttxy" => ["existentially"],
      "aabeinssstttu" => ["substantiates"], "adeeimnorsttv" => ["demonstrative"],
      "cceffiiinnsuy" => ["insufficiency"], "aeeeimnnrsttt" => ["reinstatement"],
      "cehiilmossuvy" => ["mischievously"], "aaacegilmmnos" => ["megalomaniacs"],
      "egiillnnnssuw" => ["unwillingness"], "ceeiilmopttvy" => ["competitively"],
      "acfgiinnoortu" => ["configuration"], "aaceilmoprtvy" => ["comparatively"],
      "aceehimnssstt" => ["chastisements"], "abeeeinrrsttv" => ["invertebrates"],
      "cdgiiinnnostu" => ["discontinuing"], "aceilmmnoprty" => ["complimentary"],
      "aaceiinopprst" => ["appreciations"], "cdeiinnooprst" => ["preconditions"],
      "aeeegmnnrsstt" => ["estrangements"], "aaeeillnrttvy" => ["alternatively"],
      "ccceghiknorss" => ["crosschecking"], "aaceiiilmrstt" => ["materialistic"],
      "aacghilopprty" => ["typographical"], "cdiinnoorsttu" => ["introductions"],
      "deiinooopprst" => ["propositioned"], "cceeillnoorst" => ["recollections"],
      "eeelnoprssssw" => ["powerlessness"], "eeeeghnoorstu" => ["heterogeneous"],
      "cegiilmmnnopt" => ["complimenting"], "aceelmnpprssu" => ["upperclassmen"],
      "ccdeiinnnoost" => ["disconnection"], "aaaeilmnprrty" => ["parliamentary"],
      "aaddeelnrttuu" => ["unadulterated"], "aachlnopsstyy" => ["psychoanalyst"],
      "cciinnoopssuu" => ["inconspicuous"], "acegmnnoorssw" => ["congresswoman"],
      "abdeghinoorsu" => ["boardinghouse"], "adeghinoorsvw" => ["overshadowing"],
      "aiijnoopsttux" => ["juxtaposition"], "aacddeeeffint" => ["decaffeinated"],
      "addeeeehnrrtt" => ["tenderhearted"], "aceilmnnooptt" => ["contemplation"],
      "aaciiilnnostt" => ["nationalistic"], "aaceghoprrrst" => ["cartographers"],
      "eeiiilnnsstvy" => ["insensitively"], "eeeffinnosssv" => ["offensiveness"],
      "beeiiiilnssst" => ["sensibilities"], "aaeegimnrttuv" => ["argumentative"],
      "acdgiilnnoost" => ["consolidating"], "eeiinnnorsttv" => ["interventions"],
      "addiiiilntuvy" => ["individuality"], "adeeloopprtuv" => ["overpopulated"],
      "ddeimnoorsstu" => ["misunderstood"], "accghilloopsy" => ["psychological"],
      "eiimmnnoprsst" => ["imprisonments"], "aaciilnorsttu" => ["articulations"],
      "aabegilnorrtu" => ["gubernatorial"], "aabeiilmnorst" => ["abnormalities"],
      "aefgiilnoprrt" => ["proliferating"], "aelnnoopsstuy" => ["spontaneously"],
      "beefginrrsttu" => ["butterfingers"], "aabcdeefiprrt" => ["prefabricated"],
      "aeeiinnoqrstu" => ["questionnaire"], "ceeinoprrsssu" => ["repercussions"],
      "cceeeeeffnrsv" => ["effervescence"], "aaadeillqrrtu" => ["quadrilateral"],
      "acegilmnnoptt" => ["contemplating"], "aaegilnoprttx" => ["extrapolating"],
      "acdiilnnooost" => ["consolidation"], "adeghllnorsst" => ["strangleholds"],
      "acceginnnnotu" => ["countenancing"], "aeggiinnorrtt" => ["interrogating"],
      "aacceimmnnopt" => ["accompaniment"], "cdeeginnorstu" => ["countersigned"],
      "aeelmnpprstuy" => ["supplementary"], "aeeeglmnnnstt" => ["entanglements"],
      "eeghinorssstu" => ["righteousness"], "aabbehiilnntu" => ["uninhabitable"],
      "aeehlorssttuy" => ["southeasterly"], "abefllnoopstu" => ["tablespoonful"],
      "adeeginopprsv" => ["eavesdropping"], "ccceiimnoooos" => ["socioeconomic"],
      "cceiinnoosstu" => ["conscientious"], "achiiprssstty" => ["psychiatrists"],
      "aaceehillstty" => ["aesthetically"], "adeeiimnnortt" => ["determination"],
      "abcceeiilnnov" => ["inconceivable"], "aaacgillmmrty" => ["grammatically"],
      "acdeeilnpprru" => ["perpendicular"], "cceeinnnorstt" => ["interconnects"],
      "aagilmmnnosuy" => ["magnanimously"], "aceeilnnrssuy" => ["unnecessarily"],
      "adeiimnnnoost" => ["denominations"], "cceegiinnnost" => ["contingencies"],
      "aabceilmnnoop" => ["companionable"], "aeghnoopprrrs" => ["pornographers"],
      "ccehhiinoprsz" => ["schizophrenic"], "aagiimnopprtx" => ["approximating"],
      "adgilnnosttuy" => ["outstandingly"], "aaaceeenpprrs" => ["reappearances"],
      "aeegiilnnrrtt" => ["interrelating"], "aaccdeiinortt" => ["accreditation"],
      "cegiiinnorstu" => ["incongruities"], "aachimmnnopsy" => ["nymphomaniacs"],
      "aaccdgimmnoot" => ["accommodating"], "addeegiinrstt" => ["disintegrated"],
      "aacilmnoopttu" => ["computational"], "aeginoorrrstt" => ["interrogators"],
      "adegiiimnnrst" => ["administering"], "aceilnooprsss" => ["processionals"],
      "aeehlnorrstty" => ["northeasterly"], "aceelmnnorstu" => ["nomenclatures"],
      "acceginnnortt" => ["concentrating"], "acefiillprsuy" => ["superficially"],
      "acddeghilnnrr" => ["grandchildren"], "egilmnooosstt" => ["entomologists"],
      "ceeffiiilnnty" => ["inefficiently"], "abdeeegkllnow" => ["knowledgeable"],
      "ceeiinnorsstt" => ["intersections"], "aeiilnnooprtt" => ["interpolation"],
      "abeiiillnrtuy" => ["unreliability"], "abdeeiilnorst" => ["deliberations"],
      "aaciillssttty" => ["statistically"], "acgiinnooprrt" => ["incorporating"],
      "aabccelnnotuu" => ["unaccountable"], "aacegillrstty" => ["strategically"],
      "aaddeefghnrrt" => ["grandfathered"], "aaccillnsttyy" => ["syntactically"],
      "aefginooprrtw" => ["waterproofing"], "aeggiiinnsttv" => ["investigating"],
      "aceeimmmoortv" => ["commemorative"], "aaceiklmnopst" => ["kleptomaniacs"],
      "aabceeeillprr" => ["irreplaceable"], "acimmnnoosstu" => ["consummations"],
      "begiiiiillnty" => ["ineligibility"], "aciinnnoosttu" => ["continuations"],
      "aeegiiinsttvv" => ["investigative"], "abeeklmorrstu" => ["troublemakers"],
      "aceggiilnsttu" => ["gesticulating"], "acegiinrssttu" => ["resuscitating"],
      "abfiiiilllnty" => ["infallibility"], "aacfhimnprsst" => ["craftsmanship"],
      "aaceimnoopsst" => ["compassionate"], "aaccilmnostuu" => ["accumulations"],
      "abceflmnoortu" => ["uncomfortable"], "ccinnoorssttu" => ["constructions"],
      "ceilmnnooossu" => ["mononucleosis"], "eiinnoprrsttu" => ["interruptions"],
      "aadeefhhllrty" => ["halfheartedly"], "acdiilnooorst" => ["discoloration"],
      "acegilnnoorss" => ["congressional"], "biiiilmopssty" => ["impossibility"],
      "cdeegiinnorrs" => ["reconsidering"], "cdeegiinprsst" => ["disrespecting"],
      "dfgghiillnoot" => ["floodlighting"], "aaciiinsssttt" => ["statisticians"],
      "eeiimnprrsstt" => ["misinterprets"], "acceginnorttu" => ["counteracting"],
      "aefghhoorrstu" => ["thoroughfares"], "aaaeglnrttvxy" => ["extravagantly"],
      "achhiilnopprt" => ["philanthropic"], "aceeghhooprrr" => ["choreographer"],
      "aeehoprrssstt" => ["stratospheres"], "aaeiilnnnortt" => ["international"],
      "aaegiiilmntvy" => ["imaginatively"], "bdeefllooprtu" => ["bulletproofed"],
      "ceiinopprrsst" => ["prescriptions"], "ceeeinnqssstu" => ["quintessences"],
      "beefhimnrrstu" => ["refurbishment"], "acffiiinoortt" => ["fortification"],
      "aceeillnoptxy" => ["exceptionally"], "bbceegiknnrru" => ["rubbernecking"],
      "acdeefinnoort" => ["confederation"], "cceeeiinnnnov" => ["inconvenience"],
      "aaaddeginsstv" => ["disadvantages"], "acdehiiopsstt" => ["sophisticated"],
      "acceeinoprttv" => ["contraceptive"], "aabefhilnnosu" => ["unfashionable"],
      "acillmnnoooty" => ["monotonically"], "aehiilnoprsst" => ["relationships"],
      "ccegiimnnrtuv" => ["circumventing"], "aaccceeilnrrt" => ["recalcitrance"],
      "accceeelnnosv" => ["convalescence"], "eegiilmnoorst" => ["terminologies"],
      "adeeeggginrst" => ["desegregating"], "aaccdeillmstu" => ["miscalculated"],
      "adfgiiinsssty" => ["dissatisfying"], "aceeillmnossu" => ["miscellaneous"],
      "dddehnnooorrs" => ["rhododendrons"], "cceeeiimnnrss" => ["reminiscences"],
      "aaeiinoppprrt" => ["inappropriate"], "deeffiilnnrty" => ["indifferently"],
      "aaceinoprrtuy" => ["precautionary"], "aaceiilllrsty" => ["realistically"],
      "adeeeopprrssv" => ["eavesdroppers"], "acchimoopssty" => ["psychosomatic"],
      "acfiiinnoostt" => ["notifications"], "aaceehinstttu" => ["authenticates"],
      "aegiinopprrtx" => ["expropriating"], "egiimnnnrsttu" => ["instrumenting"],
      "acdfiiimnoost" => ["modifications"], "aaceghiloorst" => ["archaeologist"],
      "acehillnsttyy" => ["synthetically"], "aacfiiilnoqtu" => ["qualification"],
      "abdeeehknorrt" => ["brokenhearted"], "aacelmnpprssu" => ["upperclassman"],
      "dfginnoooprsu" => ["soundproofing"], "aiiillmnnostu" => ["illuminations"],
      "acdeelmnnrssu" => ["underclassmen"], "accdiiinorsty" => ["idiosyncratic"],
      "aceimnnoopsst" => ["compensations"], "bceeiilmpprty" => ["imperceptibly"],
      "addiiiilmnsuv" => ["individualism"], "aacceillnnost" => ["cancellations"],
      "acceelnnosstv" => ["convalescents"], "ceiiprrrssttw" => ["scriptwriters"],
      "acdeeilnorsty" => ["considerately"], "ceeilmnnoptty" => ["incompetently"],
      "acdhiioprsstt" => ["dictatorships"], "abeeeillmmnpt" => ["implementable"],
      "abceeefiiinrs" => ["beneficiaries"], "aabcdeekqrrtu" => ["quarterbacked"],
      "aeeilmnnnortv" => ["environmental"], "aaeeiinnrrssv" => ["anniversaries"],
      "aeeiiopprrrst" => ["proprietaries"], "aaegiiimnntuv" => ["unimaginative"],
      "adeiinorssstt" => ["dissertations"], "adegiiimnnsst" => ["disseminating"],
      "bceeeiilmpprt" => ["imperceptible"], "aefiiilmnssst" => ["semifinalists"],
      "ceeiinnoprstt" => ["interceptions"], "beiiiilopssst" => ["possibilities"],
      "aaeegiimnrrrt" => ["intermarriage"], "aaeegiimnrstv" => ["vegetarianism"],
      "aabdeehiilrtt" => ["rehabilitated"], "eghhllossttuy" => ["thoughtlessly"],
      "aceeilmnopttv" => ["contemplative"], "acilrrsstttuu" => ["structuralist"],
      "acilnnoossttu" => ["consultations"], "aaeeiklmnsstt" => ["statesmanlike"],
      "acdeinnnoosst" => ["condensations"], "abeeioorrsstv" => ["observatories"],
      "abeeeiilrrrtv" => ["irretrievable"], "ceeiinoprsstt" => ["receptionists"],
      "eegiillnnnttu" => ["unintelligent"], "aabcclnnotuuy" => ["unaccountably"],
      "aceinnnoorttv" => ["contravention"], "aabcdehorrsty" => ["carbohydrates"],
      "aeghhoopprrst" => ["photographers"], "ceefiinoprstt" => ["perfectionist"],
      "aacchiinnorst" => ["anachronistic"], "aaciilloprtty" => ["patriotically"],
      "abeghhkorrstu" => ["breakthroughs"], "acehlmmnoostw" => ["commonwealths"],
      "aacgiilmnrttu" => ["matriculating"], "beeimnnosssuw" => ["businesswomen"],
      "abdeeiilnnpss" => ["indispensable"], "aacffiiilnost" => ["falsification"],
      "degiinopsssss" => ["dispossessing"], "aabeiiklmrtty" => ["marketability"],
      "abdeeflnnnoru" => ["nonrefundable"], "abdgiinnorstu" => ["subordinating"],
      "adeegiimnprtt" => ["premeditating"], "eeeiilnnpsvxy" => ["inexpensively"],
      "aacceiinnorrt" => ["incarceration"], "aacdeehintttu" => ["authenticated"],
      "aabillnssttuy" => ["substantially"], "abeehilmnsstt" => ["establishment"],
      "adeggiilnnnst" => ["disentangling"], "eggiiilmnnnrt" => ["intermingling"],
      "acdiillnnooty" => ["conditionally"], "aacfgiiimnnot" => ["magnification"],
      "ccilnnoossuuy" => ["unconsciously"], "acfiilnnottuy" => ["functionality"],
      "aaeiiilnnostt" => ["nationalities"], "accceimnrsstu" => ["circumstances"],
      "aefiimnnortuv" => ["uninformative"], "abfiiiloprtty" => ["profitability"],
      "aceiinnnorstu" => ["renunciations"], "aghiilnnossty" => ["astonishingly"],
      "aceemnnnnostu" => ["announcements"], "aeflnnorttuuy" => ["unfortunately"],
      "accdeeefinors" => ["confederacies"], "aegillmrssttu" => ["metallurgists"],
      "aaaccdeiinptt" => ["incapacitated"], "aeeghilnnrtty" => ["threateningly"],
      "cceinnoossssu" => ["consciousness"], "bdeghhoorrstu" => ["thoroughbreds"],
      "deefgiimnrstu" => ["disfigurement"], "acdeiiimnrsst" => ["discriminates"],
      "aagiinnorstuu" => ["inaugurations"], "aaccellprstuy" => ["spectacularly"],
      "aaacfillnstty" => ["fantastically"], "aaaagilmmnost" => ["amalgamations"],
      "adeeeimorsttv" => ["overestimated"], "aiiimnooprstv" => ["improvisation"],
      "abcginooorrrt" => ["corroborating"], "aciiillnnrsty" => ["intrinsically"],
      "addeginnnrstu" => ["understanding"], "eiinoopprsttu" => ["opportunities"],
      "acceeimmnotux" => ["excommunicate"], "aghiiilnprstt" => ["hairsplitting"],
      "eeeiipqrrsstu" => ["prerequisites"], "aeeeiprrsstvv" => ["preservatives"],
      "ceefhkmorrstu" => ["motherfuckers"], "abbeiiiloprst" => ["probabilities"],
      "eemnnooppsstt" => ["postponements"], "bdeeimnrssstu" => ["disbursements"],
      "acdeiinnnostu" => ["denunciations"], "aabcceiilptty" => ["acceptability"],
      "cceimmooprrtu" => ["microcomputer"], "aacdeiillmrty" => ["diametrically"],
      "aadeiinopssst" => ["dispassionate"], "aciiiimnnnort" => ["incrimination"],
      "ccdeeinnnooss" => ["condescension"], "aachiillnnotu" => ["hallucination"],
      "abceiinorsstt" => ["obstetricians"], "aacfiiilmnopt" => ["amplification"],
      "aaceijkrssttt" => ["straitjackets"], "ceghilnoosstt" => ["technologists"],
      "acehinoorrstt" => ["orchestration"], "bceeimmossttu" => ["subcommittees"],
      "acciilmnoopst" => ["complications"], "ceiilnrsttuvy" => ["instructively"],
      "aacceeilnorst" => ["accelerations"], "aaceiinnnorrt" => ["reincarnation"],
      "abcdeeilnprtu" => ["unpredictable"], "abeekorrssstt" => ["breaststrokes"],
      "aeiiinnrssttv" => ["intransitives"], "acceinnoorsst" => ["consecrations"],
      "aceehlmnorrtu" => ["thermonuclear"], "eeilnnopsssst" => ["pointlessness"],
      "aacehillnttuy" => ["authentically"], "aaaabdilmorss" => ["ambassadorial"],
      "aaacceinnqstu" => ["acquaintances"], "abiiilnoosstt" => ["abolitionists"]}
    |> Map.get(string_id)
  end

  def valid_ids do
    ["aadiimnorrstt", "acilmnooopsst", "acdeiinnorstt", "acefghiinnnrs",
     "abcflmnoortuy", "acceehhloorst", "abeiiiilnttvy", "aceillmmrstyy",
     "aaccdimmnooot", "cceiimnnoopst", "aiillnnortuvy", "aaccdeilnootu",
     "ccdgiimnnostu", "aeeinrssstttv", "ccdegiinnorst", "adehnorrsttww",
     "aeeimnnorrstu", "egiimnopprssu", "aaehiiimnnstt", "accdeeennnrst",
     "acehhiinoprsz", "aaccegiinnrrt", "aacfiiimnorst", "aeeilnnoprrst",
     "cgiimnnorsstu", "aceeinorsstvv", "aagilnnorsttu", "ceegmnnoorssw",
     "aeeillnnoptxy", "beeeimmnrrstu", "adeegmnnrrstu", "eegilmooorstt",
     "aaagiilnorttv", "aehilmoostuxy", "acfiiimnoortt", "ceeinoorrsstv",
     "hnorrstttuuwy", "eegiinnnrsttu", "ceeinorsstttu", "eiimnoorssstt",
     "aaahiimnnrstu", "bdeeiirrssttu", "aeiilnoopprst", "aaeffiilmrtvy",
     "deeeeimnprrst", "aaiimnoopprtx", "aaeeiinnrrstv", "ddeeeiinrsstt",
     "aceeiiilprstu", "cdeeinorstttu", "aabdegiknorst", "eegiinnprrsst",
     "acdegiimnostt", "addeeegmnrrry", "acdefgillrsuy", "efgghiiilnttw",
     "acegiimmnorst", "aaaiinnosssst", "cdeeiiimnrstt", "aegiinorssttv",
     "aaceeiinorrst", "abbciiiloprst", "aacdeglnorttu", "abcceiiilssty",
     "aabcgillnoort", "aegiinnoorrtt", "eeknoopprssss", "cceeemmmnnost",
     "aacfiinossstt", "cdfghiilnoopr", "adeejmnrssttu", "acghiilloopsy",
     "cceiinnnossty", "aceeiloprstty", "ccdegiinnnost", "aceegiinnsstt",
     "ceeiijnnorstt", "aceeilnnoqstu", "adeeeiimnnrtt", "aadefllmnntuy",
     "abeeeinorrrtv", "aadeinorrrtxy", "cdeimnnooprsu", "ceiimmnoorsss",
     "accdeeilnopsy", "aaiilmnnopstu", "abeeeginrrrtv", "acgghiklnostu",
     "acdeeennopprr", "acfgiiiinnnst", "acdgiinnosttu", "eeffglnorsstu",
     "abdeglnorsttu", "aaadddeginstv", "aeeeinrsssstv", "acdeeiinnorst",
     "acegimmmnoort", "aaegiimmnnrst", "abdeiinnorstu", "adeefinoorstt",
     "aaeinnnossttu", "aabbddeegilor", "eeiilmnpsssuv", "eeeennprrrstu",
     "eiinoprsssttu", "aeeiimnnorttx", "aaeegimmmnnst", "aceinnnoorstt",
     "cdeegiinorrsv", "aagiinoppprrt", "aaeeelmmnprtt", "adiiilnrssttu",
     "ddeghiiinsstu", "defgginnoorru", "adeeimnrsstuv", "behiiiimnostx",
     "aceiimmnoorst", "aegiimnnoprst", "adeehhiorrsss", "acgghhinnorst",
     "deeghilmooost", "eeeellnpsssss", "adeeiimnoprtt", "aaciilnopsttu",
     "aeeinnorsstuv", "cceeiinnossst", "acfgiiilnoort", "aeiilnnnnottu",
     "acfgiiilnnsty", "ceefiimnoprst", "aaccciiilmntt", "eegghinnnrstt",
     "ccgiinorrssss", "abelllmnoossy", "aefiiiilmnnst", "aceiinoprrstt",
     "cegiinnooprss", "aahiinopsstxy", "aacceginnnott", "ddeeeeimnprrt",
     "cdeeiiorssstu", "ccdeehilorrty", "aaciimnnnoott", "aiimnnorsssst",
     "cdeennooprrst", "cgiiimmnnooss", "cdeefilprsstu", "ciinoopprsttu",
     "ciinoopprrsst", "acgiiillnnstt", "aaeeegmnnrrrt", "cdeeefinorttu",
     "aegikllnorrst", "abeeghiknorsu", "aaaiilnorsttt", "aeeeimorssttv",
     "acfiiijnosttu", "behiiiinosttx", "eeghiinrsstux", "accdgiinnortt",
     "aacfgiiinortt", "deeiiinoqrstu", "aceilnoorrstv", "aiiilnnostttu",
     "adeeeghlmmrss", "ddeginnrstuuy", "deeeegiprrrst", "eehlorssttuwy",
     "abgiimnnorrst", "aafiilmnnoort", "ccilmoorsstty", "aaelnnprrstty",
     "ccdeimnoorstu", "aacgiimnnnott", "accdiinnoortt", "cdeiiilnsttvy",
     "aabciiillppty", "achhiilloopps", "acfinnnooortt", "aaccegillorty",
     "aaiinooppprrt", "aadegoprssttu", "aacceinnnoott", "acdeghiinnnst",
     "eeehilmnnprst", "aeeloopprstuv", "aagilnnnprstt", "aaceehilnprtt",
     "abefiijlnstuu", "aacdeeeffinst", "ccddeeginnnos", "acdeeeilnssst",
     "eeegiimnnprtx", "ceiiilnnsttvy", "abbcghiiilopr", "adehorssttuww",
     "aaehiiortttuv", "abeiillnrtuvy", "deeeginnortvx", "aceeegillnrty",
     "adeeeffiinrtt", "eegiilnnrstty", "cefilnoprrtuy", "behiiiloprtvy",
     "aaacdilloprxy", "aaefgimnnortt", "aabcillnooort", "ghiilnooorstt",
     "aceeilorrttvy", "deghiiinssstu", "aegiinorrsstt", "bceeeeghrrssu",
     "abeimnnosssuw", "adeeegginorst", "aeggiinorrttu", "adefghinoorsw",
     "accghillnooor", "acgiimmnoorrs", "aeilnoorrtuvy", "aaeilmopprtxy",
     "aeefggiinrrrt", "aeeeiilnsttuv", "deeeelmnoprtv", "ciinnoosstttu",
     "agghhinoopprt", "aaaaehilnpprr", "adeeeimnrsttv", "acchiooprrrst",
     "beegloorrsttt", "beeeiilprrrss", "deeeghilnnntu", "ceeginoprrstt",
     "cdehknrrsttuu", "aacceiiorrsst", "eegiloprrssvy", "bdiiinorssttu",
     "ceeelmmorsttu", "ddeiiillnossu", "adiiiilmrssty", "cceeinnoopprt",
     "ceeinorrrsstu", "cdeiiinnorsst", "cceeilnostuvy", "acdeghiimnnrs",
     "aegiiinnosttv", "aceiiinopprtt", "aaagiinnsssst", "abbceeijlnoot",
     "aegggiinrrttu", "acceinnooprtt", "accghiilmnops", "cceeilnoorttu",
     "cciinnoorsstt", "acfiimnnoorst", "aaefilnqrrstu", "acdeimnnnoost",
     "adeeghiinnrst", "bddeeiirrsttu", "abbbehlmorstu", "ccceeefimnrru",
     "acdefilmnnotu", "aegghiinnrstt", "adeeiinoorrtt", "aabdeinsstttu",
     "abdeegkllnowy", "ceeeeffinsstv", "aaccfiiilnort", "eiilmnoqrstuv",
     "adeimnnoorstt", "addiiiilnstuv", "aghilnooortty", "aaaccillrssty",
     "ccilnoopssuuy", "aaciiinopprtt", "aciinnoprrstt", "aciimnnoosstu",
     "acceinnnoortt", "abciiilmoptty", "aadehnorrsttw", "aaddegghnrrtu",
     "aaeiloppprrty", "aeefgiinorrrt", "aaaceegnrstvx", "aaehimnpssstt",
     "acdeefginnort", "beiilnoprrssy", "aeggiimnssttu", "cceegiinnoprv",
     "cdeginnooprrs", "aaacehiimmntt", "aeeinnoprsstt", "aaccdeimnnopu",
     "eeknnoopssstu", "efgghiilnnrty", "abelnopprstuu", "acilllmrttuuu",
     "aciinnoooprrt", "aabghiooprtuy", "aaiillnnosstt", "ceghinorstttu",
     "accegiinoprrt", "acdfilnnostuy", "abgilmnosuuuy", "eiioprrssttuu",
     "cdeiimnooopst", "adeeeimnrsttu", "acgiiiimnnnrt", "abdehhnosssuu",
     "acegiiinpprtt", "aeegiimnnrttx", "aacdiiiorttvy", "aeiimnnooprst",
     "adeeghprssttu", "accefiiinortt", "acdeeilmnpsst", "eeiiiinsssttv",
     "acegghiinnnrt", "aabiilnnssttu", "acehhmmnrstuy", "achillorrttuu",
     "acddeiinnortt", "befiiiillntxy", "aceiinorssttu", "eeilnoprsttuy",
     "adeeeiimnrstt", "acdeimmnnoost", "eeeimnprrssst", "aabelmmnosswy",
     "aceelmmnoprty", "aeggimmnoprrr", "aeghhiprssuwy", "aaceiilnprstt",
     "aaacceiinpstt", "aabcceeirrsuu", "aaacillmottuy", "aegilmnorsstu",
     "cddeeiinnoort", "eiioprsssttuu", "acdeegimmnnor", "aaacdeeinpprs",
     "adegiimmnnrst", "adefillssttuy", "aacceillmsstu", "aeehinnopprss",
     "adiiillnosstt", "aacegilnnpstu", "accgiimmnnotu", "accefgiiinrtt",
     "aadiillnortty", "aacceknortttu", "acdeeimnorstu", "aiillnooprsvy",
     "ceghhiiloprsy", "accdinoorrtty", "aeiinnopssstx", "acceehirrsttu",
     "aaacilnnrsttt", "abbcegiklnrry", "deefgiinnprrt", "accefiiinopst",
     "aaciiinnopstt", "aaeilnooprttx", "acccdeimnrstu", "abeeiilrrrtvy",
     "deeginnorsuvz", "beeeehilnprrs", "acehhopprstyy", "eiiimnnorssst",
     "afgiiilnnrtuy", "aaacgilmmnrtu", "aehimmooprsst", "aabeeghiknrrt",
     "aeinooopprrtt", "acceeilorsttt", "aacghiillnntu", "aacefmnrrstuu",
     "deefiilnnrstu", "aceimmmnooort", "bciinoprssstu", "ceemopprrstuu",
     "abeelmmnosswy", "acdeefhhiknrs", "aacdelmnnrssu", "aegginnrrssst",
     "acccdeeeinnns", "acciimmnnootu", "cdeinooprrstu", "aceeglmnoorst",
     "cdeeeeiinnprx", "aceeiilnrttvy", "aacdeillnotuy", "aaeegginorstx",
     "aeeiilnoprsst", "efgimnooprrtu", "ceeiinoprsttv", "egghiiinnstux",
     "aceehillortty", "cdiiinnosttuy", "aabcllooorrst", "abcdehiilnnrr",
     "acdeeghhooprr", "ceegilmmnnopt", "acceinoopprtu", "cdeeeiilnnqsu",
     "aeeimnorrsttx", "cdegiinnnostt", "dhinooorssttt", "aabbeiinorstv",
     "cdeennrrrstuu", "acginoprssstt", "adeegiinrsstt", "aiillnorssttu",
     "aeeghnoprrsst", "aaciilmnorttu", "ddeeeilnnnpty", "aghhllmooopty",
     "aceeegmnnortu", "adeeellmorrst", "aabeehiilrstt", "acceiimmnotuv",
     "acegginnoorst", "aaahiinorrttu", "ceeeioprrsttv", "abeehiilnstux",
     "aaeillnnossty", "cceegilnorttu", "eegiilllnntty", "adeilmnnoprty",
     "adeeeimnnortu", "ceegilmmnottu", "agiiinnnorstt", "abeefglnorttu",
     "aeilmnnrssttu", "aaefiimnnostt", "adeegiinorrtt", "aceehmnopprrt",
     "cdeeefilnsstu", "acdeeikloopss", "ehiorrrstttuw", "achiimnnoopps",
     "adfgiiilnqsuy", "aaceglnorsttu", "acdegiilllooy", "cdfgiimnoorst",
     "aabceinrrsstt", "ademnoorrsstt", "eefgiimnnnrst", "acdeggiklnnow",
     "ceeefinorrttu", "degiilnrsssty", "abbcdeiilnrsy", "adgiiinnoppst",
     "bbcgghiilnntu", "accdeeiinprss", "aaeillnooprty", "dfillrssttuuy",
     "aeghimnorssuw", "eiilnoqrsttuv", "aceillnnoostt", "adeiinnopssst",
     "aagiiklnnpsty", "cfghilmnooorr", "aacgilllnosty", "aaccehilrrttu",
     "eghiiimnoprsv", "aeeehlorsstux", "adeiiimnnosst", "acdeeeiossttv",
     "aabbdeefglrst", "ccciiimnorssu", "addeimnnrsstu", "aaceinoprrstt",
     "ceginrrrsttuu", "ceehimnnooprs", "ceiinnorrsstu", "aacdeiilnortv",
     "abcinoooorrrt", "acdeeglmnoort", "dehmnorrssttu", "aaiillmnnottu",
     "aceinnoorsstv", "aabelnoprrstt", "eeeghilmnnntt", "aceeilllnsttu",
     "aadehorssttuw", "aaelnprrsstuu", "aabceefiprrst", "aeimnooprrsst",
     "acdeiinorrsty", "acddeiiimnrst", "cdeeiilnoprst", "aacfgimnnrtuu",
     "aaddgginnnrst", "acehiiprttvyy", "adeeegimnrsst", "giinnooopprrt",
     "aegiimnnrrrty", "cdeeghimnnopr", "acdefiinnsstt", "adegimnnorstt",
     "aehhiopprstyy", "abdiinnoorstu", "aeehmmooprsst", "cfimnnnooorst",
     "eghiiilnnqrsu", "aceegillmorty", "abceeiilnnnst", "bdeeginnorruv",
     "acceghillnoot", "deghiiiinnrst", "aciinnnooprtu", "abbiiilmoprty",
     "aacegiinnnrrt", "aeeiiilmnprrs", "achhiimnoppss", "beeehillmmnst",
     "ailnooopprrst", "acdeiinnoorst", "eefghiilrsttw", "ccdeenorrsttu",
     "cceiimnnortuv", "aeginnorrssst", "aeefgiorrrrst", "eeeghimnosstu",
     "acefgiilmnnty", "befgiiilnrstu", "abbcdeeiilnrs", "ceeefimnnorrt",
     "aiilnooopprst", "aacgiiinpprtt", "beeiilnoprrss", "ceeehimnoprsv",
     "aceeiinnrsttu", "aciilllmooqsu", "accdhhinoopry", "biinossstttuu",
     "adeegiknnrrst", "aefghhorstttu", "cddeeeennprtu", "acdeimnnoottu",
     "acdiilnnnootu", "acceiilmmmors", "accfiinnoosst", "aafiilmmnnost",
     "aaddeegnrrtuu", "ahimnopprssst", "aabceilloortv", "acehiiopssstt",
     "aeiinoopprrtx", "ceimnnooprssu", "eegilmnnppstu", "eehlnorrsttwy",
     "aeiillnnnotty", "aceghinorrstt", "adeehhimoprrt", "aefiilnooprrt",
     "aacilmnooprst", "adeeilnnrttvy", "eeiiimopprrst", "bciinnoorsttu",
     "aaiiilnnoprst", "eiiiinnssttvy", "aceehiinorstt", "adegiimnnoprt",
     "aeeeimnnnrttt", "aefilnooprsss", "aabeemmnrrsst", "cghiloopsssty",
     "adeiimnnosstu", "ceeghiilnoprt", "aaiiilnorrtty", "abceiilmnopst",
     "behlooorssttu", "ceemnnnooprtu", "aabdeekorrsst", "aeeiillnsttxy",
     "aabeinssstttu", "adeeimnorsttv", "cceffiiinnsuy", "aeeeimnnrsttt",
     "cehiilmossuvy", "aaacegilmmnos", "egiillnnnssuw", "ceeiilmopttvy",
     "acfgiinnoortu", "aaceilmoprtvy", "aceehimnssstt", "abeeeinrrsttv",
     "cdgiiinnnostu", "aceilmmnoprty", "aaceiinopprst", "cdeiinnooprst",
     "aeeegmnnrsstt", "aaeeillnrttvy", "ccceghiknorss", "aaceiiilmrstt",
     "aacghilopprty", "cdiinnoorsttu", "deiinooopprst", "cceeillnoorst",
     "eeelnoprssssw", "eeeeghnoorstu", "cegiilmmnnopt", "aceelmnpprssu",
     "ccdeiinnnoost", "aaaeilmnprrty", "aaddeelnrttuu", "aachlnopsstyy",
     "cciinnoopssuu", "acegmnnoorssw", "abdeghinoorsu", "adeghinoorsvw",
     "aiijnoopsttux", "aacddeeeffint", "addeeeehnrrtt", "aceilmnnooptt",
     "aaciiilnnostt", "aaceghoprrrst", "eeiiilnnsstvy", "eeeffinnosssv",
     "beeiiiilnssst", "aaeegimnrttuv", "acdgiilnnoost", "eeiinnnorsttv",
     "addiiiilntuvy", "adeeloopprtuv", "ddeimnoorsstu", "accghilloopsy",
     "eiimmnnoprsst", "aaciilnorsttu", "aabegilnorrtu", "aabeiilmnorst",
     "aefgiilnoprrt", "aelnnoopsstuy", "beefginrrsttu", "aabcdeefiprrt",
     "aeeiinnoqrstu", "ceeinoprrsssu", "cceeeeeffnrsv", "aaadeillqrrtu",
     "acegilmnnoptt", "aaegilnoprttx", "acdiilnnooost", "adeghllnorsst",
     "acceginnnnotu", "aeggiinnorrtt", "aacceimmnnopt", "cdeeginnorstu",
     "aeelmnpprstuy", "aeeeglmnnnstt", "eeghinorssstu", "aabbehiilnntu",
     "aeehlorssttuy", "abefllnoopstu", "adeeginopprsv", "ccceiimnoooos",
     "cceiinnoosstu", "achiiprssstty", "aaceehillstty", "adeeiimnnortt",
     "abcceeiilnnov", "aaacgillmmrty", "acdeeilnpprru", "cceeinnnorstt",
     "aagilmmnnosuy", "aceeilnnrssuy", "adeiimnnnoost", "cceegiinnnost",
     "aabceilmnnoop", "aeghnoopprrrs", "ccehhiinoprsz", "aagiimnopprtx",
     "adgilnnosttuy", "aaaceeenpprrs", "aeegiilnnrrtt", "aaccdeiinortt",
     "cegiiinnorstu", "aachimmnnopsy", "aaccdgimmnoot", "addeegiinrstt",
     "aacilmnoopttu", "aeginoorrrstt", "adegiiimnnrst", "aceilnooprsss",
     "aeehlnorrstty", "aceelmnnorstu", "acceginnnortt", "acefiillprsuy",
     "acddeghilnnrr", "egilmnooosstt", "ceeffiiilnnty", "abdeeegkllnow",
     "ceeiinnorsstt", "aeiilnnooprtt", "abeiiillnrtuy", "abdeeiilnorst",
     "aaciillssttty", "acgiinnooprrt", "aabccelnnotuu", "aacegillrstty",
     "aaddeefghnrrt", "aaccillnsttyy", "aefginooprrtw", "aeggiiinnsttv",
     "aceeimmmoortv", "aaceiklmnopst", "aabceeeillprr", "acimmnnoosstu",
     "begiiiiillnty", "aciinnnoosttu", "aeegiiinsttvv", "abeeklmorrstu",
     "aceggiilnsttu", "acegiinrssttu", "abfiiiilllnty", "aacfhimnprsst",
     "aaceimnoopsst", "aaccilmnostuu", "abceflmnoortu", "ccinnoorssttu",
     "ceilmnnooossu", "eiinnoprrsttu", "aadeefhhllrty", "acdiilnooorst",
     "acegilnnoorss", "biiiilmopssty", "cdeegiinnorrs", "cdeegiinprsst",
     "dfgghiillnoot", "aaciiinsssttt", "eeiimnprrsstt", "acceginnorttu",
     "aefghhoorrstu", "aaaeglnrttvxy", "achhiilnopprt", "aceeghhooprrr",
     "aeehoprrssstt", "aaeiilnnnortt", "aaegiiilmntvy", "bdeefllooprtu",
     "ceiinopprrsst", "ceeeinnqssstu", "beefhimnrrstu", "acffiiinoortt",
     "aceeillnoptxy", "bbceegiknnrru", "acdeefinnoort", "cceeeiinnnnov",
     "aaaddeginsstv", "acdehiiopsstt", "acceeinoprttv", "aabefhilnnosu",
     "acillmnnoooty", "aehiilnoprsst", "ccegiimnnrtuv", "aaccceeilnrrt",
     "accceeelnnosv", "eegiilmnoorst", "adeeeggginrst", "aaccdeillmstu",
     "adfgiiinsssty", "aceeillmnossu", "dddehnnooorrs", "cceeeiimnnrss",
     "aaeiinoppprrt", "deeffiilnnrty", "aaceinoprrtuy", "aaceiilllrsty",
     "adeeeopprrssv", "acchimoopssty", "acfiiinnoostt", "aaceehinstttu",
     "aegiinopprrtx", "egiimnnnrsttu", "acdfiiimnoost", "aaceghiloorst",
     "acehillnsttyy", "aacfiiilnoqtu", "abdeeehknorrt", "aacelmnpprssu",
     "dfginnoooprsu", "aiiillmnnostu", "acdeelmnnrssu", "accdiiinorsty",
     "aceimnnoopsst", "bceeiilmpprty", "addiiiilmnsuv", "aacceillnnost",
     "acceelnnosstv", "ceiiprrrssttw", "acdeeilnorsty", "ceeilmnnoptty",
     "acdhiioprsstt", "abeeeillmmnpt", "abceeefiiinrs", "aabcdeekqrrtu",
     "aeeilmnnnortv", "aaeeiinnrrssv", "aeeiiopprrrst", "aaegiiimnntuv",
     "adeiinorssstt", "adegiiimnnsst", "bceeeiilmpprt", "aefiiilmnssst",
     "ceeiinnoprstt", "beiiiilopssst", "aaeegiimnrrrt", "aaeegiimnrstv",
     "aabdeehiilrtt", "eghhllossttuy", "aceeilmnopttv", "acilrrsstttuu",
     "acilnnoossttu", "aaeeiklmnsstt", "acdeinnnoosst", "abeeioorrsstv",
     "abeeeiilrrrtv", "ceeiinoprsstt", "eegiillnnnttu", "aabcclnnotuuy",
     "aceinnnoorttv", "aabcdehorrsty", "aeghhoopprrst", "ceefiinoprstt",
     "aacchiinnorst", "aaciilloprtty", "abeghhkorrstu", "acehlmmnoostw",
     "aacgiilmnrttu", "beeimnnosssuw", "abdeeiilnnpss", "aacffiiilnost",
     "degiinopsssss", "aabeiiklmrtty", "abdeeflnnnoru", "abdgiinnorstu",
     "adeegiimnprtt", "eeeiilnnpsvxy", "aacceiinnorrt", "aacdeehintttu",
     "aabillnssttuy", "abeehilmnsstt", "adeggiilnnnst", "eggiiilmnnnrt",
     "acdiillnnooty", "aacfgiiimnnot", "ccilnnoossuuy", "acfiilnnottuy",
     "aaeiiilnnostt", "accceimnrsstu", "aefiimnnortuv", "abfiiiloprtty",
     "aceiinnnorstu", "aghiilnnossty", "aceemnnnnostu", "aeflnnorttuuy",
     "accdeeefinors", "aegillmrssttu", "aaaccdeiinptt", "aeeghilnnrtty",
     "cceinnoossssu", "bdeghhoorrstu", "deefgiimnrstu", "acdeiiimnrsst",
     "aagiinnorstuu", "aaccellprstuy", "aaacfillnstty", "aaaagilmmnost",
     "adeeeimorsttv", "aiiimnooprstv", "abcginooorrrt", "aciiillnnrsty",
     "addeginnnrstu", "eiinoopprsttu", "acceeimmnotux", "aghiiilnprstt",
     "eeeiipqrrsstu", "aeeeiprrsstvv", "ceefhkmorrstu", "abbeiiiloprst",
     "eemnnooppsstt", "bdeeimnrssstu", "acdeiinnnostu", "aabcceiilptty",
     "cceimmooprrtu", "aacdeiillmrty", "aadeiinopssst", "aciiiimnnnort",
     "ccdeeinnnooss", "aachiillnnotu", "abceiinorsstt", "aacfiiilmnopt",
     "aaceijkrssttt", "ceghilnoosstt", "acehinoorrstt", "bceeimmossttu",
     "acciilmnoopst", "ceiilnrsttuvy", "aacceeilnorst", "aaceiinnnorrt",
     "abcdeeilnprtu", "abeekorrssstt", "aeiiinnrssttv", "acceinnoorsst",
     "aceehlmnorrtu", "eeilnnopsssst", "aacehillnttuy", "aaaabdilmorss",
     "aaacceinnqstu", "abiiilnoosstt"]
    |> Enum.into(HashSet.new)
  end
end
