defmodule Jumble.ScowlDict.Size40.Length12 do
  def get(string_id) do
    %{"aaiillnnostt" => ["installation"], "abciimnnoost" => ["combinations"],
      "aacilmnooprt" => ["proclamation"], "cilnnoostuuy" => ["continuously"],
      "degllnorssuw" => ["groundswells"], "aeehllmnnopy" => ["phenomenally"],
      "aabefgiknrst" => ["breakfasting"], "abcgiikllnst" => ["blacklisting"],
      "ddeelnnopsty" => ["despondently"], "aaciilnopttu" => ["capitulation"],
      "adeeeeggrsst" => ["desegregates"], "eeginopprstv" => ["overstepping"],
      "deeginnrrrsu" => ["surrendering"], "ceerrrssttuu" => ["restructures"],
      "bcinoorrsttu" => ["contributors"], "aaccehhiilrr" => ["hierarchical"],
      "aeeiopprrstx" => ["expropriates"], "acceilmnnoou" => ["uneconomical"],
      "aacdhiioprss" => ["aphrodisiacs"], "abcdeooorrrt" => ["corroborated"],
      "ceelnnoqstuy" => ["consequently"], "adeeimnrstuv" => ["misadventure"],
      "aaccehhmosst" => ["stomachaches"], "acdegiiknrst" => ["sidetracking"],
      "ccdeeelorttu" => ["electrocuted"], "adeiinorsstt" => ["dissertation"],
      "aefnnorsttuu" => ["unfortunates"], "aeimnooprrst" => ["impersonator"],
      "aeeggilnosst" => ["genealogists"], "aabbdeekrsst" => ["breadbaskets"],
      "abcdeilnorsy" => ["considerably"], "adeghmnorrst" => ["grandmothers"],
      "accceimnrstu" => ["circumstance"], "aeeemrssssst" => ["seamstresses"],
      "acdeeiiinnrs" => ["incendiaries"], "aacehoprsstt" => ["catastrophes"],
      "eehlnrsssstu" => ["ruthlessness"], "aeeinorrsstv" => ["reservations"],
      "acceimmnostu" => ["communicates"], "abeinoorsstv" => ["observations"],
      "aaceijllmsty" => ["majestically"], "acdeiinnnotu" => ["denunciation"],
      "aceiinoprrtt" => ["practitioner"], "aefmnorrrsst" => ["transformers"],
      "cdeginoorrvw" => ["overcrowding"], "aacdeillnpty" => ["pedantically"],
      "aegiilrrrtuy" => ["irregularity"], "aceghhnorsst" => ["shortchanges"],
      "aacegiinnrst" => ["ascertaining"], "cdeiinoprsst" => ["descriptions"],
      "efgiinnoprsy" => ["personifying"], "eeginoprstty" => ["stereotyping"],
      "bdeeefiilnns" => ["indefensible"], "ccdeehilpssy" => ["psychedelics"],
      "ceinnosstttu" => ["constituents"], "acehillorrty" => ["rhetorically"],
      "aabeeelnprtu" => ["unrepeatable"], "aacdeilmrttu" => ["matriculated"],
      "deefiiinnort" => ["redefinition"], "cginoopprstu" => ["outcroppings"],
      "acdeegiinprt" => ["depreciating"], "cdefhlmooorr" => ["chloroformed"],
      "eeginoprssss" => ["repossessing"], "aaccdemmoost" => ["accommodates"],
      "aaceghiloprs" => ["archipelagos"], "begiiilllnty" => ["intelligibly"],
      "ccddeimnostu" => ["misconducted"], "aceilnnnootv" => ["conventional"],
      "adeeersssstw" => ["stewardesses"], "ahimoopppstu" => ["hippopotamus"],
      "ceehinoorrss" => ["rhinoceroses"], "aaceinrtttuv" => ["unattractive"],
      "accgiillooos" => ["sociological"], "cceeennoqssu" => ["consequences"],
      "acehiinssttu" => ["enthusiastic"], "adeeffiilnrt" => ["differential"],
      "aabcghiilopr" => ["biographical"], "abdegiikmnrs" => ["disembarking"],
      "aeefgiorrrrt" => ["refrigerator"], "aaefilnqrrtu" => ["quarterfinal"],
      "aegiilmnnrst" => ["streamlining"], "aehimnnosstt" => ["astonishment"],
      "aiillnorsttu" => ["illustration"], "aaeeiinnrrtv" => ["veterinarian"],
      "deeeinprrsst" => ["interspersed"], "aefgillmnnuy" => ["meaningfully"],
      "accdeeinnnst" => ["incandescent"], "accceeeinqsu" => ["acquiescence"],
      "eiinoprssttu" => ["superstition"], "aacceilnrrtt" => ["recalcitrant"],
      "bghiillnsttu" => ["bullshitting"], "accfiinnoost" => ["confiscation"],
      "adeeimnoprst" => ["impersonated", "predominates"],
      "acdeffgiinst" => ["disaffecting"], "achiiprsstty" => ["psychiatrist"],
      "aachimmnnopy" => ["nymphomaniac"], "cddeeinnostt" => ["discontented"],
      "acffiillnouy" => ["unofficially"], "addeeiimnsst" => ["disseminated"],
      "aginnoprrstt" => ["transporting"], "eeilmooprsst" => ["metropolises"],
      "aeeillnqtuvy" => ["equivalently"], "acciiinrssst" => ["narcissistic"],
      "acceiloprstu" => ["plutocracies"], "aceemmmoorst" => ["commemorates"],
      "acdeefhinnrs" => ["enfranchised"],
      "aceinnoorstv" => ["conservation", "conversation"],
      "ccgiinnnnouv" => ["unconvincing"], "ddeeeinnnpst" => ["independents"],
      "ccegijnnortu" => ["conjecturing"], "aaiilnnorstt" => ["transitional"],
      "beehoprrsstt" => ["stepbrothers"], "aaabeiilmnnt" => ["maintainable"],
      "abdginnoorsw" => ["snowboarding"], "abcdeeilnors" => ["considerable"],
      "adeehhlorrss" => ["shareholders"], "ceennoorrsst" => ["cornerstones"],
      "aciiinopssuu" => ["inauspicious"], "aabeeksssttw" => ["wastebaskets"],
      "aaeehimmnpst" => ["amphetamines"], "aceginorsssu" => ["graciousness"],
      "cdeeeoprrsss" => ["predecessors"], "aceghhooprry" => ["choreography"],
      "acceeilllrty" => ["electrically"], "acdinooorrst" => ["coordinators"],
      "aacillmnorty" => ["romantically"], "aeehnnorrstt" => ["northeastern"],
      "cceeffiinost" => ["coefficients"], "aciilmnoopst" => ["compilations"],
      "deeeghnnrstt" => ["strengthened"], "deefiiilnnty" => ["indefinitely"],
      "bceeeelnnosv" => ["benevolences"], "aceeimmorsst" => ["commiserates"],
      "abdehhnossuu" => ["househusband"], "acilmnooopst" => ["cosmopolitan"],
      "aaeeemnppsst" => ["appeasements"], "ceinooprsstu" => ["prosecutions"],
      "aeeilprssuvy" => ["persuasively"], "acdeelmnoptt" => ["contemplated"],
      "aeimnrrssttt" => ["transmitters"], "adilorssstuy" => ["disastrously"],
      "aacceeilnort" => ["acceleration"], "aefghhoorrtu" => ["thoroughfare"],
      "cdeennrrrtuu" => ["undercurrent"], "aadefghnrrst" => ["grandfathers"],
      "deeelmnopstv" => ["developments"], "eghinoorrtvw" => ["overthrowing"],
      "eiiimnnorsst" => ["intermission"], "eeeilnrrrtvy" => ["irreverently"],
      "bcceeelnooss" => ["obsolescence"], "abdeeeerrrtv" => ["reverberated"],
      "adeeghimnost" => ["homesteading"], "aaceijlnostu" => ["ejaculations"],
      "deeeilnrsssw" => ["wildernesses"], "cdeeilmnoopx" => ["complexioned"],
      "abeeffilnrsu" => ["insufferable"], "deeeinprstux" => ["expenditures"],
      "aceehimnsstt" => ["chastisement"], "adeeefgirrrt" => ["refrigerated"],
      "aaceillprrst" => ["caterpillars"], "agghiimnnrst" => ["hamstringing"],
      "abiinorstttu" => ["attributions"], "abcgikknorst" => ["backstroking"],
      "dggiilnnrstu" => ["disgruntling"], "acdiilnnoost" => ["conditionals"],
      "aagghinoprtu" => ["autographing"], "aefgimnorrtt" => ["reformatting"],
      "aaeilnnorstt" => ["alternations"], "ccdddeeennos" => ["condescended"],
      "eelmmnnoptuy" => ["unemployment"], "aabegimnrrss" => ["embarrassing"],
      "acegimnnopss" => ["encompassing"], "ccelnnorrtuy" => ["concurrently"],
      "aeiiimnnnost" => ["insemination"], "abefgilnoruv" => ["unforgivable"],
      "adeiinnnostt" => ["indentations"], "abehinprsstu" => ["paintbrushes"],
      "bhiiinooprst" => ["prohibitions"], "aaghiiilnnnt" => ["annihilating"],
      "ceeeefinnrrt" => ["interference"], "aabeglmmoprr" => ["programmable"],
      "befgilnrttuy" => ["butterflying"], "adefiiisssst" => ["dissatisfies"],
      "aainnnoprsst" => ["nonpartisans"], "ddefghilloot" => ["floodlighted"],
      "aaceijkrsttt" => ["straitjacket"], "abdelmnorsty" => ["demonstrably"],
      "acgiiilnprtt" => ["triplicating"], "ceefgiilnrty" => ["electrifying"],
      "bdeeeilmnrtw" => ["bewilderment"], "aaggiinnrtuu" => ["inaugurating"],
      "accgiiilnnot" => ["conciliating"], "aabefllmmnno" => ["nonflammable"],
      "aadegikmnrrt" => ["trademarking"], "aeffhilnsstu" => ["faithfulness"],
      "deeeeimnprtx" => ["experimented"], "addeeffnrstu" => ["understaffed"],
      "adeeeiimnrtt" => ["intermediate"], "aeeopprrrstt" => ["perpetrators"],
      "aaceeggillno" => ["genealogical"], "acehinoprrss" => ["chairpersons"],
      "achiillorsty" => ["historically"], "ccdeiorrssss" => ["crisscrossed"],
      "aaeilnopssty" => ["passionately"], "cghinoooppty" => ["photocopying"],
      "ccefiiinnstu" => ["unscientific"], "ceilnnosstty" => ["consistently"],
      "cdhinooorstt" => ["orthodontics"], "aaccilmnotuu" => ["accumulation"],
      "aeghlmnnoors" => ["longshoreman"], "deeelmnppstu" => ["supplemented"],
      "abcdeeehirsu" => ["debaucheries"], "ccgiinnorstt" => ["constricting"],
      "aaccilnooptu" => ["occupational"], "abceeelmnrss" => ["resemblances"],
      "aceeillnrsuv" => ["surveillance"], "cceeelorsttu" => ["electrocutes"],
      "aacceillnnot" => ["cancellation"], "aaeilmnprstu" => ["planetariums"],
      "eegiiinnrtvw" => ["interviewing"], "aciiilnpprty" => ["principality"],
      "adeeiilnprst" => ["presidential"], "adgiillnnotu" => ["longitudinal"],
      "aaeegmnnrrst" => ["arrangements"], "abeeeinrrttv" => ["invertebrate"],
      "abdeeilprstu" => ["disreputable"], "aegiinorrstt" => ["registration"],
      "aaacceiinptt" => ["incapacitate"], "diiillnosssu" => ["disillusions"],
      "beeeiilrrrsv" => ["irreversible"], "degiinopprss" => ["predisposing"],
      "aeilmnosstuu" => ["simultaneous"], "cgiilooossst" => ["sociologists"],
      "aggimmmnnoor" => ["monogramming"], "acddeeefnort" => ["confederated"],
      "aceffghilnrs" => ["cliffhangers"], "clnoprssuuuu" => ["unscrupulous"],
      "abceiilnrtxy" => ["inextricably"], "aacdeilnorst" => ["declarations"],
      "aeeeinnrrstt" => ["entertainers"], "aacegiimrrss" => ["miscarriages"],
      "eeelllnrssty" => ["relentlessly"], "cddegiiinrst" => ["discrediting"],
      "abbghiilopry" => ["bibliography"], "accegiinrtux" => ["excruciating"],
      "achhiloprsss" => ["scholarships"], "ceeelmmorttu" => ["telecommuter"],
      "aabeghiknrtt" => ["breathtaking"], "abdeeeilmnrt" => ["determinable"],
      "afinorrssttu" => ["frustrations"], "acddeilnoost" => ["consolidated"],
      "eeimopprsssu" => ["superimposes"], "aabeelnnorsu" => ["unreasonable"],
      "abiiilnoostt" => ["abolitionist"], "ceeehiknsttt" => ["kitchenettes"],
      "eeehllnpssss" => ["helplessness"], "eeegilnoprsv" => ["oversleeping"],
      "cceeilllotvy" => ["collectively"], "cdefgiiinnst" => ["disinfecting"],
      "accegilnnosv" => ["convalescing"], "aadeeimmnrst" => ["mainstreamed"],
      "adeegmmoprrr" => ["reprogrammed"], "ddeeeimnnrtu" => ["undetermined"],
      "cccdeeiinnos" => ["coincidences"], "eiinnoprrttu" => ["interruption"],
      "cceiorrsssss" => ["crisscrosses"], "abeiilmnnrty" => ["interminably"],
      "eegilnnortuv" => ["volunteering"], "acceelnnostv" => ["convalescent"],
      "acehhiloptty" => ["hypothetical"], "bdeegiimmnrs" => ["dismembering"],
      "aciinnoopstt" => ["constipation"], "abiilnorsttu" => ["tribulations"],
      "aceeeflnpssu" => ["peacefulness"], "aabeilmmrsuy" => ["immeasurably"],
      "acemmnoprstt" => ["compartments"], "aeiiiilmrsst" => ["similarities"],
      "ahiilrssstty" => ["hairstylists"], "aeegimnnostt" => ["segmentation"],
      "acdiinorssyy" => ["idiosyncrasy"], "aaegillnpprw" => ["wallpapering"],
      "cceeinnnortt" => ["interconnect"], "ceeikknopstv" => ["pocketknives"],
      "adeiilnnorty" => ["inordinately"], "accdeennnotu" => ["countenanced"],
      "aiimnnorssst" => ["transmission"], "bbcdeeeknrru" => ["rubbernecked"],
      "aaffiiilnost" => ["affiliations"], "ceghilnoostt" => ["technologist"],
      "ceghilnooors" => ["chronologies"], "eiinoprsssuv" => ["supervisions"],
      "adegiknnrstu" => ["undertakings"], "adeeinnrrstu" => ["unrestrained"],
      "cceeemmmnnot" => ["commencement"], "adghilnnopry" => ["hydroplaning"],
      "abcinorssttu" => ["subtractions"], "cceeeiimnnrs" => ["reminiscence"],
      "aceeeilnqsuv" => ["equivalences"], "aacdeeiinqsu" => ["inadequacies"],
      "acceehirrttu" => ["architecture"], "aaeilmnnostt" => ["lamentations"],
      "aceiillnsstt" => ["scintillates"], "ceeeinnqsstu" => ["quintessence"],
      "ailnopprtuuy" => ["unpopularity"], "egghhhiilrst" => ["highlighters"],
      "adeiinorsttx" => ["extraditions"], "abcdeghiilnr" => ["childbearing"],
      "aggiiinnortv" => ["invigorating"], "aadeelllnpru" => ["unparalleled"],
      "cdeegimmnnor" => ["recommending"], "aiiinnnosstu" => ["insinuations"],
      "cceeeinoprsv" => ["preconceives"], "aaccehillmny" => ["mechanically"],
      "ddeefgnoorru" => ["foregrounded"], "aaceiklmnopt" => ["kleptomaniac"],
      "cdeeiiinnstv" => ["disincentive"], "aeeilrrrsstt" => ["terrestrials"],
      "cddeiinnostu" => ["discontinued"], "aabceiiilpst" => ["capabilities"],
      "aabcdgilnopr" => ["clapboarding"], "adeeiimnssst" => ["disseminates"],
      "aaggiiinnrtt" => ["ingratiating"], "degllnorssuy" => ["groundlessly"],
      "iinooopprsst" => ["propositions"], "aaacdillmrty" => ["dramatically"],
      "bceeeinrssuv" => ["subservience"], "abddeinorstu" => ["subordinated"],
      "aeehnorssttu" => ["southeastern"], "adeegimssttu" => ["guesstimated"],
      "aeeemnrssttt" => ["restatements"], "acdeiillnstt" => ["scintillated"],
      "aabcgiikllmn" => ["blackmailing"], "acdefiinnstt" => ["disinfectant"],
      "aaagiilnnotv" => ["navigational"], "aabdeeegilrs" => ["disagreeable"],
      "adejmnnorstu" => ["adjournments"], "eeinnoprssuv" => ["unresponsive"],
      "aceiloprrsuy" => ["precariously"], "abceeilnorst" => ["celebrations"],
      "aceeirsssttu" => ["resuscitates"], "accdehilmops" => ["accomplished"],
      "acdgiinnoort" => ["coordinating"], "ccdeeimnrtuv" => ["circumvented"],
      "aabbefglrsst" => ["flabbergasts"], "aaceimoprstv" => ["comparatives"],
      "cdeeiiilnsvy" => ["indecisively"], "aeegilnrsstv" => ["everlastings"],
      "ceehmorsttyy" => ["hysterectomy"], "acegiilorssu" => ["sacrilegious"],
      "aabeeilnprss" => ["inseparables"], "ccgiilnnnovy" => ["convincingly"],
      "cdiinnoorttu" => ["introduction"], "ceeeeiinnprx" => ["inexperience"],
      "aaceilmnostx" => ["exclamations"], "aacehillnstu" => ["hallucinates"],
      "lmnnoooostuy" => ["monotonously"], "aabceinrrstt" => ["scatterbrain"],
      "abehiilnopst" => ["inhospitable"], "bceilorsstuu" => ["tuberculosis"],
      "aaacceinnqtu" => ["acquaintance"], "aabiklmnstuy" => ["unmistakably"],
      "aciiinoqsstu" => ["acquisitions"], "aehiinoprrss" => ["parishioners"],
      "adefhiloorst" => ["foolhardiest"], "cdeeinrrsttu" => ["unrestricted"],
      "eeehlmnossss" => ["homelessness"], "ceeegiinnprx" => ["experiencing"],
      "ceginnpsstuu" => ["unsuspecting"], "eeiilmprssvy" => ["impressively"],
      "adefiiilqssu" => ["disqualifies"], "addeeeimprtt" => ["premeditated"],
      "aeeemmnrsstu" => ["measurements"], "adeeehprssst" => ["spreadsheets"],
      "ceiimmnoprtu" => ["minicomputer"], "bdghiimmnrsu" => ["hummingbirds"],
      "adiiiimnnott" => ["intimidation"], "aacegiilmnns" => ["malignancies"],
      "eeehilrssstv" => ["shirtsleeves"], "ceeelmmosttu" => ["telecommutes"],
      "agillmnnoosu" => ["monolinguals"], "aeehoprrsstt" => ["stratosphere"],
      "ccimnnoopstu" => ["compunctions"], "beiinorrsttu" => ["retributions"],
      "acegiilnnrsy" => ["increasingly"], "ceeinoprsstu" => ["persecutions"],
      "aabbegiinrtv" => ["abbreviating"], "acfiimnnoort" => ["confirmation"],
      "aaeegginnrtu" => ["guaranteeing"], "ceeiiinrsstu" => ["insecurities"],
      "acdeeghinnrt" => ["interchanged"], "egiinnoprrtv" => ["overprinting"],
      "aeeginorrstt" => ["interrogates"], "aacceegilnrt" => ["accelerating"],
      "iinooprstttu" => ["prostitution"], "eghimnnnoooy" => ["honeymooning"],
      "aeegillrsstu" => ["legislatures"], "befghiinrrsu" => ["refurbishing"],
      "acehillnopty" => ["phonetically"], "aceeeilmnpst" => ["mantelpieces"],
      "aceehorrsstt" => ["orchestrates"], "bddfgiillnno" => ["blindfolding"],
      "degiinnrrtuw" => ["underwriting"], "aeimnoprsttu" => ["permutations"],
      "acdeeeehlrrs" => ["cheerleaders"], "aaeegginortx" => ["exaggeration"],
      "fginooprrstu" => ["rustproofing"], "cceiinnottvy" => ["connectivity"],
      "addefiiilqsu" => ["disqualified"], "aacceeghosst" => ["stagecoaches"],
      "aaeiilmnptuv" => ["manipulative"], "eeghiinrstux" => ["extinguisher"],
      "abceillnnoos" => ["inconsolable"], "aeeemprrsttu" => ["temperatures"],
      "aaghiinpstxy" => ["asphyxiating"], "acefiiinortv" => ["verification"],
      "eefgiilmnpxy" => ["exemplifying"], "aabdeegilrsy" => ["disagreeably"],
      "aadefgginrsu" => ["safeguarding"], "deeegilnoprv" => ["redeveloping"],
      "eeeilmnnsttt" => ["entitlements"], "bddeeenorruv" => ["overburdened"],
      "abdeeilnrssu" => ["undesirables"], "aacfillnorty" => ["fractionally"],
      "aceginnnortv" => ["contravening"], "acenoorrstvy" => ["conservatory"],
      "afiiilnnortt" => ["infiltration"], "eeeefghilnrw" => ["freewheeling"],
      "aafiinnosttu" => ["infatuations"], "aeiinnoorstt" => ["orientations"],
      "bdgiiinrsttu" => ["distributing"], "eeghilrssttt" => ["streetlights"],
      "bcinoorrttuy" => ["contributory"], "aacgiinnostt" => ["antagonistic"],
      "deeiiillrsst" => ["distilleries"], "aeghhiinstww" => ["whitewashing"],
      "ciilopsssuuy" => ["suspiciously"], "adeeginorrtt" => ["interrogated"],
      "abeeillnnruv" => ["invulnerable"], "eefillpssttu" => ["spitefullest"],
      "eeginooprrvw" => ["overpowering"], "ccdeeeinoprv" => ["preconceived"],
      "aabcdeorrsst" => ["broadcasters"], "aabbeilrtttu" => ["attributable"],
      "aeehinnopprs" => ["apprehension"], "aacdeelnpstu" => ["encapsulated"],
      "aceefmnoprrs" => ["performances"], "cceeginnnort" => ["reconnecting"],
      "acfillnnotuy" => ["functionally"], "adeiinnorstt" => ["transitioned"],
      "ceeelmnopsst" => ["completeness"], "acdeeeilnsst" => ["delicatessen"],
      "cdfinnosstuy" => ["dysfunctions"], "aabcdelloort" => ["collaborated"],
      "addeegilnnst" => ["disentangled"], "acdeehimnrss" => ["merchandises"],
      "aacfiiinortt" => ["ratification"], "acccegiinnor" => ["carcinogenic"],
      "ceeiinnorstt" => ["intersection"], "bbceelnoosst" => ["cobblestones"],
      "cefiilnoprty" => ["proficiently"], "ceehilnnorty" => ["incoherently"],
      "aaegikmnrrtw" => ["watermarking"], "cdiimmnnoosu" => ["condominiums"],
      "acdeegklnosw" => ["acknowledges"], "aceiiilrsttv" => ["relativistic"],
      "aacehilmpsty" => ["metaphysical"], "dddehnnooorr" => ["rhododendron"],
      "cdeeelmmnopt" => ["complemented"], "acegimnnopst" => ["compensating"],
      "cdehkloorsst" => ["stockholders"], "deeelnrrsuvy" => ["unreservedly"],
      "abdfginorrsu" => ["surfboarding"], "aeegiinnnrtt" => ["entertaining"],
      "eeeilprssvxy" => ["expressively"], "eehloprrsstu" => ["upholsterers"],
      "aceiinnorrst" => ["incinerators"], "abddeilnoost" => ["bloodstained"],
      "ceinnoorsssu" => ["connoisseurs"], "abdeiilnpstu" => ["indisputable"],
      "cdeeelnptuxy" => ["unexpectedly"], "cceillnosuvy" => ["conclusively"],
      "aacdeeinnrrt" => ["reincarnated"], "aeegiinnrtvw" => ["interweaving"],
      "adeegiinrstt" => ["disintegrate"], "aeeehinpprsv" => ["apprehensive"],
      "aeeimnnorstu" => ["mountaineers"], "aceehiinnrst" => ["inheritances"],
      "aeghioopprst" => ["topographies"], "aaciinpprstt" => ["participants"],
      "abdeiiiilsst" => ["disabilities"], "aaaceegnrtvx" => ["extravagance"],
      "aeinoorrsstt" => ["restorations"], "fghhllottuuy" => ["thoughtfully"],
      "aeiimnnorstt" => ["terminations"], "ddeeenorsuvz" => ["rendezvoused"],
      "acciilnorstu" => ["circulations"], "deeimnnrsttu" => ["instrumented"],
      "bbceilmosstu" => ["combustibles"], "aacehillmpty" => ["emphatically"],
      "bceeilmnoptt" => ["contemptible"], "adeeeghlmmrs" => ["sledgehammer"],
      "fgiiimmnnors" => ["misinforming"], "cdellnnoortu" => ["uncontrolled"],
      "aeegimsssttu" => ["guesstimates"], "aaceffinostt" => ["affectations"],
      "cdeeiiimorst" => ["mediocrities"], "aeefiinrrstt" => ["fraternities"],
      "aeeegmnnrstt" => ["estrangement"], "bgiilmnnoosw" => ["snowmobiling"],
      "acceinnoorst" => ["consecration"], "acehillrstyy" => ["hysterically"],
      "acefillorsuw" => ["cauliflowers"], "aaiiilmprtty" => ["impartiality"],
      "accdeenorttu" => ["counteracted"], "aadehioprrty" => ["radiotherapy"],
      "cdeehilnprst" => ["stepchildren"], "aaciinoossst" => ["associations"],
      "cdeeirrrssvw" => ["screwdrivers"],
      "aeeinnoprstt" => ["penetrations", "presentation"],
      "deeghiinstux" => ["extinguished"], "cdeinorsstuy" => ["countrysides"],
      "deehiilnqrsu" => ["relinquished"], "acdeeghllnnu" => ["unchallenged"],
      "aaddiiilnopt" => ["dilapidation"], "eeffghiirrst" => ["firefighters"],
      "aabceiillnpp" => ["inapplicable"], "ceefhkmorrtu" => ["motherfucker"],
      "aacddijorstu" => ["adjudicators"], "aaeeillqrstu" => ["equilaterals"],
      "bcgiilmooory" => ["microbiology"], "beeiiklnsssu" => ["businesslike"],
      "aacceeinrrst" => ["incarcerates"], "acinoooprstv" => ["provocations"],
      "ceiimmnoorss" => ["commissioner"], "aacfgiiilntt" => ["facilitating"],
      "aabeillrrstz" => ["trailblazers"], "acgiiinnottx" => ["intoxicating"],
      "aaccgiinrrtu" => ["caricaturing"], "ceiiprrrsttw" => ["scriptwriter"],
      "aefgiilrtuvy" => ["figuratively"], "aabceikllmrs" => ["blackmailers"],
      "aeefiloprrst" => ["proliferates"], "cccgiiimnrsu" => ["circumcising"],
      "bdhiloorstty" => ["bloodthirsty"], "begiilnnprtu" => ["blueprinting"],
      "aabinoopprst" => ["approbations"], "eehinrssstyz" => ["synthesizers"],
      "ceffiilnstuy" => ["sufficiently"], "abciilnopstu" => ["publications"],
      "bcekkoorrsst" => ["stockbrokers"], "aeeggilrssvy" => ["aggressively"],
      "bdeegiiilnst" => ["indigestible"], "aceeegiknrrt" => ["racketeering"],
      "aginooprsstt" => ["protagonists"], "deeeinnrsttu" => ["uninterested"],
      "accdeennortt" => ["concentrated"], "deegiilmnnrt" => ["intermingled"],
      "aabfllmnotyy" => ["flamboyantly"], "aeggiiilmntt" => ["legitimating"],
      "aabddeglllrs" => ["gallbladders"], "aadeilnorttu" => ["adulteration"],
      "aaeimnoooopt" => ["onomatopoeia"], "defgiiinrsvy" => ["diversifying"],
      "aeeghnoprrst" => ["stenographer"], "bdehhooorrst" => ["brotherhoods"],
      "acceeiilnrst" => ["electricians"], "aaaccdeillmy" => ["academically"],
      "aceeelnrssss" => ["carelessness"], "adgiiiimnntt" => ["intimidating"],
      "acdeginnnrst" => ["transcending"], "acdeiiimnrst" => ["discriminate"],
      "cdeeiilnoprt" => ["predilection"], "accehilmopss" => ["accomplishes"],
      "afinnorssstu" => ["transfusions"], "aaeilnorstuv" => ["revaluations"],
      "aefgggilnopr" => ["leapfrogging"], "addeemnorstt" => ["demonstrated"],
      "cdeeeiinprss" => ["presidencies"], "aacegiimnnpt" => ["emancipating"],
      "aeeillnqstuy" => ["sequentially"], "aceggginnort" => ["congregating"],
      "aaddiillnoty" => ["additionally"], "deefiilnnrru" => ["unfriendlier"],
      "aaggiillnntv" => ["gallivanting"], "deefiiiilnst" => ["infidelities"],
      "aaaegiilnrst" => ["egalitarians"], "aceeginorrtv" => ["overreacting"],
      "aaegimnnrrst" => ["arraignments"], "ceehikmnosss" => ["homesickness"],
      "aceeinoprrtu" => ["recuperation"], "aeeinoprrstv" => ["preservation"],
      "aacegiinpprt" => ["appreciating"], "deeinnnorsst" => ["nonresidents"],
      "abefilnoprtu" => ["unprofitable"], "aaciinnnorst" => ["incarnations"],
      "aefilnooprss" => ["professional"], "aabelnnorsuy" => ["unreasonably"],
      "acenoorrsstv" => ["conservators"], "ceegiinnrssu" => ["insurgencies"],
      "ceefiimnoprt" => ["imperfection"], "abcdeinoorst" => ["noticeboards"],
      "aaabcehloppr" => ["approachable"], "aeeillnrrstt" => ["interstellar"],
      "aacehiimrrst" => ["matriarchies"], "acdeeimmorst" => ["commiserated"],
      "aaccillnoosy" => ["occasionally"], "achhiimnopps" => ["championship"],
      "ceeiijnnortt" => ["interjection"], "ehiilmrssstv" => ["silversmiths"],
      "ceeiinnnnotv" => ["inconvenient"], "acdehillmoty" => ["methodically"],
      "aabcelloorst" => ["collaborates"], "aceeginprrtu" => ["recuperating"],
      "aceinooprrst" => ["incorporates"], "acdloooprstt" => ["postdoctoral"],
      "aciiilmnptuy" => ["municipality"], "aaabcehillpt" => ["alphabetical"],
      "aeegiinssttv" => ["investigates"], "aaccceiinrsu" => ["inaccuracies"],
      "aceemnnnnotu" => ["announcement"], "ceeeeffnrstv" => ["effervescent"],
      "aefgillnorst" => ["forestalling"], "aceeghilnrtw" => ["cartwheeling"],
      "aaceeklmprst" => ["marketplaces"], "aaceilmrsttu" => ["matriculates"],
      "cdeginnorrsu" => ["underscoring"], "aadeilnostuv" => ["devaluations"],
      "egiiinnnrttw" => ["intertwining"], "aacilnorstvy" => ["clairvoyants"],
      "cdeeeeiinpsx" => ["expediencies"], "acceelnnrstu" => ["translucence"],
      "aeeinrsstttv" => ["transvestite"], "aehioprrstwy" => ["praiseworthy"],
      "adeeeimprstt" => ["premeditates"], "eilmorsstuyy" => ["mysteriously"],
      "aaeimopprstx" => ["approximates"], "aabdegiimstu" => ["disambiguate"],
      "aciilnnoostu" => ["inoculations"], "deeenorssuvz" => ["rendezvouses"],
      "aacgiilnpttu" => ["capitulating"], "abcceilmmnou" => ["communicable"],
      "aeeimnnorrtu" => ["remuneration"], "aceimnorsstv" => ["conservatism"],
      "almnooostuuy" => ["autonomously"], "aadeflmnnstu" => ["fundamentals"],
      "eemnnooppstt" => ["postponement"], "aacceillmstu" => ["miscalculate"],
      "cddeeehmnopr" => ["comprehended"], "aaccillnostu" => ["calculations"],
      "eeeinprrrstt" => ["interpreters"], "acdeimmnnoot" => ["commendation"],
      "ciimnooopsst" => ["compositions"], "aabeehiilrtt" => ["rehabilitate"],
      "adeeenpprrss" => ["preparedness"], "acemnooprsty" => ["compensatory"],
      "ceeghilnoost" => ["technologies"], "aeeeglmnnntt" => ["entanglement"],
      "cegimnnnosst" => ["consignments"], "abiiillpstuy" => ["plausibility"],
      "abdegiiilntt" => ["debilitating"], "adeeiinprsss" => ["dispensaries"],
      "aaccgimnnopy" => ["accompanying"], "aaeilllnrtuy" => ["unilaterally"],
      "aaeghiilnrtx" => ["exhilarating"], "acdeeikloops" => ["kaleidoscope"],
      "abdeefiiilnt" => ["identifiable"], "ceilmooprssu" => ["compulsories"],
      "achnnoorssuy" => ["asynchronous"], "acddeinosttu" => ["outdistanced"],
      "bdeghhoorrtu" => ["thoroughbred"], "aaegiilmnort" => ["ameliorating"],
      "aadeeghinprs" => ["spearheading"], "abceeiilnnnt" => ["bicentennial"],
      "emopprsstuuu" => ["presumptuous"], "bdeeiirrsttu" => ["redistribute"],
      "aegggilnrsty" => ["staggeringly"], "accimmnoortu" => ["communicator"],
      "aeeeilnrrstt" => ["interrelates"], "aacceelorrst" => ["accelerators"],
      "aeghimnorsuw" => ["housewarming"], "acchhioppsty" => ["psychopathic"],
      "aafiilmmnnot" => ["inflammation"], "aadegnnprrst" => ["grandparents"],
      "aaadegnostuv" => ["advantageous"], "eeoopprrsstu" => ["preposterous"],
      "acghhioopprt" => ["photographic"], "aeeimmnrsttt" => ["mistreatment"],
      "aadegoprsttu" => ["postgraduate"], "ahilmnoorsuy" => ["harmoniously"],
      "cdeginnrttuu" => ["undercutting"], "ccilmoorstty" => ["motorcyclist"],
      "abcdeinrsstu" => ["disturbances"], "ceiinnorrstu" => ["insurrection"],
      "behhoorssttu" => ["toothbrushes"], "eegghiilnnnt" => ["enlightening"],
      "acceginnorst" => ["consecrating"], "cdeiinnooprt" => ["precondition"],
      "ceehillnosst" => ["clotheslines"], "acilnnoosttu" => ["consultation"],
      "ceegiijnnrtt" => ["interjecting"], "ceghiinnrsst" => ["christenings"],
      "ceiinnnosstt" => ["inconsistent"], "acfiiinoprtu" => ["purification"],
      "egiillmnptux" => ["multiplexing"], "cceiilnnosuv" => ["inconclusive"],
      "aabdmoorrrst" => ["mortarboards"], "aiilmnnorttu" => ["malnutrition"],
      "cdeffiiilstu" => ["difficulties"], "cdiiilnnstty" => ["indistinctly"],
      "efiilmoprsvy" => ["oversimplify"], "aaceillmmtuy" => ["immaculately"],
      "bcdgiikmnors" => ["mockingbirds"], "diiinoopssst" => ["dispositions"],
      "acilmmnnoott" => ["noncommittal"], "ceeeiiprrstv" => ["irrespective"],
      "clloprssuuuy" => ["scrupulously"], "abdeinorsstu" => ["subordinates"],
      "aaccdeillnty" => ["accidentally"], "eginooprrsss" => ["progressions"],
      "aabceeeghlrr" => ["rechargeable"], "egiinnnortvy" => ["inventorying"],
      "aeeimnorrttx" => ["exterminator"], "aeeeilmnprtx" => ["experimental"],
      "cgiinnostttu" => ["constituting"], "aaeoopprrrst" => ["paratroopers"],
      "inoopprssttu" => ["opportunists"], "abcgiklnoppt" => ["blacktopping"],
      "aabeilnoorst" => ["elaborations"], "aciiilnnnost" => ["inclinations"],
      "ahhilnopprty" => ["philanthropy"], "aceefhinnrss" => ["enfranchises"],
      "degilnnorsuy" => ["resoundingly"], "eimnopprsstu" => ["presumptions"],
      "ciiillmpttuy" => ["multiplicity"], "aacegginopst" => ["scapegoating"],
      "eellorrsstty" => ["storytellers"], "ceefimnnnost" => ["confinements"],
      "aeiiilmnnost" => ["eliminations"], "addeeiimnrst" => ["administered"],
      "aeeijnnortuv" => ["rejuvenation"], "ceeillmnopty" => ["incompletely"],
      "aaadeinsssst" => ["assassinated"], "accdeeelnoss" => ["adolescences"],
      "aeeeimnrsttx" => ["exterminates"], "acemnooprrty" => ["contemporary"],
      "ceeeinorstux" => ["executioners"], "acciiilnnoot" => ["conciliation"],
      "abeeeilmnprt" => ["impenetrable"], "aacciiorrstt" => ["aristocratic"],
      "eeeehnnssttv" => ["seventeenths"], "aehinpprrsst" => ["partnerships"],
      "ahiiilmnostu" => ["humiliations"], "aagghiijmnst" => ["thingamajigs"],
      "eeghlmnnoors" => ["longshoremen"], "agiillnrsttu" => ["illustrating"],
      "agiiklmnsttu" => ["multitasking"], "aabbcegikknr" => ["backbreaking"],
      "abeeeerrrstv" => ["reverberates"], "aeiiimnorsss" => ["missionaries"],
      "iiinnosstttu" => ["institutions"], "aeeiinnprtty" => ["penitentiary"],
      "acdemmmnnost" => ["commandments"], "aceeefffrstt" => ["aftereffects"],
      "aacegghilopr" => ["geographical"], "cdiiinnosstt" => ["distinctions"],
      "adeinooprstt" => ["deportations"], "aacdehillntu" => ["hallucinated"],
      "beeeirsstttw" => ["bittersweets"], "aadegilnrttu" => ["adulterating"],
      "abeghhkorrtu" => ["breakthrough"], "aegghilnrstu" => ["slaughtering"],
      "aceghhooprrs" => ["choreographs"], "aciiilmnopst" => ["implications"],
      "degiiinnorst" => ["disorienting"], "bcehiimorsty" => ["biochemistry"],
      "eeeimnprrsst" => ["misrepresent"], "aeeeginnorrt" => ["regeneration"],
      "aegilnrrssuy" => ["reassuringly"], "adeiinnosstt" => ["destinations"],
      "cdiioprttuvy" => ["productivity"], "eefghiilrttw" => ["weightlifter"],
      "cdgiiinnnoot" => ["conditioning"], "acdeemmmoort" => ["commemorated"],
      "aceiinnnortu" => ["renunciation"], "ccceeiinrtty" => ["eccentricity"],
      "aeginoorrrtt" => ["interrogator"], "aeghopprrsss" => ["grasshoppers"],
      "aabcceirrtuu" => ["bureaucratic"], "aceegilssttu" => ["gesticulates"],
      "cceinorsttuv" => ["constructive"], "aacciilprtty" => ["practicality"],
      "acgiinnnorst" => ["constraining"], "acehillnopst" => ["plainclothes"],
      "aiimnooprstt" => ["importations"], "adegiimnnprr" => ["reprimanding"],
      "aacefmnrrtuu" => ["manufacturer"], "aeiiillmnors" => ["millionaires"],
      "abcehlnostuu" => ["untouchables"], "abcgiinnrrst" => ["transcribing"],
      "bdiiorrssttu" => ["distributors"], "ceefllprstuy" => ["respectfully"],
      "aacehilmoprt" => ["metaphorical"], "adefginooprr" => ["proofreading"],
      "aacillprrtuy" => ["particularly"], "aeeinoortttx" => ["extortionate"],
      "acehiintttuy" => ["authenticity"], "acgijnnoostu" => ["conjugations"],
      "aabeiloorrst" => ["laboratories"],
      "cdeiinnoorst" => ["conditioners", "reconditions"],
      "adeeghhilrtt" => ["lighthearted"], "aeeggirrsttu" => ["regurgitates"],
      "aceghhilrsst" => ["searchlights"], "ceiinopprrst" => ["prescription"],
      "aabbeilnnotu" => ["unobtainable"], "aaceimnnostt" => ["contaminates"],
      "acceefiirstt" => ["certificates"], "bdiiinorsttu" => ["distribution"],
      "bgiinsstttuu" => ["substituting"], "accdeimnortu" => ["undemocratic"],
      "aabbeirrsttu" => ["barbiturates"], "iiiinnoqsstu" => ["inquisitions"],
      "aceiiimnnrst" => ["incriminates"], "aabdeehhrrsy" => ["haberdashery"],
      "beeeelmmntzz" => ["embezzlement"], "aacgiilnrttu" => ["articulating"],
      "aaceiipprstt" => ["participates"], "aaeiinoprrtt" => ["repatriation"],
      "aadeehqrrstu" => ["headquarters"], "aeggiimnnprt" => ["impregnating"],
      "aacinnorsstt" => ["transactions"], "cdeehorstttu" => ["outstretched"],
      "ceeeklnrssss" => ["recklessness"], "aeegijnnrtuv" => ["rejuvenating"],
      "ailnooopprrt" => ["proportional"], "aaccgilmntuu" => ["accumulating"],
      "cddeeeinorrs" => ["reconsidered"], "aaceiinopprt" => ["appreciation"],
      "aacdeemnnstv" => ["advancements"], "eeelnrssssst" => ["restlessness"],
      "aadegiinpprs" => ["disappearing"], "ceeiinnoprtt" => ["interception"],
      "abcelllnoort" => ["controllable"], "abeehllrssty" => ["breathlessly"],
      "ceiimnoopstt" => ["competitions"], "cceeeinnnosv" => ["conveniences"],
      "aacdeiipprtt" => ["participated"], "aaahiimnnrtu" => ["humanitarian"],
      "degiinnossuu" => ["disingenuous"], "aceiilrrsstu" => ["surrealistic"],
      "addeefhoorsw" => ["foreshadowed"], "deegiinppsst" => ["sidestepping"],
      "abceiilmnopt" => ["incompatible"], "eiimmnnoprst" => ["imprisonment"],
      "bdeegiimnorr" => ["embroidering"], "abeeiilmnnrt" => ["interminable"],
      "aefimnoorrst" => ["reformations"], "abciilmnopty" => ["incompatibly"],
      "aaeghhiknrst" => ["earthshaking"], "cemnoopsttuu" => ["contemptuous"],
      "aaeghlmnrstu" => ["manslaughter"], "aaeilnoprrst" => ["proletarians"],
      "eeeginnprrst" => ["representing"], "cceflnsssuuu" => ["unsuccessful"],
      "ccceennorrsu" => ["concurrences"], "aaabiiilltvy" => ["availability"],
      "aciinnnoottu" => ["continuation"], "ceeimnnopstt" => ["incompetents"],
      "agiimnnrsttt" => ["transmitting"], "ddeeeenortvx" => ["overextended"],
      "aabdgilnnsst" => ["sandblasting"], "acdeeeinsstt" => ["necessitated"],
      "cgiimmnooprs" => ["compromising"], "adeiimnnnoot" => ["denomination"],
      "abdeglnorttu" => ["battleground"], "bdeefiilrstu" => ["filibustered"],
      "giinoprstttu" => ["prostituting"], "deeinnoqstuu" => ["unquestioned"],
      "ccegiknorrsw" => ["corkscrewing"], "aaeiimnnostx" => ["examinations"],
      "aeilmnnrsttu" => ["instrumental"], "ccehilnopsty" => ["polytechnics"],
      "adgiinopprsv" => ["disapproving"], "adeeegimnrst" => ["disagreement"],
      "accegiiknrsw" => ["wisecracking"], "ceehklnossuy" => ["honeysuckles"],
      "aeeghipprstw" => ["paperweights"], "efgiinnprrst" => ["fingerprints"],
      "eegiilmmnnpt" => ["implementing"], "cfgiiilmmnor" => ["microfilming"],
      "aceeehimnstv" => ["achievements"], "acfilmnnostu" => ["malfunctions"],
      "agiinnoopprt" => ["apportioning"], "abbbehlmortu" => ["blabbermouth"],
      "eginoppprssu" => ["presupposing"], "ciiinnoprsst" => ["inscriptions"],
      "ccddeeinorst" => ["disconcerted"], "begimnnortuu" => ["outnumbering"],
      "aadeelmnprtt" => ["departmental"], "aaccdeeinrrt" => ["incarcerated"],
      "ccciiimnorsu" => ["circumcision"], "aabceilmnopr" => ["incomparable"],
      "eeiinopprsst" => ["propensities"], "aacceilmprst" => ["malpractices"],
      "adeghllnorst" => ["stranglehold"], "acdeinooprrt" => ["incorporated"],
      "abcdhiorsstw" => ["switchboards"], "abcceemnnrsu" => ["encumbrances"],
      "aaciillrstty" => ["artistically"], "aabccelnptuy" => ["unacceptably"],
      "acceillmnooy" => ["economically"], "eeeghimnostu" => ["meetinghouse"],
      "cddeeeeinnnp" => ["independence"], "eeekloopppss" => ["spokespeople"],
      "egilnoorsstu" => ["neurologists"], "acinoooprrst" => ["corporations"],
      "abcdgiklnoor" => ["roadblocking"], "gghhinoorsuu" => ["roughhousing"],
      "accdeefiirtt" => ["certificated"], "deinooopprrt" => ["proportioned"],
      "aegimnnrsttu" => ["menstruating"], "eeehlnopssss" => ["hopelessness"],
      "cdeeilmmnopt" => ["complimented"], "adeehirrrsss" => ["hairdressers"],
      "acegillmooty" => ["etymological"], "aceinopssssu" => ["spaciousness"],
      "adeefooprrtw" => ["waterproofed"], "aeehilstuvxy" => ["exhaustively"],
      "addeeeeggrst" => ["desegregated"], "aacegillnort" => ["reallocating"],
      "gghiilmnnoot" => ["moonlighting"], "aagiilmnnptu" => ["manipulating"],
      "adeelmorsstu" => ["somersaulted"], "agiiinnoprtt" => ["partitioning"],
      "eeegiprrrsst" => ["preregisters"], "aceffghinruu" => ["chauffeuring"],
      "eghilnoprstu" => ["upholstering"], "bceeijlstuvy" => ["subjectively"],
      "bcegiiilnorr" => ["incorrigible"], "aaceillrttuy" => ["articulately"],
      "ddeehiiinrst" => ["disinherited"], "agghilnoppry" => ["polygraphing"],
      "bfgghiillntu" => ["bullfighting"], "gghiilnopstt" => ["spotlighting"],
      "cdeinoprtuuv" => ["unproductive"], "cdeeioprrtuv" => ["reproductive"],
      "aacdilloprsy" => ["sporadically"], "bceghimnnooy" => ["honeycombing"],
      "acceeioprrst" => ["reciprocates"], "eehiilnqrssu" => ["relinquishes"],
      "acinnnooostt" => ["connotations"], "acceiinoprss" => ["conspiracies"],
      "adeegnrrssst" => ["transgressed"], "ceefinorsttu" => ["counterfeits"],
      "aceghiillnyy" => ["hygienically"], "aabeennrrstu" => ["subterranean"],
      "aegilmnoprsv" => ["oversampling"], "eeknoopprsss" => ["spokesperson"],
      "giilnprrssuy" => ["surprisingly"], "acchiiloprty" => ["hypocritical"],
      "defhinprsstt" => ["spendthrifts"], "eeghiilnnprs" => ["replenishing"],
      "ccdeeefiiins" => ["deficiencies"], "abdeeinnrrsw" => ["breadwinners"],
      "aaeiilmnoort" => ["amelioration"], "acddeehinnst" => ["disenchanted"],
      "accellnoptuy" => ["conceptually"], "aeeeglmnnrst" => ["enlargements"],
      "acceillmmory" => ["commercially"], "cdgiiiilnnps" => ["disciplining"],
      "eeghiinsstux" => ["extinguishes"], "aeiinnopsstx" => ["expansionist"],
      "acdeeirssttu" => ["resuscitated"], "aaiillnorrty" => ["irrationally"],
      "aacgiiinnptt" => ["anticipating"], "aabdeekorrst" => ["skateboarder"],
      "aceilnoorrst" => ["correlations"], "acdeegilsttu" => ["gesticulated"],
      "acghiilnnort" => ["chlorinating"], "aaaiilmprrty" => ["paramilitary"],
      "eghinooprrsv" => ["governorship"], "acdhhinoopry" => ["hypochondria"],
      "ggiiillnnotu" => ["guillotining"], "aaceiimnnopt" => ["emancipation"],
      "ceegiinnrstt" => ["intersecting"], "eegiilmnnrst" => ["intermingles"],
      "aceimmorrstu" => ["crematoriums"], "ceeiklmnppru" => ["pumpernickel"],
      "fginoopsstuy" => ["pussyfooting"], "adeegiknnrrt" => ["kindergarten"],
      "acehlmmnootw" => ["commonwealth"], "ceeillorssty" => ["electrolysis"],
      "aaegiinprrtt" => ["repatriating"], "eefiiinnrsst" => ["intensifiers"],
      "abbeeeillnuv" => ["unbelievable"], "aaciilnorttu" => ["articulation"],
      "adeiinoprstu" => ["repudiations"], "aaelnrssstux" => ["transsexuals"],
      "acdeeefnorst" => ["confederates"], "ceillmostuuy" => ["meticulously"],
      "adeegiinsttv" => ["investigated"], "aadeeloprttx" => ["extrapolated"],
      "aaehiilnortx" => ["exhilaration"], "aabeeklmnrru" => ["unremarkable"],
      "ahillnoortyz" => ["horizontally"], "cdeeeffiinnr" => ["indifference"],
      "agilorsttuuy" => ["gratuitously"], "bbceklorsstu" => ["blockbusters"],
      "aacfiinnosst" => ["fascinations"], "aefghhortttu" => ["afterthought"],
      "adeejmnrsttu" => ["readjustment"], "eiinoopprsst" => ["prepositions"],
      "acimmnnoostu" => ["consummation"], "adeehimrssst" => ["headmistress"],
      "aafiilnnorty" => ["inflationary"], "ceeeipprsstv" => ["perspectives"],
      "aeilnoortuvy" => ["evolutionary"], "aaceknnorstu" => ["cantankerous"],
      "aacddgiijntu" => ["adjudicating"], "acdiiinoosst" => ["dissociation"],
      "aaceiilnrttu" => ["inarticulate"], "acdfiiimnoot" => ["modification"],
      "aeiilmnosstt" => ["testimonials"], "cceillooopss" => ["oscilloscope"],
      "acddeeinnrsu" => ["redundancies"], "cdeeehiloprt" => ["helicoptered"],
      "abdeeeillrty" => ["deliberately"], "ccddeeinnost" => ["disconnected"],
      "aacfggilmnou" => ["camouflaging"], "beegloorrttt" => ["globetrotter"],
      "ceehlooprrss" => ["preschoolers"], "egghhiilsttw" => ["lightweights"],
      "acehiiopsstt" => ["sophisticate"], "eeimnnnorstv" => ["environments"],
      "acdeiinnortt" => ["indoctrinate"], "aceiiinnnort" => ["incineration"],
      "aaeilllmrttu" => ["multilateral"], "aagiinnortuu" => ["inauguration"],
      "aeeglmnnortv" => ["governmental"], "eiimnnooprst" => ["premonitions"],
      "acchiiinstuv" => ["chauvinistic"], "eeggilsstuvy" => ["suggestively"],
      "aeiilorrrstt" => ["territorials"], "aachimnnorss" => ["anachronisms"],
      "dggiilnsstuy" => ["disgustingly"], "aagiiilmnsst" => ["assimilating"],
      "egilmnooostt" => ["entomologist"], "aabceefiprrt" => ["prefabricate"],
      "acfiiinnoott" => ["notification"], "ddeefiiinntu" => ["unidentified"],
      "ehmnnoorrstt" => ["northernmost"], "acegiinnpprt" => ["apprenticing"],
      "abdeiiirsssu" => ["subsidiaries"], "acgiinnopstt" => ["constipating"],
      "aeegiillmtty" => ["legitimately"], "aaagghinpprr" => ["paragraphing"],
      "cdegiiimnrst" => ["misdirecting"], "accegilllooy" => ["ecologically"],
      "aacdeilmmort" => ["melodramatic"], "aefgllnrtuuy" => ["ungratefully"],
      "aceeimnorsvw" => ["servicewoman"], "aghiloopsstt" => ["pathologists"],
      "cegiiklnnort" => ["interlocking"], "aacehillptty" => ["pathetically"],
      "acegloorsuuy" => ["courageously"], "aaccimnopsst" => ["accompanists"],
      "acdeeiipprtt" => ["precipitated"], "abdginoprrss" => ["springboards"],
      "adeeeiorrstt" => ["deteriorates"], "aceeijorrstt" => ["trajectories"],
      "acdeilnoosst" => ["consolidates", "disconsolate"],
      "aaeiilmrsstt" => ["materialists"], "aaceeilnorrt" => ["recreational"],
      "hlmoopsstuuy" => ["posthumously"], "ccdeimnoorss" => ["microseconds"],
      "aaagginorstv" => ["aggravations"], "aabeinsstttu" => ["substantiate"],
      "beeegillnrst" => ["belligerents"], "aeilnooprstx" => ["explorations"],
      "aaacegilmmno" => ["megalomaniac"], "aceeglmnoort" => ["conglomerate"],
      "aegillmrsttu" => ["metallurgist"], "ddefnoooprsu" => ["soundproofed"],
      "beiiilrrssty" => ["irresistibly"], "eeefhmnrrsst" => ["refreshments"],
      "aciilmnnostu" => ["culminations"], "eghiorrssttw" => ["ghostwriters"],
      "accdeeioprrt" => ["reciprocated"], "abeeklmorrtu" => ["troublemaker"],
      "aacdegiinptt" => ["decapitating"], "aacceginnttu" => ["accentuating"],
      "cdeioorsstuu" => ["discourteous"], "adiiilnoqstu" => ["liquidations"],
      "acdeeimnnopr" => ["predominance"], "eefgiimnnnrt" => ["infringement"],
      "deeeeimnprrt" => ["predetermine"], "bcgiinnorttu" => ["contributing"],
      "acceefikrrrs" => ["firecrackers"], "aegiilnprstt" => ["earsplitting"],
      "aagiiimnnost" => ["imaginations"], "aeeeflnrssss" => ["fearlessness"],
      "acceennorstt" => ["concentrates"], "abdeimnorrst" => ["brainstormed"],
      "eeefhiknrrst" => ["freethinkers"], "addeeeiorrtt" => ["deteriorated"],
      "acddeehimnrs" => ["merchandised"], "aacceennostt" => ["concatenates"],
      "deegiinnprst" => ["predestining"], "aeegioprrstv" => ["prerogatives"],
      "abbdemmnorst" => ["bombardments"], "abdehmoorrst" => ["motherboards"],
      "aaceilrtttvy" => ["attractively"], "adefllnrtuuy" => ["fraudulently"],
      "aaceiilmnstx" => ["anticlimaxes"], "aegiinnorsst" => ["resignations"],
      "aceehhmoprty" => ["chemotherapy"], "aaaeinssssst" => ["assassinates"],
      "abegiilnortt" => ["obliterating"], "acddeegklnow" => ["acknowledged"],
      "accdeiklnsst" => ["candlesticks"], "ceeinorstttu" => ["reconstitute"],
      "aacdghiinnpp" => ["handicapping"], "aeegghilnprt" => ["telegraphing"],
      "acciilnoorty" => ["conciliatory"], "acegginnoort" => ["congregation"],
      "ceeeffhoossu" => ["coffeehouses"], "acdeeiinoprt" => ["depreciation"],
      "cceeilsssuvy" => ["successively"], "acillmorsuuy" => ["miraculously"],
      "deeemnnorsst" => ["endorsements"], "abeeilnoqstu" => ["questionable"],
      "deeiinrssstt" => ["disinterests"], "acdeiiimnnrt" => ["incriminated"],
      "aaciiinssttt" => ["statistician"], "eeeiilpprstx" => ["perplexities"],
      "efhlnrssttuu" => ["truthfulness"], "aaaghinpprrs" => ["paraphrasing"],
      "ceefggilnntu" => ["genuflecting"], "aacfiiillrty" => ["artificially"],
      "aaaiilnorttt" => ["totalitarian"], "accgiilmnopt" => ["complicating"],
      "aafilmmnorty" => ["inflammatory"], "cceeiinnnnot" => ["incontinence"],
      "aabcinorsstt" => ["abstractions"], "deghhiorsstt" => ["shortsighted"],
      "deegiilnpruv" => ["unprivileged"], "cceegillnort" => ["recollecting"],
      "abcilllmosyy" => ["symbolically"], "aaeeggginrtx" => ["exaggerating"],
      "aaabeilnnttu" => ["unattainable"], "bbennorssstu" => ["stubbornness"],
      "accefgiiinns" => ["significance"], "aaciilnoppst" => ["applications"],
      "acdgiiinosst" => ["dissociating"], "abdeeiknrrsw" => ["windbreakers"],
      "eegioprrsssv" => ["progressives"], "ciinnorssttu" => ["instructions"],
      "eeehmmorrstt" => ["thermometers"], "ceghiiknprsw" => ["shipwrecking"],
      "aachhiimnprs" => ["chairmanship"], "acdiiilnprsy" => ["disciplinary"],
      "aeeimnoprsst" => ["impersonates"], "eehiimoprssv" => ["impoverishes"],
      "acdeghhnorst" => ["shortchanged"], "aeegiiillmtt" => ["illegitimate"],
      "aeeehlorstux" => ["heterosexual"], "acceemnoppsu" => ["comeuppances"],
      "eeghhinoorss" => ["horseshoeing"], "aceeeenprrsv" => ["perseverance"],
      "aceeilllnttu" => ["intellectual"], "abceiillnpxy" => ["inexplicably"],
      "accinnoorstt" => ["contractions"], "ceeeiimnnprt" => ["impertinence"],
      "ceeegiillnnt" => ["intelligence"], "acdeehorrstt" => ["orchestrated"],
      "ceeilnnnotvy" => ["conveniently"], "aaacehilmmtt" => ["mathematical"],
      "eefghiiknnrt" => ["freethinking"], "aghlnoooprty" => ["anthropology"],
      "ceeinoprrssu" => ["repercussion"], "eghiilnosttu" => ["silhouetting"],
      "bceeeegillnr" => ["belligerence"], "abdeefillstt" => ["battlefields"],
      "aaeegmnoprst" => ["pomegranates"], "aeeghhistvwy" => ["heavyweights"],
      "cdeiillmnoss" => ["milliseconds"], "ccinnoorsttu" => ["construction"],
      "aaeeklnrsstt" => ["rattlesnakes"], "cceeefhiknrs" => ["neckerchiefs"],
      "accefiillpsy" => ["specifically"], "deehiimoprsv" => ["impoverished"],
      "eeeiipqrrstu" => ["prerequisite"], "acdiilnoosst" => ["dislocations"],
      "ccgilmnoorty" => ["motorcycling"], "aaeilnnopstx" => ["explanations"],
      "aeeilprsstuv" => ["superlatives"], "adeeggirrttu" => ["regurgitated"],
      "cdeinooprrtu" => ["reproduction"], "abcgggiiknpy" => ["piggybacking"],
      "abccinoosstt" => ["tobacconists"], "cgghiinoprty" => ["copyrighting"],
      "cdeiilnnppru" => ["unprincipled"], "abeeirrrsstw" => ["strawberries"],
      "aacfiorsstty" => ["satisfactory"], "eehnorssttuw" => ["southwestern"],
      "aaegiinprttx" => ["expatriating"], "aceilnnnostt" => ["continentals"],
      "cceginoppruy" => ["preoccupying"], "acddeeimostt" => ["domesticated"],
      "aeeiiilnqstu" => ["inequalities"], "cddefhiloopr" => ["childproofed"],
      "dddeeinrstuu" => ["understudied"], "addeeimmnrst" => ["masterminded"],
      "aceeeinssstt" => ["necessitates"], "aiiinnoprsst" => ["inspirations"],
      "aeghhiprsuwy" => ["superhighway"], "ceffiiinnstu" => ["insufficient"],
      "aabeeflnrrst" => ["transferable"], "ggghhhiiilnt" => ["highlighting"],
      "aaiilmnnoptu" => ["manipulation"], "eehinnoprsty" => ["hypertension"],
      "defiinoprstu" => ["profundities"], "egiillmnpsss" => ["misspellings"],
      "aacchioprstt" => ["catastrophic"], "eghhnoorsstu" => ["thoroughness"],
      "aaeeginprstx" => ["exasperating"], "aacgillrrtuu" => ["agricultural"],
      "aegiinorsttv" => ["investigator"], "ceipprrssstu" => ["superscripts"],
      "aaeeilnrsttv" => ["alternatives"], "aeggimnnorrw" => ["warmongering"],
      "eeiiooprrsst" => ["repositories"], "abdeegiilnrt" => ["deliberating"],
      "acceefgiimnn" => ["magnificence"], "aadeioppprrt" => ["appropriated"],
      "eeeimnqrrstu" => ["requirements"], "aehiilnoprst" => ["relationship"],
      "eeghilmnorvw" => ["overwhelming"], "aciiinnoottx" => ["intoxication"],
      "aacciinnostv" => ["vaccinations"], "befllooprstu" => ["bulletproofs"],
      "adeegmnrrrsy" => ["gerrymanders"], "abceiknprstu" => ["bankruptcies"],
      "aefiinnosstt" => ["infestations"], "bddfgimnnouu" => ["dumbfounding"],
      "aabceeginrtx" => ["exacerbating"], "cdiillorsuuy" => ["ridiculously"],
      "agiiillmnntu" => ["illuminating"], "ceegimnnoprs" => ["recompensing"],
      "aceeinorstvv" => ["conservative"], "adehilmnorsu" => ["malnourished"],
      "ccenorrssttu" => ["reconstructs"], "abeeeemnrstv" => ["bereavements"],
      "afgiiilnnrtt" => ["infiltrating"], "abceeemmnrrs" => ["remembrances"],
      "adeemnorsstt" => ["demonstrates"], "aabceilorsuv" => ["vocabularies"],
      "aeilmnooprtt" => ["metropolitan"], "aabchiinoott" => ["cohabitation"],
      "cghiloopssty" => ["psychologist"], "aabccgijkkln" => ["blackjacking"],
      "behlooorsttu" => ["troubleshoot"], "aacefmnrstuu" => ["manufactures"],
      "dehlnoorrsuy" => ["horrendously"], "eeiiinrsstuv" => ["universities"],
      "adeegilnnsst" => ["disentangles"], "adeeegginnrt" => ["degenerating"],
      "bdeeeiimorrs" => ["embroideries"], "aeiiinnrsttv" => ["intransitive"],
      "bcddeeeiinos" => ["disobedience"], "aacilmnoorst" => ["astronomical"],
      "adeeeginnort" => ["degeneration"], "aeiiilmprsst" => ["imperialists"],
      "acdeiiinorst" => ["dictionaries"], "acdeeilmnpst" => ["displacement"],
      "aabgimnrsttu" => ["masturbating"], "abceeiillnpx" => ["inexplicable"],
      "abeiilnoortt" => ["obliteration"], "eeegiinorsst" => ["generosities"],
      "deefiiilntvy" => ["definitively"], "eeeinprrssst" => ["intersperses"],
      "aehinoorsttx" => ["exhortations"], "aacennprrsty" => ["transparency"],
      "aabcfiinorst" => ["fabrications"], "ceghiloopssy" => ["psychologies"],
      "giinopprsttu" => ["outstripping"], "eghinooorstv" => ["overshooting"],
      "cdeiimmnooss" => ["commissioned"], "abiiiilrrtty" => ["irritability"],
      "aceeghinnrst" => ["interchanges"], "adeegmnnrrtu" => ["undergarment"],
      "aabcekqrrstu" => ["quarterbacks"], "addeeehinrst" => ["disheartened"],
      "acehilmssttz" => ["schmaltziest"], "afilmnoorstu" => ["formulations"],
      "acdefiilnnot" => ["confidential"], "addeefhlmory" => ["formaldehyde"],
      "aacgilloorst" => ["astrological"], "ceeginnnortu" => ["encountering"],
      "abeiiillnors" => ["billionaires"], "defgiiimnnny" => ["indemnifying"],
      "eefgiinoprrt" => ["profiteering"], "aceeginnprrt" => ["carpentering"],
      "aeimnnorsttu" => ["menstruation"], "aeeiilnnssst" => ["inessentials"],
      "cddeeeiorrsv" => ["rediscovered"], "adeeiimnrrty" => ["intermediary"],
      "acemmnoorstt" => ["commentators"], "acdeiiinppst" => ["appendicitis"],
      "acceennnostu" => ["countenances"], "aacdeimnorsy" => ["aerodynamics"],
      "eefilnnqrtuy" => ["infrequently"], "aegiinprsstt" => ["stripteasing"],
      "abbceeiklrrs" => ["blackberries"], "adeeeopprrsv" => ["eavesdropper"],
      "cddefimoorst" => ["discomforted"], "aaceglnorttu" => ["congratulate"],
      "aaceeinnrrst" => ["reincarnates"], "bddeeeinnsst" => ["indebtedness"],
      "acegghinorrv" => ["overcharging"], "aabcceilllnu" => ["incalculable"],
      "aceeiooprstv" => ["cooperatives"], "aabddeekorst" => ["skateboarded"],
      "afgimnnorrst" => ["transforming"], "aceegiilnstv" => ["evangelistic"],
      "abcgiilllooy" => ["biologically"], "ceimnorssstu" => ["misconstrues"],
      "acefgiiilmns" => ["facsimileing"], "adegiinnosst" => ["designations"],
      "adeiimnnostu" => ["mountainside"], "bdeeimnrsstu" => ["disbursement"],
      "aaccelprsstu" => ["spectaculars"], "acdeeimnprst" => ["predicaments"],
      "acegiiinnnrt" => ["incinerating"], "aceeeegiknpp" => ["peacekeeping"],
      "aeefimnnortt" => ["fermentation"], "abeeelnnnorw" => ["nonrenewable"],
      "ademnoorrstt" => ["demonstrator"], "bciinoprsstu" => ["subscription"],
      "eiiinoqrsstu" => ["requisitions"], "adgiiloorsst" => ["radiologists"],
      "eeeiinrrstvw" => ["interviewers"], "ceeiinoprstt" => ["receptionist"],
      "beelnqsstuuy" => ["subsequently"], "acefiilmnors" => ["infomercials"],
      "aeehhilnsttu" => ["unhealthiest"], "cddeemnnotuu" => ["undocumented"],
      "aefiiilmnsst" => ["semifinalist"], "aahiiilnnnot" => ["annihilation"],
      "ghiiklnnntuy" => ["unthinkingly"], "adeeghprsttu" => ["stepdaughter"],
      "ceegiinnprtt" => ["intercepting"], "aaceeghrrsst" => ["gatecrashers"],
      "aabeiklmnstu" => ["unmistakable"], "aabimnorsttu" => ["masturbation"],
      "acdhiioprstt" => ["dictatorship"], "aeffknrrrstu" => ["frankfurters"],
      "begiimnrsttu" => ["resubmitting"], "ceeehiiprrsv" => ["receivership"],
      "effgiinooprr" => ["fireproofing"], "aeeginpprttu" => ["perpetuating"],
      "abdeimorstux" => ["ambidextrous"], "abeghiilnsst" => ["establishing"],
      "ceimnnooprsu" => ["mispronounce"], "aceeiipprstt" => ["precipitates"],
      "aadddegnnrst" => ["grandstanded"], "ccefllsssuuy" => ["successfully"],
      "aaceelnpsstu" => ["encapsulates"], "aaceilnorstt" => ["altercations"],
      "aaceillmnsty" => ["semantically"], "aeiillrsttuv" => ["illustrative"],
      "addeeimnoprt" => ["predominated"], "aacdeimnnott" => ["contaminated"],
      "bbellnosttuy" => ["bellybuttons"], "cefiloorsuvy" => ["vociferously"],
      "beeiiilrrsst" => ["irresistible"], "adiiillnostt" => ["distillation"],
      "cceeffiiinny" => ["inefficiency"], "cdeeiinnrsst" => ["indirectness"],
      "bceeilnorstv" => ["convertibles"], "adeimnnoorst" => ["denominators"],
      "efgiiinnnsty" => ["intensifying"], "cccdeehkorss" => ["crosschecked"],
      "aegloorstuuy" => ["outrageously"], "aaceenrrsssu" => ["reassurances"],
      "acdeiillnnty" => ["incidentally"], "aceeelmnprst" => ["replacements"],
      "ceghhiilopry" => ["hieroglyphic"], "deefmooprrtu" => ["outperformed"],
      "aaaddeginstv" => ["disadvantage"], "deelmnorstuy" => ["tremendously"],
      "aadeginnpprs" => ["sandpapering"], "aabcceelnptu" => ["unacceptable"],
      "aeiilnoopttx" => ["exploitation"], "aefginnrrrst" => ["transferring"],
      "aeeloopprtuv" => ["overpopulate"], "ccijnnnoostu" => ["conjunctions"],
      "addefiiissst" => ["dissatisfied"], "aegillnnostw" => ["stonewalling"],
      "deeeemoprsst" => ["speedometers"], "aiilnopssttu" => ["stipulations"],
      "aaeeilnprsst" => ["pleasantries"], "aaeeloprsttx" => ["extrapolates"],
      "aaceeiipprtv" => ["appreciative"], "eeiinnnorttv" => ["intervention"],
      "bbddgiilnouy" => ["bodybuilding"], "aabcehilnrtu" => ["uncharitable"],
      "aeghnoopprrr" => ["pornographer"], "aadeeilnqtuy" => ["inadequately"],
      "ceginnorsstu" => ["countersigns"], "aahiinopstxy" => ["asphyxiation"],
      "aaeiinqtttuv" => ["quantitative"], "abdeiiilmnss" => ["inadmissible"],
      "aeeginpprrtt" => ["perpetrating"], "adghiinnsttw" => ["withstanding"],
      "abcceeiilnss" => ["inaccessible"], "abeekorrsstt" => ["breaststroke"],
      "aaceegillnsv" => ["evangelicals"], "aeiinopprrst" => ["perspiration"],
      "bccehorstttu" => ["butterscotch"], "aacfiiimnort" => ["ramification"],
      "addeehoorsvw" => ["overshadowed"], "aaciinnnostt" => ["incantations"],
      "ciinoopprrst" => ["proscription"], "dginnorrssuu" => ["surroundings"],
      "aabeelnnossu" => ["unseasonable"], "abeehlorrsww" => ["wheelbarrows"],
      "acdhhioprrss" => ["harpsichords"], "aceilnopsstu" => ["speculations"],
      "cdeeelmmottu" => ["telecommuted"], "cghimnoorsst" => ["shortcomings"],
      "aabeelnnrsuw" => ["unanswerable"], "acfilnosttuu" => ["fluctuations"],
      "aachllnnnoty" => ["nonchalantly"], "accfgiinnost" => ["confiscating"],
      "bghilnnoottu" => ["buttonholing"], "aehiiimnnstu" => ["inhumanities"],
      "ddeeiopsssss" => ["dispossessed"], "afiilnorrstt" => ["infiltrators"],
      "ceehoopssstt" => ["stethoscopes"], "adeiinoprstv" => ["deprivations"],
      "cciinnoorstt" => ["constriction"], "eimooprssttt" => ["optometrists"],
      "ccghhinoopst" => ["hopscotching"], "addeeeopprsv" => ["eavesdropped"],
      "aceeemnnrstt" => ["reenactments"], "adeeehhlortw" => ["wholehearted"],
      "eefilmooorst" => ["tomfooleries"], "cdeimnorsstu" => ["misconstrued"],
      "aacfiinosstt" => ["satisfaction"], "addeiinoppst" => ["disappointed"],
      "ceeopprssstu" => ["prospectuses"], "aacchiimrsst" => ["charismatics"],
      "eimnoooprrst" => ["promontories"], "deeimopprssu" => ["superimposed"],
      "eegiinnprrtt" => ["interpreting"], "aeeefgirrrst" => ["refrigerates"],
      "ceeeimnorsvw" => ["servicewomen"], "aeghoopprrst" => ["topographers"],
      "abdelmoorsst" => ["bloodstreams"], "aeegimnnrrtu" => ["remunerating"],
      "bciinnoorttu" => ["contribution"], "ahilmnprttuy" => ["triumphantly"],
      "achhillmrtyy" => ["rhythmically"], "adeeeilnrrtt" => ["interrelated"],
      "deefiilnnrss" => ["friendliness"], "aaceehintttu" => ["authenticate"],
      "cemnnoortuwy" => ["countrywomen"], "abdeiiilrsty" => ["desirability"],
      "cdinoorrttuy" => ["introductory"], "cddeenooprrs" => ["corresponded"],
      "abdeeiilnort" => ["deliberation"], "abceehorsttx" => ["chatterboxes"],
      "bccinoosssuu" => ["subconscious"], "aabeeilmmrsu" => ["immeasurable"],
      "aeeegginnrrt" => ["regenerating"], "aceefglnrssu" => ["gracefulness"],
      "accelmmnoops" => ["commonplaces"], "abeellmnopuy" => ["unemployable"],
      "cceinnosttuy" => ["constituency"], "acgimmnnostu" => ["consummating"],
      "bcinoorssttu" => ["obstructions"], "ccdeeiiinsst" => ["insecticides"],
      "aaeioppprrst" => ["appropriates"], "aeiiilmmorst" => ["immoralities"],
      "abbeeillnuvy" => ["unbelievably"], "acegiiillmty" => ["illegitimacy"],
      "cehiooopprst" => ["photocopiers"], "cdeiiimnorst" => ["misdirection"],
      "cdeefginorru" => ["reconfigured"], "aaceghoprrrt" => ["cartographer"],
      "aacdiillssty" => ["sadistically"], "adehinqrrstu" => ["hindquarters"],
      "acdeeimosstt" => ["domesticates"], "adeeghinrstt" => ["straightened"],
      "acciiloprsuy" => ["capriciously"], "aeeiinorrstt" => ["reiterations"],
      "acdggiinorsu" => ["discouraging"], "aahllmmorssw" => ["marshmallows"],
      "aciillnoosst" => ["oscillations"], "aceeeimprsst" => ["masterpieces"],
      "adeiinnopsst" => ["dispensation"], "eeeehlnrsstv" => ["nevertheless"],
      "aabccgikknrt" => ["backtracking"], "aacghlmoopry" => ["pharmacology"],
      "aaiilnnosstt" => ["nationalists"], "bceeeeghrrsu" => ["cheeseburger"],
      "aaaceeenpprr" => ["reappearance"], "cddeeeeinnps" => ["dependencies"],
      "acchiooprrrt" => ["chiropractor"], "aeimnnoppstt" => ["appointments"],
      "acinooprrsst" => ["conspirators"], "accddeinortt" => ["contradicted"],
      "eeeghiknopsu" => ["housekeeping"], "acillllooquy" => ["colloquially"],
      "ciinnoostttu" => ["constitution"], "abcimnorstuu" => ["rambunctious"],
      "ddeeinrsstuu" => ["understudies"], "ceeeilpprtvy" => ["perceptively"],
      "cfghiiknoprt" => ["pitchforking"], "aeeemmnprstt" => ["temperaments"],
      "aeeeiprrstvv" => ["preservative"], "eehnnorrsttw" => ["northwestern"],
      "aeelnoprssss" => ["salespersons"], "aacehiiprrst" => ["patriarchies"],
      "acegillnooru" => ["neurological"], "acenoprrsttu" => ["counterparts"],
      "aeflnoopsstu" => ["teaspoonfuls"], "adefimnoorst" => ["deformations"],
      "acdeghimoprs" => ["demographics"], "addeggiinrrs" => ["disregarding"],
      "acegimmnnott" => ["commentating"], "ceeefhlnrssu" => ["cheerfulness"],
      "aillorrssttu" => ["illustrators"], "aaffiimnorst" => ["affirmations"],
      "aceimnnoopst" => ["compensation"], "aiiillmnnotu" => ["illumination"],
      "defghillltuy" => ["delightfully"], "aeegnrrsssst" => ["transgresses"],
      "ceeefhllrstu" => ["cheerfullest"], "aceehimmnpst" => ["impeachments"],
      "abelllmnoosy" => ["monosyllable"], "cdiiijnorstu" => ["jurisdiction"],
      "aadgiiilnntv" => ["invalidating"], "aaeiilnorstt" => ["retaliations"],
      "befghillrstu" => ["bullfighters"], "aceehiinortt" => ["theoretician"],
      "aceilnooprss" => ["processional"], "cdeeghilnrsu" => ["rescheduling"],
      "ceiinorrsstt" => ["restrictions"], "egghiilnnoop" => ["pigeonholing"],
      "ceefloorrssu" => ["foreclosures"], "ehhiloopprss" => ["philosophers"],
      "aaccdeennott" => ["concatenated"], "aceelmnopstt" => ["contemplates"],
      "aaaaggilmmnt" => ["amalgamating"], "aeillmnoprsy" => ["impersonally"],
      "eeimmnoprstv" => ["improvements"], "aeeeimorsttv" => ["overestimate"],
      "eeiimnnrtttt" => ["intermittent"], "acciilmnoopt" => ["complication"],
      "bdiiinosssuv" => ["subdivisions"], "addiiillnuvy" => ["individually"],
      "bbcdeghilntu" => ["nightclubbed"], "giiinnooprsv" => ["provisioning"],
      "aegiinnoostt" => ["negotiations"], "aceiinnorstt" => ["interactions"],
      "egiinnprrttu" => ["interrupting"], "eeiimnprrstt" => ["misinterpret"],
      "aeehmmooprst" => ["metamorphose"], "cdeiiinnorst" => ["indiscretion"],
      "biinosstttuu" => ["substitution"], "aailnnorsstt" => ["translations"],
      "acdeefhhiknr" => ["handkerchief"], "aeeiimnrrrst" => ["intermarries"],
      "ceeiilmopstx" => ["complexities"], "acdeinnnoost" => ["condensation"],
      "adeekloprssu" => ["loudspeakers"], "bceeimmosttu" => ["subcommittee"],
      "cceeillnoort" => ["recollection"], "deegilnprssy" => ["depressingly"],
      "aabcllooorrt" => ["collaborator"], "adeeghinnppr" => ["apprehending"],
      "aeinoosstttu" => ["ostentatious"], "acdiiinnostv" => ["vindications"],
      "ceeiimoprssu" => ["semiprecious"], "aaeffiimrstv" => ["affirmatives"],
      "aegiimnnoptt" => ["pigmentation"], "dehmnorrsttu" => ["thunderstorm"],
      "acinnooprstt" => ["contraptions"], "adeefiloprrt" => ["proliferated"],
      "accdeiilnnot" => ["coincidental"], "bdehlnorsttu" => ["thunderbolts"],
      "egimnoorrtty" => ["trigonometry"], "aadeimopprtx" => ["approximated"],
      "acdeiillopry" => ["periodically"], "aaaagilmmnot" => ["amalgamation"],
      "aabcdehorrty" => ["carbohydrate"], "aceeehmnnnst" => ["enhancements"],
      "eeeghnorsstt" => ["togetherness"], "aegillmnorst" => ["steamrolling"],
      "cddeeeiprsst" => ["disrespected"], "aefinooprrst" => ["perforations"],
      "biiiiilnstvy" => ["invisibility"], "adeeiopprrtx" => ["expropriated"],
      "cdeeinooprss" => ["processioned"], "acghinoopprr" => ["pornographic"],
      "aabghiinnrsw" => ["brainwashing"], "deeinnrrttuw" => ["underwritten"],
      "ddegnnorrsuu" => ["undergrounds"], "eeilnprsstty" => ["persistently"],
      "aacghilloopt" => ["pathological"], "aeekmprrsstu" => ["supermarkets"],
      "aacdeeeffint" => ["decaffeinate"], "eeeeinssstwy" => ["eyewitnesses"],
      "deeiopssssss" => ["dispossesses"], "aeellmorrsst" => ["steamrollers"],
      "eeeennprrrtu" => ["entrepreneur"], "aaceghnoopry" => ["oceanography"],
      "bdegiillnnps" => ["spellbinding"], "ceeeilprstvy" => ["respectively"],
      "aceeinopsttx" => ["expectations"], "aceelmnnortu" => ["nomenclature"],
      "aggilmnoprtu" => ["promulgating"], "aceehmnnnstt" => ["enchantments"],
      "abcefgilnoru" => ["configurable"], "aaeinopprrst" => ["preparations"],
      "accdeimmnotu" => ["communicated"], "aeeeiinrrstv" => ["veterinaries"],
      "cegikknorsty" => ["skyrocketing"], "dhinooorsttt" => ["orthodontist"],
      "cehilorrttuu" => ["horticulture"], "bdeegiiilnsv" => ["disbelieving"],
      "ceeginrrrstu" => ["resurrecting"], "eegiinnprrst" => ["enterprising"],
      "beeghiillmns" => ["embellishing"], "aaccddemmoot" => ["accommodated"],
      "acdiinnooort" => ["coordination"], "bceijnsstuuv" => ["subjunctives"],
      "ccginnorsttu" => ["constructing"], "aceelmnopttu" => ["outplacement"],
      "acdiinorsstt" => ["distractions"], "eefghilnrrsy" => ["refreshingly"],
      "ccfiiinorsux" => ["crucifixions"], "abeggimnnoor" => ["boomeranging"],
      "aceeeilnrrsv" => ["irrelevances"], "cdeerrrsttuu" => ["restructured"],
      "cceeeimnnopt" => ["incompetence"], "aaeghimnrrtw" => ["heartwarming"],
      "accghhiinttt" => ["chitchatting"], "cdenrrsttuuu" => ["unstructured"],
      "aagiinnnqrtu" => ["quarantining"], "aadegimnqrsu" => ["masquerading"],
      "cdeeeoprrstt" => ["retrospected"], "acdeimnnnoot" => ["condemnation"],
      "adeeiimnrrrt" => ["intermarried"], "abgiilmnootu" => ["automobiling"],
      "accehiilntty" => ["technicality"], "adeginnrsttu" => ["understating"],
      "adeghhoopprt" => ["photographed"], "aabciilnorst" => ["calibrations"],
      "acddeeemmnor" => ["commandeered"], "aeeefilnprrt" => ["preferential"],
      "acilnnooosst" => ["consolations"], "aeghhoopprrt" => ["photographer"],
      "acehirssttww" => ["wristwatches"], "eeilmnnostvv" => ["involvements"],
      "acimnoopsttu" => ["computations"], "acdeinossttu" => ["outdistances"],
      "iinooppssstu" => ["suppositions"], "acmnnoortuwy" => ["countrywoman"],
      "ceefiiiilnst" => ["infelicities"], "eghiilnssttu" => ["unsightliest"],
      "ceehorsstttu" => ["outstretches"], "accdeeilnopy" => ["encyclopedia"],
      "adeeeimnrttx" => ["exterminated"], "aacceilnorvy" => ["clairvoyance"],
      "aceeimmnorst" => ["commentaries"], "aaceeffinott" => ["affectionate"],
      "aadelnnprstt" => ["transplanted"], "aaeeinoprstx" => ["exasperation"],
      "cdeiinnosstu" => ["discontinues"], "abceooorrrst" => ["corroborates"],
      "aabbeiinortv" => ["abbreviation"], "aaellnnpstuy" => ["unpleasantly"],
      "eeeehkoprssu" => ["housekeepers"], "aceiilnoprst" => ["replications"],
      "eeeekoprrsst" => ["storekeepers"], "beegiiilllnt" => ["intelligible"],
      "aeegikllnpsw" => ["sleepwalking"], "ceeiipprrstv" => ["prescriptive"],
      "ehhiilooppss" => ["philosophies"], "eeffllorssty" => ["effortlessly"],
      "aacehilmnpru" => ["alphanumeric"], "aacdefmnrtuu" => ["manufactured"],
      "aaiiilmnosst" => ["assimilation"], "acghillmooty" => ["mythological"],
      "bcdeeiinnost" => ["benedictions"], "abceiinorstt" => ["obstetrician"],
      "ceeinorrrstu" => ["resurrection"], "aaciiinnoptt" => ["anticipation"],
      "aiknoorssttw" => ["workstations"], "aeellmnppstu" => ["supplemental"],
      "aaelnprrstuu" => ["supernatural"], "aegghiilnnst" => ["nightingales"],
      "aabcdginorst" => ["broadcasting"]}
    |> Map.get(string_id)
  end

  def valid_ids do
    ["aaiillnnostt", "abciimnnoost", "aacilmnooprt", "cilnnoostuuy", "degllnorssuw",
     "aeehllmnnopy", "aabefgiknrst", "abcgiikllnst", "ddeelnnopsty", "aaciilnopttu",
     "adeeeeggrsst", "eeginopprstv", "deeginnrrrsu", "ceerrrssttuu", "bcinoorrsttu",
     "aaccehhiilrr", "aeeiopprrstx", "acceilmnnoou", "aacdhiioprss", "abcdeooorrrt",
     "ceelnnoqstuy", "adeeimnrstuv", "aaccehhmosst", "acdegiiknrst", "ccdeeelorttu",
     "adeiinorsstt", "aefnnorsttuu", "aeimnooprrst", "aeeggilnosst", "aabbdeekrsst",
     "abcdeilnorsy", "adeghmnorrst", "accceimnrstu", "aeeemrssssst", "acdeeiiinnrs",
     "aacehoprsstt", "eehlnrsssstu", "aeeinorrsstv", "acceimmnostu", "abeinoorsstv",
     "aaceijllmsty", "acdeiinnnotu", "aceiinoprrtt", "aefmnorrrsst", "cdeginoorrvw",
     "aacdeillnpty", "aegiilrrrtuy", "aceghhnorsst", "aacegiinnrst", "cdeiinoprsst",
     "efgiinnoprsy", "eeginoprstty", "bdeeefiilnns", "ccdeehilpssy", "ceinnosstttu",
     "acehillorrty", "aabeeelnprtu", "aacdeilmrttu", "deefiiinnort", "cginoopprstu",
     "acdeegiinprt", "cdefhlmooorr", "eeginoprssss", "aaccdemmoost", "aaceghiloprs",
     "begiiilllnty", "ccddeimnostu", "aceilnnnootv", "adeeersssstw", "ahimoopppstu",
     "ceehinoorrss", "aaceinrtttuv", "accgiillooos", "cceeennoqssu", "acehiinssttu",
     "adeeffiilnrt", "aabcghiilopr", "abdegiikmnrs", "aeefgiorrrrt", "aaefilnqrrtu",
     "aegiilmnnrst", "aehimnnosstt", "aiillnorsttu", "aaeeiinnrrtv", "deeeinprrsst",
     "aefgillmnnuy", "accdeeinnnst", "accceeeinqsu", "eiinoprssttu", "aacceilnrrtt",
     "bghiillnsttu", "accfiinnoost", "adeeimnoprst", "acdeffgiinst", "achiiprsstty",
     "aachimmnnopy", "cddeeinnostt", "acffiillnouy", "addeeiimnsst", "aginnoprrstt",
     "eeilmooprsst", "aeeillnqtuvy", "acciiinrssst", "acceiloprstu", "aceemmmoorst",
     "acdeefhinnrs", "aceinnoorstv", "ccgiinnnnouv", "ddeeeinnnpst", "ccegijnnortu",
     "aaiilnnorstt", "beehoprrsstt", "aaabeiilmnnt", "abdginnoorsw", "abcdeeilnors",
     "adeehhlorrss", "ceennoorrsst", "aciiinopssuu", "aabeeksssttw", "aaeehimmnpst",
     "aceginorsssu", "cdeeeoprrsss", "aceghhooprry", "acceeilllrty", "acdinooorrst",
     "aacillmnorty", "aeehnnorrstt", "cceeffiinost", "aciilmnoopst", "deeeghnnrstt",
     "deefiiilnnty", "bceeeelnnosv", "aceeimmorsst", "abdehhnossuu", "acilmnooopst",
     "aaeeemnppsst", "ceinooprsstu", "aeeilprssuvy", "acdeelmnoptt", "aeimnrrssttt",
     "adilorssstuy", "aacceeilnort", "aefghhoorrtu", "cdeennrrrtuu", "aadefghnrrst",
     "deeelmnopstv", "eghinoorrtvw", "eiiimnnorsst", "eeeilnrrrtvy", "bcceeelnooss",
     "abdeeeerrrtv", "adeeghimnost", "aaceijlnostu", "deeeilnrsssw", "cdeeilmnoopx",
     "abeeffilnrsu", "deeeinprstux", "aceehimnsstt", "adeeefgirrrt", "aaceillprrst",
     "agghiimnnrst", "abiinorstttu", "abcgikknorst", "dggiilnnrstu", "acdiilnnoost",
     "aagghinoprtu", "aefgimnorrtt", "aaeilnnorstt", "ccdddeeennos", "eelmmnnoptuy",
     "aabegimnrrss", "acegimnnopss", "ccelnnorrtuy", "aeiiimnnnost", "abefgilnoruv",
     "adeiinnnostt", "abehinprsstu", "bhiiinooprst", "aaghiiilnnnt", "ceeeefinnrrt",
     "aabeglmmoprr", "befgilnrttuy", "adefiiisssst", "aainnnoprsst", "ddefghilloot",
     "aaceijkrsttt", "abdelmnorsty", "acgiiilnprtt", "ceefgiilnrty", "bdeeeilmnrtw",
     "aaggiinnrtuu", "accgiiilnnot", "aabefllmmnno", "aadegikmnrrt", "aeffhilnsstu",
     "deeeeimnprtx", "addeeffnrstu", "adeeeiimnrtt", "aeeopprrrstt", "aaceeggillno",
     "acehinoprrss", "achiillorsty", "ccdeiorrssss", "aaeilnopssty", "cghinoooppty",
     "ccefiiinnstu", "ceilnnosstty", "cdhinooorstt", "aaccilmnotuu", "aeghlmnnoors",
     "deeelmnppstu", "abcdeeehirsu", "ccgiinnorstt", "aaccilnooptu", "abceeelmnrss",
     "aceeillnrsuv", "cceeelorsttu", "aacceillnnot", "aaeilmnprstu", "eegiiinnrtvw",
     "aciiilnpprty", "adeeiilnprst", "adgiillnnotu", "aaeegmnnrrst", "abeeeinrrttv",
     "abdeeilprstu", "aegiinorrstt", "aaacceiinptt", "diiillnosssu", "beeeiilrrrsv",
     "degiinopprss", "aeilmnosstuu", "cgiilooossst", "aggimmmnnoor", "acddeeefnort",
     "aceffghilnrs", "clnoprssuuuu", "abceiilnrtxy", "aacdeilnorst", "aeeeinnrrstt",
     "aacegiimrrss", "eeelllnrssty", "cddegiiinrst", "abbghiilopry", "accegiinrtux",
     "achhiloprsss", "ceeelmmorttu", "aabeghiknrtt", "abdeeeilmnrt", "afinorrssttu",
     "acddeilnoost", "eeimopprsssu", "aabeelnnorsu", "abiiilnoostt", "ceeehiknsttt",
     "eeehllnpssss", "eeegilnoprsv", "cceeilllotvy", "cdefgiiinnst", "accegilnnosv",
     "aadeeimmnrst", "adeegmmoprrr", "ddeeeimnnrtu", "cccdeeiinnos", "eiinnoprrttu",
     "cceiorrsssss", "abeiilmnnrty", "eegilnnortuv", "acceelnnostv", "acehhiloptty",
     "bdeegiimmnrs", "aciinnoopstt", "abiilnorsttu", "aceeeflnpssu", "aabeilmmrsuy",
     "acemmnoprstt", "aeiiiilmrsst", "ahiilrssstty", "aeegimnnostt", "acdiinorssyy",
     "aaegillnpprw", "cceeinnnortt", "ceeikknopstv", "adeiilnnorty", "accdeennnotu",
     "aiimnnorssst", "bbcdeeeknrru", "aaffiiilnost", "ceghilnoostt", "ceghilnooors",
     "eiinoprsssuv", "adegiknnrstu", "adeeinnrrstu", "cceeemmmnnot", "adghilnnopry",
     "abcinorssttu", "cceeeiimnnrs", "aceeeilnqsuv", "aacdeeiinqsu", "acceehirrttu",
     "aaeilmnnostt", "aceiillnsstt", "ceeeinnqsstu", "ailnopprtuuy", "egghhhiilrst",
     "adeiinorsttx", "abcdeghiilnr", "aggiiinnortv", "aadeelllnpru", "cdeegimmnnor",
     "aiiinnnosstu", "cceeeinoprsv", "aaccehillmny", "ddeefgnoorru", "aaceiklmnopt",
     "cdeeiiinnstv", "aeeilrrrsstt", "cddeiinnostu", "aabceiiilpst", "aabcdgilnopr",
     "adeeiimnssst", "aaggiiinnrtt", "degllnorssuy", "iinooopprsst", "aaacdillmrty",
     "bceeeinrssuv", "abddeinorstu", "aeehnorssttu", "adeegimssttu", "aeeemnrssttt",
     "acdeiillnstt", "aabcgiikllmn", "acdefiinnstt", "aaagiilnnotv", "aabdeeegilrs",
     "adejmnnorstu", "eeinnoprssuv", "aceiloprrsuy", "abceeilnorst", "aceeirsssttu",
     "accdehilmops", "acdgiinnoort", "ccdeeimnrtuv", "aabbefglrsst", "aaceimoprstv",
     "cdeeiiilnsvy", "aeegilnrsstv", "ceehmorsttyy", "acegiilorssu", "aabeeilnprss",
     "ccgiilnnnovy", "cdiinnoorttu", "ceeeeiinnprx", "aaceilmnostx", "aacehillnstu",
     "lmnnoooostuy", "aabceinrrstt", "abehiilnopst", "bceilorsstuu", "aaacceinnqtu",
     "aabiklmnstuy", "aciiinoqsstu", "aehiinoprrss", "adefhiloorst", "cdeeinrrsttu",
     "eeehlmnossss", "ceeegiinnprx", "ceginnpsstuu", "eeiilmprssvy", "adefiiilqssu",
     "addeeeimprtt", "aeeemmnrsstu", "adeeehprssst", "ceiimmnoprtu", "bdghiimmnrsu",
     "adiiiimnnott", "aacegiilmnns", "eeehilrssstv", "ceeelmmosttu", "agillmnnoosu",
     "aeehoprrsstt", "ccimnnoopstu", "beiinorrsttu", "acegiilnnrsy", "ceeinoprsstu",
     "aabbegiinrtv", "acfiimnnoort", "aaeegginnrtu", "ceeiiinrsstu", "acdeeghinnrt",
     "egiinnoprrtv", "aeeginorrstt", "aacceegilnrt", "iinooprstttu", "eghimnnnoooy",
     "aeegillrsstu", "befghiinrrsu", "acehillnopty", "aceeeilmnpst", "aceehorrsstt",
     "bddfgiillnno", "degiinnrrtuw", "aeimnoprsttu", "acdeeeehlrrs", "aaeegginortx",
     "fginooprrstu", "cceiinnottvy", "addefiiilqsu", "aacceeghosst", "aaeiilmnptuv",
     "eeghiinrstux", "abceillnnoos", "aeeemprrsttu", "aaghiinpstxy", "acefiiinortv",
     "eefgiilmnpxy", "aabdeegilrsy", "aadefgginrsu", "deeegilnoprv", "eeeilmnnsttt",
     "bddeeenorruv", "abdeeilnrssu", "aacfillnorty", "aceginnnortv", "acenoorrstvy",
     "afiiilnnortt", "eeeefghilnrw", "aafiinnosttu", "aeiinnoorstt", "bdgiiinrsttu",
     "eeghilrssttt", "bcinoorrttuy", "aacgiinnostt", "deeiiillrsst", "aeghhiinstww",
     "ciilopsssuuy", "adeeginorrtt", "abeeillnnruv", "eefillpssttu", "eeginooprrvw",
     "ccdeeeinoprv", "aabcdeorrsst", "aabbeilrtttu", "aeehinnopprs", "aacdeelnpstu",
     "aceefmnoprrs", "cceeginnnort", "acfillnnotuy", "adeiinnorstt", "ceeelmnopsst",
     "acdeeeilnsst", "cdfinnosstuy", "aabcdelloort", "addeegilnnst", "acdeehimnrss",
     "aacfiiinortt", "acccegiinnor", "ceeiinnorstt", "bbceelnoosst", "cefiilnoprty",
     "ceehilnnorty", "aaegikmnrrtw", "cdiimmnnoosu", "acdeegklnosw", "aceiiilrsttv",
     "aacehilmpsty", "dddehnnooorr", "cdeeelmmnopt", "acegimnnopst", "cdehkloorsst",
     "deeelnrrsuvy", "abdfginorrsu", "aeegiinnnrtt", "eeeilprssvxy", "eehloprrsstu",
     "aceiinnorrst", "abddeilnoost", "ceinnoorsssu", "abdeiilnpstu", "cdeeelnptuxy",
     "cceillnosuvy", "aacdeeinnrrt", "aeegiinnrtvw", "adeegiinrstt", "aeeehinpprsv",
     "aeeimnnorstu", "aceehiinnrst", "aeghioopprst", "aaciinpprstt", "abdeiiiilsst",
     "aaaceegnrtvx", "aeinoorrsstt", "fghhllottuuy", "aeiimnnorstt", "ddeeenorsuvz",
     "acciilnorstu", "deeimnnrsttu", "bbceilmosstu", "aacehillmpty", "bceeilmnoptt",
     "adeeeghlmmrs", "fgiiimmnnors", "cdellnnoortu", "aeegimsssttu", "aaceffinostt",
     "cdeeiiimorst", "aeefiinrrstt", "aeeegmnnrstt", "bgiilmnnoosw", "acceinnoorst",
     "acehillrstyy", "acefillorsuw", "aaiiilmprtty", "accdeenorttu", "aadehioprrty",
     "cdeehilnprst", "aaciinoossst", "cdeeirrrssvw", "aeeinnoprstt", "deeghiinstux",
     "cdeinorsstuy", "deehiilnqrsu", "acdeeghllnnu", "aaddiiilnopt", "eeffghiirrst",
     "aabceiillnpp", "ceefhkmorrtu", "aacddijorstu", "aaeeillqrstu", "bcgiilmooory",
     "beeiiklnsssu", "aacceeinrrst", "acinoooprstv", "ceiimmnoorss", "aacfgiiilntt",
     "aabeillrrstz", "acgiiinnottx", "aaccgiinrrtu", "ceiiprrrsttw", "aefgiilrtuvy",
     "aabceikllmrs", "aeefiloprrst", "cccgiiimnrsu", "bdhiloorstty", "begiilnnprtu",
     "aabinoopprst", "eehinrssstyz", "ceffiilnstuy", "abciilnopstu", "bcekkoorrsst",
     "aeeggilrssvy", "bdeegiiilnst", "aceeegiknrrt", "aginooprsstt", "deeeinnrsttu",
     "accdeennortt", "deegiilmnnrt", "aabfllmnotyy", "aeggiiilmntt", "aabddeglllrs",
     "aadeilnorttu", "aaeimnoooopt", "defgiiinrsvy", "aeeghnoprrst", "bdehhooorrst",
     "acceeiilnrst", "aaaccdeillmy", "aceeelnrssss", "adgiiiimnntt", "acdeginnnrst",
     "acdeiiimnrst", "cdeeiilnoprt", "accehilmopss", "afinnorssstu", "aaeilnorstuv",
     "aefgggilnopr", "addeemnorstt", "cdeeeiinprss", "aacegiimnnpt", "aeeillnqstuy",
     "aceggginnort", "aaddiillnoty", "deefiilnnrru", "aaggiillnntv", "deefiiiilnst",
     "aaaegiilnrst", "aceeginorrtv", "aaegimnnrrst", "ceehikmnosss", "aceeinoprrtu",
     "aeeinoprrstv", "aacegiinpprt", "deeinnnorsst", "abefilnoprtu", "aaciinnnorst",
     "aefilnooprss", "aabelnnorsuy", "acenoorrsstv", "ceegiinnrssu", "ceefiimnoprt",
     "abcdeinoorst", "aaabcehloppr", "aeeillnrrstt", "aacehiimrrst", "acdeeimmorst",
     "aaccillnoosy", "achhiimnopps", "ceeiijnnortt", "ehiilmrssstv", "ceeiinnnnotv",
     "acdehillmoty", "aabcelloorst", "aceeginprrtu", "aceinooprrst", "acdloooprstt",
     "aciiilmnptuy", "aaabcehillpt", "aeegiinssttv", "aaccceiinrsu", "aceemnnnnotu",
     "ceeeeffnrstv", "aefgillnorst", "aceeghilnrtw", "aaceeklmprst", "aaceilmrsttu",
     "cdeginnorrsu", "aadeilnostuv", "egiiinnnrttw", "aacilnorstvy", "cdeeeeiinpsx",
     "acceelnnrstu", "aeeinrsstttv", "aehioprrstwy", "adeeeimprstt", "eilmorsstuyy",
     "aaeimopprstx", "aabdegiimstu", "aciilnnoostu", "deeenorssuvz", "aacgiilnpttu",
     "abcceilmmnou", "aeeimnnorrtu", "aceimnorsstv", "almnooostuuy", "aadeflmnnstu",
     "eemnnooppstt", "aacceillmstu", "cddeeehmnopr", "aaccillnostu", "eeeinprrrstt",
     "acdeimmnnoot", "ciimnooopsst", "aabeehiilrtt", "adeeenpprrss", "acemnooprsty",
     "ceeghilnoost", "aeeeglmnnntt", "cegimnnnosst", "abiiillpstuy", "abdegiiilntt",
     "adeeiinprsss", "aaccgimnnopy", "aaeilllnrtuy", "aaeghiilnrtx", "acdeeikloops",
     "abdeefiiilnt", "ceilmooprssu", "achnnoorssuy", "acddeinosttu", "bdeghhoorrtu",
     "aaegiilmnort", "aadeeghinprs", "abceeiilnnnt", "emopprsstuuu", "bdeeiirrsttu",
     "aegggilnrsty", "accimmnoortu", "aeeeilnrrstt", "aacceelorrst", "aeghimnorsuw",
     "acchhioppsty", "aafiilmmnnot", "aadegnnprrst", "aaadegnostuv", "eeoopprrsstu",
     "acghhioopprt", "aeeimmnrsttt", "aadegoprsttu", "ahilmnoorsuy", "cdeginnrttuu",
     "ccilmoorstty", "abcdeinrsstu", "ceiinnorrstu", "behhoorssttu", "eegghiilnnnt",
     "acceginnorst", "cdeiinnooprt", "ceehillnosst", "acilnnoosttu", "ceegiijnnrtt",
     "ceghiinnrsst", "ceiinnnosstt", "acfiiinoprtu", "egiillmnptux", "cceiilnnosuv",
     "aabdmoorrrst", "aiilmnnorttu", "cdeffiiilstu", "cdiiilnnstty", "efiilmoprsvy",
     "aaceillmmtuy", "bcdgiikmnors", "diiinoopssst", "acilmmnnoott", "ceeeiiprrstv",
     "clloprssuuuy", "abdeinorsstu", "aaccdeillnty", "eginooprrsss", "aabceeeghlrr",
     "egiinnnortvy", "aeeimnorrttx", "aeeeilmnprtx", "cgiinnostttu", "aaeoopprrrst",
     "inoopprssttu", "abcgiklnoppt", "aabeilnoorst", "aciiilnnnost", "ahhilnopprty",
     "aceefhinnrss", "degilnnorsuy", "eimnopprsstu", "ciiillmpttuy", "aacegginopst",
     "eellorrsstty", "ceefimnnnost", "aeiiilmnnost", "addeeiimnrst", "aeeijnnortuv",
     "ceeillmnopty", "aaadeinsssst", "accdeeelnoss", "aeeeimnrsttx", "acemnooprrty",
     "ceeeinorstux", "acciiilnnoot", "abeeeilmnprt", "aacciiorrstt", "eeeehnnssttv",
     "aehinpprrsst", "ahiiilmnostu", "aagghiijmnst", "eeghlmnnoors", "agiillnrsttu",
     "agiiklmnsttu", "aabbcegikknr", "abeeeerrrstv", "aeiiimnorsss", "iiinnosstttu",
     "aeeiinnprtty", "acdemmmnnost", "aceeefffrstt", "aacegghilopr", "cdiiinnosstt",
     "adeinooprstt", "aacdehillntu", "beeeirsstttw", "aadegilnrttu", "abeghhkorrtu",
     "aegghilnrstu", "aceghhooprrs", "aciiilmnopst", "degiiinnorst", "bcehiimorsty",
     "eeeimnprrsst", "aeeeginnorrt", "aegilnrrssuy", "adeiinnosstt", "cdiioprttuvy",
     "eefghiilrttw", "cdgiiinnnoot", "acdeemmmoort", "aceiinnnortu", "ccceeiinrtty",
     "aeginoorrrtt", "aeghopprrsss", "aabcceirrtuu", "aceegilssttu", "cceinorsttuv",
     "aacciilprtty", "acgiinnnorst", "acehillnopst", "aiimnooprstt", "adegiimnnprr",
     "aacefmnrrtuu", "aeiiillmnors", "abcehlnostuu", "abcgiinnrrst", "bdiiorrssttu",
     "ceefllprstuy", "aacehilmoprt", "adefginooprr", "aacillprrtuy", "aeeinoortttx",
     "acehiintttuy", "acgijnnoostu", "aabeiloorrst", "cdeiinnoorst", "adeeghhilrtt",
     "aeeggirrsttu", "aceghhilrsst", "ceiinopprrst", "aabbeilnnotu", "aaceimnnostt",
     "acceefiirstt", "bdiiinorsttu", "bgiinsstttuu", "accdeimnortu", "aabbeirrsttu",
     "iiiinnoqsstu", "aceiiimnnrst", "aabdeehhrrsy", "beeeelmmntzz", "aacgiilnrttu",
     "aaceiipprstt", "aaeiinoprrtt", "aadeehqrrstu", "aeggiimnnprt", "aacinnorsstt",
     "cdeehorstttu", "ceeeklnrssss", "aeegijnnrtuv", "ailnooopprrt", "aaccgilmntuu",
     "cddeeeinorrs", "aaceiinopprt", "aacdeemnnstv", "eeelnrssssst", "aadegiinpprs",
     "ceeiinnoprtt", "abcelllnoort", "abeehllrssty", "ceiimnoopstt", "cceeeinnnosv",
     "aacdeiipprtt", "aaahiimnnrtu", "degiinnossuu", "aceiilrrsstu", "addeefhoorsw",
     "deegiinppsst", "abceiilmnopt", "eiimmnnoprst", "bdeegiimnorr", "abeeiilmnnrt",
     "aefimnoorrst", "abciilmnopty", "aaeghhiknrst", "cemnoopsttuu", "aaeghlmnrstu",
     "aaeilnoprrst", "eeeginnprrst", "cceflnsssuuu", "ccceennorrsu", "aaabiiilltvy",
     "aciinnnoottu", "ceeimnnopstt", "agiimnnrsttt", "ddeeeenortvx", "aabdgilnnsst",
     "acdeeeinsstt", "cgiimmnooprs", "adeiimnnnoot", "abdeglnorttu", "bdeefiilrstu",
     "giinoprstttu", "deeinnoqstuu", "ccegiknorrsw", "aaeiimnnostx", "aeilmnnrsttu",
     "ccehilnopsty", "adgiinopprsv", "adeeegimnrst", "accegiiknrsw", "ceehklnossuy",
     "aeeghipprstw", "efgiinnprrst", "eegiilmmnnpt", "cfgiiilmmnor", "aceeehimnstv",
     "acfilmnnostu", "agiinnoopprt", "abbbehlmortu", "eginoppprssu", "ciiinnoprsst",
     "ccddeeinorst", "begimnnortuu", "aadeelmnprtt", "aaccdeeinrrt", "ccciiimnorsu",
     "aabceilmnopr", "eeiinopprsst", "aacceilmprst", "adeghllnorst", "acdeinooprrt",
     "abcdhiorsstw", "abcceemnnrsu", "aaciillrstty", "aabccelnptuy", "acceillmnooy",
     "eeeghimnostu", "cddeeeeinnnp", "eeekloopppss", "egilnoorsstu", "acinoooprrst",
     "abcdgiklnoor", "gghhinoorsuu", "accdeefiirtt", "deinooopprrt", "aegimnnrsttu",
     "eeehlnopssss", "cdeeilmmnopt", "adeehirrrsss", "acegillmooty", "aceinopssssu",
     "adeefooprrtw", "aeehilstuvxy", "addeeeeggrst", "aacegillnort", "gghiilmnnoot",
     "aagiilmnnptu", "adeelmorsstu", "agiiinnoprtt", "eeegiprrrsst", "aceffghinruu",
     "eghilnoprstu", "bceeijlstuvy", "bcegiiilnorr", "aaceillrttuy", "ddeehiiinrst",
     "agghilnoppry", "bfgghiillntu", "gghiilnopstt", "cdeinoprtuuv", "cdeeioprrtuv",
     "aacdilloprsy", "bceghimnnooy", "acceeioprrst", "eehiilnqrssu", "acinnnooostt",
     "acceiinoprss", "adeegnrrssst", "ceefinorsttu", "aceghiillnyy", "aabeennrrstu",
     "aegilmnoprsv", "eeknoopprsss", "giilnprrssuy", "acchiiloprty", "defhinprsstt",
     "eeghiilnnprs", "ccdeeefiiins", "abdeeinnrrsw", "aaeiilmnoort", "acddeehinnst",
     "accellnoptuy", "aeeeglmnnrst", "acceillmmory", "cdgiiiilnnps", "eeghiinsstux",
     "aeiinnopsstx", "acdeeirssttu", "aaiillnorrty", "aacgiiinnptt", "aabdeekorrst",
     "aceilnoorrst", "acdeegilsttu", "acghiilnnort", "aaaiilmprrty", "eghinooprrsv",
     "acdhhinoopry", "ggiiillnnotu", "aaceiimnnopt", "ceegiinnrstt", "eegiilmnnrst",
     "aceimmorrstu", "ceeiklmnppru", "fginoopsstuy", "adeegiknnrrt", "acehlmmnootw",
     "ceeillorssty", "aaegiinprrtt", "eefiiinnrsst", "abbeeeillnuv", "aaciilnorttu",
     "adeiinoprstu", "aaelnrssstux", "acdeeefnorst", "ceillmostuuy", "adeegiinsttv",
     "aadeeloprttx", "aaehiilnortx", "aabeeklmnrru", "ahillnoortyz", "cdeeeffiinnr",
     "agilorsttuuy", "bbceklorsstu", "aacfiinnosst", "aefghhortttu", "adeejmnrsttu",
     "eiinoopprsst", "acimmnnoostu", "adeehimrssst", "aafiilnnorty", "ceeeipprsstv",
     "aeilnoortuvy", "aaceknnorstu", "aacddgiijntu", "acdiiinoosst", "aaceiilnrttu",
     "acdfiiimnoot", "aeiilmnosstt", "cceillooopss", "acddeeinnrsu", "cdeeehiloprt",
     "abdeeeillrty", "ccddeeinnost", "aacfggilmnou", "beegloorrttt", "ceehlooprrss",
     "egghhiilsttw", "acehiiopsstt", "eeimnnnorstv", "acdeiinnortt", "aceiiinnnort",
     "aaeilllmrttu", "aagiinnortuu", "aeeglmnnortv", "eiimnnooprst", "acchiiinstuv",
     "eeggilsstuvy", "aeiilorrrstt", "aachimnnorss", "dggiilnsstuy", "aagiiilmnsst",
     "egilmnooostt", "aabceefiprrt", "acfiiinnoott", "ddeefiiinntu", "ehmnnoorrstt",
     "acegiinnpprt", "abdeiiirsssu", "acgiinnopstt", "aeegiillmtty", "aaagghinpprr",
     "cdegiiimnrst", "accegilllooy", "aacdeilmmort", "aefgllnrtuuy", "aceeimnorsvw",
     "aghiloopsstt", "cegiiklnnort", "aacehillptty", "acegloorsuuy", "aaccimnopsst",
     "acdeeiipprtt", "abdginoprrss", "adeeeiorrstt", "aceeijorrstt", "acdeilnoosst",
     "aaeiilmrsstt", "aaceeilnorrt", "hlmoopsstuuy", "ccdeimnoorss", "aaagginorstv",
     "aabeinsstttu", "beeegillnrst", "aeilnooprstx", "aaacegilmmno", "aceeglmnoort",
     "aegillmrsttu", "ddefnoooprsu", "beiiilrrssty", "eeefhmnrrsst", "aciilmnnostu",
     "eghiorrssttw", "accdeeioprrt", "abeeklmorrtu", "aacdegiinptt", "aacceginnttu",
     "cdeioorsstuu", "adiiilnoqstu", "acdeeimnnopr", "eefgiimnnnrt", "deeeeimnprrt",
     "bcgiinnorttu", "acceefikrrrs", "aegiilnprstt", "aagiiimnnost", "aeeeflnrssss",
     "acceennorstt", "abdeimnorrst", "eeefhiknrrst", "addeeeiorrtt", "acddeehimnrs",
     "aacceennostt", "deegiinnprst", "aeegioprrstv", "abbdemmnorst", "abdehmoorrst",
     "aaceilrtttvy", "adefllnrtuuy", "aaceiilmnstx", "aegiinnorsst", "aceehhmoprty",
     "aaaeinssssst", "abegiilnortt", "acddeegklnow", "accdeiklnsst", "ceeinorstttu",
     "aacdghiinnpp", "aeegghilnprt", "acciilnoorty", "acegginnoort", "ceeeffhoossu",
     "acdeeiinoprt", "cceeilsssuvy", "acillmorsuuy", "deeemnnorsst", "abeeilnoqstu",
     "deeiinrssstt", "acdeiiimnnrt", "aaciiinssttt", "eeeiilpprstx", "efhlnrssttuu",
     "aaaghinpprrs", "ceefggilnntu", "aacfiiillrty", "aaaiilnorttt", "accgiilmnopt",
     "aafilmmnorty", "cceeiinnnnot", "aabcinorsstt", "deghhiorsstt", "deegiilnpruv",
     "cceegillnort", "abcilllmosyy", "aaeeggginrtx", "aaabeilnnttu", "bbennorssstu",
     "accefgiiinns", "aaciilnoppst", "acdgiiinosst", "abdeeiknrrsw", "eegioprrsssv",
     "ciinnorssttu", "eeehmmorrstt", "ceghiiknprsw", "aachhiimnprs", "acdiiilnprsy",
     "aeeimnoprsst", "eehiimoprssv", "acdeghhnorst", "aeegiiillmtt", "aeeehlorstux",
     "acceemnoppsu", "eeghhinoorss", "aceeeenprrsv", "aceeilllnttu", "abceiillnpxy",
     "accinnoorstt", "ceeeiimnnprt", "ceeegiillnnt", "acdeehorrstt", "ceeilnnnotvy",
     "aaacehilmmtt", "eefghiiknnrt", "aghlnoooprty", "ceeinoprrssu", "eghiilnosttu",
     "bceeeegillnr", "abdeefillstt", "aaeegmnoprst", "aeeghhistvwy", "cdeiillmnoss",
     "ccinnoorsttu", "aaeeklnrsstt", "cceeefhiknrs", "accefiillpsy", "deehiimoprsv",
     "eeeiipqrrstu", "acdiilnoosst", "ccgilmnoorty", "aaeilnnopstx", "aeeilprsstuv",
     "adeeggirrttu", "cdeinooprrtu", "abcgggiiknpy", "abccinoosstt", "cgghiinoprty",
     "cdeiilnnppru", "abeeirrrsstw", "aacfiorsstty", "eehnorssttuw", "aaegiinprttx",
     "aceilnnnostt", "cceginoppruy", "acddeeimostt", "aeeiiilnqstu", "cddefhiloopr",
     "dddeeinrstuu", "addeeimmnrst", "aceeeinssstt", "aiiinnoprsst", "aeghhiprsuwy",
     "ceffiiinnstu", "aabeeflnrrst", "ggghhhiiilnt", "aaiilmnnoptu", "eehinnoprsty",
     "defiinoprstu", "egiillmnpsss", "aacchioprstt", "eghhnoorsstu", "aaeeginprstx",
     "aacgillrrtuu", "aegiinorsttv", "ceipprrssstu", "aaeeilnrsttv", "aeggimnnorrw",
     "eeiiooprrsst", "abdeegiilnrt", "acceefgiimnn", "aadeioppprrt", "eeeimnqrrstu",
     "aehiilnoprst", "eeghilmnorvw", "aciiinnoottx", "aacciinnostv", "befllooprstu",
     "adeegmnrrrsy", "abceiknprstu", "aefiinnosstt", "bddfgimnnouu", "aabceeginrtx",
     "cdiillorsuuy", "agiiillmnntu", "ceegimnnoprs", "aceeinorstvv", "adehilmnorsu",
     "ccenorrssttu", "abeeeemnrstv", "afgiiilnnrtt", "abceeemmnrrs", "adeemnorsstt",
     "aabceilorsuv", "aeilmnooprtt", "aabchiinoott", "cghiloopssty", "aabccgijkkln",
     "behlooorsttu", "aacefmnrstuu", "dehlnoorrsuy", "eeiiinrsstuv", "adeegilnnsst",
     "adeeegginnrt", "bdeeeiimorrs", "aeiiinnrsttv", "bcddeeeiinos", "aacilmnoorst",
     "adeeeginnort", "aeiiilmprsst", "acdeiiinorst", "acdeeilmnpst", "aabgimnrsttu",
     "abceeiillnpx", "abeiilnoortt", "eeegiinorsst", "deefiiilntvy", "eeeinprrssst",
     "aehinoorsttx", "aacennprrsty", "aabcfiinorst", "ceghiloopssy", "giinopprsttu",
     "eghinooorstv", "cdeiimmnooss", "abiiiilrrtty", "aceeghinnrst", "adeegmnnrrtu",
     "aabcekqrrstu", "addeeehinrst", "acehilmssttz", "afilmnoorstu", "acdefiilnnot",
     "addeefhlmory", "aacgilloorst", "ceeginnnortu", "abeiiillnors", "defgiiimnnny",
     "eefgiinoprrt", "aceeginnprrt", "aeimnnorsttu", "aeeiilnnssst", "cddeeeiorrsv",
     "adeeiimnrrty", "acemmnoorstt", "acdeiiinppst", "acceennnostu", "aacdeimnorsy",
     "eefilnnqrtuy", "aegiinprsstt", "abbceeiklrrs", "adeeeopprrsv", "cddefimoorst",
     "aaceglnorttu", "aaceeinnrrst", "bddeeeinnsst", "acegghinorrv", "aabcceilllnu",
     "aceeiooprstv", "aabddeekorst", "afgimnnorrst", "aceegiilnstv", "abcgiilllooy",
     "ceimnorssstu", "acefgiiilmns", "adegiinnosst", "adeiimnnostu", "bdeeimnrsstu",
     "aaccelprsstu", "acdeeimnprst", "acegiiinnnrt", "aceeeegiknpp", "aeefimnnortt",
     "abeeelnnnorw", "ademnoorrstt", "bciinoprsstu", "eiiinoqrsstu", "adgiiloorsst",
     "eeeiinrrstvw", "ceeiinoprstt", "beelnqsstuuy", "acefiilmnors", "aeehhilnsttu",
     "cddeemnnotuu", "aefiiilmnsst", "aahiiilnnnot", "ghiiklnnntuy", "adeeghprsttu",
     "ceegiinnprtt", "aaceeghrrsst", "aabeiklmnstu", "aabimnorsttu", "acdhiioprstt",
     "aeffknrrrstu", "begiimnrsttu", "ceeehiiprrsv", "effgiinooprr", "aeeginpprttu",
     "abdeimorstux", "abeghiilnsst", "ceimnnooprsu", "aceeiipprstt", "aadddegnnrst",
     "ccefllsssuuy", "aaceelnpsstu", "aaceilnorstt", "aaceillmnsty", "aeiillrsttuv",
     "addeeimnoprt", "aacdeimnnott", "bbellnosttuy", "cefiloorsuvy", "beeiiilrrsst",
     "adiiillnostt", "cceeffiiinny", "cdeeiinnrsst", "bceeilnorstv", "adeimnnoorst",
     "efgiiinnnsty", "cccdeehkorss", "aegloorstuuy", "aaceenrrsssu", "acdeiillnnty",
     "aceeelmnprst", "ceghhiilopry", "deefmooprrtu", "aaaddeginstv", "deelmnorstuy",
     "aadeginnpprs", "aabcceelnptu", "aeiilnoopttx", "aefginnrrrst", "aeeloopprtuv",
     "ccijnnnoostu", "addefiiissst", "aegillnnostw", "deeeemoprsst", "aiilnopssttu",
     "aaeeilnprsst", "aaeeloprsttx", "aaceeiipprtv", "eeiinnnorttv", "bbddgiilnouy",
     "aabcehilnrtu", "aeghnoopprrr", "aadeeilnqtuy", "ceginnorsstu", "aahiinopstxy",
     "aaeiinqtttuv", "abdeiiilmnss", "aeeginpprrtt", "adghiinnsttw", "abcceeiilnss",
     "abeekorrsstt", "aaceegillnsv", "aeiinopprrst", "bccehorstttu", "aacfiiimnort",
     "addeehoorsvw", "aaciinnnostt", "ciinoopprrst", "dginnorrssuu", "aabeelnnossu",
     "abeehlorrsww", "acdhhioprrss", "aceilnopsstu", "cdeeelmmottu", "cghimnoorsst",
     "aabeelnnrsuw", "acfilnosttuu", "aachllnnnoty", "accfgiinnost", "bghilnnoottu",
     "aehiiimnnstu", "ddeeiopsssss", "afiilnorrstt", "ceehoopssstt", "adeiinoprstv",
     "cciinnoorstt", "eimooprssttt", "ccghhinoopst", "addeeeopprsv", "aceeemnnrstt",
     "adeeehhlortw", "eefilmooorst", "cdeimnorsstu", "aacfiinosstt", "addeiinoppst",
     "ceeopprssstu", "aacchiimrsst", "eimnoooprrst", "deeimopprssu", "eegiinnprrtt",
     "aeeefgirrrst", "ceeeimnorsvw", "aeghoopprrst", "abdelmoorsst", "aeegimnnrrtu",
     "bciinnoorttu", "ahilmnprttuy", "achhillmrtyy", "adeeeilnrrtt", "deefiilnnrss",
     "aaceehintttu", "cemnnoortuwy", "abdeiiilrsty", "cdinoorrttuy", "cddeenooprrs",
     "abdeeiilnort", "abceehorsttx", "bccinoosssuu", "aabeeilmmrsu", "aeeegginnrrt",
     "aceefglnrssu", "accelmmnoops", "abeellmnopuy", "cceinnosttuy", "acgimmnnostu",
     "bcinoorssttu", "ccdeeiiinsst", "aaeioppprrst", "aeiiilmmorst", "abbeeillnuvy",
     "acegiiillmty", "cehiooopprst", "cdeiiimnorst", "cdeefginorru", "aaceghoprrrt",
     "aacdiillssty", "adehinqrrstu", "acdeeimosstt", "adeeghinrstt", "acciiloprsuy",
     "aeeiinorrstt", "acdggiinorsu", "aahllmmorssw", "aciillnoosst", "aceeeimprsst",
     "adeiinnopsst", "eeeehlnrsstv", "aabccgikknrt", "aacghlmoopry", "aaiilnnosstt",
     "bceeeeghrrsu", "aaaceeenpprr", "cddeeeeinnps", "acchiooprrrt", "aeimnnoppstt",
     "acinooprrsst", "accddeinortt", "eeeghiknopsu", "acillllooquy", "ciinnoostttu",
     "abcimnorstuu", "ddeeinrsstuu", "ceeeilpprtvy", "cfghiiknoprt", "aeeemmnprstt",
     "aeeeiprrstvv", "eehnnorrsttw", "aeelnoprssss", "aacehiiprrst", "acegillnooru",
     "acenoprrsttu", "aeflnoopsstu", "adefimnoorst", "acdeghimoprs", "addeggiinrrs",
     "acegimmnnott", "ceeefhlnrssu", "aillorrssttu", "aaffiimnorst", "aceimnnoopst",
     "aiiillmnnotu", "defghillltuy", "aeegnrrsssst", "ceeefhllrstu", "aceehimmnpst",
     "abelllmnoosy", "cdiiijnorstu", "aadgiiilnntv", "aaeiilnorstt", "befghillrstu",
     "aceehiinortt", "aceilnooprss", "cdeeghilnrsu", "ceiinorrsstt", "egghiilnnoop",
     "ceefloorrssu", "ehhiloopprss", "aaccdeennott", "aceelmnopstt", "aaaaggilmmnt",
     "aeillmnoprsy", "eeimmnoprstv", "aeeeimorsttv", "eeiimnnrtttt", "acciilmnoopt",
     "bdiiinosssuv", "addiiillnuvy", "bbcdeghilntu", "giiinnooprsv", "aegiinnoostt",
     "aceiinnorstt", "egiinnprrttu", "eeiimnprrstt", "aeehmmooprst", "cdeiiinnorst",
     "biinosstttuu", "aailnnorsstt", "acdeefhhiknr", "aeeiimnrrrst", "ceeiilmopstx",
     "acdeinnnoost", "adeekloprssu", "bceeimmosttu", "cceeillnoort", "deegilnprssy",
     "aabcllooorrt", "adeeghinnppr", "aeinoosstttu", "acdiiinnostv", "ceeiimoprssu",
     "aaeffiimrstv", "aegiimnnoptt", "dehmnorrsttu", "acinnooprstt", "adeefiloprrt",
     "accdeiilnnot", "bdehlnorsttu", "egimnoorrtty", "aadeimopprtx", "acdeiillopry",
     "aaaagilmmnot", "aabcdehorrty", "aceeehmnnnst", "eeeghnorsstt", "aegillmnorst",
     "cddeeeiprsst", "aefinooprrst", "biiiiilnstvy", "adeeiopprrtx", "cdeeinooprss",
     "acghinoopprr", "aabghiinnrsw", "deeinnrrttuw", "ddegnnorrsuu", "eeilnprsstty",
     "aacghilloopt", "aeekmprrsstu", "aacdeeeffint", "eeeeinssstwy", "deeiopssssss",
     "aeellmorrsst", "eeeennprrrtu", "aaceghnoopry", "bdegiillnnps", "ceeeilprstvy",
     "aceeinopsttx", "aceelmnnortu", "aggilmnoprtu", "aceehmnnnstt", "abcefgilnoru",
     "aaeinopprrst", "accdeimmnotu", "aeeeiinrrstv", "cegikknorsty", "dhinooorsttt",
     "cehilorrttuu", "bdeegiiilnsv", "ceeginrrrstu", "eegiinnprrst", "beeghiillmns",
     "aaccddemmoot", "acdiinnooort", "bceijnsstuuv", "ccginnorsttu", "aceelmnopttu",
     "acdiinorsstt", "eefghilnrrsy", "ccfiiinorsux", "abeggimnnoor", "aceeeilnrrsv",
     "cdeerrrsttuu", "cceeeimnnopt", "aaeghimnrrtw", "accghhiinttt", "cdenrrsttuuu",
     "aagiinnnqrtu", "aadegimnqrsu", "cdeeeoprrstt", "acdeimnnnoot", "adeeiimnrrrt",
     "abgiilmnootu", "accehiilntty", "adeginnrsttu", "adeghhoopprt", "aabciilnorst",
     "acddeeemmnor", "aeeefilnprrt", "acilnnooosst", "aeghhoopprrt", "acehirssttww",
     "eeilmnnostvv", "acimnoopsttu", "acdeinossttu", "iinooppssstu", "acmnnoortuwy",
     "ceefiiiilnst", "eghiilnssttu", "ceehorsstttu", "accdeeilnopy", "adeeeimnrttx",
     "aacceilnorvy", "aceeimmnorst", "aaceeffinott", "aadelnnprstt", "aaeeinoprstx",
     "cdeiinnosstu", "abceooorrrst", "aabbeiinortv", "aaellnnpstuy", "eeeehkoprssu",
     "aceiilnoprst", "eeeekoprrsst", "beegiiilllnt", "aeegikllnpsw", "ceeiipprrstv",
     "ehhiilooppss", "eeffllorssty", "aacehilmnpru", "aacdefmnrtuu", "aaiiilmnosst",
     "acghillmooty", "bcdeeiinnost", "abceiinorstt", "ceeinorrrstu", "aaciiinnoptt",
     "aiknoorssttw", "aeellmnppstu", "aaelnprrstuu", "aegghiilnnst", "aabcdginorst"]
    |> Enum.into(HashSet.new)
  end
end
