defmodule Jumble.ScowlDict.Size40.Length4 do
  def get(string_id) do
    %{"grsu" => ["rugs"], "ekow" => ["woke"],
      "hstu" => ["tush", "huts", "shut", "thus"], "eilw" => ["wile"],
      "eilm" => ["lime", "mile"], "hloy" => ["holy"], "afos" => ["oafs", "sofa"],
      "gimr" => ["grim"], "bbes" => ["ebbs"], "intw" => ["twin"],
      "adkn" => ["dank"], "gnos" => ["song"], "adip" => ["paid"],
      "ilnt" => ["lint"], "aetz" => ["zeta"], "imps" => ["imps"],
      "dhtu" => ["thud"], "deho" => ["hoed"], "dehs" => ["shed"],
      "blos" => ["lobs", "slob"], "aegv" => ["gave"], "flux" => ["flux"],
      "aees" => ["ease"], "irwy" => ["wiry"], "besw" => ["webs"],
      "iquz" => ["quiz"], "ilmp" => ["limp"], "blow" => ["bowl", "blow"],
      "aept" => ["pate", "peat", "tape"], "ceht" => ["etch"],
      "gstu" => ["gust", "tugs", "guts"], "cefl" => ["clef"],
      "eilt" => ["lite", "tile"], "ahow" => ["whoa"], "best" => ["best", "bets"],
      "aesy" => ["ayes", "easy"], "bill" => ["bill"], "afir" => ["fair"],
      "aeht" => ["hate", "heat"], "girs" => ["rigs"], "ekls" => ["elks"],
      "achp" => ["chap"], "eikt" => ["kite"], "kosw" => ["woks"],
      "agnp" => ["pang"], "elos" => ["sole", "lose"], "eert" => ["tree"],
      "aikn" => ["akin"], "diks" => ["skid", "kids", "disk"], "ceir" => ["rice"],
      "anst" => ["ants", "tans"], "emos" => ["some"], "agot" => ["toga", "goat"],
      "ceor" => ["core"], "ahst" => ["hats"], "cikp" => ["pick"],
      "iqtu" => ["quit"], "bmsu" => ["bums"], "egst" => ["gets"],
      "iklo" => ["kilo"], "amsy" => ["yams"], "aelt" => ["tale", "late"],
      "amps" => ["amps", "maps"], "antw" => ["want"], "aitx" => ["taxi"],
      "impw" => ["wimp"], "eils" => ["isle", "lies"], "ehlp" => ["help"],
      "deln" => ["lend"], "dims" => ["dims"], "arsw" => ["wars"],
      "foor" => ["roof"], "ilot" => ["toil"], "aemx" => ["exam"],
      "eekw" => ["week"], "adhr" => ["hard"], "amss" => ["mass"],
      "afhl" => ["half"], "adds" => ["dads", "adds"], "ehno" => ["hone"],
      "fssu" => ["fuss"], "loot" => ["loot", "tool"], "fuzz" => ["fuzz"],
      "npuy" => ["puny"], "deeg" => ["geed", "edge"], "ackp" => ["pack"],
      "ahtw" => ["thaw", "what"], "beit" => ["bite"], "ddoo" => ["dodo"],
      "aklr" => ["lark"], "elru" => ["lure", "rule"], "ikss" => ["skis", "kiss"],
      "clru" => ["curl"], "dnos" => ["nods", "dons"], "elns" => ["lens"],
      "hosw" => ["hows", "show"], "deem" => ["deem"], "arwy" => ["awry", "wary"],
      "beij" => ["jibe"], "eorw" => ["wore"], "ansy" => ["nays"],
      "pttu" => ["putt"], "bllu" => ["bull"], "akmr" => ["mark"],
      "chop" => ["chop"], "hrtu" => ["hurt"], "aapp" => ["papa"],
      "aftw" => ["waft"], "gnot" => ["tong"],
      "aprs" => ["pars", "raps", "rasp", "spar"], "cjko" => ["jock"],
      "agsy" => ["gays"], "jlot" => ["jolt"], "dorw" => ["word"],
      "agns" => ["nags", "sang", "snag"], "elpy" => ["yelp"], "hntu" => ["hunt"],
      "acev" => ["cave"], "pstu" => ["puts"], "eipp" => ["pipe"],
      "delw" => ["lewd", "weld"], "noos" => ["soon"], "fgit" => ["gift"],
      "mosw" => ["mows"], "cmsu" => ["scum", "cums"], "aepx" => ["apex"],
      "desy" => ["dyes"], "alov" => ["oval"], "aalv" => ["lava"],
      "aehr" => ["hare", "hear"], "bdei" => ["bide"], "cdeo" => ["coed", "code"],
      "loos" => ["solo"], "adry" => ["yard"], "diov" => ["void"],
      "ills" => ["ills", "sill"], "akos" => ["oaks", "soak"], "efrs" => ["refs"],
      "bboo" => ["boob"], "dmru" => ["drum"], "adep" => ["aped"],
      "belo" => ["lobe"], "deis" => ["dies", "side"], "iklm" => ["milk"],
      "delo" => ["dole"], "dilw" => ["wild"], "imot" => ["omit"],
      "hist" => ["shit", "hits", "this"], "nort" => ["torn"],
      "aeps" => ["apes", "peas"], "ahsy" => ["hays"], "orsy" => ["rosy"],
      "awxy" => ["waxy"], "irst" => ["stir"], "admn" => ["damn"],
      "cdru" => ["crud", "curd"], "mstu" => ["smut", "must"], "hklu" => ["hulk"],
      "allm" => ["mall"], "cdlo" => ["clod", "cold"], "eppr" => ["prep"],
      "abds" => ["dabs"], "fnot" => ["font"], "afmo" => ["foam"],
      "aceg" => ["cage"], "abde" => ["bade", "bead"], "bdsu" => ["buds", "dubs"],
      "entu" => ["tune"], "imnt" => ["mint"], "intt" => ["tint"],
      "elms" => ["elms"], "acht" => ["chat"], "bety" => ["byte"],
      "aegs" => ["sage", "ages"], "gilt" => ["gilt"], "doru" => ["dour"],
      "ilps" => ["lips", "lisp", "slip"], "eopp" => ["pope"], "know" => ["know"],
      "fglu" => ["gulf"], "essu" => ["sues", "uses"], "elry" => ["lyre", "rely"],
      "gijs" => ["jigs"], "dknu" => ["dunk"], "emop" => ["mope", "poem"],
      "aknt" => ["tank"], "blru" => ["blur"], "istz" => ["zits"],
      "aelm" => ["lame", "male", "meal"], "ehmt" => ["them"], "ginp" => ["ping"],
      "egnt" => ["gent"], "aeev" => ["eave"], "hmow" => ["whom"],
      "mouv" => ["ovum"], "lmsu" => ["slum"], "dlou" => ["loud"],
      "eirs" => ["sire", "rise"], "afiw" => ["waif"],
      "ilos" => ["oils", "silo", "soil"], "eegs" => ["gees"],
      "losw" => ["lows", "owls", "slow"], "aesw" => ["awes"], "ejko" => ["joke"],
      "ehmo" => ["home"], "dinr" => ["rind"], "einv" => ["vine", "vein"],
      "ailn" => ["nail", "lain"], "gotu" => ["gout"], "fort" => ["fort"],
      "eilr" => ["rile"], "eorz" => ["zero"], "mnor" => ["morn", "norm"],
      "afgn" => ["fang"], "cksu" => ["suck"], "behr" => ["herb"],
      "gips" => ["pigs"], "ahss" => ["sash"], "knoo" => ["nook"],
      "aegw" => ["wage"], "ipst" => ["pits", "spit", "tips"], "ainr" => ["rain"],
      "assy" => ["says"], "abin" => ["bani"], "illp" => ["pill"],
      "fruy" => ["fury"], "aegz" => ["gaze"], "adis" => ["dais", "aids", "said"],
      "aclo" => ["cola", "coal"], "cops" => ["cops"], "emmo" => ["memo"],
      "acst" => ["cast", "cats", "acts"], "eooz" => ["ooze"], "afnw" => ["fawn"],
      "arty" => ["tray"], "imsw" => ["swim"], "adqu" => ["quad"],
      "estz" => ["zest"], "agin" => ["gain"], "aefl" => ["flea", "leaf"],
      "efls" => ["self"], "opss" => ["sops"], "lowy" => ["yowl"],
      "amot" => ["moat", "atom"], "cdtu" => ["duct"], "cikk" => ["kick"],
      "adrt" => ["dart"], "bclo" => ["bloc"], "lnoy" => ["only"],
      "knsu" => ["sunk"], "eilu" => ["lieu"], "defl" => ["fled"],
      "koor" => ["rook"], "bglo" => ["glob", "blog"], "mmos" => ["moms"],
      "anyz" => ["zany"], "flou" => ["foul"], "bgos" => ["gobs", "bogs"],
      "lops" => ["lops", "slop"], "aehv" => ["have"], "deop" => ["dope"],
      "osst" => ["toss"], "bkoo" => ["book"], "belu" => ["blue"],
      "aerr" => ["rear", "rare"], "inow" => ["wino"], "dlop" => ["plod"],
      "acdr" => ["card"], "aemr" => ["mare", "ream"], "cltu" => ["cult"],
      "acrt" => ["cart"], "djou" => ["judo"], "mrsu" => ["rums"],
      "efst" => ["fest"], "efiw" => ["wife"], "avwy" => ["wavy"],
      "astv" => ["vats", "vast"], "eikp" => ["pike"], "abfl" => ["flab"],
      "bhot" => ["both"], "cehk" => ["heck"], "ilms" => ["slim"],
      "acer" => ["acre", "care", "race"], "dfnu" => ["fund"],
      "desu" => ["dues", "sued", "used"], "alor" => ["oral"],
      "ader" => ["dare", "dear", "read"], "iort" => ["trio", "riot"],
      "agst" => ["stag", "tags"], "bdes" => ["beds"], "depu" => ["dupe"],
      "oppr" => ["prop"], "agoy" => ["yoga"], "foot" => ["foot"],
      "denv" => ["vend"], "admp" => ["damp"], "adst" => ["tads"],
      "aegr" => ["gear", "rage"], "lopt" => ["plot"], "dels" => ["sled"],
      "adlo" => ["load"], "egls" => ["gels", "legs"], "aorr" => ["roar"],
      "eejr" => ["jeer"], "gjsu" => ["jugs"], "hlsu" => ["lush"],
      "dily" => ["idly"], "adot" => ["toad"], "ahkr" => ["hark"],
      "bblu" => ["bulb"], "amoy" => ["mayo"], "boor" => ["boor"],
      "cghu" => ["chug"], "bdis" => ["bids"], "ahoy" => ["ahoy"],
      "dehr" => ["herd"], "mnoo" => ["mono", "moon"], "absw" => ["swab"],
      "aehp" => ["heap"], "bhoo" => ["hobo"], "apry" => ["pray"],
      "alpy" => ["play"], "ostw" => ["stow", "tows", "twos"], "acel" => ["lace"],
      "hisw" => ["wish"], "ahrs" => ["rash"], "elmo" => ["mole"],
      "aflo" => ["foal", "loaf"], "enox" => ["oxen"], "cehw" => ["chew"],
      "adps" => ["pads"], "begs" => ["begs"], "dgnu" => ["dung"],
      "amst" => ["mast", "mats"], "dluy" => ["duly"], "allt" => ["tall"],
      "gitw" => ["twig"], "aims" => ["aims"], "chko" => ["hock"],
      "aett" => ["teat"], "afmr" => ["farm"], "ainp" => ["pain"],
      "jmpu" => ["jump"], "estw" => ["stew", "wets", "west"], "dnop" => ["pond"],
      "cikl" => ["lick"], "abes" => ["base"], "beik" => ["bike"],
      "asty" => ["stay"], "eovw" => ["wove"], "kmno" => ["monk"],
      "anvy" => ["navy"], "bent" => ["bent"], "adns" => ["sand"],
      "hnsu" => ["shun"], "aben" => ["bane", "bean"], "belt" => ["belt"],
      "hoop" => ["hoop"], "brsu" => ["rubs"], "dgru" => ["drug"],
      "ekrt" => ["trek"], "degy" => ["edgy"], "artt" => ["tart"],
      "bjos" => ["jobs"], "amny" => ["many"], "bclu" => ["club"],
      "deer" => ["deer", "reed"], "epry" => ["prey", "pyre"], "ghhi" => ["high"],
      "ablm" => ["balm", "lamb"], "deet" => ["teed"], "ciss" => ["sics"],
      "egru" => ["urge"], "chir" => ["rich"], "entt" => ["tent"],
      "adet" => ["date"], "elpt" => ["pelt"], "jost" => ["jots"],
      "inot" => ["into"], "aert" => ["tear", "rate"], "girt" => ["grit"],
      "ehty" => ["they"], "cein" => ["nice"], "ahpr" => ["harp"],
      "beer" => ["beer"], "eekp" => ["peek", "keep"], "gisw" => ["swig", "wigs"],
      "efos" => ["foes"], "opsy" => ["posy"], "ppsu" => ["pups"],
      "illm" => ["mill"], "apsz" => ["zaps"], "abot" => ["boat"],
      "abbr" => ["barb"], "bceu" => ["cube"], "cgos" => ["cogs"],
      "dees" => ["seed"], "dhos" => ["shod"], "hhsu" => ["hush"],
      "cllu" => ["cull"], "deov" => ["dove"], "josy" => ["joys"],
      "aggs" => ["gags"], "emrt" => ["term"], "cpsu" => ["cups"],
      "aflt" => ["flat"], "aesv" => ["vase", "save"], "been" => ["been"],
      "dimn" => ["mind"], "aagl" => ["alga", "gala"], "adhs" => ["dash"],
      "hins" => ["shin"], "hkoo" => ["hook"], "hmot" => ["moth"],
      "cell" => ["cell"], "aeft" => ["feat", "fate"], "hmos" => ["ohms"],
      "abem" => ["beam"], "frtu" => ["turf"], "loop" => ["polo", "loop", "pool"],
      "eemr" => ["mere"], "anps" => ["naps", "pans", "snap", "span"],
      "eost" => ["toes"], "adsy" => ["days"], "ekoy" => ["yoke"],
      "ghis" => ["sigh"], "istw" => ["wist", "wits"], "aclt" => ["talc"],
      "iknw" => ["wink"], "delm" => ["meld"], "abdu" => ["daub", "baud"],
      "cetu" => ["cute"], "bcir" => ["crib"], "nost" => ["snot", "tons"],
      "bdoy" => ["body"], "efnr" => ["fern"], "glpu" => ["gulp", "plug"],
      "eilp" => ["pile"], "acpr" => ["carp", "crap"], "beil" => ["bile"],
      "ckuy" => ["yuck"], "ikmn" => ["mink"], "delu" => ["duel"],
      "ghnu" => ["hung"], "knpu" => ["punk"], "drsy" => ["drys"],
      "agps" => ["gaps", "gasp"], "deos" => ["odes", "dose", "does"],
      "dllu" => ["dull"], "mpru" => ["rump"], "errs" => ["errs"],
      "acds" => ["scad"], "aels" => ["ales", "seal", "sale"], "oprs" => ["pros"],
      "opsu" => ["opus", "soup"], "film" => ["film"], "bmnu" => ["numb"],
      "enno" => ["neon", "none"], "deku" => ["duke"], "gost" => ["togs"],
      "nosw" => ["sown", "owns", "snow"], "apsw" => ["paws", "wasp", "swap"],
      "alos" => ["also"], "cekp" => ["peck"], "ejkr" => ["jerk"],
      "flot" => ["loft"], "adft" => ["daft"], "nnoo" => ["noon"],
      "acrs" => ["arcs", "scar", "cars"], "dssu" => ["suds"],
      "alst" => ["slat", "salt", "last"], "adez" => ["daze"], "bttu" => ["butt"],
      "enov" => ["oven"], "emno" => ["omen"], "llop" => ["poll"],
      "eflw" => ["flew"], "eelp" => ["peel"], "bdeo" => ["bode"],
      "bdet" => ["debt"], "imss" => ["miss"], "efir" => ["rife", "fire"],
      "ikll" => ["kill"], "lllu" => ["lull"], "hips" => ["hips", "ship"],
      "bgsu" => ["bugs"], "ajsw" => ["jaws"], "ailv" => ["vial"],
      "adgo" => ["goad"], "aelz" => ["zeal"], "eekn" => ["knee", "keen"],
      "aekw" => ["wake", "weak"], "hilt" => ["hilt"], "aekl" => ["lake", "leak"],
      "ahlu" => ["haul"], "deno" => ["node", "done"], "ansu" => ["anus"],
      "bimr" => ["brim"], "afry" => ["fray"], "ejst" => ["jets", "jest"],
      "bmoo" => ["boom"], "acft" => ["fact"], "ddei" => ["died"],
      "aehz" => ["haze"], "acek" => ["cake"], "hnor" => ["horn"],
      "mmsu" => ["mums"], "aamm" => ["mama"], "agss" => ["sags"],
      "bklu" => ["bulk"], "nopr" => ["porn"], "kopy" => ["poky"],
      "ceop" => ["cope"], "ahpt" => ["path"], "dirt" => ["dirt"],
      "beef" => ["beef"], "anov" => ["nova"], "llpu" => ["pull"],
      "eghu" => ["huge"], "afil" => ["fail"], "dlot" => ["told"],
      "bder" => ["bred"], "abcs" => ["cabs", "scab"], "abel" => ["bale", "able"],
      "aghs" => ["gash", "hags"], "lpsu" => ["plus"], "betu" => ["tube"],
      "jstu" => ["juts", "just"], "bnor" => ["born"], "chik" => ["hick"],
      "osvw" => ["vows"], "bdmu" => ["dumb"], "aehy" => ["yeah"],
      "alot" => ["alto"], "abdn" => ["band"], "frsu" => ["furs", "surf"],
      "aekm" => ["make"], "ikps" => ["skip"], "eeks" => ["ekes", "seek"],
      "ostu" => ["oust", "outs"], "egor" => ["gore", "ogre", "ergo"],
      "anno" => ["anon"], "eorv" => ["rove", "over"], "deey" => ["eyed"],
      "ahmr" => ["harm"], "iknt" => ["knit"], "ehlo" => ["hole"],
      "ikkn" => ["kink"], "notw" => ["wont", "town"], "ertu" => ["true"],
      "abst" => ["bats", "stab", "tabs"], "dhis" => ["dish"], "ffit" => ["tiff"],
      "belw" => ["blew"], "adln" => ["land"], "acde" => ["aced"],
      "ally" => ["ally"], "bilm" => ["limb"], "bops" => ["bops"],
      "gsuy" => ["guys"], "abkn" => ["bank"], "lrsu" => ["slur"],
      "eflt" => ["felt", "left"], "flop" => ["flop"], "oruy" => ["your"],
      "mooz" => ["zoom"], "eimt" => ["mite", "emit", "item", "time"],
      "ffos" => ["offs"], "eels" => ["eels", "else"], "nrtu" => ["runt", "turn"],
      "prsu" => ["spur"], "intu" => ["unit"], "oort" => ["root"],
      "glsu" => ["lugs", "slug"], "dnow" => ["down"], "dfor" => ["ford"],
      "npsu" => ["spun", "puns"], "ehiv" => ["hive"], "almo" => ["loam"],
      "fizz" => ["fizz"], "agnt" => ["gnat", "tang"], "ortu" => ["rout", "tour"],
      "coop" => ["coop"], "afst" => ["fats", "fast"], "dity" => ["tidy"],
      "aest" => ["teas", "seat", "east", "eats"], "afkl" => ["flak"],
      "ehpy" => ["hype"], "cdek" => ["deck"], "beno" => ["bone"],
      "acry" => ["racy"], "eswy" => ["yews"], "dstu" => ["stud", "dust"],
      "ehsu" => ["hues"], "ostt" => ["tots"], "aijl" => ["jail"],
      "acks" => ["cask", "sack"], "emov" => ["move"], "gist" => ["gist"],
      "ikno" => ["oink"], "mppu" => ["pump"], "berv" => ["verb"],
      "derw" => ["drew"], "hmty" => ["myth"], "elmu" => ["mule"],
      "ffru" => ["ruff"], "eeps" => ["pees", "seep"], "cssu" => ["cuss"],
      "eenv" => ["even"], "ikns" => ["inks", "sink", "skin"], "ajms" => ["jams"],
      "amor" => ["roam"], "ajsy" => ["jays"], "msuw" => ["swum"],
      "aksy" => ["yaks"], "irtw" => ["writ"], "aces" => ["aces", "case"],
      "bilo" => ["boil"], "agls" => ["gals", "lags", "slag"], "ceiv" => ["vice"],
      "kstu" => ["tusk"], "elnt" => ["lent"], "ahkw" => ["hawk"],
      "chmu" => ["chum", "much"], "eins" => ["sine"], "cnor" => ["corn"],
      "deef" => ["feed"], "aipr" => ["pair"], "eesy" => ["eyes"],
      "bbis" => ["bibs"], "ahtt" => ["that"], "elor" => ["lore", "role"],
      "aefr" => ["fare", "fear"], "eirw" => ["wire"], "ensy" => ["yens"],
      "nstu" => ["nuts", "stun"], "bosy" => ["boys"], "aefs" => ["safe"],
      "bden" => ["bend"], "beep" => ["beep"], "deks" => ["desk"],
      "deep" => ["peed", "deep"], "agmr" => ["gram"], "fgis" => ["figs"],
      "ehll" => ["hell"], "adgr" => ["grad", "drag"], "envy" => ["envy"],
      "acem" => ["mace", "came"], "elop" => ["lope", "pole"],
      "abet" => ["bate", "abet", "beat", "beta"], "nrsu" => ["urns", "runs"],
      "bouy" => ["buoy"], "allp" => ["pall"], "antu" => ["tuna", "aunt"],
      "acox" => ["coax"], "bnoy" => ["bony"], "dfoo" => ["food"],
      "aent" => ["ante", "neat"], "aclw" => ["claw"], "ccko" => ["cock"],
      "eotv" => ["veto", "vote"], "afgl" => ["flag"],
      "lost" => ["slot", "lost", "lots"], "eens" => ["seen"],
      "enot" => ["tone", "note"], "ahms" => ["hams", "mash", "sham"],
      "ijno" => ["join"], "abit" => ["bait"], "aals" => ["alas"],
      "eott" => ["tote"], "door" => ["door"], "hiss" => ["hiss"],
      "ceov" => ["cove"], "abil" => ["bail"], "alms" => ["alms", "slam"],
      "dhoo" => ["hood"], "emor" => ["more"], "bhsu" => ["hubs", "bush"],
      "ablw" => ["bawl"], "gmsy" => ["gyms"], "mttu" => ["mutt"],
      "bflu" => ["flub"], "aklw" => ["walk"], "bblo" => ["blob"],
      "illw" => ["will"], "inpt" => ["pint"], "eltu" => ["lute"],
      "eerw" => ["weer", "were"], "hmny" => ["hymn"], "ahls" => ["lash"],
      "ekpu" => ["puke"], "ails" => ["ails", "sail"],
      "aemt" => ["mate", "meat", "tame", "team"], "inor" => ["iron"],
      "fost" => ["soft"], "aelx" => ["axle"], "aegp" => ["gape", "page"],
      "aehl" => ["hale", "heal"], "arst" => ["tars", "arts", "rats", "star"],
      "amrw" => ["warm"], "bssu" => ["subs", "buss"], "cktu" => ["tuck"],
      "egps" => ["pegs"], "hipw" => ["whip"], "bdlo" => ["bold"],
      "boot" => ["boot"], "acsw" => ["caws"], "alsw" => ["laws"],
      "dikn" => ["kind"], "aimn" => ["main"], "abjm" => ["jamb"],
      "aerv" => ["rave"], "aovw" => ["avow"], "eptw" => ["wept"],
      "aden" => ["dean"], "cstu" => ["cuts"], "deft" => ["deft"],
      "aiot" => ["iota"], "acms" => ["scam"], "aops" => ["soap"],
      "acot" => ["taco", "coat"], "dill" => ["dill"], "fglo" => ["flog", "golf"],
      "bnoo" => ["boon"], "ilwy" => ["wily"], "abht" => ["bath"],
      "elly" => ["yell"], "cosw" => ["cows"], "ikms" => ["skim"],
      "elss" => ["less"], "beiv" => ["vibe"], "cdei" => ["iced", "dice"],
      "gknu" => ["gunk"], "defu" => ["feud"], "firs" => ["firs"],
      "adeg" => ["aged"], "eisw" => ["wise"], "copy" => ["copy"],
      "ciks" => ["sick"], "noot" => ["onto"], "eiln" => ["lien", "line"],
      "aenp" => ["nape", "pane"], "emtu" => ["mute"], "fins" => ["fins"],
      "abhl" => ["blah"], "aags" => ["saga"], "arsy" => ["rays"],
      "bdno" => ["bond"], "nptu" => ["punt"], "inos" => ["ions"],
      "ffgu" => ["guff"], "ehns" => ["hens"], "epps" => ["peps"],
      "alsy" => ["slay", "lays"], "ailr" => ["lair", "liar", "rail"],
      "gilr" => ["girl"], "esty" => ["yest"], "dmor" => ["dorm"],
      "aenr" => ["earn", "near"], "aegm" => ["game"], "alss" => ["lass"],
      "dips" => ["dips"], "efil" => ["file", "life"], "kloo" => ["look"],
      "bnos" => ["snob"], "eltw" => ["welt"], "emst" => ["stem"],
      "deil" => ["deli", "idle", "lied"], "adeh" => ["head"], "ghin" => ["nigh"],
      "aflp" => ["flap"], "ceex" => ["exec"], "eegl" => ["glee"],
      "iikw" => ["kiwi"], "deor" => ["doer", "redo", "rode"], "eekr" => ["reek"],
      "epsy" => ["yeps"], "egms" => ["megs", "gems"], "dost" => ["dots"],
      "lopy" => ["ploy"], "ahlt" => ["lath", "halt"], "essw" => ["sews"],
      "chit" => ["chit", "itch"], "ceit" => ["cite"],
      "enos" => ["noes", "nose", "ones"], "cikn" => ["nick"], "gipr" => ["grip"],
      "ijnx" => ["jinx"], "abgr" => ["brag", "garb", "grab"],
      "adil" => ["dial", "laid"], "ehor" => ["hero"], "adnr" => ["darn"],
      "ilmo" => ["limo"], "glos" => ["slog", "logs"], "agrs" => ["rags"],
      "cloo" => ["cool"], "aelp" => ["peal", "leap", "pale", "plea"],
      "agll" => ["gall"], "cdko" => ["dock"], "dffu" => ["duff"],
      "dehu" => ["hued"], "lllo" => ["loll"], "chin" => ["chin", "inch"],
      "imtt" => ["mitt"], "notu" => ["unto"], "ipqu" => ["quip"],
      "eefr" => ["reef", "free"], "corw" => ["crow"], "cefh" => ["chef"],
      "ipty" => ["pity"], "dtuy" => ["duty"], "hlow" => ["howl"],
      "efiv" => ["five"], "moor" => ["moor", "room"], "eepw" => ["weep"],
      "egks" => ["kegs"], "iltt" => ["tilt"], "agnw" => ["gnaw"],
      "akpr" => ["park"], "aekr" => ["rake"], "bnru" => ["burn"],
      "esst" => ["sets"], "opru" => ["pour"], "abdr" => ["bard", "drab"],
      "inns" => ["inns"], "defn" => ["fend"], "oopr" => ["poor"],
      "elvy" => ["levy"], "acnt" => ["cant"], "ehmp" => ["hemp"],
      "irss" => ["sirs"], "aflw" => ["flaw"], "bcku" => ["buck"],
      "hims" => ["hims"], "ffpu" => ["puff"], "ipsw" => ["wisp"],
      "fist" => ["fist", "sift", "fits"], "ehms" => ["hems", "mesh"],
      "ggis" => ["gigs"], "ammo" => ["ammo"], "ados" => ["soda"],
      "aprw" => ["warp", "wrap"], "eerv" => ["veer", "ever"], "mops" => ["mops"],
      "gjos" => ["jogs"], "horu" => ["hour"], "aawy" => ["away"],
      "ckmo" => ["mock"], "abbl" => ["blab"], "ddee" => ["deed"],
      "acmr" => ["cram"], "aefm" => ["fame"], "floo" => ["fool"],
      "enop" => ["nope", "peon", "open"], "filo" => ["foil"], "ahot" => ["oath"],
      "aems" => ["seam", "same"], "afns" => ["fans"], "hllu" => ["hull"],
      "acdl" => ["clad"], "efsu" => ["fuse"], "eitx" => ["exit"],
      "efmu" => ["fume"], "egiv" => ["give"], "ailp" => ["pail"],
      "egln" => ["glen"], "eesv" => ["eves"], "hknu" => ["hunk"],
      "eegn" => ["gene"], "abks" => ["bask"], "fhoo" => ["hoof"],
      "demn" => ["mend"], "opps" => ["pops"], "acss" => ["sacs"],
      "hpsu" => ["push"], "ailw" => ["wail"], "dein" => ["dine"],
      "ehtw" => ["whet"], "eisv" => ["vies", "vise"], "aclm" => ["clam", "calm"],
      "eirt" => ["rite", "tier", "tire"], "inss" => ["sins"], "aquy" => ["quay"],
      "ampr" => ["pram", "ramp"], "dfin" => ["find"], "ittw" => ["twit"],
      "korw" => ["work"], "eegk" => ["geek"], "fimr" => ["firm"],
      "deeh" => ["heed"], "host" => ["shot", "host"], "cest" => ["sect"],
      "orsu" => ["sour", "ours"], "eflu" => ["flue", "fuel"], "eetw" => ["twee"],
      "hmpu" => ["hump"], "osty" => ["toys"], "acnr" => ["narc"],
      "eklp" => ["kelp"], "aens" => ["sane"], "abtu" => ["tuba"],
      "ahsw" => ["wash"], "iklt" => ["kilt"], "deot" => ["dote", "toed"],
      "elmt" => ["melt"], "jruy" => ["jury"], "chow" => ["chow"],
      "dhin" => ["hind"], "abrs" => ["bras", "bars"], "aswy" => ["sway", "ways"],
      "boss" => ["sobs", "boss"], "iimn" => ["mini"], "ehik" => ["hike"],
      "akor" => ["okra"], "koot" => ["took"], "acly" => ["clay", "lacy"],
      "lnoo" => ["loon"], "entx" => ["next"], "aaru" => ["aura"],
      "ceip" => ["epic"], "abek" => ["beak", "bake"], "nnou" => ["noun"],
      "aevw" => ["wave"], "attw" => ["watt"], "astw" => ["swat"],
      "cklo" => ["lock"], "eist" => ["site", "ties"], "gory" => ["gory", "orgy"],
      "eors" => ["ores", "roes", "rose", "sore"], "bgil" => ["glib"],
      "bsuy" => ["busy", "buys"], "efin" => ["fine"], "gint" => ["ting"],
      "aery" => ["year"], "bcsu" => ["cubs"], "hill" => ["hill"],
      "acmp" => ["camp"], "ckmu" => ["muck"], "allw" => ["wall"],
      "elov" => ["love"], "eops" => ["pose"], "eelr" => ["leer", "reel"],
      "eent" => ["teen"], "egrw" => ["grew"], "bknu" => ["bunk"],
      "ackl" => ["lack"], "copr" => ["crop"], "kopr" => ["pork"],
      "attu" => ["taut"], "bcos" => ["cobs"], "cemo" => ["come"],
      "bbos" => ["bobs"], "illy" => ["lily"], "bgnu" => ["bung"],
      "cffu" => ["cuff"], "dkor" => ["dork"], "copu" => ["coup"],
      "nosu" => ["onus"], "bstu" => ["buts", "stub", "tubs", "bust"],
      "oopp" => ["poop"], "birs" => ["ribs"], "ehlm" => ["helm"],
      "aajr" => ["ajar"], "aitw" => ["wait"], "ajrs" => ["jars"],
      "adel" => ["lade", "deal", "lead"], "aerw" => ["ware", "wear"],
      "opst" => ["pots", "opts", "tops", "post", "spot", "stop"],
      "akmo" => ["amok"], "abis" => ["bias"], "ensw" => ["sewn", "news"],
      "oosw" => ["woos"], "llnu" => ["null"], "answ" => ["swan"],
      "llor" => ["roll"], "deit" => ["tide", "diet", "edit", "tied"],
      "eimn" => ["mien", "mine"], "dksu" => ["dusk"], "amns" => ["mans"],
      "iirs" => ["iris"], "dent" => ["dent", "tend"], "iknr" => ["rink"],
      "gruu" => ["guru"], "cilo" => ["coil"], "ghsu" => ["gush", "hugs"],
      "ahyz" => ["hazy"], "dmpu" => ["dump"], "firt" => ["rift"],
      "bmot" => ["tomb"], "apst" => ["pats", "spat", "taps", "past"],
      "noss" => ["sons"], "deiw" => ["wide"], "cdis" => ["disc"],
      "ahlo" => ["halo"], "ejll" => ["jell"], "eips" => ["pies"],
      "impr" => ["prim"], "gluy" => ["ugly"], "flru" => ["furl"],
      "orsw" => ["rows"], "dgir" => ["grid"], "erst" => ["rest"],
      "lmpu" => ["plum", "lump"], "aadt" => ["data"], "osuy" => ["yous"],
      "gill" => ["gill"], "ahhs" => ["hash"], "coos" => ["coos"],
      "aekt" => ["teak", "take"], "gmos" => ["smog"], "dehi" => ["hide"],
      "alnw" => ["lawn"], "hjno" => ["john"], "eepr" => ["peer"],
      "ipss" => ["piss", "sips"], "defy" => ["defy"], "fllu" => ["full"],
      "eems" => ["seem"], "ilst" => ["silt", "slit", "list"], "einw" => ["wine"],
      "cglo" => ["clog"], "alyz" => ["lazy"], "bffu" => ["buff"],
      "eglu" => ["glue"], "epsw" => ["pews", "spew"], "degl" => ["geld"],
      "bist" => ["bits"], "acns" => ["cans", "scan"], "amry" => ["army"],
      "acep" => ["cape", "pace"], "acen" => ["acne", "cane"], "aaer" => ["area"],
      "fgor" => ["frog"], "aenv" => ["vane"], "afll" => ["fall"],
      "aabs" => ["baas"], "beor" => ["robe", "bore"], "dgoo" => ["good"],
      "eikl" => ["like"], "efll" => ["fell"], "aggn" => ["gang"],
      "dops" => ["pods"], "cess" => ["secs"], "ceru" => ["cure"],
      "ghtu" => ["thug"], "mopr" => ["prom", "romp"], "emnu" => ["menu"],
      "cilp" => ["clip"], "anrt" => ["rant"], "eekm" => ["meek"],
      "celu" => ["clue"], "anrw" => ["warn"], "moos" => ["moos"],
      "arzz" => ["razz"], "egos" => ["egos", "goes"], "abkr" => ["bark"],
      "egno" => ["gone"], "aisv" => ["visa"], "llmu" => ["mull"],
      "hlru" => ["hurl"], "aers" => ["ares", "eras", "sear", "ears"],
      "glno" => ["long"], "insw" => ["wins"], "lmoo" => ["loom"],
      "norw" => ["worn"], "pssu" => ["puss"], "ceil" => ["lice"],
      "aglo" => ["goal"], "achk" => ["hack"], "dllo" => ["doll"],
      "nopu" => ["upon"], "ahll" => ["hall"], "amrs" => ["mars", "rams", "arms"],
      "alps" => ["laps", "pals", "slap"], "city" => ["city"], "eksy" => ["keys"],
      "acll" => ["call"], "eipw" => ["wipe"], "chou" => ["ouch"],
      "anpt" => ["pant"], "abdl" => ["bald"], "epst" => ["pest", "pets", "step"],
      "denr" => ["nerd", "rend"], "botu" => ["bout"], "empr" => ["perm"],
      "inps" => ["nips", "snip", "pins", "spin"], "dosu" => ["duos"],
      "bdin" => ["bind"], "adsw" => ["wads"], "ekty" => ["tyke"],
      "doow" => ["wood"], "lopp" => ["plop"], "deim" => ["dime"],
      "aisx" => ["axis"], "bilp" => ["blip"], "eest" => ["tees"],
      "deen" => ["need"], "chsu" => ["such"], "imrs" => ["rims"],
      "aepv" => ["pave"], "berw" => ["brew"], "elsw" => ["slew"],
      "adfs" => ["fads"], "imst" => ["mist"], "adms" => ["dams", "mads"],
      "enoz" => ["zone"], "drtu" => ["turd"], "ahir" => ["hair"],
      "csty" => ["cyst"], "almp" => ["palm", "lamp"], "mopp" => ["pomp"],
      "aprt" => ["tarp", "rapt", "part", "trap"], "ervy" => ["very"],
      "airs" => ["airs", "sari"], "cklu" => ["luck"], "eosw" => ["woes", "owes"],
      "akst" => ["task"], "eprt" => ["pert"], "abck" => ["back"],
      "eeft" => ["feet"], "nosy" => ["nosy"], "istu" => ["suit"],
      "ghos" => ["gosh", "hogs"], "eeht" => ["thee"], "llot" => ["toll"],
      "akss" => ["asks"], "aemn" => ["amen", "mane", "mean", "name"],
      "fill" => ["fill"], "emot" => ["tome"], "dinw" => ["wind"],
      "gloo" => ["logo"], "eemt" => ["mete", "teem", "meet"],
      "hmsu" => ["hums", "mush"], "eefl" => ["flee", "feel"], "abos" => ["boas"],
      "ikrs" => ["irks", "risk"], "bmos" => ["mobs"], "dpsu" => ["spud"],
      "eijv" => ["jive"], "ahmw" => ["wham"], "cikt" => ["tick"],
      "ahox" => ["hoax"], "hkno" => ["honk"], "bdel" => ["bled"],
      "kloy" => ["yolk"], "esxy" => ["sexy"], "ably" => ["ably"],
      "aefk" => ["fake"], "oops" => ["oops"], "dfno" => ["fond"],
      "knot" => ["knot"], "bkno" => ["knob"], "aerz" => ["raze"],
      "ortt" => ["tort", "trot"], "eesx" => ["exes"], "epty" => ["type"],
      "aekp" => ["peak"], "booz" => ["bozo"], "osww" => ["wows"],
      "adkr" => ["dark"], "einp" => ["pine"], "glnu" => ["lung"],
      "fgos" => ["fogs"], "gllu" => ["gull"], "adde" => ["dead"],
      "adew" => ["awed", "wade"], "impp" => ["pimp"], "achs" => ["cash"],
      "gnow" => ["gown"], "amrt" => ["mart"], "ehrs" => ["hers"],
      "eers" => ["seer"], "eisz" => ["size"], "iprs" => ["rips"],
      "ehww" => ["whew"], "achr" => ["arch", "char"], "klru" => ["lurk"],
      "adls" => ["lads"], "bpru" => ["burp"], "ckor" => ["cork", "rock"],
      "ikls" => ["silk"], "dnou" => ["undo"], "cnos" => ["cons"],
      "ettx" => ["text"], "acmo" => ["coma"], "besy" => ["byes"],
      "oprw" => ["prow"], "beet" => ["beet"], "crtu" => ["curt"],
      "ehnw" => ["when"], "afit" => ["fiat"], "ehov" => ["hove"],
      "ekpr" => ["perk"], "cnsy" => ["sync"], "egmr" => ["germ"],
      "loss" => ["loss"], "dgis" => ["digs"], "adnw" => ["wand", "dawn"],
      "ddeu" => ["dude"], "mssu" => ["muss", "sums"], "ffim" => ["miff"],
      "elno" => ["lone"], "deky" => ["dyke"], "ijlt" => ["jilt"],
      "empt" => ["temp"], "iltw" => ["wilt"], "ciky" => ["icky"],
      "inst" => ["snit", "nits", "tins"], "abrt" => ["brat"], "bbmo" => ["bomb"],
      "eejz" => ["jeez"], "denu" => ["dune", "nude"], "bmpu" => ["bump"],
      "cent" => ["cent"], "adly" => ["lady"], "achy" => ["achy"],
      "ginw" => ["wing"], "eilv" => ["veil", "evil", "vile", "live"],
      "alop" => ["opal"], "akns" => ["sank"], "dgil" => ["gild"],
      "ceis" => ["ices"], "dilm" => ["mild"], "acln" => ["clan"],
      "gorw" => ["grow"], "adgl" => ["glad"], "glow" => ["glow"],
      "dhlo" => ["hold"], "ikln" => ["kiln", "link"],
      "aepr" => ["pare", "pear", "reap", "rape"], "bpsu" => ["pubs"],
      "gnoo" => ["goon"], "istt" => ["tits"], "ossw" => ["sows"],
      "cdik" => ["dick"], "ehop" => ["hope"], "desw" => ["weds"],
      "ddsu" => ["duds"], "eopx" => ["expo"], "eikm" => ["mike"],
      "acjk" => ["jack"], "ekpt" => ["kept"], "bcmo" => ["comb"],
      "agkw" => ["gawk"], "aeln" => ["lane", "lean"], "dort" => ["trod"],
      "most" => ["most"], "filp" => ["flip"], "rstu" => ["rust", "ruts"],
      "ikny" => ["inky"], "cdku" => ["duck"], "adem" => ["dame", "made"],
      "alnp" => ["plan"], "ahnt" => ["than"], "clot" => ["clot", "colt"],
      "gnsu" => ["gnus", "snug", "guns", "sung"], "aost" => ["oats"],
      "cdeu" => ["cued"], "eflx" => ["flex"], "deow" => ["owed"],
      "isst" => ["sits"], "deiv" => ["vied", "dive"], "ajzz" => ["jazz"],
      "ders" => ["reds"], "opty" => ["typo"], "ehsw" => ["hews"],
      "ikst" => ["skit", "kits"], "beoo" => ["oboe"], "aegl" => ["gale"],
      "ehss" => ["shes"], "eopr" => ["pore", "rope"], "adex" => ["axed"],
      "brru" => ["burr"], "fmor" => ["form", "from"], "cdos" => ["cods"],
      "enps" => ["pens"], "gpsy" => ["gyps"], "fttu" => ["tuft"],
      "ddey" => ["dyed", "eddy"], "hoot" => ["hoot"], "efor" => ["fore"],
      "ackr" => ["rack"], "abns" => ["nabs", "bans"], "eort" => ["rote", "tore"],
      "deew" => ["weed"], "abss" => ["bass"], "hksu" => ["husk"],
      "adiv" => ["avid"], "eity" => ["yeti"], "inty" => ["tiny"],
      "eopt" => ["poet"], "almu" => ["maul"], "ckoo" => ["cook"],
      "bell" => ["bell"], "abby" => ["baby"], "aelr" => ["earl", "real"],
      "deir" => ["dire", "ride"], "acgr" => ["crag"], "prsy" => ["spry"],
      "entv" => ["vent"], "morw" => ["worm"], "cist" => ["tics"],
      "enru" => ["rune"], "himw" => ["whim"], "dens" => ["dens", "ends", "send"],
      "ahrt" => ["hart"], "deru" => ["rued", "rude"], "acdi" => ["acid"],
      "eekl" => ["keel", "leek"], "emsu" => ["muse"], "ansv" => ["vans"],
      "prru" => ["purr"], "ehos" => ["hoes", "hose", "shoe"],
      "enst" => ["nest", "nets", "tens", "sent"], "ellt" => ["tell"],
      "emss" => ["mess"], "aors" => ["oars", "soar"], "ersv" => ["revs"],
      "fino" => ["info"], "ehnt" => ["then"], "adim" => ["amid", "maid"],
      "optu" => ["pout"], "aotu" => ["auto"], "afgs" => ["fags"],
      "eefs" => ["fees"], "nssu" => ["suns"], "adef" => ["fade", "deaf"],
      "hrsu" => ["rush"], "hoos" => ["shoo"], "dipr" => ["drip"],
      "alno" => ["loan"], "cost" => ["cots", "cost"], "actt" => ["tact"],
      "klsu" => ["sulk"], "ejtu" => ["jute"], "ceho" => ["echo"],
      "hswy" => ["whys"], "boos" => ["boos"], "dlos" => ["sold"],
      "estv" => ["vest", "vets"], "bins" => ["bins"], "eggs" => ["eggs"],
      "fopr" => ["prof"], "deoz" => ["doze"], "abhs" => ["bash"],
      "nopy" => ["pony"], "flow" => ["fowl", "wolf", "flow"], "bcru" => ["curb"],
      "ckpu" => ["puck"], "ackt" => ["tack"], "elst" => ["lest", "lets"],
      "lppu" => ["pulp"], "afrt" => ["fart", "frat", "raft"], "acps" => ["caps"],
      "dopr" => ["prod", "drop"], "filt" => ["flit", "lift"], "anry" => ["yarn"],
      "adhn" => ["hand"], "iprt" => ["trip"], "dirs" => ["rids"],
      "beoy" => ["obey"], "blot" => ["blot", "bolt"], "bruy" => ["ruby", "bury"],
      "enrw" => ["wren"], "eksw" => ["skew"], "ampu" => ["puma"],
      "abfr" => ["barf"], "eglo" => ["ogle"], "dflo" => ["fold"],
      "ador" => ["road"], "aemz" => ["maze"], "oprt" => ["port"],
      "abry" => ["bray"], "artw" => ["wart"], "anpw" => ["pawn"],
      "ceim" => ["mice"], "ginr" => ["grin", "ring"], "eivw" => ["wive", "view"],
      "ckos" => ["sock"], "cdee" => ["cede"], "jlow" => ["jowl"],
      "cfku" => ["fuck"], "agsw" => ["wags"], "emsw" => ["mews"],
      "ottu" => ["tout"], "aair" => ["aria"], "asss" => ["sass"],
      "absy" => ["bays"], "adlu" => ["laud", "dual"], "ddos" => ["odds"],
      "abjs" => ["jabs"], "cikw" => ["wick"], "cinz" => ["zinc"],
      "acef" => ["face"], "abgn" => ["bang"], "ekop" => ["poke"],
      "cchi" => ["chic"], "bdir" => ["bird"], "fknu" => ["funk"],
      "amsw" => ["swam"], "oott" => ["toot"], "ffhu" => ["huff"],
      "ainv" => ["vain"], "ceko" => ["coke"], "ahmt" => ["math"],
      "airy" => ["airy"], "hitw" => ["with"], "assw" => ["saws"],
      "abll" => ["ball"], "illt" => ["lilt", "till"], "doss" => ["sods"],
      "estt" => ["test"], "akny" => ["yank"], "acfl" => ["calf"],
      "bgru" => ["grub"], "lstu" => ["slut", "lust"], "dors" => ["rods"],
      "ilno" => ["loin", "lion"], "deny" => ["deny"], "ailt" => ["tail"],
      "foru" => ["four"], "ffiy" => ["iffy"], "deps" => ["sped"],
      "nnsu" => ["nuns"], "gmsu" => ["gums", "mugs", "smug"], "ailm" => ["mail"],
      "oosz" => ["zoos"], "ells" => ["sell"], "fotu" => ["tofu"],
      "ellw" => ["well"], "aess" => ["seas"], "ggno" => ["gong"],
      "abcr" => ["crab"], "eprs" => ["reps"], "efrt" => ["fret"],
      "aclp" => ["clap"], "buzz" => ["buzz"], "adei" => ["aide", "idea"],
      "aesx" => ["axes"], "gltu" => ["glut"], "eknu" => ["nuke"],
      "adlr" => ["lard"], "agit" => ["gait"], "dins" => ["dins"],
      "eess" => ["sees"], "eepp" => ["peep"], "apsy" => ["spay", "yaps", "pays"],
      "abor" => ["boar"], "adir" => ["arid", "raid"], "dmoo" => ["doom", "mood"],
      "crux" => ["crux"], "bfis" => ["fibs"], "aefz" => ["faze"],
      "abnr" => ["barn", "bran"], "aenw" => ["anew", "wane", "wean"],
      "aeks" => ["sake"], "moss" => ["moss"], "epru" => ["pure"],
      "aghn" => ["hang"], "oost" => ["soot"], "einn" => ["nine"],
      "anwy" => ["yawn"], "agnr" => ["rang"], "gins" => ["gins", "sing", "sign"],
      "moot" => ["moot"], "apss" => ["saps", "spas", "pass"],
      "abgs" => ["gabs", "bags"], "bors" => ["robs"], "akrs" => ["arks"],
      "foow" => ["woof"], "eimr" => ["emir", "mire"], "ffmu" => ["muff"],
      "kmsu" => ["musk"], "jknu" => ["junk"], "losu" => ["soul"],
      "aknr" => ["nark", "rank"], "eknw" => ["knew"], "iknp" => ["pink"],
      "aceh" => ["ache", "each"], "lotv" => ["volt"], "imrt" => ["trim"],
      "aafr" => ["afar"], "akms" => ["mask"], "eipr" => ["pier", "ripe"],
      "ehir" => ["heir", "hire"], "inru" => ["ruin"], "defs" => ["feds"],
      "orst" => ["rots", "sort"], "borw" => ["brow"], "dlor" => ["lord"],
      "gnru" => ["rung"], "einr" => ["rein"], "eehl" => ["heel"],
      "foxy" => ["foxy"], "demo" => ["demo", "dome", "mode"], "fgoo" => ["goof"],
      "ersu" => ["rues", "ruse", "sure", "user"], "bees" => ["bees"],
      "eesw" => ["ewes", "wees"], "ahil" => ["hail"], "adej" => ["jade"],
      "hint" => ["hint", "thin"], "bmow" => ["womb"], "aber" => ["bare", "bear"],
      "cekn" => ["neck"], "gikn" => ["king"], "acpt" => ["pact"],
      "cerw" => ["crew"], "cdor" => ["cord"], "detu" => ["duet"],
      "chip" => ["chip"], "eimm" => ["mime"], "aklt" => ["talk"],
      "bosw" => ["bows"], "abls" => ["slab", "labs"], "arvy" => ["vary"],
      "ipsz" => ["zips"], "fhis" => ["fish"], "hotu" => ["thou"],
      "hops" => ["posh", "hops", "shop"], "dgos" => ["dogs", "gods"],
      "bnsu" => ["buns", "snub"], "enrt" => ["rent"], "aaln" => ["anal"],
      "almt" => ["malt"], "fkor" => ["fork"], "aegt" => ["gate"],
      "dehl" => ["held"], "aimm" => ["maim"], "fklo" => ["folk"],
      "deek" => ["eked"], "iloy" => ["oily"], "dilo" => ["idol"],
      "cino" => ["coin", "icon"], "amno" => ["moan"], "entw" => ["newt", "went"],
      "loow" => ["wool"], "cesu" => ["cues"], "ceno" => ["cone", "once"],
      "glmu" => ["glum"], "aelv" => ["veal"], "eehr" => ["here"],
      "dils" => ["lids", "slid"], "dglo" => ["gold"], "abbe" => ["babe"],
      "adrw" => ["ward", "draw"]}
    |> Map.get(string_id)
  end
end
