defmodule Jumble.ScowlDict.Size55.Length4.Dict do
  def get do
    %{"cder" => ["cred"], "grsu" => ["rugs"], "ekow" => ["woke"],
      "hstu" => ["tush", "huts", "shut", "thus"], "eilw" => ["wile"],
      "adgn" => ["dang"], "eilm" => ["lime", "mile"], "ilmy" => ["limy"],
      "hloy" => ["holy"], "afos" => ["oafs", "sofa"], "akln" => ["lank"],
      "aefv" => ["fave"], "gimr" => ["grim"], "bbes" => ["ebbs"],
      "intw" => ["twin"], "adkn" => ["dank"], "gnos" => ["snog", "song"],
      "eflo" => ["floe"], "adip" => ["paid"], "ilnt" => ["lint"],
      "aetz" => ["zeta"], "imps" => ["imps"], "dhow" => ["dhow"],
      "dhtu" => ["thud"], "deho" => ["hoed"], "dehs" => ["shed"],
      "blos" => ["lobs", "slob"], "aegv" => ["gave"], "flux" => ["flux"],
      "agms" => ["mags"], "aees" => ["ease"], "irwy" => ["wiry"],
      "besw" => ["webs"], "iquz" => ["quiz"], "ilmp" => ["limp"],
      "ksuy" => ["yuks"], "desz" => ["zeds"], "blow" => ["bowl", "blow"],
      "aept" => ["pate", "peat", "tape"], "ceht" => ["etch"],
      "gstu" => ["gust", "tugs", "guts"], "cefl" => ["clef"],
      "eilt" => ["lite", "tile"], "apps" => ["apps", "paps"], "ahow" => ["whoa"],
      "best" => ["best", "bets"], "aesy" => ["yeas", "ayes", "easy"],
      "krsu" => ["rusk"], "bill" => ["bill"], "afir" => ["fair"],
      "lnxy" => ["lynx"], "aeht" => ["hate", "heat"], "girs" => ["rigs"],
      "ekls" => ["elks"], "achp" => ["chap"], "eikt" => ["kite"],
      "kosw" => ["woks"], "agnp" => ["pang"], "elos" => ["sloe", "sole", "lose"],
      "eert" => ["tree"], "aikn" => ["akin"], "diks" => ["skid", "kids", "disk"],
      "ceir" => ["rice"], "gosw" => ["wogs"], "anst" => ["ants", "tans"],
      "emos" => ["emos", "some"], "emow" => ["meow"], "agot" => ["toga", "goat"],
      "aggo" => ["agog"], "ceor" => ["core"], "ahst" => ["hast", "shat", "hats"],
      "clop" => ["clop"], "cikp" => ["pick"], "iqtu" => ["quit"],
      "bmsu" => ["bums"], "egst" => ["gets"], "iklo" => ["kilo"],
      "amsy" => ["yams"], "begi" => ["gibe"], "aelt" => ["teal", "tale", "late"],
      "amps" => ["spam", "amps", "maps"], "antw" => ["want"], "aitx" => ["taxi"],
      "impw" => ["wimp"], "eils" => ["leis", "isle", "lies"], "ehlp" => ["help"],
      "deln" => ["lend"], "noxy" => ["onyx"], "acio" => ["ciao"],
      "dims" => ["dims"], "arsw" => ["wars"], "foor" => ["roof"],
      "ilot" => ["toil"], "cepu" => ["puce"], "aemx" => ["exam"],
      "eekw" => ["week"], "adhr" => ["hard"], "amss" => ["mass"],
      "afhl" => ["half"], "adds" => ["dads", "adds"], "ehno" => ["hone"],
      "fssu" => ["fuss"], "loot" => ["loot", "tool"], "fuzz" => ["fuzz"],
      "npuy" => ["puny"], "deeg" => ["geed", "edge"], "ackp" => ["pack"],
      "ahtw" => ["thaw", "what"], "beit" => ["bite"], "oouz" => ["ouzo"],
      "ddoo" => ["dodo"], "aklr" => ["lark"], "elru" => ["lure", "rule"],
      "ikss" => ["skis", "kiss"], "clru" => ["curl"], "eoru" => ["euro"],
      "ceps" => ["pecs", "spec"], "dnos" => ["nods", "dons"], "elns" => ["lens"],
      "hosw" => ["hows", "show"], "bfos" => ["fobs"], "deem" => ["deem"],
      "arwy" => ["awry", "wary"], "beij" => ["jibe"], "eorw" => ["wore"],
      "elmw" => ["mewl"], "ansy" => ["nays"], "pttu" => ["putt"],
      "bllu" => ["bull"], "akmr" => ["mark"], "chop" => ["chop"],
      "deik" => ["dike"], "hrtu" => ["thru", "hurt"], "aapp" => ["papa"],
      "denw" => ["wend"], "aftw" => ["waft"], "fopu" => ["pouf"],
      "gnot" => ["tong"], "aprs" => ["pars", "raps", "rasp", "spar"],
      "cjko" => ["jock"], "abps" => ["baps"], "agsy" => ["gays"],
      "jlot" => ["jolt"], "dorw" => ["word"], "eims" => ["semi"],
      "agns" => ["nags", "sang", "snag"], "elpy" => ["yelp"], "hntu" => ["hunt"],
      "acev" => ["cave"], "pstu" => ["puts"], "psst" => ["psst"],
      "eipp" => ["pipe"], "delw" => ["lewd", "weld"], "noos" => ["soon"],
      "fgit" => ["gift"], "mosw" => ["mows"], "cmsu" => ["scum", "cums"],
      "aepx" => ["apex"], "desy" => ["dyes"], "alov" => ["oval"],
      "aalv" => ["lava"], "aehr" => ["rhea", "hare", "hear"], "bdei" => ["bide"],
      "cdeo" => ["coed", "code"], "loos" => ["loos", "solo"],
      "adry" => ["dray", "yard"], "diov" => ["void"], "ills" => ["ills", "sill"],
      "akos" => ["oaks", "soak"], "acsv" => ["vacs"], "efrs" => ["serf", "refs"],
      "ackm" => ["mack"], "bboo" => ["boob"], "dmru" => ["drum"],
      "aint" => ["anti"], "adep" => ["aped"], "belo" => ["bole", "lobe"],
      "deis" => ["ides", "dies", "side"], "iklm" => ["milk"],
      "delo" => ["lode", "dole"], "anss" => ["sans"], "dilw" => ["wild"],
      "imot" => ["omit"], "hist" => ["shit", "hits", "this"], "beuz" => ["zebu"],
      "nort" => ["torn"], "aeps" => ["apse", "apes", "peas"],
      "ahsy" => ["ashy", "hays"], "orsy" => ["rosy"], "awxy" => ["waxy"],
      "irst" => ["stir"], "ftuz" => ["futz"], "admn" => ["damn"],
      "cdru" => ["crud", "curd"], "mstu" => ["tums", "smut", "must"],
      "hklu" => ["hulk"], "clow" => ["cowl"], "allm" => ["mall"],
      "cdlo" => ["clod", "cold"], "anuy" => ["yuan"], "eppr" => ["prep"],
      "abds" => ["dabs"], "fnot" => ["font"], "afmo" => ["foam"],
      "ejoy" => ["joey"], "aceg" => ["cage"], "abde" => ["abed", "bade", "bead"],
      "bdsu" => ["buds", "dubs"], "entu" => ["tune"], "imnt" => ["mint"],
      "intt" => ["tint"], "elms" => ["elms"], "biot" => ["obit"],
      "acht" => ["chat"], "bety" => ["byte"], "ablo" => ["bola"],
      "aegs" => ["sage", "ages"], "gilt" => ["gilt"], "doru" => ["dour"],
      "ilps" => ["lips", "lisp", "slip"], "eopp" => ["pope"],
      "know" => ["wonk", "know"], "fglu" => ["gulf"], "ahht" => ["hath"],
      "essu" => ["sues", "uses"], "amms" => ["mams"], "elry" => ["lyre", "rely"],
      "gijs" => ["jigs"], "dknu" => ["dunk"], "adow" => ["woad"],
      "emop" => ["mope", "poem"], "aknt" => ["tank"], "blru" => ["blur"],
      "agny" => ["yang"], "istz" => ["zits"], "lluu" => ["lulu"],
      "bgno" => ["bong"], "aelm" => ["lame", "male", "meal"], "ehmt" => ["them"],
      "ginp" => ["ping"], "egnt" => ["gent"], "aeev" => ["eave"],
      "enpt" => ["pent"], "hmow" => ["whom"], "mouv" => ["ovum"],
      "dikr" => ["dirk"], "lmsu" => ["slum"], "dlou" => ["ludo", "loud"],
      "eirs" => ["sire", "rise"], "afiw" => ["waif"],
      "ilos" => ["oils", "silo", "soil"], "eegs" => ["gees"],
      "losw" => ["lows", "owls", "slow"], "aesw" => ["awes"], "ejko" => ["joke"],
      "ehmo" => ["home"], "dinr" => ["rind"], "einv" => ["vine", "vein"],
      "ailn" => ["nail", "lain"], "gotu" => ["gout"], "fort" => ["fort"],
      "eilr" => ["lire", "rile"], "cdsu" => ["cuds", "scud"], "eorz" => ["zero"],
      "mnor" => ["morn", "norm"], "afgn" => ["fang"], "cksu" => ["suck"],
      "behr" => ["herb"], "gips" => ["pigs"], "ahss" => ["sash"],
      "ciru" => ["uric"], "knoo" => ["nook"], "aegw" => ["wage"],
      "ipst" => ["pits", "spit", "tips"], "ainr" => ["rani", "rain"],
      "assy" => ["says"], "abin" => ["bani"], "illp" => ["pill"],
      "aopt" => ["atop"], "fruy" => ["fury"], "aegz" => ["gaze"],
      "adis" => ["dais", "aids", "said"], "aclo" => ["cola", "coal"],
      "cops" => ["cops"], "delv" => ["veld"], "emmo" => ["memo"],
      "ackw" => ["wack"], "acst" => ["scat", "cast", "cats", "acts"],
      "hipt" => ["pith"], "eooz" => ["ooze"], "afnw" => ["fawn"],
      "arty" => ["arty", "tray"], "imsw" => ["swim"], "adqu" => ["quad"],
      "estz" => ["zest"], "agin" => ["gain"], "aefl" => ["flea", "leaf"],
      "efls" => ["self"], "opss" => ["sops"], "lowy" => ["yowl"],
      "amot" => ["moat", "atom"], "cdtu" => ["duct"], "cikk" => ["kick"],
      "adrt" => ["drat", "trad", "dart"], "bclo" => ["bloc"], "lnoy" => ["only"],
      "knsu" => ["sunk"], "eilu" => ["lieu"], "ttuu" => ["tutu"],
      "defl" => ["fled"], "koor" => ["rook"], "bglo" => ["glob", "blog"],
      "mmos" => ["moms"], "anyz" => ["zany"], "aksu" => ["skua", "auks"],
      "flou" => ["foul"], "bgos" => ["gobs", "bogs"],
      "lops" => ["pols", "lops", "slop"], "aehv" => ["have"], "deop" => ["dope"],
      "osst" => ["sots", "toss"], "mosu" => ["sumo"], "bkoo" => ["book"],
      "belu" => ["lube", "blue"], "aerr" => ["rear", "rare"], "kosu" => ["souk"],
      "cips" => ["pics", "spic"], "inow" => ["wino"], "dlop" => ["plod"],
      "acdr" => ["card"], "aemr" => ["mare", "ream"], "cltu" => ["cult"],
      "acrt" => ["cart"], "djou" => ["judo"], "mrsu" => ["rums"],
      "efst" => ["fest"], "efiw" => ["wife"], "avwy" => ["wavy"],
      "astv" => ["vats", "vast"], "eikp" => ["pike"], "abfl" => ["flab"],
      "bhot" => ["both"], "ahjj" => ["hajj"], "cehk" => ["heck"],
      "ilms" => ["mils", "slim"], "bemr" => ["berm"],
      "acer" => ["acre", "care", "race"], "dfnu" => ["fund"],
      "desu" => ["dues", "sued", "used"], "alor" => ["oral"],
      "ader" => ["dare", "dear", "read"], "iort" => ["trio", "riot"],
      "inqu" => ["quin"], "aagg" => ["gaga"], "agst" => ["stag", "tags"],
      "aehk" => ["hake"], "bdes" => ["debs", "beds"], "depu" => ["dupe"],
      "oppr" => ["prop"], "agoy" => ["yoga"], "foot" => ["foot"],
      "denv" => ["vend"], "eory" => ["yore"], "admp" => ["damp"],
      "adst" => ["tads"], "aegr" => ["gear", "rage"], "lopt" => ["plot"],
      "dels" => ["sled"], "adlo" => ["load"], "egls" => ["gels", "legs"],
      "aorr" => ["roar"], "aaqu" => ["aqua"], "eejr" => ["jeer"],
      "gjsu" => ["jugs"], "hlsu" => ["lush"], "dily" => ["idly"],
      "adot" => ["toad"], "ckru" => ["ruck"], "ahkr" => ["hark"],
      "mpsu" => ["sump", "umps"], "bblu" => ["bulb"], "alow" => ["awol"],
      "amoy" => ["mayo"], "boor" => ["boor"], "cghu" => ["chug"],
      "bdis" => ["bids"], "ahoy" => ["ahoy"], "cims" => ["mics"],
      "dehr" => ["herd"], "mnoo" => ["mono", "moon"], "absw" => ["swab"],
      "aehp" => ["heap"], "bhoo" => ["hobo"], "apry" => ["pray"],
      "alpy" => ["play"], "ostw" => ["swot", "stow", "tows", "twos"],
      "acel" => ["lace"], "hisw" => ["wish"], "ahrs" => ["rash"],
      "elmo" => ["mole"], "hlos" => ["hols"], "aflo" => ["foal", "loaf"],
      "enox" => ["oxen"], "cehw" => ["chew"], "ooyz" => ["oozy"],
      "adps" => ["pads"], "begs" => ["begs"], "dgnu" => ["dung"],
      "amst" => ["tams", "mast", "mats"], "dluy" => ["duly"], "allt" => ["tall"],
      "gitw" => ["twig"], "aims" => ["aims"], "chko" => ["hock"],
      "aett" => ["teat"], "abim" => ["iamb"], "afmr" => ["farm"],
      "ainp" => ["pain"], "jmpu" => ["jump"], "estw" => ["stew", "wets", "west"],
      "dnop" => ["pond"], "cikl" => ["lick"], "abes" => ["base"],
      "beik" => ["bike"], "asty" => ["stay"], "eovw" => ["wove"],
      "kmno" => ["monk"], "anvy" => ["navy"], "egns" => ["gens"],
      "bent" => ["bent"], "adns" => ["sand"], "hnsu" => ["shun"],
      "aben" => ["bane", "bean"], "belt" => ["belt"], "hoop" => ["pooh", "hoop"],
      "clos" => ["cols"], "brsu" => ["burs", "rubs"], "dgru" => ["drug"],
      "ekrt" => ["trek"], "degy" => ["edgy"], "artt" => ["tart"],
      "bjos" => ["jobs"], "amny" => ["myna", "many"], "bclu" => ["club"],
      "ampt" => ["tamp"], "deer" => ["deer", "reed"], "epry" => ["prey", "pyre"],
      "ghhi" => ["high"], "ablm" => ["balm", "lamb"], "deet" => ["teed"],
      "ciss" => ["sics"], "egru" => ["urge"], "chir" => ["rich"],
      "entt" => ["tent"], "adet" => ["date"], "elpt" => ["pelt"],
      "jost" => ["jots"], "inot" => ["into"], "aert" => ["tare", "tear", "rate"],
      "girt" => ["girt", "trig", "grit"], "ehty" => ["they"],
      "cein" => ["cine", "nice"], "ahpr" => ["harp"], "beer" => ["beer"],
      "eekp" => ["peke", "peek", "keep"], "gisw" => ["swig", "wigs"],
      "efos" => ["foes"], "opsy" => ["posy"], "ppsu" => ["pups"],
      "illm" => ["mill"], "apsz" => ["zaps"], "abot" => ["boat"],
      "abbr" => ["barb"], "bceu" => ["cube"], "aagr" => ["agar", "raga"],
      "cgos" => ["cogs"], "dees" => ["seed"], "npsw" => ["pwns"],
      "dhos" => ["dosh", "hods", "shod"], "hhsu" => ["hush"], "cllu" => ["cull"],
      "deov" => ["dove"], "josy" => ["joys"], "aggs" => ["gags"],
      "emrt" => ["term"], "cpsu" => ["cusp", "cups"], "aflt" => ["flat"],
      "aesv" => ["vase", "save"], "been" => ["been"], "dimn" => ["mind"],
      "aagl" => ["alga", "gala"], "adhs" => ["shad", "dash"], "hins" => ["shin"],
      "hkoo" => ["hook"], "hmot" => ["moth"], "cell" => ["cell"],
      "aeft" => ["feta", "feat", "fate"], "hmos" => ["mosh", "ohms"],
      "abem" => ["beam"], "frtu" => ["turf"], "loop" => ["polo", "loop", "pool"],
      "eemr" => ["mere"], "acip" => ["pica"],
      "anps" => ["naps", "pans", "snap", "span"], "eost" => ["toes"],
      "adsy" => ["days"], "ekoy" => ["yoke"], "ghis" => ["sigh"],
      "istw" => ["wist", "wits"], "aclt" => ["talc"], "iknw" => ["wink"],
      "delm" => ["meld"], "abdu" => ["daub", "baud"], "cetu" => ["cute"],
      "bcir" => ["crib"], "aluu" => ["luau"], "nost" => ["snot", "tons"],
      "bdoy" => ["body"], "bfmu" => ["bumf"], "inov" => ["vino"],
      "ehpw" => ["phew"], "efnr" => ["fern"], "sttu" => ["tuts"],
      "glpu" => ["gulp", "plug"], "eilp" => ["pile"], "acpr" => ["carp", "crap"],
      "beil" => ["bile"], "ckuy" => ["yuck"], "ikmn" => ["mink"],
      "delu" => ["duel"], "ghnu" => ["hung"], "dhot" => ["doth"],
      "knpu" => ["punk"], "dlmo" => ["mold"], "drsy" => ["drys"],
      "agps" => ["gaps", "gasp"], "diqu" => ["quid"], "afly" => ["flay"],
      "bikl" => ["bilk"], "deos" => ["odes", "dose", "does"], "eluy" => ["yule"],
      "dllu" => ["dull"], "agmy" => ["gamy"], "mpru" => ["rump"],
      "errs" => ["errs"], "acds" => ["cads", "scad"],
      "aels" => ["leas", "ales", "seal", "sale"], "oprs" => ["pros"],
      "opsu" => ["opus", "soup"], "film" => ["milf", "film"], "cior" => ["coir"],
      "bmnu" => ["numb"], "einz" => ["zine"], "ggor" => ["grog"],
      "enno" => ["neon", "none"], "deku" => ["duke"], "gost" => ["togs"],
      "nosw" => ["sown", "owns", "snow"], "apsw" => ["paws", "wasp", "swap"],
      "alos" => ["also"], "cekp" => ["peck"], "ejkr" => ["jerk"],
      "cikm" => ["mick"], "flot" => ["loft"], "adft" => ["daft"],
      "nnoo" => ["noon"], "acrs" => ["arcs", "scar", "cars"], "dssu" => ["suds"],
      "alst" => ["lats", "slat", "salt", "last"], "adez" => ["adze", "daze"],
      "ckop" => ["pock"], "bttu" => ["butt"], "aipt" => ["pita"],
      "enov" => ["oven"], "emno" => ["omen"], "llop" => ["poll"],
      "eflw" => ["flew"], "eelp" => ["peel"], "bdeo" => ["bode"],
      "agjs" => ["jags"], "gioy" => ["yogi"], "anox" => ["axon"],
      "bdet" => ["debt"], "imss" => ["isms", "sims", "miss"],
      "efir" => ["rife", "fire"], "ikll" => ["kill"], "lllu" => ["lull"],
      "eemm" => ["meme"], "hips" => ["hips", "ship"], "bgsu" => ["bugs"],
      "acim" => ["mica"], "ajsw" => ["jaws"], "ailv" => ["vial"],
      "adgo" => ["dago", "goad"], "aelz" => ["laze", "zeal"],
      "eekn" => ["knee", "keen"], "aekw" => ["wake", "weak"], "hilt" => ["hilt"],
      "aekl" => ["kale", "lake", "leak"], "ahkn" => ["ankh", "hank", "khan"],
      "ahlu" => ["hula", "haul"], "deno" => ["node", "done"], "ansu" => ["anus"],
      "bimr" => ["brim"], "afry" => ["fray"], "ejst" => ["jets", "jest"],
      "bmoo" => ["boom"], "acft" => ["fact"], "alwy" => ["yawl"],
      "eikk" => ["kike"], "ddei" => ["died"], "aehz" => ["haze"],
      "acek" => ["cake"], "inpy" => ["piny"], "hnor" => ["horn"],
      "mmsu" => ["mums"], "aamm" => ["mama"], "agss" => ["sags"],
      "bklu" => ["bulk"], "nopr" => ["porn"], "kopy" => ["poky"],
      "eepv" => ["veep"], "alsv" => ["lavs"], "ceop" => ["cope"],
      "biis" => ["ibis"], "ahpt" => ["path"], "dirt" => ["dirt"],
      "beef" => ["beef"], "anov" => ["nova"], "llpu" => ["pull"],
      "eghu" => ["huge"], "afil" => ["fail"], "dlot" => ["dolt", "told"],
      "bder" => ["bred"], "abcs" => ["cabs", "scab"], "abel" => ["bale", "able"],
      "aghs" => ["shag", "gash", "hags"], "lpsu" => ["plus"], "betu" => ["tube"],
      "jstu" => ["juts", "just"], "bnor" => ["born"], "chik" => ["hick"],
      "osvw" => ["vows"], "bdmu" => ["dumb"], "aehy" => ["yeah"],
      "alot" => ["alto"], "abdn" => ["band"], "frsu" => ["furs", "surf"],
      "aekm" => ["make"], "ikps" => ["kips", "skip"], "eeks" => ["ekes", "seek"],
      "ostu" => ["oust", "outs"], "dest" => ["teds"],
      "egor" => ["goer", "gore", "ogre", "ergo"], "anno" => ["anon"],
      "eorv" => ["rove", "over"], "deey" => ["eyed"], "ahmr" => ["harm"],
      "afnu" => ["faun"], "iknt" => ["knit"], "ehlo" => ["hole"],
      "ikkn" => ["kink"], "notw" => ["nowt", "wont", "town"], "ertu" => ["true"],
      "iopt" => ["topi"], "abst" => ["bast", "bats", "stab", "tabs"],
      "astt" => ["tats"], "dhis" => ["dish"], "ffit" => ["tiff"],
      "sssu" => ["suss"], "belw" => ["blew"], "adln" => ["land"],
      "acde" => ["aced"], "ally" => ["ally"], "bilm" => ["limb"],
      "bcek" => ["beck"], "bops" => ["bops"], "gsuy" => ["guys"],
      "abkn" => ["bank"], "lrsu" => ["slur"], "eflt" => ["felt", "left"],
      "flop" => ["flop"], "oruy" => ["your"], "mooz" => ["zoom"],
      "eimt" => ["mite", "emit", "item", "time"], "ffos" => ["offs"],
      "eels" => ["lees", "eels", "else"], "nrtu" => ["runt", "turn"],
      "prsu" => ["spur"], "intu" => ["unit"], "oort" => ["root"],
      "belp" => ["pleb"], "llmo" => ["moll"], "glsu" => ["lugs", "slug"],
      "dnow" => ["down"], "dfor" => ["ford"], "npsu" => ["spun", "puns"],
      "ehiv" => ["hive"], "almo" => ["loam"], "fizz" => ["fizz"],
      "agnt" => ["gnat", "tang"], "anor" => ["roan"], "ortu" => ["rout", "tour"],
      "coop" => ["coop"], "afst" => ["fats", "fast"], "dity" => ["tidy"],
      "aest" => ["sate", "teas", "seat", "east", "eats"], "afkl" => ["flak"],
      "ehpy" => ["hype"], "cdek" => ["deck"], "beno" => ["bone"],
      "acry" => ["racy"], "eswy" => ["yews"], "dstu" => ["stud", "dust"],
      "ehsu" => ["hues"], "ostt" => ["tots"], "aijl" => ["jail"],
      "hikt" => ["kith"], "acks" => ["cask", "sack"], "emov" => ["move"],
      "gist" => ["gits", "gist"], "ikno" => ["oink"], "mppu" => ["pump"],
      "berv" => ["verb"], "derw" => ["drew"], "hmty" => ["myth"],
      "elmu" => ["mule"], "ffru" => ["ruff"], "eeps" => ["pees", "seep"],
      "celw" => ["clew"], "cssu" => ["cuss"], "illr" => ["rill"],
      "eenv" => ["even"], "cloy" => ["cloy"], "ikns" => ["inks", "sink", "skin"],
      "ajms" => ["jams"], "amor" => ["roam"], "hjos" => ["josh"],
      "ajsy" => ["jays"], "msuw" => ["swum"], "aksy" => ["yaks"],
      "irtw" => ["writ"], "aces" => ["aces", "case"], "bilo" => ["boil"],
      "ijkn" => ["jink"], "afln" => ["flan"], "agls" => ["gals", "lags", "slag"],
      "ceiv" => ["vice"], "bgir" => ["brig"], "kstu" => ["tusk"],
      "elnt" => ["lent"], "ahkw" => ["hawk"], "chmu" => ["chum", "much"],
      "eins" => ["sine"], "cnor" => ["corn"], "deef" => ["feed"],
      "aipr" => ["pair"], "eesy" => ["eyes"], "bbis" => ["bibs"],
      "ahtt" => ["that"], "elor" => ["lore", "role"], "aefr" => ["fare", "fear"],
      "eirw" => ["weir", "wire"], "ensy" => ["yens"],
      "nstu" => ["tuns", "nuts", "stun"], "bosy" => ["yobs", "boys"],
      "aefs" => ["safe"], "bden" => ["bend"], "beep" => ["beep"],
      "deks" => ["desk"], "deep" => ["peed", "deep"], "agmr" => ["gram"],
      "fgis" => ["figs"], "bffi" => ["biff"], "ehll" => ["hell"],
      "adgr" => ["grad", "drag"], "envy" => ["envy"], "ccho" => ["choc"],
      "acem" => ["acme", "mace", "came"], "elop" => ["lope", "pole"],
      "abet" => ["bate", "abet", "beat", "beta"], "nrsu" => ["urns", "runs"],
      "bouy" => ["buoy"], "allp" => ["pall"], "antu" => ["tuna", "aunt"],
      "acox" => ["coax"], "bnoy" => ["bony"], "dfoo" => ["food"],
      "aent" => ["ante", "neat"], "aclw" => ["claw"], "ccko" => ["cock"],
      "beru" => ["rube"], "eotv" => ["veto", "vote"], "afgl" => ["flag"],
      "aimr" => ["amir"], "beix" => ["ibex"], "lost" => ["slot", "lost", "lots"],
      "eens" => ["seen"], "enot" => ["tone", "note"],
      "ahms" => ["hams", "mash", "sham"], "ijno" => ["join"], "abit" => ["bait"],
      "aals" => ["alas"], "admr" => ["dram"], "eott" => ["tote"],
      "door" => ["rood", "odor", "door"], "hiss" => ["hiss"], "ceov" => ["cove"],
      "ceot" => ["cote"], "abil" => ["bail"], "alms" => ["lams", "alms", "slam"],
      "dhoo" => ["hood"], "emor" => ["more"], "bhsu" => ["hubs", "bush"],
      "ablw" => ["bawl"], "gmsy" => ["gyms"], "mttu" => ["mutt"],
      "bflu" => ["flub"], "aklw" => ["walk"], "bblo" => ["blob"],
      "illw" => ["will"], "inpt" => ["pint"], "eltu" => ["lute"],
      "eerw" => ["ewer", "weer", "were"], "hmny" => ["hymn"], "ahls" => ["lash"],
      "ekpu" => ["puke"], "ails" => ["ails", "sail"], "acrz" => ["czar"],
      "aemt" => ["mate", "meat", "tame", "team"], "inor" => ["iron"],
      "fost" => ["soft"], "ahiy" => ["hiya"], "cehl" => ["lech"],
      "aelx" => ["axle"], "aegp" => ["gape", "page"], "aehl" => ["hale", "heal"],
      "adiw" => ["wadi"], "arst" => ["tars", "arts", "rats", "star"],
      "amrw" => ["warm"], "bssu" => ["subs", "buss"], "cktu" => ["tuck"],
      "egps" => ["pegs"], "hipw" => ["whip"], "dery" => ["dyer"],
      "bdlo" => ["bold"], "boot" => ["boot"], "acsw" => ["caws"],
      "eejp" => ["jeep"], "alsw" => ["awls", "slaw", "laws"], "dikn" => ["kind"],
      "aimn" => ["main"], "abjm" => ["jamb"], "aerv" => ["aver", "rave"],
      "aovw" => ["avow"], "eptw" => ["wept"], "aden" => ["dean"],
      "cstu" => ["cuts"], "deft" => ["deft"], "ampv" => ["vamp"],
      "aiot" => ["iota"], "acms" => ["macs", "cams", "scam"], "aops" => ["soap"],
      "acot" => ["taco", "coat"], "dill" => ["dill"], "fglo" => ["flog", "golf"],
      "bnoo" => ["boon"], "ilwy" => ["wily"], "abht" => ["bath"],
      "elly" => ["yell"], "ipsy" => ["yips"], "cosw" => ["scow", "cows"],
      "ikms" => ["skim"], "elss" => ["less"], "beiv" => ["vibe"],
      "cdei" => ["iced", "dice"], "gknu" => ["gunk"], "lnor" => ["lorn"],
      "defu" => ["feud"], "firs" => ["firs"], "adeg" => ["aged"],
      "orux" => ["roux"], "eisw" => ["wise"], "copy" => ["copy"],
      "ciks" => ["sick"], "noot" => ["onto"], "eiln" => ["lien", "line"],
      "aenp" => ["nape", "pane"], "addo" => ["dado"], "hnos" => ["nosh"],
      "efns" => ["fens"], "fgir" => ["frig"], "emtu" => ["mute"],
      "itzz" => ["tizz"], "fins" => ["fins"], "disy" => ["yids"],
      "doyz" => ["dozy"], "abhl" => ["blah"], "aags" => ["saga"],
      "arsy" => ["rays"], "bdno" => ["bond"], "nptu" => ["punt"],
      "inos" => ["ions"], "ffgu" => ["guff"], "ehns" => ["hens"],
      "epps" => ["peps"], "alsy" => ["slay", "lays"],
      "ailr" => ["lira", "lair", "liar", "rail"], "gilr" => ["girl"],
      "esty" => ["stye", "yest"], "dlow" => ["wold"], "dmor" => ["dorm"],
      "aenr" => ["earn", "near"], "opry" => ["ropy"], "noty" => ["tony"],
      "aegm" => ["mega", "game"], "alss" => ["lass"], "eegh" => ["ghee"],
      "dips" => ["dips"], "abgl" => ["blag"], "efil" => ["lief", "file", "life"],
      "kloo" => ["look"], "bnos" => ["nobs", "snob"], "eltw" => ["welt"],
      "emst" => ["stem"], "hopy" => ["hypo"], "deil" => ["deli", "idle", "lied"],
      "beir" => ["brie", "bier"], "aehm" => ["ahem"], "adeh" => ["head"],
      "kkoo" => ["kook"], "ghin" => ["nigh"], "aflp" => ["flap"],
      "ceex" => ["exec"], "aort" => ["rota", "taro"], "eegl" => ["glee"],
      "iikw" => ["wiki", "kiwi"], "deor" => ["doer", "redo", "rode"],
      "eekr" => ["reek"], "epsy" => ["espy", "yeps"], "egms" => ["megs", "gems"],
      "dost" => ["dost", "dots"], "lopy" => ["poly", "ploy"],
      "ahlt" => ["lath", "halt"], "essw" => ["sews"], "chit" => ["chit", "itch"],
      "ceit" => ["cite"], "enos" => ["noes", "nose", "ones"], "cikn" => ["nick"],
      "gipr" => ["prig", "grip"], "ijnx" => ["jinx"],
      "abgr" => ["brag", "garb", "grab"], "adil" => ["dial", "laid"],
      "dell" => ["dell"], "ehor" => ["hero"], "gnop" => ["pong"],
      "adnr" => ["rand", "darn"], "aegu" => ["ague"], "dory" => ["dory"],
      "ilmo" => ["limo"], "egit" => ["gite"], "affg" => ["gaff"],
      "glos" => ["slog", "logs"], "agrs" => ["rags"], "cloo" => ["loco", "cool"],
      "aelp" => ["peal", "leap", "pale", "plea"], "agll" => ["gall"],
      "cdko" => ["dock"], "dffu" => ["duff"], "eftw" => ["weft"],
      "dehu" => ["hued"], "lllo" => ["loll"], "dnsu" => ["duns"],
      "chin" => ["chin", "inch"], "imtt" => ["mitt"], "notu" => ["unto"],
      "ipqu" => ["quip"], "eefr" => ["reef", "free"], "corw" => ["crow"],
      "cefh" => ["chef"], "ipty" => ["pity"], "dtuy" => ["duty"],
      "hlow" => ["howl"], "efiv" => ["five"], "moor" => ["moor", "room"],
      "eepw" => ["weep"], "hklo" => ["kohl"], "egks" => ["kegs"],
      "iltt" => ["tilt"], "agnw" => ["gnaw"], "akpr" => ["park"],
      "aekr" => ["rake"], "bnru" => ["burn"], "esst" => ["sets"],
      "opru" => ["pour"], "abdr" => ["brad", "bard", "drab"], "inns" => ["inns"],
      "defn" => ["fend"], "oopr" => ["poor"], "elvy" => ["levy"],
      "acnt" => ["cant"], "ehmp" => ["hemp"], "irss" => ["sirs"],
      "aflw" => ["flaw"], "bcku" => ["buck"], "hims" => ["shim", "hims"],
      "ffpu" => ["puff"], "ipsw" => ["wisp"], "fist" => ["fist", "sift", "fits"],
      "aflx" => ["flax"], "ehms" => ["hems", "mesh"], "ggis" => ["gigs"],
      "ammo" => ["ammo"], "ados" => ["soda"], "aprw" => ["warp", "wrap"],
      "eerv" => ["veer", "ever"], "mops" => ["poms", "mops"], "gjos" => ["jogs"],
      "horu" => ["hour"], "aawy" => ["away"], "ckmo" => ["mock"],
      "abbl" => ["blab"], "ddee" => ["deed"], "acmr" => ["cram"],
      "aefm" => ["fame"], "floo" => ["fool"],
      "enop" => ["pone", "nope", "peon", "open"], "filo" => ["filo", "foil"],
      "ahot" => ["oath"], "aems" => ["mesa", "seam", "same"], "afns" => ["fans"],
      "hllu" => ["hull"], "acdl" => ["clad"], "efsu" => ["fuse"],
      "eitx" => ["exit"], "efmu" => ["fume"], "egiv" => ["give"],
      "ailp" => ["pail"], "egln" => ["glen"], "eesv" => ["eves"],
      "hknu" => ["hunk"], "eegn" => ["gene"], "abks" => ["bask"],
      "fhoo" => ["hoof"], "demn" => ["mend"], "opps" => ["pops"],
      "acss" => ["sacs"], "hpsu" => ["push"], "ailw" => ["wail"],
      "dein" => ["dine"], "ehtw" => ["whet"], "eisv" => ["vies", "vise"],
      "aann" => ["naan"], "fops" => ["fops"], "aclm" => ["clam", "calm"],
      "eirt" => ["rite", "tier", "tire"], "inss" => ["sins"], "aquy" => ["quay"],
      "ampr" => ["pram", "ramp"], "dfin" => ["find"], "ittw" => ["twit"],
      "korw" => ["work"], "bdos" => ["bods", "dobs"], "eegk" => ["geek"],
      "fimr" => ["firm"], "deeh" => ["heed"],
      "host" => ["hots", "tosh", "shot", "host"], "cest" => ["sect"],
      "orsu" => ["sour", "ours"], "eflu" => ["flue", "fuel"], "acdo" => ["coda"],
      "eetw" => ["twee"], "hmpu" => ["hump"], "osty" => ["toys"],
      "acnr" => ["narc"], "eklp" => ["kelp"], "aens" => ["sane"],
      "abtu" => ["abut", "tuba"], "ahsw" => ["haws", "wash"], "iklt" => ["kilt"],
      "deot" => ["dote", "toed"], "elmt" => ["melt"], "afff" => ["faff"],
      "jruy" => ["jury"], "chow" => ["chow"], "dhin" => ["hind"],
      "abrs" => ["bras", "bars"], "aswy" => ["yaws", "sway", "ways"],
      "boss" => ["sobs", "boss"], "iimn" => ["mini"], "ehik" => ["hike"],
      "akor" => ["okra"], "koot" => ["took"], "acly" => ["clay", "lacy"],
      "lnoo" => ["loon"], "entx" => ["next"], "aaru" => ["aura"],
      "ceip" => ["epic"], "abek" => ["beak", "bake"], "nnou" => ["noun"],
      "bijs" => ["jibs"], "aevw" => ["wave"], "attw" => ["twat", "watt"],
      "astw" => ["swat"], "gsuv" => ["guvs"], "cklo" => ["lock"],
      "eist" => ["site", "ties"], "gory" => ["gyro", "gory", "orgy"],
      "eors" => ["ores", "roes", "rose", "sore"], "bgil" => ["glib"],
      "bsuy" => ["busy", "buys"], "efin" => ["fine"], "gint" => ["ting"],
      "ikos" => ["oiks"], "aery" => ["year"], "bcsu" => ["cubs"],
      "hill" => ["hill"], "acmp" => ["camp"], "ckmu" => ["muck"],
      "allw" => ["wall"], "elov" => ["vole", "love"], "eops" => ["peso", "pose"],
      "eelr" => ["leer", "reel"], "eent" => ["teen"], "egrw" => ["grew"],
      "bknu" => ["bunk"], "ackl" => ["lack"], "copr" => ["crop"],
      "crsu" => ["curs"], "kopr" => ["pork"], "attu" => ["taut"],
      "bcos" => ["cobs"], "cemo" => ["come"], "bbos" => ["bobs"],
      "illy" => ["lily"], "bgnu" => ["bung"], "cffu" => ["cuff"],
      "dkor" => ["dork"], "copu" => ["coup"], "nosu" => ["nous", "onus"],
      "aejp" => ["jape"], "bstu" => ["buts", "stub", "tubs", "bust"],
      "oopp" => ["poop"], "birs" => ["ribs"], "ehlm" => ["helm"],
      "aajr" => ["raja", "ajar"], "aitw" => ["wait"], "ajrs" => ["jars"],
      "iswz" => ["swiz"], "adel" => ["dale", "lade", "deal", "lead"],
      "bllo" => ["boll"], "aerw" => ["ware", "wear"],
      "opst" => ["pots", "opts", "tops", "post", "spot", "stop"],
      "boxy" => ["boxy"], "akmo" => ["amok"], "abis" => ["bias"],
      "loru" => ["lour"], "ensw" => ["wens", "sewn", "news"], "oosw" => ["woos"],
      "llnu" => ["null"], "answ" => ["swan"], "acff" => ["caff"],
      "llor" => ["roll"], "deit" => ["tide", "diet", "edit", "tied"],
      "eimn" => ["mien", "mine"], "dksu" => ["dusk"], "ssuw" => ["wuss"],
      "amns" => ["mans"], "iirs" => ["iris"], "dent" => ["dent", "tend"],
      "iknr" => ["rink"], "gruu" => ["guru"], "cors" => ["orcs"],
      "cilo" => ["loci", "coil"], "ghsu" => ["gush", "hugs"], "ahyz" => ["hazy"],
      "dmpu" => ["dump"], "ilov" => ["viol"], "abeu" => ["beau"],
      "firt" => ["rift"], "aglm" => ["glam"], "bmot" => ["tomb"],
      "bekr" => ["berk"], "apst" => ["pats", "spat", "taps", "past"],
      "ffin" => ["niff"], "ffot" => ["toff"], "noss" => ["sons"],
      "bksu" => ["busk"], "deiw" => ["wide"], "cdis" => ["disc"],
      "ahlo" => ["halo"], "ejll" => ["jell"], "eips" => ["pies"],
      "impr" => ["prim"], "gluy" => ["ugly"], "flru" => ["furl"],
      "orsw" => ["rows"], "dgir" => ["gird", "grid"], "erst" => ["rest"],
      "lmpu" => ["plum", "lump"], "aadt" => ["data"], "osuy" => ["yous"],
      "begr" => ["berg"], "gill" => ["gill"], "ahhs" => ["shah", "hash"],
      "coos" => ["coos"], "aekt" => ["teak", "take"], "gmos" => ["smog"],
      "dehi" => ["hied", "hide"], "alnw" => ["lawn"], "hjno" => ["john"],
      "eepr" => ["peer"], "ipss" => ["piss", "sips"], "defy" => ["defy"],
      "appu" => ["pupa"], "fllu" => ["full"], "eems" => ["seem"],
      "ilst" => ["silt", "slit", "list"], "einw" => ["wine"], "cglo" => ["clog"],
      "alyz" => ["lazy"], "bffu" => ["buff"], "eglu" => ["luge", "glue"],
      "epsw" => ["pews", "spew"], "degl" => ["geld"], "bist" => ["bits"],
      "acns" => ["cans", "scan"], "ekns" => ["kens"], "amry" => ["army"],
      "acep" => ["cape", "pace"], "effi" => ["fief", "fife"],
      "acen" => ["acne", "cane"], "aaer" => ["area"], "fgor" => ["frog"],
      "aenv" => ["nave", "vane"], "afll" => ["fall"], "aabs" => ["baas"],
      "beor" => ["robe", "bore"], "dgoo" => ["good"], "eikl" => ["like"],
      "aelo" => ["aloe"], "efll" => ["fell"], "aggn" => ["gang"],
      "dops" => ["pods"], "cess" => ["secs"], "imnx" => ["minx"],
      "ceru" => ["ecru", "cure"], "ghtu" => ["thug"], "mopr" => ["prom", "romp"],
      "emnu" => ["menu"], "cilp" => ["clip"], "derv" => ["derv"],
      "anrt" => ["tarn", "rant"], "eekm" => ["meek"], "celu" => ["clue"],
      "anrw" => ["warn"], "ffir" => ["riff"], "moos" => ["moos"],
      "arzz" => ["razz"], "egos" => ["egos", "goes"], "cmor" => ["corm"],
      "kmru" => ["murk"], "abkr" => ["bark"], "egno" => ["gone"],
      "aisv" => ["visa"], "llmu" => ["mull"], "aalm" => ["lama"],
      "hlru" => ["hurl"], "aers" => ["ares", "eras", "sear", "ears"],
      "glno" => ["long"], "insw" => ["wins"], "lmoo" => ["loom"],
      "norw" => ["worn"], "pssu" => ["sups", "puss"], "ceil" => ["lice"],
      "aglo" => ["goal"], "achk" => ["hack"], "dllo" => ["doll"],
      "nopu" => ["upon"], "ahll" => ["hall"], "gkoo" => ["gook"],
      "elsu" => ["slue"], "amrs" => ["mars", "rams", "arms"],
      "alps" => ["laps", "pals", "slap"], "ehwy" => ["whey"], "fikn" => ["fink"],
      "orty" => ["troy", "tyro"], "city" => ["city"], "eksy" => ["keys"],
      "ilmn" => ["limn"], "acll" => ["call"], "eipw" => ["wipe"],
      "chou" => ["ouch"], "anpt" => ["pant"], "abdl" => ["bald"],
      "hirw" => ["whir"], "cnoy" => ["cony"], "epst" => ["pest", "pets", "step"],
      "denr" => ["nerd", "rend"], "effs" => ["effs"], "botu" => ["bout"],
      "empr" => ["perm"], "inps" => ["nips", "snip", "pins", "spin"],
      "dmos" => ["mods"], "dosu" => ["duos"], "bdin" => ["bind"],
      "adsw" => ["wads"], "ekty" => ["tyke"], "doow" => ["wood"],
      "lopp" => ["plop"], "deim" => ["idem", "dime"], "aisx" => ["axis"],
      "bilp" => ["blip"], "bery" => ["byre"], "eest" => ["tees"],
      "deen" => ["need"], "chsu" => ["such"], "imrs" => ["rims"],
      "aepv" => ["vape", "pave"], "berw" => ["brew"], "elsw" => ["slew"],
      "adfs" => ["fads"], "imst" => ["mist"], "adms" => ["dams", "mads"],
      "enoz" => ["zone"], "agpw" => ["gawp"], "drtu" => ["turd"],
      "ahir" => ["hair"], "csty" => ["cyst"], "almp" => ["palm", "lamp"],
      "mopp" => ["pomp"], "chos" => ["cosh"],
      "aprt" => ["prat", "tarp", "rapt", "part", "trap"], "ervy" => ["very"],
      "airs" => ["airs", "sari"], "cklu" => ["luck"], "gior" => ["giro"],
      "eosw" => ["woes", "owes"], "akst" => ["task"], "alnu" => ["ulna"],
      "eprt" => ["pert"], "efht" => ["heft"], "abck" => ["back"],
      "eeft" => ["feet"], "cfio" => ["coif"], "ipsv" => ["spiv"],
      "nosy" => ["nosy"], "istu" => ["suit"], "ghos" => ["gosh", "hogs"],
      "eeht" => ["thee"], "llot" => ["toll"], "akss" => ["asks"],
      "aemn" => ["amen", "mane", "mean", "name"], "fill" => ["fill"],
      "emot" => ["mote", "tome"], "dinw" => ["wind"], "gloo" => ["logo"],
      "eemt" => ["mete", "teem", "meet"], "hmsu" => ["hums", "mush"],
      "eefl" => ["flee", "feel"], "abos" => ["boas"], "ikrs" => ["irks", "risk"],
      "bmos" => ["mobs"], "dpsu" => ["puds", "spud"], "eijv" => ["jive"],
      "ahmw" => ["wham"], "psuy" => ["yups"], "cikt" => ["tick"],
      "ahox" => ["hoax"], "hkno" => ["honk"], "bdel" => ["bled"],
      "dint" => ["dint"], "kloy" => ["yolk"], "esxy" => ["sexy"],
      "ably" => ["ably"], "aefk" => ["fake"], "oops" => ["poos", "oops"],
      "dfno" => ["fond"], "knot" => ["knot"], "bkno" => ["bonk", "knob"],
      "aerz" => ["raze"], "ortt" => ["tort", "trot"], "eesx" => ["exes"],
      "dgin" => ["ding"], "epty" => ["type"], "aekp" => ["peak"],
      "booz" => ["bozo"], "osww" => ["wows"], "adkr" => ["dark"],
      "einp" => ["pine"], "glnu" => ["lung"], "fgos" => ["fogs"],
      "gllu" => ["gull"], "bbsu" => ["bubs"], "adde" => ["dead"],
      "adew" => ["awed", "wade"], "aiks" => ["saki"], "impp" => ["pimp"],
      "achs" => ["cash"], "gnow" => ["gown"], "amrt" => ["tram", "mart"],
      "ehrs" => ["hers"], "eers" => ["sere", "seer"], "eisz" => ["size"],
      "iprs" => ["rips"], "ehww" => ["whew"], "achr" => ["arch", "char"],
      "klru" => ["lurk"], "adls" => ["lads"], "bpru" => ["burp"],
      "ckor" => ["cork", "rock"], "ikls" => ["ilks", "silk"], "dnou" => ["undo"],
      "cnos" => ["cons"], "ettx" => ["text"], "acmo" => ["coma"],
      "besy" => ["byes"], "oprw" => ["prow"], "beet" => ["beet"],
      "crtu" => ["curt"], "ehnw" => ["when"], "afit" => ["fiat"],
      "ehov" => ["hove"], "ekpr" => ["perk"], "cnsy" => ["sync"],
      "ipps" => ["pips"], "egmr" => ["germ"], "loss" => ["sols", "loss"],
      "dgis" => ["digs"], "adnw" => ["wand", "dawn"], "ddeu" => ["dude"],
      "mssu" => ["muss", "sums"], "eint" => ["tine", "nite"], "ffim" => ["miff"],
      "elno" => ["noel", "lone"], "deky" => ["dyke"], "ijlt" => ["jilt"],
      "empt" => ["temp"], "iltw" => ["wilt"], "ciky" => ["icky"],
      "inst" => ["snit", "nits", "tins"], "abrt" => ["brat"], "bbmo" => ["bomb"],
      "eejz" => ["jeez"], "denu" => ["dune", "nude"], "bmpu" => ["bump"],
      "cent" => ["cent"], "adly" => ["lady"], "achy" => ["achy"],
      "ginw" => ["wing"], "acny" => ["cyan"],
      "eilv" => ["veil", "evil", "vile", "live"], "alop" => ["opal"],
      "gpsu" => ["pugs"], "akns" => ["sank"], "dgil" => ["gild"],
      "ceis" => ["ices"], "dilm" => ["mild"], "acln" => ["clan"],
      "gorw" => ["grow"], "adgl" => ["glad"], "glow" => ["glow"],
      "dhlo" => ["hold"], "ikln" => ["kiln", "link"],
      "aepr" => ["pare", "pear", "reap", "rape"], "bpsu" => ["pubs"],
      "gnoo" => ["goon"], "istt" => ["tits"], "ossw" => ["sows"],
      "cdik" => ["dick"], "ehop" => ["hope"], "desw" => ["weds"],
      "ddsu" => ["duds"], "eopx" => ["expo"], "eikm" => ["mike"],
      "acjk" => ["jack"], "ekpt" => ["kept"], "bcmo" => ["comb"],
      "agkw" => ["gawk"], "aeln" => ["lane", "lean"], "glop" => ["glop"],
      "dort" => ["trod"], "most" => ["toms", "most"], "ptuz" => ["putz"],
      "filp" => ["flip"], "rstu" => ["rust", "ruts"], "ikny" => ["inky"],
      "cdku" => ["duck"], "adem" => ["mead", "dame", "made"], "alnp" => ["plan"],
      "efss" => ["fess"], "ahnt" => ["than"], "clot" => ["clot", "colt"],
      "gnsu" => ["gnus", "snug", "guns", "sung"], "aost" => ["oats"],
      "cdeu" => ["cued"], "eflx" => ["flex"], "deow" => ["owed"],
      "isst" => ["sits"], "deiv" => ["vied", "dive"], "ajzz" => ["jazz"],
      "ders" => ["reds"], "opty" => ["typo"], "ehsw" => ["hews"],
      "bntu" => ["bunt"], "ikst" => ["skit", "kits"], "beoo" => ["oboe"],
      "aegl" => ["gale"], "ehss" => ["shes"], "eopr" => ["pore", "rope"],
      "adex" => ["axed"], "aeno" => ["aeon"], "alpw" => ["pawl"],
      "cikr" => ["rick"], "brru" => ["burr"], "fmor" => ["form", "from"],
      "hpuw" => ["whup"], "cdos" => ["docs", "cods"], "enps" => ["pens"],
      "acrw" => ["craw"], "gpsy" => ["gyps"], "fttu" => ["tuft"],
      "ddey" => ["dyed", "eddy"], "hoot" => ["hoot"], "aeru" => ["urea"],
      "efor" => ["fore"], "ghot" => ["goth"], "ackr" => ["rack"],
      "abns" => ["nabs", "bans"], "eort" => ["rote", "tore"], "deew" => ["weed"],
      "abss" => ["bass"], "hksu" => ["husk"], "adiv" => ["diva", "avid"],
      "cilt" => ["clit"], "bdru" => ["drub"], "eity" => ["yeti"],
      "egrs" => ["ergs"], "inty" => ["tiny"], "grtu" => ["trug"],
      "eopt" => ["poet"], "almu" => ["alum", "maul"], "ckoo" => ["cook"],
      "bell" => ["bell"], "ginz" => ["zing"], "abby" => ["baby"],
      "ijnn" => ["jinn"], "aelr" => ["earl", "real"], "deir" => ["dire", "ride"],
      "acgr" => ["crag"], "prsy" => ["spry"], "entv" => ["vent"],
      "morw" => ["worm"], "cist" => ["tics"], "enru" => ["rune"],
      "himw" => ["whim"], "dens" => ["dens", "ends", "send"], "ahrt" => ["hart"],
      "deru" => ["rued", "rude"], "acdi" => ["acid"], "eekl" => ["keel", "leek"],
      "emsu" => ["emus", "muse"], "ansv" => ["vans"], "prru" => ["purr"],
      "ehos" => ["hoes", "hose", "shoe"],
      "enst" => ["nest", "nets", "tens", "sent"], "ellt" => ["tell"],
      "emss" => ["mess"], "aors" => ["oars", "soar"], "ersv" => ["revs"],
      "fino" => ["info"], "ahps" => ["hasp"], "ehnt" => ["then"],
      "adim" => ["amid", "maid"], "optu" => ["pout"], "aotu" => ["auto"],
      "afgs" => ["fags"], "eefs" => ["fees"], "nssu" => ["suns"],
      "adef" => ["fade", "deaf"], "hrsu" => ["rush"], "hoos" => ["oohs", "shoo"],
      "dipr" => ["drip"], "alno" => ["loan"], "cost" => ["cots", "cost"],
      "actt" => ["tact"], "klsu" => ["sulk"], "ejtu" => ["jute"],
      "ceho" => ["echo"], "hswy" => ["whys"], "boos" => ["boos"],
      "dlos" => ["sold"], "estv" => ["vest", "vets"], "bins" => ["nibs", "bins"],
      "eggs" => ["eggs"], "fopr" => ["prof"], "deoz" => ["doze"],
      "abhs" => ["bash"], "nopy" => ["pony"], "estu" => ["suet"],
      "hopw" => ["whop"], "flow" => ["fowl", "wolf", "flow"], "bcru" => ["curb"],
      "ckpu" => ["puck"], "ackt" => ["tack"], "elst" => ["lest", "lets"],
      "lppu" => ["pulp"], "afrt" => ["fart", "frat", "raft"], "acps" => ["caps"],
      "dopr" => ["prod", "drop"], "filt" => ["flit", "lift"],
      "anry" => ["nary", "yarn"], "adhn" => ["hand"], "iprt" => ["trip"],
      "dirs" => ["rids"], "beoy" => ["obey"], "blot" => ["blot", "bolt"],
      "bruy" => ["ruby", "bury"], "enrw" => ["wren"], "eksw" => ["skew"],
      "dffo" => ["doff"], "ampu" => ["puma"], "akrt" => ["kart"],
      "foop" => ["poof"], "abfr" => ["barf"], "eglo" => ["loge", "ogle"],
      "dflo" => ["fold"], "ador" => ["road"], "aemz" => ["maze"],
      "oprt" => ["port"], "abry" => ["bray"], "deip" => ["pied"],
      "artw" => ["wart"], "anpw" => ["pawn"], "ceim" => ["mice"],
      "ginr" => ["grin", "ring"], "eivw" => ["wive", "view"], "ckos" => ["sock"],
      "cnoo" => ["coon"], "acpy" => ["pacy"], "cdee" => ["cede"],
      "jlow" => ["jowl"], "cfku" => ["fuck"], "agsw" => ["swag", "wags"],
      "emsw" => ["mews"], "ottu" => ["tout"], "aair" => ["aria"],
      "asss" => ["sass"], "absy" => ["bays"], "adlu" => ["laud", "dual"],
      "ddos" => ["odds"], "abjs" => ["jabs"], "cikw" => ["wick"],
      "cinz" => ["zinc"], "acef" => ["face"], "abgn" => ["bang"],
      "bevy" => ["bevy"], "ekop" => ["poke"], "cchi" => ["chic"],
      "bdir" => ["bird"], "adgs" => ["dags", "gads"], "fknu" => ["funk"],
      "amsw" => ["maws", "swam"], "ehis" => ["hies"], "oott" => ["toot"],
      "ffhu" => ["huff"], "ainv" => ["vain"], "afht" => ["haft"],
      "ceko" => ["coke"], "ahmt" => ["math"], "airy" => ["airy"],
      "cntu" => ["cunt"], "aivv" => ["viva"], "hitw" => ["whit", "with"],
      "assw" => ["saws"], "abll" => ["ball"], "illt" => ["lilt", "till"],
      "doss" => ["doss", "sods"], "estt" => ["sett", "test"], "akny" => ["yank"],
      "acfl" => ["calf"], "bgru" => ["burg", "grub"], "lstu" => ["slut", "lust"],
      "ekot" => ["toke"], "dors" => ["rods"], "adgw" => ["gawd"],
      "ilno" => ["lino", "loin", "lion"], "insu" => ["unis"], "deny" => ["deny"],
      "ailt" => ["tail"], "foru" => ["four"], "ffiy" => ["iffy"],
      "deps" => ["sped"], "nnsu" => ["nuns"], "gmsu" => ["gums", "mugs", "smug"],
      "ilor" => ["roil"], "aelw" => ["wale", "weal"], "ailm" => ["mail"],
      "oosz" => ["zoos"], "ells" => ["ells", "sell"], "fotu" => ["tofu"],
      "ellw" => ["well"], "aess" => ["seas"], "ggno" => ["gong"],
      "abcr" => ["crab"], "eprs" => ["reps"], "efrt" => ["fret"],
      "aclp" => ["clap"], "buzz" => ["buzz"], "adei" => ["aide", "idea"],
      "aesx" => ["axes"], "gltu" => ["glut"], "eknu" => ["nuke"],
      "adlr" => ["lard"], "agit" => ["gait"], "dins" => ["dins"],
      "eess" => ["sees"], "eepp" => ["peep"], "apsy" => ["spay", "yaps", "pays"],
      "abor" => ["boar"], "adir" => ["arid", "raid"], "dmoo" => ["doom", "mood"],
      "crux" => ["crux"], "bfis" => ["fibs"], "aefz" => ["faze"],
      "abnr" => ["barn", "bran"], "aenw" => ["anew", "wane", "wean"],
      "aeks" => ["sake"], "moss" => ["moss"], "epru" => ["pure"],
      "aghn" => ["hang"], "oost" => ["soot"], "einn" => ["nine"],
      "anwy" => ["yawn"], "agnr" => ["gran", "rang"],
      "gins" => ["gins", "sing", "sign"], "moot" => ["moot"],
      "apss" => ["asps", "saps", "spas", "pass"], "abgs" => ["gabs", "bags"],
      "bors" => ["orbs", "robs"], "goop" => ["goop"], "dewy" => ["dewy"],
      "akrs" => ["arks"], "foow" => ["woof"], "eimr" => ["rime", "emir", "mire"],
      "ffmu" => ["muff"], "affn" => ["naff"], "kmsu" => ["musk"],
      "jknu" => ["junk"], "agos" => ["sago"], "losu" => ["soul"],
      "aknr" => ["nark", "rank"], "eknw" => ["knew"], "iknp" => ["pink"],
      "aceh" => ["ache", "each"], "lotv" => ["volt"], "imrt" => ["trim"],
      "aafr" => ["afar"], "akms" => ["mask"], "lpru" => ["purl"],
      "eipr" => ["pier", "ripe"], "ehir" => ["heir", "hire"], "inru" => ["ruin"],
      "defs" => ["feds"], "orst" => ["tors", "rots", "sort"], "borw" => ["brow"],
      "eloo" => ["oleo"], "dlor" => ["lord"], "gnru" => ["rung"],
      "egsv" => ["vegs"], "einr" => ["rein"], "eehl" => ["heel"],
      "foxy" => ["foxy"], "demo" => ["demo", "dome", "mode"], "fgoo" => ["goof"],
      "coot" => ["coot"], "ersu" => ["rues", "ruse", "sure", "user"],
      "bees" => ["bees"], "eesw" => ["ewes", "wees"], "ahil" => ["hail"],
      "adej" => ["jade"], "hint" => ["hint", "thin"], "bmow" => ["womb"],
      "aber" => ["brae", "bare", "bear"], "cekn" => ["neck"], "gikn" => ["king"],
      "acpt" => ["pact"], "illo" => ["lilo"], "cerw" => ["crew"],
      "cdor" => ["cord"], "afin" => ["fain"], "detu" => ["duet"],
      "chip" => ["chip"], "eimm" => ["mime"], "aklt" => ["talk"],
      "bhos" => ["bosh", "hobs"], "bosw" => ["bows"],
      "abls" => ["albs", "slab", "labs"], "arvy" => ["vary"], "ipsz" => ["zips"],
      "fhis" => ["fish"], "hotu" => ["thou"], "aknw" => ["wank"],
      "hops" => ["posh", "hops", "shop"], "dgos" => ["dogs", "gods"],
      "ckno" => ["conk"], "bnsu" => ["nubs", "buns", "snub"],
      "enrt" => ["tern", "rent"], "aaln" => ["anal"], "opsw" => ["wops"],
      "almt" => ["malt"], "fkor" => ["fork"], "aegt" => ["gate"],
      "fgoy" => ["fogy"], "dehl" => ["held"], "aimm" => ["imam", "maim"],
      "fklo" => ["folk"], "lotu" => ["lout"], "deek" => ["eked"],
      "agry" => ["gray"], "iloy" => ["oily"], "dilo" => ["lido", "idol"],
      "cino" => ["coin", "icon"], "amno" => ["moan"], "entw" => ["newt", "went"],
      "loow" => ["wool"], "cesu" => ["cues"], "ceno" => ["cone", "once"],
      "glmu" => ["glum"], "aelv" => ["vale", "veal"], "eehr" => ["here"],
      "dils" => ["lids", "slid"], "dglo" => ["gold"], "abbe" => ["babe"],
      "adrw" => ["ward", "draw"]}
  end
end
