defmodule Jumble.ScowlDict.Size50.Length16 do
  def get(string_id) do
    %{"aeeghiilnnprttvy" => ["hyperventilating"],
      "aceeiilnnnnorttt" => ["intercontinental"],
      "acdefiiiimnnnost" => ["indemnifications"],
      "bceehiilmnnoprsy" => ["incomprehensibly"],
      "ceehilmoorssssst" => ["schoolmistresses"],
      "aaeeeilrrrrstttx" => ["extraterrestrial"],
      "aaeeeilnnoprrstt" => ["representational"],
      "aeeeiinnoprrrttt" => ["reinterpretation"],
      "aeeimnnorrrstttu" => ["neurotransmitter"],
      "aabiiilnnnnotttu" => ["tintinnabulation"],
      "abeiiiiillmpsstu" => ["implausibilities"],
      "aabeeelnnnorsssu" => ["unreasonableness"],
      "aaacchilloprstty" => ["catastrophically"],
      "cciimnnoorsssttu" => ["misconstructions"],
      "accdegiinnnnostu" => ["discountenancing"],
      "bceiilnnoorrttvy" => ["incontrovertibly"],
      "abeeghiiilnnstux" => ["inextinguishable"],
      "abceimnnorssstuu" => ["rambunctiousness"],
      "aacccehiinrrsttu" => ["uncharacteristic"],
      "aefilnnnoooprsss" => ["nonprofessionals"],
      "aadeiiilmnrsttvy" => ["administratively"],
      "aaaaeiilmnnprrst" => ["parliamentarians"],
      "acdgiiiimnnnrstu" => ["undiscriminating"],
      "aacciillmnrsttuy" => ["circumstantially"],
      "aaacdeilllmmorty" => ["melodramatically"],
      "abbcdgiilmnoostu" => ["discombobulating"],
      "acehhiopprssstty" => ["psychotherapists"],
      "aceefiiilmnopstx" => ["exemplifications"],
      "aaceilnnnnorsttt" => ["transcontinental"],
      "adeiinooopprrstt" => ["disproportionate"],
      "bbbbeefgiiilrstt" => ["flibbertigibbets"],
      "ahijlnoooprssttu" => ["photojournalists"],
      "abcdeiiilnprttuy" => ["unpredictability"],
      "adeeeghhilnrsstt" => ["lightheartedness"],
      "aceeeinnoorsstvv" => ["neoconservatives"],
      "aehhiiopprssstty" => ["physiotherapists"],
      "bdehiilnoorssstt" => ["bloodthirstiness"],
      "bciiiilnoprrttuy" => ["incorruptibility"],
      "aaiiimnooppprrst" => ["misappropriation"],
      "cceeeefgilnnnort" => ["teleconferencing"],
      "acefiiinnooprsst" => ["personifications"],
      "aaccegiknnortttu" => ["counterattacking"],
      "aacghhilloopprty" => ["photographically"],
      "aciilnnnoostttuu" => ["unconstitutional"],
      "ahhimmnooopprrst" => ["anthropomorphism"],
      "aaceeghimnoprrst" => ["cinematographers"],
      "aeeelmnooprstuxy" => ["extemporaneously"],
      "aaeiilnnorrssttt" => ["transliterations"],
      "aacehiillnssttuy" => ["enthusiastically"],
      "aaceillnnoorstvy" => ["conversationally"],
      "acgiinnoooprsstt" => ["prognostications"],
      "acdeeeeinrrrsstu" => ["undersecretaries"],
      "aaccggiiimnnrtuv" => ["circumnavigating"],
      "aeehiinoprrssstw" => ["praiseworthiness"],
      "aceeiiloorrrssst" => ["arteriosclerosis"],
      "ceiiinnorrsssttu" => ["insurrectionists"],
      "aceeimnnoooprstv" => ["overcompensation"],
      "bceeiilnnoorrttv" => ["incontrovertible"],
      "aaabcghiilooprtu" => ["autobiographical"],
      "aaacgiillnnostty" => ["antagonistically"],
      "cceeiinnnnoorstt" => ["interconnections"],
      "aaacciillorrstty" => ["aristocratically"],
      "acciiimmmnnoostu" => ["miscommunication"],
      "acceiimmnnoostux" => ["excommunications"],
      "aaceeknnnorssstu" => ["cantankerousness"],
      "aeeeehinnpprsssv" => ["apprehensiveness"],
      "aacgiillrrssttuu" => ["agriculturalists"],
      "ccceeiklnoorstuw" => ["counterclockwise"],
      "aceiinnoorsssttv" => ["conservationists"],
      "acdeiiiilmnnrsty" => ["indiscriminately"],
      "celnnoprssssuuuu" => ["unscrupulousness"],
      "addegiimnnnrsstu" => ["misunderstanding"],
      "aghhillmooopsstt" => ["ophthalmologists"],
      "aaegiilnnorssttt" => ["gastrointestinal"],
      "aceehiinorssttuv" => ["overenthusiastic"],
      "aaaefilnoopprrss" => ["paraprofessional"],
      "ccdeehiilorrttyy" => ["hydroelectricity"],
      "eemnopprsssstuuu" => ["presumptuousness"],
      "ccciiimnoprrsstu" => ["circumscriptions"],
      "aeiilmnnrssstttu" => ["instrumentalists"],
      "aabccegilnnnortu" => ["counterbalancing"],
      "aaaacchhillmsttw" => ["whatchamacallits"],
      "aaccghilloprrsty" => ["crystallographic"],
      "aefiilmnorssstuu" => ["multifariousness"],
      "aceeeginnooprstu" => ["counterespionage"],
      "aceeegilmmnorstt" => ["electromagnetism"],
      "aeefiilmnooprsss" => ["semiprofessional"],
      "aaahiiimnorrsttu" => ["authoritarianism"],
      "aeehiimnnopprsss" => ["misapprehensions"],
      "aaabcceillrrtuuy" => ["bureaucratically"],
      "aeeiilmnnnorsttv" => ["environmentalist"],
      "aaccgiiimnnortuv" => ["circumnavigation"],
      "acdiiinnnoossttu" => ["discontinuations"],
      "eehiiinprssttvyy" => ["hypersensitivity"],
      "cgiilmmnnooprsuy" => ["uncompromisingly"],
      "beiiiilnoprrssty" => ["irresponsibility"],
      "abbeiiilmprrttuy" => ["imperturbability"],
      "aceegimnnooprstv" => ["overcompensating"],
      "acdeefhiimnnrsst" => ["disfranchisement"],
      "aceillnnnnootuvy" => ["unconventionally"],
      "acdefghiiinnnrss" => ["disenfranchising"],
      "eeghinooppstttty" => ["phototypesetting"],
      "aciillnnoostttuy" => ["constitutionally"],
      "aeeiilmmnnnorstv" => ["environmentalism"],
      "aacdeellnnnrstty" => ["transcendentally"],
      "deeghhinorsssstt" => ["shortsightedness"],
      "aeeeeinnprrsttuv" => ["unrepresentative"],
      "aaeiiilmnnnorstt" => ["internationalism"],
      "bceeehiilmnnoprs" => ["incomprehensible"],
      "aefiilnnnoooprrt" => ["nonproliferation"],
      "aciilllmmrsttuuu" => ["multiculturalism"],
      "aeehiilnnoprttvy" => ["hyperventilation"],
      "adeiiillmmnnostu" => ["multidimensional"],
      "aeiiiilllmmnortu" => ["multimillionaire"],
      "aagiiimnoppprrst" => ["misappropriating"],
      "aacdfiiiilnoqstu" => ["disqualification"],
      "beeiiiilnoprssst" => ["responsibilities"],
      "aciiimnnnooprstu" => ["mispronunciation"],
      "adeeeiimnnoprrtt" => ["predetermination"]}
    |> Map.get(string_id)
  end

  def valid_ids do
    ["aeeghiilnnprttvy", "aceeiilnnnnorttt", "acdefiiiimnnnost", "bceehiilmnnoprsy",
     "ceehilmoorssssst", "aaeeeilrrrrstttx", "aaeeeilnnoprrstt", "aeeeiinnoprrrttt",
     "aeeimnnorrrstttu", "aabiiilnnnnotttu", "abeiiiiillmpsstu", "aabeeelnnnorsssu",
     "aaacchilloprstty", "cciimnnoorsssttu", "accdegiinnnnostu", "bceiilnnoorrttvy",
     "abeeghiiilnnstux", "abceimnnorssstuu", "aacccehiinrrsttu", "aefilnnnoooprsss",
     "aadeiiilmnrsttvy", "aaaaeiilmnnprrst", "acdgiiiimnnnrstu", "aacciillmnrsttuy",
     "aaacdeilllmmorty", "abbcdgiilmnoostu", "acehhiopprssstty", "aceefiiilmnopstx",
     "aaceilnnnnorsttt", "adeiinooopprrstt", "bbbbeefgiiilrstt", "ahijlnoooprssttu",
     "abcdeiiilnprttuy", "adeeeghhilnrsstt", "aceeeinnoorsstvv", "aehhiiopprssstty",
     "bdehiilnoorssstt", "bciiiilnoprrttuy", "aaiiimnooppprrst", "cceeeefgilnnnort",
     "acefiiinnooprsst", "aaccegiknnortttu", "aacghhilloopprty", "aciilnnnoostttuu",
     "ahhimmnooopprrst", "aaceeghimnoprrst", "aeeelmnooprstuxy", "aaeiilnnorrssttt",
     "aacehiillnssttuy", "aaceillnnoorstvy", "acgiinnoooprsstt", "acdeeeeinrrrsstu",
     "aaccggiiimnnrtuv", "aeehiinoprrssstw", "aceeiiloorrrssst", "ceiiinnorrsssttu",
     "aceeimnnoooprstv", "bceeiilnnoorrttv", "aaabcghiilooprtu", "aaacgiillnnostty",
     "cceeiinnnnoorstt", "aaacciillorrstty", "acciiimmmnnoostu", "acceiimmnnoostux",
     "aaceeknnnorssstu", "aeeeehinnpprsssv", "aacgiillrrssttuu", "ccceeiklnoorstuw",
     "aceiinnoorsssttv", "acdeiiiilmnnrsty", "celnnoprssssuuuu", "addegiimnnnrsstu",
     "aghhillmooopsstt", "aaegiilnnorssttt", "aceehiinorssttuv", "aaaefilnoopprrss",
     "ccdeehiilorrttyy", "eemnopprsssstuuu", "ccciiimnoprrsstu", "aeiilmnnrssstttu",
     "aabccegilnnnortu", "aaaacchhillmsttw", "aaccghilloprrsty", "aefiilmnorssstuu",
     "aceeeginnooprstu", "aceeegilmmnorstt", "aeefiilmnooprsss", "aaahiiimnorrsttu",
     "aeehiimnnopprsss", "aaabcceillrrtuuy", "aeeiilmnnnorsttv", "aaccgiiimnnortuv",
     "acdiiinnnoossttu", "eehiiinprssttvyy", "cgiilmmnnooprsuy", "beiiiilnoprrssty",
     "abbeiiilmprrttuy", "aceegimnnooprstv", "acdeefhiimnnrsst", "aceillnnnnootuvy",
     "acdefghiiinnnrss", "eeghinooppstttty", "aciillnnoostttuy", "aeeiilmmnnnorstv",
     "aacdeellnnnrstty", "deeghhinorsssstt", "aeeeeinnprrsttuv", "aaeiiilmnnnorstt",
     "bceeehiilmnnoprs", "aefiilnnnoooprrt", "aciilllmmrsttuuu", "aeehiilnnoprttvy",
     "adeiiillmmnnostu", "aeiiiilllmmnortu", "aagiiimnoppprrst", "aacdfiiiilnoqstu",
     "beeiiiilnoprssst", "aciiimnnnooprstu", "adeeeiimnnoprrtt"]
    |> Enum.into(HashSet.new)
  end
end
