defmodule Jumble.ScowlDict.Size50.Length4 do
  def get(string_id) do
    %{"grsu" => ["rugs"], "ekow" => ["woke"],
      "hstu" => ["tush", "huts", "shut", "thus"], "eilw" => ["wile"],
      "eilm" => ["lime", "mile"], "ilmy" => ["limy"], "hloy" => ["holy"],
      "afos" => ["oafs", "sofa"], "akln" => ["lank"], "gimr" => ["grim"],
      "bbes" => ["ebbs"], "intw" => ["twin"], "adkn" => ["dank"],
      "gnos" => ["song"], "eflo" => ["floe"], "adip" => ["paid"],
      "ilnt" => ["lint"], "aetz" => ["zeta"], "imps" => ["imps"],
      "dhtu" => ["thud"], "deho" => ["hoed"], "dehs" => ["shed"],
      "blos" => ["lobs", "slob"], "aegv" => ["gave"], "flux" => ["flux"],
      "aees" => ["ease"], "irwy" => ["wiry"], "besw" => ["webs"],
      "iquz" => ["quiz"], "ilmp" => ["limp"], "ksuy" => ["yuks"],
      "desz" => ["zeds"], "blow" => ["bowl", "blow"],
      "aept" => ["pate", "peat", "tape"], "ceht" => ["etch"],
      "gstu" => ["gust", "tugs", "guts"], "cefl" => ["clef"],
      "eilt" => ["lite", "tile"], "apps" => ["apps", "paps"], "ahow" => ["whoa"],
      "best" => ["best", "bets"], "aesy" => ["yeas", "ayes", "easy"],
      "krsu" => ["rusk"], "bill" => ["bill"], "afir" => ["fair"],
      "lnxy" => ["lynx"], "aeht" => ["hate", "heat"], "girs" => ["rigs"],
      "ekls" => ["elks"], "achp" => ["chap"], "eikt" => ["kite"],
      "kosw" => ["woks"], "agnp" => ["pang"], "elos" => ["sloe", "sole", "lose"],
      "eert" => ["tree"], "aikn" => ["akin"], "diks" => ["skid", "kids", "disk"],
      "ceir" => ["rice"], "anst" => ["ants", "tans"], "emos" => ["emos", "some"],
      "agot" => ["toga", "goat"], "aggo" => ["agog"], "ceor" => ["core"],
      "ahst" => ["hats"], "clop" => ["clop"], "cikp" => ["pick"],
      "iqtu" => ["quit"], "bmsu" => ["bums"], "egst" => ["gets"],
      "iklo" => ["kilo"], "amsy" => ["yams"], "aelt" => ["teal", "tale", "late"],
      "amps" => ["spam", "amps", "maps"], "antw" => ["want"], "aitx" => ["taxi"],
      "impw" => ["wimp"], "eils" => ["leis", "isle", "lies"], "ehlp" => ["help"],
      "deln" => ["lend"], "noxy" => ["onyx"], "dims" => ["dims"],
      "arsw" => ["wars"], "foor" => ["roof"], "ilot" => ["toil"],
      "aemx" => ["exam"], "eekw" => ["week"], "adhr" => ["hard"],
      "amss" => ["mass"], "afhl" => ["half"], "adds" => ["dads", "adds"],
      "ehno" => ["hone"], "fssu" => ["fuss"], "loot" => ["loot", "tool"],
      "fuzz" => ["fuzz"], "npuy" => ["puny"], "deeg" => ["geed", "edge"],
      "ackp" => ["pack"], "ahtw" => ["thaw", "what"], "beit" => ["bite"],
      "ddoo" => ["dodo"], "aklr" => ["lark"], "elru" => ["lure", "rule"],
      "ikss" => ["skis", "kiss"], "clru" => ["curl"], "eoru" => ["euro"],
      "ceps" => ["pecs", "spec"], "dnos" => ["nods", "dons"], "elns" => ["lens"],
      "hosw" => ["hows", "show"], "bfos" => ["fobs"], "deem" => ["deem"],
      "arwy" => ["awry", "wary"], "beij" => ["jibe"], "eorw" => ["wore"],
      "elmw" => ["mewl"], "ansy" => ["nays"], "pttu" => ["putt"],
      "bllu" => ["bull"], "akmr" => ["mark"], "chop" => ["chop"],
      "hrtu" => ["thru", "hurt"], "aapp" => ["papa"], "denw" => ["wend"],
      "aftw" => ["waft"], "gnot" => ["tong"],
      "aprs" => ["pars", "raps", "rasp", "spar"], "cjko" => ["jock"],
      "agsy" => ["gays"], "jlot" => ["jolt"], "dorw" => ["word"],
      "eims" => ["semi"], "agns" => ["nags", "sang", "snag"], "elpy" => ["yelp"],
      "hntu" => ["hunt"], "acev" => ["cave"], "pstu" => ["puts"],
      "psst" => ["psst"], "eipp" => ["pipe"], "delw" => ["lewd", "weld"],
      "noos" => ["soon"], "fgit" => ["gift"], "mosw" => ["mows"],
      "cmsu" => ["scum", "cums"], "aepx" => ["apex"], "desy" => ["dyes"],
      "alov" => ["oval"], "aalv" => ["lava"], "aehr" => ["rhea", "hare", "hear"],
      "bdei" => ["bide"], "cdeo" => ["coed", "code"], "loos" => ["solo"],
      "adry" => ["dray", "yard"], "diov" => ["void"], "ills" => ["ills", "sill"],
      "akos" => ["oaks", "soak"], "efrs" => ["serf", "refs"], "bboo" => ["boob"],
      "dmru" => ["drum"], "aint" => ["anti"], "adep" => ["aped"],
      "belo" => ["bole", "lobe"], "deis" => ["ides", "dies", "side"],
      "iklm" => ["milk"], "delo" => ["lode", "dole"], "anss" => ["sans"],
      "dilw" => ["wild"], "imot" => ["omit"], "hist" => ["shit", "hits", "this"],
      "beuz" => ["zebu"], "nort" => ["torn"], "aeps" => ["apse", "apes", "peas"],
      "ahsy" => ["ashy", "hays"], "orsy" => ["rosy"], "awxy" => ["waxy"],
      "irst" => ["stir"], "ftuz" => ["futz"], "admn" => ["damn"],
      "cdru" => ["crud", "curd"], "mstu" => ["smut", "must"], "hklu" => ["hulk"],
      "clow" => ["cowl"], "allm" => ["mall"], "cdlo" => ["clod", "cold"],
      "eppr" => ["prep"], "abds" => ["dabs"], "fnot" => ["font"],
      "afmo" => ["foam"], "aceg" => ["cage"], "abde" => ["abed", "bade", "bead"],
      "bdsu" => ["buds", "dubs"], "entu" => ["tune"], "imnt" => ["mint"],
      "intt" => ["tint"], "elms" => ["elms"], "biot" => ["obit"],
      "acht" => ["chat"], "bety" => ["byte"], "ablo" => ["bola"],
      "aegs" => ["sage", "ages"], "gilt" => ["gilt"], "doru" => ["dour"],
      "ilps" => ["lips", "lisp", "slip"], "eopp" => ["pope"], "know" => ["know"],
      "fglu" => ["gulf"], "ahht" => ["hath"], "essu" => ["sues", "uses"],
      "elry" => ["lyre", "rely"], "gijs" => ["jigs"], "dknu" => ["dunk"],
      "emop" => ["mope", "poem"], "aknt" => ["tank"], "blru" => ["blur"],
      "istz" => ["zits"], "bgno" => ["bong"], "aelm" => ["lame", "male", "meal"],
      "ehmt" => ["them"], "ginp" => ["ping"], "egnt" => ["gent"],
      "aeev" => ["eave"], "enpt" => ["pent"], "hmow" => ["whom"],
      "mouv" => ["ovum"], "dikr" => ["dirk"], "lmsu" => ["slum"],
      "dlou" => ["loud"], "eirs" => ["sire", "rise"], "afiw" => ["waif"],
      "ilos" => ["oils", "silo", "soil"], "eegs" => ["gees"],
      "losw" => ["lows", "owls", "slow"], "aesw" => ["awes"], "ejko" => ["joke"],
      "ehmo" => ["home"], "dinr" => ["rind"], "einv" => ["vine", "vein"],
      "ailn" => ["nail", "lain"], "gotu" => ["gout"], "fort" => ["fort"],
      "eilr" => ["lire", "rile"], "cdsu" => ["cuds", "scud"], "eorz" => ["zero"],
      "mnor" => ["morn", "norm"], "afgn" => ["fang"], "cksu" => ["suck"],
      "behr" => ["herb"], "gips" => ["pigs"], "ahss" => ["sash"],
      "ciru" => ["uric"], "knoo" => ["nook"], "aegw" => ["wage"],
      "ipst" => ["pits", "spit", "tips"], "ainr" => ["rain"], "assy" => ["says"],
      "abin" => ["bani"], "illp" => ["pill"], "aopt" => ["atop"],
      "fruy" => ["fury"], "aegz" => ["gaze"], "adis" => ["dais", "aids", "said"],
      "aclo" => ["cola", "coal"], "cops" => ["cops"], "delv" => ["veld"],
      "emmo" => ["memo"], "ackw" => ["wack"],
      "acst" => ["scat", "cast", "cats", "acts"], "hipt" => ["pith"],
      "eooz" => ["ooze"], "afnw" => ["fawn"], "arty" => ["arty", "tray"],
      "imsw" => ["swim"], "adqu" => ["quad"], "estz" => ["zest"],
      "agin" => ["gain"], "aefl" => ["flea", "leaf"], "efls" => ["self"],
      "opss" => ["sops"], "lowy" => ["yowl"], "amot" => ["moat", "atom"],
      "cdtu" => ["duct"], "cikk" => ["kick"], "adrt" => ["dart"],
      "bclo" => ["bloc"], "lnoy" => ["only"], "knsu" => ["sunk"],
      "eilu" => ["lieu"], "ttuu" => ["tutu"], "defl" => ["fled"],
      "koor" => ["rook"], "bglo" => ["glob", "blog"], "mmos" => ["moms"],
      "anyz" => ["zany"], "aksu" => ["auks"], "flou" => ["foul"],
      "bgos" => ["gobs", "bogs"], "lops" => ["pols", "lops", "slop"],
      "aehv" => ["have"], "deop" => ["dope"], "osst" => ["sots", "toss"],
      "mosu" => ["sumo"], "bkoo" => ["book"], "belu" => ["lube", "blue"],
      "aerr" => ["rear", "rare"], "inow" => ["wino"], "dlop" => ["plod"],
      "acdr" => ["card"], "aemr" => ["mare", "ream"], "cltu" => ["cult"],
      "acrt" => ["cart"], "djou" => ["judo"], "mrsu" => ["rums"],
      "efst" => ["fest"], "efiw" => ["wife"], "avwy" => ["wavy"],
      "astv" => ["vats", "vast"], "eikp" => ["pike"], "abfl" => ["flab"],
      "bhot" => ["both"], "cehk" => ["heck"], "ilms" => ["mils", "slim"],
      "bemr" => ["berm"], "acer" => ["acre", "care", "race"], "dfnu" => ["fund"],
      "desu" => ["dues", "sued", "used"], "alor" => ["oral"],
      "ader" => ["dare", "dear", "read"], "iort" => ["trio", "riot"],
      "agst" => ["stag", "tags"], "aehk" => ["hake"], "bdes" => ["debs", "beds"],
      "depu" => ["dupe"], "oppr" => ["prop"], "agoy" => ["yoga"],
      "foot" => ["foot"], "denv" => ["vend"], "eory" => ["yore"],
      "admp" => ["damp"], "adst" => ["tads"], "aegr" => ["gear", "rage"],
      "lopt" => ["plot"], "dels" => ["sled"], "adlo" => ["load"],
      "egls" => ["gels", "legs"], "aorr" => ["roar"], "aaqu" => ["aqua"],
      "eejr" => ["jeer"], "gjsu" => ["jugs"], "hlsu" => ["lush"],
      "dily" => ["idly"], "adot" => ["toad"], "ahkr" => ["hark"],
      "mpsu" => ["sump", "umps"], "bblu" => ["bulb"], "amoy" => ["mayo"],
      "boor" => ["boor"], "cghu" => ["chug"], "bdis" => ["bids"],
      "ahoy" => ["ahoy"], "dehr" => ["herd"], "mnoo" => ["mono", "moon"],
      "absw" => ["swab"], "aehp" => ["heap"], "bhoo" => ["hobo"],
      "apry" => ["pray"], "alpy" => ["play"], "ostw" => ["stow", "tows", "twos"],
      "acel" => ["lace"], "hisw" => ["wish"], "ahrs" => ["rash"],
      "elmo" => ["mole"], "aflo" => ["foal", "loaf"], "enox" => ["oxen"],
      "cehw" => ["chew"], "adps" => ["pads"], "begs" => ["begs"],
      "dgnu" => ["dung"], "amst" => ["tams", "mast", "mats"], "dluy" => ["duly"],
      "allt" => ["tall"], "gitw" => ["twig"], "aims" => ["aims"],
      "chko" => ["hock"], "aett" => ["teat"], "abim" => ["iamb"],
      "afmr" => ["farm"], "ainp" => ["pain"], "jmpu" => ["jump"],
      "estw" => ["stew", "wets", "west"], "dnop" => ["pond"], "cikl" => ["lick"],
      "abes" => ["base"], "beik" => ["bike"], "asty" => ["stay"],
      "eovw" => ["wove"], "kmno" => ["monk"], "anvy" => ["navy"],
      "bent" => ["bent"], "adns" => ["sand"], "hnsu" => ["shun"],
      "aben" => ["bane", "bean"], "belt" => ["belt"], "hoop" => ["pooh", "hoop"],
      "clos" => ["cols"], "brsu" => ["burs", "rubs"], "dgru" => ["drug"],
      "ekrt" => ["trek"], "degy" => ["edgy"], "artt" => ["tart"],
      "bjos" => ["jobs"], "amny" => ["many"], "bclu" => ["club"],
      "ampt" => ["tamp"], "deer" => ["deer", "reed"], "epry" => ["prey", "pyre"],
      "ghhi" => ["high"], "ablm" => ["balm", "lamb"], "deet" => ["teed"],
      "ciss" => ["sics"], "egru" => ["urge"], "chir" => ["rich"],
      "entt" => ["tent"], "adet" => ["date"], "elpt" => ["pelt"],
      "jost" => ["jots"], "inot" => ["into"], "aert" => ["tare", "tear", "rate"],
      "girt" => ["girt", "trig", "grit"], "ehty" => ["they"], "cein" => ["nice"],
      "ahpr" => ["harp"], "beer" => ["beer"], "eekp" => ["peek", "keep"],
      "gisw" => ["swig", "wigs"], "efos" => ["foes"], "opsy" => ["posy"],
      "ppsu" => ["pups"], "illm" => ["mill"], "apsz" => ["zaps"],
      "abot" => ["boat"], "abbr" => ["barb"], "bceu" => ["cube"],
      "aagr" => ["agar", "raga"], "cgos" => ["cogs"], "dees" => ["seed"],
      "npsw" => ["pwns"], "dhos" => ["hods", "shod"], "hhsu" => ["hush"],
      "cllu" => ["cull"], "deov" => ["dove"], "josy" => ["joys"],
      "aggs" => ["gags"], "emrt" => ["term"], "cpsu" => ["cusp", "cups"],
      "aflt" => ["flat"], "aesv" => ["vase", "save"], "been" => ["been"],
      "dimn" => ["mind"], "aagl" => ["alga", "gala"], "adhs" => ["shad", "dash"],
      "hins" => ["shin"], "hkoo" => ["hook"], "hmot" => ["moth"],
      "cell" => ["cell"], "aeft" => ["feta", "feat", "fate"], "hmos" => ["ohms"],
      "abem" => ["beam"], "frtu" => ["turf"], "loop" => ["polo", "loop", "pool"],
      "eemr" => ["mere"], "acip" => ["pica"],
      "anps" => ["naps", "pans", "snap", "span"], "eost" => ["toes"],
      "adsy" => ["days"], "ekoy" => ["yoke"], "ghis" => ["sigh"],
      "istw" => ["wist", "wits"], "aclt" => ["talc"], "iknw" => ["wink"],
      "delm" => ["meld"], "abdu" => ["daub", "baud"], "cetu" => ["cute"],
      "bcir" => ["crib"], "aluu" => ["luau"], "nost" => ["snot", "tons"],
      "bdoy" => ["body"], "efnr" => ["fern"], "glpu" => ["gulp", "plug"],
      "eilp" => ["pile"], "acpr" => ["carp", "crap"], "beil" => ["bile"],
      "ckuy" => ["yuck"], "ikmn" => ["mink"], "delu" => ["duel"],
      "ghnu" => ["hung"], "dhot" => ["doth"], "knpu" => ["punk"],
      "drsy" => ["drys"], "agps" => ["gaps", "gasp"], "diqu" => ["quid"],
      "afly" => ["flay"], "bikl" => ["bilk"], "deos" => ["odes", "dose", "does"],
      "eluy" => ["yule"], "dllu" => ["dull"], "agmy" => ["gamy"],
      "mpru" => ["rump"], "errs" => ["errs"], "acds" => ["cads", "scad"],
      "aels" => ["leas", "ales", "seal", "sale"], "oprs" => ["pros"],
      "opsu" => ["opus", "soup"], "film" => ["milf", "film"], "bmnu" => ["numb"],
      "ggor" => ["grog"], "enno" => ["neon", "none"], "deku" => ["duke"],
      "gost" => ["togs"], "nosw" => ["sown", "owns", "snow"],
      "apsw" => ["paws", "wasp", "swap"], "alos" => ["also"], "cekp" => ["peck"],
      "ejkr" => ["jerk"], "flot" => ["loft"], "adft" => ["daft"],
      "nnoo" => ["noon"], "acrs" => ["arcs", "scar", "cars"], "dssu" => ["suds"],
      "alst" => ["lats", "slat", "salt", "last"], "adez" => ["adze", "daze"],
      "ckop" => ["pock"], "bttu" => ["butt"], "aipt" => ["pita"],
      "enov" => ["oven"], "emno" => ["omen"], "llop" => ["poll"],
      "eflw" => ["flew"], "eelp" => ["peel"], "bdeo" => ["bode"],
      "agjs" => ["jags"], "gioy" => ["yogi"], "anox" => ["axon"],
      "bdet" => ["debt"], "imss" => ["isms", "sims", "miss"],
      "efir" => ["rife", "fire"], "ikll" => ["kill"], "lllu" => ["lull"],
      "eemm" => ["meme"], "hips" => ["hips", "ship"], "bgsu" => ["bugs"],
      "acim" => ["mica"], "ajsw" => ["jaws"], "ailv" => ["vial"],
      "adgo" => ["goad"], "aelz" => ["laze", "zeal"], "eekn" => ["knee", "keen"],
      "aekw" => ["wake", "weak"], "hilt" => ["hilt"],
      "aekl" => ["kale", "lake", "leak"], "ahkn" => ["ankh", "hank", "khan"],
      "ahlu" => ["hula", "haul"], "deno" => ["node", "done"], "ansu" => ["anus"],
      "bimr" => ["brim"], "afry" => ["fray"], "ejst" => ["jets", "jest"],
      "bmoo" => ["boom"], "acft" => ["fact"], "alwy" => ["yawl"],
      "ddei" => ["died"], "aehz" => ["haze"], "acek" => ["cake"],
      "hnor" => ["horn"], "mmsu" => ["mums"], "aamm" => ["mama"],
      "agss" => ["sags"], "bklu" => ["bulk"], "nopr" => ["porn"],
      "kopy" => ["poky"], "eepv" => ["veep"], "ceop" => ["cope"],
      "biis" => ["ibis"], "ahpt" => ["path"], "dirt" => ["dirt"],
      "beef" => ["beef"], "anov" => ["nova"], "llpu" => ["pull"],
      "eghu" => ["huge"], "afil" => ["fail"], "dlot" => ["dolt", "told"],
      "bder" => ["bred"], "abcs" => ["cabs", "scab"], "abel" => ["bale", "able"],
      "aghs" => ["shag", "gash", "hags"], "lpsu" => ["plus"], "betu" => ["tube"],
      "jstu" => ["juts", "just"], "bnor" => ["born"], "chik" => ["hick"],
      "osvw" => ["vows"], "bdmu" => ["dumb"], "aehy" => ["yeah"],
      "alot" => ["alto"], "abdn" => ["band"], "frsu" => ["furs", "surf"],
      "aekm" => ["make"], "ikps" => ["skip"], "eeks" => ["ekes", "seek"],
      "ostu" => ["oust", "outs"], "egor" => ["gore", "ogre", "ergo"],
      "anno" => ["anon"], "eorv" => ["rove", "over"], "deey" => ["eyed"],
      "ahmr" => ["harm"], "afnu" => ["faun"], "iknt" => ["knit"],
      "ehlo" => ["hole"], "ikkn" => ["kink"], "notw" => ["wont", "town"],
      "ertu" => ["true"], "abst" => ["bast", "bats", "stab", "tabs"],
      "astt" => ["tats"], "dhis" => ["dish"], "ffit" => ["tiff"],
      "belw" => ["blew"], "adln" => ["land"], "acde" => ["aced"],
      "ally" => ["ally"], "bilm" => ["limb"], "bcek" => ["beck"],
      "bops" => ["bops"], "gsuy" => ["guys"], "abkn" => ["bank"],
      "lrsu" => ["slur"], "eflt" => ["felt", "left"], "flop" => ["flop"],
      "oruy" => ["your"], "mooz" => ["zoom"],
      "eimt" => ["mite", "emit", "item", "time"], "ffos" => ["offs"],
      "eels" => ["lees", "eels", "else"], "nrtu" => ["runt", "turn"],
      "prsu" => ["spur"], "intu" => ["unit"], "oort" => ["root"],
      "llmo" => ["moll"], "glsu" => ["lugs", "slug"], "dnow" => ["down"],
      "dfor" => ["ford"], "npsu" => ["spun", "puns"], "ehiv" => ["hive"],
      "almo" => ["loam"], "fizz" => ["fizz"], "agnt" => ["gnat", "tang"],
      "anor" => ["roan"], "ortu" => ["rout", "tour"], "coop" => ["coop"],
      "afst" => ["fats", "fast"], "dity" => ["tidy"],
      "aest" => ["sate", "teas", "seat", "east", "eats"], "afkl" => ["flak"],
      "ehpy" => ["hype"], "cdek" => ["deck"], "beno" => ["bone"],
      "acry" => ["racy"], "eswy" => ["yews"], "dstu" => ["stud", "dust"],
      "ehsu" => ["hues"], "ostt" => ["tots"], "aijl" => ["jail"],
      "hikt" => ["kith"], "acks" => ["cask", "sack"], "emov" => ["move"],
      "gist" => ["gist"], "ikno" => ["oink"], "mppu" => ["pump"],
      "berv" => ["verb"], "derw" => ["drew"], "hmty" => ["myth"],
      "elmu" => ["mule"], "ffru" => ["ruff"], "eeps" => ["pees", "seep"],
      "celw" => ["clew"], "cssu" => ["cuss"], "illr" => ["rill"],
      "eenv" => ["even"], "cloy" => ["cloy"], "ikns" => ["inks", "sink", "skin"],
      "ajms" => ["jams"], "amor" => ["roam"], "hjos" => ["josh"],
      "ajsy" => ["jays"], "msuw" => ["swum"], "aksy" => ["yaks"],
      "irtw" => ["writ"], "aces" => ["aces", "case"], "bilo" => ["boil"],
      "afln" => ["flan"], "agls" => ["gals", "lags", "slag"], "ceiv" => ["vice"],
      "bgir" => ["brig"], "kstu" => ["tusk"], "elnt" => ["lent"],
      "ahkw" => ["hawk"], "chmu" => ["chum", "much"], "eins" => ["sine"],
      "cnor" => ["corn"], "deef" => ["feed"], "aipr" => ["pair"],
      "eesy" => ["eyes"], "bbis" => ["bibs"], "ahtt" => ["that"],
      "elor" => ["lore", "role"], "aefr" => ["fare", "fear"],
      "eirw" => ["weir", "wire"], "ensy" => ["yens"],
      "nstu" => ["tuns", "nuts", "stun"], "bosy" => ["boys"], "aefs" => ["safe"],
      "bden" => ["bend"], "beep" => ["beep"], "deks" => ["desk"],
      "deep" => ["peed", "deep"], "agmr" => ["gram"], "fgis" => ["figs"],
      "ehll" => ["hell"], "adgr" => ["grad", "drag"], "envy" => ["envy"],
      "acem" => ["acme", "mace", "came"], "elop" => ["lope", "pole"],
      "abet" => ["bate", "abet", "beat", "beta"], "nrsu" => ["urns", "runs"],
      "bouy" => ["buoy"], "allp" => ["pall"], "antu" => ["tuna", "aunt"],
      "acox" => ["coax"], "bnoy" => ["bony"], "dfoo" => ["food"],
      "aent" => ["ante", "neat"], "aclw" => ["claw"], "ccko" => ["cock"],
      "beru" => ["rube"], "eotv" => ["veto", "vote"], "afgl" => ["flag"],
      "beix" => ["ibex"], "lost" => ["slot", "lost", "lots"], "eens" => ["seen"],
      "enot" => ["tone", "note"], "ahms" => ["hams", "mash", "sham"],
      "ijno" => ["join"], "abit" => ["bait"], "aals" => ["alas"],
      "admr" => ["dram"], "eott" => ["tote"], "door" => ["rood", "door"],
      "hiss" => ["hiss"], "ceov" => ["cove"], "ceot" => ["cote"],
      "abil" => ["bail"], "alms" => ["lams", "alms", "slam"], "dhoo" => ["hood"],
      "emor" => ["more"], "bhsu" => ["hubs", "bush"], "ablw" => ["bawl"],
      "gmsy" => ["gyms"], "mttu" => ["mutt"], "bflu" => ["flub"],
      "aklw" => ["walk"], "bblo" => ["blob"], "illw" => ["will"],
      "inpt" => ["pint"], "eltu" => ["lute"], "eerw" => ["ewer", "weer", "were"],
      "hmny" => ["hymn"], "ahls" => ["lash"], "ekpu" => ["puke"],
      "ails" => ["ails", "sail"], "aemt" => ["mate", "meat", "tame", "team"],
      "inor" => ["iron"], "fost" => ["soft"], "aelx" => ["axle"],
      "aegp" => ["gape", "page"], "aehl" => ["hale", "heal"], "adiw" => ["wadi"],
      "arst" => ["tars", "arts", "rats", "star"], "amrw" => ["warm"],
      "bssu" => ["subs", "buss"], "cktu" => ["tuck"], "egps" => ["pegs"],
      "hipw" => ["whip"], "dery" => ["dyer"], "bdlo" => ["bold"],
      "boot" => ["boot"], "acsw" => ["caws"], "eejp" => ["jeep"],
      "alsw" => ["awls", "slaw", "laws"], "dikn" => ["kind"], "aimn" => ["main"],
      "abjm" => ["jamb"], "aerv" => ["aver", "rave"], "aovw" => ["avow"],
      "eptw" => ["wept"], "aden" => ["dean"], "cstu" => ["cuts"],
      "deft" => ["deft"], "ampv" => ["vamp"], "aiot" => ["iota"],
      "acms" => ["cams", "scam"], "aops" => ["soap"], "acot" => ["taco", "coat"],
      "dill" => ["dill"], "fglo" => ["flog", "golf"], "bnoo" => ["boon"],
      "ilwy" => ["wily"], "abht" => ["bath"], "elly" => ["yell"],
      "ipsy" => ["yips"], "cosw" => ["scow", "cows"], "ikms" => ["skim"],
      "elss" => ["less"], "beiv" => ["vibe"], "cdei" => ["iced", "dice"],
      "gknu" => ["gunk"], "lnor" => ["lorn"], "defu" => ["feud"],
      "firs" => ["firs"], "adeg" => ["aged"], "eisw" => ["wise"],
      "copy" => ["copy"], "ciks" => ["sick"], "noot" => ["onto"],
      "eiln" => ["lien", "line"], "aenp" => ["nape", "pane"], "addo" => ["dado"],
      "hnos" => ["nosh"], "efns" => ["fens"], "emtu" => ["mute"],
      "fins" => ["fins"], "abhl" => ["blah"], "aags" => ["saga"],
      "arsy" => ["rays"], "bdno" => ["bond"], "nptu" => ["punt"],
      "inos" => ["ions"], "ffgu" => ["guff"], "ehns" => ["hens"],
      "epps" => ["peps"], "alsy" => ["slay", "lays"],
      "ailr" => ["lira", "lair", "liar", "rail"], "gilr" => ["girl"],
      "esty" => ["yest"], "dmor" => ["dorm"], "aenr" => ["earn", "near"],
      "noty" => ["tony"], "aegm" => ["game"], "alss" => ["lass"],
      "dips" => ["dips"], "efil" => ["lief", "file", "life"], "kloo" => ["look"],
      "bnos" => ["snob"], "eltw" => ["welt"], "emst" => ["stem"],
      "hopy" => ["hypo"], "deil" => ["deli", "idle", "lied"], "beir" => ["bier"],
      "aehm" => ["ahem"], "adeh" => ["head"], "kkoo" => ["kook"],
      "ghin" => ["nigh"], "aflp" => ["flap"], "ceex" => ["exec"],
      "aort" => ["taro"], "eegl" => ["glee"], "iikw" => ["wiki", "kiwi"],
      "deor" => ["doer", "redo", "rode"], "eekr" => ["reek"],
      "epsy" => ["espy", "yeps"], "egms" => ["megs", "gems"], "dost" => ["dots"],
      "lopy" => ["ploy"], "ahlt" => ["lath", "halt"], "essw" => ["sews"],
      "chit" => ["chit", "itch"], "ceit" => ["cite"],
      "enos" => ["noes", "nose", "ones"], "cikn" => ["nick"],
      "gipr" => ["prig", "grip"], "ijnx" => ["jinx"],
      "abgr" => ["brag", "garb", "grab"], "adil" => ["dial", "laid"],
      "dell" => ["dell"], "ehor" => ["hero"], "adnr" => ["darn"],
      "aegu" => ["ague"], "dory" => ["dory"], "ilmo" => ["limo"],
      "affg" => ["gaff"], "glos" => ["slog", "logs"], "agrs" => ["rags"],
      "cloo" => ["loco", "cool"], "aelp" => ["peal", "leap", "pale", "plea"],
      "agll" => ["gall"], "cdko" => ["dock"], "dffu" => ["duff"],
      "eftw" => ["weft"], "dehu" => ["hued"], "lllo" => ["loll"],
      "dnsu" => ["duns"], "chin" => ["chin", "inch"], "imtt" => ["mitt"],
      "notu" => ["unto"], "ipqu" => ["quip"], "eefr" => ["reef", "free"],
      "corw" => ["crow"], "cefh" => ["chef"], "ipty" => ["pity"],
      "dtuy" => ["duty"], "hlow" => ["howl"], "efiv" => ["five"],
      "moor" => ["moor", "room"], "eepw" => ["weep"], "egks" => ["kegs"],
      "iltt" => ["tilt"], "agnw" => ["gnaw"], "akpr" => ["park"],
      "aekr" => ["rake"], "bnru" => ["burn"], "esst" => ["sets"],
      "opru" => ["pour"], "abdr" => ["brad", "bard", "drab"], "inns" => ["inns"],
      "defn" => ["fend"], "oopr" => ["poor"], "elvy" => ["levy"],
      "acnt" => ["cant"], "ehmp" => ["hemp"], "irss" => ["sirs"],
      "aflw" => ["flaw"], "bcku" => ["buck"], "hims" => ["shim", "hims"],
      "ffpu" => ["puff"], "ipsw" => ["wisp"], "fist" => ["fist", "sift", "fits"],
      "aflx" => ["flax"], "ehms" => ["hems", "mesh"], "ggis" => ["gigs"],
      "ammo" => ["ammo"], "ados" => ["soda"], "aprw" => ["warp", "wrap"],
      "eerv" => ["veer", "ever"], "mops" => ["mops"], "gjos" => ["jogs"],
      "horu" => ["hour"], "aawy" => ["away"], "ckmo" => ["mock"],
      "abbl" => ["blab"], "ddee" => ["deed"], "acmr" => ["cram"],
      "aefm" => ["fame"], "floo" => ["fool"],
      "enop" => ["pone", "nope", "peon", "open"], "filo" => ["foil"],
      "ahot" => ["oath"], "aems" => ["mesa", "seam", "same"], "afns" => ["fans"],
      "hllu" => ["hull"], "acdl" => ["clad"], "efsu" => ["fuse"],
      "eitx" => ["exit"], "efmu" => ["fume"], "egiv" => ["give"],
      "ailp" => ["pail"], "egln" => ["glen"], "eesv" => ["eves"],
      "hknu" => ["hunk"], "eegn" => ["gene"], "abks" => ["bask"],
      "fhoo" => ["hoof"], "demn" => ["mend"], "opps" => ["pops"],
      "acss" => ["sacs"], "hpsu" => ["push"], "ailw" => ["wail"],
      "dein" => ["dine"], "ehtw" => ["whet"], "eisv" => ["vies", "vise"],
      "fops" => ["fops"], "aclm" => ["clam", "calm"],
      "eirt" => ["rite", "tier", "tire"], "inss" => ["sins"], "aquy" => ["quay"],
      "ampr" => ["pram", "ramp"], "dfin" => ["find"], "ittw" => ["twit"],
      "korw" => ["work"], "eegk" => ["geek"], "fimr" => ["firm"],
      "deeh" => ["heed"], "host" => ["shot", "host"], "cest" => ["sect"],
      "orsu" => ["sour", "ours"], "eflu" => ["flue", "fuel"], "acdo" => ["coda"],
      "eetw" => ["twee"], "hmpu" => ["hump"], "osty" => ["toys"],
      "acnr" => ["narc"], "eklp" => ["kelp"], "aens" => ["sane"],
      "abtu" => ["abut", "tuba"], "ahsw" => ["haws", "wash"], "iklt" => ["kilt"],
      "deot" => ["dote", "toed"], "elmt" => ["melt"], "jruy" => ["jury"],
      "chow" => ["chow"], "dhin" => ["hind"], "abrs" => ["bras", "bars"],
      "aswy" => ["yaws", "sway", "ways"], "boss" => ["sobs", "boss"],
      "iimn" => ["mini"], "ehik" => ["hike"], "akor" => ["okra"],
      "koot" => ["took"], "acly" => ["clay", "lacy"], "lnoo" => ["loon"],
      "entx" => ["next"], "aaru" => ["aura"], "ceip" => ["epic"],
      "abek" => ["beak", "bake"], "nnou" => ["noun"], "bijs" => ["jibs"],
      "aevw" => ["wave"], "attw" => ["watt"], "astw" => ["swat"],
      "cklo" => ["lock"], "eist" => ["site", "ties"],
      "gory" => ["gyro", "gory", "orgy"],
      "eors" => ["ores", "roes", "rose", "sore"], "bgil" => ["glib"],
      "bsuy" => ["busy", "buys"], "efin" => ["fine"], "gint" => ["ting"],
      "aery" => ["year"], "bcsu" => ["cubs"], "hill" => ["hill"],
      "acmp" => ["camp"], "ckmu" => ["muck"], "allw" => ["wall"],
      "elov" => ["vole", "love"], "eops" => ["peso", "pose"],
      "eelr" => ["leer", "reel"], "eent" => ["teen"], "egrw" => ["grew"],
      "bknu" => ["bunk"], "ackl" => ["lack"], "copr" => ["crop"],
      "crsu" => ["curs"], "kopr" => ["pork"], "attu" => ["taut"],
      "bcos" => ["cobs"], "cemo" => ["come"], "bbos" => ["bobs"],
      "illy" => ["lily"], "bgnu" => ["bung"], "cffu" => ["cuff"],
      "dkor" => ["dork"], "copu" => ["coup"], "nosu" => ["nous", "onus"],
      "aejp" => ["jape"], "bstu" => ["buts", "stub", "tubs", "bust"],
      "oopp" => ["poop"], "birs" => ["ribs"], "ehlm" => ["helm"],
      "aajr" => ["ajar"], "aitw" => ["wait"], "ajrs" => ["jars"],
      "adel" => ["dale", "lade", "deal", "lead"], "bllo" => ["boll"],
      "aerw" => ["ware", "wear"],
      "opst" => ["pots", "opts", "tops", "post", "spot", "stop"],
      "akmo" => ["amok"], "abis" => ["bias"], "ensw" => ["wens", "sewn", "news"],
      "oosw" => ["woos"], "llnu" => ["null"], "answ" => ["swan"],
      "llor" => ["roll"], "deit" => ["tide", "diet", "edit", "tied"],
      "eimn" => ["mien", "mine"], "dksu" => ["dusk"], "ssuw" => ["wuss"],
      "amns" => ["mans"], "iirs" => ["iris"], "dent" => ["dent", "tend"],
      "iknr" => ["rink"], "gruu" => ["guru"], "cors" => ["orcs"],
      "cilo" => ["loci", "coil"], "ghsu" => ["gush", "hugs"], "ahyz" => ["hazy"],
      "dmpu" => ["dump"], "ilov" => ["viol"], "abeu" => ["beau"],
      "firt" => ["rift"], "bmot" => ["tomb"],
      "apst" => ["pats", "spat", "taps", "past"], "noss" => ["sons"],
      "deiw" => ["wide"], "cdis" => ["disc"], "ahlo" => ["halo"],
      "ejll" => ["jell"], "eips" => ["pies"], "impr" => ["prim"],
      "gluy" => ["ugly"], "flru" => ["furl"], "orsw" => ["rows"],
      "dgir" => ["gird", "grid"], "erst" => ["rest"], "lmpu" => ["plum", "lump"],
      "aadt" => ["data"], "osuy" => ["yous"], "begr" => ["berg"],
      "gill" => ["gill"], "ahhs" => ["shah", "hash"], "coos" => ["coos"],
      "aekt" => ["teak", "take"], "gmos" => ["smog"], "dehi" => ["hied", "hide"],
      "alnw" => ["lawn"], "hjno" => ["john"], "eepr" => ["peer"],
      "ipss" => ["piss", "sips"], "defy" => ["defy"], "appu" => ["pupa"],
      "fllu" => ["full"], "eems" => ["seem"], "ilst" => ["silt", "slit", "list"],
      "einw" => ["wine"], "cglo" => ["clog"], "alyz" => ["lazy"],
      "bffu" => ["buff"], "eglu" => ["glue"], "epsw" => ["pews", "spew"],
      "degl" => ["geld"], "bist" => ["bits"], "acns" => ["cans", "scan"],
      "ekns" => ["kens"], "amry" => ["army"], "acep" => ["cape", "pace"],
      "effi" => ["fief", "fife"], "acen" => ["acne", "cane"], "aaer" => ["area"],
      "fgor" => ["frog"], "aenv" => ["nave", "vane"], "afll" => ["fall"],
      "aabs" => ["baas"], "beor" => ["robe", "bore"], "dgoo" => ["good"],
      "eikl" => ["like"], "aelo" => ["aloe"], "efll" => ["fell"],
      "aggn" => ["gang"], "dops" => ["pods"], "cess" => ["secs"],
      "imnx" => ["minx"], "ceru" => ["ecru", "cure"], "ghtu" => ["thug"],
      "mopr" => ["prom", "romp"], "emnu" => ["menu"], "cilp" => ["clip"],
      "anrt" => ["rant"], "eekm" => ["meek"], "celu" => ["clue"],
      "anrw" => ["warn"], "ffir" => ["riff"], "moos" => ["moos"],
      "arzz" => ["razz"], "egos" => ["egos", "goes"], "cmor" => ["corm"],
      "kmru" => ["murk"], "abkr" => ["bark"], "egno" => ["gone"],
      "aisv" => ["visa"], "llmu" => ["mull"], "aalm" => ["lama"],
      "hlru" => ["hurl"], "aers" => ["ares", "eras", "sear", "ears"],
      "glno" => ["long"], "insw" => ["wins"], "lmoo" => ["loom"],
      "norw" => ["worn"], "pssu" => ["sups", "puss"], "ceil" => ["lice"],
      "aglo" => ["goal"], "achk" => ["hack"], "dllo" => ["doll"],
      "nopu" => ["upon"], "ahll" => ["hall"], "gkoo" => ["gook"],
      "elsu" => ["slue"], "amrs" => ["mars", "rams", "arms"],
      "alps" => ["laps", "pals", "slap"], "ehwy" => ["whey"], "fikn" => ["fink"],
      "orty" => ["troy", "tyro"], "city" => ["city"], "eksy" => ["keys"],
      "ilmn" => ["limn"], "acll" => ["call"], "eipw" => ["wipe"],
      "chou" => ["ouch"], "anpt" => ["pant"], "abdl" => ["bald"],
      "epst" => ["pest", "pets", "step"], "denr" => ["nerd", "rend"],
      "botu" => ["bout"], "empr" => ["perm"],
      "inps" => ["nips", "snip", "pins", "spin"], "dmos" => ["mods"],
      "dosu" => ["duos"], "bdin" => ["bind"], "adsw" => ["wads"],
      "ekty" => ["tyke"], "doow" => ["wood"], "lopp" => ["plop"],
      "deim" => ["dime"], "aisx" => ["axis"], "bilp" => ["blip"],
      "eest" => ["tees"], "deen" => ["need"], "chsu" => ["such"],
      "imrs" => ["rims"], "aepv" => ["vape", "pave"], "berw" => ["brew"],
      "elsw" => ["slew"], "adfs" => ["fads"], "imst" => ["mist"],
      "adms" => ["dams", "mads"], "enoz" => ["zone"], "drtu" => ["turd"],
      "ahir" => ["hair"], "csty" => ["cyst"], "almp" => ["palm", "lamp"],
      "mopp" => ["pomp"], "aprt" => ["tarp", "rapt", "part", "trap"],
      "ervy" => ["very"], "airs" => ["airs", "sari"], "cklu" => ["luck"],
      "eosw" => ["woes", "owes"], "akst" => ["task"], "alnu" => ["ulna"],
      "eprt" => ["pert"], "efht" => ["heft"], "abck" => ["back"],
      "eeft" => ["feet"], "cfio" => ["coif"], "nosy" => ["nosy"],
      "istu" => ["suit"], "ghos" => ["gosh", "hogs"], "eeht" => ["thee"],
      "llot" => ["toll"], "akss" => ["asks"],
      "aemn" => ["amen", "mane", "mean", "name"], "fill" => ["fill"],
      "emot" => ["mote", "tome"], "dinw" => ["wind"], "gloo" => ["logo"],
      "eemt" => ["mete", "teem", "meet"], "hmsu" => ["hums", "mush"],
      "eefl" => ["flee", "feel"], "abos" => ["boas"], "ikrs" => ["irks", "risk"],
      "bmos" => ["mobs"], "dpsu" => ["spud"], "eijv" => ["jive"],
      "ahmw" => ["wham"], "psuy" => ["yups"], "cikt" => ["tick"],
      "ahox" => ["hoax"], "hkno" => ["honk"], "bdel" => ["bled"],
      "dint" => ["dint"], "kloy" => ["yolk"], "esxy" => ["sexy"],
      "ably" => ["ably"], "aefk" => ["fake"], "oops" => ["oops"],
      "dfno" => ["fond"], "knot" => ["knot"], "bkno" => ["knob"],
      "aerz" => ["raze"], "ortt" => ["tort", "trot"], "eesx" => ["exes"],
      "dgin" => ["ding"], "epty" => ["type"], "aekp" => ["peak"],
      "booz" => ["bozo"], "osww" => ["wows"], "adkr" => ["dark"],
      "einp" => ["pine"], "glnu" => ["lung"], "fgos" => ["fogs"],
      "gllu" => ["gull"], "adde" => ["dead"], "adew" => ["awed", "wade"],
      "impp" => ["pimp"], "achs" => ["cash"], "gnow" => ["gown"],
      "amrt" => ["tram", "mart"], "ehrs" => ["hers"], "eers" => ["sere", "seer"],
      "eisz" => ["size"], "iprs" => ["rips"], "ehww" => ["whew"],
      "achr" => ["arch", "char"], "klru" => ["lurk"], "adls" => ["lads"],
      "bpru" => ["burp"], "ckor" => ["cork", "rock"], "ikls" => ["ilks", "silk"],
      "dnou" => ["undo"], "cnos" => ["cons"], "ettx" => ["text"],
      "acmo" => ["coma"], "besy" => ["byes"], "oprw" => ["prow"],
      "beet" => ["beet"], "crtu" => ["curt"], "ehnw" => ["when"],
      "afit" => ["fiat"], "ehov" => ["hove"], "ekpr" => ["perk"],
      "cnsy" => ["sync"], "ipps" => ["pips"], "egmr" => ["germ"],
      "loss" => ["sols", "loss"], "dgis" => ["digs"], "adnw" => ["wand", "dawn"],
      "ddeu" => ["dude"], "mssu" => ["muss", "sums"], "eint" => ["tine"],
      "ffim" => ["miff"], "elno" => ["noel", "lone"], "deky" => ["dyke"],
      "ijlt" => ["jilt"], "empt" => ["temp"], "iltw" => ["wilt"],
      "ciky" => ["icky"], "inst" => ["snit", "nits", "tins"], "abrt" => ["brat"],
      "bbmo" => ["bomb"], "eejz" => ["jeez"], "denu" => ["dune", "nude"],
      "bmpu" => ["bump"], "cent" => ["cent"], "adly" => ["lady"],
      "achy" => ["achy"], "ginw" => ["wing"],
      "eilv" => ["veil", "evil", "vile", "live"], "alop" => ["opal"],
      "gpsu" => ["pugs"], "akns" => ["sank"], "dgil" => ["gild"],
      "ceis" => ["ices"], "dilm" => ["mild"], "acln" => ["clan"],
      "gorw" => ["grow"], "adgl" => ["glad"], "glow" => ["glow"],
      "dhlo" => ["hold"], "ikln" => ["kiln", "link"],
      "aepr" => ["pare", "pear", "reap", "rape"], "bpsu" => ["pubs"],
      "gnoo" => ["goon"], "istt" => ["tits"], "ossw" => ["sows"],
      "cdik" => ["dick"], "ehop" => ["hope"], "desw" => ["weds"],
      "ddsu" => ["duds"], "eopx" => ["expo"], "eikm" => ["mike"],
      "acjk" => ["jack"], "ekpt" => ["kept"], "bcmo" => ["comb"],
      "agkw" => ["gawk"], "aeln" => ["lane", "lean"], "glop" => ["glop"],
      "dort" => ["trod"], "most" => ["toms", "most"], "filp" => ["flip"],
      "rstu" => ["rust", "ruts"], "ikny" => ["inky"], "cdku" => ["duck"],
      "adem" => ["mead", "dame", "made"], "alnp" => ["plan"], "ahnt" => ["than"],
      "clot" => ["clot", "colt"], "gnsu" => ["gnus", "snug", "guns", "sung"],
      "aost" => ["oats"], "cdeu" => ["cued"], "eflx" => ["flex"],
      "deow" => ["owed"], "isst" => ["sits"], "deiv" => ["vied", "dive"],
      "ajzz" => ["jazz"], "ders" => ["reds"], "opty" => ["typo"],
      "ehsw" => ["hews"], "bntu" => ["bunt"], "ikst" => ["skit", "kits"],
      "beoo" => ["oboe"], "aegl" => ["gale"], "ehss" => ["shes"],
      "eopr" => ["pore", "rope"], "adex" => ["axed"], "alpw" => ["pawl"],
      "cikr" => ["rick"], "brru" => ["burr"], "fmor" => ["form", "from"],
      "cdos" => ["docs", "cods"], "enps" => ["pens"], "acrw" => ["craw"],
      "gpsy" => ["gyps"], "fttu" => ["tuft"], "ddey" => ["dyed", "eddy"],
      "hoot" => ["hoot"], "aeru" => ["urea"], "efor" => ["fore"],
      "ackr" => ["rack"], "abns" => ["nabs", "bans"], "eort" => ["rote", "tore"],
      "deew" => ["weed"], "abss" => ["bass"], "hksu" => ["husk"],
      "adiv" => ["diva", "avid"], "cilt" => ["clit"], "bdru" => ["drub"],
      "eity" => ["yeti"], "egrs" => ["ergs"], "inty" => ["tiny"],
      "eopt" => ["poet"], "almu" => ["alum", "maul"], "ckoo" => ["cook"],
      "bell" => ["bell"], "ginz" => ["zing"], "abby" => ["baby"],
      "ijnn" => ["jinn"], "aelr" => ["earl", "real"], "deir" => ["dire", "ride"],
      "acgr" => ["crag"], "prsy" => ["spry"], "entv" => ["vent"],
      "morw" => ["worm"], "cist" => ["tics"], "enru" => ["rune"],
      "himw" => ["whim"], "dens" => ["dens", "ends", "send"], "ahrt" => ["hart"],
      "deru" => ["rued", "rude"], "acdi" => ["acid"], "eekl" => ["keel", "leek"],
      "emsu" => ["emus", "muse"], "ansv" => ["vans"], "prru" => ["purr"],
      "ehos" => ["hoes", "hose", "shoe"],
      "enst" => ["nest", "nets", "tens", "sent"], "ellt" => ["tell"],
      "emss" => ["mess"], "aors" => ["oars", "soar"], "ersv" => ["revs"],
      "fino" => ["info"], "ahps" => ["hasp"], "ehnt" => ["then"],
      "adim" => ["amid", "maid"], "optu" => ["pout"], "aotu" => ["auto"],
      "afgs" => ["fags"], "eefs" => ["fees"], "nssu" => ["suns"],
      "adef" => ["fade", "deaf"], "hrsu" => ["rush"], "hoos" => ["shoo"],
      "dipr" => ["drip"], "alno" => ["loan"], "cost" => ["cots", "cost"],
      "actt" => ["tact"], "klsu" => ["sulk"], "ejtu" => ["jute"],
      "ceho" => ["echo"], "hswy" => ["whys"], "boos" => ["boos"],
      "dlos" => ["sold"], "estv" => ["vest", "vets"], "bins" => ["nibs", "bins"],
      "eggs" => ["eggs"], "fopr" => ["prof"], "deoz" => ["doze"],
      "abhs" => ["bash"], "nopy" => ["pony"], "estu" => ["suet"],
      "flow" => ["fowl", "wolf", "flow"], "bcru" => ["curb"], "ckpu" => ["puck"],
      "ackt" => ["tack"], "elst" => ["lest", "lets"], "lppu" => ["pulp"],
      "afrt" => ["fart", "frat", "raft"], "acps" => ["caps"],
      "dopr" => ["prod", "drop"], "filt" => ["flit", "lift"],
      "anry" => ["nary", "yarn"], "adhn" => ["hand"], "iprt" => ["trip"],
      "dirs" => ["rids"], "beoy" => ["obey"], "blot" => ["blot", "bolt"],
      "bruy" => ["ruby", "bury"], "enrw" => ["wren"], "eksw" => ["skew"],
      "dffo" => ["doff"], "ampu" => ["puma"], "abfr" => ["barf"],
      "eglo" => ["loge", "ogle"], "dflo" => ["fold"], "ador" => ["road"],
      "aemz" => ["maze"], "oprt" => ["port"], "abry" => ["bray"],
      "deip" => ["pied"], "artw" => ["wart"], "anpw" => ["pawn"],
      "ceim" => ["mice"], "ginr" => ["grin", "ring"], "eivw" => ["wive", "view"],
      "ckos" => ["sock"], "cnoo" => ["coon"], "cdee" => ["cede"],
      "jlow" => ["jowl"], "cfku" => ["fuck"], "agsw" => ["swag", "wags"],
      "emsw" => ["mews"], "ottu" => ["tout"], "aair" => ["aria"],
      "asss" => ["sass"], "absy" => ["bays"], "adlu" => ["laud", "dual"],
      "ddos" => ["odds"], "abjs" => ["jabs"], "cikw" => ["wick"],
      "cinz" => ["zinc"], "acef" => ["face"], "abgn" => ["bang"],
      "bevy" => ["bevy"], "ekop" => ["poke"], "cchi" => ["chic"],
      "bdir" => ["bird"], "adgs" => ["gads"], "fknu" => ["funk"],
      "amsw" => ["maws", "swam"], "ehis" => ["hies"], "oott" => ["toot"],
      "ffhu" => ["huff"], "ainv" => ["vain"], "afht" => ["haft"],
      "ceko" => ["coke"], "ahmt" => ["math"], "airy" => ["airy"],
      "cntu" => ["cunt"], "aivv" => ["viva"], "hitw" => ["whit", "with"],
      "assw" => ["saws"], "abll" => ["ball"], "illt" => ["lilt", "till"],
      "doss" => ["sods"], "estt" => ["test"], "akny" => ["yank"],
      "acfl" => ["calf"], "bgru" => ["burg", "grub"], "lstu" => ["slut", "lust"],
      "ekot" => ["toke"], "dors" => ["rods"], "ilno" => ["loin", "lion"],
      "deny" => ["deny"], "ailt" => ["tail"], "foru" => ["four"],
      "ffiy" => ["iffy"], "deps" => ["sped"], "nnsu" => ["nuns"],
      "gmsu" => ["gums", "mugs", "smug"], "ilor" => ["roil"],
      "aelw" => ["wale", "weal"], "ailm" => ["mail"], "oosz" => ["zoos"],
      "ells" => ["ells", "sell"], "fotu" => ["tofu"], "ellw" => ["well"],
      "aess" => ["seas"], "ggno" => ["gong"], "abcr" => ["crab"],
      "eprs" => ["reps"], "efrt" => ["fret"], "aclp" => ["clap"],
      "buzz" => ["buzz"], "adei" => ["aide", "idea"], "aesx" => ["axes"],
      "gltu" => ["glut"], "eknu" => ["nuke"], "adlr" => ["lard"],
      "agit" => ["gait"], "dins" => ["dins"], "eess" => ["sees"],
      "eepp" => ["peep"], "apsy" => ["spay", "yaps", "pays"], "abor" => ["boar"],
      "adir" => ["arid", "raid"], "dmoo" => ["doom", "mood"], "crux" => ["crux"],
      "bfis" => ["fibs"], "aefz" => ["faze"], "abnr" => ["barn", "bran"],
      "aenw" => ["anew", "wane", "wean"], "aeks" => ["sake"], "moss" => ["moss"],
      "epru" => ["pure"], "aghn" => ["hang"], "oost" => ["soot"],
      "einn" => ["nine"], "anwy" => ["yawn"], "agnr" => ["rang"],
      "gins" => ["gins", "sing", "sign"], "moot" => ["moot"],
      "apss" => ["asps", "saps", "spas", "pass"], "abgs" => ["gabs", "bags"],
      "bors" => ["orbs", "robs"], "goop" => ["goop"], "dewy" => ["dewy"],
      "akrs" => ["arks"], "foow" => ["woof"], "eimr" => ["rime", "emir", "mire"],
      "ffmu" => ["muff"], "kmsu" => ["musk"], "jknu" => ["junk"],
      "agos" => ["sago"], "losu" => ["soul"], "aknr" => ["nark", "rank"],
      "eknw" => ["knew"], "iknp" => ["pink"], "aceh" => ["ache", "each"],
      "lotv" => ["volt"], "imrt" => ["trim"], "aafr" => ["afar"],
      "akms" => ["mask"], "lpru" => ["purl"], "eipr" => ["pier", "ripe"],
      "ehir" => ["heir", "hire"], "inru" => ["ruin"], "defs" => ["feds"],
      "orst" => ["tors", "rots", "sort"], "borw" => ["brow"], "eloo" => ["oleo"],
      "dlor" => ["lord"], "gnru" => ["rung"], "einr" => ["rein"],
      "eehl" => ["heel"], "foxy" => ["foxy"], "demo" => ["demo", "dome", "mode"],
      "fgoo" => ["goof"], "coot" => ["coot"],
      "ersu" => ["rues", "ruse", "sure", "user"], "bees" => ["bees"],
      "eesw" => ["ewes", "wees"], "ahil" => ["hail"], "adej" => ["jade"],
      "hint" => ["hint", "thin"], "bmow" => ["womb"], "aber" => ["bare", "bear"],
      "cekn" => ["neck"], "gikn" => ["king"], "acpt" => ["pact"],
      "cerw" => ["crew"], "cdor" => ["cord"], "afin" => ["fain"],
      "detu" => ["duet"], "chip" => ["chip"], "eimm" => ["mime"],
      "aklt" => ["talk"], "bhos" => ["bosh", "hobs"], "bosw" => ["bows"],
      "abls" => ["albs", "slab", "labs"], "arvy" => ["vary"], "ipsz" => ["zips"],
      "fhis" => ["fish"], "hotu" => ["thou"], "hops" => ["posh", "hops", "shop"],
      "dgos" => ["dogs", "gods"], "ckno" => ["conk"],
      "bnsu" => ["nubs", "buns", "snub"], "enrt" => ["tern", "rent"],
      "aaln" => ["anal"], "almt" => ["malt"], "fkor" => ["fork"],
      "aegt" => ["gate"], "dehl" => ["held"], "aimm" => ["imam", "maim"],
      "fklo" => ["folk"], "lotu" => ["lout"], "deek" => ["eked"],
      "iloy" => ["oily"], "dilo" => ["idol"], "cino" => ["coin", "icon"],
      "amno" => ["moan"], "entw" => ["newt", "went"], "loow" => ["wool"],
      "cesu" => ["cues"], "ceno" => ["cone", "once"], "glmu" => ["glum"],
      "aelv" => ["vale", "veal"], "eehr" => ["here"], "dils" => ["lids", "slid"],
      "dglo" => ["gold"], "abbe" => ["babe"], "adrw" => ["ward", "draw"]}
    |> Map.get(string_id)
  end

  def valid_ids do
    ["grsu", "ekow", "hstu", "eilw", "eilm", "ilmy", "hloy", "afos", "akln", "gimr",
     "bbes", "intw", "adkn", "gnos", "eflo", "adip", "ilnt", "aetz", "imps", "dhtu",
     "deho", "dehs", "blos", "aegv", "flux", "aees", "irwy", "besw", "iquz", "ilmp",
     "ksuy", "desz", "blow", "aept", "ceht", "gstu", "cefl", "eilt", "apps", "ahow",
     "best", "aesy", "krsu", "bill", "afir", "lnxy", "aeht", "girs", "ekls", "achp",
     "eikt", "kosw", "agnp", "elos", "eert", "aikn", "diks", "ceir", "anst", "emos",
     "agot", "aggo", "ceor", "ahst", "clop", "cikp", "iqtu", "bmsu", "egst", "iklo",
     "amsy", "aelt", "amps", "antw", "aitx", "impw", "eils", "ehlp", "deln", "noxy",
     "dims", "arsw", "foor", "ilot", "aemx", "eekw", "adhr", "amss", "afhl", "adds",
     "ehno", "fssu", "loot", "fuzz", "npuy", "deeg", "ackp", "ahtw", "beit", "ddoo",
     "aklr", "elru", "ikss", "clru", "eoru", "ceps", "dnos", "elns", "hosw", "bfos",
     "deem", "arwy", "beij", "eorw", "elmw", "ansy", "pttu", "bllu", "akmr", "chop",
     "hrtu", "aapp", "denw", "aftw", "gnot", "aprs", "cjko", "agsy", "jlot", "dorw",
     "eims", "agns", "elpy", "hntu", "acev", "pstu", "psst", "eipp", "delw", "noos",
     "fgit", "mosw", "cmsu", "aepx", "desy", "alov", "aalv", "aehr", "bdei", "cdeo",
     "loos", "adry", "diov", "ills", "akos", "efrs", "bboo", "dmru", "aint", "adep",
     "belo", "deis", "iklm", "delo", "anss", "dilw", "imot", "hist", "beuz", "nort",
     "aeps", "ahsy", "orsy", "awxy", "irst", "ftuz", "admn", "cdru", "mstu", "hklu",
     "clow", "allm", "cdlo", "eppr", "abds", "fnot", "afmo", "aceg", "abde", "bdsu",
     "entu", "imnt", "intt", "elms", "biot", "acht", "bety", "ablo", "aegs", "gilt",
     "doru", "ilps", "eopp", "know", "fglu", "ahht", "essu", "elry", "gijs", "dknu",
     "emop", "aknt", "blru", "istz", "bgno", "aelm", "ehmt", "ginp", "egnt", "aeev",
     "enpt", "hmow", "mouv", "dikr", "lmsu", "dlou", "eirs", "afiw", "ilos", "eegs",
     "losw", "aesw", "ejko", "ehmo", "dinr", "einv", "ailn", "gotu", "fort", "eilr",
     "cdsu", "eorz", "mnor", "afgn", "cksu", "behr", "gips", "ahss", "ciru", "knoo",
     "aegw", "ipst", "ainr", "assy", "abin", "illp", "aopt", "fruy", "aegz", "adis",
     "aclo", "cops", "delv", "emmo", "ackw", "acst", "hipt", "eooz", "afnw", "arty",
     "imsw", "adqu", "estz", "agin", "aefl", "efls", "opss", "lowy", "amot", "cdtu",
     "cikk", "adrt", "bclo", "lnoy", "knsu", "eilu", "ttuu", "defl", "koor", "bglo",
     "mmos", "anyz", "aksu", "flou", "bgos", "lops", "aehv", "deop", "osst", "mosu",
     "bkoo", "belu", "aerr", "inow", "dlop", "acdr", "aemr", "cltu", "acrt", "djou",
     "mrsu", "efst", "efiw", "avwy", "astv", "eikp", "abfl", "bhot", "cehk", "ilms",
     "bemr", "acer", "dfnu", "desu", "alor", "ader", "iort", "agst", "aehk", "bdes",
     "depu", "oppr", "agoy", "foot", "denv", "eory", "admp", "adst", "aegr", "lopt",
     "dels", "adlo", "egls", "aorr", "aaqu", "eejr", "gjsu", "hlsu", "dily", "adot",
     "ahkr", "mpsu", "bblu", "amoy", "boor", "cghu", "bdis", "ahoy", "dehr", "mnoo",
     "absw", "aehp", "bhoo", "apry", "alpy", "ostw", "acel", "hisw", "ahrs", "elmo",
     "aflo", "enox", "cehw", "adps", "begs", "dgnu", "amst", "dluy", "allt", "gitw",
     "aims", "chko", "aett", "abim", "afmr", "ainp", "jmpu", "estw", "dnop", "cikl",
     "abes", "beik", "asty", "eovw", "kmno", "anvy", "bent", "adns", "hnsu", "aben",
     "belt", "hoop", "clos", "brsu", "dgru", "ekrt", "degy", "artt", "bjos", "amny",
     "bclu", "ampt", "deer", "epry", "ghhi", "ablm", "deet", "ciss", "egru", "chir",
     "entt", "adet", "elpt", "jost", "inot", "aert", "girt", "ehty", "cein", "ahpr",
     "beer", "eekp", "gisw", "efos", "opsy", "ppsu", "illm", "apsz", "abot", "abbr",
     "bceu", "aagr", "cgos", "dees", "npsw", "dhos", "hhsu", "cllu", "deov", "josy",
     "aggs", "emrt", "cpsu", "aflt", "aesv", "been", "dimn", "aagl", "adhs", "hins",
     "hkoo", "hmot", "cell", "aeft", "hmos", "abem", "frtu", "loop", "eemr", "acip",
     "anps", "eost", "adsy", "ekoy", "ghis", "istw", "aclt", "iknw", "delm", "abdu",
     "cetu", "bcir", "aluu", "nost", "bdoy", "efnr", "glpu", "eilp", "acpr", "beil",
     "ckuy", "ikmn", "delu", "ghnu", "dhot", "knpu", "drsy", "agps", "diqu", "afly",
     "bikl", "deos", "eluy", "dllu", "agmy", "mpru", "errs", "acds", "aels", "oprs",
     "opsu", "film", "bmnu", "ggor", "enno", "deku", "gost", "nosw", "apsw", "alos",
     "cekp", "ejkr", "flot", "adft", "nnoo", "acrs", "dssu", "alst", "adez", "ckop",
     "bttu", "aipt", "enov", "emno", "llop", "eflw", "eelp", "bdeo", "agjs", "gioy",
     "anox", "bdet", "imss", "efir", "ikll", "lllu", "eemm", "hips", "bgsu", "acim",
     "ajsw", "ailv", "adgo", "aelz", "eekn", "aekw", "hilt", "aekl", "ahkn", "ahlu",
     "deno", "ansu", "bimr", "afry", "ejst", "bmoo", "acft", "alwy", "ddei", "aehz",
     "acek", "hnor", "mmsu", "aamm", "agss", "bklu", "nopr", "kopy", "eepv", "ceop",
     "biis", "ahpt", "dirt", "beef", "anov", "llpu", "eghu", "afil", "dlot", "bder",
     "abcs", "abel", "aghs", "lpsu", "betu", "jstu", "bnor", "chik", "osvw", "bdmu",
     "aehy", "alot", "abdn", "frsu", "aekm", "ikps", "eeks", "ostu", "egor", "anno",
     "eorv", "deey", "ahmr", "afnu", "iknt", "ehlo", "ikkn", "notw", "ertu", "abst",
     "astt", "dhis", "ffit", "belw", "adln", "acde", "ally", "bilm", "bcek", "bops",
     "gsuy", "abkn", "lrsu", "eflt", "flop", "oruy", "mooz", "eimt", "ffos", "eels",
     "nrtu", "prsu", "intu", "oort", "llmo", "glsu", "dnow", "dfor", "npsu", "ehiv",
     "almo", "fizz", "agnt", "anor", "ortu", "coop", "afst", "dity", "aest", "afkl",
     "ehpy", "cdek", "beno", "acry", "eswy", "dstu", "ehsu", "ostt", "aijl", "hikt",
     "acks", "emov", "gist", "ikno", "mppu", "berv", "derw", "hmty", "elmu", "ffru",
     "eeps", "celw", "cssu", "illr", "eenv", "cloy", "ikns", "ajms", "amor", "hjos",
     "ajsy", "msuw", "aksy", "irtw", "aces", "bilo", "afln", "agls", "ceiv", "bgir",
     "kstu", "elnt", "ahkw", "chmu", "eins", "cnor", "deef", "aipr", "eesy", "bbis",
     "ahtt", "elor", "aefr", "eirw", "ensy", "nstu", "bosy", "aefs", "bden", "beep",
     "deks", "deep", "agmr", "fgis", "ehll", "adgr", "envy", "acem", "elop", "abet",
     "nrsu", "bouy", "allp", "antu", "acox", "bnoy", "dfoo", "aent", "aclw", "ccko",
     "beru", "eotv", "afgl", "beix", "lost", "eens", "enot", "ahms", "ijno", "abit",
     "aals", "admr", "eott", "door", "hiss", "ceov", "ceot", "abil", "alms", "dhoo",
     "emor", "bhsu", "ablw", "gmsy", "mttu", "bflu", "aklw", "bblo", "illw", "inpt",
     "eltu", "eerw", "hmny", "ahls", "ekpu", "ails", "aemt", "inor", "fost", "aelx",
     "aegp", "aehl", "adiw", "arst", "amrw", "bssu", "cktu", "egps", "hipw", "dery",
     "bdlo", "boot", "acsw", "eejp", "alsw", "dikn", "aimn", "abjm", "aerv", "aovw",
     "eptw", "aden", "cstu", "deft", "ampv", "aiot", "acms", "aops", "acot", "dill",
     "fglo", "bnoo", "ilwy", "abht", "elly", "ipsy", "cosw", "ikms", "elss", "beiv",
     "cdei", "gknu", "lnor", "defu", "firs", "adeg", "eisw", "copy", "ciks", "noot",
     "eiln", "aenp", "addo", "hnos", "efns", "emtu", "fins", "abhl", "aags", "arsy",
     "bdno", "nptu", "inos", "ffgu", "ehns", "epps", "alsy", "ailr", "gilr", "esty",
     "dmor", "aenr", "noty", "aegm", "alss", "dips", "efil", "kloo", "bnos", "eltw",
     "emst", "hopy", "deil", "beir", "aehm", "adeh", "kkoo", "ghin", "aflp", "ceex",
     "aort", "eegl", "iikw", "deor", "eekr", "epsy", "egms", "dost", "lopy", "ahlt",
     "essw", "chit", "ceit", "enos", "cikn", "gipr", "ijnx", "abgr", "adil", "dell",
     "ehor", "adnr", "aegu", "dory", "ilmo", "affg", "glos", "agrs", "cloo", "aelp",
     "agll", "cdko", "dffu", "eftw", "dehu", "lllo", "dnsu", "chin", "imtt", "notu",
     "ipqu", "eefr", "corw", "cefh", "ipty", "dtuy", "hlow", "efiv", "moor", "eepw",
     "egks", "iltt", "agnw", "akpr", "aekr", "bnru", "esst", "opru", "abdr", "inns",
     "defn", "oopr", "elvy", "acnt", "ehmp", "irss", "aflw", "bcku", "hims", "ffpu",
     "ipsw", "fist", "aflx", "ehms", "ggis", "ammo", "ados", "aprw", "eerv", "mops",
     "gjos", "horu", "aawy", "ckmo", "abbl", "ddee", "acmr", "aefm", "floo", "enop",
     "filo", "ahot", "aems", "afns", "hllu", "acdl", "efsu", "eitx", "efmu", "egiv",
     "ailp", "egln", "eesv", "hknu", "eegn", "abks", "fhoo", "demn", "opps", "acss",
     "hpsu", "ailw", "dein", "ehtw", "eisv", "fops", "aclm", "eirt", "inss", "aquy",
     "ampr", "dfin", "ittw", "korw", "eegk", "fimr", "deeh", "host", "cest", "orsu",
     "eflu", "acdo", "eetw", "hmpu", "osty", "acnr", "eklp", "aens", "abtu", "ahsw",
     "iklt", "deot", "elmt", "jruy", "chow", "dhin", "abrs", "aswy", "boss", "iimn",
     "ehik", "akor", "koot", "acly", "lnoo", "entx", "aaru", "ceip", "abek", "nnou",
     "bijs", "aevw", "attw", "astw", "cklo", "eist", "gory", "eors", "bgil", "bsuy",
     "efin", "gint", "aery", "bcsu", "hill", "acmp", "ckmu", "allw", "elov", "eops",
     "eelr", "eent", "egrw", "bknu", "ackl", "copr", "crsu", "kopr", "attu", "bcos",
     "cemo", "bbos", "illy", "bgnu", "cffu", "dkor", "copu", "nosu", "aejp", "bstu",
     "oopp", "birs", "ehlm", "aajr", "aitw", "ajrs", "adel", "bllo", "aerw", "opst",
     "akmo", "abis", "ensw", "oosw", "llnu", "answ", "llor", "deit", "eimn", "dksu",
     "ssuw", "amns", "iirs", "dent", "iknr", "gruu", "cors", "cilo", "ghsu", "ahyz",
     "dmpu", "ilov", "abeu", "firt", "bmot", "apst", "noss", "deiw", "cdis", "ahlo",
     "ejll", "eips", "impr", "gluy", "flru", "orsw", "dgir", "erst", "lmpu", "aadt",
     "osuy", "begr", "gill", "ahhs", "coos", "aekt", "gmos", "dehi", "alnw", "hjno",
     "eepr", "ipss", "defy", "appu", "fllu", "eems", "ilst", "einw", "cglo", "alyz",
     "bffu", "eglu", "epsw", "degl", "bist", "acns", "ekns", "amry", "acep", "effi",
     "acen", "aaer", "fgor", "aenv", "afll", "aabs", "beor", "dgoo", "eikl", "aelo",
     "efll", "aggn", "dops", "cess", "imnx", "ceru", "ghtu", "mopr", "emnu", "cilp",
     "anrt", "eekm", "celu", "anrw", "ffir", "moos", "arzz", "egos", "cmor", "kmru",
     "abkr", "egno", "aisv", "llmu", "aalm", "hlru", "aers", "glno", "insw", "lmoo",
     "norw", "pssu", "ceil", "aglo", "achk", "dllo", "nopu", "ahll", "gkoo", "elsu",
     "amrs", "alps", "ehwy", "fikn", "orty", "city", "eksy", "ilmn", "acll", "eipw",
     "chou", "anpt", "abdl", "epst", "denr", "botu", "empr", "inps", "dmos", "dosu",
     "bdin", "adsw", "ekty", "doow", "lopp", "deim", "aisx", "bilp", "eest", "deen",
     "chsu", "imrs", "aepv", "berw", "elsw", "adfs", "imst", "adms", "enoz", "drtu",
     "ahir", "csty", "almp", "mopp", "aprt", "ervy", "airs", "cklu", "eosw", "akst",
     "alnu", "eprt", "efht", "abck", "eeft", "cfio", "nosy", "istu", "ghos", "eeht",
     "llot", "akss", "aemn", "fill", "emot", "dinw", "gloo", "eemt", "hmsu", "eefl",
     "abos", "ikrs", "bmos", "dpsu", "eijv", "ahmw", "psuy", "cikt", "ahox", "hkno",
     "bdel", "dint", "kloy", "esxy", "ably", "aefk", "oops", "dfno", "knot", "bkno",
     "aerz", "ortt", "eesx", "dgin", "epty", "aekp", "booz", "osww", "adkr", "einp",
     "glnu", "fgos", "gllu", "adde", "adew", "impp", "achs", "gnow", "amrt", "ehrs",
     "eers", "eisz", "iprs", "ehww", "achr", "klru", "adls", "bpru", "ckor", "ikls",
     "dnou", "cnos", "ettx", "acmo", "besy", "oprw", "beet", "crtu", "ehnw", "afit",
     "ehov", "ekpr", "cnsy", "ipps", "egmr", "loss", "dgis", "adnw", "ddeu", "mssu",
     "eint", "ffim", "elno", "deky", "ijlt", "empt", "iltw", "ciky", "inst", "abrt",
     "bbmo", "eejz", "denu", "bmpu", "cent", "adly", "achy", "ginw", "eilv", "alop",
     "gpsu", "akns", "dgil", "ceis", "dilm", "acln", "gorw", "adgl", "glow", "dhlo",
     "ikln", "aepr", "bpsu", "gnoo", "istt", "ossw", "cdik", "ehop", "desw", "ddsu",
     "eopx", "eikm", "acjk", "ekpt", "bcmo", "agkw", "aeln", "glop", "dort", "most",
     "filp", "rstu", "ikny", "cdku", "adem", "alnp", "ahnt", "clot", "gnsu", "aost",
     "cdeu", "eflx", "deow", "isst", "deiv", "ajzz", "ders", "opty", "ehsw", "bntu",
     "ikst", "beoo", "aegl", "ehss", "eopr", "adex", "alpw", "cikr", "brru", "fmor",
     "cdos", "enps", "acrw", "gpsy", "fttu", "ddey", "hoot", "aeru", "efor", "ackr",
     "abns", "eort", "deew", "abss", "hksu", "adiv", "cilt", "bdru", "eity", "egrs",
     "inty", "eopt", "almu", "ckoo", "bell", "ginz", "abby", "ijnn", "aelr", "deir",
     "acgr", "prsy", "entv", "morw", "cist", "enru", "himw", "dens", "ahrt", "deru",
     "acdi", "eekl", "emsu", "ansv", "prru", "ehos", "enst", "ellt", "emss", "aors",
     "ersv", "fino", "ahps", "ehnt", "adim", "optu", "aotu", "afgs", "eefs", "nssu",
     "adef", "hrsu", "hoos", "dipr", "alno", "cost", "actt", "klsu", "ejtu", "ceho",
     "hswy", "boos", "dlos", "estv", "bins", "eggs", "fopr", "deoz", "abhs", "nopy",
     "estu", "flow", "bcru", "ckpu", "ackt", "elst", "lppu", "afrt", "acps", "dopr",
     "filt", "anry", "adhn", "iprt", "dirs", "beoy", "blot", "bruy", "enrw", "eksw",
     "dffo", "ampu", "abfr", "eglo", "dflo", "ador", "aemz", "oprt", "abry", "deip",
     "artw", "anpw", "ceim", "ginr", "eivw", "ckos", "cnoo", "cdee", "jlow", "cfku",
     "agsw", "emsw", "ottu", "aair", "asss", "absy", "adlu", "ddos", "abjs", "cikw",
     "cinz", "acef", "abgn", "bevy", "ekop", "cchi", "bdir", "adgs", "fknu", "amsw",
     "ehis", "oott", "ffhu", "ainv", "afht", "ceko", "ahmt", "airy", "cntu", "aivv",
     "hitw", "assw", "abll", "illt", "doss", "estt", "akny", "acfl", "bgru", "lstu",
     "ekot", "dors", "ilno", "deny", "ailt", "foru", "ffiy", "deps", "nnsu", "gmsu",
     "ilor", "aelw", "ailm", "oosz", "ells", "fotu", "ellw", "aess", "ggno", "abcr",
     "eprs", "efrt", "aclp", "buzz", "adei", "aesx", "gltu", "eknu", "adlr", "agit",
     "dins", "eess", "eepp", "apsy", "abor", "adir", "dmoo", "crux", "bfis", "aefz",
     "abnr", "aenw", "aeks", "moss", "epru", "aghn", "oost", "einn", "anwy", "agnr",
     "gins", "moot", "apss", "abgs", "bors", "goop", "dewy", "akrs", "foow", "eimr",
     "ffmu", "kmsu", "jknu", "agos", "losu", "aknr", "eknw", "iknp", "aceh", "lotv",
     "imrt", "aafr", "akms", "lpru", "eipr", "ehir", "inru", "defs", "orst", "borw",
     "eloo", "dlor", "gnru", "einr", "eehl", "foxy", "demo", "fgoo", "coot", "ersu",
     "bees", "eesw", "ahil", "adej", "hint", "bmow", "aber", "cekn", "gikn", "acpt",
     "cerw", "cdor", "afin", "detu", "chip", "eimm", "aklt", "bhos", "bosw", "abls",
     "arvy", "ipsz", "fhis", "hotu", "hops", "dgos", "ckno", "bnsu", "enrt", "aaln",
     "almt", "fkor", "aegt", "dehl", "aimm", "fklo", "lotu", "deek", "iloy", "dilo",
     "cino", "amno", "entw", "loow", "cesu", "ceno", "glmu", "aelv", "eehr", "dils",
     "dglo", "abbe", "adrw"]
    |> Enum.into(HashSet.new)
  end
end
