defmodule Jumble.ScowlDict.Size50.Length15 do
  def get(string_id) do
    %{"begiiiiilllntty" => ["intelligibility"],
      "bbbbeefgiiilrtt" => ["flibbertigibbet"],
      "cceeehhnoopprss" => ["phosphorescence"],
      "aadeiimoppprrst" => ["misappropriated"],
      "aeeiilmnnsssttt" => ["sentimentalists"],
      "aaccehillrrttuy" => ["architecturally"],
      "aceeiiinqssstuv" => ["acquisitiveness"],
      "ccdeeeeeflnnort" => ["teleconferenced"],
      "ccdeeennooprrss" => ["correspondences"],
      "cceegiinnnnortt" => ["interconnecting"],
      "aacceilrrrrtuux" => ["extracurricular"],
      "aacghillnoooprt" => ["anthropological"],
      "acggiinnooprstt" => ["prognosticating"],
      "aeehiimnnopprss" => ["misapprehension"],
      "aeeiilnoorrstuv" => ["revolutionaries"],
      "aadiiimnnorsstt" => ["administrations"],
      "aciilmnnoosstuy" => ["sanctimoniously"],
      "aaehiilortttuvy" => ["authoritatively"],
      "acdefiiilnnotty" => ["confidentiality"],
      "efgiiilmnoprsvy" => ["oversimplifying"],
      "ceehiimnossssuv" => ["mischievousness"],
      "aaccegiimnrstuv" => ["circumnavigates"],
      "aaaaeiilmnnprrt" => ["parliamentarian"],
      "aiilnooopprrtty" => ["proportionality"],
      "acfiiiilmnopsst" => ["simplifications"],
      "aceilmmnnoprtuy" => ["uncomplimentary"],
      "aabcceiilnpttuy" => ["unacceptability"],
      "cdeeghimnnnopru" => ["uncomprehending"],
      "aceilnnoorrstuv" => ["uncontroversial"],
      "aaeiilnnorrsttt" => ["transliteration"],
      "eegiiimnnprrstt" => ["misinterpreting"],
      "aceeegiillnortt" => ["intercollegiate"],
      "adeeeghinnrssst" => ["nearsightedness"],
      "ccdenooprrsstuu" => ["superconductors"],
      "aaeiimoppprrsst" => ["misappropriates"],
      "accdeeinnnosstu" => ["discountenances"],
      "ceeiimnnopsssuu" => ["impecuniousness"],
      "eiinooppprssstu" => ["presuppositions"],
      "adeeghiimnnpprs" => ["misapprehending"],
      "aaeilnnnossttuy" => ["instantaneously"],
      "aacdeiimnnnoott" => ["decontamination"],
      "aabdeinnsstttuu" => ["unsubstantiated"],
      "cceegiiinnnnnov" => ["inconveniencing"],
      "aaaaghimnoprsst" => ["phantasmagorias"],
      "aefiilmnooprsss" => ["professionalism"],
      "aacinooprrrsstt" => ["procrastinators"],
      "eeghhlnossssttu" => ["thoughtlessness"],
      "aeeiilnnopprtty" => ["plenipotentiary"],
      "aabcdeennprssuu" => ["superabundances"],
      "ccciiimnoprrstu" => ["circumscription"],
      "abeeiiillnrstuv" => ["vulnerabilities"],
      "cceimoooprrrsss" => ["microprocessors"],
      "aeeimnnoopprrtt" => ["reapportionment"],
      "aacdegiimnnnott" => ["decontaminating"],
      "acefiiinnooprst" => ["personification"],
      "adeeimnnorsttuv" => ["undemonstrative"],
      "aeeiinnoprrsttt" => ["interpretations"],
      "adghiinnnostttw" => ["notwithstanding"],
      "aadeiilnopsssty" => ["dispassionately"],
      "chiilorrsstttuu" => ["horticulturists"],
      "aaailnnnoprsttt" => ["transplantation"],
      "aabiinnossstttu" => ["substantiations"],
      "aaeiinnpprrsstt" => ["antiperspirants"],
      "acddeefhiinnrss" => ["disenfranchised"],
      "cegiilmnoprsstu" => ["multiprocessing"],
      "ccciilmnoorstuu" => ["circumlocutions"],
      "aeiillnnnnottuy" => ["unintentionally"],
      "ceeeefinnnnorrt" => ["noninterference"],
      "bceeinorsssttuv" => ["obstructiveness"],
      "cdeeeinnnprstuy" => ["superintendency"],
      "acceeiinnoorsss" => ["concessionaires"],
      "accdeiinnnosstu" => ["discontinuances"],
      "aacfilnnnooortt" => ["confrontational"],
      "bciinoorssstttu" => ["obstructionists"],
      "accdeeilmnorsty" => ["electrodynamics"],
      "aeeggiinorssstt" => ["segregationists"],
      "cdeeeeinnnprstu" => ["superintendence"],
      "deiiinoopprssst" => ["predispositions"],
      "aceeefhimnnnrst" => ["enfranchisement"],
      "bcgiiiiilnorrty" => ["incorrigibility"],
      "aeiilmnnrsstttu" => ["instrumentalist"],
      "accegiilmnnortu" => ["counterclaiming"],
      "acdefiiiinorstv" => ["diversification"],
      "cceeiinnnnoortt" => ["interconnection"],
      "acdiillnnnootuy" => ["unconditionally"],
      "egiilnnnoqstuuy" => ["unquestioningly"],
      "cceeefiinnoorst" => ["confectioneries"],
      "aaaccehilmprstu" => ["pharmaceuticals"],
      "aaceehillnprtty" => ["parenthetically"],
      "aaaacchhillmttw" => ["whatchamacallit"],
      "ddeeeiilnrsstty" => ["disinterestedly"],
      "cddeeeeeinnnprt" => ["interdependence"],
      "acfgiiiilnnnsty" => ["insignificantly"],
      "aeeehilorsttuxy" => ["heterosexuality"],
      "acdeeiilnnorsty" => ["inconsiderately"],
      "acdeegimnorsstu" => ["discouragements"],
      "aceeemnooprsstv" => ["overcompensates"],
      "adeeemnnrsstttu" => ["understatements"],
      "accehiilnorsstt" => ["interscholastic"],
      "adeeffiiinnortt" => ["differentiation"],
      "aeefghinooprrtw" => ["weatherproofing"],
      "beehlooorrssttu" => ["troubleshooters"],
      "acceefiiilnortt" => ["electrification"],
      "aceehhiopprssty" => ["psychotherapies"],
      "acdeefhiinnrsss" => ["disenfranchises"],
      "ceiiinnorrssttu" => ["insurrectionist"],
      "aehhiiopprsstty" => ["physiotherapist"],
      "eeemnopssssttuu" => ["tempestuousness"],
      "accehilmmnopsst" => ["accomplishments"],
      "aacccehiirrsstt" => ["characteristics"],
      "abdiiinnnoorstu" => ["insubordination"],
      "cdegilnnooprrsy" => ["correspondingly"],
      "aacdilmnooprruy" => ["cardiopulmonary"],
      "aaahiiimmnnrstu" => ["humanitarianism"],
      "aacehillmpsttyy" => ["sympathetically"],
      "aceillnoorrstvy" => ["controversially"],
      "accghilllnooory" => ["chronologically"],
      "aadelnoprsttuuy" => ["polyunsaturated"],
      "addegilnnnrstuy" => ["understandingly"],
      "aeehinpppprrssw" => ["whippersnappers"],
      "bhiiiinooprsstt" => ["prohibitionists"],
      "aaeeellmmnprtty" => ["temperamentally"],
      "aeiklmnnoprsstu" => ["unsportsmanlike"],
      "abbcdeilmoosstu" => ["discombobulates"],
      "aabceeghilnnrty" => ["interchangeably"],
      "aceeeinnoorstvv" => ["neoconservative"],
      "abdeggiknnorrsu" => ["groundbreakings"],
      "acceeegilmnortt" => ["electromagnetic"],
      "aacghlloprrstyy" => ["crystallography"],
      "aeiilmnnrstttuy" => ["instrumentality"],
      "aacciillmnosstu" => ["miscalculations"],
      "acceiiilnnoorst" => ["reconciliations"],
      "aefiiiillmnnsty" => ["infinitesimally"],
      "aeeiilmmnnopstt" => ["implementations"],
      "acceiimmnnootux" => ["excommunication"],
      "abcegiiloorsstt" => ["bacteriologists"],
      "aacehiinnostttu" => ["authentications"],
      "acehhiopprsstty" => ["psychotherapist"],
      "aaegiilnnrrsttt" => ["transliterating"],
      "cdeeiiinnsssttv" => ["distinctiveness"],
      "aeeghhlorssstuu" => ["slaughterhouses"],
      "eiiloprrssttuuy" => ["surreptitiously"],
      "adeeehilnprttvy" => ["hyperventilated"],
      "aaceiilnoprsttu" => ["recapitulations"],
      "abeeeillmmnnptu" => ["unimplementable"],
      "aabcfiiillnosty" => ["syllabification"],
      "aceehimmnorsssv" => ["servomechanisms"],
      "aceeiilnnnoqstu" => ["inconsequential"],
      "aceeiilllmnsttu" => ["intellectualism"],
      "adeeeiilmnnrtty" => ["indeterminately"],
      "ceeeflnorrsssuu" => ["resourcefulness"],
      "ahijlnoooprsttu" => ["photojournalist"],
      "aciiillmnopsttu" => ["multiplications"],
      "aghhillmooopstt" => ["ophthalmologist"],
      "ceeiillmnoosstt" => ["tonsillectomies"],
      "aacehillmoprsty" => ["atmospherically"],
      "aeiimnnnorstttu" => ["instrumentation"],
      "bdehiiloorssttt" => ["bloodthirstiest"],
      "aafimnnoorrsstt" => ["transformations"],
      "aeegiinoprrrstt" => ["preregistration"],
      "abdeghiiilnssst" => ["disestablishing"],
      "aaccdegiimnrtuv" => ["circumnavigated"],
      "aeeiiilnssstttx" => ["existentialists"],
      "aeegiinoorrrstt" => ["interrogatories"],
      "aaeiilnoppprrty" => ["inappropriately"],
      "ceeilmnnoorsuuy" => ["unceremoniously"],
      "cciilnnoopssuuy" => ["inconspicuously"],
      "aaabdhimoprssss" => ["ambassadorships"],
      "aacghilmooprsst" => ["pharmacologists"],
      "adeeilmnorsttvy" => ["demonstratively"],
      "aacghillopprtyy" => ["typographically"],
      "aaaaccdiiklllsy" => ["lackadaisically"],
      "abbeiiiilmoprst" => ["improbabilities"],
      "beiiiiilmopssst" => ["impossibilities"],
      "ceeehilmnoprsvy" => ["comprehensively"],
      "abceelnnnoopruu" => ["unpronounceable"],
      "abeiiillnnrtuvy" => ["invulnerability"],
      "aceehillmnnopst" => ["plainclothesmen"],
      "acceiimmnnotuuv" => ["uncommunicative"],
      "acefinrrrssttuu" => ["infrastructures"],
      "aabceilllmoprty" => ["problematically"],
      "aeeeinnoprrsstt" => ["representations"],
      "cdegiiimmnnooss" => ["decommissioning"],
      "cceeinnoosssssu" => ["consciousnesses"],
      "aabeghiiooprstu" => ["autobiographies"],
      "aadeiilnorrrtxy" => ["extraordinarily"],
      "ceiinnnoopprrst" => ["nonprescription"],
      "aeeeimnprrrssuu" => ["supernumeraries"],
      "deiinnorsssstuu" => ["industriousness"],
      "aceeelmnoprstux" => ["counterexamples"],
      "cceeiiinnnossst" => ["inconsistencies"],
      "bcgiiilmooorsst" => ["microbiologists"],
      "aaceehillprttuy" => ["therapeutically"],
      "eeiinnnnnoorttv" => ["nonintervention"],
      "aaeeinoppprrsst" => ["appropriateness"],
      "cciimnnoorssttu" => ["misconstruction"],
      "aaeiilnnosssstt" => ["sensationalists"],
      "achiioprsssstty" => ["astrophysicists"],
      "eeehoopprstttty" => ["phototypesetter"],
      "aacdiiiilnnprss" => ["disciplinarians"],
      "aceiinnoorssttv" => ["conservationist"],
      "acceghilllnooty" => ["technologically"],
      "acegilmnnooorst" => ["conglomerations"],
      "acefgiinnoorrtu" => ["reconfiguration"],
      "adeiimnnoppsstt" => ["disappointments"],
      "addeeeeehllnssv" => ["levelheadedness"],
      "aaciinnooprrstt" => ["procrastination"],
      "cdegiiinnnooprt" => ["preconditioning"],
      "aabcceelnnorstu" => ["counterbalances"],
      "aceehiloorrssst" => ["atherosclerosis"],
      "adgiiilnnoppsty" => ["disappointingly"],
      "aaceiilllnrstuy" => ["unrealistically"],
      "beghilnooorsttu" => ["troubleshooting"],
      "aabbcghiiillopr" => ["bibliographical"],
      "acdeeiinnoorrst" => ["reconsideration"],
      "aacgiillrrsttuu" => ["agriculturalist"],
      "acgiinnoooprstt" => ["prognostication"],
      "aceefiiilmnoptx" => ["exemplification"],
      "cdeefillprsstuy" => ["disrespectfully"],
      "ddeghiiinnsstuu" => ["undistinguished"],
      "accehinnooprrtt" => ["anthropocentric"],
      "ccdeinnoorssttu" => ["deconstructions"],
      "aeilnooopprrtty" => ["proportionately"],
      "accegiimmnnotux" => ["excommunicating"],
      "acceghiillnnosu" => ["hallucinogenics"],
      "abcceiiiilnssty" => ["inaccessibility"],
      "cceinnoorrssttu" => ["reconstructions"],
      "acdefiiiimnnnot" => ["indemnification"],
      "aadeeefhhlnrsst" => ["halfheartedness"],
      "aacgiinnoprrstt" => ["procrastinating"],
      "abceeeilnnoptux" => ["unexceptionable"],
      "aadehiioprrsstt" => ["radiotherapists"],
      "aceehiinppprsst" => ["apprenticeships"],
      "achhimnooopprrt" => ["anthropomorphic"],
      "ccdeennorrsttuu" => ["unreconstructed"],
      "acddiiiiilnstuv" => ["individualistic"],
      "achhiilllooppsy" => ["philosophically"],
      "acdeeemnooprstv" => ["overcompensated"],
      "ceeeeffiinnsstv" => ["ineffectiveness"],
      "ceeeiimnopssttv" => ["competitiveness"],
      "cdeeeinrsssttuv" => ["destructiveness"],
      "aafgiinnorrsttu" => ["transfiguration"],
      "accddeeinnnostu" => ["discountenanced"],
      "adeeegghilmmnrs" => ["sledgehammering"],
      "aabccegiilloort" => ["bacteriological"],
      "acdehiinopssttu" => ["unsophisticated"],
      "aaccdeeknortttu" => ["counterattacked"],
      "ceiiiimnoprssst" => ["impressionistic"],
      "deiiillmnnosstu" => ["disillusionment"],
      "aabccdeelnnortu" => ["counterbalanced"],
      "aabceeeghilnnrt" => ["interchangeable"],
      "abdeghiiilnsstu" => ["distinguishable"],
      "ccddeegilnnnosy" => ["condescendingly"],
      "adeeegilmnnnstt" => ["disentanglement"],
      "aacgilnnoorsttu" => ["congratulations"],
      "aeeillmnnnortvy" => ["environmentally"],
      "acefiiiinnnostt" => ["intensification"],
      "ahijlmnoooprstu" => ["photojournalism"],
      "aaceeghimnoprrt" => ["cinematographer"],
      "aceiilnnnoottvy" => ["conventionality"],
      "eeeinnoprsssttu" => ["pretentiousness"],
      "ddeeegiilnprruv" => ["underprivileged"],
      "aeeeeinprrssttv" => ["representatives"],
      "acginoooprrsstt" => ["prognosticators"],
      "aacdfiiinossstt" => ["dissatisfaction"],
      "eiiloprsssttuuy" => ["superstitiously"],
      "aadeeinnprssstt" => ["antidepressants"],
      "aacdeehinntttuu" => ["unauthenticated"],
      "aeeeghinnoprsst" => ["parthenogenesis"],
      "abeeiiilmnprtty" => ["impenetrability"],
      "aadfghiorrrsttw" => ["straightforward"],
      "abciiiilmnoptty" => ["incompatibility"],
      "adeeffgiiinnrtt" => ["differentiating"],
      "adeegginoprrtuy" => ["daguerreotyping"],
      "accghillloopsyy" => ["psychologically"],
      "aceiiillmpsssty" => ["pessimistically"],
      "cdeiiiinnossttu" => ["discontinuities"],
      "aaabiiiilmnntty" => ["maintainability"],
      "aefilnnnoooprss" => ["nonprofessional"],
      "aacillmnoopttuy" => ["computationally"],
      "cceiilnnoosstuy" => ["conscientiously"],
      "ceeeiloprrsttvy" => ["retrospectively"],
      "eeegiimnnprrsst" => ["misrepresenting"],
      "ceeprrrsssttuuu" => ["superstructures"],
      "aaaeeginnprsstu" => ["septuagenarians"],
      "aacehillmnnopst" => ["plainclothesman"],
      "aacceeinnnorsss" => ["reconnaissances"],
      "acdeeimmnnoorst" => ["recommendations"],
      "aacdgiilnpqrtuu" => ["quadruplicating"],
      "ehinorrssstttuw" => ["trustworthiness"],
      "abbceeijlnnootu" => ["unobjectionable"],
      "aceemnnoooprstu" => ["contemporaneous"],
      "addeeeghnnorssw" => ["wrongheadedness"],
      "aacdeghillmopry" => ["demographically"],
      "aeeglmnnnnoortv" => ["nongovernmental"],
      "aeeehilnprsttvy" => ["hyperventilates"],
      "aaceiiilprrsttu" => ["particularities"],
      "adeiiiiilmrssst" => ["dissimilarities"],
      "deeeinnnosssttu" => ["tendentiousness"],
      "aacegiijknrsttt" => ["straitjacketing"],
      "accciillmooprsy" => ["microscopically"],
      "acdiiinnnoosttu" => ["discontinuation"],
      "aaccfiiilnossst" => ["classifications"],
      "aceehiillmpstuy" => ["euphemistically"],
      "abbcddeilmoostu" => ["discombobulated"],
      "aabeeflnnnorrst" => ["nontransferable"],
      "aaddeeehhnrrsst" => ["hardheartedness"],
      "aaacdeillmnoryy" => ["aerodynamically"],
      "aadiiilnorssttt" => ["traditionalists"],
      "eeeeilprrstttwy" => ["teletypewriters"],
      "adeegiimnnrsttu" => ["underestimating"],
      "aaennorrssstuuy" => ["tyrannosauruses"],
      "aaeiillnnnortty" => ["internationally"],
      "aaaddeginosstuv" => ["disadvantageous"],
      "ahhiilnopprsstt" => ["philanthropists"],
      "aghilnoooprsstt" => ["anthropologists"],
      "aadefilmnnssttu" => ["fundamentalists"],
      "aeeeeilnnprrrtu" => ["entrepreneurial"],
      "adeeehilnooprst" => ["radiotelephones"],
      "aeeeiimnnoprttx" => ["experimentation"],
      "cceinnnoossssuu" => ["unconsciousness"],
      "deeeinnnprssttu" => ["superintendents"],
      "aciilnnoosstttu" => ["constitutionals"],
      "accehiillprrtyy" => ["hypercritically"],
      "eeiiiinnqssstuv" => ["inquisitiveness"],
      "aaceilmnoopssty" => ["compassionately"],
      "aaaiiilmnorsttt" => ["totalitarianism"],
      "cceeeeeflnnorst" => ["teleconferences"]}
    |> Map.get(string_id)
  end

  def valid_ids do
    ["begiiiiilllntty", "bbbbeefgiiilrtt", "cceeehhnoopprss", "aadeiimoppprrst",
     "aeeiilmnnsssttt", "aaccehillrrttuy", "aceeiiinqssstuv", "ccdeeeeeflnnort",
     "ccdeeennooprrss", "cceegiinnnnortt", "aacceilrrrrtuux", "aacghillnoooprt",
     "acggiinnooprstt", "aeehiimnnopprss", "aeeiilnoorrstuv", "aadiiimnnorsstt",
     "aciilmnnoosstuy", "aaehiilortttuvy", "acdefiiilnnotty", "efgiiilmnoprsvy",
     "ceehiimnossssuv", "aaccegiimnrstuv", "aaaaeiilmnnprrt", "aiilnooopprrtty",
     "acfiiiilmnopsst", "aceilmmnnoprtuy", "aabcceiilnpttuy", "cdeeghimnnnopru",
     "aceilnnoorrstuv", "aaeiilnnorrsttt", "eegiiimnnprrstt", "aceeegiillnortt",
     "adeeeghinnrssst", "ccdenooprrsstuu", "aaeiimoppprrsst", "accdeeinnnosstu",
     "ceeiimnnopsssuu", "eiinooppprssstu", "adeeghiimnnpprs", "aaeilnnnossttuy",
     "aacdeiimnnnoott", "aabdeinnsstttuu", "cceegiiinnnnnov", "aaaaghimnoprsst",
     "aefiilmnooprsss", "aacinooprrrsstt", "eeghhlnossssttu", "aeeiilnnopprtty",
     "aabcdeennprssuu", "ccciiimnoprrstu", "abeeiiillnrstuv", "cceimoooprrrsss",
     "aeeimnnoopprrtt", "aacdegiimnnnott", "acefiiinnooprst", "adeeimnnorsttuv",
     "aeeiinnoprrsttt", "adghiinnnostttw", "aadeiilnopsssty", "chiilorrsstttuu",
     "aaailnnnoprsttt", "aabiinnossstttu", "aaeiinnpprrsstt", "acddeefhiinnrss",
     "cegiilmnoprsstu", "ccciilmnoorstuu", "aeiillnnnnottuy", "ceeeefinnnnorrt",
     "bceeinorsssttuv", "cdeeeinnnprstuy", "acceeiinnoorsss", "accdeiinnnosstu",
     "aacfilnnnooortt", "bciinoorssstttu", "accdeeilmnorsty", "aeeggiinorssstt",
     "cdeeeeinnnprstu", "deiiinoopprssst", "aceeefhimnnnrst", "bcgiiiiilnorrty",
     "aeiilmnnrsstttu", "accegiilmnnortu", "acdefiiiinorstv", "cceeiinnnnoortt",
     "acdiillnnnootuy", "egiilnnnoqstuuy", "cceeefiinnoorst", "aaaccehilmprstu",
     "aaceehillnprtty", "aaaacchhillmttw", "ddeeeiilnrsstty", "cddeeeeeinnnprt",
     "acfgiiiilnnnsty", "aeeehilorsttuxy", "acdeeiilnnorsty", "acdeegimnorsstu",
     "aceeemnooprsstv", "adeeemnnrsstttu", "accehiilnorsstt", "adeeffiiinnortt",
     "aeefghinooprrtw", "beehlooorrssttu", "acceefiiilnortt", "aceehhiopprssty",
     "acdeefhiinnrsss", "ceiiinnorrssttu", "aehhiiopprsstty", "eeemnopssssttuu",
     "accehilmmnopsst", "aacccehiirrsstt", "abdiiinnnoorstu", "cdegilnnooprrsy",
     "aacdilmnooprruy", "aaahiiimmnnrstu", "aacehillmpsttyy", "aceillnoorrstvy",
     "accghilllnooory", "aadelnoprsttuuy", "addegilnnnrstuy", "aeehinpppprrssw",
     "bhiiiinooprsstt", "aaeeellmmnprtty", "aeiklmnnoprsstu", "abbcdeilmoosstu",
     "aabceeghilnnrty", "aceeeinnoorstvv", "abdeggiknnorrsu", "acceeegilmnortt",
     "aacghlloprrstyy", "aeiilmnnrstttuy", "aacciillmnosstu", "acceiiilnnoorst",
     "aefiiiillmnnsty", "aeeiilmmnnopstt", "acceiimmnnootux", "abcegiiloorsstt",
     "aacehiinnostttu", "acehhiopprsstty", "aaegiilnnrrsttt", "cdeeiiinnsssttv",
     "aeeghhlorssstuu", "eiiloprrssttuuy", "adeeehilnprttvy", "aaceiilnoprsttu",
     "abeeeillmmnnptu", "aabcfiiillnosty", "aceehimmnorsssv", "aceeiilnnnoqstu",
     "aceeiilllmnsttu", "adeeeiilmnnrtty", "ceeeflnorrsssuu", "ahijlnoooprsttu",
     "aciiillmnopsttu", "aghhillmooopstt", "ceeiillmnoosstt", "aacehillmoprsty",
     "aeiimnnnorstttu", "bdehiiloorssttt", "aafimnnoorrsstt", "aeegiinoprrrstt",
     "abdeghiiilnssst", "aaccdegiimnrtuv", "aeeiiilnssstttx", "aeegiinoorrrstt",
     "aaeiilnoppprrty", "ceeilmnnoorsuuy", "cciilnnoopssuuy", "aaabdhimoprssss",
     "aacghilmooprsst", "adeeilmnorsttvy", "aacghillopprtyy", "aaaaccdiiklllsy",
     "abbeiiiilmoprst", "beiiiiilmopssst", "ceeehilmnoprsvy", "abceelnnnoopruu",
     "abeiiillnnrtuvy", "aceehillmnnopst", "acceiimmnnotuuv", "acefinrrrssttuu",
     "aabceilllmoprty", "aeeeinnoprrsstt", "cdegiiimmnnooss", "cceeinnoosssssu",
     "aabeghiiooprstu", "aadeiilnorrrtxy", "ceiinnnoopprrst", "aeeeimnprrrssuu",
     "deiinnorsssstuu", "aceeelmnoprstux", "cceeiiinnnossst", "bcgiiilmooorsst",
     "aaceehillprttuy", "eeiinnnnnoorttv", "aaeeinoppprrsst", "cciimnnoorssttu",
     "aaeiilnnosssstt", "achiioprsssstty", "eeehoopprstttty", "aacdiiiilnnprss",
     "aceiinnoorssttv", "acceghilllnooty", "acegilmnnooorst", "acefgiinnoorrtu",
     "adeiimnnoppsstt", "addeeeeehllnssv", "aaciinnooprrstt", "cdegiiinnnooprt",
     "aabcceelnnorstu", "aceehiloorrssst", "adgiiilnnoppsty", "aaceiilllnrstuy",
     "beghilnooorsttu", "aabbcghiiillopr", "acdeeiinnoorrst", "aacgiillrrsttuu",
     "acgiinnoooprstt", "aceefiiilmnoptx", "cdeefillprsstuy", "ddeghiiinnsstuu",
     "accehinnooprrtt", "ccdeinnoorssttu", "aeilnooopprrtty", "accegiimmnnotux",
     "acceghiillnnosu", "abcceiiiilnssty", "cceinnoorrssttu", "acdefiiiimnnnot",
     "aadeeefhhlnrsst", "aacgiinnoprrstt", "abceeeilnnoptux", "aadehiioprrsstt",
     "aceehiinppprsst", "achhimnooopprrt", "ccdeennorrsttuu", "acddiiiiilnstuv",
     "achhiilllooppsy", "acdeeemnooprstv", "ceeeeffiinnsstv", "ceeeiimnopssttv",
     "cdeeeinrsssttuv", "aafgiinnorrsttu", "accddeeinnnostu", "adeeegghilmmnrs",
     "aabccegiilloort", "acdehiinopssttu", "aaccdeeknortttu", "ceiiiimnoprssst",
     "deiiillmnnosstu", "aabccdeelnnortu", "aabceeeghilnnrt", "abdeghiiilnsstu",
     "ccddeegilnnnosy", "adeeegilmnnnstt", "aacgilnnoorsttu", "aeeillmnnnortvy",
     "acefiiiinnnostt", "ahijlmnoooprstu", "aaceeghimnoprrt", "aceiilnnnoottvy",
     "eeeinnoprsssttu", "ddeeegiilnprruv", "aeeeeinprrssttv", "acginoooprrsstt",
     "aacdfiiinossstt", "eiiloprsssttuuy", "aadeeinnprssstt", "aacdeehinntttuu",
     "aeeeghinnoprsst", "abeeiiilmnprtty", "aadfghiorrrsttw", "abciiiilmnoptty",
     "adeeffgiiinnrtt", "adeegginoprrtuy", "accghillloopsyy", "aceiiillmpsssty",
     "cdeiiiinnossttu", "aaabiiiilmnntty", "aefilnnnoooprss", "aacillmnoopttuy",
     "cceiilnnoosstuy", "ceeeiloprrsttvy", "eeegiimnnprrsst", "ceeprrrsssttuuu",
     "aaaeeginnprsstu", "aacehillmnnopst", "aacceeinnnorsss", "acdeeimmnnoorst",
     "aacdgiilnpqrtuu", "ehinorrssstttuw", "abbceeijlnnootu", "aceemnnoooprstu",
     "addeeeghnnorssw", "aacdeghillmopry", "aeeglmnnnnoortv", "aeeehilnprsttvy",
     "aaceiiilprrsttu", "adeiiiiilmrssst", "deeeinnnosssttu", "aacegiijknrsttt",
     "accciillmooprsy", "acdiiinnnoosttu", "aaccfiiilnossst", "aceehiillmpstuy",
     "abbcddeilmoostu", "aabeeflnnnorrst", "aaddeeehhnrrsst", "aaacdeillmnoryy",
     "aadiiilnorssttt", "eeeeilprrstttwy", "adeegiimnnrsttu", "aaennorrssstuuy",
     "aaeiillnnnortty", "aaaddeginosstuv", "ahhiilnopprsstt", "aghilnoooprsstt",
     "aadefilmnnssttu", "aeeeeilnnprrrtu", "adeeehilnooprst", "aeeeiimnnoprttx",
     "cceinnnoossssuu", "deeeinnnprssttu", "aciilnnoosstttu", "accehiillprrtyy",
     "eeiiiinnqssstuv", "aaceilmnoopssty", "aaaiiilmnorsttt", "cceeeeeflnnorst"]
    |> Enum.into(HashSet.new)
  end
end
