defmodule Jumble.ScowlDict.Size50.Length3 do
  def get(string_id) do
    %{"abo" => ["boa"], "hot" => ["tho", "hot"], "oow" => ["woo"], "ctu" => ["cut"],
      "afr" => ["far"], "dgu" => ["dug"], "abd" => ["dab", "bad"], "hip" => ["hip"],
      "bgi" => ["big"], "osy" => ["soy"], "imx" => ["mix"], "ikl" => ["ilk"],
      "nru" => ["urn", "run"], "gmy" => ["gym"], "bde" => ["deb", "bed"],
      "lot" => ["lot"], "agj" => ["jag"], "muy" => ["yum"], "ehu" => ["hue"],
      "ehi" => ["hie"], "hnt" => ["nth"], "ajy" => ["jay"], "aey" => ["yea", "aye"],
      "eil" => ["lei", "lie"], "deu" => ["due"], "bil" => ["lib"], "ooz" => ["zoo"],
      "hop" => ["hop"], "nno" => ["non"], "ggi" => ["gig"], "npw" => ["pwn"],
      "ivy" => ["ivy"], "aes" => ["sea"], "mmo" => ["mom"], "fnu" => ["fun"],
      "ewy" => ["yew"], "afn" => ["fan"], "ott" => ["tot"], "cgo" => ["cog"],
      "abl" => ["alb", "lab"], "aft" => ["aft", "fat"], "dop" => ["pod"],
      "cox" => ["cox"], "chi" => ["chi"], "flu" => ["flu"], "ops" => ["sop"],
      "epy" => ["yep"], "tux" => ["tux"], "eit" => ["tie"], "ehr" => ["her"],
      "now" => ["now", "own", "won"], "app" => ["pap"], "acm" => ["cam"],
      "ovw" => ["vow"], "bfi" => ["fib"], "amy" => ["yam", "may"], "atx" => ["tax"],
      "ept" => ["pet"], "psy" => ["spy"], "amt" => ["tam", "mat"],
      "aps" => ["asp", "pas", "sap", "spa"], "itt" => ["tit"], "aly" => ["lay"],
      "bow" => ["bow"], "ddo" => ["odd"], "akr" => ["ark"], "alx" => ["lax"],
      "ell" => ["ell"], "eny" => ["yen"], "dim" => ["mid", "dim"], "beg" => ["beg"],
      "cno" => ["con"], "ajw" => ["jaw"], "opp" => ["pop"], "eeg" => ["gee"],
      "aot" => ["oat"], "est" => ["set"], "aet" => ["eta", "ate", "eat", "tea"],
      "mru" => ["rum"], "orw" => ["row"], "dos" => ["dos", "sod"], "inn" => ["inn"],
      "etw" => ["wet"], "aqu" => ["qua"], "ill" => ["ill"], "dei" => ["die"],
      "oty" => ["toy"], "fop" => ["fop"], "hor" => ["rho"], "den" => ["den", "end"],
      "cit" => ["tic"], "aim" => ["aim"], "itz" => ["zit"], "ilo" => ["oil"],
      "fgo" => ["fog"], "emn" => ["men"], "nsu" => ["sun"], "ilp" => ["lip"],
      "rty" => ["try"], "coo" => ["coo"], "oru" => ["our"], "fot" => ["oft"],
      "ipt" => ["pit", "tip"], "los" => ["sol"], "emu" => ["emu"], "enp" => ["pen"],
      "alw" => ["awl", "law"], "bir" => ["rib"], "cei" => ["ice"],
      "ent" => ["net", "ten"], "mmu" => ["mum"], "eey" => ["eye"],
      "add" => ["dad", "add"], "pry" => ["pry"], "ady" => ["day"], "acp" => ["cap"],
      "ems" => ["ems", "mes"], "def" => ["fed"], "blo" => ["lob"], "ary" => ["ray"],
      "mow" => ["mow"], "bet" => ["bet"], "ads" => ["ads", "sad"], "ego" => ["ego"],
      "eht" => ["the"], "esu" => ["sue", "use"], "bfo" => ["fob"], "ahy" => ["hay"],
      "ast" => ["sat"], "abc" => ["cab"], "eru" => ["rue"], "guy" => ["guy"],
      "efo" => ["foe"], "anr" => ["ran"], "ipr" => ["rip"], "adw" => ["wad"],
      "iwz" => ["wiz"], "agr" => ["rag"], "dir" => ["rid"], "efi" => ["fie"],
      "aor" => ["oar"], "egm" => ["meg", "gem"], "anv" => ["van"],
      "dis" => ["ids", "dis"], "del" => ["led"], "htu" => ["hut"], "ehp" => ["hep"],
      "gju" => ["jug"], "aer" => ["ear", "era", "are"], "bjo" => ["job"],
      "ilt" => ["lit"], "ffo" => ["off"], "aep" => ["ape", "pea"], "dry" => ["dry"],
      "ino" => ["ion"], "oww" => ["wow"], "efr" => ["fer", "ref"], "bmo" => ["mob"],
      "egg" => ["egg"], "bbi" => ["bib"], "boy" => ["boy"], "act" => ["act", "cat"],
      "dot" => ["dot"], "deo" => ["ode", "doe"], "bhu" => ["hub"], "glu" => ["lug"],
      "eno" => ["one"], "eip" => ["pie"], "lsy" => ["sly"], "eev" => ["eve"],
      "amp" => ["amp", "map"], "eow" => ["woe", "owe"], "bey" => ["bye"],
      "moo" => ["moo"], "adt" => ["tad"], "bdu" => ["bud", "dub"], "dnu" => ["dun"],
      "cop" => ["cop"], "ail" => ["ail"], "ekn" => ["ken"],
      "psu" => ["pus", "sup", "ups"], "dor" => ["rod"], "msy" => ["mys"],
      "ant" => ["ant", "tan"], "ajr" => ["jar"], "ikt" => ["kit"], "gjo" => ["jog"],
      "adl" => ["lad"], "dmo" => ["mod"], "hos" => ["hos", "ohs"],
      "bor" => ["orb", "rob"], "bgo" => ["gob", "bog"], "epp" => ["pep"],
      "ehm" => ["meh", "hem"], "bcu" => ["cub"], "mpu" => ["ump"], "iss" => ["sis"],
      "enw" => ["wen", "new"], "aht" => ["hat"], "ist" => ["its", "sit"],
      "dno" => ["nod", "don"], "eho" => ["hoe"], "ams" => ["mas"], "hsy" => ["shy"],
      "anp" => ["nap", "pan"], "ahs" => ["ash", "has"], "osw" => ["sow"],
      "bru" => ["bur", "rub"], "ehs" => ["hes", "she"], "acr" => ["arc", "car"],
      "adh" => ["had"], "etv" => ["vet"], "cis" => ["sic"], "dip" => ["dip"],
      "ako" => ["oak"], "ado" => ["ado"], "esy" => ["yes"], "ehx" => ["hex"],
      "imr" => ["rim"], "kuy" => ["yuk"], "emw" => ["mew"], "imv" => ["vim"],
      "aku" => ["auk"], "adf" => ["fad"], "aby" => ["bay"], "abg" => ["gab", "bag"],
      "agw" => ["wag"], "bit" => ["bit"], "hoo" => ["oho"], "noy" => ["yon"],
      "bnu" => ["nub", "bun"], "hhu" => ["huh"], "cdu" => ["cud"],
      "apy" => ["yap", "pay"], "abr" => ["bra", "bar"], "bbe" => ["ebb"],
      "ikn" => ["kin", "ink"], "dlo" => ["old"], "all" => ["all"], "eet" => ["tee"],
      "coy" => ["coy"], "giw" => ["wig"], "mot" => ["tom"], "eef" => ["fee"],
      "gru" => ["rug"], "efz" => ["fez"], "eky" => ["key"], "fix" => ["fix"],
      "gin" => ["gin"], "buy" => ["buy"], "ipz" => ["zip"], "bos" => ["sob"],
      "iks" => ["ski"], "hmu" => ["hum"], "got" => ["tog", "got"], "aeg" => ["age"],
      "imp" => ["imp"], "eor" => ["ore", "roe"], "ees" => ["see"], "adi" => ["aid"],
      "his" => ["his"], "eir" => ["ire"], "dez" => ["zed"], "dmu" => ["mud"],
      "ipy" => ["yip"], "bho" => ["hob"], "bbo" => ["bob"], "fir" => ["fir"],
      "iln" => ["nil"], "ost" => ["sot"], "agg" => ["gag"], "puy" => ["yup"],
      "ael" => ["lea", "ale"], "emo" => ["emo"], "pxy" => ["pyx"], "fly" => ["fly"],
      "goo" => ["goo"], "int" => ["nit", "tin"], "air" => ["air"], "elm" => ["elm"],
      "cru" => ["cur"], "lop" => ["pol", "lop"], "kow" => ["wok"], "afo" => ["oaf"],
      "not" => ["ton", "not"], "sty" => ["sty"], "any" => ["nay", "any"],
      "gij" => ["jig"], "ely" => ["lye"], "brr" => ["brr"], "abj" => ["jab"],
      "ehn" => ["hen"], "abh" => ["bah"], "opr" => ["pro"], "fry" => ["fry"],
      "ekl" => ["elk"], "aks" => ["ask"], "apt" => ["apt", "pat", "tap"],
      "cor" => ["orc"], "alp" => ["lap", "pal"], "dhi" => ["hid"], "npu" => ["pun"],
      "art" => ["tar", "rat", "art"], "asy" => ["say"], "ceu" => ["cue"],
      "ghu" => ["hug", "ugh"], "bew" => ["web"], "ips" => ["pis", "sip"],
      "cot" => ["cot"], "eot" => ["toe"], "egk" => ["keg"], "agl" => ["gal", "lag"],
      "aab" => ["baa"], "efy" => ["fey"], "hty" => ["thy"], "ptu" => ["put"],
      "rwy" => ["wry"], "emt" => ["met"], "agh" => ["hag"], "asx" => ["sax"],
      "adn" => ["and"], "joy" => ["joy"], "low" => ["owl", "low"], "isx" => ["six"],
      "elt" => ["let"], "abt" => ["bat", "tab"], "fin" => ["fin"], "aew" => ["awe"],
      "ipp" => ["pip"], "hwy" => ["why"], "ddi" => ["did"],
      "opt" => ["opt", "pot", "top"], "itw" => ["wit"], "hit" => ["hit"],
      "bdi" => ["bid"], "agn" => ["nag"], "ins" => ["ins", "sin"], "efw" => ["few"],
      "irs" => ["sir"], "bpu" => ["pub"], "agy" => ["gay"], "jot" => ["jot"],
      "afg" => ["fag"], "att" => ["tat"], "rtu" => ["rut"], "otu" => ["out"],
      "awx" => ["wax"], "egl" => ["gel", "leg"], "fis" => ["ifs"], "acw" => ["caw"],
      "asw" => ["saw", "was"], "acd" => ["cad"], "aah" => ["aha"], "inx" => ["nix"],
      "dew" => ["dew", "wed"], "eer" => ["ere"], "nnu" => ["nun"], "egr" => ["erg"],
      "dil" => ["lid"], "gho" => ["hog"], "ouy" => ["you"], "din" => ["din"],
      "lpy" => ["ply"], "how" => ["how", "who"], "ery" => ["rye"],
      "ags" => ["sag", "gas"], "hmo" => ["ohm"], "ikr" => ["irk"], "egt" => ["get"],
      "amr" => ["mar", "ram", "arm"], "inp" => ["nip", "pin"],
      "dgo" => ["god", "dog"], "nos" => ["son"], "adp" => ["pad"], "ilm" => ["mil"],
      "der" => ["red"], "ehw" => ["hew"], "amw" => ["maw"], "bee" => ["bee"],
      "oot" => ["too"], "fit" => ["fit"], "apw" => ["paw"], "gir" => ["rig"],
      "gip" => ["pig"], "ntu" => ["tun", "nut"], "abn" => ["nab", "ban"],
      "ort" => ["tor", "rot"], "ddu" => ["dud"], "cdo" => ["doc", "cod"],
      "amn" => ["man"], "cry" => ["cry"], "gmu" => ["gum", "mug"], "erv" => ["rev"],
      "eew" => ["ewe", "wee"], "cow" => ["cow"], "ciy" => ["icy"], "bij" => ["jib"],
      "arw" => ["raw", "war"], "mop" => ["mop"], "alm" => ["lam"], "esx" => ["sex"],
      "eep" => ["pee"], "egp" => ["peg"], "box" => ["box"], "aov" => ["ova"],
      "agp" => ["gap"], "cpu" => ["cup"], "dho" => ["hod"], "opx" => ["pox"],
      "bmu" => ["bum"], "ago" => ["ago"], "adm" => ["dam", "mad"], "acn" => ["can"],
      "msu" => ["sum"], "dey" => ["dye"], "dgi" => ["dig"], "esw" => ["sew"],
      "epr" => ["rep", "per"], "lox" => ["lox"], "awy" => ["yaw", "way"],
      "btu" => ["tub", "but"], "dhu" => ["duh"], "aky" => ["yak"], "gpy" => ["gyp"],
      "acs" => ["sac"], "ety" => ["yet"], "gtu" => ["tug", "gut"],
      "eel" => ["eel", "lee"], "eiv" => ["vie"], "evx" => ["vex"], "ajm" => ["jam"],
      "ksy" => ["sky"], "bop" => ["bop"], "ahm" => ["ham"], "iop" => ["poi"],
      "glo" => ["log"], "ejt" => ["jet"], "dik" => ["kid"], "gnu" => ["gnu", "gun"],
      "ppu" => ["pup"], "bgu" => ["bug"], "atv" => ["vat"], "ahw" => ["haw"],
      "nor" => ["nor"], "dou" => ["duo"], "apr" => ["rap", "par"], "fox" => ["fox"],
      "otw" => ["tow", "wot", "two"], "inw" => ["win"], "fgi" => ["fig"],
      "for" => ["fro", "for"], "jtu" => ["jut"], "eek" => ["eke"], "ass" => ["ass"],
      "bco" => ["cob"], "ehy" => ["hey"], "fru" => ["fur"], "bin" => ["nib", "bin"],
      "bsu" => ["sub", "bus"], "him" => ["him"], "apz" => ["zap"], "aiv" => ["via"],
      "efl" => ["elf"], "efn" => ["fen"], "err" => ["err"], "ims" => ["ism", "sim"],
      "ace" => ["ace"], "boo" => ["boo"], "gpu" => ["pug"], "adg" => ["gad"],
      "anw" => ["wan"], "afx" => ["fax"], "agt" => ["tag"], "epw" => ["pew"]}
    |> Map.get(string_id)
  end
end
