defmodule Jumble.ScowlDict.Size50.Length14 do
  def get(string_id) do
    %{"cdeeinoprsstuv" => ["productiveness"],
      "aeeiimnnorsttx" => ["exterminations"],
      "adeeehilnooprt" => ["radiotelephone"],
      "acillmmnnootty" => ["noncommittally"],
      "aceeeglmnorstt" => ["electromagnets"],
      "aaceiillnpstty" => ["antiseptically"],
      "abeeghiilnstux" => ["extinguishable"],
      "adeiiinnoorstt" => ["disorientation"],
      "aaciiilmnoppst" => ["misapplication"],
      "aainnooprrsttt" => ["transportation"],
      "aeegiilnnnrtty" => ["entertainingly"],
      "eeeegggiinnnor" => ["geoengineering"],
      "ccdeeeinnnortt" => ["interconnected"],
      "aeghimmnooprst" => ["metamorphosing"],
      "cddeeilnnostty" => ["discontentedly"],
      "acdeegilnnoqru" => ["grandiloquence"],
      "ceefgiinnorttu" => ["counterfeiting"],
      "acegiillmnoort" => ["terminological"],
      "eeeiilmnopssst" => ["impolitenesses"],
      "elmopprsstuuuy" => ["presumptuously"],
      "aaaeglllmoprrs" => ["parallelograms"],
      "aeegiilmnorsss" => ["generalissimos"],
      "ccdehhillnoors" => ["schoolchildren"],
      "aeegginorrsssu" => ["gregariousness"],
      "aceeghilnorssu" => ["clearinghouses"],
      "aaceghiloorsst" => ["archaeologists"],
      "adeeginnopprrt" => ["preponderating"],
      "acegilmnnooort" => ["conglomeration"],
      "elnoopssstuuuv" => ["voluptuousness"],
      "aceeghillnopry" => ["hypoallergenic"],
      "adeeehhllortwy" => ["wholeheartedly"],
      "abccginnorsttu" => ["subcontracting"],
      "abccnoorrssttu" => ["subcontractors"],
      "efhioopprrssss" => ["professorships"],
      "celmnoopsttuuy" => ["contemptuously"],
      "abdeeiilnnpsss" => ["indispensables"],
      "aceghopprrrsty" => ["cryptographers"],
      "acegghhinooprr" => ["choreographing"],
      "aaiillmnnosttu" => ["multinationals"],
      "aceilnnnnootuv" => ["unconventional"],
      "cceiimnnoopsst" => ["misconceptions"],
      "addeeeffiinrtt" => ["differentiated"],
      "eehiilmnnqrstu" => ["relinquishment"],
      "aacillmopsttyy" => ["asymptotically"],
      "abdeefiiilnntu" => ["unidentifiable"],
      "acfgiinnoorstu" => ["configurations"],
      "acghiiinopsstt" => ["sophisticating"],
      "aaaccillorttuy" => ["autocratically"],
      "accefiiinopsst" => ["specifications"],
      "aacdiilllmopty" => ["diplomatically"],
      "aceehimmnorssv" => ["servomechanism"],
      "aaddegghnrrstu" => ["granddaughters"],
      "aacghillloopty" => ["pathologically"],
      "ceeeioprrssttv" => ["retrospectives"],
      "acdeiinnoorsst" => ["considerations"],
      "abeeiilmnoprss" => ["impressionable"],
      "cceeeeeflnnort" => ["teleconference"],
      "aabcillnooorst" => ["collaborations"],
      "bcdeegiimnnrsu" => ["disencumbering"],
      "ceeeilmnnopsst" => ["incompleteness"],
      "beeinooqssssuu" => ["obsequiousness"],
      "aaceiinnnorrst" => ["reincarnations"],
      "aceeimmnnorstu" => ["incommensurate"],
      "aaccfiiilnorst" => ["clarifications"],
      "accchloopsstuy" => ["staphylococcus"],
      "aeeefghhirsttw" => ["featherweights"],
      "ccdeeennooprrs" => ["correspondence"],
      "aegiinnoopprrt" => ["reapportioning"],
      "adeeeimnrssttu" => ["underestimates"],
      "aadeeinnprsstt" => ["antidepressant"],
      "ceeefinorrsttu" => ["counterfeiters"],
      "aceillnnoosstt" => ["constellations"],
      "aaceehilllptty" => ["telepathically"],
      "aachilnopsssyy" => ["psychoanalysis"],
      "aabcefiiinostt" => ["beatifications"],
      "aeegiimnorsttv" => ["overestimating"],
      "aaeiimoppprrst" => ["misappropriate"],
      "bhiiiinooprstt" => ["prohibitionist"],
      "aacdeeimnnostt" => ["decontaminates"],
      "aeginnorrsssst" => ["transgressions"],
      "aegiinnoorrstt" => ["interrogations"],
      "dgghiiiinnsstu" => ["distinguishing"],
      "aadiiilnorsttt" => ["traditionalist"],
      "cceiillnnosuvy" => ["inconclusively"],
      "acchiilloprtyy" => ["hypocritically"],
      "aeeggiinorsstt" => ["segregationist"],
      "acceehhloorsst" => ["schoolteachers"],
      "efghhlnossttuu" => ["thoughtfulness"],
      "cegiinnorstttu" => ["reconstituting"],
      "aaeginnnprstuu" => ["superannuating"],
      "ccgiilnnnnouvy" => ["unconvincingly"],
      "ehiiooppprrrst" => ["proprietorship"],
      "eeeinnoprssssv" => ["responsiveness"],
      "aaabcehlnoppru" => ["unapproachable"],
      "acdeiiinorsssy" => ["idiosyncrasies"],
      "abcinoooorrrst" => ["corroborations"],
      "ceeefimnnorrst" => ["reinforcements"],
      "aadiimnorrsstt" => ["administrators"],
      "aaaeiiilmprrst" => ["paramilitaries"],
      "aaaccehilmprtu" => ["pharmaceutical"],
      "cdeennooprrsst" => ["correspondents"],
      "aadehiioprrstt" => ["radiotherapist"],
      "aaadeillqrrstu" => ["quadrilaterals"],
      "aabbefggilnrst" => ["flabbergasting"],
      "abdeilmorstuxy" => ["ambidextrously"],
      "aaacehiimmnstt" => ["mathematicians"],
      "cceginnorrsttu" => ["reconstructing"],
      "aeegiinorrsttv" => ["interrogatives"],
      "aacciilmnrsttu" => ["circumstantial"],
      "aaimnnorsstttu" => ["transmutations"],
      "bcdeiilnrsttuy" => ["indestructibly"],
      "aacdeeffgiinnt" => ["decaffeinating"],
      "acefiiilmnostu" => ["emulsification"],
      "acdeghillmooot" => ["methodological"],
      "aeeiilmnnssttt" => ["sentimentalist"],
      "aaceiilnoprttu" => ["recapitulation"],
      "eeeiimnprssssv" => ["impressiveness", "permissiveness"],
      "ceeeegiilnnort" => ["electioneering"],
      "eeeellnnrsssst" => ["relentlessness"],
      "aacciiilmprtty" => ["impracticality"],
      "ccdenooprrstuu" => ["superconductor"],
      "ceeilmnopsssuv" => ["compulsiveness"],
      "bdegiiinrrsttu" => ["redistributing"],
      "acgghiklnosstu" => ["laughingstocks"],
      "aabddeelnnrstu" => ["understandable"],
      "bceeehilmnoprs" => ["comprehensible"],
      "acginoooprrstt" => ["prognosticator"],
      "acdefiiinoottx" => ["detoxification"],
      "adeeeggimnnsst" => ["disengagements"],
      "cdeeeiiinnsssv" => ["indecisiveness"],
      "aaceilnnoorstv" => ["conversational"],
      "ahiimnoprssstt" => ["misanthropists"],
      "abeegiinrssssu" => ["agribusinesses"],
      "aaaeeginnprstu" => ["septuagenarian"],
      "deeiiiilmrstuv" => ["verisimilitude"],
      "cceeinnoopprst" => ["preconceptions"],
      "beegiiilllnntu" => ["unintelligible"],
      "aeeiilmnnsttty" => ["sentimentality"],
      "acgiimmnoorrss" => ["microorganisms"],
      "accefiiinorstt" => ["rectifications", "certifications"],
      "eeehiinprsstvy" => ["hypersensitive"],
      "aadddeeehhnrss" => ["hardheadedness"],
      "beeinoorsssstu" => ["boisterousness"],
      "giiinnooopprst" => ["propositioning"],
      "aefillnooprssy" => ["professionally"],
      "aacfinorssttuy" => ["unsatisfactory"],
      "aacchilllossty" => ["scholastically"],
      "aciinnoprrsstt" => ["transcriptions"],
      "aadeiiimnrsttv" => ["administrative"],
      "aceeinoorrsstv" => ["conservatories"],
      "aaahiinorrsttu" => ["authoritarians"],
      "aaceeinnprrsst" => ["transparencies"],
      "bdiiiiiilnstvy" => ["indivisibility"],
      "aabcdeginorrst" => ["rebroadcasting"],
      "aacegillloopty" => ["apologetically"],
      "acceinoopprstu" => ["preoccupations"],
      "aaiimnoopprstx" => ["approximations"],
      "cceghiklnosttu" => ["shuttlecocking"],
      "aeiiilnnrsttvy" => ["intransitively"],
      "efggiiinnnprrt" => ["fingerprinting"],
      "aaaiinnossssst" => ["assassinations"],
      "ddeehinnorrsuu" => ["undernourished"],
      "ceeehimnoprssv" => ["comprehensives"],
      "aaceinoprrsstt" => ["procrastinates"],
      "aacfgiiimnnost" => ["magnifications"],
      "aaceghilllmpty" => ["phlegmatically"],
      "cceeeffiiiinns" => ["inefficiencies"],
      "abcchhiioprrss" => ["archbishoprics"],
      "ceeilmnossstuu" => ["meticulousness"],
      "aeeiiilmnssttx" => ["existentialism"],
      "bdehiiloorrstt" => ["bloodthirstier"],
      "aiinnooprssstt" => ["transpositions"],
      "accehilmmnopst" => ["accomplishment"],
      "abenoorrssstuu" => ["brontosauruses"],
      "aadeeilnrrsttt" => ["transliterated"],
      "cceelnorrttuuu" => ["counterculture"],
      "ceiilnnnosstty" => ["inconsistently"],
      "cdeinoooprrtuv" => ["overproduction"],
      "aeeegginrssssv" => ["aggressiveness"],
      "aaaccdilorrsuv" => ["cardiovascular"],
      "acdeeghiinnruv" => ["underachieving"],
      "aeeeeinprrsttv" => ["representative"],
      "abdeggiknnorru" => ["groundbreaking"],
      "aabeghiiilnrtt" => ["rehabilitating"],
      "cceeeiinnnnosv" => ["inconveniences"],
      "addeimnnrssstu" => ["misunderstands"],
      "acdeefhiinnrss" => ["disenfranchise"],
      "adeeghhillrtty" => ["lightheartedly"],
      "aceiiiilnpprst" => ["principalities"],
      "acceemnorrsstt" => ["concertmasters"],
      "aaggiilnnosttu" => ["agglutinations"],
      "aaceklnnorstuy" => ["cantankerously"],
      "aacfgilnnoorst" => ["conflagrations"],
      "aiijnoopssttux" => ["juxtapositions"],
      "aaceeinrsstttv" => ["attractiveness"],
      "acdiilnooorsst" => ["discolorations"],
      "aacdeimnnnottu" => ["uncontaminated"],
      "eegilmooorsstt" => ["meteorologists"],
      "aeeiilmmnnoptt" => ["implementation"],
      "aceiiinopprstt" => ["precipitations"],
      "aacehiinnotttu" => ["authentication"],
      "ceemopprrsstuu" => ["supercomputers"],
      "chiilorrstttuu" => ["horticulturist"],
      "addeeeeghlmmrs" => ["sledgehammered"],
      "acdeiiilnnortu" => ["unidirectional"],
      "acdegimnnnortu" => ["countermanding"],
      "aceiiillmpttuv" => ["multiplicative"],
      "aacdgiiinnosst" => ["diagnosticians"],
      "acceeimmnostux" => ["excommunicates"],
      "aaceghimnoprty" => ["cinematography"],
      "ccciilmnoortuu" => ["circumlocution"],
      "ceeiimnnoopttv" => ["noncompetitive"],
      "aaailnnnorsstt" => ["transnationals"],
      "aehimnnoorsssu" => ["harmoniousness"],
      "aehhiilnopprst" => ["philanthropies"],
      "abeeehlnrsssst" => ["breathlessness"],
      "aiiimnooprsstv" => ["improvisations"],
      "ceeehimorsstty" => ["hysterectomies"],
      "acccgiimnnrstu" => ["circumstancing"],
      "adeggiiinnrstt" => ["disintegrating"],
      "eeeinopssssssv" => ["possessiveness"],
      "cddeeiinnooprt" => ["preconditioned"],
      "abcdeeehiilnpr" => ["indecipherable"],
      "aacdeiiilllsty" => ["idealistically"],
      "aaceeffilnotty" => ["affectionately"],
      "aehimoopppsstu" => ["hippopotamuses"],
      "aabcciilnottuy" => ["accountability"],
      "acceiinoprsssu" => ["capriciousness"],
      "ceemnnnooprstu" => ["pronouncements"],
      "acdeeimmnnoort" => ["recommendation"],
      "aacffiiilnosst" => ["falsifications"],
      "abdeehiilsssst" => ["disestablishes"],
      "aeiinoopprrstx" => ["expropriations"],
      "bdgggiillmnnoy" => ["mindbogglingly"],
      "acefinrrrsttuu" => ["infrastructure"],
      "achiioprssstty" => ["astrophysicist"],
      "aafimnnoorrstt" => ["transformation"],
      "diiiinnoopssst" => ["indispositions"],
      "aabdeeehhirrss" => ["haberdasheries"],
      "aeeemnorsstttv" => ["overstatements"],
      "aeehinpppprrsw" => ["whippersnapper"],
      "accdeiillnnoty" => ["coincidentally"],
      "aaceiinoprrstv" => ["prevarications"],
      "eeegiinnprrrtt" => ["reinterpreting"],
      "abeelnnnorrstu" => ["nonreturnables"],
      "aacdeinoprrstt" => ["procrastinated"],
      "cdelmnnoooosty" => ["monocotyledons"],
      "acddeegklnnouw" => ["unacknowledged"],
      "ciinnooorssttt" => ["contortionists"],
      "aaaegiiilmnrst" => ["egalitarianism"],
      "aacdeeijkrsttt" => ["straitjacketed"],
      "acdeeeiosssttv" => ["videocassettes"],
      "abeeilmnnnostu" => ["unmentionables"],
      "adeeehimrsssst" => ["headmistresses"],
      "aaacceghilloor" => ["archaeological"],
      "aaadeglnostuvy" => ["advantageously"],
      "eiilnoorssttuv" => ["revolutionists"],
      "aabbeiillosssu" => ["bouillabaisses"],
      "bcdeeiilnrsttu" => ["indestructible"],
      "cgiiilmnoorsst" => ["criminologists"],
      "acegiilnossttu" => ["gesticulations"],
      "aceghlnnnoooty" => ["nanotechnology"],
      "aeillmnosstuuy" => ["simultaneously"],
      "cceimoooprrrss" => ["microprocessor"],
      "abeeeinorrrstv" => ["reverberations"],
      "acdeeennopprrs" => ["preponderances"],
      "aacdeglmnnorss" => ["scandalmongers"],
      "aaceghiinntttu" => ["authenticating"],
      "acceeiinnoorss" => ["concessionaire"],
      "beeehillmmnsst" => ["embellishments"],
      "acfgiiiinnosst" => ["significations"],
      "abcdenooorrrtu" => ["uncorroborated"],
      "aaacehimoopprs" => ["pharmacopoeias"],
      "achiiinoopsstt" => ["sophistication"],
      "aefiiiilmnnsst" => ["infinitesimals"],
      "cdeiiinnnssstt" => ["indistinctness"],
      "abcegiiloorstt" => ["bacteriologist"],
      "ceeeiooprrttvv" => ["overprotective"],
      "cdeeiiinnsstvv" => ["vindictiveness"],
      "adeeiinnoprstt" => ["predestination"],
      "acdeegimnorstu" => ["discouragement"],
      "begilnorsssuuu" => ["lugubriousness"],
      "aadeegimnnrrst" => ["disarrangement"],
      "acdeeeimnoppst" => ["appendectomies"],
      "ccdeiinnnoosst" => ["disconnections"],
      "deeeeillmmosss" => ["mesdemoiselles"],
      "ghiilnooorsstt" => ["ornithologists"],
      "acdiiiilnnnost" => ["disinclination"],
      "aacceknorstttu" => ["counterattacks"],
      "ceiinoprsssstu" => ["percussionists"],
      "cegiiknnnorstu" => ["countersinking"],
      "aabceenrsssstt" => ["abstractnesses"],
      "aaehiiimnnsstt" => ["antihistamines"],
      "ceefiinnossstu" => ["infectiousness"],
      "acfinnnooorstt" => ["confrontations"],
      "acffiiinoorstt" => ["fortifications"],
      "ccefllnsssuuuy" => ["unsuccessfully"],
      "acceehilmoprst" => ["petrochemicals"],
      "accdhhinooprsy" => ["hypochondriacs"],
      "aeffhilnnsstuu" => ["unfaithfulness"],
      "aaeilnooprsttx" => ["extrapolations"],
      "aeeeinnoprrstt" => ["representation"],
      "aeeiilnnorrstt" => ["interrelations"],
      "accceillnnorty" => ["concentrically"],
      "acdeeenrrrstuy" => ["undersecretary"],
      "aaiinooppprrst" => ["appropriations"],
      "aeiimnnooprsst" => ["impersonations"],
      "cceeiinnossttu" => ["constituencies"],
      "beeeimmnrrsstu" => ["reimbursements"],
      "abeeghiilnrsst" => ["reestablishing"],
      "abbeghiiiloprs" => ["bibliographies"],
      "deehhnorrsstuw" => ["thundershowers"],
      "aeegiimnnnortu" => ["mountaineering"],
      "acceinnnoorstt" => ["concentrations"],
      "aaccegiimnrtuv" => ["circumnavigate"],
      "acehiinnssttuu" => ["unenthusiastic"],
      "abclllnnoortuy" => ["uncontrollably"],
      "acdehhiimoprrt" => ["hermaphroditic"],
      "eeeilnoprssssx" => ["expressionless"],
      "aceeeeinnrrstt" => ["tercentenaries"],
      "aabcdeennprsuu" => ["superabundance"],
      "aabcefgiinprrt" => ["prefabricating"],
      "accinprssttuuu" => ["acupuncturists"],
      "aaceeghnooprrs" => ["oceanographers"],
      "adeeeffiinrstt" => ["differentiates"],
      "acfiiilnostttu" => ["stultification"],
      "aabcefiiinottu" => ["beautification"],
      "aeegiiilrrrstu" => ["irregularities"],
      "aacinooprrrstt" => ["procrastinator"],
      "ceiiiillmpsttu" => ["multiplicities"],
      "ddeeeeinnnprtt" => ["interdependent"],
      "abcdeeehilnpru" => ["undecipherable"],
      "aaabdhimoprsss" => ["ambassadorship"],
      "adeeegoprrstuy" => ["daguerreotypes"],
      "aacghilmooprst" => ["pharmacologist"],
      "acfgiilmnnnotu" => ["malfunctioning"],
      "abbcdeilmoostu" => ["discombobulate"],
      "cfimnnnooorsst" => ["nonconformists"],
      "aciiiilprssttu" => ["spiritualistic"],
      "ccceeeiiinrstt" => ["eccentricities"],
      "addeeegoprrtuy" => ["daguerreotyped"],
      "aeeeiinprrtttv" => ["interpretative"],
      "eefiiilmoprssv" => ["oversimplifies"],
      "deefiiilmoprsv" => ["oversimplified"],
      "adeiimnnoppstt" => ["disappointment"],
      "aeeeiiinnprstt" => ["penitentiaries"],
      "aeeiinnoprrttt" => ["interpretation"],
      "aabdeiikmnorst" => ["disembarkation"],
      "aceillnnnootvy" => ["conventionally"],
      "ceeghinorsttuw" => ["counterweights"],
      "dddeeeelnopruv" => ["underdeveloped"],
      "acdeefinnoorst" => ["confederations"],
      "accefgiiiinnns" => ["insignificance"],
      "aacehiillnttty" => ["antithetically"],
      "aeeeillmnprtxy" => ["experimentally"],
      "abcceilnnnoosu" => ["unconscionable"],
      "aadefgghinnrrt" => ["grandfathering"],
      "aabchilooprstu" => ["claustrophobia"],
      "aaabcehilllpty" => ["alphabetically"],
      "aabcefiinoprrt" => ["prefabrication"],
      "aachlnopssstyy" => ["psychoanalysts"],
      "ccdeeeiinnnnov" => ["inconvenienced"],
      "aacglnoorrttuy" => ["congratulatory"],
      "aabeiiilnprsty" => ["inseparability"],
      "aeeehilnprttvy" => ["hyperventilate"],
      "ceeiinnorrsttv" => ["nonrestrictive"],
      "aacciillmnostu" => ["miscalculation"],
      "aillnooopprrty" => ["proportionally"],
      "aaeiilnnossstt" => ["sensationalist"],
      "aaeeilnnprrtty" => ["interplanetary"],
      "aeeghhlorsstuu" => ["slaughterhouse"],
      "aacegghillopry" => ["geographically"],
      "behiiiinossttx" => ["exhibitionists"],
      "afiiimmnnoorst" => ["misinformation"],
      "adeeeimnrssttv" => ["advertisements"],
      "abcdeeiilnnors" => ["inconsiderable"],
      "aaeiilmnnossst" => ["sensationalism"],
      "beeeillnorsssu" => ["rebelliousness"],
      "aabcdeeinrrstt" => ["scatterbrained"],
      "aacdeelnnnrstt" => ["transcendental"],
      "bccilnoosssuuy" => ["subconsciously"],
      "accdeeinnnostu" => ["discountenance"],
      "deeeelmnoprstv" => ["redevelopments"],
      "acdeiiiimnnrst" => ["indiscriminate"],
      "eehiinoopssttv" => ["photosensitive"],
      "aceehiinppprst" => ["apprenticeship"],
      "aceinnnooooprt" => ["noncooperation"],
      "acdiilnnooosst" => ["consolidations"],
      "aceeghhooprrrs" => ["choreographers"],
      "aaeiilnnnorstt" => ["internationals"],
      "aaciilnooprrst" => ["conspiratorial"],
      "aeilnooopprtuv" => ["overpopulation"],
      "adiiilnrsssttu" => ["industrialists"],
      "adegilmoorsstt" => ["dermatologists"],
      "aabehiiilnortt" => ["rehabilitation"],
      "eeghillmnorvwy" => ["overwhelmingly"],
      "acehilmoprsstt" => ["thermoplastics"],
      "beefhimnrrsstu" => ["refurbishments"],
      "ccehhiinoprssz" => ["schizophrenics"],
      "aacceinnnoostt" => ["concatenations"],
      "aaceillmmrstyy" => ["asymmetrically"],
      "aaeemnnopprsww" => ["newspaperwoman"],
      "abefllnoopsstu" => ["tablespoonfuls"],
      "aaeeegmnnrrrst" => ["rearrangements"],
      "aeegillmnorrst" => ["steamrollering"],
      "adfiiimnnoorst" => ["disinformation"],
      "aadefilmnnsttu" => ["fundamentalist"],
      "aegiiinnossttv" => ["investigations"],
      "acdggiilnorsuy" => ["discouragingly"],
      "aabegilmnrrssy" => ["embarrassingly"],
      "ccceiimmnooors" => ["microeconomics"],
      "aacddeeimnnott" => ["decontaminated"],
      "abegiiilmnprty" => ["impregnability"],
      "aciiillmnopttu" => ["multiplication"],
      "cgiimmnnooprsu" => ["uncompromising"],
      "addeeehimnpprs" => ["misapprehended"],
      "aeeiilmmnnsstt" => ["sentimentalism"],
      "aceegillnoprtt" => ["electroplating"],
      "cehilmoorsssst" => ["schoolmistress"],
      "deeegiimnnprrt" => ["predetermining"],
      "aaccfiiilnosst" => ["classification"],
      "acfiiijnossttu" => ["justifications"],
      "acceehiiilnstt" => ["technicalities"],
      "abcdeiiilprtty" => ["predictability"],
      "aabeghiklnrtty" => ["breathtakingly"],
      "ccdeimnoorsstu" => ["semiconductors"],
      "aefilnnooprssu" => ["unprofessional"],
      "acdiiijlnorstu" => ["jurisdictional"],
      "aeeemnooprstux" => ["extemporaneous"],
      "cdeiilnorsssuu" => ["ridiculousness"],
      "bceiiilpssttuy" => ["susceptibility"],
      "aaaaghimnoprst" => ["phantasmagoria"],
      "aeeiiilnopsttt" => ["potentialities"],
      "aeghiilnnsttuy" => ["unhesitatingly"],
      "accefiiillnsty" => ["scientifically"],
      "aceehmnopprrst" => ["rapprochements"],
      "eeeiopprrrssst" => ["proprietresses"],
      "cddeeiimmnooss" => ["decommissioned"],
      "adeeemnnrstttu" => ["understatement"],
      "ceffiiilnnstuy" => ["insufficiently"],
      "aaccfiiinnostt" => ["sanctification"],
      "accdeeilmnortu" => ["counterclaimed"],
      "bbciiilmosttuy" => ["combustibility"],
      "aaeelnnnpssstu" => ["unpleasantness"],
      "abdeeeiilmnnrt" => ["indeterminable"],
      "aacceimmnnopst" => ["accompaniments"],
      "adgiilllnnotuy" => ["longitudinally"],
      "aceginooprsstt" => ["prognosticates"],
      "acdfiiiilnoost" => ["solidification"],
      "acceeilllnorty" => ["electronically"],
      "aaccceeiillsst" => ["ecclesiastical"],
      "acdiiiimnnorst" => ["discrimination"],
      "acdefiillnnoty" => ["confidentially"],
      "aceeemnooprstv" => ["overcompensate"],
      "ceehhnoopprsst" => ["phosphorescent"],
      "aaceiimmossttu" => ["semiautomatics"],
      "ddeeiilnorrsss" => ["disorderliness"],
      "eeghilnoprrstu" => ["reupholstering"],
      "aagiimnnorrstt" => ["transmigration"],
      "accegiilnrtuxy" => ["excruciatingly"],
      "aaccdeillmorty" => ["democratically"],
      "accceeelnnossv" => ["convalescences"],
      "aacfiilorsstty" => ["satisfactorily"],
      "ccdeinnoorsttu" => ["deconstruction"],
      "aacfiiilnoqstu" => ["qualifications"],
      "bdeiiorrrssttu" => ["redistributors"],
      "addeeeimnrsttu" => ["underestimated"],
      "aacegiilnprttu" => ["recapitulating"],
      "aceiiiilmnpstu" => ["municipalities"],
      "abiiiillmpstuy" => ["implausibility"],
      "acefiiilprstuy" => ["superficiality"],
      "aceiilnossssuv" => ["lasciviousness"],
      "addeeeimnprttu" => ["unpremeditated"],
      "defgiiiimnnsty" => ["misidentifying"],
      "aeeinoqrsssttu" => ["sequestrations"],
      "aacehiillmrtty" => ["arithmetically"],
      "aceeelmnoprtux" => ["counterexample"],
      "abceeeefnrssst" => ["benefactresses"],
      "adeimnnoorsstt" => ["demonstrations"],
      "cdegiiinnnoort" => ["reconditioning"],
      "aaceeiilpprtvy" => ["appreciatively"],
      "aciilllmooqssu" => ["colloquialisms"],
      "aacillmnoorsty" => ["astronomically"],
      "bdeehlooorsttu" => ["troubleshooted"],
      "aaceggilnnoort" => ["congregational"],
      "acdeillnoossty" => ["disconsolately"],
      "ceiijnooprsstt" => ["projectionists"],
      "aabciiilnrttty" => ["intractability"],
      "acceilmmnnoors" => ["noncommercials"],
      "eeimnorsssstuy" => ["mysteriousness"],
      "eeeeinprssssvx" => ["expressiveness"],
      "acdehimmnorsty" => ["thermodynamics"],
      "aaaddggiinnstv" => ["disadvantaging"],
      "aabcegiknqrrtu" => ["quarterbacking"],
      "aaaccgiiinnptt" => ["incapacitating"],
      "aegilnoopprtuv" => ["overpopulating"],
      "ceehimnnooprss" => ["comprehensions"],
      "aeeemnnopprsww" => ["newspaperwomen"],
      "addiiiilnsstuv" => ["individualists"],
      "accdiinnoorstt" => ["contradictions"],
      "aacdeilpqrstuu" => ["quadruplicates"],
      "aceinnnoorsttv" => ["contraventions"],
      "cdeiloorsstuuy" => ["discourteously"],
      "aeeegillnssttv" => ["televangelists"],
      "aeiilnnooprstt" => ["interpolations"],
      "aacdeiilnorstv" => ["valedictorians"],
      "ceeiilnnnnotvy" => ["inconveniently"],
      "ceginrrrssttuu" => ["restructurings"],
      "begiiilllnntuy" => ["unintelligibly"],
      "ahhiilnopprstt" => ["philanthropist"],
      "aaccehhiillrry" => ["hierarchically"],
      "deeeinnnprsttu" => ["superintendent"],
      "cceeinooprsssu" => ["precociousness"],
      "eiiimnoprsssst" => ["impressionists"],
      "ceeeeinpprsstv" => ["perceptiveness"],
      "acdeeehinrrsuv" => ["underachievers"],
      "acdeeilnpprrsu" => ["perpendiculars"],
      "deefgiimnrsstu" => ["disfigurements"],
      "aeeefillnprrty" => ["preferentially"],
      "acefgiiinnortt" => ["gentrification"],
      "aghilnoooprstt" => ["anthropologist"],
      "aceeilmnopsttv" => ["contemplatives"],
      "aabcceelnnortu" => ["counterbalance"],
      "aaacehillmmtty" => ["mathematically"],
      "aacilllnorstuy" => ["ultrasonically"],
      "aeeiinnoqrsstu" => ["questionnaires"],
      "aaeeilnrrssttt" => ["transliterates"],
      "aaccdimmnooost" => ["accommodations"],
      "ehiorrssttttuw" => ["trustworthiest"],
      "deiiinoopprsst" => ["predisposition"],
      "ceeprrrssttuuu" => ["superstructure"],
      "abdeiiilnrstuy" => ["undesirability"],
      "aacdgiiinossst" => ["disassociating"],
      "aabddelnnrstuy" => ["understandably"],
      "abeehilmnssstt" => ["establishments"],
      "bcgiiilmooorst" => ["microbiologist"],
      "aeeiinnnoopttx" => ["exponentiation"],
      "deghhilorsstty" => ["shortsightedly"],
      "eeiinoprsssstx" => ["expressionists"],
      "aabcciiilprtty" => ["practicability"],
      "adeeimnorssttv" => ["demonstratives"],
      "aadiiimnnorstt" => ["administration"],
      "deegiinnnprstu" => ["superintending"],
      "beiiilnoprssty" => ["responsibility"],
      "aabdeginorrstw" => ["waterboardings"],
      "adegiiinnorstt" => ["disintegration"],
      "aceiimmnoorsst" => ["commiserations"],
      "aaceeiinpprtuv" => ["unappreciative"],
      "ceggiinnnorstu" => ["countersigning"],
      "acdeehimnnnstt" => ["disenchantment"],
      "cllnoprssuuuuy" => ["unscrupulously"],
      "aacceiinnorrst" => ["incarcerations"],
      "aaceilnnopsstu" => ["encapsulations"],
      "ceefiinoprsstt" => ["perfectionists"],
      "cceilnorsttuvy" => ["constructively"],
      "aceeillllnttuy" => ["intellectually"],
      "befgillnooprtu" => ["bulletproofing"],
      "aeilnoopssttux" => ["expostulations"],
      "ccceeefimnrrsu" => ["circumferences"],
      "aceeghiloprrsx" => ["lexicographers"],
      "abeilmnnorstuu" => ["insurmountable"],
      "adeeggimnnrrry" => ["gerrymandering"],
      "aceggilmnnoort" => ["conglomerating"],
      "acefiiiinortvv" => ["revivification"],
      "aceimmmnooorst" => ["commemorations"],
      "bdeiiinorrsttu" => ["redistribution"],
      "acciimmnnoostu" => ["communications"],
      "dgiiiillnnossu" => ["disillusioning"],
      "acehinoorrsstt" => ["orchestrations"],
      "ceeeinoprssttv" => ["protectiveness"],
      "aceiinopssssuu" => ["auspiciousness"],
      "cciiijnnosttuv" => ["conjunctivitis"],
      "aaceeilmmnsstu" => ["immaculateness"],
      "efghhinorrsstt" => ["forthrightness"],
      "abdeghinoorssu" => ["boardinghouses"],
      "acceiiilnnoort" => ["reconciliation"],
      "aaceiillnrttuy" => ["inarticulately"],
      "abddeeefghinrt" => ["featherbedding"],
      "beehlooorrsttu" => ["troubleshooter"],
      "acfiiiilmnopst" => ["simplification"],
      "cdeeegilnnoruv" => ["overindulgence"],
      "aacceeinnnorss" => ["reconnaissance"],
      "aacfiiinorsttt" => ["stratification"],
      "eiinooppprsstu" => ["presupposition"],
      "ccceiimnoprstu" => ["circumspection"],
      "aceeegmnnorstu" => ["encouragements"],
      "aabceilnorsstu" => ["constabularies"],
      "adefiinosssstu" => ["fastidiousness"],
      "aacdiiiilnnprs" => ["disciplinarian"],
      "aaeggilmnoorst" => ["agglomerations"],
      "aacdeeginrrrsu" => ["undercarriages"],
      "eefghinnoorrst" => ["foreshortening"],
      "adeehhimoprrst" => ["hermaphrodites"],
      "aacfgiiinorstt" => ["gratifications"],
      "aadeiilmnnnoot" => ["denominational"],
      "adeeiimnnorstt" => ["determinations"],
      "eggilnooorsstt" => ["gerontologists"],
      "aciilnnoostttu" => ["constitutional"],
      "aaiiiilmnrsttu" => ["utilitarianism"],
      "cgiimnnnooprsu" => ["mispronouncing"],
      "eiilnoqrssttuv" => ["ventriloquists"],
      "adgiilnopprsvy" => ["disapprovingly"],
      "bciinoorsstttu" => ["obstructionist"],
      "aabeeelnnorsss" => ["reasonableness"],
      "aaeiinnpprrstt" => ["antiperspirant"],
      "aacehillmoprty" => ["metaphorically"],
      "aeegiiilllmtty" => ["illegitimately"],
      "aacccehiirrstt" => ["characteristic"],
      "aaacdeeinpprss" => ["disappearances"],
      "aeeehilnpprsvy" => ["apprehensively"],
      "aciinnnooprstu" => ["pronunciations"],
      "cdeeimnnnosttt" => ["discontentment"],
      "adeeefimnnoort" => ["aforementioned"],
      "addeginnnrsstu" => ["understandings"],
      "adeefghinrssst" => ["farsightedness"],
      "aabceehiloprrr" => ["irreproachable"],
      "cceeilnoorsttu" => ["electrocutions"],
      "acdiiinnnoortt" => ["indoctrination"],
      "cceinnoorrsttu" => ["reconstruction"],
      "aaeegiimnrrrst" => ["intermarriages"],
      "aacgilnnoorttu" => ["congratulation"],
      "aaggiiilnnrtty" => ["ingratiatingly"],
      "aceiillmnnooos" => ["neocolonialism"],
      "aeeiilnnqssttu" => ["quintessential"],
      "aciiillmopstty" => ["optimistically"],
      "acdiiimnorrsty" => ["discriminatory"],
      "aabdgiiimnostu" => ["disambiguation"],
      "adeeefhooprrtw" => ["weatherproofed"],
      "acdefiiiinnott" => ["identification"],
      "aaccgiillmnstu" => ["miscalculating"],
      "aaceeilnrssttu" => ["articulateness"],
      "acceeinoprsttv" => ["contraceptives"],
      "eeeggiinprrrst" => ["preregistering"],
      "aabiinnosstttu" => ["substantiation"],
      "aaeemqrrrssttu" => ["quartermasters"],
      "deefiilnnnrssu" => ["unfriendliness"],
      "aceeilnorstvvy" => ["conservatively"],
      "aabeemmnrrssst" => ["embarrassments"],
      "aaaabcceelrstu" => ["baccalaureates"],
      "eeiilmnnrtttty" => ["intermittently"],
      "ceeiilnnossstu" => ["licentiousness"],
      "acceinnoorsttu" => ["counteractions"],
      "deeeeimnprrsst" => ["misrepresented"],
      "aaddeegnrrstuu" => ["undergraduates"],
      "acdgiiinnnortt" => ["indoctrinating"],
      "accdeiinnnostu" => ["discontinuance"],
      "abddeehiilssst" => ["disestablished"],
      "eeeghilnsssstw" => ["weightlessness"],
      "aabgiinnsstttu" => ["substantiating"],
      "abcceeiillnorr" => ["irreconcilable"],
      "deeeiimnprrstt" => ["misinterpreted"],
      "ccddeeilnnosty" => ["disconnectedly"],
      "aabdiinoopprst" => ["disapprobation"],
      "acceghiillnnou" => ["hallucinogenic"],
      "aeefglnnrsstuu" => ["ungratefulness"],
      "ddeeghhinrstuw" => ["hundredweights"],
      "acdeginooprstt" => ["prognosticated"],
      "aaciilllrsttuy" => ["altruistically"],
      "aeegiiillnnstt" => ["intelligentsia"],
      "aceegillmooort" => ["meteorological"],
      "abcchilooprstu" => ["claustrophobic"],
      "cceimmooprrstu" => ["microcomputers"],
      "aachiillnnostu" => ["hallucinations"],
      "aceiiimnnorrst" => ["recriminations"],
      "aeegiinnoprrst" => ["peregrinations"],
      "abccilnnnoosuy" => ["unconscionably"],
      "eehilloorssstt" => ["tortoiseshells"],
      "aaggiimnnrrstt" => ["transmigrating"],
      "abceeiilprstty" => ["respectability"],
      "aeilnoosstttuy" => ["ostentatiously"],
      "eehiimmnoprstv" => ["impoverishment"],
      "acdfghiiinnrss" => ["disfranchising"],
      "egiiiinnoqrstu" => ["requisitioning"],
      "eeginnoppssstt" => ["steppingstones"],
      "aaceillmssttyy" => ["systematically"],
      "aeeiiilnsstttx" => ["existentialist"],
      "eeeeilprrtttwy" => ["teletypewriter"],
      "achlnnoorssuyy" => ["asynchronously"],
      "aceeimnooprrst" => ["contemporaries"],
      "aeeeimnnnrsttt" => ["entertainments"],
      "ehhinoopssstty" => ["photosynthesis"],
      "aadefilmmnnstu" => ["fundamentalism"],
      "acdgiiiimnnrst" => ["discriminating"],
      "abeilnnoqstuuy" => ["unquestionably"],
      "aacfiiilmnopst" => ["amplifications"],
      "aaefiimnnosstt" => ["manifestations"],
      "abbeghiiloprrs" => ["bibliographers"],
      "diinooopprrsst" => ["disproportions"],
      "adeeeiiimnrrst" => ["intermediaries"],
      "abcelllnnoortu" => ["uncontrollable"],
      "accdeeimmnotux" => ["excommunicated"],
      "aeeeinprssssuv" => ["persuasiveness"],
      "acehhillopttyy" => ["hypothetically"],
      "eeloopprrsstuy" => ["preposterously"],
      "aacggilnnorttu" => ["congratulating"],
      "cegilmooossstt" => ["cosmetologists"],
      "abeeilnnoqstuu" => ["unquestionable"],
      "eeimoprssssstt" => ["postmistresses"],
      "aacceiiilprstt" => ["practicalities"],
      "aacddeilpqrtuu" => ["quadruplicated"],
      "acehhmmnrsstuy" => ["chrysanthemums"],
      "aadgiiimnnrstt" => ["administrating"],
      "bcccgiiimnrrsu" => ["circumscribing"],
      "aaeeegmnnprrrt" => ["prearrangement"],
      "aacghloopprsyy" => ["parapsychology"],
      "adeiillnoprtvy" => ["providentially"]}
    |> Map.get(string_id)
  end

  def valid_ids do
    ["cdeeinoprsstuv", "aeeiimnnorsttx", "adeeehilnooprt", "acillmmnnootty",
     "aceeeglmnorstt", "aaceiillnpstty", "abeeghiilnstux", "adeiiinnoorstt",
     "aaciiilmnoppst", "aainnooprrsttt", "aeegiilnnnrtty", "eeeegggiinnnor",
     "ccdeeeinnnortt", "aeghimmnooprst", "cddeeilnnostty", "acdeegilnnoqru",
     "ceefgiinnorttu", "acegiillmnoort", "eeeiilmnopssst", "elmopprsstuuuy",
     "aaaeglllmoprrs", "aeegiilmnorsss", "ccdehhillnoors", "aeegginorrsssu",
     "aceeghilnorssu", "aaceghiloorsst", "adeeginnopprrt", "acegilmnnooort",
     "elnoopssstuuuv", "aceeghillnopry", "adeeehhllortwy", "abccginnorsttu",
     "abccnoorrssttu", "efhioopprrssss", "celmnoopsttuuy", "abdeeiilnnpsss",
     "aceghopprrrsty", "acegghhinooprr", "aaiillmnnosttu", "aceilnnnnootuv",
     "cceiimnnoopsst", "addeeeffiinrtt", "eehiilmnnqrstu", "aacillmopsttyy",
     "abdeefiiilnntu", "acfgiinnoorstu", "acghiiinopsstt", "aaaccillorttuy",
     "accefiiinopsst", "aacdiilllmopty", "aceehimmnorssv", "aaddegghnrrstu",
     "aacghillloopty", "ceeeioprrssttv", "acdeiinnoorsst", "abeeiilmnoprss",
     "cceeeeeflnnort", "aabcillnooorst", "bcdeegiimnnrsu", "ceeeilmnnopsst",
     "beeinooqssssuu", "aaceiinnnorrst", "aceeimmnnorstu", "aaccfiiilnorst",
     "accchloopsstuy", "aeeefghhirsttw", "ccdeeennooprrs", "aegiinnoopprrt",
     "adeeeimnrssttu", "aadeeinnprsstt", "ceeefinorrsttu", "aceillnnoosstt",
     "aaceehilllptty", "aachilnopsssyy", "aabcefiiinostt", "aeegiimnorsttv",
     "aaeiimoppprrst", "bhiiiinooprstt", "aacdeeimnnostt", "aeginnorrsssst",
     "aegiinnoorrstt", "dgghiiiinnsstu", "aadiiilnorsttt", "cceiillnnosuvy",
     "acchiilloprtyy", "aeeggiinorsstt", "acceehhloorsst", "efghhlnossttuu",
     "cegiinnorstttu", "aaeginnnprstuu", "ccgiilnnnnouvy", "ehiiooppprrrst",
     "eeeinnoprssssv", "aaabcehlnoppru", "acdeiiinorsssy", "abcinoooorrrst",
     "ceeefimnnorrst", "aadiimnorrsstt", "aaaeiiilmprrst", "aaaccehilmprtu",
     "cdeennooprrsst", "aadehiioprrstt", "aaadeillqrrstu", "aabbefggilnrst",
     "abdeilmorstuxy", "aaacehiimmnstt", "cceginnorrsttu", "aeegiinorrsttv",
     "aacciilmnrsttu", "aaimnnorsstttu", "bcdeiilnrsttuy", "aacdeeffgiinnt",
     "acefiiilmnostu", "acdeghillmooot", "aeeiilmnnssttt", "aaceiilnoprttu",
     "eeeiimnprssssv", "ceeeegiilnnort", "eeeellnnrsssst", "aacciiilmprtty",
     "ccdenooprrstuu", "ceeilmnopsssuv", "bdegiiinrrsttu", "acgghiklnosstu",
     "aabddeelnnrstu", "bceeehilmnoprs", "acginoooprrstt", "acdefiiinoottx",
     "adeeeggimnnsst", "cdeeeiiinnsssv", "aaceilnnoorstv", "ahiimnoprssstt",
     "abeegiinrssssu", "aaaeeginnprstu", "deeiiiilmrstuv", "cceeinnoopprst",
     "beegiiilllnntu", "aeeiilmnnsttty", "acgiimmnoorrss", "accefiiinorstt",
     "eeehiinprsstvy", "aadddeeehhnrss", "beeinoorsssstu", "giiinnooopprst",
     "aefillnooprssy", "aacfinorssttuy", "aacchilllossty", "aciinnoprrsstt",
     "aadeiiimnrsttv", "aceeinoorrsstv", "aaahiinorrsttu", "aaceeinnprrsst",
     "bdiiiiiilnstvy", "aabcdeginorrst", "aacegillloopty", "acceinoopprstu",
     "aaiimnoopprstx", "cceghiklnosttu", "aeiiilnnrsttvy", "efggiiinnnprrt",
     "aaaiinnossssst", "ddeehinnorrsuu", "ceeehimnoprssv", "aaceinoprrsstt",
     "aacfgiiimnnost", "aaceghilllmpty", "cceeeffiiiinns", "abcchhiioprrss",
     "ceeilmnossstuu", "aeeiiilmnssttx", "bdehiiloorrstt", "aiinnooprssstt",
     "accehilmmnopst", "abenoorrssstuu", "aadeeilnrrsttt", "cceelnorrttuuu",
     "ceiilnnnosstty", "cdeinoooprrtuv", "aeeegginrssssv", "aaaccdilorrsuv",
     "acdeeghiinnruv", "aeeeeinprrsttv", "abdeggiknnorru", "aabeghiiilnrtt",
     "cceeeiinnnnosv", "addeimnnrssstu", "acdeefhiinnrss", "adeeghhillrtty",
     "aceiiiilnpprst", "acceemnorrsstt", "aaggiilnnosttu", "aaceklnnorstuy",
     "aacfgilnnoorst", "aiijnoopssttux", "aaceeinrsstttv", "acdiilnooorsst",
     "aacdeimnnnottu", "eegilmooorsstt", "aeeiilmmnnoptt", "aceiiinopprstt",
     "aacehiinnotttu", "ceemopprrsstuu", "chiilorrstttuu", "addeeeeghlmmrs",
     "acdeiiilnnortu", "acdegimnnnortu", "aceiiillmpttuv", "aacdgiiinnosst",
     "acceeimmnostux", "aaceghimnoprty", "ccciilmnoortuu", "ceeiimnnoopttv",
     "aaailnnnorsstt", "aehimnnoorsssu", "aehhiilnopprst", "abeeehlnrsssst",
     "aiiimnooprsstv", "ceeehimorsstty", "acccgiimnnrstu", "adeggiiinnrstt",
     "eeeinopssssssv", "cddeeiinnooprt", "abcdeeehiilnpr", "aacdeiiilllsty",
     "aaceeffilnotty", "aehimoopppsstu", "aabcciilnottuy", "acceiinoprsssu",
     "ceemnnnooprstu", "acdeeimmnnoort", "aacffiiilnosst", "abdeehiilsssst",
     "aeiinoopprrstx", "bdgggiillmnnoy", "acefinrrrsttuu", "achiioprssstty",
     "aafimnnoorrstt", "diiiinnoopssst", "aabdeeehhirrss", "aeeemnorsstttv",
     "aeehinpppprrsw", "accdeiillnnoty", "aaceiinoprrstv", "eeegiinnprrrtt",
     "abeelnnnorrstu", "aacdeinoprrstt", "cdelmnnoooosty", "acddeegklnnouw",
     "ciinnooorssttt", "aaaegiiilmnrst", "aacdeeijkrsttt", "acdeeeiosssttv",
     "abeeilmnnnostu", "adeeehimrsssst", "aaacceghilloor", "aaadeglnostuvy",
     "eiilnoorssttuv", "aabbeiillosssu", "bcdeeiilnrsttu", "cgiiilmnoorsst",
     "acegiilnossttu", "aceghlnnnoooty", "aeillmnosstuuy", "cceimoooprrrss",
     "abeeeinorrrstv", "acdeeennopprrs", "aacdeglmnnorss", "aaceghiinntttu",
     "acceeiinnoorss", "beeehillmmnsst", "acfgiiiinnosst", "abcdenooorrrtu",
     "aaacehimoopprs", "achiiinoopsstt", "aefiiiilmnnsst", "cdeiiinnnssstt",
     "abcegiiloorstt", "ceeeiooprrttvv", "cdeeiiinnsstvv", "adeeiinnoprstt",
     "acdeegimnorstu", "begilnorsssuuu", "aadeegimnnrrst", "acdeeeimnoppst",
     "ccdeiinnnoosst", "deeeeillmmosss", "ghiilnooorsstt", "acdiiiilnnnost",
     "aacceknorstttu", "ceiinoprsssstu", "cegiiknnnorstu", "aabceenrsssstt",
     "aaehiiimnnsstt", "ceefiinnossstu", "acfinnnooorstt", "acffiiinoorstt",
     "ccefllnsssuuuy", "acceehilmoprst", "accdhhinooprsy", "aeffhilnnsstuu",
     "aaeilnooprsttx", "aeeeinnoprrstt", "aeeiilnnorrstt", "accceillnnorty",
     "acdeeenrrrstuy", "aaiinooppprrst", "aeiimnnooprsst", "cceeiinnossttu",
     "beeeimmnrrsstu", "abeeghiilnrsst", "abbeghiiiloprs", "deehhnorrsstuw",
     "aeegiimnnnortu", "acceinnnoorstt", "aaccegiimnrtuv", "acehiinnssttuu",
     "abclllnnoortuy", "acdehhiimoprrt", "eeeilnoprssssx", "aceeeeinnrrstt",
     "aabcdeennprsuu", "aabcefgiinprrt", "accinprssttuuu", "aaceeghnooprrs",
     "adeeeffiinrstt", "acfiiilnostttu", "aabcefiiinottu", "aeegiiilrrrstu",
     "aacinooprrrstt", "ceiiiillmpsttu", "ddeeeeinnnprtt", "abcdeeehilnpru",
     "aaabdhimoprsss", "adeeegoprrstuy", "aacghilmooprst", "acfgiilmnnnotu",
     "abbcdeilmoostu", "cfimnnnooorsst", "aciiiilprssttu", "ccceeeiiinrstt",
     "addeeegoprrtuy", "aeeeiinprrtttv", "eefiiilmoprssv", "deefiiilmoprsv",
     "adeiimnnoppstt", "aeeeiiinnprstt", "aeeiinnoprrttt", "aabdeiikmnorst",
     "aceillnnnootvy", "ceeghinorsttuw", "dddeeeelnopruv", "acdeefinnoorst",
     "accefgiiiinnns", "aacehiillnttty", "aeeeillmnprtxy", "abcceilnnnoosu",
     "aadefgghinnrrt", "aabchilooprstu", "aaabcehilllpty", "aabcefiinoprrt",
     "aachlnopssstyy", "ccdeeeiinnnnov", "aacglnoorrttuy", "aabeiiilnprsty",
     "aeeehilnprttvy", "ceeiinnorrsttv", "aacciillmnostu", "aillnooopprrty",
     "aaeiilnnossstt", "aaeeilnnprrtty", "aeeghhlorsstuu", "aacegghillopry",
     "behiiiinossttx", "afiiimmnnoorst", "adeeeimnrssttv", "abcdeeiilnnors",
     "aaeiilmnnossst", "beeeillnorsssu", "aabcdeeinrrstt", "aacdeelnnnrstt",
     "bccilnoosssuuy", "accdeeinnnostu", "deeeelmnoprstv", "acdeiiiimnnrst",
     "eehiinoopssttv", "aceehiinppprst", "aceinnnooooprt", "acdiilnnooosst",
     "aceeghhooprrrs", "aaeiilnnnorstt", "aaciilnooprrst", "aeilnooopprtuv",
     "adiiilnrsssttu", "adegilmoorsstt", "aabehiiilnortt", "eeghillmnorvwy",
     "acehilmoprsstt", "beefhimnrrsstu", "ccehhiinoprssz", "aacceinnnoostt",
     "aaceillmmrstyy", "aaeemnnopprsww", "abefllnoopsstu", "aaeeegmnnrrrst",
     "aeegillmnorrst", "adfiiimnnoorst", "aadefilmnnsttu", "aegiiinnossttv",
     "acdggiilnorsuy", "aabegilmnrrssy", "ccceiimmnooors", "aacddeeimnnott",
     "abegiiilmnprty", "aciiillmnopttu", "cgiimmnnooprsu", "addeeehimnpprs",
     "aeeiilmmnnsstt", "aceegillnoprtt", "cehilmoorsssst", "deeegiimnnprrt",
     "aaccfiiilnosst", "acfiiijnossttu", "acceehiiilnstt", "abcdeiiilprtty",
     "aabeghiklnrtty", "ccdeimnoorsstu", "aefilnnooprssu", "acdiiijlnorstu",
     "aeeemnooprstux", "cdeiilnorsssuu", "bceiiilpssttuy", "aaaaghimnoprst",
     "aeeiiilnopsttt", "aeghiilnnsttuy", "accefiiillnsty", "aceehmnopprrst",
     "eeeiopprrrssst", "cddeeiimmnooss", "adeeemnnrstttu", "ceffiiilnnstuy",
     "aaccfiiinnostt", "accdeeilmnortu", "bbciiilmosttuy", "aaeelnnnpssstu",
     "abdeeeiilmnnrt", "aacceimmnnopst", "adgiilllnnotuy", "aceginooprsstt",
     "acdfiiiilnoost", "acceeilllnorty", "aaccceeiillsst", "acdiiiimnnorst",
     "acdefiillnnoty", "aceeemnooprstv", "ceehhnoopprsst", "aaceiimmossttu",
     "ddeeiilnorrsss", "eeghilnoprrstu", "aagiimnnorrstt", "accegiilnrtuxy",
     "aaccdeillmorty", "accceeelnnossv", "aacfiilorsstty", "ccdeinnoorsttu",
     "aacfiiilnoqstu", "bdeiiorrrssttu", "addeeeimnrsttu", "aacegiilnprttu",
     "aceiiiilmnpstu", "abiiiillmpstuy", "acefiiilprstuy", "aceiilnossssuv",
     "addeeeimnprttu", "defgiiiimnnsty", "aeeinoqrsssttu", "aacehiillmrtty",
     "aceeelmnoprtux", "abceeeefnrssst", "adeimnnoorsstt", "cdegiiinnnoort",
     "aaceeiilpprtvy", "aciilllmooqssu", "aacillmnoorsty", "bdeehlooorsttu",
     "aaceggilnnoort", "acdeillnoossty", "ceiijnooprsstt", "aabciiilnrttty",
     "acceilmmnnoors", "eeimnorsssstuy", "eeeeinprssssvx", "acdehimmnorsty",
     "aaaddggiinnstv", "aabcegiknqrrtu", "aaaccgiiinnptt", "aegilnoopprtuv",
     "ceehimnnooprss", "aeeemnnopprsww", "addiiiilnsstuv", "accdiinnoorstt",
     "aacdeilpqrstuu", "aceinnnoorsttv", "cdeiloorsstuuy", "aeeegillnssttv",
     "aeiilnnooprstt", "aacdeiilnorstv", "ceeiilnnnnotvy", "ceginrrrssttuu",
     "begiiilllnntuy", "ahhiilnopprstt", "aaccehhiillrry", "deeeinnnprsttu",
     "cceeinooprsssu", "eiiimnoprsssst", "ceeeeinpprsstv", "acdeeehinrrsuv",
     "acdeeilnpprrsu", "deefgiimnrsstu", "aeeefillnprrty", "acefgiiinnortt",
     "aghilnoooprstt", "aceeilmnopsttv", "aabcceelnnortu", "aaacehillmmtty",
     "aacilllnorstuy", "aeeiinnoqrsstu", "aaeeilnrrssttt", "aaccdimmnooost",
     "ehiorrssttttuw", "deiiinoopprsst", "ceeprrrssttuuu", "abdeiiilnrstuy",
     "aacdgiiinossst", "aabddelnnrstuy", "abeehilmnssstt", "bcgiiilmooorst",
     "aeeiinnnoopttx", "deghhilorsstty", "eeiinoprsssstx", "aabcciiilprtty",
     "adeeimnorssttv", "aadiiimnnorstt", "deegiinnnprstu", "beiiilnoprssty",
     "aabdeginorrstw", "adegiiinnorstt", "aceiimmnoorsst", "aaceeiinpprtuv",
     "ceggiinnnorstu", "acdeehimnnnstt", "cllnoprssuuuuy", "aacceiinnorrst",
     "aaceilnnopsstu", "ceefiinoprsstt", "cceilnorsttuvy", "aceeillllnttuy",
     "befgillnooprtu", "aeilnoopssttux", "ccceeefimnrrsu", "aceeghiloprrsx",
     "abeilmnnorstuu", "adeeggimnnrrry", "aceggilmnnoort", "acefiiiinortvv",
     "aceimmmnooorst", "bdeiiinorrsttu", "acciimmnnoostu", "dgiiiillnnossu",
     "acehinoorrsstt", "ceeeinoprssttv", "aceiinopssssuu", "cciiijnnosttuv",
     "aaceeilmmnsstu", "efghhinorrsstt", "abdeghinoorssu", "acceiiilnnoort",
     "aaceiillnrttuy", "abddeeefghinrt", "beehlooorrsttu", "acfiiiilmnopst",
     "cdeeegilnnoruv", "aacceeinnnorss", "aacfiiinorsttt", "eiinooppprsstu",
     "ccceiimnoprstu", "aceeegmnnorstu", "aabceilnorsstu", "adefiinosssstu",
     "aacdiiiilnnprs", "aaeggilmnoorst", "aacdeeginrrrsu", "eefghinnoorrst",
     "adeehhimoprrst", "aacfgiiinorstt", "aadeiilmnnnoot", "adeeiimnnorstt",
     "eggilnooorsstt", "aciilnnoostttu", "aaiiiilmnrsttu", "cgiimnnnooprsu",
     "eiilnoqrssttuv", "adgiilnopprsvy", "bciinoorsstttu", "aabeeelnnorsss",
     "aaeiinnpprrstt", "aacehillmoprty", "aeegiiilllmtty", "aacccehiirrstt",
     "aaacdeeinpprss", "aeeehilnpprsvy", "aciinnnooprstu", "cdeeimnnnosttt",
     "adeeefimnnoort", "addeginnnrsstu", "adeefghinrssst", "aabceehiloprrr",
     "cceeilnoorsttu", "acdiiinnnoortt", "cceinnoorrsttu", "aaeegiimnrrrst",
     "aacgilnnoorttu", "aaggiiilnnrtty", "aceiillmnnooos", "aeeiilnnqssttu",
     "aciiillmopstty", "acdiiimnorrsty", "aabdgiiimnostu", "adeeefhooprrtw",
     "acdefiiiinnott", "aaccgiillmnstu", "aaceeilnrssttu", "acceeinoprsttv",
     "eeeggiinprrrst", "aabiinnosstttu", "aaeemqrrrssttu", "deefiilnnnrssu",
     "aceeilnorstvvy", "aabeemmnrrssst", "aaaabcceelrstu", "eeiilmnnrtttty",
     "ceeiilnnossstu", "acceinnoorsttu", "deeeeimnprrsst", "aaddeegnrrstuu",
     "acdgiiinnnortt", "accdeiinnnostu", "abddeehiilssst", "eeeghilnsssstw",
     "aabgiinnsstttu", "abcceeiillnorr", "deeeiimnprrstt", "ccddeeilnnosty",
     "aabdiinoopprst", "acceghiillnnou", "aeefglnnrsstuu", "ddeeghhinrstuw",
     "acdeginooprstt", "aaciilllrsttuy", "aeegiiillnnstt", "aceegillmooort",
     "abcchilooprstu", "cceimmooprrstu", "aachiillnnostu", "aceiiimnnorrst",
     "aeegiinnoprrst", "abccilnnnoosuy", "eehilloorssstt", "aaggiimnnrrstt",
     "abceeiilprstty", "aeilnoosstttuy", "eehiimmnoprstv", "acdfghiiinnrss",
     "egiiiinnoqrstu", "eeginnoppssstt", "aaceillmssttyy", "aeeiiilnsstttx",
     "eeeeilprrtttwy", "achlnnoorssuyy", "aceeimnooprrst", "aeeeimnnnrsttt",
     "ehhinoopssstty", "aadefilmmnnstu", "acdgiiiimnnrst", "abeilnnoqstuuy",
     "aacfiiilmnopst", "aaefiimnnosstt", "abbeghiiloprrs", "diinooopprrsst",
     "adeeeiiimnrrst", "abcelllnnoortu", "accdeeimmnotux", "aeeeinprssssuv",
     "acehhillopttyy", "eeloopprrsstuy", "aacggilnnorttu", "cegilmooossstt",
     "abeeilnnoqstuu", "eeimoprssssstt", "aacceiiilprstt", "aacddeilpqrtuu",
     "acehhmmnrsstuy", "aadgiiimnnrstt", "bcccgiiimnrrsu", "aaeeegmnnprrrt",
     "aacghloopprsyy", "adeiillnoprtvy"]
    |> Enum.into(HashSet.new)
  end
end
