defmodule Jumble.ScowlDict.Size50.Length13 do
  def get(string_id) do
    %{"aadiimnorrstt" => ["administrator"], "adggiiimnnoss" => ["misdiagnosing"],
      "acilmnooopsst" => ["cosmopolitans"], "acdeiinnorstt" => ["indoctrinates"],
      "acefghiinnnrs" => ["enfranchising"], "aceiorrsssttu" => ["resuscitators"],
      "abcchhiioprrs" => ["archbishopric"], "ceennoorrsttu" => ["countertenors"],
      "aeeinoqrssttu" => ["sequestration"], "abcflmnoortuy" => ["uncomfortably"],
      "acceehhloorst" => ["schoolteacher"], "ceeehmnnrrstt" => ["retrenchments"],
      "acceeiimorrst" => ["meritocracies"], "aegiiilnrsstu" => ["singularities"],
      "aceilooprtvvy" => ["provocatively"], "abeiiiilnttvy" => ["inevitability"],
      "aceillmmrstyy" => ["symmetrically"], "aaccdimmnooot" => ["accommodation"],
      "cceiimnnoopst" => ["misconception"], "aabdennprstuu" => ["superabundant"],
      "ceiilnoossttu" => ["elocutionists"], "aiillnnortuvy" => ["involuntarily"],
      "aaccdeilnootu" => ["coeducational"], "abellllopssyy" => ["polysyllables"],
      "ccdgiimnnostu" => ["misconducting"], "adhiimnoorssu" => ["disharmonious"],
      "aeeinrssstttv" => ["transvestites"], "ccdegiinnorst" => ["disconcerting"],
      "iiinnorsstttu" => ["nutritionists"], "adehnorrsttww" => ["northwestward"],
      "aeeimnnorrstu" => ["remunerations"], "aceemnnorrsst" => ["remonstrances"],
      "egiimnopprssu" => ["superimposing"], "aaehiiimnnstt" => ["antihistamine"],
      "accdeeennnrst" => ["transcendence"], "aeeimnnopprtt" => ["reappointment"],
      "acehhiinoprsz" => ["schizophrenia"], "aaccegiinnrrt" => ["incarcerating"],
      "aabdeemnrrssu" => ["unembarrassed"], "abeiilrtttuvy" => ["attributively"],
      "aacfiiimnorst" => ["ramifications"], "aeeilnnoprrst" => ["interpersonal"],
      "adegilmoorstt" => ["dermatologist"], "aegilnopsttux" => ["expostulating"],
      "aaimnnorstttu" => ["transmutation"], "cgiimnnorsstu" => ["misconstruing"],
      "deeilnosssstu" => ["dissoluteness"], "eiiimmnoprsss" => ["impressionism"],
      "aceeinorsstvv" => ["conservatives"], "aagilnnorsttu" => ["strangulation"],
      "aeeefghhirttw" => ["featherweight"], "beeegilllnrty" => ["belligerently"],
      "ceegmnnoorssw" => ["congresswomen"], "aeeillnnoptxy" => ["exponentially"],
      "beeeimmnrrstu" => ["reimbursement"], "bbeeeinorrssy" => ["boysenberries"],
      "aeeemnorstttv" => ["overstatement"], "adeegmnnrrstu" => ["undergarments"],
      "eiilmoorrstuy" => ["meritoriously"], "aceegiinnnrst" => ["intransigence"],
      "eegilmooorstt" => ["meteorologist"], "aaagiilnorttv" => ["gravitational"],
      "eeinooprsssss" => ["repossessions"], "ceilnoorrttuy" => ["interlocutory"],
      "acgilllooopty" => ["topologically"], "abeegilnnnoot" => ["nonnegotiable"],
      "cceilnoooopss" => ["colonoscopies"], "aehilmoostuxy" => ["homosexuality"],
      "aacceghinoopr" => ["oceanographic"], "beiiiilnnssty" => ["insensibility"],
      "acfiiimnoortt" => ["mortification"], "bceeeijnosstv" => ["objectiveness"],
      "ceeinoorrsstv" => ["controversies"], "hnorrstttuuwy" => ["untrustworthy"],
      "aceeehnnrssst" => ["enchantresses"], "eegiinnnrsttu" => ["uninteresting"],
      "bcdeeginorrss" => ["crossbreeding"], "ceeinorsstttu" => ["reconstitutes"],
      "eiimnoorssstt" => ["monstrosities"], "eiinoorsstttx" => ["extortionists"],
      "aaahiimnnrstu" => ["humanitarians"], "aeeggiinnortt" => ["renegotiating"],
      "bdeeiirrssttu" => ["redistributes"], "cdeginooprruv" => ["overproducing"],
      "abeeeeilmmprs" => ["semipermeable"], "aeiilnoopprst" => ["prepositional"],
      "aaeffiilmrtvy" => ["affirmatively"], "deeeeimnprrst" => ["predetermines"],
      "aaiimnoopprtx" => ["approximation"], "aaeeiinnrrstv" => ["veterinarians"],
      "aeemnprrrsuuy" => ["supernumerary"], "aceeilnnoptux" => ["unexceptional"],
      "ceeiilrrsttvy" => ["restrictively"], "acdegiilpqrsu" => ["quadriplegics"],
      "ddeeeiinrsstt" => ["disinterested"], "aceeiiilprstu" => ["peculiarities"],
      "cdeeinorstttu" => ["reconstituted"], "eeeimnnprsstt" => ["presentiments"],
      "aabdegiknorst" => ["skateboarding"], "eegiinnprrsst" => ["interspersing"],
      "adeeiinoprtxy" => ["expeditionary"], "aaeemqrrrsttu" => ["quartermaster"],
      "adegghinnorty" => ["hydrogenating"], "acdegiimnostt" => ["domesticating"],
      "addeeegmnrrry" => ["gerrymandered"], "aabilnnssttuu" => ["unsubstantial"],
      "acdefgillrsuy" => ["disgracefully"], "efgghiiilnttw" => ["weightlifting"],
      "acegiimmnorst" => ["commiserating"], "aaaiinnosssst" => ["assassination"],
      "cdeeiiimnrstt" => ["deterministic"], "adeeenopprrst" => ["preponderates"],
      "aehhooprrssst" => ["sharpshooters"], "aegiinorssttv" => ["investigators"],
      "aaceeiinorrst" => ["reactionaries"], "abbciiiloprst" => ["probabilistic"],
      "aacdeglnorttu" => ["congratulated"], "abcceiiilssty" => ["accessibility"],
      "aabcgillnoort" => ["collaborating"], "aegiinnoorrtt" => ["interrogation"],
      "eeknoopprssss" => ["spokespersons"], "acehilmoprstt" => ["thermoplastic"],
      "deeginnoprsux" => ["underexposing"], "cceeemmmnnost" => ["commencements"],
      "aacfiinossstt" => ["satisfactions"], "aacegiinprrtv" => ["prevaricating"],
      "cdfghiilnoopr" => ["childproofing"], "acfgiiiinnost" => ["signification"],
      "adeejmnrssttu" => ["readjustments"], "aceegiimnnost" => ["miscegenation"],
      "aceinnorssttu" => ["encrustations"], "acghiilloopsy" => ["physiological"],
      "aeefhooprrstw" => ["weatherproofs"], "aacdhilllruyy" => ["hydraulically"],
      "aceghopprrrty" => ["cryptographer"], "cceiinnnossty" => ["inconsistency"],
      "aceeiloprstty" => ["stereotypical"], "ceegikllnopss" => ["glockenspiels"],
      "ceeilmnoorsuy" => ["ceremoniously"], "ccdegiinnnost" => ["disconnecting"],
      "aceegiinnsstt" => ["necessitating"], "abeefilllnnor" => ["nonrefillable"],
      "ceeiijnnorstt" => ["interjections"], "aceeilnnoqstu" => ["consequential"],
      "adeeeiimnnrtt" => ["indeterminate"], "cdeeiilprstvy" => ["descriptively"],
      "eefilnrsssstu" => ["fruitlessness"], "acfgiiinnoptt" => ["pontificating"],
      "adehimmnnosst" => ["admonishments"], "bcccdeiimrrsu" => ["circumscribed"],
      "aadefllmnntuy" => ["fundamentally"], "abeeeinorrrtv" => ["reverberation"],
      "aadeinorrrtxy" => ["extraordinary"], "aacegilllmrtu" => ["metallurgical"],
      "aceehimoorstt" => ["tracheotomies"], "cdeimnnooprsu" => ["mispronounced"],
      "ceiimmnoorsss" => ["commissioners"], "aceeeehlpssst" => ["steeplechases"],
      "eeiimnoprsssu" => ["imperiousness"], "adeeenrssstuv" => ["adventuresses"],
      "accdeeilnopsy" => ["encyclopedias"], "cceefinnoorty" => ["confectionery"],
      "beeehilnprrsy" => ["reprehensibly"], "aabcciilmprty" => ["impracticably"],
      "aeegiinorrttv" => ["interrogative"], "aacceinopsssu" => ["capaciousness"],
      "aaiilmnnopstu" => ["manipulations"], "ceefiinoprsst" => ["frontispieces"],
      "abeeeginrrrtv" => ["reverberating"], "acgghiklnostu" => ["laughingstock"],
      "acdeeennopprr" => ["preponderance"], "acfgiiiinnnst" => ["insignificant"],
      "ceeehmnnnrstt" => ["entrenchments"], "acdgiinnosttu" => ["outdistancing"],
      "eeffglnorsstu" => ["forgetfulness"], "abdeglnorsttu" => ["battlegrounds"],
      "aaadddeginstv" => ["disadvantaged"], "aeeeinrsssstv" => ["assertiveness"],
      "acdeeiinnorst" => ["inconsiderate"], "aabeilllnnstu" => ["uninstallable"],
      "acegimmmnoort" => ["commemorating"], "aaegiimmnnrst" => ["mainstreaming"],
      "abdeiinnorstu" => ["insubordinate"], "adeefinoorstt" => ["deforestation"],
      "aagiilnnorttu" => ["triangulation"], "acdeeelloprtt" => ["electroplated"],
      "aaeinnnossttu" => ["instantaneous"], "ddeeeinnprstu" => ["superintended"],
      "egiilnnoqstuy" => ["questioningly"], "aabbddeegilor" => ["biodegradable"],
      "eeiilmnpsssuv" => ["impulsiveness"], "eeeennprrrstu" => ["entrepreneurs"],
      "aeeeinprsttvv" => ["preventatives"], "eiinoprsssttu" => ["superstitions"],
      "aeeiimnnorttx" => ["extermination"], "aaeegimmmnnst" => ["mismanagement"],
      "aaciilprrttuy" => ["particularity"], "aceinnnoorstt" => ["consternation"],
      "acceilmnnnoop" => ["noncompliance"], "aabdeeiiilrst" => ["readabilities"],
      "cdeegiinorrsv" => ["rediscovering"], "aagiinoppprrt" => ["appropriating"],
      "aaeeelmmnprtt" => ["temperamental"], "adiiilnrssttu" => ["industrialist"],
      "ddeghiiinsstu" => ["distinguished"], "deeefhnoorrst" => ["foreshortened"],
      "aceeinoorrstv" => ["overreactions"], "adeinosssssuu" => ["assiduousness"],
      "defgginnoorru" => ["foregrounding"], "adeeimnrsstuv" => ["misadventures"],
      "bbcgiinnrssuu" => ["unsubscribing"], "acginnnooostu" => ["noncontagious"],
      "ceeffnoorrstu" => ["counteroffers"], "behiiiimnostx" => ["exhibitionism"],
      "aceiimmnoorst" => ["commiseration"], "aegiimnnoprst" => ["impersonating"],
      "agilnnoooprst" => ["prolongations"], "aiillnnorttuy" => ["nutritionally"],
      "adeehhiorrsss" => ["horseradishes"], "acgghhinnorst" => ["shortchanging"],
      "deeghilmooost" => ["methodologies"], "eeeellnpsssss" => ["sleeplessness"],
      "abeilnopprstu" => ["insupportable"], "aeefinoorrstt" => ["reforestation"],
      "aabcegilnnorv" => ["overbalancing"], "adeeiimnoprtt" => ["premeditation"],
      "aaciilnopsttu" => ["capitulations"], "adefgiinnoorr" => ["foreordaining"],
      "aeeinnorsstuv" => ["intravenouses"], "cceeiinnossst" => ["consistencies"],
      "acfgiiilnoort" => ["glorification"], "aeiilnnnnottu" => ["unintentional"],
      "acfgiiilnnsty" => ["significantly"],
      "ceefiimnoprst" => ["perfectionism", "imperfections"],
      "aacghiloopprt" => ["topographical"], "aaccciiilmntt" => ["anticlimactic"],
      "aaceinoprsssu" => ["rapaciousness"], "eegghinnnrstt" => ["strengthening"],
      "ccgiinorrssss" => ["crisscrossing"], "abelllmnoossy" => ["monosyllables"],
      "eegiimnoprrtu" => ["primogeniture"], "cegiimnoorrtt" => ["trigonometric"],
      "aefiiiilmnnst" => ["infinitesimal"], "aceiinoprrstt" => ["practitioners"],
      "cegiinnooprss" => ["processioning"], "acdefhiinrsss" => ["disfranchises"],
      "aahiinopsstxy" => ["asphyxiations"], "aacceginnnott" => ["concatenating"],
      "acdeeiilorstv" => ["valedictories"], "aiillmnopssuu" => ["pusillanimous"],
      "deiiinnossssu" => ["insidiousness"], "aeiklmnoprsst" => ["sportsmanlike"],
      "abceeilnnostt" => ["incontestable"], "ddeeeeimnprrt" => ["predetermined"],
      "cdeeiiorssstu" => ["discourtesies"], "ccdeehilorrty" => ["hydroelectric"],
      "aceeiimnnosst" => ["amniocentesis"], "aaciimnnnoott" => ["contamination"],
      "abdeeehilrsst" => ["reestablished"], "aiimnnorsssst" => ["transmissions"],
      "cdeennooprrst" => ["correspondent"], "aabciillnosty" => ["syllabication"],
      "cgiiimmnnooss" => ["commissioning"], "cdeefilprsstu" => ["disrespectful"],
      "ciinoopprsttu" => ["opportunistic"], "ciinoopprrsst" => ["proscriptions"],
      "acgiiillnnstt" => ["scintillating"], "abeiimoorstuv" => ["overambitious"],
      "aaeeegmnnrrrt" => ["rearrangement"], "accehiilprrty" => ["hypercritical"],
      "cdeeefinorttu" => ["counterfeited"], "aegikllnorrst" => ["rollerskating"],
      "abeeghiknorsu" => ["housebreaking"], "aaaiilnorsttt" => ["totalitarians"],
      "aeeeimorssttv" => ["overestimates"], "acfiiijnosttu" => ["justification"],
      "aacfiiiilrtty" => ["artificiality"], "behiiiinosttx" => ["exhibitionist"],
      "eeghiinrsstux" => ["extinguishers"], "adelnorstuuvy" => ["adventurously"],
      "accdgiinnortt" => ["contradicting"], "accchiioprrst" => ["chiropractics"],
      "aacfgiiinortt" => ["gratification"], "deeiiinoqrstu" => ["requisitioned"],
      "aceilnoorrstv" => ["controversial"], "aiiilnnostttu" => ["institutional"],
      "adeeeghlmmrss" => ["sledgehammers"], "aceeinooprttx" => ["expectoration"],
      "ddeginnrstuuy" => ["understudying"], "acdefgiilnssy" => ["declassifying"],
      "deeeegiprrrst" => ["preregistered"], "deeeinnprrttu" => ["uninterpreted"],
      "eehlorssttuwy" => ["southwesterly"], "abgiimnnorrst" => ["brainstorming"],
      "aafiilmnnoort" => ["informational"], "aaeegilmnoorr" => ["oleomargarine"],
      "ccilmoorsstty" => ["motorcyclists"], "aaelnnprrstty" => ["transparently"],
      "ccdeimnoorstu" => ["semiconductor"], "aacgiimnnnott" => ["contaminating"],
      "accdiinnoortt" => ["contradiction"], "eeeilnnosssss" => ["noiselessness"],
      "cdeiiilnsttvy" => ["distinctively"], "acceilmmnnoor" => ["noncommercial"],
      "aabcciiilnnst" => ["cannibalistic"], "eeeghilrsttww" => ["welterweights"],
      "eelmopssttuuy" => ["tempestuously"], "aabciiillppty" => ["applicability"],
      "achhiilloopps" => ["philosophical"], "aegghiimmnopr" => ["mimeographing"],
      "acfinnnooortt" => ["confrontation"], "aaccegillorty" => ["categorically"],
      "aaiinooppprrt" => ["appropriation"], "aadegoprssttu" => ["postgraduates"],
      "aacceinnnoott" => ["concatenation"], "eeffiilnnosvy" => ["inoffensively"],
      "acdeghiinnnst" => ["disenchanting"], "eeehilmnnprst" => ["replenishment"],
      "aeeloopprstuv" => ["overpopulates"], "aagilnnnprstt" => ["transplanting"],
      "cdeeimnooprss" => ["decompression"], "aaceehilnprtt" => ["parenthetical"],
      "abefiijlnstuu" => ["unjustifiable"], "abefglnorttuy" => ["unforgettably"],
      "eeginnnosssuu" => ["ingenuousness"], "bcdeeiiilnnrs" => ["indiscernible"],
      "adefhilnoorss" => ["foolhardiness"], "ddefghiiimnuy" => ["dehumidifying"],
      "aaaeeginnrssx" => ["sexagenarians"], "aacdeeeffinst" => ["decaffeinates"],
      "aacciirrssttu" => ["caricaturists"], "deeiilopstuxy" => ["expeditiously"],
      "ccddeeginnnos" => ["condescending"], "acdeeeilnssst" => ["delicatessens"],
      "eeegiimnnprtx" => ["experimenting"], "ceiiilnnsttvy" => ["instinctively"],
      "abbcghiiilopr" => ["bibliographic"], "aabciiillmpty" => ["implacability"],
      "aghiinnpprsst" => ["transshipping"], "adeeellmnoptv" => ["developmental"],
      "adehorssttuww" => ["southwestward"], "ceeeffiilntvy" => ["ineffectively"],
      "aaehiiortttuv" => ["authoritative"], "abeiillnrtuvy" => ["vulnerability"],
      "deeehloprrstu" => ["reupholstered"], "deeeginnortvx" => ["overextending"],
      "aceeegillnrty" => ["energetically"], "adeeeffiinrtt" => ["differentiate"],
      "eegiilnnrstty" => ["interestingly"], "cefilnoprrtuy" => ["perfunctorily"],
      "eiilnoorsttuv" => ["revolutionist"], "eeeeinnqrsstu" => ["equestriennes"],
      "eiiillmoopsty" => ["poliomyelitis"], "behiiiloprtvy" => ["prohibitively"],
      "aaacdilloprxy" => ["paradoxically"], "accimmnoorstu" => ["communicators"],
      "aacdgiiinnost" => ["diagnostician"], "aaefgimnnortt" => ["fragmentation"],
      "aabcillnooort" => ["collaboration"], "adeeffiilnrst" => ["differentials"],
      "ghiilnooorstt" => ["ornithologist"], "aeefhilnsssst" => ["faithlessness"],
      "aceiilmnooprt" => ["recompilation"], "aceillnnnossy" => ["nonsensically"],
      "aceeilorrttvy" => ["retroactively"], "aceehhiilmprs" => ["hemispherical"],
      "deghiiinssstu" => ["distinguishes"], "aegiinorrsstt" => ["registrations"],
      "bceeeeghrrssu" => ["cheeseburgers"], "abeimnnosssuw" => ["businesswoman"],
      "adeeegginorst" => ["desegregation"], "aeggiinorrttu" => ["regurgitation"],
      "ccceooprssttu" => ["streptococcus"], "adefghinoorsw" => ["foreshadowing"],
      "deefiiiimnsst" => ["misidentifies"], "accghillnooor" => ["chronological"],
      "aceiinosssuvv" => ["vivaciousness"], "diiiinoqssstu" => ["disquisitions"],
      "aceeginoprttx" => ["expectorating"], "acgiimmnoorrs" => ["microorganism"],
      "bceiilnoprrtu" => ["incorruptible"], "cdeegimnoprss" => ["decompressing"],
      "aeilnoorrtuvy" => ["revolutionary"], "aaeennprsstuu" => ["superannuates"],
      "acefhlloprruy" => ["reproachfully"], "accdeilmnoptu" => ["uncomplicated"],
      "aaeilmopprtxy" => ["approximately"], "aeefggiinrrrt" => ["refrigerating"],
      "aeeeiilnsttuv" => ["eventualities"], "abceiooorrrtv" => ["corroborative"],
      "deeeelmnoprtv" => ["redevelopment"], "ciinnoosstttu" => ["constitutions"],
      "accegiinnnort" => ["concertinaing"], "agghhinoopprt" => ["photographing"],
      "aiiilnoossstt" => ["isolationists"], "aaaaehilnpprr" => ["paraphernalia"],
      "ceeeinrrrsstw" => ["screenwriters"], "aacdeeginrrru" => ["undercarriage"],
      "adeeeimnrsttv" => ["advertisement"], "acchiooprrrst" => ["chiropractors"],
      "beegloorrsttt" => ["globetrotters"], "beeeiilprrrss" => ["irrepressible"],
      "deeeghilnnntu" => ["unenlightened"], "aaceiinoprrtv" => ["prevarication"],
      "ceeginoprrstt" => ["retrospecting"], "cdehknrrsttuu" => ["thunderstruck"],
      "eegillnnnrtuy" => ["unrelentingly"], "aacceiiorrsst" => ["aristocracies"],
      "eegiloprrssvy" => ["progressively"], "aaggilnnrsttu" => ["strangulating"],
      "ddeeelmnopruy" => ["underemployed"], "bdiiinorssttu" => ["distributions"],
      "ceeelmmorsttu" => ["telecommuters"], "ceeeeinprsstv" => ["receptiveness"],
      "ddeiiillnossu" => ["disillusioned"], "abeiilmnrssst" => ["transmissible"],
      "cdehiioprrsst" => ["directorships"], "acefiiinorstv" => ["versification"],
      "deehhnorrstuw" => ["thundershower"], "aaceghillprrs" => ["calligraphers"],
      "acccelooprstt" => ["streptococcal"], "adiiiilmrssty" => ["dissimilarity"],
      "cceeinnoopprt" => ["preconception"], "ceeinorrrsstu" => ["resurrections"],
      "cdeiiinnorsst" => ["indiscretions"], "cceeilnostuvy" => ["consecutively"],
      "abeelnnnorrtu" => ["nonreturnable"], "acdeghiimnnrs" => ["merchandising"],
      "aegiiinnosttv" => ["investigation"], "aceiiinopprtt" => ["precipitation"],
      "acchilopprsty" => ["prophylactics"], "aaagiinnsssst" => ["assassinating"],
      "cdeegiilrrsty" => ["triglycerides"], "aaeeilnrrsttt" => ["transliterate"],
      "abbceeijlnoot" => ["objectionable"], "aegggiinrrttu" => ["regurgitating"],
      "abddeeiilnpty" => ["dependability"], "acceinnooprtt" => ["contraception"],
      "accghiilmnops" => ["accomplishing"], "aciiilmnoprsv" => ["provincialism"],
      "aeinooprssttt" => ["protestations"], "eeeilnopsssvx" => ["explosiveness"],
      "cceeilnoorttu" => ["electrocution"], "cciinnoorsstt" => ["constrictions"],
      "acfiimnnoorst" => ["confirmations"], "aaefilnqrrstu" => ["quarterfinals"],
      "abbeeilmprrtu" => ["imperturbable"], "aeegiinnoprrt" => ["peregrination"],
      "abeiimnossstu" => ["ambitiousness"], "abehllmopssuy" => ["blasphemously"],
      "acdeimnnnoost" => ["condemnations"], "adeeghiinnrst" => ["disheartening"],
      "aacdeeimnnott" => ["decontaminate"], "ceiimmnoprstu" => ["minicomputers"],
      "bddeeiirrsttu" => ["redistributed"], "abbbehlmorstu" => ["blabbermouths"],
      "ccceeefimnrru" => ["circumference"], "acdefilmnnotu" => ["malfunctioned"],
      "aegghiinnrstt" => ["straightening"], "abbeilmprrtuy" => ["imperturbably"],
      "adeeiinoorrtt" => ["deterioration"], "cdeiimmnoosss" => ["decommissions"],
      "cdeillnorsuuy" => ["incredulously"], "aabdeinsstttu" => ["substantiated"],
      "abdeegkllnowy" => ["knowledgeably"], "ceeeeffinsstv" => ["effectiveness"],
      "eeginnoppsstt" => ["steppingstone"], "aaccfiiilnort" => ["clarification"],
      "eiilmnoqrstuv" => ["ventriloquism"], "eefhilnssssst" => ["shiftlessness"],
      "adeimnnoorstt" => ["demonstration"], "addiiiilnstuv" => ["individualist"],
      "aabceehilmnpu" => ["unimpeachable"], "aghilnooortty" => ["orthogonality"],
      "aaaccillrssty" => ["sarcastically"], "ccilnoopssuuy" => ["conspicuously"],
      "aaciiinopprtt" => ["participation"], "aciinnoprrstt" => ["transcription"],
      "aciimnnoosstu" => ["sanctimonious"], "acceinnnoortt" => ["concentration"],
      "abciiilmoptty" => ["compatibility"], "aadehnorrsttw" => ["northeastward"],
      "aaddegghnrrtu" => ["granddaughter"], "adeeiimnnostt" => ["sedimentation"],
      "diilmnosttuuu" => ["multitudinous"], "aaciiopprrstt" => ["participators"],
      "aaeiloppprrty" => ["appropriately"], "aceiinooqstuv" => ["equivocations"],
      "aeefgiinorrrt" => ["refrigeration"], "abilmmnossstu" => ["somnambulists"],
      "aaaceegnrstvx" => ["extravagances"], "aaehimnpssstt" => ["statesmanship"],
      "aabdefgiilnty" => ["indefatigably"], "eegginorrrsst" => ["retrogressing"],
      "ceeehhmorsstt" => ["homestretches"], "acdeefginnort" => ["confederating"],
      "beiilnoprrssy" => ["irresponsibly"], "aeggiimnssttu" => ["guesstimating"],
      "cceegiinnoprv" => ["preconceiving"], "aaiinnoprrstt" => ["transpiration"],
      "cdeilnorsssuu" => ["ludicrousness"], "cdeginnooprrs" => ["corresponding"],
      "aaacehiimmntt" => ["mathematician"], "aeeinnoprsstt" => ["presentations"],
      "aeehimnqssssu" => ["squeamishness"], "bchiiiopsssty" => ["biophysicists"],
      "aaccdeimnnopu" => ["unaccompanied"], "eeknnoopssstu" => ["outspokenness"],
      "efgghiilnnrty" => ["frighteningly"], "cgiiilmnoorst" => ["criminologist"],
      "abelnopprstuu" => ["unsupportable"], "acilllmrttuuu" => ["multicultural"],
      "aciinnoooprrt" => ["incorporation"], "aabghiooprtuy" => ["autobiography"],
      "aaiillnnosstt" => ["installations"], "ceghinorstttu" => ["outstretching"],
      "aabcceiilmprt" => ["impracticable"], "degiiilnpsstt" => ["sidesplitting"],
      "aceeeimnnosst" => ["amniocenteses"], "deghinnoorstu" => ["undershooting"],
      "adeeginoprrsv" => ["overspreading"], "accegiinoprrt" => ["reciprocating"],
      "acdfilnnostuy" => ["dysfunctional"], "abgilmnosuuuy" => ["unambiguously"],
      "aacgiilnorstu" => ["cartilaginous"], "eiioprrssttuu" => ["surreptitious"],
      "cdeiimnooopst" => ["decomposition"], "adeeeimnrsttu" => ["underestimate"],
      "bceinnnossttu" => ["subcontinents"], "acgiiiimnnnrt" => ["incriminating"],
      "eghiimnoopssy" => ["physiognomies"], "abdehhnosssuu" => ["househusbands"],
      "acegiiinpprtt" => ["precipitating"], "agghhiilnoprt" => ["lithographing"],
      "aeegiimnnrttx" => ["exterminating"], "aacdiiiorttvy" => ["radioactivity"],
      "aeiimnnooprst" => ["impersonation"], "cdehillooprsy" => ["policyholders"],
      "adeeghprssttu" => ["stepdaughters"], "aafiiilmnrtuy" => ["unfamiliarity"],
      "eeeiinorsstvv" => ["oversensitive"],
      "accefiiinortt" => ["rectification", "certification"],
      "deeellnnprsty" => ["resplendently"], "acdeeilmnpsst" => ["displacements"],
      "eeiiiinsssttv" => ["sensitivities"], "aaceehimnnopt" => ["acetaminophen"],
      "aceghiimoprss" => ["seismographic"], "acdinooqrsstu" => ["conquistadors"],
      "aceginooprstt" => ["prognosticate"], "adeeeggimnnst" => ["disengagement"],
      "acegghiinnnrt" => ["interchanging"], "acghillmooopr" => ["morphological"],
      "aabiilnnssttu" => ["insubstantial"], "acehhmmnrstuy" => ["chrysanthemum"],
      "achillorrttuu" => ["horticultural"], "cdeeffhiloors" => ["officeholders"],
      "acddeiinnortt" => ["indoctrinated"], "befiiiillntxy" => ["inflexibility"],
      "aceiinorssttu" => ["resuscitation"], "adiiilmnrsstu" => ["industrialism"],
      "eeilnoprsttuy" => ["pretentiously"], "adeeeiimnrstt" => ["intermediates"],
      "aeegiimnnortt" => ["regimentation"], "abceilnnostty" => ["incontestably"],
      "acdeimmnnoost" => ["commendations"], "abcghiklnssuw" => ["swashbuckling"],
      "aeefhhllnsstu" => ["healthfulness"], "eeeimnprrssst" => ["misrepresents"],
      "cdeennooprsst" => ["corespondents"], "eehlnorsssstw" => ["worthlessness"],
      "aaaeglllmoprr" => ["parallelogram"], "ceiinnooprstt" => ["introspection"],
      "deeeeinprrrtt" => ["reinterpreted"], "aabelmmnosswy" => ["assemblywoman"],
      "cdeeiilnosssu" => ["deliciousness"], "aceelmmnoprty" => ["complementary"],
      "aeggimmnoprrr" => ["reprogramming"], "aeghhiprssuwy" => ["superhighways"],
      "aaceiilnprstt" => ["antiparticles", "paternalistic"],
      "aeilnoopsttux" => ["expostulation"], "aaacceiinpstt" => ["incapacitates"],
      "bddeeiilnosty" => ["disobediently"], "aabcceeirrsuu" => ["bureaucracies"],
      "cdeeeeeilnort" => ["electioneered"], "aaacillmottuy" => ["automatically"],
      "aadginopprsst" => ["propagandists"], "cdeinnooprtuv" => ["nonproductive"],
      "aadeefnsssstt" => ["steadfastness"], "aaeeglmnorstv" => ["galvanometers"],
      "aegilmnorsstu" => ["somersaulting"], "cddeeiinnoort" => ["reconditioned"],
      "adeggimmnoprr" => ["deprogramming"], "aeeeghmnoprst" => ["magnetosphere"],
      "acchimmnooort" => ["monochromatic"], "abeeeeflnorsu" => ["unforeseeable"],
      "eiioprsssttuu" => ["superstitious"], "acdeegimmnnor" => ["commandeering"],
      "aaacdeeinpprs" => ["disappearance"], "bcddeeeimnrsu" => ["disencumbered"],
      "aadeegimnprst" => ["disparagement"], "aceefinossstu" => ["facetiousness"],
      "adegiimmnnrst" => ["masterminding"], "adefillssttuy" => ["distastefully"],
      "aacceillmsstu" => ["miscalculates"], "aeehinnopprss" => ["apprehensions"],
      "adiiillnosstt" => ["distillations"], "efillllmosuuy" => ["mellifluously"],
      "aacegilnnpstu" => ["encapsulating"], "accgiimmnnotu" => ["communicating"],
      "aceeghilnnosu" => ["housecleaning"], "aeeilnnnoprst" => ["antipersonnel"],
      "accefgiiinrtt" => ["certificating"], "aadiillnortty" => ["traditionally"],
      "aacceknortttu" => ["counterattack"], "acdeeimnorstu" => ["documentaries"],
      "aiillnooprsvy" => ["provisionally"], "aaciillnprtuy" => ["puritanically"],
      "ceghhiiloprsy" => ["hieroglyphics"], "aaegimnrrsstt" => ["transmigrates"],
      "accdinoorrtty" => ["contradictory"], "aeiinnopssstx" => ["expansionists"],
      "ddeefhiiimrsu" => ["dehumidifiers"], "aeegllmnnntuy" => ["ungentlemanly"],
      "eiiimnoprssst" => ["impressionist"], "aannorrsstuuy" => ["tyrannosaurus"],
      "acceehirrsttu" => ["architectures"], "aaacilnnrsttt" => ["transatlantic"],
      "aabdeefgiilnt" => ["indefatigable"], "aciinnorssttu" => ["incrustations"],
      "abbcegiklnrry" => ["blackberrying"], "deefgiinnprrt" => ["fingerprinted"],
      "aeefinnorsssu" => ["nefariousness"], "aaabegiilmnty" => ["manageability"],
      "aaegggilmnort" => ["agglomerating"], "acceemnorrstt" => ["concertmaster"],
      "accefiiinopst" => ["specification"], "aceoprrsssstt" => ["sportscasters"],
      "aaciiinnopstt" => ["anticipations"], "ccceioopprsst" => ["spectroscopic"],
      "beilnorstuuvy" => ["unobtrusively"], "aaeilnooprttx" => ["extrapolation"],
      "acccdeimnrstu" => ["circumstanced"], "acddefhiinrss" => ["disfranchised"],
      "abeeiilrrrtvy" => ["irretrievably"], "eghhiinopprsw" => ["horsewhipping"],
      "cceiimnoosssu" => ["semiconscious"], "deeginnorsuvz" => ["rendezvousing"],
      "aaabceeilnrst" => ["ascertainable"], "abcdeiiilnort" => ["bidirectional"],
      "abbceijlnooty" => ["objectionably"], "beeeehilnprrs" => ["reprehensible"],
      "acehhopprstyy" => ["psychotherapy"], "eiiimnnorssst" => ["intermissions"],
      "afgiiilnnrtuy" => ["infuriatingly"], "aaacgilmmnrtu" => ["ungrammatical"],
      "egiiilnossstu" => ["litigiousness"], "aehimmooprsst" => ["metamorphosis"],
      "aabeeghiknrrt" => ["heartbreaking"], "aeinooopprrtt" => ["proportionate"],
      "efgghiiinprtz" => ["prizefighting"], "deiinoopsssss" => ["dispossession"],
      "acceeilorsttt" => ["electrostatic"], "aacghiillnntu" => ["hallucinating"],
      "abdeiilnnpssy" => ["indispensably"], "aeeelnssssstt" => ["tastelessness"],
      "aacefmnrrstuu" => ["manufacturers"], "deefiilnnrstu" => ["unfriendliest"],
      "agghiiknnsstv" => ["thanksgivings"], "aceimmmnooort" => ["commemoration"],
      "abdiiiilmssty" => ["admissibility"], "bciinoprssstu" => ["subscriptions"],
      "ceemopprrstuu" => ["supercomputer"], "abeelmmnosswy" => ["assemblywomen"],
      "acdeefhhiknrs" => ["handkerchiefs"], "cfimnnnooorty" => ["nonconformity"],
      "aacdelmnnrssu" => ["underclassman"], "aeeilmnnnsttu" => ["unsentimental"],
      "aegginnrrssst" => ["transgressing"], "acccdeeeinnns" => ["incandescence"],
      "bbceiilmnostu" => ["incombustible"], "acciimmnnootu" => ["communication"],
      "cdeinooprrstu" => ["reproductions"], "aceeglmnoorst" => ["conglomerates"],
      "cdeeeeiinnprx" => ["inexperienced"], "aceeooprrsttt" => ["protectorates"],
      "aabceeggprrst" => ["carpetbaggers"], "acegghinprrsu" => ["supercharging"],
      "aceeiilnrttvy" => ["interactively"], "adiilnopsttuu" => ["platitudinous"],
      "aacdeillnotuy" => ["educationally"], "aaddeiimnrstt" => ["administrated"],
      "aaeegginorstx" => ["exaggerations"], "abcflnooorrsu" => ["fluorocarbons"],
      "aeeiilnoprsst" => ["personalities"], "efgimnooprrtu" => ["outperforming"],
      "ceeiinoprsttv" => ["introspective"], "egghiiinnstux" => ["extinguishing"],
      "aceehillortty" => ["theoretically"], "cdiiinnosttuy" => ["discontinuity"],
      "chlnnoorssuyy" => ["synchronously"], "aabcllooorrst" => ["collaborators"],
      "ceefllorrsuuy" => ["resourcefully"], "abcdehiilnnrr" => ["brainchildren"],
      "acdeeghhooprr" => ["choreographed"], "ceegilmmnnopt" => ["complementing"],
      "abdegiilmnsss" => ["disassembling"], "acceinoopprtu" => ["preoccupation"],
      "cgilnnoorsuuy" => ["incongruously"], "cdeeeiilnnqsu" => ["delinquencies"],
      "aaegimnnosttu" => ["augmentations"], "aaceillmnptuy" => ["pneumatically"],
      "cdeeemnnnostu" => ["denouncements"], "aeeimnorrsttx" => ["exterminators"],
      "aaceghilllrty" => ["lethargically"], "cdegiinnnostt" => ["discontenting"],
      "aabdeginorrtw" => ["waterboarding"], "dhinooorssttt" => ["orthodontists"],
      "aabbeiinorstv" => ["abbreviations"], "cdeennrrrstuu" => ["undercurrents"],
      "eeinnoprsttuu" => ["unpretentious"], "acginoprssstt" => ["sportscasting"],
      "aegghilnoortw" => ["woolgathering"], "adeegiinrsstt" => ["disintegrates"],
      "cehiiknopsssy" => ["psychokinesis"], "aiillnorssttu" => ["illustrations"],
      "aiiimnnorsstt" => ["ministrations"], "aadegimnrrstt" => ["transmigrated"],
      "aeeghnoprrsst" => ["stenographers"], "aaciilmnorttu" => ["matriculation"],
      "aefgilmnorrtu" => ["reformulating"], "ddeeeilnnnpty" => ["independently"],
      "egiinnnoqstuu" => ["unquestioning"], "aghhllmooopty" => ["ophthalmology"],
      "aceeegmnnortu" => ["encouragement"], "adeeellmorrst" => ["steamrollered"],
      "aeeemnrssssst" => ["reassessments"], "aacdeiinnpttu" => ["unanticipated"],
      "abceelnnoopru" => ["pronounceable"], "cdeeilrsttuvy" => ["destructively"],
      "aabeehiilrstt" => ["rehabilitates"], "abcddeeiilrst" => ["discreditable"],
      "acceiimmnotuv" => ["communicative"], "acegginnoorst" => ["congregations"],
      "aaahiinorrttu" => ["authoritarian"], "ceeeioprrsttv" => ["retrospective"],
      "acdeegnnosstt" => ["decongestants"], "abeehiilnstux" => ["inexhaustible"],
      "eiiiilnqstuvy" => ["inquisitively"], "aciilnnorsttu" => ["instructional"],
      "abceenoprrstu" => ["protuberances"], "aaeillnnossty" => ["sensationally"],
      "cceegilnorttu" => ["electrocuting"], "aabceggginprt" => ["carpetbagging"],
      "eeeeimnprrstx" => ["experimenters"], "acfimnnooorst" => ["conformations"],
      "eegiilllnntty" => ["intelligently"], "adeilmnnoprty" => ["predominantly"],
      "aiimnooqssttu" => ["misquotations"], "begilmoorssty" => ["embryologists"],
      "aceeinooprtuv" => ["uncooperative"], "adeeeimnnortu" => ["mountaineered"],
      "ceegilmmnottu" => ["telecommuting"], "agiiinnnorstt" => ["transitioning"],
      "cdiinnoosstuu" => ["discontinuous"], "abeefglnorttu" => ["unforgettable"],
      "aeilmnnrssttu" => ["instrumentals"], "aaefiimnnostt" => ["manifestation"],
      "adiiilmnosstu" => ["dissimulation"], "cefghikmnortu" => ["motherfucking"],
      "adeegiinorrtt" => ["deteriorating"], "cddeiiilnnpsu" => ["undisciplined"],
      "cceiillossttv" => ["collectivists"], "ddehilnnooprs" => ["philodendrons"],
      "aceehmnopprrt" => ["rapprochement"], "cdeeefilnsstu" => ["deceitfulness"],
      "aeeiilnnorrtt" => ["interrelation"], "adeefiiloqruv" => ["overqualified"],
      "acdeeikloopss" => ["kaleidoscopes"], "aeeillmnnstty" => ["sentimentally"],
      "agghilooprsst" => ["graphologists"], "ggghhinooortu" => ["thoroughgoing"],
      "ceiijnooprstt" => ["projectionist"], "ehiorrrstttuw" => ["trustworthier"],
      "eeegiorrrsstv" => ["retrogressive"], "achiimnnoopps" => ["companionship"],
      "adfgiiilnqsuy" => ["disqualifying"], "cdelmnnooooty" => ["monocotyledon"],
      "aceiiiilmprst" => ["imperialistic"], "aaceglnorsttu" => ["congratulates"],
      "aaacgillmprty" => ["pragmatically"], "acdegiilllooy" => ["ideologically"],
      "cdfgiimnoorst" => ["discomforting"], "aabceinrrsstt" => ["scatterbrains"],
      "ademnoorrsstt" => ["demonstrators"], "aceehimnorsss" => ["marchionesses"],
      "eefgiimnnnrst" => ["infringements"], "acdeggiklnnow" => ["acknowledging"],
      "ceeefinorrttu" => ["counterfeiter"], "ddeeghiilmstw" => ["middleweights"],
      "ceeeeinrssstv" => ["secretiveness"], "aegimnopprstu" => ["mousetrapping"],
      "aciiilnoosstt" => ["solicitations"], "degiilnrsssty" => ["distressingly"],
      "aabeilmnrsttt" => ["transmittable"], "abbcdeiilnrsy" => ["indescribably"],
      "adgiiinnoppst" => ["disappointing"], "bbcgghiilnntu" => ["nightclubbing"],
      "aehimnnprsstt" => ["transshipment"], "accdeeiinprss" => ["discrepancies"],
      "beeiiilmmprss" => ["impermissible"], "acehlmoorssst" => ["schoolmasters"],
      "acfiiimmmnotu" => ["mummification"], "aaeillnooprty" => ["operationally"],
      "dfillrssttuuy" => ["distrustfully"], "aeghimnorssuw" => ["housewarmings"],
      "eiilnoqrsttuv" => ["ventriloquist"], "aaggiilnnottu" => ["agglutination"],
      "aceillnnoostt" => ["constellation"], "adeiinnopssst" => ["dispensations"],
      "aeeehlnpsssss" => ["shapelessness"], "acegiilnosttu" => ["gesticulation"],
      "aagiiklnnpsty" => ["painstakingly"], "deiilmnoprtvy" => ["improvidently"],
      "cfghilmnooorr" => ["chloroforming"], "aacgilllnosty" => ["nostalgically"],
      "aaccehilrrttu" => ["architectural"], "eghiiimnoprsv" => ["impoverishing"],
      "aeeeklrrssttw" => ["streetwalkers"], "cdeehillnssss" => ["childlessness"],
      "aaeimnnnoortt" => ["ornamentation"], "aeeehlorsstux" => ["heterosexuals"],
      "adeiiimnnosst" => ["dissemination"], "acdeeeiossttv" => ["videocassette"],
      "aabbdeefglrst" => ["flabbergasted"], "ccciiimnorssu" => ["circumcisions"],
      "adeggiilnnrss" => ["niggardliness"], "eeiinoprssstx" => ["expressionist"],
      "addeimnnrsstu" => ["misunderstand"], "aaceinoprrstt" => ["procrastinate"],
      "ceginrrrsttuu" => ["restructuring"], "eghiilnprssst" => ["sprightliness"],
      "ceehimnnooprs" => ["comprehension"], "ceiinnorrsstu" => ["insurrections"],
      "ceeinooprrstt" => ["retrospection"], "afggiinnrrstu" => ["transfiguring"],
      "aacdeiilnortv" => ["valedictorian"], "aceeghprrrssu" => ["superchargers"],
      "abcinoooorrrt" => ["corroboration"], "diinooopprrst" => ["disproportion"],
      "eiioopprssstu" => ["suppositories"], "acdeeglmnoort" => ["conglomerated"],
      "dehmnorrssttu" => ["thunderstorms"], "aeeehlnrsssst" => ["heartlessness"],
      "aaiillmnnottu" => ["multinational"], "ceeghinorttuw" => ["counterweight"],
      "aacillmnopsty" => ["complaisantly"], "aaceilnnopstu" => ["encapsulation"],
      "aaccegiilnrtt" => ["intergalactic"], "aceinnoorsstv" => ["conversations"],
      "aabelnoprrstt" => ["transportable"], "eeeghilmnnntt" => ["enlightenment"],
      "cdeefinnoortv" => ["overconfident"], "aceeilllnsttu" => ["intellectuals"],
      "accdeiikloops" => ["kaleidoscopic"], "aadehorssttuw" => ["southeastward"],
      "aaaeginnnnors" => ["nonagenarians"], "aaelnprrsstuu" => ["supernaturals"],
      "aceeeglmnortt" => ["electromagnet"], "ceeiinnorssst" => ["intercessions"],
      "aabceefiprrst" => ["prefabricates"], "aacdiiillmoty" => ["idiomatically"],
      "aabciilmoprty" => ["comparability"], "aeimnooprrsst" => ["impersonators"],
      "aceiillnrstxy" => ["extrinsically"], "aceeehiorrsvv" => ["overachievers"],
      "acdeiinorrsty" => ["discretionary"], "aaaaillprrsss" => ["sarsaparillas"],
      "hiilloopprsww" => ["whippoorwills"], "aabegilmnprtu" => ["perambulating"],
      "acddeiiimnrst" => ["discriminated"], "cdeeiilnoprst" => ["predilections"],
      "aacfgimnnrtuu" => ["manufacturing"], "deeilnnosttuy" => ["tendentiously"],
      "aaddgginnnrst" => ["grandstanding"], "acehiiprttvyy" => ["hyperactivity"],
      "adeeegimnrsst" => ["disagreements"], "giinnooopprrt" => ["proportioning"],
      "aegiimnnrrrty" => ["intermarrying"], "cdeeghimnnopr" => ["comprehending"],
      "acceiilmnosss" => ["neoclassicism"], "acdefiinnsstt" => ["disinfectants"],
      "adegimnnorstt" => ["demonstrating"], "aehhiopprstyy" => ["physiotherapy"],
      "cccdeeeenrrsu" => ["recrudescence"], "abdiinnoorstu" => ["subordination"],
      "aeehmmooprsst" => ["metamorphoses"], "acceehilmoprt" => ["petrochemical"],
      "cfimnnnooorst" => ["nonconformist"], "eghiiilnnqrsu" => ["relinquishing"],
      "aceegillmorty" => ["geometrically"], "abceeiilnnnst" => ["bicentennials"],
      "abbennnoorsst" => ["nonabsorbents"], "beeinorssstuv" => ["obtrusiveness"],
      "bbdeelnrsssuu" => ["blunderbusses"], "bdeeginnorruv" => ["overburdening"],
      "cfghiillnnnuy" => ["unflinchingly"], "acceghillnoot" => ["technological"],
      "aeeillprstuvy" => ["superlatively"], "deghiiiinnrst" => ["disinheriting"],
      "beeeiilnprssx" => ["inexpressible"], "aciinnnooprtu" => ["pronunciation"],
      "bdeeegiinnrrt" => ["interbreeding"], "abbiiilmoprty" => ["improbability"],
      "deeinnprrttuu" => ["uninterrupted"], "aeghimnorttuw" => ["mouthwatering"],
      "aaegiilnopsst" => ["angioplasties"], "aacegiinnnrrt" => ["reincarnating"],
      "aeeiiilmnprrs" => ["preliminaries"], "achhiimnoppss" => ["championships"],
      "beeehillmmnst" => ["embellishment"], "aaccehillmsty" => ["schematically"],
      "ailnooopprrst" => ["proportionals"], "acdeiinnoorst" => ["consideration"],
      "acddeeehinruv" => ["underachieved"], "eefghiilrsttw" => ["weightlifters"],
      "ccdeenorrsttu" => ["reconstructed"], "cceiimnnortuv" => ["circumvention"],
      "cceeghikllnps" => ["spellchecking"], "ceillmnoostty" => ["tonsillectomy"],
      "aeginnorrssst" => ["transgression"], "acehnnooprrss" => ["anchorpersons"],
      "aeefgiorrrrst" => ["refrigerators"], "eeeghimnosstu" => ["meetinghouses"],
      "acefgiilmnnty" => ["magnificently"], "befgiiilnrstu" => ["filibustering"],
      "abbcdeeiilnrs" => ["indescribable"], "adeelnnsssstu" => ["dauntlessness"],
      "giiilmnnoosuy" => ["ignominiously"], "ceeefimnnorrt" => ["reinforcement"],
      "eeehmnnnorstt" => ["enthronements"], "aiilnooopprst" => ["propositional"],
      "eiiinnooprstt" => ["interposition"], "ceeeehlnrssss" => ["cheerlessness"],
      "aacgiiinpprtt" => ["participating"], "beeiilnoprrss" => ["irresponsible"],
      "diilnorsstuuy" => ["industriously"], "degiinnnnprsu" => ["underpinnings"],
      "accdiimmnnoou" => ["incommunicado"], "acegiinoorsst" => ["cosignatories"],
      "aabceeikmnrst" => ["cabinetmakers"], "ceeehimnoprsv" => ["comprehensive"],
      "cceefinnoorst" => ["confectioners"], "aceeiinnrsttu" => ["uncertainties"],
      "eggilnooorstt" => ["gerontologist"], "eeeiinnsssstv" => ["sensitiveness"],
      "acdeegiimorst" => ["tragicomedies"], "aciilllmooqsu" => ["colloquialism"],
      "accdhhinoopry" => ["hypochondriac"], "biinossstttuu" => ["substitutions"],
      "adeegiknnrrst" => ["kindergartens"], "cdeeeeinpsstv" => ["deceptiveness"],
      "acegillmnooot" => ["entomological"], "aacegillllory" => ["allegorically"],
      "aefiilllnntuy" => ["influentially"], "aabcefiiinott" => ["beatification"],
      "aefghhorstttu" => ["afterthoughts"], "efhioopprrsss" => ["professorship"],
      "cddeeeennprtu" => ["unprecedented"], "acdeimnnoottu" => ["documentation"],
      "acdiilnnnootu" => ["unconditional"], "acceiilmmmors" => ["commercialism"],
      "accfiinnoosst" => ["confiscations"], "aafiilmmnnost" => ["inflammations"],
      "egiilmoosssst" => ["seismologists"], "aaddeegnrrtuu" => ["undergraduate"],
      "ahimnopprssst" => ["sportsmanship"], "aabceilloortv" => ["collaborative"],
      "acehiiopssstt" => ["sophisticates"], "aaaabcceelrtu" => ["baccalaureate"],
      "begggiijnrttu" => ["jitterbugging"], "aeiinoopprrtx" => ["expropriation"],
      "ceimnnooprssu" => ["mispronounces"], "aaacehillptty" => ["apathetically"],
      "eegilmnnppstu" => ["supplementing"], "aabelmoprrstu" => ["perambulators"],
      "eehlnorrsttwy" => ["northwesterly"], "aacdillmopssy" => ["spasmodically"],
      "adegjlmnnnotu" => ["nonjudgmental"], "aeiillnnnotty" => ["intentionally"],
      "aceghinorrstt" => ["orchestrating"], "adeehhimoprrt" => ["hermaphrodite"],
      "aefiilnooprrt" => ["proliferation"], "aacilmnooprst" => ["proclamations"],
      "aaaaccdiiklls" => ["lackadaisical"], "adeiioooprsst" => ["radioisotopes"],
      "aaaciillmotxy" => ["axiomatically"], "afiillorsttuy" => ["flirtatiously"],
      "adeeilnnrttvy" => ["inadvertently"], "eeiiimopprrst" => ["improprieties"],
      "cdeiijnosssuu" => ["judiciousness"], "bciinnoorsttu" => ["contributions"],
      "adegilnnoqrtu" => ["grandiloquent"], "adiilnnnorstu" => ["nonindustrial"],
      "ccegiiimnnosv" => ["misconceiving"], "aaiiilnnoprst" => ["inspirational"],
      "eiiiinnssttvy" => ["insensitivity"], "cceeefilnnors" => ["inflorescence"],
      "aaegimnnorttu" => ["argumentation"], "aceehiinorstt" => ["theoreticians"],
      "adegiimnnoprt" => ["predominating"], "aeeeimnnnrttt" => ["entertainment"],
      "acdehimmnorty" => ["thermodynamic"], "acdgiiloorsst" => ["cardiologists"],
      "aefilnooprsss" => ["professionals"], "aabeemmnrrsst" => ["embarrassment"],
      "cghiloopsssty" => ["psychologists"], "adeiimnnosstu" => ["mountainsides"],
      "ceeghiilnoprt" => ["helicoptering"], "aaiiilnorrtty" => ["irrationality"],
      "aaeggilmnoort" => ["agglomeration"], "abceiilmnopst" => ["incompatibles"],
      "behlooorssttu" => ["troubleshoots"], "acceilnnosstu" => ["consultancies"],
      "ceemnnnooprtu" => ["pronouncement"], "aachillnortuy" => ["hallucinatory"],
      "accchiloopsty" => ["staphylococci"], "aagggiilnnttu" => ["agglutinating"],
      "aabdeekorrsst" => ["skateboarders"], "abcceiilnnovy" => ["inconceivably"],
      "aeeiillnsttxy" => ["existentially"], "aabeinssstttu" => ["substantiates"],
      "adeeimnorsttv" => ["demonstrative"], "cceffiiinnsuy" => ["insufficiency"],
      "acddeemnnortu" => ["countermanded"], "aeeeimnnrsttt" => ["reinstatement"],
      "cehiilmossuvy" => ["mischievously"], "aaacegilmmnos" => ["megalomaniacs"],
      "egiillnnnssuw" => ["unwillingness"], "ceeiilmopttvy" => ["competitively"],
      "acfgiinnoortu" => ["configuration"], "acdegghinnrru" => ["undercharging"],
      "aaceilmoprtvy" => ["comparatively"], "aeghhiooprrst" => ["orthographies"],
      "abccnoorrsttu" => ["subcontractor"], "aceehimnssstt" => ["chastisements"],
      "acehimnpsttuy" => ["unsympathetic"], "abeeeinrrsttv" => ["invertebrates"],
      "aaaghirssttwy" => ["straightaways"], "cdgiiinnnostu" => ["discontinuing"],
      "aegiilmnorsst" => ["mineralogists"], "aceilmmnoprty" => ["complimentary"],
      "egilnopprsuvy" => ["oversupplying"], "adeeegoprrtuy" => ["daguerreotype"],
      "aaceiinopprst" => ["appreciations"], "adgiiilmnsstu" => ["dissimulating"],
      "cdeiinnooprst" => ["preconditions"], "aeeegmnnrsstt" => ["estrangements"],
      "aacdeeilprttu" => ["recapitulated"], "aaeeillnrttvy" => ["alternatively"],
      "aaacehimooppr" => ["pharmacopoeia"], "aeegiilmnorss" => ["generalissimo"],
      "eeeeinnssstvx" => ["extensiveness"], "ccceghiknorss" => ["crosschecking"],
      "aaceiiilmrstt" => ["materialistic"], "aabceillmoprt" => ["problematical"],
      "deeeefinnsssv" => ["defensiveness"], "abcceehkrsstt" => ["backstretches"],
      "acceiiklnostw" => ["anticlockwise"], "aacghilopprty" => ["typographical"],
      "cdiinnoorsttu" => ["introductions"], "deiinooopprst" => ["propositioned"],
      "cceeillnoorst" => ["recollections"], "aiiilprsssttu" => ["spiritualists"],
      "eeelnoprssssw" => ["powerlessness"], "acdeiimnoostt" => ["domestication"],
      "eeeeghnoorstu" => ["heterogeneous"], "acceilmnorstu" => ["counterclaims"],
      "ceiilopprstuy" => ["precipitously"], "cegiilmmnnopt" => ["complimenting"],
      "aceelmnpprssu" => ["upperclassmen"], "ccdeiinnnoost" => ["disconnection"],
      "aaaeilmnprrty" => ["parliamentary"], "aaddeelnrttuu" => ["unadulterated"],
      "aachlnopsstyy" => ["psychoanalyst"], "aiinnooprsstt" => ["transposition"],
      "cciinnoopssuu" => ["inconspicuous"], "aaabcegilllry" => ["algebraically"],
      "acegmnnoorssw" => ["congresswoman"], "abdeghinoorsu" => ["boardinghouse"],
      "aabeiinrrrsst" => ["arbitrariness"], "adeghinoorsvw" => ["overshadowing"],
      "aiijnoopsttux" => ["juxtaposition"], "abccdenorsttu" => ["subcontracted"],
      "aacddeeeffint" => ["decaffeinated"], "addeeeehnrrtt" => ["tenderhearted"],
      "aceilmnnooptt" => ["contemplation"], "aaciiilnnostt" => ["nationalistic"],
      "aaceghoprrrst" => ["cartographers"], "aacimnnoopswy" => ["companionways"],
      "eeiiilnnsstvy" => ["insensitively"], "aeeegillnsttv" => ["televangelist"],
      "eeeffinnosssv" => ["offensiveness"], "beeiiiilnssst" => ["sensibilities"],
      "aadejlmmnsttu" => ["maladjustment"], "aeimnnoopprtt" => ["apportionment"],
      "aaeegimnrttuv" => ["argumentative"], "acdgiilnnoost" => ["consolidating"],
      "aaceehnnppsst" => ["happenstances"], "eeeiinnnsstvv" => ["inventiveness"],
      "cgiilmoossstu" => ["musicologists"], "eeiinnnorsttv" => ["interventions"],
      "addiiiilntuvy" => ["individuality"], "adeeloopprtuv" => ["overpopulated"],
      "ddeimnoorsstu" => ["misunderstood"], "accghilloopsy" => ["psychological"],
      "eiimmnnoprsst" => ["imprisonments"], "aaciilnorsttu" => ["articulations"],
      "aabbeiillossu" => ["bouillabaisse"], "aabegilnorrtu" => ["gubernatorial"],
      "aabeiilmnorst" => ["abnormalities"], "abeeelnnprtuv" => ["unpreventable"],
      "aacdeinosssuu" => ["audaciousness"], "aefgiilnoprrt" => ["proliferating"],
      "aelnnoopsstuy" => ["spontaneously"], "beefginrrsttu" => ["butterfingers"],
      "aabcdeefiprrt" => ["prefabricated"], "bdeeeimmmnrst" => ["dismemberment"],
      "aeeiinnoqrstu" => ["questionnaire"], "cceehilooprtt" => ["photoelectric"],
      "ceeinoprrsssu" => ["repercussions"], "acdeeiimnnrty" => ["indeterminacy"],
      "cceeeeeffnrsv" => ["effervescence"], "aaadeillqrrtu" => ["quadrilateral"],
      "acegilmnnoptt" => ["contemplating"], "aaegilnoprttx" => ["extrapolating"],
      "ceeeilnsssuvx" => ["exclusiveness"], "acdiilnnooost" => ["consolidation"],
      "adeghllnorsst" => ["strangleholds"], "acceginnnnotu" => ["countenancing"],
      "aeggiinnorrtt" => ["interrogating"], "abeeehilrssst" => ["reestablishes"],
      "aacceimmnnopt" => ["accompaniment"], "aabeilnoorstv" => ["observational"],
      "cdeeginnorstu" => ["countersigned"], "aeelmnpprstuy" => ["supplementary"],
      "aeeeglmnnnstt" => ["entanglements"], "abdehilmnnsst" => ["blandishments"],
      "eeghinorssstu" => ["righteousness"], "aabbehiilnntu" => ["uninhabitable"],
      "achhiilmnoprs" => ["philharmonics"], "eefghiiprrstz" => ["prizefighters"],
      "aaceennpprstu" => ["appurtenances"], "aeehlorssttuy" => ["southeasterly"],
      "bdeiiorrrsttu" => ["redistributor"], "aegimnnorrstt" => ["remonstrating"],
      "abefllnoopstu" => ["tablespoonful"], "adeeginopprsv" => ["eavesdropping"],
      "ceeehlnnosttu" => ["luncheonettes"], "ccceiimnoooos" => ["socioeconomic"],
      "bcdeiiiilnrty" => ["incredibility"], "cceiinnoosstu" => ["conscientious"],
      "achiiprssstty" => ["psychiatrists"], "aaceehillstty" => ["aesthetically"],
      "cdeeijnprrsuu" => ["jurisprudence"], "aaciimmorssst" => ["commissariats"],
      "adeeiimnnortt" => ["determination"], "abcceeiilnnov" => ["inconceivable"],
      "aeegillmoopss" => ["megalopolises"], "bcerrsssttuuu" => ["substructures"],
      "acfiiillnnotu" => ["nullification"], "ddeeghhinrtuw" => ["hundredweight"],
      "aacfgilnnoort" => ["conflagration"], "aceinoorssstu" => ["atrociousness"],
      "aaacgillmmrty" => ["grammatically"], "ceiinoorsstuv" => ["insectivorous"],
      "bceghilnoooty" => ["biotechnology"], "aadeiimnrsstt" => ["administrates"],
      "bcddgillnooru" => ["bloodcurdling"], "acdeeilnpprru" => ["perpendicular"],
      "ceginnoorrttv" => ["controverting"], "cceeinnnorstt" => ["interconnects"],
      "aagilmmnnosuy" => ["magnanimously"], "aceeilnnrssuy" => ["unnecessarily"],
      "acehillopprty" => ["prophetically"], "adeiimnnnoost" => ["denominations"],
      "cceegiinnnost" => ["contingencies"], "aabceilmnnoop" => ["companionable"],
      "aeghnoopprrrs" => ["pornographers"], "ccehhiinoprsz" => ["schizophrenic"],
      "aagiimnopprtx" => ["approximating"], "adgilnnosttuy" => ["outstandingly"],
      "abeeilmnnnotu" => ["unmentionable"], "aaccllnorttuy" => ["contractually"],
      "aceehlorrstuy" => ["treacherously"], "ceeimnnoorsuu" => ["unceremonious"],
      "eeellmorrsssy" => ["remorselessly"], "aaaceeenpprrs" => ["reappearances"],
      "aeegiilnnrrtt" => ["interrelating"], "cegilmooosstt" => ["cosmetologist"],
      "aaccdeiinortt" => ["accreditation"], "cegiiinnorstu" => ["incongruities"],
      "abceelmmnorsu" => ["commensurable"], "aceillnoquuvy" => ["unequivocally"],
      "eennorsssstuu" => ["strenuousness"], "aachimmnnopsy" => ["nymphomaniacs"],
      "aciilnoppsstu" => ["supplications"], "eghiilnnssstu" => ["unsightliness"],
      "aaccdgimmnoot" => ["accommodating"], "ceefinoorsssu" => ["ferociousness"],
      "addeegiinrstt" => ["disintegrated"], "aacilmnoopttu" => ["computational"],
      "cddehlnorstuu" => ["thunderclouds"], "aeginoorrrstt" => ["interrogators"],
      "abceelnnoqruu" => ["unconquerable"], "adegiiimnnrst" => ["administering"],
      "aacdeglmnnors" => ["scandalmonger"], "cilmooprssuuy" => ["promiscuously"],
      "aceilnooprsss" => ["processionals"], "ahiimnoprsstt" => ["misanthropist"],
      "aeeeinnpsssvx" => ["expansiveness"], "aeehlnorrstty" => ["northeasterly"],
      "aceelmnnorstu" => ["nomenclatures"], "acceginnnortt" => ["concentrating"],
      "aafilmmnoorst" => ["malformations"], "acefiillprsuy" => ["superficially"],
      "adeeinoopprrt" => ["reapportioned"], "acddeghilnnrr" => ["grandchildren"],
      "egilmnooosstt" => ["entomologists"], "eemmnnoossstu" => ["momentousness"],
      "accceeiilssst" => ["ecclesiastics"], "aabcdeennoruv" => ["overabundance"],
      "ceeffiiilnnty" => ["inefficiently"], "abdeeegkllnow" => ["knowledgeable"],
      "ceeiinnorsstt" => ["intersections"], "aeiilnnooprtt" => ["interpolation"],
      "abeiiillnrtuy" => ["unreliability"], "abdeeiilnorst" => ["deliberations"],
      "aaciillssttty" => ["statistically"], "aeeeinnsstttv" => ["attentiveness"],
      "acgiinnooprrt" => ["incorporating"], "aabccelnnotuu" => ["unaccountable"],
      "aceegiilnnrtv" => ["cantilevering"], "aacegillrstty" => ["strategically"],
      "aaddeefghnrrt" => ["grandfathered"], "aaccillnsttyy" => ["syntactically"],
      "aefginooprrtw" => ["waterproofing"], "cceillooopsss" => ["oscilloscopes"],
      "aeggiiinnsttv" => ["investigating"], "aceeimmmoortv" => ["commemorative"],
      "accinprsttuuu" => ["acupuncturist"], "aaceiklmnopst" => ["kleptomaniacs"],
      "cdeeennnosstt" => ["contentedness"], "abdeffhlorssu" => ["shuffleboards"],
      "aabceeeillprr" => ["irreplaceable"], "aciilllssttyy" => ["stylistically"],
      "adeeeillmmoss" => ["mademoiselles"], "ccdeehklosttu" => ["shuttlecocked"],
      "acimmnnoosstu" => ["consummations"], "begiiiiillnty" => ["ineligibility"],
      "aciinnnoosttu" => ["continuations"], "cddgilllmnooy" => ["mollycoddling"],
      "aeegiiinsttvv" => ["investigative"], "abeeklmorrstu" => ["troublemakers"],
      "aaceiimmosttu" => ["semiautomatic"], "aceggiilnsttu" => ["gesticulating"],
      "aceehopprrrss" => ["sharecroppers"], "acegiinrssttu" => ["resuscitating"],
      "abfiiiilllnty" => ["infallibility"], "aacfhimnprsst" => ["craftsmanship"],
      "cceeoopprssst" => ["spectroscopes"], "bccceiimrrssu" => ["circumscribes"],
      "aeeimmnsssttt" => ["misstatements"], "aaceimnoopsst" => ["compassionate"],
      "aaccilmnostuu" => ["accumulations"], "addgiillllnyy" => ["dillydallying"],
      "bciiiiilnntvy" => ["invincibility"], "abceflmnoortu" => ["uncomfortable"],
      "ccinnoorssttu" => ["constructions"], "ciinnooorsttt" => ["contortionist"],
      "ceilmnnooossu" => ["mononucleosis"], "abcehklrsssuw" => ["swashbucklers"],
      "bceeehiklrrsu" => ["huckleberries"], "aacgilmnoorst" => ["gastronomical"],
      "eiinnoprrsttu" => ["interruptions"], "aadeefhhllrty" => ["halfheartedly"],
      "acdiilnooorst" => ["discoloration"], "acegilnnoorss" => ["congressional"],
      "biiiilmopssty" => ["impossibility"], "cdeegiinnorrs" => ["reconsidering"],
      "aaegiillmrsty" => ["magisterially"], "cdeegiinprsst" => ["disrespecting"],
      "dfgghiillnoot" => ["floodlighting"], "deeeilmmnnptu" => ["unimplemented"],
      "aaciiinsssttt" => ["statisticians"], "aceghillnnosu" => ["hallucinogens"],
      "eeiimnprrsstt" => ["misinterprets"], "acceginnorttu" => ["counteracting"],
      "aceeffillntuy" => ["ineffectually"], "abdeeilmnoprs" => ["imponderables"],
      "aceggilnnoruy" => ["encouragingly"], "aefghhoorrstu" => ["thoroughfares"],
      "aaaeglnrttvxy" => ["extravagantly"], "cdegiiinrrstt" => ["redistricting"],
      "aiiillmnpstuy" => ["pusillanimity"], "aacddeiiossst" => ["disassociated"],
      "achhiilnopprt" => ["philanthropic"], "acceehmnnorst" => ["encroachments"],
      "aegiinnnrsstt" => ["intransigents"], "aaeeiklnssttv" => ["talkativeness"],
      "accceeillnrty" => ["eccentrically"], "aceeghhooprrr" => ["choreographer"],
      "adeeefillnrty" => ["deferentially"], "beeeimrsssstw" => ["webmistresses"],
      "aeehoprrssstt" => ["stratospheres"], "aadefhinnostu" => ["fountainheads"],
      "cceeinnorrsst" => ["incorrectness"], "aaeiilnnnortt" => ["international"],
      "aaegiiilmntvy" => ["imaginatively"], "acceinnoorttu" => ["counteraction"],
      "accdfiiinoost" => ["codifications"], "aaceeghnooprr" => ["oceanographer"],
      "aaeginoorstty" => ["geostationary"], "bdeefllooprtu" => ["bulletproofed"],
      "ceiinopprrsst" => ["prescriptions"], "ceeeinnqssstu" => ["quintessences"],
      "ceefgilnnostu" => ["genuflections"], "beefhimnrrstu" => ["refurbishment"],
      "acffiiinoortt" => ["fortification"], "aaeelnprrrttu" => ["preternatural"],
      "adddeehlnnruy" => ["underhandedly"], "aceeillnoptxy" => ["exceptionally"],
      "bbceegiknnrru" => ["rubbernecking"], "deeiinoprsstu" => ["serendipitous"],
      "acdeefinnoort" => ["confederation"], "cceeeiinnnnov" => ["inconvenience"],
      "eeeeghinortty" => ["heterogeneity"], "aaaddeginsstv" => ["disadvantages"],
      "acdeefhnorrtw" => ["thenceforward"], "acdehiiopsstt" => ["sophisticated"],
      "acceeinoprttv" => ["contraceptive"], "aabefhilnnosu" => ["unfashionable"],
      "acillmnnoooty" => ["monotonically"], "aceeelloprstt" => ["electroplates"],
      "aceeiilpprtty" => ["precipitately"], "aehiilnoprsst" => ["relationships"],
      "ccegiimnnrtuv" => ["circumventing"], "aaccceeilnrrt" => ["recalcitrance"],
      "accceeelnnosv" => ["convalescence"], "eeghlmnooosuy" => ["homogeneously"],
      "eilnorsssuuux" => ["luxuriousness"], "ceilnnoosttuy" => ["contentiously"],
      "eegiilmnoorst" => ["terminologies"], "adeeeggginrst" => ["desegregating"],
      "aaccdeillmstu" => ["miscalculated"], "aaeiillqttuvy" => ["qualitatively"],
      "adfgiiinsssty" => ["dissatisfying"], "aceeillmnossu" => ["miscellaneous"],
      "aeeioopprsttv" => ["postoperative"], "aaceginnoorst" => ["octogenarians"],
      "dddehnnooorrs" => ["rhododendrons"], "abiiiillnotvy" => ["inviolability"],
      "cceeeiimnnrss" => ["reminiscences"], "aeekmorrssstt" => ["masterstrokes"],
      "aeefhlmorrstw" => ["flamethrowers"], "aeilnnorstuvy" => ["intravenously"],
      "abceiimnnoort" => ["recombination"], "aaeiinoppprrt" => ["inappropriate"],
      "deeffiilnnrty" => ["indifferently"], "aaceeilprsttu" => ["recapitulates"],
      "aaceinoprrtuy" => ["precautionary"], "cceghilmopsyy" => ["hypoglycemics"],
      "abbeghiiloprr" => ["bibliographer"], "aaceiilllrsty" => ["realistically"],
      "adeeeopprrssv" => ["eavesdroppers"], "acceiinooprrt" => ["reciprocation"],
      "aadeilmnrsstt" => ["mistranslated"], "aceiiimnnorrt" => ["recrimination"],
      "acchimoopssty" => ["psychosomatic"], "diiiinnoopsst" => ["indisposition"],
      "acfiiinnoostt" => ["notifications"], "aabeghimnsttw" => ["bantamweights"],
      "eeeilnprsssuv" => ["repulsiveness"], "aaceehinstttu" => ["authenticates"],
      "acfiiimnostty" => ["mystification"], "aegiinopprrtx" => ["expropriating"],
      "egiimnnnrsttu" => ["instrumenting"], "acdfiiimnoost" => ["modifications"],
      "aaceghiloorst" => ["archaeologist"], "adeehimnpprss" => ["misapprehends"],
      "bceilorsttuvy" => ["obstructively"], "acehillnsttyy" => ["synthetically"],
      "acddeinnoortu" => ["uncoordinated"], "aacfiiilnoqtu" => ["qualification"],
      "aaeerrrssttuu" => ["restaurateurs"], "abdeeehknorrt" => ["brokenhearted"],
      "aacelmnpprssu" => ["upperclassman"], "dfginnoooprsu" => ["soundproofing"],
      "acegiiimnnrrt" => ["recriminating"], "aiiillmnnostu" => ["illuminations"],
      "aegiilnnoprtt" => ["interpolating"], "deeefgklnoorw" => ["foreknowledge"],
      "acdeelmnnrssu" => ["underclassmen"], "aaceioprrrstv" => ["prevaricators"],
      "accdiiinorsty" => ["idiosyncratic"], "aceimnnoopsst" => ["compensations"],
      "eeiilmnnprtty" => ["impertinently"], "abceeeilnoptx" => ["exceptionable"],
      "aceeghiinorvv" => ["overachieving"], "acefiinnorstu" => ["functionaries"],
      "abceiilmnprsu" => ["republicanism"], "bceeiilmpprty" => ["imperceptibly"],
      "acgiinnnostuy" => ["consanguinity"], "addiiiilmnsuv" => ["individualism"],
      "aacceillnnost" => ["cancellations"], "aacdeiiosssst" => ["disassociates"],
      "acefiiinnortu" => ["reunification"], "acceelnnosstv" => ["convalescents"],
      "ddeefiiiimnst" => ["misidentified"], "aacdeiinopstt" => ["decapitations"],
      "deeeehhprssss" => ["shepherdesses"], "ceiiprrrssttw" => ["scriptwriters"],
      "acceffiilosuy" => ["efficaciously"], "acdeeilnorsty" => ["considerately"],
      "deeiilmnnosss" => ["dimensionless"], "ceeilmnnoptty" => ["incompetently"],
      "aceeilooprtvy" => ["cooperatively"], "aabeglmmoprrs" => ["programmables"],
      "acdhiioprsstt" => ["dictatorships"], "acefilnnoosss" => ["confessionals"],
      "abeinoprrsttu" => ["perturbations"], "eeeelnnssssss" => ["senselessness"],
      "abeeeillmmnpt" => ["implementable"], "abceeefiiinrs" => ["beneficiaries"],
      "aabcdeekqrrtu" => ["quarterbacked"], "aeeilmnnnortv" => ["environmental"],
      "aabcmnnnoostt" => ["noncombatants"], "aaeeiinnrrssv" => ["anniversaries"],
      "aeeiiopprrrst" => ["proprietaries"], "addeeenopprrt" => ["preponderated"],
      "aaegiiimnntuv" => ["unimaginative"], "adeiinorssstt" => ["dissertations"],
      "aeefimoorrrst" => ["reformatories"], "adegiiimnnsst" => ["disseminating"],
      "aacdeeinpprtu" => ["unappreciated"], "bceeeiilmpprt" => ["imperceptible"],
      "aefiiilmnssst" => ["semifinalists"], "ceeiinnoprstt" => ["interceptions"],
      "beiiiilopssst" => ["possibilities"], "aceeghilnorsu" => ["clearinghouse"],
      "abehiilnstuxy" => ["inexhaustibly"], "eeginopprssss" => ["prepossessing"],
      "acefgiilnrssy" => ["reclassifying"], "aaeegiimnrrrt" => ["intermarriage"],
      "acceiiopprssu" => ["perspicacious"], "aadeennprstuu" => ["superannuated"],
      "aaeegiimnrstv" => ["vegetarianism"], "aabbehilnoprt" => ["phenobarbital"],
      "ceeinosssstuv" => ["viscountesses"], "aabdeehiilrtt" => ["rehabilitated"],
      "eghhllossttuy" => ["thoughtlessly"], "aceeilmnopttv" => ["contemplative"],
      "aaciiilnorstt" => ["rationalistic"], "acilrrsstttuu" => ["structuralist"],
      "acilnnoossttu" => ["consultations"], "aaeeiklmnsstt" => ["statesmanlike"],
      "acdeinnnoosst" => ["condensations"], "cgiilooossttx" => ["toxicologists"],
      "aaeiillnorstt" => ["alliterations"], "abeeioorrsstv" => ["observatories"],
      "abeeeiilrrrtv" => ["irretrievable"], "ccdeelnnnoruy" => ["unconcernedly"],
      "ceeiinoprsstt" => ["receptionists"], "eegiillnnnttu" => ["unintelligent"],
      "aeeegiklmnrtt" => ["telemarketing"], "eehilloorsstt" => ["tortoiseshell"],
      "aabcclnnotuuy" => ["unaccountably"], "aaccilnorttuu" => ["acculturation"],
      "aceeghiloprrx" => ["lexicographer"], "acegiillostty" => ["egotistically"],
      "aceinnnoorttv" => ["contravention"], "ceeiinossssst" => ["secessionists"],
      "acdiillmnpstu" => ["multiplicands"], "aciiillnnostt" => ["scintillation"],
      "aabcdehorrsty" => ["carbohydrates"], "aeghhoopprrst" => ["photographers"],
      "ceefiinoprstt" => ["perfectionist"], "aacchiinnorst" => ["anachronistic"],
      "adeegghirsstt" => ["straightedges"], "deeilmnoosssu" => ["melodiousness"],
      "aaciilloprtty" => ["patriotically"], "abeghhkorrstu" => ["breakthroughs"],
      "aaailnnoprstu" => ["supranational"], "acehlmmnoostw" => ["commonwealths"],
      "aacgiilmnrttu" => ["matriculating"], "beeimnnosssuw" => ["businesswomen"],
      "abdeeiilnnpss" => ["indispensable"], "eeehlmnoosssw" => ["wholesomeness"],
      "aacffiiilnost" => ["falsification"], "degiinopsssss" => ["dispossessing"],
      "aabeiiklmrtty" => ["marketability"], "abdeeflnnnoru" => ["nonrefundable"],
      "beehilnorrsst" => ["brotherliness"], "abdgiinnorstu" => ["subordinating"],
      "aaceilnossssu" => ["salaciousness"], "adeegiimnprtt" => ["premeditating"],
      "eeeiilnnpsvxy" => ["inexpensively"], "aiiilmmnsttuv" => ["multivitamins"],
      "aacceiinnorrt" => ["incarceration"], "aacdeehintttu" => ["authenticated"],
      "eehiilmmnosst" => ["semimonthlies"], "aaiiilnnosttv" => ["invitationals"],
      "aabillnssttuy" => ["substantially"], "abeehilmnsstt" => ["establishment"],
      "adeggiilnnnst" => ["disentangling"], "eggiiilmnnnrt" => ["intermingling"],
      "aceeeiilnrrsv" => ["irrelevancies"], "acdiillnnooty" => ["conditionally"],
      "eeeeinnrssttv" => ["retentiveness"], "abceeeflnnoru" => ["unenforceable"],
      "ccdnnnooorstu" => ["nonconductors"], "aacfgiiimnnot" => ["magnification"],
      "ccilnnoossuuy" => ["unconsciously"], "acfiilnnottuy" => ["functionality"],
      "aaeiiilnnostt" => ["nationalities"], "accceimnrsstu" => ["circumstances"],
      "aefiimnnortuv" => ["uninformative"], "ceffiinoosssu" => ["officiousness"],
      "addeeghlnorwy" => ["wrongheadedly"], "abfiiiloprtty" => ["profitability"],
      "aceiinnnorstu" => ["renunciations"], "aghiilnnossty" => ["astonishingly"],
      "eeiimnoprsssx" => ["expressionism"], "aceemnnnnostu" => ["announcements"],
      "aeflnnorttuuy" => ["unfortunately"], "accdeeefinors" => ["confederacies"],
      "abceeeilorrrv" => ["irrecoverable"], "aegillmrssttu" => ["metallurgists"],
      "aaaccdeiinptt" => ["incapacitated"], "aeeghilnnrtty" => ["threateningly"],
      "acccegiinnors" => ["carcinogenics"], "beiilnoosssuv" => ["obliviousness"],
      "aeglnorrsssuu" => ["garrulousness"], "cceinnoossssu" => ["consciousness"],
      "bdeghhoorrstu" => ["thoroughbreds"], "deefgiimnrstu" => ["disfigurement"],
      "aacegiillmnty" => ["enigmatically"], "acdeiiimnrsst" => ["discriminates"],
      "aagiinnorstuu" => ["inaugurations"], "aeghhiloprrst" => ["lithographers"],
      "acdeeillnnsty" => ["clandestinely"], "aaailnnnorstt" => ["transnational"],
      "aehmnooprsssu" => ["amorphousness"], "adeeemnorstuv" => ["adventuresome"],
      "aaccellprstuy" => ["spectacularly"], "aaacfillnstty" => ["fantastically"],
      "aaaagilmmnost" => ["amalgamations"], "cceeehkllprss" => ["spellcheckers"],
      "adeeeimorsttv" => ["overestimated"], "aegnorrrsssst" => ["transgressors"],
      "aiiimnooprstv" => ["improvisation"], "bcddeeilnnotu" => ["nondeductible"],
      "deggiilnnoruv" => ["overindulging"], "abcginooorrrt" => ["corroborating"],
      "acceghhiooprr" => ["choreographic"], "ceinnooprsttu" => ["counterpoints"],
      "aciiillnnrsty" => ["intrinsically"], "addeginnnrstu" => ["understanding"],
      "eiinoopprsttu" => ["opportunities"], "acceeimmnotux" => ["excommunicate"],
      "aghiiilnprstt" => ["hairsplitting"], "aeginoorrrtty" => ["interrogatory"],
      "eeeiipqrrsstu" => ["prerequisites"], "addeeehhnosst" => ["hotheadedness"],
      "aeeeiprrsstvv" => ["preservatives"], "ceefhkmorrstu" => ["motherfuckers"],
      "abbeiiiloprst" => ["probabilities"], "aabdehhirrsst" => ["hairsbreadths"],
      "aacdeilpqrtuu" => ["quadruplicate"], "eemnnooppsstt" => ["postponements"],
      "ciillnopstuuy" => ["punctiliously"], "ceenoorssstuu" => ["courteousness"],
      "aaddeehhlrrty" => ["hardheartedly"], "bdeeimnrssstu" => ["disbursements"],
      "aaaaegnrstvxz" => ["extravaganzas"], "acdeiinnnostu" => ["denunciations"],
      "aabcceiilptty" => ["acceptability"], "cceimmooprrtu" => ["microcomputer"],
      "aacdeiillmrty" => ["diametrically"], "aadeiinopssst" => ["dispassionate"],
      "aciiiimnnnort" => ["incrimination"], "ccdeeinnnooss" => ["condescension"],
      "aaeffinoorstt" => ["afforestation"], "abcceiiilmpty" => ["impeccability"],
      "aachiillnnotu" => ["hallucination"], "aceeeglnrssss" => ["gracelessness"],
      "abceiinorsstt" => ["obstetricians"], "acdeeehinrruv" => ["underachiever"],
      "aacfiiilmnopt" => ["amplification"], "adeehmmooprst" => ["metamorphosed"],
      "acfiiillmnoot" => ["mollification"], "aaceijkrssttt" => ["straitjackets"],
      "ceghilnoosstt" => ["technologists"], "acgiilmnnnopu" => ["uncomplaining"],
      "acehinoorrstt" => ["orchestration"], "bceeimmossttu" => ["subcommittees"],
      "acciilmnoopst" => ["complications"], "ceiilnrsttuvy" => ["instructively"],
      "aabeeelnorsst" => ["elaborateness"], "acceeehillnrs" => ["chancelleries"],
      "aciiimnnorrty" => ["incriminatory"], "aaciiopprrtty" => ["participatory"],
      "aacceeilnorst" => ["accelerations"], "aaceiinnnorrt" => ["reincarnation"],
      "eeginoorrrsst" => ["retrogression"], "abcdeeilnprtu" => ["unpredictable"],
      "abeekorrssstt" => ["breaststrokes"], "ceiinoprssstu" => ["percussionist"],
      "aeiiinnrssttv" => ["intransitives"], "cdeghilnnortu" => ["underclothing"],
      "aeehlmnoossst" => ["loathsomeness"], "ghiiloopsssty" => ["physiologists"],
      "acceinnoorsst" => ["consecrations"], "aceehlmnorrtu" => ["thermonuclear"],
      "eeilnnopsssst" => ["pointlessness"], "eefhilnnssssu" => ["unselfishness"],
      "aacehillnttuy" => ["authentically"], "aaaabdilmorss" => ["ambassadorial"],
      "aaacceinnqstu" => ["acquaintances"], "abiiilnoosstt" => ["abolitionists"],
      "aaaabcchilnns" => ["bacchanalians"], "acdeeehinrsuv" => ["underachieves"]}
    |> Map.get(string_id)
  end

  def valid_ids do
    ["aadiimnorrstt", "adggiiimnnoss", "acilmnooopsst", "acdeiinnorstt",
     "acefghiinnnrs", "aceiorrsssttu", "abcchhiioprrs", "ceennoorrsttu",
     "aeeinoqrssttu", "abcflmnoortuy", "acceehhloorst", "ceeehmnnrrstt",
     "acceeiimorrst", "aegiiilnrsstu", "aceilooprtvvy", "abeiiiilnttvy",
     "aceillmmrstyy", "aaccdimmnooot", "cceiimnnoopst", "aabdennprstuu",
     "ceiilnoossttu", "aiillnnortuvy", "aaccdeilnootu", "abellllopssyy",
     "ccdgiimnnostu", "adhiimnoorssu", "aeeinrssstttv", "ccdegiinnorst",
     "iiinnorsstttu", "adehnorrsttww", "aeeimnnorrstu", "aceemnnorrsst",
     "egiimnopprssu", "aaehiiimnnstt", "accdeeennnrst", "aeeimnnopprtt",
     "acehhiinoprsz", "aaccegiinnrrt", "aabdeemnrrssu", "abeiilrtttuvy",
     "aacfiiimnorst", "aeeilnnoprrst", "adegilmoorstt", "aegilnopsttux",
     "aaimnnorstttu", "cgiimnnorsstu", "deeilnosssstu", "eiiimmnoprsss",
     "aceeinorsstvv", "aagilnnorsttu", "aeeefghhirttw", "beeegilllnrty",
     "ceegmnnoorssw", "aeeillnnoptxy", "beeeimmnrrstu", "bbeeeinorrssy",
     "aeeemnorstttv", "adeegmnnrrstu", "eiilmoorrstuy", "aceegiinnnrst",
     "eegilmooorstt", "aaagiilnorttv", "eeinooprsssss", "ceilnoorrttuy",
     "acgilllooopty", "abeegilnnnoot", "cceilnoooopss", "aehilmoostuxy",
     "aacceghinoopr", "beiiiilnnssty", "acfiiimnoortt", "bceeeijnosstv",
     "ceeinoorrsstv", "hnorrstttuuwy", "aceeehnnrssst", "eegiinnnrsttu",
     "bcdeeginorrss", "ceeinorsstttu", "eiimnoorssstt", "eiinoorsstttx",
     "aaahiimnnrstu", "aeeggiinnortt", "bdeeiirrssttu", "cdeginooprruv",
     "abeeeeilmmprs", "aeiilnoopprst", "aaeffiilmrtvy", "deeeeimnprrst",
     "aaiimnoopprtx", "aaeeiinnrrstv", "aeemnprrrsuuy", "aceeilnnoptux",
     "ceeiilrrsttvy", "acdegiilpqrsu", "ddeeeiinrsstt", "aceeiiilprstu",
     "cdeeinorstttu", "eeeimnnprsstt", "aabdegiknorst", "eegiinnprrsst",
     "adeeiinoprtxy", "aaeemqrrrsttu", "adegghinnorty", "acdegiimnostt",
     "addeeegmnrrry", "aabilnnssttuu", "acdefgillrsuy", "efgghiiilnttw",
     "acegiimmnorst", "aaaiinnosssst", "cdeeiiimnrstt", "adeeenopprrst",
     "aehhooprrssst", "aegiinorssttv", "aaceeiinorrst", "abbciiiloprst",
     "aacdeglnorttu", "abcceiiilssty", "aabcgillnoort", "aegiinnoorrtt",
     "eeknoopprssss", "acehilmoprstt", "deeginnoprsux", "cceeemmmnnost",
     "aacfiinossstt", "aacegiinprrtv", "cdfghiilnoopr", "acfgiiiinnost",
     "adeejmnrssttu", "aceegiimnnost", "aceinnorssttu", "acghiilloopsy",
     "aeefhooprrstw", "aacdhilllruyy", "aceghopprrrty", "cceiinnnossty",
     "aceeiloprstty", "ceegikllnopss", "ceeilmnoorsuy", "ccdegiinnnost",
     "aceegiinnsstt", "abeefilllnnor", "ceeiijnnorstt", "aceeilnnoqstu",
     "adeeeiimnnrtt", "cdeeiilprstvy", "eefilnrsssstu", "acfgiiinnoptt",
     "adehimmnnosst", "bcccdeiimrrsu", "aadefllmnntuy", "abeeeinorrrtv",
     "aadeinorrrtxy", "aacegilllmrtu", "aceehimoorstt", "cdeimnnooprsu",
     "ceiimmnoorsss", "aceeeehlpssst", "eeiimnoprsssu", "adeeenrssstuv",
     "accdeeilnopsy", "cceefinnoorty", "beeehilnprrsy", "aabcciilmprty",
     "aeegiinorrttv", "aacceinopsssu", "aaiilmnnopstu", "ceefiinoprsst",
     "abeeeginrrrtv", "acgghiklnostu", "acdeeennopprr", "acfgiiiinnnst",
     "ceeehmnnnrstt", "acdgiinnosttu", "eeffglnorsstu", "abdeglnorsttu",
     "aaadddeginstv", "aeeeinrsssstv", "acdeeiinnorst", "aabeilllnnstu",
     "acegimmmnoort", "aaegiimmnnrst", "abdeiinnorstu", "adeefinoorstt",
     "aagiilnnorttu", "acdeeelloprtt", "aaeinnnossttu", "ddeeeinnprstu",
     "egiilnnoqstuy", "aabbddeegilor", "eeiilmnpsssuv", "eeeennprrrstu",
     "aeeeinprsttvv", "eiinoprsssttu", "aeeiimnnorttx", "aaeegimmmnnst",
     "aaciilprrttuy", "aceinnnoorstt", "acceilmnnnoop", "aabdeeiiilrst",
     "cdeegiinorrsv", "aagiinoppprrt", "aaeeelmmnprtt", "adiiilnrssttu",
     "ddeghiiinsstu", "deeefhnoorrst", "aceeinoorrstv", "adeinosssssuu",
     "defgginnoorru", "adeeimnrsstuv", "bbcgiinnrssuu", "acginnnooostu",
     "ceeffnoorrstu", "behiiiimnostx", "aceiimmnoorst", "aegiimnnoprst",
     "agilnnoooprst", "aiillnnorttuy", "adeehhiorrsss", "acgghhinnorst",
     "deeghilmooost", "eeeellnpsssss", "abeilnopprstu", "aeefinoorrstt",
     "aabcegilnnorv", "adeeiimnoprtt", "aaciilnopsttu", "adefgiinnoorr",
     "aeeinnorsstuv", "cceeiinnossst", "acfgiiilnoort", "aeiilnnnnottu",
     "acfgiiilnnsty", "ceefiimnoprst", "aacghiloopprt", "aaccciiilmntt",
     "aaceinoprsssu", "eegghinnnrstt", "ccgiinorrssss", "abelllmnoossy",
     "eegiimnoprrtu", "cegiimnoorrtt", "aefiiiilmnnst", "aceiinoprrstt",
     "cegiinnooprss", "acdefhiinrsss", "aahiinopsstxy", "aacceginnnott",
     "acdeeiilorstv", "aiillmnopssuu", "deiiinnossssu", "aeiklmnoprsst",
     "abceeilnnostt", "ddeeeeimnprrt", "cdeeiiorssstu", "ccdeehilorrty",
     "aceeiimnnosst", "aaciimnnnoott", "abdeeehilrsst", "aiimnnorsssst",
     "cdeennooprrst", "aabciillnosty", "cgiiimmnnooss", "cdeefilprsstu",
     "ciinoopprsttu", "ciinoopprrsst", "acgiiillnnstt", "abeiimoorstuv",
     "aaeeegmnnrrrt", "accehiilprrty", "cdeeefinorttu", "aegikllnorrst",
     "abeeghiknorsu", "aaaiilnorsttt", "aeeeimorssttv", "acfiiijnosttu",
     "aacfiiiilrtty", "behiiiinosttx", "eeghiinrsstux", "adelnorstuuvy",
     "accdgiinnortt", "accchiioprrst", "aacfgiiinortt", "deeiiinoqrstu",
     "aceilnoorrstv", "aiiilnnostttu", "adeeeghlmmrss", "aceeinooprttx",
     "ddeginnrstuuy", "acdefgiilnssy", "deeeegiprrrst", "deeeinnprrttu",
     "eehlorssttuwy", "abgiimnnorrst", "aafiilmnnoort", "aaeegilmnoorr",
     "ccilmoorsstty", "aaelnnprrstty", "ccdeimnoorstu", "aacgiimnnnott",
     "accdiinnoortt", "eeeilnnosssss", "cdeiiilnsttvy", "acceilmmnnoor",
     "aabcciiilnnst", "eeeghilrsttww", "eelmopssttuuy", "aabciiillppty",
     "achhiilloopps", "aegghiimmnopr", "acfinnnooortt", "aaccegillorty",
     "aaiinooppprrt", "aadegoprssttu", "aacceinnnoott", "eeffiilnnosvy",
     "acdeghiinnnst", "eeehilmnnprst", "aeeloopprstuv", "aagilnnnprstt",
     "cdeeimnooprss", "aaceehilnprtt", "abefiijlnstuu", "abefglnorttuy",
     "eeginnnosssuu", "bcdeeiiilnnrs", "adefhilnoorss", "ddefghiiimnuy",
     "aaaeeginnrssx", "aacdeeeffinst", "aacciirrssttu", "deeiilopstuxy",
     "ccddeeginnnos", "acdeeeilnssst", "eeegiimnnprtx", "ceiiilnnsttvy",
     "abbcghiiilopr", "aabciiillmpty", "aghiinnpprsst", "adeeellmnoptv",
     "adehorssttuww", "ceeeffiilntvy", "aaehiiortttuv", "abeiillnrtuvy",
     "deeehloprrstu", "deeeginnortvx", "aceeegillnrty", "adeeeffiinrtt",
     "eegiilnnrstty", "cefilnoprrtuy", "eiilnoorsttuv", "eeeeinnqrsstu",
     "eiiillmoopsty", "behiiiloprtvy", "aaacdilloprxy", "accimmnoorstu",
     "aacdgiiinnost", "aaefgimnnortt", "aabcillnooort", "adeeffiilnrst",
     "ghiilnooorstt", "aeefhilnsssst", "aceiilmnooprt", "aceillnnnossy",
     "aceeilorrttvy", "aceehhiilmprs", "deghiiinssstu", "aegiinorrsstt",
     "bceeeeghrrssu", "abeimnnosssuw", "adeeegginorst", "aeggiinorrttu",
     "ccceooprssttu", "adefghinoorsw", "deefiiiimnsst", "accghillnooor",
     "aceiinosssuvv", "diiiinoqssstu", "aceeginoprttx", "acgiimmnoorrs",
     "bceiilnoprrtu", "cdeegimnoprss", "aeilnoorrtuvy", "aaeennprsstuu",
     "acefhlloprruy", "accdeilmnoptu", "aaeilmopprtxy", "aeefggiinrrrt",
     "aeeeiilnsttuv", "abceiooorrrtv", "deeeelmnoprtv", "ciinnoosstttu",
     "accegiinnnort", "agghhinoopprt", "aiiilnoossstt", "aaaaehilnpprr",
     "ceeeinrrrsstw", "aacdeeginrrru", "adeeeimnrsttv", "acchiooprrrst",
     "beegloorrsttt", "beeeiilprrrss", "deeeghilnnntu", "aaceiinoprrtv",
     "ceeginoprrstt", "cdehknrrsttuu", "eegillnnnrtuy", "aacceiiorrsst",
     "eegiloprrssvy", "aaggilnnrsttu", "ddeeelmnopruy", "bdiiinorssttu",
     "ceeelmmorsttu", "ceeeeinprsstv", "ddeiiillnossu", "abeiilmnrssst",
     "cdehiioprrsst", "acefiiinorstv", "deehhnorrstuw", "aaceghillprrs",
     "acccelooprstt", "adiiiilmrssty", "cceeinnoopprt", "ceeinorrrsstu",
     "cdeiiinnorsst", "cceeilnostuvy", "abeelnnnorrtu", "acdeghiimnnrs",
     "aegiiinnosttv", "aceiiinopprtt", "acchilopprsty", "aaagiinnsssst",
     "cdeegiilrrsty", "aaeeilnrrsttt", "abbceeijlnoot", "aegggiinrrttu",
     "abddeeiilnpty", "acceinnooprtt", "accghiilmnops", "aciiilmnoprsv",
     "aeinooprssttt", "eeeilnopsssvx", "cceeilnoorttu", "cciinnoorsstt",
     "acfiimnnoorst", "aaefilnqrrstu", "abbeeilmprrtu", "aeegiinnoprrt",
     "abeiimnossstu", "abehllmopssuy", "acdeimnnnoost", "adeeghiinnrst",
     "aacdeeimnnott", "ceiimmnoprstu", "bddeeiirrsttu", "abbbehlmorstu",
     "ccceeefimnrru", "acdefilmnnotu", "aegghiinnrstt", "abbeilmprrtuy",
     "adeeiinoorrtt", "cdeiimmnoosss", "cdeillnorsuuy", "aabdeinsstttu",
     "abdeegkllnowy", "ceeeeffinsstv", "eeginnoppsstt", "aaccfiiilnort",
     "eiilmnoqrstuv", "eefhilnssssst", "adeimnnoorstt", "addiiiilnstuv",
     "aabceehilmnpu", "aghilnooortty", "aaaccillrssty", "ccilnoopssuuy",
     "aaciiinopprtt", "aciinnoprrstt", "aciimnnoosstu", "acceinnnoortt",
     "abciiilmoptty", "aadehnorrsttw", "aaddegghnrrtu", "adeeiimnnostt",
     "diilmnosttuuu", "aaciiopprrstt", "aaeiloppprrty", "aceiinooqstuv",
     "aeefgiinorrrt", "abilmmnossstu", "aaaceegnrstvx", "aaehimnpssstt",
     "aabdefgiilnty", "eegginorrrsst", "ceeehhmorsstt", "acdeefginnort",
     "beiilnoprrssy", "aeggiimnssttu", "cceegiinnoprv", "aaiinnoprrstt",
     "cdeilnorsssuu", "cdeginnooprrs", "aaacehiimmntt", "aeeinnoprsstt",
     "aeehimnqssssu", "bchiiiopsssty", "aaccdeimnnopu", "eeknnoopssstu",
     "efgghiilnnrty", "cgiiilmnoorst", "abelnopprstuu", "acilllmrttuuu",
     "aciinnoooprrt", "aabghiooprtuy", "aaiillnnosstt", "ceghinorstttu",
     "aabcceiilmprt", "degiiilnpsstt", "aceeeimnnosst", "deghinnoorstu",
     "adeeginoprrsv", "accegiinoprrt", "acdfilnnostuy", "abgilmnosuuuy",
     "aacgiilnorstu", "eiioprrssttuu", "cdeiimnooopst", "adeeeimnrsttu",
     "bceinnnossttu", "acgiiiimnnnrt", "eghiimnoopssy", "abdehhnosssuu",
     "acegiiinpprtt", "agghhiilnoprt", "aeegiimnnrttx", "aacdiiiorttvy",
     "aeiimnnooprst", "cdehillooprsy", "adeeghprssttu", "aafiiilmnrtuy",
     "eeeiinorsstvv", "accefiiinortt", "deeellnnprsty", "acdeeilmnpsst",
     "eeiiiinsssttv", "aaceehimnnopt", "aceghiimoprss", "acdinooqrsstu",
     "aceginooprstt", "adeeeggimnnst", "acegghiinnnrt", "acghillmooopr",
     "aabiilnnssttu", "acehhmmnrstuy", "achillorrttuu", "cdeeffhiloors",
     "acddeiinnortt", "befiiiillntxy", "aceiinorssttu", "adiiilmnrsstu",
     "eeilnoprsttuy", "adeeeiimnrstt", "aeegiimnnortt", "abceilnnostty",
     "acdeimmnnoost", "abcghiklnssuw", "aeefhhllnsstu", "eeeimnprrssst",
     "cdeennooprsst", "eehlnorsssstw", "aaaeglllmoprr", "ceiinnooprstt",
     "deeeeinprrrtt", "aabelmmnosswy", "cdeeiilnosssu", "aceelmmnoprty",
     "aeggimmnoprrr", "aeghhiprssuwy", "aaceiilnprstt", "aeilnoopsttux",
     "aaacceiinpstt", "bddeeiilnosty", "aabcceeirrsuu", "cdeeeeeilnort",
     "aaacillmottuy", "aadginopprsst", "cdeinnooprtuv", "aadeefnsssstt",
     "aaeeglmnorstv", "aegilmnorsstu", "cddeeiinnoort", "adeggimmnoprr",
     "aeeeghmnoprst", "acchimmnooort", "abeeeeflnorsu", "eiioprsssttuu",
     "acdeegimmnnor", "aaacdeeinpprs", "bcddeeeimnrsu", "aadeegimnprst",
     "aceefinossstu", "adegiimmnnrst", "adefillssttuy", "aacceillmsstu",
     "aeehinnopprss", "adiiillnosstt", "efillllmosuuy", "aacegilnnpstu",
     "accgiimmnnotu", "aceeghilnnosu", "aeeilnnnoprst", "accefgiiinrtt",
     "aadiillnortty", "aacceknortttu", "acdeeimnorstu", "aiillnooprsvy",
     "aaciillnprtuy", "ceghhiiloprsy", "aaegimnrrsstt", "accdinoorrtty",
     "aeiinnopssstx", "ddeefhiiimrsu", "aeegllmnnntuy", "eiiimnoprssst",
     "aannorrsstuuy", "acceehirrsttu", "aaacilnnrsttt", "aabdeefgiilnt",
     "aciinnorssttu", "abbcegiklnrry", "deefgiinnprrt", "aeefinnorsssu",
     "aaabegiilmnty", "aaegggilmnort", "acceemnorrstt", "accefiiinopst",
     "aceoprrsssstt", "aaciiinnopstt", "ccceioopprsst", "beilnorstuuvy",
     "aaeilnooprttx", "acccdeimnrstu", "acddefhiinrss", "abeeiilrrrtvy",
     "eghhiinopprsw", "cceiimnoosssu", "deeginnorsuvz", "aaabceeilnrst",
     "abcdeiiilnort", "abbceijlnooty", "beeeehilnprrs", "acehhopprstyy",
     "eiiimnnorssst", "afgiiilnnrtuy", "aaacgilmmnrtu", "egiiilnossstu",
     "aehimmooprsst", "aabeeghiknrrt", "aeinooopprrtt", "efgghiiinprtz",
     "deiinoopsssss", "acceeilorsttt", "aacghiillnntu", "abdeiilnnpssy",
     "aeeelnssssstt", "aacefmnrrstuu", "deefiilnnrstu", "agghiiknnsstv",
     "aceimmmnooort", "abdiiiilmssty", "bciinoprssstu", "ceemopprrstuu",
     "abeelmmnosswy", "acdeefhhiknrs", "cfimnnnooorty", "aacdelmnnrssu",
     "aeeilmnnnsttu", "aegginnrrssst", "acccdeeeinnns", "bbceiilmnostu",
     "acciimmnnootu", "cdeinooprrstu", "aceeglmnoorst", "cdeeeeiinnprx",
     "aceeooprrsttt", "aabceeggprrst", "acegghinprrsu", "aceeiilnrttvy",
     "adiilnopsttuu", "aacdeillnotuy", "aaddeiimnrstt", "aaeegginorstx",
     "abcflnooorrsu", "aeeiilnoprsst", "efgimnooprrtu", "ceeiinoprsttv",
     "egghiiinnstux", "aceehillortty", "cdiiinnosttuy", "chlnnoorssuyy",
     "aabcllooorrst", "ceefllorrsuuy", "abcdehiilnnrr", "acdeeghhooprr",
     "ceegilmmnnopt", "abdegiilmnsss", "acceinoopprtu", "cgilnnoorsuuy",
     "cdeeeiilnnqsu", "aaegimnnosttu", "aaceillmnptuy", "cdeeemnnnostu",
     "aeeimnorrsttx", "aaceghilllrty", "cdegiinnnostt", "aabdeginorrtw",
     "dhinooorssttt", "aabbeiinorstv", "cdeennrrrstuu", "eeinnoprsttuu",
     "acginoprssstt", "aegghilnoortw", "adeegiinrsstt", "cehiiknopsssy",
     "aiillnorssttu", "aiiimnnorsstt", "aadegimnrrstt", "aeeghnoprrsst",
     "aaciilmnorttu", "aefgilmnorrtu", "ddeeeilnnnpty", "egiinnnoqstuu",
     "aghhllmooopty", "aceeegmnnortu", "adeeellmorrst", "aeeemnrssssst",
     "aacdeiinnpttu", "abceelnnoopru", "cdeeilrsttuvy", "aabeehiilrstt",
     "abcddeeiilrst", "acceiimmnotuv", "acegginnoorst", "aaahiinorrttu",
     "ceeeioprrsttv", "acdeegnnosstt", "abeehiilnstux", "eiiiilnqstuvy",
     "aciilnnorsttu", "abceenoprrstu", "aaeillnnossty", "cceegilnorttu",
     "aabceggginprt", "eeeeimnprrstx", "acfimnnooorst", "eegiilllnntty",
     "adeilmnnoprty", "aiimnooqssttu", "begilmoorssty", "aceeinooprtuv",
     "adeeeimnnortu", "ceegilmmnottu", "agiiinnnorstt", "cdiinnoosstuu",
     "abeefglnorttu", "aeilmnnrssttu", "aaefiimnnostt", "adiiilmnosstu",
     "cefghikmnortu", "adeegiinorrtt", "cddeiiilnnpsu", "cceiillossttv",
     "ddehilnnooprs", "aceehmnopprrt", "cdeeefilnsstu", "aeeiilnnorrtt",
     "adeefiiloqruv", "acdeeikloopss", "aeeillmnnstty", "agghilooprsst",
     "ggghhinooortu", "ceiijnooprstt", "ehiorrrstttuw", "eeegiorrrsstv",
     "achiimnnoopps", "adfgiiilnqsuy", "cdelmnnooooty", "aceiiiilmprst",
     "aaceglnorsttu", "aaacgillmprty", "acdegiilllooy", "cdfgiimnoorst",
     "aabceinrrsstt", "ademnoorrsstt", "aceehimnorsss", "eefgiimnnnrst",
     "acdeggiklnnow", "ceeefinorrttu", "ddeeghiilmstw", "ceeeeinrssstv",
     "aegimnopprstu", "aciiilnoosstt", "degiilnrsssty", "aabeilmnrsttt",
     "abbcdeiilnrsy", "adgiiinnoppst", "bbcgghiilnntu", "aehimnnprsstt",
     "accdeeiinprss", "beeiiilmmprss", "acehlmoorssst", "acfiiimmmnotu",
     "aaeillnooprty", "dfillrssttuuy", "aeghimnorssuw", "eiilnoqrsttuv",
     "aaggiilnnottu", "aceillnnoostt", "adeiinnopssst", "aeeehlnpsssss",
     "acegiilnosttu", "aagiiklnnpsty", "deiilmnoprtvy", "cfghilmnooorr",
     "aacgilllnosty", "aaccehilrrttu", "eghiiimnoprsv", "aeeeklrrssttw",
     "cdeehillnssss", "aaeimnnnoortt", "aeeehlorsstux", "adeiiimnnosst",
     "acdeeeiossttv", "aabbdeefglrst", "ccciiimnorssu", "adeggiilnnrss",
     "eeiinoprssstx", "addeimnnrsstu", "aaceinoprrstt", "ceginrrrsttuu",
     "eghiilnprssst", "ceehimnnooprs", "ceiinnorrsstu", "ceeinooprrstt",
     "afggiinnrrstu", "aacdeiilnortv", "aceeghprrrssu", "abcinoooorrrt",
     "diinooopprrst", "eiioopprssstu", "acdeeglmnoort", "dehmnorrssttu",
     "aeeehlnrsssst", "aaiillmnnottu", "ceeghinorttuw", "aacillmnopsty",
     "aaceilnnopstu", "aaccegiilnrtt", "aceinnoorsstv", "aabelnoprrstt",
     "eeeghilmnnntt", "cdeefinnoortv", "aceeilllnsttu", "accdeiikloops",
     "aadehorssttuw", "aaaeginnnnors", "aaelnprrsstuu", "aceeeglmnortt",
     "ceeiinnorssst", "aabceefiprrst", "aacdiiillmoty", "aabciilmoprty",
     "aeimnooprrsst", "aceiillnrstxy", "aceeehiorrsvv", "acdeiinorrsty",
     "aaaaillprrsss", "hiilloopprsww", "aabegilmnprtu", "acddeiiimnrst",
     "cdeeiilnoprst", "aacfgimnnrtuu", "deeilnnosttuy", "aaddgginnnrst",
     "acehiiprttvyy", "adeeegimnrsst", "giinnooopprrt", "aegiimnnrrrty",
     "cdeeghimnnopr", "acceiilmnosss", "acdefiinnsstt", "adegimnnorstt",
     "aehhiopprstyy", "cccdeeeenrrsu", "abdiinnoorstu", "aeehmmooprsst",
     "acceehilmoprt", "cfimnnnooorst", "eghiiilnnqrsu", "aceegillmorty",
     "abceeiilnnnst", "abbennnoorsst", "beeinorssstuv", "bbdeelnrsssuu",
     "bdeeginnorruv", "cfghiillnnnuy", "acceghillnoot", "aeeillprstuvy",
     "deghiiiinnrst", "beeeiilnprssx", "aciinnnooprtu", "bdeeegiinnrrt",
     "abbiiilmoprty", "deeinnprrttuu", "aeghimnorttuw", "aaegiilnopsst",
     "aacegiinnnrrt", "aeeiiilmnprrs", "achhiimnoppss", "beeehillmmnst",
     "aaccehillmsty", "ailnooopprrst", "acdeiinnoorst", "acddeeehinruv",
     "eefghiilrsttw", "ccdeenorrsttu", "cceiimnnortuv", "cceeghikllnps",
     "ceillmnoostty", "aeginnorrssst", "acehnnooprrss", "aeefgiorrrrst",
     "eeeghimnosstu", "acefgiilmnnty", "befgiiilnrstu", "abbcdeeiilnrs",
     "adeelnnsssstu", "giiilmnnoosuy", "ceeefimnnorrt", "eeehmnnnorstt",
     "aiilnooopprst", "eiiinnooprstt", "ceeeehlnrssss", "aacgiiinpprtt",
     "beeiilnoprrss", "diilnorsstuuy", "degiinnnnprsu", "accdiimmnnoou",
     "acegiinoorsst", "aabceeikmnrst", "ceeehimnoprsv", "cceefinnoorst",
     "aceeiinnrsttu", "eggilnooorstt", "eeeiinnsssstv", "acdeegiimorst",
     "aciilllmooqsu", "accdhhinoopry", "biinossstttuu", "adeegiknnrrst",
     "cdeeeeinpsstv", "acegillmnooot", "aacegillllory", "aefiilllnntuy",
     "aabcefiiinott", "aefghhorstttu", "efhioopprrsss", "cddeeeennprtu",
     "acdeimnnoottu", "acdiilnnnootu", "acceiilmmmors", "accfiinnoosst",
     "aafiilmmnnost", "egiilmoosssst", "aaddeegnrrtuu", "ahimnopprssst",
     "aabceilloortv", "acehiiopssstt", "aaaabcceelrtu", "begggiijnrttu",
     "aeiinoopprrtx", "ceimnnooprssu", "aaacehillptty", "eegilmnnppstu",
     "aabelmoprrstu", "eehlnorrsttwy", "aacdillmopssy", "adegjlmnnnotu",
     "aeiillnnnotty", "aceghinorrstt", "adeehhimoprrt", "aefiilnooprrt",
     "aacilmnooprst", "aaaaccdiiklls", "adeiioooprsst", "aaaciillmotxy",
     "afiillorsttuy", "adeeilnnrttvy", "eeiiimopprrst", "cdeiijnosssuu",
     "bciinnoorsttu", "adegilnnoqrtu", "adiilnnnorstu", "ccegiiimnnosv",
     "aaiiilnnoprst", "eiiiinnssttvy", "cceeefilnnors", "aaegimnnorttu",
     "aceehiinorstt", "adegiimnnoprt", "aeeeimnnnrttt", "acdehimmnorty",
     "acdgiiloorsst", "aefilnooprsss", "aabeemmnrrsst", "cghiloopsssty",
     "adeiimnnosstu", "ceeghiilnoprt", "aaiiilnorrtty", "aaeggilmnoort",
     "abceiilmnopst", "behlooorssttu", "acceilnnosstu", "ceemnnnooprtu",
     "aachillnortuy", "accchiloopsty", "aagggiilnnttu", "aabdeekorrsst",
     "abcceiilnnovy", "aeeiillnsttxy", "aabeinssstttu", "adeeimnorsttv",
     "cceffiiinnsuy", "acddeemnnortu", "aeeeimnnrsttt", "cehiilmossuvy",
     "aaacegilmmnos", "egiillnnnssuw", "ceeiilmopttvy", "acfgiinnoortu",
     "acdegghinnrru", "aaceilmoprtvy", "aeghhiooprrst", "abccnoorrsttu",
     "aceehimnssstt", "acehimnpsttuy", "abeeeinrrsttv", "aaaghirssttwy",
     "cdgiiinnnostu", "aegiilmnorsst", "aceilmmnoprty", "egilnopprsuvy",
     "adeeegoprrtuy", "aaceiinopprst", "adgiiilmnsstu", "cdeiinnooprst",
     "aeeegmnnrsstt", "aacdeeilprttu", "aaeeillnrttvy", "aaacehimooppr",
     "aeegiilmnorss", "eeeeinnssstvx", "ccceghiknorss", "aaceiiilmrstt",
     "aabceillmoprt", "deeeefinnsssv", "abcceehkrsstt", "acceiiklnostw",
     "aacghilopprty", "cdiinnoorsttu", "deiinooopprst", "cceeillnoorst",
     "aiiilprsssttu", "eeelnoprssssw", "acdeiimnoostt", "eeeeghnoorstu",
     "acceilmnorstu", "ceiilopprstuy", "cegiilmmnnopt", "aceelmnpprssu",
     "ccdeiinnnoost", "aaaeilmnprrty", "aaddeelnrttuu", "aachlnopsstyy",
     "aiinnooprsstt", "cciinnoopssuu", "aaabcegilllry", "acegmnnoorssw",
     "abdeghinoorsu", "aabeiinrrrsst", "adeghinoorsvw", "aiijnoopsttux",
     "abccdenorsttu", "aacddeeeffint", "addeeeehnrrtt", "aceilmnnooptt",
     "aaciiilnnostt", "aaceghoprrrst", "aacimnnoopswy", "eeiiilnnsstvy",
     "aeeegillnsttv", "eeeffinnosssv", "beeiiiilnssst", "aadejlmmnsttu",
     "aeimnnoopprtt", "aaeegimnrttuv", "acdgiilnnoost", "aaceehnnppsst",
     "eeeiinnnsstvv", "cgiilmoossstu", "eeiinnnorsttv", "addiiiilntuvy",
     "adeeloopprtuv", "ddeimnoorsstu", "accghilloopsy", "eiimmnnoprsst",
     "aaciilnorsttu", "aabbeiillossu", "aabegilnorrtu", "aabeiilmnorst",
     "abeeelnnprtuv", "aacdeinosssuu", "aefgiilnoprrt", "aelnnoopsstuy",
     "beefginrrsttu", "aabcdeefiprrt", "bdeeeimmmnrst", "aeeiinnoqrstu",
     "cceehilooprtt", "ceeinoprrsssu", "acdeeiimnnrty", "cceeeeeffnrsv",
     "aaadeillqrrtu", "acegilmnnoptt", "aaegilnoprttx", "ceeeilnsssuvx",
     "acdiilnnooost", "adeghllnorsst", "acceginnnnotu", "aeggiinnorrtt",
     "abeeehilrssst", "aacceimmnnopt", "aabeilnoorstv", "cdeeginnorstu",
     "aeelmnpprstuy", "aeeeglmnnnstt", "abdehilmnnsst", "eeghinorssstu",
     "aabbehiilnntu", "achhiilmnoprs", "eefghiiprrstz", "aaceennpprstu",
     "aeehlorssttuy", "bdeiiorrrsttu", "aegimnnorrstt", "abefllnoopstu",
     "adeeginopprsv", "ceeehlnnosttu", "ccceiimnoooos", "bcdeiiiilnrty",
     "cceiinnoosstu", "achiiprssstty", "aaceehillstty", "cdeeijnprrsuu",
     "aaciimmorssst", "adeeiimnnortt", "abcceeiilnnov", "aeegillmoopss",
     "bcerrsssttuuu", "acfiiillnnotu", "ddeeghhinrtuw", "aacfgilnnoort",
     "aceinoorssstu", "aaacgillmmrty", "ceiinoorsstuv", "bceghilnoooty",
     "aadeiimnrsstt", "bcddgillnooru", "acdeeilnpprru", "ceginnoorrttv",
     "cceeinnnorstt", "aagilmmnnosuy", "aceeilnnrssuy", "acehillopprty",
     "adeiimnnnoost", "cceegiinnnost", "aabceilmnnoop", "aeghnoopprrrs",
     "ccehhiinoprsz", "aagiimnopprtx", "adgilnnosttuy", "abeeilmnnnotu",
     "aaccllnorttuy", "aceehlorrstuy", "ceeimnnoorsuu", "eeellmorrsssy",
     "aaaceeenpprrs", "aeegiilnnrrtt", "cegilmooosstt", "aaccdeiinortt",
     "cegiiinnorstu", "abceelmmnorsu", "aceillnoquuvy", "eennorsssstuu",
     "aachimmnnopsy", "aciilnoppsstu", "eghiilnnssstu", "aaccdgimmnoot",
     "ceefinoorsssu", "addeegiinrstt", "aacilmnoopttu", "cddehlnorstuu",
     "aeginoorrrstt", "abceelnnoqruu", "adegiiimnnrst", "aacdeglmnnors",
     "cilmooprssuuy", "aceilnooprsss", "ahiimnoprsstt", "aeeeinnpsssvx",
     "aeehlnorrstty", "aceelmnnorstu", "acceginnnortt", "aafilmmnoorst",
     "acefiillprsuy", "adeeinoopprrt", "acddeghilnnrr", "egilmnooosstt",
     "eemmnnoossstu", "accceeiilssst", "aabcdeennoruv", "ceeffiiilnnty",
     "abdeeegkllnow", "ceeiinnorsstt", "aeiilnnooprtt", "abeiiillnrtuy",
     "abdeeiilnorst", "aaciillssttty", "aeeeinnsstttv", "acgiinnooprrt",
     "aabccelnnotuu", "aceegiilnnrtv", "aacegillrstty", "aaddeefghnrrt",
     "aaccillnsttyy", "aefginooprrtw", "cceillooopsss", "aeggiiinnsttv",
     "aceeimmmoortv", "accinprsttuuu", "aaceiklmnopst", "cdeeennnosstt",
     "abdeffhlorssu", "aabceeeillprr", "aciilllssttyy", "adeeeillmmoss",
     "ccdeehklosttu", "acimmnnoosstu", "begiiiiillnty", "aciinnnoosttu",
     "cddgilllmnooy", "aeegiiinsttvv", "abeeklmorrstu", "aaceiimmosttu",
     "aceggiilnsttu", "aceehopprrrss", "acegiinrssttu", "abfiiiilllnty",
     "aacfhimnprsst", "cceeoopprssst", "bccceiimrrssu", "aeeimmnsssttt",
     "aaceimnoopsst", "aaccilmnostuu", "addgiillllnyy", "bciiiiilnntvy",
     "abceflmnoortu", "ccinnoorssttu", "ciinnooorsttt", "ceilmnnooossu",
     "abcehklrsssuw", "bceeehiklrrsu", "aacgilmnoorst", "eiinnoprrsttu",
     "aadeefhhllrty", "acdiilnooorst", "acegilnnoorss", "biiiilmopssty",
     "cdeegiinnorrs", "aaegiillmrsty", "cdeegiinprsst", "dfgghiillnoot",
     "deeeilmmnnptu", "aaciiinsssttt", "aceghillnnosu", "eeiimnprrsstt",
     "acceginnorttu", "aceeffillntuy", "abdeeilmnoprs", "aceggilnnoruy",
     "aefghhoorrstu", "aaaeglnrttvxy", "cdegiiinrrstt", "aiiillmnpstuy",
     "aacddeiiossst", "achhiilnopprt", "acceehmnnorst", "aegiinnnrsstt",
     "aaeeiklnssttv", "accceeillnrty", "aceeghhooprrr", "adeeefillnrty",
     "beeeimrsssstw", "aeehoprrssstt", "aadefhinnostu", "cceeinnorrsst",
     "aaeiilnnnortt", "aaegiiilmntvy", "acceinnoorttu", "accdfiiinoost",
     "aaceeghnooprr", "aaeginoorstty", "bdeefllooprtu", "ceiinopprrsst",
     "ceeeinnqssstu", "ceefgilnnostu", "beefhimnrrstu", "acffiiinoortt",
     "aaeelnprrrttu", "adddeehlnnruy", "aceeillnoptxy", "bbceegiknnrru",
     "deeiinoprsstu", "acdeefinnoort", "cceeeiinnnnov", "eeeeghinortty",
     "aaaddeginsstv", "acdeefhnorrtw", "acdehiiopsstt", "acceeinoprttv",
     "aabefhilnnosu", "acillmnnoooty", "aceeelloprstt", "aceeiilpprtty",
     "aehiilnoprsst", "ccegiimnnrtuv", "aaccceeilnrrt", "accceeelnnosv",
     "eeghlmnooosuy", "eilnorsssuuux", "ceilnnoosttuy", "eegiilmnoorst",
     "adeeeggginrst", "aaccdeillmstu", "aaeiillqttuvy", "adfgiiinsssty",
     "aceeillmnossu", "aeeioopprsttv", "aaceginnoorst", "dddehnnooorrs",
     "abiiiillnotvy", "cceeeiimnnrss", "aeekmorrssstt", "aeefhlmorrstw",
     "aeilnnorstuvy", "abceiimnnoort", "aaeiinoppprrt", "deeffiilnnrty",
     "aaceeilprsttu", "aaceinoprrtuy", "cceghilmopsyy", "abbeghiiloprr",
     "aaceiilllrsty", "adeeeopprrssv", "acceiinooprrt", "aadeilmnrsstt",
     "aceiiimnnorrt", "acchimoopssty", "diiiinnoopsst", "acfiiinnoostt",
     "aabeghimnsttw", "eeeilnprsssuv", "aaceehinstttu", "acfiiimnostty",
     "aegiinopprrtx", "egiimnnnrsttu", "acdfiiimnoost", "aaceghiloorst",
     "adeehimnpprss", "bceilorsttuvy", "acehillnsttyy", "acddeinnoortu",
     "aacfiiilnoqtu", "aaeerrrssttuu", "abdeeehknorrt", "aacelmnpprssu",
     "dfginnoooprsu", "acegiiimnnrrt", "aiiillmnnostu", "aegiilnnoprtt",
     "deeefgklnoorw", "acdeelmnnrssu", "aaceioprrrstv", "accdiiinorsty",
     "aceimnnoopsst", "eeiilmnnprtty", "abceeeilnoptx", "aceeghiinorvv",
     "acefiinnorstu", "abceiilmnprsu", "bceeiilmpprty", "acgiinnnostuy",
     "addiiiilmnsuv", "aacceillnnost", "aacdeiiosssst", "acefiiinnortu",
     "acceelnnosstv", "ddeefiiiimnst", "aacdeiinopstt", "deeeehhprssss",
     "ceiiprrrssttw", "acceffiilosuy", "acdeeilnorsty", "deeiilmnnosss",
     "ceeilmnnoptty", "aceeilooprtvy", "aabeglmmoprrs", "acdhiioprsstt",
     "acefilnnoosss", "abeinoprrsttu", "eeeelnnssssss", "abeeeillmmnpt",
     "abceeefiiinrs", "aabcdeekqrrtu", "aeeilmnnnortv", "aabcmnnnoostt",
     "aaeeiinnrrssv", "aeeiiopprrrst", "addeeenopprrt", "aaegiiimnntuv",
     "adeiinorssstt", "aeefimoorrrst", "adegiiimnnsst", "aacdeeinpprtu",
     "bceeeiilmpprt", "aefiiilmnssst", "ceeiinnoprstt", "beiiiilopssst",
     "aceeghilnorsu", "abehiilnstuxy", "eeginopprssss", "acefgiilnrssy",
     "aaeegiimnrrrt", "acceiiopprssu", "aadeennprstuu", "aaeegiimnrstv",
     "aabbehilnoprt", "ceeinosssstuv", "aabdeehiilrtt", "eghhllossttuy",
     "aceeilmnopttv", "aaciiilnorstt", "acilrrsstttuu", "acilnnoossttu",
     "aaeeiklmnsstt", "acdeinnnoosst", "cgiilooossttx", "aaeiillnorstt",
     "abeeioorrsstv", "abeeeiilrrrtv", "ccdeelnnnoruy", "ceeiinoprsstt",
     "eegiillnnnttu", "aeeegiklmnrtt", "eehilloorsstt", "aabcclnnotuuy",
     "aaccilnorttuu", "aceeghiloprrx", "acegiillostty", "aceinnnoorttv",
     "ceeiinossssst", "acdiillmnpstu", "aciiillnnostt", "aabcdehorrsty",
     "aeghhoopprrst", "ceefiinoprstt", "aacchiinnorst", "adeegghirsstt",
     "deeilmnoosssu", "aaciilloprtty", "abeghhkorrstu", "aaailnnoprstu",
     "acehlmmnoostw", "aacgiilmnrttu", "beeimnnosssuw", "abdeeiilnnpss",
     "eeehlmnoosssw", "aacffiiilnost", "degiinopsssss", "aabeiiklmrtty",
     "abdeeflnnnoru", "beehilnorrsst", "abdgiinnorstu", "aaceilnossssu",
     "adeegiimnprtt", "eeeiilnnpsvxy", "aiiilmmnsttuv", "aacceiinnorrt",
     "aacdeehintttu", "eehiilmmnosst", "aaiiilnnosttv", "aabillnssttuy",
     "abeehilmnsstt", "adeggiilnnnst", "eggiiilmnnnrt", "aceeeiilnrrsv",
     "acdiillnnooty", "eeeeinnrssttv", "abceeeflnnoru", "ccdnnnooorstu",
     "aacfgiiimnnot", "ccilnnoossuuy", "acfiilnnottuy", "aaeiiilnnostt",
     "accceimnrsstu", "aefiimnnortuv", "ceffiinoosssu", "addeeghlnorwy",
     "abfiiiloprtty", "aceiinnnorstu", "aghiilnnossty", "eeiimnoprsssx",
     "aceemnnnnostu", "aeflnnorttuuy", "accdeeefinors", "abceeeilorrrv",
     "aegillmrssttu", "aaaccdeiinptt", "aeeghilnnrtty", "acccegiinnors",
     "beiilnoosssuv", "aeglnorrsssuu", "cceinnoossssu", "bdeghhoorrstu",
     "deefgiimnrstu", "aacegiillmnty", "acdeiiimnrsst", "aagiinnorstuu",
     "aeghhiloprrst", "acdeeillnnsty", "aaailnnnorstt", "aehmnooprsssu",
     "adeeemnorstuv", "aaccellprstuy", "aaacfillnstty", "aaaagilmmnost",
     "cceeehkllprss", "adeeeimorsttv", "aegnorrrsssst", "aiiimnooprstv",
     "bcddeeilnnotu", "deggiilnnoruv", "abcginooorrrt", "acceghhiooprr",
     "ceinnooprsttu", "aciiillnnrsty", "addeginnnrstu", "eiinoopprsttu",
     "acceeimmnotux", "aghiiilnprstt", "aeginoorrrtty", "eeeiipqrrsstu",
     "addeeehhnosst", "aeeeiprrsstvv", "ceefhkmorrstu", "abbeiiiloprst",
     "aabdehhirrsst", "aacdeilpqrtuu", "eemnnooppsstt", "ciillnopstuuy",
     "ceenoorssstuu", "aaddeehhlrrty", "bdeeimnrssstu", "aaaaegnrstvxz",
     "acdeiinnnostu", "aabcceiilptty", "cceimmooprrtu", "aacdeiillmrty",
     "aadeiinopssst", "aciiiimnnnort", "ccdeeinnnooss", "aaeffinoorstt",
     "abcceiiilmpty", "aachiillnnotu", "aceeeglnrssss", "abceiinorsstt",
     "acdeeehinrruv", "aacfiiilmnopt", "adeehmmooprst", "acfiiillmnoot",
     "aaceijkrssttt", "ceghilnoosstt", "acgiilmnnnopu", "acehinoorrstt",
     "bceeimmossttu", "acciilmnoopst", "ceiilnrsttuvy", "aabeeelnorsst",
     "acceeehillnrs", "aciiimnnorrty", "aaciiopprrtty", "aacceeilnorst",
     "aaceiinnnorrt", "eeginoorrrsst", "abcdeeilnprtu", "abeekorrssstt",
     "ceiinoprssstu", "aeiiinnrssttv", "cdeghilnnortu", "aeehlmnoossst",
     "ghiiloopsssty", "acceinnoorsst", "aceehlmnorrtu", "eeilnnopsssst",
     "eefhilnnssssu", "aacehillnttuy", "aaaabdilmorss", "aaacceinnqstu",
     "abiiilnoosstt", "aaaabcchilnns", "acdeeehinrsuv"]
    |> Enum.into(HashSet.new)
  end
end
