defmodule Jumble.ScowlDict.Size10.Length7 do
  def get(string_id) do
    %{"ceiprtu" => ["picture"], "ddeeirs" => ["desired"], "afgiiln" => ["failing"],
      "deemorv" => ["removed"], "adepstu" => ["updates"],
      "adeelrt" => ["altered", "related"], "adegiln" => ["dealing", "leading"],
      "aaenruw" => ["unaware"], "ginoprv" => ["proving"], "giillnw" => ["willing"],
      "cceeins" => ["science"], "hlorsty" => ["shortly"], "aegorst" => ["storage"],
      "aeeelrs" => ["release"], "aeiprtv" => ["private"], "eiorrsw" => ["worries"],
      "adilpry" => ["rapidly"], "eghilnp" => ["helping"], "enrrstu" => ["returns"],
      "ahilppy" => ["happily"], "eegikns" => ["seeking"], "deeirss" => ["desires"],
      "addeopt" => ["adopted"], "dfgiinn" => ["finding"], "cemnooy" => ["economy"],
      "aeilrty" => ["reality"], "adiilnv" => ["invalid"], "ailqtuy" => ["quality"],
      "aeinptt" => ["patient"], "eginnop" => ["opening"], "eoopprs" => ["propose"],
      "eelrstt" => ["letters"], "aaginst" => ["against"], "cgiklno" => ["locking"],
      "ceiosty" => ["society"], "beeentw" => ["between"], "eknortw" => ["network"],
      "aiorsuv" => ["various"], "deiilmp" => ["implied"], "afilquy" => ["qualify"],
      "eggintt" => ["getting"], "hiottuw" => ["without"], "adilpsy" => ["display"],
      "aeeglnr" => ["general"], "acffirt" => ["traffic"], "ginrsst" => ["strings"],
      "cdeeorv" => ["covered"], "deeeknw" => ["weekend"], "giinnnw" => ["winning"],
      "eeirrtw" => ["rewrite"], "giinstu" => ["suiting"], "ccesssu" => ["success"],
      "eeiqrru" => ["require"], "aerrstt" => ["restart"], "behorrt" => ["brother"],
      "eegsssu" => ["guesses"], "eehhrtw" => ["whether"], "afissty" => ["satisfy"],
      "adeflot" => ["floated"], "adegnrt" => ["granted"], "deelstt" => ["settled"],
      "dginorw" => ["wording"], "giiklnn" => ["linking"], "bginruy" => ["burying"],
      "ceeetux" => ["execute"], "aemrstt" => ["matters"], "adenstt" => ["attends"],
      "aeehrtw" => ["weather"], "ceiintz" => ["citizen"], "ceelrtu" => ["lecture"],
      "aderssu" => ["assured"], "eopprsu" => ["purpose"], "eilorrs" => ["lorries"],
      "accehns" => ["chances"], "deegimn" => ["deeming"], "egilntt" => ["letting"],
      "allsuuy" => ["usually"], "agmoprr" => ["program"], "aginrvy" => ["varying"],
      "aegilnv" => ["leaving"], "ghhottu" => ["thought"], "eeginnu" => ["genuine"],
      "adeinst" => ["instead"], "belortu" => ["trouble"], "eeginrt" => ["integer"],
      "eghhist" => ["highest"], "aehnort" => ["another"], "deefrsu" => ["refused"],
      "deiinot" => ["edition"], "adefhls" => ["flashed"], "dgiimnn" => ["minding"],
      "ginorst" => ["sorting", "storing"], "ceefprt" => ["perfect"],
      "acinnot" => ["contain"], "cginttu" => ["cutting"], "abceesu" => ["because"],
      "accdors" => ["accords"], "giklnoo" => ["looking"], "eeginnv" => ["evening"],
      "efgorst" => ["forgets"], "allotty" => ["totally"], "agloopy" => ["apology"],
      "cdehotu" => ["touched"], "ainostt" => ["station"], "ceiilnn" => ["incline"],
      "fgiilln" => ["filling"], "eeemrtx" => ["extreme"], "belmopr" => ["problem"],
      "acforst" => ["factors"], "efhilms" => ["himself"], "gilnosv" => ["solving"],
      "eimnnot" => ["mention"], "inoopst" => ["options"], "adehlns" => ["handles"],
      "eimprst" => ["permits"], "cenrrtu" => ["current"], "efginrs" => ["fingers"],
      "aegnrst" => ["strange"], "bemnrsu" => ["numbers"], "cennott" => ["content"],
      "aehilvy" => ["heavily"], "aginstt" => ["stating"], "ceelmow" => ["welcome"],
      "abcekrt" => ["bracket"], "beggist" => ["biggest"], "adeprss" => ["spreads"],
      "adhiloy" => ["holiday"], "aiilmrs" => ["similar"], "aehpprs" => ["perhaps"],
      "eilnovv" => ["involve"], "eeenpsx" => ["expense"], "bceorsu" => ["obscure"],
      "deegssu" => ["guessed"], "ccilnou" => ["council"], "adeginr" => ["reading"],
      "adgiilt" => ["digital"], "addemns" => ["demands"], "hiorsty" => ["history"],
      "cfginor" => ["forcing"], "aegllly" => ["legally"], "abdnoyy" => ["anybody"],
      "acdehrs" => ["crashed"], "deefins" => ["defines"], "deimops" => ["imposed"],
      "acgillo" => ["logical"], "ddeiisv" => ["divides"], "aceiqru" => ["acquire"],
      "aadkrww" => ["awkward"], "aeirrsv" => ["arrives"], "eoppssu" => ["suppose"],
      "acfilry" => ["clarify"], "ginopst" => ["posting"], "adennoy" => ["annoyed"],
      "acelnru" => ["unclear"], "einosss" => ["session"], "cdeelux" => ["exclude"],
      "eglnost" => ["longest"], "cdeorrs" => ["records"], "agiintw" => ["waiting"],
      "aghntuy" => ["naughty"], "fimnors" => ["informs"], "aeiprst" => ["parties"],
      "eilqtuy" => ["quietly"], "afilnpu" => ["painful"], "ehmoosw" => ["somehow"],
      "ccdeesu" => ["succeed"], "acehstw" => ["watches"], "aeginrw" => ["wearing"],
      "acilpst" => ["plastic"], "ceeffst" => ["effects"], "cenrtuy" => ["century"],
      "deiostu" => ["outside", "tedious"], "cepsstu" => ["suspect"],
      "deeistx" => ["existed"], "addeptu" => ["updated"], "eginors" => ["ignores"],
      "aginnrw" => ["warning"], "ghinnot" => ["nothing"], "abceens" => ["absence"],
      "ceffisu" => ["suffice"], "ghinott" => ["tonight"], "enoosst" => ["soonest"],
      "eefprrs" => ["prefers"], "dehmost" => ["methods"], "aacegkp" => ["package"],
      "addeiov" => ["avoided"], "ddeoppr" => ["dropped"], "deoppst" => ["stopped"],
      "aeilpps" => ["applies"], "eelsstt" => ["settles"], "adellow" => ["allowed"],
      "acchrst" => ["scratch"], "aemsssu" => ["assumes"], "begintt" => ["betting"],
      "deeelst" => ["deletes"], "ceenrss" => ["screens"], "eefrssu" => ["refuses"],
      "aehprss" => ["phrases"], "aenrssw" => ["answers"], "egorsss" => ["grosses"],
      "cdeestt" => ["detects"], "aeeoprt" => ["operate"], "aefilru" => ["failure"],
      "aaffirs" => ["affairs"], "giinstt" => ["sitting"], "aceffst" => ["affects"],
      "eehorvw" => ["however", "whoever"], "aeimnrs" => ["remains", "seminar"],
      "adgilno" => ["loading"], "aegimnn" => ["meaning"], "bgilooy" => ["biology"],
      "acdeirr" => ["carried"], "aeilost" => ["isolate"], "ceeeirv" => ["receive"],
      "adeghin" => ["heading"], "bdeeiss" => ["besides"], "einprrt" => ["printer"],
      "aceehiv" => ["achieve"], "giknorw" => ["working"], "eefhlrs" => ["herself"],
      "aefsstt" => ["fastest"], "cenorrs" => ["corners"], "aloppru" => ["popular"],
      "adepprt" => ["trapped"], "eimoprv" => ["improve"], "ehorrst" => ["shorter"],
      "bioosuv" => ["obvious"], "aiiilnt" => ["initial"], "aaegnrr" => ["arrange"],
      "adinstt" => ["distant"], "cnortuy" => ["country"], "beefint" => ["benefit"],
      "cdeeelt" => ["elected"], "giiklln" => ["killing"], "ceepstx" => ["expects"],
      "amnostu" => ["amounts"], "aadegms" => ["damages"], "aeelpss" => ["pleases"],
      "adghinn" => ["handing"], "bceimno" => ["combine"], "aekmrrs" => ["remarks"],
      "cddeeru" => ["reduced"], "aghinrs" => ["sharing"], "agilnss" => ["signals"],
      "deiikls" => ["dislike"], "abertty" => ["battery"], "aeopprv" => ["approve"],
      "acdeilm" => ["claimed", "medical"], "cdeilnu" => ["include"],
      "cemoptu" => ["compute"], "efmoprr" => ["perform"], "aailprt" => ["partial"],
      "aefhlss" => ["flashes"], "opprstu" => ["support"], "ddeistu" => ["studied"],
      "eeorrst" => ["restore"], "alnsuuu" => ["unusual"], "ccellot" => ["collect"],
      "acellry" => ["clearly"], "eegiknp" => ["keeping"], "acemopr" => ["compare"],
      "egillnt" => ["telling"], "efginor" => ["foreign"], "aginntw" => ["wanting"],
      "ceeiprs" => ["precise"], "aeeilrr" => ["earlier"], "acelsss" => ["classes"],
      "aginstw" => ["wasting"], "egillns" => ["selling"], "deeirsv" => ["derives"],
      "beeorsv" => ["observe"], "aaepprs" => ["appears"], "adeilry" => ["readily"],
      "eginstt" => ["setting", "testing"], "eenprst" => ["present"],
      "aeefrtu" => ["feature"], "acdehtw" => ["watched"], "fijstuy" => ["justify"],
      "eehinrt" => ["neither"], "adegrrs" => ["regards"], "afillny" => ["finally"],
      "afgilln" => ["falling"], "ceffios" => ["offices"], "aeemrsu" => ["measure"],
      "cefipsy" => ["specify"], "accehst" => ["catches"], "degiint" => ["editing"],
      "celmopx" => ["complex"], "aeeprst" => ["repeats"],
      "acdeelr" => ["cleared", "declare"], "aceghrs" => ["charges"],
      "aempttt" => ["attempt"], "ccdeehk" => ["checked"], "adeelps" => ["pleased"],
      "eirsuvv" => ["survive"], "ahnppuy" => ["unhappy"], "acehprt" => ["chapter"],
      "ghinosw" => ["showing"], "bcejost" => ["objects"], "beemmrs" => ["members"],
      "aellorv" => ["overall"], "deirrsv" => ["drivers"], "dgnorsu" => ["grounds"],
      "adeinrt" => ["trained"], "adderss" => ["address"], "befilry" => ["briefly"],
      "cefnosu" => ["confuse"], "ceeorrv" => ["recover"], "aeirtvy" => ["variety"],
      "aenprtt" => ["pattern"], "beehrty" => ["thereby"], "acefrsu" => ["surface"],
      "adeerrs" => ["readers"], "ddehnru" => ["hundred"], "dehopps" => ["shopped"],
      "giilnst" => ["listing"], "ccenopt" => ["concept"], "imnoort" => ["monitor"],
      "ceegllo" => ["college"], "ggiinns" => ["signing"], "cenottx" => ["context"],
      "gginorw" => ["growing"], "aceehrt" => ["teacher"], "cdoprtu" => ["product"],
      "cdenotu" => ["counted"], "eginrsv" => ["serving"], "aceehpr" => ["cheaper"],
      "ciorsuu" => ["curious"], "aaegmns" => ["manages"], "abiilty" => ["ability"],
      "abdhnsu" => ["husband"], "giknnow" => ["knowing"], "eegimnt" => ["meeting"],
      "beiilsv" => ["visible"], "ainnstt" => ["instant"], "acdeghn" => ["changed"],
      "aegluvy" => ["vaguely"], "aacdenv" => ["advance"], "deenstx" => ["extends"],
      "definrs" => ["friends"], "acelnrt" => ["central"], "deioprv" => ["provide"],
      "deginns" => ["sending"], "cdisssu" => ["discuss"], "denoprs" => ["respond"],
      "deeenrt" => ["entered"], "aillnst" => ["install"], "cejoprt" => ["project"],
      "ccennor" => ["concern"], "eooppss" => ["opposes"], "acghipr" => ["graphic"],
      "aiilrtv" => ["trivial"], "deimott" => ["omitted"], "deiilmt" => ["limited"],
      "afhlmru" => ["harmful"], "ceeirsv" => ["service"], "emsssty" => ["systems"],
      "accnotu" => ["account"], "deginor" => ["ignored"], "ddeeotv" => ["devoted"],
      "ceoprss" => ["process"], "iinssst" => ["insists"], "aginsty" => ["staying"],
      "cddeeis" => ["decides"], "aeghinr" => ["hearing"], "bceemos" => ["becomes"],
      "ddeeelt" => ["deleted"], "aeeisst" => ["easiest"], "aalnrtu" => ["natural"],
      "agikmnr" => ["marking"], "adeertt" => ["treated"], "ccennot" => ["connect"],
      "eemprsu" => ["presume"], "aeeimnx" => ["examine"], "ceikqru" => ["quicker"],
      "ceinost" => ["notices", "section"], "aaddegm" => ["damaged"],
      "aceinrt" => ["certain"], "bdirstu" => ["disturb"], "eimnstu" => ["minutes"],
      "aggiinn" => ["gaining"], "aderstt" => ["started"], "adefltu" => ["default"],
      "aceghns" => ["changes"], "deopstt" => ["spotted"], "cdeersu" => ["reduces"],
      "eemnoos" => ["someone"], "ddenosu" => ["sounded"], "aalmnsu" => ["manuals"],
      "aelmorv" => ["removal"], "aeikmst" => ["mistake"], "cdenoss" => ["seconds"],
      "elrsstu" => ["results"], "aceltxy" => ["exactly"], "adprsuw" => ["upwards"],
      "eeforrv" => ["forever"], "aeelmpx" => ["example"], "cehostu" => ["touches"],
      "eeprssx" => ["express"], "cenortu" => ["counter"], "aceelpr" => ["replace"],
      "aabceln" => ["balance"], "aeglrty" => ["greatly"], "cdeeisv" => ["devices"],
      "acdirst" => ["drastic"], "ekorrsw" => ["workers"], "agginru" => ["arguing"],
      "ceejrst" => ["rejects"], "efgirsu" => ["figures"], "dersttu" => ["trusted"],
      "cdeinot" => ["noticed"], "adforrw" => ["forward"], "bddgiin" => ["bidding"],
      "elnosss" => ["lessons"], "adginrw" => ["drawing"], "dgiinrv" => ["driving"],
      "boorrsw" => ["borrows"], "chlooss" => ["schools"], "eeprsss" => ["presses"],
      "ddeeorr" => ["ordered"], "fimnoru" => ["uniform"], "ddeefin" => ["defined"],
      "beglnos" => ["belongs"], "deoopps" => ["opposed"], "aersssu" => ["assures"],
      "eoprstt" => ["protest"], "deeipst" => ["despite"], "aeglrst" => ["largest"],
      "ceeflrt" => ["reflect"], "adelnnp" => ["planned"], "acehrss" => ["crashes"],
      "abcgikn" => ["backing"], "gimnnor" => ["morning"], "ceikstt" => ["tickets"],
      "knnnouw" => ["unknown"], "cdekkno" => ["knocked"], "cinosst" => ["consist"],
      "deimmsu" => ["mediums"], "cciirtu" => ["circuit"], "eelsssu" => ["useless"],
      "deiintv" => ["invited"], "aceirrs" => ["carries"], "eimopss" => ["imposes"],
      "acdeehr" => ["reached"], "aeilnpx" => ["explain"], "eimoprs" => ["promise"],
      "deeginn" => ["needing"], "eeprstx" => ["experts"], "cginost" => ["costing"],
      "adgilnn" => ["landing"], "agiklnt" => ["talking"], "iimmmnu" => ["minimum"],
      "giinssu" => ["issuing"], "gggilno" => ["logging"], "ceeprst" => ["respect"],
      "cenortv" => ["convert"], "elrttuy" => ["utterly"], "aeelrst" => ["relates"],
      "deefmor" => ["freedom"], "adeeflr" => ["federal"], "deimnrs" => ["reminds"],
      "enoprss" => ["persons"], "ginpttu" => ["putting"], "eeqrstu" => ["request"],
      "clnoort" => ["control"], "gillnpu" => ["pulling"], "eikrsst" => ["strikes"],
      "aaegmnr" => ["manager"], "dinosww" => ["windows"], "deorsty" => ["destroy"],
      "bimsstu" => ["submits"], "addeisv" => ["advised"], "ddeenps" => ["depends"],
      "eenrssu" => ["ensures"], "aeegrrt" => ["greater"], "bemnstu" => ["numbest"],
      "ginnrtu" => ["turning"], "deefgin" => ["feeding"], "eeilntt" => ["entitle"],
      "ddgiinr" => ["ridding"], "deeilrv" => ["deliver"], "filrsty" => ["firstly"],
      "aabcelp" => ["capable"], "ikmoost" => ["mistook"], "giimnss" => ["missing"],
      "enorsuv" => ["nervous"], "agiinrs" => ["raising"], "aiilmmn" => ["minimal"],
      "cfimnor" => ["confirm"], "aeqrrtu" => ["quarter"], "agimnsu" => ["amusing"],
      "acehlnn" => ["channel"], "fgiintt" => ["fitting"], "giinrtw" => ["writing"],
      "aellmrs" => ["smaller"], "deeffor" => ["offered"], "efhrrtu" => ["further"],
      "aeegmss" => ["message"], "aehhlty" => ["healthy"], "eeelmnt" => ["element"],
      "aeglrru" => ["regular"], "aeehrsw" => ["whereas"], "bdgiinn" => ["binding"],
      "acerttx" => ["extract"], "aabeggr" => ["garbage"], "acehmst" => ["matches"],
      "celosst" => ["closest"], "cgilnos" => ["closing"],
      "aeelrsv" => ["reveals", "several"], "acdeert" => ["created"],
      "agilnpy" => ["playing"], "einrsst" => ["inserts"], "flloosw" => ["follows"],
      "abeelns" => ["enables"], "cemoops" => ["compose"], "ghloruy" => ["roughly"],
      "effrssu" => ["suffers"], "efnortu" => ["fortune"], "coprrtu" => ["corrupt"],
      "aceelrr" => ["clearer"], "deinprt" => ["printed"], "adeilpp" => ["applied"],
      "acilpty" => ["typical"], "eggsstu" => ["suggest"], "aceilrt" => ["article"],
      "agiklnw" => ["walking"], "iillmno" => ["million"], "cdeirst" => ["directs"],
      "cehooss" => ["chooses"], "adeilms" => ["mislead"], "aadelry" => ["already"],
      "eeerrsv" => ["reserve", "reverse"], "eenrstw" => ["western"],
      "acinost" => ["actions"], "giijnno" => ["joining"], "aadegmn" => ["managed"],
      "adehrst" => ["hardest"], "aceflru" => ["careful"], "cgimmnu" => ["cumming"],
      "aegllry" => ["largely"], "adeilst" => ["details"], "cginopy" => ["copying"],
      "aefhrrt" => ["farther"], "aceehst" => ["teaches"], "behorst" => ["bothers"],
      "einorsv" => ["version"], "ghinpsu" => ["pushing"], "aimprry" => ["primary"],
      "aeepprr" => ["prepare"], "accepst" => ["accepts"], "denpssu" => ["suspend"],
      "abilrry" => ["library"], "dddeiiv" => ["divided"], "eefgiln" => ["feeling"],
      "deisstu" => ["studies"], "deeprss" => ["pressed"], "abeginr" => ["bearing"],
      "deginss" => ["designs"], "deinopt" => ["pointed"], "ademssu" => ["assumed"],
      "denorsw" => ["wonders"], "acmnopy" => ["company"], "aegilll" => ["illegal"],
      "afhinos" => ["fashion"], "acdmmno" => ["command"], "eeilprs" => ["replies"],
      "beehrwy" => ["whereby"], "beeeilv" => ["believe"], "deeostv" => ["devotes"],
      "deiorrw" => ["worried"], "adorstw" => ["towards"], "fgimnor" => ["forming"],
      "densttu" => ["student"], "einortu" => ["routine"], "aceerst" => ["creates"],
      "eenprtv" => ["prevent"], "ammrsuy" => ["summary"], "eemorsv" => ["removes"],
      "einnstv" => ["invents"], "aaeegrv" => ["average"], "eiorssu" => ["serious"],
      "eeinrst" => ["entries"], "eoprrst" => ["reports"], "acgilnp" => ["placing"],
      "deelopv" => ["develop"], "aacrttt" => ["attract"], "blmossy" => ["symbols"],
      "acgilln" => ["calling"], "adenpsx" => ["expands"], "aeenrst" => ["nearest"],
      "aimmmux" => ["maximum"], "einrttw" => ["written"], "deenrsu" => ["ensured"],
      "acepsst" => ["aspects"], "ddeeirv" => ["derived"], "ghhortu" => ["through"],
      "aceehrs" => ["reaches"], "aceilps" => ["special"], "cellosy" => ["closely"],
      "acdeghr" => ["charged"], "aacilpt" => ["capital"], "ceffior" => ["officer"],
      "bcejstu" => ["subject"], "efhllpu" => ["helpful"], "cdddeei" => ["decided"],
      "deeilpr" => ["replied"], "addehln" => ["handled"], "aellquy" => ["equally"],
      "cdeopru" => ["produce"], "aehnpps" => ["happens"], "celrtuu" => ["culture"],
      "efforst" => ["efforts"], "bhilpsu" => ["publish"],
      "ceorssu" => ["courses", "sources"], "eehnorw" => ["nowhere"],
      "aegiimn" => ["imagine"], "ciklquy" => ["quickly"], "abeirrz" => ["bizarre"],
      "ahorstu" => ["authors"], "deinnst" => ["intends"], "agghinn" => ["hanging"],
      "aeimssv" => ["massive"], "dghilno" => ["holding"], "abinost" => ["obtains"],
      "bbhirsu" => ["rubbish"], "ghiinsw" => ["wishing"], "adeissv" => ["advises"],
      "eiilmps" => ["implies"], "aeekprs" => ["speaker"], "cgiiknp" => ["picking"],
      "elosstw" => ["slowest"], "acehimn" => ["machine"], "iilttuy" => ["utility"],
      "ceelsst" => ["selects"], "deeegrs" => ["degrees"], "acgikln" => ["lacking"],
      "ginoqtu" => ["quoting"], "aceinnt" => ["ancient"], "bdiosuu" => ["dubious"],
      "adeirrv" => ["arrived"], "aacinpt" => ["captain"], "bghortu" => ["brought"],
      "ginnnru" => ["running"], "eilmprs" => ["simpler"], "iinnoop" => ["opinion"],
      "acginsu" => ["causing"], "ceoprtt" => ["protect"], "aginpss" => ["passing"],
      "ghiintt" => ["hitting"], "deiorst" => ["editors"], "cceorrt" => ["correct"],
      "accnott" => ["contact"], "eiinstv" => ["invites"], "aenorss" => ["reasons"],
      "eegimns" => ["seeming"], "cemmnot" => ["comment"]}
    |> Map.get(string_id)
  end

  def valid_ids do
    ["ceiprtu", "ddeeirs", "afgiiln", "deemorv", "adepstu", "adeelrt", "adegiln",
     "aaenruw", "ginoprv", "giillnw", "cceeins", "hlorsty", "aegorst", "aeeelrs",
     "aeiprtv", "eiorrsw", "adilpry", "eghilnp", "enrrstu", "ahilppy", "eegikns",
     "deeirss", "addeopt", "dfgiinn", "cemnooy", "aeilrty", "adiilnv", "ailqtuy",
     "aeinptt", "eginnop", "eoopprs", "eelrstt", "aaginst", "cgiklno", "ceiosty",
     "beeentw", "eknortw", "aiorsuv", "deiilmp", "afilquy", "eggintt", "hiottuw",
     "adilpsy", "aeeglnr", "acffirt", "ginrsst", "cdeeorv", "deeeknw", "giinnnw",
     "eeirrtw", "giinstu", "ccesssu", "eeiqrru", "aerrstt", "behorrt", "eegsssu",
     "eehhrtw", "afissty", "adeflot", "adegnrt", "deelstt", "dginorw", "giiklnn",
     "bginruy", "ceeetux", "aemrstt", "adenstt", "aeehrtw", "ceiintz", "ceelrtu",
     "aderssu", "eopprsu", "eilorrs", "accehns", "deegimn", "egilntt", "allsuuy",
     "agmoprr", "aginrvy", "aegilnv", "ghhottu", "eeginnu", "adeinst", "belortu",
     "eeginrt", "eghhist", "aehnort", "deefrsu", "deiinot", "adefhls", "dgiimnn",
     "ginorst", "ceefprt", "acinnot", "cginttu", "abceesu", "accdors", "giklnoo",
     "eeginnv", "efgorst", "allotty", "agloopy", "cdehotu", "ainostt", "ceiilnn",
     "fgiilln", "eeemrtx", "belmopr", "acforst", "efhilms", "gilnosv", "eimnnot",
     "inoopst", "adehlns", "eimprst", "cenrrtu", "efginrs", "aegnrst", "bemnrsu",
     "cennott", "aehilvy", "aginstt", "ceelmow", "abcekrt", "beggist", "adeprss",
     "adhiloy", "aiilmrs", "aehpprs", "eilnovv", "eeenpsx", "bceorsu", "deegssu",
     "ccilnou", "adeginr", "adgiilt", "addemns", "hiorsty", "cfginor", "aegllly",
     "abdnoyy", "acdehrs", "deefins", "deimops", "acgillo", "ddeiisv", "aceiqru",
     "aadkrww", "aeirrsv", "eoppssu", "acfilry", "ginopst", "adennoy", "acelnru",
     "einosss", "cdeelux", "eglnost", "cdeorrs", "agiintw", "aghntuy", "fimnors",
     "aeiprst", "eilqtuy", "afilnpu", "ehmoosw", "ccdeesu", "acehstw", "aeginrw",
     "acilpst", "ceeffst", "cenrtuy", "deiostu", "cepsstu", "deeistx", "addeptu",
     "eginors", "aginnrw", "ghinnot", "abceens", "ceffisu", "ghinott", "enoosst",
     "eefprrs", "dehmost", "aacegkp", "addeiov", "ddeoppr", "deoppst", "aeilpps",
     "eelsstt", "adellow", "acchrst", "aemsssu", "begintt", "deeelst", "ceenrss",
     "eefrssu", "aehprss", "aenrssw", "egorsss", "cdeestt", "aeeoprt", "aefilru",
     "aaffirs", "giinstt", "aceffst", "eehorvw", "aeimnrs", "adgilno", "aegimnn",
     "bgilooy", "acdeirr", "aeilost", "ceeeirv", "adeghin", "bdeeiss", "einprrt",
     "aceehiv", "giknorw", "eefhlrs", "aefsstt", "cenorrs", "aloppru", "adepprt",
     "eimoprv", "ehorrst", "bioosuv", "aiiilnt", "aaegnrr", "adinstt", "cnortuy",
     "beefint", "cdeeelt", "giiklln", "ceepstx", "amnostu", "aadegms", "aeelpss",
     "adghinn", "bceimno", "aekmrrs", "cddeeru", "aghinrs", "agilnss", "deiikls",
     "abertty", "aeopprv", "acdeilm", "cdeilnu", "cemoptu", "efmoprr", "aailprt",
     "aefhlss", "opprstu", "ddeistu", "eeorrst", "alnsuuu", "ccellot", "acellry",
     "eegiknp", "acemopr", "egillnt", "efginor", "aginntw", "ceeiprs", "aeeilrr",
     "acelsss", "aginstw", "egillns", "deeirsv", "beeorsv", "aaepprs", "adeilry",
     "eginstt", "eenprst", "aeefrtu", "acdehtw", "fijstuy", "eehinrt", "adegrrs",
     "afillny", "afgilln", "ceffios", "aeemrsu", "cefipsy", "accehst", "degiint",
     "celmopx", "aeeprst", "acdeelr", "aceghrs", "aempttt", "ccdeehk", "adeelps",
     "eirsuvv", "ahnppuy", "acehprt", "ghinosw", "bcejost", "beemmrs", "aellorv",
     "deirrsv", "dgnorsu", "adeinrt", "adderss", "befilry", "cefnosu", "ceeorrv",
     "aeirtvy", "aenprtt", "beehrty", "acefrsu", "adeerrs", "ddehnru", "dehopps",
     "giilnst", "ccenopt", "imnoort", "ceegllo", "ggiinns", "cenottx", "gginorw",
     "aceehrt", "cdoprtu", "cdenotu", "eginrsv", "aceehpr", "ciorsuu", "aaegmns",
     "abiilty", "abdhnsu", "giknnow", "eegimnt", "beiilsv", "ainnstt", "acdeghn",
     "aegluvy", "aacdenv", "deenstx", "definrs", "acelnrt", "deioprv", "deginns",
     "cdisssu", "denoprs", "deeenrt", "aillnst", "cejoprt", "ccennor", "eooppss",
     "acghipr", "aiilrtv", "deimott", "deiilmt", "afhlmru", "ceeirsv", "emsssty",
     "accnotu", "deginor", "ddeeotv", "ceoprss", "iinssst", "aginsty", "cddeeis",
     "aeghinr", "bceemos", "ddeeelt", "aeeisst", "aalnrtu", "agikmnr", "adeertt",
     "ccennot", "eemprsu", "aeeimnx", "ceikqru", "ceinost", "aaddegm", "aceinrt",
     "bdirstu", "eimnstu", "aggiinn", "aderstt", "adefltu", "aceghns", "deopstt",
     "cdeersu", "eemnoos", "ddenosu", "aalmnsu", "aelmorv", "aeikmst", "cdenoss",
     "elrsstu", "aceltxy", "adprsuw", "eeforrv", "aeelmpx", "cehostu", "eeprssx",
     "cenortu", "aceelpr", "aabceln", "aeglrty", "cdeeisv", "acdirst", "ekorrsw",
     "agginru", "ceejrst", "efgirsu", "dersttu", "cdeinot", "adforrw", "bddgiin",
     "elnosss", "adginrw", "dgiinrv", "boorrsw", "chlooss", "eeprsss", "ddeeorr",
     "fimnoru", "ddeefin", "beglnos", "deoopps", "aersssu", "eoprstt", "deeipst",
     "aeglrst", "ceeflrt", "adelnnp", "acehrss", "abcgikn", "gimnnor", "ceikstt",
     "knnnouw", "cdekkno", "cinosst", "deimmsu", "cciirtu", "eelsssu", "deiintv",
     "aceirrs", "eimopss", "acdeehr", "aeilnpx", "eimoprs", "deeginn", "eeprstx",
     "cginost", "adgilnn", "agiklnt", "iimmmnu", "giinssu", "gggilno", "ceeprst",
     "cenortv", "elrttuy", "aeelrst", "deefmor", "adeeflr", "deimnrs", "enoprss",
     "ginpttu", "eeqrstu", "clnoort", "gillnpu", "eikrsst", "aaegmnr", "dinosww",
     "deorsty", "bimsstu", "addeisv", "ddeenps", "eenrssu", "aeegrrt", "bemnstu",
     "ginnrtu", "deefgin", "eeilntt", "ddgiinr", "deeilrv", "filrsty", "aabcelp",
     "ikmoost", "giimnss", "enorsuv", "agiinrs", "aiilmmn", "cfimnor", "aeqrrtu",
     "agimnsu", "acehlnn", "fgiintt", "giinrtw", "aellmrs", "deeffor", "efhrrtu",
     "aeegmss", "aehhlty", "eeelmnt", "aeglrru", "aeehrsw", "bdgiinn", "acerttx",
     "aabeggr", "acehmst", "celosst", "cgilnos", "aeelrsv", "acdeert", "agilnpy",
     "einrsst", "flloosw", "abeelns", "cemoops", "ghloruy", "effrssu", "efnortu",
     "coprrtu", "aceelrr", "deinprt", "adeilpp", "acilpty", "eggsstu", "aceilrt",
     "agiklnw", "iillmno", "cdeirst", "cehooss", "adeilms", "aadelry", "eeerrsv",
     "eenrstw", "acinost", "giijnno", "aadegmn", "adehrst", "aceflru", "cgimmnu",
     "aegllry", "adeilst", "cginopy", "aefhrrt", "aceehst", "behorst", "einorsv",
     "ghinpsu", "aimprry", "aeepprr", "accepst", "denpssu", "abilrry", "dddeiiv",
     "eefgiln", "deisstu", "deeprss", "abeginr", "deginss", "deinopt", "ademssu",
     "denorsw", "acmnopy", "aegilll", "afhinos", "acdmmno", "eeilprs", "beehrwy",
     "beeeilv", "deeostv", "deiorrw", "adorstw", "fgimnor", "densttu", "einortu",
     "aceerst", "eenprtv", "ammrsuy", "eemorsv", "einnstv", "aaeegrv", "eiorssu",
     "eeinrst", "eoprrst", "acgilnp", "deelopv", "aacrttt", "blmossy", "acgilln",
     "adenpsx", "aeenrst", "aimmmux", "einrttw", "deenrsu", "acepsst", "ddeeirv",
     "ghhortu", "aceehrs", "aceilps", "cellosy", "acdeghr", "aacilpt", "ceffior",
     "bcejstu", "efhllpu", "cdddeei", "deeilpr", "addehln", "aellquy", "cdeopru",
     "aehnpps", "celrtuu", "efforst", "bhilpsu", "ceorssu", "eehnorw", "aegiimn",
     "ciklquy", "abeirrz", "ahorstu", "deinnst", "agghinn", "aeimssv", "dghilno",
     "abinost", "bbhirsu", "ghiinsw", "adeissv", "eiilmps", "aeekprs", "cgiiknp",
     "elosstw", "acehimn", "iilttuy", "ceelsst", "deeegrs", "acgikln", "ginoqtu",
     "aceinnt", "bdiosuu", "adeirrv", "aacinpt", "bghortu", "ginnnru", "eilmprs",
     "iinnoop", "acginsu", "ceoprtt", "aginpss", "ghiintt", "deiorst", "cceorrt",
     "accnott", "eiinstv", "aenorss", "eegimns", "cemmnot"]
    |> Enum.into(HashSet.new)
  end
end
