defmodule Jumble.ScowlDict.Size10.Length5 do
  def get(string_id) do
    %{"ademn" => ["named"], "enrty" => ["entry"], "first" => ["first"],
      "eoprw" => ["power"], "aelqu" => ["equal"], "enpst" => ["spent"],
      "adilv" => ["valid"], "eenrt" => ["enter"], "eimpr" => ["prime"],
      "adhny" => ["handy"], "aflls" => ["falls"], "alnps" => ["plans"],
      "aprty" => ["party"], "ellps" => ["spell"], "acehp" => ["cheap"],
      "ejnoy" => ["enjoy"], "gnouy" => ["young"], "aghpr" => ["graph"],
      "ackls" => ["lacks"], "aeegr" => ["agree"], "empty" => ["empty"],
      "denot" => ["noted"], "ehllo" => ["hello"], "dehpt" => ["depth"],
      "afluw" => ["awful"], "chhiw" => ["which"], "doors" => ["doors"],
      "achin" => ["chain"], "abelm" => ["blame"], "eppru" => ["upper"],
      "aksst" => ["tasks"], "hsstu" => ["shuts"], "agnry" => ["angry"],
      "eimsx" => ["mixes"], "deinx" => ["index"], "eprss" => ["press"],
      "inopt" => ["point"], "elorw" => ["lower"], "dorsw" => ["words"],
      "kloos" => ["looks"], "deikl" => ["liked"], "aeelv" => ["leave"],
      "ehlow" => ["whole"], "aadeh" => ["ahead"], "gilny" => ["lying"],
      "abess" => ["bases"], "denst" => ["tends"], "esstt" => ["tests"],
      "ehilw" => ["while"], "amnow" => ["woman"],
      "defil" => ["field", "filed", "flied"], "orsty" => ["story"],
      "emosv" => ["moves"], "cikst" => ["stick"], "abelt" => ["table"],
      "ioprr" => ["prior"], "ailnp" => ["plain"], "ckost" => ["stock"],
      "abdly" => ["badly"], "aistw" => ["waits"], "iqstu" => ["quits"],
      "ghotu" => ["ought"], "eiqtu" => ["quiet", "quite"], "afils" => ["fails"],
      "eelps" => ["sleep"], "ehosw" => ["whose"], "eefls" => ["feels"],
      "deorv" => ["drove"], "adiov" => ["avoid"], "adlns" => ["lands"],
      "besty" => ["bytes"], "abegn" => ["began"], "aelpp" => ["apple"],
      "egisv" => ["gives"], "adgru" => ["guard"], "acllo" => ["local"],
      "elpry" => ["reply"], "acehl" => ["leach"], "inosy" => ["noisy"],
      "iklls" => ["kills", "skill"], "ehops" => ["hopes"], "aepsu" => ["pause"],
      "depty" => ["typed"], "fhist" => ["shift"], "dgiit" => ["digit"],
      "knnow" => ["known"], "ginsu" => ["using"], "ceins" => ["since"],
      "einos" => ["noise"], "ckluy" => ["lucky"], "corss" => ["cross"],
      "degju" => ["judge"], "dginy" => ["dying"], "abeov" => ["above"],
      "abotu" => ["about"], "eikls" => ["likes"], "aertx" => ["extra"],
      "ehrtw" => ["threw"], "ccely" => ["cycle"], "agins" => ["gains"],
      "bekor" => ["broke"], "lopst" => ["plots"], "aefrt" => ["after"],
      "imost" => ["omits"], "hiknt" => ["think"], "inptu" => ["input"],
      "abers" => ["bears"], "ackrt" => ["track"], "ainst" => ["saint"],
      "cikps" => ["picks"], "adeim" => ["aimed", "media"], "aefls" => ["false"],
      "aegru" => ["argue"], "aelnp" => ["plane"], "achtw" => ["watch"],
      "ddeen" => ["ended"], "ceeip" => ["piece"], "assty" => ["stays"],
      "hmnot" => ["month"], "cddeo" => ["coded"], "ahmnu" => ["human"],
      "deimx" => ["mixed"], "eensv" => ["evens", "seven"],
      "aeirs" => ["arise", "raise"], "fhort" => ["forth"], "dhirt" => ["third"],
      "aeluv" => ["value"], "aaekw" => ["awake"], "eemst" => ["meets"],
      "denss" => ["sends"], "adels" => ["deals", "leads"], "instu" => ["units"],
      "ehosu" => ["house"], "achmt" => ["match"], "doprs" => ["drops"],
      "acesu" => ["cause"], "ghoru" => ["rough"], "cdhil" => ["child"],
      "aglno" => ["along"], "ailtv" => ["vital"], "deorr" => ["order"],
      "aagin" => ["again"], "ahprs" => ["sharp"], "orsst" => ["sorts"],
      "illst" => ["still"], "eknot" => ["token"], "efirs" => ["fries"],
      "cdeos" => ["codes"], "abemy" => ["maybe"], "deist" => ["edits"],
      "arstt" => ["start"], "alott" => ["total"], "illsw" => ["wills"],
      "accht" => ["catch"], "adoty" => ["today"], "adest" => ["dates"],
      "aehps" => ["phase", "shape"], "acert" => ["react", "trace"],
      "aemnt" => ["meant"], "eissu" => ["issue"], "abhit" => ["habit"],
      "fghit" => ["fight"], "amrry" => ["marry"], "adipr" => ["rapid"],
      "adeks" => ["asked"], "aghns" => ["hangs"], "aaprt" => ["apart"],
      "eenss" => ["sense"], "ffstu" => ["stuff"], "begnu" => ["begun"],
      "addde" => ["added"], "eistx" => ["exist"], "aceps" => ["space"],
      "ceitw" => ["twice"], "anstw" => ["wants"], "ginow" => ["owing"],
      "adopt" => ["adopt"], "ahppy" => ["happy"], "aalmr" => ["alarm"],
      "abiss" => ["basis"], "epsty" => ["types"], "ceiov" => ["voice"],
      "abekr" => ["break"], "aersy" => ["years"], "deens" => ["needs"],
      "eiltt" => ["title"], "defix" => ["fixed"], "ckstu" => ["stuck"],
      "eeksw" => ["weeks"], "dgino" => ["doing"], "ciprs" => ["crisp"],
      "orstw" => ["worst"], "abcis" => ["basic"], "acess" => ["cases"],
      "dnosu" => ["sound"], "aadrw" => ["award"], "adlsy" => ["sadly"],
      "afhls" => ["flash"], "aclls" => ["calls"], "denru" => ["under"],
      "adeis" => ["aside", "ideas"], "acfst" => ["facts"], "hmotu" => ["mouth"],
      "psttu" => ["putts"], "adely" => ["delay"], "ehost" => ["those"],
      "delor" => ["older"], "abdor" => ["board"], "aegsu" => ["usage"],
      "effor" => ["offer"], "efhrs" => ["fresh"], "aclss" => ["class"],
      "aeknt" => ["taken"], "eequu" => ["queue"], "ehlos" => ["holes"],
      "ceorv" => ["cover"], "ablmu" => ["album"], "ehirt" => ["their"],
      "eirtw" => ["write"], "aehms" => ["shame"], "deilv" => ["lived"],
      "ahrst" => ["trash"], "aflot" => ["float"], "ccehk" => ["check"],
      "alpsy" => ["plays"], "dhlos" => ["holds"], "dnopu" => ["pound"],
      "dilos" => ["solid"], "achpt" => ["patch"], "aeguv" => ["vague"],
      "ehors" => ["horse"], "imnor" => ["minor"], "agnrt" => ["grant"],
      "illsy" => ["silly"], "aails" => ["alias"], "efils" => ["files", "flies"],
      "horsu" => ["hours"], "eenrv" => ["never"], "korsw" => ["works"],
      "ggino" => ["going"], "floor" => ["floor"], "agrsu" => ["sugar"],
      "deirt" => ["tried"], "adesv" => ["saved"], "dginr" => ["grind"],
      "cnotu" => ["count"], "biltu" => ["built"], "orrsy" => ["sorry"],
      "dehop" => ["hoped"], "deeps" => ["speed"], "adimt" => ["admit"],
      "acprs" => ["scrap"], "abdnr" => ["brand"], "aefmr" => ["frame"],
      "ciopt" => ["topic"], "gnorw" => ["grown", "wrong"], "aelno" => ["alone"],
      "aertt" => ["treat"], "eorsw" => ["worse"], "erssu" => ["users"],
      "adgnr" => ["grand"], "efhls" => ["shelf"], "deirv" => ["drive"],
      "alsuu" => ["usual"], "eortw" => ["wrote"], "eersv" => ["serve"],
      "elnov" => ["novel"], "flnow" => ["flown"], "bdotu" => ["doubt"],
      "diknr" => ["drink"], "acehr" => ["reach"], "deems" => ["deems"],
      "eirst" => ["tries"], "hossw" => ["shows"], "eehrt" => ["there", "three"],
      "nrstu" => ["turns"], "horst" => ["short"], "afiln" => ["final"],
      "eefrr" => ["refer"], "eerst" => ["trees"], "aeprs" => ["spare"],
      "hinst" => ["hints"], "aegnr" => ["range"], "aeppr" => ["paper"],
      "allsw" => ["walls"], "rsttu" => ["trust"], "ainrt" => ["train"],
      "ceelt" => ["elect"], "aerst" => ["rates"], "eloss" => ["loses"],
      "delmo" => ["model"], "aekps" => ["speak"], "almor" => ["moral"],
      "ehlps" => ["helps"], "flluy" => ["fully"], "aegln" => ["angle"],
      "dfins" => ["finds"], "benor" => ["borne"], "ellst" => ["tells"],
      "aelry" => ["early"], "eisst" => ["sites"], "adrsw" => ["draws"],
      "jmpsu" => ["jumps"], "eervy" => ["every"], "eekss" => ["seeks"],
      "aelss" => ["sales"], "befir" => ["brief"], "adehs" => ["heads"],
      "aeent" => ["eaten"], "acels" => ["scale"], "acdrs" => ["cards"],
      "chips" => ["chips"], "gorss" => ["gross"], "achrs" => ["chars", "crash"],
      "gopru" => ["group"], "alsst" => ["lasts"], "knrtu" => ["trunk"],
      "dikns" => ["kinds"], "aekms" => ["makes"], "adepy" => ["payed"],
      "ginty" => ["tying"], "eehrw" => ["where"], "eghit" => ["eight"],
      "demov" => ["moved"], "degiu" => ["guide"], "eemny" => ["enemy"],
      "beist" => ["bites"], "dimns" => ["minds"], "adily" => ["daily"],
      "eehtt" => ["teeth"], "enopr" => ["prone"], "celos" => ["close"],
      "orsuy" => ["yours"], "achos" => ["chaos"], "elrsu" => ["rules"],
      "hopss" => ["shops"], "achmr" => ["march"], "ilpst" => ["split"],
      "dfnsu" => ["funds"], "acetx" => ["exact"], "bnorw" => ["brown"],
      "emnoy" => ["money"], "diott" => ["ditto"], "hnort" => ["north"],
      "adnrw" => ["drawn"], "eilns" => ["lines"], "cikqu" => ["quick"],
      "aegms" => ["games"], "ekops" => ["spoke"], "ghint" => ["night", "thing"],
      "adhns" => ["hands"], "cosst" => ["costs"], "eoqtu" => ["quote"],
      "dlorw" => ["world"], "eirrv" => ["river"], "ahlls" => ["shall"],
      "bdilu" => ["build"], "enorw" => ["owner"], "cdlou" => ["could"],
      "aestw" => ["waste"], "hnosw" => ["shown"], "deiov" => ["video"],
      "aegst" => ["stage"], "eellv" => ["level"], "bginr" => ["bring"],
      "adnst" => ["stand"], "ghist" => ["sight"], "ghimt" => ["might"],
      "aceep" => ["peace"], "ilsst" => ["lists"], "allow" => ["allow"],
      "bcklo" => ["block"], "ijnot" => ["joint"], "aefrs" => ["safer"],
      "eimrt" => ["merit"], "adehr" => ["heard"], "ccoru" => ["occur"],
      "cemos" => ["comes"], "gorsw" => ["grows"], "afhit" => ["faith"],
      "eilsv" => ["lives"], "akmrs" => ["marks"], "elosv" => ["solve"],
      "eorrr" => ["error"], "eimov" => ["movie"], "ehort" => ["other"],
      "ahknt" => ["thank"], "foopr" => ["proof"], "aeilv" => ["alive"],
      "iilmt" => ["limit"], "ailrt" => ["trial"], "eefrw" => ["fewer"],
      "below" => ["below"], "ghilt" => ["light"], "chotu" => ["touch"],
      "aegll" => ["legal"], "aelmt" => ["metal"], "beosx" => ["boxes"],
      "dehis" => ["hides"], "ceinr" => ["nicer"], "eostv" => ["votes"],
      "aaflt" => ["fatal"], "cgilo" => ["logic"], "emrst" => ["terms"],
      "anrsw" => ["warns"], "hrttu" => ["truth"], "aemsu" => ["amuse"],
      "deirw" => ["weird", "wider"], "eortu" => ["outer", "route"],
      "adior" => ["radio"], "alppy" => ["apply"], "aaers" => ["areas"],
      "cimsu" => ["music"], "aeinv" => ["naive"], "hoott" => ["tooth"],
      "aestt" => ["state", "taste"], "begin" => ["begin", "being"],
      "eilms" => ["miles", "smile"], "fklos" => ["folks"],
      "enost" => ["notes", "stone"], "deefs" => ["feeds"], "abkln" => ["blank"],
      "acees" => ["cease"], "aepst" => ["tapes"], "ckrtu" => ["truck"],
      "aceht" => ["teach"], "adery" => ["ready"], "ccklo" => ["clock"],
      "achir" => ["chair"], "ilmpy" => ["imply"], "ademr" => ["dream"],
      "eimst" => ["items", "times"], "enops" => ["opens"], "isstu" => ["suits"],
      "ceipr" => ["price"], "ginss" => ["signs"], "aprst" => ["parts", "traps"],
      "fnort" => ["front"], "aklsw" => ["walks"], "addet" => ["dated"],
      "acrry" => ["carry"], "acdet" => ["acted"], "acelr" => ["clear"],
      "afltu" => ["fault"], "dfnou" => ["found"], "adeht" => ["death"],
      "ghirt" => ["right"], "eehlw" => ["wheel"], "aeglr" => ["large"],
      "eehst" => ["sheet", "these"], "emnow" => ["women"], "abesu" => ["abuse"],
      "orrwy" => ["worry"], "epstu" => ["upset"], "eorst" => ["store"],
      "cortu" => ["court"], "eoprv" => ["prove"], "cefor" => ["force"],
      "acgim" => ["magic"], "ceens" => ["scene"], "abell" => ["label"],
      "acers" => ["cares"], "eissz" => ["sizes"], "aceln" => ["clean"],
      "eipst" => ["spite"], "acryz" => ["crazy"], "ajmor" => ["major"],
      "acfny" => ["fancy"], "allms" => ["small"],
      "opsst" => ["posts", "spots", "stops"], "ijnos" => ["joins"],
      "ehlls" => ["shell"], "eintu" => ["unite"], "knosw" => ["knows"],
      "aklst" => ["talks"], "fmors" => ["forms"], "aglss" => ["glass"],
      "aertw" => ["water"], "aehvy" => ["heavy"], "doost" => ["stood"],
      "ckkno" => ["knock"], "dnoru" => ["round"], "adelt" => ["dealt"],
      "aehrt" => ["earth", "heart"], "alnpt" => ["plant"], "eegnr" => ["green"],
      "fnnuy" => ["funny"], "bkoos" => ["books"], "aehrs" => ["hears", "share"],
      "acelp" => ["place"], "dlouw" => ["would"], "abckl" => ["black"],
      "bdins" => ["binds"], "ehitw" => ["white"], "aemns" => ["means", "names"],
      "fills" => ["fills"], "adlos" => ["loads"], "ehnop" => ["phone"],
      "aersw" => ["wears"], "ceors" => ["score"], "aaerw" => ["aware"],
      "einnr" => ["inner"], "aelrt" => ["alter", "later"], "elsty" => ["style"],
      "lrtuy" => ["truly"], "cikrt" => ["trick"], "ghitt" => ["tight"],
      "iklns" => ["links"], "hortw" => ["throw", "worth"], "dgoos" => ["goods"],
      "hoost" => ["shoot"], "abcks" => ["backs"], "lorry" => ["lorry"],
      "efnot" => ["often"], "affst" => ["staff"], "llpsu" => ["pulls"],
      "eginv" => ["given"], "aders" => ["reads"], "ilntu" => ["until"],
      "abdes" => ["based"], "aegrv" => ["grave"], "dstuy" => ["study"],
      "deimt" => ["timed"], "aiprs" => ["pairs"], "adeil" => ["ideal"],
      "aegim" => ["image"], "ansty" => ["nasty"], "ceehn" => ["hence"],
      "aelnr" => ["learn"], "dirty" => ["dirty"], "bdnou" => ["bound"],
      "ehlot" => ["hotel"], "moors" => ["rooms"], "eemss" => ["seems"],
      "hostu" => ["south"], "ellss" => ["sells"], "eisvw" => ["views"],
      "aegps" => ["pages"], "aekst" => ["takes"], "cdiss" => ["discs"],
      "denoz" => ["dozen"], "acilm" => ["claim"], "cklos" => ["locks"],
      "cehos" => ["chose"], "eloos" => ["loose"], "admtu" => ["datum"],
      "efisx" => ["fixes"], "chlnu" => ["lunch"], "inprt" => ["print"],
      "annoy" => ["annoy"], "egssu" => ["guess"], "aknst" => ["tanks"],
      "eekps" => ["keeps"], "emssy" => ["messy"], "aegrt" => ["great"],
      "iistv" => ["visit"], "deiss" => ["sides"], "aessv" => ["saves"],
      "hrruy" => ["hurry"], "eentv" => ["event"], "denps" => ["spend"],
      "aelst" => ["least", "steal"]}
    |> Map.get(string_id)
  end
end
