defmodule Jumble.ScowlDict.Size10.Length3 do
  def get(string_id) do
    %{"hot" => ["hot"], "ctu" => ["cut"], "afr" => ["far"], "abd" => ["bad"],
      "bgi" => ["big"], "imx" => ["mix"], "nru" => ["run"], "bde" => ["bed"],
      "lot" => ["lot"], "eil" => ["lie"], "deu" => ["due"], "fnu" => ["fun"],
      "afn" => ["fan"], "eit" => ["tie"], "ehr" => ["her"],
      "now" => ["now", "own", "won"], "amy" => ["may"], "atx" => ["tax"],
      "aly" => ["lay"], "ddo" => ["odd"], "opp" => ["pop"], "est" => ["set"],
      "aet" => ["ate", "eat", "tea"], "orw" => ["row"], "ill" => ["ill"],
      "dei" => ["die"], "den" => ["end"], "aim" => ["aim"], "ilo" => ["oil"],
      "emn" => ["men"], "nsu" => ["sun"], "rty" => ["try"], "oru" => ["our"],
      "enp" => ["pen"], "alw" => ["law"], "cei" => ["ice"], "ent" => ["net", "ten"],
      "eey" => ["eye"], "add" => ["add"], "ady" => ["day"], "def" => ["fed"],
      "bet" => ["bet"], "ads" => ["sad"], "eht" => ["the"], "esu" => ["use"],
      "ast" => ["sat"], "guy" => ["guy"], "anr" => ["ran"], "dir" => ["rid"],
      "anv" => ["van"], "del" => ["led"], "aer" => ["are"], "bjo" => ["job"],
      "ffo" => ["off"], "dry" => ["dry"], "boy" => ["boy"], "act" => ["act", "cat"],
      "deo" => ["doe"], "eno" => ["one"], "amp" => ["map"], "eow" => ["owe"],
      "dmo" => ["mod"], "enw" => ["new"], "aht" => ["hat"], "ist" => ["its", "sit"],
      "ahs" => ["has"], "ehs" => ["hes", "she"], "acr" => ["car"], "adh" => ["had"],
      "esy" => ["yes"], "bit" => ["bit"], "apy" => ["pay"], "abr" => ["bar"],
      "dlo" => ["old"], "all" => ["all"], "eky" => ["key"], "fix" => ["fix"],
      "buy" => ["buy"], "got" => ["got"], "aeg" => ["age"], "ees" => ["see"],
      "adi" => ["aid"], "his" => ["his"], "fly" => ["fly"], "int" => ["tin"],
      "air" => ["air"], "not" => ["not"], "any" => ["any"], "fry" => ["fry"],
      "aks" => ["ask"], "dhi" => ["hid"], "art" => ["art"], "asy" => ["say"],
      "ptu" => ["put"], "emt" => ["met"], "adn" => ["and"], "joy" => ["joy"],
      "low" => ["low"], "isx" => ["six"], "elt" => ["let"], "hwy" => ["why"],
      "ddi" => ["did"], "opt" => ["top"], "hit" => ["hit"], "bdi" => ["bid"],
      "efw" => ["few"], "otu" => ["out"], "egl" => ["leg"], "asw" => ["saw", "was"],
      "ouy" => ["you"], "how" => ["how", "who"], "ags" => ["gas"], "egt" => ["get"],
      "amr" => ["arm"], "dgo" => ["dog"], "nos" => ["son"], "der" => ["red"],
      "oot" => ["too"], "fit" => ["fit"], "abn" => ["ban"], "amn" => ["man"],
      "cry" => ["cry"], "arw" => ["raw", "war"], "esx" => ["sex"], "box" => ["box"],
      "agp" => ["gap"], "cpu" => ["cup"], "ago" => ["ago"], "adm" => ["mad"],
      "acn" => ["can"], "msu" => ["sum"], "epr" => ["per"], "awy" => ["way"],
      "btu" => ["but"], "ety" => ["yet"], "glo" => ["log"], "dik" => ["kid"],
      "gnu" => ["gun"], "bgu" => ["bug"], "nor" => ["nor"], "otw" => ["two"],
      "inw" => ["win"], "for" => ["for"], "bsu" => ["bus"], "him" => ["him"],
      "aiv" => ["via"], "err" => ["err"]}
    |> Map.get(string_id)
  end
end
