defmodule Jumble.LengthDict.Length3 do
  def get(string_id) do
    %{"fmr" => ["mfr"], "bez" => ["bez"], "Aes" => ["Ase"], "Sak" => ["Sak"],
      "CGM" => ["CGM", "CMG", "GCM", "GMC"], "loy" => ["loy"], "Flr" => ["Frl"],
      "Try" => ["Tyr"], "DLN" => ["DNL", "NDL"],
      "abo" => ["abo", "aob", "boa", "oba"], "aek" => ["ake", "kae", "kea"],
      "fgk" => ["kgf"], "BFI" => ["FBI", "FIB", "IFB"], "Man" => ["Man"],
      "AVX" => ["VAX"], "imz" => ["miz"], "CMU" => ["CMU", "MCU"],
      "SSW" => ["SSW", "SWS"], "hot" => ["hot", "tho"],
      "aem" => ["ame", "eam", "mae", "mea"], "oow" => ["woo"],
      "NOS" => ["NOS", "NSO", "OSN"], "Aan" => ["Ana"], "LPW" => ["LWP"],
      "PSU" => ["PSU", "SPU", "UPS", "USP"], "DNO" => ["OND"], "GNU" => ["GNU"],
      "ctu" => ["cut", "utc"], "afr" => ["arf", "far", "fra", "raf"],
      "mux" => ["mux"], "AAX" => ["AAX"], "zzz" => ["zzz"],
      "MNS" => ["MNS", "MSN", "NMS", "SNM"], "eoy" => ["oye", "yeo", "yoe"],
      "GNP" => ["GNP", "NPG"], "ahk" => ["hak", "kha"],
      "CFS" => ["CSF", "FCS", "SCF"], "IRS" => ["IRS", "ISR", "RSI", "SIR", "SRI"],
      "Nce" => ["Nec"], "COV" => ["CVO", "VCO"], "Igo" => ["Igo"], "Cis" => ["Cis"],
      "RVs" => ["RVs"], "dgu" => ["dug", "gud"], "abd" => ["abd", "bad", "dab"],
      "Gel" => ["Gel", "Gle"], "EUW" => ["WEU"], "Dbi" => ["Dib"],
      "lor" => ["lor", "orl"], "GOS" => ["GOS"],
      "hip" => ["hip", "ihp", "iph", "phi"], "afp" => ["afp", "fap"],
      "elu" => ["leu", "lue", "ule"], "swy" => ["swy"], "DJT" => ["DJT"],
      "CPR" => ["CPR", "CRP", "PRC", "RCP", "RPC"], "EMR" => ["EMR", "MRE", "REM"],
      "CDT" => ["CDT", "CTD", "DCT", "DTC", "TDC"], "BGT" => ["GBT"],
      "Zim" => ["Zim"], "Sim" => ["Sim"], "BNT" => ["BTN", "TNB"], "Aem" => ["Ame"],
      "DDJ" => ["DDJ"], "EIP" => ["IPE", "PEI"], "inu" => ["uni"], "Oms" => ["Oms"],
      "Gbi" => ["Gib"], "RTU" => ["RTU", "TUR", "UTR"], "EGK" => ["EKG"],
      "IPS" => ["IPS", "ISP", "PSI", "SIP", "SPI"], "bgi" => ["big", "gib"],
      "FPP" => ["FPP"], "Nru" => ["Nur"],
      "ACN" => ["ANC", "CAN", "CNA", "NAC", "NCA"], "osy" => ["oys", "soy", "yos"],
      "Rdo" => ["Rod"], "Tak" => ["Tak"], "Abu" => ["Abu"], "Kew" => ["Kew"],
      "MOU" => ["MOU"], "eff" => ["eff"], "BJS" => ["BSJ", "JBS"],
      "Kaw" => ["Kaw", "Kwa"], "pru" => ["pur", "urp"], "FIV" => ["IVF"],
      "Lir" => ["Lir"], "Ull" => ["Ull"], "imx" => ["mix"],
      "CLU" => ["CLU", "CUL", "UCL"], "Kan" => ["Kan"], "Tim" => ["Tim"],
      "bms" => ["msb"], "abf" => ["afb", "fab"], "ikl" => ["ilk", "kil"],
      "nru" => ["nur", "run", "urn"], "ERW" => ["RWE"], "gmy" => ["gym", "myg"],
      "DFI" => ["DFI", "DIF", "IDF"], "ILQ" => ["QLI"], "Mak" => ["Mak"],
      "EIS" => ["EIS", "ESI", "SEI"], "bde" => ["bde", "bed", "deb"],
      "CDV" => ["DVC", "VDC"], "Pat" => ["Pat", "Pta"], "gpt" => ["ptg"],
      "aak" => ["aka"], "dsu" => ["sud", "uds"], "Pai" => ["Pia"], "Bop" => ["Bop"],
      "ABV" => ["BVA", "VAB"], "MSc" => ["MSc", "ScM"], "ADY" => ["DAY"],
      "gox" => ["gox"], "FMM" => ["MFM"], "lot" => ["lot", "tlo", "tol"],
      "Iir" => ["Iri"], "bnw" => ["nbw", "wbn"], "ITU" => ["ITU", "UIT"],
      "Jbo" => ["Job"], "agj" => ["gaj", "jag"], "muy" => ["yum"], "Uan" => ["Una"],
      "CEV" => ["CEV", "ECV"], "cly" => ["cly", "cyl", "lyc"], "ehu" => ["hue"],
      "Tey" => ["Tye"], "Wnu" => ["Wun"], "egn" => ["eng", "gen", "neg"],
      "GTW" => ["TWG"], "civ" => ["civ", "vic"], "elp" => ["lep", "pel"],
      "bgl" => ["glb"], "ehi" => ["hei", "hie"], "Ges" => ["Ges"], "Hbe" => ["Heb"],
      "DGP" => ["DGP", "GDP", "GPD"], "Joo" => ["Joo"], "MSV" => ["MVS", "VMS"],
      "mpw" => ["wpm"], "Peg" => ["Peg"], "Aas" => ["Asa"], "Zak" => ["Zak"],
      "Mno" => ["Mon"], "Keg" => ["Keg"], "Eir" => ["Eri"], "AIL" => ["ALI", "ILA"],
      "egu" => ["gue"], "hnt" => ["nth"], "eov" => ["voe"],
      "AAM" => ["AAM", "AMA", "MAA"], "BDD" => ["BDD", "DDB"], "Den" => ["Den"],
      "bel" => ["bel", "elb"], "ajy" => ["jay"], "Mei" => ["Mei"], "BHT" => ["BHT"],
      "ASU" => ["ASU", "AUS", "USA"], "frt" => ["frt", "tfr", "trf"],
      "htw" => ["hwt"], "gry" => ["gry"], "Eno" => ["Eno"], "MRX" => ["XRM"],
      "ano" => ["noa", "ona"], "Jae" => ["Jae", "Jea"], "aat" => ["taa"],
      "Clo" => ["Clo", "Col"], "ALR" => ["LAR"], "aey" => ["aye", "yea"],
      "eil" => ["eli", "ile", "lei", "lie"], "Aak" => ["Aka"], "deu" => ["due"],
      "MPQ" => ["QMP"], "ILM" => ["LIM", "MIL"], "EIQ" => ["QEI"],
      "HJS" => ["HJS", "JHS"], "CJR" => ["JCR", "JRC"], "Ben" => ["Ben"],
      "bil" => ["lib"], "FPS" => ["FPS", "PSF", "SPF"], "iqu" => ["qui"],
      "ooz" => ["zoo"], "MTW" => ["MWT", "TWM"], "hop" => ["hop", "pho", "poh"],
      "drw" => ["rwd"], "Kel" => ["Kel"], "Gcg" => ["Gcg"], "Ado" => ["Ado"],
      "nno" => ["non"], "Lbi" => ["Lib"], "ggi" => ["gig", "igg"],
      "cfm" => ["cfm", "mcf"], "Wlp" => ["lpW"],
      "ELS" => ["ESL", "LSE", "SEL", "SLE"], "acy" => ["acy", "cay"],
      "npw" => ["pwn"], "MOR" => ["MOR", "ORM", "ROM"],
      "ahp" => ["aph", "hap", "pah"], "apu" => ["pau", "pua"], "ivy" => ["ivy"],
      "IMT" => ["IMT", "ITM", "MIT", "MTI"],
      "aes" => ["aes", "ase", "eas", "sae", "sea"], "ekw" => ["ewk"],
      "COT" => ["COT", "CTO", "OTC", "TOC"], "mmo" => ["mom"], "fnu" => ["fun"],
      "Gan" => ["Gan"], "Tan" => ["Tan"], "ewy" => ["wey", "wye", "yew"],
      "afn" => ["fan", "naf"], "Yeh" => ["Yeh"], "gkr" => ["kgr"], "cex" => ["exc"],
      "BJM" => ["BMJ"], "NRR" => ["RNR"], "ott" => ["tot"], "LXX" => ["LXX", "XXL"],
      "ADI" => ["ADI", "AID", "DIA", "IAD", "IDA"], "psw" => ["psw"],
      "hlo" => ["hol"], "doy" => ["yod"], "Bab" => ["Bab"], "Par" => ["Par"],
      "Jeh" => ["Jeh"], "clt" => ["tlc"], "CMR" => ["MCR", "MRC", "RCM", "RMC"],
      "NRZ" => ["NRZ"], "iju" => ["uji"], "DHW" => ["HWD"], "BIP" => ["BPI"],
      "DGI" => ["GID"], "dev" => ["dev"], "Lad" => ["Lad"], "cgo" => ["cog"],
      "SSV" => ["SVS", "VSS"], "abl" => ["abl", "alb", "bal", "lab"],
      "aft" => ["aft", "fat"], "FIN" => ["FIN"], "Sar" => ["Sar", "Sra"],
      "Tex" => ["Tex"], "Scf" => ["Sfc"], "Zas" => ["Zsa"], "dop" => ["dop", "pod"],
      "Wii" => ["Wii"], "bdo" => ["bod", "dob"], "FLS" => ["FLS", "LFS"],
      "Bbc" => ["Bcb"], "imn" => ["min", "nim"], "csv" => ["svc"], "BPP" => ["PPB"],
      "Biu" => ["Bui"], "DPa" => ["PaD"], "EFR" => ["RFE"], "Nip" => ["Nip"],
      "imm" => ["mim"], "BOY" => ["BYO", "YOB"], "Ros" => ["Ros"],
      "ALT" => ["LAT", "LTA", "TAL", "TLA"], "BKS" => ["KBS"], "gmr" => ["mgr"],
      "sst" => ["tss"], "FIK" => ["KIF"], "crs" => ["crs", "scr"], "Lak" => ["Lak"],
      "mnt" => ["mtn"], "cgi" => ["cig"], "cox" => ["cox"], "fno" => ["fon"],
      "Fbe" => ["Feb"], "Npt" => ["Npt"], "EFV" => ["FEV"], "mps" => ["pms"],
      "FIT" => ["FIT"], "Fde" => ["Fed"], "Oar" => ["Ora"], "fll" => ["fll"],
      "qqs" => ["sqq"], "crt" => ["crt", "ctr", "rct"], "KSW" => ["WKS"],
      "eej" => ["jee"], "chi" => ["chi", "hic", "ich"], "BIN" => ["IBN"],
      "IJS" => ["JIS"], "Bos" => ["Bos"], "Cim" => ["mCi"], "AJP" => ["APJ", "JAP"],
      "GPa" => ["PaG"], "flu" => ["flu"], "aln" => ["aln", "lan"],
      "ops" => ["ops", "pos", "sop"], "Iuw" => ["Iwu"], "BRZ" => ["ZBR"],
      "Ttu" => ["Tut"], "epy" => ["pye", "yep"], "GPW" => ["PWG"],
      "BDN" => ["DNB", "NDB"], "tux" => ["tux"], "Row" => ["Row"], "lnp" => ["lpn"],
      "Koo" => ["Koo"], "Bru" => ["Bur"], "eit" => ["tie"], "otv" => ["tov"],
      "Ahl" => ["Ahl"], "ehr" => ["her", "reh", "rhe"], "ckl" => ["clk"],
      "CEM" => ["ECM", "EMC", "MEC"], "DEM" => ["DME", "MDE", "MED"],
      "JPs" => ["PJs"], "efk" => ["kef"], "Set" => ["Set", "Ste"], "CLW" => ["WCL"],
      "hny" => ["hny"], "GOO" => ["OGO"], "ior" => ["rio", "roi"], "BJP" => ["PBJ"],
      "Kae" => ["Kea"], "Oly" => ["Oly"], "BSc" => ["BSc", "ScB"], "Cor" => ["Cor"],
      "fil" => ["fil", "lif"], "COQ" => ["COQ"], "now" => ["now", "own", "won"],
      "app" => ["app", "pap", "ppa"], "Sap" => ["Spa"], "LNR" => ["NRL"],
      "Rad" => ["Rad"], "lnt" => ["tln"], "glt" => ["glt"], "Aov" => ["Avo"],
      "CMW" => ["CMW", "WMC"], "Frs" => ["Frs"], "Mex" => ["Mex"], "CMQ" => ["QMC"],
      "BCL" => ["BCL"], "DEL" => ["DLE", "LED"], "lnr" => ["lnr"],
      "DLL" => ["DLL", "LDL", "LLD"], "hoy" => ["hoy"], "oos" => ["oos"],
      "Miz" => ["Mzi"], "Nap" => ["Nap"], "acm" => ["cam", "mac"], "hku" => ["khu"],
      "DFW" => ["DFW", "FWD"], "Dav" => ["Dav"], "AAS" => ["AAS", "ASA", "SAA"],
      "Dan" => ["Dan"], "NPV" => ["NPV", "PVN", "VPN"], "MUU" => ["UUM"],
      "ATZ" => ["AZT"], "ovw" => ["vow"], "gmt" => ["gmt", "mgt", "mtg"],
      "EMN" => ["MNE"], "BRR" => ["RRB"], "emr" => ["mer", "rem"],
      "BCP" => ["BCP", "BPC", "PBC", "PCB"], "bfi" => ["fbi", "fib"],
      "Aex" => ["Axe"], "RTW" => ["TRW", "WRT", "WTR"], "CTU" => ["TUC", "UTC"],
      "amy" => ["amy", "may", "mya", "yam"], "GPX" => ["XPG"], "FFT" => ["FFT"],
      "ajn" => ["jan"], "EGT" => ["GTE"], "atx" => ["tax", "xat"],
      "MMW" => ["MMW", "MWM"], "ILN" => ["INL"], "frs" => ["frs", "rfs"],
      "Pmy" => ["Pym"], "BLP" => ["LBP"], "ikm" => ["kim"],
      "dep" => ["dep", "edp", "ped"], "ept" => ["pet", "pte"],
      "ENT" => ["ENT", "ETN", "NET"], "Bmu" => ["Bum"], "Dao" => ["Dao"],
      "CCT" => ["CCT", "CTC", "TCC"], "IRV" => ["VIR", "VRI"], "GIs" => ["GIs"],
      "PSS" => ["PSS", "SPS", "SSP"], "HRV" => ["RHV"], "Ket" => ["Ket"],
      "psy" => ["spy"], "EIg" => ["IgE"], "AHQ" => ["AHQ"], "Wil" => ["Wil"],
      "Roy" => ["Roy"], "DNX" => ["DNX"], "Jal" => ["Jal"],
      "amt" => ["amt", "atm", "mat", "tam"], "clu" => ["cul"], "fik" => ["kif"],
      "Gos" => ["Gos"], "aps" => ["asp", "pas", "sap", "spa"],
      "ILU" => ["LIU", "UIL"], "itt" => ["tit"], "rsy" => ["syr", "yrs"],
      "Rsu" => ["Rus"], "INR" => ["IRN", "NIR"], "aly" => ["aly", "lay"],
      "AEG" => ["AGE", "EGA"], "QSS" => ["QSS"], "Edn" => ["End"],
      "DIV" => ["DIV", "IDV", "VDI"], "Mir" => ["Mir"], "Dev" => ["Dev"],
      "eqr" => ["req"], "IIP" => ["IPI"], "bow" => ["bow", "wob"],
      "CNP" => ["NCP", "NPC", "PCN"], "prt" => ["rpt", "trp"], "Tam" => ["Tam"],
      "aoz" => ["azo", "zoa"], "KPU" => ["PKU"], "Ial" => ["Ila"],
      "ddo" => ["dod", "odd"], "CTX" => ["XTC"], "CMO" => ["COM", "MOC"],
      "akr" => ["ark", "kra"], "Pot" => ["Pto"], "alx" => ["lax"], "Pir" => ["Pri"],
      "LTV" => ["LTV", "TLV", "VLT"], "iil" => ["lii"], "Oaz" => ["Oza"],
      "cht" => ["tch"], "GPU" => ["GPU"], "mpv" => ["mvp"],
      "EOS" => ["EOS", "ESO", "OES"], "Chi" => ["Chi"], "Tet" => ["Tet"],
      "ACP" => ["ACP", "APC", "CAP", "CPA", "PAC", "PCA"], "FTT" => ["TFT"],
      "XYZ" => ["XYZ"], "Rap" => ["Rap"], "ell" => ["ell"], "HJK" => ["HKJ"],
      "Cai" => ["Cai", "Cia"], "AAC" => ["CAA"], "FSS" => ["FSS", "SSF"],
      "Lan" => ["Lan"], "Iey" => ["Iey"], "Mor" => ["Mor"], "CRW" => ["RWC"],
      "euy" => ["uey", "yue"], "foy" => ["foy"], "FRV" => ["VFR"], "BTX" => ["XBT"],
      "dkl" => ["dkl"], "diy" => ["yid"], "esz" => ["sez"], "How" => ["How"],
      "Ohl" => ["Ohl"], "ors" => ["ors", "ros"], "DFU" => ["FUD"], "Cad" => ["Cad"],
      "Pip" => ["Pip"], "Sal" => ["Sal"], "Net" => ["Net"],
      "AMU" => ["AMU", "AUM", "MAU", "MUA", "UAM"], "BGZ" => ["GBZ"],
      "DGR" => ["DRG", "GDR", "GRD"], "dix" => ["dix"],
      "GIN" => ["GIN", "ING", "NIG"], "eny" => ["eyn", "nye", "yen"],
      "enn" => ["nne"], "IOS" => ["ISO", "OSI"], "Qmu" => ["Qum"], "Coo" => ["Coo"],
      "qqv" => ["qqv"], "Bak" => ["Bak"], "EEG" => ["EEG"], "GIU" => ["GUI"],
      "Hbi" => ["Hib"], "dim" => ["dim", "mid"], "beg" => ["beg", "geb"],
      "cno" => ["con", "nco"], "AHP" => ["HAP", "PHA"], "Ldg" => ["Ldg"],
      "fio" => ["iof"], "ARW" => ["RWA", "WRA"], "bsw" => ["sbw", "wbs"],
      "Kmu" => ["Kum"], "ajw" => ["jaw"], "opp" => ["opp", "pop"],
      "CCP" => ["CCP", "CPC", "PCC"], "eeg" => ["eeg", "gee"],
      "BDE" => ["BED", "DBE", "EDB"], "CCF" => ["CCF", "CFC", "FCC"],
      "Yuu" => ["Yuu"], "dqt" => ["qtd"], "lou" => ["luo"], "Sku" => ["Suk"],
      "CDO" => ["CDO", "COD", "DCO", "DOC", "OCD"], "AFY" => ["FYA"],
      "DDH" => ["HDD"], "FNT" => ["NFT", "NTF"], "KST" => ["KTS"], "kop" => ["kop"],
      "Lab" => ["Lab"], "aot" => ["oat", "tao", "toa"], "ilx" => ["lix", "lxi"],
      "DER" => ["DRE", "ERD"], "FOR" => ["FOR"], "NTW" => ["NWT"], "Tgn" => ["Tng"],
      "Sky" => ["Sky"], "BMX" => ["BMX"], "Ail" => ["Ali"], "ddm" => ["dmd"],
      "Kal" => ["Kal"], "est" => ["est", "set", "tes"], "Kat" => ["Kat"],
      "PPS" => ["PPS", "PSP"], "Lal" => ["Lal"], "GIV" => ["VGI"], "ADH" => ["HDA"],
      "EHW" => ["HEW"], "aet" => ["aet", "ate", "eat", "eta", "tae", "tea"],
      "iio" => ["oii"], "auv" => ["uva", "vau"], "flo" => ["flo", "fol", "lof"],
      "bch" => ["bch", "hcb"], "ilr" => ["lir"], "Sad" => ["Sad"],
      "CHR" => ["HCR", "RCH", "RHC"], "CII" => ["CII", "ICI"], "Mko" => ["Mok"],
      "DTW" => ["WDT"], "GMk" => ["MGk"], "EPS" => ["EPS", "ESP", "PSE", "SPE"],
      "Cby" => ["Cyb"], "DTU" => ["DTU", "DUT", "UDT"], "Blu" => ["Blu", "Bul"],
      "CEL" => ["ECL", "ELC", "LEC"], "Iar" => ["Ira"], "deh" => ["edh", "hed"],
      "IOT" => ["IOT", "ITO"], "cpt" => ["cpt", "pct", "tcp"], "Rip" => ["Rip"],
      "NOU" => ["UNO"], "Ceh" => ["Che"], "HSV" => ["VHS"], "For" => ["For"],
      "FMk" => ["FMk"], "LNT" => ["TLN"], "imo" => ["imo", "moi"], "FGM" => ["MFG"],
      "mru" => ["rum"], "Nde" => ["Ned"], "Bae" => ["Bea"], "ssw" => ["ssw"],
      "orw" => ["row", "wro"], "MRV" => ["VMR", "VRM"], "Uor" => ["Uro"],
      "dos" => ["dos", "dso", "ods", "sod"], "inn" => ["inn"], "bfr" => ["rfb"],
      "Zel" => ["Zel"], "Zfi" => ["Zif"], "etw" => ["ewt", "tew", "wet"],
      "BFN" => ["BNF"], "Dio" => ["Doi"], "aqu" => ["qua"], "EHT" => ["ETH"],
      "kou" => ["kou", "ouk"], "qst" => ["qts"], "dht" => ["thd"], "ill" => ["ill"],
      "DIs" => ["IDs"], "IPR" => ["PRI", "RIP", "RPI"], "Bad" => ["dBa"],
      "Nmy" => ["Nym"], "ASV" => ["ASV"], "Heo" => ["Hoe"],
      "DHL" => ["DHL", "HDL", "LHD"], "hsw" => ["whs"], "Aev" => ["Ave"],
      "Adl" => ["Ald"], "dei" => ["dei", "die", "ide"],
      "DIU" => ["DIU", "DUI", "IUD", "UDI", "UID"], "Lek" => ["Lek"],
      "oty" => ["toy", "yot"], "Ziv" => ["Ziv"], "Ogn" => ["Ong"], "Erz" => ["Ezr"],
      "DHM" => ["MHD"], "Uin" => ["Uni"], "Oer" => ["Ore"], "Ier" => ["Ier", "Ire"],
      "diw" => ["wid"], "kno" => ["kon"], "bcc" => ["cbc"],
      "INS" => ["INS", "ISN", "NIS", "SIN"], "Smo" => ["Som"],
      "hrs" => ["hrs", "shr"], "Ten" => ["Ten"], "SUW" => ["USW", "UWS"],
      "hpp" => ["pph"], "DEd" => ["DEd", "EdD"], "Sau" => ["Sau"], "Mas" => ["Mas"],
      "CCO" => ["COC", "OCC"], "cmu" => ["cum"], "bio" => ["bio", "obi"],
      "Adi" => ["Adi"], "BPW" => ["PWB", "WPB"], "Oby" => ["Oby"], "Mes" => ["Mes"],
      "fop" => ["fop"], "MVY" => ["MVY"], "Dix" => ["Dix"], "Rct" => ["Rct"],
      "CLL" => ["LCL", "LLC"], "Gnu" => ["Gun"], "Air" => ["Air", "Ari"],
      "DSV" => ["DVS", "SDV"], "BDU" => ["UDB"], "Gav" => ["Gav"], "Lem" => ["Lem"],
      "ENP" => ["NEP", "PEN"], "cju" => ["cuj"], "EHO" => ["HEO"], "TUU" => ["UUT"],
      "BUV" => ["UVB"], "DSW" => ["DSW", "WSD"], "Fem" => ["Fem"], "Geo" => ["Geo"],
      "AUV" => ["UVA"], "Mcf" => ["Mcf"], "hmm" => ["hmm"], "ESW" => ["EWS"],
      "Wde" => ["Wed"], "Ert" => ["Etr"], "Aku" => ["Auk"], "Jer" => ["Jer"],
      "ipv" => ["vip"], "CDR" => ["CDR", "CRD", "RDC"],
      "ALS" => ["ALS", "ASL", "SLA"], "Abe" => ["Abe"],
      "IMN" => ["MIN", "NIM", "NMI"], "lmo" => ["mol", "olm"], "Abo" => ["Abo"],
      "ERT" => ["ERT", "ETR", "TER"], "DMR" => ["MRD", "RDM"], "Ehr" => ["Ehr"],
      "Bde" => ["Bde"], "Pop" => ["Pop"], "AKP" => ["PAK"], "Gen" => ["Gen"],
      "Uir" => ["Uri"], "IMS" => ["IMS", "ISM", "MIS", "MSI", "SMI"],
      "AOT" => ["ATO", "OAT", "OTA", "TAO"], "ACU" => ["ACU", "AUC", "CAU", "CUA"],
      "Vor" => ["Vor"], "AET" => ["AET", "ATE", "ETA", "TAE"],
      "hor" => ["hor", "rho"], "ein" => ["nei", "nie"], "IVX" => ["VXI"],
      "den" => ["den", "end", "ned"], "bpy" => ["byp"], "Fir" => ["Fri"],
      "AIM" => ["AIM", "AMI", "IAM", "MIA"], "HLV" => ["HLV"], "Cat" => ["Cat"],
      "FMP" => ["FPM"], "cit" => ["cit", "tic"], "Lfi" => ["Lif"],
      "MPV" => ["MPV", "MVP"], "Lru" => ["Lur"], "aim" => ["aim", "ami", "mia"],
      "ORT" => ["ORT", "OTR", "ROT"], "BMO" => ["BMO", "BOM", "MBO", "OMB"],
      "bgn" => ["nbg"], "ekz" => ["zek"],
      "FOS" => ["FOS", "OFS", "OSF", "SFO", "SOF"], "Aiv" => ["Avi"],
      "itz" => ["zit"], "Ydi" => ["Yid"], "BLL" => ["BLL", "LBL", "LLB"],
      "FFV" => ["FFV"], "APT" => ["APT", "ATP", "PAT", "PTA", "TAP"],
      "uzz" => ["zuz"], "ILT" => ["TLI"],
      "ACE" => ["ACE", "AEC", "CAE", "CEA", "ECA"], "iko" => ["koi", "oik", "oki"],
      "ilo" => ["ilo", "oil"], "oss" => ["sos"], "Hag" => ["Hag"], "Dbo" => ["Dob"],
      "gim" => ["gim", "mig"], "Laz" => ["Laz"], "fgo" => ["fog"], "Oal" => ["Ola"],
      "BDT" => ["BDT", "DTB", "TBD"], "AOQ" => ["AOQ"], "emn" => ["men"],
      "JRS" => ["RSJ"], "Lil" => ["Lil"], "BGJ" => ["GBJ"], "rsu" => ["sur", "urs"],
      "EFP" => ["FEP", "FPE"], "FMO" => ["OFM"], "AMQ" => ["QAM"], "Neh" => ["Neh"],
      "avx" => ["vax"], "AGU" => ["AGU"], "Gag" => ["Gag"], "AHY" => ["AYH", "YHA"],
      "DLX" => ["LDX"], "eik" => ["eik", "ike", "kie"], "www" => ["www"],
      "Uis" => ["Uis"], "cfh" => ["cfh", "hcf"], "chm" => ["chm"], "bbu" => ["bub"],
      "jos" => ["ojs"], "BEG" => ["BGE", "GBE"], "nsu" => ["nus", "sun", "uns"],
      "APP" => ["APP", "PAP", "PPA"], "Jnr" => ["Jnr"], "imu" => ["imu"],
      "acu" => ["uca"], "Skt" => ["Skt"], "AUW" => ["AWU", "UAW"], "Mat" => ["Mat"],
      "Tpw" => ["Twp"], "FJK" => ["JFK"], "elr" => ["ler", "rel", "rle"],
      "Bau" => ["Bau"], "afm" => ["fam", "mfa"], "NSW" => ["NSW", "NWS", "WSN"],
      "Tpr" => ["Tpr"], "Egk" => ["Egk"], "ilp" => ["ipl", "lip", "pil", "pli"],
      "hss" => ["ssh"], "Iab" => ["Iba"], "DDX" => ["DDX"], "jnr" => ["jnr"],
      "duw" => ["wud"], "ABR" => ["BAR"], "rty" => ["try", "tyr"], "abe" => ["bae"],
      "Woy" => ["Wyo"], "BIR" => ["BRI", "RBI"], "CLN" => ["LCN", "NLC"],
      "opu" => ["oup", "upo"], "Win" => ["Win"], "DTV" => ["VDT"], "coo" => ["coo"],
      "oru" => ["our"], "fot" => ["fot", "oft"], "Vci" => ["Vic"],
      "orx" => ["rox", "xor"], "MMT" => ["MMT", "MTM"], "JMS" => ["JMS", "MSJ"],
      "etz" => ["tez"], "ipt" => ["pit", "tip", "tpi"], "PUV" => ["VUP"],
      "Snr" => ["Snr"], "ahi" => ["ahi", "hia"], "EMU" => ["EMU"],
      "AHL" => ["AHL", "HAL", "HLA"], "FMs" => ["FMs"], "BCT" => ["TCB"],
      "Hen" => ["Hen"], "LRT" => ["RLT", "RTL"], "los" => ["los", "sol"],
      "Zip" => ["Zip"], "nov" => ["nov", "von"], "PPP" => ["PPP"], "cpy" => ["cyp"],
      "dll" => ["ldl", "lld"], "emu" => ["emu", "meu", "ume"],
      "CHL" => ["HCL", "HLC"], "Lai" => ["Lai", "Lia"], "epx" => ["exp"],
      "iiv" => ["vii"], "Dem" => ["Dem"], "ben" => ["ben", "ebn", "nbe", "neb"],
      "BRU" => ["BUR"], "kmw" => ["wmk"], "egv" => ["evg", "veg"],
      "AIT" => ["ATI", "ITA", "TIA"], "lno" => ["nol"],
      "mst" => ["mst", "mts", "stm"], "LMN" => ["NLM"], "ccm" => ["ccm"],
      "cnt" => ["ctn"], "kmt" => ["mkt"], "enp" => ["nep", "pen"], "EFI" => ["EFI"],
      "Lku" => ["Luk"], "alw" => ["alw", "awl", "law"], "bir" => ["rbi", "rib"],
      "cei" => ["cie", "ice"], "BIT" => ["BIT"], "AAK" => ["AKA"],
      "AOU" => ["AOU", "OAU"], "BEW" => ["BEW"], "ent" => ["net", "ten"],
      "Ody" => ["Ody"], "bll" => ["llb"], "Vgi" => ["Vig"], "cef" => ["fec"],
      "Tad" => ["Tad"], "Tor" => ["Tor", "Tro"], "Pau" => ["Pau"], "FIY" => ["FYI"],
      "CNR" => ["CNR", "NCR", "NRC", "RCN"], "iii" => ["iii"], "grx" => ["grx"],
      "MPU" => ["MPU", "MUP", "PMU"], "ajk" => ["jak"], "FTW" => ["FTW", "WTF"],
      "eez" => ["zee"], "Dot" => ["Dot"], "mmu" => ["mum", "umm"],
      "AEP" => ["APE", "EPA"], "Orr" => ["Orr"], "Rao" => ["Rao"], "lmp" => ["lpm"],
      "aix" => ["aix"], "Nah" => ["Nah"], "BFG" => ["FGB"], "ITV" => ["ITV", "VTI"],
      "CDG" => ["GCD"], "Ekl" => ["Elk"], "Zai" => ["Zia"], "ilq" => ["liq"],
      "bip" => ["bpi"], "MMP" => ["MMP"], "Mbo" => ["Mob"], "eey" => ["eye", "yee"],
      "ekx" => ["kex"], "Siu" => ["Sui"], "add" => ["add", "dad"],
      "MOP" => ["MOP", "MPO", "OPM", "PMO", "POM"], "ppt" => ["ppt", "ptp"],
      "IOU" => ["IOU", "OIU"], "Gaz" => ["Gza"], "Deo" => ["Deo", "Doe"],
      "ccf" => ["cfc"], "LOS" => ["LOS", "SOL"], "pry" => ["pry", "pyr"],
      "MRT" => ["MTR", "RTM", "TMR"], "Edo" => ["Edo"], "isv" => ["vis"],
      "LMR" => ["MLR"], "EMX" => ["MEX"], "ady" => ["ady", "day", "yad"],
      "ANT" => ["ATN"], "Eek" => ["Eek"], "Mio" => ["Mio", "Moi"], "FPR" => ["RFP"],
      "EMP" => ["EMP", "MEP", "MPE", "PEM"], "aru" => ["aru", "ura"],
      "Rix" => ["Rix"], "acp" => ["apc", "cap", "cpa", "pac"], "Akr" => ["Ark"],
      "Map" => ["Map"], "Sdy" => ["Syd"], "ems" => ["ems", "esm", "mes", "sem"],
      "def" => ["def", "fed"], "DEI" => ["DEI", "EDI", "IDE", "IED"],
      "CES" => ["CSE", "ECS", "SCE", "SEC"], "FOP" => ["FPO", "OPF", "POF"],
      "Dai" => ["Dai", "Dia"], "Ran" => ["Ran"], "BCh" => ["BCh", "ChB"],
      "Ebn" => ["Ebn"], "suy" => ["yus"], "CFG" => ["FCG", "FGC", "GCF"],
      "blo" => ["blo", "bol", "lob", "obl"],
      "ary" => ["ary", "ayr", "ray", "rya", "yar"], "JMM" => ["MMJ"],
      "ckw" => ["ckw"], "BMU" => ["UBM"], "EEE" => ["EEE"], "hps" => ["shp"],
      "nuw" => ["wun"], "isu" => ["sui"], "HMP" => ["HMP", "MPH"],
      "OPT" => ["PTO", "TOP", "TPO"], "DLP" => ["DLP", "LDP", "PDL", "PLD"],
      "mow" => ["mow", "wmo"], "ddt" => ["ddt", "dtd"], "Rwy" => ["Rwy"],
      "Pry" => ["Pry"], "alu" => ["aul", "ula"], "Say" => ["Say"], "AAL" => ["ALA"],
      "GOP" => ["GOP", "GPO"], "Bay" => ["Bay"], "opy" => ["poy"], "bet" => ["bet"],
      "ACR" => ["ARC", "CAR", "RAC", "RCA"], "GOX" => ["GOX"],
      "dit" => ["dit", "itd", "tid"], "AMN" => ["MAN", "MNA", "NAM"],
      "AGJ" => ["JAG"], "ads" => ["ads", "das", "sad"],
      "DIR" => ["DIR", "DRI", "IRD", "RID"], "Sik" => ["Sik"], "Ngo" => ["Ngo"],
      "Xer" => ["Xer"], "ego" => ["ego", "geo", "goe"], "KNS" => ["NKS"],
      "clp" => ["cpl"], "Cdy" => ["Cyd"], "GIS" => ["SGI", "SIG"], "cls" => ["lsc"],
      "NOR" => ["NOR", "NRO", "ONR"], "Snu" => ["Sun"], "Meo" => ["Meo", "Moe"],
      "DHS" => ["DHS", "SDH"], "drt" => ["tdr"], "CLO" => ["COL", "LOC"],
      "TXe" => ["TeX"], "Bev" => ["Bev"], "CSU" => ["CSU", "SCU", "USC"],
      "BCJ" => ["JCB"], "eht" => ["eth", "het", "the"], "een" => ["een", "ene"],
      "AAF" => ["AAF", "AFA", "FAA"], "abp" => ["abp", "bap"],
      "esu" => ["esu", "sue", "use"], "eop" => ["ope", "poe"], "DMZ" => ["DMZ"],
      "bfo" => ["fob"], "mrs" => ["mrs", "rms"], "LLW" => ["LWL"], "afk" => ["kaf"],
      "dpp" => ["ppd"], "Kin" => ["Kin"], "CNN" => ["CNN"], "Heu" => ["Hue"],
      "ahy" => ["hay", "yah"], "Key" => ["Key"], "Ahs" => ["Ash"], "Cbu" => ["Cub"],
      "ast" => ["ast", "sat", "sta", "tas"], "Cdr" => ["Cdr"],
      "ceh" => ["che", "ech"], "Ast" => ["Ats"], "BPh" => ["BPh"], "lmy" => ["lym"],
      "isy" => ["yis"], "BOT" => ["BOT", "BTO", "OTB", "TBO"], "QRS" => ["RQS"],
      "kkk" => ["kkk"], "ACF" => ["ACF", "AFC", "CAF", "CFA", "FCA"],
      "Cdi" => ["Cid"], "Men" => ["Men"], "AEV" => ["EVA"],
      "abc" => ["abc", "bac", "cab"], "Ide" => ["Ide"], "bht" => ["thb"],
      "AAI" => ["AIA", "IAA"], "eru" => ["rue", "ure"], "NSV" => ["SVN"],
      "DIY" => ["DIY"], "gno" => ["gon", "nog"], "CMV" => ["VCM", "VMC"],
      "TTY" => ["TTY"], "AEM" => ["AME", "EAM", "EMA", "MAE", "MEA"],
      "OTY" => ["TOY"], "BNO" => ["NBO"], "guy" => ["guy", "yug"],
      "efo" => ["eof", "foe"], "MSW" => ["MSW", "SWM"], "EUV" => ["EUV", "VEU"],
      "giu" => ["gui"], "EJT" => ["JET"], "Lno" => ["Lon"], "GIR" => ["GRI", "IRG"],
      "ADM" => ["ADM", "AMD", "DMA", "MAD"], "hox" => ["hox"], "Ief" => ["Ife"],
      "Toy" => ["Toy"], "Smu" => ["Sum"], "EEN" => ["ENE"], "GNk" => ["NGk"],
      "Orv" => ["Orv"], "anr" => ["arn", "nar", "ran", "rna"], "Opp" => ["Opp"],
      "FSW" => ["FSW", "SWF"], "ceo" => ["ceo", "coe", "eco"], "Wop" => ["Wop"],
      "ipr" => ["ipr", "pir", "rip"], "FNV" => ["VNF"], "Ilr" => ["Irl"],
      "AST" => ["AST", "ATS", "SAT", "TAS"], "ekp" => ["kep"], "Mal" => ["Mal"],
      "Sdi" => ["Sid"], "cos" => ["cos", "soc"], "Pet" => ["Pet", "Pte"],
      "ABC" => ["ABC", "ACB", "CAB"], "adw" => ["awd", "daw", "wad"],
      "iwz" => ["wiz"], "IOP" => ["IOP", "IPO", "PIO"],
      "agr" => ["agr", "arg", "gar", "gra", "rag"], "EOO" => ["OEO"],
      "cho" => ["cho", "hoc", "och"], "Uno" => ["Uno"], "abb" => ["abb", "bab"],
      "cik" => ["ick"], "HLS" => ["LHS"], "Joy" => ["Joy"], "BTW" => ["BTW", "BWT"],
      "Qdl" => ["Qld"], "Fin" => ["Fin"], "HHR" => ["HRH"], "Gij" => ["Gij"],
      "HOs" => ["HOs"], "djs" => ["djs"], "Wac" => ["Wac"], "DMX" => ["MDX"],
      "OOP" => ["OOP"], "fpt" => ["ftp"], "TTU" => ["TTU"],
      "CRT" => ["CRT", "RCT", "RTC", "TCR"], "Dhu" => ["Dhu"],
      "BIS" => ["BIS", "BSI"], "BFF" => ["BFF"], "DRT" => ["DTR", "RDT", "TDR"],
      "Bci" => ["Bic"], "BGH" => ["GBH"], "Xty" => ["Xty"],
      "CIS" => ["CIS", "CSI", "ICS", "ISC", "SCI", "SIC"], "Bax" => ["Bax"],
      "Yap" => ["Yap"], "Mou" => ["Mou"], "cce" => ["ecc"],
      "CLM" => ["CML", "LCM", "LMC", "MLC"], "Nor" => ["Nor"],
      "Sat" => ["Sat", "Sta"], "BFU" => ["BUF"], "Sch" => ["Sch"],
      "dir" => ["dir", "rid"], "AMW" => ["MWA", "WAM"], "FRU" => ["FRU"],
      "Agh" => ["Agh"], "DFT" => ["DFT", "DTF"], "LLP" => ["LLP", "LPL", "PLL"],
      "MPs" => ["PMs"], "dpu" => ["dup", "pud"],
      "BIM" => ["BIM", "BMI", "IBM", "MIB"], "EMT" => ["EMT", "MET"],
      "atu" => ["tau", "tua", "uta"], "FVW" => ["VFW"],
      "efi" => ["fei", "fie", "ife"], "CGU" => ["UGC"], "Loy" => ["Loy"],
      "Dbh" => ["Dbh"], "Ceo" => ["Coe"], "aor" => ["aor", "oar", "ora"],
      "egm" => ["gem", "meg"], "Uek" => ["Uke"], "Utu" => ["Utu"], "CGR" => ["GCR"],
      "ewx" => ["wex"], "anv" => ["avn", "nav", "van"], "EIX" => ["XIE"],
      "CIO" => ["CIO", "COI", "IOC", "OCI"], "ATW" => ["TWA"], "Hax" => ["Hax"],
      "flp" => ["plf"], "dis" => ["dis", "ids"], "Teu" => ["Tue"],
      "EHP" => ["EHP", "HEP"], "CET" => ["CET", "ECT", "ETC", "TEC"],
      "ADQ" => ["QDA"], "amx" => ["max"], "CDL" => ["DCL", "DLC", "LCD", "LDC"],
      "LXy" => ["LyX"], "EFX" => ["XFE"], "owx" => ["wox"],
      "AFR" => ["ARF", "FAR", "RAF", "RFA"], "Uet" => ["Ute"],
      "del" => ["del", "dle", "eld", "led"], "ruw" => ["wur"], "Div" => ["Div"],
      "clo" => ["clo", "col", "loc"], "MPT" => ["MPT", "MTP", "PMT", "TMP", "TPM"],
      "RST" => ["RTS", "TSR"], "Woo" => ["Woo"],
      "AES" => ["AES", "EAS", "ESA", "SAE"], "ANS" => ["ASN", "NAS", "NSA", "SNA"],
      "iqs" => ["iqs", "qis"], "NRT" => ["NTR"], "Ign" => ["Ing"], "LOX" => ["LOX"],
      "MMV" => ["VMM"], "OSU" => ["USO"], "guv" => ["guv", "vug"],
      "ens" => ["ens", "sen"], "NSS" => ["SSN"], "Ain" => ["Ain"], "QST" => ["QST"],
      "COO" => ["COO", "OCO"], "htu" => ["hut"], "GHM" => ["MGH", "MHG"],
      "bes" => ["bes", "ebs", "sbe"], "fvw" => ["vfw"],
      "acl" => ["alc", "cal", "lac", "lca"], "Fox" => ["Fox"],
      "ehp" => ["hep", "peh"], "HHS" => ["HHS", "HSH"], "Elr" => ["Erl"],
      "Eav" => ["Eva"], "gju" => ["gju", "jug"], "biu" => ["ubi"], "jnt" => ["jnt"],
      "PUU" => ["UPU"], "Les" => ["Les"], "BBN" => ["BBN"], "DDN" => ["DDN"],
      "env" => ["env"], "CCH" => ["CCH"], "Mss" => ["Mss"],
      "LPT" => ["LPT", "LTP", "PLT", "TLP"], "EMM" => ["MME"], "Bko" => ["Bok"],
      "agv" => ["avg", "vag"], "Dis" => ["Dis"],
      "AIS" => ["AIS", "ASI", "IAS", "ISA", "SAI"], "INN" => ["INN"],
      "CCL" => ["CCL", "LCC"], "NPR" => ["NPR", "RPN"], "nop" => ["pon"],
      "PTT" => ["PTT", "TPT", "TTP"], "fms" => ["sfm"],
      "BCD" => ["BCD", "BDC", "CBD", "CDB", "DCB"], "BCM" => ["BCM"],
      "Liu" => ["Liu"], "Yeo" => ["Yeo"],
      "aer" => ["aer", "are", "ear", "era", "rea"], "kly" => ["kyl"],
      "Blo" => ["Bol"], "IPY" => ["IPY"], "bjo" => ["job", "obj"],
      "ilt" => ["lit", "til"], "orv" => ["vor"], "Agr" => ["Arg"],
      "ALV" => ["LAV", "VLA"], "ERS" => ["ERS", "ESR", "RSE", "SER"],
      "ABH" => ["BHA", "HBA"], "tuy" => ["tuy"],
      "AGS" => ["AGS", "ASG", "GAS", "GSA", "SAG"], "ffo" => ["off"],
      "aep" => ["ape", "epa", "pea"], "Mee" => ["Mee"], "Ehp" => ["Eph"],
      "Mgr" => ["Mgr"], "blu" => ["bul", "lub"], "aal" => ["aal", "ala", "laa"],
      "Kay" => ["Kay"], "ORR" => ["RRO"], "Ulu" => ["Ulu"], "Mdo" => ["Mod"],
      "Zeo" => ["Zoe"], "dry" => ["dry"], "ino" => ["ion", "oni"], "Lsy" => ["Lys"],
      "CDD" => ["DCD", "DDC"], "Bbo" => ["Bob"], "HTU" => ["HUT"], "SSU" => ["USS"],
      "FFS" => ["FFS", "FSF"], "Act" => ["Act"], "cnu" => ["cun", "unc"],
      "oww" => ["wow"], "Hey" => ["Hey", "Hye"], "EIR" => ["IRE"], "Sbi" => ["Sib"],
      "DNR" => ["DNR"], "ajs" => ["saj"], "fgr" => ["frg", "grf"], "Hay" => ["Hay"],
      "efr" => ["erf", "fer", "ref"], "FKT" => ["KFT"],
      "bmo" => ["bom", "mob", "omb"], "Jes" => ["Jes"], "Iac" => ["Ica"],
      "CGH" => ["HCG"], "efu" => ["feu"], "agu" => ["aug", "gau"], "DTT" => ["TTD"],
      "MSU" => ["SUM", "USM"], "AMT" => ["AMT", "ATM", "MTA", "TAM", "TMA"],
      "agz" => ["gaz", "zag"], "Ooy" => ["Oyo"], "DFG" => ["FGD"], "Bac" => ["Bac"],
      "NSU" => ["NSU", "NUS", "SNU", "SUN", "USN"], "DIQ" => ["QID"],
      "CMS" => ["CMS", "CSM", "MCS", "MSC", "SCM", "SMC"], "det" => ["det", "ted"],
      "Mam" => ["Mam"], "Dae" => ["Dea"], "Paz" => ["Paz"], "DJU" => ["JUD"],
      "egg" => ["egg"], "IRT" => ["RIT"], "ISU" => ["IUS"],
      "MSS" => ["MSS", "SMS", "SSM"], "FOT" => ["FOT", "OTF"], "ITT" => ["ITT"],
      "AMP" => ["AMP", "APM", "MAP", "MPA", "PAM", "PMA"], "Huw" => ["Hwu"],
      "bbi" => ["bib"], "boy" => ["boy", "yob"], "FLO" => ["LOF"], "Amu" => ["Aum"],
      "hio" => ["hoi"], "ilv" => ["lvi", "vil"], "eio" => ["oie"],
      "act" => ["act", "cat"], "AIP" => ["API", "IPA", "PIA"],
      "dot" => ["dot", "tod"], "deq" => ["qed"], "Eab" => ["Eba"], "afl" => ["alf"],
      "dfl" => ["fld"], "STY" => ["YST"], "ahj" => ["haj", "jah"], "Ldt" => ["Ltd"],
      "deo" => ["doe", "edo", "ode"], "bcd" => ["bcd", "dcb"],
      "AAO" => ["AAO", "AOA"], "Lay" => ["Lay"], "bhu" => ["hub"], "CHQ" => ["CHQ"],
      "MPh" => ["MPh", "PhM"], "aco" => ["oca"], "Sax" => ["Sax"],
      "glu" => ["gul", "lug"], "stu" => ["ust", "uts"], "flv" => ["vlf"],
      "Mck" => ["kMc"], "hmz" => ["mhz"], "eno" => ["eon", "neo", "one"],
      "eip" => ["epi", "pie"], "suz" => ["suz"], "lsy" => ["lys", "sly", "syl"],
      "Ken" => ["Ken"], "Fax" => ["Fax"], "CIL" => ["CLI", "ICL", "LCI"],
      "MMO" => ["OMM"], "HST" => ["HST", "TSH"],
      "ACV" => ["ACV", "AVC", "CAV", "CVA", "VAC"], "cst" => ["cst", "cts", "sct"],
      "ijt" => ["tji"], "eev" => ["eve", "vee"], "Kar" => ["Kra"],
      "eps" => ["esp", "pes", "sep"], "Bav" => ["Bav"], "Zep" => ["Zep"],
      "tuu" => ["utu"], "Jem" => ["Jem"], "AIg" => ["IgA"], "LQS" => ["QSL", "SQL"],
      "Dnu" => ["Dun"], "amp" => ["amp", "map", "pam"], "EGO" => ["EGO", "GEO"],
      "BBS" => ["BBS"], "Sht" => ["Sth"], "DFM" => ["DFM", "FDM", "MDF"],
      "Jam" => ["Jam"], "Hst" => ["Hts"], "HKS" => ["KSH"], "AQS" => ["QAS", "SQA"],
      "eow" => ["owe", "woe"], "cfp" => ["fcp", "pcf", "pfc"], "dtt" => ["tdt"],
      "Fee" => ["Fee"], "Dee" => ["Dee"], "Asv" => ["Avs"], "DHN" => ["HND"],
      "DIL" => ["DIL", "DLI", "IDL"], "Els" => ["Els"], "Kho" => ["Kho", "Koh"],
      "AOR" => ["ARO", "RAO", "ROA"], "Bik" => ["Bik"], "INU" => ["NIU", "NUI"],
      "AGW" => ["AWG", "GAW", "WAG"], "suw" => ["usw", "wus"], "Vno" => ["Von"],
      "bey" => ["bey", "bye"], "MMU" => ["MMU"], "IUV" => ["IUV", "VIU"],
      "KTW" => ["KWT"], "abs" => ["abs", "asb", "bas", "sab"], "dgm" => ["mgd"],
      "hmp" => ["mph"], "GMO" => ["MOG"], "Any" => ["Any", "Ayn"],
      "moo" => ["moo", "oom"], "opv" => ["opv"], "adt" => ["dat", "tad"],
      "Fno" => ["Fon"], "exz" => ["zex"], "HIR" => ["HRI"], "BVY" => ["BVY"],
      "AFQ" => ["FAQ"], "Ois" => ["Osi"], "DEG" => ["GED"],
      "PRS" => ["PRS", "PSR", "RPS", "SPR", "SRP"], "Mem" => ["Mme"],
      "qrs" => ["qrs"], "Diu" => ["Diu"], "aai" => ["aia", "iaa"],
      "ABL" => ["BAL", "BLA", "LAB"], "GLT" => ["LTG"], "fpx" => ["pfx"],
      "BDV" => ["BVD"], "OSW" => ["SOW", "SWO"], "gps" => ["gps"], "dhy" => ["hyd"],
      "EEL" => ["EEL"], "INO" => ["ONI"], "avw" => ["vaw"], "Nes" => ["Nes"],
      "Emm" => ["Emm"], "fhw" => ["whf"],
      "EMS" => ["EMS", "ESM", "MSE", "SEM", "SME"], "ovx" => ["vox"],
      "AIs" => ["AIs"], "bkl" => ["blk"], "Eam" => ["Ema"], "bdu" => ["bud", "dub"],
      "Ely" => ["Ely"], "KOR" => ["ROK"], "DDO" => ["DOD", "ODD"], "Rfi" => ["Rif"],
      "Kaz" => ["Kaz"], "ILR" => ["IRL"], "Kly" => ["Kyl"], "GPT" => ["GTP"],
      "ALX" => ["LAX"], "dnu" => ["dun"], "asv" => ["sav", "vas"], "axz" => ["zax"],
      "ANU" => ["ANU", "NAU", "NUA"], "Mag" => ["Mag"], "Iav" => ["Iva"],
      "Dno" => ["Don"], "BCC" => ["BCC", "CBC"], "cop" => ["cop", "cpo"],
      "mqu" => ["qum"], "Qmo" => ["Qom"], "bhl" => ["lhb"], "LTW" => ["LWT"],
      "bls" => ["bls", "lbs"], "Bdu" => ["Bud"], "GIO" => ["OGI"], "CIs" => ["ICs"],
      "Fry" => ["Fry"], "OSS" => ["OSS", "SOS", "SSO"], "Dei" => ["Die"],
      "Suu" => ["Suu"], "CDF" => ["CDF", "CFD", "DFC"], "cdr" => ["cdr", "rcd"],
      "BOQ" => ["BOQ"], "Wis" => ["Wis"], "LLO" => ["LLO"], "fmt" => ["fmt"],
      "KOP" => ["KPO", "POK"], "ail" => ["ail", "lai"], "Bnu" => ["Bun"],
      "Sin" => ["Sin"], "elw" => ["lew"], "Uen" => ["Une"], "mno" => ["mon", "nom"],
      "dgk" => ["dkg"], "ghi" => ["ghi"], "Kes" => ["Kes"], "ILV" => ["ILV"],
      "ekn" => ["ken", "nek"], "CRR" => ["RRC"], "LNP" => ["LPN", "NLP", "NPL"],
      "Uat" => ["Uta"], "Ibo" => ["Ibo"], "psu" => ["pus", "sup", "ups"],
      "cil" => ["cli"], "OPW" => ["POW"], "CCG" => ["GCC"], "Jlu" => ["Jul"],
      "AGV" => ["VGA"], "Jan" => ["Jan"], "dor" => ["dor", "ord", "rod"],
      "msy" => ["mys", "sym"], "ant" => ["ant", "nat", "tan"], "FGV" => ["VGF"],
      "Oak" => ["Oak", "Oka"], "ajr" => ["jar", "raj"], "dfo" => ["fod"],
      "Eco" => ["Eco"], "Ecx" => ["Exc"], "FLM" => ["LMF", "MLF"],
      "APR" => ["APR", "ARP", "PAR", "PRA"], "ikt" => ["kit"], "OSY" => ["YSO"],
      "gjo" => ["jog"], "mrt" => ["trm"], "Tav" => ["Tav"], "Aai" => ["Aia"],
      "Iek" => ["Ike"], "Sam" => ["Sam"],
      "ACM" => ["ACM", "AMC", "CAM", "CMA", "MAC", "MCA"], "adv" => ["adv"],
      "Tit" => ["Tit"], "ntt" => ["tnt"], "Ury" => ["Ury"], "gkp" => ["pkg"],
      "bcf" => ["bcf"], "NNW" => ["NNW", "WNN"], "CER" => ["ECR", "REC"],
      "Thu" => ["Thu"], "adl" => ["ald", "dal", "lad"], "lru" => ["lur"],
      "fwy" => ["fwy"], "IQS" => ["QIS"], "cin" => ["inc"],
      "FMR" => ["FMR", "MFR", "MRF", "RMF"], "BCX" => ["CBX"],
      "RSS" => ["RSS", "SRS", "SSR"], "Nel" => ["Nel"], "Uds" => ["Uds"],
      "CCV" => ["CCV"], "NVY" => ["VNY"], "CMT" => ["CMT", "CTM", "MTC", "TCM"],
      "dmo" => ["dom", "mod"], "CIP" => ["CIP", "CPI", "ICP", "IPC", "PCI", "PIC"],
      "CNY" => ["NYC"], "Abp" => ["Abp"], "Ksu" => ["Kus"], "exy" => ["yex"],
      "Bes" => ["Bes"], "Ell" => ["Ell"],
      "BOS" => ["BOS", "BSO", "OBS", "OSB", "SOB"], "BFS" => ["BFS", "BSF"],
      "DTh" => ["DTh", "ThD"], "DDV" => ["DVD"], "ejo" => ["joe"],
      "bis" => ["bis", "sib"], "CQT" => ["QTC", "TQC"], "DEW" => ["DEW"],
      "hos" => ["hos", "ohs", "sho", "soh"], "gtt" => ["gtt", "tgt"],
      "Dey" => ["Dey"], "als" => ["als", "asl", "las", "sal", "sla"],
      "Elo" => ["Elo"], "ckt" => ["tck"], "OPV" => ["POV", "PVO"], "irz" => ["riz"],
      "iku" => ["kui"], "fiz" => ["fiz"], "Gow" => ["Gow"], "Bbi" => ["Bib"],
      "Aoy" => ["Ayo"], "Gdo" => ["God"], "llw" => ["lwl"], "irv" => ["riv"],
      "Lmo" => ["Lom"], "dex" => ["dex", "xed"], "Tai" => ["Tai", "Tia"],
      "bhr" => ["rhb"], "AAU" => ["AAU", "AUA"], "Gaw" => ["Gaw"],
      "IMO" => ["IMO", "IOM", "MOI"], "BBQ" => ["BBQ"], "ABg" => ["BAg"],
      "emq" => ["meq"], "CPV" => ["PVC"], "ejn" => ["jen"],
      "bor" => ["bor", "bro", "orb", "rob"], "Pos" => ["Pos"],
      "cep" => ["cep", "pec"], "Clp" => ["Cpl"], "avv" => ["vav"], "Evy" => ["Evy"],
      "ghz" => ["ghz"], "bgo" => ["bog", "gob"], "BEO" => ["OBE"], "Ray" => ["Ray"],
      "MVe" => ["MeV"], "BFV" => ["FBV"], "CFU" => ["UFC"], "abi" => ["bai", "iba"],
      "LOT" => ["OTL"], "DIS" => ["DIS", "DSI", "IDS", "SDI", "SID"],
      "CCI" => ["CCI", "CIC", "ICC"], "BLS" => ["BLS", "BSL", "LBS", "LSB"],
      "ctw" => ["cwt"], "apx" => ["apx", "pax"], "AGH" => ["GHA", "HGA"],
      "LMO" => ["MLO", "MOL"], "AFG" => ["FAG", "FGA"], "Uel" => ["Uel", "Ule"],
      "Car" => ["Car"], "ADU" => ["DUA", "UDA"], "puw" => ["wup"], "epp" => ["pep"],
      "EVX" => ["EVX", "VEX"], "GMS" => ["MSG", "SMG"], "Vey" => ["Vey"],
      "inv" => ["inv", "vin"], "Koy" => ["Koy"], "BGN" => ["NBG"], "Mad" => ["Mad"],
      "BPR" => ["PRB"], "ENR" => ["NRE", "REN"], "eem" => ["eme", "mee"],
      "FNO" => ["FON", "ONF"], "Gap" => ["Gap"], "BUY" => ["BYU"],
      "HIN" => ["INH", "NHI", "NIH"], "MNP" => ["MNP"],
      "itu" => ["tiu", "tui", "uit", "uti"], "GOT" => ["GTO", "OGT"],
      "Vet" => ["Vte"], "ehm" => ["hem", "meh"],
      "ABF" => ["AFB", "BFA", "FAB", "FBA"], "Gov" => ["Gov"],
      "ber" => ["ber", "reb"], "ixx" => ["xix", "xxi"],
      "BDF" => ["BDF", "BFD", "DBF"], "Bno" => ["Bon"], "AFP" => ["AFP", "FPA"],
      "ils" => ["isl", "lis", "sil"], "BEI" => ["BIE", "EBI", "EIB"],
      "Kee" => ["Kee"], "GLP" => ["GPL", "LPG"], "Tiv" => ["Tiv"],
      "Ney" => ["Ney", "Nye"], "PPU" => ["PUP"], "Des" => ["Des"], "giv" => ["vig"],
      "ELM" => ["ELM", "EML", "LEM", "LME"], "CTV" => ["CTV", "CVT", "VTC"],
      "Rio" => ["Rio", "Roi"], "RTT" => ["RTT"], "Reu" => ["Rue"], "Rmu" => ["Rum"],
      "DEV" => ["VDE"], "Iow" => ["Iow", "Iwo"], "FSU" => ["FSU", "FUS", "UFS"],
      "CRV" => ["CVR", "VCR", "VRC"], "Sco" => ["Soc"], "Mel" => ["Mel"],
      "Eel" => ["Ele"], "Kao" => ["Koa"], "bcu" => ["cub", "ubc"], "Hkz" => ["kHz"],
      "CLS" => ["CLS", "CSL", "LCS", "LSC", "SLC"], "hir" => ["hir"],
      "CPW" => ["CPW", "WPC"], "Egu" => ["Eug"], "Jah" => ["Jah"], "CFH" => ["HCF"],
      "goy" => ["goy", "ygo"], "Dil" => ["Dli"], "BPS" => ["BPS", "BSP", "PBS"],
      "BCO" => ["BOC", "COB"], "OPS" => ["OPS", "OSP", "POS", "PSO", "SOP"],
      "DLT" => ["DTL", "LTD", "TDL"], "DIP" => ["DIP", "DPI", "IDP", "PDI", "PID"],
      "Far" => ["Far", "Fra"], "BBZ" => ["ZBB"], "Kev" => ["Kev"], "Aet" => ["Ate"],
      "Gde" => ["Gde", "Ged"], "cpr" => ["cpr", "prc"], "Rbo" => ["Rob"],
      "AQR" => ["ARQ", "QRA"], "mpu" => ["ump"], "iss" => ["sis"], "gms" => ["msg"],
      "lux" => ["lux"], "Ler" => ["Ler"], "Iad" => ["Ida"], "muv" => ["vum"],
      "enw" => ["new", "wen"], "aht" => ["hat", "tha"], "Vin" => ["Vin"],
      "Ztz" => ["zZt"], "AMO" => ["MAO", "MOA"], "RSU" => ["RSU", "USR"],
      "KQt" => ["QKt"], "pss" => ["sps", "ssp"], "Ohp" => ["Oph"], "IJM" => ["JIM"],
      "MUX" => ["MUX", "MXU"], "OPR" => ["POR", "PRO", "ROP", "RPO"],
      "Chu" => ["Chu"], "FHS" => ["FSH", "HFS", "SHF"],
      "ist" => ["ist", "its", "sit", "tis", "tsi"], "dno" => ["don", "nod"],
      "IST" => ["IST", "ITS", "SIT", "STI", "TSI"],
      "AFI" => ["AFI", "AIF", "FAI", "IAF"], "alt" => ["alt", "lat", "tal"],
      "RSV" => ["RSV", "SVR", "VRS", "VSR"], "eho" => ["heo", "hoe"],
      "Aab" => ["Aba"], "CJM" => ["MCJ"], "ams" => ["mas", "sam", "sma"],
      "IMR" => ["IRM", "MIR", "MRI", "RIM", "RMI"], "BPX" => ["PBX"],
      "hsy" => ["shy"], "MMS" => ["MMS", "MSM", "SMM"], "anp" => ["nap", "pan"],
      "DIN" => ["DIN", "DNI", "IDN", "IND", "NDI"], "lmw" => ["lwm"],
      "fhu" => ["uhf"], "CGO" => ["GOC"], "DFS" => ["DFS", "SDF", "SFD"],
      "CHN" => ["HNC"], "ahs" => ["ahs", "ash", "has", "sah", "sha"],
      "dfm" => ["mfd"], "HOP" => ["HPO", "OHP", "POH"], "Eck" => ["Eck"],
      "NSY" => ["SYN"], "CFL" => ["CFL", "LCF"], "Ode" => ["Ode"], "Viv" => ["Viv"],
      "cgt" => ["ctg", "gtc"], "Hak" => ["Hak"], "LPh" => ["PhL"], "GNO" => ["NGO"],
      "GIP" => ["GPI", "IGP"], "bsy" => ["bys"], "bdh" => ["bhd"], "kot" => ["tko"],
      "CPs" => ["PCs"], "osw" => ["ows", "sow", "wos"], "Hab" => ["Hab"],
      "Jho" => ["Joh"], "Yim" => ["Yim"], "eeh" => ["hee"],
      "CLP" => ["CPL", "LCP", "LPC", "PCL", "PLC"], "iou" => ["iou", "oui"],
      "Dor" => ["Dor"], "CCC" => ["CCC"], "AGP" => ["APG", "GPA", "PGA"],
      "bov" => ["obv"], "DPh" => ["PhD"],
      "APS" => ["APS", "ASP", "PAS", "PSA", "SAP", "SPA"], "dps" => ["dsp"],
      "BCR" => ["BCR", "BRC", "CBR", "CRB", "RBC", "RCB"], "LNO" => ["LON"],
      "bru" => ["bur", "rub", "urb"], "stt" => ["tst"], "Kdi" => ["Kid"],
      "gmo" => ["mog"], "IOt" => ["OIt"], "mtv" => ["tmv"], "Ijo" => ["Ijo"],
      "cfs" => ["cfs", "fcs", "scf"], "ehs" => ["ehs", "hes", "she"],
      "acr" => ["arc", "car"], "APW" => ["PWA", "WAP", "WPA"], "Zio" => ["Zoi"],
      "Dlo" => ["Dlo", "Dol"], "Zae" => ["Zea"], "CGP" => ["GPC"], "acz" => ["zac"],
      "CLR" => ["CLR", "CRL", "LCR", "LRC", "RCL", "RLC"], "gis" => ["gis", "sig"],
      "Amp" => ["Amp"], "HOR" => ["ROH"], "adh" => ["adh", "dah", "dha", "had"],
      "dmx" => ["mxd"], "Flo" => ["Flo"], "Sou" => ["Sou"], "HNV" => ["NVH"],
      "BGS" => ["GBS"], "EER" => ["ERE"], "etv" => ["vet"], "Dag" => ["Dag"],
      "dky" => ["kyd"], "AHM" => ["HAM", "MHA"], "FRR" => ["FRR"], "EQS" => ["SQE"],
      "SST" => ["SST", "STS", "TSS"], "FLV" => ["VLF"],
      "CIT" => ["CIT", "ICT", "ITC", "TIC"], "AIR" => ["AIR", "IRA"],
      "EIM" => ["EMI", "MIE"], "cis" => ["cis", "csi", "sci", "sic"],
      "EEI" => ["EEI", "IEE"], "CNW" => ["NWC"], "foo" => ["foo", "ofo", "oof"],
      "NRU" => ["NUR"], "BDP" => ["PBD"], "prs" => ["prs", "rps"],
      "Der" => ["Der", "Dre"], "amm" => ["mam"], "gns" => ["gns"], "Mdi" => ["Mid"],
      "dip" => ["dip", "dpi", "idp", "pid"], "MMR" => ["RMM"], "hvy" => ["hvy"],
      "BCV" => ["BVC"], "ako" => ["ako", "koa", "oak", "oka"], "Lit" => ["Lit"],
      "Klo" => ["Kol"], "eim" => ["mei"], "Dam" => ["Dam"], "PRV" => ["RPV"],
      "dru" => ["dur", "rud", "urd"], "ado" => ["ado", "dao", "doa", "oad", "oda"],
      "Jos" => ["Jos"], "ACS" => ["ACS", "ASC", "CAS", "CSA", "SAC", "SCA"],
      "Htu" => ["Hut"], "rst" => ["str", "trs"], "NTT" => ["NTT", "TNT"],
      "EPP" => ["PEP", "PPE"], "BGR" => ["BRG", "GRB", "RGB"], "CFX" => ["XCF"],
      "CCE" => ["CEC", "ECC"], "ktt" => ["tkt"], "BHP" => ["BHP", "BPH"],
      "bef" => ["bef", "feb"], "CMN" => ["CNM", "MCN", "NMC"], "CSY" => ["SYC"],
      "Moy" => ["Myo"], "cko" => ["ock"], "NRS" => ["RSN", "SNR", "SRN"],
      "Ulm" => ["Ulm"], "esy" => ["sey", "sye", "yes"], "hpr" => ["phr"],
      "Knu" => ["Kun"], "dnp" => ["pdn"],
      "pst" => ["pst", "pts", "spt", "tps", "tsp"], "OOS" => ["OSO"],
      "ETV" => ["ETV"], "dsy" => ["dys", "yds"], "Pcf" => ["Pfc"],
      "DEO" => ["DOE", "EDO", "EOD", "OED"], "TWX" => ["TWX"], "ehx" => ["hex"],
      "DUV" => ["DUV", "VDU"], "BGK" => ["KGB"], "Rno" => ["Ron"],
      "KSU" => ["KSU", "SKU"], "AJL" => ["JAL"], "imr" => ["mir", "mri", "rim"],
      "BMS" => ["BMS", "BSM", "MSB", "SMB"], "abw" => ["baw", "wab"],
      "beo" => ["boe", "obe"], "aev" => ["ave", "vae"], "fhv" => ["vhf"],
      "Day" => ["Day"], "fow" => ["fow"], "CMM" => ["MMC"], "adu" => ["aud", "dau"],
      "ekv" => ["kev"], "SVX" => ["VSX"], "Cam" => ["Cam"], "Ger" => ["Ger"],
      "BVe" => ["BeV"], "DDL" => ["DDL"], "cir" => ["cir"], "FOV" => ["FOV", "VFO"],
      "Pal" => ["Pal"], "Ias" => ["Isa"], "kuy" => ["kyu", "yuk"], "Lev" => ["Lev"],
      "Jbe" => ["Jeb"], "ggr" => ["ggr"], "NPP" => ["NPP", "PNP", "PPN"],
      "NNX" => ["NNX"], "Niu" => ["Niu"], "IMr" => ["MIr"], "FPV" => ["VPF"],
      "SWW" => ["WSW"], "BDG" => ["GDB"], "LRS" => ["LRS", "LSR", "RSL", "SLR"],
      "imt" => ["mit", "tim"], "emw" => ["mew", "wem"], "imv" => ["vim"],
      "JSW" => ["JSW", "WSJ"], "aku" => ["aku", "auk"], "Dru" => ["Dru", "Dur"],
      "OSs" => ["SOs"], "Tay" => ["Tay"], "Had" => ["Had"], "moz" => ["moz"],
      "Ntu" => ["Nut"], "Ogg" => ["Ogg"], "Gev" => ["Gev"], "Mac" => ["Mac"],
      "Adv" => ["Adv"], "cip" => ["cpi", "pci", "pic"], "GST" => ["GTS"],
      "Lgu" => ["Lug"], "adf" => ["afd", "fad"], "ADV" => ["AVD", "DAV", "VAD"],
      "aas" => ["aas", "saa"], "BBL" => ["BBL"], "FLN" => ["FLN", "NFL", "NLF"],
      "aby" => ["aby", "bay"], "DPS" => ["DPS", "DSP", "PDS", "SDP", "SPD"],
      "ijz" => ["jiz"], "ADT" => ["ADT", "DAT"], "kmp" => ["pmk"],
      "BSW" => ["BSW", "SWB", "WBS"], "ESd" => ["EdS"], "kms" => ["mks"],
      "DMP" => ["DPM"], "Ehu" => ["Euh"], "Nam" => ["Nam"],
      "aam" => ["aam", "ama", "maa"], "ISY" => ["ISY"], "Hmo" => ["Hom"],
      "aaw" => ["awa"], "abg" => ["bag", "gab"], "NPQ" => ["QNP"], "Roz" => ["Roz"],
      "Fal" => ["Fla"], "agw" => ["gaw", "wag"], "DPQ" => ["PDQ"],
      "bit" => ["bit", "tib"], "CRY" => ["CRY"], "Box" => ["Box"], "dmr" => ["mrd"],
      "PSW" => ["PSW", "WPS", "WSP"], "EQT" => ["QET"], "LTU" => ["LUT"],
      "eqs" => ["esq", "seq"], "Yee" => ["Yee"], "fgp" => ["pfg"], "AFL" => ["AFL"],
      "Ait" => ["Ati"], "hoo" => ["hoo", "oho", "ooh"],
      "aho" => ["aho", "hao", "hoa"], "ayy" => ["yay"], "BVW" => ["BWV"],
      "LMT" => ["LMT", "MLT", "TLM"], "FFI" => ["FFI", "IFF"], "Hdr" => ["Hdr"],
      "AGN" => ["AGN", "ANG", "GAN", "NAG", "NGA"], "cgm" => ["cgm", "mcg"],
      "Zbe" => ["Zeb"], "Tbi" => ["Tbi", "Tib"], "BER" => ["BER", "BRE", "RBE"],
      "cdf" => ["cdf", "cfd"], "AOO" => ["OAO"], "Mrs" => ["Mrs"], "frz" => ["rfz"],
      "DDR" => ["DDR", "DRD"], "FHV" => ["VHF"], "CDJ" => ["JCD"], "AVr" => ["VAr"],
      "chs" => ["chs", "sch"], "Cmo" => ["Com"], "Ajo" => ["Ajo"],
      "noy" => ["noy", "ony", "yon"], "bnu" => ["bun", "nub", "unb"],
      "DOP" => ["DOP", "POD"], "DPU" => ["PDU", "PUD", "UDP"], "Oin" => ["Oni"],
      "hms" => ["msh"], "Knt" => ["Knt"], "Mah" => ["Mah"], "dgl" => ["gld", "ldg"],
      "OQS" => ["QSO"], "AVk" => ["kVA"], "Sly" => ["Sly", "Syl"], "BPQ" => ["QBP"],
      "PPT" => ["PPT", "PTP"], "Lew" => ["Lew", "Lwe"], "Gsu" => ["Gus"],
      "hhu" => ["huh"], "DDD" => ["DDD"], "JNU" => ["NUJ"], "Kah" => ["Kha"],
      "BGG" => ["GBG"], "BBB" => ["BBB"], "cdu" => ["cud", "duc"], "Coy" => ["Coy"],
      "Zao" => ["Zoa"], "EMd" => ["EdM", "MEd"], "JNS" => ["JSN"],
      "LPP" => ["LPP", "PLP"], "CJL" => ["JCL", "LCJ"],
      "apy" => ["pay", "pya", "yap"], "IJT" => ["JIT"], "Dew" => ["Dew"],
      "MSX" => ["XMS"], "Jay" => ["Jay"],
      "abr" => ["abr", "arb", "bar", "bra", "rab"], "iix" => ["xii"],
      "bbe" => ["ebb"], "BMV" => ["BMV", "BVM"], "ikn" => ["ink", "kin"],
      "GSU" => ["GUS", "SUG", "USG"], "AGM" => ["AGM", "MAG"],
      "ACT" => ["ACT", "ATC", "CAT", "CTA", "TAC", "TCA"], "GNS" => ["SNG"],
      "bgk" => ["bkg"], "CEE" => ["ECE", "EEC"], "Hoy" => ["Hoy", "Hyo"],
      "EST" => ["EST", "ETS", "SET", "TES", "TSE"], "tuw" => ["wut"],
      "Idn" => ["Ind"], "Aix" => ["Aix"], "Guy" => ["Guy"], "aow" => ["woa"],
      "CDH" => ["DCH"], "FMS" => ["FMS", "MFS", "MSF"], "AHT" => ["ATH", "HAT"],
      "ett" => ["tet"], "arv" => ["var"], "akm" => ["kam", "mak"], "Sem" => ["Sem"],
      "DGL" => ["DLG"], "Eex" => ["Exe"], "GSS" => ["SSG"], "Lau" => ["Lau"],
      "Lis" => ["Lis"], "HIP" => ["IHP"], "Ils" => ["Isl"], "Plu" => ["Pul"],
      "Bgu" => ["Bug"], "ars" => ["ars", "ras", "sar"], "Fah" => ["Fah"],
      "Nbe" => ["Neb"], "aaa" => ["aaa"], "Len" => ["Len"], "CLV" => ["CLV"],
      "ASW" => ["ASW", "SAW", "SWA"], "git" => ["git", "tig"], "Dal" => ["Dal"],
      "Veo" => ["Voe"], "Hku" => ["Huk"], "CCN" => ["CNC", "NCC"],
      "ain" => ["ain", "ani"], "IPV" => ["IVP", "VIP"], "hnu" => ["hun", "unh"],
      "DMT" => ["DMT", "MDT", "MTD", "TDM"], "Cno" => ["Con"],
      "IOW" => ["IOW", "OIW", "OWI"], "EHS" => ["ESH"], "mtx" => ["mtx"],
      "lvy" => ["vly"], "dlo" => ["dol", "lod", "old"], "KTU" => ["KTU"],
      "bim" => ["bim", "ibm", "mib"], "ISS" => ["ISS", "SIS", "SSI"],
      "all" => ["all"], "Gil" => ["Gil"], "EFQ" => ["QEF"], "BBP" => ["PBB"],
      "eet" => ["tee"], "Afg" => ["Afg"], "coy" => ["coy"], "Kdy" => ["Kyd"],
      "nox" => ["nox"], "EIN" => ["EIN", "IEN", "NEI"], "EJL" => ["JLE"],
      "clx" => ["xcl"], "ORW" => ["ROW"], "ACJ" => ["AJC", "JAC", "JCA"],
      "Apr" => ["Apr", "Arp"], "Rey" => ["Rey", "Rye"], "Hal" => ["Hal"],
      "KNP" => ["KNP"], "IOr" => ["OIr"], "giw" => ["wig"], "dss" => ["sds"],
      "DLQ" => ["DQL"], "DGN" => ["GND"], "erz" => ["rez", "zer"],
      "mot" => ["mot", "tom"], "Cdn" => ["Cdn"], "ALL" => ["LAL"], "biz" => ["biz"],
      "Bat" => ["Bat"], "aez" => ["zea"], "EJM" => ["JEM"], "ehl" => ["hel"],
      "qsu" => ["suq"], "eef" => ["fee"], "gru" => ["gur", "rug"],
      "dpt" => ["dpt", "tpd"], "EEM" => ["EEM"], "asz" => ["saz", "zas"],
      "acc" => ["acc"], "Dex" => ["Dex"], "Iam" => ["Ima"], "GMr" => ["MGr"],
      "HLM" => ["MHL"], "fim" => ["imf"], "Ary" => ["Ary", "Ayr"], "BBC" => ["BBC"],
      "Eal" => ["Eal", "Ela"], "efz" => ["fez"], "afu" => ["auf", "ufa"],
      "Gao" => ["Gao", "Goa"], "Ont" => ["Ont"], "Dbe" => ["Deb"], "Cei" => ["Cie"],
      "Shu" => ["Shu", "Suh"], "MOV" => ["MOV", "MVO", "OMV", "VOM"],
      "Msu" => ["Mus"], "ANW" => ["NWA", "WAN"], "eky" => ["key", "kye"],
      "dds" => ["dds"], "BPT" => ["PBT"], "cmy" => ["myc"], "AGY" => ["YAG"],
      "Hiu" => ["Hui"], "LTT" => ["TTL"], "fix" => ["fix"], "CIX" => ["CXI", "IXC"],
      "gin" => ["gin", "ign", "ing", "nig"], "FSY" => ["FYS"], "BGL" => ["LGB"],
      "HKT" => ["HTK"], "His" => ["Hsi"], "ade" => ["ade", "dae", "dea", "ead"],
      "Vas" => ["Vas"], "Gex" => ["Gex"], "jms" => ["jms"], "GHR" => ["RHG"],
      "Tir" => ["Tri"], "bmp" => ["bpm", "mpb"], "iim" => ["imi"],
      "EFT" => ["EFT", "ETF", "FET", "FTE"], "abu" => ["abu"], "prw" => ["pwr"],
      "qrt" => ["qtr"], "ghq" => ["ghq"], "aci" => ["cai", "cia"], "buy" => ["buy"],
      "Asu" => ["Aus"], "Ldo" => ["Lod"], "DHH" => ["HHD"],
      "ACI" => ["AIC", "CAI", "CIA", "ICA"], "bot" => ["bot", "tob"],
      "DPP" => ["DPP", "PDP", "PPD"], "dls" => ["lsd", "sld"], "ipz" => ["zip"],
      "lny" => ["lyn"], "mpr" => ["rpm"], "Odz" => ["Odz"],
      "bos" => ["bos", "obs", "sob"], "BFR" => ["BFR", "FRB"], "lmt" => ["ltm"],
      "BCH" => ["BHC"], "elo" => ["leo", "loe"], "egs" => ["seg"],
      "FLT" => ["FLT", "FTL", "LTF"], "Jap" => ["Jap"], "LMV" => ["MLV"],
      "Mbm" => ["Mbm"], "DHP" => ["DPH", "HPD"], "BIV" => ["IVB"], "GHZ" => ["GHZ"],
      "ZZZ" => ["ZZZ"], "iks" => ["ksi", "ski"], "Etz" => ["Etz"], "Cox" => ["Cox"],
      "CKQ" => ["KQC"], "bbl" => ["bbl"], "acf" => ["caf", "fac"], "DOV" => ["DOV"],
      "Lny" => ["Lyn"], "Soo" => ["Soo"], "Bdm" => ["dBm"],
      "CFI" => ["CFI", "CIF", "IFC"], "BEF" => ["BEF", "FEB"], "hmu" => ["hum"],
      "AVV" => ["VAV"], "FIM" => ["IMF", "MIF"], "Dax" => ["Dax"],
      "LNU" => ["LUN", "NUL"], "got" => ["got", "tog"], "Mab" => ["Mab"],
      "ach" => ["ach", "cha"], "aeg" => ["age", "gae"], "nww" => ["wnw"],
      "imp" => ["imp", "ipm"], "Oel" => ["Ole"], "DHX" => ["HDX"], "BHO" => ["HBO"],
      "Sab" => ["Sab"], "Sgu" => ["Sug"], "Nox" => ["Nox"], "HNP" => ["HPN"],
      "gos" => ["gos", "sog"], "Val" => ["Val"], "eor" => ["oer", "ore", "roe"],
      "epz" => ["zep"], "CFK" => ["KFC"], "aar" => ["ara"],
      "DMS" => ["DMS", "DSM", "MDS", "MSD", "SDM", "SMD"], "Tde" => ["Ted"],
      "FOU" => ["UFO"], "Plo" => ["Pol"], "DIO" => ["IOD", "ODI"],
      "ees" => ["ese", "see"], "BSV" => ["VSB"], "enz" => ["zen"], "Vip" => ["Vip"],
      "ikp" => ["kip", "pik"], "AEL" => ["LEA"], "Ohm" => ["Ohm"], "lpw" => ["lwp"],
      "Cbo" => ["Cob"], "ADR" => ["ADR", "DAR", "RAD", "RDA"], "fpr" => ["prf"],
      "eft" => ["eft", "fet", "tef"], "Tho" => ["Tho", "Toh"],
      "FIO" => ["FIO", "IFO", "IOF"], "adi" => ["aid", "dia", "ida"],
      "MQT" => ["TQM"], "Can" => ["Can"], "llu" => ["ull"], "ABG" => ["GAB", "GBA"],
      "EIU" => ["IUE"], "his" => ["his", "ihs", "ish", "shi"],
      "CFN" => ["FNC", "NFC"], "eir" => ["eir", "ire", "rei", "rie"],
      "dez" => ["zed"], "AFM" => ["AFM", "FAM", "MAF", "MFA"],
      "AKO" => ["KAO", "OAK"], "ELT" => ["ELT", "TEL"], "Kit" => ["Kit"],
      "ajp" => ["jap"], "dmu" => ["dum", "mud"], "ipy" => ["yip"],
      "FRT" => ["RFT", "RTF"], "DDE" => ["DDE", "EDD"], "Ian" => ["Ian", "Ina"],
      "Ndo" => ["Nod"], "agm" => ["gam", "mag"],
      "CPS" => ["CPS", "CSP", "PCS", "PSC", "SCP", "SPC"], "Peh" => ["Peh"],
      "NWb" => ["NbW", "WbN"], "Hsu" => ["Hsu", "Hus"], "BHL" => ["BHL"],
      "bho" => ["boh", "hob"], "cdp" => ["cpd"], "Fny" => ["Fyn"], "LNS" => ["NLS"],
      "bbo" => ["bob", "obb"], "AEd" => ["AEd"], "Ldu" => ["Lud"], "Cde" => ["Ced"],
      "Iat" => ["Ita"], "BMT" => ["BMT", "MTB"], "BFT" => ["BFT"],
      "fir" => ["fir", "fri", "rif"], "AGO" => ["GAO"], "EEO" => ["EEO", "EOE"],
      "BNR" => ["BRN"], "iln" => ["lin", "nil"], "Ifn" => ["Inf"], "nwy" => ["wyn"],
      "AAE" => ["AAE", "AEA", "EAA"], "Rbe" => ["Reb"], "Int" => ["Int"],
      "Ede" => ["Ede"], "doz" => ["doz", "dzo", "zod"], "BCG" => ["BCG", "GCB"],
      "Ham" => ["Ham"], "UVX" => ["XUV"], "Nil" => ["Nil"], "AMr" => ["ArM"],
      "DFX" => ["FDX"], "JOT" => ["OJT"], "Enr" => ["Ern"], "ijm" => ["jim"],
      "Sao" => ["Sao"], "ost" => ["sot", "tos"], "FGT" => ["FTG"],
      "BMR" => ["BMR", "BRM"], "MPX" => ["PMX"], "Ras" => ["Ras"], "Han" => ["Han"],
      "DDM" => ["DMD"], "ELU" => ["UEL"], "TTW" => ["TWT"], "CLY" => ["YCL"],
      "Edy" => ["Edy"], "CQS" => ["SQC"], "Rau" => ["Rua"], "HIM" => ["HIM", "HMI"],
      "GHz" => ["GHz"], "bfu" => ["fub"], "SUV" => ["SUV", "USV", "UVS"],
      "BLR" => ["BRL", "LRB"], "Jav" => ["Jav"], "Max" => ["Max"], "Rep" => ["Rep"],
      "MRR" => ["RMR"], "FLa" => ["LaF"], "agg" => ["gag"], "Aim" => ["Ami"],
      "irx" => ["rix"], "ABS" => ["ABS", "BAS", "BSA", "SBA"], "iny" => ["yin"],
      "isw" => ["wis"], "mor" => ["mor", "rom"], "GLR" => ["RLG"],
      "ACL" => ["ACL", "ALC", "LAC", "LCA"], "cns" => ["cns"],
      "ARS" => ["ARS", "ASR", "RAS", "RSA", "SAR", "SRA"], "oxy" => ["oxy", "yox"],
      "izz" => ["ziz"], "ftu" => ["fut"], "egj" => ["jeg"], "puy" => ["puy", "yup"],
      "Ugo" => ["Ugo"], "Niv" => ["Niv"], "Eqs" => ["Esq"], "CUV" => ["VCU"],
      "AAR" => ["ARA"], "ael" => ["ale", "ela", "lea"], "DNT" => ["NDT"],
      "Anu" => ["Anu", "Aun"], "emo" => ["emo", "eom", "moe"],
      "EOR" => ["REO", "ROE"], "cem" => ["ecm"], "Alp" => ["Apl"], "GKO" => ["GOK"],
      "DEQ" => ["QED"], "otx" => ["tox"], "dhp" => ["dph", "phd"], "Fru" => ["Fur"],
      "gnt" => ["tgn", "tng"], "ORX" => ["XOR"], "sww" => ["wsw"],
      "MPR" => ["MPR", "MRP", "RPM"], "cdi" => ["cid"], "Gat" => ["Gat", "Gta"],
      "Ott" => ["Ott"], "Vek" => ["keV"], "ory" => ["ory", "yor"], "cix" => ["xci"],
      "NQS" => ["NQS", "QNS"], "opz" => ["poz"], "Udi" => ["Udi"], "jor" => ["jor"],
      "AIV" => ["AVI"], "emm" => ["mem"], "HRS" => ["RHS", "RSH"], "Irv" => ["Irv"],
      "AFH" => ["FHA"], "GMQ" => ["QMG"], "Ruy" => ["Ruy"], "Raf" => ["Raf"],
      "Eru" => ["Eur"], "gny" => ["gyn"], "BFM" => ["FMB", "MFB"], "dlt" => ["ltd"],
      "huy" => ["yuh"], "HTX" => ["THX"], "KRS" => ["KSR"], "ESb" => ["EbS", "SbE"],
      "ijn" => ["jin"], "DKT" => ["KDT"], "pxy" => ["pyx"], "giz" => ["zig"],
      "AII" => ["IIA"], "FST" => ["FTS", "TFS", "TSF"], "dfi" => ["dif", "fid"],
      "Waf" => ["Waf"], "FPU" => ["FPU"], "OST" => ["OST", "OTS", "TOS", "TSO"],
      "Jno" => ["Jno", "Jon"], "ACO" => ["ACO"], "Lat" => ["Lat"],
      "CRS" => ["CRS", "CSR", "RCS", "RSC", "SCR", "SRC"], "ANO" => ["ONA"],
      "Afl" => ["Alf"], "Cdo" => ["Cod"], "fly" => ["fly"], "cjl" => ["jcl"],
      "AAG" => ["AAG"], "Lim" => ["Lim"], "EPX" => ["PEX"], "Pan" => ["Pan"],
      "Yat" => ["Yat"], "KPs" => ["KPs"], "anu" => ["anu", "una"], "goo" => ["goo"],
      "Obi" => ["Obi"], "gor" => ["gor", "gro", "org", "rog"], "BCK" => ["KCB"],
      "GMM" => ["MGM"], "akl" => ["alk", "kal", "lak"],
      "int" => ["int", "nit", "tin"], "GIY" => ["IGY"], "CIW" => ["CWI", "IWC"],
      "Pam" => ["Pam"], "air" => ["air", "ira", "rai", "ria"], "FTX" => ["TFX"],
      "gou" => ["gou"], "Rhu" => ["Rhu"], "elm" => ["elm", "lem", "mel"],
      "Mar" => ["Mar"], "cru" => ["cru", "cur", "ruc"], "JMP" => ["JMP"],
      "Hno" => ["Hon"], "CIR" => ["CRI", "IRC", "RCI", "RIC"], "Boy" => ["Boy"],
      "Tas" => ["Tas"], "Ens" => ["Ens"], "Bil" => ["Bil"], "afw" => ["faw", "waf"],
      "AHS" => ["SHA"], "Kip" => ["Kip"], "fmp" => ["fpm"], "Ems" => ["Ems"],
      "Rik" => ["Rik"], "DPR" => ["DRP", "RDP"], "COR" => ["OCR", "RCO", "ROC"],
      "Pac" => ["Pac"], "Kbe" => ["Keb"], "Amo" => ["Amo"],
      "ios" => ["ios", "iso", "ois", "osi"], "lop" => ["lop", "olp", "pol"],
      "inz" => ["zin"], "Acs" => ["Asc"], "diu" => ["dui", "iud"], "Liv" => ["Liv"],
      "kow" => ["kow", "owk", "wok"], "ggo" => ["gog"], "Cly" => ["Cly"],
      "Nan" => ["Nan"], "bdm" => ["mbd"], "FPT" => ["FTP", "TFP"],
      "etu" => ["tue", "ute"], "HMM" => ["MMH"],
      "CNS" => ["CNS", "CSN", "NCS", "NSC"],
      "ABD" => ["ABD", "ADB", "BDA", "DAB", "DBA"], "Ice" => ["Ice"],
      "Wno" => ["Won"], "DSc" => ["DSc", "ScD"], "HRT" => ["TRH"], "Oir" => ["Ori"],
      "AKN" => ["NAK"], "luv" => ["luv"], "PPV" => ["PVP"], "GKS" => ["GKS"],
      "ptt" => ["ptt"], "BDI" => ["BID", "DBI", "DIB", "IDB"], "Way" => ["Way"],
      "GMT" => ["GMT", "MGT"], "Dov" => ["Dov"], "ILP" => ["ILP", "IPL"],
      "NST" => ["NST", "NTS", "STN"], "dej" => ["jed"], "Icn" => ["Inc"],
      "CDS" => ["CDS", "CSD", "DCS", "DSC"], "aap" => ["apa"], "Uac" => ["Uca"],
      "EJS" => ["JES"], "bns" => ["bns"], "May" => ["May", "Mya"], "blr" => ["brl"],
      "NTU" => ["NUT"], "ATT" => ["ATT", "TAT"], "ACK" => ["ACK", "AKC"],
      "Jeo" => ["Joe"], "Eil" => ["Eli"], "lxx" => ["lxx"], "dfp" => ["pfd"],
      "DII" => ["IDI"], "Ube" => ["Ube"], "Nov" => ["Nov"], "Hio" => ["Hoi"],
      "ann" => ["ann", "nan"], "iot" => ["toi"], "Ukr" => ["Ukr"], "Oan" => ["Ona"],
      "afo" => ["fao", "oaf"], "oop" => ["oop", "poo"], "EOT" => ["EOT", "ETO"],
      "osz" => ["ozs", "zos"], "Hau" => ["Hau", "Hua"],
      "CIN" => ["CNI", "INC", "NIC"], "jsu" => ["jus"], "Kim" => ["Kim"],
      "Keo" => ["Keo"], "DHV" => ["VHD"], "cgs" => ["cgs"], "GRT" => ["RTG"],
      "Mao" => ["Mao"], "NOP" => ["NOP"], "GPS" => ["GPS", "PSG", "SGP"],
      "loq" => ["loq"], "DDK" => ["DDK", "KDD"], "not" => ["not", "ont", "ton"],
      "Sev" => ["Sev"], "ptw" => ["pwt", "twp"], "Zen" => ["Zen"], "ttx" => ["txt"],
      "ABM" => ["ABM", "BAM", "BMA", "MBA"], "Ver" => ["Ver"], "sty" => ["sty"],
      "Fan" => ["Fan"], "MTX" => ["MTX"], "FSZ" => ["FZS"], "equ" => ["que"],
      "dee" => ["dee"], "BGM" => ["BMG", "GBM", "GMB", "MGB"], "Eaw" => ["Ewa"],
      "Pel" => ["Pel"], "any" => ["any", "nay", "yan"], "gij" => ["jig"],
      "Var" => ["Var"], "imw" => ["wim"], "JMT" => ["JTM"], "aux" => ["aux"],
      "csw" => ["csw", "wcs"], "ely" => ["eyl", "ley", "lye"],
      "IPP" => ["PIP", "PPI"], "Rab" => ["Rab"], "AMV" => ["AVM", "MVA"],
      "Efl" => ["Elf"], "Pax" => ["Pax"], "ADE" => ["DAE", "DEA", "EDA"],
      "Six" => ["Six"], "ffi" => ["iff"], "KMS" => ["MKS"], "ejw" => ["jew"],
      "adk" => ["dak"], "Rai" => ["Rai", "Ria"], "ghp" => ["gph"],
      "adz" => ["adz", "zad"], "aop" => ["opa", "poa"], "crv" => ["vcr"],
      "dgp" => ["gdp", "gpd"], "ERV" => ["ERV"], "luz" => ["luz"], "Ill" => ["Ill"],
      "brr" => ["brr"], "CST" => ["CST", "CTS", "SCT", "STC", "TCS"],
      "FGI" => ["GFI", "GIF"], "ANV" => ["VAN"], "luu" => ["ulu"], "Asz" => ["Asz"],
      "Emp" => ["Emp"], "Jit" => ["Jit"], "GHN" => ["NHG"],
      "PSV" => ["PSV", "SVP", "VSP"], "BWd" => ["dBW"], "ssu" => ["ssu", "sus"],
      "QTY" => ["QTY"], "BCE" => ["BCE", "CBE"],
      "ALP" => ["ALP", "LAP", "PAL", "PLA"], "atw" => ["taw", "twa", "wat"],
      "DTs" => ["DTs"], "Mai" => ["Mai", "Mia"], "abj" => ["jab"], "nqu" => ["unq"],
      "ehn" => ["hen"], "hoz" => ["zho"], "LSU" => ["USL"], "Rmo" => ["Rom"],
      "Ptv" => ["Pvt"], "BEP" => ["BEP", "BPE"], "EHN" => ["NEH"], "Hel" => ["Hel"],
      "AEU" => ["AEU", "EAU", "UAE"], "Haw" => ["Haw"], "AIU" => ["AUI", "IAU"],
      "Ahn" => ["Anh"], "Ram" => ["Ram"], "Neo" => ["Neo", "Noe"],
      "abh" => ["bah", "hab"], "ahu" => ["ahu", "auh", "hau"], "cim" => ["mic"],
      "PQR" => ["QRP", "RPQ"], "EFL" => ["EFL", "ELF"],
      "els" => ["els", "les", "sel", "sle"], "opr" => ["por", "pro"],
      "ABr" => ["BAr"], "lpu" => ["plu", "pul"], "Liz" => ["Liz"], "hkp" => ["kph"],
      "Cav" => ["Cav"], "arr" => ["arr"], "Ead" => ["Eda"],
      "BEM" => ["BEM", "BME", "MBE"], "OPP" => ["POP", "PPO"], "fry" => ["fry"],
      "qty" => ["qty"], "Jas" => ["Jas"], "fmm" => ["mmf"], "ekl" => ["elk", "lek"],
      "Wal" => ["Wal"], "Cal" => ["Cal"], "GMi" => ["MiG"],
      "DJS" => ["DJS", "JDS", "JSD", "SJD"], "Zzz" => ["Zzz"], "Iny" => ["Iny"],
      "aks" => ["ask", "kas", "ska"], "ESV" => ["VSE"],
      "CHM" => ["CMH", "HCM", "HMC", "MCH"],
      "apt" => ["apt", "atp", "pat", "pta", "tap"],
      "cor" => ["cor", "cro", "orc", "roc"], "AAH" => ["AHA", "HAA"],
      "egi" => ["gie"], "aex" => ["axe"], "alp" => ["alp", "apl", "lap", "pal"],
      "ADL" => ["DLA"], "bbs" => ["bbs"], "Gbe" => ["Geb"], "Gru" => ["Gur"],
      "Lin" => ["Lin"], "GIM" => ["IGM", "MIG"], "FMU" => ["MUF"], "dhi" => ["hid"],
      "adr" => ["ard", "dar", "rad"], "npu" => ["pun", "unp"], "CIV" => ["VIC"],
      "Dou" => ["Dou"], "art" => ["art", "rat", "tar", "tra"], "SSX" => ["SXS"],
      "DGS" => ["GDS"], "CGL" => ["GCL", "GLC"], "Egn" => ["Eng"],
      "Gad" => ["Gad", "Gda"], "GHV" => ["HGV"], "bfs" => ["bsf", "fsb"],
      "Yan" => ["Yan"], "cps" => ["cps", "csp"], "Las" => ["Las"],
      "cfi" => ["cfi", "cif", "ifc"], "ekr" => ["erk"],
      "asy" => ["ays", "say", "yas"], "dde" => ["ded", "edd"], "AHR" => ["RHA"],
      "DLM" => ["DML", "MLD"], "ceu" => ["cue", "ecu"], "brw" => ["bwr"],
      "MTh" => ["MTh", "ThM"], "MPS" => ["MPS", "MSP", "PMS", "PSM", "SMP"],
      "bks" => ["bks"], "Nee" => ["Nee"], "ghu" => ["hug", "ugh"], "dfu" => ["fud"],
      "bew" => ["web"], "FNU" => ["NFU"], "HIT" => ["THI"],
      "ips" => ["ips", "pis", "psi", "sip"], "Ylu" => ["Yul"], "osx" => ["sox"],
      "KKt" => ["KKt"], "cot" => ["cot", "cto", "oct", "otc", "toc"],
      "MNR" => ["NMR", "NRM"], "eot" => ["toe"], "EGP" => ["EGP"], "aww" => ["waw"],
      "San" => ["San"], "lnu" => ["nul", "unl"], "MUW" => ["UMW"], "Cop" => ["Cop"],
      "bfn" => ["bnf"], "DDP" => ["DDP"], "GOR" => ["GRO", "ROG"], "OSV" => ["VSO"],
      "loo" => ["loo"], "egk" => ["ekg", "keg"], "arz" => ["zar"],
      "EPT" => ["EPT", "PET", "PTE", "TPE"], "LPs" => ["LPs"], "fht" => ["fth"],
      "AIN" => ["ANI", "NIA"], "Uad" => ["Uda"], "Fen" => ["Fen"],
      "DNP" => ["DPN", "NDP", "PDN"], "DST" => ["DST", "STD", "TSD"],
      "BCU" => ["UBC", "UCB"], "NUY" => ["NYU"], "Dow" => ["Dow"], "AEe" => ["AeE"],
      "agl" => ["alg", "gal", "lag"], "CRU" => ["RCU", "RUC", "UCR", "URC"],
      "bmr" => ["bmr"], "Abl" => ["Alb"], "alv" => ["lav", "val"], "Slo" => ["Sol"],
      "CLT" => ["LCT", "LTC", "TLC"], "Vai" => ["Vai", "Via"],
      "CIU" => ["CIU", "ICU", "UCI", "UIC"], "GLU" => ["LUG"], "Ahk" => ["Akh"],
      "Adr" => ["Ard"], "cel" => ["cel"], "DEP" => ["DPE", "EDP", "EPD", "PDE"],
      "BCW" => ["BWC", "CBW", "WBC"], "DOT" => ["DOT", "ODT", "TDO", "TOD"],
      "Ace" => ["Ace"], "BGP" => ["BGP"], "atz" => ["azt", "zat"], "flt" => ["flt"],
      "Yao" => ["Yao"], "ait" => ["ait", "ita", "tai"], "Reo" => ["Reo", "Roe"],
      "ILO" => ["ILO", "LOI"], "AFF" => ["FFA"], "IUX" => ["XUI"],
      "HMS" => ["HMS", "HSM", "MHS", "MSH", "SHM"], "Hbo" => ["Hob"],
      "BHM" => ["HBM"], "oqu" => ["quo"], "gmp" => ["gpm", "mpg"],
      "aab" => ["aba", "baa"], "mss" => ["mss"], "ANY" => ["NYA"], "BKT" => ["KTB"],
      "pty" => ["pty", "typ"], "bkt" => ["bkt"], "efy" => ["fey"],
      "dow" => ["dow", "owd", "wod"], "LMX" => ["XML"],
      "CHP" => ["CHP", "CPH", "PCH", "PHC"], "eln" => ["enl"], "hty" => ["thy"],
      "eos" => ["eos", "oes", "ose", "soe"], "AEg" => ["AgE"], "Rgo" => ["Rog"],
      "dmt" => ["mtd"], "eju" => ["jeu"], "Jeu" => ["Jeu"],
      "ART" => ["ART", "ATR", "RTA", "TAR"], "Gtu" => ["Gut"],
      "ptu" => ["put", "tup"], "rwy" => ["rwy", "wry"], "OTW" => ["TOW", "WTO"],
      "hho" => ["hoh"], "cov" => ["voc"], "lov" => ["vol"], "CEh" => ["ChE"],
      "bst" => ["tbs"], "Fez" => ["Fez"], "dpq" => ["pdq"], "Tmo" => ["Tom"],
      "Iai" => ["Iia"], "egz" => ["gez"], "GMW" => ["GMW"], "emt" => ["met", "tem"],
      "CFT" => ["FCT", "FTC", "TFC"], "OWW" => ["WOW"], "FTZ" => ["FTZ"],
      "AAD" => ["ADA"], "Rgt" => ["Rgt"], "CNT" => ["TNC"],
      "ACC" => ["ACC", "CAC", "CCA"], "DLR" => ["RDL", "RLD"], "aqt" => ["qat"],
      "agh" => ["hag"], "Iyz" => ["Izy"], "AAN" => ["ANA", "NAA"],
      "EPR" => ["ERP", "PRE"], "hpy" => ["hyp"], "Ios" => ["Ios"],
      "BMP" => ["BMP", "PBM"], "ipx" => ["pix"], "Rox" => ["Rox"], "asx" => ["sax"],
      "Arv" => ["Arv"], "dlr" => ["dlr", "rld"], "kor" => ["kor", "rok"],
      "AOS" => ["AOS", "OAS", "OSA", "SAO"], "Alo" => ["Alo"], "Gdl" => ["Gld"],
      "lps" => ["spl"], "MMX" => ["MMX", "XMM"],
      "CDN" => ["CDN", "CND", "DNC", "NCD"],
      "DOS" => ["DOS", "DSO", "ODS", "OSD", "SDO"],
      "adn" => ["and", "dan", "dna", "nad"], "joy" => ["joy"], "BJL" => ["LBJ"],
      "aan" => ["ana", "naa"], "low" => ["low", "owl"], "FJS" => ["JFS"],
      "Rae" => ["Rae", "Rea"], "Sry" => ["Syr"], "AEF" => ["AEF", "FAE", "FEA"],
      "CCS" => ["CCS", "CSC", "SCC"], "Sep" => ["Sep"],
      "BCN" => ["BNC", "NBC", "NCB"], "isx" => ["six", "xis"], "ELX" => ["LXE"],
      "FMQ" => ["QMF"], "fmu" => ["fum"], "Ofo" => ["Ofo"],
      "elt" => ["elt", "let", "tel"], "MPW" => ["MPW"], "Bai" => ["Bai", "Bia"],
      "Pei" => ["Pei"], "LNV" => ["LVN", "VNL"],
      "AMR" => ["ARM", "MAR", "MRA", "RAM", "RMA"], "KPR" => ["KRP"],
      "IOR" => ["IRO", "ROI"], "muu" => ["umu"], "abt" => ["abt", "bat", "tab"],
      "nsy" => ["nys", "sny", "syn"], "CMi" => ["MCi"], "Wei" => ["Wei", "Wie"],
      "Teh" => ["Teh", "The"], "WWW" => ["WWW"], "FNR" => ["NFR"],
      "NPT" => ["NTP", "PTN", "TPN"], "alo" => ["alo", "lao", "loa", "ola"],
      "Saw" => ["Saw"], "STZ" => ["ZST"], "lrt" => ["ltr", "tlr"], "ckp" => ["kpc"],
      "cdl" => ["lcd"], "Cik" => ["kCi"], "Agt" => ["Agt"],
      "ANR" => ["NAR", "NRA", "RAN", "RNA"], "auy" => ["ayu"],
      "fhs" => ["fsh", "shf"], "fin" => ["fin", "inf"], "Ono" => ["Ono"],
      "ASm" => ["SAm"], "TVs" => ["TVs"], "DMU" => ["DMU", "MDU", "MUD"],
      "moy" => ["moy", "yom"], "kst" => ["stk", "tsk"], "hii" => ["ihi"],
      "aew" => ["awe", "wae"], "ipp" => ["pip", "ppi"],
      "BFO" => ["BOF", "FBO", "FOB"], "Bst" => ["Bts"], "fgm" => ["mfg"],
      "Wae" => ["Wea"], "Del" => ["Del", "Dle"], "Udr" => ["Urd"], "xxx" => ["xxx"],
      "BLV" => ["BLV"], "FMN" => ["FMN"], "Hew" => ["Hew"], "hwy" => ["hwy", "why"],
      "mou" => ["mou"], "Nae" => ["Nea"], "Aks" => ["Ask"], "DDI" => ["DDI", "DID"],
      "Oac" => ["Oca"], "efh" => ["ehf", "feh"], "ddi" => ["did"], "DTX" => ["DXT"],
      "cee" => ["cee", "eec"], "ENS" => ["ENS", "ESN", "NES", "NSE", "SEN"],
      "ahr" => ["rah", "rha"], "DFP" => ["FDP", "PDF"], "gsu" => ["gus", "ugs"],
      "kpt" => ["pkt", "tpk"], "opt" => ["opt", "pot", "top"],
      "BMW" => ["BMW", "BWM"], "itw" => ["twi", "wit"], "AOV" => ["VOA"],
      "hit" => ["hit"], "bdi" => ["bid", "dib"], "AFX" => ["FAX"], "Rex" => ["Rex"],
      "IKP" => ["KIP"], "LLT" => ["LTL"], "agn" => ["gan", "nag"],
      "ALO" => ["AOL", "LAO", "LOA"], "BST" => ["BST", "BTS", "STB", "TBS"],
      "Kru" => ["Kru", "Kur"], "ADP" => ["ADP", "DAP", "DPA", "PAD"],
      "MOW" => ["WMO"], "Bee" => ["Bee"], "Gal" => ["Gal"], "bpx" => ["pbx"],
      "ins" => ["ins", "isn", "nis", "sin"], "Uam" => ["Uma"], "fho" => ["foh"],
      "cpp" => ["pcp"], "doo" => ["doo"], "efw" => ["few", "wef"],
      "ADG" => ["AGD", "DGA"], "Ctu" => ["Cut"], "irs" => ["irs", "sir", "sri"],
      "AFN" => ["AFN", "ANF"], "FMT" => ["MFT", "MTF"], "akz" => ["zak"],
      "Nho" => ["Noh"], "Btu" => ["Btu"], "bpu" => ["pub"], "BIL" => ["BLI"],
      "aeh" => ["hae"], "Art" => ["Art"], "Ebr" => ["Erb"], "Nxy" => ["Nyx"],
      "BNP" => ["NBP", "PNB"], "ADF" => ["ADF", "DFA", "FAD", "FDA"],
      "agy" => ["agy", "gay", "yag"], "EGN" => ["ENG", "NEG"],
      "OTV" => ["OTV", "VTO"], "LRU" => ["LRU", "URL"],
      "DSU" => ["DSU", "SDU", "USD"], "fsu" => ["suf", "ufs"], "Nep" => ["Nep"],
      "jot" => ["jot"], "NOT" => ["NOT", "NTO"], "BTh" => ["BTh", "ThB"],
      "ESX" => ["SEX"], "afg" => ["fag"], "Edd" => ["Edd"], "gov" => ["gov", "vog"],
      "GHQ" => ["GHQ"], "ADs" => ["DAs"], "OOT" => ["OOT"], "att" => ["att", "tat"],
      "rtu" => ["rut", "tur"], "ANP" => ["NPA", "PAN", "PNA"], "IPW" => ["WIP"],
      "Mst" => ["Mts"], "Lae" => ["Lae", "Lea"], "EMV" => ["VME"],
      "ABU" => ["BAU", "UAB", "UBA"], "bpp" => ["ppb"], "Sgi" => ["Sig"],
      "CEG" => ["CGE", "ECG", "GCE"], "otu" => ["out", "tou"], "Hdu" => ["Hud"],
      "awx" => ["wax"], "STV" => ["STV", "VTS"], "egl" => ["gel", "leg"],
      "DMW" => ["WDM", "WMD"], "NXX" => ["NXX"], "Lam" => ["Lam"],
      "PST" => ["PST", "STP", "TPS", "TSP"], "Bly" => ["Bly"],
      "Wey" => ["Wey", "Wye"], "fis" => ["ifs", "sif"], "dks" => ["dks"],
      "aeq" => ["aeq"], "New" => ["New"], "CGN" => ["CGN", "NGC"], "ATU" => ["TAU"],
      "Nmu" => ["Num"], "IIL" => ["IIL"], "MRU" => ["MRU", "RUM"], "Obe" => ["Obe"],
      "BIX" => ["BIX"], "FKS" => ["FSK", "KSF"], "Dak" => ["Dak"], "Sai" => ["Sia"],
      "clr" => ["clr", "crl"], "DIW" => ["DWI"], "acw" => ["caw", "wac"],
      "Kas" => ["Kas"], "DEF" => ["DFE", "EDF", "EFD", "FED"],
      "LMW" => ["LWM", "MLW", "WLM"], "CEI" => ["CEI", "CIE", "ICE", "IEC"],
      "PTW" => ["PTW"], "Rko" => ["Rok"], "BEV" => ["BVE"], "oox" => ["oxo"],
      "DFL" => ["LDF"], "asw" => ["aws", "saw", "swa", "was"], "Rem" => ["Rem"],
      "acd" => ["adc", "cad", "dca"], "fou" => ["fou", "ouf", "ufo"],
      "CEP" => ["CPE"], "fgu" => ["fug"], "aah" => ["aah", "aha"], "Dmo" => ["Dom"],
      "hry" => ["rhy"], "inx" => ["nix"], "lmu" => ["lum"], "FHU" => ["UHF"],
      "oor" => ["oor", "roo"], "Sru" => ["Sur"], "Cbe" => ["Ceb"], "NSX" => ["XNS"],
      "BET" => ["BTE", "TEB"], "Mde" => ["Med"], "dew" => ["dew", "wed"],
      "eer" => ["eer", "ere", "ree"], "Jez" => ["Jez"], "mmy" => ["mym"],
      "AAJ" => ["AJA"], "nnu" => ["nun", "unn"], "dny" => ["dyn"], "Spu" => ["Sup"],
      "ioy" => ["iyo", "yoi"], "mos" => ["mos", "oms", "som"], "Gor" => ["Gor"],
      "CDM" => ["CMD", "DCM", "MDC"], "BEE" => ["BEE"],
      "FNS" => ["NFS", "NSF", "SNF"], "CCR" => ["CCR", "CRC", "RCC"],
      "BTU" => ["BTU", "BUT"], "ADN" => ["ADN", "AND", "DNA", "NAD", "NDA"],
      "egr" => ["erg", "ger", "gre", "reg"], "Ivy" => ["Ivy"], "Sil" => ["Sil"],
      "STT" => ["TST", "TTS"], "HOS" => ["SOH"], "Gmu" => ["Gum"], "rux" => ["rux"],
      "Min" => ["Min"], "FJM" => ["MFJ"], "dil" => ["dil", "lid"],
      "ORS" => ["SOR", "SRO"], "ALW" => ["AWL", "WAL"], "mpt" => ["pmt", "tpm"],
      "hmt" => ["thm", "tmh"], "gho" => ["hog"], "BFP" => ["PFB"],
      "irt" => ["rit", "rti", "tri"], "afy" => ["fay"], "DHU" => ["HUD"],
      "CEN" => ["CEN", "ECN", "NCE", "NEC"], "Loz" => ["Loz"], "cft" => ["ctf"],
      "DFR" => ["FDR", "FRD", "RDF", "RFD"], "COW" => ["CWO"], "gst" => ["stg"],
      "FVY" => ["VFY"], "IPZ" => ["ZIP"], "Din" => ["Din"], "ouy" => ["you"],
      "din" => ["din", "ind", "nid"], "Zin" => ["Zin"],
      "GMP" => ["GMP", "GPM", "MPG", "PMG"], "lpy" => ["ply"], "BEK" => ["KBE"],
      "Bel" => ["Bel"], "Imo" => ["Imo"], "GLM" => ["LGM", "MLG"],
      "DRS" => ["DRS", "DSR", "RDS", "SDR", "SRD"], "IPX" => ["IPX"],
      "efm" => ["emf", "fem"], "EII" => ["IIE"], "hiu" => ["hui"], "gil" => ["lig"],
      "Aar" => ["Aar", "Ara"], "CFP" => ["CFP", "FPC", "PCF", "PFC"],
      "MNU" => ["NMU", "NUM"], "Foy" => ["Foy"], "how" => ["how", "who"],
      "Tdo" => ["Tod"], "ery" => ["eyr", "rye", "yer"], "Caz" => ["Caz"],
      "Rei" => ["Rie"], "CKS" => ["KSC"], "Tao" => ["Tao"], "elz" => ["lez", "zel"],
      "dek" => ["ked"], "ght" => ["hgt"], "ISW" => ["IWS", "WIS", "WSI"],
      "Aat" => ["Ata"], "Mil" => ["Mil", "Mli"],
      "ALM" => ["ALM", "LAM", "MAL", "MLA"], "ags" => ["ags", "asg", "gas", "sag"],
      "Neu" => ["Neu"], "LLM" => ["LLM", "MLL"], "nnw" => ["nnw"], "AAT" => ["ATA"],
      "hmo" => ["hmo", "hom", "mho", "ohm"], "Pmo" => ["Pom"],
      "ikr" => ["irk", "kir"], "inr" => ["rin"], "IMM" => ["IMM", "MIM"],
      "BDS" => ["BDS", "BSD", "DBS", "SDB"], "ESS" => ["ESS", "SES", "SSE"],
      "ISV" => ["ISV"], "Jaf" => ["Jaf"], "Tbo" => ["Tob"], "AHI" => ["AIH", "IAH"],
      "CCM" => ["CMC", "MCC"], "AGR" => ["AGR", "GAR"],
      "eis" => ["ise", "sei", "sie"], "btv" => ["bvt"], "ABO" => ["BAO"],
      "Odo" => ["Odo"], "akt" => ["kat", "tak"],
      "DMV" => ["DMV", "DVM", "MVD", "VDM", "VMD"], "fps" => ["fps", "psf"],
      "Bem" => ["Bme"], "Wes" => ["Wes"], "Aos" => ["Aso"],
      "egt" => ["get", "gte", "teg"], "djn" => ["jnd"], "Ops" => ["Ops"],
      "acg" => ["cag"], "IPU" => ["UIP", "UPI"], "dhh" => ["hhd"], "coz" => ["coz"],
      "amr" => ["arm", "mar", "ram"], "isz" => ["isz"], "Eos" => ["Eos"],
      "CIQ" => ["QIC"], "DOs" => ["ODs"], "lms" => ["mls", "msl", "sml"],
      "ETU" => ["UTE"], "DEN" => ["END", "NDE", "NED"], "inp" => ["nip", "pin"],
      "Wit" => ["Wit"], "FGR" => ["FRG"], "ADD" => ["ADD", "DAD", "DDA"],
      "CJS" => ["JCS", "JSC", "SJC"], "deg" => ["deg", "ged"], "CHT" => ["THC"],
      "dgo" => ["dog", "god"], "xyz" => ["xyz"], "osv" => ["sov"], "Vdo" => ["Vod"],
      "bek" => ["keb"], "BOP" => ["POB"], "nos" => ["nos", "ons", "son"],
      "LPR" => ["LPR", "PLR"], "GSZ" => ["ZGS"],
      "ers" => ["ers", "esr", "res", "ser"], "RTV" => ["VTR"], "ANm" => ["mAN"],
      "LST" => ["LST", "LTS", "STL"], "adp" => ["adp", "dap", "pad"],
      "Kai" => ["Kai"], "DPs" => ["DPs"], "AER" => ["ARE", "ERA", "REA"],
      "jow" => ["jow"], "Dly" => ["Dyl"], "cjt" => ["jct"], "koy" => ["yok"],
      "CGT" => ["GCT", "GTC", "TCG", "TGC"], "elv" => ["lev", "vel"],
      "ilm" => ["lim", "mil"], "grs" => ["grs"], "CFo" => ["FoC"],
      "afq" => ["faq", "qaf"], "Rci" => ["Ric"], "AKS" => ["ASK"],
      "CCW" => ["CCW", "CWC", "WCC"], "Wgi" => ["Wig"], "Eat" => ["Eta"],
      "dlu" => ["lud"], "ess" => ["ess", "sse"], "Sce" => ["Sec"],
      "der" => ["der", "erd", "red"], "CNO" => ["CNO", "NCO", "NOC", "ONC"],
      "Iev" => ["Ive"], "fip" => ["fip"], "Fai" => ["Fai", "Fia"], "chn" => ["chn"],
      "Ggo" => ["Gog"], "Abm" => ["Amb"], "Bor" => ["Bor", "Bro"], "GGP" => ["GGP"],
      "ehw" => ["hew"], "GJR" => ["JGR"], "ELP" => ["ELP", "EPL"], "cdm" => ["cmd"],
      "EFM" => ["EMF", "FEM"], "ccs" => ["csc"], "amw" => ["awm", "maw"],
      "IIN" => ["IIN"], "Amy" => ["Amy", "Aym"], "bee" => ["bee"], "Raj" => ["Raj"],
      "enr" => ["ern", "ren"], "oot" => ["oot", "oto", "too"], "Cot" => ["Cot"],
      "bds" => ["bds"], "HNS" => ["HNS", "NHS"], "Iot" => ["Ito"], "Seu" => ["Sue"],
      "Gar" => ["Gar"], "Afr" => ["Afr"], "CHS" => ["HSC"], "fit" => ["fit"],
      "aik" => ["aik", "kai"], "FSV" => ["VFS"], "Olm" => ["Olm"],
      "ans" => ["ans", "nas", "san"], "dio" => ["ido"], "HPV" => ["HPV"],
      "apw" => ["paw", "wap"], "Eks" => ["Esk"], "Odr" => ["Ord"], "tvw" => ["wtv"],
      "Ypu" => ["Yup"], "dju" => ["jud"], "lst" => ["lst", "slt"], "gir" => ["rig"],
      "Yoo" => ["Yoo"], "cde" => ["dec"], "gip" => ["gip", "pig"], "IIS" => ["ISI"],
      "Jdu" => ["Jud"], "acv" => ["cav", "cva", "vac"], "ntu" => ["nut", "tun"],
      "PTU" => ["UTP"], "abn" => ["abn", "ban", "nab"], "Kam" => ["Kam"],
      "aiw" => ["iwa"], "dhl" => ["hdl", "hld", "lhd"],
      "ort" => ["ort", "rot", "tor"], "BCF" => ["CFB"], "DHI" => ["IHD"],
      "CSW" => ["WCS"], "Nis" => ["Nis"], "Jen" => ["Jen"], "GLO" => ["OLG"],
      "des" => ["des", "eds", "esd", "sed"], "NNP" => ["NNP", "NPN"],
      "BDW" => ["DWB"], "LSV" => ["LSV"], "Ean" => ["Ena"],
      "COP" => ["COP", "CPO", "OPC", "PCO", "POC"], "ITW" => ["WIT"],
      "Aht" => ["Aht"], "JMX" => ["JMX"], "ddu" => ["dud"], "Ban" => ["Ban"],
      "DRU" => ["UDR"], "cdo" => ["cod", "doc"], "Edi" => ["Edi"],
      "bce" => ["bec", "ecb"], "Eew" => ["Ewe"], "ahn" => ["han", "nah"],
      "ahh" => ["ahh", "hah"], "ahv" => ["hav"], "Aal" => ["Ala"], "Mev" => ["Mev"],
      "CFF" => ["CFF", "FFC"], "ARU" => ["ARU", "UAR"], "dux" => ["dux"],
      "rtw" => ["rtw"], "amn" => ["man", "mna", "nam"], "ajt" => ["jat", "taj"],
      "cry" => ["cry"], "Ade" => ["Ade"], "Whk" => ["kWh"], "bfl" => ["flb", "lbf"],
      "Cmy" => ["Cym"], "GTT" => ["GTT"], "gmu" => ["gum", "mug"],
      "CDI" => ["CDI", "CID", "DCI", "DIC", "ICD", "IDC"], "Sac" => ["Sac"],
      "DKM" => ["DMK"], "Cny" => ["Cyn"], "BLT" => ["BLT", "BTL", "TLB"],
      "bhs" => ["bsh"], "BOO" => ["OBO", "OOB"], "Zde" => ["Zed"], "BRW" => ["BWR"],
      "Mer" => ["Mer"], "Maj" => ["Maj"], "CPU" => ["CPU", "PUC", "UPC"],
      "hhs" => ["shh"], "Inn" => ["Inn"], "IWW" => ["IWW", "WWI"], "NPY" => ["NYP"],
      "ABE" => ["BAE", "BEA"], "HOV" => ["HOV"], "CSV" => ["CVS", "SVC", "VCS"],
      "Jnp" => ["Jpn"], "Oct" => ["Oct"], "iow" => ["iwo"], "HIV" => ["HIV"],
      "Cas" => ["Cas"], "GNT" => ["TGN"], "CSS" => ["CSS", "SCS", "SSC"],
      "pps" => ["pps", "spp"], "ehh" => ["heh"], "ERU" => ["ERU"], "Bim" => ["Bim"],
      "hrw" => ["whr"], "Ual" => ["Ula"], "CGS" => ["CGS", "GCS", "GSC"],
      "ppr" => ["ppr", "prp"], "Gay" => ["Gay"], "erv" => ["rev", "ver"],
      "aip" => ["pia"], "DSS" => ["DSS", "SDS", "SSD"], "Lou" => ["Lou", "Luo"],
      "eew" => ["ewe", "wee"], "ghm" => ["mhg"],
      "IPT" => ["IPT", "PIT", "PTI", "TIP", "TPI"], "Ssu" => ["Sus"],
      "Rsx" => ["Rxs"], "Rev" => ["Rev"], "ABP" => ["APB", "BPA"],
      "cow" => ["cow", "cwo"], "Vlu" => ["Vul"], "kps" => ["pks"],
      "MRS" => ["MRS", "MSR", "RMS", "RSM", "SMR", "SRM"], "Bal" => ["Bal"],
      "ciy" => ["icy"], "CTT" => ["CTT", "TCT", "TTC"], "ttu" => ["tut"],
      "Rde" => ["Red"], "GPP" => ["PGP"], "KOs" => ["KOs", "OKs"], "Aad" => ["Ada"],
      "Fay" => ["Fay"], "ert" => ["ert", "ret", "rte", "ter"], "bij" => ["jib"],
      "arw" => ["raw", "war"], "SVW" => ["VWS", "WVS"], "Him" => ["Him"],
      "Phi" => ["Phi"], "AFW" => ["FWA", "WAF"], "npr" => ["prn"], "AIK" => ["KIA"],
      "BIU" => ["BIU"], "ivx" => ["xiv", "xvi"], "Nht" => ["Nth"],
      "ILS" => ["ILS", "LSI"], "ACD" => ["ACD", "ADC", "CAD", "CDA", "DAC", "DCA"],
      "MOS" => ["MOS", "MSO", "OMS", "SMO"], "HMR" => ["MHR"],
      "BLO" => ["LBO", "LOB"], "div" => ["div", "vid"], "Iov" => ["Ivo"],
      "Dcu" => ["Duc"], "Byz" => ["Byz"], "Ziu" => ["Zui"], "Dir" => ["Dir"],
      "SSS" => ["SSS"], "Van" => ["Van"], "hpt" => ["pht", "tph"], "ABB" => ["BBA"],
      "ksu" => ["suk"], "ORV" => ["VOR"], "clm" => ["cml", "lcm"],
      "Low" => ["Low", "Lwo"], "BTo" => ["BoT"], "HPS" => ["HSP", "PHS"],
      "Ynu" => ["Yun"], "ABI" => ["ABI", "BIA", "IAB", "IBA"], "aag" => ["aga"],
      "Kiu" => ["Kui"], "NPW" => ["WNP"], "mnu" => ["mun", "num"], "Vat" => ["Vat"],
      "cmo" => ["com", "moc"], "LPV" => ["LPV"], "mop" => ["mop", "pom"],
      "CSX" => ["SCX"], "ejr" => ["jer"], "alm" => ["lam", "mal"], "DOW" => ["DOW"],
      "Kou" => ["Kuo"], "jnu" => ["jun"], "dkm" => ["dkm"], "dgt" => ["gtd"],
      "esx" => ["sex"], "BRT" => ["BRT", "RBT"], "rtt" => ["trt"], "FGS" => ["FGS"],
      "eep" => ["pee"], "Kir" => ["Kir"], "Jim" => ["Jim"], "DDF" => ["DFD"],
      "Mae" => ["Mae"], "egp" => ["peg"], "BDO" => ["BOD", "DBO", "DOB", "OBD"],
      "FQR" => ["RFQ"], "Luz" => ["Luz"], "Cos" => ["Cos"], "cfy" => ["fcy"],
      "HNR" => ["NHR"], "box" => ["box"], "DNS" => ["DNS", "DSN", "SDN"],
      "Adm" => ["Adm"], "Bap" => ["Bap"], "bhp" => ["bhp"], "AHO" => ["HAO"],
      "ltu" => ["lut", "ult"], "bdl" => ["bdl", "bld", "dbl"],
      "aov" => ["avo", "ova"], "Dce" => ["Dec"], "Kau" => ["Kua"], "hov" => ["ohv"],
      "gnp" => ["gnp"], "Ddu" => ["Dud"], "erw" => ["rew", "wer"],
      "cmp" => ["cpm", "pcm"], "Xes" => ["Xes"], "SWb" => ["SbW", "WbS"],
      "Leo" => ["Leo"], "agp" => ["gap"], "BHS" => ["HSB"], "Lee" => ["Lee"],
      "amu" => ["amu", "aum", "mau", "uma"],
      "MST" => ["MST", "MTS", "SMT", "STM", "TMS", "TSM"], "Tal" => ["Tal"],
      "Wbe" => ["Web"], "FLP" => ["LPF"], "ADO" => ["DOA", "ODA"], "EJR" => ["RJE"],
      "ack" => ["ack"], "IVs" => ["IVs"], "cdg" => ["cdg", "gcd"], "Odd" => ["Odd"],
      "EES" => ["ESE"], "mtu" => ["mut", "tum"], "COU" => ["OCU"], "ptv" => ["pvt"],
      "COY" => ["CYO"], "cpu" => ["cpu", "cup"], "DIX" => ["DIX", "XID"],
      "RSY" => ["SYR", "YRS"], "ceg" => ["ecg"],
      "DLS" => ["DLS", "LDS", "LSD", "SDL"], "Jat" => ["Jat"], "Bow" => ["Bow"],
      "AAB" => ["ABA", "BAA"], "arx" => ["arx", "rax"], "osu" => ["ous", "sou"],
      "Ann" => ["Ann"], "RRS" => ["RSR"], "Ker" => ["Ker"], "CKL" => ["KCL"],
      "Ber" => ["Ber", "Bre"], "dho" => ["doh", "hod"],
      "ASS" => ["ASS", "SAS", "SSA"], "opx" => ["pox"], "LQW" => ["QWL"],
      "CMh" => ["ChM", "MCh"], "vxx" => ["xxv"], "GTV" => ["TGV"], "ahl" => ["lah"],
      "etx" => ["ext", "tex"], "grr" => ["grr"], "DIT" => ["DTI", "TDI", "TID"],
      "Hoo" => ["Hoo"], "dem" => ["dem", "med"], "bmu" => ["bum"], "Gae" => ["Gae"],
      "amo" => ["mao", "moa", "oam"], "ALU" => ["ALU"],
      "AMS" => ["AMS", "ASM", "MAS", "MSA", "SAM", "SMA"], "BNU" => ["BNU"],
      "ssv" => ["vss"], "ago" => ["ago", "goa"], "dfr" => ["fdr"], "Mdm" => ["Mdm"],
      "adm" => ["adm", "dam", "mad"], "AGL" => ["AGL", "LGA"], "Flu" => ["Ful"],
      "GVe" => ["GeV"], "acn" => ["anc", "can"], "Gab" => ["Gab"],
      "msu" => ["mus", "sum", "ums"], "Chr" => ["Chr"], "Aor" => ["Aor", "Aro"],
      "bsx" => ["bxs"], "ces" => ["esc", "sec"], "OPX" => ["OPX"], "aav" => ["ava"],
      "Zgu" => ["Zug"], "FIS" => ["IFS", "ISF"], "Lao" => ["Lao", "Loa"],
      "dey" => ["dey", "dye", "yed"], "noo" => ["noo", "ono", "oon"],
      "cpv" => ["pvc"], "CGX" => ["CGX"], "EFH" => ["EHF", "HFE"],
      "IMX" => ["IXM", "XIM", "XMI"], "Lar" => ["Lar"], "LLR" => ["RLL"],
      "ccy" => ["cyc"], "ACH" => ["ACH", "CHA", "HAC"], "Doy" => ["Doy"],
      "FOr" => ["OFr"], "dlp" => ["pdl"], "KOT" => ["TKO"], "afs" => ["fas"],
      "gio" => ["gio", "goi"], "FIR" => ["FIR", "IFR", "RFI", "RIF"],
      "ais" => ["ais", "sai"], "CDU" => ["CDU", "UCD", "UDC"], "eko" => ["oke"],
      "AAP" => ["AAP", "APA"], "MRW" => ["RWM"], "Eht" => ["Eth"],
      "hno" => ["hon", "noh"], "dgi" => ["dig", "gid"], "Obs" => ["Obs"],
      "hiv" => ["hiv"], "akw" => ["awk", "kaw", "kwa"], "abv" => ["abv"],
      "Nos" => ["Nos"], "cds" => ["scd"], "ccr" => ["crc"],
      "AFS" => ["AFS", "FAS", "FSA"], "esw" => ["sew"], "dgs" => ["gds", "sgd"],
      "epr" => ["per", "pre", "rep"], "EGp" => ["GpE"],
      "COS" => ["COS", "CSO", "OCS", "OSC", "SCO", "SOC"], "lox" => ["lox"],
      "gow" => ["wog"], "Meg" => ["Meg"], "GPR" => ["PRG", "RGP", "RPG"],
      "awy" => ["way", "yaw"], "chl" => ["hcl"], "Abs" => ["Abs"],
      "btu" => ["btu", "but", "tub"], "ABT" => ["ATB", "TAB", "TBA"],
      "ELV" => ["ELV"], "CFM" => ["CMF", "FMC"], "BOR" => ["BOR", "ORB", "ROB"],
      "Aeg" => ["Age"], "HMz" => ["MHz"], "Jru" => ["Jur"],
      "hpu" => ["hup", "phu", "puh"], "lry" => ["rly"], "lpp" => ["ppl"],
      "bno" => ["bon", "nob"], "ATV" => ["ATV", "TVA", "VAT"],
      "dhu" => ["dhu", "duh", "hud"], "Tiu" => ["Tiu"], "CHI" => ["CHI", "HIC"],
      "EMZ" => ["MEZ"], "Kaf" => ["Kaf"], "Jew" => ["Jew"], "oqt" => ["qto"],
      "AWY" => ["WAY"], "HIS" => ["HIS", "HSI", "IHS", "ISH"], "oyy" => ["yoy"],
      "Wan" => ["Wan"], "asu" => ["sau", "usa"], "cen" => ["cen", "enc"],
      "BGW" => ["BWG"], "Ley" => ["Ley"], "Tlo" => ["Tol"], "aky" => ["kay", "yak"],
      "Agu" => ["Aug"], "GIg" => ["IgG"], "gpy" => ["gyp"], "ELR" => ["ERL"],
      "Gcm" => ["Gmc"], "Peo" => ["Poe"], "MOT" => ["MOT", "MTO", "OTM", "TMO"],
      "AEH" => ["AHE"], "Ree" => ["Ree"], "Sis" => ["Sis"], "juv" => ["juv"],
      "INP" => ["NPI", "PIN"], "CEF" => ["CEF", "CFE", "ECF", "FEC"],
      "drs" => ["dsr"], "buz" => ["buz"], "AGT" => ["TAG"], "Stu" => ["Stu"],
      "Tem" => ["Tem"], "VWa" => ["WVa"], "AKW" => ["AWK"], "Hos" => ["Hos"],
      "acs" => ["sac"], "Aop" => ["Apo"], "Cho" => ["Cho", "Coh"], "suu" => ["usu"],
      "War" => ["War"], "bps" => ["bps", "pbs"], "Ven" => ["Ven"], "FIZ" => ["ZIF"],
      "Ret" => ["Rte"], "gty" => ["tyg"], "ety" => ["ety", "tye", "yet"],
      "CCD" => ["CCD", "CDC", "DCC"], "EFO" => ["EOF", "FOE"], "dnr" => ["rnd"],
      "IMP" => ["IMP", "IPM", "MIP"], "DES" => ["DES", "DSE", "EDS", "ESD", "SED"],
      "LTh" => ["LTh"], "aty" => ["tay", "yat"], "Yin" => ["Yin"],
      "gtu" => ["gut", "tug", "ugt"], "cgh" => ["chg"], "EPW" => ["EPW"],
      "aos" => ["oas", "sao"], "Nay" => ["Nay"], "GLk" => ["LGk"], "AOW" => ["AOW"],
      "Dry" => ["Dry"], "Sfi" => ["Sif"], "MMM" => ["MMM"], "Ecs" => ["Esc"],
      "CPT" => ["CPT", "PTC", "TCP", "TPC"], "RRT" => ["RTR", "TRR"],
      "Kos" => ["Kos"], "DNV" => ["NDV"], "EFS" => ["EFS", "ESF", "FSE"],
      "DMO" => ["DOM", "MOD", "ODM", "OMD"], "ESU" => ["ESU", "USE"],
      "BES" => ["BES", "BSE", "EBS", "ESB", "SBE"], "ARR" => ["RAR"],
      "dfw" => ["fwd"], "FRS" => ["FRS", "FSR", "RFS"], "AHN" => ["NHA"],
      "cer" => ["cer", "cre", "rec"], "krs" => ["krs"], "DJO" => ["DOJ"],
      "eel" => ["eel", "lee"], "Aax" => ["Axa"], "apv" => ["pav", "pva"],
      "Uiz" => ["Uzi"], "eiv" => ["ive", "vei", "vie"], "Wny" => ["Wyn"],
      "evx" => ["vex"], "Tel" => ["Tel"], "Erv" => ["Erv"], "DSX" => ["DSX"],
      "ajm" => ["jam"], "Wbn" => ["Wbn"], "aen" => ["ane", "ean", "nae", "nea"],
      "FHM" => ["MFH", "MHF"], "AFO" => ["FAO"], "Tes" => ["Tes", "Tse"],
      "hik" => ["khi"], "Sen" => ["Sen"], "ksy" => ["sky"], "DGT" => ["DTG"],
      "bop" => ["bop", "pob"], "EGM" => ["GEM"], "hin" => ["hin"],
      "Yam" => ["Yam", "Yma"], "ivz" => ["viz"],
      "AFT" => ["AFT", "ATF", "FAT", "TAF"], "IMg" => ["IgM"], "ahm" => ["ham"],
      "iop" => ["ipo", "poi"], "AOP" => ["AOP", "APO", "OAP", "OPA", "PAO", "POA"],
      "glo" => ["gol", "log"], "AEK" => ["EAK"], "KKK" => ["KKK"], "Wat" => ["Wat"],
      "aio" => ["iao"], "hkz" => ["khz"], "ejt" => ["jet"], "ENb" => ["EbN", "NbE"],
      "cks" => ["csk"], "Sci" => ["Sci", "Sic"], "dst" => ["std"], "HLN" => ["NHL"],
      "aef" => ["fae"], "Uru" => ["Uru"], "DFN" => ["NFD"],
      "afh" => ["fah", "fha", "haf"], "dik" => ["kid"],
      "CFR" => ["CFR", "FRC", "RCF", "RFC"], "CDW" => ["WDC"], "BLM" => ["BLM"],
      "gnu" => ["gnu", "gun", "ung"], "JLP" => ["JPL"],
      "DIM" => ["DIM", "DMI", "IDM", "IMD", "MDI", "MID"], "FIP" => ["FIP", "PIF"],
      "ppu" => ["pup"], "Qeu" => ["Que"], "Qkt" => ["Qkt"], "Pen" => ["Pen"],
      "dqs" => ["sqd"], "hsu" => ["uhs", "ush"], "Hux" => ["Hux"], "AEN" => ["NEA"],
      "Cah" => ["Cha"], "bgu" => ["bug", "gub"], "fgn" => ["fgn"], "BKP" => ["KBP"],
      "Sgt" => ["Sgt"], "Osy" => ["Osy", "Oys"], "Amr" => ["Amr", "Arm"],
      "Los" => ["Los"], "hst" => ["hts", "sht", "tsh"], "Kmy" => ["Kym"],
      "atv" => ["tav", "vat"], "ABW" => ["AWB"], "GUU" => ["UUG"],
      "ahw" => ["haw", "wah", "wha"], "Jde" => ["Jed"], "CGI" => ["CGI", "GCI"],
      "nor" => ["nor", "ron"], "Nci" => ["Nic"], "dou" => ["duo", "oud", "udo"],
      "Imp" => ["Imp"], "Mgi" => ["Mig"], "ENN" => ["NNE"], "EOP" => ["OEP", "POE"],
      "LLN" => ["LLN"], "Bbu" => ["Bub"], "Gio" => ["Gio"], "Jnu" => ["Jun"],
      "diq" => ["qid"], "bko" => ["bok", "kob"], "NPS" => ["NSP", "PSN", "SNP"],
      "aij" => ["jai"], "BIW" => ["BWI"], "Ino" => ["Ino", "Ion"],
      "APU" => ["APU", "AUP", "PAU"], "MTU" => ["MTU", "UMT"],
      "apr" => ["apr", "par", "rap"], "Let" => ["Let"], "Lei" => ["Lie"],
      "Oab" => ["Oba"], "CCU" => ["CCU", "UCC"], "JVW" => ["JWV"], "Giu" => ["Gui"],
      "DRX" => ["RDX", "XDR"], "ALN" => ["ANL", "LAN"], "Fey" => ["Fey"],
      "HMW" => ["HWM", "MHW"], "ELO" => ["ELO", "LEO", "LOE"],
      "BSS" => ["BSS", "SBS", "SSB"], "Uem" => ["Ume"], "Tiw" => ["Tiw", "Twi"],
      "tty" => ["tty", "tyt"], "Aav" => ["Ava"], "Ocs" => ["Osc"], "DRV" => ["DVR"],
      "Ciu" => ["Cui"], "BEd" => ["BEd", "EdB"], "Mru" => ["Mru", "Mur"],
      "llm" => ["llm"], "fox" => ["fox"], "LMS" => ["LSM", "MLS", "MSL"],
      "blw" => ["lbw"], "Aps" => ["Asp"], "otw" => ["owt", "tow", "two", "wot"],
      "STW" => ["TWS"], "DTY" => ["TDY", "YTD"], "eku" => ["euk", "kue", "uke"],
      "BDM" => ["DBM"], "AEI" => ["EIA"], "Fae" => ["Fae"], "aff" => ["aff", "ffa"],
      "EHR" => ["HRE"], "inw" => ["win"], "Ido" => ["Ido"], "Sno" => ["Son"],
      "HMO" => ["HMO", "MOH"], "bpt" => ["bpt"], "BEN" => ["NEB"], "dtw" => ["dwt"],
      "LMP" => ["MPL", "PLM"], "fgi" => ["fig", "gif"], "IQR" => ["IQR", "IRQ"],
      "ACG" => ["AGC", "CGA", "GCA"], "CMP" => ["CPM", "MCP", "MPC", "PCM", "PMC"],
      "Bar" => ["Bar", "Bra"], "CNV" => ["NCV"], "Ods" => ["Ods"], "ALQ" => ["AQL"],
      "GPZ" => ["ZPG"], "Nat" => ["Nat"], "Uks" => ["Usk"], "HMT" => ["HMT"],
      "BNS" => ["BNS", "BSN", "NBS", "NSB"], "Tat" => ["Tat"], "Hmu" => ["Hum"],
      "CDP" => ["CDP", "CPD", "DCP", "DPC"], "BRS" => ["BRS", "RSB", "SRB"],
      "Epp" => ["Epp"], "Agl" => ["Alg"], "CPP" => ["CPP", "PCP", "PPC"],
      "abm" => ["abm", "amb", "bam", "mab", "mba"], "for" => ["for", "fro", "orf"],
      "HOW" => ["HOW", "WHO"], "EHM" => ["HEM", "MHE"], "MTV" => ["MTV", "TMV"],
      "jtu" => ["jut"], "Uaf" => ["Ufa"], "HHI" => ["HIH"],
      "CFO" => ["CFO", "FCO", "FOC"], "HLO" => ["HOL"],
      "ACW" => ["ACW", "CWA", "WAC"], "EMO" => ["EOM", "OEM", "OME"],
      "NOW" => ["NOW"], "Pao" => ["Poa"], "Hnu" => ["Hun"], "cmw" => ["cwm"],
      "Vee" => ["Vee"], "eek" => ["eek", "eke"],
      "CDE" => ["CED", "DCE", "DEC", "ECD", "EDC"], "ass" => ["ass"],
      "blt" => ["blt", "btl"], "dft" => ["dft"], "LOP" => ["LOP", "PLO", "POL"],
      "akn" => ["kan", "nak"], "egy" => ["gey", "gye"], "Mnu" => ["Mun"],
      "iuz" => ["uzi"], "QQV" => ["QQV"], "APX" => ["PAX"], "Eev" => ["Eve"],
      "efs" => ["efs", "fes"], "Boz" => ["Boz"],
      "LPS" => ["LPS", "LSP", "PLS", "PSL", "SLP", "SPL"],
      "DET" => ["DET", "DTE", "EDT", "ETD", "TDE"], "emp" => ["emp"],
      "dhr" => ["rhd"], "DPW" => ["DPW", "PWD"], "Pas" => ["Pas", "Psa"],
      "BEL" => ["BLE"], "GSW" => ["GWS", "SWG", "WGS"], "Oot" => ["Oto"],
      "alr" => ["lar"], "AAA" => ["AAA"], "cuz" => ["cuz"], "HLL" => ["HLL"],
      "Rew" => ["Rew"], "JST" => ["JST"], "CEU" => ["ECU", "EUC", "UEC"],
      "Eds" => ["Esd"], "DVX" => ["DVX"], "NWW" => ["WNW"], "bco" => ["boc", "cob"],
      "EOW" => ["EWO"], "ABN" => ["NAB", "NBA"], "QSY" => ["QSY"], "Aam" => ["Ama"],
      "ekt" => ["ket"], "Odl" => ["Old"], "owy" => ["woy", "yow"],
      "ehy" => ["hey", "hye", "yeh"], "Lux" => ["Lux"], "fru" => ["fur", "urf"],
      "BVd" => ["dBV"], "Yku" => ["Yuk"], "NNT" => ["NTN", "TNN"], "MQS" => ["QMS"],
      "bin" => ["bin", "nib"], "cet" => ["cte", "ect", "etc", "tec"],
      "opw" => ["pow", "wop"], "bsu" => ["bus", "sub"], "him" => ["him"],
      "Oek" => ["kOe"], "ERX" => ["REX"], "aeu" => ["eau"], "Tab" => ["Tab"],
      "apz" => ["zap"], "Cin" => ["nCi"], "Nnu" => ["Nun"], "aiv" => ["iva", "via"],
      "efl" => ["efl", "elf"], "OQV" => ["VOQ"], "GLN" => ["LNG"], "eoz" => ["ezo"],
      "Per" => ["Per"], "Yen" => ["Yen"], "irw" => ["wir"], "efn" => ["fen", "nef"],
      "AKT" => ["ATK"], "HKz" => ["KHz"], "Nev" => ["Nev"], "Sir" => ["Sir", "Sri"],
      "adj" => ["adj", "jad"], "CIM" => ["CIM", "CMI", "ICM", "IMC", "MCI"],
      "Jac" => ["Jac"], "DDT" => ["DDT", "DTD", "TDD"],
      "BCS" => ["BCS", "BSC", "CBS", "CSB", "SBC", "SCB"], "err" => ["err"],
      "GRS" => ["GRS", "GSR", "RGS"], "ims" => ["ism", "mis", "sim"],
      "AIX" => ["AIX"], "ace" => ["ace", "aec"], "boo" => ["boo", "obo"],
      "LSS" => ["LSS", "SLS"], "mpp" => ["ppm"], "gpu" => ["gup", "pug"],
      "adg" => ["dag", "gad"], "elx" => ["lex"], "CEQ" => ["CEQ"],
      "anw" => ["awn", "naw", "wan"], "Lot" => ["Lot"], "Gee" => ["Gee"],
      "cjw" => ["wjc"], "Adn" => ["And"], "GRU" => ["RGU"], "See" => ["See"],
      "DLO" => ["DLO"], "ccw" => ["ccw"], "afx" => ["fax"], "APV" => ["PVA", "VAP"],
      "GHO" => ["OHG"], "Pru" => ["Pru", "Pur"], "Mci" => ["Mic"], "KPS" => ["PSK"],
      "ADS" => ["ADS", "DAS", "DSA", "SDA"], "erx" => ["exr", "rex"],
      "ARV" => ["ARV", "VAR"], "BFL" => ["BLF", "FLB"], "Reg" => ["Reg"],
      "DDS" => ["DDS", "DSD", "SDD"], "MPP" => ["MPP", "PPM"], "gop" => ["gop"],
      "agt" => ["agt", "gat", "tag"], "fsz" => ["sfz"], "CIJ" => ["ICJ", "JIC"],
      "Ibn" => ["Ibn"], "Pit" => ["Pit"], "kln" => ["kln"], "AUX" => ["AUX"],
      "BCI" => ["CBI", "CIB", "ICB"], "CEO" => ["CEO", "COE", "ECO", "OCE"],
      "Oav" => ["Ova"], "lmx" => ["mlx"], "Kei" => ["Kei"], "fsy" => ["fys"],
      "IUZ" => ["UZI"], "Dar" => ["Dar"], "Law" => ["Law"], "Zan" => ["Zan"],
      "kos" => ["kos", "sok"], "epw" => ["pew"], "abk" => ["kab"], "Ldp" => ["Ldp"],
      "PTV" => ["PTV", "PVT", "VTP"], "BSU" => ["BUS", "SBU", "UBS", "USB"],
      "DPT" => ["DPT", "DTP", "PDT", "PTD"], "guz" => ["guz"]}
    |> Map.get(string_id)
  end
end
