defmodule Jumble.LengthDict.Length22 do
  def get(string_id) do
    %{"acchhhiiiilloooopprsst" => ["philosophicohistorical"],
      "aceeehiiilllmnoooppsty" => ["polioencephalomyelitis"],
      "aacceeeeghhllnoopprrty" => ["electroencephalography"],
      "accceeiimmnnnooorttuux" => ["counterexcommunication"],
      "accceiillmnooprrrsttyy" => ["microcryptocrystalline"],
      "aaeeeiilmnnnnooprrsstt" => ["nonrepresentationalism"],
      "aabccdeehlnnooorrrstyy" => ["dacryocystoblennorrhea"],
      "accdgimnoooorrssttyyyy" => ["dacryocystosyringotomy"],
      "aaeeeeeehhilmmnnrtttxy" => ["hexamethylenetetramine"],
      "aacehhhiillmnnnoppstuy" => ["naphthylaminesulphonic"],
      "aacdehhimoooprrrtttyyy" => ["thyroparathyroidectomy"],
      "cceeehiinnnooprsssstuy" => ["hyperconscientiousness"],
      "aacceeghhiillmooopstty" => ["theologicometaphysical"],
      "ccddeehlmnooooossttuyy" => ["cholecystoduodenostomy",
       "duodenocholecystostomy"],
      "aaabcceeiilmmnnoopqttu" => ["aquopentamminecobaltic"],
      "aacehllmooooopprrsttyy" => ["laparocolpohysterotomy"],
      "abccehiiijlnnooprsttuv" => ["blepharoconjunctivitis"],
      "aaccghhhillnoooopprrty" => ["photochronographically"],
      "cceehiilmnoooppssttuyy" => ["pyopneumocholecystitis"],
      "aadehhiimnnoooopprrttz" => ["deanthropomorphization"],
      "aeeeeeiimnnnoprrsssttv" => ["omnirepresentativeness"],
      "aceeghhhilooooppprrstt" => ["photospectroheliograph"],
      "cccdehiiiiiloooorrsstt" => ["scleroticochorioiditis"],
      "aaaccghiiillmnoooopsty" => ["anatomicophysiological"],
      "aadeeghhiillmmnnooopty" => ["lymphangioendothelioma"],
      "aadeeehhiiilmnnnoprtxy" => ["hexanitrodiphenylamine"],
      "acceeehhhlnooprrrsttyy" => ["cholecystenterorrhaphy"],
      "aaaccegimnoooprrssttty" => ["pancreaticogastrostomy"],
      "aceeghhimoooopprrrstty" => ["stereophotomicrography"],
      "ccdddeehhlmnoooooostuy" => ["choledochoduodenostomy"],
      "acddeehiimmnoopprrruuy" => ["hydropneumopericardium",
       "pneumohydropericardium"],
      "aaceeimnooorrsssstttuy" => ["ureterocystanastomosis"],
      "Padghhiilmooooopprrrss" => ["Prorhipidoglossomorpha"],
      "aceeghilmnnoopprrtuuvy" => ["pneumoventriculography"],
      "ceeeeeeehllmmoorrrtttt" => ["electrotelethermometer"],
      "aacceghiillmnooooorstt" => ["theologicoastronomical"],
      "cddeelmnnoooooopsstuuy" => ["pseudomonocotyledonous"],
      "aaccegghiilloooooorstz" => ["zoologicoarchaeologist"],
      "aaabbccchiiiilloorsstt" => ["historicocabbalistical"]}
    |> Map.get(string_id)
  end
end
