defmodule Jumble.LengthDict.Length2 do
  def get(string_id) do
    %{"fg" => ["fg"], "OX" => ["XO"], "cp" => ["cp", "pc"], "Ja" => ["Ja"],
      "AJ" => ["AJ", "JA"], "eg" => ["eg", "ge"], "lo" => ["lo", "ol"],
      "eo" => ["eo", "oe"], "Gc" => ["Gc"], "Ar" => ["Ar"], "PQ" => ["PQ", "QP"],
      "vv" => ["vv"], "TV" => ["TV", "VT"], "OW" => ["OW", "WO"],
      "DP" => ["DP", "PD"], "KZ" => ["ZK"], "Ab" => ["Ab"], "Oe" => ["Oe"],
      "oy" => ["oy", "yo"], "JJ" => ["JJ"], "mp" => ["mp", "pm"], "Bk" => ["Bk"],
      "CD" => ["CD", "DC"], "dt" => ["dt"], "cr" => ["cr", "rc"], "Gd" => ["Gd"],
      "ae" => ["ae", "ea"], "sy" => ["ys"], "TW" => ["TW"], "NP" => ["NP", "PN"],
      "JR" => ["RJ"], "IW" => ["IW", "WI"], "el" => ["el", "le"], "Es" => ["Es"],
      "QS" => ["QS"], "fo" => ["fo", "of"], "Ri" => ["Ri"], "cm" => ["cm", "mc"],
      "MY" => ["MY"], "ii" => ["ii"], "Ho" => ["Ho"], "Sc" => ["Sc", "cS"],
      "mw" => ["mw", "wm"], "FH" => ["HF"], "GM" => ["GM", "MG"], "hu" => ["uh"],
      "PW" => ["PW", "WP"], "nz" => ["zn"], "Lr" => ["Lr"], "Sw" => ["Sw"],
      "cx" => ["xc"], "pv" => ["vp"], "WY" => ["WY"], "NR" => ["NR", "RN"],
      "KW" => ["KW"], "bk" => ["bk", "kb"], "Un" => ["Un"], "MU" => ["MU"],
      "il" => ["il", "li"], "Se" => ["Se"], "gi" => ["gi", "ig"], "Mw" => ["Mw"],
      "ac" => ["ac", "ca"], "nr" => ["nr", "rn"], "Ty" => ["Ty"], "Wp" => ["pW"],
      "GI" => ["GI", "IG"], "Zl" => ["Zl"], "ah" => ["ah", "ha"],
      "er" => ["er", "re"], "AH" => ["AH", "HA"], "AR" => ["AR", "RA"],
      "Hs" => ["Hs"], "Id" => ["Id"], "DU" => ["DU"], "Su" => ["Su"],
      "rw" => ["wr"], "qv" => ["qv"], "GW" => ["GW", "WG"], "rx" => ["xr"],
      "AT" => ["AT", "TA"], "AW" => ["AW", "WA"], "Hm" => ["mH"],
      "IT" => ["IT", "TI"], "BI" => ["BI", "IB"], "GR" => ["GR"], "Nb" => ["Nb"],
      "DR" => ["DR", "RD"], "cy" => ["cy"], "bi" => ["bi", "ib"],
      "FO" => ["FO", "OF"], "Tb" => ["Tb"], "FF" => ["FF"], "Cm" => ["Cm", "mC"],
      "OO" => ["OO"], "An" => ["An"], "cg" => ["cg", "gc"], "Ah" => ["Ah"],
      "Lo" => ["Lo"], "Ph" => ["Ph"], "Ky" => ["Ky"], "AC" => ["AC", "CA"],
      "Ka" => ["Ka"], "Zr" => ["Zr"], "PS" => ["PS", "SP"], "kp" => ["pk"],
      "Dy" => ["Dy"], "KR" => ["KR"], "ch" => ["ch"], "Gr" => ["Gr"],
      "Ng" => ["Ng"], "CT" => ["CT", "TC"], "ST" => ["ST", "TS"], "HV" => ["HV"],
      "gs" => ["gs", "sg"], "au" => ["au"], "cq" => ["cq"], "Bz" => ["Bz", "zB"],
      "Dm" => ["Dm"], "JP" => ["JP"], "Jy" => ["Jy"], "GQ" => ["GQ"],
      "ls" => ["ls", "sl"], "Fn" => ["nF"], "Oz" => ["Oz"], "su" => ["su", "us"],
      "Pt" => ["Pt"], "HJ" => ["HJ"], "ss" => ["ss"], "LS" => ["LS", "SL"],
      "Ca" => ["Ca"], "gj" => ["jg"], "LT" => ["LT", "TL"], "sv" => ["sv", "vs"],
      "Ds" => ["Ds"], "eq" => ["eq", "qe"], "JM" => ["MJ"], "AZ" => ["AZ", "ZA"],
      "EQ" => ["EQ", "QE"], "ee" => ["ee"], "lu" => ["lu"], "Fm" => ["Fm", "mF"],
      "lr" => ["lr"], "PV" => ["PV", "VP"], "Et" => ["Et"], "Od" => ["Od"],
      "RV" => ["RV", "VR"], "SW" => ["SW", "WS"], "FR" => ["FR", "RF"],
      "NV" => ["NV", "VN"], "GG" => ["GG"], "LO" => ["LO", "OL"], "Ad" => ["Ad"],
      "hl" => ["hl", "lh"], "ay" => ["ay", "ya"], "ps" => ["ps", "sp"],
      "Ba" => ["Ba"], "BZ" => ["ZB"], "kn" => ["kn"], "et" => ["et", "te"],
      "VY" => ["YV"], "Ez" => ["Ez"], "GL" => ["LG"], "Di" => ["Di"],
      "Wa" => ["Wa"], "Bo" => ["Bo"], "ap" => ["ap", "pa"], "RS" => ["RS", "SR"],
      "tu" => ["tu", "ut"], "iv" => ["iv", "vi"], "CV" => ["CV", "VC"],
      "ff" => ["ff"], "Mg" => ["Mg"], "BM" => ["BM", "MB"], "Cd" => ["Cd"],
      "TX" => ["TX", "XT"], "Gl" => ["Gl"], "cw" => ["cw", "wc"], "EU" => ["EU"],
      "Fi" => ["Fi"], "lp" => ["lp", "pl"], "bt" => ["bt", "tb"], "PP" => ["PP"],
      "DJ" => ["DJ", "JD"], "VV" => ["VV"], "KS" => ["KS", "SK"], "Ay" => ["Ay"],
      "Zz" => ["Zz"], "oo" => ["oo"], "Tc" => ["Tc"], "lv" => ["lv", "vl"],
      "Cr" => ["Cr"], "ev" => ["ev"], "NW" => ["NW"], "BV" => ["BV", "VB"],
      "Ij" => ["Ij"], "DD" => ["DD"], "Hz" => ["Hz"], "EK" => ["KE"],
      "hm" => ["hm", "mh"], "uz" => ["zu"], "Mr" => ["Mr"], "Ku" => ["Ku"],
      "Wy" => ["Wy"], "Mk" => ["Mk"], "CK" => ["KC"], "EM" => ["EM", "ME"],
      "Zs" => ["Zs"], "gu" => ["gu", "ug"], "ks" => ["ks", "sk"],
      "aw" => ["aw", "wa"], "lt" => ["lt", "tl"], "IU" => ["IU", "UI"],
      "Yt" => ["Yt"], "BS" => ["BS", "SB"], "He" => ["He"], "dg" => ["dg", "gd"],
      "dw" => ["wd"], "ad" => ["ad", "da"], "qy" => ["qy"], "my" => ["my", "ym"],
      "ly" => ["ly"], "HN" => ["NH"], "al" => ["al", "la"], "CP" => ["CP", "PC"],
      "BF" => ["BF", "FB"], "vx" => ["xv"], "QX" => ["XQ"], "Pu" => ["Pu"],
      "Eu" => ["Eu"], "UV" => ["UV", "VU"], "CE" => ["CE", "EC"], "Sb" => ["Sb"],
      "br" => ["br", "rb"], "Ib" => ["Ib"], "VX" => ["VX"], "gk" => ["kg"],
      "BR" => ["BR", "RB"], "Cl" => ["Cl"], "dz" => ["dz"], "cs" => ["cs", "sc"],
      "tx" => ["tx", "xt"], "ER" => ["ER", "RE"], "Xe" => ["Xe"],
      "ms" => ["ms", "sm"], "Na" => ["Na"], "Rx" => ["Rx"], "Em" => ["Em"],
      "Eo" => ["Eo"], "IQ" => ["IQ"], "BB" => ["BB"], "Vu" => ["Vu"],
      "GK" => ["KG"], "BP" => ["BP", "PB"], "nu" => ["nu", "un"],
      "PY" => ["PY", "YP"], "IR" => ["IR", "RI"], "gp" => ["gp", "pg"],
      "OU" => ["OU"], "CH" => ["CH", "HC"], "oz" => ["oz", "zo"], "NX" => ["XN"],
      "Cb" => ["Cb"], "bz" => ["bz"], "Pi" => ["Pi"], "Al" => ["Al"],
      "bg" => ["bg", "gb"], "Ob" => ["Ob"], "qu" => ["qu"], "FW" => ["FW", "WF"],
      "bl" => ["bl", "lb"], "Ac" => ["Ac"], "Wk" => ["kW"], "es" => ["es", "se"],
      "jo" => ["jo", "oj"], "jr" => ["jr"], "IX" => ["IX"], "No" => ["No"],
      "ik" => ["ik", "ki"], "BQ" => ["QB"], "ab" => ["ab", "ba"], "Ms" => ["Ms"],
      "So" => ["So"], "Hu" => ["Hu"], "Wh" => ["Wh"], "lw" => ["lw", "wl"],
      "HQ" => ["HQ"], "ip" => ["pi"], "CI" => ["CI", "IC"], "ag" => ["ag", "ga"],
      "Mx" => ["Mx"], "Os" => ["Os"], "Yf" => ["Yf"], "en" => ["en", "ne"],
      "Ul" => ["Ul"], "ux" => ["ux", "xu"], "ou" => ["ou"], "Ki" => ["Ki"],
      "bd" => ["bd", "db"], "iy" => ["yi"], "cv" => ["cv", "vc"], "Br" => ["Br"],
      "Ce" => ["Ce"], "af" => ["af", "fa"], "uw" => ["wu"], "ZZ" => ["ZZ"],
      "NY" => ["NY"], "cc" => ["cc"], "ir" => ["ir"], "OS" => ["OS", "SO"],
      "dj" => ["dj"], "DW" => ["DW", "WD"], "AQ" => ["AQ", "QA"],
      "mt" => ["mt", "tm"], "Og" => ["Og"], "YY" => ["YY"], "Po" => ["Po"],
      "iu" => ["ui"], "TT" => ["TT"], "am" => ["am", "ma"], "Vm" => ["mV"],
      "Si" => ["Si"], "Rm" => ["mR"], "bw" => ["bw", "wb"], "lx" => ["lx", "xl"],
      "DM" => ["DM", "MD"], "Me" => ["Me"], "bx" => ["bx"], "CM" => ["CM", "MC"],
      "CC" => ["CC"], "Ax" => ["Ax"], "LZ" => ["LZ"], "Ha" => ["Ha"],
      "EO" => ["EO", "OE"], "rz" => ["zr"], "LX" => ["XL"], "MR" => ["MR", "RM"],
      "Om" => ["Om"], "HM" => ["HM", "MH"], "Ap" => ["Ap"], "RW" => ["RW", "WR"],
      "cf" => ["cf", "fc"], "js" => ["js"], "VW" => ["VW", "WV"], "JN" => ["NJ"],
      "Kt" => ["Kt"], "DV" => ["DV", "VD"], "Wb" => ["Wb"], "Ir" => ["Ir"],
      "tt" => ["tt"], "Sp" => ["Sp"], "Fe" => ["Fe"], "FY" => ["FY"],
      "JL" => ["LJ"], "FM" => ["FM", "MF"], "uy" => ["yu"], "OT" => ["OT", "TO"],
      "Il" => ["Il"], "Er" => ["Er"], "Hf" => ["Hf"], "hw" => ["hw", "wh"],
      "bm" => ["bm", "mb"], "Ni" => ["Ni"], "MP" => ["MP", "PM"], "Ft" => ["Ft"],
      "MW" => ["MW", "WM"], "Vk" => ["kV"], "ov" => ["vo"], "Kb" => ["Kb"],
      "IV" => ["IV", "VI"], "KY" => ["KY"], "CN" => ["CN", "NC"],
      "ew" => ["ew", "we"], "DZ" => ["DZ", "ZD"], "GZ" => ["ZG"],
      "NU" => ["NU", "UN"], "fm" => ["fm", "mf"], "Nt" => ["Nt"], "Iy" => ["Iy"],
      "Mv" => ["Mv"], "Av" => ["Av"], "GO" => ["GO", "OG"], "Im" => ["Im"],
      "PT" => ["PT", "TP"], "KV" => ["KV"], "co" => ["co", "oc"],
      "MS" => ["MS", "SM"], "ce" => ["ce", "ec"], "hr" => ["hr", "rh"],
      "LW" => ["LW", "WL"], "Fo" => ["Fo"], "eh" => ["eh", "he"],
      "dp" => ["dp", "pd"], "pu" => ["pu", "up"], "gl" => ["gl", "lg"],
      "KT" => ["KT"], "ES" => ["ES", "SE"], "EV" => ["EV", "VE"],
      "ds" => ["ds", "sd"], "AM" => ["AM", "MA"], "Cc" => ["Cc"],
      "ct" => ["ct", "tc"], "wy" => ["wy"], "dd" => ["dd"], "ci" => ["ci", "ic"],
      "MM" => ["MM"], "Pd" => ["Pd"], "HW" => ["HW", "WH"], "AO" => ["AO", "OA"],
      "If" => ["If"], "aj" => ["ja"], "LV" => ["LV", "VL"], "Ru" => ["Ru"],
      "Ra" => ["Ra"], "Gi" => ["Gi"], "ox" => ["ox"], "IK" => ["KI"],
      "Rb" => ["Rb"], "Bi" => ["Bi"], "BH" => ["BH", "HB"], "hy" => ["hy"],
      "FT" => ["FT"], "pr" => ["pr"], "Bt" => ["Bt"], "gr" => ["gr", "rg"],
      "Pl" => ["Pl"], "FV" => ["FV", "VF"], "EN" => ["NE"], "hs" => ["hs", "sh"],
      "Li" => ["Li"], "rs" => ["rs", "sr"], "DI" => ["DI", "ID"], "Ed" => ["Ed"],
      "It" => ["It"], "Tr" => ["Tr"], "Fu" => ["Fu"], "Th" => ["Th"],
      "ht" => ["ht", "th"], "Co" => ["Co"], "io" => ["io", "oi"],
      "EG" => ["EG", "GE"], "Cy" => ["Cy"], "Ne" => ["Ne"], "PU" => ["PU", "UP"],
      "no" => ["no", "on"], "ow" => ["ow", "wo"], "ei" => ["ie"], "IZ" => ["ZI"],
      "pt" => ["pt", "tp"], "Yb" => ["Yb"], "Wn" => ["nW"], "AX" => ["XA"],
      "LM" => ["LM", "ML"], "MQ" => ["QM"], "WW" => ["WW"], "bp" => ["bp", "pb"],
      "ln" => ["ln", "nl"], "RR" => ["RR"], "fl" => ["fl", "lf"], "uv" => ["uv"],
      "Re" => ["Re"], "Gm" => ["Gm"], "Ct" => ["Ct"], "Ly" => ["Ly"],
      "ku" => ["ku", "uk"], "Gw" => ["Gw"], "IP" => ["IP", "PI"], "Vi" => ["Vi"],
      "Aq" => ["Aq"], "Wm" => ["Wm", "mW"], "HS" => ["HS"], "Ju" => ["Ju"],
      "Au" => ["Au"], "MX" => ["MX"], "BK" => ["KB"], "ns" => ["ns", "sn"],
      "Ks" => ["Ks"], "mm" => ["mm"], "Bd" => ["dB"], "Fr" => ["Fr"],
      "bc" => ["bc", "cb"], "qs" => ["qs", "sq"], "SV" => ["SV", "VS"],
      "AS" => ["AS", "SA"], "ck" => ["ck", "kc"], "Sa" => ["Sa"],
      "dn" => ["dn", "nd"], "IJ" => ["JI"], "DL" => ["LD"], "IN" => ["IN", "NI"],
      "Nd" => ["Nd"], "LU" => ["LU", "UL"], "Hb" => ["Hb"], "HT" => ["HT", "TH"],
      "Sy" => ["Sy"], "Dq" => ["Dq"], "hi" => ["hi"], "as" => ["as", "sa"],
      "DE" => ["DE", "ED"], "Xn" => ["Xn"], "Qy" => ["Qy"], "CG" => ["CG", "GC"],
      "Ko" => ["Ko"], "rt" => ["rt", "tr"], "ET" => ["ET", "TE"],
      "OP" => ["OP", "PO"], "cd" => ["cd", "dc"], "CZ" => ["CZ"],
      "HL" => ["HL", "LH"], "nv" => ["nv"], "ai" => ["ai", "ia"], "Ro" => ["Ro"],
      "mn" => ["mn", "nm"], "La" => ["La"], "LN" => ["NL"], "Jk" => ["kJ"],
      "Ti" => ["Ti"], "OV" => ["OV", "VO"], "HR" => ["HR", "RH"], "Ld" => ["Ld"],
      "CY" => ["CY"], "ky" => ["ky"], "BO" => ["BO", "OB"], "bu" => ["bu"],
      "mo" => ["mo", "om"], "im" => ["im", "mi"], "Sl" => ["Sl"], "qr" => ["qr"],
      "Rh" => ["Rh"], "lm" => ["lm", "ml"], "gv" => ["gv", "vg"], "mv" => ["mv"],
      "MO" => ["MO", "OM"], "kw" => ["kw", "wk"], "FI" => ["FI", "IF"],
      "Bu" => ["Bu"], "Tu" => ["Tu"], "dl" => ["dl", "ld"], "PR" => ["PR", "RP"],
      "ny" => ["ny", "yn"], "Oc" => ["Oc"], "GN" => ["GN", "NG"], "At" => ["At"],
      "Tm" => ["Tm"], "Du" => ["Du"], "AA" => ["AA"], "ey" => ["ey", "ye"],
      "cu" => ["cu", "uc"], "ko" => ["ko", "ok"], "hv" => ["hv"], "Pa" => ["Pa"],
      "Ot" => ["Ot"], "ho" => ["ho", "oh"], "jt" => ["jt"], "Mo" => ["Mo"],
      "mq" => ["qm"], "ix" => ["ix", "xi"], "Gy" => ["Gy"], "Jo" => ["Jo"],
      "Ut" => ["Ut"], "rv" => ["rv", "vr"], "Lw" => ["Lw"], "PX" => ["PX", "XP"],
      "mu" => ["mu", "um"], "HH" => ["HH"], "np" => ["np"], "Ge" => ["Ge"],
      "kl" => ["kl"], "fh" => ["hf"], "km" => ["km", "mk"], "Ch" => ["Ch"],
      "DX" => ["DX", "XD"], "do" => ["do", "od"], "DQ" => ["DQ", "QD"],
      "My" => ["My"], "AB" => ["AB", "BA"], "EL" => ["EL", "LE"],
      "bo" => ["bo", "ob"], "Ao" => ["Ao"], "IL" => ["IL", "LI"],
      "CW" => ["CW", "WC"], "pq" => ["pq", "qp"], "GH" => ["GH", "HG"],
      "Sn" => ["Sn"], "gm" => ["gm", "mg"], "ft" => ["ft"], "Bn" => ["Bn"],
      "TZ" => ["ZT"], "RT" => ["RT", "TR"], "ru" => ["ru", "ur"], "Ls" => ["Ls"],
      "Va" => ["Va"], "Ji" => ["Ji"], "Yu" => ["Yu"], "JO" => ["JO", "OJ"],
      "GV" => ["VG"], "Ex" => ["Ex"], "El" => ["El"], "MV" => ["MV", "VM"],
      "TY" => ["YT"], "BE" => ["BE"], "Rs" => ["Rs"], "Pg" => ["Pg"],
      "Ve" => ["Ve", "eV"], "FQ" => ["QF"], "sz" => ["zs"], "Hr" => ["Hr"],
      "DK" => ["DK", "KD"], "qt" => ["qt"], "Lu" => ["Lu"], "at" => ["at", "ta"],
      "fz" => ["fz"], "fn" => ["fn"], "GS" => ["GS", "SG"], "Je" => ["Je"],
      "AI" => ["AI", "IA"], "Ea" => ["Ea"], "NT" => ["NT", "TN"], "Zn" => ["Zn"],
      "Ci" => ["Ci"], "HP" => ["HP", "PH"], "mr" => ["mr", "rm"], "Ry" => ["Ry"],
      "UY" => ["YU"], "nw" => ["nw"], "FS" => ["FS", "SF"], "Lm" => ["mL"],
      "kv" => ["kv"], "dm" => ["dm", "md"], "ot" => ["ot", "to"],
      "DN" => ["DN", "ND"], "KN" => ["KN"], "HU" => ["HU", "UH"], "bb" => ["bb"],
      "Td" => ["Td"], "BT" => ["BT", "TB"], "Cf" => ["Cf"], "mx" => ["mx"],
      "NO" => ["ON"], "On" => ["On"], "sx" => ["xs"], "lq" => ["ql"],
      "DF" => ["DF", "FD"], "RU" => ["RU", "UR"], "fy" => ["fy"], "eu" => ["eu"],
      "QR" => ["QR", "RQ"], "op" => ["op", "po"], "ll" => ["ll"], "Fp" => ["pF"],
      "De" => ["De"], "SY" => ["SY"], "Ln" => ["Ln"], "DO" => ["DO", "OD"],
      "KP" => ["KP", "PK"], "Ev" => ["Ev"], "fu" => ["fu"], "os" => ["os", "so"],
      "go" => ["go", "og"], "Ag" => ["Ag"], "Gs" => ["Gs"], "RX" => ["RX"],
      "em" => ["em", "me"], "FX" => ["FX"], "av" => ["av", "va"],
      "LP" => ["LP", "PL"], "EF" => ["EF", "FE"], "Cu" => ["Cu"],
      "KO" => ["KO", "OK"], "HK" => ["HK"], "Ep" => ["Ep"], "an" => ["an", "na"],
      "BW" => ["BW", "WB"], "Is" => ["Is"], "Cs" => ["Cs"], "Mc" => ["Mc"],
      "FN" => ["NF"], "Ak" => ["kA"], "Mm" => ["mM"], "CQ" => ["CQ", "QC"],
      "IO" => ["IO"], "in" => ["in", "ni"], "BU" => ["BU", "UB"], "UU" => ["UU"],
      "de" => ["de", "ed"], "Rn" => ["Rn"], "fi" => ["fi", "if"], "Pb" => ["Pb"],
      "Ok" => ["Ok"], "ry" => ["yr"], "EP" => ["EP", "PE"], "it" => ["it", "ti"],
      "AG" => ["AG", "GA"], "fv" => ["fv"], "DG" => ["DG", "GD"], "aq" => ["aq"],
      "Kr" => ["Kr"], "Lt" => ["Lt"], "HI" => ["HI"], "Io" => ["Io"],
      "GP" => ["GP", "PG"], "ex" => ["ex", "xe"], "CS" => ["CS", "SC"],
      "Hp" => ["pH"], "nq" => ["qn"], "be" => ["be"], "Te" => ["Te"],
      "Wu" => ["Wu"], "aa" => ["aa"], "dk" => ["dk"], "BN" => ["BN", "NB"],
      "jn" => ["nj"], "Iz" => ["Iz"], "ax" => ["ax"], "iw" => ["iw", "wi"],
      "Eg" => ["Eg"], "IM" => ["IM", "MI"], "pp" => ["pp"], "Rp" => ["Rp"],
      "BD" => ["BD", "DB"], "Ud" => ["Ud"], "FP" => ["FP", "PF"], "bh" => ["hb"],
      "EI" => ["EI", "IE"], "Vt" => ["Vt"], "AL" => ["AL", "LA"], "Yi" => ["Yi"],
      "JV" => ["JV", "VJ"], "dx" => ["dx", "xd"], "MT" => ["MT", "TM"],
      "In" => ["In"], "az" => ["az", "za"], "Sq" => ["Sq"], "fs" => ["fs", "sf"],
      "st" => ["st", "ts"], "kt" => ["kt", "tk"], "sw" => ["sw", "ws"],
      "gn" => ["gn", "ng"], "iq" => ["iq", "qi"], "Dr" => ["Dr"],
      "ak" => ["ak", "ka"], "hp" => ["hp", "ph"], "Jr" => ["Jr"], "EW" => ["EW"],
      "BG" => ["BG", "GB"], "dr" => ["dr", "rd"], "AV" => ["AV", "VA"],
      "Pr" => ["Pr"], "NQ" => ["NQ", "QN"], "Qq" => ["Qq"], "UW" => ["UW", "WU"],
      "gh" => ["hg"], "AE" => ["AE", "EA"], "ep" => ["ep", "pe"],
      "OR" => ["OR", "RO"], "NZ" => ["NZ"], "ty" => ["yt"], "Jl" => ["Jl"],
      "MN" => ["MN", "NM"], "FL" => ["FL", "LF"], "Rf" => ["Rf"], "Ox" => ["Ox"],
      "DT" => ["DT", "TD"], "Xt" => ["Xt"], "JS" => ["SJ"], "LL" => ["LL"],
      "is" => ["is", "si"], "Gk" => ["Gk", "kG"], "BL" => ["BL", "LB"],
      "Sm" => ["Sm"], "EE" => ["EE"], "bv" => ["bv", "vb"], "ef" => ["ef", "fe"],
      "LR" => ["LR", "RL"], "As" => ["As"], "QV" => ["QV"], "SX" => ["SX", "XS"],
      "TU" => ["TU", "UT"], "DH" => ["DH", "HD"], "Ic" => ["Ic"],
      "CO" => ["CO", "OC"], "CF" => ["CF", "FC"], "AK" => ["AK"],
      "SU" => ["SU", "US"], "Ga" => ["Ga"], "CR" => ["CR", "RC"],
      "AU" => ["AU", "UA"], "gt" => ["gt", "tg"], "Ns" => ["Ns"],
      "bn" => ["bn", "nb"], "GT" => ["GT", "TG"], "by" => ["by", "yb"],
      "or" => ["or", "ro"], "dy" => ["dy", "yd"], "dh" => ["hd"], "KU" => ["UK"],
      "AF" => ["AF", "FA"], "AN" => ["AN", "NA"], "wx" => ["xw"],
      "AP" => ["AP", "PA"], "Op" => ["Op"], "Pm" => ["Pm"], "HO" => ["HO", "OH"],
      "Py" => ["Py"], "Ma" => ["Ma"], "Mn" => ["Mn"], "AD" => ["AD", "DA"],
      "Tl" => ["Tl"], "AY" => ["AY", "YA"], "gw" => ["wg"], "Go" => ["Go"],
      "tv" => ["tv", "vt"], "cl" => ["cl", "lc"], "Hg" => ["Hg"], "dv" => ["vd"],
      "nt" => ["nt", "tn"], "hz" => ["hz"], "BC" => ["BC", "CB"], "Eb" => ["Eb"],
      "NS" => ["NS", "SN"], "Ps" => ["Ps"], "CL" => ["CL", "LC"],
      "fw" => ["fw", "wf"], "Mb" => ["Mb"], "bf" => ["bf", "fb"], "St" => ["St"],
      "Mt" => ["Mt"], "du" => ["du"], "Le" => ["Le"], "Ia" => ["Ia"],
      "fp" => ["fp", "pf"], "BX" => ["BX", "XB"], "Hy" => ["Hy"], "tw" => ["wt"],
      "Rd" => ["Rd"], "CJ" => ["CJ", "JC"], "HZ" => ["HZ"], "Ur" => ["Ur"],
      "kr" => ["kr"], "xx" => ["xx"], "di" => ["di", "id"], "Af" => ["Af"],
      "fr" => ["fr", "rf"], "Sr" => ["Sr"], "Be" => ["Be"], "Hi" => ["Hi"],
      "Fl" => ["Fl"], "GU" => ["GU", "UG"], "Ta" => ["Ta"], "SS" => ["SS"],
      "Md" => ["Md"], "Np" => ["Np"], "BY" => ["YB"], "IS" => ["IS", "SI"],
      "bs" => ["bs", "sb"], "DS" => ["DS", "SD"], "Gb" => ["Gb"], "hn" => ["hn"],
      "Am" => ["Am", "mA"], "hq" => ["hq", "qh"], "CU" => ["CU", "UC"],
      "ar" => ["ar", "ra"], "EH" => ["HE"]}
    |> Map.get(string_id)
  end
end
