defmodule Jumble.LengthDict.Length3 do
  def get(string_id) do
    %{"Sak" => ["Sak"], "loy" => ["loy"], "abo" => ["boa"], "aek" => ["ake", "kea"],
      "hot" => ["hot", "tho"], "aem" => ["ame", "mae"], "oow" => ["woo"],
      "Aan" => ["Ana"], "ctu" => ["cut"], "afr" => ["far", "fra"], "mux" => ["mux"],
      "eoy" => ["yeo", "yoe"], "ahk" => ["hak"], "dgu" => ["dug", "gud"],
      "abd" => ["bad", "dab"], "hip" => ["hip", "phi"],
      "elu" => ["leu", "lue", "ule"], "Sim" => ["Sim"], "Gbi" => ["Gib"],
      "bgi" => ["big", "gib"], "osy" => ["soy"], "Rdo" => ["Rod"], "Abu" => ["Abu"],
      "Kaw" => ["Kaw"], "pru" => ["pur"], "imx" => ["mix"], "Tim" => ["Tim"],
      "ikl" => ["ilk", "kil"], "nru" => ["run", "urn"], "gmy" => ["gym"],
      "bde" => ["bed", "deb"], "Pat" => ["Pat"], "aak" => ["aka"], "dsu" => ["sud"],
      "Pai" => ["Pia"], "lot" => ["lot", "tol"], "Jbo" => ["Job"],
      "agj" => ["gaj", "jag"], "Uan" => ["Una"], "cly" => ["cly"], "ehu" => ["hue"],
      "egn" => ["gen"], "ehi" => ["hei", "hie"], "Ges" => ["Ges"], "Peg" => ["Peg"],
      "Aas" => ["Asa"], "Mno" => ["Mon"], "egu" => ["gue"], "hnt" => ["nth"],
      "eov" => ["voe"], "Urs" => ["Urs"], "bel" => ["bel", "elb"], "ajy" => ["jay"],
      "ano" => ["noa", "ona"], "aat" => ["taa"], "aey" => ["aye", "yea"],
      "eil" => ["lei", "lie"], "Aak" => ["Aka"], "deu" => ["due"], "Ben" => ["Ben"],
      "ooz" => ["zoo"], "hop" => ["hop", "pho", "poh"], "nno" => ["non"],
      "ggi" => ["gig"], "acy" => ["cay"], "ahp" => ["hap", "pah"],
      "apu" => ["pau", "pua"], "ivy" => ["ivy"], "aes" => ["aes", "ase", "sea"],
      "fnu" => ["fun"], "ewy" => ["wey", "wye", "yew"], "afn" => ["fan"],
      "ott" => ["tot"], "Bab" => ["Bab"], "iju" => ["uji"], "dev" => ["dev"],
      "cgo" => ["cog"], "abl" => ["alb", "bal", "lab"], "aft" => ["aft", "fat"],
      "dop" => ["dop", "pod"], "bdo" => ["bod", "dob"], "imn" => ["min", "nim"],
      "Nip" => ["Nip"], "imm" => ["mim"], "Kaj" => ["Kaj"], "Lak" => ["Lak"],
      "cgi" => ["cig"], "cox" => ["cox"], "chi" => ["chi", "hic", "ich"],
      "Bos" => ["Bos"], "flu" => ["flu"], "aln" => ["aln", "lan"], "ops" => ["sop"],
      "epy" => ["yep"], "tux" => ["tux"], "eit" => ["tie"],
      "ehr" => ["her", "reh", "rhe"], "efk" => ["kef"], "ior" => ["rio", "roi"],
      "now" => ["now", "own", "won"], "app" => ["pap"], "hoy" => ["hoy"],
      "acm" => ["cam", "mac"], "hku" => ["khu"], "Dan" => ["Dan"], "ovw" => ["vow"],
      "bfi" => ["fib"], "amy" => ["amy", "may", "yam"], "atx" => ["tax"],
      "ikm" => ["kim"], "dep" => ["ped"], "ept" => ["pet"], "psy" => ["spy"],
      "Roy" => ["Roy"], "amt" => ["amt", "mat", "tam"],
      "aps" => ["asp", "sap", "spa"], "itt" => ["tit"], "Rsu" => ["Rus"],
      "aly" => ["aly", "lay"], "bow" => ["bow", "wob"], "aoz" => ["azo", "zoa"],
      "Ial" => ["Ila"], "ddo" => ["dod", "odd"], "akr" => ["ark", "kra"],
      "alx" => ["lax"], "cht" => ["tch"], "ell" => ["ell"], "foy" => ["foy"],
      "Sal" => ["Sal"], "Net" => ["Net"], "eny" => ["eyn", "nye", "yen"],
      "dim" => ["dim", "mid"], "beg" => ["beg"], "cno" => ["con"], "ajw" => ["jaw"],
      "opp" => ["pop"], "eeg" => ["gee"], "Sku" => ["Suk"], "kop" => ["kop"],
      "aot" => ["oat", "tao", "toa"], "est" => ["set"],
      "aet" => ["ate", "eat", "eta", "tae", "tea"], "iio" => ["oii"],
      "auv" => ["uva", "vau"], "flo" => ["lof"], "Iar" => ["Ira"], "deh" => ["edh"],
      "For" => ["For"], "mru" => ["rum"], "Nde" => ["Ned"], "Bae" => ["Bea"],
      "orw" => ["row", "wro"], "Uor" => ["Uro"], "dos" => ["dos", "sod"],
      "inn" => ["inn"], "etw" => ["tew", "wet"], "aqu" => ["qua"], "kou" => ["kou"],
      "ill" => ["ill"], "Aev" => ["Ave"], "dei" => ["die", "ide"],
      "oty" => ["toy", "yot"], "diw" => ["wid"], "kno" => ["kon"], "cmu" => ["cum"],
      "bio" => ["obi"], "Mes" => ["Mes"], "fop" => ["fop"], "Aku" => ["Auk"],
      "Abe" => ["Abe"], "lmo" => ["olm"], "Abo" => ["Abo"], "Pop" => ["Pop"],
      "Uir" => ["Uri"], "hor" => ["rho"], "ein" => ["nei"], "den" => ["den", "end"],
      "Cat" => ["Cat"], "cit" => ["cit", "tic"], "Lfi" => ["Lif"], "Lru" => ["Lur"],
      "aim" => ["aim", "ami"], "Ydi" => ["Yid"], "iko" => ["koi", "oki"],
      "ilo" => ["oil"], "Dbo" => ["Dob"], "gim" => ["gim", "mig"], "Laz" => ["Laz"],
      "fgo" => ["fog"], "emn" => ["men"], "rsu" => ["sur"], "Lcu" => ["Luc"],
      "bbu" => ["bub"], "nsu" => ["sun"], "imu" => ["imu"], "Mat" => ["Mat"],
      "elr" => ["rel"], "afm" => ["fam"], "ilp" => ["lip"], "duw" => ["wud"],
      "rty" => ["try"], "abe" => ["bae"], "opu" => ["upo"], "Win" => ["Win"],
      "coo" => ["coo"], "oru" => ["our"], "fot" => ["fot", "oft"], "Vci" => ["Vic"],
      "orx" => ["rox"], "etz" => ["tez"], "ipt" => ["pit", "tip"], "ahi" => ["hia"],
      "los" => ["sol"], "cpy" => ["cyp"], "emu" => ["emu", "ume"], "Lai" => ["Lai"],
      "ben" => ["ben", "neb"], "enp" => ["nep", "pen"], "alw" => ["awl", "law"],
      "bir" => ["rib"], "cei" => ["ice"], "ent" => ["net", "ten"], "Tad" => ["Tad"],
      "Tor" => ["Tor"], "eez" => ["zee"], "Dot" => ["Dot"], "mmu" => ["mum"],
      "eey" => ["eye", "yee"], "ekx" => ["kex"], "Siu" => ["Sui"],
      "add" => ["add", "dad"], "pry" => ["pry", "pyr"], "Lmu" => ["Lum"],
      "Edo" => ["Edo"], "isv" => ["vis"], "ady" => ["ady", "day", "yad"],
      "Mio" => ["Moi"], "aru" => ["aru", "ura"], "acp" => ["cap", "pac"],
      "Sdy" => ["Syd"], "def" => ["fed"], "Ran" => ["Ran"], "suy" => ["yus"],
      "blo" => ["blo", "lob"], "ary" => ["ary", "ray", "yar"], "nuw" => ["wun"],
      "mow" => ["mow"], "alu" => ["ula"], "opy" => ["poy"], "bet" => ["bet"],
      "dit" => ["dit", "tid"], "ads" => ["das", "sad"], "ego" => ["ego", "geo"],
      "Meo" => ["Meo", "Moe"], "eht" => ["het", "the"], "een" => ["nee"],
      "abp" => ["bap"], "esu" => ["sue", "use"], "eop" => ["ope", "poe"],
      "bfo" => ["fob"], "ahy" => ["hay", "yah"], "ast" => ["ast", "sat"],
      "ceh" => ["che"], "isy" => ["yis"], "Spy" => ["Spy"], "Cdi" => ["Cid"],
      "abc" => ["bac", "cab"], "eru" => ["rue", "ure"], "gno" => ["gon", "nog"],
      "guy" => ["guy"], "efo" => ["foe"], "hox" => ["hox"],
      "anr" => ["arn", "nar", "ran"], "ceo" => ["coe"], "ipr" => ["pir", "rip"],
      "ekp" => ["kep"], "Sdi" => ["Sid"], "cos" => ["cos", "soc"],
      "adw" => ["awd", "daw", "wad"], "iwz" => ["wiz"],
      "agr" => ["gar", "gra", "rag"], "cho" => ["cho", "och"], "abb" => ["abb"],
      "Fin" => ["Fin"], "Wac" => ["Wac"], "dir" => ["rid"], "dpu" => ["dup", "pud"],
      "atu" => ["tau", "tua", "uta"], "efi" => ["fei", "fie", "ife"],
      "aor" => ["oar", "ora"], "egm" => ["gem"], "Maw" => ["Mwa"], "anv" => ["van"],
      "dis" => ["dis"], "Uet" => ["Ute"], "del" => ["eld", "led"], "ruw" => ["wur"],
      "clo" => ["col"], "Ign" => ["Ing"], "guv" => ["vug"], "ens" => ["ens", "sen"],
      "htu" => ["hut"], "bes" => ["bes"], "acl" => ["cal", "lac"], "ehp" => ["hep"],
      "Eav" => ["Eva"], "gju" => ["jug"], "biu" => ["ubi"], "Les" => ["Les"],
      "agv" => ["vag"], "nop" => ["pon"], "Liu" => ["Lui"],
      "aer" => ["aer", "are", "ear", "era", "rea"], "kly" => ["kyl"],
      "bjo" => ["job"], "ilt" => ["lit", "til"], "ffo" => ["off"],
      "aep" => ["ape", "pea"], "aal" => ["aal", "ala"], "Kay" => ["Kay"],
      "Mdo" => ["Mod"], "dry" => ["dry"], "ino" => ["ion"], "Bbo" => ["Bob"],
      "oww" => ["wow"], "ajs" => ["saj"], "efr" => ["ref"], "bmo" => ["bom", "mob"],
      "efu" => ["feu"], "agu" => ["gau"], "agz" => ["gaz", "zag"], "det" => ["ted"],
      "Mam" => ["Mam"], "egg" => ["egg"], "bbi" => ["bib"], "boy" => ["boy"],
      "hio" => ["hoi"], "act" => ["act", "cat"], "dot" => ["dot", "tod"],
      "afl" => ["alf"], "deo" => ["doe", "ode"], "bhu" => ["hub"],
      "glu" => ["gul", "lug"], "stu" => ["ust"], "eno" => ["eon", "neo", "one"],
      "eip" => ["pie"], "suz" => ["suz"], "lsy" => ["lys", "sly"], "Ken" => ["Ken"],
      "ijt" => ["tji"], "eev" => ["eve", "vee"], "Kar" => ["Kra"], "eps" => ["pes"],
      "Zep" => ["Zep"], "tuu" => ["utu"], "Jem" => ["Jem"], "amp" => ["map", "pam"],
      "Jam" => ["Jam"], "eow" => ["owe", "woe"], "bey" => ["bey", "bye"],
      "abs" => ["bas", "sab"], "moo" => ["moo"], "adt" => ["tad"], "Fno" => ["Fon"],
      "Sho" => ["Sho"], "Emm" => ["Emm"], "bdu" => ["bud", "dub"], "dnu" => ["dun"],
      "asv" => ["vas"], "axz" => ["zax"], "Dno" => ["Don"], "cop" => ["cop"],
      "Bdu" => ["Bud"], "Suu" => ["Suu"], "ail" => ["ail", "lai"], "elw" => ["lew"],
      "mno" => ["mon"], "ekn" => ["ken"], "Uat" => ["Uta"], "Ibo" => ["Ibo"],
      "psu" => ["pus", "sup"], "Jan" => ["Jan"], "dor" => ["dor", "rod"],
      "ant" => ["ant", "nat", "tan"], "ajr" => ["jar", "raj"], "dfo" => ["fod"],
      "ikt" => ["kit"], "gjo" => ["jog"], "Iek" => ["Ike"], "Sam" => ["Sam"],
      "adl" => ["dal", "lad"], "Uds" => ["Uds"], "dmo" => ["dom"], "exy" => ["yex"],
      "ejo" => ["joe"], "bis" => ["bis", "sib"], "hos" => ["sho", "soh"],
      "als" => ["las", "sal", "sla"], "ckt" => ["tck"], "Gdo" => ["God"],
      "Tai" => ["Tai"], "bor" => ["bor", "orb", "rob"], "cep" => ["cep"],
      "bgo" => ["bog", "gob"], "Ray" => ["Ray"], "abi" => ["iba"], "apx" => ["pax"],
      "puw" => ["wup"], "epp" => ["pep"], "eem" => ["eme"], "itu" => ["tui"],
      "ehm" => ["hem"], "ber" => ["ber", "reb"], "Bno" => ["Bon"],
      "ils" => ["lis", "sil"], "Kee" => ["Kee"], "Rio" => ["Rio"], "Rmu" => ["Rum"],
      "bcu" => ["cub"], "goy" => ["goy"], "Gde" => ["Ged"], "Rbo" => ["Rob"],
      "mpu" => ["ump"], "iss" => ["sis"], "lux" => ["lux"], "Ler" => ["Ler"],
      "Iad" => ["Ida"], "muv" => ["vum"], "enw" => ["new", "wen"],
      "aht" => ["hat", "tha"], "ist" => ["ist", "its", "sit"],
      "dno" => ["don", "nod"], "alt" => ["alt", "lat", "tal"], "eho" => ["hoe"],
      "ams" => ["mas", "sam", "sma"], "hsy" => ["shy"], "anp" => ["nap", "pan"],
      "ahs" => ["ash", "sah", "sha"], "osw" => ["sow"], "Dor" => ["Dor"],
      "bru" => ["bur", "rub"], "stt" => ["tst"], "gmo" => ["mog"], "Ijo" => ["Ijo"],
      "ehs" => ["she"], "acr" => ["arc", "car"], "Dlo" => ["Dol"], "Zae" => ["Zea"],
      "acz" => ["zac"], "gis" => ["sig"], "adh" => ["dah", "dha", "had"],
      "Flo" => ["Flo"], "etv" => ["vet"], "cis" => ["sic"], "foo" => ["foo"],
      "dip" => ["dip"], "ako" => ["ako", "koa", "oak", "oka"], "Klo" => ["Kol"],
      "dru" => ["rud", "urd"], "ado" => ["ado", "dao", "oda"], "Jos" => ["Jos"],
      "cko" => ["ock"], "esy" => ["sey", "sye", "yes"], "pst" => ["pst"],
      "ehx" => ["hex"], "Rno" => ["Ron"], "imr" => ["mir", "rim"],
      "abw" => ["baw", "wab"], "beo" => ["obe"], "aev" => ["ave"], "fow" => ["fow"],
      "emw" => ["mew", "wem"], "imv" => ["vim"], "aku" => ["aku", "auk"],
      "Mac" => ["Mac"], "cip" => ["pic"], "Lgu" => ["Lug"], "adf" => ["fad"],
      "aas" => ["saa"], "aby" => ["aby", "bay"], "aam" => ["aam", "ama"],
      "aaw" => ["awa"], "abg" => ["bag", "gab"], "agw" => ["gaw", "wag"],
      "bit" => ["bit", "tib"], "Ait" => ["Ati"], "hoo" => ["oho"],
      "aho" => ["aho", "hao"], "Mrs" => ["Mrs"], "noy" => ["noy", "yon"],
      "bnu" => ["bun", "nub"], "Mah" => ["Mah"], "Lew" => ["Lew"], "Gsu" => ["Gus"],
      "hhu" => ["huh"], "Kah" => ["Kha"], "cdu" => ["cud"], "Zao" => ["Zoa"],
      "apy" => ["pay", "pya", "yap"], "Jay" => ["Jay"],
      "abr" => ["bar", "bra", "rab"], "bbe" => ["ebb"], "ikn" => ["ink", "kin"],
      "tuw" => ["wut"], "Idn" => ["Ind"], "Aix" => ["Aix"], "Guy" => ["Guy"],
      "ars" => ["ras", "sar"], "Len" => ["Len"], "git" => ["git", "tig"],
      "Hku" => ["Huk"], "ain" => ["ani"], "dlo" => ["lod", "old"], "Pim" => ["Pim"],
      "bim" => ["mib"], "all" => ["all"], "Gil" => ["Gil"], "eet" => ["tee"],
      "coy" => ["coy"], "Hal" => ["Hal"], "giw" => ["wig"], "erz" => ["zer"],
      "mot" => ["mot"], "biz" => ["biz"], "Bat" => ["Bat"], "eef" => ["fee"],
      "gru" => ["gur", "rug"], "Iam" => ["Ima"], "efz" => ["fez"], "Dbe" => ["Deb"],
      "Shu" => ["Shu"], "Msu" => ["Mus"], "eky" => ["key"], "Hiu" => ["Hui"],
      "fix" => ["fix"], "gin" => ["gin", "ing", "nig"], "His" => ["Hsi"],
      "ade" => ["ade", "dae"], "iim" => ["imi"], "abu" => ["abu"], "buy" => ["buy"],
      "Asu" => ["Aus"], "bot" => ["bot"], "ipz" => ["zip"], "Odz" => ["Odz"],
      "bos" => ["sob"], "egs" => ["seg"], "Jap" => ["Jap"], "iks" => ["ski"],
      "hmu" => ["hum"], "got" => ["got", "tog"], "Mab" => ["Mab"],
      "ach" => ["ach", "cha"], "aeg" => ["age"], "imp" => ["imp"], "Oel" => ["Ole"],
      "gos" => ["gos", "sog"], "Val" => ["Val"], "eor" => ["oer", "ore", "roe"],
      "aar" => ["ara"], "Tde" => ["Ted"], "ees" => ["see"], "Vip" => ["Vip"],
      "ikp" => ["kip", "pik"], "eft" => ["eft", "fet"], "Tho" => ["Tho"],
      "adi" => ["aid"], "llu" => ["ull"], "his" => ["his", "shi"],
      "eir" => ["ire", "rie"], "dez" => ["zed"], "Kit" => ["Kit"], "ajp" => ["jap"],
      "dmu" => ["dum", "mud"], "ipy" => ["yip"], "Ian" => ["Ian"],
      "agm" => ["gam", "mag"], "bho" => ["hob"], "bbo" => ["bob"], "Iat" => ["Ita"],
      "fir" => ["fir"], "iln" => ["lin", "nil"], "nwy" => ["wyn"], "ost" => ["sot"],
      "Rau" => ["Rua"], "bfu" => ["fub"], "Max" => ["Max"], "agg" => ["gag"],
      "Aim" => ["Ami"], "irx" => ["rix"], "iny" => ["yin"], "isw" => ["wis"],
      "mor" => ["mor"], "oxy" => ["oxy", "yox"], "ftu" => ["fut"],
      "ael" => ["ale", "lea"], "otx" => ["tox"], "Fru" => ["Fur"],
      "ory" => ["ory", "yor"], "Udi" => ["Udi"], "emm" => ["mem"], "gny" => ["gyn"],
      "huy" => ["yuh"], "pxy" => ["pyx"], "giz" => ["zig"], "dfi" => ["fid"],
      "Waf" => ["Waf"], "Jno" => ["Jon"], "Afl" => ["Alf"], "fly" => ["fly"],
      "Pan" => ["Pan"], "goo" => ["goo"], "gor" => ["gor", "rog"],
      "akl" => ["alk", "lak"], "int" => ["nit", "tin"], "Pam" => ["Pam"],
      "air" => ["air", "ria"], "elm" => ["elm", "mel"], "Mar" => ["Mar"],
      "cru" => ["cur"], "Hno" => ["Hon"], "Rik" => ["Rik"], "ios" => ["iso"],
      "lop" => ["lop", "pol"], "Liv" => ["Liv"], "kow" => ["owk"], "ggo" => ["gog"],
      "Nan" => ["Nan"], "etu" => ["tue"], "dej" => ["jed"], "aap" => ["apa"],
      "Uac" => ["Uca"], "May" => ["May", "Mya"], "Jeo" => ["Joe"], "Eil" => ["Eli"],
      "ann" => ["ann", "nan"], "iot" => ["toi"], "Oan" => ["Ona"], "afo" => ["oaf"],
      "Kim" => ["Kim"], "not" => ["not", "ton"], "Zen" => ["Zen"], "sty" => ["sty"],
      "Fan" => ["Fan"], "dee" => ["dee"], "any" => ["any", "nay", "yan"],
      "gij" => ["jig"], "imw" => ["wim"], "ely" => ["ley", "lye"], "Rab" => ["Rab"],
      "adk" => ["dak"], "adz" => ["adz", "zad"], "luu" => ["ulu"], "ssu" => ["ssu"],
      "atw" => ["taw", "twa", "wat"], "abj" => ["jab"], "ehn" => ["hen"],
      "Haw" => ["Hwa"], "Ram" => ["Ram"], "abh" => ["bah"],
      "ahu" => ["ahu", "auh", "hau"], "els" => ["els"], "opr" => ["pro"],
      "lpu" => ["pul"], "Liz" => ["Liz"], "fry" => ["fry"], "ekl" => ["elk", "lek"],
      "aks" => ["ask"], "apt" => ["apt", "pat", "tap"],
      "cor" => ["cor", "cro", "orc", "roc"], "egi" => ["gie"], "aex" => ["axe"],
      "alp" => ["alp", "lap", "pal"], "Lin" => ["Lin"], "adr" => ["dar", "rad"],
      "npu" => ["pun"], "art" => ["art", "rat", "tar", "tra"], "Gad" => ["Gad"],
      "asy" => ["say", "yas"], "ceu" => ["cue"], "ghu" => ["hug", "ugh"],
      "dfu" => ["fud"], "bew" => ["web"], "ips" => ["psi", "sip"], "cot" => ["cot"],
      "eot" => ["toe"], "aww" => ["waw"], "San" => ["San"], "lnu" => ["nul"],
      "loo" => ["loo"], "egk" => ["keg"], "arz" => ["zar"], "agl" => ["gal", "lag"],
      "Abl" => ["Alb"], "Slo" => ["Sol"], "Vai" => ["Vai"], "atz" => ["zat"],
      "Yao" => ["Yao"], "ait" => ["ait", "tai"], "oqu" => ["quo"],
      "aab" => ["aba", "baa"], "efy" => ["fey"], "dow" => ["dow", "owd", "wod"],
      "hty" => ["thy"], "eos" => ["oes", "ose", "soe"], "ptu" => ["put", "tup"],
      "rwy" => ["wry"], "lov" => ["vol"], "Tmo" => ["Tom"], "egz" => ["gez"],
      "emt" => ["met"], "agh" => ["hag"], "hpy" => ["hyp"], "ipx" => ["pix"],
      "asx" => ["sax"], "kor" => ["kor"], "adn" => ["and", "dan"], "joy" => ["joy"],
      "aan" => ["ana", "naa"], "low" => ["low", "owl"], "isx" => ["six"],
      "fmu" => ["fum"], "Ofo" => ["Ofo"], "elt" => ["elt", "let"], "muu" => ["umu"],
      "abt" => ["bat", "tab"], "nsy" => ["sny"], "Wei" => ["Wei"], "Teh" => ["The"],
      "alo" => ["alo", "loa"], "auy" => ["ayu"], "fin" => ["fin"],
      "moy" => ["moy", "yom"], "hii" => ["ihi"], "aew" => ["awe", "wae"],
      "ipp" => ["pip"], "Wae" => ["Wea"], "Del" => ["Del"], "hwy" => ["why"],
      "mou" => ["mou"], "ddi" => ["did"], "cee" => ["cee"], "ahr" => ["rah"],
      "opt" => ["opt", "pot", "top"], "itw" => ["wit"], "hit" => ["hit"],
      "bdi" => ["bid", "dib"], "Rex" => ["Rex"], "agn" => ["gan", "nag"],
      "Kru" => ["Kru"], "Bee" => ["Bee"], "ins" => ["sin"], "efw" => ["few"],
      "irs" => ["sir", "sri"], "akz" => ["zak"], "bpu" => ["pub"], "Art" => ["Art"],
      "agy" => ["agy", "gay"], "Nep" => ["Nep"], "jot" => ["jot"], "afg" => ["fag"],
      "gov" => ["vog"], "att" => ["tat"], "rtu" => ["rut", "tur"], "Lae" => ["Lea"],
      "otu" => ["out", "tou"], "awx" => ["wax"], "egl" => ["gel", "leg"],
      "Sai" => ["Sia"], "acw" => ["caw"], "Rko" => ["Rok"], "Jef" => ["Jef"],
      "asw" => ["saw", "swa", "was"], "acd" => ["cad"], "fou" => ["fou", "ouf"],
      "aah" => ["aha"], "inx" => ["nix"], "lmu" => ["lum"], "Nou" => ["Nou"],
      "dew" => ["dew", "wed"], "eer" => ["eer", "ere", "ree"], "nnu" => ["nun"],
      "ioy" => ["iyo", "yoi"], "Gor" => ["Gor"], "egr" => ["erg", "ger", "reg"],
      "Gmu" => ["Gum"], "rux" => ["rux"], "dil" => ["lid"], "gho" => ["hog"],
      "irt" => ["rit", "tri"], "afy" => ["fay"], "ouy" => ["you"],
      "din" => ["din", "nid"], "lpy" => ["ply"], "Bel" => ["Bel"],
      "how" => ["how", "who"], "Tdo" => ["Tod"], "ery" => ["rye", "yer"],
      "Tao" => ["Tao"], "elz" => ["zel"], "dek" => ["ked"], "Aat" => ["Ata"],
      "Mil" => ["Mil"], "ags" => ["gas", "sag"], "hmo" => ["mho", "ohm"],
      "ikr" => ["irk"], "eis" => ["sie"], "akt" => ["kat"], "Wes" => ["Wes"],
      "egt" => ["get", "teg"], "acg" => ["cag"], "coz" => ["coz"],
      "amr" => ["arm", "mar", "ram"], "inp" => ["nip", "pin"],
      "deg" => ["deg", "ged"], "dgo" => ["dog", "god"], "osv" => ["sov"],
      "Vdo" => ["Vod"], "bek" => ["keb"], "nos" => ["ons", "son"],
      "ers" => ["ers", "ser"], "adp" => ["dap", "pad"], "jow" => ["jow"],
      "koy" => ["yok"], "elv" => ["lev"], "ilm" => ["lim", "mil"], "Rci" => ["Ric"],
      "ess" => ["ess"], "der" => ["erd", "red"], "fip" => ["fip"], "ehw" => ["hew"],
      "amw" => ["maw"], "Amy" => ["Amy"], "bee" => ["bee"], "Raj" => ["Raj"],
      "oot" => ["too"], "Iot" => ["Ito"], "Seu" => ["Sue"], "fit" => ["fit"],
      "aik" => ["kai"], "ans" => ["san"], "apw" => ["paw", "wap"], "dju" => ["jud"],
      "gir" => ["rig"], "gip" => ["gip", "pig"], "ntu" => ["nut", "tun"],
      "abn" => ["ban", "nab"], "aiw" => ["iwa"], "ort" => ["ort", "rot", "tor"],
      "Aht" => ["Aht"], "ddu" => ["dud"], "Ban" => ["Ban"], "cdo" => ["cod", "doc"],
      "Eew" => ["Ewe"], "ahn" => ["han"], "ahh" => ["hah"], "Mev" => ["Mev"],
      "dux" => ["dux"], "amn" => ["man", "nam"], "ajt" => ["taj"], "cry" => ["cry"],
      "Ade" => ["Ade"], "gmu" => ["gum", "mug"], "Sac" => ["Sac"], "Mer" => ["Mer"],
      "Bim" => ["Bim"], "erv" => ["rev"], "aip" => ["pia"], "Lou" => ["Lou", "Luo"],
      "eew" => ["ewe", "wee"], "Ssu" => ["Sus"], "cow" => ["cow"], "Bal" => ["Bal"],
      "ciy" => ["icy"], "ttu" => ["tut"], "Rde" => ["Red"], "Aad" => ["Ada"],
      "Fay" => ["Fay"], "ert" => ["ret"], "bij" => ["jib"], "arw" => ["raw", "war"],
      "div" => ["div"], "Van" => ["Van"], "Low" => ["Lwo"], "Ynu" => ["Yun"],
      "aag" => ["aga"], "Kiu" => ["Kui"], "mnu" => ["mun"], "mop" => ["mop", "pom"],
      "alm" => ["lam", "mal"], "esx" => ["sex"], "eep" => ["pee"], "Jim" => ["Jim"],
      "egp" => ["peg"], "ltu" => ["lut"], "aov" => ["avo", "ova"], "Kau" => ["Kua"],
      "erw" => ["wer"], "Leo" => ["Leo"], "agp" => ["gap"], "Lee" => ["Lee"],
      "amu" => ["aum", "mau"], "Tal" => ["Tal"], "mtu" => ["tum"], "cpu" => ["cup"],
      "Jat" => ["Jat"], "arx" => ["arx", "rax"], "osu" => ["sou"], "Ann" => ["Ann"],
      "Ker" => ["Ker"], "dho" => ["hod"], "opx" => ["pox"], "grr" => ["grr"],
      "bmu" => ["bum"], "amo" => ["mao", "oam"], "ago" => ["ago", "goa"],
      "adm" => ["dam", "mad"], "acn" => ["can"], "msu" => ["sum"], "Aor" => ["Aro"],
      "ces" => ["sec"], "aav" => ["ava"], "Lao" => ["Lao", "Loa"],
      "dey" => ["dey", "dye", "yed"], "Kuy" => ["Kyu"], "Lar" => ["Lar"],
      "gio" => ["gio", "goi"], "ais" => ["sai"], "dgi" => ["dig", "gid"],
      "esw" => ["sew"], "epr" => ["per", "rep"], "lox" => ["lox"], "gow" => ["wog"],
      "Meg" => ["Meg"], "awy" => ["way", "yaw"], "btu" => ["but", "tub"],
      "Jru" => ["Jur"], "hpu" => ["hup", "phu"], "bno" => ["bon", "nob"],
      "dhu" => ["dhu", "hud"], "Kaf" => ["Kaf"], "Jew" => ["Jew"], "oyy" => ["yoy"],
      "aky" => ["kay", "yak"], "gpy" => ["gyp"], "Ree" => ["Ree"],
      "Sis" => ["Sis", "Ssi"], "Stu" => ["Stu"], "acs" => ["sac"], "gty" => ["tyg"],
      "ety" => ["tye", "yet"], "aty" => ["tay", "yat"], "Yin" => ["Yin"],
      "gtu" => ["gut", "tug"], "aos" => ["sao"], "eel" => ["eel", "lee"],
      "Jin" => ["Jin"], "eiv" => ["vei", "vie"], "evx" => ["vex"], "ajm" => ["jam"],
      "aen" => ["ean", "nae", "nea"], "ksy" => ["sky"], "bop" => ["bop", "pob"],
      "hin" => ["hin"], "ahm" => ["ham"], "iop" => ["poi"], "glo" => ["gol", "log"],
      "Wat" => ["Wat"], "aio" => ["iao"], "ejt" => ["jet"], "aef" => ["fae"],
      "Uru" => ["Uru"], "gnu" => ["gnu", "gun"], "ppu" => ["pup"], "hsu" => ["ush"],
      "bgu" => ["bug"], "atv" => ["tav", "vat"], "ahw" => ["haw", "wah", "wha"],
      "nor" => ["nor"], "dou" => ["duo", "udo"], "Jnu" => ["Jun"], "bko" => ["kob"],
      "Ino" => ["Ino"], "apr" => ["par", "rap"], "Tiw" => ["Twi"], "tty" => ["tyt"],
      "Ocs" => ["Osc"], "Mru" => ["Mru"], "fox" => ["fox"],
      "otw" => ["tow", "two", "wot"], "eku" => ["uke"], "inw" => ["win"],
      "Ido" => ["Ido"], "Sno" => ["Son"], "fgi" => ["fig", "gif"], "eyz" => ["yez"],
      "Ods" => ["Ods"], "Tat" => ["Tat"], "abm" => ["bam"],
      "for" => ["for", "fro", "orf"], "Lex" => ["Lex"], "jtu" => ["jut"],
      "Pao" => ["Poa"], "Hnu" => ["Hun"], "cmw" => ["cwm"], "eek" => ["eke"],
      "ass" => ["ass"], "akn" => ["kan", "nak"], "egy" => ["gey"], "Eev" => ["Eve"],
      "Oot" => ["Oto"], "alr" => ["lar"], "bco" => ["cob"], "ekt" => ["ket"],
      "Odl" => ["Old"], "owy" => ["woy", "yow"], "ehy" => ["hey"],
      "fru" => ["fur", "urf"], "bin" => ["bin", "nib"], "cet" => ["tec"],
      "opw" => ["pow", "wop"], "bsu" => ["bus", "sub"], "him" => ["him"],
      "Tab" => ["Tab"], "aiv" => ["iva", "via"], "efl" => ["elf"], "Per" => ["Per"],
      "irw" => ["wir"], "efn" => ["fen", "nef"], "Sir" => ["Sir", "Sri"],
      "err" => ["err"], "ims" => ["ism"], "ace" => ["ace"], "boo" => ["boo"],
      "gpu" => ["gup", "pug"], "adg" => ["dag", "gad"],
      "anw" => ["awn", "naw", "wan"], "Lot" => ["Lot"], "Gee" => ["Gee"],
      "erx" => ["rex"], "agt" => ["gat", "tag"], "Oav" => ["Ova"], "Zan" => ["Zan"],
      "kos" => ["kos", "sok"], "epw" => ["pew"], "guz" => ["guz"]}
    |> Map.get(string_id)
  end
end
