defmodule Jumble.LengthDict.Length3 do
  def get(string_id) do
    %{"fmr" => ["mfr"], "abo" => ["boa"], "hot" => ["hot", "tho"], "aem" => ["mae"],
      "oow" => ["woo"], "ctu" => ["utc", "cut"], "afr" => ["raf", "far"],
      "dgu" => ["dug"], "abd" => ["bad", "dab"], "hip" => ["hip"], "bgi" => ["big"],
      "osy" => ["soy"], "imx" => ["mix"], "ikl" => ["ilk"], "nru" => ["run", "urn"],
      "gmy" => ["gym"], "bde" => ["bed", "deb"], "lot" => ["lot"], "suv" => ["suv"],
      "agj" => ["jag"], "muy" => ["yum"], "ehu" => ["hue"],
      "egn" => ["eng", "gen", "neg"], "civ" => ["vic"], "ehi" => ["hie"],
      "hnt" => ["nth"], "ajy" => ["jay"], "aey" => ["aye", "yea"],
      "eil" => ["eli", "lie", "lei"], "deu" => ["due"], "bil" => ["lib"],
      "ooz" => ["zoo"], "hop" => ["hop"], "nno" => ["non"], "ggi" => ["gig"],
      "npw" => ["pwn"], "ivy" => ["ivy"], "aes" => ["sea"], "mmo" => ["mom"],
      "fnu" => ["fun"], "ewy" => ["yew"], "afn" => ["fan"], "ott" => ["tot"],
      "clt" => ["tlc"], "cgo" => ["cog"], "abl" => ["alb", "lab"],
      "aft" => ["aft", "fat"], "lrs" => ["slr"], "dop" => ["pod"], "imn" => ["min"],
      "csv" => ["cvs"], "sst" => ["sst"], "cox" => ["cox"], "mps" => ["pms"],
      "crt" => ["crt"], "chi" => ["chi"], "flu" => ["flu"], "ops" => ["sop", "ops"],
      "epy" => ["yep"], "tux" => ["tux"], "lnp" => ["lpn"], "auw" => ["uaw"],
      "eit" => ["tie"], "ehr" => ["her"], "ior" => ["rio"],
      "now" => ["now", "own", "won"], "app" => ["app", "pap"], "aad" => ["ada"],
      "acm" => ["mac", "cam"], "ovw" => ["vow"], "gmt" => ["gmt"], "emr" => ["rem"],
      "bfi" => ["fbi", "fib"], "amy" => ["amy", "may", "yam"], "ajn" => ["jan"],
      "atx" => ["tax"], "ikm" => ["kim"], "ept" => ["pet"], "psy" => ["spy"],
      "amt" => ["atm", "amt", "mat", "tam"], "aps" => ["sap", "asp", "pas", "spa"],
      "itt" => ["tit"], "rsy" => ["yrs"], "dmz" => ["dmz"], "aly" => ["lay"],
      "bow" => ["bow"], "cny" => ["nyc"], "ddo" => ["odd"], "akr" => ["ark"],
      "alx" => ["lax"], "iil" => ["lii"], "mpv" => ["mvp"], "ell" => ["ell"],
      "ors" => ["sro"], "dix" => ["dix"], "eny" => ["yen"], "dim" => ["dim", "mid"],
      "beg" => ["beg"], "cno" => ["nco", "con"], "bcn" => ["nbc"], "ajw" => ["jaw"],
      "opp" => ["pop"], "eeg" => ["eeg", "gee"], "lou" => ["lou"],
      "aot" => ["tao", "oat"], "ilx" => ["lix", "lxi"], "est" => ["est", "set"],
      "aet" => ["eta", "ate", "eat", "tea"], "flo" => ["flo"], "cpt" => ["pct"],
      "imo" => ["imo"], "ddh" => ["hdd"], "mru" => ["rum"], "orw" => ["row"],
      "dos" => ["dos", "ods", "sod"], "inn" => ["inn"], "etw" => ["wet"],
      "aqu" => ["qua"], "ill" => ["ill"], "bff" => ["bff"],
      "dei" => ["ide", "ied", "die"], "oty" => ["toy"], "diw" => ["dwi"],
      "hrs" => ["hrs"], "cmu" => ["cum"], "bio" => ["ibo"], "lqs" => ["sql"],
      "fop" => ["fpo", "fop"], "hsv" => ["vhs"], "eeo" => ["eeo"], "ipv" => ["vip"],
      "hor" => ["rho"], "den" => ["ned", "den", "end"], "cit" => ["tic"],
      "aim" => ["mia", "mai", "aim"], "itz" => ["zit"], "ilo" => ["oil"],
      "oss" => ["sos"], "gim" => ["mig"], "fgo" => ["fog"], "emn" => ["men"],
      "bbq" => ["bbq"], "avx" => ["vax"], "eik" => ["ike"], "www" => ["www"],
      "nsu" => ["sun", "usn"], "ilp" => ["lip"], "rty" => ["try"], "abe" => ["abe"],
      "coo" => ["coo"], "oru" => ["our"], "fot" => ["oft"], "orx" => ["xor"],
      "ipt" => ["pit", "tip"], "los" => ["los", "sol"], "nov" => ["nov"],
      "aaf" => ["faa"], "emu" => ["emu"], "iiv" => ["vii"], "ben" => ["ben"],
      "lno" => ["lon"], "mst" => ["mst"], "orr" => ["orr"], "hln" => ["nhl"],
      "enp" => ["pen"], "alw" => ["awl", "law"], "bir" => ["rbi", "rib"],
      "cei" => ["ice"], "ent" => ["net", "ten"], "rsv" => ["rsv", "rvs"],
      "iii" => ["iii"], "mmu" => ["mum"], "eey" => ["eye"], "add" => ["add", "dad"],
      "ccf" => ["cfc", "fcc"], "pry" => ["pry"], "fln" => ["nfl"], "isv" => ["ivs"],
      "ady" => ["day"], "acp" => ["cpa", "pac", "cap"], "ems" => ["ems", "mes"],
      "def" => ["fed"], "blo" => ["lob"], "ary" => ["ray"], "isu" => ["sui"],
      "mow" => ["mow"], "ddt" => ["ddt"], "bet" => ["bet"], "ads" => ["ads", "sad"],
      "ego" => ["geo", "ego"], "eht" => ["the"], "esu" => ["sue", "use"],
      "eop" => ["poe"], "bfo" => ["fob"], "mrs" => ["mrs"], "ahy" => ["hay"],
      "ast" => ["ats", "sat"], "ceh" => ["che"], "kkk" => ["kkk"],
      "abc" => ["abc", "cab"], "eru" => ["rue"], "guy" => ["guy"], "efo" => ["foe"],
      "giu" => ["gui"], "anr" => ["rna", "ran"], "ceo" => ["ceo", "eco"],
      "ipr" => ["rip"], "adw" => ["wad"], "iwz" => ["wiz"], "agr" => ["rag"],
      "fpt" => ["ftp"], "dir" => ["rid"], "efi" => ["fie"], "aor" => ["ora", "oar"],
      "egm" => ["meg", "gem"], "anv" => ["van"], "dis" => ["dis", "ids", "sid"],
      "amx" => ["max"], "del" => ["del", "led"], "hhr" => ["hrh"], "clo" => ["col"],
      "ens" => ["sen"], "htu" => ["hut"], "acl" => ["cal"], "ehp" => ["hep"],
      "gju" => ["jug"], "env" => ["nev"], "agv" => ["avg"], "fms" => ["fms"],
      "aer" => ["era", "rae", "are", "ear"], "bjo" => ["job", "obj"],
      "ilt" => ["lit"], "ffo" => ["off"], "aep" => ["epa", "ape", "pea"],
      "blu" => ["blu"], "aal" => ["ala"], "dry" => ["dry"], "ino" => ["ion"],
      "oww" => ["wow"], "efr" => ["fer", "ref"], "bmo" => ["mob"], "agu" => ["aug"],
      "det" => ["edt", "etd", "ted"], "egg" => ["egg"], "bbi" => ["bib"],
      "boy" => ["boy"], "ilv" => ["lvi"], "act" => ["act", "cat"],
      "dot" => ["dot", "tod"], "afl" => ["fla"], "deo" => ["doe", "ode"],
      "bhu" => ["hub"], "glu" => ["lug"], "stu" => ["stu"], "flv" => ["vlf"],
      "hmz" => ["mhz"], "eno" => ["noe", "eon", "one"], "eip" => ["pei", "pie"],
      "lsy" => ["sly"], "cst" => ["cst"], "eev" => ["eve"], "eps" => ["esp", "sep"],
      "amp" => ["pam", "amp", "map"], "eow" => ["owe", "woe"], "gpp" => ["pgp"],
      "bey" => ["bye"], "hmp" => ["mph"], "moo" => ["moo"], "adt" => ["dat", "tad"],
      "gps" => ["gps"], "bdu" => ["bud", "dub"], "dnu" => ["dun"],
      "cop" => ["cpo", "cop"], "bls" => ["lbs"], "ail" => ["ali", "ila", "ail"],
      "elw" => ["lew"], "mno" => ["mon"], "ekn" => ["ken"],
      "psu" => ["ups", "pus", "sup"], "dor" => ["rod"], "msy" => ["mys"],
      "ant" => ["nat", "ant", "tan"], "ajr" => ["jar"], "ikt" => ["kit"],
      "gjo" => ["jog"], "adv" => ["adv"], "ntt" => ["tnt"], "gkp" => ["pkg"],
      "adl" => ["lad"], "lru" => ["url"], "fiv" => ["ivf"], "cin" => ["inc"],
      "dmo" => ["mod"], "ejo" => ["joe"], "hos" => ["hos", "ohs"],
      "als" => ["asl", "las", "sal"], "cfk" => ["kfc"], "bor" => ["rob", "orb"],
      "ghz" => ["ghz"], "bgo" => ["bog", "gob"], "epp" => ["pep"], "ffs" => ["fsf"],
      "ehm" => ["hem", "meh"], "ixx" => ["xix", "xxi"], "ciu" => ["icu"],
      "bcu" => ["cub"], "cpr" => ["cpr"], "mpu" => ["ump"], "iss" => ["iss", "sis"],
      "gms" => ["msg"], "enw" => ["new", "wen"], "aht" => ["hat"],
      "ist" => ["its", "sit"], "dno" => ["don", "nod"], "alt" => ["alt", "lat"],
      "eho" => ["hoe"], "ams" => ["sam", "mas"], "hsy" => ["shy"],
      "anp" => ["pan", "nap"], "fhu" => ["uhf"], "ahs" => ["ash", "has"],
      "kot" => ["tko"], "osw" => ["sow"], "iou" => ["iou"], "dps" => ["dps"],
      "bru" => ["bur", "rub"], "mtv" => ["mtv"], "ehs" => ["hes", "she"],
      "acr" => ["rca", "arc", "car"], "adh" => ["had"], "etv" => ["vet"],
      "jno" => ["jon"], "cis" => ["sic"], "foo" => ["foo"], "prs" => ["rps"],
      "dip" => ["dip", "dpi"], "ako" => ["oak"], "iww" => ["wwi"],
      "ado" => ["doa", "ado"], "bef" => ["feb"], "esy" => ["yes"],
      "pst" => ["pst", "tsp"], "ehx" => ["hex"], "imr" => ["mri", "mir", "rim"],
      "aev" => ["ave", "eva"], "fhv" => ["vhf"], "cir" => ["irc"], "kuy" => ["yuk"],
      "imt" => ["mit", "tim"], "emw" => ["mew"], "imv" => ["vim"], "aku" => ["auk"],
      "cip" => ["cpi"], "adf" => ["fda", "fad"], "aby" => ["bay"], "aam" => ["ama"],
      "abg" => ["bag", "gab"], "agw" => ["wag"], "bit" => ["bit"], "eqs" => ["esq"],
      "hoo" => ["oho"], "noy" => ["yon"], "bnu" => ["bun", "nub"], "hms" => ["hms"],
      "hhu" => ["huh"], "bcp" => ["pcb"], "cdu" => ["cud"], "apy" => ["pay", "yap"],
      "abr" => ["bar", "bra"], "iix" => ["xii"], "bbe" => ["ebb"],
      "ikn" => ["ink", "kin"], "bgk" => ["kgb"], "dmw" => ["wmd"], "ett" => ["tet"],
      "arv" => ["var"], "eiw" => ["wei"], "aaa" => ["aaa"],
      "ain" => ["ian", "ina", "ani"], "hnu" => ["hun"], "dlo" => ["old"],
      "bim" => ["ibm"], "all" => ["all"], "eet" => ["tee"], "coy" => ["coy"],
      "giw" => ["wig"], "mot" => ["tom"], "eef" => ["fee"], "gru" => ["rug"],
      "dpt" => ["dpt", "dtp"], "fim" => ["imf"], "efz" => ["fez"], "afu" => ["ufa"],
      "bjl" => ["lbj"], "eky" => ["key"], "dds" => ["dds"], "fix" => ["fix"],
      "gin" => ["ing", "gin"], "bmp" => ["bpm"], "ghq" => ["ghq"], "aci" => ["cia"],
      "buy" => ["buy"], "stv" => ["tvs"], "bot" => ["bot"], "dls" => ["lsd"],
      "ipz" => ["zip"], "mpr" => ["rpm"], "bos" => ["sob"], "elo" => ["leo"],
      "fjk" => ["jfk"], "iks" => ["ski"], "acf" => ["afc"], "hmu" => ["hum"],
      "got" => ["got", "tog"], "aeg" => ["age"], "imp" => ["imp"],
      "eor" => ["ore", "roe"], "aar" => ["ara"], "ees" => ["see"], "enz" => ["zen"],
      "ikp" => ["kip"], "adi" => ["ida", "aid"], "his" => ["his"], "eir" => ["ire"],
      "dez" => ["zed"], "dmu" => ["mud"], "ipy" => ["yip"], "bho" => ["hbo", "hob"],
      "gmm" => ["mgm"], "bbo" => ["bob"], "fir" => ["fri", "fir"],
      "iln" => ["lin", "nil"], "doz" => ["doz"], "ijm" => ["jim"], "ost" => ["sot"],
      "agg" => ["gag"], "fiy" => ["fyi"], "isw" => ["wis"], "mor" => ["rom"],
      "puy" => ["yup"], "ael" => ["lea", "ale"], "emo" => ["moe", "emo"],
      "dhp" => ["phd"], "cdi" => ["cid"], "ory" => ["roy"], "cix" => ["xci"],
      "btw" => ["btw"], "dlt" => ["ltd"], "pxy" => ["pyx"], "fly" => ["fly"],
      "goo" => ["goo"], "int" => ["int", "nit", "tin"], "air" => ["ira", "air"],
      "elm" => ["mel", "elm"], "bci" => ["bic"], "cru" => ["cur"], "bmw" => ["bmw"],
      "ios" => ["iso"], "lop" => ["plo", "lop", "pol"], "diu" => ["dui", "iud"],
      "kow" => ["wok"], "ggo" => ["gog"], "etu" => ["ute"], "luv" => ["luv"],
      "dej" => ["jed"], "dfp" => ["pdf"], "ann" => ["ann", "nan"], "iot" => ["ito"],
      "afo" => ["oaf"], "ilz" => ["liz"], "not" => ["not", "ton"], "sty" => ["sty"],
      "dee" => ["dee"], "any" => ["any", "nay"], "gij" => ["jig"], "ely" => ["lye"],
      "ejw" => ["jew"], "adz" => ["adz"], "aop" => ["apo"], "crv" => ["vcr"],
      "luz" => ["luz"], "brr" => ["brr"], "ssu" => ["uss"], "atw" => ["twa"],
      "abj" => ["jab"], "ehn" => ["hen"], "abh" => ["bah"], "cim" => ["mci"],
      "els" => ["esl", "les"], "opr" => ["pro"], "fry" => ["fry"], "ekl" => ["elk"],
      "aks" => ["ask"], "apt" => ["atp", "pta", "pat", "apt", "tap"],
      "cor" => ["orc"], "aex" => ["axe"], "alp" => ["lap", "pal"], "bbs" => ["bbs"],
      "dhi" => ["hid"], "adr" => ["rda"], "npu" => ["pun"],
      "art" => ["art", "rat", "tar"], "cps" => ["pcs"], "asy" => ["say"],
      "ceu" => ["cue"], "ghu" => ["hug", "ugh"], "dfu" => ["fud"], "bew" => ["web"],
      "ips" => ["isp", "pis", "sip"], "osx" => ["sox"], "cot" => ["oct", "cot"],
      "eot" => ["toe"], "egk" => ["ekg", "keg"], "agl" => ["gal", "lag"],
      "dhs" => ["dhs"], "alv" => ["val"], "atz" => ["azt"], "ait" => ["tia"],
      "gmp" => ["mpg"], "aab" => ["baa"], "efy" => ["fey"], "dow" => ["dow"],
      "eln" => ["len"], "hty" => ["thy"], "ptu" => ["put"], "rwy" => ["wry"],
      "lov" => ["vol"], "bst" => ["tbs"], "dpq" => ["pdq"], "emt" => ["emt", "met"],
      "agh" => ["hag"], "asx" => ["sax"], "adn" => ["dna", "dan", "and"],
      "joy" => ["joy"], "aan" => ["ana"], "low" => ["low", "owl"], "isx" => ["six"],
      "fmu" => ["fum"], "elt" => ["let", "tel"], "abt" => ["tba", "bat", "tab"],
      "alo" => ["aol", "lao", "ola"], "cdl" => ["lcd"], "fin" => ["fin"],
      "aew" => ["awe"], "ipp" => ["pip"], "fgm" => ["mfg"], "xxx" => ["xxx"],
      "hwy" => ["hwy", "why"], "ddi" => ["did"], "cee" => ["eec"], "gsu" => ["gus"],
      "opt" => ["opt", "pot", "top"], "itw" => ["wit"], "hit" => ["hit"],
      "bdi" => ["bid"], "agn" => ["nag"], "bpx" => ["pbx"], "ins" => ["ins", "sin"],
      "efw" => ["few"], "irs" => ["irs", "sir"], "bpu" => ["pub"], "agy" => ["gay"],
      "jot" => ["jot"], "afg" => ["fag"], "gov" => ["gov"], "att" => ["tat"],
      "rtu" => ["rut"], "otu" => ["out"], "awx" => ["wax"], "egl" => ["gel", "leg"],
      "fis" => ["ifs"], "acw" => ["wac", "caw"], "asw" => ["saw", "was"],
      "acd" => ["cad"], "fou" => ["ufo"], "ipu" => ["upi"], "aah" => ["aha"],
      "inx" => ["nix"], "dew" => ["wed", "dew"], "eer" => ["ere"], "nnu" => ["nun"],
      "mos" => ["mos"], "egr" => ["ger", "erg"], "dil" => ["lid"], "gho" => ["hog"],
      "afy" => ["fay"], "cft" => ["ftc"], "gst" => ["sgt"], "ouy" => ["you"],
      "din" => ["ind", "din"], "lpy" => ["ply"], "efm" => ["fem"], "hiu" => ["hui"],
      "gil" => ["gil"], "how" => ["who", "how"], "ery" => ["rye"], "ddv" => ["dvd"],
      "ght" => ["hgt"], "ags" => ["gas", "sag"], "hmo" => ["hmo", "ohm"],
      "ikr" => ["irk"], "egt" => ["gte", "get"], "amr" => ["mar", "ram", "arm"],
      "inp" => ["pin", "nip"], "deg" => ["ged"], "dgo" => ["god", "dog"],
      "nos" => ["son", "nos"], "adp" => ["pad"], "ilm" => ["mil"], "afq" => ["faq"],
      "der" => ["red"], "ehw" => ["hew"], "amw" => ["maw"], "bee" => ["bee"],
      "oot" => ["too"], "bds" => ["bsd"], "fit" => ["fit"], "aik" => ["kia"],
      "ans" => ["nsa", "san"], "apw" => ["paw"], "gir" => ["rig"], "cde" => ["dec"],
      "gip" => ["pig"], "ntu" => ["nut", "tun"], "abn" => ["nba", "ban", "nab"],
      "ort" => ["rot", "tor"], "des" => ["eds"], "ddu" => ["dud"],
      "cdo" => ["cod", "doc"], "ahn" => ["han"], "ahh" => ["hah"], "bcs" => ["cbs"],
      "amn" => ["man", "nam"], "cry" => ["cry"], "bbb" => ["bbb"],
      "gmu" => ["gum", "mug"], "hhs" => ["hhs"], "erv" => ["rev"],
      "aip" => ["api", "ipa"], "eew" => ["ewe", "wee"], "cow" => ["cow"],
      "ciy" => ["icy"], "ttu" => ["tut"], "ert" => ["rte"], "bij" => ["jib"],
      "ntw" => ["nwt"], "arw" => ["raw", "war"], "npr" => ["npr"],
      "ivx" => ["xiv", "xvi"], "moq" => ["qom"], "cmo" => ["com"], "mop" => ["mop"],
      "alm" => ["lam"], "jnu" => ["jun"], "esx" => ["xes", "sex"], "eep" => ["pee"],
      "egp" => ["peg"], "cci" => ["icc"], "box" => ["box"], "bbc" => ["bbc"],
      "aov" => ["ova"], "hov" => ["hov"], "gnp" => ["gnp"], "agp" => ["gpa", "gap"],
      "cpu" => ["cpu", "upc", "cup"], "ceg" => ["ecg"], "osu" => ["uso"],
      "dho" => ["hod"], "opx" => ["pox"], "vxx" => ["xxv"], "ahl" => ["hal"],
      "etx" => ["tex"], "dem" => ["dem", "med"], "bmu" => ["bum"], "amo" => ["mao"],
      "ago" => ["goa", "ago"], "dfr" => ["fdr", "rfd"],
      "adm" => ["amd", "dam", "mad"], "acn" => ["can"], "msu" => ["sum"],
      "ces" => ["sec"], "aav" => ["ava"], "dey" => ["dye"], "dtv" => ["vdt"],
      "noo" => ["ono"], "cpv" => ["pvc"], "ais" => ["ais"], "hno" => ["hon", "noh"],
      "dgi" => ["dig"], "hiv" => ["hiv"], "esw" => ["sew"], "epr" => ["rep", "per"],
      "nsv" => ["svn"], "lox" => ["lox"], "lxy" => ["lyx"], "awy" => ["way", "yaw"],
      "btu" => ["btu", "but", "tub"], "dhu" => ["hud", "duh"], "asu" => ["usa"],
      "aky" => ["kay", "yak"], "gpy" => ["gyp"], "acs" => ["sac"], "bps" => ["pbs"],
      "ety" => ["yet"], "gtu" => ["gut", "tug"], "aos" => ["oas"], "dfw" => ["fwd"],
      "eel" => ["lee", "eel"], "eiv" => ["vie"], "evx" => ["vex"],
      "ajm" => ["maj", "jam"], "ksy" => ["sky"], "bop" => ["bop"], "ivz" => ["viz"],
      "ahm" => ["ham"], "iop" => ["ipo", "poi"], "glo" => ["log"], "hkz" => ["khz"],
      "ejt" => ["jet"], "dst" => ["dst", "std"], "cnn" => ["cnn"], "afh" => ["fha"],
      "dik" => ["kid"], "gnu" => ["gnu", "gun"], "ppu" => ["pup"], "hsu" => ["hus"],
      "bgu" => ["bug"], "hst" => ["hst"], "atv" => ["atv", "tva", "vat"],
      "ahw" => ["haw"], "nor" => ["ron", "nor"], "dou" => ["duo"], "cfr" => ["rfc"],
      "apr" => ["apr", "par", "rap"], "fox" => ["fox"],
      "otw" => ["wto", "tow", "two", "wot"], "inw" => ["win"],
      "fgi" => ["gif", "fig"], "abm" => ["abm", "mba"], "for" => ["for", "fro"],
      "jtu" => ["jut"], "eek" => ["eke"], "mpy" => ["pym"], "ass" => ["ssa", "ass"],
      "jlu" => ["jul"], "blt" => ["blt"], "iuz" => ["uzi"], "iiw" => ["wii"],
      "drv" => ["dvr"], "bco" => ["cob"], "owy" => ["wyo"], "ehy" => ["hey"],
      "fru" => ["fur"], "bin" => ["bin", "nib"], "cet" => ["etc"], "opw" => ["pow"],
      "bsu" => ["ubs", "usb", "bus", "sub"], "him" => ["him"], "apz" => ["zap"],
      "aiv" => ["iva", "via"], "efl" => ["efl", "elf"], "eoz" => ["zoe"],
      "efn" => ["fen"], "adj" => ["adj"], "err" => ["err"], "ims" => ["ism", "sim"],
      "ace" => ["ace"], "boo" => ["boo"], "gpu" => ["gpu", "pug"], "adg" => ["gad"],
      "anw" => ["wan"], "afx" => ["fax"], "erx" => ["rex"], "gop" => ["gop"],
      "agt" => ["tag"], "lmx" => ["xml"], "kos" => ["oks"], "epw" => ["pew"]}
    |> Map.get(string_id)
  end
end
