defmodule Jumble.LengthDict.Length4 do
  def get(string_id) do
    %{"arss" => ["sars"], "cder" => ["recd"], "grsu" => ["grus", "rugs"],
      "ekow" => ["woke"], "hstu" => ["huts", "shut", "thus", "tush"],
      "eilw" => ["wile"], "eilm" => ["emil", "lime", "mile"], "ilmy" => ["limy"],
      "hloy" => ["holy"], "iixx" => ["xxii"], "afos" => ["oafs", "sofa"],
      "akln" => ["klan", "lank"], "gimr" => ["grim"], "bbes" => ["ebbs"],
      "intw" => ["twin"], "adkn" => ["dank"], "gnos" => ["song"],
      "eflo" => ["floe"], "aiqr" => ["iraq"], "msty" => ["myst"],
      "aamy" => ["maya"], "celm" => ["clem"], "adip" => ["ipad", "paid"],
      "ilnt" => ["lint"], "aklo" => ["okla"], "eloy" => ["eloy"],
      "arsu" => ["ursa"], "aetz" => ["zeta"], "imps" => ["mips", "imps"],
      "eryy" => ["eyry"], "fiks" => ["fisk"], "dhtu" => ["thud"],
      "deho" => ["hoed"], "dehs" => ["shed"], "blos" => ["lobs", "slob"],
      "aegv" => ["vega", "gave"], "flux" => ["flux"], "eoor" => ["oreo"],
      "aees" => ["ease"], "cdhi" => ["chid"], "irwy" => ["wiry"],
      "enor" => ["nero", "reno"], "afnr" => ["fran"], "besw" => ["webs"],
      "iquz" => ["quiz"], "ilmp" => ["limp"], "ksuy" => ["yuks"],
      "desz" => ["zeds"], "blow" => ["blow", "bowl"],
      "aept" => ["pate", "peat", "tape"], "ceht" => ["etch", "tech"],
      "gstu" => ["gust", "guts", "tugs"], "amnx" => ["manx"], "cefl" => ["clef"],
      "eilt" => ["lite", "tile"], "apps" => ["apps", "paps"], "ikkr" => ["kirk"],
      "ahow" => ["whoa"], "best" => ["best", "bets"], "eikr" => ["erik", "keri"],
      "acin" => ["cain", "inca"], "aesy" => ["ayes", "easy", "yeas"],
      "krsu" => ["rusk"], "acwy" => ["ywca"], "bill" => ["bill"],
      "afir" => ["fair"], "agiz" => ["giza"], "lnxy" => ["lynx"],
      "aeht" => ["thea", "hate", "heat"], "girs" => ["gris", "rigs"],
      "cory" => ["cory"], "ahtu" => ["utah"], "ekls" => ["elks"],
      "achp" => ["caph", "chap"], "eikt" => ["kite", "tike"], "kosw" => ["woks"],
      "agnp" => ["pang"], "elos" => ["leos", "lose", "sloe", "sole"],
      "eert" => ["tree"], "aikn" => ["akin"], "diks" => ["disk", "kids", "skid"],
      "ceir" => ["eric", "rice"], "anst" => ["stan", "ants", "tans"],
      "emos" => ["emos", "some"], "emow" => ["meow"], "agot" => ["goat", "toga"],
      "aggo" => ["agog"], "delp" => ["pled"], "ceor" => ["core"],
      "ahst" => ["hats", "shat"], "clop" => ["clop"], "amos" => ["amos"],
      "amrx" => ["marx"], "cikp" => ["pick"], "iqtu" => ["quit"],
      "bmsu" => ["bums"], "egst" => ["gets"], "iklo" => ["loki", "kilo"],
      "amsy" => ["mays", "yams"], "bior" => ["biro"], "begi" => ["gibe"],
      "aelt" => ["leta", "late", "tale", "teal"],
      "amps" => ["spam", "amps", "maps"], "ehst" => ["seth"], "antw" => ["want"],
      "aitx" => ["taxi"], "impw" => ["wimp"], "eils" => ["isle", "leis", "lies"],
      "ahos" => ["ohsa", "osha"], "ehlp" => ["help"], "deln" => ["lend"],
      "noxy" => ["onyx"], "ghpu" => ["pugh"], "dims" => ["dims"],
      "arsw" => ["wars"], "foor" => ["roof"], "ilot" => ["toil"],
      "aemx" => ["exam"], "eekw" => ["week"], "acdm" => ["dmca"],
      "adhr" => ["hard"], "emrs" => ["rems"], "amss" => ["mass"],
      "afhl" => ["half"], "gmoo" => ["moog"], "adds" => ["adds", "dads"],
      "ehno" => ["hone"], "jluy" => ["july"], "fssu" => ["fuss"],
      "loot" => ["loot", "tool"], "fuzz" => ["fuzz"], "npuy" => ["puny"],
      "deeg" => ["edge", "geed"], "aagz" => ["gaza"], "ackp" => ["pack"],
      "ahtw" => ["thaw", "what"], "beit" => ["bite"], "ddoo" => ["dodo"],
      "aklr" => ["karl", "lark"], "elru" => ["lure", "rule"],
      "ikss" => ["kiss", "skis"], "clru" => ["curl"], "eoru" => ["euro"],
      "ceps" => ["pecs", "spec"], "dnos" => ["dons", "nods"], "elns" => ["lens"],
      "hosw" => ["hows", "show"], "bfos" => ["fobs"], "deem" => ["deem"],
      "arwy" => ["awry", "wary"], "beij" => ["jibe"], "eorw" => ["rowe", "wore"],
      "ahou" => ["oahu"], "htuu" => ["hutu"], "elmw" => ["mewl"],
      "ansy" => ["nays"], "pttu" => ["putt"], "bllu" => ["bull"],
      "akmr" => ["mark"], "chop" => ["chop"], "deik" => ["dike"],
      "hrtu" => ["ruth", "thur", "hurt", "thru"], "aapp" => ["papa"],
      "bboy" => ["byob"], "denw" => ["wend"], "aftw" => ["waft"],
      "gnot" => ["tong"], "aprs" => ["pars", "raps", "rasp", "spar"],
      "cjko" => ["jock"], "djuy" => ["judy"], "aefy" => ["faye"],
      "agsy" => ["gays"], "jlot" => ["jolt"], "dorw" => ["word"],
      "eims" => ["semi"], "agns" => ["sang", "nags", "snag"],
      "elpy" => ["pyle", "yelp"], "hntu" => ["hunt"], "acev" => ["cave"],
      "akno" => ["kano", "koan"], "pstu" => ["puts"], "psst" => ["psst"],
      "eipp" => ["pipe"], "mnow" => ["mown"], "delw" => ["lewd", "weld"],
      "noos" => ["soon"], "fgit" => ["gift"], "mosw" => ["mows"],
      "celt" => ["celt"], "cmsu" => ["usmc", "cums", "scum"], "aepx" => ["apex"],
      "eegr" => ["gere"], "desy" => ["dyes"], "alov" => ["olav", "oval"],
      "anot" => ["nato"], "aalv" => ["alva", "lava"],
      "aehr" => ["hera", "rhea", "hare", "hear"], "bdei" => ["bide"],
      "cdeo" => ["code", "coed"], "aluy" => ["yalu"], "loos" => ["oslo", "solo"],
      "adry" => ["dray", "yard"], "diov" => ["ovid", "void"],
      "ills" => ["ills", "sill"], "akos" => ["oaks", "soak"], "gimn" => ["ming"],
      "efrs" => ["refs", "serf"], "ackm" => ["mack"], "bboo" => ["boob"],
      "dmru" => ["drum"], "aint" => ["nita", "tina", "anti"], "adep" => ["aped"],
      "belo" => ["bole", "lobe"], "deis" => ["dies", "ides", "side"],
      "iklm" => ["milk"], "delo" => ["dole", "lode"], "anss" => ["assn", "sans"],
      "dilw" => ["wild"], "aaip" => ["apia"], "imot" => ["omit"],
      "hist" => ["hits", "shit", "this"], "beuz" => ["zebu"],
      "nort" => ["torn", "tron"], "aeps" => ["apes", "apse", "peas"],
      "ahsy" => ["hays", "ashy"], "orsy" => ["rosy"], "iiix" => ["xiii"],
      "beel" => ["elbe"], "awxy" => ["waxy"], "irst" => ["stir"],
      "ftuz" => ["futz"], "admn" => ["damn"], "cdru" => ["crud", "curd"],
      "mstu" => ["tums", "must", "smut"], "hklu" => ["hulk"], "clow" => ["cowl"],
      "allm" => ["mall"], "cdlo" => ["clod", "cold"], "gouy" => ["yugo"],
      "anuy" => ["yuan"], "eppr" => ["prep"], "abds" => ["dabs"],
      "fnot" => ["font"], "afmo" => ["foam"], "aelu" => ["eula", "laue"],
      "ejoy" => ["joey"], "aceg" => ["cage"], "abde" => ["abed", "bade", "bead"],
      "ehuy" => ["huey"], "bdsu" => ["buds", "dubs"], "entu" => ["tune"],
      "imnt" => ["mint"], "intt" => ["tint"], "elms" => ["elms"],
      "akls" => ["salk"], "biot" => ["obit"], "acht" => ["acth", "chat"],
      "adno" => ["dona"], "bety" => ["byte"], "emmy" => ["emmy"],
      "ablo" => ["bola"], "aegs" => ["sega", "ages", "sage"], "gilt" => ["gilt"],
      "doru" => ["dour"], "ilps" => ["lips", "lisp", "slip"], "eopp" => ["pope"],
      "eept" => ["pete"], "jnou" => ["juno"], "know" => ["know"],
      "fglu" => ["gulf"], "ahht" => ["hath"], "essu" => ["suse", "sues", "uses"],
      "cehm" => ["chem"], "admu" => ["maud"], "elry" => ["lyre", "rely"],
      "gijs" => ["jigs"], "dknu" => ["dunk"], "emop" => ["mope", "poem"],
      "aknt" => ["kant", "tank"], "blru" => ["burl", "blur"],
      "agny" => ["nagy", "yang"], "dkru" => ["kurd"], "istz" => ["zits"],
      "lluu" => ["lulu"], "bgno" => ["bong"], "aikr" => ["kari"],
      "aelm" => ["elam", "elma", "male", "lame", "meal"], "ehmt" => ["them"],
      "ginp" => ["ping"], "egnt" => ["gent"], "aeev" => ["eave"],
      "gopr" => ["gorp"], "enpt" => ["pent"], "cilv" => ["clvi"],
      "agmu" => ["guam"], "hmow" => ["whom"], "mouv" => ["ovum"],
      "achm" => ["mach"], "dikr" => ["dirk"], "lmsu" => ["slum"],
      "dlou" => ["loud"], "eirs" => ["eris", "reis", "rise", "sire"],
      "afiw" => ["waif"], "ilos" => ["lois", "oils", "silo", "soil", "soli"],
      "bjsu" => ["subj"], "cins" => ["incs"], "eegs" => ["gees"],
      "losw" => ["lows", "owls", "slow"], "allu" => ["lula"], "aesw" => ["awes"],
      "aoss" => ["sosa"], "boty" => ["toby"], "ejko" => ["joke"],
      "ehmo" => ["home"], "dinr" => ["rind"], "einv" => ["vein", "vine"],
      "fisu" => ["sufi"], "alru" => ["raul", "ural"], "abch" => ["bach"],
      "ailn" => ["lina", "lain", "nail"], "gotu" => ["gout"], "fort" => ["fort"],
      "dhim" => ["hdmi"], "eilr" => ["riel", "lire", "rile"],
      "cdsu" => ["scud", "cuds"], "ades" => ["sade"], "eorz" => ["zero"],
      "mnor" => ["morn", "norm"], "afgn" => ["fang"], "cksu" => ["suck"],
      "behr" => ["herb"], "prsv" => ["rsvp"], "gips" => ["pigs"],
      "ahss" => ["sash"], "ciru" => ["uric"], "knoo" => ["nook"],
      "aegw" => ["wage"], "ailz" => ["liza"], "ipst" => ["pits", "spit", "tips"],
      "ainr" => ["iran", "nair", "rain"], "assy" => ["says"], "ahwy" => ["ywha"],
      "abin" => ["bani"], "aejn" => ["jane", "jean"], "bhor" => ["bohr"],
      "ainn" => ["nina"], "illp" => ["pill"], "aopt" => ["atop"],
      "fruy" => ["fury"], "aegz" => ["gaze"], "adis" => ["aids", "dais", "said"],
      "aclo" => ["cola", "coal"], "cops" => ["cops"], "delv" => ["veld"],
      "emmo" => ["memo"], "ackw" => ["wack"],
      "acst" => ["acts", "cast", "cats", "scat"], "hipt" => ["pith"],
      "cosy" => ["cosy"], "eooz" => ["ooze"], "afnw" => ["fawn"],
      "arty" => ["arty", "tray"], "acil" => ["cali"], "imsw" => ["swim"],
      "adqu" => ["quad"], "estz" => ["zest"], "agin" => ["agni", "gina", "gain"],
      "aefl" => ["flea", "leaf"], "chku" => ["huck"], "efls" => ["self"],
      "opss" => ["poss", "sops"], "lowy" => ["yowl"], "amot" => ["atom", "moat"],
      "cdtu" => ["duct"], "cikk" => ["kick"], "adrt" => ["dart"],
      "bclo" => ["bloc"], "lnoy" => ["lyon", "only"], "knsu" => ["sunk"],
      "arsv" => ["vars"], "eilu" => ["lieu"], "cmmo" => ["comm"],
      "ttuu" => ["tutu"], "defl" => ["fled"], "koor" => ["rook"],
      "bglo" => ["blog", "glob"], "losv" => ["vols"], "mmos" => ["moms"],
      "anyz" => ["zany"], "dhtv" => ["hdtv"], "aksu" => ["auks"],
      "flou" => ["foul"], "mott" => ["mott"], "egry" => ["grey"],
      "hrru" => ["ruhr"], "bgos" => ["bogs", "gobs"], "ilxx" => ["lxix"],
      "lops" => ["lops", "pols", "slop"], "aehv" => ["have"], "deop" => ["dope"],
      "osst" => ["sots", "toss"], "mosu" => ["sumo"], "bkoo" => ["book"],
      "belu" => ["blue", "lube"], "aerr" => ["rare", "rear"], "gotv" => ["govt"],
      "inow" => ["wino"], "dlop" => ["plod"], "acdr" => ["card"],
      "adsu" => ["usda"], "aemr" => ["erma", "mare", "ream"], "cltu" => ["cult"],
      "acrt" => ["cart"], "djou" => ["judo"], "actv" => ["catv"],
      "mrsu" => ["rums"], "efst" => ["fest"], "efiw" => ["wife"],
      "avwy" => ["wavy"], "astv" => ["vast", "vats"], "aahs" => ["haas"],
      "eikp" => ["pike"], "abfl" => ["flab"], "bhot" => ["both"],
      "ellu" => ["elul"], "cehk" => ["heck"], "ilms" => ["mils", "slim"],
      "bemr" => ["berm"], "acer" => ["acre", "care", "race"], "dfnu" => ["fund"],
      "alsu" => ["saul"], "cfrs" => ["rfcs"],
      "desu" => ["duse", "dues", "sued", "used"], "alor" => ["lora", "oral"],
      "ader" => ["dare", "dear", "read"], "iort" => ["riot", "tiro", "trio"],
      "agst" => ["stag", "tags"], "aehk" => ["hake"], "bdes" => ["debs", "beds"],
      "depu" => ["dupe"], "acgy" => ["cagy"], "oppr" => ["prop"],
      "agoy" => ["goya", "yoga"], "foot" => ["foot"], "denv" => ["vend"],
      "eory" => ["yore"], "agmt" => ["gmat"], "admp" => ["damp"],
      "adst" => ["tads"], "aegr" => ["gear", "rage"], "lsuv" => ["luvs"],
      "civx" => ["xciv", "xcvi"], "lopt" => ["plot"], "ajnu" => ["juan"],
      "cluy" => ["lucy"], "dels" => ["sled"], "adlo" => ["aldo", "load"],
      "egls" => ["gels", "legs"], "aorr" => ["roar"], "aaqu" => ["aqua"],
      "bdgl" => ["bldg"], "eejr" => ["jeer"], "alnt" => ["natl"],
      "gjsu" => ["jugs"], "hlsu" => ["lush"], "dily" => ["idly", "idyl"],
      "eoss" => ["oses"], "adot" => ["toad"], "ahkr" => ["hark"],
      "abrr" => ["barr"], "mpsu" => ["sump", "umps"], "bblu" => ["bulb"],
      "alow" => ["awol"], "amoy" => ["mayo"], "elow" => ["lowe"],
      "boor" => ["boor"], "egis" => ["egis"], "cghu" => ["chug"],
      "bdis" => ["bids"], "ahoy" => ["ahoy"], "fiww" => ["fwiw"],
      "aimu" => ["maui"], "cims" => ["misc"], "dehr" => ["herd"],
      "acow" => ["waco"], "mnoo" => ["moon", "mono"], "amru" => ["amur"],
      "absw" => ["swab"], "aehp" => ["heap"], "rssu" => ["russ", "ussr"],
      "bhoo" => ["hobo"], "apry" => ["pray"], "alpy" => ["play"],
      "ostw" => ["stow", "tows", "twos"], "acel" => ["alec", "lace"],
      "hisw" => ["wish"], "ekrr" => ["kerr"], "imor" => ["miro"],
      "ahrs" => ["rash"], "elmo" => ["elmo", "lome", "mole"],
      "aflo" => ["olaf", "foal", "loaf"], "enox" => ["oxen"], "cehw" => ["chew"],
      "adps" => ["pads"], "begs" => ["begs"], "dgnu" => ["dung"],
      "amst" => ["mast", "mats", "tams"], "cipt" => ["pict"], "dluy" => ["duly"],
      "allt" => ["tall"], "agim" => ["magi"], "eknr" => ["kern"],
      "gitw" => ["twig"], "aims" => ["siam", "aims"], "goot" => ["togo"],
      "cdoy" => ["cody"], "chko" => ["koch", "hock"],
      "aett" => ["etta", "tate", "teat"], "abim" => ["iamb"], "afmr" => ["farm"],
      "ainp" => ["pain"], "jmpu" => ["jump"], "fiij" => ["fiji"],
      "estw" => ["west", "stew", "wets"], "dnop" => ["pond"], "cikl" => ["lick"],
      "eijr" => ["jeri"], "aclr" => ["carl"], "abes" => ["base"],
      "beik" => ["bike"], "asty" => ["stay"], "bcim" => ["icbm"],
      "eovw" => ["wove"], "kmno" => ["monk"], "anvy" => ["navy"],
      "egns" => ["gens"], "bent" => ["bent"], "adns" => ["sand"],
      "hnsu" => ["huns", "shun"], "aben" => ["bean", "bane"], "belt" => ["belt"],
      "hoop" => ["pooh", "hoop"], "clos" => ["cols"], "brsu" => ["burs", "rubs"],
      "dgru" => ["drug"], "ekrt" => ["trek"], "degy" => ["edgy"],
      "dgou" => ["doug"], "artt" => ["tart"], "bjos" => ["jobs"],
      "amny" => ["many", "myna"], "bclu" => ["club"], "ampt" => ["tamp"],
      "deer" => ["reed", "deer"], "epry" => ["prey", "pyre"], "bdii" => ["ibid"],
      "ghhi" => ["high"], "bglt" => ["lgbt"], "ablm" => ["lamb", "balm"],
      "acdh" => ["chad"], "deet" => ["teed"], "abcu" => ["cuba"],
      "ciss" => ["sics"], "egru" => ["grue", "urge"], "acct" => ["acct"],
      "chir" => ["rich"], "fiju" => ["fuji"], "entt" => ["nett", "tent"],
      "kpwy" => ["pkwy"], "adet" => ["date"], "elpt" => ["lept", "pelt"],
      "jost" => ["jots"], "ivxx" => ["xxiv", "xxvi"], "cixx" => ["xcix"],
      "begy" => ["gybe"], "inot" => ["toni", "into"],
      "aert" => ["rate", "tare", "tear"], "girt" => ["girt", "grit", "trig"],
      "ehty" => ["they"], "cein" => ["nice"], "ahpr" => ["harp"],
      "beer" => ["beer"], "eekp" => ["keep", "peek"], "gisw" => ["swig", "wigs"],
      "efos" => ["foes"], "opsy" => ["posy"], "ppsu" => ["pups"],
      "illm" => ["mill"], "apsz" => ["zaps"], "bess" => ["bess"],
      "abot" => ["boat"], "abbr" => ["abbr", "barb"], "bdlv" => ["blvd"],
      "bceu" => ["cebu", "cube"], "aagr" => ["agra", "agar", "raga"],
      "cgos" => ["cogs"], "dees" => ["seed"], "npsw" => ["pwns"],
      "hort" => ["roth", "thor"], "dhos" => ["hods", "shod"], "ahno" => ["noah"],
      "hhsu" => ["hush"], "eeir" => ["eire", "erie"], "cllu" => ["cull"],
      "deov" => ["dove"], "josy" => ["joys"], "aggs" => ["gags"],
      "emrt" => ["term"], "cpsu" => ["cups", "cusp"], "aflt" => ["flat"],
      "aesv" => ["save", "vase"], "been" => ["eben", "been"], "dimn" => ["mind"],
      "aagl" => ["alga", "gala"], "adhs" => ["dash", "shad"], "hins" => ["shin"],
      "hkoo" => ["hook"], "hmot" => ["moth"], "agln" => ["lang"],
      "cell" => ["cell"], "aeft" => ["fate", "feat", "feta"], "hmos" => ["ohms"],
      "abem" => ["beam"], "frtu" => ["turf"], "loop" => ["polo", "loop", "pool"],
      "iors" => ["rios"], "eemr" => ["mere"], "acip" => ["pica"],
      "aijn" => ["jain"], "anps" => ["naps", "pans", "snap", "span"],
      "eost" => ["toes"], "adsy" => ["days"], "ekoy" => ["yoke"],
      "ghis" => ["gish", "sigh"], "istw" => ["wist", "wits"], "aclt" => ["talc"],
      "iknw" => ["wink"], "delm" => ["meld"], "cnot" => ["cont"],
      "abdu" => ["baud", "daub"], "cetu" => ["cute"], "bcir" => ["crib"],
      "aluu" => ["luau"], "nost" => ["snot", "tons"], "bdoy" => ["boyd", "body"],
      "kooy" => ["yoko"], "efnr" => ["fern", "nerf"], "aakm" => ["kama"],
      "achn" => ["chan"], "glpu" => ["gulp", "plug"], "eilp" => ["pile"],
      "acpr" => ["parc", "carp", "crap"], "beil" => ["bile"], "ckuy" => ["yuck"],
      "ikmn" => ["mink"], "ensv" => ["sven"], "delu" => ["duel"],
      "iruy" => ["yuri"], "aejm" => ["jame"], "ghnu" => ["hung"],
      "dhot" => ["doth"], "knpu" => ["punk"], "bbew" => ["webb"],
      "inuz" => ["zuni"], "dlmo" => ["mold"], "ainu" => ["ainu"],
      "drsy" => ["drys"], "agps" => ["gaps", "gasp"], "diqu" => ["quid"],
      "afly" => ["flay"], "bikl" => ["bilk"], "deos" => ["does", "dose", "odes"],
      "eluy" => ["yule"], "dllu" => ["dull"], "agmy" => ["gamy"],
      "mpru" => ["rump"], "errs" => ["errs"], "acds" => ["cads", "scad"],
      "aels" => ["elsa", "lesa", "ales", "lase", "leas", "sale", "seal"],
      "esuz" => ["suez", "zeus"], "oprs" => ["pros"], "opsu" => ["opus", "soup"],
      "film" => ["film", "milf"], "cior" => ["rico"], "bmnu" => ["numb"],
      "osux" => ["oxus"], "einz" => ["inez"], "ggor" => ["grog"],
      "kmos" => ["omsk"], "enno" => ["neon", "none"], "deku" => ["duke"],
      "gost" => ["togs"], "hlot" => ["holt", "loth"],
      "nosw" => ["snow", "owns", "sown"], "apsw" => ["wasp", "paws", "swap"],
      "alos" => ["laos", "also"], "cekp" => ["peck"], "ejkr" => ["jerk"],
      "aill" => ["lila"], "beht" => ["beth"], "cikm" => ["mick"],
      "flot" => ["loft"], "adft" => ["daft"], "nnoo" => ["noon"],
      "celx" => ["excl"], "aosy" => ["soya"], "acrs" => ["arcs", "cars", "scar"],
      "dssu" => ["suds"], "alst" => ["salt", "alts", "last", "lats", "slat"],
      "adez" => ["adze", "daze"], "ckop" => ["pock"], "bttu" => ["butt"],
      "aipt" => ["pita"], "enov" => ["oven"], "emno" => ["nome", "omen"],
      "llop" => ["poll"], "eflw" => ["flew"], "eelp" => ["peel", "pele"],
      "bdeo" => ["bode"], "agjs" => ["jags"], "gioy" => ["yogi"],
      "anox" => ["axon"], "bdet" => ["debt"], "ejss" => ["jess"],
      "efry" => ["frey", "frye"], "imss" => ["miss", "sims", "isms"],
      "efir" => ["fire", "rife"], "ikll" => ["kill"], "lllu" => ["lull"],
      "airz" => ["ariz"], "eemm" => ["meme"], "hips" => ["hips", "ship"],
      "bgsu" => ["bugs"], "acim" => ["mica"], "ajsw" => ["jaws"],
      "ailv" => ["vila", "vial"], "adgo" => ["goad"], "aelz" => ["laze", "zeal"],
      "eekn" => ["keen", "knee"], "aekw" => ["wake", "weak"], "hilt" => ["hilt"],
      "aekl" => ["kale", "lake", "leak"], "ahkn" => ["hank", "khan", "ankh"],
      "ahlu" => ["haul", "hula"], "deno" => ["deon", "done", "node"],
      "ansu" => ["anus"], "egpr" => ["grep"], "bimr" => ["brim"],
      "afry" => ["fray"], "ejst" => ["jest", "jets"], "aapr" => ["paar"],
      "stxy" => ["styx"], "bmoo" => ["boom"], "acft" => ["fact"],
      "adoy" => ["yoda"], "hiks" => ["sikh"], "alwy" => ["yawl"],
      "ddei" => ["died"], "abku" => ["baku"], "dnnu" => ["dunn"],
      "aehz" => ["haze"], "dopy" => ["dopy"], "acek" => ["cake"],
      "hnor" => ["horn"], "mmsu" => ["mums"], "aacn" => ["ncaa"],
      "aamm" => ["mama"], "agss" => ["sags"], "bklu" => ["bulk"],
      "nopr" => ["porn", "pron"], "kopy" => ["poky"], "eepv" => ["veep"],
      "alsv" => ["slav"], "gkno" => ["kong", "gonk"], "ceop" => ["opec", "cope"],
      "biis" => ["ibis"], "ahpt" => ["ptah", "path"], "dirt" => ["dirt"],
      "beef" => ["beef"], "anov" => ["avon", "nova"], "llpu" => ["pull"],
      "eghu" => ["huge"], "afil" => ["fail"], "dlot" => ["dolt", "told"],
      "bder" => ["bred"], "abcs" => ["abcs", "cabs", "scab"],
      "abel" => ["abel", "bela", "elba", "able", "bale"],
      "aghs" => ["gash", "hags", "shag"], "lnny" => ["lynn"], "lpsu" => ["plus"],
      "betu" => ["tube"], "lott" => ["lott"], "vxxx" => ["xxxv"],
      "jstu" => ["just", "juts"], "bnor" => ["born", "brno"], "chik" => ["hick"],
      "osvw" => ["vows"], "eios" => ["oise"], "bdmu" => ["dumb"],
      "bdry" => ["byrd"], "aehy" => ["yeah"], "alot" => ["alto"],
      "abdn" => ["band"], "eehp" => ["heep"], "frsu" => ["furs", "surf"],
      "aekm" => ["make"], "ikps" => ["skip"], "eeks" => ["ekes", "seek"],
      "ostu" => ["oust", "outs"], "egor" => ["gore", "roeg", "ergo", "ogre"],
      "anno" => ["nona", "anon"], "eorv" => ["rove", "over"], "deey" => ["eyed"],
      "ahmr" => ["harm"], "afnu" => ["faun"], "iknt" => ["knit"],
      "ehlo" => ["hole"], "defr" => ["fred"], "ikkn" => ["kink"],
      "notw" => ["town", "wont"], "ertu" => ["true"],
      "abst" => ["bast", "bats", "stab", "tabs"], "astt" => ["stat", "tats"],
      "dhis" => ["dish"], "aeim" => ["amie"], "ffit" => ["tiff"],
      "belw" => ["blew"], "adln" => ["land"], "acde" => ["aced"],
      "ally" => ["ally"], "bilm" => ["limb"], "bcek" => ["beck"],
      "bops" => ["bops"], "imru" => ["muir"], "gsuy" => ["guys"],
      "bdee" => ["bede"], "abkn" => ["bank"], "benz" => ["benz"],
      "lrsu" => ["urls", "slur"], "eflt" => ["left", "felt"], "flop" => ["flop"],
      "oruy" => ["your"], "mooz" => ["zoom"],
      "eimt" => ["emit", "item", "mite", "time"], "ffos" => ["offs"],
      "eels" => ["eels", "else", "lees"], "nrtu" => ["runt", "turn"],
      "prsu" => ["spur"], "intu" => ["unit"], "oort" => ["oort", "root"],
      "hmoy" => ["homy"], "llmo" => ["moll"], "glsu" => ["lugs", "slug"],
      "dnow" => ["down"], "dfor" => ["ford"], "dioz" => ["izod"],
      "npsu" => ["puns", "spun"], "ehiv" => ["hive"], "acmy" => ["macy", "ymca"],
      "almo" => ["loam"], "fizz" => ["fizz"], "agnt" => ["gnat", "tang"],
      "anor" => ["arno", "aron", "nora", "oran", "roan"], "deij" => ["jedi"],
      "ortu" => ["rout", "tour"], "ahit" => ["thai"], "coop" => ["coop"],
      "ains" => ["ansi", "sian"], "amsx" => ["xmas"], "afst" => ["fast", "fats"],
      "dity" => ["tidy"], "ciix" => ["xcii"],
      "aest" => ["east", "eats", "sate", "seat", "teas"], "afkl" => ["flak"],
      "ehpy" => ["hype"], "cdek" => ["deck"], "beno" => ["bone"],
      "acry" => ["cary", "cray", "racy"], "eswy" => ["yews"],
      "dstu" => ["dust", "stud"], "ehsu" => ["hues"], "ekmp" => ["kemp"],
      "ostt" => ["tost", "tots"], "aijl" => ["jail"], "joot" => ["tojo"],
      "hikt" => ["kith"], "acks" => ["cask", "sack"], "emov" => ["move"],
      "gist" => ["gist"], "ikno" => ["ikon", "oink"], "mppu" => ["pump"],
      "berv" => ["verb"], "iiss" => ["isis"], "derw" => ["drew"],
      "hmty" => ["myth"], "abms" => ["abms"], "elmu" => ["mule"],
      "ffru" => ["ruff"], "eeps" => ["pees", "seep"], "celw" => ["clew"],
      "cssu" => ["cuss"], "illr" => ["rill"], "eenv" => ["even"],
      "iiiv" => ["viii"], "cloy" => ["cloy"], "ikns" => ["inks", "sink", "skin"],
      "ajms" => ["jams"], "amor" => ["omar", "roam"], "hjos" => ["josh"],
      "ajsy" => ["jays"], "msuw" => ["swum"], "aksy" => ["yaks"],
      "irtw" => ["writ"], "aces" => ["case", "aces"], "bilo" => ["boil"],
      "aadd" => ["dada"], "afln" => ["flan"], "aabh" => ["ahab"],
      "agls" => ["gals", "lags", "slag"], "ceiv" => ["vice"], "bgir" => ["brig"],
      "iost" => ["otis"], "kstu" => ["tusk"], "elnt" => ["lent"],
      "ahkw" => ["hawk"], "chmu" => ["chum", "much"], "eins" => ["ines", "sine"],
      "cnor" => ["corn"], "deef" => ["feed"], "ghno" => ["hong"],
      "bchs" => ["hsbc"], "aipr" => ["pair"], "eesy" => ["eyes"],
      "bbis" => ["bibs"], "ahtt" => ["that"], "elor" => ["lore", "role"],
      "aefr" => ["fare", "fear"], "eirw" => ["weir", "wire"], "dloz" => ["lodz"],
      "ensy" => ["yens"], "nstu" => ["nuts", "stun", "tuns"], "bosy" => ["boys"],
      "aefs" => ["safe"], "bden" => ["bend"], "beep" => ["beep"],
      "deks" => ["desk"], "ddde" => ["dded"], "deep" => ["deep", "peed"],
      "agmr" => ["gram"], "fgis" => ["figs"], "ddot" => ["todd"],
      "bffi" => ["biff"], "ehll" => ["hell"], "fiiw" => ["wifi"],
      "adgr" => ["drag", "grad"], "alpu" => ["paul"], "ablt" => ["blat"],
      "envy" => ["envy"], "acem" => ["mace", "acme", "came"],
      "elop" => ["opel", "pole", "lope"],
      "abet" => ["abet", "bate", "beat", "beta"], "nrsu" => ["runs", "urns"],
      "bouy" => ["buoy"], "amux" => ["axum"], "aloz" => ["zola"],
      "allp" => ["pall"], "antu" => ["aunt", "tuna"], "acox" => ["coax"],
      "blst" => ["blts"], "bnoy" => ["bony"], "aadn" => ["adan", "dana"],
      "dfoo" => ["food"], "aent" => ["etna", "nate", "ante", "neat"],
      "aclw" => ["claw"], "eery" => ["eyre", "eery"], "ccko" => ["cock"],
      "beru" => ["rube"], "eotv" => ["veto", "vote"], "afgl" => ["flag"],
      "aimr" => ["irma", "mari", "mira", "amir"], "beix" => ["ibex"],
      "lost" => ["stol", "lost", "lots", "slot"], "eens" => ["seen"],
      "enot" => ["eton", "note", "tone"], "ahms" => ["hams", "mash", "sham"],
      "elpr" => ["perl"], "ijno" => ["joni", "join"], "abit" => ["bait"],
      "aals" => ["alas"], "aais" => ["asia"], "admr" => ["dram"],
      "eott" => ["tote"], "door" => ["door", "odor", "rood"], "adiu" => ["audi"],
      "esvy" => ["yves"], "hiss" => ["hiss"], "ceov" => ["cove"],
      "fpst" => ["ftps"], "ceot" => ["cote"], "abil" => ["bali", "bail"],
      "alms" => ["alms", "lams", "slam"], "dhoo" => ["hood"],
      "emor" => ["more", "rome"], "bhsu" => ["bush", "hubs"], "ablw" => ["bawl"],
      "biko" => ["biko"], "coyz" => ["cozy"], "ensz" => ["zens"],
      "adpv" => ["avdp"], "gmsy" => ["gyms"], "mttu" => ["mutt"],
      "lory" => ["orly"], "bflu" => ["flub"], "aklw" => ["walk"],
      "enrv" => ["vern"], "bblo" => ["blob"], "illw" => ["will"],
      "nnwy" => ["wynn"], "inpt" => ["pint"], "eltu" => ["lute"],
      "eerw" => ["ewer", "weer", "were"], "ejlo" => ["joel"], "hmny" => ["hymn"],
      "ahls" => ["hals", "lash"], "ekpu" => ["puke"], "ilvy" => ["livy"],
      "ails" => ["lisa", "ails", "sail"], "adho" => ["doha"], "acrz" => ["czar"],
      "aemt" => ["mate", "meat", "meta", "tame", "team"],
      "inor" => ["orin", "iron"], "fost" => ["soft"], "aelx" => ["alex", "axle"],
      "aegp" => ["page", "gape"], "aehl" => ["hale", "leah", "heal"],
      "aegn" => ["gena"], "adiw" => ["wadi"], "inoz" => ["zion"],
      "arst" => ["arts", "rats", "star", "tars", "tsar"], "amrw" => ["warm"],
      "bssu" => ["buss", "subs"], "cktu" => ["tuck"], "egps" => ["pegs"],
      "hiop" => ["hopi"], "hipw" => ["whip"], "aesu" => ["esau"],
      "dery" => ["dyer"], "lltu" => ["tull"], "bdlo" => ["bold"],
      "cilx" => ["clix", "clxi"], "boot" => ["boot"], "acsw" => ["caws"],
      "eejp" => ["jeep"], "alsw" => ["awls", "laws", "slaw"],
      "dikn" => ["dink", "kind"], "irsu" => ["uris"], "aimn" => ["mani", "main"],
      "dgoy" => ["dogy"], "abjm" => ["jamb"],
      "aerv" => ["reva", "vera", "aver", "rave"], "aovw" => ["avow"],
      "eptw" => ["wept"], "aden" => ["aden", "dane", "dean", "dena", "edna"],
      "cstu" => ["cuts"], "deft" => ["deft"], "ampv" => ["vamp"],
      "aiot" => ["iota"], "acms" => ["cams", "masc", "scam"], "aops" => ["soap"],
      "acot" => ["cato", "coat", "taco"], "dill" => ["dill"],
      "fglo" => ["flog", "golf"], "bnoo" => ["bono", "boon"], "ilwy" => ["wily"],
      "abht" => ["bath"], "elly" => ["lyle", "yell"], "ipsy" => ["yips"],
      "ddju" => ["judd"], "cosw" => ["cows", "scow"], "ikms" => ["skim"],
      "elss" => ["less"], "llyy" => ["lyly"], "eggo" => ["eggo"],
      "beiv" => ["vibe"], "cdei" => ["dice", "iced"], "gknu" => ["gunk"],
      "lnor" => ["lorn"], "defu" => ["feud"], "iiww" => ["wwii"],
      "bgor" => ["borg"], "firs" => ["firs"], "adeg" => ["aged"],
      "klwy" => ["wkly"], "eisw" => ["wise"], "copy" => ["copy"],
      "ciks" => ["sick"], "noot" => ["onto"],
      "eiln" => ["neil", "nile", "lien", "line"], "aarz" => ["zara"],
      "aenp" => ["pena", "nape", "pane"], "abmu" => ["baum"], "addo" => ["dado"],
      "hnos" => ["nosh"], "efns" => ["fens"], "emtu" => ["mute"],
      "ennp" => ["penn"], "fins" => ["fins"], "abhl" => ["blah"],
      "aags" => ["saga"], "arsy" => ["rays"], "bdno" => ["bond"],
      "cesy" => ["secy"], "nptu" => ["punt"], "inos" => ["ions"],
      "ffgu" => ["guff"], "aaeg" => ["gaea"], "ehns" => ["hens"],
      "epps" => ["peps"], "alsy" => ["lays", "slay"],
      "ailr" => ["lair", "liar", "lira", "rail"], "bdss" => ["bsds"],
      "gilr" => ["girl"], "esty" => ["stye", "yest"], "dmor" => ["dorm"],
      "dehy" => ["hyde"], "aenr" => ["erna", "rena", "earn", "near"],
      "noty" => ["tony"], "aegm" => ["game"], "alss" => ["lass"],
      "dips" => ["dips"], "efil" => ["leif", "file", "lief", "life"],
      "kloo" => ["look"], "bnos" => ["snob"], "eltw" => ["welt"],
      "emst" => ["stem"], "hopy" => ["hypo"], "eglt" => ["gelt"],
      "deil" => ["deli", "idle", "lied"], "beir" => ["brie", "bier"],
      "aehm" => ["ahem"], "adeh" => ["head"], "kkoo" => ["kook"],
      "aadi" => ["aida"], "ghin" => ["hing", "nigh"], "aflp" => ["flap"],
      "iott" => ["tito"], "ceex" => ["exec"], "aort" => ["taro"],
      "eegl" => ["glee"], "iikw" => ["kiwi", "wiki"],
      "deor" => ["oder", "doer", "redo", "rode"], "eekr" => ["reek"],
      "epsy" => ["espy", "yeps"], "egms" => ["gems", "megs"], "dost" => ["dots"],
      "lopy" => ["ploy"], "ahlt" => ["halt", "lath"], "essw" => ["sews"],
      "aabl" => ["alba", "baal"], "chit" => ["chit", "itch"], "ceit" => ["cite"],
      "enos" => ["enos", "eons", "noes", "nose", "ones"],
      "asst" => ["tass", "asst"], "cikn" => ["nick"], "gipr" => ["grip", "prig"],
      "ijll" => ["jill"], "alry" => ["lyra"], "acky" => ["yack"],
      "ijnx" => ["jinx"], "abgr" => ["brag", "garb", "grab"],
      "adil" => ["dali", "dial", "laid"], "beko" => ["kobe"], "dell" => ["dell"],
      "ehor" => ["hero"], "adnr" => ["rand", "darn"], "aegu" => ["ague"],
      "dory" => ["dory"], "ilmo" => ["milo", "limo"], "affg" => ["gaff"],
      "glos" => ["logs", "slog"], "agrs" => ["rags"],
      "cloo" => ["colo", "cool", "loco"],
      "aelp" => ["leap", "pale", "peal", "plea"], "agll" => ["gall"],
      "cdko" => ["dock"], "dffu" => ["duff"], "eftw" => ["weft"],
      "dehu" => ["hued"], "lllo" => ["loll"], "dnsu" => ["duns"],
      "ckoy" => ["yock"], "chin" => ["chin", "inch"], "imtt" => ["mitt"],
      "notu" => ["unto"], "ipqu" => ["quip"], "eefr" => ["free", "reef"],
      "aalt" => ["alta"], "corw" => ["crow"], "amnn" => ["mann"],
      "cefh" => ["chef"], "ipty" => ["pity"], "dtuy" => ["duty"],
      "hlow" => ["howl"], "dijo" => ["jodi"], "efiv" => ["five"],
      "lmot" => ["molt"], "iptt" => ["pitt"], "acor" => ["cora"],
      "moor" => ["moor", "moro", "room"], "eepw" => ["weep"], "hklo" => ["kohl"],
      "egks" => ["kegs"], "iltt" => ["tilt"], "agnw" => ["wang", "gnaw"],
      "akpr" => ["park"], "aekr" => ["rake"], "bnru" => ["burn"],
      "aajn" => ["jana"], "esst" => ["tess", "sets"], "opru" => ["pour"],
      "iptu" => ["tupi"], "cjno" => ["conj"], "abdr" => ["brad", "bard", "drab"],
      "inns" => ["inns"], "defn" => ["fend"], "ahmy" => ["ymha"],
      "oopr" => ["poor"], "elvy" => ["levy"], "acnt" => ["cant"],
      "ehmp" => ["hemp"], "irss" => ["sirs"], "aflw" => ["flaw"],
      "bcku" => ["buck"], "hims" => ["hims", "shim"], "ffpu" => ["puff"],
      "ipsw" => ["wisp"], "fist" => ["fist", "fits", "sift"], "aflx" => ["flax"],
      "beeh" => ["hebe"], "aadm" => ["adam"], "ehms" => ["hems", "mesh"],
      "ggis" => ["gigs"], "ammo" => ["ammo"], "ados" => ["soda"],
      "aprw" => ["warp", "wrap"], "fosu" => ["ufos"], "ghhu" => ["hugh"],
      "aovz" => ["azov"], "eerv" => ["ever", "veer"], "mops" => ["mops"],
      "bgoy" => ["bogy"], "gjos" => ["jogs"], "horu" => ["hour"],
      "aawy" => ["away"], "ckmo" => ["mock"], "orss" => ["ross"],
      "abbl" => ["blab"], "ddee" => ["deed"], "acmr" => ["marc", "cram"],
      "aefm" => ["fame"], "floo" => ["fool"],
      "enop" => ["nope", "open", "peon", "pone"], "aenn" => ["anne"],
      "filo" => ["foil"], "ahot" => ["oath"], "aems" => ["mesa", "same", "seam"],
      "afns" => ["fans"], "acrr" => ["carr"], "egjp" => ["jpeg"],
      "hllu" => ["hull"], "acdl" => ["clad"], "bers" => ["serb"],
      "efsu" => ["fuse"], "eitx" => ["exit"], "efmu" => ["fume"],
      "egiv" => ["give"], "ailp" => ["pail"], "bert" => ["bert", "bret"],
      "egln" => ["glen"], "eesv" => ["eves"], "beos" => ["bose"],
      "egnw" => ["gwen"], "adlw" => ["wald"], "hknu" => ["kuhn", "hunk"],
      "eegn" => ["gene"], "abks" => ["bask"], "fhoo" => ["hoof"],
      "demn" => ["mend"], "opps" => ["pops"], "acss" => ["sacs"],
      "hpsu" => ["push"], "imsu" => ["imus"], "ailw" => ["wail"],
      "amtt" => ["matt"], "dein" => ["enid", "dine"], "ehtw" => ["whet"],
      "aalr" => ["alar", "aral", "lara"], "eisv" => ["ives", "vies", "vise"],
      "aclu" => ["aclu", "ucla"], "aann" => ["anna"], "fops" => ["fops"],
      "aclm" => ["calm", "clam"], "eirt" => ["teri", "rite", "tier", "tire"],
      "eegz" => ["geez"], "erty" => ["trey", "tyre"], "inss" => ["sins"],
      "aquy" => ["quay"], "ampr" => ["pram", "ramp"], "dfin" => ["find"],
      "aeky" => ["kaye"], "ittw" => ["witt", "twit"], "korw" => ["work"],
      "aacr" => ["cara"], "eegk" => ["geek"], "fimr" => ["firm"],
      "deeh" => ["heed"], "host" => ["host", "shot"], "cest" => ["sect"],
      "prtu" => ["prut"], "orsu" => ["ours", "sour"], "eflu" => ["flue", "fuel"],
      "acdo" => ["coda"], "agir" => ["riga"], "eetw" => ["twee"],
      "hmpu" => ["hump"], "osty" => ["toys"], "acnr" => ["narc"],
      "eklp" => ["kelp"], "aens" => ["sean", "sane"],
      "abtu" => ["batu", "abut", "tabu", "tuba"], "aips" => ["pisa"],
      "ahsw" => ["shaw", "wash", "haws"], "iklt" => ["kilt"],
      "deot" => ["dote", "toed"], "elmt" => ["melt"], "jruy" => ["jury"],
      "chow" => ["chow"], "dhin" => ["hind"], "abrs" => ["bars", "bras"],
      "aswy" => ["sway", "ways", "yaws"], "boss" => ["boss", "sobs"],
      "iimn" => ["mini"], "agio" => ["iago"], "ehik" => ["hike"],
      "akor" => ["karo", "okra"], "koot" => ["took"], "acly" => ["clay", "lacy"],
      "lnoo" => ["loon"], "entx" => ["next"], "aaru" => ["aura"],
      "ceip" => ["epic"], "abek" => ["bake", "beak"], "stty" => ["ttys"],
      "nnou" => ["noun"], "bijs" => ["jibs"], "aevw" => ["wave"],
      "attw" => ["watt"], "astw" => ["swat", "wats"], "cklo" => ["lock"],
      "eist" => ["site", "ties"], "norz" => ["zorn"],
      "gory" => ["gory", "gyro", "orgy"],
      "eors" => ["eros", "rose", "ores", "roes", "sore"], "bgil" => ["glib"],
      "bsuy" => ["busy", "buys"], "efin" => ["enif", "fine"], "iimm" => ["mimi"],
      "agil" => ["gail", "gila"], "gint" => ["ting"], "aery" => ["aery", "year"],
      "bcsu" => ["cubs"], "hill" => ["hill"], "acmp" => ["camp"],
      "ckmu" => ["muck"], "allw" => ["wall"], "adny" => ["andy"],
      "cekk" => ["keck"], "elov" => ["love", "vole"], "eops" => ["peso", "pose"],
      "eelr" => ["leer", "reel"], "ejsw" => ["jews"], "eent" => ["teen"],
      "egrw" => ["grew"], "bknu" => ["bunk"], "ackl" => ["calk", "lack"],
      "copr" => ["corp", "crop"], "crsu" => ["curs"], "eekz" => ["zeke"],
      "aell" => ["ella", "lela"], "egin" => ["inge"], "errt" => ["terr"],
      "kopr" => ["pork"], "attu" => ["taut"], "atty" => ["atty"],
      "bcos" => ["cobs"], "cemo" => ["come"], "afqs" => ["faqs"],
      "bbos" => ["bobs"], "hiwz" => ["whiz"], "cgno" => ["cong"],
      "illy" => ["lily"], "afmn" => ["fnma"], "bgnu" => ["bung"],
      "cffu" => ["cuff"], "dkor" => ["dork"], "copu" => ["coup"],
      "nosu" => ["nous", "onus"], "efrx" => ["xref"], "aejp" => ["jape"],
      "bstu" => ["bust", "buts", "stub", "tubs"], "oopp" => ["poop"],
      "birs" => ["ribs"], "ehlm" => ["helm"], "aajr" => ["ajar", "raja"],
      "alpp" => ["lapp"], "imnn" => ["minn"], "gmnu" => ["mung"],
      "aitw" => ["wait"], "ajrs" => ["jars"],
      "adel" => ["dale", "leda", "deal", "lade", "lead"],
      "abkl" => ["kalb", "balk"], "bllo" => ["boll"], "ipxy" => ["pixy"],
      "eikv" => ["kiev"], "krtu" => ["kurt", "turk"], "aerw" => ["ware", "wear"],
      "opst" => ["post", "opts", "pots", "spot", "stop", "tops"],
      "akmo" => ["amok"], "acfi" => ["fica"], "ilsu" => ["luis"],
      "ehow" => ["howe"], "abis" => ["bias"], "ensw" => ["news", "sewn", "wens"],
      "afsu" => ["usaf"], "ggio" => ["gigo"], "oosw" => ["woos"],
      "llnu" => ["null"], "answ" => ["sawn", "swan"], "llor" => ["roll"],
      "deit" => ["tide", "diet", "edit", "tied"], "aart" => ["tara"],
      "eimn" => ["mien", "mine"], "dksu" => ["dusk"], "ssuw" => ["wuss"],
      "amns" => ["mans"], "iirs" => ["iris"], "dent" => ["dent", "tend"],
      "iknr" => ["rink"], "gruu" => ["guru"], "cors" => ["orcs"],
      "ixxx" => ["xxix", "xxxi"], "cefr" => ["cerf"],
      "cilo" => ["clio", "coil", "loci"], "ghsu" => ["gush", "hugs"],
      "opuz" => ["puzo"], "ahyz" => ["hazy"], "degi" => ["gide"],
      "dmpu" => ["dump"], "ilov" => ["viol"], "abeu" => ["beau"],
      "firt" => ["rift"], "bmot" => ["tomb"], "bekr" => ["kerb"],
      "denp" => ["pend"], "apst" => ["past", "pats", "spat", "taps"],
      "noss" => ["sons"], "benr" => ["bern"], "deiw" => ["wide"],
      "cdis" => ["disc"], "ahlo" => ["halo"], "ejll" => ["jell"],
      "deju" => ["jude"], "eips" => ["pies"], "impr" => ["prim"],
      "gluy" => ["ugly"], "flru" => ["furl"], "orsw" => ["rows"],
      "afgr" => ["frag"], "dgir" => ["gird", "grid"], "firz" => ["friz"],
      "efuz" => ["fuze"], "erst" => ["rest"], "airt" => ["rita"],
      "lmpu" => ["lump", "plum"], "bgio" => ["gobi"], "aadt" => ["data"],
      "osuy" => ["yous"], "begr" => ["berg"], "gill" => ["gill"],
      "ahhs" => ["hash", "shah"], "degn" => ["deng"], "coos" => ["coos"],
      "elln" => ["nell"], "aekt" => ["kate", "take", "teak"], "aely" => ["yale"],
      "gmos" => ["smog"], "dehi" => ["hide", "hied"], "alnw" => ["lawn"],
      "hjno" => ["john"], "eepr" => ["peer"], "ipss" => ["piss", "sips"],
      "defy" => ["defy"], "ehmu" => ["hume"], "abey" => ["ebay"],
      "birt" => ["brit"], "appu" => ["pupa"], "fllu" => ["full"],
      "eems" => ["seem"], "ilst" => ["list", "silt", "slit"], "ghou" => ["hugo"],
      "adht" => ["thad"], "einw" => ["wine"], "adlv" => ["vlad"],
      "alrs" => ["lars"], "cglo" => ["clog"], "alyz" => ["lazy"],
      "bffu" => ["buff"], "eglu" => ["glue"], "epsw" => ["pews", "spew"],
      "eklu" => ["luke"], "degl" => ["geld"], "bist" => ["bits"],
      "acns" => ["cans", "scan"], "ekns" => ["kens"],
      "amry" => ["mary", "myra", "army"], "acep" => ["pace", "cape"],
      "effi" => ["fief", "fife"], "acen" => ["acne", "cane"], "aaer" => ["area"],
      "fgor" => ["frog"], "aenv" => ["evan", "neva", "nave", "vane"],
      "afll" => ["fall"], "dior" => ["dior"], "mnos" => ["mons"],
      "aabs" => ["saab", "baas"], "beor" => ["boer", "ebro", "bore", "robe"],
      "cort" => ["rotc"], "dgoo" => ["good"], "eikl" => ["kiel", "like"],
      "aelo" => ["aloe"], "efll" => ["fell"], "aggn" => ["gang"],
      "dops" => ["pods"], "cess" => ["secs"], "imnx" => ["minx"],
      "aagi" => ["gaia"], "ceru" => ["cure", "ecru"], "ghtu" => ["thug"],
      "mopr" => ["prom", "romp"], "afip" => ["piaf"], "emnu" => ["menu"],
      "cilp" => ["clip"], "anrt" => ["tran", "rant"], "eekm" => ["meek"],
      "celu" => ["luce", "clue"], "anrw" => ["warn"], "cruz" => ["cruz"],
      "ffir" => ["riff"], "moos" => ["moos"], "arzz" => ["razz"],
      "egos" => ["egos", "goes"], "cmor" => ["corm"], "kmru" => ["murk"],
      "abkr" => ["bark"], "egno" => ["gone"], "aisv" => ["avis", "siva", "visa"],
      "llmu" => ["mull"], "aalm" => ["alma", "lama"], "hlru" => ["hurl"],
      "aers" => ["ares", "arse", "ears", "eras", "sear", "sera"],
      "glno" => ["long"], "insw" => ["wins"], "lmoo" => ["loom"],
      "norw" => ["worn"], "cfho" => ["foch"], "pssu" => ["puss", "sups"],
      "abez" => ["baez"], "ceil" => ["lice"], "aglo" => ["olga", "gaol", "goal"],
      "achk" => ["hack"], "dllo" => ["doll"], "nopu" => ["upon"],
      "ahll" => ["hall"], "gkoo" => ["gook"], "eikn" => ["nike"],
      "elsu" => ["slue"], "amrs" => ["mars", "rams", "arms"],
      "alps" => ["alps", "laps", "pals", "slap"], "aejk" => ["jake"],
      "ehwy" => ["whey"], "fikn" => ["fink"], "orty" => ["tory", "troy", "tyro"],
      "cnno" => ["conn"], "city" => ["city"], "aakr" => ["kara"],
      "eksy" => ["skye", "keys"], "ilmn" => ["limn"], "acll" => ["call"],
      "eipw" => ["wipe"], "chou" => ["chou", "ouch"], "anpt" => ["pant"],
      "abdl" => ["bald"], "hirw" => ["whir"],
      "epst" => ["sept", "pest", "pets", "step"], "denr" => ["nerd", "rend"],
      "elpu" => ["lupe"], "botu" => ["bout"], "empr" => ["perm"],
      "inps" => ["nips", "pins", "snip", "spin"], "dmos" => ["mods"],
      "dosu" => ["duos"], "fflo" => ["fofl"], "dloy" => ["loyd"],
      "bdin" => ["bind"], "adsw" => ["wads"], "ekty" => ["tyke"],
      "doow" => ["wood"], "aadr" => ["adar"], "lopp" => ["plop"],
      "allo" => ["lola"], "ekly" => ["kyle"], "deim" => ["diem", "dime"],
      "aisx" => ["axis"], "agor" => ["argo"], "bilp" => ["blip"],
      "adiz" => ["diaz"], "inux" => ["unix"], "eest" => ["tees"],
      "deen" => ["eden", "need"], "chsu" => ["such"], "imrs" => ["rims"],
      "aepv" => ["pave", "vape"], "berw" => ["brew"], "elsw" => ["slew"],
      "adfs" => ["fads"], "imst" => ["mist", "smit"], "adms" => ["dams", "mads"],
      "enoz" => ["zeno", "zone"], "acgs" => ["scag"], "drtu" => ["turd"],
      "ahir" => ["hair"], "csty" => ["cyst"], "chlo" => ["loch"],
      "kory" => ["kory", "york"], "almp" => ["lamp", "palm"], "mopp" => ["pomp"],
      "aprt" => ["tarp", "part", "rapt", "trap"], "ervy" => ["very"],
      "airs" => ["iras", "airs", "sari"], "akoy" => ["okay"], "cklu" => ["luck"],
      "adtv" => ["advt"], "gior" => ["igor"], "eosw" => ["owes", "woes"],
      "akst" => ["task"], "alnu" => ["luna", "ulna"], "eprt" => ["pert"],
      "efht" => ["heft"], "abck" => ["back"], "eeft" => ["feet"],
      "cfio" => ["coif", "foci"], "ddik" => ["kidd"], "ejnu" => ["june"],
      "ipsv" => ["vips"], "nosy" => ["sony", "nosy"], "istu" => ["suit"],
      "ghos" => ["gosh", "hogs"], "eeht" => ["thee"], "llot" => ["toll"],
      "aglu" => ["gaul"], "akss" => ["saks", "asks"], "hptt" => ["http"],
      "aemn" => ["amen", "mane", "mean", "name"], "fill" => ["fill"],
      "emot" => ["moet", "mote", "tome"], "dinw" => ["wind"],
      "aars" => ["saar", "sara"], "gloo" => ["logo"],
      "eemt" => ["meet", "mete", "teem"], "hmsu" => ["hums", "mush"],
      "eefl" => ["feel", "flee"], "deko" => ["oked"], "abos" => ["boas"],
      "ikrs" => ["kris", "irks", "risk"], "eqsu" => ["ques"], "bmos" => ["mobs"],
      "dpsu" => ["spud"], "eijv" => ["jive"], "ahmw" => ["wham"],
      "psuy" => ["yups"], "cikt" => ["tick"], "ahox" => ["hoax"],
      "hkno" => ["honk"], "bdel" => ["bled"], "dint" => ["dint"],
      "kloy" => ["yolk"], "dfio" => ["fido"], "esxy" => ["sexy"],
      "ably" => ["ably"], "aiow" => ["iowa"], "aefk" => ["fake"],
      "oops" => ["oops"], "dfno" => ["fond"], "knot" => ["knot"],
      "bkno" => ["knob"], "aerz" => ["ezra", "raze"], "ortt" => ["tort", "trot"],
      "eesx" => ["exes"], "dgin" => ["ding"], "epty" => ["type"],
      "aekp" => ["peak"], "booz" => ["bozo"], "osww" => ["wows"],
      "adkr" => ["dark"], "einp" => ["pine"], "glnu" => ["lung"],
      "fgos" => ["fogs"], "gllu" => ["gull"], "adde" => ["edda", "dead"],
      "adew" => ["wade", "awed"], "aiks" => ["saki"], "effj" => ["jeff"],
      "aaps" => ["asap"], "impp" => ["pimp"], "achs" => ["cash"],
      "gnow" => ["wong", "gown"], "amrt" => ["mart", "tram"], "ehrs" => ["hers"],
      "eers" => ["erse", "seer", "sere"], "eisz" => ["size"], "adfh" => ["fahd"],
      "bort" => ["robt"], "iprs" => ["rips"], "ehww" => ["whew"],
      "achr" => ["arch", "char"], "klru" => ["lurk"], "adls" => ["lads"],
      "bpru" => ["burp"], "ckor" => ["kroc", "rock", "cork"],
      "ikls" => ["ilks", "silk"], "dnou" => ["undo"], "cnos" => ["cons"],
      "ettx" => ["text"], "acmo" => ["coma"], "aemm" => ["emma"],
      "bbco" => ["cobb"], "besy" => ["byes"], "oprw" => ["prow"],
      "beet" => ["beet"], "crtu" => ["curt"], "ehnw" => ["hewn", "when"],
      "afit" => ["fiat"], "ehov" => ["hove"], "ekpr" => ["perk"],
      "cnsy" => ["sync"], "ipps" => ["pips"], "egmr" => ["germ"],
      "loss" => ["loss", "sols"], "dgis" => ["digs"], "adnw" => ["dawn", "wand"],
      "ddeu" => ["dude"], "mssu" => ["muss", "sums"], "eint" => ["nite", "tine"],
      "iruz" => ["ruiz"], "gnoy" => ["yong"], "ffim" => ["miff"],
      "irtz" => ["ritz"], "elno" => ["leno", "leon", "noel", "olen", "lone"],
      "deky" => ["dyke"], "eenr" => ["rene"], "ijlt" => ["jilt"],
      "empt" => ["temp"], "iltw" => ["wilt"], "ciky" => ["icky"],
      "inst" => ["nits", "snit", "tins"], "abrt" => ["bart", "brat"],
      "bbmo" => ["bomb"], "eejz" => ["jeez"], "denu" => ["dune", "nude"],
      "bmpu" => ["bump"], "cent" => ["cent"], "adly" => ["lady"],
      "achy" => ["achy"], "ginw" => ["wing"], "knox" => ["knox"],
      "eilv" => ["levi", "evil", "live", "veil", "vile"],
      "alop" => ["alpo", "opal"], "gpsu" => ["pugs"], "akns" => ["kans", "sank"],
      "dgil" => ["gild"], "ceis" => ["ices"], "dilm" => ["mild"],
      "acln" => ["clan"], "gorw" => ["grow"], "diop" => ["ipod"],
      "adgl" => ["glad"], "glow" => ["glow"], "dhlo" => ["hold"],
      "ikln" => ["kiln", "link"],
      "aepr" => ["earp", "pare", "pear", "rape", "reap"], "dios" => ["odis"],
      "bpsu" => ["pubs"], "gnoo" => ["goon"], "adrs" => ["sadr"],
      "istt" => ["tits"], "iipt" => ["tipi"], "ossw" => ["sows"],
      "cdik" => ["dick"], "ehop" => ["hope"], "desw" => ["weds"],
      "ddsu" => ["duds"], "eopx" => ["expo"], "eikm" => ["mike"],
      "acjk" => ["jack"], "ekpt" => ["kept"], "bcmo" => ["comb"],
      "agkw" => ["gawk"], "aeln" => ["lane", "lean", "lena", "neal"],
      "aenz" => ["zane"], "hilp" => ["phil"], "glop" => ["glop"],
      "dort" => ["trod"], "most" => ["most", "toms"], "filp" => ["flip"],
      "rstu" => ["rust", "ruts"], "himo" => ["imho"], "ikny" => ["inky"],
      "cdku" => ["duck"], "adem" => ["edam", "mead", "dame", "made"],
      "ennv" => ["venn"], "eeei" => ["ieee"], "fmrt" => ["rtfm"],
      "lopw" => ["plow"], "aikl" => ["kali"], "alnp" => ["plan"],
      "ahnt" => ["than"], "clot" => ["colt", "clot"],
      "gnsu" => ["sung", "gnus", "guns", "snug"], "aost" => ["oats"],
      "cdeu" => ["cued"], "eflx" => ["flex"], "deow" => ["owed"],
      "isst" => ["sits"], "deiv" => ["devi", "dive", "vied"], "ajzz" => ["jazz"],
      "ders" => ["reds"], "opty" => ["typo"], "ehsw" => ["hews"],
      "bntu" => ["bunt"], "ikst" => ["kits", "skit"], "beoo" => ["oboe"],
      "aegl" => ["gael", "gale"], "ehss" => ["hess", "shes"],
      "eopr" => ["pore", "rope"], "adex" => ["axed"], "aeno" => ["aeon"],
      "alpw" => ["pawl"], "cikr" => ["rick"], "brru" => ["burr"],
      "fmor" => ["form", "from"], "cdos" => ["cods", "docs"],
      "enps" => ["espn", "pens"], "aads" => ["adas"], "ddio" => ["dido"],
      "acrw" => ["craw"], "gpsy" => ["gyps"], "fttu" => ["tuft"],
      "ddey" => ["eddy", "dyed"], "hoot" => ["otoh", "hoot"], "aegg" => ["gage"],
      "aeru" => ["urea"], "ainz" => ["nazi"], "efor" => ["fore"],
      "ghot" => ["goth"], "ackr" => ["rack"], "abns" => ["bans", "nabs"],
      "eort" => ["rote", "tore"], "deew" => ["weed"], "abss" => ["bass"],
      "hksu" => ["husk"], "adiv" => ["avid", "diva"], "cilt" => ["clit"],
      "bdru" => ["drub"], "eity" => ["yeti"], "egrs" => ["ergs"],
      "inty" => ["tiny"], "eopt" => ["poet"], "almu" => ["alum", "maul"],
      "ckoo" => ["cook"], "bell" => ["bell"], "ginz" => ["zing"],
      "abby" => ["abby", "baby"], "ijnn" => ["jinn"],
      "aelr" => ["earl", "lear", "real"], "deir" => ["reid", "ride", "dire"],
      "acgr" => ["crag"], "demp" => ["pmed"], "prsy" => ["spry"],
      "entv" => ["vent"], "gnwy" => ["gwyn"], "morw" => ["worm"],
      "cist" => ["tics"], "orry" => ["rory"], "enru" => ["rune"],
      "ddst" => ["ddts"], "ipsu" => ["pius"], "himw" => ["whim"],
      "dens" => ["dens", "ends", "send"], "orxy" => ["roxy"],
      "ahrt" => ["hart", "thar"], "deru" => ["rude", "rued"], "acdi" => ["acid"],
      "eekl" => ["klee", "keel", "leek"], "emsu" => ["muse", "emus"],
      "egmo" => ["mego"], "ansv" => ["vans"], "prru" => ["purr"],
      "ehos" => ["hoes", "hose", "shoe"],
      "enst" => ["nest", "nets", "sent", "tens"], "ellt" => ["tell"],
      "emss" => ["mess"], "aors" => ["rosa", "oars", "soar"], "ersv" => ["revs"],
      "egmp" => ["mpeg"], "fino" => ["info"], "ahps" => ["hasp"],
      "ehnt" => ["then"], "adim" => ["amid", "maid"], "optu" => ["pout"],
      "aotu" => ["auto"], "afgs" => ["fags"], "ceer" => ["cree"],
      "hlmt" => ["html"], "eefs" => ["fees"], "nssu" => ["suns"],
      "adef" => ["deaf", "fade"], "hrsu" => ["rush"], "hoos" => ["soho", "shoo"],
      "dipr" => ["drip"], "alno" => ["nola", "loan"],
      "cost" => ["scot", "cost", "cots"], "actt" => ["catt", "tact"],
      "klsu" => ["sulk"], "ejtu" => ["jute"], "iilx" => ["lxii"],
      "ceho" => ["echo"], "ceky" => ["eyck"], "advy" => ["davy"],
      "hswy" => ["whys"], "boos" => ["boos"], "dlos" => ["sold"],
      "estv" => ["vest", "vets"], "bins" => ["bins", "nibs"], "gjnu" => ["jung"],
      "eggs" => ["eggs"], "fopr" => ["prof"], "deoz" => ["doze"],
      "luuz" => ["zulu"], "abhs" => ["bash"], "bnno" => ["bonn"],
      "nopy" => ["pony"], "finn" => ["finn"], "estu" => ["tues", "suet"],
      "flow" => ["wolf", "flow", "fowl"], "bcru" => ["curb"], "ckpu" => ["puck"],
      "ackt" => ["tack"], "elst" => ["lest", "lets"], "bioz" => ["zibo"],
      "lppu" => ["pulp"], "ejos" => ["jose"], "afrt" => ["fart", "frat", "raft"],
      "cdfi" => ["fdic"], "boru" => ["boru"], "acps" => ["caps"],
      "afor" => ["afro", "fora"], "dopr" => ["drop", "prod"], "iilv" => ["lvii"],
      "filt" => ["flit", "lift"], "abgo" => ["boga"],
      "anry" => ["ryan", "nary", "yarn"], "adhn" => ["hand"], "lovv" => ["lvov"],
      "adev" => ["dave", "veda"], "crst" => ["crts"], "iprt" => ["trip"],
      "dirs" => ["rids"], "beoy" => ["obey"], "blot" => ["blot", "bolt"],
      "bruy" => ["ruby", "bury"], "enrw" => ["wren"], "eksw" => ["skew"],
      "dffo" => ["doff"], "ampu" => ["puma"], "abfr" => ["barf"],
      "eglo" => ["lego", "loge", "ogle"], "dflo" => ["fold"],
      "ador" => ["dora", "road"], "aemz" => ["maze"], "oprt" => ["port"],
      "abry" => ["bray"], "deip" => ["pied"], "artw" => ["wart"],
      "anpw" => ["pawn"], "ceim" => ["mice"], "ginr" => ["grin", "ring"],
      "eivw" => ["view", "wive"], "ffho" => ["hoff"], "ckos" => ["sock"],
      "cnoo" => ["coon"], "celo" => ["cleo", "cole"], "cdee" => ["cede"],
      "jlow" => ["jowl"], "cfku" => ["fuck"], "agsw" => ["swag", "wags"],
      "emsw" => ["mews"], "ottu" => ["tout"], "diny" => ["indy"],
      "koru" => ["roku"], "aair" => ["aria"], "ciil" => ["clii"],
      "asss" => ["sass"], "absy" => ["bays"], "accy" => ["yacc"],
      "aeik" => ["ikea"], "adlu" => ["laud", "dual"], "ddos" => ["odds"],
      "cehn" => ["chen"], "abjs" => ["jabs"], "cikw" => ["wick"],
      "cinz" => ["zinc"], "acef" => ["face"], "abgn" => ["bang"],
      "bevy" => ["bevy"], "hioo" => ["ohio"], "ekop" => ["poke"],
      "fmsu" => ["fums"], "cchi" => ["chic"], "bdir" => ["bird"],
      "adgs" => ["gads"], "druu" => ["urdu"], "fknu" => ["funk"],
      "amsw" => ["maws", "swam"], "ehis" => ["hies"],
      "oott" => ["otto", "toto", "toot"], "elmy" => ["lyme"], "ffhu" => ["huff"],
      "ainv" => ["ivan", "vain"], "afht" => ["haft"], "enow" => ["owen"],
      "ceko" => ["coke"], "ahmt" => ["math"], "airy" => ["iyar", "airy"],
      "cntu" => ["cunt"], "aekn" => ["kane"], "aivv" => ["viva"],
      "druy" => ["rudy"], "hitw" => ["whit", "with"], "assw" => ["saws"],
      "abll" => ["ball"], "illt" => ["lilt", "till"], "doss" => ["sods"],
      "estt" => ["test"], "ahns" => ["hans", "nash"], "akny" => ["yank"],
      "acfl" => ["calf"], "bgru" => ["burg", "grub"], "lstu" => ["lust", "slut"],
      "ekot" => ["toke"], "dors" => ["rods"], "ilno" => ["olin", "lion", "loin"],
      "deny" => ["deny"], "altw" => ["walt"], "ailt" => ["alit", "tail"],
      "foru" => ["four"], "ffiy" => ["iffy"], "gino" => ["gino"],
      "deps" => ["sped"], "nnsu" => ["nuns"], "gmsu" => ["gums", "mugs", "smug"],
      "flor" => ["rofl"], "ilor" => ["lori", "roil"], "aelw" => ["wale", "weal"],
      "ailm" => ["lima", "mali", "mail"], "oosz" => ["zoos"],
      "ells" => ["ells", "sell"], "fotu" => ["tofu"], "ellw" => ["well"],
      "aess" => ["sase", "seas"], "cmoo" => ["como", "mooc"], "ggno" => ["gong"],
      "bkor" => ["bork"], "abcr" => ["crab"], "eprs" => ["pres", "reps", "resp"],
      "efrt" => ["fret"], "aclp" => ["clap"], "buzz" => ["buzz"],
      "adei" => ["aide", "idea"], "bpst" => ["tbsp"], "aesx" => ["axes"],
      "mort" => ["mort"], "gltu" => ["glut"], "aabr" => ["arab"],
      "aftt" => ["taft"], "eknu" => ["nuke"], "gkor" => ["grok"],
      "brtu" => ["brut", "burt"], "adlr" => ["lard"], "agit" => ["gait"],
      "dins" => ["dins"], "eess" => ["sees"], "eepp" => ["peep"],
      "aimt" => ["tami"], "apsy" => ["pays", "spay", "yaps"], "abor" => ["boar"],
      "adir" => ["arid", "raid"], "dmoo" => ["odom", "doom", "mood"],
      "crux" => ["crux"], "bfis" => ["fibs"], "aefz" => ["faze"],
      "abnr" => ["bran", "barn"], "aenw" => ["anew", "wane", "wean"],
      "aeks" => ["sake"], "moss" => ["moss"], "epru" => ["peru", "pure"],
      "aghn" => ["hang"], "oost" => ["soto", "soot"], "einn" => ["nine"],
      "anwy" => ["yawn"], "agnr" => ["rang"], "chim" => ["mich"],
      "klop" => ["polk"], "gins" => ["gins", "sign", "sing"], "moot" => ["moot"],
      "apss" => ["asps", "pass", "saps", "spas"], "eknt" => ["kent"],
      "abgs" => ["bags", "gabs"], "bors" => ["orbs", "robs"],
      "goop" => ["pogo", "goop"], "dewy" => ["dewy"], "akrs" => ["arks"],
      "foow" => ["woof"], "eimr" => ["meir", "emir", "mire", "rime"],
      "ffmu" => ["muff"], "depp" => ["depp"], "djoy" => ["jody"],
      "diss" => ["sids", "diss"], "kmsu" => ["musk"], "aamr" => ["mara", "rama"],
      "jknu" => ["junk"], "agos" => ["sago"], "ejov" => ["jove"],
      "losu" => ["soul"], "aknr" => ["nark", "rank"], "eknw" => ["knew"],
      "iknp" => ["pink"], "aceh" => ["ache", "each"], "artz" => ["tzar"],
      "aprr" => ["parr"], "lotv" => ["vtol", "volt"], "imrt" => ["trim"],
      "aafr" => ["afar"], "akms" => ["mask"], "lnps" => ["lpns"],
      "lpru" => ["purl"], "eipr" => ["pier", "ripe"], "aans" => ["nasa", "sana"],
      "ffgo" => ["goff"], "ehir" => ["heir", "hire", "rehi"], "aijm" => ["jami"],
      "inru" => ["ruin"], "defs" => ["feds"], "orst" => ["rots", "sort", "tors"],
      "asuv" => ["suva"], "borw" => ["brow"], "eloo" => ["oleo"],
      "dlor" => ["lord"], "gnru" => ["rung"], "ajno" => ["joan"],
      "eggr" => ["greg"], "einr" => ["erin", "rein"], "aajx" => ["ajax"],
      "ghiw" => ["whig"], "dnno" => ["donn"], "hmoo" => ["moho"],
      "eehl" => ["heel"], "agnv" => ["vang"], "adin" => ["dina"],
      "foxy" => ["foxy"], "demo" => ["demo", "dome", "mode"], "fgoo" => ["goof"],
      "coot" => ["coot"], "ersu" => ["rues", "ruse", "sure", "user"],
      "mnot" => ["mont"], "bees" => ["bees"], "suyz" => ["suzy"],
      "eesw" => ["ewes", "wees"], "ahil" => ["hail"], "adej" => ["jade"],
      "hint" => ["hint", "thin"], "bmow" => ["womb"],
      "aber" => ["reba", "bare", "bear"], "cekn" => ["neck"], "gikn" => ["king"],
      "acpt" => ["capt", "pact"], "cerw" => ["crew"], "cdor" => ["cord"],
      "dept" => ["dept"], "afin" => ["fain"], "dino" => ["dino", "dion", "odin"],
      "ilvx" => ["lxiv", "lxvi"], "detu" => ["duet"], "chip" => ["chip"],
      "eimm" => ["mime"], "aklt" => ["talk"], "bhos" => ["bosh", "hobs"],
      "aajv" => ["java"], "bosw" => ["bows", "swob"],
      "abls" => ["albs", "labs", "slab"], "arvy" => ["vary"], "iivx" => ["xvii"],
      "ipsz" => ["zips"], "drsv" => ["dvrs"], "mmvy" => ["ymmv"],
      "fhis" => ["fish"], "hotu" => ["thou"], "aknw" => ["kwan", "wank"],
      "hops" => ["hops", "posh", "shop"], "dgos" => ["dogs", "gods"],
      "ckno" => ["conk"], "eruy" => ["urey"], "bnsu" => ["buns", "nubs", "snub"],
      "enrt" => ["rent", "tern"], "aaln" => ["alan", "lana", "anal"],
      "opsw" => ["swop"], "ahhn" => ["hahn"], "almt" => ["malt"],
      "fkor" => ["fork"], "aegt" => ["gate"], "fgoy" => ["fogy"],
      "dehl" => ["held"], "aimm" => ["imam", "maim"], "iotv" => ["vito"],
      "fklo" => ["folk"], "imry" => ["ymir"], "lotu" => ["lout"],
      "deek" => ["eked"], "agry" => ["gary", "gray"], "akty" => ["katy"],
      "iloy" => ["oily"], "dilo" => ["idol"], "cino" => ["coin", "icon"],
      "aehs" => ["ashe", "shea"], "cdes" => ["decs"],
      "amno" => ["mona", "oman", "moan"], "entw" => ["newt", "went"],
      "loow" => ["wool"], "diln" => ["lind"], "cesu" => ["cues"],
      "ceno" => ["cone", "once"], "glmu" => ["glum"],
      "aelv" => ["elva", "vela", "vale", "veal"], "eehr" => ["rhee", "here"],
      "dfsu" => ["fuds"], "dils" => ["lids", "slid"], "dglo" => ["gold"],
      "abbe" => ["babe"], "dffi" => ["diff"], "adrw" => ["ward", "draw"]}
    |> Map.get(string_id)
  end
end
