defmodule Jumble.ScowlDict.Size55.Length14 do
  def get(string_id) do
    %{"aaceilnrtttuvy" => ["unattractively"],
      "cdeeinoprsstuv" => ["productiveness"],
      "aceeinoprrsssu" => ["precariousness"],
      "aeeiimnnorsttx" => ["exterminations"],
      "adeeehilnooprt" => ["radiotelephone"],
      "aceghilllnooty" => ["ethnologically"],
      "aceiillnnooost" => ["neocolonialist"],
      "aadehnorrssttw" => ["northeastwards"],
      "acillmmnnootty" => ["noncommittally"],
      "aceeeglmnorstt" => ["electromagnets"],
      "aaceiillnpstty" => ["antiseptically"],
      "abeeghiilnstux" => ["extinguishable"],
      "adeiiinnoorstt" => ["disorientation"],
      "aaciiilmnoppst" => ["misapplication"],
      "aainnooprrsttt" => ["transportation"],
      "aeegiilnnnrtty" => ["entertainingly"],
      "eeeegggiinnnor" => ["geoengineering"],
      "ccdeeeinnnortt" => ["interconnected"],
      "aeghimmnooprst" => ["metamorphosing"],
      "cddeeilnnostty" => ["discontentedly"],
      "acdeegilnnoqru" => ["grandiloquence"],
      "ceefgiinnorttu" => ["counterfeiting"],
      "acegiillmnoort" => ["terminological"],
      "eeeiilmnopssst" => ["impolitenesses"],
      "elmopprsstuuuy" => ["presumptuously"],
      "aaaeglllmoprrs" => ["parallelograms"],
      "adefgiimnorrst" => ["transmogrified"],
      "aeegiilmnorsss" => ["generalissimos"],
      "ccdehhillnoors" => ["schoolchildren"],
      "aeegginorrsssu" => ["gregariousness"],
      "aceeghilnorssu" => ["clearinghouses"],
      "aaceghiloorsst" => ["archaeologists"],
      "adeeginnopprrt" => ["preponderating"],
      "acegilmnnooort" => ["conglomeration"],
      "elnoopssstuuuv" => ["voluptuousness"],
      "aceeghillnopry" => ["hypoallergenic"],
      "adeeehhllortwy" => ["wholeheartedly"],
      "abccginnorsttu" => ["subcontracting"],
      "ceeghinorrsttv" => ["overstretching"],
      "abccnoorrssttu" => ["subcontractors"],
      "aacgillloottuy" => ["tautologically"],
      "efhioopprrssss" => ["professorships"],
      "celmnoopsttuuy" => ["contemptuously"],
      "abdeeiilnnpsss" => ["indispensables"],
      "aceghopprrrsty" => ["cryptographers"],
      "acegghhinooprr" => ["choreographing"],
      "aaiillmnnosttu" => ["multinationals"],
      "aceilnnnnootuv" => ["unconventional"],
      "aacegiillllsty" => ["legalistically"],
      "cceiimnnoopsst" => ["misconceptions"],
      "addeeeffiinrtt" => ["differentiated"],
      "eehiilmnnqrstu" => ["relinquishment"],
      "acegilllmootyy" => ["etymologically"],
      "acghiillnooort" => ["ornithological"],
      "aacillmopsttyy" => ["asymptotically"],
      "abdeefiiilnntu" => ["unidentifiable"],
      "acfgiinnoorstu" => ["configurations"],
      "acghiiinopsstt" => ["sophisticating"],
      "aaaccillorttuy" => ["autocratically"],
      "accefiiinopsst" => ["specifications"],
      "eeeeinprrssssv" => ["repressiveness"],
      "aacdiilllmopty" => ["diplomatically"],
      "aceehimmnorssv" => ["servomechanism"],
      "aaddegghnrrstu" => ["granddaughters"],
      "aacghillloopty" => ["pathologically"],
      "ceeeioprrssttv" => ["retrospectives"],
      "acdeiinnoorsst" => ["considerations"],
      "abeeiilmnoprss" => ["impressionable"],
      "cceeeeeflnnort" => ["teleconference"],
      "aabcillnooorst" => ["collaborations"],
      "bcdeegiimnnrsu" => ["disencumbering"],
      "adeffgiinorsst" => ["disafforesting"],
      "ceeeilmnnopsst" => ["incompleteness"],
      "beeinooqssssuu" => ["obsequiousness"],
      "aaceiinnnorrst" => ["reincarnations"],
      "aceeimmnnorstu" => ["incommensurate"],
      "aaccfiiilnorst" => ["clarifications"],
      "accchloopsstuy" => ["staphylococcus"],
      "aeeefghhirsttw" => ["featherweights"],
      "ccdeeennooprrs" => ["correspondence"],
      "aegiinnoopprrt" => ["reapportioning"],
      "adeeeimnrssttu" => ["underestimates"],
      "aadeeinnprsstt" => ["antidepressant"],
      "ceeefinorrsttu" => ["counterfeiters"],
      "aadiiilmnorstt" => ["traditionalism"],
      "aceillnnoosstt" => ["constellations"],
      "aacgilmnoopsst" => ["campanologists"],
      "aaceehilllptty" => ["telepathically"],
      "ccdegiimnnostu" => ["semiconducting"],
      "aachilnopsssyy" => ["psychoanalysis"],
      "aabcefiiinostt" => ["beatifications"],
      "aeegiimnorsttv" => ["overestimating"],
      "aaeiimoppprrst" => ["misappropriate"],
      "bhiiiinooprstt" => ["prohibitionist"],
      "aacdeeimnnostt" => ["decontaminates"],
      "abcceiillnorry" => ["irreconcilably"],
      "aeginnorrsssst" => ["transgressions"],
      "aegiinnoorrstt" => ["interrogations"],
      "dgghiiiinnsstu" => ["distinguishing"],
      "aadiiilnorsttt" => ["traditionalist"],
      "cceiillnnosuvy" => ["inconclusively"],
      "acchiilloprtyy" => ["hypocritically"],
      "aeeggiinorsstt" => ["segregationist"],
      "acceehhloorsst" => ["schoolteachers"],
      "efghhlnossttuu" => ["thoughtfulness"],
      "cegiinnorstttu" => ["reconstituting"],
      "abcelnosstuuuy" => ["subcutaneously"],
      "aaeehimnrssstu" => ["amateurishness"],
      "aaeginnnprstuu" => ["superannuating"],
      "ccgiilnnnnouvy" => ["unconvincingly"],
      "aeefgilmnnnssu" => ["meaningfulness"],
      "ehiiooppprrrst" => ["proprietorship"],
      "eeeinnoprssssv" => ["responsiveness"],
      "aaabcehlnoppru" => ["unapproachable"],
      "acdeiiinorsssy" => ["idiosyncrasies"],
      "abcinoooorrrst" => ["corroborations"],
      "ceeefimnnorrst" => ["reinforcements"],
      "aadiimnorrsstt" => ["administrators"],
      "aaaeiiilmprrst" => ["paramilitaries"],
      "aaaccehilmprtu" => ["pharmaceutical"],
      "cdeennooprrsst" => ["correspondents"],
      "aadehiioprrstt" => ["radiotherapist"],
      "aaadeillqrrstu" => ["quadrilaterals"],
      "abdefiillorrst" => ["defibrillators"],
      "aabbefggilnrst" => ["flabbergasting"],
      "abdeilmorstuxy" => ["ambidextrously"],
      "aaacehiimmnstt" => ["mathematicians"],
      "cceginnorrsttu" => ["reconstructing"],
      "aeegiinorrsttv" => ["interrogatives"],
      "aeeiimnoorsttv" => ["overestimation"],
      "aacciilmnrsttu" => ["circumstantial"],
      "acilrrssstttuu" => ["structuralists"],
      "aaimnnorsstttu" => ["transmutations"],
      "beeiimnsssssuv" => ["submissiveness"],
      "bcdeiilnrsttuy" => ["indestructibly"],
      "aacdeeffgiinnt" => ["decaffeinating"],
      "acefiiilmnostu" => ["emulsification"],
      "acdeghillmooot" => ["methodological"],
      "aeeiilmnnssttt" => ["sentimentalist"],
      "aaceiilnoprttu" => ["recapitulation"],
      "eeeiimnprssssv" => ["impressiveness", "permissiveness"],
      "ceeeegiilnnort" => ["electioneering"],
      "eeeellnnrsssst" => ["relentlessness"],
      "aacciiilmprtty" => ["impracticality"],
      "ccdenooprrstuu" => ["superconductor"],
      "ceeilmnopsssuv" => ["compulsiveness"],
      "bdegiiinrrsttu" => ["redistributing"],
      "acgghiklnosstu" => ["laughingstocks"],
      "aabddeelnnrstu" => ["understandable"],
      "bceeehilmnoprs" => ["comprehensible"],
      "acginoooprrstt" => ["prognosticator"],
      "aabcccghiknrst" => ["backscratching"],
      "acdefiiinoottx" => ["detoxification"],
      "adeeeggimnnsst" => ["disengagements"],
      "cdeeeiiinnsssv" => ["indecisiveness"],
      "aaceilnnoorstv" => ["conversational"],
      "ahiimnoprssstt" => ["misanthropists"],
      "abeegiinrssssu" => ["agribusinesses"],
      "aaaeeginnprstu" => ["septuagenarian"],
      "deeiiiilmrstuv" => ["verisimilitude"],
      "cceeinnoopprst" => ["preconceptions"],
      "aegiilnnnrstty" => ["intransigently"],
      "beegiiilllnntu" => ["unintelligible"],
      "aeeiilmnnsttty" => ["sentimentality"],
      "acgiimmnoorrss" => ["microorganisms"],
      "accefiiinorstt" => ["rectifications", "certifications"],
      "eeehiinprsstvy" => ["hypersensitive"],
      "aadddeeehhnrss" => ["hardheadedness"],
      "beeinoorsssstu" => ["boisterousness"],
      "giiinnooopprst" => ["propositioning"],
      "aefillnooprssy" => ["professionally"],
      "aacfinorssttuy" => ["unsatisfactory"],
      "aaeilnoorstuvv" => ["overvaluations"],
      "aacchilllossty" => ["scholastically"],
      "aciinnoprrsstt" => ["transcriptions"],
      "adiilnoprssttu" => ["postindustrial"],
      "aadeiiimnrsttv" => ["administrative"],
      "aceeinoorrsstv" => ["conservatoires", "conservatories"],
      "aaahiinorrsttu" => ["authoritarians"],
      "aaceeinnprrsst" => ["transparencies"],
      "bdiiiiiilnstvy" => ["indivisibility"],
      "aabcdeginorrst" => ["rebroadcasting"],
      "aacegillloopty" => ["apologetically"],
      "acceinoopprstu" => ["preoccupations"],
      "aaiimnoopprstx" => ["approximations"],
      "cceghiklnosttu" => ["shuttlecocking"],
      "aeiiilnnrsttvy" => ["intransitively"],
      "efggiiinnnprrt" => ["fingerprinting"],
      "aaaiinnossssst" => ["assassinations"],
      "ddeehinnorrsuu" => ["undernourished"],
      "ceeehimnoprssv" => ["comprehensives"],
      "aaceinoprrsstt" => ["procrastinates"],
      "aacfgiiimnnost" => ["magnifications"],
      "aaceghilllmpty" => ["phlegmatically"],
      "cceeeffiiiinns" => ["inefficiencies"],
      "abcchhiioprrss" => ["archbishoprics"],
      "ceeilmnossstuu" => ["meticulousness"],
      "aeeiiilmnssttx" => ["existentialism"],
      "bdehiiloorrstt" => ["bloodthirstier"],
      "bbcdeeiorrssuv" => ["oversubscribed"],
      "aiinnooprssstt" => ["transpositions"],
      "acceegillnorty" => ["egocentrically"],
      "aeginorsssttuu" => ["gratuitousness"],
      "cceeinorrsttuv" => ["reconstructive"],
      "accehilmmnopst" => ["accomplishment"],
      "abenoorrssstuu" => ["brontosauruses"],
      "aadeeilnrrsttt" => ["transliterated"],
      "cceelnorrttuuu" => ["counterculture"],
      "ceiilnnnosstty" => ["inconsistently"],
      "cdeinoooprrtuv" => ["overproduction"],
      "eegilnooprrvwy" => ["overpoweringly"],
      "aeeegginrssssv" => ["aggressiveness"],
      "aaaccdilorrsuv" => ["cardiovascular"],
      "acdeeghiinnruv" => ["underachieving"],
      "aaeffiimnorrst" => ["reaffirmations"],
      "aeeeeinprrsttv" => ["representative"],
      "abdeggiknnorru" => ["groundbreaking"],
      "bdeegiiillnsvy" => ["disbelievingly"],
      "aabeghiiilnrtt" => ["rehabilitating"],
      "cceeeiinnnnosv" => ["inconveniences"],
      "addeimnnrssstu" => ["misunderstands"],
      "deeegilnooprvv" => ["overdeveloping"],
      "acdeefhiinnrss" => ["disenfranchise"],
      "adeeghhillrtty" => ["lightheartedly"],
      "aceiiiilnpprst" => ["principalities"],
      "acceemnorrsstt" => ["concertmasters"],
      "aaggiilnnosttu" => ["agglutinations"],
      "bceehilmnoprsy" => ["comprehensibly"],
      "aaceklnnorstuy" => ["cantankerously"],
      "aacfgilnnoorst" => ["conflagrations"],
      "abciiilnrsttuy" => ["inscrutability"],
      "aiijnoopssttux" => ["juxtapositions"],
      "aaceeinrsstttv" => ["attractiveness"],
      "acdiilnooorsst" => ["discolorations"],
      "abeeilnnssttuu" => ["sublieutenants"],
      "aacdeimnnnottu" => ["uncontaminated"],
      "eegilmooorsstt" => ["meteorologists"],
      "aeeiilmmnnoptt" => ["implementation"],
      "aceiiinopprstt" => ["precipitations"],
      "aacehiinnotttu" => ["authentication"],
      "ceemopprrsstuu" => ["supercomputers"],
      "chiilorrstttuu" => ["horticulturist"],
      "addeeeeghlmmrs" => ["sledgehammered"],
      "acdeiiilnnortu" => ["unidirectional"],
      "aacdeiilnosttu" => ["educationalist"],
      "acdegimnnnortu" => ["countermanding"],
      "aceiiillmpttuv" => ["multiplicative"],
      "aacdgiiinnosst" => ["diagnosticians"],
      "acceeimmnostux" => ["excommunicates"],
      "aaceghimnoprty" => ["cinematography"],
      "ccciilmnoortuu" => ["circumlocution"],
      "ceeiimnnoopttv" => ["noncompetitive"],
      "aaailnnnorsstt" => ["transnationals"],
      "aehimnnoorsssu" => ["harmoniousness"],
      "aehhiilnopprst" => ["philanthropies"],
      "abeeehlnrsssst" => ["breathlessness"],
      "aiiimnooprsstv" => ["improvisations"],
      "ceeehimorsstty" => ["hysterectomies"],
      "acccgiimnnrstu" => ["circumstancing"],
      "adeggiiinnrstt" => ["disintegrating"],
      "eeeinopssssssv" => ["possessiveness"],
      "cddeeiinnooprt" => ["preconditioned"],
      "abcdeeehiilnpr" => ["indecipherable"],
      "aacdeiiilllsty" => ["idealistically"],
      "aeeilnoortttxy" => ["extortionately"],
      "aaceeffilnotty" => ["affectionately"],
      "ceiiiinossttvv" => ["vivisectionist"],
      "aehimoopppsstu" => ["hippopotamuses"],
      "aabcciilnottuy" => ["accountability"],
      "acceiinoprsssu" => ["capriciousness"],
      "ceemnnnooprstu" => ["pronouncements"],
      "acdeeimmnnoort" => ["recommendation"],
      "aacffiiilnosst" => ["falsifications"],
      "abdeehiilsssst" => ["disestablishes"],
      "aeiinoopprrstx" => ["expropriations"],
      "bdgggiillmnnoy" => ["mindbogglingly"],
      "acefinrrrsttuu" => ["infrastructure"],
      "achiioprssstty" => ["astrophysicist"],
      "aaccillnooptuy" => ["occupationally"],
      "aafimnnoorrstt" => ["transformation"],
      "diiiinnoopssst" => ["indispositions"],
      "aabdeeehhirrss" => ["haberdasheries"],
      "aeeemnorsstttv" => ["overstatements"],
      "aeehinpppprrsw" => ["whippersnapper"],
      "accdeiillnnoty" => ["coincidentally"],
      "aaceiinoprrstv" => ["prevarications"],
      "aceiiimmnoorss" => ["commissionaire"],
      "eeegiinnprrrtt" => ["reinterpreting"],
      "abeelnnnorrstu" => ["nonreturnables"],
      "aacdeinoprrstt" => ["procrastinated"],
      "accceimmnooors" => ["macroeconomics"],
      "cdelmnnoooosty" => ["monocotyledons"],
      "acddeegklnnouw" => ["unacknowledged"],
      "ciinnooorssttt" => ["contortionists"],
      "aaaegiiilmnrst" => ["egalitarianism"],
      "aacdeeijkrsttt" => ["straitjacketed"],
      "aadehorsssttuw" => ["southeastwards"],
      "acdeeeiosssttv" => ["videocassettes"],
      "abeeilmnnnostu" => ["unmentionables"],
      "adeeehimrsssst" => ["headmistresses"],
      "aaacceghilloor" => ["archaeological"],
      "aehiioorrssttt" => ["osteoarthritis"],
      "aaadeglnostuvy" => ["advantageously"],
      "eiilnoorssttuv" => ["revolutionists"],
      "aabbeiillosssu" => ["bouillabaisses"],
      "acfiilnnossttu" => ["functionalists"],
      "bcdeeiilnrsttu" => ["indestructible"],
      "cgiiilmnoorsst" => ["criminologists"],
      "acegiilnossttu" => ["gesticulations"],
      "aceghlnnnoooty" => ["nanotechnology"],
      "aaeegilnprstxy" => ["exasperatingly"],
      "aeillmnosstuuy" => ["simultaneously"],
      "cceimoooprrrss" => ["microprocessor"],
      "abeeeinorrrstv" => ["reverberations"],
      "acdeeennopprrs" => ["preponderances"],
      "aacdeglmnnorss" => ["scandalmongers"],
      "aaceghiinntttu" => ["authenticating"],
      "acceeiinnoorss" => ["concessionaire"],
      "beeehillmmnsst" => ["embellishments"],
      "acfgiiiinnosst" => ["significations"],
      "abcdenooorrrtu" => ["uncorroborated"],
      "aaacehimoopprs" => ["pharmacopoeias"],
      "achiiinoopsstt" => ["sophistication"],
      "aefiiiilmnnsst" => ["infinitesimals"],
      "cdeiiinnnssstt" => ["indistinctness"],
      "abcegiiloorstt" => ["bacteriologist"],
      "ceeeiooprrttvv" => ["overprotective"],
      "aacehlnopsssyy" => ["psychoanalyses"],
      "adehorsssttuww" => ["southwestwards"],
      "aceeemnorrstuu" => ["countermeasure"],
      "cdeeiiinnsstvv" => ["vindictiveness"],
      "adeeiinnoprstt" => ["predestination"],
      "acdeegimnorstu" => ["discouragement"],
      "acegiillorssuy" => ["sacrilegiously"],
      "aadeeghinqrrtu" => ["headquartering"],
      "eefimnnoorrstw" => ["frontierswomen"],
      "bcceeikkknorrs" => ["knickerbockers"],
      "begilnorsssuuu" => ["lugubriousness"],
      "aadeegimnnrrst" => ["disarrangement"],
      "acdeeeimnoppst" => ["appendectomies"],
      "ccdeiinnnoosst" => ["disconnections"],
      "deeeeillmmosss" => ["mesdemoiselles"],
      "aefgiimnorrsst" => ["transmogrifies"],
      "ghiilnooorsstt" => ["ornithologists"],
      "aceeggimnnorrs" => ["scaremongering"],
      "acdiiiilnnnost" => ["disinclination"],
      "aacceknorstttu" => ["counterattacks"],
      "ceiinoprsssstu" => ["percussionists"],
      "cegiiknnnorstu" => ["countersinking"],
      "aabceenrsssstt" => ["abstractnesses"],
      "aaehiiimnnsstt" => ["antihistamines"],
      "ceefiinnossstu" => ["infectiousness"],
      "acfinnnooorstt" => ["confrontations"],
      "acffiiinoorstt" => ["fortifications"],
      "ccefllnsssuuuy" => ["unsuccessfully"],
      "acceehilmoprst" => ["petrochemicals"],
      "accdhhinooprsy" => ["hypochondriacs"],
      "aacchilnopstyy" => ["psychoanalytic"],
      "aeffhilnnsstuu" => ["unfaithfulness"],
      "aaelnoprsttuuy" => ["polyunsaturate"],
      "aaeilnooprsttx" => ["extrapolations"],
      "aeeeinnoprrstt" => ["representation"],
      "beeeinrssssuvv" => ["subversiveness"],
      "aeeiilnnorrstt" => ["interrelations"],
      "accceillnnorty" => ["concentrically"],
      "acdeeenrrrstuy" => ["undersecretary"],
      "aaiinooppprrst" => ["appropriations"],
      "aeiimnnooprsst" => ["impersonations"],
      "cceeiinnossttu" => ["constituencies"],
      "beeeimmnrrsstu" => ["reimbursements"],
      "abeeghiilnrsst" => ["reestablishing"],
      "abbeghiiiloprs" => ["bibliographies"],
      "deehhnorrsstuw" => ["thundershowers"],
      "aeegiimnnnortu" => ["mountaineering"],
      "acceinnnoorstt" => ["concentrations"],
      "aaccegiimnrtuv" => ["circumnavigate"],
      "acehiinnssttuu" => ["unenthusiastic"],
      "abclllnnoortuy" => ["uncontrollably"],
      "acdehhiimoprrt" => ["hermaphroditic"],
      "eeeilnoprssssx" => ["expressionless"],
      "aceeeeinnrrstt" => ["tercentenaries"],
      "aabcdeennprsuu" => ["superabundance"],
      "aabcefgiinprrt" => ["prefabricating"],
      "accinprssttuuu" => ["acupuncturists"],
      "ceeinnosssstuu" => ["incestuousness"],
      "aaceeghnooprrs" => ["oceanographers"],
      "adeeeffiinrstt" => ["differentiates"],
      "acfiiilnostttu" => ["stultification"],
      "aabcefiiinottu" => ["beautification"],
      "aeegiiilrrrstu" => ["irregularities"],
      "aacinooprrrstt" => ["procrastinator"],
      "ceiiiillmpsttu" => ["multiplicities"],
      "ddeeeeinnnprtt" => ["interdependent"],
      "abcdeeehilnpru" => ["undecipherable"],
      "aaabdhimoprsss" => ["ambassadorship"],
      "adeeegoprrstuy" => ["daguerreotypes"],
      "aacghilmooprst" => ["pharmacologist"],
      "acfgiilmnnnotu" => ["malfunctioning"],
      "abbcdeilmoostu" => ["discombobulate"],
      "aabeilmnoprstu" => ["perambulations"],
      "aabegiillnosuv" => ["bougainvilleas"],
      "cfimnnnooorsst" => ["nonconformists"],
      "aciiiilprssttu" => ["spiritualistic"],
      "ccceeeiiinrstt" => ["eccentricities"],
      "addeeegoprrtuy" => ["daguerreotyped"],
      "aeeeiinprrtttv" => ["interpretative"],
      "eefiiilmoprssv" => ["oversimplifies"],
      "deefiiilmoprsv" => ["oversimplified"],
      "adeiimnnoppstt" => ["disappointment"],
      "aeeeiiinnprstt" => ["penitentiaries"],
      "aeeiinnoprrttt" => ["interpretation"],
      "aabdeiikmnorst" => ["disembarkation"],
      "aceillnnnootvy" => ["conventionally"],
      "ceeghinorsttuw" => ["counterweights"],
      "dddeeeelnopruv" => ["underdeveloped"],
      "acdeefinnoorst" => ["confederations"],
      "accefgiiiinnns" => ["insignificance"],
      "aacehiillnttty" => ["antithetically"],
      "aeeeillmnprtxy" => ["experimentally"],
      "abcceilnnnoosu" => ["unconscionable"],
      "aadefgghinnrrt" => ["grandfathering"],
      "aabchilooprstu" => ["claustrophobia"],
      "aaabcehilllpty" => ["alphabetically"],
      "aabcefiinoprrt" => ["prefabrication"],
      "aachlnopssstyy" => ["psychoanalysts"],
      "ccdeeeiinnnnov" => ["inconvenienced"],
      "aacglnoorrttuy" => ["congratulatory"],
      "aabeiiilnprsty" => ["inseparability"],
      "aeeehilnprttvy" => ["hyperventilate"],
      "ceeiinnorrsttv" => ["nonrestrictive"],
      "aacciillmnostu" => ["miscalculation"],
      "aillnooopprrty" => ["proportionally"],
      "aaeiilnnossstt" => ["sensationalist"],
      "aaeeilnnprrtty" => ["interplanetary"],
      "aeeghhlorsstuu" => ["slaughterhouse"],
      "aacegghillopry" => ["geographically"],
      "behiiiinossttx" => ["exhibitionists"],
      "afiiimmnnoorst" => ["misinformation"],
      "adeeeimnrssttv" => ["advertisements"],
      "abcdeeiilnnors" => ["inconsiderable"],
      "aaeiilmnnossst" => ["sensationalism"],
      "beeeillnorsssu" => ["rebelliousness"],
      "aabcdeeinrrstt" => ["scatterbrained"],
      "aacdeelnnnrstt" => ["transcendental"],
      "bccilnoosssuuy" => ["subconsciously"],
      "deegiiilmoopst" => ["epidemiologist"],
      "accdeeinnnostu" => ["discountenance"],
      "deeeelmnoprstv" => ["redevelopments"],
      "acdeiiiimnnrst" => ["indiscriminate"],
      "eehiinoopssttv" => ["photosensitive"],
      "aceehiinppprst" => ["apprenticeship"],
      "aceinnnooooprt" => ["noncooperation"],
      "acdiilnnooosst" => ["consolidations"],
      "aceeghhooprrrs" => ["choreographers"],
      "achiiillnorsty" => ["histrionically"],
      "aaeiilnnnorstt" => ["internationals"],
      "aefimnnoorrstw" => ["frontierswoman"],
      "aaciilnooprrst" => ["conspiratorial"],
      "adeelnnopprrty" => ["preponderantly"],
      "aeilnooopprtuv" => ["overpopulation"],
      "adiiilnrsssttu" => ["industrialists"],
      "adegilmoorsstt" => ["dermatologists"],
      "aciiilnopssuuy" => ["inauspiciously"],
      "acgiiilllnstuy" => ["linguistically"],
      "aabehiiilnortt" => ["rehabilitation"],
      "eeghillmnorvwy" => ["overwhelmingly"],
      "acehilmoprsstt" => ["thermoplastics"],
      "adeiilnosttuvy" => ["adventitiously"],
      "beefhimnrrsstu" => ["refurbishments"],
      "ccehhiinoprssz" => ["schizophrenics"],
      "aacceinnnoostt" => ["concatenations"],
      "aaceillmmrstyy" => ["asymmetrically"],
      "aaeemnnopprsww" => ["newspaperwoman"],
      "abefllnoopsstu" => ["tablespoonfuls"],
      "aaeeegmnnrrrst" => ["rearrangements"],
      "aeegillmnorrst" => ["steamrollering"],
      "adfiiimnnoorst" => ["disinformation"],
      "aadefilmnnsttu" => ["fundamentalist"],
      "aacfiiinnoqttu" => ["quantification"],
      "aegiiinnossttv" => ["investigations"],
      "acdggiilnorsuy" => ["discouragingly"],
      "aefilnooprsssw" => ["passionflowers"],
      "aabegilmnrrssy" => ["embarrassingly"],
      "ccceiimmnooors" => ["microeconomics"],
      "aacddeeimnnott" => ["decontaminated"],
      "abegiiilmnprty" => ["impregnability"],
      "aaellnprrstuuy" => ["supernaturally"],
      "aciiillmnopttu" => ["multiplication"],
      "cgiimmnnooprsu" => ["uncompromising"],
      "addeeehimnpprs" => ["misapprehended"],
      "aeeiilmmnnsstt" => ["sentimentalism"],
      "aceegillnoprtt" => ["electroplating"],
      "cehilmoorsssst" => ["schoolmistress"],
      "deeegiimnnprrt" => ["predetermining"],
      "aaccfiiilnosst" => ["classification"],
      "acfiiijnossttu" => ["justifications"],
      "acceehiiilnstt" => ["technicalities"],
      "abcdeiiilprtty" => ["predictability"],
      "aabceeilllmmty" => ["emblematically"],
      "aabeghiklnrtty" => ["breathtakingly"],
      "ccdeimnoorsstu" => ["semiconductors"],
      "aefilnnooprssu" => ["unprofessional"],
      "acdiiijlnorstu" => ["jurisdictional"],
      "aeeemnooprstux" => ["extemporaneous"],
      "cdeiilnorsssuu" => ["ridiculousness"],
      "bceiiilpssttuy" => ["susceptibility"],
      "aaaaghimnoprst" => ["phantasmagoria"],
      "aeeiiilnopsttt" => ["potentialities"],
      "aeghiilnnsttuy" => ["unhesitatingly"],
      "accefiiillnsty" => ["scientifically"],
      "aceehmnopprrst" => ["rapprochements"],
      "deimnooprssstt" => ["postmodernists"],
      "eeeiopprrrssst" => ["proprietresses"],
      "acfiiijllnoost" => ["jollifications"],
      "cddeeiimmnooss" => ["decommissioned"],
      "adeeemnnrstttu" => ["understatement"],
      "ceffiiilnnstuy" => ["insufficiently"],
      "aaccfiiinnostt" => ["sanctification"],
      "accdeeilmnortu" => ["counterclaimed"],
      "bbciiilmosttuy" => ["combustibility"],
      "aaeelnnnpssstu" => ["unpleasantness"],
      "abdeeeiilmnnrt" => ["indeterminable"],
      "aacceimmnnopst" => ["accompaniments"],
      "adgiilllnnotuy" => ["longitudinally"],
      "aceginooprsstt" => ["prognosticates"],
      "acdfiiiilnoost" => ["solidification"],
      "acceeilllnorty" => ["electronically"],
      "aaccceeiillsst" => ["ecclesiastical"],
      "acdiiiimnnorst" => ["discrimination"],
      "acdefiillnnoty" => ["confidentially"],
      "aceeemnooprstv" => ["overcompensate"],
      "ceehhnoopprsst" => ["phosphorescent"],
      "aaceiimmossttu" => ["semiautomatics"],
      "aaabcelmmnnouw" => ["ambulancewoman"],
      "ddeeiilnorrsss" => ["disorderliness"],
      "eeghilnoprrstu" => ["reupholstering"],
      "aagiimnnorrstt" => ["transmigration"],
      "accegiilnrtuxy" => ["excruciatingly"],
      "aaccdeillmorty" => ["democratically"],
      "accceeelnnossv" => ["convalescences"],
      "aacfiilorsstty" => ["satisfactorily"],
      "ccdeinnoorsttu" => ["deconstruction"],
      "aacfiiilnoqstu" => ["qualifications"],
      "bdeiiorrrssttu" => ["redistributors"],
      "cccilmoorrtuuy" => ["circumlocutory"],
      "addeeeimnrsttu" => ["underestimated"],
      "aacegiilnprttu" => ["recapitulating"],
      "aceiiiilmnpstu" => ["municipalities"],
      "abiiiillmpstuy" => ["implausibility"],
      "acefiiilprstuy" => ["superficiality"],
      "aceiilnossssuv" => ["lasciviousness"],
      "aciiilllmpssty" => ["simplistically"],
      "addeeeimnprttu" => ["unpremeditated"],
      "defgiiiimnnsty" => ["misidentifying"],
      "aeeinoqrsssttu" => ["sequestrations"],
      "aacehiillmrtty" => ["arithmetically"],
      "aceeelmnoprtux" => ["counterexample"],
      "abceeeefnrssst" => ["benefactresses"],
      "adeimnnoorsstt" => ["demonstrations"],
      "cdegiiinnnoort" => ["reconditioning"],
      "deeegknoprrssu" => ["groundskeepers"],
      "aaceeiilpprtvy" => ["appreciatively"],
      "aciilllmooqssu" => ["colloquialisms"],
      "aacillmnoorsty" => ["astronomically"],
      "bdeehlooorsttu" => ["troubleshooted"],
      "aaceggilnnoort" => ["congregational"],
      "acdeillnoossty" => ["disconsolately"],
      "ceiijnooprsstt" => ["projectionists"],
      "aaeinnnoprstuu" => ["superannuation"],
      "aabciiilnrttty" => ["intractability"],
      "acceilmmnnoors" => ["noncommercials"],
      "ceeeehlnpsssss" => ["speechlessness"],
      "eeimnorsssstuy" => ["mysteriousness"],
      "abeeeikkrrrsst" => ["strikebreakers"],
      "eeeeinprssssvx" => ["expressiveness"],
      "acdehimmnorsty" => ["thermodynamics"],
      "aaaddggiinnstv" => ["disadvantaging"],
      "aabcegiknqrrtu" => ["quarterbacking"],
      "aaaccgiiinnptt" => ["incapacitating"],
      "aegilnoopprtuv" => ["overpopulating"],
      "ceehimnnooprss" => ["comprehensions"],
      "abeegiikknrrst" => ["strikebreaking"],
      "ddeeeimnnnortu" => ["undermentioned"],
      "aeeemnnopprsww" => ["newspaperwomen"],
      "addiiiilnsstuv" => ["individualists"],
      "aabceelmmnnouw" => ["ambulancewomen"],
      "accgiilllooosy" => ["sociologically"],
      "accdiinnoorstt" => ["contradictions"],
      "aacdeilpqrstuu" => ["quadruplicates"],
      "aceinnnoorsttv" => ["contraventions"],
      "cdeiloorsstuuy" => ["discourteously"],
      "aeeegillnssttv" => ["televangelists"],
      "aeiilnnooprstt" => ["interpolations"],
      "aacdeiilnorstv" => ["valedictorians"],
      "ceeiilnnnnotvy" => ["inconveniently"],
      "ceginrrrssttuu" => ["restructurings"],
      "acgiillmoosstt" => ["climatologists"],
      "begiiilllnntuy" => ["unintelligibly"],
      "ahhiilnopprstt" => ["philanthropist"],
      "aaccehhiillrry" => ["hierarchically"],
      "deeeinnnprsttu" => ["superintendent"],
      "aehhinopprstty" => ["hypnotherapist"],
      "cceeinooprsssu" => ["precociousness"],
      "eiiimnoprsssst" => ["impressionists"],
      "ceeeeinpprsstv" => ["perceptiveness"],
      "acdeeehinrrsuv" => ["underachievers"],
      "aiilmnooprssuy" => ["parsimoniously"],
      "acdeeilnpprrsu" => ["perpendiculars"],
      "deefgiimnrsstu" => ["disfigurements"],
      "aeeefillnprrty" => ["preferentially"],
      "ceiinnoorstttu" => ["reconstitution"],
      "acefgiiinnortt" => ["gentrification"],
      "aghilnoooprstt" => ["anthropologist"],
      "aceeilmnopsttv" => ["contemplatives"],
      "aabcceelnnortu" => ["counterbalance"],
      "aaacehillmmtty" => ["mathematically"],
      "aacilllnorstuy" => ["ultrasonically"],
      "aeeiinnoqrsstu" => ["questionnaires"],
      "aaeeilnrrssttt" => ["transliterates"],
      "degiilnnossuuy" => ["disingenuously"],
      "aaccdimmnooost" => ["accommodations"],
      "ehiorrssttttuw" => ["trustworthiest"],
      "deiiinoopprsst" => ["predisposition"],
      "aaaehimoprrstt" => ["aromatherapist"],
      "ceeprrrssttuuu" => ["superstructure"],
      "abdeiiilnrstuy" => ["undesirability"],
      "aacdgiiinossst" => ["disassociating"],
      "aabddelnnrstuy" => ["understandably"],
      "abeehilmnssstt" => ["establishments"],
      "bcgiiilmooorst" => ["microbiologist"],
      "aeeiinnnoopttx" => ["exponentiation"],
      "deghhilorsstty" => ["shortsightedly"],
      "eeiinoprsssstx" => ["expressionists"],
      "aabcciiilprtty" => ["practicability"],
      "adeeimnorssttv" => ["demonstratives"],
      "aaceeggilllnoy" => ["genealogically"],
      "aadiiimnnorstt" => ["administration"],
      "deegiinnnprstu" => ["superintending"],
      "beiiilnoprssty" => ["responsibility"],
      "aabdeginorrstw" => ["waterboardings"],
      "adegiiinnorstt" => ["disorientating", "disintegration"],
      "aceiimmnoorsst" => ["commiserations"],
      "aaceeiinpprtuv" => ["unappreciative"],
      "ceggiinnnorstu" => ["countersigning"],
      "acdeehimnnnstt" => ["disenchantment"],
      "cllnoprssuuuuy" => ["unscrupulously"],
      "aegginoossttuu" => ["autosuggestion"],
      "aacceiinnorrst" => ["incarcerations"],
      "aaceilnnopsstu" => ["encapsulations"],
      "ceefiinoprsstt" => ["perfectionists"],
      "aceelmmnorstuy" => ["commensurately"],
      "cceilnorsttuvy" => ["constructively"],
      "aceeillllnttuy" => ["intellectually"],
      "aadeeiinorrrtx" => ["extraordinaire"],
      "befgillnooprtu" => ["bulletproofing"],
      "aeilnoopssttux" => ["expostulations"],
      "ccceeefimnrrsu" => ["circumferences"],
      "aacgillloorsty" => ["astrologically"],
      "aabcehiloprrry" => ["irreproachably"],
      "aceggillnooort" => ["gerontological"],
      "aceeghiloprrsx" => ["lexicographers"],
      "abeilmnnorstuu" => ["insurmountable"],
      "adeeggimnnrrry" => ["gerrymandering"],
      "aceggilmnnoort" => ["conglomerating"],
      "acefiiiinortvv" => ["revivification"],
      "aceimmmnooorst" => ["commemorations"],
      "bdeiiinorrsttu" => ["redistribution"],
      "acciimmnnoostu" => ["communications"],
      "dgiiiillnnossu" => ["disillusioning"],
      "acehinoorrsstt" => ["orchestrations"],
      "ceeeinoprssttv" => ["protectiveness"],
      "aceiinopssssuu" => ["auspiciousness"],
      "cdeekklnrsstuu" => ["knuckledusters"],
      "cdeeinnooprttu" => ["counterpointed"],
      "bceiiilnorttvy" => ["convertibility"],
      "aaacfiilllstty" => ["fatalistically"],
      "cciiijnnosttuv" => ["conjunctivitis"],
      "aaceeilmmnsstu" => ["immaculateness"],
      "bciimnoorssttu" => ["obstructionism"],
      "efghhinorrsstt" => ["forthrightness"],
      "aacdhimoosssst" => ["sadomasochists"],
      "bbceeiorrsssuv" => ["oversubscribes"],
      "abdeghinoorssu" => ["boardinghouses"],
      "acceiiilnnoort" => ["reconciliation"],
      "aaceiillnrttuy" => ["inarticulately"],
      "abddeeefghinrt" => ["featherbedding"],
      "beehlooorrsttu" => ["troubleshooter"],
      "acfiiiilmnopst" => ["simplification"],
      "cdeeegilnnoruv" => ["overindulgence"],
      "aacceeinnnorss" => ["reconnaissance"],
      "aacfiiinorsttt" => ["stratification"],
      "eiinooppprsstu" => ["presupposition"],
      "ccceiimnoprstu" => ["circumspection"],
      "aceeegmnnorstu" => ["encouragements"],
      "aabceilnorsstu" => ["constabularies"],
      "adefiinosssstu" => ["fastidiousness"],
      "acciiillooopst" => ["sociopolitical"],
      "aacdiiiilnnprs" => ["disciplinarian"],
      "aabdeeefhinrrt" => ["featherbrained"],
      "aaeggilmnoorst" => ["agglomerations"],
      "aacdeeginrrrsu" => ["undercarriages"],
      "eefghinnoorrst" => ["foreshortening"],
      "adeehhimoprrst" => ["hermaphrodites"],
      "aacfgiiinorstt" => ["gratifications"],
      "aadeiilmnnnoot" => ["denominational"],
      "adeeiimnnorstt" => ["determinations"],
      "eggilnooorsstt" => ["gerontologists"],
      "aciilnnoostttu" => ["constitutional"],
      "eeflnopprsssuu" => ["purposefulness"],
      "aaiiiilmnrsttu" => ["utilitarianism"],
      "cgiimnnnooprsu" => ["mispronouncing"],
      "eiilnoqrssttuv" => ["ventriloquists"],
      "adgiilnopprsvy" => ["disapprovingly"],
      "bciinoorsstttu" => ["obstructionist"],
      "aabeeelnnorsss" => ["reasonableness"],
      "aaeiinnpprrstt" => ["antiperspirant"],
      "aacehillmoprty" => ["metaphorically"],
      "aeegiiilllmtty" => ["illegitimately"],
      "aacccehiirrstt" => ["characteristic"],
      "eennooprsssttu" => ["portentousness"],
      "ceiinooprssttt" => ["protectionists"],
      "aaacdeeinpprss" => ["disappearances"],
      "aeeehilnpprsvy" => ["apprehensively"],
      "aciinnnooprstu" => ["pronunciations"],
      "cdeeimnnnosttt" => ["discontentment"],
      "cdeeeennpsstux" => ["unexpectedness"],
      "adeeefimnnoort" => ["aforementioned"],
      "addeginnnrsstu" => ["understandings"],
      "adeefghinrssst" => ["farsightedness"],
      "aabceehiloprrr" => ["irreproachable"],
      "cceeilnoorsttu" => ["electrocutions"],
      "acdiiinnnoortt" => ["indoctrination"],
      "cceinnoorrsttu" => ["reconstruction"],
      "aaeegiimnrrrst" => ["intermarriages"],
      "aacgilnnoorttu" => ["congratulation"],
      "aaggiiilnnrtty" => ["ingratiatingly"],
      "aceiillmnnooos" => ["neocolonialism"],
      "aeeiilnnqssttu" => ["quintessential"],
      "cegiiilnoorsst" => ["coreligionists"],
      "aciiillmopstty" => ["optimistically"],
      "acdiiimnorrsty" => ["discriminatory"],
      "aabdgiiimnostu" => ["disambiguation"],
      "adeeefhooprrtw" => ["weatherproofed"],
      "aeeeeinnprrttt" => ["interpenetrate"],
      "acdefiiiinnott" => ["identification"],
      "aaccgiillmnstu" => ["miscalculating"],
      "aaceeilnrssttu" => ["articulateness"],
      "acceeinoprsttv" => ["contraceptives"],
      "eeeggiinprrrst" => ["preregistering"],
      "aabiinnosstttu" => ["substantiation"],
      "aaeemqrrrssttu" => ["quartermasters"],
      "deefiilnnnrssu" => ["unfriendliness"],
      "aceeilnorstvvy" => ["conservatively"],
      "aabeemmnrrssst" => ["embarrassments"],
      "aaaabcceelrstu" => ["baccalaureates"],
      "eeiilmnnrtttty" => ["intermittently"],
      "ceeiilnnossstu" => ["licentiousness"],
      "acceinnoorsttu" => ["counteractions"],
      "deeeeimnprrsst" => ["misrepresented"],
      "aaddeegnrrstuu" => ["undergraduates"],
      "aaeimnorsssttt" => ["stationmasters"],
      "adehilnnossstu" => ["outlandishness"],
      "acdgiiinnnortt" => ["indoctrinating"],
      "accdeiinnnostu" => ["discontinuance"],
      "adehnorrssttww" => ["northwestwards"],
      "abddeehiilssst" => ["disestablished"],
      "eeeghilnsssstw" => ["weightlessness"],
      "ceiilnoosssstu" => ["solicitousness"],
      "aabgiinnsstttu" => ["substantiating"],
      "abcceeiillnorr" => ["irreconcilable"],
      "deeeiimnprrstt" => ["misinterpreted"],
      "ccddeeilnnosty" => ["disconnectedly"],
      "aabdiinoopprst" => ["disapprobation"],
      "acceghiillnnou" => ["hallucinogenic"],
      "aeefglnnrsstuu" => ["ungratefulness"],
      "ddeeghhinrstuw" => ["hundredweights"],
      "acdeginooprstt" => ["prognosticated"],
      "aaciilllrsttuy" => ["altruistically"],
      "aeegiiillnnstt" => ["intelligentsia"],
      "aceegillmooort" => ["meteorological"],
      "abcchilooprstu" => ["claustrophobic"],
      "eeeinopprssssv" => ["oppressiveness"],
      "cceimmooprrstu" => ["microcomputers"],
      "aachiillnnostu" => ["hallucinations"],
      "aaacgilnnosttu" => ["anticoagulants"],
      "ceiilloprssuuy" => ["superciliously"],
      "aceiiimnnorrst" => ["recriminations"],
      "aeegiinnoprrst" => ["peregrinations"],
      "aeiiilorrrttty" => ["territoriality"],
      "abccilnnnoosuy" => ["unconscionably"],
      "eehilloorssstt" => ["tortoiseshells"],
      "aaggiimnnrrstt" => ["transmigrating"],
      "abceeiilprstty" => ["respectability"],
      "aeilnoosstttuy" => ["ostentatiously"],
      "ccdeginnorsttu" => ["deconstructing"],
      "eehiimmnoprstv" => ["impoverishment"],
      "deeeeimnprrrst" => ["predeterminers"],
      "bdeiiiilmqrsuu" => ["disequilibrium"],
      "acdfghiiinnrss" => ["disfranchising"],
      "egiiiinnoqrstu" => ["requisitioning"],
      "aabiiilnssttuy" => ["sustainability"],
      "eeginnoppssstt" => ["steppingstones"],
      "aaceillmssttyy" => ["systematically"],
      "aeeiiilnsstttx" => ["existentialist"],
      "eeeeilprrtttwy" => ["teletypewriter"],
      "achlnnoorssuyy" => ["asynchronously"],
      "aceeimnooprrst" => ["contemporaries"],
      "aeeeimnnnrsttt" => ["entertainments"],
      "ehhinoopssstty" => ["photosynthesis"],
      "aadefilmmnnstu" => ["fundamentalism"],
      "aaeiilnqtttuvy" => ["quantitatively"],
      "acdgiiiimnnrst" => ["discriminating"],
      "abeilnnoqstuuy" => ["unquestionably"],
      "aacfiiilmnopst" => ["amplifications"],
      "aaefiimnnosstt" => ["manifestations"],
      "abbeghiiloprrs" => ["bibliographers"],
      "diinooopprrsst" => ["disproportions"],
      "adeeeiiimnrrst" => ["intermediaries"],
      "aeeehllorstuxy" => ["heterosexually"],
      "abcelllnnoortu" => ["uncontrollable"],
      "accdeeimmnotux" => ["excommunicated"],
      "giilnnprrssuuy" => ["unsurprisingly"],
      "aeeeinprssssuv" => ["persuasiveness"],
      "acehhillopttyy" => ["hypothetically"],
      "eeloopprrsstuy" => ["preposterously"],
      "aacggilnnorttu" => ["congratulating"],
      "ceeeinnnoorstv" => ["conventioneers"],
      "aefhiilnnoprty" => ["hyperinflation"],
      "acegiilnnortuv" => ["countervailing"],
      "cegilmooossstt" => ["cosmetologists"],
      "abeeilnnoqstuu" => ["unquestionable"],
      "eeimoprssssstt" => ["postmistresses"],
      "aacceiiilprstt" => ["practicalities"],
      "aacddeilpqrtuu" => ["quadruplicated"],
      "acehhmmnrsstuy" => ["chrysanthemums"],
      "abdiiilnorsttu" => ["distributional"],
      "aadgiiimnnrstt" => ["administrating"],
      "bcccgiiimnrrsu" => ["circumscribing"],
      "aaeeegmnnprrrt" => ["prearrangement"],
      "aacghloopprsyy" => ["parapsychology"],
      "adeiillnoprtvy" => ["providentially"]}
    |> Map.get(string_id)
  end

  def valid_ids do
    ["aaceilnrtttuvy", "cdeeinoprsstuv", "aceeinoprrsssu", "aeeiimnnorsttx",
     "adeeehilnooprt", "aceghilllnooty", "aceiillnnooost", "aadehnorrssttw",
     "acillmmnnootty", "aceeeglmnorstt", "aaceiillnpstty", "abeeghiilnstux",
     "adeiiinnoorstt", "aaciiilmnoppst", "aainnooprrsttt", "aeegiilnnnrtty",
     "eeeegggiinnnor", "ccdeeeinnnortt", "aeghimmnooprst", "cddeeilnnostty",
     "acdeegilnnoqru", "ceefgiinnorttu", "acegiillmnoort", "eeeiilmnopssst",
     "elmopprsstuuuy", "aaaeglllmoprrs", "adefgiimnorrst", "aeegiilmnorsss",
     "ccdehhillnoors", "aeegginorrsssu", "aceeghilnorssu", "aaceghiloorsst",
     "adeeginnopprrt", "acegilmnnooort", "elnoopssstuuuv", "aceeghillnopry",
     "adeeehhllortwy", "abccginnorsttu", "ceeghinorrsttv", "abccnoorrssttu",
     "aacgillloottuy", "efhioopprrssss", "celmnoopsttuuy", "abdeeiilnnpsss",
     "aceghopprrrsty", "acegghhinooprr", "aaiillmnnosttu", "aceilnnnnootuv",
     "aacegiillllsty", "cceiimnnoopsst", "addeeeffiinrtt", "eehiilmnnqrstu",
     "acegilllmootyy", "acghiillnooort", "aacillmopsttyy", "abdeefiiilnntu",
     "acfgiinnoorstu", "acghiiinopsstt", "aaaccillorttuy", "accefiiinopsst",
     "eeeeinprrssssv", "aacdiilllmopty", "aceehimmnorssv", "aaddegghnrrstu",
     "aacghillloopty", "ceeeioprrssttv", "acdeiinnoorsst", "abeeiilmnoprss",
     "cceeeeeflnnort", "aabcillnooorst", "bcdeegiimnnrsu", "adeffgiinorsst",
     "ceeeilmnnopsst", "beeinooqssssuu", "aaceiinnnorrst", "aceeimmnnorstu",
     "aaccfiiilnorst", "accchloopsstuy", "aeeefghhirsttw", "ccdeeennooprrs",
     "aegiinnoopprrt", "adeeeimnrssttu", "aadeeinnprsstt", "ceeefinorrsttu",
     "aadiiilmnorstt", "aceillnnoosstt", "aacgilmnoopsst", "aaceehilllptty",
     "ccdegiimnnostu", "aachilnopsssyy", "aabcefiiinostt", "aeegiimnorsttv",
     "aaeiimoppprrst", "bhiiiinooprstt", "aacdeeimnnostt", "abcceiillnorry",
     "aeginnorrsssst", "aegiinnoorrstt", "dgghiiiinnsstu", "aadiiilnorsttt",
     "cceiillnnosuvy", "acchiilloprtyy", "aeeggiinorsstt", "acceehhloorsst",
     "efghhlnossttuu", "cegiinnorstttu", "abcelnosstuuuy", "aaeehimnrssstu",
     "aaeginnnprstuu", "ccgiilnnnnouvy", "aeefgilmnnnssu", "ehiiooppprrrst",
     "eeeinnoprssssv", "aaabcehlnoppru", "acdeiiinorsssy", "abcinoooorrrst",
     "ceeefimnnorrst", "aadiimnorrsstt", "aaaeiiilmprrst", "aaaccehilmprtu",
     "cdeennooprrsst", "aadehiioprrstt", "aaadeillqrrstu", "abdefiillorrst",
     "aabbefggilnrst", "abdeilmorstuxy", "aaacehiimmnstt", "cceginnorrsttu",
     "aeegiinorrsttv", "aeeiimnoorsttv", "aacciilmnrsttu", "acilrrssstttuu",
     "aaimnnorsstttu", "beeiimnsssssuv", "bcdeiilnrsttuy", "aacdeeffgiinnt",
     "acefiiilmnostu", "acdeghillmooot", "aeeiilmnnssttt", "aaceiilnoprttu",
     "eeeiimnprssssv", "ceeeegiilnnort", "eeeellnnrsssst", "aacciiilmprtty",
     "ccdenooprrstuu", "ceeilmnopsssuv", "bdegiiinrrsttu", "acgghiklnosstu",
     "aabddeelnnrstu", "bceeehilmnoprs", "acginoooprrstt", "aabcccghiknrst",
     "acdefiiinoottx", "adeeeggimnnsst", "cdeeeiiinnsssv", "aaceilnnoorstv",
     "ahiimnoprssstt", "abeegiinrssssu", "aaaeeginnprstu", "deeiiiilmrstuv",
     "cceeinnoopprst", "aegiilnnnrstty", "beegiiilllnntu", "aeeiilmnnsttty",
     "acgiimmnoorrss", "accefiiinorstt", "eeehiinprsstvy", "aadddeeehhnrss",
     "beeinoorsssstu", "giiinnooopprst", "aefillnooprssy", "aacfinorssttuy",
     "aaeilnoorstuvv", "aacchilllossty", "aciinnoprrsstt", "adiilnoprssttu",
     "aadeiiimnrsttv", "aceeinoorrsstv", "aaahiinorrsttu", "aaceeinnprrsst",
     "bdiiiiiilnstvy", "aabcdeginorrst", "aacegillloopty", "acceinoopprstu",
     "aaiimnoopprstx", "cceghiklnosttu", "aeiiilnnrsttvy", "efggiiinnnprrt",
     "aaaiinnossssst", "ddeehinnorrsuu", "ceeehimnoprssv", "aaceinoprrsstt",
     "aacfgiiimnnost", "aaceghilllmpty", "cceeeffiiiinns", "abcchhiioprrss",
     "ceeilmnossstuu", "aeeiiilmnssttx", "bdehiiloorrstt", "bbcdeeiorrssuv",
     "aiinnooprssstt", "acceegillnorty", "aeginorsssttuu", "cceeinorrsttuv",
     "accehilmmnopst", "abenoorrssstuu", "aadeeilnrrsttt", "cceelnorrttuuu",
     "ceiilnnnosstty", "cdeinoooprrtuv", "eegilnooprrvwy", "aeeegginrssssv",
     "aaaccdilorrsuv", "acdeeghiinnruv", "aaeffiimnorrst", "aeeeeinprrsttv",
     "abdeggiknnorru", "bdeegiiillnsvy", "aabeghiiilnrtt", "cceeeiinnnnosv",
     "addeimnnrssstu", "deeegilnooprvv", "acdeefhiinnrss", "adeeghhillrtty",
     "aceiiiilnpprst", "acceemnorrsstt", "aaggiilnnosttu", "bceehilmnoprsy",
     "aaceklnnorstuy", "aacfgilnnoorst", "abciiilnrsttuy", "aiijnoopssttux",
     "aaceeinrsstttv", "acdiilnooorsst", "abeeilnnssttuu", "aacdeimnnnottu",
     "eegilmooorsstt", "aeeiilmmnnoptt", "aceiiinopprstt", "aacehiinnotttu",
     "ceemopprrsstuu", "chiilorrstttuu", "addeeeeghlmmrs", "acdeiiilnnortu",
     "aacdeiilnosttu", "acdegimnnnortu", "aceiiillmpttuv", "aacdgiiinnosst",
     "acceeimmnostux", "aaceghimnoprty", "ccciilmnoortuu", "ceeiimnnoopttv",
     "aaailnnnorsstt", "aehimnnoorsssu", "aehhiilnopprst", "abeeehlnrsssst",
     "aiiimnooprsstv", "ceeehimorsstty", "acccgiimnnrstu", "adeggiiinnrstt",
     "eeeinopssssssv", "cddeeiinnooprt", "abcdeeehiilnpr", "aacdeiiilllsty",
     "aeeilnoortttxy", "aaceeffilnotty", "ceiiiinossttvv", "aehimoopppsstu",
     "aabcciilnottuy", "acceiinoprsssu", "ceemnnnooprstu", "acdeeimmnnoort",
     "aacffiiilnosst", "abdeehiilsssst", "aeiinoopprrstx", "bdgggiillmnnoy",
     "acefinrrrsttuu", "achiioprssstty", "aaccillnooptuy", "aafimnnoorrstt",
     "diiiinnoopssst", "aabdeeehhirrss", "aeeemnorsstttv", "aeehinpppprrsw",
     "accdeiillnnoty", "aaceiinoprrstv", "aceiiimmnoorss", "eeegiinnprrrtt",
     "abeelnnnorrstu", "aacdeinoprrstt", "accceimmnooors", "cdelmnnoooosty",
     "acddeegklnnouw", "ciinnooorssttt", "aaaegiiilmnrst", "aacdeeijkrsttt",
     "aadehorsssttuw", "acdeeeiosssttv", "abeeilmnnnostu", "adeeehimrsssst",
     "aaacceghilloor", "aehiioorrssttt", "aaadeglnostuvy", "eiilnoorssttuv",
     "aabbeiillosssu", "acfiilnnossttu", "bcdeeiilnrsttu", "cgiiilmnoorsst",
     "acegiilnossttu", "aceghlnnnoooty", "aaeegilnprstxy", "aeillmnosstuuy",
     "cceimoooprrrss", "abeeeinorrrstv", "acdeeennopprrs", "aacdeglmnnorss",
     "aaceghiinntttu", "acceeiinnoorss", "beeehillmmnsst", "acfgiiiinnosst",
     "abcdenooorrrtu", "aaacehimoopprs", "achiiinoopsstt", "aefiiiilmnnsst",
     "cdeiiinnnssstt", "abcegiiloorstt", "ceeeiooprrttvv", "aacehlnopsssyy",
     "adehorsssttuww", "aceeemnorrstuu", "cdeeiiinnsstvv", "adeeiinnoprstt",
     "acdeegimnorstu", "acegiillorssuy", "aadeeghinqrrtu", "eefimnnoorrstw",
     "bcceeikkknorrs", "begilnorsssuuu", "aadeegimnnrrst", "acdeeeimnoppst",
     "ccdeiinnnoosst", "deeeeillmmosss", "aefgiimnorrsst", "ghiilnooorsstt",
     "aceeggimnnorrs", "acdiiiilnnnost", "aacceknorstttu", "ceiinoprsssstu",
     "cegiiknnnorstu", "aabceenrsssstt", "aaehiiimnnsstt", "ceefiinnossstu",
     "acfinnnooorstt", "acffiiinoorstt", "ccefllnsssuuuy", "acceehilmoprst",
     "accdhhinooprsy", "aacchilnopstyy", "aeffhilnnsstuu", "aaelnoprsttuuy",
     "aaeilnooprsttx", "aeeeinnoprrstt", "beeeinrssssuvv", "aeeiilnnorrstt",
     "accceillnnorty", "acdeeenrrrstuy", "aaiinooppprrst", "aeiimnnooprsst",
     "cceeiinnossttu", "beeeimmnrrsstu", "abeeghiilnrsst", "abbeghiiiloprs",
     "deehhnorrsstuw", "aeegiimnnnortu", "acceinnnoorstt", "aaccegiimnrtuv",
     "acehiinnssttuu", "abclllnnoortuy", "acdehhiimoprrt", "eeeilnoprssssx",
     "aceeeeinnrrstt", "aabcdeennprsuu", "aabcefgiinprrt", "accinprssttuuu",
     "ceeinnosssstuu", "aaceeghnooprrs", "adeeeffiinrstt", "acfiiilnostttu",
     "aabcefiiinottu", "aeegiiilrrrstu", "aacinooprrrstt", "ceiiiillmpsttu",
     "ddeeeeinnnprtt", "abcdeeehilnpru", "aaabdhimoprsss", "adeeegoprrstuy",
     "aacghilmooprst", "acfgiilmnnnotu", "abbcdeilmoostu", "aabeilmnoprstu",
     "aabegiillnosuv", "cfimnnnooorsst", "aciiiilprssttu", "ccceeeiiinrstt",
     "addeeegoprrtuy", "aeeeiinprrtttv", "eefiiilmoprssv", "deefiiilmoprsv",
     "adeiimnnoppstt", "aeeeiiinnprstt", "aeeiinnoprrttt", "aabdeiikmnorst",
     "aceillnnnootvy", "ceeghinorsttuw", "dddeeeelnopruv", "acdeefinnoorst",
     "accefgiiiinnns", "aacehiillnttty", "aeeeillmnprtxy", "abcceilnnnoosu",
     "aadefgghinnrrt", "aabchilooprstu", "aaabcehilllpty", "aabcefiinoprrt",
     "aachlnopssstyy", "ccdeeeiinnnnov", "aacglnoorrttuy", "aabeiiilnprsty",
     "aeeehilnprttvy", "ceeiinnorrsttv", "aacciillmnostu", "aillnooopprrty",
     "aaeiilnnossstt", "aaeeilnnprrtty", "aeeghhlorsstuu", "aacegghillopry",
     "behiiiinossttx", "afiiimmnnoorst", "adeeeimnrssttv", "abcdeeiilnnors",
     "aaeiilmnnossst", "beeeillnorsssu", "aabcdeeinrrstt", "aacdeelnnnrstt",
     "bccilnoosssuuy", "deegiiilmoopst", "accdeeinnnostu", "deeeelmnoprstv",
     "acdeiiiimnnrst", "eehiinoopssttv", "aceehiinppprst", "aceinnnooooprt",
     "acdiilnnooosst", "aceeghhooprrrs", "achiiillnorsty", "aaeiilnnnorstt",
     "aefimnnoorrstw", "aaciilnooprrst", "adeelnnopprrty", "aeilnooopprtuv",
     "adiiilnrsssttu", "adegilmoorsstt", "aciiilnopssuuy", "acgiiilllnstuy",
     "aabehiiilnortt", "eeghillmnorvwy", "acehilmoprsstt", "adeiilnosttuvy",
     "beefhimnrrsstu", "ccehhiinoprssz", "aacceinnnoostt", "aaceillmmrstyy",
     "aaeemnnopprsww", "abefllnoopsstu", "aaeeegmnnrrrst", "aeegillmnorrst",
     "adfiiimnnoorst", "aadefilmnnsttu", "aacfiiinnoqttu", "aegiiinnossttv",
     "acdggiilnorsuy", "aefilnooprsssw", "aabegilmnrrssy", "ccceiimmnooors",
     "aacddeeimnnott", "abegiiilmnprty", "aaellnprrstuuy", "aciiillmnopttu",
     "cgiimmnnooprsu", "addeeehimnpprs", "aeeiilmmnnsstt", "aceegillnoprtt",
     "cehilmoorsssst", "deeegiimnnprrt", "aaccfiiilnosst", "acfiiijnossttu",
     "acceehiiilnstt", "abcdeiiilprtty", "aabceeilllmmty", "aabeghiklnrtty",
     "ccdeimnoorsstu", "aefilnnooprssu", "acdiiijlnorstu", "aeeemnooprstux",
     "cdeiilnorsssuu", "bceiiilpssttuy", "aaaaghimnoprst", "aeeiiilnopsttt",
     "aeghiilnnsttuy", "accefiiillnsty", "aceehmnopprrst", "deimnooprssstt",
     "eeeiopprrrssst", "acfiiijllnoost", "cddeeiimmnooss", "adeeemnnrstttu",
     "ceffiiilnnstuy", "aaccfiiinnostt", "accdeeilmnortu", "bbciiilmosttuy",
     "aaeelnnnpssstu", "abdeeeiilmnnrt", "aacceimmnnopst", "adgiilllnnotuy",
     "aceginooprsstt", "acdfiiiilnoost", "acceeilllnorty", "aaccceeiillsst",
     "acdiiiimnnorst", "acdefiillnnoty", "aceeemnooprstv", "ceehhnoopprsst",
     "aaceiimmossttu", "aaabcelmmnnouw", "ddeeiilnorrsss", "eeghilnoprrstu",
     "aagiimnnorrstt", "accegiilnrtuxy", "aaccdeillmorty", "accceeelnnossv",
     "aacfiilorsstty", "ccdeinnoorsttu", "aacfiiilnoqstu", "bdeiiorrrssttu",
     "cccilmoorrtuuy", "addeeeimnrsttu", "aacegiilnprttu", "aceiiiilmnpstu",
     "abiiiillmpstuy", "acefiiilprstuy", "aceiilnossssuv", "aciiilllmpssty",
     "addeeeimnprttu", "defgiiiimnnsty", "aeeinoqrsssttu", "aacehiillmrtty",
     "aceeelmnoprtux", "abceeeefnrssst", "adeimnnoorsstt", "cdegiiinnnoort",
     "deeegknoprrssu", "aaceeiilpprtvy", "aciilllmooqssu", "aacillmnoorsty",
     "bdeehlooorsttu", "aaceggilnnoort", "acdeillnoossty", "ceiijnooprsstt",
     "aaeinnnoprstuu", "aabciiilnrttty", "acceilmmnnoors", "ceeeehlnpsssss",
     "eeimnorsssstuy", "abeeeikkrrrsst", "eeeeinprssssvx", "acdehimmnorsty",
     "aaaddggiinnstv", "aabcegiknqrrtu", "aaaccgiiinnptt", "aegilnoopprtuv",
     "ceehimnnooprss", "abeegiikknrrst", "ddeeeimnnnortu", "aeeemnnopprsww",
     "addiiiilnsstuv", "aabceelmmnnouw", "accgiilllooosy", "accdiinnoorstt",
     "aacdeilpqrstuu", "aceinnnoorsttv", "cdeiloorsstuuy", "aeeegillnssttv",
     "aeiilnnooprstt", "aacdeiilnorstv", "ceeiilnnnnotvy", "ceginrrrssttuu",
     "acgiillmoosstt", "begiiilllnntuy", "ahhiilnopprstt", "aaccehhiillrry",
     "deeeinnnprsttu", "aehhinopprstty", "cceeinooprsssu", "eiiimnoprsssst",
     "ceeeeinpprsstv", "acdeeehinrrsuv", "aiilmnooprssuy", "acdeeilnpprrsu",
     "deefgiimnrsstu", "aeeefillnprrty", "ceiinnoorstttu", "acefgiiinnortt",
     "aghilnoooprstt", "aceeilmnopsttv", "aabcceelnnortu", "aaacehillmmtty",
     "aacilllnorstuy", "aeeiinnoqrsstu", "aaeeilnrrssttt", "degiilnnossuuy",
     "aaccdimmnooost", "ehiorrssttttuw", "deiiinoopprsst", "aaaehimoprrstt",
     "ceeprrrssttuuu", "abdeiiilnrstuy", "aacdgiiinossst", "aabddelnnrstuy",
     "abeehilmnssstt", "bcgiiilmooorst", "aeeiinnnoopttx", "deghhilorsstty",
     "eeiinoprsssstx", "aabcciiilprtty", "adeeimnorssttv", "aaceeggilllnoy",
     "aadiiimnnorstt", "deegiinnnprstu", "beiiilnoprssty", "aabdeginorrstw",
     "adegiiinnorstt", "aceiimmnoorsst", "aaceeiinpprtuv", "ceggiinnnorstu",
     "acdeehimnnnstt", "cllnoprssuuuuy", "aegginoossttuu", "aacceiinnorrst",
     "aaceilnnopsstu", "ceefiinoprsstt", "aceelmmnorstuy", "cceilnorsttuvy",
     "aceeillllnttuy", "aadeeiinorrrtx", "befgillnooprtu", "aeilnoopssttux",
     "ccceeefimnrrsu", "aacgillloorsty", "aabcehiloprrry", "aceggillnooort",
     "aceeghiloprrsx", "abeilmnnorstuu", "adeeggimnnrrry", "aceggilmnnoort",
     "acefiiiinortvv", "aceimmmnooorst", "bdeiiinorrsttu", "acciimmnnoostu",
     "dgiiiillnnossu", "acehinoorrsstt", "ceeeinoprssttv", "aceiinopssssuu",
     "cdeekklnrsstuu", "cdeeinnooprttu", "bceiiilnorttvy", "aaacfiilllstty",
     "cciiijnnosttuv", "aaceeilmmnsstu", "bciimnoorssttu", "efghhinorrsstt",
     "aacdhimoosssst", "bbceeiorrsssuv", "abdeghinoorssu", "acceiiilnnoort",
     "aaceiillnrttuy", "abddeeefghinrt", "beehlooorrsttu", "acfiiiilmnopst",
     "cdeeegilnnoruv", "aacceeinnnorss", "aacfiiinorsttt", "eiinooppprsstu",
     "ccceiimnoprstu", "aceeegmnnorstu", "aabceilnorsstu", "adefiinosssstu",
     "acciiillooopst", "aacdiiiilnnprs", "aabdeeefhinrrt", "aaeggilmnoorst",
     "aacdeeginrrrsu", "eefghinnoorrst", "adeehhimoprrst", "aacfgiiinorstt",
     "aadeiilmnnnoot", "adeeiimnnorstt", "eggilnooorsstt", "aciilnnoostttu",
     "eeflnopprsssuu", "aaiiiilmnrsttu", "cgiimnnnooprsu", "eiilnoqrssttuv",
     "adgiilnopprsvy", "bciinoorsstttu", "aabeeelnnorsss", "aaeiinnpprrstt",
     "aacehillmoprty", "aeegiiilllmtty", "aacccehiirrstt", "eennooprsssttu",
     "ceiinooprssttt", "aaacdeeinpprss", "aeeehilnpprsvy", "aciinnnooprstu",
     "cdeeimnnnosttt", "cdeeeennpsstux", "adeeefimnnoort", "addeginnnrsstu",
     "adeefghinrssst", "aabceehiloprrr", "cceeilnoorsttu", "acdiiinnnoortt",
     "cceinnoorrsttu", "aaeegiimnrrrst", "aacgilnnoorttu", "aaggiiilnnrtty",
     "aceiillmnnooos", "aeeiilnnqssttu", "cegiiilnoorsst", "aciiillmopstty",
     "acdiiimnorrsty", "aabdgiiimnostu", "adeeefhooprrtw", "aeeeeinnprrttt",
     "acdefiiiinnott", "aaccgiillmnstu", "aaceeilnrssttu", "acceeinoprsttv",
     "eeeggiinprrrst", "aabiinnosstttu", "aaeemqrrrssttu", "deefiilnnnrssu",
     "aceeilnorstvvy", "aabeemmnrrssst", "aaaabcceelrstu", "eeiilmnnrtttty",
     "ceeiilnnossstu", "acceinnoorsttu", "deeeeimnprrsst", "aaddeegnrrstuu",
     "aaeimnorsssttt", "adehilnnossstu", "acdgiiinnnortt", "accdeiinnnostu",
     "adehnorrssttww", "abddeehiilssst", "eeeghilnsssstw", "ceiilnoosssstu",
     "aabgiinnsstttu", "abcceeiillnorr", "deeeiimnprrstt", "ccddeeilnnosty",
     "aabdiinoopprst", "acceghiillnnou", "aeefglnnrsstuu", "ddeeghhinrstuw",
     "acdeginooprstt", "aaciilllrsttuy", "aeegiiillnnstt", "aceegillmooort",
     "abcchilooprstu", "eeeinopprssssv", "cceimmooprrstu", "aachiillnnostu",
     "aaacgilnnosttu", "ceiilloprssuuy", "aceiiimnnorrst", "aeegiinnoprrst",
     "aeiiilorrrttty", "abccilnnnoosuy", "eehilloorssstt", "aaggiimnnrrstt",
     "abceeiilprstty", "aeilnoosstttuy", "ccdeginnorsttu", "eehiimmnoprstv",
     "deeeeimnprrrst", "bdeiiiilmqrsuu", "acdfghiiinnrss", "egiiiinnoqrstu",
     "aabiiilnssttuy", "eeginnoppssstt", "aaceillmssttyy", "aeeiiilnsstttx",
     "eeeeilprrtttwy", "achlnnoorssuyy", "aceeimnooprrst", "aeeeimnnnrsttt",
     "ehhinoopssstty", "aadefilmmnnstu", "aaeiilnqtttuvy", "acdgiiiimnnrst",
     "abeilnnoqstuuy", "aacfiiilmnopst", "aaefiimnnosstt", "abbeghiiloprrs",
     "diinooopprrsst", "adeeeiiimnrrst", "aeeehllorstuxy", "abcelllnnoortu",
     "accdeeimmnotux", "giilnnprrssuuy", "aeeeinprssssuv", "acehhillopttyy",
     "eeloopprrsstuy", "aacggilnnorttu", "ceeeinnnoorstv", "aefhiilnnoprty",
     "acegiilnnortuv", "cegilmooossstt", "abeeilnnoqstuu", "eeimoprssssstt",
     "aacceiiilprstt", "aacddeilpqrtuu", "acehhmmnrsstuy", "abdiiilnorsttu",
     "aadgiiimnnrstt", "bcccgiiimnrrsu", "aaeeegmnnprrrt", "aacghloopprsyy",
     "adeiillnoprtvy"]
    |> Enum.into(HashSet.new)
  end
end
