defmodule Jumble.ScowlDict.Size55.Length16 do
  def get(string_id) do
    %{"aeeghiilnnprttvy" => ["hyperventilating"],
      "deehimnnnorrstuu" => ["undernourishment"],
      "aceeiilnnnnorttt" => ["intercontinental"],
      "adeeiimnnorssttu" => ["underestimations"],
      "aacehillmorsttty" => ["thermostatically"],
      "acdefiiiimnnnost" => ["indemnifications"],
      "acdeeeehimnnrtuv" => ["underachievement"],
      "bceehiilmnnoprsy" => ["incomprehensibly"],
      "ceehilmoorssssst" => ["schoolmistresses"],
      "aaeeeilrrrrstttx" => ["extraterrestrial"],
      "aaeeeilnnoprrstt" => ["representational"],
      "aeeeiinnoprrrttt" => ["reinterpretation"],
      "aeeimnnorrrstttu" => ["neurotransmitter"],
      "aaaacghilmnoprst" => ["phantasmagorical"],
      "aabiiilnnnnotttu" => ["tintinnabulation"],
      "abeiiiiillmpsstu" => ["implausibilities"],
      "aabeeelnnnorsssu" => ["unreasonableness"],
      "aaacchilloprstty" => ["catastrophically"],
      "cciimnnoorsssttu" => ["misconstructions"],
      "aacghhillooprrty" => ["orthographically"],
      "accdegiinnnnostu" => ["discountenancing"],
      "bceiilnnoorrttvy" => ["incontrovertibly"],
      "abeeghiiilnnstux" => ["inextinguishable"],
      "abceimnnorssstuu" => ["rambunctiousness"],
      "aacccehiinrrsttu" => ["uncharacteristic"],
      "aefilnnnoooprsss" => ["nonprofessionals"],
      "eeeehinnpprrrstu" => ["entrepreneurship"],
      "aadeiiilmnrsttvy" => ["administratively"],
      "aeeiinoprrsssttv" => ["preservationists"],
      "aaeiiilnnnorsttt" => ["internationalist"],
      "aaaaeiilmnnprrst" => ["parliamentarians"],
      "ccceeiilmnoorrst" => ["microelectronics"],
      "acdgiiiimnnnrstu" => ["undiscriminating"],
      "bceeiiiilpsssttu" => ["susceptibilities"],
      "aefillnnooprssuy" => ["unprofessionally"],
      "aeeegiinnnprrttt" => ["interpenetrating"],
      "aacciillmnrsttuy" => ["circumstantially"],
      "aeeiillnnqssttuy" => ["quintessentially"],
      "aaacdeilllmmorty" => ["melodramatically"],
      "abbcdgiilmnoostu" => ["discombobulating"],
      "acehhiopprssstty" => ["psychotherapists"],
      "aceefiiilmnopstx" => ["exemplifications"],
      "aaceilnnnnorsttt" => ["transcontinental"],
      "adeiinooopprrstt" => ["disproportionate"],
      "bbbbeefgiiilrstt" => ["flibbertigibbets"],
      "cdeehiinorrssttw" => ["creditworthiness"],
      "ahijlnoooprssttu" => ["photojournalists"],
      "eeiiinnnorsstttv" => ["interventionists"],
      "abcdeiiilnprttuy" => ["unpredictability"],
      "deeflnooprsssstu" => ["dessertspoonfuls"],
      "ceeiilnoprssssuu" => ["superciliousness"],
      "aaaccehiinnpqstu" => ["acquaintanceship"],
      "aaceeiilnnrssttu" => ["inarticulateness"],
      "adeeeghhilnrsstt" => ["lightheartedness"],
      "aceeeinnoorsstvv" => ["neoconservatives"],
      "aehhiiopprssstty" => ["physiotherapists"],
      "bdehiilnoorssstt" => ["bloodthirstiness"],
      "achiillorrstttuu" => ["horticulturalist"],
      "bciiiilnoprrttuy" => ["incorruptibility"],
      "aeeeiinnnoprrttt" => ["interpenetration"],
      "aaiiimnooppprrst" => ["misappropriation"],
      "cceeeefgilnnnort" => ["teleconferencing"],
      "acefiiinnooprsst" => ["personifications"],
      "aaccegiknnortttu" => ["counterattacking"],
      "aaceghhillnoprty" => ["ethnographically"],
      "aacghhilloopprty" => ["photographically"],
      "aciilnnnoostttuu" => ["unconstitutional"],
      "aceegmnnorrsttuu" => ["counterarguments"],
      "ahhimmnooopprrst" => ["anthropomorphism"],
      "aaceeghimnoprrst" => ["cinematographers"],
      "aeeelmnooprstuxy" => ["extemporaneously"],
      "aaeiilnnorrssttt" => ["transliterations"],
      "aacehiillnssttuy" => ["enthusiastically"],
      "aabciillnooorstt" => ["collaborationist"],
      "aaceillnnoorstvy" => ["conversationally"],
      "acgiinnoooprsstt" => ["prognostications"],
      "aaccdefiiilnosst" => ["declassification"],
      "acdeeeeinrrrsstu" => ["undersecretaries"],
      "aaccggiiimnnrtuv" => ["circumnavigating"],
      "aeehiinoprrssstw" => ["praiseworthiness"],
      "aceeiiloorrrssst" => ["arteriosclerosis"],
      "acdeghilllmoooty" => ["methodologically"],
      "ceiiinnorrsssttu" => ["insurrectionists"],
      "aceeimnnoooprstv" => ["overcompensation"],
      "bceeiilnnoorrttv" => ["incontrovertible"],
      "aaabcghiilooprtu" => ["autobiographical"],
      "abdeehiilmnssstt" => ["disestablishment"],
      "aaacgiillnnostty" => ["antagonistically"],
      "cceeiinnnnoorstt" => ["interconnections"],
      "aaacciillorrstty" => ["aristocratically"],
      "ceeeffinnoorstuv" => ["counteroffensive"],
      "acciiimmmnnoostu" => ["miscommunication"],
      "acceiimmnnoostux" => ["excommunications"],
      "aaaacdgiillmmrty" => ["diagrammatically"],
      "aaceeknnnorssstu" => ["cantankerousness"],
      "aeeeehinnpprsssv" => ["apprehensiveness"],
      "aacgiillrrssttuu" => ["agriculturalists"],
      "ccceeiklnoorstuw" => ["counterclockwise"],
      "aceiinnoorsssttv" => ["conservationists"],
      "acdeiiiilmnnrsty" => ["indiscriminately"],
      "celnnoprssssuuuu" => ["unscrupulousness"],
      "addegiimnnnrsstu" => ["misunderstanding"],
      "aghhillmooopsstt" => ["ophthalmologists"],
      "aaciillnooprrsty" => ["conspiratorially"],
      "aaeeiilorrrrtttx" => ["extraterritorial"],
      "aaegiilnnorssttt" => ["gastrointestinal"],
      "aceehiinorssttuv" => ["overenthusiastic"],
      "aaaefilnoopprrss" => ["paraprofessional"],
      "ccdeehiilorrttyy" => ["hydroelectricity"],
      "eemnopprsssstuuu" => ["presumptuousness"],
      "ccciiimnoprrsstu" => ["circumscriptions"],
      "aeiilmnnrssstttu" => ["instrumentalists"],
      "aabccegilnnnortu" => ["counterbalancing"],
      "aaaacchhillmsttw" => ["whatchamacallits"],
      "aaccghilloprrsty" => ["crystallographic"],
      "ccdeefiiimmnnouy" => ["immunodeficiency"],
      "aefiilmnorssstuu" => ["multifariousness"],
      "aceeeginnooprstu" => ["counterespionage"],
      "aceeegilmmnorstt" => ["electromagnetism"],
      "aeefiilmnooprsss" => ["semiprofessional"],
      "aaahiiimnorrsttu" => ["authoritarianism"],
      "aeehiimnnopprsss" => ["misapprehensions"],
      "aaabcceillrrtuuy" => ["bureaucratically"],
      "bdhiiioprrsssttu" => ["distributorships"],
      "aeeiilmnnnorsttv" => ["environmentalist"],
      "aaccgiiimnnortuv" => ["circumnavigation"],
      "acdiiinnnoossttu" => ["discontinuations"],
      "eehiiinprssttvyy" => ["hypersensitivity"],
      "cgiilmmnnooprsuy" => ["uncompromisingly"],
      "eeeillnoprssssxy" => ["expressionlessly"],
      "beiiiilnoprrssty" => ["irresponsibility"],
      "abbeiiilmprrttuy" => ["imperturbability"],
      "aceegimnnooprstv" => ["overcompensating"],
      "acdeefhiimnnrsst" => ["disfranchisement"],
      "aceillnnnnootuvy" => ["unconventionally"],
      "aaacceghillloory" => ["archaeologically"],
      "aaccdiiinnnoortt" => ["contraindication"],
      "aabcciiiilmprtty" => ["impracticability"],
      "aacchiiillnstuvy" => ["chauvinistically"],
      "acdefghiiinnnrss" => ["disenfranchising"],
      "eeghinooppstttty" => ["phototypesetting"],
      "aciillnnoostttuy" => ["constitutionally"],
      "aeeiilmmnnnorstv" => ["environmentalism"],
      "aacdeellnnnrstty" => ["transcendentally"],
      "deeghhinorsssstt" => ["shortsightedness"],
      "aeeeeinnprrsttuv" => ["unrepresentative"],
      "aaeiiilmnnnorstt" => ["internationalism"],
      "aceeghillmnnooop" => ["phenomenological"],
      "bceeehiilmnnoprs" => ["incomprehensible"],
      "aefiilnnnoooprrt" => ["nonproliferation"],
      "aciilllmmrsttuuu" => ["multiculturalism"],
      "aeehiilnnoprttvy" => ["hyperventilation"],
      "adeiiillmmnnostu" => ["multidimensional"],
      "aeiiiilllmmnortu" => ["multimillionaire"],
      "aagiiimnoppprrst" => ["misappropriating"],
      "aacdfiiiilnoqstu" => ["disqualification"],
      "abdeiiiilnnpssty" => ["indispensability"],
      "beeiiiilnoprssst" => ["responsibilities"],
      "beeenooprrsssstu" => ["obstreperousness"],
      "aciiimnnnooprstu" => ["mispronunciation"],
      "adeeeiimnnoprrtt" => ["predetermination"]}
    |> Map.get(string_id)
  end

  def valid_ids do
    ["aeeghiilnnprttvy", "deehimnnnorrstuu", "aceeiilnnnnorttt", "adeeiimnnorssttu",
     "aacehillmorsttty", "acdefiiiimnnnost", "acdeeeehimnnrtuv", "bceehiilmnnoprsy",
     "ceehilmoorssssst", "aaeeeilrrrrstttx", "aaeeeilnnoprrstt", "aeeeiinnoprrrttt",
     "aeeimnnorrrstttu", "aaaacghilmnoprst", "aabiiilnnnnotttu", "abeiiiiillmpsstu",
     "aabeeelnnnorsssu", "aaacchilloprstty", "cciimnnoorsssttu", "aacghhillooprrty",
     "accdegiinnnnostu", "bceiilnnoorrttvy", "abeeghiiilnnstux", "abceimnnorssstuu",
     "aacccehiinrrsttu", "aefilnnnoooprsss", "eeeehinnpprrrstu", "aadeiiilmnrsttvy",
     "aeeiinoprrsssttv", "aaeiiilnnnorsttt", "aaaaeiilmnnprrst", "ccceeiilmnoorrst",
     "acdgiiiimnnnrstu", "bceeiiiilpsssttu", "aefillnnooprssuy", "aeeegiinnnprrttt",
     "aacciillmnrsttuy", "aeeiillnnqssttuy", "aaacdeilllmmorty", "abbcdgiilmnoostu",
     "acehhiopprssstty", "aceefiiilmnopstx", "aaceilnnnnorsttt", "adeiinooopprrstt",
     "bbbbeefgiiilrstt", "cdeehiinorrssttw", "ahijlnoooprssttu", "eeiiinnnorsstttv",
     "abcdeiiilnprttuy", "deeflnooprsssstu", "ceeiilnoprssssuu", "aaaccehiinnpqstu",
     "aaceeiilnnrssttu", "adeeeghhilnrsstt", "aceeeinnoorsstvv", "aehhiiopprssstty",
     "bdehiilnoorssstt", "achiillorrstttuu", "bciiiilnoprrttuy", "aeeeiinnnoprrttt",
     "aaiiimnooppprrst", "cceeeefgilnnnort", "acefiiinnooprsst", "aaccegiknnortttu",
     "aaceghhillnoprty", "aacghhilloopprty", "aciilnnnoostttuu", "aceegmnnorrsttuu",
     "ahhimmnooopprrst", "aaceeghimnoprrst", "aeeelmnooprstuxy", "aaeiilnnorrssttt",
     "aacehiillnssttuy", "aabciillnooorstt", "aaceillnnoorstvy", "acgiinnoooprsstt",
     "aaccdefiiilnosst", "acdeeeeinrrrsstu", "aaccggiiimnnrtuv", "aeehiinoprrssstw",
     "aceeiiloorrrssst", "acdeghilllmoooty", "ceiiinnorrsssttu", "aceeimnnoooprstv",
     "bceeiilnnoorrttv", "aaabcghiilooprtu", "abdeehiilmnssstt", "aaacgiillnnostty",
     "cceeiinnnnoorstt", "aaacciillorrstty", "ceeeffinnoorstuv", "acciiimmmnnoostu",
     "acceiimmnnoostux", "aaaacdgiillmmrty", "aaceeknnnorssstu", "aeeeehinnpprsssv",
     "aacgiillrrssttuu", "ccceeiklnoorstuw", "aceiinnoorsssttv", "acdeiiiilmnnrsty",
     "celnnoprssssuuuu", "addegiimnnnrsstu", "aghhillmooopsstt", "aaciillnooprrsty",
     "aaeeiilorrrrtttx", "aaegiilnnorssttt", "aceehiinorssttuv", "aaaefilnoopprrss",
     "ccdeehiilorrttyy", "eemnopprsssstuuu", "ccciiimnoprrsstu", "aeiilmnnrssstttu",
     "aabccegilnnnortu", "aaaacchhillmsttw", "aaccghilloprrsty", "ccdeefiiimmnnouy",
     "aefiilmnorssstuu", "aceeeginnooprstu", "aceeegilmmnorstt", "aeefiilmnooprsss",
     "aaahiiimnorrsttu", "aeehiimnnopprsss", "aaabcceillrrtuuy", "bdhiiioprrsssttu",
     "aeeiilmnnnorsttv", "aaccgiiimnnortuv", "acdiiinnnoossttu", "eehiiinprssttvyy",
     "cgiilmmnnooprsuy", "eeeillnoprssssxy", "beiiiilnoprrssty", "abbeiiilmprrttuy",
     "aceegimnnooprstv", "acdeefhiimnnrsst", "aceillnnnnootuvy", "aaacceghillloory",
     "aaccdiiinnnoortt", "aabcciiiilmprtty", "aacchiiillnstuvy", "acdefghiiinnnrss",
     "eeghinooppstttty", "aciillnnoostttuy", "aeeiilmmnnnorstv", "aacdeellnnnrstty",
     "deeghhinorsssstt", "aeeeeinnprrsttuv", "aaeiiilmnnnorstt", "aceeghillmnnooop",
     "bceeehiilmnnoprs", "aefiilnnnoooprrt", "aciilllmmrsttuuu", "aeehiilnnoprttvy",
     "adeiiillmmnnostu", "aeiiiilllmmnortu", "aagiiimnoppprrst", "aacdfiiiilnoqstu",
     "abdeiiiilnnpssty", "beeiiiilnoprssst", "beeenooprrsssstu", "aciiimnnnooprstu",
     "adeeeiimnnoprrtt"]
    |> Enum.into(HashSet.new)
  end
end
