defmodule Jumble.ScowlDict.Size70.Length4.Dict do
  def get do
    %{"cder" => ["cred"], "grsu" => ["rugs"], "ekow" => ["woke"],
      "hstu" => ["tush", "huts", "shut", "thus"], "eilw" => ["lwei", "wile"],
      "adgn" => ["dang"], "eilm" => ["lime", "mile"], "ilmy" => ["limy"],
      "hloy" => ["holy"], "afos" => ["oafs", "sofa"], "akln" => ["lank"],
      "aefv" => ["fave"], "gimr" => ["grim"], "muzz" => ["muzz"],
      "bbes" => ["ebbs"], "intw" => ["twin"], "cfis" => ["fisc"],
      "adkn" => ["dank"], "gnos" => ["nogs", "snog", "song"], "eflo" => ["floe"],
      "aamy" => ["maya"], "celm" => ["clem"], "adip" => ["paid"],
      "ilnt" => ["lint"], "aklo" => ["kola"], "arsu" => ["sura"],
      "aetz" => ["zeta"], "imps" => ["simp", "imps"], "dhow" => ["dhow"],
      "dhtu" => ["thud"], "deho" => ["hoed"], "dehs" => ["shed"],
      "eipt" => ["piet"], "blos" => ["lobs", "slob"], "apsu" => ["upas"],
      "aegv" => ["gave"], "flux" => ["flux"], "deei" => ["eide"],
      "agms" => ["mags"], "aees" => ["ease"], "aasv" => ["vasa"],
      "irwy" => ["wiry"], "besw" => ["webs"], "iquz" => ["quiz"],
      "ilmp" => ["limp"], "ksuy" => ["yuks"], "desz" => ["zeds"],
      "blow" => ["bowl", "blow"], "aept" => ["pate", "peat", "tape"],
      "ceht" => ["echt", "etch"], "gstu" => ["gust", "tugs", "guts"],
      "cefl" => ["clef"], "eilt" => ["lite", "tile"], "apps" => ["apps", "paps"],
      "ahow" => ["whoa"], "mmpu" => ["mump"], "best" => ["best", "bets"],
      "cefk" => ["feck"], "eikr" => ["kier"], "acin" => ["cain"],
      "aesy" => ["eyas", "yeas", "ayes", "easy"], "krsu" => ["rusk"],
      "bill" => ["bill"], "afir" => ["fair"], "aakv" => ["kava"],
      "lnxy" => ["lynx"], "aeht" => ["hate", "heat"], "girs" => ["rigs"],
      "ekls" => ["leks", "elks"], "achp" => ["chap"], "eikt" => ["kite"],
      "kosw" => ["woks"], "agnp" => ["pang"],
      "elos" => ["oles", "sloe", "sole", "lose"], "eert" => ["rete", "tree"],
      "aikn" => ["kain", "kina", "akin"], "dntu" => ["dunt"],
      "diks" => ["skid", "kids", "disk"], "ceir" => ["rice"], "gosw" => ["wogs"],
      "anst" => ["ants", "tans"], "drsu" => ["surd"], "emos" => ["emos", "some"],
      "agot" => ["toga", "goat"], "aggo" => ["agog"], "ceor" => ["cero", "core"],
      "ahst" => ["hast", "hats"], "aeor" => ["aero"], "efly" => ["fley"],
      "acop" => ["capo"], "clop" => ["clop"], "amos" => ["moas", "soma"],
      "cikp" => ["pick"], "iqtu" => ["quit"], "bmsu" => ["bums"],
      "egst" => ["gest", "gets"], "iklo" => ["kilo"], "addu" => ["duad"],
      "amsy" => ["yams"], "bior" => ["brio"],
      "aelt" => ["tael", "teal", "tale", "late"],
      "amps" => ["spam", "amps", "maps"], "ehst" => ["hest"], "biss" => ["sibs"],
      "antw" => ["want"], "aitx" => ["taxi"], "impw" => ["wimp"],
      "eils" => ["leis", "isle", "lies"], "ehlp" => ["help"], "deln" => ["lend"],
      "noxy" => ["onyx"], "acio" => ["ciao"], "dims" => ["dims"],
      "arsw" => ["wars"], "foor" => ["roof"], "ilot" => ["loti", "toil"],
      "cepu" => ["puce"], "aemx" => ["exam"], "eekw" => ["week"],
      "adhr" => ["hard"], "emrs" => ["rems"], "amss" => ["mass"],
      "afhl" => ["half"], "adds" => ["dads", "adds"], "ehno" => ["hone"],
      "fssu" => ["fuss"], "loot" => ["loot", "tool"], "fuzz" => ["fuzz"],
      "npuy" => ["puny"], "deeg" => ["geed", "edge"], "ackp" => ["pack"],
      "ahtw" => ["thaw", "what"], "beit" => ["bite"], "gnpu" => ["pung"],
      "oouz" => ["ouzo"], "ddoo" => ["dodo"], "aklr" => ["lark"],
      "elru" => ["lure", "rule"], "ikss" => ["skis", "kiss"], "clru" => ["curl"],
      "eoru" => ["euro"], "aahm" => ["amah"], "ceps" => ["pecs", "spec"],
      "afrz" => ["zarf"], "ortw" => ["trow", "wort"], "dnos" => ["nods", "dons"],
      "efkr" => ["kerf"], "elns" => ["lens"], "hosw" => ["hows", "show"],
      "adeo" => ["odea"], "bfos" => ["fobs"], "deem" => ["deme", "meed", "deem"],
      "arwy" => ["awry", "wary"], "beij" => ["jibe"], "eorw" => ["wore"],
      "elmw" => ["mewl"], "ansy" => ["nays"], "pttu" => ["putt"],
      "inop" => ["pion"], "bllu" => ["bull"], "akmr" => ["mark"],
      "chop" => ["chop"], "hrtu" => ["ruth", "thru", "hurt"], "aapp" => ["papa"],
      "aikp" => ["pika"], "denw" => ["wend"], "aftw" => ["waft"],
      "fopu" => ["pouf"], "gnot" => ["tong"],
      "aprs" => ["pars", "raps", "rasp", "spar"], "cjko" => ["jock"],
      "abps" => ["baps"], "aght" => ["ghat"], "agsy" => ["gays"],
      "jlot" => ["jolt"], "dorw" => ["word"], "eims" => ["semi"],
      "agns" => ["nags", "sang", "snag"], "elpy" => ["yelp"], "fmuy" => ["fumy"],
      "hntu" => ["hunt"], "acev" => ["cave"], "akno" => ["kaon", "koan"],
      "pstu" => ["puts"], "psst" => ["psst"], "eipp" => ["pipe"],
      "delw" => ["lewd", "weld"], "noos" => ["soon"], "fgit" => ["gift"],
      "mosw" => ["mows"], "celt" => ["celt"], "cmsu" => ["scum", "cums"],
      "aepx" => ["apex"], "eegr" => ["gree"], "desy" => ["dyes"],
      "alov" => ["oval"], "ekos" => ["soke"], "aalv" => ["lava"],
      "aehr" => ["rhea", "hare", "hear"], "beju" => ["jube"], "bdei" => ["bide"],
      "cdeo" => ["deco", "coed", "code"], "cgku" => ["guck"],
      "loos" => ["loos", "solo"], "lmos" => ["mols"], "adry" => ["dray", "yard"],
      "diov" => ["void"], "ills" => ["ills", "sill"], "epsu" => ["spue"],
      "akos" => ["okas", "oaks", "soak"], "acsv" => ["vacs"],
      "efrs" => ["serf", "refs"], "bboo" => ["boob"], "dmru" => ["drum"],
      "aint" => ["tain", "anti"], "adep" => ["aped"], "emou" => ["moue"],
      "belo" => ["bole", "lobe"], "deis" => ["ides", "dies", "side"],
      "iklm" => ["milk"], "delo" => ["lode", "dole"], "abep" => ["peba"],
      "anss" => ["sans"], "ehnr" => ["hern"], "dilw" => ["wild"],
      "abir" => ["abri"], "adgu" => ["gaud"], "imot" => ["omit"],
      "hist" => ["shit", "hits", "this"], "beuz" => ["zebu"], "nort" => ["torn"],
      "aeps" => ["pase", "spae", "apse", "apes", "peas"],
      "ahsy" => ["shay", "ashy", "hays"], "orsy" => ["rosy"], "awxy" => ["waxy"],
      "irst" => ["stir"], "ftuz" => ["futz"], "admn" => ["damn"],
      "cdru" => ["crud", "curd"], "mstu" => ["muts", "tums", "smut", "must"],
      "hipz" => ["phiz"], "hklu" => ["hulk"], "clow" => ["cowl"],
      "elot" => ["tole"], "allm" => ["mall"], "cdlo" => ["clod", "cold"],
      "anuy" => ["yuan"], "eppr" => ["repp", "prep"], "abds" => ["dabs"],
      "nooz" => ["zoon"], "fnot" => ["font"], "afmo" => ["foam"],
      "ejoy" => ["joey"], "aceg" => ["cage"], "abde" => ["abed", "bade", "bead"],
      "bdsu" => ["buds", "dubs"], "entu" => ["tune"], "imnt" => ["mint"],
      "intt" => ["tint"], "elms" => ["elms"], "biot" => ["obit"],
      "acht" => ["tach", "chat"], "adno" => ["dona"], "bety" => ["byte"],
      "ablo" => ["bola"], "aegs" => ["sage", "ages"], "gilt" => ["gilt"],
      "doru" => ["duro", "dour"], "ceku" => ["cuke"],
      "ilps" => ["lips", "lisp", "slip"], "eopp" => ["pope"],
      "know" => ["wonk", "know"], "fglu" => ["gulf"], "ahht" => ["hath"],
      "essu" => ["sues", "uses"], "adop" => ["dopa"], "admu" => ["duma"],
      "amms" => ["mams"], "elry" => ["lyre", "rely"], "abgy" => ["gaby"],
      "gijs" => ["jigs"], "dknu" => ["dunk"], "adow" => ["woad"],
      "emop" => ["pome", "mope", "poem"], "aknt" => ["tank"],
      "blru" => ["burl", "blur"], "agny" => ["yang"], "istz" => ["zits"],
      "lluu" => ["lulu"], "bgno" => ["bong"], "aikr" => ["raki"],
      "aelm" => ["lame", "male", "meal"], "ehmt" => ["them"], "ginp" => ["ping"],
      "egnt" => ["gent"], "aeev" => ["eave"], "gopr" => ["gorp"],
      "enpt" => ["pent"], "hmow" => ["whom"], "mouv" => ["ovum"],
      "achm" => ["cham"], "dikr" => ["dirk"], "lmsu" => ["slum"],
      "dlou" => ["ludo", "loud"], "eirs" => ["sire", "rise"], "iisw" => ["iwis"],
      "afiw" => ["waif"], "ilos" => ["oils", "silo", "soil"], "bdnu" => ["bund"],
      "eegs" => ["gees"], "losw" => ["lows", "owls", "slow"], "gilm" => ["glim"],
      "gimp" => ["gimp"], "aesw" => ["awes"], "ehko" => ["hoke"],
      "ejko" => ["joke"], "ehmo" => ["home"], "dinr" => ["rind"],
      "klnu" => ["lunk"], "einv" => ["nevi", "vine", "vein"], "abch" => ["bach"],
      "ailn" => ["anil", "nail", "lain"], "gotu" => ["gout"], "fort" => ["fort"],
      "eilr" => ["riel", "lire", "rile"], "cdsu" => ["cuds", "scud"],
      "eorz" => ["zero"], "mnor" => ["morn", "norm"], "afgn" => ["fang"],
      "cksu" => ["cusk", "suck"], "behr" => ["herb"], "gips" => ["pigs"],
      "ahss" => ["sash"], "apru" => ["prau"], "ciru" => ["uric"],
      "knoo" => ["nook"], "aegw" => ["wage"], "ipst" => ["pits", "spit", "tips"],
      "ainr" => ["rain"], "assy" => ["says"], "iint" => ["inti"],
      "abin" => ["bani"], "aejn" => ["jane", "jean"], "ahop" => ["opah"],
      "aacs" => ["casa"], "illp" => ["pill"], "aopt" => ["atop"],
      "fruy" => ["fury"], "aegz" => ["gaze"], "ciot" => ["otic"],
      "adis" => ["dais", "aids", "said"], "aclo" => ["cola", "coal"],
      "cops" => ["scop", "cops"], "delv" => ["veld"], "emmo" => ["memo"],
      "ackw" => ["wack"], "ajot" => ["jota", "jato"],
      "acst" => ["scat", "cast", "cats", "acts"], "hipt" => ["pith"],
      "eooz" => ["ooze"], "afnw" => ["fawn"], "arty" => ["arty", "tray"],
      "aakk" => ["kaka"], "acil" => ["laic"], "imsw" => ["swim"],
      "adqu" => ["quad"], "estz" => ["zest"], "agin" => ["gain"],
      "aefl" => ["feal", "flea", "leaf"], "ahku" => ["haku"], "efls" => ["self"],
      "opss" => ["sops"], "lowy" => ["yowl"], "amot" => ["moat", "atom"],
      "cdtu" => ["duct"], "cikk" => ["kick"], "adrt" => ["drat", "trad", "dart"],
      "bclo" => ["bloc"], "lnoy" => ["only"], "knsu" => ["sunk"],
      "arsv" => ["vars"], "eilu" => ["lieu"], "ttuu" => ["tutu"],
      "defl" => ["fled"], "koor" => ["rook"], "bglo" => ["glob", "blog"],
      "acet" => ["cate", "tace"], "mmos" => ["moms"], "anyz" => ["zany"],
      "aksu" => ["skua", "auks"], "clmu" => ["culm"], "flou" => ["foul"],
      "egry" => ["gyre"], "aeuv" => ["uvea"], "bgos" => ["gobs", "bogs"],
      "lops" => ["pols", "lops", "slop"], "aehv" => ["have"],
      "deop" => ["oped", "dope"], "osst" => ["sots", "toss"], "mosu" => ["sumo"],
      "bkoo" => ["kobo", "book"], "belu" => ["lube", "blue"],
      "aerr" => ["rear", "rare"], "kosu" => ["souk"], "cips" => ["pics", "spic"],
      "inow" => ["wino"], "dlop" => ["plod"], "acdr" => ["card"],
      "efik" => ["kief"], "aemr" => ["mare", "ream"], "cltu" => ["cult"],
      "acrt" => ["cart"], "djou" => ["judo"], "mrsu" => ["rums"],
      "efst" => ["efts", "fest"], "efiw" => ["wife"], "avwy" => ["wavy"],
      "astv" => ["vats", "vast"], "eikp" => ["kepi", "pike"], "lmoy" => ["moly"],
      "ehlr" => ["herl", "lehr"], "abfl" => ["flab"], "bhot" => ["both"],
      "abdw" => ["bawd"], "ahjj" => ["hajj"], "cehk" => ["heck"],
      "ilms" => ["mils", "slim"], "bemr" => ["berm"],
      "acer" => ["acre", "care", "race"], "dfnu" => ["fund"],
      "desu" => ["dues", "sued", "used"], "alor" => ["oral"],
      "ader" => ["dare", "dear", "read"], "iort" => ["tori", "trio", "riot"],
      "inqu" => ["quin"], "aagg" => ["gaga"], "agst" => ["gats", "stag", "tags"],
      "aehk" => ["hake"], "bdes" => ["debs", "beds"], "depu" => ["dupe"],
      "acpu" => ["puca"], "oppr" => ["prop"], "agoy" => ["yoga"],
      "foot" => ["foot"], "denv" => ["vend"], "eory" => ["oyer", "yore"],
      "aagm" => ["agma"], "admp" => ["damp"], "adst" => ["tads"],
      "aegr" => ["gear", "rage"], "inwy" => ["winy"], "lopt" => ["plot"],
      "dels" => ["sled"], "adlo" => ["load"], "egls" => ["gels", "legs"],
      "aorr" => ["roar"], "aaqu" => ["aqua"], "eejr" => ["jeer"],
      "lort" => ["rotl"], "gjsu" => ["jugs"], "hlsu" => ["shul", "lush"],
      "dily" => ["idly"], "rtuy" => ["yurt"], "eoss" => ["oses"],
      "adot" => ["dato", "toad"], "agqu" => ["quag"], "ckru" => ["ruck"],
      "ahkr" => ["hark"], "affr" => ["raff"], "mpsu" => ["sump", "umps"],
      "bblu" => ["bulb"], "alow" => ["alow"], "amoy" => ["mayo"],
      "boor" => ["boor"], "cchs" => ["csch"], "cghu" => ["chug"],
      "jmoo" => ["mojo"], "almm" => ["malm"], "bdis" => ["dibs", "bids"],
      "ahoy" => ["ahoy"], "cims" => ["mics"], "dehr" => ["herd"],
      "mnoo" => ["mono", "moon"], "amru" => ["arum"], "absw" => ["swab"],
      "aehp" => ["heap"], "bhoo" => ["hobo"], "apry" => ["pray"],
      "alpy" => ["paly", "play"], "ostw" => ["swot", "stow", "tows", "twos"],
      "acel" => ["lace"], "hisw" => ["wish"], "ahrs" => ["rash"],
      "apwy" => ["yawp"], "addy" => ["dyad"], "elmo" => ["mole"],
      "ahlm" => ["halm"], "hlos" => ["hols"], "aflo" => ["foal", "loaf"],
      "enox" => ["exon", "oxen"], "cehw" => ["chew"], "ooyz" => ["oozy"],
      "adps" => ["pads"], "begs" => ["begs"], "dgnu" => ["dung"],
      "amst" => ["tams", "mast", "mats"], "dluy" => ["duly"], "allt" => ["tall"],
      "agim" => ["magi"], "hisv" => ["shiv"], "eknr" => ["kern"],
      "gitw" => ["twig"], "aims" => ["sima", "aims"], "chko" => ["hock"],
      "aett" => ["teat"], "abim" => ["iamb"], "afmr" => ["farm"],
      "ainp" => ["nipa", "pain"], "jmpu" => ["jump"],
      "estw" => ["stew", "wets", "west"], "dnop" => ["pond"], "cikl" => ["lick"],
      "aclr" => ["carl"], "abes" => ["base"], "akly" => ["alky", "laky"],
      "beik" => ["kibe", "bike"], "asty" => ["stay"], "eovw" => ["wove"],
      "kmno" => ["monk"], "anvy" => ["navy"], "egns" => ["gens"],
      "bent" => ["bent"], "adns" => ["sand"], "hnsu" => ["shun"],
      "rsuu" => ["urus"], "aben" => ["bane", "bean"], "belt" => ["belt"],
      "hoop" => ["pooh", "hoop"], "bgoo" => ["gobo"], "clos" => ["clos", "cols"],
      "brsu" => ["burs", "rubs"], "fflu" => ["luff"], "dgru" => ["drug"],
      "ekrt" => ["trek"], "degy" => ["edgy"], "artt" => ["tart"],
      "bjos" => ["jobs"], "amny" => ["many"], "bclu" => ["club"],
      "ampt" => ["tamp"], "deer" => ["dree", "rede", "deer", "reed"],
      "epry" => ["prey", "pyre"], "ghhi" => ["high"], "ablm" => ["balm", "lamb"],
      "adfr" => ["fard"], "acdh" => ["chad"], "deet" => ["teed"],
      "ajlr" => ["jarl"], "ciss" => ["sics"], "egru" => ["urge"],
      "chir" => ["rich"], "entt" => ["tent"], "oorz" => ["orzo"],
      "adet" => ["date"], "elpt" => ["pelt"], "jost" => ["jots"],
      "inot" => ["into"], "aert" => ["tare", "tear", "rate"],
      "girt" => ["girt", "trig", "grit"], "ahik" => ["haik"], "ehty" => ["they"],
      "dego" => ["doge"], "cein" => ["cine", "nice"], "ahpr" => ["harp"],
      "beer" => ["bree", "beer"], "eekp" => ["peke", "peek", "keep"],
      "gisw" => ["swig", "wigs"], "efos" => ["foes"], "opsy" => ["posy"],
      "ppsu" => ["pups"], "illm" => ["mill"], "apsz" => ["zaps"],
      "ahkl" => ["lakh"], "abot" => ["boat"], "abbr" => ["barb"],
      "aagh" => ["agha"], "bceu" => ["cube"], "aagr" => ["agar", "raga"],
      "cgos" => ["cogs"], "dees" => ["seed"], "npsw" => ["pwns"],
      "dhos" => ["dosh", "hods", "shod"], "hhsu" => ["hush"], "cllu" => ["cull"],
      "deov" => ["dove"], "josy" => ["joys"], "aggs" => ["gags"],
      "emrt" => ["term"], "cpsu" => ["scup", "cusp", "cups"], "aflt" => ["flat"],
      "aesv" => ["vase", "save"], "been" => ["been"], "dimn" => ["mind"],
      "aagl" => ["alga", "gala"], "adhs" => ["dahs", "shad", "dash"],
      "hins" => ["hins", "sinh", "shin"], "hkoo" => ["hook"], "hmot" => ["moth"],
      "cell" => ["cell"], "aeft" => ["feta", "feat", "fate"], "afux" => ["faux"],
      "hmos" => ["mhos", "shmo", "mosh", "ohms"], "abem" => ["bema", "beam"],
      "frtu" => ["turf"], "loop" => ["polo", "loop", "pool"], "iors" => ["sori"],
      "eemr" => ["mere"], "acip" => ["pica"],
      "anps" => ["naps", "pans", "snap", "span"], "eost" => ["toes"],
      "adsy" => ["days"], "ekoy" => ["yoke"], "ghis" => ["sigh"],
      "istw" => ["wist", "wits"], "aclt" => ["talc"], "iknw" => ["wink"],
      "delm" => ["meld"], "finr" => ["firn"], "abdu" => ["daub", "baud"],
      "cetu" => ["cute"], "bcir" => ["crib"], "aluu" => ["luau"],
      "nost" => ["snot", "tons"], "bdoy" => ["body"], "bfmu" => ["bumf"],
      "inov" => ["vino"], "ehpw" => ["phew"], "efnr" => ["fern"],
      "sttu" => ["tuts"], "agno" => ["agon"], "emms" => ["mems"],
      "glpu" => ["gulp", "plug"], "eilp" => ["pile"], "acpr" => ["carp", "crap"],
      "beil" => ["bile"], "ckuy" => ["yuck"], "ikmn" => ["mink"],
      "hopq" => ["qoph"], "adit" => ["adit"], "delu" => ["duel"],
      "ghnu" => ["hung"], "dhot" => ["doth"], "knpu" => ["punk"],
      "drsy" => ["drys"], "agps" => ["gaps", "gasp"], "diqu" => ["quid"],
      "aknp" => ["knap"], "afly" => ["flay"], "bikl" => ["bilk"],
      "ahnw" => ["hwan"], "aant" => ["anta", "tana"],
      "deos" => ["odes", "dose", "does"], "eluy" => ["yule"], "dllu" => ["dull"],
      "agmy" => ["gamy"], "mpru" => ["rump"], "errs" => ["errs"],
      "acds" => ["cads", "scad"],
      "aels" => ["lase", "leas", "ales", "seal", "sale"], "oprs" => ["pros"],
      "opsu" => ["opus", "soup"], "film" => ["milf", "film"], "cior" => ["coir"],
      "bmnu" => ["numb"], "achw" => ["chaw"], "einz" => ["zine"],
      "ggor" => ["grog"], "enno" => ["neon", "none"], "deku" => ["duke"],
      "aarv" => ["vara"], "gost" => ["togs"], "hlot" => ["holt"],
      "nosw" => ["sown", "owns", "snow"], "apsw" => ["paws", "wasp", "swap"],
      "alos" => ["sola", "also"], "cekp" => ["peck"], "ejkr" => ["jerk"],
      "beht" => ["beth"], "cikm" => ["mick"], "flot" => ["loft"],
      "adft" => ["daft"], "nnoo" => ["noon"], "eflp" => ["pelf"],
      "mnou" => ["muon"], "acrs" => ["arcs", "scar", "cars"], "dssu" => ["suds"],
      "alst" => ["lats", "slat", "salt", "last"], "adez" => ["adze", "daze"],
      "ckop" => ["pock"], "bttu" => ["butt"], "aipt" => ["pita"],
      "enov" => ["oven"], "emno" => ["omen"], "bhru" => ["buhr"],
      "llop" => ["poll"], "eflw" => ["flew"], "ahly" => ["hyla"],
      "eelp" => ["peel"], "bdeo" => ["bode"], "agjs" => ["jags"],
      "gioy" => ["yogi"], "anox" => ["axon"], "bdet" => ["debt"],
      "ejss" => ["jess"], "imss" => ["isms", "sims", "miss"],
      "efir" => ["rife", "fire"], "ikll" => ["kill"], "lllu" => ["lull"],
      "cmsw" => ["cwms"], "eemm" => ["meme"],
      "hips" => ["pish", "phis", "hips", "ship"], "ekno" => ["keno"],
      "bgsu" => ["bugs"], "acim" => ["mica"], "ajsw" => ["jaws"],
      "ailv" => ["vail", "vial"], "adgo" => ["dago", "goad"],
      "aelz" => ["laze", "zeal"], "eekn" => ["knee", "keen"],
      "aekw" => ["weka", "wake", "weak"], "hilt" => ["hilt"],
      "aekl" => ["kale", "lake", "leak"], "ahkn" => ["ankh", "hank", "khan"],
      "ahlu" => ["hula", "haul"], "deno" => ["node", "done"], "ansu" => ["anus"],
      "bimr" => ["brim"], "afry" => ["fray"], "ejst" => ["jets", "jest"],
      "bmoo" => ["boom"], "acft" => ["fact"], "hiks" => ["kish"],
      "alwy" => ["yawl"], "eikk" => ["kike"], "ddei" => ["died"],
      "aehz" => ["haze"], "acek" => ["cake"], "hnor" => ["horn"],
      "mmsu" => ["mums"], "aamm" => ["mama"], "agss" => ["sags"],
      "lopu" => ["loup"], "bklu" => ["bulk"], "nopr" => ["porn"],
      "kopy" => ["poky"], "eepv" => ["veep"], "alsv" => ["lavs"],
      "diot" => ["doit"], "ceop" => ["cope"], "biis" => ["ibis"],
      "ahpt" => ["phat", "path"], "dirt" => ["dirt"], "beef" => ["beef"],
      "anov" => ["nova"], "llpu" => ["pull"], "eghu" => ["huge"],
      "afil" => ["fila", "fail"], "dlot" => ["dolt", "told"], "bder" => ["bred"],
      "eoty" => ["eyot"], "abcs" => ["cabs", "scab"], "abel" => ["bale", "able"],
      "ikmr" => ["mirk"], "aghs" => ["shag", "gash", "hags"],
      "lpsu" => ["puls", "plus"], "betu" => ["tube"], "jstu" => ["juts", "just"],
      "bnor" => ["born"], "chik" => ["hick"], "osvw" => ["vows"],
      "cfor" => ["corf"], "bdmu" => ["dumb"], "blsu" => ["slub"],
      "aehy" => ["yeah"], "alot" => ["lota", "tola", "alto"], "abdn" => ["band"],
      "afpr" => ["frap"], "frsu" => ["furs", "surf"], "aekm" => ["kame", "make"],
      "ikps" => ["kips", "skip"], "eeks" => ["ekes", "seek"],
      "ostu" => ["oust", "outs"], "aftu" => ["tufa"], "dest" => ["teds"],
      "aikk" => ["kaki"], "egor" => ["goer", "gore", "ogre", "ergo"],
      "anno" => ["anon"], "eorv" => ["rove", "over"], "deey" => ["eyed"],
      "dgno" => ["dong"], "ahmr" => ["harm"], "afnu" => ["faun"],
      "iknt" => ["knit"], "ehlo" => ["hole"], "ikkn" => ["kink"],
      "notw" => ["nowt", "wont", "town"], "gloy" => ["logy"], "ertu" => ["true"],
      "iopt" => ["topi"], "abst" => ["bast", "bats", "stab", "tabs"],
      "astt" => ["tats"], "dhis" => ["dish"], "aeim" => ["amie"],
      "ffit" => ["tiff"], "sssu" => ["suss"], "belw" => ["blew"],
      "adln" => ["land"], "acde" => ["cade", "dace", "aced"], "bcko" => ["bock"],
      "ally" => ["ally"], "bilm" => ["limb"], "bcek" => ["beck"],
      "bops" => ["bops"], "gsuy" => ["guys"], "ilpu" => ["puli"],
      "abkn" => ["bank"], "lrsu" => ["slur"], "egnu" => ["genu"],
      "eflt" => ["felt", "left"], "flop" => ["flop"], "oruy" => ["your"],
      "mooz" => ["zoom"], "eimt" => ["mite", "emit", "item", "time"],
      "ffos" => ["offs"], "eels" => ["seel", "lees", "eels", "else"],
      "nrtu" => ["runt", "turn"], "prsu" => ["spur"], "aosv" => ["avos"],
      "intu" => ["unit"], "oort" => ["root"], "belp" => ["pleb"],
      "afoy" => ["ofay"], "eelt" => ["leet"], "llmo" => ["moll"],
      "glsu" => ["lugs", "slug"], "dnow" => ["down"], "dfor" => ["ford"],
      "eitw" => ["wite"], "eklo" => ["koel"], "inoy" => ["yoni"],
      "npsu" => ["spun", "puns"], "ehiv" => ["hive"], "aikm" => ["kami"],
      "acmy" => ["cyma"], "almo" => ["mola", "loam"], "fizz" => ["fizz"],
      "agnt" => ["gnat", "tang"], "anor" => ["roan"], "eenp" => ["peen"],
      "ortu" => ["rout", "tour"], "coop" => ["poco", "coop"],
      "ains" => ["anis", "sain"], "afst" => ["fats", "fast"], "dity" => ["tidy"],
      "aest" => ["etas", "sate", "teas", "seat", "east", "eats"],
      "afkl" => ["flak"], "ehpy" => ["hype"], "cdek" => ["deck"],
      "beno" => ["ebon", "bone"], "acry" => ["racy"], "eswy" => ["yews"],
      "dstu" => ["stud", "dust"], "ehsu" => ["hues"], "ostt" => ["tots"],
      "aijl" => ["jail"], "hikt" => ["kith"], "acks" => ["cask", "sack"],
      "emov" => ["move"], "gist" => ["gits", "gist"], "ikno" => ["kino", "oink"],
      "mppu" => ["pump"], "berv" => ["verb"], "chot" => ["coth"],
      "derw" => ["drew"], "diim" => ["midi"], "hmty" => ["myth"],
      "elmu" => ["mule"], "ffru" => ["ruff"], "eeps" => ["pees", "seep"],
      "celw" => ["clew"], "cssu" => ["cuss"], "illr" => ["rill"],
      "eefj" => ["jefe"], "eenv" => ["even"], "cloy" => ["coly", "cloy"],
      "ikns" => ["inks", "sink", "skin"], "ajms" => ["jams"],
      "amor" => ["mora", "roam"], "hjos" => ["josh"], "ajsy" => ["jays"],
      "msuw" => ["swum"], "aksy" => ["yaks"], "eklt" => ["kelt"],
      "irtw" => ["writ"], "aces" => ["aces", "case"], "bilo" => ["boil"],
      "aadd" => ["dada"], "ijkn" => ["jink"], "afln" => ["flan"],
      "glmo" => ["glom"], "agls" => ["gals", "lags", "slag"], "ceiv" => ["vice"],
      "bgir" => ["brig"], "ddeo" => ["eddo"], "kstu" => ["tusk"],
      "elnt" => ["lent"], "ahkw" => ["hawk"], "chmu" => ["chum", "much"],
      "eins" => ["sine"], "cnor" => ["corn"], "deef" => ["feed"],
      "ghno" => ["hong"], "aipr" => ["pair"], "jkoo" => ["jook"],
      "eesy" => ["eyes"], "bbis" => ["bibs"], "ahtt" => ["that"],
      "elor" => ["orle", "lore", "role"], "aefr" => ["frae", "fare", "fear"],
      "eirw" => ["weir", "wire"], "ensy" => ["syne", "yens"],
      "nstu" => ["tuns", "nuts", "stun"], "bosy" => ["yobs", "boys"],
      "aefs" => ["safe"], "bden" => ["bend"], "beep" => ["beep"],
      "deks" => ["desk"], "deep" => ["peed", "deep"], "agmr" => ["gram"],
      "fgis" => ["figs"], "bffi" => ["biff"], "ehll" => ["hell"],
      "hors" => ["rhos"], "adgr" => ["darg", "grad", "drag"], "alpu" => ["pula"],
      "gort" => ["grot"], "degr" => ["dreg"], "ablt" => ["blat"],
      "envy" => ["envy"], "ccho" => ["choc"], "acem" => ["acme", "mace", "came"],
      "elop" => ["lope", "pole"], "ehtt" => ["teth"],
      "abet" => ["bate", "abet", "beat", "beta"], "nrsu" => ["urns", "runs"],
      "bouy" => ["buoy"], "allp" => ["pall"], "antu" => ["tuna", "aunt"],
      "acox" => ["coxa", "coax"], "bnoy" => ["bony"], "bens" => ["bens", "nebs"],
      "dfoo" => ["food"], "aent" => ["etna", "ante", "neat"], "aclw" => ["claw"],
      "eery" => ["eyer", "eyre"], "ccko" => ["cock"], "beru" => ["rube"],
      "eotv" => ["veto", "vote"], "abtt" => ["batt"], "afgl" => ["flag"],
      "eehm" => ["heme"], "beix" => ["ibex"], "lost" => ["slot", "lost", "lots"],
      "eens" => ["sene", "seen"], "enot" => ["tone", "note"],
      "ahms" => ["hams", "mash", "sham"], "ijno" => ["join"], "gmno" => ["mong"],
      "abit" => ["bait"], "iimp" => ["impi"], "aals" => ["alas"],
      "admr" => ["dram"], "eott" => ["tote"], "door" => ["ordo", "rood", "door"],
      "hiss" => ["hiss"], "aiil" => ["ilia"], "ceov" => ["cove"],
      "ceot" => ["cote"], "abil" => ["bail"], "alms" => ["lams", "alms", "slam"],
      "dhoo" => ["hood"], "emor" => ["omer", "more"], "bhsu" => ["hubs", "bush"],
      "ablw" => ["bawl"], "gmsy" => ["gyms"], "mttu" => ["mutt"],
      "bflu" => ["flub"], "aklw" => ["walk"], "bblo" => ["blob"],
      "illw" => ["will"], "inpt" => ["pint"], "eltu" => ["lute"],
      "orrt" => ["torr"], "eerw" => ["ewer", "weer", "were"], "hmny" => ["hymn"],
      "ahls" => ["lash"], "ekpu" => ["puke"], "ails" => ["ails", "sail"],
      "bkos" => ["bosk", "kobs"], "aemt" => ["mate", "meat", "tame", "team"],
      "inor" => ["iron"], "fost" => ["soft"], "ahiy" => ["hiya"],
      "cehl" => ["lech"], "aelx" => ["axle"], "aegp" => ["peag", "gape", "page"],
      "aehl" => ["hale", "heal"], "aegn" => ["gean"], "adiw" => ["wadi"],
      "joss" => ["joss"], "arst" => ["tars", "arts", "rats", "star"],
      "amrw" => ["warm"], "bssu" => ["subs", "buss"], "aijv" => ["jiva"],
      "cktu" => ["tuck"], "egps" => ["pegs"], "hipw" => ["whip"],
      "dery" => ["dyer"], "bdlo" => ["bold"], "boot" => ["boot"],
      "acsw" => ["caws"], "eejp" => ["jeep"], "alsw" => ["awls", "slaw", "laws"],
      "dikn" => ["dink", "kind"], "aimn" => ["main"], "abjm" => ["jamb"],
      "airv" => ["vair"], "aerv" => ["aver", "rave"], "aovw" => ["avow"],
      "eptw" => ["wept"], "aden" => ["dean"], "dopu" => ["updo"],
      "cstu" => ["scut", "cuts"], "agiv" => ["vagi"], "deft" => ["deft"],
      "fgru" => ["frug"], "ampv" => ["vamp"], "aiot" => ["iota"],
      "acms" => ["macs", "cams", "scam"], "estx" => ["sext"], "aops" => ["soap"],
      "acot" => ["taco", "coat"], "dill" => ["dill"], "fglo" => ["flog", "golf"],
      "bnoo" => ["boon"], "ilwy" => ["wily"], "abht" => ["baht", "bath"],
      "elly" => ["yell"], "ipsy" => ["yips"], "cosw" => ["scow", "cows"],
      "ikms" => ["skim"], "elss" => ["less"], "aakn" => ["kana"],
      "beiv" => ["vibe"], "cdei" => ["cedi", "iced", "dice"], "aeot" => ["toea"],
      "gknu" => ["gunk"], "lnor" => ["lorn"], "defu" => ["feud"],
      "abmo" => ["ambo"], "firs" => ["firs"], "iitz" => ["ziti"],
      "adeg" => ["egad", "aged"], "orux" => ["roux"], "eisw" => ["wise"],
      "copy" => ["copy"], "ciks" => ["sick"], "noot" => ["onto"],
      "eiln" => ["lien", "line"], "ffij" => ["jiff"],
      "aenp" => ["pean", "neap", "nape", "pane"], "addo" => ["dado"],
      "bbbi" => ["bibb"], "hnos" => ["hons", "nosh"], "efns" => ["fens"],
      "fgir" => ["frig"], "emtu" => ["mute"], "itzz" => ["tizz"],
      "fins" => ["fins"], "anos" => ["naos"], "disy" => ["yids"],
      "doyz" => ["dozy"], "abhl" => ["blah"], "aags" => ["saga"],
      "arsy" => ["ryas", "rays"], "bdno" => ["bond"], "cesy" => ["syce"],
      "nptu" => ["punt"], "inos" => ["ions"], "ffgu" => ["guff"],
      "ehns" => ["hens"], "epps" => ["peps"], "alsy" => ["slay", "lays"],
      "ailr" => ["aril", "lari", "rial", "lira", "lair", "liar", "rail"],
      "gilr" => ["girl"], "esty" => ["yest"], "dlow" => ["wold"],
      "dmor" => ["dorm"], "aenr" => ["earn", "near"], "elnu" => ["lune"],
      "opry" => ["ropy"], "noty" => ["tony"], "aegm" => ["mage", "mega", "game"],
      "alss" => ["lass"], "eegh" => ["ghee"], "dips" => ["psid", "dips"],
      "abgl" => ["blag"], "efil" => ["lief", "file", "life"],
      "kloo" => ["kolo", "look"], "dist" => ["dits"], "bnos" => ["nobs", "snob"],
      "eltw" => ["welt"], "emst" => ["stem"], "hopy" => ["hypo"],
      "deil" => ["deil", "deli", "idle", "lied"],
      "beir" => ["brei", "brie", "bier"], "deel" => ["dele"],
      "aehm" => ["hame", "ahem"], "adeh" => ["hade", "head"], "kkoo" => ["kook"],
      "aknu" => ["kuna"], "ghin" => ["nigh"], "aflp" => ["flap"],
      "agru" => ["gaur"], "ceex" => ["exec"], "aort" => ["rota", "taro"],
      "eegl" => ["glee"], "iikw" => ["wiki", "kiwi"],
      "deor" => ["doer", "redo", "rode"], "aopr" => ["proa"], "eekr" => ["reek"],
      "epsy" => ["espy", "yeps"], "egms" => ["megs", "gems"],
      "dost" => ["dost", "dots"], "lopy" => ["poly", "ploy"],
      "ahlt" => ["lath", "halt"], "essw" => ["sews"], "aabl" => ["alba"],
      "jjuu" => ["juju"], "abrw" => ["braw"], "chit" => ["chit", "itch"],
      "ceit" => ["cite"], "enos" => ["sone", "noes", "nose", "ones"],
      "asst" => ["tass"], "cikn" => ["nick"], "astu" => ["taus"],
      "gipr" => ["prig", "grip"], "ijll" => ["jill"], "alry" => ["aryl"],
      "acky" => ["caky"], "ijnx" => ["jinx"], "abgr" => ["brag", "garb", "grab"],
      "adil" => ["dial", "laid"], "dell" => ["dell"], "ehor" => ["hoer", "hero"],
      "asww" => ["waws"], "gnop" => ["pong"], "adnr" => ["nard", "rand", "darn"],
      "aegu" => ["ague"], "dory" => ["dory"], "ilmo" => ["milo", "moil", "limo"],
      "egit" => ["gite"], "ggir" => ["grig"], "affg" => ["gaff"],
      "acis" => ["asci"], "glos" => ["slog", "logs"], "emru" => ["mure"],
      "agrs" => ["gars", "rags"], "cloo" => ["loco", "cool"],
      "aelp" => ["peal", "leap", "pale", "plea"], "agll" => ["gall"],
      "cdko" => ["dock"], "dffu" => ["duff"], "eftw" => ["weft"],
      "dehu" => ["hued"], "lllo" => ["loll"], "dnsu" => ["duns"],
      "chin" => ["chin", "inch"], "imtt" => ["mitt"], "eivv" => ["vive"],
      "chis" => ["chis"], "notu" => ["unto"], "ipqu" => ["quip"],
      "eefr" => ["reef", "free"], "aalt" => ["tala"], "corw" => ["crow"],
      "cefh" => ["chef"], "ipty" => ["pity"], "dtuy" => ["duty"],
      "ainy" => ["ayin"], "almr" => ["marl"], "hlow" => ["howl"],
      "efiv" => ["five"], "acor" => ["orca"], "eirv" => ["rive"],
      "moor" => ["moor", "room"], "eepw" => ["weep"], "hklo" => ["kohl"],
      "egks" => ["skeg", "kegs"], "iltt" => ["tilt"], "agnw" => ["gnaw"],
      "akpr" => ["park"], "aekr" => ["rake"], "bnru" => ["burn"],
      "esst" => ["sets"], "opru" => ["roup", "pour"],
      "abdr" => ["brad", "bard", "drab"], "inns" => ["inns"], "defn" => ["fend"],
      "oopr" => ["poor"], "elvy" => ["levy"], "acnt" => ["cant"],
      "ehmp" => ["hemp"], "irss" => ["sirs"], "aflw" => ["flaw"],
      "bcku" => ["buck"], "hims" => ["shim", "hims"], "iloo" => ["olio"],
      "abcn" => ["banc"], "ffpu" => ["puff"], "ipsw" => ["wisp"],
      "fist" => ["fist", "sift", "fits"], "aflx" => ["flax"],
      "ehms" => ["hems", "mesh"], "ggis" => ["gigs"], "ammo" => ["ammo"],
      "ados" => ["soda"], "aprw" => ["warp", "wrap"], "eerv" => ["veer", "ever"],
      "mops" => ["poms", "mops"], "bgoy" => ["goby"], "gjos" => ["jogs"],
      "horu" => ["hour"], "aist" => ["sati"], "aawy" => ["away"],
      "ckmo" => ["mock"], "abbl" => ["blab"], "ddee" => ["deed"],
      "acmr" => ["marc", "cram"], "aefm" => ["fame"], "floo" => ["fool"],
      "enop" => ["pone", "nope", "peon", "open"], "bchu" => ["chub"],
      "filo" => ["filo", "foil"], "ahot" => ["oath"],
      "aems" => ["mesa", "seam", "same"], "afns" => ["fans"], "hllu" => ["hull"],
      "acdl" => ["clad"], "eefk" => ["keef"], "efsu" => ["fuse"],
      "eitx" => ["exit"], "efmu" => ["fume"], "egiv" => ["give"],
      "hinw" => ["whin"], "abmr" => ["barm"], "ailp" => ["pail"],
      "egln" => ["glen"], "eesv" => ["eves"], "ekmo" => ["moke"],
      "hknu" => ["hunk"], "ejku" => ["juke"], "bcei" => ["bice"],
      "eegn" => ["gene"], "abks" => ["bask"], "choo" => ["coho"],
      "fhoo" => ["hoof"], "demn" => ["mend"], "opps" => ["pops"],
      "acss" => ["sacs"], "coss" => ["coss"], "hpsu" => ["push"],
      "ailw" => ["wail"], "dein" => ["nide", "dine"], "ehtw" => ["thew", "whet"],
      "aalr" => ["alar"], "eisv" => ["vies", "vise"], "aclu" => ["caul"],
      "adff" => ["daff"], "aann" => ["anna", "naan"], "fops" => ["fops"],
      "aclm" => ["clam", "calm"], "eirt" => ["rite", "tier", "tire"],
      "erty" => ["trey"], "inss" => ["sins"], "efms" => ["emfs"],
      "aquy" => ["quay"], "ampr" => ["pram", "ramp"], "dfin" => ["find"],
      "ittw" => ["twit"], "korw" => ["work"], "bdos" => ["bods", "dobs"],
      "bost" => ["stob", "bots"], "eegk" => ["geek"], "fimr" => ["firm"],
      "deeh" => ["heed"], "host" => ["hots", "tosh", "shot", "host"],
      "cest" => ["sect"], "abnt" => ["bant"], "fott" => ["toft"],
      "orsu" => ["sour", "ours"], "eflu" => ["flue", "fuel"],
      "ilny" => ["inly", "liny"], "acdo" => ["coda"], "agir" => ["ragi"],
      "eetw" => ["twee"], "hmpu" => ["hump"], "osty" => ["toys"],
      "acnr" => ["narc"], "almy" => ["amyl"], "imos" => ["miso"],
      "aanz" => ["azan"], "eklp" => ["kelp"], "aens" => ["sane"],
      "abtu" => ["abut", "tuba"], "aips" => ["psia"],
      "ahsw" => ["shaw", "haws", "wash"], "iklt" => ["kilt"],
      "deot" => ["dote", "toed"], "elmt" => ["melt"], "afff" => ["faff"],
      "jruy" => ["jury"], "chow" => ["chow"], "dhin" => ["hind"],
      "abrs" => ["arbs", "bras", "bars"], "aswy" => ["yaws", "sway", "ways"],
      "boss" => ["sobs", "boss"], "iimn" => ["mini"], "agio" => ["agio"],
      "ehik" => ["hike"], "akor" => ["okra"], "eehw" => ["whee"],
      "koot" => ["koto", "took"], "acly" => ["acyl", "clay", "lacy"],
      "lnoo" => ["nolo", "loon"], "entx" => ["next"], "aaru" => ["aura"],
      "ceip" => ["pice", "epic"], "ajru" => ["jura"], "abek" => ["beak", "bake"],
      "nnou" => ["noun"], "bijs" => ["jibs"], "aevw" => ["wave"],
      "efky" => ["fyke"], "attw" => ["twat", "watt"],
      "astw" => ["taws", "twas", "wast", "swat"], "gsuv" => ["guvs"],
      "cklo" => ["lock"], "ertw" => ["wert"], "eist" => ["site", "ties"],
      "gory" => ["gyro", "gory", "orgy"],
      "eors" => ["ores", "roes", "rose", "sore"], "bgil" => ["glib"],
      "bsuy" => ["busy", "buys"], "efin" => ["fine"], "forw" => ["frow"],
      "ghoy" => ["yogh"], "agil" => ["glia"], "gint" => ["ting"],
      "ikos" => ["oiks"], "aery" => ["eyra", "yare", "year"], "bcsu" => ["cubs"],
      "hill" => ["hill"], "acmp" => ["camp"], "ckmu" => ["muck"],
      "allw" => ["wall"], "cekk" => ["keck"], "elov" => ["vole", "love"],
      "eops" => ["epos", "opes", "peso", "pose"], "eelr" => ["leer", "reel"],
      "aemw" => ["wame"], "eent" => ["teen"], "egrw" => ["grew"],
      "bknu" => ["bunk"], "ackl" => ["kcal", "lack"], "copr" => ["crop"],
      "crsu" => ["crus", "curs"], "aell" => ["leal"], "kopr" => ["pork"],
      "attu" => ["taut"], "bcos" => ["cobs"], "cemo" => ["come"],
      "bbos" => ["bobs"], "eesz" => ["zees"], "illy" => ["lily"],
      "bgnu" => ["bung"], "cffu" => ["cuff"], "dkor" => ["dork"],
      "copu" => ["coup"], "nosu" => ["nous", "onus"], "aejp" => ["jape"],
      "bstu" => ["buts", "stub", "tubs", "bust"], "oopp" => ["poop"],
      "birs" => ["bris", "ribs"], "ehlm" => ["helm"], "aajr" => ["ajar"],
      "alpp" => ["palp"], "aitw" => ["wait"], "ajrs" => ["jars"],
      "aeny" => ["yean"], "iswz" => ["swiz"],
      "adel" => ["dale", "lade", "deal", "lead"], "bllo" => ["boll"],
      "aerw" => ["ware", "wear"],
      "opst" => ["pots", "opts", "tops", "post", "spot", "stop"],
      "iins" => ["nisi"], "boxy" => ["boxy"], "akmo" => ["mako", "amok"],
      "abis" => ["bias"], "loru" => ["lour"], "ensw" => ["wens", "sewn", "news"],
      "oosw" => ["woos"], "llnu" => ["null"], "answ" => ["awns", "swan"],
      "acff" => ["caff"], "llor" => ["roll"], "enss" => ["ness", "sens"],
      "deit" => ["tide", "diet", "edit", "tied"], "aart" => ["rata"],
      "eimn" => ["mien", "mine"], "dksu" => ["dusk"], "aeel" => ["alee"],
      "gisz" => ["zigs"], "ehmr" => ["herm"], "aahr" => ["haar"],
      "ssuw" => ["wuss"], "amns" => ["mans"], "iirs" => ["iris"],
      "dent" => ["dent", "tend"], "iknr" => ["rink"], "ccoo" => ["coco"],
      "aamn" => ["mana"], "gruu" => ["guru"], "cors" => ["rocs", "orcs"],
      "cilo" => ["loci", "coil"], "ghsu" => ["gush", "hugs"], "ahyz" => ["hazy"],
      "eego" => ["ogee"], "dmpu" => ["dump"], "doop" => ["pood"],
      "ilov" => ["viol"], "abeu" => ["beau"], "firt" => ["frit", "rift"],
      "aglm" => ["glam"], "bmot" => ["tomb"], "bekr" => ["berk"],
      "apst" => ["pats", "spat", "taps", "past"], "ffin" => ["niff"],
      "ffot" => ["toff"], "noss" => ["sons"], "bksu" => ["busk"],
      "deiw" => ["wide"], "ilpy" => ["pily"], "cdis" => ["disc"],
      "ahlo" => ["halo"], "ejll" => ["jell"], "eips" => ["pies"],
      "impr" => ["prim"], "iikt" => ["tiki"], "gluy" => ["ugly"],
      "flru" => ["furl"], "aflr" => ["farl"], "ilmt" => ["milt"],
      "orsw" => ["rows"], "afgr" => ["frag"], "dgir" => ["gird", "grid"],
      "cflo" => ["floc"], "erst" => ["rets", "erst", "rest"], "airt" => ["airt"],
      "lmpu" => ["plum", "lump"], "aadt" => ["data"], "osuy" => ["yous"],
      "begr" => ["berg"], "gill" => ["gill"], "ahhs" => ["shah", "hash"],
      "coos" => ["coos"], "bott" => ["bott"], "aekt" => ["teak", "take"],
      "agnu" => ["guan"], "fftu" => ["tuff"], "gmos" => ["smog"],
      "dehi" => ["hied", "hide"], "alnw" => ["lawn"], "hjno" => ["john"],
      "eepr" => ["peer"], "ipss" => ["psis", "piss", "sips"], "defy" => ["defy"],
      "birt" => ["brit"], "appu" => ["pupa"], "fllu" => ["full"],
      "eems" => ["seem"], "ilst" => ["silt", "slit", "list"], "einw" => ["wine"],
      "cglo" => ["clog"], "alyz" => ["lazy"], "bffu" => ["buff"],
      "adfo" => ["fado"], "eglu" => ["luge", "glue"], "epsw" => ["pews", "spew"],
      "degl" => ["geld"], "bist" => ["bits"], "acns" => ["cans", "scan"],
      "ekns" => ["kens"], "amry" => ["army"], "acep" => ["cape", "pace"],
      "effi" => ["fief", "fife"], "acen" => ["acne", "cane"], "aaer" => ["area"],
      "fgor" => ["frog"], "aenv" => ["vena", "nave", "vane"], "afll" => ["fall"],
      "afsy" => ["fays"], "aabs" => ["abas", "baas"], "beor" => ["robe", "bore"],
      "dgoo" => ["good"], "eikl" => ["like"], "aelo" => ["aloe"],
      "efll" => ["fell"], "aggn" => ["gang"], "dops" => ["pods"],
      "cess" => ["cess", "secs"], "imnx" => ["minx"], "amox" => ["moxa"],
      "ceru" => ["ecru", "cure"], "bitt" => ["bitt"], "ghtu" => ["thug"],
      "mopr" => ["prom", "romp"], "emnu" => ["menu"], "cilp" => ["clip"],
      "derv" => ["derv"], "anrt" => ["tarn", "rant"], "eekm" => ["meek"],
      "celu" => ["luce", "clue"], "anrw" => ["warn"], "aitv" => ["vita"],
      "ailx" => ["axil"], "ffir" => ["riff"], "moos" => ["moos"],
      "arzz" => ["razz"], "egos" => ["egos", "goes"], "cmor" => ["corm"],
      "kmru" => ["murk"], "abkr" => ["bark"], "eiks" => ["sike"],
      "egno" => ["gone"], "aisv" => ["visa"], "llmu" => ["mull"],
      "aalm" => ["lama"], "hlru" => ["hurl"],
      "aers" => ["ares", "eras", "sear", "ears"], "glno" => ["long"],
      "insw" => ["wins"], "lmoo" => ["loom"], "norw" => ["worn"],
      "pssu" => ["sups", "puss"], "iops" => ["piso"], "ceil" => ["ceil", "lice"],
      "aglo" => ["goal"], "achk" => ["hack"], "dllo" => ["doll"],
      "nopu" => ["upon"], "ahll" => ["hall"], "gkoo" => ["gook"],
      "eikn" => ["kine"], "elsu" => ["lues", "slue"], "aeil" => ["ilea"],
      "amrs" => ["mars", "rams", "arms"],
      "alps" => ["alps", "laps", "pals", "slap"], "egmu" => ["geum"],
      "ehwy" => ["whey"], "fikn" => ["fink"], "orty" => ["troy", "tyro"],
      "knop" => ["knop"], "aorv" => ["arvo"], "cnno" => ["conn"],
      "city" => ["city"], "aakr" => ["arak"], "eksy" => ["keys"],
      "ilmn" => ["limn"], "acll" => ["call"], "eipw" => ["wipe"],
      "eekk" => ["keek"], "chou" => ["chou", "ouch"], "anpt" => ["pant"],
      "abdl" => ["bald"], "cnoy" => ["cony"], "eefm" => ["feme"],
      "epst" => ["sept", "pest", "pets", "step"], "denr" => ["nerd", "rend"],
      "elpu" => ["pule"], "gosy" => ["goys"], "effs" => ["effs"],
      "botu" => ["bout"], "empr" => ["perm"],
      "inps" => ["nips", "snip", "pins", "spin"], "dmos" => ["mods"],
      "dosu" => ["duos"], "dloy" => ["odyl"], "bdin" => ["bind"],
      "adsw" => ["daws", "wads"], "ekty" => ["tyke"], "doow" => ["wood"],
      "lopp" => ["plop"], "allo" => ["olla"], "ekly" => ["kyle"],
      "deim" => ["idem", "dime"], "aisx" => ["axis"], "bilp" => ["blip"],
      "ehju" => ["jehu"], "bery" => ["byre"], "doty" => ["tody"],
      "biks" => ["bisk"], "eest" => ["tees"], "atuv" => ["vatu"],
      "egnp" => ["peng"], "deen" => ["dene", "need"], "aael" => ["alae"],
      "aimx" => ["maxi"], "chsu" => ["such"], "imrs" => ["rims"],
      "aepv" => ["vape", "pave"], "berw" => ["brew"], "elsw" => ["slew"],
      "adfs" => ["fads"], "imst" => ["mist"], "adms" => ["dams", "mads"],
      "enoz" => ["zone"], "agpw" => ["gawp"], "drtu" => ["turd"],
      "ahir" => ["hair"], "csty" => ["cyst"], "amyz" => ["mazy"],
      "kory" => ["york"], "almp" => ["palm", "lamp"], "mopp" => ["pomp"],
      "chos" => ["cosh"], "aprt" => ["prat", "tarp", "rapt", "part", "trap"],
      "ervy" => ["very"], "ertt" => ["tret"], "aabb" => ["abba", "baba"],
      "airs" => ["airs", "sari"], "akoy" => ["kayo"], "cklu" => ["luck"],
      "gior" => ["giro"], "eosw" => ["woes", "owes"], "akst" => ["skat", "task"],
      "alnu" => ["ulna"], "eprt" => ["pert"], "efht" => ["heft"],
      "abck" => ["back"], "eeft" => ["feet"], "cfio" => ["fico", "coif"],
      "ipsv" => ["spiv"], "nosy" => ["nosy"], "istu" => ["suit"],
      "fils" => ["fils"], "ghos" => ["gosh", "hogs"], "aflm" => ["flam"],
      "eeht" => ["thee"], "llot" => ["toll"], "acsy" => ["cays"],
      "aglu" => ["gula"], "akss" => ["asks"], "aano" => ["anoa"],
      "aemn" => ["amen", "mane", "mean", "name"], "fill" => ["fill"],
      "emot" => ["mote", "tome"], "dinw" => ["wind"], "gloo" => ["logo"],
      "eemt" => ["mete", "teem", "meet"], "hmsu" => ["hums", "mush"],
      "adks" => ["daks"], "eefl" => ["flee", "feel"], "abos" => ["soba", "boas"],
      "ikrs" => ["kris", "irks", "risk"], "bbel" => ["bleb"], "bmos" => ["mobs"],
      "dpsu" => ["puds", "spud"], "eijv" => ["jive"], "adpr" => ["pard"],
      "dder" => ["redd"], "ahmw" => ["wham"], "psuy" => ["yups"],
      "cikt" => ["tick"], "ahox" => ["hoax"], "hkno" => ["honk"],
      "bdel" => ["bled"], "dint" => ["dint"], "kloy" => ["yolk"],
      "esxy" => ["sexy"], "ably" => ["ably"], "ahpw" => ["whap"],
      "aefk" => ["fake"], "oops" => ["poos", "oops"], "dfno" => ["fond"],
      "knot" => ["knot"], "bkno" => ["bonk", "knob"], "aerz" => ["raze"],
      "ortt" => ["tort", "trot"], "aikv" => ["kiva"], "eesx" => ["exes"],
      "dgin" => ["ding"], "epty" => ["type"], "aekp" => ["peak"],
      "booz" => ["bozo"], "osww" => ["wows"], "birr" => ["birr"],
      "ehht" => ["heth"], "adkr" => ["dark"], "einp" => ["pine"],
      "glnu" => ["lung"], "eenw" => ["ween"], "fgos" => ["fogs"],
      "gllu" => ["gull"], "bbsu" => ["bubs"], "adde" => ["dead"],
      "adew" => ["awed", "wade"], "aiks" => ["sika"], "ainw" => ["wain"],
      "impp" => ["pimp"], "achs" => ["cash"], "chno" => ["chon"],
      "adhl" => ["dahl"], "gnow" => ["gown"], "amrt" => ["tram", "mart"],
      "ehrs" => ["hers"], "eers" => ["sere", "seer"], "eisz" => ["size"],
      "bort" => ["bort"], "cehz" => ["chez"], "iprs" => ["rips"],
      "ehww" => ["whew"], "achr" => ["arch", "char"], "klru" => ["lurk"],
      "adls" => ["lads"], "bpru" => ["burp"], "nors" => ["sorn"],
      "ckor" => ["cork", "rock"], "ikls" => ["ilks", "silk"], "dnou" => ["undo"],
      "cnos" => ["cons"], "ettx" => ["text"], "acmo" => ["coma"],
      "bgiu" => ["guib"], "besy" => ["beys", "byes"], "inpr" => ["pirn"],
      "oprw" => ["prow"], "beet" => ["beet"], "crtu" => ["curt"],
      "ehnw" => ["when"], "afit" => ["fiat"], "ehov" => ["hove"],
      "afhs" => ["fash"], "agmp" => ["gamp"], "aiqu" => ["quai"],
      "ekpr" => ["perk"], "cnsy" => ["sync"], "ipps" => ["pips"],
      "egmr" => ["germ"], "loss" => ["sols", "loss"], "dgis" => ["digs"],
      "adnw" => ["wand", "dawn"], "ddeu" => ["dude"], "noop" => ["poon"],
      "mssu" => ["muss", "sums"], "eint" => ["tine"], "ffim" => ["miff"],
      "elno" => ["enol", "leno", "noel", "lone"], "deky" => ["dyke"],
      "eenr" => ["erne"], "ijlt" => ["jilt"], "empt" => ["temp"],
      "iltw" => ["wilt"], "ciky" => ["icky"], "inst" => ["snit", "nits", "tins"],
      "abrt" => ["brat"], "bbmo" => ["bomb"], "eejz" => ["jeez"],
      "denu" => ["dune", "nude"], "bmpu" => ["bump"], "cent" => ["cent"],
      "adly" => ["lady"], "achy" => ["achy"], "aeeg" => ["agee"],
      "knoz" => ["zonk"], "ginw" => ["wing"], "acny" => ["cyan"],
      "eilv" => ["veil", "evil", "vile", "live"], "alop" => ["opal"],
      "gpsu" => ["pugs"], "akns" => ["sank"], "dgil" => ["gild"],
      "ceis" => ["ices"], "dilm" => ["mild"], "acln" => ["clan"],
      "gorw" => ["grow"], "adgl" => ["glad"], "glow" => ["glow"],
      "dhlo" => ["hold"], "ikln" => ["kiln", "link"],
      "aepr" => ["pare", "pear", "reap", "rape"], "bpsu" => ["pubs"],
      "gnoo" => ["goon"], "adrs" => ["sard", "rads"], "istt" => ["tits"],
      "adiq" => ["qadi"], "ossw" => ["sows"], "bios" => ["bios", "obis"],
      "cdik" => ["dick"], "ehop" => ["hope"], "desw" => ["dews", "weds"],
      "ddsu" => ["sudd", "duds"], "eopx" => ["expo"], "eikm" => ["mike"],
      "acjk" => ["jack"], "ekpt" => ["kept"], "bcmo" => ["comb"],
      "agkw" => ["gawk"], "aeln" => ["lane", "lean"], "hlop" => ["holp"],
      "glop" => ["glop"], "dort" => ["trod"], "bilr" => ["birl"],
      "most" => ["mots", "toms", "most"], "ptuz" => ["putz"], "filp" => ["flip"],
      "rstu" => ["rust", "ruts"], "ikny" => ["inky"], "cdku" => ["duck"],
      "adem" => ["mead", "dame", "made"], "aikl" => ["kail", "kali"],
      "alnp" => ["plan"], "efss" => ["fess"], "ahnt" => ["tanh", "than"],
      "clot" => ["clot", "colt"], "gnsu" => ["gnus", "snug", "guns", "sung"],
      "ceoz" => ["coze"], "aost" => ["oast", "stoa", "oats"],
      "cdeu" => ["duce", "cued"], "eflx" => ["flex"], "deow" => ["owed"],
      "isst" => ["sits"], "deiv" => ["vide", "vied", "dive"], "ajzz" => ["jazz"],
      "ders" => ["reds"], "opty" => ["typo"], "ehsw" => ["shew", "hews"],
      "bntu" => ["bunt"], "eosv" => ["voes"], "ikst" => ["kist", "skit", "kits"],
      "beoo" => ["oboe"], "aegl" => ["gale"], "ehss" => ["shes"],
      "eopr" => ["pore", "rope"], "adex" => ["axed"], "klos" => ["skol"],
      "alpw" => ["pawl"], "cikr" => ["rick"], "brru" => ["burr"],
      "fmor" => ["form", "from"], "ahkp" => ["kaph"], "hpuw" => ["whup"],
      "cdos" => ["docs", "cods"], "enps" => ["pens"], "ddio" => ["dido"],
      "acrw" => ["craw"], "gpsy" => ["gyps"], "fttu" => ["tuft"],
      "ddey" => ["dyed", "eddy"], "cekr" => ["reck"], "hoot" => ["hoot"],
      "aeru" => ["urea"], "efor" => ["froe", "fore"], "ghot" => ["goth"],
      "ackr" => ["cark", "rack"], "abns" => ["nabs", "bans"],
      "eort" => ["rote", "tore"], "deew" => ["weed"], "abss" => ["bass"],
      "hksu" => ["husk"], "adiv" => ["diva", "avid"], "acce" => ["ceca"],
      "cilt" => ["clit"], "bdru" => ["drub"], "eity" => ["yeti"],
      "egrs" => ["ergs"], "inty" => ["tiny"], "grtu" => ["trug"],
      "eopt" => ["tope", "poet"], "almu" => ["alum", "maul"], "ckoo" => ["cook"],
      "bell" => ["bell"], "ginz" => ["zing"], "abby" => ["baby"],
      "ijnn" => ["jinn"], "aelr" => ["rale", "earl", "real"],
      "ahor" => ["hoar", "hora"], "deir" => ["dire", "ride"], "acgr" => ["crag"],
      "prsy" => ["spry"], "entv" => ["vent"], "hosy" => ["hoys"],
      "morw" => ["worm"], "cist" => ["cist", "tics"], "enru" => ["rune"],
      "himw" => ["whim"], "dens" => ["dens", "ends", "send"], "aiix" => ["ixia"],
      "acvy" => ["cavy"], "orxy" => ["oryx"],
      "ahrt" => ["rath", "tahr", "thar", "hart"], "deru" => ["rued", "rude"],
      "acdi" => ["cadi", "acid"], "eekl" => ["keel", "leek"],
      "emsu" => ["emus", "muse"], "ansv" => ["vans"], "prru" => ["purr"],
      "fgsu" => ["fugs"], "ehos" => ["hoes", "hose", "shoe"],
      "enst" => ["nest", "nets", "tens", "sent"], "ellt" => ["tell"],
      "amnu" => ["maun"], "emss" => ["mess"], "aors" => ["sora", "oars", "soar"],
      "ersv" => ["revs"], "fino" => ["fino", "foin", "info"],
      "ahps" => ["pash", "hasp"], "ehnt" => ["hent", "then"],
      "adim" => ["amid", "maid"], "optu" => ["pout"], "aotu" => ["auto"],
      "afgs" => ["fags"], "gopy" => ["pogy"], "eefs" => ["fees"],
      "nssu" => ["suns"], "adef" => ["fade", "deaf"], "hrsu" => ["rush"],
      "hoos" => ["oohs", "shoo"], "dipr" => ["drip"], "alno" => ["loan"],
      "aafh" => ["haaf"], "cost" => ["cots", "cost"], "actt" => ["tact"],
      "agku" => ["kagu"], "ditz" => ["ditz"], "dkuu" => ["kudu"],
      "klsu" => ["sulk"], "ekor" => ["kero"], "ejtu" => ["jute"],
      "ceho" => ["echo"], "bhlu" => ["buhl"], "hswy" => ["whys"],
      "boos" => ["boos"], "abgm" => ["gamb"], "dlos" => ["dols", "sold"],
      "estv" => ["vest", "vets"], "bins" => ["nibs", "bins"], "ilnn" => ["linn"],
      "afik" => ["kaif"], "eggs" => ["eggs"], "fopr" => ["prof"],
      "deoz" => ["doze"], "dkou" => ["kudo"], "ahlr" => ["harl"],
      "bloo" => ["bolo", "lobo"], "abhs" => ["bash"], "nopy" => ["pony"],
      "estu" => ["suet"], "hopw" => ["whop"], "flow" => ["fowl", "wolf", "flow"],
      "bcru" => ["curb"], "ckpu" => ["puck"], "ackt" => ["tack"],
      "elst" => ["lest", "lets"], "gmru" => ["grum"], "aclx" => ["calx"],
      "lppu" => ["pulp"], "hkop" => ["koph"], "afrt" => ["fart", "frat", "raft"],
      "iitt" => ["titi"], "acps" => ["caps"], "afor" => ["faro"],
      "dopr" => ["dorp", "prod", "drop"], "filt" => ["flit", "lift"],
      "ahkt" => ["khat"], "cehs" => ["sech"], "anry" => ["nary", "yarn"],
      "adhn" => ["hand"], "iprt" => ["trip"], "dirs" => ["rids"],
      "beoy" => ["obey"], "blot" => ["blot", "bolt"], "bruy" => ["ruby", "bury"],
      "enrw" => ["wren"], "eksw" => ["skew"], "dffo" => ["doff"],
      "ampu" => ["puma"], "akrt" => ["kart"], "egvy" => ["gyve"],
      "foop" => ["poof"], "gkow" => ["gowk"], "abfr" => ["barf"],
      "eglo" => ["loge", "ogle"], "dflo" => ["fold"], "ador" => ["road"],
      "aemz" => ["maze"], "oprt" => ["port"], "abry" => ["bray"],
      "doxy" => ["doxy"], "deip" => ["pied"], "artw" => ["wart"],
      "anpw" => ["pawn"], "ceim" => ["mice"], "bein" => ["bine"],
      "bbou" => ["bubo"], "ginr" => ["grin", "ring"], "eivw" => ["wive", "view"],
      "ckos" => ["sock"], "cnoo" => ["coon"], "celo" => ["cole"],
      "acpy" => ["pacy"], "cdee" => ["cede"], "jlow" => ["jowl"],
      "cfku" => ["fuck"], "agsw" => ["swag", "wags"], "knru" => ["knur"],
      "emsw" => ["smew", "mews"], "ottu" => ["tout"], "aair" => ["aria"],
      "asss" => ["sass"], "absy" => ["bays"], "adlu" => ["laud", "dual"],
      "ddos" => ["odds"], "abjs" => ["jabs"], "cikw" => ["wick"],
      "cinz" => ["zinc"], "acef" => ["face"], "abgn" => ["bang"],
      "bevy" => ["bevy"], "ekop" => ["poke"], "cchi" => ["chic"],
      "bdir" => ["bird"], "adgs" => ["dags", "gads"], "aefn" => ["fane"],
      "iilp" => ["pili"], "fknu" => ["funk"], "amsw" => ["maws", "swam"],
      "ehis" => ["hies"], "oott" => ["otto", "toot"], "ossu" => ["sous"],
      "elmy" => ["ylem"], "ffhu" => ["huff"], "ainv" => ["vina", "vain"],
      "dfry" => ["fyrd"], "afht" => ["haft"], "enow" => ["enow"],
      "ceko" => ["coke"], "ahmt" => ["math"], "airy" => ["airy"],
      "cntu" => ["cunt"], "abju" => ["juba"], "aivv" => ["viva"],
      "hitw" => ["whit", "with"], "assw" => ["saws"], "abll" => ["ball"],
      "illt" => ["lilt", "till"], "doss" => ["doss", "sods"],
      "estt" => ["stet", "sett", "test"], "akny" => ["yank"], "acfl" => ["calf"],
      "bgru" => ["burg", "grub"], "lstu" => ["slut", "lust"], "ekot" => ["toke"],
      "dors" => ["rods"], "adgw" => ["gawd"],
      "ilno" => ["noil", "lino", "loin", "lion"], "insu" => ["unis"],
      "deny" => ["dyne", "deny"], "ailt" => ["lati", "tali", "tail"],
      "foru" => ["four"], "ffiy" => ["iffy"], "deps" => ["sped"],
      "nnsu" => ["sunn", "nuns"], "gmsu" => ["gums", "mugs", "smug"],
      "ilor" => ["roil"], "aelw" => ["wale", "weal"], "ailm" => ["mail"],
      "oosz" => ["zoos"], "ells" => ["ells", "sell"], "fotu" => ["tofu"],
      "ellw" => ["well"], "eemn" => ["mene"], "eilx" => ["ilex"],
      "aeek" => ["akee"], "aess" => ["seas"], "cmoo" => ["coom"],
      "ggno" => ["gong"], "abcr" => ["crab"], "eprs" => ["reps"],
      "efrt" => ["reft", "fret"], "aclp" => ["clap"], "buzz" => ["buzz"],
      "adei" => ["aide", "idea"], "aesx" => ["axes"], "mort" => ["mort"],
      "gltu" => ["glut"], "eknu" => ["nuke"], "brtu" => ["brut"],
      "adlr" => ["lard"], "iswy" => ["ywis"], "agit" => ["gait"],
      "dins" => ["dins"], "eess" => ["esse", "sees"], "eepp" => ["peep"],
      "dely" => ["yeld"], "apsy" => ["pyas", "spay", "yaps", "pays"],
      "doqu" => ["quod"], "kors" => ["kors"], "abor" => ["bora", "boar"],
      "adir" => ["arid", "raid"], "dmoo" => ["doom", "mood"], "crux" => ["crux"],
      "bfis" => ["fibs"], "aefz" => ["faze"], "aahy" => ["ayah"],
      "abnr" => ["barn", "bran"], "aenw" => ["anew", "wane", "wean"],
      "aeks" => ["keas", "sake"], "moss" => ["moss"], "epru" => ["pure"],
      "aakt" => ["taka"], "aghn" => ["hang"], "oost" => ["soot"],
      "einn" => ["nine"], "anwy" => ["yawn"], "agnr" => ["gran", "rang"],
      "gins" => ["gins", "sing", "sign"], "moot" => ["moot"],
      "apss" => ["asps", "saps", "spas", "pass"], "eknt" => ["kent"],
      "abgs" => ["gabs", "bags"], "egly" => ["gley"],
      "bors" => ["sorb", "orbs", "robs"], "goop" => ["pogo", "goop"],
      "dewy" => ["dewy"], "akrs" => ["arks"], "foow" => ["woof"],
      "eimr" => ["rime", "emir", "mire"], "ffmu" => ["muff"], "affn" => ["naff"],
      "kmsu" => ["musk"], "aamr" => ["mara"], "jknu" => ["junk"],
      "agos" => ["sago"], "losu" => ["soul"], "aknr" => ["knar", "nark", "rank"],
      "eknw" => ["knew"], "iknp" => ["pink"], "aceh" => ["ache", "each"],
      "aprr" => ["parr"], "lotv" => ["volt"], "imrt" => ["trim"],
      "aafr" => ["afar"], "akms" => ["mask"], "elux" => ["luxe"],
      "lpru" => ["purl"], "eipr" => ["peri", "pier", "ripe"], "eipy" => ["yipe"],
      "aans" => ["anas"], "ehir" => ["heir", "hire"], "inru" => ["ruin"],
      "defs" => ["feds"], "orst" => ["orts", "tors", "rots", "sort"],
      "borw" => ["brow"], "ijvy" => ["jivy"], "eloo" => ["oleo"],
      "dlor" => ["lord"], "gnru" => ["rung"], "adik" => ["kadi"],
      "einr" => ["rein"], "elsy" => ["leys", "lyse"], "hmoo" => ["homo"],
      "eehl" => ["heel"], "agnv" => ["vang"], "demy" => ["demy"],
      "foxy" => ["foxy"], "demo" => ["demo", "dome", "mode"], "fgoo" => ["goof"],
      "nops" => ["pons"], "coot" => ["coot"],
      "ersu" => ["suer", "rues", "ruse", "sure", "user"], "acco" => ["coca"],
      "bees" => ["bees"], "eesw" => ["ewes", "wees"], "ahil" => ["hila", "hail"],
      "adej" => ["jade"], "hint" => ["hint", "thin"], "bmow" => ["womb"],
      "aber" => ["brae", "bare", "bear"], "cekn" => ["neck"],
      "gikn" => ["gink", "king"], "acpt" => ["pact"], "illo" => ["lilo"],
      "cerw" => ["crew"], "cdor" => ["cord"], "afin" => ["naif", "fain"],
      "dino" => ["nodi"], "detu" => ["duet"], "chip" => ["chip"],
      "eimm" => ["mime"], "aklt" => ["talk"], "bhos" => ["bosh", "hobs"],
      "aajv" => ["java"], "ddru" => ["rudd"], "bosw" => ["bows"],
      "abls" => ["albs", "slab", "labs"], "arvy" => ["vary"], "ipsz" => ["zips"],
      "cffo" => ["coff"], "fhis" => ["fish"], "hotu" => ["thou"],
      "aknw" => ["wank"], "hops" => ["posh", "hops", "shop"],
      "dgos" => ["dogs", "gods"], "ckno" => ["nock", "conk"],
      "bnsu" => ["nubs", "buns", "snub"], "enrt" => ["tern", "rent"],
      "aaln" => ["anal"], "opsw" => ["wops"], "dnwy" => ["wynd"],
      "eggy" => ["yegg"], "almt" => ["malt"], "ekps" => ["skep"],
      "fkor" => ["fork"], "aegt" => ["gate"], "dehl" => ["held"],
      "aimm" => ["imam", "maim"], "fklo" => ["folk"], "imry" => ["rimy", "miry"],
      "lotu" => ["tolu", "lout"], "deek" => ["eked"], "akty" => ["kyat"],
      "iloy" => ["oily"], "dilo" => ["olid", "lido", "idol"],
      "cino" => ["cion", "coin", "icon"], "eoyz" => ["oyez"],
      "amno" => ["noma", "moan"], "entw" => ["newt", "went"], "loow" => ["wool"],
      "cesu" => ["cues"], "ceno" => ["cone", "once"], "glmu" => ["glum"],
      "aelv" => ["leva", "lave", "vela", "vale", "veal"], "hlmo" => ["holm"],
      "eehr" => ["here"], "dils" => ["sild", "lids", "slid"], "dglo" => ["gold"],
      "abbe" => ["babe"], "adrw" => ["ward", "draw"]}
  end
end
