defmodule Jumble.ScowlDict.Medium.Length3 do
  def get(string_id) do
    %{"hot" => ["tho"], "inu" => ["uni"], "osy" => ["soy"], "abf" => ["fab"],
      "bde" => ["deb"], "agj" => ["jag"], "muy" => ["yum"], "ehi" => ["hie"],
      "hnt" => ["nth"], "aey" => ["yea"], "eil" => ["lei"], "bil" => ["lib"],
      "npw" => ["pwn"], "ahp" => ["pah"], "abl" => ["alb"], "aft" => ["aft"],
      "bdo" => ["bod", "dob"], "ops" => ["ops"], "epy" => ["yep"], "tux" => ["tux"],
      "acm" => ["mac"], "amt" => ["tam"], "aps" => ["asp"], "ell" => ["ell"],
      "diy" => ["yid"], "dim" => ["mid"], "aot" => ["oat"], "aet" => ["eta"],
      "imo" => ["moi"], "fop" => ["fop"], "hmm" => ["hmm"], "hor" => ["rho"],
      "cit" => ["tic"], "itz" => ["zit"], "iko" => ["oik"], "bbu" => ["bub"],
      "hss" => ["ssh"], "fot" => ["oft"], "los" => ["sol"], "emu" => ["emu"],
      "egv" => ["veg"], "alw" => ["awl"], "ems" => ["ems"], "abp" => ["bap"],
      "bfo" => ["fob"], "cho" => ["och"], "dpu" => ["pud"], "efi" => ["fie"],
      "egm" => ["meg"], "dis" => ["ids", "dis"], "guv" => ["guv"], "ehp" => ["hep"],
      "ilt" => ["til"], "efr" => ["fer", "ref"], "det" => ["ted"], "boy" => ["yob"],
      "ahj" => ["haj"], "adt" => ["tad"], "dnu" => ["dun"], "hos" => ["hos"],
      "bor" => ["orb"], "ehm" => ["meh"], "mpu" => ["ump"], "iss" => ["sis"],
      "enw" => ["wen"], "bru" => ["bur"], "amm" => ["mam"], "ehx" => ["hex"],
      "kuy" => ["yuk"], "imv" => ["vim"], "aku" => ["auk"], "cip" => ["pic"],
      "hoo" => ["ooh", "oho"], "noy" => ["yon"], "bnu" => ["nub"], "cdu" => ["cud"],
      "git" => ["git"], "mot" => ["tom"], "biz" => ["biz"], "got" => ["tog"],
      "ikp" => ["kip"], "dez" => ["zed"], "ipy" => ["yip"], "bho" => ["hob"],
      "ost" => ["sot"], "iny" => ["yin"], "puy" => ["yup"], "ael" => ["lea"],
      "emo" => ["emo"], "pxy" => ["pyx"], "lop" => ["pol"], "oop" => ["poo"],
      "sty" => ["sty"], "brr" => ["brr"], "abh" => ["bah"], "cim" => ["mic"],
      "aks" => ["ska"], "cor" => ["orc"], "ceu" => ["ecu"], "loo" => ["loo"],
      "aab" => ["baa"], "efy" => ["fey"], "ipx" => ["pix"], "asx" => ["sax"],
      "ipp" => ["pip"], "afg" => ["fag"], "att" => ["tat"], "fgu" => ["fug"],
      "aah" => ["aah", "aha"], "inx" => ["nix"], "eer" => ["ere"], "egr" => ["erg"],
      "ery" => ["yer"], "ilm" => ["mil"], "amw" => ["maw"], "acv" => ["vac"],
      "ntu" => ["tun"], "ort" => ["tor"], "cdo" => ["doc"], "ahn" => ["nah"],
      "hhs" => ["shh"], "ttu" => ["tut"], "bij" => ["jib"], "mop" => ["pom"],
      "alm" => ["lam"], "eep" => ["pee"], "mtu" => ["tum"], "osu" => ["sou"],
      "dho" => ["hod"], "opx" => ["pox"], "epr" => ["rep"], "lox" => ["lox"],
      "gow" => ["wog"], "awy" => ["yaw"], "bno" => ["nob"], "dhu" => ["duh"],
      "gpy" => ["gyp"], "aen" => ["nae"], "iop" => ["poi"], "ahw" => ["haw"],
      "eek" => ["eek"], "bin" => ["nib"], "opw" => ["pow", "wop"], "apz" => ["zap"],
      "ims" => ["ism", "sim"], "gpu" => ["pug"], "adg" => ["gad"], "afx" => ["fax"]}
    |> Map.get(string_id)
  end
end
