defmodule Jumble.ScowlDict.Medium.Length4 do
  def get(string_id) do
    %{"cder" => ["cred"], "hstu" => ["tush"], "eilw" => ["wile"],
      "adgn" => ["dang"], "ilmy" => ["limy"], "akln" => ["lank"],
      "aefv" => ["fave"], "gnos" => ["snog"], "eflo" => ["floe"],
      "dhow" => ["dhow"], "agms" => ["mags"], "ksuy" => ["yuks"],
      "desz" => ["zeds"], "eilt" => ["lite"], "apps" => ["apps", "paps"],
      "aesy" => ["yeas"], "krsu" => ["rusk"], "lnxy" => ["lynx"],
      "elos" => ["sloe"], "gosw" => ["wogs"], "emos" => ["emos"],
      "aggo" => ["agog"], "ahst" => ["hast"], "clop" => ["clop"],
      "aelt" => ["teal"], "amps" => ["spam"], "impw" => ["wimp"],
      "eils" => ["leis"], "noxy" => ["onyx"], "acio" => ["ciao"],
      "cepu" => ["puce"], "oouz" => ["ouzo"], "eoru" => ["euro"],
      "ceps" => ["pecs", "spec"], "bfos" => ["fobs"], "elmw" => ["mewl"],
      "hrtu" => ["thru"], "denw" => ["wend"], "fopu" => ["pouf"],
      "cjko" => ["jock"], "abps" => ["baps"], "eims" => ["semi"],
      "psst" => ["psst"], "aehr" => ["rhea"], "cdeo" => ["coed"],
      "loos" => ["loos"], "adry" => ["dray"], "acsv" => ["vacs"],
      "efrs" => ["serf", "refs"], "bboo" => ["boob"], "aint" => ["anti"],
      "belo" => ["bole"], "deis" => ["ides"], "delo" => ["lode"],
      "anss" => ["sans"], "hist" => ["shit"], "beuz" => ["zebu"],
      "aeps" => ["apse"], "ahsy" => ["ashy"], "ftuz" => ["futz"],
      "cdru" => ["crud"], "mstu" => ["tums"], "clow" => ["cowl"],
      "anuy" => ["yuan"], "eppr" => ["prep"], "ejoy" => ["joey"],
      "abde" => ["abed"], "biot" => ["obit"], "ablo" => ["bola"],
      "know" => ["wonk"], "ahht" => ["hath"], "amms" => ["mams"],
      "adow" => ["woad"], "agny" => ["yang"], "istz" => ["zits"],
      "lluu" => ["lulu"], "bgno" => ["bong"], "ginp" => ["ping"],
      "enpt" => ["pent"], "dikr" => ["dirk"], "dlou" => ["ludo"],
      "eilr" => ["lire"], "cdsu" => ["cuds", "scud"], "ciru" => ["uric"],
      "aopt" => ["atop"], "aclo" => ["cola"], "delv" => ["veld"],
      "ackw" => ["wack"], "acst" => ["scat"], "hipt" => ["pith"],
      "arty" => ["arty"], "adqu" => ["quad"], "adrt" => ["drat", "trad"],
      "ttuu" => ["tutu"], "bglo" => ["glob"], "aksu" => ["skua", "auks"],
      "lops" => ["pols"], "osst" => ["sots"], "mosu" => ["sumo"],
      "belu" => ["lube"], "kosu" => ["souk"], "cips" => ["pics", "spic"],
      "inow" => ["wino"], "efst" => ["fest"], "abfl" => ["flab"],
      "ahjj" => ["hajj"], "cehk" => ["heck"], "ilms" => ["mils"],
      "bemr" => ["berm"], "inqu" => ["quin"], "aagg" => ["gaga"],
      "aehk" => ["hake"], "bdes" => ["debs"], "eory" => ["yore"],
      "adst" => ["tads"], "egls" => ["gels"], "aaqu" => ["aqua"],
      "ckru" => ["ruck"], "mpsu" => ["sump", "umps"], "amoy" => ["mayo"],
      "cims" => ["mics"], "mnoo" => ["mono"], "ostw" => ["swot"],
      "hlos" => ["hols"], "ooyz" => ["oozy"], "amst" => ["tams"],
      "abim" => ["iamb"], "egns" => ["gens"], "aben" => ["bane"],
      "hoop" => ["pooh"], "clos" => ["cols"], "brsu" => ["burs"],
      "ampt" => ["tamp"], "aert" => ["tare"], "girt" => ["girt", "trig"],
      "cein" => ["cine"], "eekp" => ["peke"], "apsz" => ["zaps"],
      "aagr" => ["agar", "raga"], "npsw" => ["pwns"], "dhos" => ["dosh", "hods"],
      "cpsu" => ["cusp"], "adhs" => ["shad"], "aeft" => ["feta"],
      "hmos" => ["mosh"], "acip" => ["pica"], "delm" => ["meld"],
      "aluu" => ["luau"], "bfmu" => ["bumf"], "inov" => ["vino"],
      "ehpw" => ["phew"], "sttu" => ["tuts"], "dhot" => ["doth"],
      "diqu" => ["quid"], "afly" => ["flay"], "bikl" => ["bilk"],
      "eluy" => ["yule"], "agmy" => ["gamy"], "acds" => ["cads", "scad"],
      "aels" => ["leas"], "film" => ["milf"], "cior" => ["coir"],
      "einz" => ["zine"], "ggor" => ["grog"], "gost" => ["togs"],
      "cikm" => ["mick"], "alst" => ["lats"], "adez" => ["adze"],
      "ckop" => ["pock"], "aipt" => ["pita"], "agjs" => ["jags"],
      "gioy" => ["yogi"], "anox" => ["axon"], "imss" => ["isms", "sims"],
      "eemm" => ["meme"], "acim" => ["mica"], "adgo" => ["dago"],
      "aelz" => ["laze"], "aekl" => ["kale"], "ahkn" => ["ankh", "hank", "khan"],
      "ahlu" => ["hula"], "alwy" => ["yawl"], "eikk" => ["kike"],
      "nopr" => ["porn"], "eepv" => ["veep"], "alsv" => ["lavs"],
      "biis" => ["ibis"], "dlot" => ["dolt"], "aghs" => ["shag"],
      "aehy" => ["yeah"], "ikps" => ["kips"], "dest" => ["teds"],
      "egor" => ["goer"], "eorv" => ["rove"], "afnu" => ["faun"],
      "notw" => ["nowt"], "iopt" => ["topi"], "abst" => ["bast"],
      "astt" => ["tats"], "sssu" => ["suss"], "bcek" => ["beck"],
      "bops" => ["bops"], "eels" => ["lees"], "belp" => ["pleb"],
      "llmo" => ["moll"], "anor" => ["roan"], "aest" => ["sate"],
      "ehpy" => ["hype"], "hikt" => ["kith"], "gist" => ["gits"],
      "ikno" => ["oink"], "eeps" => ["pees"], "celw" => ["clew"],
      "cssu" => ["cuss"], "illr" => ["rill"], "cloy" => ["cloy"],
      "hjos" => ["josh"], "ijkn" => ["jink"], "afln" => ["flan"],
      "bgir" => ["brig"], "eirw" => ["weir"], "nstu" => ["tuns"],
      "bosy" => ["yobs"], "beep" => ["beep"], "deep" => ["peed"],
      "bffi" => ["biff"], "adgr" => ["grad"], "ccho" => ["choc"],
      "acem" => ["acme"], "abet" => ["bate"], "aent" => ["ante"],
      "beru" => ["rube"], "beix" => ["ibex"], "admr" => ["dram"],
      "door" => ["rood"], "ceot" => ["cote"], "alms" => ["lams"],
      "bflu" => ["flub"], "eerw" => ["ewer"], "ahiy" => ["hiya"],
      "cehl" => ["lech"], "adiw" => ["wadi"], "dery" => ["dyer"],
      "eejp" => ["jeep"], "alsw" => ["awls", "slaw"], "aerv" => ["aver"],
      "ampv" => ["vamp"], "acms" => ["macs", "cams", "scam"], "ipsy" => ["yips"],
      "cosw" => ["scow"], "beiv" => ["vibe"], "gknu" => ["gunk"],
      "lnor" => ["lorn"], "orux" => ["roux"], "eiln" => ["lien"],
      "addo" => ["dado"], "hnos" => ["nosh"], "efns" => ["fens"],
      "fgir" => ["frig"], "itzz" => ["tizz"], "disy" => ["yids"],
      "doyz" => ["dozy"], "abhl" => ["blah"], "ffgu" => ["guff"],
      "ailr" => ["lira"], "esty" => ["yest"], "dlow" => ["wold"],
      "dmor" => ["dorm"], "opry" => ["ropy"], "noty" => ["tony"],
      "aegm" => ["mega"], "eegh" => ["ghee"], "abgl" => ["blag"],
      "efil" => ["lief"], "bnos" => ["nobs"], "hopy" => ["hypo"],
      "beir" => ["brie", "bier"], "aehm" => ["ahem"], "kkoo" => ["kook"],
      "ceex" => ["exec"], "aort" => ["rota", "taro"], "iikw" => ["wiki"],
      "epsy" => ["espy", "yeps"], "egms" => ["megs"], "dost" => ["dost"],
      "lopy" => ["poly"], "chit" => ["chit"], "gipr" => ["prig"],
      "dell" => ["dell"], "gnop" => ["pong"], "adnr" => ["rand"],
      "aegu" => ["ague"], "dory" => ["dory"], "ilmo" => ["limo"],
      "egit" => ["gite"], "affg" => ["gaff"], "cloo" => ["loco"],
      "eftw" => ["weft"], "dnsu" => ["duns"], "hklo" => ["kohl"],
      "abdr" => ["brad"], "hims" => ["shim"], "aflx" => ["flax"],
      "ammo" => ["ammo"], "mops" => ["poms"], "enop" => ["pone", "nope"],
      "filo" => ["filo"], "aems" => ["mesa"], "aann" => ["naan"],
      "fops" => ["fops"], "ittw" => ["twit"], "bdos" => ["bods", "dobs"],
      "eegk" => ["geek"], "host" => ["hots", "tosh"], "acdo" => ["coda"],
      "acnr" => ["narc"], "abtu" => ["abut"], "ahsw" => ["haws"],
      "afff" => ["faff"], "aswy" => ["yaws"], "iimn" => ["mini"],
      "bijs" => ["jibs"], "attw" => ["twat"], "gsuv" => ["guvs"],
      "gory" => ["gyro"], "ikos" => ["oiks"], "elov" => ["vole"],
      "eops" => ["peso"], "crsu" => ["curs"], "dkor" => ["dork"],
      "nosu" => ["nous"], "aejp" => ["jape"], "iswz" => ["swiz"],
      "adel" => ["dale"], "bllo" => ["boll"], "aerw" => ["ware"],
      "boxy" => ["boxy"], "loru" => ["lour"], "ensw" => ["wens"],
      "acff" => ["caff"], "ssuw" => ["wuss"], "cors" => ["orcs"],
      "cilo" => ["loci"], "ilov" => ["viol"], "abeu" => ["beau"],
      "aglm" => ["glam"], "bekr" => ["berk"], "ffin" => ["niff"],
      "ffot" => ["toff"], "bksu" => ["busk"], "dgir" => ["gird"],
      "begr" => ["berg"], "ahhs" => ["shah"], "dehi" => ["hied"],
      "hjno" => ["john"], "ipss" => ["piss"], "appu" => ["pupa"],
      "eglu" => ["luge"], "ekns" => ["kens"], "effi" => ["fief", "fife"],
      "aenv" => ["nave"], "aabs" => ["baas"], "aelo" => ["aloe"],
      "cess" => ["secs"], "imnx" => ["minx"], "ceru" => ["ecru"],
      "derv" => ["derv"], "anrt" => ["tarn"], "ffir" => ["riff"],
      "arzz" => ["razz"], "cmor" => ["corm"], "kmru" => ["murk"],
      "aalm" => ["lama"], "pssu" => ["sups"], "gkoo" => ["gook"],
      "elsu" => ["slue"], "ehwy" => ["whey"], "fikn" => ["fink"],
      "orty" => ["troy", "tyro"], "ilmn" => ["limn"], "cnoy" => ["cony"],
      "denr" => ["nerd"], "effs" => ["effs"], "empr" => ["perm"],
      "dmos" => ["mods"], "dosu" => ["duos"], "ekty" => ["tyke"],
      "deim" => ["idem"], "bery" => ["byre"], "aepv" => ["vape"],
      "agpw" => ["gawp"], "drtu" => ["turd"], "chos" => ["cosh"],
      "aprt" => ["prat", "tarp"], "gior" => ["giro"], "alnu" => ["ulna"],
      "efht" => ["heft"], "cfio" => ["coif"], "ipsv" => ["spiv"],
      "emot" => ["mote"], "dpsu" => ["puds"], "eijv" => ["jive"],
      "ahmw" => ["wham"], "psuy" => ["yups"], "dint" => ["dint"],
      "oops" => ["poos", "oops"], "bkno" => ["bonk"], "ortt" => ["tort"],
      "eesx" => ["exes"], "dgin" => ["ding"], "booz" => ["bozo"],
      "bbsu" => ["bubs"], "impp" => ["pimp"], "amrt" => ["tram"],
      "eers" => ["sere"], "ikls" => ["ilks"], "afit" => ["fiat"],
      "cnsy" => ["sync"], "ipps" => ["pips"], "loss" => ["sols"],
      "eint" => ["tine"], "ffim" => ["miff"], "elno" => ["noel"],
      "deky" => ["dyke"], "empt" => ["temp"], "ciky" => ["icky"],
      "inst" => ["snit"], "eejz" => ["jeez"], "achy" => ["achy"],
      "acny" => ["cyan"], "gpsu" => ["pugs"], "bpsu" => ["pubs"],
      "cdik" => ["dick"], "eopx" => ["expo"], "glop" => ["glop"],
      "most" => ["toms"], "ptuz" => ["putz"], "adem" => ["mead"],
      "efss" => ["fess"], "aost" => ["oats"], "opty" => ["typo"],
      "bntu" => ["bunt"], "alpw" => ["pawl"], "cikr" => ["rick"],
      "hpuw" => ["whup"], "cdos" => ["docs"], "acrw" => ["craw"],
      "gpsy" => ["gyps"], "aeru" => ["urea"], "ghot" => ["goth"],
      "adiv" => ["diva"], "cilt" => ["clit"], "bdru" => ["drub"],
      "egrs" => ["ergs"], "grtu" => ["trug"], "almu" => ["alum"],
      "ginz" => ["zing"], "ijnn" => ["jinn"], "cist" => ["tics"],
      "emsu" => ["emus"], "ahps" => ["hasp"], "afgs" => ["fags"],
      "hoos" => ["oohs"], "bins" => ["nibs"], "fopr" => ["prof"],
      "estu" => ["suet"], "hopw" => ["whop"], "afrt" => ["fart", "frat"],
      "anry" => ["nary"], "dffo" => ["doff"], "akrt" => ["kart"],
      "foop" => ["poof"], "abfr" => ["barf"], "eglo" => ["loge"],
      "deip" => ["pied"], "cnoo" => ["coon"], "acpy" => ["pacy"],
      "jlow" => ["jowl"], "cfku" => ["fuck"], "agsw" => ["swag"],
      "asss" => ["sass"], "bevy" => ["bevy"], "adgs" => ["dags", "gads"],
      "fknu" => ["funk"], "amsw" => ["maws"], "ehis" => ["hies"],
      "afht" => ["haft"], "cntu" => ["cunt"], "aivv" => ["viva"],
      "hitw" => ["whit"], "doss" => ["doss"], "estt" => ["sett"],
      "bgru" => ["burg"], "ekot" => ["toke"], "adgw" => ["gawd"],
      "ilno" => ["lino"], "insu" => ["unis"], "ffiy" => ["iffy"],
      "ilor" => ["roil"], "aelw" => ["wale", "weal"], "ells" => ["ells"],
      "fotu" => ["tofu"], "eprs" => ["reps"], "eknu" => ["nuke"],
      "agnr" => ["gran"], "apss" => ["asps"], "bors" => ["orbs"],
      "goop" => ["goop"], "dewy" => ["dewy"], "eimr" => ["rime"],
      "affn" => ["naff"], "agos" => ["sago"], "aknr" => ["nark"],
      "lpru" => ["purl"], "orst" => ["tors"], "eloo" => ["oleo"],
      "demo" => ["demo"], "coot" => ["coot"], "aber" => ["brae"],
      "illo" => ["lilo"], "afin" => ["fain"], "bhos" => ["bosh", "hobs"],
      "abls" => ["albs"], "aknw" => ["wank"], "hops" => ["posh"],
      "ckno" => ["conk"], "bnsu" => ["nubs"], "enrt" => ["tern"],
      "opsw" => ["wops"], "aimm" => ["imam"], "lotu" => ["lout"],
      "dilo" => ["lido"], "aelv" => ["vale"]}
    |> Map.get(string_id)
  end
end
