defmodule Jumble.ScowlDict.Medium.Length6 do
  def get(string_id) do
    %{"egirsv" => ["givers"], "addrsy" => ["dryads"], "dekkuy" => ["yukked"],
      "aalsss" => ["salsas"], "ejortt" => ["jotter"], "aciknt" => ["catkin"],
      "aacefr" => ["carafe"], "ablsty" => ["stably"], "einpru" => ["unripe"],
      "aceprs" => ["crapes"], "agorsy" => ["argosy"], "aeelrs" => ["sealer"],
      "gginos" => ["goings"], "mmoopp" => ["pompom"], "fllouy" => ["foully"],
      "eefils" => ["selfie"], "begins" => ["binges"],
      "hilosw" => ["lowish", "owlish"], "gnoppu" => ["popgun"],
      "adinor" => ["inroad"], "adelop" => ["pedalo"], "gilnos" => ["logins"],
      "abbess" => ["abbess"], "ainnos" => ["anions"], "adefff" => ["faffed"],
      "acelpt" => ["caplet"], "adkosv" => ["vodkas"], "aglnry" => ["gnarly"],
      "aallny" => ["anally"], "cchnos" => ["conchs"], "ddegit" => ["geddit"],
      "eehppr" => ["hepper"], "aefmrr" => ["framer"], "ddelno" => ["noddle"],
      "cejoos" => ["jocose"], "einsvx" => ["vixens"], "ddeoss" => ["dossed"],
      "iippst" => ["pipits"], "aersty" => ["stayer"], "achilp" => ["caliph"],
      "abbdeu" => ["bedaub"], "deimpw" => ["wimped"], "acdeff" => ["decaff"],
      "deffir" => ["riffed"], "clpstu" => ["sculpt"], "acdily" => ["acidly"],
      "clnruu" => ["uncurl"], "bdegnu" => ["bunged"], "adfmno" => ["fandom"],
      "ailmnr" => ["marlin"], "borstu" => ["turbos"], "beimnn" => ["binmen"],
      "cfrsuy" => ["scurfy"], "aeelst" => ["teasel", "elates"],
      "eggiln" => ["niggle"], "bbbelo" => ["bobble"], "ddeios" => ["diodes"],
      "beorrs" => ["borers"], "aeekrt" => ["retake"], "aeknsv" => ["knaves"],
      "aabcls" => ["cabals"], "ddeffo" => ["doffed"], "adelrr" => ["larder"],
      "eenotw" => ["townee"], "acgims" => ["magics"], "efortw" => ["twofer"],
      "aeprtx" => ["pretax"], "desssu" => ["sussed"],
      "ghlosu" => ["loughs", "slough"], "ceosvy" => ["coveys"],
      "ceorst" => ["rectos"], "aggins" => ["niggas"], "ffhios" => ["offish"],
      "aegirt" => ["gaiter", "triage"], "aaggrt" => ["ragtag"],
      "aehjjs" => ["hajjes"], "josstu" => ["jousts"], "eehmns" => ["enmesh"],
      "eefhor" => ["hereof"], "abeiit" => ["tibiae"], "bddeir" => ["bidder"],
      "aegort" => ["toerag"], "aefrry" => ["rarefy"], "accdii" => ["acidic"],
      "beegrs" => ["grebes"], "diopss" => ["dipsos"], "cehnot" => ["techno"],
      "hooptt" => ["hotpot"], "aabmnt" => ["batman", "bantam"],
      "cekorr" => ["corker"], "dddeil" => ["diddle", "lidded"],
      "ddilos" => ["dildos"], "eioprr" => ["ropier"], "dloruy" => ["dourly"],
      "aehkrw" => ["hawker"], "aelmny" => ["meanly"], "acimst" => ["mastic"],
      "belsuy" => ["bluesy"], "bdeffi" => ["biffed"], "adgnos" => ["gonads"],
      "erstvy" => ["vestry"], "akoosz" => ["kazoos"], "abeils" => ["abseil"],
      "defknu" => ["funked"], "eehinr" => ["inhere"], "eesttx" => ["sextet"],
      "eeglmn" => ["legmen"], "aaprst" => ["satrap"], "acituy" => ["acuity"],
      "ccostu" => ["stucco"], "deetwy" => ["tweedy"], "eegmno" => ["genome"],
      "cegnor" => ["conger"], "aaelmt" => ["tamale"], "celoot" => ["ocelot"],
      "ceirrs" => ["criers"], "ceelrs" => ["creels"], "cddelo" => ["coddle"],
      "dfjors" => ["fjords"], "bbemnu" => ["benumb"], "bceiox" => ["icebox"],
      "elostw" => ["owlets"], "deefht" => ["hefted"],
      "aelrsv" => ["velars", "salver", "slaver"], "aeirrt" => ["artier"],
      "bekrsu" => ["busker"], "ceikpr" => ["picker"], "deoprs" => ["spored"],
      "eeestt" => ["settee"], "cdefnu" => ["fecund"], "eehrsw" => ["hewers"],
      "acoptw" => ["cowpat"], "eilpss" => ["spiels"], "ehlmop" => ["phloem"],
      "egilmt" => ["gimlet"], "beefly" => ["feebly"], "eepstt" => ["septet"],
      "emostt" => ["motets"], "adelmm" => ["lammed"], "degnru" => ["gerund"],
      "aegist" => ["ageist"], "adesst" => ["steads"], "aknswy" => ["swanky"],
      "bdmosu" => ["dumbos"], "achktw" => ["thwack"], "ceknor" => ["conker"],
      "bdegos" => ["bodges"], "cegkos" => ["geckos"], "eehkls" => ["shekel"],
      "alrstu" => ["ultras"], "ceelor" => ["creole"], "acelms" => ["mescal"],
      "effilp" => ["piffle"], "oprsty" => ["sporty"], "cdeoyz" => ["zydeco"],
      "cdersy" => ["descry"], "hilmsu" => ["mulish"], "beilnu" => ["nubile"],
      "aegnsv" => ["vegans"], "ceinqu" => ["quince"], "goprss" => ["sprogs"],
      "bbdefo" => ["fobbed"], "aahipr" => ["pariah"], "inoptt" => ["tinpot"],
      "deeils" => ["elides"], "agortu" => ["ragout"], "aafghn" => ["afghan"],
      "acemnp" => ["encamp"], "aestyy" => ["yeasty"], "abcory" => ["carboy"],
      "eelnsw" => ["newels"], "aeemrr" => ["reamer"], "histty" => ["shitty"],
      "deorrv" => ["drover"], "inppsu" => ["pinups"], "eilpsx" => ["pixels"],
      "adelrs" => ["alders"], "effiir" => ["iffier"], "aaderw" => ["adware"],
      "aenrst" => ["astern"], "clmops" => ["clomps"], "chmpsu" => ["chumps"],
      "bbejor" => ["jobber"], "bbdinu" => ["dubbin"], "elnsxy" => ["lynxes"],
      "ddeosw" => ["dowsed"], "eiorsv" => ["vireos"], "ehmrsu" => ["musher"],
      "aeiopt" => ["opiate"], "ilsstt" => ["stilts"], "abekrr" => ["barker"],
      "knoorr" => ["kronor"], "ddenno" => ["donned"], "ailpst" => ["plaits"],
      "aadmru" => ["maraud"], "eghinw" => ["whinge"], "agruuy" => ["augury"],
      "anstuv" => ["vaunts"], "egiill" => ["gillie"], "abeeln" => ["baleen"],
      "denotw" => ["wonted"], "aeennt" => ["neaten"], "bekoot" => ["betook"],
      "ennptu" => ["punnet"], "aiprsw" => ["ripsaw"], "aeflru" => ["earful"],
      "eilmpt" => ["limpet"], "degglo" => ["dogleg"], "ailnvy" => ["vainly"],
      "aagsuv" => ["guavas"], "adeprs" => ["padres"], "abmmos" => ["mambos"],
      "aeghis" => ["geisha"], "deelnr" => ["lender"], "cimoty" => ["comity"],
      "aeglsy" => ["sagely"], "dddelo" => ["doddle"], "ackosw" => ["wackos"],
      "aehrsw" => ["hawser"], "aissst" => ["stasis"], "essssu" => ["susses"],
      "acmors" => ["caroms", "macros"], "delosw" => ["dowels"],
      "aglors" => ["largos"], "eiorst" => ["sortie"],
      "opsstu" => ["stoups", "tossup"], "enrttu" => ["nutter"],
      "efirst" => ["refits", "sifter"], "cehktv" => ["kvetch"],
      "bdiilo" => ["libido"], "addels" => ["addles"], "bdikno" => ["bodkin"],
      "eefluy" => ["eyeful"], "agghis" => ["haggis"], "ccehlo" => ["cloche"],
      "acdels" => ["decals"], "binoot" => ["bonito"], "aeflst" => ["festal"],
      "ilorsy" => ["rosily"], "knpsuy" => ["spunky"], "eprrsu" => ["purser"],
      "empssu" => ["spumes"], "aaciss" => ["cassia"], "aimpss" => ["passim"],
      "abdefr" => ["barfed"], "dehjos" => ["joshed"], "cklnos" => ["clonks"],
      "abeekt" => ["betake"], "acghot" => ["gotcha"], "ggilwy" => ["wiggly"],
      "aahlps" => ["alphas"], "eginrz" => ["zinger"], "ciostu" => ["coitus"],
      "cgimno" => ["gnomic"], "acimps" => ["scampi"], "aahjrs" => ["rajahs"],
      "cehisv" => ["chives"], "aaegtu" => ["gateau"], "aalmnw" => ["lawman"],
      "ahrssu" => ["hussar"], "abilvy" => ["viably"], "afimry" => ["ramify"],
      "ipptuy" => ["uppity"], "ioqstu" => ["quoits"], "aaccnn" => ["cancan"],
      "efinry" => ["finery"], "eginrr" => ["ringer"], "abbegl" => ["gabble"],
      "begoru" => ["brogue"], "lmmoux" => ["lummox"], "deelmw" => ["mewled"],
      "biiktz" => ["kibitz"], "ffinsy" => ["sniffy"], "akmpru" => ["markup"],
      "bcistu" => ["cubist", "cubits"], "aamnoz" => ["amazon"],
      "bejjuu" => ["jujube"], "degosw" => ["wodges"], "ehorsy" => ["horsey"],
      "allnos" => ["llanos"], "allost" => ["atolls"], "bbelno" => ["nobble"],
      "agilnw" => ["waling"], "aabess" => ["abases"], "aaartv" => ["avatar"],
      "ceopry" => ["recopy"], "abdegl" => ["gabled"], "ghinoo" => ["oohing"],
      "hlpssy" => ["sylphs"], "eillmt" => ["millet"], "ahilyz" => ["hazily"],
      "iprsty" => ["stripy"], "beelsv" => ["bevels"], "elnors" => ["loners"],
      "cdeikr" => ["dicker", "ricked"], "arssty" => ["satyrs"],
      "aikmsu" => ["umiaks"], "ceeems" => ["emcees"], "dhimos" => ["modish"],
      "abeqsu" => ["basque"], "beimsu" => ["imbues"], "cerstu" => ["cruets"],
      "hhoosw" => ["whoosh"], "floruy" => ["floury"],
      "aeerst" => ["teaser", "eaters"], "eiprss" => ["pisser"],
      "aimstu" => ["autism"], "eelmsy" => ["seemly"], "giijnv" => ["jiving"],
      "ehkoty" => ["hotkey"], "aceopt" => ["toecap"], "noopsy" => ["snoopy"],
      "acdegr" => ["cadger"], "abddei" => ["baddie"], "bdorwy" => ["byword"],
      "emnosy" => ["moneys"], "abfnoy" => ["fanboy"], "airsst" => ["sitars"],
      "cehlor" => ["choler"], "aepptu" => ["pupate"], "bdegin" => ["binged"],
      "aanstv" => ["savant"], "aaadmr" => ["armada"], "hhrstu" => ["thrush"],
      "abiorr" => ["barrio"], "aciils" => ["silica"], "afimss" => ["massif"],
      "egoost" => ["stooge"], "dhoooo" => ["hoodoo"], "bcdeek" => ["bedeck"],
      "cpstuu" => ["cutups"], "abbgmu" => ["bumbag"], "aalpry" => ["parlay"],
      "aaaclp" => ["alpaca"], "abimnn" => ["binman"], "eimnzz" => ["mizzen"],
      "degost" => ["stodge"], "afilps" => ["pilafs"], "ehinrw" => ["whiner"],
      "eijnty" => ["jitney"], "ceikrt" => ["ticker"], "afhims" => ["famish"],
      "eggrru" => ["rugger"], "abdenp" => ["bedpan"], "abfglu" => ["bagful"],
      "deinru" => ["inured"], "ehirsv" => ["shrive"], "ehmnsy" => ["hymens"],
      "aderzz" => ["razzed"], "fiillp" => ["fillip"], "abdeir" => ["airbed"],
      "bdeopp" => ["bopped"], "agrrtu" => ["rugrat"], "dddily" => ["diddly"],
      "bilrty" => ["trilby"], "demops" => ["mopeds"], "deginz" => ["zinged"],
      "egiost" => ["stogie", "egoist"], "kloopu" => ["lookup"],
      "aceirs" => ["caries"], "cginos" => ["cosign"], "cdefku" => ["fucked"],
      "coopwx" => ["cowpox"], "aceenr" => ["careen"], "adefgg" => ["fagged"],
      "deorrt" => ["retrod"], "alpsst" => ["splats"], "deiktt" => ["kitted"],
      "deegls" => ["sledge"], "acppsu" => ["cuppas"], "afiill" => ["filial"],
      "aderrw" => ["warder"], "allmos" => ["slalom"], "efgors" => ["gofers"],
      "adirst" => ["triads"], "aahllw" => ["wallah"], "aelppt" => ["applet"],
      "addeln" => ["dandle"], "ahopst" => ["potash"], "aappww" => ["pawpaw"],
      "eeipss" => ["espies"], "bcnouy" => ["bouncy"], "abjjoo" => ["jojoba"],
      "aortvy" => ["votary"], "gginor" => ["gringo"], "filrty" => ["flirty"],
      "eegrss" => ["egress"], "aejprs" => ["jasper"], "ggiloo" => ["gigolo"],
      "abikmo" => ["akimbo"], "berstu" => ["tubers", "buster"],
      "aeglry" => ["argyle"], "aepprz" => ["zapper"], "bgmosu" => ["gumbos"],
      "acinrs" => ["cairns"], "eegssu" => ["segues"], "aeelsz" => ["sleaze"],
      "bdensu" => ["sunbed"], "aceivv" => ["vivace"], "eorrst" => ["sorter"],
      "aacmsw" => ["macaws"], "eglntu" => ["gluten"], "bbgino" => ["gibbon"],
      "bllory" => ["brolly"], "bchiop" => ["phobic"], "bdennu" => ["unbend"],
      "enorrs" => ["snorer"], "hinnsy" => ["shinny"], "gortty" => ["grotty"],
      "fimstu" => ["muftis"], "abemnt" => ["batmen"], "aelrtv" => ["varlet"],
      "cimnor" => ["micron"], "aaglnr" => ["raglan"], "aippst" => ["papist"],
      "flooyz" => ["floozy"], "deerrw" => ["redrew"], "aehkrs" => ["shaker"],
      "aegrss" => ["sarges"], "abckpu" => ["backup"], "bdeeit" => ["betide"],
      "ehirsw" => ["wisher"], "cekors" => ["ockers"], "ilopty" => ["polity"],
      "ijosst" => ["joists"], "abeort" => ["boater"], "ehitwy" => ["whitey"],
      "beilny" => ["byline"], "acfkls" => ["flacks"], "aoppps" => ["poppas"],
      "ceimnr" => ["mincer"], "eegils" => ["lieges"], "acdelv" => ["calved"],
      "alttuy" => ["tautly"], "beikoo" => ["bookie"], "acdegs" => ["cadges"],
      "abdilr" => ["ribald"], "cilnou" => ["uncoil"], "eoprsy" => ["osprey"],
      "aceipr" => ["pacier"], "aafstw" => ["fatwas"], "dgmsuy" => ["smudgy"],
      "ccdeis" => ["sicced"], "delpru" => ["purled"], "gilnsu" => ["sluing"],
      "deemns" => ["emends"], "cdekop" => ["pocked"], "accems" => ["meccas"],
      "eiklnv" => ["kelvin"], "bdekno" => ["bonked"], "afllow" => ["fallow"],
      "eillnt" => ["lintel"], "aknssw" => ["swanks"], "ehmoss" => ["moshes"],
      "eeimnr" => ["ermine"], "aiklno" => ["kaolin"], "ceeinv" => ["evince"],
      "ddeeil" => ["elided"], "enpruy" => ["penury"], "aabbbo" => ["baobab"],
      "iprssy" => ["prissy"], "acchny" => ["chancy"], "abgint" => ["bating"],
      "ooprrt" => ["torpor"], "degppy" => ["gypped"], "dooswy" => ["woodsy"],
      "bggiiw" => ["bigwig"], "deenrs" => ["resend"], "ceopss" => ["copses"],
      "adimot" => ["diatom"], "demorr" => ["dormer"], "ainsty" => ["satiny"],
      "cghilt" => ["glitch"], "iimmns" => ["minims"], "bghrsu" => ["burghs"],
      "achhoo" => ["ahchoo"], "aacdnr" => ["canard"], "dennru" => ["dunner"],
      "cinnou" => ["nuncio"], "acmpss" => ["scamps"], "abcrst" => ["bracts"],
      "himsty" => ["smithy"], "adefrt" => ["dafter", "farted"],
      "aefkry" => ["freaky"], "deensu" => ["endues"], "abehrs" => ["rehabs"],
      "beimrt" => ["timbre"], "defgir" => ["fridge"], "lsttuy" => ["slutty"],
      "aadpyy" => ["payday"], "adefry" => ["defray"], "abmrsu" => ["rumbas"],
      "aerssv" => ["savers"], "forwyz" => ["frowzy"], "eorssw" => ["sowers"],
      "aahssy" => ["sashay"], "ceinpt" => ["pectin"], "mooprs" => ["promos"],
      "eflouw" => ["woeful"], "eloprs" => ["proles"], "egglmu" => ["muggle"],
      "accirt" => ["arctic"], "abqssu" => ["squabs"], "epsstu" => ["setups"],
      "ahknss" => ["shanks"], "bimnsu" => ["nimbus"], "cikoss" => ["sickos"],
      "aghoqu" => ["quahog"], "eehirr" => ["rehire"], "aiprst" => ["tapirs"],
      "aossvy" => ["savoys"], "errsuu" => ["usurer"], "ceiikr" => ["ickier"],
      "eeelss" => ["lessee"], "lnopsy" => ["pylons"], "aghlos" => ["galosh"],
      "aegrsz" => ["gazers"], "dimnsu" => ["nudism"], "aajnps" => ["japans"],
      "ehirtz" => ["zither"], "ahllmu" => ["mullah"], "cemors" => ["comers"],
      "aeglmn" => ["legman"], "dglsuy" => ["sludgy"], "imsssu" => ["missus"],
      "aeilmr" => ["mailer"], "chippy" => ["chippy"], "eimors" => ["moires"],
      "aanrtt" => ["rattan"], "gnoruv" => ["guvnor"], "aaipzz" => ["piazza"],
      "deemot" => ["emoted"], "anorss" => ["sonars"], "ahmowy" => ["haymow"],
      "deeknn" => ["kenned"], "adeilm" => ["medial"], "aadhil" => ["dahlia"],
      "lmooru" => ["ormolu"], "fiossy" => ["ossify"], "hlnouy" => ["unholy"],
      "amorsy" => ["morays"], "affqsu" => ["quaffs"], "cehnuu" => ["eunuch"],
      "ehsstu" => ["tushes"], "hlmpuy" => ["phylum"],
      "eloort" => ["retool", "looter"], "aemmnr" => ["merman"],
      "eiilmu" => ["milieu"], "eehwyz" => ["wheezy"], "eilsxy" => ["sexily"],
      "eloott" => ["tootle"], "adekrs" => ["drakes"], "deffru" => ["duffer"],
      "bkmnuu" => ["bunkum"], "aelmpu" => ["ampule"], "eeirrw" => ["rewire"],
      "hmnopy" => ["nympho"], "eghinx" => ["hexing"], "acepsy" => ["spacey"],
      "deeirt" => ["tiered", "dieter"], "aellpt" => ["pallet"],
      "aacrtv" => ["cravat"], "cdeeem" => ["emceed"], "aeeirs" => ["aeries"],
      "chlrsu" => ["churls"], "aafinr" => ["farina"], "chimty" => ["mythic"],
      "aaipry" => ["apiary"], "aaqrsu" => ["quasar"], "ghistw" => ["wights"],
      "eorrsw" => ["rowers"], "moorrw" => ["morrow"], "abcers" => ["cabers"],
      "eimsty" => ["stymie"], "aghirt" => ["aright"], "efoort" => ["footer"],
      "ceerss" => ["screes"], "acimns" => ["manics"], "ahpssw" => ["pshaws"],
      "eirsst" => ["resits"], "aelpry" => ["parley", "pearly"],
      "adeejy" => ["deejay"], "aeehrt" => ["reheat"], "aabnny" => ["banyan"],
      "aaacci" => ["acacia"], "egippr" => ["grippe"], "aehprs" => ["seraph"],
      "eipsss" => ["sepsis", "pisses"], "filoos" => ["folios"],
      "gmpsuy" => ["gypsum"], "bbeiim" => ["imbibe"], "ffilps" => ["spliff"],
      "adhrsy" => ["hydras"], "hlorsw" => ["whorls"], "cefors" => ["fresco"],
      "adempv" => ["vamped"], "abcemw" => ["webcam"], "elmrsu" => ["lemurs"],
      "cdfioy" => ["codify"], "affloy" => ["layoff"], "innpsu" => ["unpins"],
      "ilppsy" => ["slippy"], "eimoty" => ["moiety"], "abilmu" => ["labium"],
      "akqrsu" => ["quarks"], "abllsy" => ["ballsy"], "aabdes" => ["abased"],
      "bgilnu" => ["lubing"], "ccinos" => ["conics"], "acersv" => ["cavers"],
      "cklnuy" => ["clunky"], "ioprry" => ["priory"], "aimopy" => ["myopia"],
      "ehlpsw" => ["whelps"], "oprsst" => ["strops"], "ehisst" => ["heists"],
      "elorsv" => ["solver"], "aginry" => ["grainy"], "aacdhs" => ["dachas"],
      "aegprs" => ["pagers"], "adefly" => ["flayed"], "eijnno" => ["enjoin"],
      "eehmnp" => ["hempen"], "ceipst" => ["septic"], "aegisv" => ["visage"],
      "deftuz" => ["futzed"], "aeknrw" => ["wanker"], "bdeeep" => ["beeped"],
      "deessw" => ["swedes"], "ammrsy" => ["smarmy"], "abflry" => ["barfly"],
      "bbknoy" => ["knobby"], "ceehky" => ["cheeky"],
      "adinsv" => ["divans", "viands"], "aeflls" => ["fellas"],
      "eimprs" => ["simper"], "cknoru" => ["uncork"], "bemoss" => ["besoms"],
      "cdessu" => ["cussed"], "eeflnn" => ["fennel"], "adegsw" => ["wadges"],
      "aiintt" => ["titian"], "bdoory" => ["broody"], "aginrs" => ["arsing"],
      "ackpsy" => ["skycap"], "agglsu" => ["gulags"], "cklopu" => ["lockup"],
      "afikrs" => ["fakirs"], "enosxy" => ["onyxes"], "giinsw" => ["wising"],
      "aginrt" => ["gratin", "taring"], "chikst" => ["kitsch", "shtick"],
      "aeinns" => ["sienna"], "cdeloy" => ["cloyed"], "acehis" => ["chaise"],
      "chimrs" => ["smirch"], "deflno" => ["enfold"], "ceorsw" => ["escrow"],
      "alsuuv" => ["uvulas"], "cccios" => ["coccis"], "ffgloo" => ["logoff"],
      "agimns" => ["gamins"], "abhotx" => ["hatbox"], "emoorr" => ["roomer"],
      "ahortx" => ["thorax"], "msttuy" => ["smutty"], "aegggl" => ["gaggle"],
      "ddirsu" => ["druids"], "cceers" => ["recces"], "aerstw" => ["waster"],
      "cimprs" => ["crimps", "scrimp"], "addeos" => ["dadoes"],
      "acinot" => ["cation"], "destuv" => ["duvets"], "ehpryz" => ["zephyr"],
      "aepsst" => ["spates"], "cenosz" => ["cozens"], "aamntx" => ["taxman"],
      "aelrsy" => ["slayer"], "aemnss" => ["manses"], "aeehrr" => ["hearer"],
      "eelsty" => ["sleety", "steely"], "epstuz" => ["putzes"],
      "diilps" => ["lipids"], "adhijs" => ["jihads"], "biopsy" => ["biopsy"],
      "himswy" => ["whimsy"], "erstuu" => ["suture"], "ahllrt" => ["thrall"],
      "eiotvv" => ["votive"], "iilttw" => ["twilit"], "effopu" => ["pouffe"],
      "blopuw" => ["blowup"], "eeillw" => ["wellie"], "cdeglu" => ["cudgel"],
      "crsuvy" => ["scurvy"], "ehirtt" => ["hitter"], "aeginr" => ["gainer"],
      "ahiltw" => ["withal"], "deeerw" => ["weeder"], "ffipsy" => ["spiffy"],
      "allmow" => ["mallow"], "ddegor" => ["dodger"], "aehlsw" => ["wheals"],
      "eioppt" => ["potpie"], "eilmsy" => ["limeys", "smiley"],
      "effgin" => ["effing"], "chikos" => ["hoicks"], "clrtuy" => ["curtly"],
      "ceefnr" => ["fencer"], "adeior" => ["roadie"], "ainstt" => ["titans"],
      "abeily" => ["bailey"], "cottuu" => ["cutout"], "aeprrw" => ["prewar"],
      "aiimns" => ["simian"], "ffikss" => ["skiffs"], "eiorss" => ["osiers"],
      "ceipry" => ["pricey"], "emossy" => ["moseys"], "ginoop" => ["pooing"],
      "dnossy" => ["synods"], "eioost" => ["otiose"], "abikku" => ["kabuki"],
      "bceels" => ["celebs"], "eilmrs" => ["milers"], "aoorry" => ["arroyo"],
      "eopprt" => ["topper"], "adekpy" => ["keypad"], "csuyzz" => ["scuzzy"],
      "deempr" => ["permed"], "alrtty" => ["tartly"], "fmprsu" => ["frumps"],
      "deffim" => ["miffed"], "enorst" => ["toners", "stoner", "tensor"],
      "abemrs" => ["breams"], "achstw" => ["swatch"], "aegmns" => ["gasmen"],
      "eilmsu" => ["muesli"], "acosst" => ["ascots"], "einpsu" => ["supine"],
      "efhoor" => ["hoofer"], "addden" => ["addend"], "celmuy" => ["lyceum"],
      "cdeosu" => ["escudo"], "beehop" => ["phoebe"],
      "acerst" => ["carets", "recast"], "agnrty" => ["gantry"],
      "ainssw" => ["swains"], "ammstu" => ["summat"], "hlssuy" => ["slushy"],
      "eeprsu" => ["rupees"], "aeelrv" => ["leaver"], "enorry" => ["ornery"],
      "cenops" => ["ponces"], "eirtvy" => ["verity"], "bbdeij" => ["jibbed"],
      "aemqsu" => ["masque"], "ablpyy" => ["byplay"], "ahmotz" => ["matzoh"],
      "deknoz" => ["zonked"], "eeeepw" => ["peewee"], "ceikry" => ["crikey"],
      "degnop" => ["ponged"], "filnty" => ["flinty"], "fiilln" => ["infill"],
      "aehnrt" => ["anther"], "giknnu" => ["nuking"], "aamnrt" => ["mantra"],
      "bciiop" => ["biopic"], "eikmst" => ["kismet"], "abbeks" => ["kebabs"],
      "cmrssu" => ["scrums"], "aadmrs" => ["madras"], "aeilnv" => ["venial"],
      "aejmst" => ["jetsam"], "acprss" => ["scarps"], "degims" => ["midges"],
      "egilru" => ["gluier"], "eelprt" => ["petrel"], "aemorr" => ["roamer"],
      "cestuy" => ["cuteys", "cutesy"], "epppry" => ["preppy"],
      "aiopst" => ["patois"], "abegnr" => ["banger"], "aaclnu" => ["lacuna"],
      "ahillp" => ["phalli"], "admnos" => ["damson"], "achotw" => ["wotcha"],
      "aeepst" => ["peseta"], "lorsuy" => ["sourly"], "einsux" => ["unisex"],
      "agjlmo" => ["logjam"], "aadins" => ["naiads"], "celrru" => ["curler"],
      "eeekrs" => ["seeker"], "abcemr" => ["camber"], "eglnnu" => ["gunnel"],
      "ghossu" => ["soughs"], "ellmtu" => ["mullet"], "gggily" => ["giggly"],
      "aghinw" => ["hawing"], "eginow" => ["wigeon"], "ammort" => ["marmot"],
      "aeegmn" => ["menage"], "eggnru" => ["grunge"], "eimnsx" => ["minxes"],
      "aerrsv" => ["ravers"], "abbnos" => ["nabobs"], "aairwy" => ["airway"],
      "adistv" => ["davits"], "aloppt" => ["laptop"], "acstty" => ["scatty"],
      "aeglot" => ["legato"], "eorssu" => ["serous"], "aaccdi" => ["cicada"],
      "ceikkr" => ["kicker"], "acelnu" => ["unlace"], "ekoort" => ["retook"],
      "cenoss" => ["scones"], "ainrtu" => ["nutria"], "aeggnr" => ["grange"],
      "benrtu" => ["brunet"], "deettx" => ["texted"],
      "egorrs" => ["reorgs", "rogers"], "aadhmr" => ["dharma"],
      "iloprx" => ["prolix"], "ddeemo" => ["demoed"], "imprsu" => ["purism"],
      "bbdeil" => ["dibble"], "egmnor" => ["monger"], "acehrs" => ["chaser"],
      "ehmors" => ["homers"], "abehrt" => ["bather"], "ellptu" => ["pullet"],
      "llnoru" => ["unroll"], "eijknr" => ["jerkin"], "adiktt" => ["diktat"],
      "deosss" => ["dosses"], "eorssv" => ["versos", "servos"],
      "hiqssu" => ["squish"], "borttu" => ["turbot"], "bchity" => ["bitchy"],
      "adeknw" => ["wanked"], "ceimsu" => ["miscue"], "eoqstu" => ["toques"],
      "eilnpu" => ["lineup"], "cdensy" => ["synced"], "cffotu" => ["cutoff"],
      "hilnpt" => ["plinth"], "ceekpr" => ["pecker"], "aefgln" => ["flange"],
      "cdehru" => ["ruched"], "agrsuu" => ["augurs"], "aeensu" => ["unease"],
      "ademop" => ["pomade"], "enosuv" => ["venous"], "hoossw" => ["swoosh"],
      "ciprss" => ["scrips"], "eipptx" => ["tippex"], "aeiprr" => ["rapier"],
      "giknot" => ["toking"], "ceistv" => ["civets"], "aenrrt" => ["ranter"],
      "acekrw" => ["wacker"], "aeklnr" => ["lanker"], "ahmmwy" => ["whammy"],
      "abgnor" => ["brogan"], "ilmrty" => ["trimly"], "eertvx" => ["vertex"],
      "amostz" => ["matzos"], "ddeflu" => ["fuddle"], "acddeu" => ["adduce"],
      "cennoo" => ["neocon"], "cdehou" => ["douche"], "hmotuy" => ["mouthy"],
      "ademot" => ["moated"], "cdnoos" => ["condos"], "acllot" => ["lolcat"],
      "adelpw" => ["dewlap"], "aeeimn" => ["meanie"], "ailmss" => ["missal"],
      "adilrs" => ["lairds"], "abddey" => ["daybed"], "hillss" => ["shills"],
      "eipprr" => ["ripper"], "adeort" => ["orated"], "aeghiw" => ["aweigh"],
      "cjnosu" => ["juncos"], "anorsw" => ["rowans"], "acdepr" => ["redcap"],
      "abestu" => ["beauts"], "abhiss" => ["sahibs"], "abdelo" => ["doable"],
      "ceeips" => ["specie"], "cdeeis" => ["deices"], "iknops" => ["pinkos"],
      "achopr" => ["carhop"], "ablmru" => ["lumbar"], "filnor" => ["florin"],
      "prsuyy" => ["syrupy"], "ddegin" => ["dinged"], "egilpt" => ["piglet"],
      "cehort" => ["hector"], "eilrst" => ["tilers"], "aerttt" => ["tatter"],
      "alruuv" => ["uvular"], "aelnpt" => ["platen"], "eeeppr" => ["peeper"],
      "adeisu" => ["adieus"], "klnpsu" => ["plunks"], "ceostt" => ["octets"],
      "chhnoo" => ["honcho"], "einosw" => ["nowise"], "eorsst" => ["tosser"],
      "begoor" => ["booger", "goober"], "aflmnu" => ["manful"],
      "cinorz" => ["zircon"], "ablswy" => ["bylaws"], "aghstu" => ["aughts"],
      "dhilos" => ["oldish"], "doopry" => ["droopy"], "aelnsu" => ["unseal"],
      "bdeksu" => ["busked"], "ehoopy" => ["phooey"],
      "acehms" => ["sachem", "schema"], "eennrt" => ["tenner", "rennet"],
      "aallrv" => ["larval"], "ceimmo" => ["commie"], "aegiln" => ["linage"],
      "bilmos" => ["limbos"], "eelpst" => ["pestle"], "ceeirs" => ["cerise"],
      "eillvy" => ["evilly", "vilely"], "ehoorv" => ["hoover"],
      "ehimst" => ["theism"], "aalnot" => ["atonal"], "ailnpt" => ["plaint"],
      "ehlost" => ["helots"], "beeopp" => ["peepbo"], "diimtw" => ["dimwit"],
      "acdlty" => ["dactyl"], "delnou" => ["nodule"], "inoprs" => ["prions"],
      "ceirvx" => ["cervix"], "eellrt" => ["retell"], "aeintu" => ["auntie"],
      "bcdiou" => ["cuboid"], "deimnr" => ["minder"], "eeoruv" => ["oeuvre"],
      "eimnor" => ["merino"], "ehmruy" => ["rheumy"], "acehkl" => ["hackle"],
      "aabgrt" => ["ratbag"], "deegnn" => ["genned"], "eopppt" => ["poppet"],
      "nooprt" => ["pronto"], "demmos" => ["modems"], "orsstu" => ["rousts"],
      "cdeimo" => ["medico"], "aefitx" => ["fixate"], "bboosy" => ["yobbos"],
      "ggnoor" => ["gorgon"], "aeiils" => ["liaise"],
      "cdeors" => ["credos", "decors"], "defgos" => ["defogs"],
      "beegnu" => ["bungee"], "eeinrw" => ["wiener"], "cirrsu" => ["cirrus"],
      "celtuy" => ["cutely"], "choort" => ["cohort"], "hlpsuy" => ["plushy"],
      "bemoor" => ["boomer"], "iopptt" => ["tiptop"], "glmnoo" => ["mongol"],
      "acehpy" => ["peachy"], "denosy" => ["doyens"], "ddeenw" => ["wended"],
      "deegos" => ["geodes"], "aaeswy" => ["seaway"], "ceinos" => ["cosine"],
      "degily" => ["edgily"], "empstu" => ["septum"], "iopsst" => ["posits"],
      "cgiors" => ["corgis"], "ffiqsu" => ["quiffs"], "cdeims" => ["medics"],
      "adenrs" => ["sander"], "cehoss" => ["coshes"], "aeffgs" => ["gaffes"],
      "deiins" => ["indies"], "cenors" => ["recons", "crones"],
      "cekrtu" => ["tucker"], "abosss" => ["bassos"],
      "acceip" => ["icecap", "ipecac"], "adlmos" => ["modals"],
      "ailrwy" => ["warily"], "aeorst" => ["orates"], "ehmrst" => ["therms"],
      "deiors" => ["dories"], "ciknss" => ["snicks"], "aehils" => ["sheila"],
      "ceehlr" => ["lecher"], "eiilrx" => ["elixir"], "inqstu" => ["quints"],
      "cchkos" => ["chocks"], "bbegot" => ["gobbet"], "ablnoz" => ["blazon"],
      "nostty" => ["snotty"], "agnoqu" => ["quango"], "bdeikl" => ["bilked"],
      "acortx" => ["oxcart"], "einnot" => ["intone"], "alossv" => ["salvos"],
      "aadgio" => ["adagio"], "agnprs" => ["prangs"],
      "einsst" => ["insets", "steins"], "eikssv" => ["skives"],
      "iklnpu" => ["linkup"], "ginorv" => ["roving"], "aablms" => ["balsam"],
      "aemrrs" => ["rearms"], "cceklo" => ["cockle"], "deeirw" => ["dewier"],
      "deempt" => ["temped"], "einotw" => ["townie"], "acenrv" => ["craven"],
      "deinsu" => ["undies"], "aacmrt" => ["tarmac"], "cdimtu" => ["dictum"],
      "acehir" => ["achier"], "alprsu" => ["pulsar"], "noosst" => ["snoots"],
      "aalrst" => ["astral"], "aghnos" => ["hogans"], "eelstv" => ["svelte"],
      "deimrs" => ["dermis"], "ceiorw" => ["cowrie"], "eeersv" => ["reeves"],
      "eeopst" => ["topees"], "adeefn" => ["deafen"], "acmnor" => ["macron"],
      "ailmno" => ["oilman"], "deilst" => ["tildes"], "eeilvw" => ["weevil"],
      "aikort" => ["troika"], "beggii" => ["biggie"], "abdlly" => ["baldly"],
      "aeilns" => ["saline"], "delmno" => ["dolmen"], "agiorv" => ["virago"],
      "aegils" => ["silage"], "clmsuy" => ["muscly"], "deippp" => ["pipped"],
      "einpst" => ["spinet"], "ceikmy" => ["mickey"], "eoruvy" => ["voyeur"],
      "eeggiv" => ["veggie"], "eghiin" => ["hieing"], "eggjlo" => ["joggle"],
      "adiimr" => ["midair"], "mprsuu" => ["rumpus"], "bemnot" => ["entomb"],
      "cegnty" => ["cygnet"], "aerszz" => ["razzes"], "afhloo" => ["loofah"],
      "eipprt" => ["tipper"], "eiirvz" => ["vizier"], "eghinr" => ["nigher"],
      "deorsw" => ["dowser"], "ceggpu" => ["eggcup"], "ceiins" => ["incise"],
      "definr" => ["finder"], "ceehsw" => ["eschew"], "afhios" => ["oafish"],
      "beklos" => ["blokes"], "aasssy" => ["assays"], "chsssu" => ["schuss"],
      "botuuy" => ["buyout"], "adimmt" => ["dammit"], "adrssw" => ["swards"],
      "cmmsuy" => ["scummy"], "eegrst" => ["egrets"], "abentt" => ["batten"],
      "bcenos" => ["bonces"], "aenrtt" => ["natter"], "ddejru" => ["judder"],
      "ceioot" => ["cootie"], "birstu" => ["bruits"], "deestw" => ["tweeds"],
      "hiimst" => ["mishit"], "afglno" => ["flagon"], "horsty" => ["shorty"],
      "aelstt" => ["lattes"], "alosss" => ["lassos"], "ehlrru" => ["hurler"],
      "bcehln" => ["blench"], "aegimr" => ["gamier"], "ccenos" => ["sconce"],
      "cdeelw" => ["clewed"], "aalopy" => ["payola"], "ahloop" => ["hoopla"],
      "cinort" => ["citron"], "elnnru" => ["runnel"], "aefils" => ["falsie"],
      "aaalms" => ["salaam"], "cgilny" => ["clingy"], "agijnp" => ["japing"],
      "ceinpr" => ["pincer"], "ekmosy" => ["smokey"], "aaeert" => ["aerate"],
      "aelnpr" => ["planer"], "enostx" => ["sexton"], "cimost" => ["sitcom"],
      "cddeei" => ["deiced"], "delopy" => ["deploy"], "abders" => ["debars"],
      "belmsu" => ["umbels"], "ahinpt" => ["hatpin"], "beeisx" => ["ibexes"],
      "ejknru" => ["junker"], "einops" => ["opines"], "achppy" => ["chappy"],
      "gllmuy" => ["glumly"], "aegnrr" => ["garner"], "abeqru" => ["barque"],
      "ilrswy" => ["swirly"], "cefkru" => ["fucker"], "belrsy" => ["beryls"],
      "aeggww" => ["gewgaw"], "adhssu" => ["sadhus"], "ciilmu" => ["cilium"],
      "ceehls" => ["leches"], "adddeg" => ["gadded"], "gilnpu" => ["plugin"],
      "ceirsu" => ["curies"], "eefilr" => ["liefer", "refile"],
      "deeptu" => ["depute"], "aelppr" => ["rappel"], "aeepsy" => ["payees"],
      "afirry" => ["friary"], "beerrw" => ["brewer"], "ehlstu" => ["sleuth"],
      "eqstuu" => ["tuques"], "deegll" => ["gelled"], "efirsx" => ["fixers"],
      "bbelru" => ["lubber"], "aemnrt" => ["marten"], "ceiloo" => ["coolie"],
      "eiilnn" => ["inline"], "eiopst" => ["postie"], "addeil" => ["laddie"],
      "filnow" => ["inflow"], "acnops" => ["capons"], "acddeg" => ["cadged"],
      "eijnor" => ["joiner"], "eefsss" => ["fesses"], "bbimos" => ["bimbos"],
      "aforrw" => ["farrow"], "abdefl" => ["fabled"], "cdekor" => ["docker"],
      "eeppst" => ["steppe"], "egiinp" => ["pieing"], "deefss" => ["fessed"],
      "beloor" => ["bolero"], "accilt" => ["lactic"], "eorrtt" => ["rotter"],
      "eeeipw" => ["weepie"], "epruvy" => ["purvey"],
      "acerrs" => ["carers", "racers"], "afnnot" => ["nonfat"],
      "adeitv" => ["dative"], "eeeinw" => ["weenie"], "aiinnz" => ["zinnia"],
      "ehmnop" => ["phenom"], "ekorst" => ["stoker"], "cdekot" => ["docket"],
      "bgnoos" => ["bongos"], "aeiklt" => ["talkie"], "aabmss" => ["sambas"],
      "ehkrsu" => ["husker"], "ooprss" => ["spoors"],
      "inopst" => ["pintos", "pitons"], "aerstt" => ["taters", "taster"],
      "eeopty" => ["peyote"], "cccoxy" => ["coccyx"], "gnotuu" => ["outgun"],
      "cenosy" => ["coneys"], "bdlmuy" => ["dumbly"], "adeelt" => ["elated"],
      "belosu" => ["boules"], "einpps" => ["pepsin"], "afnssu" => ["snafus"],
      "aeenrs" => ["ranees"], "chitty" => ["titchy"], "aginst" => ["sating"],
      "hjnnoy" => ["johnny"], "aailrt" => ["lariat"], "abeein" => ["beanie"],
      "acipss" => ["aspics"], "cdeers" => ["screed"], "benott" => ["botnet"],
      "efirsv" => ["fivers"], "ddegir" => ["girded"], "egggno" => ["eggnog"],
      "chiosz" => ["schizo"], "deippr" => ["dipper"], "chikot" => ["thicko"],
      "bemnow" => ["bowmen"], "imnost" => ["inmost"], "eopppr" => ["popper"],
      "acehst" => ["sachet"], "bbnnoo" => ["bonbon"], "ddeiss" => ["dissed"],
      "deiklt" => ["kilted"], "ggnruy" => ["grungy"], "ceijru" => ["juicer"],
      "deeirs" => ["eiders"], "aabgin" => ["baaing"], "abikst" => ["batiks"],
      "eoorsw" => ["wooers"], "aimmos" => ["mimosa"], "ahsstw" => ["swaths"],
      "ekopsy" => ["pokeys"], "aaeglm" => ["agleam"],
      "aersst" => ["asters", "tasers"], "efoorw" => ["woofer"],
      "aemnsv" => ["mavens"], "emorsu" => ["mouser"], "floptu" => ["potful"],
      "ablost" => ["bloats"], "abelsy" => ["basely", "belays"],
      "ilmnsu" => ["muslin"], "eggoru" => ["gouger"], "adhpru" => ["purdah"],
      "einrsu" => ["inures"], "aepprs" => ["sapper"], "adenos" => ["anodes"],
      "dehitt" => ["tithed"], "abqrsu" => ["burqas"], "elmmop" => ["pommel"],
      "dellwy" => ["lewdly"], "dehmos" => ["moshed"],
      "adeprt" => ["petard", "prated"], "aemnor" => ["moaner"],
      "ceehit" => ["techie"], "detttu" => ["tutted"], "bbelmu" => ["bumble"],
      "ademnu" => ["unmade"], "ccisty" => ["cystic"], "cefirr" => ["ferric"],
      "beegst" => ["begets"], "aeimnr" => ["airmen"], "dgnoos" => ["godson"],
      "aessss" => ["sasses"], "aacfis" => ["fascia"], "aemqru" => ["marque"],
      "loopss" => ["sloops"], "ennost" => ["tenons"], "delors" => ["resold"],
      "adelsy" => ["slayed"], "acdior" => ["cardio"], "iilpst" => ["pistil"],
      "achhnu" => ["haunch"], "ijrstu" => ["jurist"], "dekstu" => ["tusked"],
      "demrsu" => ["demurs"], "aemntx" => ["taxmen"], "gglooy" => ["googly"],
      "dhiosv" => ["dovish"], "eginss" => ["gneiss"], "ghinpy" => ["hyping"],
      "knpssu" => ["spunks"], "elmnpu" => ["lumpen", "plenum"],
      "abbeir" => ["barbie"], "cccosu" => ["coccus"], "lmmsuy" => ["slummy"],
      "eijkor" => ["jokier"], "aeeggr" => ["reggae"], "cdehos" => ["coshed"],
      "ademnr" => ["remand"], "bbeops" => ["bebops"], "cimors" => ["micros"],
      "ceiiks" => ["sickie"], "egsstu" => ["gusset"], "beiiss" => ["ibises"],
      "ceehsy" => ["cheesy"], "eiilmr" => ["limier"], "hirrss" => ["shirrs"],
      "cdekru" => ["rucked"], "agorst" => ["gators", "argots"],
      "aehlru" => ["hauler"], "aeffnr" => ["naffer"], "adders" => ["adders"],
      "bcnotu" => ["cobnut"], "delort" => ["retold"], "cehiky" => ["hickey"],
      "dinpuw" => ["upwind", "windup"], "addeim" => ["diadem"],
      "eipsst" => ["pistes"], "eellrs" => ["resell"], "aooswz" => ["wazoos"],
      "ellpru" => ["puller"], "abbcir" => ["bicarb"], "gmoopr" => ["pogrom"],
      "degitw" => ["widget"], "moprst" => ["tromps"], "chiint" => ["chitin"],
      "aillyz" => ["lazily"], "aaelnn" => ["anneal"], "cinoss" => ["scions"],
      "aeinpr" => ["rapine"], "eiknoo" => ["nookie"], "bioost" => ["oboist"],
      "eosssu" => ["souses"], "egotyz" => ["zygote"], "ceosst" => ["cosset"],
      "ahilps" => ["palish", "phials"], "bhirsu" => ["hubris"],
      "ggmosy" => ["smoggy"], "bciino" => ["bionic"], "elosuv" => ["ovules"],
      "addhoo" => ["doodah"], "abegoz" => ["gazebo"], "giilnw" => ["wiling"],
      "aknrsy" => ["snarky"], "iinppp" => ["pippin"], "almtuu" => ["umlaut"],
      "chmoos" => ["smooch"], "ekoprr" => ["porker"], "aagnor" => ["angora"],
      "afosst" => ["fatsos"], "bhoooo" => ["boohoo"], "aahlos" => ["alohas"],
      "cekkop" => ["kopeck"], "deppsu" => ["supped"], "dehitw" => ["whited"],
      "ehnoss" => ["noshes"], "ginnpw" => ["pwning"], "cginno" => ["coning"],
      "aepptt" => ["tappet"], "aginwy" => ["yawing"], "efisty" => ["feisty"],
      "ccikrs" => ["cricks"], "acnoor" => ["corona"], "eilnno" => ["online"],
      "eiprty" => ["pyrite"], "aelttw" => ["wattle"], "aagmms" => ["gammas"],
      "ddegmo" => ["dodgem"], "abentu" => ["butane"], "aeilnp" => ["alpine"],
      "cddruy" => ["cruddy"], "aelnrv" => ["vernal"], "acceht" => ["cachet"],
      "aehrst" => ["haters"], "amnopt" => ["tampon"], "glmosu" => ["moguls"],
      "eggloo" => ["google"], "aeissz" => ["assize"], "ceiprs" => ["cripes"],
      "deossw" => ["dowses"], "aaclpr" => ["carpal"], "agnors" => ["sarong"],
      "cdmoot" => ["dotcom"], "bdeesw" => ["dweebs"], "bloott" => ["blotto"],
      "innoww" => ["winnow"], "eilnoo" => ["loonie"], "aacdlu" => ["caudal"],
      "belorw" => ["blower"], "efioot" => ["footie"], "aepstx" => ["expats"],
      "aelotz" => ["zealot"], "hmoprs" => ["morphs"], "aemsty" => ["mateys"],
      "anopst" => ["pantos"], "diostv" => ["divots"], "hilmoy" => ["homily"],
      "cilosu" => ["coulis"], "fiivvy" => ["vivify"], "booswx" => ["oxbows"],
      "eikrss" => ["kisser", "skiers"], "ahnstu" => ["sunhat"],
      "cdeiir" => ["dicier"], "aerstz" => ["ersatz"],
      "ddeenu" => ["denude", "endued"], "eipprs" => ["pipers"],
      "copsuy" => ["coypus"], "lnnosy" => ["nylons"], "aabggs" => ["gasbag"],
      "bffino" => ["boffin"], "eikrst" => ["trikes"], "chinop" => ["phonic"],
      "abemnr" => ["barmen"], "blrruy" => ["blurry"], "aabcrs" => ["scarab"],
      "adklny" => ["dankly"], "cdiisv" => ["viscid"], "hootty" => ["toothy"],
      "aaegst" => ["agates"], "hmstuy" => ["thymus"], "bdegno" => ["bonged"],
      "fgjluu" => ["jugful"], "abglmo" => ["gambol"], "ehimru" => ["humeri"],
      "cmnnoo" => ["noncom"], "ehinrs" => ["shiner"], "ggitwy" => ["twiggy"],
      "bflsyy" => ["flybys"], "bblrsu" => ["blurbs"], "himmsy" => ["shimmy"],
      "acghou" => ["gaucho"], "eikprs" => ["pikers"], "delosu" => ["loused"],
      "cklnsu" => ["clunks"], "bcimsu" => ["cubism"],
      "gimnpu" => ["impugn", "umping"], "abeert" => ["berate"],
      "aaimms" => ["miasma"], "beosst" => ["besots"], "himnoy" => ["hominy"],
      "adefor" => ["fedora"], "acnort" => ["cantor"], "aimssw" => ["swamis"],
      "aaffry" => ["affray"], "bdegiu" => ["budgie"], "deipss" => ["pissed"],
      "acprsu" => ["carpus"], "defnou" => ["fondue"], "illmpy" => ["limply"],
      "aflmru" => ["armful"], "aabder" => ["abrade"], "agimnx" => ["maxing"],
      "bbeils" => ["bibles"], "bdirtu" => ["turbid"], "aafims" => ["mafias"],
      "ahirtw" => ["wraith"], "aginpv" => ["vaping"], "acders" => ["cadres"],
      "abnrsu" => ["unbars"], "ddikos" => ["kiddos"], "aoqrtu" => ["quarto"],
      "bdemos" => ["demobs"], "dgiinp" => ["pidgin"], "glnpuu" => ["unplug"],
      "deemnr" => ["mender"], "footux" => ["outfox"], "cissuv" => ["viscus"],
      "deijkn" => ["jinked"], "dioosv" => ["ovoids"], "dginos" => ["doings"],
      "achnos" => ["nachos"], "ammpuw" => ["wampum"], "agilnz" => ["lazing"],
      "glnoos" => ["logons"], "ddeelm" => ["melded"], "dillsy" => ["idylls"],
      "anorty" => ["notary"], "gorstu" => ["grouts"], "annpsu" => ["unsnap"],
      "eeiinw" => ["wienie"], "cdeesu" => ["deuces"], "eloprv" => ["plover"],
      "aacimn" => ["caiman"], "abbels" => ["babels"], "akprsy" => ["sparky"],
      "aehrtt" => ["hatter"], "cdeeir" => ["deicer"], "acgily" => ["cagily"],
      "bdiotu" => ["outbid"], "aabgir" => ["airbag"], "agimos" => ["amigos"],
      "deggir" => ["digger"], "diloyz" => ["dozily"], "bdinnu" => ["unbind"],
      "fiitxy" => ["fixity"], "adeikr" => ["darkie"], "elorrs" => ["sorrel"],
      "accsuy" => ["yuccas"], "aeghio" => ["hoagie"], "adhnsy" => ["shandy"],
      "lprssu" => ["slurps"], "eflort" => ["floret"], "acfkrs" => ["fracks"],
      "aioptu" => ["utopia"], "acdent" => ["canted", "decant"],
      "efirss" => ["serifs"], "abkrsu" => ["burkas"], "eeepsw" => ["pewees"],
      "erstuy" => ["surety"], "elpsux" => ["plexus"], "aamnps" => ["sampan"],
      "denorw" => ["downer"], "eeelpr" => ["peeler"], "eirttw" => ["witter"],
      "ilrtwy" => ["twirly"], "chiilt" => ["litchi"], "defikn" => ["finked"],
      "eoprss" => ["posers"], "aegims" => ["ageism"], "ceoprt" => ["copter"],
      "acgttu" => ["catgut"], "elmrty" => ["myrtle"], "abimru" => ["barium"],
      "ehistt" => ["tithes"], "aegotu" => ["outage"], "acimno" => ["manioc"],
      "einort" => ["tonier"], "aimnsu" => ["animus"], "beoort" => ["reboot"],
      "deeinr" => ["denier"], "abesst" => ["basset"], "deimpp" => ["pimped"],
      "elorsw" => ["rowels"], "adeffg" => ["gaffed"], "giinnx" => ["nixing"],
      "aehmrs" => ["masher"], "deikno" => ["oinked"], "eilttt" => ["tittle"],
      "inpsuz" => ["unzips"], "abrtty" => ["bratty"], "efmrsu" => ["femurs"],
      "acgnos" => ["congas"], "eemnss" => ["menses"], "ejlpsu" => ["juleps"],
      "iinttu" => ["intuit"], "chimss" => ["schism"], "lrrsuy" => ["slurry"],
      "aehhst" => ["heaths"], "efhils" => ["elfish"], "elnosv" => ["sloven"],
      "ahllow" => ["hallow"], "benors" => ["boners"], "acilry" => ["racily"],
      "abhost" => ["bathos"], "abbcsy" => ["scabby"], "deeffr" => ["reffed"],
      "adempt" => ["tamped"], "eopstx" => ["sexpot"], "ailmnu" => ["alumni"],
      "aeittt" => ["tattie"], "aehirs" => ["ashier"], "aaginn" => ["angina"],
      "aeglnw" => ["wangle"], "aagmns" => ["gasman"], "cchhii" => ["chichi"],
      "cehkor" => ["choker"], "adelpp" => ["dapple"], "llloop" => ["lollop"],
      "jnooru" => ["journo"], "ddeiik" => ["kiddie"], "ehikrs" => ["shrike"],
      "aeerty" => ["eatery"], "ggikno" => ["ginkgo"], "aeflty" => ["fealty"],
      "cehsty" => ["chesty"], "aaamnp" => ["panama"], "cdeiky" => ["dickey"],
      "beoorz" => ["boozer"], "bbddeo" => ["dobbed"], "aeklnt" => ["anklet"],
      "aairvy" => ["aviary"], "abdirs" => ["disbar"], "acenot" => ["octane"],
      "eknorr" => ["kroner"], "dehnos" => ["noshed"], "bhikos" => ["kibosh"],
      "deginp" => ["pinged"], "ceehor" => ["cohere"], "bbdeoo" => ["boobed"],
      "accruy" => ["curacy"], "aekmnu" => ["unmake"], "ailotx" => ["oxtail"],
      "cefhis" => ["fiches"], "cdegor" => ["codger"], "ekrstw" => ["twerks"],
      "aailmp" => ["impala"], "einrwy" => ["winery"], "cioprt" => ["tropic"],
      "inorss" => ["rosins"], "aorstt" => ["tarots"], "aegglw" => ["waggle"],
      "deggot" => ["togged"], "cinost" => ["tocsin"], "begilt" => ["giblet"],
      "aeehnp" => ["peahen"], "aaimnr" => ["airman"],
      "acerrt" => ["carter", "tracer"], "aeerrw" => ["wearer"],
      "aoptuy" => ["payout"], "dempsu" => ["spumed"], "bilntz" => ["blintz"],
      "diinox" => ["dioxin"], "adersw" => ["waders"], "bceips" => ["biceps"],
      "ddeffu" => ["duffed"], "aabill" => ["labial"], "aegirw" => ["earwig"],
      "adlnpu" => ["upland"], "eginrw" => ["winger"], "diilty" => ["tidily"],
      "hmmsuu" => ["hummus"], "eiiknp" => ["pinkie"], "ddennu" => ["dunned"],
      "eersst" => ["esters", "serest"], "aaffir" => ["raffia"],
      "chinos" => ["chinos"], "aalssv" => ["vassal"], "clnoou" => ["uncool"],
      "adinrs" => ["dinars", "nadirs"], "gipsty" => ["pigsty"],
      "beoosz" => ["boozes"], "ainnnt" => ["tannin"], "enppru" => ["prenup"],
      "deeggv" => ["vegged"], "eikrsv" => ["skiver"], "cciino" => ["iconic"],
      "eqrtwy" => ["qwerty"], "abiors" => ["isobar"], "bghist" => ["bights"],
      "aahmns" => ["shaman"], "defioo" => ["foodie"], "celruw" => ["curlew"],
      "eoprst" => ["tropes"], "eeprst" => ["preset"], "beehst" => ["behest"],
      "inopty" => ["pointy"], "acerrv" => ["carver"], "hnrtuu" => ["unhurt"],
      "eiknrs" => ["sinker"], "bdeloo" => ["boodle"], "efstuz" => ["futzes"],
      "derstu" => ["duster"], "deesst" => ["steeds"], "dlnosu" => ["unsold"],
      "efoorr" => ["roofer"], "ansyzz" => ["snazzy"], "ennstu" => ["unsent"],
      "aeegmt" => ["gamete"], "bbelpy" => ["plebby", "pebbly"],
      "blmnuy" => ["numbly"], "cclotu" => ["occult"], "ahhkoo" => ["hookah"],
      "cdeehl" => ["leched"], "aaerwx" => ["earwax"], "deefsu" => ["defuse"],
      "eeiptw" => ["peewit"], "binrsu" => ["bruins"], "elorss" => ["lessor"],
      "adfgly" => ["gadfly"], "degios" => ["dogies"], "aceghu" => ["gauche"],
      "eiprst" => ["sprite"], "kltuyz" => ["klutzy"],
      "aelpss" => ["passel", "sepals"], "eggijr" => ["jigger"],
      "dddeor" => ["dodder"], "elosvy" => ["loveys"], "bcgory" => ["cyborg"],
      "abinos" => ["bonsai"], "cdekno" => ["conked"], "deorrw" => ["reword"],
      "begmsu" => ["begums"], "beelps" => ["plebes", "bleeps"],
      "eiprtv" => ["privet"], "aeglmy" => ["gamely"], "adejru" => ["adjure"],
      "deorru" => ["ordure"], "einppr" => ["nipper"], "eilnps" => ["spline"],
      "bootyy" => ["toyboy"], "ciosst" => ["stoics"], "cmprsu" => ["scrump"],
      "hiopps" => ["hippos"], "iprstz" => ["spritz"],
      "deinop" => ["ponied", "opined"], "eilmot" => ["motile"],
      "hmrstu" => ["thrums"], "beilmy" => ["blimey"], "dglooy" => ["goodly"],
      "acdefs" => ["decafs"], "eeeprw" => ["weeper"], "aemmry" => ["yammer"],
      "iksvvy" => ["skivvy"], "ahlmos" => ["shalom"],
      "acorst" => ["castor", "scrota", "costar"], "inppsy" => ["snippy"],
      "aablss" => ["balsas"], "ccehil" => ["chicle"], "begosy" => ["bogeys"],
      "eeefrr" => ["reefer"], "aegimn" => ["gamine"],
      "deilrs" => ["idlers", "slider"], "efrrsu" => ["surfer"],
      "acnnry" => ["cranny"], "adilvy" => ["avidly"], "eeilry" => ["eerily"],
      "adhips" => ["aphids"], "eenrrt" => ["renter"], "abbgry" => ["grabby"],
      "aostty" => ["toasty"], "ceehrt" => ["etcher"],
      "aeprst" => ["prates", "repast"], "ekloor" => ["looker"],
      "ehoprs" => ["posher"], "fnostu" => ["futons"], "cdenop" => ["ponced"],
      "eorrsv" => ["rovers"], "aenttu" => ["tauten"], "aellmy" => ["lamely"],
      "dggruy" => ["druggy"], "eiinpt" => ["tiepin"], "afginx" => ["faxing"],
      "dehott" => ["hotted"], "aeenst" => ["sateen"], "ekllns" => ["knells"],
      "aflmyy" => ["mayfly"], "giklny" => ["kingly"], "abchpu" => ["hubcap"],
      "mpstuy" => ["stumpy"], "bmoosy" => ["bosomy"], "celosy" => ["coleys"],
      "cdipsu" => ["cupids", "cuspid"], "beorsw" => ["bowers"],
      "deilor" => ["roiled"], "acekly" => ["lackey"], "blnotu" => ["unbolt"],
      "aeinrs" => ["sarnie"], "aeehhw" => ["heehaw"], "aaacmr" => ["maraca"],
      "eimmru" => ["immure"], "bnorsu" => ["suborn"], "eilort" => ["toiler"],
      "aalnst" => ["aslant"], "clmosu" => ["locums"], "adhrss" => ["shards"],
      "acelnt" => ["lancet"], "aefrst" => ["afters", "strafe"],
      "ghiort" => ["righto"], "abbelu" => ["bauble"], "cllssu" => ["sculls"],
      "cdenot" => ["docent"], "ehklsw" => ["whelks"], "ceilrs" => ["slicer"],
      "ehirss" => ["shires"], "eesttu" => ["suttee"], "ehikor" => ["hokier"],
      "bddego" => ["bodged"], "abeilw" => ["bewail"],
      "adegos" => ["dagoes", "dosage"], "aanrrt" => ["arrant"],
      "efilrs" => ["lifers"], "ceopsu" => ["coupes"], "aoprrt" => ["raptor"],
      "chikrs" => ["kirsch"], "aaenps" => ["paeans"], "ilnopp" => ["poplin"],
      "eefltt" => ["fettle"], "dioprt" => ["torpid"], "nopstu" => ["unstop"],
      "cehlps" => ["schlep"], "aeilln" => ["lineal"], "adddel" => ["addled"],
      "eilpry" => ["ripely"], "ddeikr" => ["kidder"], "ammmno" => ["mammon"],
      "ghnosu" => ["shogun"], "aelmms" => ["lemmas"], "eiloor" => ["oriole"],
      "ilmstu" => ["litmus"], "beells" => ["belles"], "bbegit" => ["gibbet"],
      "aelnsy" => ["sanely"], "diilmp" => ["limpid"], "aegnnt" => ["gannet"],
      "deloru" => ["loured"], "eilppu" => ["pileup"], "abegln" => ["bangle"],
      "acppry" => ["crappy"], "cejnou" => ["jounce"], "hirsty" => ["shirty"],
      "acmstu" => ["muscat"], "bhilsu" => ["bluish"], "ddiims" => ["misdid"],
      "acelrr" => ["carrel"], "eprstw" => ["twerps"], "eeprsv" => ["vesper"],
      "cilmuu" => ["cumuli"], "achlry" => ["archly"], "abcelm" => ["becalm"],
      "hiopsy" => ["physio"], "ahmnos" => ["hansom"], "cdjnou" => ["jocund"],
      "acdemp" => ["decamp"], "fhirst" => ["firths", "shrift"],
      "inorst" => ["intros"], "alnsvy" => ["sylvan"], "giimnr" => ["riming"],
      "bceehr" => ["breech"], "beorst" => ["strobe", "sorbet"],
      "bdeiir" => ["birdie"], "abjost" => ["jabots"], "aelnor" => ["loaner"],
      "depssu" => ["pseuds"], "eoprsu" => ["poseur"], "lmmpuy" => ["plummy"],
      "aegrsu" => ["augers"], "dhiost" => ["dhotis"], "isttwy" => ["twisty"],
      "eimrst" => ["mister"], "aiiptw" => ["wapiti"], "kklmuu" => ["mukluk"],
      "acelyy" => ["clayey"], "elmott" => ["mottle"], "dksuuz" => ["kudzus"],
      "begios" => ["bogies"], "ackrsw" => ["wracks"], "eiostv" => ["soviet"],
      "aeluvv" => ["vulvae"], "aainpt" => ["patina"], "adettt" => ["tatted"],
      "agginz" => ["niggaz"], "bdeooz" => ["boozed"], "aefkrs" => ["fakers"],
      "achssw" => ["schwas"], "aipstt" => ["pittas"], "abkmoo" => ["kaboom"],
      "eehort" => ["hetero", "hereto"], "aeelnv" => ["leaven"],
      "eginst" => ["signet"], "esssuw" => ["wusses"], "allory" => ["orally"],
      "emoppt" => ["moppet"], "egijrs" => ["rejigs"], "aprsst" => ["sprats"],
      "cesssu" => ["cusses"], "adegpw" => ["gawped"], "hkoopu" => ["hookup"],
      "ehjoss" => ["joshes"], "bdeist" => ["bedsit", "bidets"],
      "aahmrs" => ["ashram"], "fmpruy" => ["frumpy"], "elorst" => ["ostler"],
      "deinos" => ["onside"], "ahirrs" => ["sirrah"], "bbceor" => ["cobber"],
      "amorsu" => ["amours"], "abdekr" => ["debark"], "ceeimt" => ["emetic"],
      "efrrsy" => ["fryers"], "efilwy" => ["wifely"], "ffipss" => ["spiffs"],
      "copruy" => ["croupy"], "dlloop" => ["dollop"], "bdentu" => ["bunted"],
      "effilr" => ["riffle"], "cehlou" => ["louche"], "aefinr" => ["fainer"],
      "beorvv" => ["bovver"], "eeelty" => ["eyelet"], "achoot" => ["cahoot"],
      "dehoop" => ["poohed"], "abcssu" => ["scubas"], "ddilty" => ["tiddly"],
      "ccooor" => ["rococo"], "adeprr" => ["draper"], "eflmsu" => ["flumes"],
      "befgos" => ["befogs"], "acelov" => ["coeval"], "ceehrw" => ["chewer"],
      "cdeltu" => ["dulcet"], "aemnoy" => ["yeoman"], "adegot" => ["dotage"],
      "aaerrt" => ["errata"], "bilssy" => ["sibyls"], "amottz" => ["matzot"],
      "eeegrz" => ["geezer"], "aeeprs" => ["serape"], "ejlosu" => ["joules"],
      "abmnow" => ["bowman"], "aegmos" => ["omegas"], "acnnot" => ["canton"],
      "dehioo" => ["hoodie"], "bbosuy" => ["busboy"], "adglop" => ["lapdog"],
      "ahoosy" => ["yahoos"], "einnpt" => ["tenpin"], "chisst" => ["schist"],
      "deossu" => ["soused"], "biorst" => ["bistro"], "anoprt" => ["tarpon"],
      "aeppry" => ["papery"], "biqssu" => ["squibs"], "beillt" => ["billet"],
      "aglnsy" => ["slangy"], "acddiy" => ["dyadic"], "eemost" => ["emotes"],
      "eilppt" => ["tipple"], "ahmpsu" => ["mashup"], "acertu" => ["curate"],
      "clmpuy" => ["clumpy"], "aosstt" => ["stoats"], "acceit" => ["acetic"],
      "acelpr" => ["carpel", "placer"], "gilnty" => ["tingly"],
      "aeilss" => ["lassie"], "eilsst" => ["islets", "stiles"],
      "emmmru" => ["mummer"], "cehtty" => ["tetchy"], "eelmpt" => ["pelmet"],
      "lprsyy" => ["spryly"], "aabggr" => ["ragbag"], "elprty" => ["pertly"],
      "abcfno" => ["confab"], "aanqtu" => ["quanta"], "deilop" => ["dipole"],
      "aalmnu" => ["alumna"], "eorstt" => ["tortes"], "aeglrs" => ["lagers"],
      "abdees" => ["seabed"], "acdstu" => ["ducats"], "chnpuy" => ["punchy"],
      "ehorst" => ["throes"], "mmuuuu" => ["muumuu"], "abciim" => ["iambic"],
      "beiqsu" => ["bisque"], "acilno" => ["oilcan"], "aelmrt" => ["armlet"],
      "ailnru" => ["urinal"], "addenr" => ["dander"], "eeirsx" => ["sexier"],
      "ehknru" => ["hunker"], "ennnop" => ["pennon"], "enrrsu" => ["reruns"],
      "eiklrt" => ["kilter"], "eegrrv" => ["verger"], "deilmn" => ["limned"],
      "eeippy" => ["yippee"], "eiklnw" => ["winkle", "welkin"],
      "aabegt" => ["teabag"], "gimosz" => ["gizmos"], "ellmuv" => ["vellum"],
      "ailstv" => ["vitals"], "abfilu" => ["fibula"], "rsstty" => ["trysts"],
      "chpstu" => ["putsch"], "deorss" => ["dosser"], "giltyz" => ["glitzy"],
      "eeefft" => ["effete"], "enosst" => ["stenos"], "adhhow" => ["howdah"],
      "eopsss" => ["posses"], "cdelno" => ["cloned"], "acelnr" => ["lancer"],
      "aabmms" => ["mambas"], "mpstuu" => ["sputum"], "egginr" => ["nigger"],
      "aelmnw" => ["lawmen"], "beeisv" => ["bevies"], "cenosv" => ["covens"],
      "deiorz" => ["dozier"], "dghouy" => ["doughy"], "aahirs" => ["sharia"],
      "acehop" => ["cheapo"], "cekmor" => ["mocker"], "aciinn" => ["niacin"],
      "dnoors" => ["rondos"], "beegno" => ["begone"], "eilnns" => ["linens"],
      "eemmnr" => ["mermen"], "aeegop" => ["apogee"], "aemnst" => ["stamen"],
      "chopsy" => ["psycho"], "dinstu" => ["nudist"], "deiksv" => ["skived"],
      "emoprr" => ["romper"], "degirt" => ["girted"], "aeflnx" => ["flaxen"],
      "abenry" => ["barney"], "eilrvy" => ["livery", "verily"],
      "aahpss" => ["pashas"], "aborrw" => ["barrow"], "dfoorx" => ["oxford"],
      "iklnsy" => ["slinky"], "ehlorw" => ["howler"], "begioo" => ["boogie"],
      "defirv" => ["fervid"], "abelot" => ["oblate"], "aimrtu" => ["atrium"],
      "bcmruy" => ["crumby"], "eiqrsu" => ["quires"], "eirrst" => ["triers"],
      "deehmt" => ["themed"], "aehnns" => ["hennas"], "acilot" => ["coital"],
      "errsuy" => ["surrey"], "aiilry" => ["airily"], "ehkoor" => ["hooker"],
      "aemrst" => ["tamers"], "aaellp" => ["paella"], "ceippt" => ["peptic"],
      "aceemr" => ["raceme"], "deeips" => ["espied"], "ginost" => ["ingots"],
      "eemnoy" => ["yeomen"], "benntu" => ["unbent"], "cginox" => ["coxing"],
      "aeimns" => ["inseam"], "bbikos" => ["skibob"], "ersstu" => ["russet"],
      "dempru" => ["dumper"], "abcors" => ["carobs"], "ceiorr" => ["corrie"],
      "aeeglt" => ["eaglet", "legate"], "agmpuz" => ["gazump"],
      "eejjnu" => ["jejune"], "eilnos" => ["insole"], "depsuy" => ["pseudy"],
      "agmmno" => ["gammon"], "ceortt" => ["cotter"], "efgsuu" => ["fugues"],
      "aadmyy" => ["mayday"], "aadkms" => ["damask"], "adlmpy" => ["damply"],
      "aceeff" => ["efface"], "acilsv" => ["cavils"], "eilnnt" => ["linnet"],
      "gginno" => ["noggin"], "aepprr" => ["rapper"], "klnops" => ["plonks"],
      "agirst" => ["gratis"], "beikrs" => ["bikers"], "aqssuw" => ["squaws"],
      "eeggsv" => ["vegges"], "emoszz" => ["mezzos"], "chmops" => ["chomps"],
      "aeffgr" => ["gaffer"], "eippuy" => ["yuppie"], "aamoss" => ["samosa"],
      "ossttu" => ["stouts"], "hilmos" => ["holism"], "beflou" => ["befoul"],
      "beirst" => ["bestir"], "abdego" => ["bodega"], "eeginp" => ["peeing"],
      "eilmpw" => ["wimple"], "acnost" => ["cantos"], "gmprsu" => ["grumps"],
      "ablmoo" => ["abloom"], "deilnn" => ["linden"], "aablst" => ["basalt"],
      "eillrt" => ["tiller"], "glootu" => ["logout"], "bdeimu" => ["imbued"],
      "ilprty" => ["triply"], "deikpp" => ["kipped"], "aijnns" => ["ninjas"],
      "abnory" => ["barony"], "abelss" => ["sables"],
      "dllory" => ["drolly", "lordly"], "bbnosy" => ["snobby"],
      "eilmno" => ["oilmen"], "eirttv" => ["trivet"], "deippy" => ["yipped"],
      "aeemss" => ["sesame"], "arstux" => ["surtax"], "adertt" => ["tarted"],
      "denrsu" => ["sunder"], "deegsu" => ["segued"], "ceistu" => ["cuties"],
      "eilnsv" => ["snivel"], "aceins" => ["casein"], "aggiww" => ["wigwag"],
      "aampps" => ["pampas"], "aklnox" => ["klaxon"], "abinrs" => ["bairns"],
      "egnruy" => ["gurney"], "elmnoy" => ["lemony"], "hlopss" => ["splosh"],
      "begils" => ["bilges"], "aclopu" => ["copula", "cupola"],
      "eimptu" => ["impute"], "aaabcn" => ["cabana"], "dippry" => ["drippy"],
      "eeilnp" => ["penile"], "aimnst" => ["mantis", "matins"],
      "aehorx" => ["hoaxer"], "chipry" => ["chirpy"], "ceenrs" => ["censer"],
      "abehlr" => ["herbal"], "aahmtz" => ["hazmat"], "ffnoru" => ["runoff"],
      "ghinty" => ["thingy"], "eentux" => ["exeunt"], "ahikrs" => ["rakish"],
      "abejru" => ["abjure"], "aerswy" => ["sawyer"], "aaegln" => ["galena"],
      "iprstu" => ["purist"], "adddoo" => ["doodad"], "bcmoos" => ["combos"],
      "doprsy" => ["dropsy"], "adeppz" => ["zapped"], "adesss" => ["sassed"],
      "afglnu" => ["fungal"], "adhnnu" => ["unhand"], "deilos" => ["oldies"],
      "abderu" => ["dauber", "earbud"], "deimst" => ["demist"],
      "abdlry" => ["drably"], "alpssy" => ["splays"], "ffinpu" => ["puffin"],
      "aelruv" => ["valuer"]}
    |> Map.get(string_id)
  end
end
