defmodule Jumble.ScowlDict.Medium.Length5 do
  def get(string_id) do
    %{"ademn" => ["admen"], "bgrsu" => ["burgs"], "cchno" => ["conch"],
      "ilmos" => ["limos"], "eknor" => ["krone"], "denuw" => ["unwed"],
      "insst" => ["snits"], "filty" => ["fitly"], "cdiks" => ["dicks"],
      "aemty" => ["matey", "meaty"], "deego" => ["geode"], "aelmm" => ["lemma"],
      "abhij" => ["bhaji"], "fiins" => ["finis"], "fmpru" => ["frump"],
      "ehpry" => ["hyper"], "lopsy" => ["polys"], "eijmo" => ["emoji"],
      "emors" => ["mores"], "belry" => ["beryl"], "egirv" => ["giver"],
      "akrsy" => ["sarky"], "ejlou" => ["joule"], "ahssw" => ["swash"],
      "aailx" => ["axial"], "ehist" => ["heist"], "acems" => ["acmes"],
      "bgirs" => ["brigs"], "allxy" => ["laxly"], "elnos" => ["noels"],
      "affqu" => ["quaff"], "knooy" => ["nooky"], "lnopy" => ["pylon"],
      "cehst" => ["techs"], "ddoty" => ["toddy"], "ghsuy" => ["gushy"],
      "cdssu" => ["scuds"], "aderw" => ["wader"], "fstuy" => ["fusty"],
      "cdeim" => ["medic"], "abehr" => ["rehab"], "rsstu" => ["truss"],
      "acdef" => ["decaf"], "bbtuy" => ["tubby"], "acips" => ["aspic"],
      "doors" => ["roods"], "deery" => ["reedy"], "eemry" => ["emery"],
      "abkly" => ["balky"], "ffips" => ["spiff"], "eimrx" => ["remix"],
      "celru" => ["lucre"], "aeort" => ["orate"], "chivy" => ["chivy"],
      "abbek" => ["kebab"], "adent" => ["anted"], "arsty" => ["satyr", "artsy"],
      "ahory" => ["hoary"], "dioov" => ["ovoid"], "eoorw" => ["wooer"],
      "agnry" => ["rangy"], "prstu" => ["turps"], "bghru" => ["burgh"],
      "aainv" => ["avian"], "anowy" => ["noway"], "deinx" => ["nixed"],
      "giosy" => ["yogis"], "agnor" => ["argon"], "ciilt" => ["licit"],
      "egnor" => ["negro"], "enrvy" => ["nervy"], "deeil" => ["elide"],
      "inopt" => ["pinto", "piton"], "cehiv" => ["chive"], "agnrs" => ["grans"],
      "aottu" => ["outta"], "elorw" => ["rowel"], "achry" => ["chary"],
      "cikky" => ["kicky"], "eorxx" => ["xerox"], "begoy" => ["bogey"],
      "ijmmy" => ["jimmy"], "gloos" => ["logos"], "ittwx" => ["twixt"],
      "deijv" => ["jived"], "deeir" => ["eider"], "aensv" => ["naves"],
      "achlr" => ["larch"], "gotuy" => ["gouty"], "deoop" => ["pooed"],
      "oppsy" => ["soppy"], "ilors" => ["roils"], "akssu" => ["skuas"],
      "abtty" => ["batty"], "hlsyy" => ["shyly"], "cloos" => ["locos"],
      "adesz" => ["adzes"], "admrs" => ["drams"], "adnry" => ["randy"],
      "esstt" => ["setts"], "eprsv" => ["pervs"], "beelv" => ["bevel"],
      "dffsu" => ["duffs"], "abbel" => ["babel"], "orsty" => ["troys", "tyros"],
      "acffs" => ["caffs"], "ddoos" => ["dodos"], "aabes" => ["abase"],
      "eegsu" => ["segue"], "chlru" => ["churl"], "eglos" => ["loges"],
      "aahps" => ["pasha"], "aairt" => ["atria"], "cikns" => ["snick"],
      "eossu" => ["souse"], "eikrs" => ["skier"], "fopsu" => ["poufs"],
      "ffiny" => ["niffy"], "aeepy" => ["payee"], "adhss" => ["shads"],
      "adnor" => ["radon"], "eltwy" => ["wetly"], "chmpu" => ["chump"],
      "rsuuy" => ["usury"], "adhip" => ["aphid"], "lrwyy" => ["wryly"],
      "orstu" => ["roust", "torus"], "amprs" => ["prams"], "efguu" => ["fugue"],
      "akpry" => ["parky"], "einst" => ["inset", "stein", "tines"],
      "iinnt" => ["innit"], "elnor" => ["loner"], "densw" => ["wends"],
      "ackrw" => ["wrack"], "lppuy" => ["pulpy"], "ehitt" => ["tithe"],
      "einru" => ["inure"], "defgo" => ["defog"], "chino" => ["chino"],
      "ceost" => ["cotes"], "abdly" => ["baldy"], "ahlsu" => ["hulas"],
      "beikr" => ["biker"], "adepr" => ["padre"], "ackwy" => ["wacky"],
      "aahll" => ["halal"], "eirsw" => ["weirs"], "bflsu" => ["flubs"],
      "ehpsy" => ["hypes"], "deorv" => ["roved"], "eggnu" => ["gunge"],
      "deisw" => ["wised"], "blowy" => ["blowy"], "alosv" => ["salvo"],
      "ddety" => ["teddy"], "ersst" => ["tress"], "aefir" => ["afire"],
      "eijsv" => ["jives"], "foops" => ["poofs"], "dotty" => ["dotty"],
      "ademx" => ["maxed"], "girst" => ["girts", "grist"], "aisvv" => ["vivas"],
      "eflmu" => ["flume"], "kossu" => ["souks"], "ceesx" => ["execs"],
      "adegw" => ["wadge"], "morwy" => ["wormy"], "ailpt" => ["plait"],
      "adert" => ["tared"], "ggipy" => ["piggy"], "acsst" => ["scats"],
      "acdss" => ["scads"], "ainsw" => ["swain"], "aflns" => ["flans"],
      "illrs" => ["rills"], "beorr" => ["borer"], "eeltx" => ["telex"],
      "aacdh" => ["dacha"], "einop" => ["opine"], "empst" => ["temps"],
      "eprtw" => ["twerp"], "epppy" => ["peppy"], "aluuv" => ["uvula"],
      "iijnn" => ["jinni"], "cjkos" => ["jocks"], "acmpy" => ["campy"],
      "belos" => ["boles"], "acerv" => ["caver"], "booyz" => ["boozy"],
      "akmny" => ["manky"], "dells" => ["dells"], "hmoop" => ["oomph"],
      "ilosv" => ["viols"], "aeins" => ["anise"], "egist" => ["gites"],
      "hoops" => ["poohs"], "aelsv" => ["vales"], "akkpu" => ["pukka"],
      "bdeit" => ["bidet"], "bgnsu" => ["bungs"], "ampst" => ["tamps"],
      "cfksu" => ["fucks"], "jlowy" => ["jowly"], "moopr" => ["promo"],
      "ammmy" => ["mammy"], "adhsu" => ["sadhu"], "bcitu" => ["cubit"],
      "aepsv" => ["vapes"], "chitt" => ["titch"], "artwy" => ["warty"],
      "bbooy" => ["yobbo"], "aclos" => ["colas"], "besuz" => ["zebus"],
      "gootu" => ["outgo"], "ekrtw" => ["twerk"], "grstu" => ["trugs"],
      "aesst" => ["sates"], "ehooy" => ["hooey"], "hkooy" => ["hooky"],
      "agssw" => ["swags"], "drstu" => ["turds"], "cfios" => ["coifs"],
      "ceops" => ["copse"], "aalnt" => ["natal"], "dkuuz" => ["kudzu"],
      "cloyy" => ["coyly"], "billy" => ["billy"], "dgins" => ["dings"],
      "acmss" => ["scams"], "cinos" => ["scion"], "aknsw" => ["wanks", "swank"],
      "eegrs" => ["serge"], "aelnu" => ["ulnae"], "abdet" => ["bated"],
      "bceel" => ["celeb"], "ilsty" => ["styli"], "apzzz" => ["pzazz"],
      "apppy" => ["pappy"], "ahstw" => ["swath"], "akptu" => ["kaput"],
      "giltz" => ["glitz"], "afikr" => ["fakir"], "abmmo" => ["mambo"],
      "cikrs" => ["ricks"], "opsty" => ["typos"], "hortt" => ["troth"],
      "ainst" => ["antis"], "cetuy" => ["cutey"], "dhosw" => ["dhows"],
      "eemms" => ["memes"], "cptuu" => ["cutup"], "aejps" => ["japes"],
      "adhij" => ["jihad"], "abcrt" => ["bract"], "gimpy" => ["gimpy"],
      "hpsuw" => ["whups"], "bdery" => ["derby"], "alppu" => ["pupal"],
      "akkop" => ["kapok"], "acmps" => ["scamp"], "aegru" => ["auger"],
      "ahmmy" => ["hammy"], "alswy" => ["yawls"], "artty" => ["tarty"],
      "ajyzz" => ["jazzy"], "aelos" => ["aloes"], "adinv" => ["divan", "viand"],
      "filoo" => ["folio"], "effis" => ["fiefs", "fifes"], "copuy" => ["coypu"],
      "acepr" => ["crape"], "adqsu" => ["quads"], "knowy" => ["wonky"],
      "aborx" => ["borax"], "glloy" => ["golly"], "kkooy" => ["kooky"],
      "acnop" => ["capon"], "aqsuw" => ["squaw"], "cfmoy" => ["comfy"],
      "dempu" => ["umped"], "aimno" => ["amino"], "eggly" => ["leggy"],
      "aerrv" => ["raver"], "hiopp" => ["hippo"], "adels" => ["dales"],
      "aenns" => ["senna"], "aeimn" => ["anime"], "aasty" => ["satay"],
      "biqsu" => ["squib"], "eorrv" => ["rover"], "allpy" => ["pally"],
      "appyz" => ["zappy"], "ahiku" => ["haiku"], "ceopu" => ["coupe"],
      "eknsu" => ["nukes"], "ciily" => ["icily"], "dimtu" => ["tumid"],
      "emott" => ["motet"], "eenty" => ["teeny"], "aemnv" => ["maven"],
      "oowyz" => ["woozy"], "optty" => ["potty"], "bnstu" => ["bunts"],
      "eglsu" => ["luges"], "aadin" => ["naiad"], "gkoos" => ["gooks"],
      "eopxy" => ["epoxy"], "eilst" => ["islet", "stile"], "cehnt" => ["tench"],
      "choop" => ["pooch"], "aemss" => ["mesas"], "eilmy" => ["limey"],
      "adeiu" => ["adieu"], "aemsx" => ["maxes"], "acinr" => ["cairn"],
      "sttuu" => ["tutus"], "impsw" => ["wimps"], "acipr" => ["carpi"],
      "deesw" => ["swede"], "gimny" => ["mingy"], "aaggr" => ["ragga"],
      "efirs" => ["serif"], "cdeos" => ["coeds"], "adffy" => ["daffy"],
      "cdhuy" => ["duchy"], "ceort" => ["recto"], "bgmou" => ["gumbo"],
      "bilsy" => ["sibyl"], "acksw" => ["wacks"], "acdos" => ["codas"],
      "estty" => ["testy"], "bdego" => ["bodge"], "acilv" => ["cavil"],
      "efsst" => ["fests"], "innpy" => ["pinny"], "adoty" => ["toady"],
      "aorst" => ["rotas", "taros"], "iimmn" => ["minim"],
      "adest" => ["sated", "stead"], "acert" => ["caret"], "deimr" => ["rimed"],
      "demos" => ["demos"], "deest" => ["steed"], "cemor" => ["comer"],
      "mmopy" => ["pommy"], "adeno" => ["anode"], "abest" => ["betas", "bates"],
      "ooprs" => ["spoor"], "bersu" => ["rebus", "rubes"], "glruy" => ["lurgy"],
      "noost" => ["snoot"], "ginyz" => ["zingy"], "anopt" => ["panto"],
      "achno" => ["nacho"], "efirx" => ["fixer"], "ainno" => ["anion"],
      "loopy" => ["loopy"], "ahsst" => ["stash"], "agimn" => ["gamin"],
      "aboss" => ["basso"], "ggnuy" => ["gungy"], "inors" => ["rosin"],
      "gmoss" => ["smogs"], "orstt" => ["torts"], "affty" => ["taffy"],
      "hhips" => ["phish"], "films" => ["milfs"], "bbeop" => ["bebop"],
      "elssu" => ["slues"], "agimo" => ["amigo"], "emost" => ["motes"],
      "ajmmy" => ["jammy"], "epsxy" => ["pyxes"], "aabls" => ["balsa", "basal"],
      "aaprs" => ["paras"], "aegnv" => ["vegan"], "deims" => ["deism"],
      "cdkuy" => ["ducky"], "eoprs" => ["poser"], "adisv" => ["divas"],
      "eiors" => ["osier"], "iswzz" => ["swizz"], "aflsy" => ["flays"],
      "aijnn" => ["ninja"], "boowx" => ["oxbow"], "afnsu" => ["fauns", "snafu"],
      "cklnu" => ["clunk"], "befgo" => ["befog"], "acppu" => ["cuppa"],
      "efiln" => ["elfin"], "fknsu" => ["funks"], "gilno" => ["login"],
      "elovy" => ["lovey"], "abnns" => ["banns"], "inqsu" => ["quins"],
      "cepss" => ["specs"], "abeiz" => ["baize"], "dffos" => ["doffs"],
      "achmo" => ["mocha"], "aaguv" => ["guava"], "afflo" => ["offal"],
      "acdit" => ["dicta"], "dgino" => ["dingo"], "aefsx" => ["faxes"],
      "ghosu" => ["sough"], "cgior" => ["corgi"], "deemn" => ["emend"],
      "ahpss" => ["hasps"], "aenov" => ["novae"], "ciprs" => ["scrip"],
      "ehilx" => ["helix"], "noopr" => ["porno"], "opsuy" => ["soupy"],
      "aostt" => ["stoat"], "aabms" => ["samba"], "cerru" => ["curer"],
      "bllos" => ["bolls"], "bertu" => ["tuber"], "aoppp" => ["poppa"],
      "bknos" => ["bonks"], "bglos" => ["globs"], "aalms" => ["lamas"],
      "ehmor" => ["homer"], "acnrs" => ["narcs"], "abegt" => ["begat"],
      "empsu" => ["spume"], "efirt" => ["refit"], "lorsu" => ["lours"],
      "asstt" => ["stats"], "eflos" => ["floes"], "iklsy" => ["silky"],
      "aeips" => ["sepia"], "abetu" => ["beaut"], "eepru" => ["rupee"],
      "fknuy" => ["funky"], "adekr" => ["drake"], "eippr" => ["piper"],
      "bdelu" => ["lubed"], "ehrtz" => ["hertz"], "hssuy" => ["hussy"],
      "achit" => ["aitch"], "adinr" => ["dinar", "nadir"], "llsuu" => ["lulus"],
      "inqtu" => ["quint"], "adefx" => ["faxed"], "beklo" => ["bloke"],
      "hinwy" => ["whiny"], "ahpsw" => ["pshaw"], "bortu" => ["turbo"],
      "ablwy" => ["bylaw"], "cehtv" => ["vetch"], "gimoz" => ["gizmo"],
      "gilns" => ["lings"], "acnot" => ["canto"], "abder" => ["debar"],
      "accuy" => ["yucca"], "bceks" => ["becks"], "acrsw" => ["craws"],
      "alpsy" => ["palsy", "splay"], "fimtu" => ["mufti"], "dggoy" => ["doggy"],
      "abiit" => ["tibia"], "dilos" => ["lidos"], "eisss" => ["sises"],
      "allot" => ["atoll"], "ilmns" => ["limns"], "eiqru" => ["quire"],
      "beell" => ["belle"], "eklln" => ["knell"], "cdeor" => ["credo", "decor"],
      "ilppy" => ["lippy"], "giors" => ["giros"], "aeprt" => ["prate"],
      "hills" => ["shill"], "ginps" => ["pings"], "aciil" => ["cilia"],
      "emosy" => ["mosey"], "nntuy" => ["tunny"], "iknop" => ["pinko"],
      "osstw" => ["swots"], "closy" => ["cloys"], "goprs" => ["sprog"],
      "ehklw" => ["whelk"], "oprsy" => ["prosy"], "klnop" => ["plonk"],
      "abfrs" => ["barfs"], "gpsyy" => ["gypsy"], "cmors" => ["corms"],
      "lprsu" => ["purls", "slurp"], "cegko" => ["gecko"], "ffirs" => ["riffs"],
      "bgnoo" => ["bongo"], "elopr" => ["prole"], "aaegt" => ["agate"],
      "eilsx" => ["lexis"], "diqsu" => ["quids"], "eehsx" => ["hexes"],
      "ddeio" => ["diode"], "elltu" => ["tulle"], "acost" => ["ascot"],
      "aabcl" => ["cabal"], "cipss" => ["spics"], "ikpsy" => ["spiky"],
      "cruvy" => ["curvy"], "efnry" => ["ferny"], "aagmm" => ["magma"],
      "dippy" => ["dippy"], "denrs" => ["nerds"], "oosuz" => ["ouzos"],
      "cenov" => ["coven"], "aoowz" => ["wazoo"], "degim" => ["midge"],
      "acdel" => ["decal"], "erstw" => ["trews"], "hlorw" => ["whorl"],
      "belmu" => ["umbel"], "diilp" => ["lipid"], "cekor" => ["ocker"],
      "impwy" => ["wimpy"], "aehlw" => ["wheal"], "eopss" => ["pesos", "posse"],
      "ckops" => ["pocks"], "cimpr" => ["crimp"], "bdelo" => ["lobed"],
      "cdeiy" => ["dicey"], "deksy" => ["dykes"], "aahjr" => ["rajah"],
      "dhisy" => ["dishy"], "eilpx" => ["pixel"], "ikllr" => ["krill"],
      "nnosy" => ["sonny"], "abkru" => ["burka"], "bnnoy" => ["bonny"],
      "acnst" => ["cants"], "acprs" => ["scarp", "craps"], "cdors" => ["scrod"],
      "enrru" => ["rerun"], "agnou" => ["guano"], "aabil" => ["labia"],
      "acerr" => ["carer"], "beorw" => ["bower"], "cjnou" => ["junco"],
      "demru" => ["demur"], "agnpr" => ["prang"], "egijr" => ["rejig"],
      "bijou" => ["bijou"], "lostu" => ["louts"], "aluvv" => ["vulva"],
      "eerss" => ["seers"], "eeopt" => ["topee"], "affgs" => ["gaffs"],
      "bdeny" => ["bendy"], "aertt" => ["tater"], "eorsw" => ["sower"],
      "degow" => ["wodge"], "abgls" => ["blags"], "denoy" => ["doyen"],
      "bbboy" => ["bobby"], "ablos" => ["bolas"], "eimss" => ["semis"],
      "inpuz" => ["unzip"], "aaqsu" => ["aquas"], "aadmn" => ["adman"],
      "einvx" => ["vixen"], "accem" => ["mecca"], "aelnv" => ["venal"],
      "alsuu" => ["luaus"], "aehnt" => ["neath"], "aelps" => ["sepal"],
      "anvvy" => ["navvy"], "abcor" => ["carob"], "denry" => ["nerdy"],
      "chhoo" => ["hooch"], "illos" => ["lilos"], "egilt" => ["legit"],
      "cgioy" => ["yogic"], "himss" => ["shims"], "ccino" => ["conic"],
      "hmrry" => ["myrrh"], "hlpsy" => ["sylph"], "eekst" => ["skeet"],
      "ceovy" => ["covey"], "ahpry" => ["harpy"], "ityzz" => ["tizzy"],
      "begmu" => ["begum"], "eirst" => ["resit"], "aikmu" => ["umiak"],
      "efgor" => ["gofer"], "aabmm" => ["mamba"], "llmos" => ["molls"],
      "begio" => ["bogie"], "ckmuy" => ["mucky"], "adewy" => ["yawed"],
      "bggoy" => ["boggy"], "cdeno" => ["coned"], "abccy" => ["baccy"],
      "alpsw" => ["pawls"], "lpsuu" => ["lupus"], "ffost" => ["toffs"],
      "bhmpu" => ["bumph"], "eoprt" => ["trope"], "dilly" => ["dilly", "idyll"],
      "abdrs" => ["brads"], "akmuz" => ["muzak"], "ceitu" => ["cutie"],
      "amory" => ["moray"], "ackow" => ["wacko"], "ffims" => ["miffs"],
      "ahkns" => ["ankhs", "hanks", "khans", "shank"], "eegrt" => ["egret"],
      "efstw" => ["wefts"], "adisw" => ["wadis"], "bemrs" => ["berms"],
      "hissu" => ["sushi"], "eerst" => ["ester"], "kopry" => ["porky"],
      "ejosy" => ["joeys"], "acopr" => ["copra"], "aagjn" => ["ganja"],
      "aegrz" => ["gazer"], "afhst" => ["hafts"], "dlosw" => ["wolds"],
      "aerty" => ["teary"], "eopsx" => ["poxes", "expos"], "eiksv" => ["skive"],
      "aelrv" => ["velar"], "acmor" => ["carom", "macro"], "irtyz" => ["ritzy"],
      "ckrsu" => ["rucks"], "binru" => ["bruin"], "allno" => ["llano"],
      "egorr" => ["reorg", "roger"],
      "aerst" => ["resat", "aster", "tares", "taser"], "aalss" => ["salsa"],
      "eloss" => ["sloes"], "moprt" => ["tromp"], "aaftw" => ["fatwa"],
      "cenop" => ["ponce"], "bepsu" => ["pubes"], "ddimy" => ["middy"],
      "deehx" => ["hexed"], "aekps" => ["spake"], "eopsy" => ["poesy"],
      "inopr" => ["prion"], "alnoz" => ["zonal"], "cllsu" => ["scull"],
      "hhmpu" => ["humph"], "amrst" => ["trams"], "eelnw" => ["newel"],
      "llloy" => ["lolly"], "aintt" => ["titan"], "egors" => ["goers", "gorse"],
      "bdrsu" => ["drubs"], "imnty" => ["minty"], "aeffg" => ["gaffe"],
      "chmop" => ["chomp"], "benor" => ["boner"], "elotw" => ["owlet"],
      "actty" => ["catty"], "ceers" => ["scree"], "mmmoy" => ["mommy"],
      "kkoos" => ["kooks"], "delow" => ["dowel"], "jlosw" => ["jowls"],
      "dhowy" => ["howdy"], "cenno" => ["nonce"], "eisst" => ["sties"],
      "acepy" => ["pacey"], "aaegp" => ["agape"], "adrsw" => ["sward"],
      "bemsu" => ["sebum"], "hknoy" => ["honky"], "ennox" => ["xenon"],
      "aastv" => ["avast"], "addfy" => ["faddy"], "deiin" => ["indie"],
      "allwy" => ["wally"], "aiprt" => ["tapir"], "ehint" => ["thine"],
      "dikny" => ["dinky"], "ioqtu" => ["quoit"], "dssuy" => ["sudsy"],
      "aclxy" => ["calyx"], "kkuyy" => ["yukky"], "eegky" => ["geeky"],
      "aprry" => ["parry"], "aelsw" => ["wales", "weals"], "gnops" => ["pongs"],
      "aemrr" => ["rearm"], "annos" => ["anons"], "cikos" => ["sicko"],
      "hkmou" => ["hokum"], "abimt" => ["ambit"], "akmor" => ["korma"],
      "aimsw" => ["swami"], "kmrsu" => ["murks"], "apsty" => ["patsy"],
      "addry" => ["dryad"], "ensux" => ["nexus"], "ekost" => ["tokes"],
      "ipssv" => ["spivs"], "eopst" => ["pesto"], "hopsy" => ["hypos"],
      "eemot" => ["emote"], "footy" => ["footy"], "bcmoo" => ["combo"],
      "fgguy" => ["fuggy"], "inosw" => ["winos"], "oprst" => ["strop"],
      "copru" => ["croup"], "eeerv" => ["reeve"], "acder" => ["cadre"],
      "achsw" => ["schwa"], "cccio" => ["cocci"], "eehrw" => ["hewer"],
      "abstu" => ["abuts"], "deilo" => ["oldie"], "hnoow" => ["nohow"],
      "einpy" => ["piney"], "aggin" => ["nigga"], "bflyy" => ["flyby"],
      "aeeir" => ["aerie"], "ehmny" => ["hymen"], "aepty" => ["peaty"],
      "einsx" => ["nixes"], "biost" => ["obits"], "acdlu" => ["ducal"],
      "agruu" => ["augur"], "eilrt" => ["tiler"], "deenu" => ["endue"],
      "ainpt" => ["inapt"], "bdmou" => ["dumbo"], "aeppu" => ["pupae"],
      "eikks" => ["kikes"], "fikns" => ["finks"], "aguyz" => ["gauzy"],
      "aeflr" => ["feral"], "cerst" => ["certs"], "cknos" => ["conks"],
      "aeltt" => ["latte"], "efrry" => ["fryer"], "cdeei" => ["deice"],
      "dersy" => ["dyers"], "delos" => ["lodes"], "aahlo" => ["aloha"],
      "aknsy" => ["snaky"], "bghit" => ["bight"], "ahlpy" => ["phyla"],
      "abqru" => ["burqa"], "abmry" => ["barmy"], "aartt" => ["attar"],
      "muyzz" => ["muzzy"], "kltuz" => ["klutz"], "eilns" => ["liens"],
      "fosty" => ["softy"], "eopps" => ["popes"], "dmors" => ["dorms"],
      "aagll" => ["algal"], "bdemo" => ["demob"], "aapst" => ["tapas"],
      "beost" => ["besot"], "adelz" => ["lazed"], "firzz" => ["frizz"],
      "delsu" => ["slued"], "eorrw" => ["rower"], "dehoo" => ["oohed"],
      "cinru" => ["runic"], "beimu" => ["imbue"], "adhrs" => ["shard"],
      "cdeeu" => ["deuce"], "almoy" => ["loamy"], "acfkl" => ["flack"],
      "innpu" => ["unpin"], "binox" => ["inbox"], "aimms" => ["imams"],
      "adgos" => ["dagos"], "biimn" => ["nimbi"], "cfort" => ["croft"],
      "ejmmy" => ["jemmy"], "eksty" => ["tykes"], "eoqtu" => ["toque"],
      "fgirs" => ["frigs"], "aacmw" => ["macaw"], "eiksy" => ["yikes"],
      "iopst" => ["posit"], "adelr" => ["alder"], "ddiko" => ["kiddo"],
      "loott" => ["lotto"], "appsy" => ["sappy"], "adilr" => ["laird"],
      "efhst" => ["hefts"], "eimox" => ["moxie"], "asttw" => ["twats"],
      "hopsw" => ["whops"], "finny" => ["finny"], "hmsuu" => ["humus"],
      "bikls" => ["bilks"], "eiorv" => ["vireo"], "aeenr" => ["ranee"],
      "cnoos" => ["coons"], "cceer" => ["recce"], "ddnoy" => ["noddy"],
      "ittty" => ["titty"], "ciost" => ["stoic"], "anosx" => ["axons"],
      "diops" => ["dipso"], "cdeox" => ["coxed", "codex"], "errty" => ["terry"],
      "degio" => ["dogie"], "aemny" => ["meany"], "abely" => ["belay"],
      "acgno" => ["conga"], "belsu" => ["lubes"], "adlno" => ["nodal"],
      "abbcy" => ["cabby"], "fkluy" => ["fluky"], "bstuy" => ["busty"],
      "adhry" => ["hydra"], "delms" => ["melds"], "dekot" => ["toked"],
      "abbgy" => ["gabby"], "adelw" => ["waled"], "ellwy" => ["welly"],
      "bipsu" => ["pubis"], "chilm" => ["milch"], "adgno" => ["gonad"],
      "adepv" => ["vaped"], "hjnos" => ["johns"], "bffis" => ["biffs"],
      "beegt" => ["beget"], "afnny" => ["fanny"], "amoru" => ["amour"],
      "dnosy" => ["synod"], "aelsz" => ["lazes"], "eegil" => ["liege"],
      "ddilo" => ["dildo"], "enort" => ["toner"], "abnru" => ["unbar"],
      "afost" => ["fatso"], "abemr" => ["bream"], "ejlpu" => ["julep"],
      "gnnuy" => ["gunny"], "krssu" => ["rusks"], "ahpst" => ["staph"],
      "aknry" => ["narky"], "aflou" => ["afoul"], "aiptt" => ["pitta"],
      "illtw" => ["twill"], "elouv" => ["ovule"], "giprs" => ["prigs"],
      "eenwy" => ["weeny"], "estux" => ["tuxes"], "egptu" => ["getup"],
      "addel" => ["addle"], "aenwx" => ["waxen"], "eqtuu" => ["tuque"],
      "ehkoy" => ["hokey"], "aemsy" => ["samey", "seamy"], "cchko" => ["chock"],
      "akooz" => ["kazoo"], "iiksw" => ["wikis"], "inpsy" => ["spiny"],
      "bttuy" => ["butty"], "elosv" => ["voles"], "efruz" => ["furze"],
      "aehks" => ["hakes"], "gmpyy" => ["pygmy"], "ceeem" => ["emcee"],
      "bekrs" => ["berks"], "anorw" => ["rowan"], "aamnn" => ["manna"],
      "ehort" => ["throe"], "abens" => ["banes"], "ablot" => ["bloat"],
      "hmrtu" => ["thrum"], "ijost" => ["joist"], "abcrs" => ["carbs"],
      "cklno" => ["clonk"], "agmmy" => ["gammy"], "ellty" => ["telly"],
      "bboos" => ["boobs"], "cikms" => ["micks"], "acenr" => ["nacre"],
      "agssy" => ["gassy"], "aortt" => ["tarot"], "chmoo" => ["mooch"],
      "hknuy" => ["hunky"], "divvy" => ["divvy"], "abjot" => ["jabot"],
      "bbsuy" => ["busby"], "jostu" => ["joust"], "cerss" => ["cress"],
      "celoy" => ["coley"], "agnty" => ["tangy"], "beery" => ["beery"],
      "aimty" => ["amity"], "ampss" => ["spams"], "delsv" => ["velds"],
      "ffiks" => ["skiff"], "eimor" => ["moire"], "aghtu" => ["aught"],
      "annny" => ["nanny"], "agilr" => ["grail"], "chsuy" => ["cushy"],
      "bemru" => ["umber"], "aenrr" => ["reran"], "aepss" => ["apses"],
      "beelp" => ["plebe", "bleep"], "eegks" => ["geeks"], "bddiy" => ["biddy"],
      "almpy" => ["palmy"], "glmou" => ["mogul"], "ghitw" => ["wight"],
      "klnpu" => ["plunk"], "deeff" => ["effed"], "adrsy" => ["drays"],
      "acmsu" => ["sumac"], "llsyy" => ["slyly"], "deiiv" => ["ivied"],
      "cpssu" => ["cusps"], "eersw" => ["ewers"], "aaegv" => ["agave"],
      "emozz" => ["mezzo"], "ahmsw" => ["whams"], "begin" => ["binge"],
      "loops" => ["sloop"], "gmpru" => ["grump"], "cenos" => ["scone"],
      "deegs" => ["sedge"], "enost" => ["steno"], "aabem" => ["abeam"],
      "impps" => ["pimps"], "begrs" => ["bergs"], "fhirt" => ["firth"],
      "acdhr" => ["chard"], "aepst" => ["septa"], "ahhss" => ["shahs"],
      "eekop" => ["pekoe"], "ddiru" => ["druid"], "aloss" => ["lasso"],
      "ceiru" => ["curie"], "amotz" => ["matzo"], "aekpy" => ["peaky"],
      "adirt" => ["triad"], "anors" => ["roans", "sonar"], "begil" => ["bilge"],
      "adery" => ["deary"], "adehw" => ["hawed"], "bkssu" => ["busks"],
      "ghiny" => ["hying"], "ehlsw" => ["welsh"], "ehmst" => ["meths"],
      "agpsw" => ["gawps"], "ccikr" => ["crick"], "ahooy" => ["yahoo"],
      "akrst" => ["karts"], "deotx" => ["detox"], "aegis" => ["aegis"],
      "abels" => ["sable"], "enops" => ["pones"], "bgnos" => ["bongs"],
      "deilw" => ["wiled"], "afrst" => ["farts", "frats"], "ampsv" => ["vamps"],
      "aprst" => ["prats", "sprat", "tarps"], "eprst" => ["strep"],
      "bgluy" => ["bulgy"], "kmsuy" => ["musky"], "aakmr" => ["karma"],
      "ghlpy" => ["glyph"], "eilmr" => ["miler"], "llsuy" => ["sully"],
      "bcipu" => ["pubic"], "aagmn" => ["manga"], "aiqsu" => ["quasi"],
      "degil" => ["gelid"], "certu" => ["cruet"], "aggsy" => ["saggy"],
      "diotv" => ["divot"], "aditv" => ["davit"], "elmsw" => ["mewls"],
      "ejkoy" => ["jokey"], "bdeew" => ["dweeb"], "gortu" => ["grout"],
      "ahlst" => ["shalt"], "aeelt" => ["elate"], "boosz" => ["bozos"],
      "gorsy" => ["gyros"], "eehst" => ["thees"], "mmuyy" => ["yummy"],
      "abesu" => ["beaus"], "aabde" => ["baaed"], "epstu" => ["setup"],
      "epprs" => ["preps"], "inppu" => ["pinup"], "bimny" => ["nimby"],
      "dhiot" => ["dhoti"], "aefll" => ["fella"], "cfrsu" => ["scurf"],
      "ghost" => ["goths"], "beeps" => ["beeps"], "eorrt" => ["retro"],
      "aggor" => ["aggro"], "ceelr" => ["creel"], "achnt" => ["natch"],
      "agsty" => ["stagy"], "aahsw" => ["awash"], "ehmru" => ["rheum"],
      "iimns" => ["minis"], "aintw" => ["twain"], "ceirt" => ["trice"],
      "hirrs" => ["shirr"], "alnwy" => ["wanly"], "beirs" => ["biers"],
      "aehls" => ["shale"], "fnotu" => ["futon"], "cilst" => ["clits"],
      "eipst" => ["piste"], "eortt" => ["torte"], "eikpr" => ["piker"],
      "illwy" => ["willy"], "glnoo" => ["logon"], "achoo" => ["achoo"],
      "bceno" => ["bonce"], "cehkt" => ["ketch"], "eflty" => ["lefty"],
      "aglor" => ["largo"], "dikrs" => ["dirks"], "adejp" => ["japed"],
      "aaenp" => ["paean"], "abcsu" => ["scuba"], "knosw" => ["wonks"],
      "belps" => ["plebs"], "bbimo" => ["bimbo"], "adder" => ["adder"],
      "bchtu" => ["butch"], "eirrt" => ["trier"], "defiy" => ["edify"],
      "mssuy" => ["mussy"], "deknu" => ["nuked"], "fhors" => ["frosh"],
      "chiko" => ["hoick"], "begot" => ["begot"], "acdeg" => ["cadge"],
      "bceip" => ["bicep"], "aglss" => ["slags"], "eilov" => ["voile"],
      "ailss" => ["sisal"], "afilp" => ["pilaf"], "aprsy" => ["raspy"],
      "ahist" => ["saith"], "aehrt" => ["hater"], "aajnp" => ["japan"],
      "ddgoy" => ["dodgy"], "afist" => ["fiats"], "abqsu" => ["squab"],
      "eorsv" => ["verso", "servo", "roves"], "aehnn" => ["henna"],
      "ckuyy" => ["yucky"], "aosvy" => ["savoy"], "iippt" => ["pipit"],
      "aenst" => ["antes"], "aehrs" => ["rheas"], "aagrs" => ["ragas"],
      "beegr" => ["grebe"], "aafim" => ["mafia"], "gstuy" => ["gutsy"],
      "aemns" => ["manse"], "gilry" => ["girly"], "iknst" => ["skint"],
      "clmou" => ["locum"], "aefsv" => ["faves"], "dgirs" => ["girds"],
      "adipv" => ["vapid"], "clops" => ["clops"], "ahilp" => ["phial"],
      "ceirr" => ["crier"], "aersw" => ["wares"], "aefkr" => ["faker"],
      "einrv" => ["riven"], "denpw" => ["pwned"], "aehsy" => ["yeahs"],
      "gnoss" => ["snogs"], "ceitv" => ["civet"], "eilsw" => ["wiles"],
      "cdnoo" => ["condo"], "aanns" => ["naans"], "cimnu" => ["cumin"],
      "cenor" => ["recon", "crone"], "cenoz" => ["cozen"], "aeptu" => ["taupe"],
      "afffs" => ["faffs"], "ceott" => ["octet"], "efmru" => ["femur"],
      "birtu" => ["bruit"], "dehpy" => ["hyped"], "abikt" => ["batik"],
      "aersv" => ["avers"], "closu" => ["locus"], "isttw" => ["twits"],
      "dimos" => ["misdo"], "eeepw" => ["pewee"], "einnu" => ["ennui"],
      "cimor" => ["micro"], "acfkr" => ["frack"], "ablly" => ["bally"],
      "ailty" => ["laity"], "hortw" => ["wroth"], "bemos" => ["besom"],
      "eills" => ["lisle"], "anrst" => ["tarns"], "eorsu" => ["euros"],
      "abinr" => ["bairn"], "chilz" => ["zilch"], "beisv" => ["vibes"],
      "hoost" => ["sooth"], "airst" => ["astir", "sitar"], "dfjor" => ["fjord"],
      "abcer" => ["caber"], "eepwy" => ["weepy"], "bnoor" => ["boron"],
      "eerrs" => ["serer"], "billr" => ["brill"], "agglu" => ["gulag"],
      "demmo" => ["modem"], "ennot" => ["tenon"], "bersy" => ["byres"],
      "abims" => ["iambs"], "eejps" => ["jeeps"], "gostu" => ["gusto"],
      "aipst" => ["pitas"], "ghlou" => ["lough"], "acdtu" => ["ducat"],
      "elmru" => ["lemur"], "bbhuy" => ["hubby"], "cossw" => ["scows"],
      "clmop" => ["clomp"], "cmrsu" => ["scrum"], "ippyz" => ["zippy"],
      "akmou" => ["oakum"], "eegsv" => ["veges"], "chist" => ["chits"],
      "aders" => ["arsed"], "ilntu" => ["unlit"], "hoqtu" => ["quoth"],
      "antuv" => ["vaunt"], "dkory" => ["dorky"], "aessx" => ["saxes"],
      "abhis" => ["sahib"], "ginot" => ["ingot"], "egluy" => ["gluey"],
      "abmru" => ["rumba"], "giinp" => ["piing"], "rstty" => ["tryst"],
      "cnstu" => ["cunts"], "eimrs" => ["rimes"], "agort" => ["gator", "argot"],
      "cdipu" => ["cupid"], "ginsz" => ["zings"], "ffiqu" => ["quiff"],
      "hhssu" => ["shush"], "knosy" => ["yonks"], "dnoor" => ["rondo"],
      "ansty" => ["antsy", "tansy"], "foprs" => ["profs"], "almsu" => ["alums"],
      "aghno" => ["hogan"], "aelnr" => ["renal"], "cnopy" => ["poncy"],
      "einss" => ["sines"], "bevvy" => ["bevvy"], "aekno" => ["oaken"],
      "aeptx" => ["expat"], "hisst" => ["shits"], "anosv" => ["novas"],
      "beelt" => ["betel"], "ehlpw" => ["whelp"], "dkors" => ["dorks"],
      "abbno" => ["nabob"], "eisty" => ["yetis"], "aacep" => ["apace"],
      "ehlot" => ["helot"], "celsw" => ["clews"], "einsz" => ["zines"],
      "aghss" => ["shags"], "ceosx" => ["coxes"], "aegmr" => ["marge"],
      "ijkns" => ["jinks"], "histw" => ["whist", "whits"], "eilps" => ["spiel"],
      "agott" => ["gotta"], "cchos" => ["chocs"], "mpssu" => ["sumps"],
      "aabft" => ["abaft"], "closw" => ["cowls"], "opstu" => ["stoup"],
      "aenot" => ["oaten"], "aemrt" => ["mater"], "coost" => ["coots"],
      "dlost" => ["dolts"], "aabhs" => ["abash"], "cehnw" => ["wench"],
      "bitty" => ["bitty"], "eikrt" => ["trike"], "aegrs" => ["sarge"],
      "eepsv" => ["veeps"], "hlopx" => ["phlox"], "abuzz" => ["abuzz"],
      "deosw" => ["dowse"], "enrst" => ["terns"], "efilr" => ["lifer"],
      "elmxy" => ["xylem"], "iknos" => ["oinks"], "eekps" => ["pekes"],
      "dimou" => ["odium"], "emntu" => ["unmet"], "cnssy" => ["syncs"],
      "bgiln" => ["bling"], "adgrs" => ["grads"], "aeknv" => ["knave"],
      "aderr" => ["drear"], "efrss" => ["serfs"], "emprs" => ["perms"],
      "aassy" => ["assay"], "aelst" => ["teals"], "ilstt" => ["stilt"]}
    |> Map.get(string_id)
  end
end
