defmodule Jumble.ScowlDict.Large.Length4 do
  def get(string_id) do
    %{"arss" => ["sars"], "aeko" => ["koae"], "grsu" => ["grus", "gurs"],
      "hstu" => ["hust"], "eilw" => ["weli", "wiel", "weil", "lwei"],
      "iixx" => ["xxii"], "ptyy" => ["typy"], "diiv" => ["divi"],
      "akln" => ["klan"], "ccor" => ["croc"], "muzz" => ["muzz"],
      "ipru" => ["puir", "puri"], "intw" => ["wint"], "cfis" => ["fisc"],
      "abfs" => ["fabs"], "adkn" => ["kand"], "bruz" => ["zubr"],
      "gnos" => ["gons", "nogs"], "eflo" => ["fole"], "aiqr" => ["iraq"],
      "msty" => ["myst"], "aamy" => ["amay", "yama", "maya"], "dilv" => ["vild"],
      "celm" => ["clem"], "cils" => ["scil"], "adip" => ["padi"],
      "abuy" => ["yabu"], "aklo" => ["kalo", "loka", "kola"],
      "aluv" => ["uval", "ulva"], "gguu" => ["gugu"], "efhp" => ["efph"],
      "airr" => ["arri"], "arsu" => ["saur", "usar", "rusa", "ursa", "sura"],
      "imps" => ["mips", "simp"], "dhow" => ["whod"], "fiks" => ["fisk", "kifs"],
      "deho" => ["ohed"], "beky" => ["byke"], "llvv" => ["vvll"],
      "dehs" => ["edhs"], "hory" => ["hory"], "eipt" => ["epit", "tipe", "piet"],
      "apsu" => ["apsu", "apus", "supa", "upas"], "aegv" => ["vage", "vega"],
      "deei" => ["eide"], "agms" => ["gams"], "ccem" => ["eccm"],
      "eoor" => ["oreo"], "aasv" => ["avas", "vasa"], "cdhi" => ["dich"],
      "dhnu" => ["hund"], "immo" => ["momi"],
      "enor" => ["nore", "reno", "oner", "rone"], "lnou" => ["loun", "noul"],
      "ghuv" => ["vugh"], "aaei" => ["iaea"], "ilmp" => ["pilm", "plim"],
      "ksuy" => ["kyus"], "hhwy" => ["yhwh"], "denz" => ["zend"],
      "erss" => ["sers"], "esss" => ["sess"], "disu" => ["iuds", "suid"],
      "aptu" => ["patu", "paut", "tapu"], "aciv" => ["vica"], "adou" => ["doua"],
      "aacw" => ["waac"], "aept" => ["peta", "teap", "tepa"],
      "ceht" => ["tche", "echt"], "gstu" => ["stug"], "cfot" => ["coft"],
      "nswy" => ["wyns"], "nnor" => ["norn"], "amnx" => ["manx"],
      "dddo" => ["dodd"], "agmo" => ["ogam"], "eilt" => ["itel", "teli", "teil"],
      "ikkr" => ["rikk"], "iikp" => ["piki"], "bisv" => ["vibs"],
      "cfoo" => ["coof"], "mmpu" => ["mump"], "fhik" => ["fikh"],
      "nrru" => ["nurr"], "ggnu" => ["gung"], "drru" => ["durr"],
      "cefk" => ["feck"], "cott" => ["cott"], "hoqs" => ["shoq"],
      "eikr" => ["reik", "keir", "kier"], "acin" => ["inca", "cain"],
      "aesy" => ["eyas"], "acwy" => ["ywca"], "afir" => ["fiar"],
      "ehil" => ["hile", "elhi", "heil", "heli"], "aakv" => ["kava"],
      "amop" => ["mapo"], "agiz" => ["gazi", "giza"], "acuv" => ["cavu"],
      "aeht" => ["thea", "eath", "thae"], "girs" => ["gris"],
      "cory" => ["croy", "cory"], "cenu" => ["unce"], "ahtu" => ["utah", "haut"],
      "ekls" => ["skel", "leks"], "achp" => ["caph"], "hirs" => ["shir", "shri"],
      "kosw" => ["kows"], "elos" => ["leos", "oles"], "efmr" => ["ferm"],
      "eert" => ["reet", "rete"], "aikn" => ["ikan", "naik", "kain", "kina"],
      "dntu" => ["tund", "dunt"], "hirt" => ["thir"], "akry" => ["yark", "kyar"],
      "akwy" => ["waky"], "ceir" => ["icer"], "anst" => ["nast", "nats", "sant"],
      "drsu" => ["ruds", "urds", "surd"], "emos" => ["meso", "moes", "mose"],
      "emow" => ["mowe"], "dhku" => ["khud"], "ceor" => ["cero"],
      "emmr" => ["mrem"], "ahst" => ["tash"], "einu" => ["unie"],
      "aeor" => ["orae", "aero"], "efly" => ["fyle", "fley"], "biru" => ["buri"],
      "acop" => ["acop", "copa", "paco", "capo"], "fkot" => ["koft"],
      "clop" => ["colp"], "hily" => ["hyli"],
      "amos" => ["amos", "soam", "moas", "soma"], "fors" => ["fros", "orfs"],
      "amrx" => ["marx"], "deht" => ["thed"], "abbd" => ["dabb"],
      "bmsu" => ["bmus"], "akmw" => ["mawk"], "egst" => ["steg", "tegs", "gest"],
      "iklo" => ["koil", "loki"], "addu" => ["daud", "duad"], "beey" => ["byee"],
      "amsy" => ["mays"], "bior" => ["bori", "biro", "brio"],
      "aelt" => ["atle", "laet", "leat", "tela", "tael"], "fiky" => ["fiky"],
      "amps" => ["pams", "samp"], "aino" => ["aion", "naio", "naoi"],
      "ehst" => ["seth", "eths", "shet", "hest"], "biss" => ["sibs"],
      "insv" => ["vins"], "antw" => ["nawt", "tawn"], "bhty" => ["byth"],
      "isyz" => ["sizy"], "diis" => ["sidi"], "ajku" => ["jauk"],
      "eils" => ["seil", "sile"], "emsy" => ["emys"], "filr" => ["flir"],
      "ajps" => ["japs", "jasp"], "ahos" => ["osha", "hoas"], "inrt" => ["trin"],
      "ekst" => ["kest", "sekt", "sket", "kets"], "dhiy" => ["hidy"],
      "acio" => ["icao"], "chiz" => ["chiz"], "ghpu" => ["pugh"],
      "dims" => ["mids"], "arsw" => ["raws"], "losy" => ["loys"],
      "efgs" => ["fegs"], "ilot" => ["ilot", "loti"], "dosy" => ["sody", "yods"],
      "mnsu" => ["snum", "muns"], "dpst" => ["ptsd"], "aemx" => ["amex"],
      "eezz" => ["zeze"], "gisu" => ["sugi"], "ajwy" => ["jawy"],
      "ssuu" => ["susu"], "emrs" => ["rems"], "ftuy" => ["yuft"],
      "fnoo" => ["fono", "foon"],
      "efis" => ["fise", "sife", "feis", "fies", "seif"], "gmoo" => ["mogo"],
      "jluy" => ["july"], "adnu" => ["danu", "daun", "nuda", "unda", "duan"],
      "enpy" => ["pyne"], "loot" => ["loto"], "ahtw" => ["wath"],
      "aitz" => ["tiza", "zati"], "cinr" => ["crin"], "dotu" => ["dout"],
      "mrru" => ["murr"], "gnpu" => ["pung"], "aklr" => ["kral"],
      "efuy" => ["fuye"], "lnuy" => ["luny"], "fntu" => ["funt"],
      "aahm" => ["maha", "amah"], "ceps" => ["psec", "ceps"], "epqu" => ["quep"],
      "afrz" => ["zarf"], "ortw" => ["rowt", "trow", "wort"],
      "dnos" => ["sond", "snod"], "efkr" => ["ferk", "kerf"], "afft" => ["afft"],
      "adeo" => ["odea"], "deem" => ["mede", "deme", "meed"], "mptu" => ["tump"],
      "arwy" => ["wray"], "eftu" => ["fute"], "ellv" => ["vell"],
      "ahou" => ["oahu"], "ffuu" => ["fufu"], "ggoo" => ["gogo", "goog"],
      "ammu" => ["ammu", "umma"], "ansy" => ["nyas"], "iklw" => ["wilk"],
      "inop" => ["pino", "pion"], "cdrw" => ["crwd"], "akmr" => ["kram"],
      "hrtu" => ["urth", "ruth"], "aikp" => ["paik", "pika"],
      "hiko" => ["hoik", "hoki"], "bffo" => ["boff"], "djuy" => ["judy"],
      "chwy" => ["wych"], "akky" => ["kyak"], "tuzz" => ["tuzz"],
      "aght" => ["gath", "ghat"], "agsy" => ["sagy", "yags"], "ituw" => ["tuwi"],
      "cfms" => ["scfm"], "dorw" => ["drow"], "eejl" => ["jeel"],
      "eims" => ["sime"], "aacl" => ["alca"], "ceiy" => ["ycie"],
      "afkw" => ["wakf"], "fmuy" => ["fumy"], "aqtu" => ["quat"],
      "akno" => ["kona", "nako", "kaon", "koan"], "innw" => ["winn"],
      "pstu" => ["sput", "tups"], "aagj" => ["jaga"], "ooty" => ["toyo"],
      "psst" => ["psts"], "jkuu" => ["juku"], "actu" => ["actu"],
      "noos" => ["oons"], "dlsu" => ["slud", "suld", "luds"],
      "mosw" => ["sowm", "swom"], "gsty" => ["tygs"], "celt" => ["celt"],
      "ffpt" => ["pfft"], "aadv" => ["vaad", "vada"],
      "eegr" => ["geer", "gere", "gree"], "desy" => ["deys", "syed"],
      "alov" => ["vola"], "ekos" => ["okes", "skeo", "soke"],
      "anot" => ["nato", "nota"], "aalv" => ["aval"], "eelm" => ["leme"],
      "hmtu" => ["muth"], "clno" => ["locn", "clon"], "aehr" => ["hera"],
      "bgin" => ["bing"], "beju" => ["jube"], "agju" => ["juga"],
      "bdei" => ["dieb"], "mrtu" => ["turm"], "asyy" => ["yays"],
      "cdeo" => ["ecod", "deco"], "girr" => ["girr"], "aluy" => ["yalu"],
      "cgku" => ["guck"], "aiip" => ["apii"], "loos" => ["oslo", "sloo", "sool"],
      "lmos" => ["olms", "mols"], "egir" => ["geir", "gire"], "adry" => ["adry"],
      "hilo" => ["holi"], "diov" => ["ovid"], "ekrz" => ["zerk"],
      "epsu" => ["supe", "spue"], "akos" => ["asok", "soka", "koas", "okas"],
      "mopy" => ["yomp"], "fgio" => ["figo"], "gimn" => ["ming"],
      "cipy" => ["pyic"], "efrs" => ["fers"],
      "anru" => ["naur", "uran", "urna", "raun"], "bjoo" => ["bojo", "jobo"],
      "bboo" => ["bobo"], "anpu" => ["napu", "puan", "puna"], "dhuw" => ["whud"],
      "clpu" => ["culp"], "aint" => ["aint", "inta", "tain"], "oopy" => ["yoop"],
      "adep" => ["depa", "peda"], "emou" => ["moue"], "belo" => ["bleo"],
      "deis" => ["deis", "desi", "ised"], "delo" => ["elod", "odel"],
      "abep" => ["peba"], "akpp" => ["kapp"], "ikor" => ["irok", "kori"],
      "dijn" => ["djin"], "bdeu" => ["bude", "bedu"], "abff" => ["baff"],
      "ehnr" => ["hern"], "cegt" => ["ctge"],
      "abir" => ["abir", "bari", "rabi", "abri"], "adgu" => ["gaud"],
      "aaip" => ["apia"], "lnru" => ["nurl"], "imot" => ["itmo", "moit"],
      "empy" => ["ympe"], "hist" => ["isth", "tshi", "sith"],
      "nort" => ["ront", "tron"], "bssy" => ["byss"],
      "aeps" => ["pesa", "pase", "spae"], "ahsy" => ["yahs", "shay"],
      "iiix" => ["xiii"], "beel" => ["elbe", "blee"], "irst" => ["rist", "rits"],
      "admn" => ["mand"], "mstu" => ["stum", "muts"], "hipz" => ["phiz"],
      "cehp" => ["pech"], "clow" => ["clow"], "diit" => ["tidi"],
      "ekmr" => ["merk"], "elot" => ["leto", "lote", "tole"],
      "aagw" => ["awag", "waag"], "duuw" => ["wudu"], "anuy" => ["anyu"],
      "eppr" => ["repp"], "abds" => ["bads"], "nooz" => ["zoon"],
      "ditt" => ["ditt"], "beow" => ["bowe"], "huwz" => ["whuz"],
      "elpw" => ["plew"], "noov" => ["novo"], "cefi" => ["fice"],
      "dnoy" => ["ondy", "yond"], "chnu" => ["chun"], "aguy" => ["yuga"],
      "ahrr" => ["harr"], "ehhs" => ["hehs"], "elms" => ["mels"],
      "akls" => ["lask", "skal", "laks"], "cceo" => ["ecco"], "hopt" => ["toph"],
      "biot" => ["boti", "bito"], "acht" => ["acth", "cath", "tach"],
      "adno" => ["adon", "dona"], "bety" => ["ybet"], "emmy" => ["emmy"],
      "aajm" => ["jama", "maja"], "akuw" => ["wauk"], "aegs" => ["gaes"],
      "aksw" => ["kaws", "skaw"], "defo" => ["feod"], "gilt" => ["glit"],
      "doru" => ["drou", "ordu", "roud", "duro"], "ceku" => ["cuke"],
      "eopp" => ["epop", "pepo"], "eept" => ["pete", "tepe"], "kouz" => ["zouk"],
      "jnou" => ["juno"], "imxy" => ["mixy"], "adop" => ["apod", "dopa"],
      "agrv" => ["grav"], "eiqr" => ["qeri"], "admu" => ["maud", "duma"],
      "gooz" => ["zogo"], "dixy" => ["dixy"], "abgy" => ["gaby"],
      "aeox" => ["oxea"], "biit" => ["biti"], "emop" => ["pome"],
      "aknt" => ["kant"], "abft" => ["baft"], "cety" => ["cyte"],
      "iltz" => ["litz"], "ilop" => ["poil"], "eqtu" => ["quet"],
      "acpw" => ["pwca"], "osss" => ["soss"], "blru" => ["burl"],
      "eiru" => ["iure"], "einx" => ["nixe"], "dkru" => ["kurd"],
      "istz" => ["sitz"], "efhs" => ["fehs"], "glor" => ["glor"],
      "aikr" => ["ikra", "irak", "raik", "raki"],
      "aelm" => ["alem", "amel", "alme", "leam", "mela"], "ehmt" => ["meth"],
      "egnt" => ["teng"], "adtu" => ["daut"], "blry" => ["byrl"],
      "gopr" => ["gorp"], "hhop" => ["phoh"], "cilv" => ["cliv"],
      "agmu" => ["guam", "muga", "gaum"], "aoop" => ["pooa"], "llry" => ["llyr"],
      "jmnu" => ["munj"], "delt" => ["delt", "teld"], "achm" => ["cham"],
      "afks" => ["kafs"], "lmsu" => ["lums"], "aotx" => ["toxa"],
      "dlou" => ["ould"], "eirs" => ["eris", "ries", "sier", "ires", "seir"],
      "bemw" => ["wemb"], "hpru" => ["pruh"], "aaly" => ["alay"],
      "iisw" => ["iwis"], "dhny" => ["hynd"], "ilos" => ["siol"],
      "bdnu" => ["bund"], "losw" => ["sowl"], "fikr" => ["firk"],
      "gilm" => ["glim"], "eeqr" => ["qere"], "allu" => ["ulla"],
      "gimp" => ["gimp"], "kkno" => ["konk"], "aesw" => ["waes", "wase"],
      "aoss" => ["ossa"], "blou" => ["boul"], "ehko" => ["okeh", "hoke"],
      "aipu" => ["piua"], "boty" => ["toby"], "aduw" => ["dauw"],
      "eeny" => ["eyen", "eyne"], "klnu" => ["lunk"], "eghi" => ["eigh"],
      "einv" => ["nevi"], "fisu" => ["sufi"], "alru" => ["laur", "lura", "ural"],
      "annr" => ["rann"], "abch" => ["chab", "bach"],
      "ailn" => ["alin", "lina", "anil"], "gotu" => ["toug"], "fort" => ["frot"],
      "agpr" => ["prag"], "ekpy" => ["pyke"], "eilr" => ["leir", "lier", "riel"],
      "cdsu" => ["ducs"], "krsy" => ["skry", "skyr"],
      "ades" => ["daes", "dase", "deas", "sade"], "ooss" => ["soso"],
      "adgi" => ["gadi", "gaid", "igad"], "eotw" => ["wote"], "eknp" => ["penk"],
      "cdno" => ["cond"], "cksu" => ["cusk"], "fosw" => ["sowf"],
      "prsv" => ["rsvp"], "gips" => ["psig", "spig"], "nopw" => ["pown"],
      "lxxx" => ["lxxx"], "apru" => ["rupa", "prau"], "ciru" => ["cuir"],
      "aegw" => ["waeg"], "kouy" => ["youk", "yuko"], "aeiv" => ["avie"],
      "ailz" => ["liza", "zila"], "ipst" => ["pist"], "desv" => ["devs"],
      "ainr" => ["arni", "iran", "airn"], "eouz" => ["ouze"], "aajp" => ["jaap"],
      "cmpu" => ["cump"], "iint" => ["inti"], "deev" => ["deve", "deev"],
      "abin" => ["bain", "naib"], "dirw" => ["wird"], "bglu" => ["glub"],
      "aejn" => ["jena", "jane", "jean"], "bhor" => ["borh"],
      "ahop" => ["paho", "poha", "opah"], "ainn" => ["anni", "nina", "nain"],
      "lnnu" => ["lunn"], "koop" => ["pook"], "aagu" => ["agua"],
      "aacs" => ["casa"], "aopt" => ["pato"], "afhk" => ["khaf"],
      "ciot" => ["cito", "coit", "otic"],
      "adis" => ["dasi", "dias", "disa", "sadi", "sida"],
      "aclo" => ["alco", "calo", "loca"], "cops" => ["scop"], "emmo" => ["mome"],
      "cegl" => ["cleg"], "ackw" => ["cawk"], "aaks" => ["asak", "kasa", "kaas"],
      "ajot" => ["jota", "jato"], "hipt" => ["phit", "hipt"],
      "artu" => ["ruta", "taur", "ratu"], "cosy" => ["coys"], "arty" => ["atry"],
      "aakk" => ["kaka"], "acil" => ["laic"], "hmor" => ["mohr"],
      "aeew" => ["awee"], "drwy" => ["wyrd"], "cdhr" => ["drch"],
      "aeux" => ["eaux"], "agsz" => ["zags"], "hlwy" => ["hwyl"],
      "msuv" => ["vums"], "bdor" => ["brod"],
      "agin" => ["agni", "inga", "nagi", "naig", "ngai", "agin"],
      "aefl" => ["alef", "feal"], "ahku" => ["kahu", "haku"], "chku" => ["huck"],
      "epsz" => ["zeps"], "efls" => ["elfs", "fels"], "irvy" => ["ivry"],
      "aemy" => ["ayme"], "dnru" => ["durn", "nurd", "rund"],
      "lowy" => ["lowy", "owly"], "amot" => ["atmo", "mota"],
      "aikt" => ["ikat", "kati", "taki", "tika"], "aehj" => ["haje"],
      "akrv" => ["kvar"], "lnoy" => ["loyn", "lyon"], "ajnt" => ["jant"],
      "firy" => ["firy"], "knsu" => ["skun"], "eknz" => ["knez"],
      "arsv" => ["vars"], "bcho" => ["chob"], "adek" => ["aked", "kade"],
      "defl" => ["delf"], "deqr" => ["reqd"], "efrv" => ["ferv"],
      "koor" => ["kroo", "okro"], "losv" => ["solv"],
      "acet" => ["teca", "cate", "tace"], "issu" => ["susi"],
      "aanp" => ["pana", "napa"], "dhoz" => ["dzho"], "aksu" => ["kusa", "sauk"],
      "clmu" => ["clum", "culm"], "ehjt" => ["jeth"], "bims" => ["mibs"],
      "mott" => ["mott"], "egry" => ["gery", "gyre"], "hrru" => ["hurr", "ruhr"],
      "aeuv" => ["uvae", "veau", "uvea"], "bceo" => ["boce"],
      "eosy" => ["yeso", "oyes"], "deop" => ["oped"],
      "mosu" => ["mous", "muso", "soum"], "bkoo" => ["boko", "kobo"],
      "belu" => ["bleu"], "aaww" => ["wawa"], "gotv" => ["vogt"],
      "alpr" => ["parl"], "kosu" => ["ouks"], "aitu" => ["utai", "aitu"],
      "crru" => ["curr"], "defi" => ["fied", "defi", "fide"], "ahis" => ["shia"],
      "efik" => ["fike", "kief"], "aemr" => ["mear", "rame"], "aafv" => ["fava"],
      "adgp" => ["gpad"], "oqsu" => ["quos"], "acrt" => ["trac"],
      "ehkt" => ["khet"], "mrsu" => ["rsum", "smur"],
      "efst" => ["fets", "tefs", "efts"], "ilrv" => ["virl", "vril"],
      "astv" => ["tavs"], "aetv" => ["tave", "veta"], "aahs" => ["aahs", "ahas"],
      "pstt" => ["ptts"], "eikp" => ["kipe", "kepi"], "hoow" => ["whoo"],
      "lmoy" => ["moyl", "moly"], "ehlr" => ["herl", "lehr"], "ekky" => ["kyke"],
      "awyy" => ["yawy"], "lpuv" => ["pulv"], "bhot" => ["thob"],
      "moop" => ["moop", "pomo"], "abdw" => ["bawd"], "irrw" => ["wirr"],
      "lotw" => ["lowt", "owlt"], "ellu" => ["elul"], "ehmv" => ["vehm"],
      "ehny" => ["hyen", "hyne"], "aapu" => ["paua"], "acer" => ["acer"],
      "alsu" => ["laus", "sula", "saul"], "iotw" => ["iowt"], "cdgp" => ["gpcd"],
      "dgow" => ["gowd"], "cdls" => ["sdlc"], "eelw" => ["weel"],
      "desu" => ["sude", "deus"], "alor" => ["lora"],
      "ader" => ["daer", "rade", "ared", "eard"], "epsv" => ["veps", "vesp"],
      "iort" => ["roit", "roti", "tori"], "cnnu" => ["nunc"], "hluy" => ["huly"],
      "hotw" => ["thow", "whot"], "agst" => ["agst", "gast", "gats"],
      "hkor" => ["khor"], "acpu" => ["caup", "pacu", "puca"], "eghn" => ["heng"],
      "akkr" => ["kark"], "oppr" => ["ropp"], "binr" => ["birn", "brin"],
      "aady" => ["aday"], "eklm" => ["kmel"], "eory" => ["roey", "oyer"],
      "aagm" => ["gama", "agma"], "dipt" => ["dipt"], "adhi" => ["dhai"],
      "adst" => ["satd", "stad", "dast"], "aegr" => ["areg", "gare"],
      "dfow" => ["dowf"], "inwy" => ["winy"], "lopt" => ["polt"],
      "ajnu" => ["jaun", "juan"], "cluy" => ["cyul", "lucy"],
      "dels" => ["leds", "dels", "elds", "seld"],
      "adlo" => ["dalo", "dola", "alod", "odal"], "begn" => ["beng"],
      "glms" => ["sgml"], "aorr" => ["orra"], "cenr" => ["cern"],
      "eejr" => ["jere"], "lort" => ["rotl"], "alnt" => ["lant"],
      "gjsu" => ["gjus"], "tuyz" => ["yutz"], "hlsu" => ["shul"],
      "rtuy" => ["yurt"], "frru" => ["furr"], "eoss" => ["osse", "oses"],
      "appr" => ["parp"], "adot" => ["toda", "doat", "dato"], "agqu" => ["quag"],
      "aglr" => ["glar"], "ahkr" => ["khar", "rakh"], "abrr" => ["barr"],
      "affr" => ["raff"], "hosu" => ["shou", "huso"], "alow" => ["lowa", "alow"],
      "amoy" => ["amoy", "moya"], "elow" => ["lowe"], "boor" => ["boro", "broo"],
      "cchs" => ["csch"], "cdlu" => ["dulc"], "egis" => ["gise", "gies"],
      "jmoo" => ["joom", "jomo", "mojo"], "almm" => ["lamm", "malm"],
      "bdis" => ["dibs"], "eimw" => ["wime"], "eirr" => ["rier"],
      "ddir" => ["dird"], "ahoy" => ["hoya"], "aety" => ["yeat", "yeta", "yate"],
      "fhot" => ["thof"], "aimu" => ["maui"], "acuy" => ["cuya", "yuca"],
      "hiil" => ["hili"], "ajks" => ["jaks"], "ekkl" => ["kelk"],
      "amru" => ["amur", "maru", "mura", "arum"], "absw" => ["wabs"],
      "aehp" => ["epha"], "rssu" => ["russ", "ussr"], "hpty" => ["hypt"],
      "bhoo" => ["boho", "booh"], "alpy" => ["pyal", "pyla", "paly"],
      "ostw" => ["owts", "sowt", "wost", "wots"],
      "acel" => ["acle", "alce", "alec"], "imor" => ["miro", "moir"],
      "ejmr" => ["jerm"], "ahrs" => ["rahs"], "motu" => ["motu", "mout"],
      "apwy" => ["yawp"], "aggu" => ["guga"], "adlm" => ["aldm"],
      "addy" => ["dyad"], "iosv" => ["ovis"], "elmo" => ["lome"],
      "eitt" => ["tite"], "mooy" => ["moyo"], "amnw" => ["mawn"],
      "ahlm" => ["halm"], "hlos" => ["losh"], "aglp" => ["galp"],
      "enox" => ["noex", "exon"], "foss" => ["foss"],
      "adps" => ["adps", "spad", "daps"], "dsuy" => ["syud"], "amst" => ["stam"],
      "cipt" => ["pict"], "agim" => ["magi"], "imty" => ["mity"],
      "hisv" => ["shiv"], "erwy" => ["ewry"], "eknr" => ["renk", "nerk", "kern"],
      "rsty" => ["syrt"],
      "aims" => ["mias", "sami", "siam", "amis", "saim", "sima"],
      "goot" => ["goto", "togo"], "aayy" => ["yaya"], "chko" => ["chok"],
      "aett" => ["atte", "tate"], "abix" => ["bixa"], "abim" => ["mabi", "bima"],
      "ainp" => ["pian", "nipa"], "asvw" => ["vaws"], "fiij" => ["fiji"],
      "glst" => ["stlg"], "estw" => ["ewts", "tews"], "aclr" => ["clar", "carl"],
      "dinp" => ["pind"], "iopy" => ["pioy"], "inpx" => ["pinx"],
      "acfr" => ["carf"], "abes" => ["besa", "sabe"], "akly" => ["alky", "laky"],
      "beik" => ["kibe"], "acnn" => ["cann"], "asty" => ["tays"],
      "bcim" => ["icbm"], "egns" => ["engs", "negs"], "bmps" => ["mbps", "mpbs"],
      "adns" => ["ands", "dans"], "hnsu" => ["huns"], "aotv" => ["vota"],
      "rsuu" => ["urus"], "bhtu" => ["bhut"], "iklr" => ["lirk"],
      "acju" => ["jacu"], "aben" => ["bena", "nabe"], "benn" => ["benn", "nebn"],
      "gllo" => ["goll"], "belt" => ["blet"], "dopw" => ["dowp"],
      "hoop" => ["phoo"], "bgoo" => ["bogo", "gobo"], "clos" => ["clos"],
      "ddet" => ["detd"], "brsu" => ["urbs"], "dijr" => ["jird"],
      "fflu" => ["luff"], "ffuw" => ["wuff"], "cioz" => ["zoic"],
      "aahk" => ["akha", "haak", "kaha", "haka"], "kmoy" => ["moky"],
      "chmo" => ["moch"], "artt" => ["trat"], "abiw" => ["biwa"],
      "deer" => ["ered", "dere", "dree", "rede"], "epry" => ["rype"],
      "bdii" => ["bidi"], "ablm" => ["blam"], "ilty" => ["yilt"],
      "adfr" => ["fard"], "adfl" => ["dalf"], "degs" => ["geds"],
      "cooy" => ["coyo"], "acdh" => ["chad"], "deet" => ["deet"],
      "ajlr" => ["jarl"], "abcu" => ["cuba"], "ciss" => ["scsi"],
      "egru" => ["grue"], "bkpr" => ["bkpr"], "ggho" => ["hogg"],
      "fiju" => ["fuji"], "oorz" => ["orzo"], "deux" => ["deux"],
      "adet" => ["adet", "ated", "tade", "taed", "tead"], "fiil" => ["fili"],
      "otww" => ["wowt"], "cehy" => ["yech"], "abco" => ["boca"],
      "abox" => ["abox"], "akow" => ["woak"], "ivxx" => ["xxiv", "xxvi"],
      "puxy" => ["puxy"], "fnos" => ["fons"], "inot" => ["nito", "oint"],
      "efgo" => ["foge"], "abln" => ["blan"], "iikr" => ["kiri"],
      "mpuy" => ["pumy", "umpy", "yump"], "cfit" => ["fict"], "dekn" => ["kend"],
      "aert" => ["arte", "erat", "tera", "aret"], "diuv" => ["uvid"],
      "foos" => ["foos", "oofs"], "aquw" => ["quaw"], "ahik" => ["haik"],
      "ahsu" => ["shua"], "bhis" => ["bish"], "ehty" => ["yeth", "hyte"],
      "dego" => ["gode", "doge"], "beer" => ["bere", "bree"], "eovy" => ["ovey"],
      "ceiw" => ["wice"], "opsy" => ["opsy"], "cepr" => ["crpe"],
      "apsz" => ["spaz"], "ahkl" => ["lakh"], "bess" => ["bess", "sebs"],
      "abot" => ["bota"], "abbr" => ["brab"], "goos" => ["goos"],
      "clrt" => ["ctrl"], "kssy" => ["skys"], "aagh" => ["agha"],
      "bceu" => ["cebu"], "aagr" => ["gara"], "moru" => ["roum"],
      "cgos" => ["scog"], "imoo" => ["moio", "mooi"], "dees" => ["dees"],
      "ejuv" => ["juve"], "hort" => ["orth", "thor", "thro"], "acck" => ["cack"],
      "aams" => ["amas", "maas", "masa", "sama"], "ahno" => ["noah"],
      "glru" => ["gurl", "lurg"], "hhsu" => ["huhs"], "mmuu" => ["mumu"],
      "eeir" => ["eire", "erie"], "eerr" => ["erer"], "alll" => ["lall"],
      "cpsu" => ["scup"], "aflt" => ["laft"], "aesv" => ["aves", "vaes"],
      "been" => ["nebe", "bene"], "dimn" => ["midn"], "aabd" => ["daba"],
      "aagl" => ["agal", "agla"], "adhs" => ["hads", "sadh", "dahs"],
      "hins" => ["hisn", "hins", "sinh"], "eiky" => ["ikey", "yike"],
      "ekll" => ["kell"], "aitt" => ["tait"], "aeft" => ["atef"],
      "afux" => ["faux"], "hmos" => ["mhos", "shmo"],
      "abem" => ["ambe", "mabe", "bema"], "dorr" => ["dorr"],
      "iors" => ["soir", "sori"], "eftt" => ["fett"],
      "eemr" => ["erme", "reem", "meer"], "acip" => ["capi"],
      "ahko" => ["hako", "hoka"], "aijn" => ["jain", "jina"], "aklv" => ["klva"],
      "bgis" => ["bigs", "gibs"], "eost" => ["tose"], "adsy" => ["dyas"],
      "ekoy" => ["okey"], "eeru" => ["eure"], "ddeg" => ["gedd"],
      "eghp" => ["pegh"], "ghis" => ["gish"], "aclt" => ["clat"],
      "acou" => ["coua"], "finr" => ["firn"], "cdhl" => ["hdlc"],
      "abdu" => ["buda"], "bmou" => ["ombu", "umbo"], "aluu" => ["aulu", "ulua"],
      "agjr" => ["jarg"], "nost" => ["nots", "onst"],
      "ablu" => ["baul", "bual", "luba", "balu"], "ahim" => ["hami"],
      "jlou" => ["joul"], "bdoy" => ["doby"], "dgsu" => ["dugs"],
      "acfk" => ["fack"], "afmu" => ["fuma"], "kooy" => ["yook"],
      "efnr" => ["fren"], "sttu" => ["stut"], "ceen" => ["cene"],
      "gott" => ["togt"], "bouw" => ["bouw"], "agpy" => ["gapy"],
      "aakm" => ["kama"], "agno" => ["ango", "agon"], "eimo" => ["meio", "oime"],
      "fitz" => ["fitz"], "achn" => ["chan", "nach"], "emms" => ["mems"],
      "aabg" => ["agba", "baga", "gaba"], "eilp" => ["epil", "lipe"],
      "acpr" => ["parc"], "ilns" => ["lins", "nils"], "booy" => ["yobo", "boyo"],
      "hopq" => ["qoph"], "adit" => ["dita", "adit"], "abdi" => ["abid", "bida"],
      "delu" => ["deul", "dule", "leud", "lude"], "httu" => ["tuth"],
      "apuz" => ["zupa"], "aagn" => ["anga", "naga"], "iiiw" => ["iiwi"],
      "aehx" => ["hexa"], "cill" => ["cill"], "ektu" => ["teuk", "tuke"],
      "eeln" => ["elne", "lene"], "inuz" => ["zuni"], "bikr" => ["birk"],
      "cnru" => ["curn"], "adpp" => ["appd"], "aqst" => ["qats"],
      "noow" => ["woon"], "coru" => ["cour"], "ainu" => ["ainu", "unai"],
      "oopt" => ["toop", "poot", "topo"], "agps" => ["spag"], "iijt" => ["jiti"],
      "erxx" => ["exrx"], "ossv" => ["sovs"], "irxy" => ["rixy"],
      "dnuy" => ["duny", "undy"], "aknp" => ["pank", "knap"], "acdy" => ["cady"],
      "esuy" => ["suey", "ueys"], "ikry" => ["yirk"], "imzz" => ["mizz"],
      "ahnw" => ["whan", "hwan"], "aant" => ["anta", "tana"], "abci" => ["baic"],
      "dllu" => ["llud"], "aklm" => ["klam"], "npxy" => ["pnyx"],
      "acgl" => ["clag"], "errs" => ["serr"], "dmsu" => ["dmus", "musd", "muds"],
      "aels" => ["lase"], "esuz" => ["suez", "zeus"], "ijko" => ["koji"],
      "oprs" => ["spor"], "opsu" => ["oups"], "ikru" => ["kuri"],
      "fhmu" => ["humf"], "aijr" => ["jari"], "achw" => ["chaw"],
      "aepp" => ["pape"], "efsy" => ["feys"], "efft" => ["teff"],
      "einz" => ["zein"], "kmos" => ["omsk", "mosk"], "aghm" => ["magh"],
      "aarv" => ["vara"], "gost" => ["stog"], "cint" => ["tinc"],
      "moxy" => ["myxo"], "acos" => ["saco", "ocas", "soca"], "hlot" => ["holt"],
      "nosw" => ["nows", "wons"], "apsw" => ["spaw", "waps"],
      "alos" => ["laos", "sola"], "dosz" => ["dzos"], "intx" => ["xint"],
      "aill" => ["lila"], "ijos" => ["sijo"], "beht" => ["theb", "beth"],
      "flot" => ["flot"], "lnow" => ["nowl", "lown"], "eflp" => ["pelf"],
      "mnou" => ["moun", "muon"], "agsu" => ["gaus"], "acrs" => ["srac"],
      "issv" => ["viss"], "ccly" => ["cycl"], "ejrt" => ["jert"],
      "isuu" => ["iuus"], "alst" => ["alts"], "dehn" => ["hend"],
      "cenp" => ["pnce"], "aeww" => ["wawe"], "aipt" => ["atip"],
      "adko" => ["koda"], "enov" => ["nevo"], "attt" => ["tatt"],
      "hosz" => ["zhos"], "ddmo" => ["dmod"],
      "emno" => ["mone", "nemo", "meno", "nome"], "aakl" => ["kala"],
      "elty" => ["lyte", "yelt"], "bhru" => ["burh", "buhr"], "ahly" => ["hyla"],
      "eelp" => ["leep", "pele"], "bdeo" => ["dobe"], "mmoo" => ["momo"],
      "aafm" => ["mafa"], "lluw" => ["wull"], "anox" => ["noxa", "oxan"],
      "gguw" => ["wugg"], "cerx" => ["crex"], "iszz" => ["sizz"],
      "ejss" => ["jess"], "efry" => ["frey", "ryfe"], "lnot" => ["nolt"],
      "efir" => ["fier", "reif"], "cmsw" => ["cwms"],
      "airz" => ["zira", "izar", "riza", "zari"], "aacc" => ["acca", "caca"],
      "klov" => ["volk"], "dety" => ["tedy", "tyde", "tyed"], "ghho" => ["hogh"],
      "aghr" => ["argh"], "hkot" => ["khot"], "hips" => ["pish", "phis"],
      "eeko" => ["okee"], "ekno" => ["keno"], "bgsu" => ["subg", "gubs"],
      "acim" => ["amic", "cima", "cami"], "ailv" => ["vila", "vali", "vail"],
      "aekw" => ["weka"], "hilt" => ["ilth"], "aoty" => ["oaty"],
      "aagp" => ["gapa", "paga"], "afmp" => ["famp"], "hmop" => ["moph"],
      "eprr" => ["repr"], "ahlu" => ["lahu"], "qrst" => ["sqrt"],
      "deno" => ["doen", "endo"], "ansu" => ["ansu"], "ablp" => ["lapb"],
      "dlnu" => ["lund"], "fgow" => ["gowf"], "aapr" => ["aarp", "apar", "paar"],
      "stxy" => ["styx", "xyst"], "iqsu" => ["quis"],
      "hiks" => ["sikh", "khis", "kish"], "bhin" => ["binh"], "egmn" => ["meng"],
      "alwy" => ["waly"], "acnu" => ["unca"], "ddei" => ["deid"],
      "kosy" => ["yoks"], "eltt" => ["lett", "telt"],
      "abku" => ["baku", "bauk", "kuba"], "ntuz" => ["untz"], "aach" => ["chaa"],
      "abdo" => ["doab"], "emnn" => ["nemn"], "inou" => ["unio"],
      "lpuy" => ["puly"], "aabc" => ["abac", "caba"], "dmno" => ["domn"],
      "ciop" => ["cipo", "pico"], "emnt" => ["ment"], "inpy" => ["pyin"],
      "bcik" => ["bick"], "bdnr" => ["dbrn"], "egpy" => ["gype"],
      "eemv" => ["meve"], "aamm" => ["amma", "maam"], "lopu" => ["loup"],
      "akru" => ["kura", "rauk", "raku"], "asuy" => ["ayus"], "bimz" => ["zimb"],
      "ntuy" => ["tuny"], "dnor" => ["dorn", "rond"], "eiqu" => ["quei"],
      "ditu" => ["duit"], "gims" => ["gism", "migs"], "ackn" => ["cank"],
      "diot" => ["doit"], "gkno" => ["kong", "gonk"], "ceop" => ["opec"],
      "ahpt" => ["ptah", "phat"], "fiin" => ["fini"], "amqt" => ["qtam"],
      "dirt" => ["trid"], "beef" => ["feeb"], "chio" => ["icho"],
      "diuw" => ["widu"], "eghu" => ["eugh"], "afil" => ["alif", "fila"],
      "eoty" => ["yote", "toey", "eyot"], "bils" => ["libs"],
      "abcs" => ["abcs", "bacs"],
      "abel" => ["abel", "beal", "bela", "blea", "albe", "blae"],
      "efnt" => ["fent"], "elpx" => ["plex"], "gnnu" => ["nung"],
      "elsz" => ["zels"], "ikmr" => ["mirk"], "lnny" => ["lynn"],
      "lpsu" => ["slup", "puls"], "betu" => ["bute"], "lott" => ["tolt"],
      "chik" => ["chik"], "amsu" => ["musa", "saum", "amus", "masu"],
      "egll" => ["gell"], "cfor" => ["corf"], "asuu" => ["ausu"],
      "blsu" => ["slub"], "iikk" => ["kiki"], "abej" => ["beja"],
      "ajko" => ["jako"], "aipp" => ["paip", "pipa"],
      "aehy" => ["ahey", "eyah", "haye"], "lnos" => ["slon"],
      "alot" => ["lota", "tola"], "abgi" => ["gabi", "biga"],
      "aetw" => ["wate", "twae", "weta"], "eehp" => ["heep"], "afpr" => ["frap"],
      "bnow" => ["bown"], "aekm" => ["meak", "kame"], "ikps" => ["pisk"],
      "atwy" => ["tway"], "eeks" => ["eeks", "skee"], "ostu" => ["otus", "sout"],
      "aftu" => ["faut", "tufa"], "dest" => ["sted"], "rruu" => ["ruru"],
      "aikk" => ["kaik", "kaki"], "egor" => ["rego"], "anno" => ["anno", "nona"],
      "bdoo" => ["bood", "doob"], "deey" => ["yeed", "yede"],
      "dgno" => ["gond", "dong"], "aios" => ["asio"], "adhu" => ["haud"],
      "gilu" => ["iglu", "ugli"], "ajpw" => ["jawp"], "bimu" => ["imbu"],
      "rtty" => ["tryt"], "ffiz" => ["ziff"], "iknt" => ["tink"],
      "ehlo" => ["helo"], "defr" => ["derf"], "gloy" => ["gloy", "logy"],
      "cfiu" => ["cuif", "fuci"], "iopt" => ["poti"], "chor" => ["croh", "roch"],
      "hnuw" => ["whun"], "aprz" => ["zarp"], "ainx" => ["axin", "xian"],
      "aoxz" => ["azox"], "dhis" => ["sidh"], "ehin" => ["hine"],
      "aeim" => ["miae", "amie"], "imny" => ["miny"], "beot" => ["bote", "tobe"],
      "dkoo" => ["dook"], "bmru" => ["brum", "rumb"], "nptx" => ["pnxt"],
      "acde" => ["ecad", "cade", "dace"], "diir" => ["irid"], "bcko" => ["bock"],
      "aboz" => ["boza"], "aatt" => ["atta"], "bops" => ["pobs"],
      "imru" => ["urim", "muir", "rimu"], "gsuy" => ["yugs"], "ivyz" => ["vizy"],
      "bdee" => ["debe", "bede"], "eggg" => ["gegg"], "ilpu" => ["puli"],
      "abkn" => ["knab", "nabk"], "lrsu" => ["lurs"], "ahin" => ["hani", "hain"],
      "egnu" => ["gneu", "genu"], "afrw" => ["warf"], "eflt" => ["flet"],
      "ccis" => ["cisc", "sicc"], "mooz" => ["mozo"],
      "eels" => ["lese", "sele", "slee", "seel"], "nrtu" => ["trun"],
      "girw" => ["wrig"], "prsu" => ["purs", "urps"], "aosv" => ["avos"],
      "aptt" => ["patt"], "oort" => ["roto", "toro"], "afoy" => ["yafo", "ofay"],
      "ippy" => ["pipy"], "cceh" => ["ecch"], "eelt" => ["lete", "teel", "leet"],
      "annt" => ["nant"], "aadw" => ["adaw", "wada"], "glsu" => ["guls"],
      "iilw" => ["wili"], "illv" => ["vill"], "aacm" => ["caam"],
      "aejt" => ["jeat", "jeta"], "gguv" => ["vugg"], "dfor" => ["drof"],
      "eitw" => ["twie", "wite"], "ikop" => ["kopi"], "eklo" => ["loke", "koel"],
      "fhiq" => ["fiqh"], "mozz" => ["mozz"], "dioz" => ["zoid"],
      "inoy" => ["yoni"], "npsu" => ["snup"], "ehiv" => ["hevi"],
      "mopu" => ["moup"], "aikm" => ["maki", "kaim", "maik", "kami"],
      "acmy" => ["ymca", "cyma"], "almo" => ["malo", "olam", "loma", "mola"],
      "cios" => ["iocs"], "agnt" => ["gant"], "anor" => ["arno", "oran", "orna"],
      "hior" => ["hiro"], "eenp" => ["neep", "pene", "peen"], "agho" => ["hoga"],
      "ortu" => ["outr", "toru"], "anow" => ["anow", "woan"], "cemr" => ["merc"],
      "ddow" => ["dowd"], "ahit" => ["aith", "hait", "thai"], "adhw" => ["dhaw"],
      "abij" => ["bija"], "coop" => ["poco"],
      "ains" => ["ansi", "asin", "nais", "nasi", "sian", "sina", "ains", "anis",
       "sain"], "amsx" => ["xmas"], "afst" => ["saft"], "addw" => ["dawd", "wadd"],
      "egrt" => ["gret"], "impy" => ["impy"], "ksst" => ["tsks"],
      "dhsu" => ["dush"], "gors" => ["gros"], "aest" => ["ates", "etas"],
      "afkl" => ["falk"], "ceks" => ["seck"], "adyz" => ["dazy"],
      "hjow" => ["jhow"], "beno" => ["beno", "nebo", "ebon"], "acry" => ["cray"],
      "opqu" => ["quop"], "eswy" => ["swey", "weys", "wyes"], "aily" => ["yali"],
      "elwy" => ["wyle"], "ehsu" => ["huse"], "hptu" => ["phut"],
      "ekmp" => ["kemp"], "ostt" => ["stot"], "aatw" => ["awat", "tawa"],
      "aijl" => ["lija"], "bflo" => ["flob"], "diin" => ["nidi"],
      "ahks" => ["hask"], "gist" => ["tigs"], "epqt" => ["eqpt"],
      "ikno" => ["kino"], "aast" => ["asta", "sata"], "berv" => ["brev"],
      "chot" => ["ocht", "toch", "coth"], "apty" => ["paty", "pyat"],
      "iiss" => ["isis", "sisi"], "aiin" => ["inia"], "egss" => ["gess", "segs"],
      "kknu" => ["kunk"], "aijo" => ["jiao"], "diim" => ["imid", "midi"],
      "abms" => ["bams"], "imqu" => ["quim"], "akov" => ["akov"],
      "llru" => ["rull", "ullr"], "anoz" => ["onza", "azon", "zona"],
      "ertz" => ["trez"], "cdel" => ["cled"], "degu" => ["degu", "gude"],
      "eefj" => ["jefe"], "affh" => ["haff"], "eenv" => ["eevn", "veen"],
      "stuw" => ["wust"], "iiiv" => ["viii"], "antz" => ["zant"],
      "cloy" => ["coly"], "ejlr" => ["jerl"], "ikns" => ["kins"],
      "amor" => ["amor", "maro", "roma", "mora"], "ajsy" => ["jasy"],
      "eggt" => ["tegg"], "aksy" => ["kays"], "koss" => ["koss"],
      "eklt" => ["kelt"], "fooy" => ["oofy", "yoof"], "aces" => ["esca", "ceas"],
      "insz" => ["zins"], "fklu" => ["fulk"], "bilo" => ["bilo", "obli", "lobi"],
      "aadd" => ["adad", "adda", "dada"], "deio" => ["ideo", "iode"],
      "aabh" => ["ahab", "haab"], "aaby" => ["abay", "baya", "yaba"],
      "glmo" => ["glom"], "ceiv" => ["cive"], "iost" => ["otis"],
      "bhik" => ["bikh"], "aass" => ["sasa"], "ddeo" => ["dedo", "eddo"],
      "afru" => ["frau"], "tuuy" => ["yutu"], "eins" => ["nies", "sien"],
      "agrt" => ["gart", "trag", "grat"], "eksu" => ["euks", "kues", "ukes"],
      "egot" => ["gote", "toge"], "ahmo" => ["moha"], "disv" => ["divs", "vids"],
      "optt" => ["pott"], "ghno" => ["hong"], "bchs" => ["bchs"],
      "jkou" => ["jouk"], "aipr" => ["pari", "ripa"], "jkoo" => ["jook"],
      "eesy" => ["yees", "yese"], "bbis" => ["sibb"], "ilrt" => ["tirl"],
      "bimn" => ["nimb"], "ahtt" => ["hatt", "tath"], "elor" => ["eorl", "orle"],
      "aefr" => ["afer", "frae"], "eirw" => ["weri"], "dloz" => ["lodz"],
      "ensy" => ["syen", "nyes", "snye", "syne"], "nstu" => ["sunt", "tsun"],
      "bosy" => ["sybo"], "jntu" => ["junt"], "aarr" => ["rara", "arar"],
      "ghii" => ["higi"], "absu" => ["suba"], "issw" => ["wiss"],
      "chjo" => ["joch"], "deks" => ["sked", "keds"], "ddde" => ["dedd"],
      "deep" => ["depe"], "adku" => ["dauk", "duka"], "itvy" => ["tivy"],
      "agiy" => ["yagi"], "hors" => ["shor", "hors", "rhos"], "huzz" => ["huzz"],
      "bdfu" => ["fdub"], "adgr" => ["gard", "darg"],
      "alpu" => ["upla", "paul", "pula"], "gort" => ["trog", "grot"],
      "degr" => ["dreg"], "ablt" => ["blat"], "envy" => ["veny"],
      "ccho" => ["coch"], "abcm" => ["camb"], "filx" => ["flix"],
      "imsy" => ["misy", "ismy"], "ehtt" => ["teth"], "cdey" => ["dyce"],
      "gnor" => ["rong"], "nrsu" => ["snur", "nurs"], "amux" => ["maux"],
      "cees" => ["cees"], "aloz" => ["lazo", "zola"], "abew" => ["wabe"],
      "antu" => ["antu", "natu", "taun", "unta", "tuan"],
      "cmos" => ["coms", "mocs"], "acox" => ["coxa"],
      "abru" => ["baru", "baur", "bura"], "ackz" => ["zack"], "ikpp" => ["kipp"],
      "aabj" => ["baja"], "eimz" => ["zemi"], "aoru" => ["roua", "urao"],
      "dkno" => ["donk", "kond"], "acmu" => ["caum"], "afgo" => ["goaf"],
      "bnoy" => ["byon"], "addr" => ["addr", "dard", "drad"],
      "ceel" => ["cele", "clee"], "aadn" => ["anda", "dana", "nada"],
      "hkru" => ["rukh"], "bens" => ["sneb", "bens", "nebs"], "iimr" => ["miri"],
      "aent" => ["anet", "taen", "tean", "tane", "etna"], "chhi" => ["chih"],
      "ellp" => ["pell"], "aclw" => ["cawl"], "eery" => ["yere", "eyer", "eyre"],
      "beru" => ["bure", "erub"], "efno" => ["foen", "fone"], "ersw" => ["rews"],
      "eotv" => ["voet"], "ejoo" => ["ejoo"], "nuxy" => ["yunx"],
      "bnnw" => ["nwbn"], "dmoy" => ["mody", "domy"], "abtt" => ["batt"],
      "eehm" => ["heme"], "aimr" => ["mari", "mair", "rami", "rima"],
      "eens" => ["enes", "ense", "nese", "esne", "snee", "sene"],
      "ciln" => ["clin"], "enot" => ["ento", "eton"], "agks" => ["skag"],
      "ahms" => ["samh"], "afsw" => ["faws"], "elpr" => ["lerp"],
      "aabm" => ["amba"], "bkou" => ["kobu", "bouk"], "aarw" => ["waar"],
      "aaik" => ["akia"], "gmno" => ["mong"], "cirs" => ["risc", "cris"],
      "abit" => ["abit", "tabi"], "hhjv" => ["jhvh"], "gksu" => ["skug"],
      "ffnu" => ["nuff"], "bejo" => ["jobe"], "iimp" => ["impi"],
      "aals" => ["lasa", "sala", "aals", "laas"], "dhiw" => ["whid"],
      "aais" => ["asia", "aias"], "admr" => ["mard"], "kuyy" => ["yuky"],
      "door" => ["oord", "ordo"], "efks" => ["kefs"], "ippr" => ["ripp"],
      "copt" => ["copt"], "kuuz" => ["kuzu"], "hiss" => ["sish"],
      "aiil" => ["alii", "ilia"], "ceov" => ["voce"], "cehr" => ["cher"],
      "ceot" => ["ecto"], "abil" => ["bali"], "alms" => ["mals"],
      "emor" => ["mero", "rome", "omer"], "alrw" => ["warl"], "gosv" => ["govs"],
      "dizz" => ["dizz"], "ablw" => ["blaw"], "biko" => ["kobi"],
      "ghoo" => ["hogo"], "lory" => ["orly"], "aklw" => ["lawk"],
      "abko" => ["boak"], "acew" => ["wace"], "aacv" => ["cava"],
      "iinv" => ["ivin"], "amqu" => ["quam"], "oors" => ["roos"],
      "hkrw" => ["kwhr"], "nnwy" => ["wynn"], "eewx" => ["wexe"],
      "eltu" => ["tule"], "orrt" => ["rort", "torr"], "ejlo" => ["joel", "jole"],
      "ahls" => ["hals", "lahs"], "ekpu" => ["keup"], "hopu" => ["ouph"],
      "ails" => ["lias", "sial", "sila"], "adho" => ["doha", "odah"],
      "choy" => ["choy"], "bkos" => ["boks", "bosk", "kobs"], "aemt" => ["meta"],
      "inor" => ["inro", "noir", "nori", "roin"], "chiw" => ["wich"],
      "aeip" => ["peai"], "fost" => ["fots", "stof"], "ahiy" => ["yahi"],
      "aelx" => ["exla", "axel"], "aegp" => ["pega", "peag"], "aehl" => ["hela"],
      "aegn" => ["agen", "gaen", "gane", "gena", "gean"],
      "bdio" => ["biod", "boid"], "douy" => ["youd"], "imnu" => ["muni"],
      "bekm" => ["kemb"], "adiw" => ["waid"], "joss" => ["joss"],
      "inoz" => ["zion"], "arst" => ["rast", "sart", "stra"], "amrw" => ["mawr"],
      "ntyy" => ["tyyn"], "aijv" => ["jiva"], "abpr" => ["barp"],
      "egps" => ["sepg"], "hiop" => ["hopi"], "ampy" => ["yamp"],
      "acir" => ["cair", "cira"], "afsx" => ["sfax"], "aesu" => ["esau", "eaus"],
      "dery" => ["drey", "yerd"], "aapv" => ["pava"], "cdiy" => ["dicy"],
      "alnr" => ["larn"], "bdlo" => ["dobl"], "boot" => ["boto"],
      "acsw" => ["wacs", "scaw"], "ossy" => ["soys"], "dikn" => ["dink"],
      "aadl" => ["daal"], "aimn" => ["iman", "mian", "amin", "mani"],
      "ddiy" => ["didy"], "airv" => ["aivr", "vari", "riva", "vair"],
      "llny" => ["llyn"], "chiv" => ["chiv"], "aerv" => ["vare", "vera"],
      "fffu" => ["fuff"], "aden" => ["aden"], "dopu" => ["doup", "updo"],
      "cstu" => ["cust", "scut"], "agiv" => ["viga", "vagi"],
      "fgru" => ["gruf", "frug"], "nnow" => ["nown"], "aiot" => ["tiao"],
      "estx" => ["sext"], "aops" => ["asop", "paso", "sapo", "poas"],
      "acot" => ["atoc", "octa"], "bioy" => ["yobi"], "bnoo" => ["bono"],
      "abht" => ["bhat", "baht"], "ajnn" => ["jann"], "bory" => ["orby"],
      "adwy" => ["wady"], "gttu" => ["gutt"], "elss" => ["sels"],
      "cinu" => ["unci"], "aakn" => ["akan", "kana"], "ajss" => ["jass"],
      "cdei" => ["cide", "cedi"], "foww" => ["wowf"], "accu" => ["cuca"],
      "aeot" => ["toea"], "gknu" => ["kung"], "ccdi" => ["ccid"],
      "afqw" => ["waqf"], "agkn" => ["kang", "knag"], "fnou" => ["foun"],
      "akpw" => ["pawk"], "egsu" => ["gues"], "moow" => ["woom"],
      "cdou" => ["coud", "douc"], "kkuu" => ["kuku"], "iiww" => ["wiwi"],
      "admo" => ["mado"], "bgor" => ["gorb", "brog"], "abmo" => ["boma", "ambo"],
      "anop" => ["paon"], "firs" => ["fris", "rifs"], "iitz" => ["ziti"],
      "adeg" => ["gade", "egad"], "orux" => ["uxor"], "aaim" => ["maia", "amia"],
      "ekwy" => ["wyke"], "aetu" => ["aute", "etua"], "noot" => ["oont", "toon"],
      "lnuv" => ["vuln"], "ensu" => ["sune"], "eiss" => ["sise", "seis"],
      "eiln" => ["nile"], "aarz" => ["zaar"], "erru" => ["ruer"],
      "ffij" => ["jiff"], "dnty" => ["tynd"], "kpuu" => ["puku"],
      "aenp" => ["nepa", "pean", "neap"], "addo" => ["adod"], "aary" => ["raya"],
      "bbbi" => ["bibb"], "agtt" => ["gatt"], "hnos" => ["hons"],
      "efns" => ["nefs"], "emtu" => ["tume"], "ottw" => ["towt"],
      "aimo" => ["maoi"], "ehpt" => ["hept"], "anos" => ["naso", "naos"],
      "disy" => ["sidy"], "oprr" => ["porr"], "aags" => ["agas"],
      "inrs" => ["rins"], "arsy" => ["ryas"], "djsu" => ["juds"],
      "cesy" => ["scye", "syce"], "dpuu" => ["pudu"], "inos" => ["sion"],
      "hisu" => ["huis"], "apvy" => ["pavy"], "aaeg" => ["gaea"],
      "ehns" => ["nesh"], "deoy" => ["yedo", "yode"],
      "ailr" => ["aril", "lari", "rial"], "ahnr" => ["harn"],
      "adru" => ["ardu", "daur", "duar", "dura"], "esty" => ["stey", "tyes"],
      "dhno" => ["hond"], "dlow" => ["dowl"], "dmor" => ["mord"],
      "aggh" => ["hagg"], "dehy" => ["hyde", "hyed"],
      "aenr" => ["anre", "aren", "rane", "nare", "rean"], "elnu" => ["lune"],
      "opry" => ["pory", "pyro"], "noty" => ["yont"], "bejn" => ["benj"],
      "aegm" => ["egma", "mage"], "alss" => ["sals"], "ikmo" => ["komi", "moki"],
      "dglu" => ["guld"], "dips" => ["disp", "psid"], "ehsy" => ["hyes", "heys"],
      "efil" => ["feil", "fiel"], "kloo" => ["kolo"],
      "dist" => ["stid", "tids", "dits"], "berr" => ["brer"],
      "bnos" => ["bons", "bosn"], "emst" => ["mest", "mets", "tems"],
      "acko" => ["coak"], "deil" => ["diel", "eild", "deil"],
      "beir" => ["ribe", "brei"], "deel" => ["lede", "leed", "dele"],
      "aehm" => ["haem", "hame"], "eell" => ["elle"], "adeh" => ["ahed", "hade"],
      "kkoo" => ["koko"], "aknu" => ["kuan", "kuna"], "ghin" => ["hing"],
      "dekl" => ["keld"], "mtuy" => ["tyum"], "agru" => ["ruga", "gaur"],
      "abbi" => ["abib"], "iott" => ["toit"], "cfhs" => ["scfh"],
      "aort" => ["rato"], "eegl" => ["lege"],
      "deor" => ["dero", "oder", "ored", "dore"], "abno" => ["oban", "bona"],
      "aopr" => ["prao", "proa"], "eekr" => ["eker"], "epsy" => ["pyes", "sype"],
      "adhk" => ["dhak"], "irry" => ["yirr"], "esuw" => ["suwe"],
      "jllo" => ["joll"], "atuz" => ["tuza"], "ampw" => ["mawp", "wamp"],
      "jovy" => ["jovy"], "dost" => ["stod", "tods"], "cdst" => ["sctd"],
      "aabl" => ["baal", "alba"], "jjuu" => ["juju"], "efhm" => ["fehm"],
      "abrw" => ["warb", "bawr", "braw"], "chit" => ["tich"],
      "ceit" => ["ceti", "etic", "tice"], "ehlt" => ["htel"], "enos" => ["sone"],
      "asst" => ["tass"], "ceou" => ["coue"], "ellm" => ["mell"],
      "eevw" => ["weve"], "grru" => ["gurr"], "ffko" => ["koff"],
      "nrty" => ["rynt"], "astu" => ["tasu", "saut", "utas", "taus"],
      "ijll" => ["jill"], "alry" => ["lyra", "yarl", "ryal", "aryl"],
      "acky" => ["caky"], "aehn" => ["haen"], "adil" => ["dail", "dali"],
      "dikl" => ["kild"], "efff" => ["feff"], "beko" => ["boke"],
      "koos" => ["koso", "skoo", "soko", "sook"], "ehor" => ["hoer"],
      "aalx" => ["axal"], "asww" => ["waws"], "beks" => ["kebs"],
      "illl" => ["lill"], "adnr" => ["nard"], "aegu" => ["auge"],
      "abiz" => ["izba"], "ilmo" => ["milo", "moil"], "egit" => ["geit", "tige"],
      "atxy" => ["taxy"], "csuz" => ["scuz"], "ggir" => ["rigg", "grig"],
      "ahuw" => ["whau"], "acis" => ["saic", "asci"], "glos" => ["glos"],
      "emru" => ["rume", "mure"], "agrs" => ["gras", "gars"], "bbls" => ["bbls"],
      "aelp" => ["alep", "lepa", "pela"], "sswy" => ["wyss"], "iims" => ["simi"],
      "afiv" => ["favi"], "klno" => ["koln"], "nppt" => ["pptn"],
      "ckoy" => ["coky"], "eivv" => ["vive"], "iknz" => ["zink"],
      "chis" => ["hics", "ichs", "sich", "chis"], "bosu" => ["obus"],
      "hhoo" => ["hoho"], "notu" => ["nout", "tuno", "toun"], "epxy" => ["expy"],
      "ceos" => ["coes", "soce", "cose", "seco"], "ipqu" => ["piqu"],
      "eiry" => ["eiry"], "ckow" => ["cowk", "wock"],
      "aalt" => ["lata", "taal", "tala"], "crsy" => ["scry"], "ainy" => ["ayin"],
      "loor" => ["loro", "orlo", "rool", "loor"], "almr" => ["marl"],
      "hlow" => ["holw"], "mosy" => ["moys"], "ghit" => ["gith", "thig"],
      "iptt" => ["tipt"], "acor" => ["acor", "cora", "arco", "orca"],
      "eirv" => ["veri", "rive"], "aimp" => ["pima"], "ddor" => ["rodd"],
      "moor" => ["moro"], "hklo" => ["holk"], "afgu" => ["gufa"],
      "egks" => ["skeg"], "eggh" => ["gheg"], "amuy" => ["yuma"],
      "ffmo" => ["moff"], "bbhu" => ["hubb"], "agnw" => ["gawn", "wang"],
      "aggr" => ["garg", "ragg"], "aekr" => ["kera", "reak"], "llno" => ["noll"],
      "acrx" => ["crax"], "dlpu" => ["plud"], "agly" => ["agly", "gyal"],
      "orsv" => ["vors"], "aajn" => ["naja"], "esst" => ["ests"],
      "opru" => ["roup"], "iptu" => ["tipu", "tupi", "ptui"], "abdr" => ["darb"],
      "aflv" => ["flav"], "oopr" => ["proo", "roop"], "allv" => ["vall"],
      "irss" => ["sris"], "iloo" => ["olio"], "abcn" => ["banc"],
      "deex" => ["exed"], "ipsw" => ["wips"], "aflx" => ["falx"],
      "beeh" => ["hebe"], "cers" => ["cres", "recs"],
      "aadm" => ["adam", "dama", "maad"], "ehms" => ["shem"], "ggis" => ["iggs"],
      "ammo" => ["mamo"], "anuu" => ["unau"], "gopu" => ["ogpu", "goup", "upgo"],
      "aahl" => ["hala"], "ados" => ["dosa", "sado", "ados", "odas"],
      "ddmu" => ["mudd"], "biln" => ["blin"], "fosu" => ["fous", "ufos"],
      "ghhu" => ["hugh"], "eerv" => ["reve"], "aapy" => ["yapa", "apay"],
      "eguz" => ["guze"], "bgoy" => ["bygo", "boyg", "goby"], "emns" => ["mens"],
      "biky" => ["kiby"],
      "aist" => ["atis", "sita", "tsia", "aits", "itas", "tais", "sati"],
      "iovv" => ["vivo"], "aepy" => ["paye"], "orss" => ["ross"],
      "kluw" => ["wulk"], "acmr" => ["marc"], "floo" => ["loof"],
      "bchu" => ["chub"], "imsv" => ["vims"], "aenn" => ["anne", "nane"],
      "ekmt" => ["kmet"], "apuw" => ["waup"], "deej" => ["jeed"],
      "eikw" => ["weki"], "filo" => ["lifo"], "cgly" => ["glyc"],
      "aems" => ["asem", "maes", "mase"], "djoo" => ["dojo"],
      "aacp" => ["capa", "paca"], "acrr" => ["carr"], "abjo" => ["jaob"],
      "ekry" => ["ryke", "yerk"], "eefk" => ["keef"], "abgh" => ["bagh"],
      "aahh" => ["haha"], "abyz" => ["bayz"], "bers" => ["serb", "rebs"],
      "egnr" => ["gren", "rgen"], "amxy" => ["myxa"], "copw" => ["cowp"],
      "klmu" => ["kulm", "mulk"], "bkps" => ["kbps"], "cegi" => ["geic"],
      "efsu" => ["feus"], "aghw" => ["wagh"], "msuu" => ["suum"],
      "aikz" => ["kazi"], "hinw" => ["whin"], "equy" => ["quey"],
      "dimu" => ["duim", "muid"], "abmr" => ["barm"],
      "ailp" => ["pali", "plia", "lipa", "pial", "pila"], "bert" => ["bret"],
      "egln" => ["engl", "leng"], "eesv" => ["seve", "vese", "vees"],
      "gizz" => ["gizz"], "beos" => ["bose", "obes"], "ekmo" => ["moke"],
      "hloo" => ["hool"], "adlw" => ["awdl", "wald"], "otwy" => ["yowt", "towy"],
      "aksv" => ["kvas"], "ioss" => ["isos"], "ejku" => ["juke"],
      "anuz" => ["uzan"], "bcei" => ["bice"], "gpss" => ["gpss"],
      "chrt" => ["tchr"], "abks" => ["kabs"], "choo" => ["coho"],
      "abbs" => ["abbs"], "acls" => ["cals", "lacs"], "acss" => ["cass"],
      "coss" => ["socs", "coss"], "hpsu" => ["hups"], "imsu" => ["sium", "sumi"],
      "ailw" => ["wali"], "ejpu" => ["jupe"],
      "dein" => ["inde", "nied", "deni", "nide"], "ehtw" => ["hewt", "thew"],
      "aalr" => ["alar"], "aclu" => ["aclu", "caul"], "bhku" => ["bukh"],
      "cdnu" => ["cund"], "appy" => ["yapp"], "behl" => ["bhel"],
      "adff" => ["daff"], "aann" => ["anan", "nana", "anna"], "acfy" => ["facy"],
      "aetx" => ["exta"], "bdls" => ["bdls"], "eirt" => ["iter", "reit", "trie"],
      "erty" => ["trye", "tyer", "trey"], "iklp" => ["klip", "kilp"],
      "efms" => ["fems", "emfs"], "diip" => ["ipid"], "emrv" => ["merv"],
      "dioo" => ["iodo", "ooid"], "aain" => ["aina"], "aeky" => ["akey"],
      "bely" => ["bely", "bley"], "aacr" => ["arca", "raca"],
      "bost" => ["stob", "bots"], "fips" => ["spif"], "fimr" => ["frim"],
      "deeh" => ["hede", "ehed"], "aacz" => ["caza"], "host" => ["thos", "soth"],
      "cest" => ["cest", "scet"], "orwx" => ["wrox"], "bcde" => ["ebcd"],
      "ehsx" => ["hexs"], "ekks" => ["keks"], "ajpr" => ["jarp"],
      "abnt" => ["bant"], "fott" => ["toft"], "prtu" => ["prut", "turp"],
      "orsu" => ["rous"], "aktt" => ["takt"], "ilny" => ["inly", "liny"],
      "aadg" => ["agad"], "agir" => ["gari", "riga", "gair", "ragi"],
      "bklr" => ["bklr"], "eetw" => ["ewte", "weet"], "hmpu" => ["umph"],
      "osty" => ["tosy"], "optv" => ["topv"], "acnr" => ["carn", "cran"],
      "almy" => ["lyam", "myal", "amyl"], "etwy" => ["wyte"], "imos" => ["miso"],
      "aanz" => ["azan"], "bfsu" => ["fubs"],
      "aens" => ["eans", "anes", "sean", "sena"], "qssu" => ["suqs"],
      "iprr" => ["pirr"], "abtu" => ["buat"],
      "aips" => ["apis", "pasi", "pisa", "saip", "pais", "pias", "psia"],
      "ahsw" => ["shaw"], "deot" => ["tode"], "aglt" => ["galt"],
      "lors" => ["lors"], "isty" => ["itsy"], "aanr" => ["arna", "rana"],
      "abrs" => ["arbs"], "alnx" => ["lanx"], "akot" => ["kota", "atok", "okta"],
      "iluy" => ["uily"], "agio" => ["iago", "agio"],
      "akor" => ["karo", "roak", "roka", "kora"], "eehw" => ["hewe", "whee"],
      "efrr" => ["ferr"], "eprz" => ["prez"], "admm" => ["mdma"],
      "koot" => ["toko", "koto"], "egil" => ["gile", "lige", "glei"],
      "hiot" => ["hoit", "hoti", "thio"], "cuvy" => ["cuvy"],
      "dlno" => ["lond", "nold"], "aaes" => ["asea"], "acly" => ["acyl"],
      "dfis" => ["difs", "fids"], "ellr" => ["ller"], "lnoo" => ["nolo"],
      "ceip" => ["pice"], "ajru" => ["jura"], "amtu" => ["muta", "taum", "maut"],
      "dkny" => ["kynd"], "gglu" => ["glug"], "adfy" => ["fady"],
      "ijns" => ["jins"], "anpy" => ["nypa"], "bsww" => ["swbw"],
      "efky" => ["fyke"], "iiln" => ["liin"], "fnpx" => ["npfx"],
      "attw" => ["tawt"],
      "astw" => ["sawt", "staw", "wats", "taws", "twas", "wast"],
      "ablr" => ["balr"], "gsuv" => ["vugs"], "imns" => ["mins", "nims"],
      "cklo" => ["colk"], "acgn" => ["cang"], "ertw" => ["trew", "wert"],
      "eist" => ["seit", "stie"], "goor" => ["goor"], "aacf" => ["cafa"],
      "eors" => ["seor", "sero"], "efin" => ["feni", "neif", "nief", "nife"],
      "fguu" => ["fugu"], "iimm" => ["immi"], "bpuy" => ["upby"],
      "forw" => ["frow"], "acfh" => ["cafh"], "ghoy" => ["yogh"],
      "agil" => ["gail", "gali", "gila", "glia"], "acfu" => ["cauf"],
      "abqu" => ["quab"], "ikos" => ["skio", "kois"],
      "aery" => ["ayre", "eyra", "yare"], "fotw" => ["woft"], "hino" => ["hoin"],
      "efnu" => ["enuf"], "cekk" => ["keck"], "elov" => ["velo"],
      "eops" => ["sope", "epos", "opes"], "amty" => ["maty"], "eelr" => ["lere"],
      "aemw" => ["meaw", "weam", "wame"], "ejsw" => ["jews"], "einy" => ["yeni"],
      "eent" => ["neet", "eten", "nete", "tene"], "bknu" => ["knub"],
      "ackl" => ["kcal"], "ffip" => ["piff"], "copr" => ["copr", "porc"],
      "biuy" => ["buyi"], "crsu" => ["rucs", "scur", "crus"], "bnww" => ["nwbw"],
      "aell" => ["leal"], "abpu" => ["bapu"], "abbu" => ["buba"],
      "bltu" => ["bult"], "egin" => ["gein", "gien"], "hnoo" => ["hoon"],
      "attu" => ["tatu"], "agtu" => ["gaut"], "ajnw" => ["jawn"],
      "bcos" => ["bosc", "scob"], "achl" => ["chal"], "mnoy" => ["onym", "mony"],
      "bekl" => ["belk"], "eemz" => ["zeme", "meze", "mzee"], "elps" => ["leps"],
      "eesz" => ["zees"], "illy" => ["illy", "yill"], "eemw" => ["weem"],
      "aeej" => ["ajee"], "afmn" => ["fnma"], "ggmu" => ["mugg"],
      "eglw" => ["glew"], "cpru" => ["crup"], "ijor" => ["roji"],
      "efrx" => ["xref"], "gmou" => ["ogum"], "chly" => ["lych"],
      "oopp" => ["oppo"], "birs" => ["bris"], "iotx" => ["otxi"],
      "ehlm" => ["heml"], "aajr" => ["jara"], "alpp" => ["lapp", "plap", "palp"],
      "gmnu" => ["mung"], "cgir" => ["crig"], "kssu" => ["suks"],
      "beek" => ["beek"], "mtuu" => ["tuum", "utum"],
      "aeny" => ["ayen", "ayne", "yean"], "eitz" => ["zite"], "biir" => ["biri"],
      "beeo" => ["eboe"], "ersy" => ["syre", "ryes"], "adel" => ["leda"],
      "aapt" => ["pata", "atap", "tapa"], "affl" => ["laff"],
      "ilmu" => ["limu", "muil"], "eikv" => ["kiev"], "krtu" => ["turk"],
      "aerw" => ["arew"], "iins" => ["nisi"], "iprx" => ["prix"],
      "alpt" => ["palt"], "akmo" => ["mako"], "dosw" => ["dows"],
      "bklo" => ["blok", "bolk"], "acfi" => ["fica"], "aact" => ["acta"],
      "ilsu" => ["lisu"], "cekl" => ["leck"], "ehow" => ["howe"],
      "abis" => ["isba"], "loru" => ["roul", "urol"], "eiou" => ["euoi"],
      "ensw" => ["snew"], "afsu" => ["sauf", "aufs"],
      "answ" => ["wasn", "snaw", "wans", "awns"], "enss" => ["ness", "sens"],
      "deit" => ["deti", "dite"], "aart" => ["taar", "atar", "tara", "rata"],
      "egsy" => ["gyse"], "eimn" => ["mein"], "aggj" => ["jagg"],
      "abbo" => ["boba"], "aghu" => ["augh"], "iist" => ["siti"],
      "adlt" => ["tald", "dalt"], "aeel" => ["eale", "alee"], "gisz" => ["zigs"],
      "ehmr" => ["herm"], "aahr" => ["haar"], "fruz" => ["fruz", "zurf"],
      "amns" => ["mnas", "nams"], "iirs" => ["siri"], "dent" => ["detn"],
      "iknr" => ["kirn"], "ccoo" => ["coco"], "aamn" => ["anam", "naam", "mana"],
      "bbdu" => ["dubb"], "gjou" => ["joug"], "fksu" => ["fusk"],
      "cors" => ["cors", "rocs"], "ixxx" => ["xxix"], "enuz" => ["unze", "zenu"],
      "egjr" => ["jger"], "ijzz" => ["jizz"], "cilo" => ["clio", "coli"],
      "ghsu" => ["shug", "sugh", "ughs"], "ahyz" => ["hayz"], "agmn" => ["mang"],
      "eegp" => ["geep"], "ijsu" => ["suji"], "cisv" => ["civs"],
      "eego" => ["ogee"], "degi" => ["gied"], "afhr" => ["fahr"],
      "lsuu" => ["sulu", "ulus"], "doop" => ["pood"], "coxy" => ["coxy"],
      "abeu" => ["aube"], "biku" => ["buik"], "bbii" => ["bibi"],
      "gssu" => ["guss"], "firt" => ["frit"], "kotu" => ["touk"],
      "aglm" => ["mgal"], "egrr" => ["regr"], "apst" => ["apts", "stap"],
      "behn" => ["behn"], "aluw" => ["waul"], "deiw" => ["weid", "wied"],
      "ilpy" => ["pily"], "cdis" => ["cids"], "ahlo" => ["hola"],
      "deju" => ["jude"], "eips" => ["ipse", "spie", "sipe"], "iikt" => ["tiki"],
      "gluy" => ["guly"], "aflr" => ["farl"], "ilmt" => ["milt"],
      "bggi" => ["bigg"], "afgr" => ["graf", "frag"], "eruv" => ["uvre", "eruv"],
      "cflo" => ["clof", "floc"], "erst" => ["sert", "stre", "rets", "erst"],
      "airt" => ["rita", "tari", "rait", "tiar", "airt"],
      "aamz" => ["maza", "zama"], "bgio" => ["gobi"], "aadt" => ["adat"],
      "dmou" => ["moud", "odum", "udom", "doum"], "begr" => ["gerb"],
      "cjku" => ["juck"], "ahhs" => ["sahh", "ahhs"], "coos" => ["soco"],
      "aeir" => ["aire", "eira", "eria", "iare"], "elzz" => ["lezz"],
      "bott" => ["bott"], "aekt" => ["keat", "keta"],
      "agnu" => ["guna", "uang", "gaun", "guan"], "aely" => ["yale"],
      "aamt" => ["maat", "mata", "atma"], "diry" => ["yird"], "eejs" => ["jees"],
      "biny" => ["inby"], "fftu" => ["tuff"], "gmos" => ["mogs"],
      "dehi" => ["heid"], "eehu" => ["eheu"], "dexy" => ["dexy"],
      "izzz" => ["zizz"], "eepr" => ["pree"], "ipss" => ["psis"],
      "immy" => ["immy"], "aahp" => ["paha"], "ilnr" => ["nirl"],
      "abey" => ["abey", "baye", "abye"], "birt" => ["birt", "brit"],
      "appu" => ["paup"], "abnw" => ["bawn"], "beku" => ["buke"],
      "aenu" => ["aune"], "eems" => ["emes", "mese", "smee"],
      "ilst" => ["lits", "tils"], "imrv" => ["mirv"], "ghou" => ["hugo", "ough"],
      "alrs" => ["rals", "lars"], "eenn" => ["nene"],
      "eelv" => ["vele", "elve", "leve"], "ajmo" => ["majo"], "adfo" => ["fado"],
      "cfsu" => ["fusc"], "dgln" => ["lndg"], "epsw" => ["swep"],
      "fhou" => ["houf"], "eklu" => ["leuk", "leku", "luke"], "degl" => ["gled"],
      "bist" => ["bist", "stib"], "ekns" => ["neks", "sken"],
      "amry" => ["mary", "yarm"], "ahio" => ["ohia"], "acep" => ["cepa"],
      "effi" => ["feif"], "acen" => ["nace", "ance"], "aenv" => ["vena"],
      "bkow" => ["bowk"], "cnsu" => ["scun", "uncs"], "afsy" => ["fays"],
      "dior" => ["roid"], "mnos" => ["mons", "noms"], "impu" => ["pium"],
      "aabs" => ["saba", "abas"], "beor" => ["boer", "ebro"], "appw" => ["wapp"],
      "cort" => ["cort", "rotc", "torc"], "eikl" => ["kiel"], "aelo" => ["olea"],
      "clsu" => ["scul"], "dops" => ["dops", "spod"], "cess" => ["cess"],
      "aggw" => ["gwag"], "amox" => ["moxa"], "abgu" => ["gaub"],
      "aagi" => ["gaia"], "ceru" => ["crue", "eruc"], "bitt" => ["bitt"],
      "aijt" => ["jati"], "chil" => ["chil", "lich"], "ehii" => ["heii"],
      "emnu" => ["neum"], "ntuu" => ["tunu"], "derv" => ["verd"],
      "ejno" => ["jeon"], "cnou" => ["cuon", "unco"], "ammr" => ["marm"],
      "anrt" => ["natr", "trna"], "hlnq" => ["hlqn"], "celu" => ["luce"],
      "anrw" => ["narw", "wran", "rawn"], "aakw" => ["waka"], "abho" => ["baho"],
      "aitv" => ["vita"], "ailx" => ["axil"], "moos" => ["ooms", "soom"],
      "egos" => ["geos", "sego"], "dimo" => ["moid", "modi"], "cmor" => ["comr"],
      "emry" => ["ryme"], "ggin" => ["ging"], "abkr" => ["kbar", "krab"],
      "aikw" => ["kwai", "waik"], "eiks" => ["eiks", "seik", "sike"],
      "egno" => ["goen"], "aisv" => ["avis", "siva", "vias"], "iorv" => ["rivo"],
      "ceet" => ["cete"], "aflu" => ["fula", "lauf"], "asvv" => ["vavs"],
      "aalm" => ["amal", "mala", "alma", "amla"], "bbru" => ["burb"],
      "aers" => ["sare"], "aiop" => ["opai", "apio"], "mnpu" => ["nump"],
      "cegk" => ["geck"], "aavy" => ["yava"], "cilr" => ["cirl"],
      "beim" => ["imbe"], "aaff" => ["affa"], "lmoo" => ["mool"],
      "eiku" => ["kuei"], "inox" => ["noix"], "iops" => ["ipso", "pois", "piso"],
      "opuy" => ["youp"], "nott" => ["nott"], "ahpu" => ["hapu", "hupa"],
      "abez" => ["baze", "ezba"], "ceil" => ["ciel", "ceil"], "aglo" => ["gola"],
      "nopu" => ["noup"], "akpu" => ["puka"], "eikn" => ["enki", "nike", "kine"],
      "elsu" => ["ules", "lues"], "oqru" => ["quor"],
      "aeil" => ["aiel", "aile", "eila", "ilea"], "adgg" => ["dgag"],
      "alps" => ["salp", "alps"], "egmu" => ["geum"], "eosx" => ["esox", "oxes"],
      "aatu" => ["atua"], "howy" => ["whyo"], "aejk" => ["jake"],
      "orty" => ["royt", "ryot"], "knop" => ["ponk", "knop"],
      "chtu" => ["tchu", "utch", "chut"], "aorv" => ["voar", "arvo"],
      "imtu" => ["muti"], "cnno" => ["conn"], "adkl" => ["dalk"],
      "gisv" => ["vigs"], "aakr" => ["akra", "kara", "arak"],
      "eksy" => ["esky", "skey", "skye", "yesk", "kyes", "syke"],
      "elmr" => ["merl"], "opzz" => ["pozz"], "eekk" => ["keek"],
      "dfmm" => ["mmfd"], "chou" => ["chou"], "abdl" => ["blad"],
      "aity" => ["yati"], "ginn" => ["ginn"], "ootw" => ["woot"],
      "cnoy" => ["coyn", "cyon"], "eefm" => ["feme"], "epst" => ["spet", "sept"],
      "denr" => ["dern"], "elpu" => ["lupe", "pelu", "pule"], "gosy" => ["goys"],
      "alww" => ["wawl"], "oswy" => ["yows"], "fstu" => ["fust"],
      "botu" => ["buto"], "dmos" => ["doms"], "dosu" => ["soud", "ouds", "udos"],
      "fitx" => ["fixt"], "aggm" => ["magg"], "dloy" => ["yold", "odyl"],
      "adsw" => ["swad", "daws"], "ekty" => ["kyte"], "bfir" => ["frib"],
      "aadr" => ["adar", "arad", "raad", "rada"],
      "allo" => ["allo", "lalo", "olla"], "ekly" => ["yelk", "ylke", "kyle"],
      "ekny" => ["kyne"], "deim" => ["demi", "diem", "mide"],
      "agor" => ["argo", "goar"], "forz" => ["forz"], "fitt" => ["fitt", "tift"],
      "ehju" => ["jehu"], "aduy" => ["yaud"], "bery" => ["brey", "yerb"],
      "kost" => ["tosk"], "inux" => ["unix"], "doty" => ["doty", "tody"],
      "biks" => ["bisk"], "atuv" => ["vaut", "vatu"], "egnp" => ["peng"],
      "deen" => ["deen", "eden", "ende", "ened", "dene"], "aael" => ["alae"],
      "aimx" => ["maxi"], "chsu" => ["cush"], "imrs" => ["mirs", "smir"],
      "ehks" => ["kesh"], "auzz" => ["zuza"], "adox" => ["doxa"],
      "eety" => ["tyee"], "aovy" => ["avoy"], "inyz" => ["nizy"],
      "elsw" => ["wels"], "imst" => ["stim"], "hhot" => ["hoth"],
      "aacu" => ["auca"], "ejux" => ["jeux"], "iipp" => ["pipi"],
      "enoz" => ["zeno"], "ikpy" => ["piky"], "acku" => ["cauk"],
      "bint" => ["bint"], "csty" => ["scyt"], "chlo" => ["chol"],
      "gntu" => ["ungt", "tung"], "amyz" => ["azym", "mazy"],
      "kory" => ["roky", "york"], "chos" => ["scho", "ochs"], "ciuv" => ["uvic"],
      "ertt" => ["tret"], "aabb" => ["abba", "baba"],
      "airs" => ["aris", "rais", "rias", "sair"], "akoy" => ["oaky", "kayo"],
      "ilsy" => ["syli"], "rrty" => ["tyrr"], "eosw" => ["owse"],
      "afnv" => ["favn"], "akst" => ["taks", "kats", "skat"],
      "alnu" => ["laun", "unal", "luna", "ulan"], "eprt" => ["terp"],
      "ooru" => ["uroo"], "orwy" => ["rowy"], "doos" => ["doos", "odso"],
      "cfio" => ["fico"], "ddik" => ["kidd"], "ejnu" => ["june"],
      "ipsv" => ["vips"], "glou" => ["gulo"], "nosy" => ["noys"],
      "istu" => ["situ", "utis", "tuis"], "civy" => ["civy"], "fils" => ["fils"],
      "afky" => ["faky"], "ghos" => ["shog"], "aflm" => ["flam"],
      "eeht" => ["ethe", "hete"], "acsy" => ["cays"],
      "ehku" => ["heuk", "huke", "kueh"], "aglu" => ["gaul", "aglu", "gula"],
      "eeov" => ["evoe"], "diix" => ["dixi"], "akss" => ["skas"],
      "alls" => ["alls", "sall"], "aano" => ["aona", "anoa"], "cefo" => ["coef"],
      "emmn" => ["mnem"], "bbuu" => ["bubu"], "hptt" => ["http"],
      "aemn" => ["enam", "nema"], "hils" => ["lish"], "ooyy" => ["yoyo"],
      "emot" => ["moet"], "dloo" => ["lood", "dool"], "aars" => ["rasa"],
      "gloo" => ["gool"], "ehoy" => ["hoey"], "eemt" => ["teme"],
      "adks" => ["daks"], "gnno" => ["nong"], "eefl" => ["fele", "leef"],
      "deko" => ["doke", "doek"], "abos" => ["abos", "obas", "soba"],
      "dhoy" => ["yodh"], "afuw" => ["awfu", "wauf"], "illz" => ["zill"],
      "ikrs" => ["kirs", "kris"], "aafl" => ["alfa", "fala"], "bbel" => ["bleb"],
      "anqu" => ["quan"], "egoy" => ["ygoe"], "koyy" => ["yoky"],
      "dpsu" => ["dups"], "adpr" => ["drap", "prad", "pard"], "dder" => ["redd"],
      "ahmw" => ["hawm"], "psuy" => ["puys", "upsy"], "cmps" => ["csmp"],
      "otty" => ["toty", "tyto"], "ehly" => ["hyle"], "bdel" => ["beld"],
      "dint" => ["tind"], "giry" => ["gyri"], "adky" => ["dyak"],
      "dfio" => ["fido", "foid"], "ably" => ["yalb", "blay"], "ahpw" => ["whap"],
      "aiow" => ["iowa"], "aefk" => ["feak"], "oops" => ["soop"],
      "knot" => ["tonk"], "aerz" => ["ezra"], "achi" => ["chai", "chia"],
      "aikv" => ["kiva"], "cekw" => ["weck"], "aory" => ["oary"],
      "epty" => ["pyet"], "dems" => ["meds"], "aekp" => ["keap"],
      "booz" => ["zobo"], "clou" => ["coul", "clou"], "ennr" => ["renn"],
      "osww" => ["swow"], "birr" => ["birr"], "dfou" => ["foud"],
      "dnot" => ["dont"], "chry" => ["chry"], "aerx" => ["axer"],
      "ehht" => ["heth"], "cels" => ["cels"], "adee" => ["edea"],
      "imno" => ["omni", "mino"], "einp" => ["pien", "peni"], "ehrr" => ["herr"],
      "glnu" => ["gunl"], "eenw" => ["wene", "enew", "ween"],
      "kntu" => ["tunk", "knut"], "fipu" => ["pfui"], "ckls" => ["sclk"],
      "bikn" => ["bink"], "elny" => ["lyne"], "adde" => ["dade", "deda", "edda"],
      "adew" => ["dawe", "deaw"], "aiks" => ["kais", "siak", "sika"],
      "aopv" => ["pavo"], "biqu" => ["quib"], "effj" => ["jeff"],
      "aaps" => ["paas", "sapa"], "enwy" => ["wyne"], "auvy" => ["vayu"],
      "eiko" => ["okie"], "ainw" => ["awin", "wain"], "emoy" => ["yeom"],
      "achs" => ["chas"], "ahmu" => ["ahum", "haum", "mahu", "huma"],
      "eklr" => ["kerl"], "chno" => ["chon"], "adhl" => ["dhal", "dahl"],
      "gnow" => ["gnow", "wong"], "ehrs" => ["rehs"],
      "eers" => ["eres", "erse", "rees"], "dhor" => ["droh", "hodr"],
      "aklp" => ["plak"], "bort" => ["brot", "bort"], "ikkl" => ["klik"],
      "altu" => ["tula", "ulta"], "cehz" => ["chez"], "iprs" => ["pirs", "risp"],
      "agyz" => ["zyga", "gazy"], "fnsu" => ["funs"], "citu" => ["cuit"],
      "achr" => ["rach"], "efix" => ["fixe"], "amow" => ["mowa"],
      "eitv" => ["vite"], "egov" => ["gove"], "adls" => ["slad", "dals"],
      "nors" => ["sorn"], "asvy" => ["avys"], "ikls" => ["skil", "slik", "lisk"],
      "dnou" => ["udon"], "admw" => ["dwam"], "eely" => ["yeel", "eely"],
      "abtz" => ["batz"], "acmo" => ["maco", "moca", "camo"], "kooz" => ["kozo"],
      "aott" => ["toat"], "aejy" => ["yaje"], "emny" => ["meny"],
      "aemm" => ["emma"], "lloz" => ["zoll"], "bgiu" => ["guib"],
      "bbco" => ["cobb"], "hssu" => ["huss"], "besy" => ["beys"],
      "inpr" => ["pirn"], "iktu" => ["tuik"], "biij" => ["jibi"],
      "beet" => ["bete"], "akmn" => ["mank"], "hllo" => ["holl"],
      "crtu" => ["crut"], "oopv" => ["voop"], "oosy" => ["oosy"],
      "afit" => ["fait"], "gios" => ["gois", "gios"], "afhs" => ["fahs", "fash"],
      "acdn" => ["cand"], "ghru" => ["guhr"], "agmp" => ["gamp"],
      "aiqu" => ["quia", "quai"], "cmru" => ["crum"], "flno" => ["flon"],
      "aatv" => ["tava"], "cdio" => ["icod", "odic"], "dgis" => ["gids"],
      "agko" => ["kago"], "ddeu" => ["dued"], "noop" => ["noop", "poon"],
      "eint" => ["neti", "tien"], "gnoy" => ["gony"], "lloo" => ["lolo"],
      "ahiu" => ["huia"], "irtz" => ["ritz"],
      "elno" => ["leon", "nole", "enol", "leno"], "fouw" => ["wouf"],
      "demr" => ["merd", "derm"], "eenr" => ["reen", "erne"], "gtuu" => ["utug"],
      "empt" => ["empt"], "inst" => ["isnt", "nist"], "abrt" => ["bart"],
      "ehky" => ["hyke"], "cimo" => ["mico"], "gimu" => ["gumi"],
      "gmor" => ["morg", "gorm"], "denu" => ["unde"], "cfru" => ["curf"],
      "enpr" => ["pern"], "bizz" => ["bizz"], "insy" => ["yins"],
      "ajpu" => ["jaup", "puja"], "adly" => ["yald"], "achy" => ["chay"],
      "dinn" => ["indn"], "aeeg" => ["agee"], "bbor" => ["brob"],
      "knor" => ["nork"], "ehlu" => ["hule"], "illn" => ["nill"],
      "knoz" => ["zonk"], "lntu" => ["lunt"], "acny" => ["cany"],
      "knox" => ["knox"], "eilv" => ["levi", "vlei"], "alop" => ["alop"],
      "dess" => ["dess", "ssed"], "gpsu" => ["spug", "gups"], "akns" => ["kans"],
      "dgil" => ["glid"], "ltuu" => ["tulu"], "ceis" => ["sice"],
      "jnxy" => ["jynx"], "bouz" => ["zobu"], "glow" => ["gowl"],
      "dhlo" => ["dhol"], "hnot" => ["hont", "thon"], "iilr" => ["liri"],
      "arrt" => ["tarr"], "ejru" => ["jure"], "acdu" => ["cuda"],
      "aepr" => ["aper"], "afrs" => ["fars", "arfs", "fras"], "dhil" => ["hild"],
      "adrs" => ["sadr", "ards", "sard", "rads"], "adiq" => ["qaid", "qadi"],
      "bios" => ["bios", "obis"], "hhis" => ["hish", "shih"], "ggsu" => ["sugg"],
      "eett" => ["teet"], "hizz" => ["hizz"], "ehop" => ["peho"],
      "ettu" => ["tute"], "desw" => ["dews"], "ddsu" => ["sudd"],
      "iilt" => ["liti"], "cfil" => ["flic"], "eesu" => ["usee"],
      "eklw" => ["welk"], "crrv" => ["rcvr"], "aefw" => ["fawe"],
      "ilpr" => ["pirl"],
      "aeln" => ["alen", "laen", "lena", "nael", "nale", "neal"],
      "hlop" => ["holp"], "aenz" => ["ezan", "naze"], "glop" => ["golp"],
      "dort" => ["dort"], "bilr" => ["libr", "birl"], "eksz" => ["zeks"],
      "fhos" => ["fosh", "fohs"], "most" => ["mots"], "brux" => ["brux"],
      "adem" => ["edam", "emda"], "cltx" => ["xctl"], "eeei" => ["ieee"],
      "dnoo" => ["doon"], "lmsy" => ["lyms"], "lopw" => ["lwop", "lowp"],
      "kops" => ["kops"], "aikl" => ["ilka", "laik", "kail", "kali"],
      "ahnt" => ["hant", "tanh"], "gnyy" => ["gyny"], "ceoz" => ["coze"],
      "aost" => ["taos", "tosa", "oast", "stoa"], "emyz" => ["zyme"],
      "adnp" => ["pand"], "cdeu" => ["duce"], "deow" => ["wode"],
      "isst" => ["sist"], "deiv" => ["devi", "vide"], "adkw" => ["dawk"],
      "opty" => ["pyot"], "ehsw" => ["shew"], "essy" => ["seys", "syes"],
      "eosv" => ["voes"], "beox" => ["obex"], "ikst" => ["kist"],
      "gijn" => ["jing"], "aegl" => ["gael", "egal", "geal"], "eopr" => ["repo"],
      "bssw" => ["swbs"], "aruv" => ["urva"], "klos" => ["skol"],
      "ailo" => ["aoli"], "dowy" => ["dowy"], "aeno" => ["eoan"],
      "oory" => ["oory"], "iksv" => ["skiv"], "acfs" => ["fasc"],
      "acej" => ["ceja"], "ahkp" => ["kaph"], "ahkv" => ["kvah"],
      "aaht" => ["taha"], "gmpy" => ["gymp"], "ccee" => ["ecce"],
      "abty" => ["bayt"], "enps" => ["sepn", "neps"], "ddio" => ["dido"],
      "cekr" => ["reck"], "chiu" => ["ichu", "huic"], "hoot" => ["thoo", "toho"],
      "mpty" => ["ympt", "tymp"], "arww" => ["wraw"], "bdms" => ["dbms"],
      "ainz" => ["zain", "nazi"], "orvw" => ["vrow"], "efor" => ["orfe", "froe"],
      "ackr" => ["cark"], "abns" => ["snab"], "mmmu" => ["mumm"],
      "deew" => ["wede"], "abss" => ["sabs"], "ghuy" => ["hugy"],
      "hksu" => ["sukh"], "acce" => ["acce", "cace", "ceca"], "bdru" => ["burd"],
      "adey" => ["yade", "yead"], "afkn" => ["fank"], "akrw" => ["wark"],
      "eity" => ["yite"], "intv" => ["vint"], "egrs" => ["regs"],
      "inty" => ["tyin"], "grtu" => ["gurt"], "lmou" => ["moul", "ulmo"],
      "eopt" => ["peto", "pote", "tope"], "ijmp" => ["jimp"], "cmsy" => ["mycs"],
      "bfoo" => ["boof"], "mors" => ["mors", "roms"], "bnnu" => ["bunn"],
      "adfn" => ["fand"], "dgiu" => ["guid"], "abby" => ["abby"],
      "ccsw" => ["ccws"], "alvy" => ["lavy"],
      "aelr" => ["eral", "arle", "laer", "lare", "lear", "rale"],
      "ahor" => ["haro", "hoar", "hora"], "lruy" => ["ruly"], "dmnu" => ["mund"],
      "deir" => ["dier", "drie", "ired"], "klmo" => ["klom"], "doux" => ["doux"],
      "prsy" => ["prys"], "motw" => ["mowt"], "iorz" => ["zori"],
      "affw" => ["waff"], "bino" => ["bino", "bion"], "gnwy" => ["gwyn"],
      "hosy" => ["hoys"], "morw" => ["morw"], "bego" => ["bego"],
      "deez" => ["zeed"], "fhnu" => ["fuhn"], "cist" => ["cits", "cist"],
      "enry" => ["ryen", "yern", "reny"], "aakp" => ["kapa"], "epsx" => ["spex"],
      "orry" => ["rory"], "enru" => ["ruen"], "imox" => ["oxim"],
      "ipsu" => ["pius"], "cekt" => ["teck"], "dens" => ["neds", "sned"],
      "ceio" => ["oeci"], "aiix" => ["ixia"], "acvy" => ["cavy"],
      "orxy" => ["roxy", "oryx"], "ahrt" => ["trah", "rath", "tahr", "thar"],
      "acdi" => ["caid", "cadi"], "eekl" => ["kele", "leke"], "emsu" => ["meus"],
      "egmo" => ["gome"], "dilr" => ["dirl"], "akps" => ["pask", "spak"],
      "prru" => ["rurp"], "fgsu" => ["fugs"], "egty" => ["gyte"],
      "blpu" => ["blup"], "enst" => ["sten"], "amnu" => ["maun"],
      "aorw" => ["arow"], "aors" => ["asor", "oras", "rosa", "osar", "sora"],
      "eotz" => ["toze"], "fino" => ["fino", "foin"],
      "ahps" => ["psha", "shap", "haps", "pahs", "pash"],
      "ehnt" => ["neth", "hent"], "ppty" => ["typp"], "aeoz" => ["zoea"],
      "adim" => ["admi"], "optu" => ["toup"], "aotu" => ["outa"],
      "afno" => ["faon", "fano"], "ccir" => ["cric"], "eorx" => ["exor", "oxer"],
      "gopy" => ["pogy"], "hlmt" => ["html"], "mrty" => ["myrt"],
      "ehot" => ["hote"], "eoot" => ["otoe"], "hsuw" => ["wush"],
      "hrsu" => ["rhus"], "hoos" => ["hoos", "ohos", "soho"], "fosy" => ["foys"],
      "aafh" => ["haaf"], "cost" => ["tocs"], "cdii" => ["idic"],
      "agku" => ["gauk", "kagu"], "ditz" => ["ditz"], "dkuu" => ["kudu"],
      "agjo" => ["ajog", "gajo"], "klsu" => ["lusk"],
      "ekor" => ["oker", "kore", "roke", "kero"], "amnt" => ["mant"],
      "aagt" => ["gata"], "foyz" => ["fozy"], "ejtu" => ["teju"],
      "inry" => ["yirn"], "ceep" => ["cepe"], "ceho" => ["oche"],
      "ceky" => ["cyke"], "eegt" => ["geet"], "bhlu" => ["buhl"],
      "ajkr" => ["jark"], "diox" => ["oxid"], "advy" => ["vady", "davy"],
      "boos" => ["obos"], "aadp" => ["pada"], "gmps" => ["pmsg"],
      "anrr" => ["narr"], "abgm" => ["gamb"],
      "dlos" => ["lods", "slod", "olds", "dols"], "bins" => ["snib"],
      "ilnn" => ["linn"], "gjnu" => ["gunj", "jung"],
      "afik" => ["faik", "faki", "kaif"], "afss" => ["fass"], "kopu" => ["pouk"],
      "arry" => ["yarr"], "abio" => ["obia"], "deoz" => ["ezod"],
      "dkou" => ["kudo"], "addn" => ["dand"], "uuwz" => ["wuzu"],
      "eemu" => ["emeu"], "ahlr" => ["harl"], "gils" => ["gils", "glis", "ligs"],
      "luuz" => ["zulu"], "chuy" => ["yuch"], "adnt" => ["dant"],
      "lrtt" => ["rtlt"], "bloo" => ["bool", "loob", "obol", "bolo", "lobo"],
      "abhs" => ["shab", "bahs"], "bnno" => ["bonn"], "aalu" => ["aula"],
      "finn" => ["finn"], "estu" => ["stue", "tues", "utes"], "bcru" => ["crub"],
      "dimv" => ["mdiv"], "eprx" => ["prex"], "elst" => ["selt", "elts"],
      "bilt" => ["blit"], "aiko" => ["okia"], "gmru" => ["grum"],
      "aclx" => ["calx"], "lppu" => ["plup"], "cruy" => ["cury"],
      "gkou" => ["gouk"], "ejos" => ["jose", "joes"], "hkop" => ["koph"],
      "adeu" => ["euda"], "cdfi" => ["fdic"], "iitt" => ["titi"],
      "boru" => ["buro", "roub"], "aoqu" => ["aquo"], "acps" => ["scap", "pacs"],
      "afor" => ["afro", "faro"], "dopr" => ["dorp"], "cdmo" => ["comd"],
      "filt" => ["filt"], "ahkt" => ["kath", "thak", "khat"], "aggi" => ["giga"],
      "abgo" => ["bago", "boga"], "cehs" => ["sech"], "adhn" => ["dhan"],
      "lovv" => ["lvov"], "adev" => ["dave", "veda", "vade"], "crst" => ["crts"],
      "amoo" => ["omao"], "iprt" => ["ript"], "dirs" => ["dsri"],
      "mopw" => ["womp"], "eksw" => ["ewks"], "dnry" => ["rynd"],
      "aiss" => ["assi", "sais"], "fgnu" => ["fung"], "efgl" => ["fleg"],
      "egvy" => ["gyve"], "abhu" => ["habu"], "gkow" => ["gowk"],
      "abfr" => ["frab"], "eglo" => ["egol", "goel"], "gkru" => ["gurk"],
      "ahip" => ["pahi"], "psuw" => ["wusp"], "dflo" => ["dolf"],
      "ador" => ["ador", "orad"], "aatx" => ["taxa"], "abry" => ["brya", "yarb"],
      "ciry" => ["ricy"], "doxy" => ["doxy"], "ceim" => ["emic"],
      "ehry" => ["hery"], "eemx" => ["xeme"],
      "bein" => ["inbe", "bein", "beni", "bien", "bine"], "bbou" => ["bubo"],
      "ginr" => ["girn"], "amnr" => ["mrna"], "aekk" => ["ekka"],
      "ijlm" => ["mijl"], "bfou" => ["bufo"], "cjou" => ["jocu"],
      "celo" => ["cole"], "cehh" => ["hech"], "knru" => ["kurn", "knur"],
      "emsw" => ["wems", "smew"], "diny" => ["indy"], "agmw" => ["gawm"],
      "ceeh" => ["chee", "eech", "eche"], "aair" => ["raia"], "anrs" => ["snar"],
      "absy" => ["abys"], "aeik" => ["kaie"], "brrr" => ["brrr"],
      "eelo" => ["eole"], "irtt" => ["trit", "ritt"], "adlu" => ["udal"],
      "dsuw" => ["wuds"], "ddos" => ["dods"], "cehn" => ["chen"],
      "ltuz" => ["lutz"], "ckot" => ["tock"], "egrx" => ["grex"],
      "hioo" => ["ohio"], "mmmm" => ["mmmm"], "fmsu" => ["fums"],
      "aejr" => ["jear"], "bdir" => ["brid", "ibrd", "drib"],
      "ikuv" => ["kivu", "kuvi"], "adgs" => ["asgd"], "aefn" => ["neaf", "fane"],
      "hooy" => ["ohoy", "yoho"], "iilp" => ["ipil", "pili"], "abow" => ["abow"],
      "ajsz" => ["jasz"], "eein" => ["eine"], "ggim" => ["migg"],
      "eevy" => ["yeve"], "acho" => ["chao"], "ehip" => ["hipe"],
      "cefy" => ["fyce"], "druu" => ["urdu"], "knos" => ["kons", "sonk"],
      "dimr" => ["mird"], "amsw" => ["wasm"], "aiit" => ["itai"],
      "oott" => ["toto", "otto"], "acci" => ["caci", "caic"], "ossu" => ["sous"],
      "elmy" => ["myel", "elmy", "lyme", "yelm", "ylem"], "ilsv" => ["vlsi"],
      "ainv" => ["navi", "vina"], "dfry" => ["fyrd"], "eekt" => ["keet"],
      "cgsu" => ["scug"], "enow" => ["wone", "enow"], "airy" => ["iyar", "yair"],
      "cntu" => ["unct"], "aekn" => ["nake"], "gkps" => ["pkgs"],
      "aafn" => ["fana"], "abju" => ["baju", "juba"], "evwy" => ["wyve"],
      "arxy" => ["xray"], "druy" => ["urdy"], "illt" => ["itll"],
      "aotw" => ["atwo"], "doss" => ["dsos"], "estt" => ["tets", "stet"],
      "ahns" => ["hans", "hasn", "nash", "shan"],
      "aalp" => ["paal", "pala", "alap"], "fkow" => ["fowk"], "nopt" => ["pont"],
      "ekrs" => ["kers", "erks", "serk", "sker"], "antv" => ["vant"],
      "ekot" => ["oket", "keto"], "ffio" => ["fifo"], "ekuy" => ["yeuk", "yuke"],
      "isss" => ["siss"], "dors" => ["dors", "ords"], "hhos" => ["hohs"],
      "ilno" => ["noil"], "cgis" => ["cigs"], "insu" => ["suni"],
      "deny" => ["nyed", "dyne"], "altw" => ["walt", "twal"],
      "ailt" => ["atli", "lait", "lati", "tali"], "foru" => ["furo"],
      "ahrw" => ["whar"], "iopr" => ["prio"], "benu" => ["unbe"],
      "ajos" => ["soja"], "gino" => ["niog", "ingo"], "lmtu" => ["mult"],
      "deps" => ["sepd", "peds"], "nnsu" => ["sunn"], "flor" => ["rolf"],
      "celp" => ["clep"], "ilor" => ["lori", "loir"], "aelw" => ["alew"],
      "iiky" => ["kiyi"], "klpu" => ["pulk"],
      "ailm" => ["amil", "amli", "mila", "lima", "mali"], "cipr" => ["crip"],
      "eemn" => ["neem", "mene"], "eilx" => ["elix", "ilex"], "aeek" => ["akee"],
      "aess" => ["asse"], "cmoo" => ["moco", "coom"], "enty" => ["nyet", "tyne"],
      "ggno" => ["nogg"], "bkor" => ["bork"], "abcr" => ["carb"],
      "adjy" => ["jady"], "lmmu" => ["mulm"], "efrt" => ["reft"],
      "aclp" => ["calp"], "adei" => ["deia", "eadi"], "aesx" => ["saxe", "seax"],
      "mort" => ["mort"], "gltu" => ["gult"], "fhmt" => ["fthm"],
      "agou" => ["guao"], "ilrw" => ["wirl"],
      "aabr" => ["arab", "baar", "bara", "arba"], "efru" => ["feru", "ufer"],
      "aftt" => ["taft"], "eknu" => ["kune", "neuk"], "gkor" => ["gork", "grok"],
      "brtu" => ["burt", "trub", "turb", "brut"], "aail" => ["alai", "alia"],
      "lpuu" => ["pulu"], "iswy" => ["ywis"], "agit" => ["agit", "taig"],
      "ilss" => ["isls", "liss"], "eilz" => ["izle"],
      "dins" => ["isdn", "nids", "sind"], "eess" => ["eses", "sese", "esse"],
      "goss" => ["goss", "sogs"], "dely" => ["yeld"], "aimt" => ["amit"],
      "apsy" => ["aspy", "pyas"], "doqu" => ["quod"], "ijms" => ["jism"],
      "mnuu" => ["unum"], "kors" => ["roks", "kors"], "glny" => ["glyn"],
      "eetv" => ["evet"], "immp" => ["mimp"], "abor" => ["abor", "raob", "bora"],
      "adir" => ["dari"], "dmoo" => ["modo"], "aklu" => ["kula"],
      "mntu" => ["munt"], "howw" => ["whow"], "aahy" => ["haya", "ayah"],
      "corv" => ["corv"], "irrt" => ["tirr"], "anns" => ["anns"],
      "aefh" => ["heaf"], "aeks" => ["saek", "seak", "akes", "kaes", "keas"],
      "moss" => ["soms"], "himp" => ["himp"], "epru" => ["peru", "puer"],
      "aakt" => ["kata", "taka"], "oost" => ["oots"], "beem" => ["beme"],
      "eehs" => ["shee"], "einn" => ["inne", "nein"], "dinu" => ["idun"],
      "anwy" => ["awny", "wany"], "agnr" => ["garn", "gnar"],
      "klop" => ["klop", "polk"], "gins" => ["snig"], "moot" => ["toom"],
      "invy" => ["viny"], "bnou" => ["boun"], "apuy" => ["puya", "yaup"],
      "flsu" => ["flus"], "eknt" => ["knet", "kent"], "adrr" => ["darr"],
      "cens" => ["cens"], "adtw" => ["dawt", "wadt"], "egly" => ["gyle", "gley"],
      "bors" => ["bors", "sorb"], "goop" => ["pogo"], "dewy" => ["wyde"],
      "akrs" => ["kras", "ksar", "sark"], "eimr" => ["reim", "meri", "riem"],
      "fhow" => ["howf"], "agpu" => ["gaup"], "diss" => ["sids"],
      "eijo" => ["joie"], "kmoo" => ["moko", "mook"],
      "aamr" => ["amar", "amra", "rama", "maar", "mara"],
      "abnu" => ["baun", "nabu", "buna"], "agos" => ["agos", "goas"],
      "ejov" => ["jove"], "aknr" => ["kran", "krna", "karn", "knar"],
      "nnot" => ["tonn"], "aabk" => ["baka"], "aceh" => ["haec"],
      "ekxy" => ["kexy"], "cckw" => ["cckw"], "aprr" => ["parr"],
      "airw" => ["wair"], "hluu" => ["hulu"], "akms" => ["kasm", "maks"],
      "ghiy" => ["yigh"], "elux" => ["exul", "ulex", "luxe"],
      "eipr" => ["irpe", "prie", "peri"], "eipy" => ["yipe"],
      "aans" => ["nasa", "sana", "ansa", "anas"], "ffgo" => ["goff"],
      "epwy" => ["pewy", "wype"], "ahky" => ["kyah"], "aijm" => ["ijma", "jami"],
      "acno" => ["caon", "onca"], "aabp" => ["paba"], "etty" => ["tyte", "yett"],
      "beov" => ["bove"], "defs" => ["defs"], "orst" => ["rost", "orts"],
      "asuv" => ["suva", "vasu", "uvas", "vaus"], "borw" => ["bowr"],
      "egku" => ["kuge"], "hikr" => ["khir"], "bimo" => ["bomi"],
      "ijvy" => ["jivy"], "aabt" => ["bata"], "gnru" => ["grun", "gurn"],
      "eill" => ["elli", "lile"], "adik" => ["dika", "kaid", "kadi"],
      "nowy" => ["nowy"], "ajno" => ["joan"], "kkou" => ["koku"],
      "ccku" => ["cuck"], "eggl" => ["gleg"], "giir" => ["giri"],
      "einr" => ["erin", "rine"], "aajx" => ["ajax"], "llsu" => ["sull"],
      "elsy" => ["lyes", "sley", "leys", "lyse"], "ghiw" => ["whig"],
      "hmoo" => ["hoom", "moho", "homo"], "agnv" => ["vang"],
      "demy" => ["emyd", "demy"], "ahlp" => ["halp"],
      "adin" => ["dain", "dian", "naid"], "prty" => ["tryp"], "demo" => ["moed"],
      "acru" => ["cura"], "etvx" => ["vext"], "fgoo" => ["fogo"],
      "nops" => ["snop", "pons"], "hoss" => ["sosh", "hoss"],
      "coot" => ["coto", "toco"], "noor" => ["roon"], "affy" => ["affy", "yaff"],
      "ersu" => ["ures", "suer"], "mnot" => ["mont"], "acco" => ["coca"],
      "ehps" => ["hesp", "heps", "pehs"], "bees" => ["sebe"],
      "eesw" => ["swee", "wese"], "cowy" => ["cowy"], "ahil" => ["hila"],
      "adej" => ["deja"], "emoz" => ["mezo", "moze"], "acsu" => ["acus"],
      "gikn" => ["gink"], "eeyy" => ["eyey"], "inxy" => ["nixy"],
      "illo" => ["loli"], "cdor" => ["dcor"], "oooo" => ["oooo"],
      "afin" => ["naif"], "ajyz" => ["jazy"],
      "dino" => ["doni", "odin", "dino", "nodi"], "gilo" => ["gilo", "goli"],
      "chho" => ["hoch"], "ajkn" => ["jank"], "chip" => ["pich"],
      "emqu" => ["quem"], "kruu" => ["kuru"], "epss" => ["pess", "seps"],
      "eoos" => ["oose"], "josw" => ["jows"], "aruw" => ["waur"],
      "ikku" => ["kiku", "kuki"], "bhos" => ["bohs"], "alxy" => ["xyla"],
      "aajv" => ["java"], "ddru" => ["rudd"], "abls" => ["abls", "blas", "bals"],
      "iivx" => ["xvii"], "aghi" => ["hagi"], "aabn" => ["anba"],
      "cffo" => ["coff"], "hotu" => ["hout"], "aknw" => ["knaw", "kwan"],
      "iltu" => ["luit", "util", "litu"], "hops" => ["phos", "pohs"],
      "ggip" => ["pigg"], "ckno" => ["nock"], "enrt" => ["entr"],
      "aaln" => ["alan", "lana", "nala"], "ddin" => ["didn"],
      "opsw" => ["sowp", "pows"], "cdiu" => ["duci"], "dnwy" => ["wynd"],
      "cjoo" => ["joco"], "eegu" => ["euge"], "ahru" => ["hura", "rahu"],
      "klou" => ["louk", "oulk"], "ccot" => ["coct"], "eggy" => ["eggy", "yegg"],
      "ekps" => ["keps", "spek", "skep"],
      "aegt" => ["aget", "gaet", "tega", "geat", "geta"], "afnt" => ["fant"],
      "efrw" => ["werf"], "loxy" => ["oxyl", "xylo"], "aapw" => ["pawa"],
      "aimm" => ["ammi", "mima"], "imry" => ["yirm", "ymir", "rimy", "miry"],
      "aany" => ["anay", "yana"], "bhoy" => ["bhoy"], "noru" => ["roun", "ourn"],
      "hpsy" => ["hyps", "syph"], "lotu" => ["ulto", "tolu"], "gmpu" => ["gump"],
      "deek" => ["deek", "deke"], "emmu" => ["meum", "mume"],
      "bdou" => ["boud", "doub", "budo"], "agry" => ["gary"],
      "akty" => ["taky", "kyat"], "afix" => ["faix"],
      "dilo" => ["dilo", "doli", "diol", "loid", "olid"],
      "cino" => ["coni", "cion"], "aehs" => ["seah", "haes", "shea"],
      "egtx" => ["extg"], "eowy" => ["yowe"], "eoyz" => ["yezo", "oyez"],
      "dotw" => ["dowt", "towd"],
      "amno" => ["amon", "oman", "mano", "mona", "noma"], "cdoo" => ["codo"],
      "eipz" => ["pize"], "aasy" => ["saya"], "ehrt" => ["erth", "hert", "tehr"],
      "diln" => ["lind"], "hhnu" => ["hunh"], "hjou" => ["hoju"],
      "lmru" => ["murl"], "aefg" => ["fage"],
      "aelv" => ["eval", "leva", "lave", "vela"], "hlmo" => ["holm"],
      "eehr" => ["heer"], "hkow" => ["howk"], "airu" => ["arui", "uria"],
      "cisu" => ["suci"], "dfsu" => ["fuds"], "rrtu" => ["turr"],
      "dils" => ["sild"], "dglo" => ["glod"], "bciu" => ["cubi"],
      "dltu" => ["dult"]}
    |> Map.get(string_id)
  end
end
