defmodule Jumble.ScowlDict.Large.Length2 do
  def get(string_id) do
    %{"fg" => ["fg"], "lo" => ["ol"], "oy" => ["oy"], "sy" => ["ys"],
      "el" => ["le"], "ii" => ["ii"], "mw" => ["mw", "wm"], "nz" => ["zn"],
      "cx" => ["xc"], "pv" => ["vp"], "bk" => ["kb"], "il" => ["il"],
      "gi" => ["ig"], "nr" => ["rn"], "rw" => ["wr"], "rx" => ["xr"],
      "cy" => ["cy"], "bi" => ["bi"], "cg" => ["gc"], "au" => ["au"],
      "cq" => ["cq"], "su" => ["su"], "ss" => ["ss"], "lu" => ["lu"],
      "lr" => ["lr"], "ay" => ["ya"], "ps" => ["ps"], "tu" => ["tu", "ut"],
      "iv" => ["iv", "vi"], "lp" => ["lp"], "bt" => ["bt"], "oo" => ["oo"],
      "ev" => ["ev"], "hm" => ["mh"], "uz" => ["zu"], "gu" => ["ug"],
      "aw" => ["wa"], "lt" => ["tl"], "ad" => ["da"], "my" => ["ym"],
      "ly" => ["ly"], "vx" => ["xv"], "br" => ["rb"], "tx" => ["tx", "xt"],
      "nu" => ["un"], "oz" => ["zo"], "bg" => ["bg", "gb"], "jo" => ["jo"],
      "ik" => ["ik", "ki"], "ab" => ["ba"], "lw" => ["lw"], "ag" => ["ag"],
      "en" => ["ne", "en"], "ux" => ["xu"], "ou" => ["ou"], "iy" => ["yi"],
      "cv" => ["cv", "vc"], "uw" => ["wu"], "ir" => ["ir"], "mt" => ["tm"],
      "iu" => ["ui"], "bw" => ["bw"], "lx" => ["xl", "lx"], "rz" => ["zr"],
      "js" => ["js"], "tt" => ["tt"], "uy" => ["yu"], "hw" => ["hw"],
      "bm" => ["mb"], "ew" => ["ew"], "fm" => ["mf"], "co" => ["oc"],
      "dp" => ["dp"], "pu" => ["pu"], "ds" => ["ds"], "ct" => ["tc"],
      "wy" => ["wy"], "ci" => ["ci", "ic"], "aj" => ["ja"], "hy" => ["hy"],
      "gr" => ["rg"], "hs" => ["hs"], "ht" => ["th"], "io" => ["io"],
      "ow" => ["wo"], "bp" => ["pb"], "ln" => ["ln"], "ku" => ["ku", "uk"],
      "ns" => ["sn", "ns"], "bc" => ["bc"], "qs" => ["qs"], "nv" => ["nv"],
      "ai" => ["ia", "ai"], "mn" => ["mn"], "ky" => ["ky"], "mo" => ["om"],
      "lm" => ["lm"], "mv" => ["mv"], "ny" => ["yn", "ny"], "ey" => ["ey"],
      "ko" => ["ok", "ko"], "hv" => ["hv"], "ix" => ["ix", "xi"],
      "rv" => ["rv", "vr"], "do" => ["od"], "pq" => ["qp"], "ru" => ["ru", "ur"],
      "sz" => ["zs"], "fz" => ["fz"], "mr" => ["mr"], "nw" => ["nw"],
      "kv" => ["kv"], "dm" => ["md"], "ot" => ["ot"], "bb" => ["bb"],
      "mx" => ["mx"], "sx" => ["xs"], "fy" => ["fy"], "eu" => ["eu"],
      "op" => ["po"], "fu" => ["fu"], "an" => ["na"], "in" => ["ni"],
      "de" => ["de"], "fi" => ["fi"], "ex" => ["xe"], "jn" => ["nj"],
      "iw" => ["iw", "wi"], "bh" => ["hb"], "dx" => ["dx"], "az" => ["za"],
      "fs" => ["fs"], "sw" => ["sw", "ws"], "gn" => ["gn", "ng"], "iq" => ["qi"],
      "ak" => ["ak", "ka"], "ty" => ["yt"], "is" => ["si"], "bv" => ["bv"],
      "ef" => ["ef"], "bn" => ["bn"], "by" => ["yb"], "or" => ["ro"],
      "dy" => ["dy"], "wx" => ["xw"], "tv" => ["tv"], "nt" => ["nt"],
      "hz" => ["hz"], "fw" => ["fw"], "bf" => ["fb"], "du" => ["du"],
      "xx" => ["xx"], "bs" => ["bs"], "hn" => ["hn"], "hq" => ["qh"],
      "ar" => ["ra"]}
    |> Map.get(string_id)
  end
end
