defmodule Jumble.ScowlDict.Large.Length3 do
  def get(string_id) do
    %{"bez" => ["bez"], "loy" => ["loy"], "abo" => ["abo", "oba"],
      "aek" => ["ake", "kae", "kea"], "fgk" => ["kgf"], "imz" => ["miz"],
      "aem" => ["ame", "eam", "mea", "mae"], "ctu" => ["utc"],
      "afr" => ["raf", "arf", "fra"], "mux" => ["mux"], "zzz" => ["zzz"],
      "eoy" => ["yeo", "yoe", "oye"], "ahk" => ["hak", "kha"], "dgu" => ["gud"],
      "abd" => ["abd"], "lor" => ["orl", "lor"], "hip" => ["iph", "phi"],
      "afp" => ["afp", "fap"], "elu" => ["lue", "ule", "leu"], "swy" => ["swy"],
      "bgi" => ["gib"], "osy" => ["oys", "yos"], "pru" => ["pur", "urp"],
      "bms" => ["msb"], "abf" => ["afb"], "ikl" => ["kil"], "nru" => ["nur"],
      "gmy" => ["myg"], "bde" => ["bde"], "dsu" => ["uds", "sud"], "gox" => ["gox"],
      "lot" => ["tlo", "tol"], "bnw" => ["nbw", "wbn"], "agj" => ["gaj"],
      "cly" => ["lyc", "cly"], "elp" => ["pel", "lep"], "bgl" => ["glb"],
      "ehi" => ["hei"], "egu" => ["gue"], "eov" => ["voe"], "bel" => ["elb"],
      "frt" => ["tfr", "trf"], "htw" => ["hwt"], "gry" => ["gry"],
      "ano" => ["noa", "ona"], "aat" => ["taa"], "eil" => ["eli", "ile"],
      "iqu" => ["qui"], "hop" => ["pho", "poh"], "ggi" => ["igg"], "cfm" => ["mcf"],
      "acy" => ["acy", "cay"], "ahp" => ["aph", "hap"], "apu" => ["pau", "pua"],
      "aes" => ["aes", "ase", "eas"], "ekw" => ["ewk"], "ewy" => ["wey", "wye"],
      "afn" => ["naf"], "gkr" => ["kgr"], "psw" => ["psw"], "hlo" => ["hol"],
      "doy" => ["yod"], "clt" => ["tlc"], "iju" => ["uji"], "dop" => ["dop"],
      "imn" => ["nim"], "imm" => ["mim"], "sst" => ["tss"], "crs" => ["crs"],
      "cgi" => ["cig"], "fno" => ["fon"], "mps" => ["pms"], "fll" => ["fll"],
      "crt" => ["crt"], "eej" => ["jee"], "chi" => ["ich", "hic"],
      "aln" => ["aln", "lan"], "epy" => ["pye"], "lnp" => ["lpn"], "otv" => ["tov"],
      "ehr" => ["rhe", "reh"], "efk" => ["kef"], "hny" => ["hny"],
      "ior" => ["rio", "roi"], "fil" => ["lif", "fil"], "app" => ["ppa"],
      "lnt" => ["tln"], "lnr" => ["lnr"], "hoy" => ["hoy"], "oos" => ["oos"],
      "hku" => ["khu"], "gmt" => ["gmt"], "bfi" => ["fbi"], "amy" => ["amy", "mya"],
      "ajn" => ["jan"], "atx" => ["xat"], "frs" => ["rfs"], "ikm" => ["kim"],
      "clu" => ["cul"], "fik" => ["kif"], "rsy" => ["syr"], "aly" => ["aly"],
      "bow" => ["wob"], "prt" => ["trp"], "aoz" => ["azo", "zoa"], "ddo" => ["dod"],
      "akr" => ["kra"], "cht" => ["tch"], "mpv" => ["mvp"], "euy" => ["yue", "uey"],
      "foy" => ["foy"], "dkl" => ["dkl"], "esz" => ["sez"], "ors" => ["ros", "ors"],
      "dix" => ["dix"], "eny" => ["eyn", "nye"], "enn" => ["nne"], "beg" => ["geb"],
      "cno" => ["nco"], "fio" => ["iof"], "bsw" => ["sbw", "wbs"], "eeg" => ["eeg"],
      "dqt" => ["qtd"], "lou" => ["luo"], "kop" => ["kop"], "aot" => ["toa", "tao"],
      "ddm" => ["dmd"], "iio" => ["oii"], "auv" => ["uva", "vau"],
      "flo" => ["flo", "lof"], "bch" => ["bch", "hcb"], "ilr" => ["lir"],
      "deh" => ["edh"], "cpt" => ["cpt", "tcp"], "imo" => ["imo"], "ssw" => ["ssw"],
      "orw" => ["wro"], "dos" => ["dso", "ods"], "bfr" => ["rfb"],
      "etw" => ["ewt", "tew"], "kou" => ["kou", "ouk"], "dht" => ["thd"],
      "dei" => ["dei", "ide"], "oty" => ["yot"], "kno" => ["kon"], "bcc" => ["cbc"],
      "hpp" => ["pph"], "bio" => ["obi"], "cju" => ["cuj"], "ipv" => ["vip"],
      "lmo" => ["olm"], "ein" => ["nei", "nie"], "den" => ["ned"], "bpy" => ["byp"],
      "aim" => ["mia", "ami"], "bgn" => ["nbg"], "ekz" => ["zek"], "uzz" => ["zuz"],
      "iko" => ["oki", "koi"], "ilo" => ["ilo"], "gim" => ["gim", "mig"],
      "rsu" => ["sur", "urs"], "avx" => ["vax"], "eik" => ["eik", "ike", "kie"],
      "www" => ["www"], "cfh" => ["cfh"], "nsu" => ["uns", "nus"], "imu" => ["imu"],
      "acu" => ["uca"], "elr" => ["ler", "rle"], "afm" => ["mfa"],
      "ilp" => ["ipl", "pil", "pli"], "jnr" => ["jnr"], "duw" => ["wud"],
      "rty" => ["tyr"], "abe" => ["bae"], "opu" => ["oup", "upo"], "fot" => ["fot"],
      "orx" => ["rox"], "etz" => ["tez"], "ipt" => ["tpi"], "ahi" => ["ahi", "hia"],
      "los" => ["los"], "nov" => ["nov", "von"], "cpy" => ["cyp"],
      "dll" => ["ldl", "lld"], "emu" => ["ume", "meu"], "iiv" => ["vii"],
      "ben" => ["ebn", "nbe", "ben", "neb"], "lno" => ["nol"],
      "mst" => ["mst", "mts", "stm"], "ccm" => ["ccm"], "enp" => ["nep"],
      "alw" => ["alw"], "bll" => ["llb"], "iii" => ["iii"], "grx" => ["grx"],
      "ajk" => ["jak"], "eez" => ["zee"], "mmu" => ["umm"], "aix" => ["aix"],
      "eey" => ["yee"], "ekx" => ["kex"], "ppt" => ["ptp"], "ccf" => ["cfc"],
      "pry" => ["pyr"], "ady" => ["ady", "yad"], "aru" => ["aru", "ura"],
      "acp" => ["apc", "cpa", "pac"], "ems" => ["esm"], "suy" => ["yus"],
      "blo" => ["blo", "bol"], "ary" => ["ayr", "ary", "yar", "rya"],
      "ckw" => ["ckw"], "hps" => ["shp"], "nuw" => ["wun"], "isu" => ["sui"],
      "mow" => ["wmo"], "ddt" => ["ddt", "dtd"], "alu" => ["aul", "ula"],
      "opy" => ["poy"], "dit" => ["itd", "tid", "dit"], "ads" => ["das"],
      "ego" => ["geo"], "cls" => ["lsc"], "drt" => ["tdr"], "eht" => ["eth"],
      "een" => ["een", "ene"], "eop" => ["ope"], "mrs" => ["mrs"], "afk" => ["kaf"],
      "ahy" => ["yah"], "ast" => ["ast", "tas"], "ceh" => ["ech", "che"],
      "lmy" => ["lym"], "isy" => ["yis"], "kkk" => ["kkk"], "abc" => ["abc", "bac"],
      "bht" => ["thb"], "eru" => ["ure"], "gno" => ["gon", "nog"], "guy" => ["yug"],
      "efo" => ["eof"], "giu" => ["gui"], "hox" => ["hox"],
      "anr" => ["arn", "nar", "rna"], "ceo" => ["ceo", "eco"],
      "ipr" => ["ipr", "pir"], "ekp" => ["kep"], "adw" => ["awd", "daw"],
      "agr" => ["arg", "gra", "gar"], "cho" => ["cho", "hoc"],
      "abb" => ["bab", "abb"], "cik" => ["ick"], "cce" => ["ecc"],
      "atu" => ["tua", "uta", "tau"], "efi" => ["fei", "ife"],
      "aor" => ["aor", "ora"], "ewx" => ["wex"], "flp" => ["plf"], "owx" => ["wox"],
      "del" => ["dle", "eld"], "ruw" => ["wur"], "clo" => ["loc"],
      "iqs" => ["iqs", "qis"], "guv" => ["vug"], "ens" => ["ens"],
      "bes" => ["ebs", "sbe", "bes"], "fvw" => ["vfw"], "acl" => ["lca", "lac"],
      "ehp" => ["peh"], "gju" => ["gju"], "biu" => ["ubi"], "agv" => ["vag"],
      "nop" => ["pon"], "fms" => ["sfm"], "aer" => ["aer", "rea"], "kly" => ["kyl"],
      "orv" => ["vor"], "tuy" => ["tuy"], "aep" => ["epa"],
      "aal" => ["aal", "laa", "ala"], "ino" => ["oni"], "cnu" => ["cun", "unc"],
      "ajs" => ["saj"], "fgr" => ["frg", "grf"], "efr" => ["erf"],
      "bmo" => ["bom", "omb"], "efu" => ["feu"], "agu" => ["gau"], "agz" => ["zag"],
      "hio" => ["hoi"], "eio" => ["oie"], "dot" => ["tod"], "deq" => ["qed"],
      "afl" => ["alf"], "ahj" => ["jah"], "deo" => ["edo"], "bcd" => ["bcd", "dcb"],
      "aco" => ["oca"], "glu" => ["gul"], "stu" => ["ust", "uts"], "hmz" => ["mhz"],
      "eno" => ["neo"], "eip" => ["epi"], "suz" => ["suz"], "lsy" => ["lys"],
      "cst" => ["cst", "sct"], "ijt" => ["tji"], "eev" => ["vee"], "eps" => ["pes"],
      "tuu" => ["utu"], "cfp" => ["fcp", "pcf", "pfc"], "dtt" => ["tdt"],
      "suw" => ["usw", "wus"], "bey" => ["bey"], "abs" => ["asb", "bas", "sab"],
      "dgm" => ["mgd"], "moo" => ["oom"], "opv" => ["opv"], "exz" => ["zex"],
      "qrs" => ["qrs"], "aai" => ["iaa", "aia"], "fpx" => ["pfx"], "gps" => ["gps"],
      "dhy" => ["hyd"], "avw" => ["vaw"], "ovx" => ["vox"], "asv" => ["sav", "vas"],
      "axz" => ["zax"], "cop" => ["cpo"], "mqu" => ["qum"], "bhl" => ["lhb"],
      "bls" => ["bls"], "cdr" => ["cdr"], "fmt" => ["fmt"], "ail" => ["lai"],
      "elw" => ["lew"], "dgk" => ["dkg"], "ekn" => ["nek"], "cil" => ["cli"],
      "dor" => ["dor"], "ajr" => ["raj"], "dfo" => ["fod"], "mrt" => ["trm"],
      "ntt" => ["tnt"], "bcf" => ["bcf"], "lru" => ["lur"], "exy" => ["yex"],
      "ejo" => ["joe"], "bis" => ["sib", "bis"], "hos" => ["sho"],
      "gtt" => ["gtt", "tgt"], "als" => ["asl", "sla", "als", "las", "sal"],
      "ckt" => ["tck"], "irz" => ["riz"], "iku" => ["kui"], "fiz" => ["fiz"],
      "dex" => ["dex", "xed"], "bhr" => ["rhb"], "emq" => ["meq"], "ejn" => ["jen"],
      "cep" => ["cep", "pec"], "avv" => ["vav"], "ghz" => ["ghz"],
      "abi" => ["bai", "iba"], "apx" => ["apx", "pax"], "puw" => ["wup"],
      "inv" => ["vin"], "eem" => ["mee", "eme"],
      "itu" => ["tiu", "uit", "uti", "tui"], "ber" => ["ber", "reb"],
      "ixx" => ["xix", "xxi"], "ils" => ["sil", "lis"], "giv" => ["vig"],
      "bcu" => ["ubc"], "hir" => ["hir"], "goy" => ["ygo", "goy"],
      "cpr" => ["cpr", "prc"], "lux" => ["lux"], "muv" => ["vum"], "aht" => ["tha"],
      "pss" => ["sps"], "ist" => ["ist", "tsi", "tis"], "alt" => ["tal"],
      "eho" => ["heo"], "ams" => ["sma", "sam"], "lmw" => ["lwm"],
      "ahs" => ["sah", "ahs", "sha"], "cgt" => ["ctg", "gtc"], "bsy" => ["bys"],
      "bdh" => ["bhd"], "osw" => ["ows", "wos"], "eeh" => ["hee"],
      "iou" => ["iou", "oui"], "bru" => ["urb"], "stt" => ["tst"], "gmo" => ["mog"],
      "mtv" => ["tmv"], "cfs" => ["fcs", "scf"], "ehs" => ["ehs"], "acz" => ["zac"],
      "gis" => ["gis"], "adh" => ["adh", "dha", "dah"], "dmx" => ["mxd"],
      "dky" => ["kyd"], "cis" => ["csi", "cis"], "foo" => ["ofo", "foo", "oof"],
      "dip" => ["idp", "pid"], "ako" => ["ako", "koa", "oka"], "eim" => ["mei"],
      "dru" => ["dur", "rud", "urd"], "ado" => ["dao", "doa", "oad", "oda"],
      "rst" => ["trs"], "bef" => ["bef", "feb"], "cko" => ["ock"],
      "esy" => ["sey", "sye"], "dnp" => ["pdn"], "pst" => ["tps", "pst"],
      "dsy" => ["dys", "yds"], "imr" => ["mri", "mir"], "abw" => ["baw", "wab"],
      "beo" => ["boe", "obe"], "aev" => ["vae"], "fow" => ["fow"], "adu" => ["dau"],
      "ekv" => ["kev"], "kuy" => ["kyu"], "ggr" => ["ggr"], "imt" => ["mit", "tim"],
      "emw" => ["wem"], "aku" => ["aku"], "moz" => ["moz"], "cip" => ["cpi", "pci"],
      "adf" => ["afd"], "aas" => ["saa", "aas"], "aby" => ["aby"], "ijz" => ["jiz"],
      "aam" => ["aam", "ama", "maa"], "aaw" => ["awa"], "agw" => ["gaw"],
      "bit" => ["tib"], "dmr" => ["mrd"], "eqs" => ["esq"], "fgp" => ["pfg"],
      "hoo" => ["hoo"], "aho" => ["aho", "hao", "hoa"], "ayy" => ["yay"],
      "cgm" => ["mcg"], "cdf" => ["cdf", "cfd"], "frz" => ["rfz"],
      "noy" => ["ony", "noy"], "hms" => ["msh"], "cdu" => ["duc"], "apy" => ["pya"],
      "abr" => ["rab", "arb"], "iix" => ["xii"], "tuw" => ["wut"], "aow" => ["woa"],
      "ett" => ["tet"], "akm" => ["kam", "mak"], "ars" => ["ars", "ras", "sar"],
      "aaa" => ["aaa"], "git" => ["tig"], "ain" => ["ain"], "hnu" => ["unh", "hun"],
      "mtx" => ["mtx"], "lvy" => ["vly"], "dlo" => ["lod"],
      "bim" => ["bim", "ibm", "mib"], "nox" => ["nox"], "clx" => ["xcl"],
      "dss" => ["sds"], "erz" => ["zer", "rez"], "mot" => ["mot"], "ehl" => ["hel"],
      "qsu" => ["suq"], "gru" => ["gur"], "dpt" => ["tpd"], "asz" => ["saz", "zas"],
      "fim" => ["imf"], "afu" => ["ufa", "auf"], "eky" => ["kye"], "dds" => ["dds"],
      "cmy" => ["myc"], "gin" => ["ing", "nig"],
      "ade" => ["ade", "dea", "ead", "dae"], "jms" => ["jms"], "bmp" => ["mpb"],
      "iim" => ["imi"], "abu" => ["abu"], "qrt" => ["qtr"], "ghq" => ["ghq"],
      "aci" => ["cai"], "bot" => ["tob"], "dls" => ["lsd"], "lny" => ["lyn"],
      "bos" => ["bos"], "lmt" => ["ltm"], "elo" => ["leo", "loe"], "egs" => ["seg"],
      "iks" => ["ksi"], "acf" => ["caf"], "ach" => ["ach", "cha"], "nww" => ["wnw"],
      "imp" => ["ipm"], "gos" => ["gos", "sog"], "eor" => ["oer"], "epz" => ["zep"],
      "aar" => ["ara"], "ees" => ["ese"], "enz" => ["zen"], "ikp" => ["pik"],
      "lpw" => ["lwp"], "eft" => ["fet", "tef", "eft"], "adi" => ["ida"],
      "llu" => ["ull"], "his" => ["ihs", "shi", "ish"],
      "eir" => ["eir", "rie", "rei"], "ajp" => ["jap"], "dmu" => ["dum"],
      "agm" => ["gam"], "bho" => ["boh"], "fir" => ["fri", "rif"], "nwy" => ["wyn"],
      "doz" => ["dzo"], "ijm" => ["jim"], "ost" => ["tos"], "bfu" => ["fub"],
      "irx" => ["rix"], "isw" => ["wis"], "cns" => ["cns"], "oxy" => ["yox", "oxy"],
      "izz" => ["ziz"], "egj" => ["jeg"], "puy" => ["puy"], "ael" => ["ela"],
      "emo" => ["moe"], "cem" => ["ecm"], "dhp" => ["dph", "phd"], "gnt" => ["tgn"],
      "sww" => ["wsw"], "cdi" => ["cid"], "ory" => ["ory", "yor"], "opz" => ["poz"],
      "huy" => ["yuh"], "ijn" => ["jin"], "giz" => ["zig"], "dfi" => ["fid"],
      "cjl" => ["jcl"], "anu" => ["una", "anu"], "gor" => ["rog"],
      "akl" => ["kal", "lak"], "air" => ["ira", "rai", "ria"], "gou" => ["gou"],
      "elm" => ["lem", "mel"], "cru" => ["ruc", "cru"], "afw" => ["waf", "faw"],
      "ios" => ["iso", "osi", "ios", "ois"], "lop" => ["olp"], "inz" => ["zin"],
      "diu" => ["iud", "dui"], "kow" => ["kow", "owk"], "ggo" => ["gog"],
      "bdm" => ["mbd"], "etu" => ["tue", "ute"], "ptt" => ["ptt"], "dej" => ["jed"],
      "aap" => ["apa"], "bns" => ["bns"], "blr" => ["brl"], "lxx" => ["lxx"],
      "iot" => ["toi"], "afo" => ["fao"], "oop" => ["oop"], "osz" => ["ozs", "zos"],
      "not" => ["ont"], "ttx" => ["txt"], "dee" => ["dee"], "any" => ["yan"],
      "imw" => ["wim"], "csw" => ["csw"], "ely" => ["eyl", "ley"], "ffi" => ["iff"],
      "ejw" => ["jew"], "adk" => ["dak"], "ghp" => ["gph"], "adz" => ["zad"],
      "aop" => ["opa", "poa"], "crv" => ["vcr"], "dgp" => ["gdp", "gpd"],
      "luz" => ["luz"], "luu" => ["ulu"], "ssu" => ["ssu", "sus"],
      "atw" => ["twa", "taw", "wat"], "nqu" => ["unq"], "hoz" => ["zho"],
      "abh" => ["hab"], "ahu" => ["ahu", "auh", "hau"], "els" => ["les", "els"],
      "opr" => ["por"], "lpu" => ["plu", "pul"], "ekl" => ["lek"], "aks" => ["kas"],
      "apt" => ["atp"], "cor" => ["cro", "roc"], "egi" => ["gie"],
      "alp" => ["apl", "alp"], "bbs" => ["bbs"], "adr" => ["dar", "ard"],
      "npu" => ["unp"], "art" => ["tra"], "bfs" => ["bsf", "fsb"], "cps" => ["csp"],
      "cfi" => ["ifc"], "ekr" => ["erk"], "asy" => ["yas", "ays"],
      "dde" => ["ded", "edd"], "brw" => ["bwr"], "dfu" => ["fud"],
      "cot" => ["cto", "otc", "toc"], "aww" => ["waw"], "lnu" => ["nul", "unl"],
      "bfn" => ["bnf"], "egk" => ["ekg"], "arz" => ["zar"], "bmr" => ["bmr"],
      "cel" => ["cel"], "atz" => ["azt", "zat"], "ait" => ["tai", "ait"],
      "oqu" => ["quo"], "gmp" => ["gpm"], "aab" => ["aba"],
      "dow" => ["owd", "wod", "dow"], "eos" => ["eos", "oes", "ose"],
      "dmt" => ["mtd"], "eju" => ["jeu"], "ptu" => ["tup"], "hho" => ["hoh"],
      "egz" => ["gez"], "emt" => ["tem"], "aqt" => ["qat"], "dlr" => ["rld"],
      "kor" => ["rok", "kor"], "lps" => ["spl"], "adn" => ["dna", "nad", "dan"],
      "aan" => ["naa", "ana"], "isx" => ["xis"], "fmu" => ["fum"], "elt" => ["elt"],
      "muu" => ["umu"], "abt" => ["abt"], "nsy" => ["nys", "sny"],
      "alo" => ["alo", "lao", "loa", "ola"], "lrt" => ["tlr"], "ckp" => ["kpc"],
      "auy" => ["ayu"], "fhs" => ["fsh", "shf"], "moy" => ["moy", "yom"],
      "kst" => ["tsk"], "hii" => ["ihi"], "aew" => ["wae"], "ipp" => ["ppi"],
      "xxx" => ["xxx"], "mou" => ["mou"], "efh" => ["ehf", "feh"],
      "cee" => ["eec", "cee"], "ahr" => ["rha", "rah"], "gsu" => ["gus", "ugs"],
      "itw" => ["twi"], "bdi" => ["dib"], "agn" => ["gan"], "bpx" => ["pbx"],
      "ins" => ["isn", "nis"], "fho" => ["foh"], "cpp" => ["pcp"], "doo" => ["doo"],
      "irs" => ["irs", "sri"], "akz" => ["zak"], "aeh" => ["hae"],
      "agy" => ["agy", "yag"], "fsu" => ["ufs"], "gov" => ["vog"], "rtu" => ["tur"],
      "bpp" => ["ppb"], "otu" => ["tou"], "fis" => ["sif"], "dks" => ["dks"],
      "clr" => ["crl"], "acw" => ["wac"], "oox" => ["oxo"], "asw" => ["swa", "aws"],
      "acd" => ["dca"], "fou" => ["ouf", "ufo", "fou"], "hry" => ["rhy"],
      "lmu" => ["lum"], "oor" => ["oor", "roo"], "eer" => ["eer", "ree"],
      "mmy" => ["mym"], "nnu" => ["unn"], "dny" => ["dyn"], "ioy" => ["iyo", "yoi"],
      "mos" => ["som", "oms"], "rux" => ["rux"], "mpt" => ["tpm"],
      "hmt" => ["thm", "tmh"], "irt" => ["rti", "tri"], "afy" => ["fay"],
      "cft" => ["ctf"], "din" => ["nid"], "hiu" => ["hui"], "gil" => ["lig"],
      "ery" => ["eyr"], "elz" => ["lez", "zel"], "ags" => ["asg", "ags"],
      "nnw" => ["nnw"], "hmo" => ["hmo", "hom", "mho"], "ikr" => ["kir"],
      "inr" => ["rin"], "eis" => ["ise", "sie", "sei"], "btv" => ["bvt"],
      "akt" => ["tak", "kat"], "egt" => ["gte", "teg"], "acg" => ["cag"],
      "dhh" => ["hhd"], "coz" => ["coz"], "isz" => ["isz"], "lms" => ["mls", "sml"],
      "xyz" => ["xyz"], "osv" => ["sov"], "bek" => ["keb"], "nos" => ["ons"],
      "ers" => ["esr", "ers"], "adp" => ["dap"], "jow" => ["jow"], "koy" => ["yok"],
      "elv" => ["lev"], "ilm" => ["lim"], "grs" => ["grs"], "afq" => ["qaf"],
      "dlu" => ["lud"], "ess" => ["sse", "ess"], "der" => ["erd"], "fip" => ["fip"],
      "chn" => ["chn"], "cdm" => ["cmd"], "ccs" => ["csc"], "amw" => ["awm"],
      "oot" => ["oto", "oot"], "aik" => ["aik", "kai"], "ans" => ["nas", "san"],
      "dio" => ["ido"], "apw" => ["wap"], "tvw" => ["wtv"], "dju" => ["jud"],
      "lst" => ["lst", "slt"], "acv" => ["cva"], "abn" => ["abn"], "aiw" => ["iwa"],
      "dhl" => ["hdl", "hld"], "ort" => ["ort"], "des" => ["des", "esd", "sed"],
      "bce" => ["bec", "ecb"], "ahn" => ["han"], "ahh" => ["ahh"], "ahv" => ["hav"],
      "dux" => ["dux"], "rtw" => ["rtw"], "amn" => ["mna", "nam"],
      "ajt" => ["jat", "taj"], "bfl" => ["flb"], "iow" => ["iwo"], "pps" => ["pps"],
      "ehh" => ["heh"], "hrw" => ["whr"], "ppr" => ["prp"], "aip" => ["pia"],
      "ghm" => ["mhg"], "kps" => ["pks"], "ivx" => ["xiv", "xvi"], "div" => ["vid"],
      "hpt" => ["tph", "pht"], "ksu" => ["suk"], "aag" => ["aga"], "cmo" => ["moc"],
      "ejr" => ["jer"], "alm" => ["mal"], "dkm" => ["dkm"], "rtt" => ["trt"],
      "cfy" => ["fcy"], "ltu" => ["lut"], "bdl" => ["bld"], "aov" => ["avo"],
      "gnp" => ["gnp"], "erw" => ["rew"], "cmp" => ["cpm"],
      "amu" => ["aum", "mau", "uma", "amu"], "cdg" => ["cdg", "gcd"],
      "mtu" => ["mut"], "ceg" => ["ecg"], "arx" => ["arx", "rax"], "osu" => ["ous"],
      "vxx" => ["xxv"], "ahl" => ["lah"], "etx" => ["tex"], "grr" => ["grr"],
      "dem" => ["dem"], "amo" => ["mao", "oam", "moa"], "ago" => ["goa"],
      "dfr" => ["fdr"], "msu" => ["ums"], "aav" => ["ava"], "dey" => ["yed", "dey"],
      "noo" => ["noo", "oon"], "cpv" => ["pvc"], "ccy" => ["cyc"],
      "gio" => ["goi", "gio"], "ais" => ["sai", "ais"], "eko" => ["oke"],
      "hno" => ["noh"], "dgi" => ["gid"], "hiv" => ["hiv"],
      "akw" => ["awk", "kwa", "kaw"], "abv" => ["abv"], "cds" => ["scd"],
      "ccr" => ["crc"], "epr" => ["pre"], "chl" => ["hcl"],
      "hpu" => ["phu", "puh", "hup"], "lpp" => ["ppl"], "bno" => ["bon"],
      "dhu" => ["dhu", "hud"], "oyy" => ["yoy"], "asu" => ["usa", "sau"],
      "aky" => ["kay"], "drs" => ["dsr"], "buz" => ["buz"], "bps" => ["pbs"],
      "gty" => ["tyg"], "ety" => ["tye"], "aty" => ["yat", "tay"], "gtu" => ["ugt"],
      "aos" => ["oas", "sao"], "krs" => ["krs"], "apv" => ["pav", "pva"],
      "eiv" => ["ive", "vei"], "aen" => ["nea", "ean", "ane"], "hik" => ["khi"],
      "bop" => ["pob"], "hin" => ["hin"], "iop" => ["ipo"], "glo" => ["gol"],
      "aio" => ["iao"], "hkz" => ["khz"], "cks" => ["csk"],
      "afh" => ["fha", "haf", "fah"], "gnu" => ["ung"], "dqs" => ["sqd"],
      "hsu" => ["uhs", "ush"], "bgu" => ["gub"], "fgn" => ["fgn"],
      "hst" => ["hts", "sht", "tsh"], "atv" => ["tav"], "ahw" => ["wah", "wha"],
      "nor" => ["ron"], "dou" => ["oud", "udo"], "diq" => ["qid"],
      "bko" => ["bok", "kob"], "aij" => ["jai"], "apr" => ["apr"],
      "tty" => ["tty", "tyt"], "llm" => ["llm"], "otw" => ["owt"],
      "eku" => ["euk", "kue", "uke"], "fgi" => ["gif"],
      "abm" => ["abm", "mab", "mba", "bam"], "for" => ["orf"], "cmw" => ["cwm"],
      "blt" => ["blt"], "dft" => ["dft"], "akn" => ["kan", "nak"], "egy" => ["gye"],
      "iuz" => ["uzi"], "efs" => ["efs", "fes"], "alr" => ["lar"], "cuz" => ["cuz"],
      "bco" => ["boc"], "ekt" => ["ket"], "owy" => ["woy", "yow"],
      "ehy" => ["hye", "yeh"], "fru" => ["urf"], "cet" => ["cte", "ect", "tec"],
      "aeu" => ["eau"], "aiv" => ["iva"], "efl" => ["efl"], "eoz" => ["ezo"],
      "irw" => ["wir"], "efn" => ["nef"], "adj" => ["jad"], "ims" => ["mis"],
      "boo" => ["obo"], "gpu" => ["gup"], "anw" => ["naw", "awn"], "cjw" => ["wjc"],
      "erx" => ["rex"], "gop" => ["gop"], "agt" => ["gat"], "fsz" => ["sfz"],
      "kln" => ["kln"], "lmx" => ["mlx"], "fsy" => ["fys"], "kos" => ["sok", "kos"],
      "abk" => ["kab"], "guz" => ["guz"]}
    |> Map.get(string_id)
  end
end
