defmodule Jumble.ScowlDict.Size70.Length16 do
  def get(string_id) do
    %{"aabcgiilnorsstuu" => ["subcartilaginous"],
      "aeeghiilnnprttvy" => ["hyperventilating"],
      "acciimnnoorrsttu" => ["macroinstruction"],
      "acefgiinnoorrstu" => ["reconfigurations"],
      "deehimnnnorrstuu" => ["undernourishment"],
      "aegiilnnoorsssuv" => ["vaingloriousness"],
      "abeehiilnnopssst" => ["inhospitableness"],
      "aceeeffiiilnsttu" => ["ineffectualities"],
      "aacdeeeinrrrsttu" => ["undersecretariat"],
      "cceeehilmorrstty" => ["electrochemistry"],
      "aceeiilnnnnorttt" => ["intercontinental"],
      "bcdeeeeiilnnrsss" => ["incrediblenesses"],
      "acghiilllnooorty" => ["ornithologically"],
      "ceeiilooppprrtvy" => ["proprioceptively"],
      "acdeeilnnoosssst" => ["disconsolateness"],
      "aeeeeilnprrsttvy" => ["representatively"],
      "aeiimnnooprssssu" => ["parsimoniousness"],
      "adeeiimnnorssttu" => ["underestimations"],
      "aeeiiilllmmnnprs" => ["premillennialism"],
      "aacehillmorsttty" => ["thermostatically"],
      "acdefiiiimnnnost" => ["indemnifications"],
      "cdeegiillnooostu" => ["oligonucleotides"],
      "acdeeeehimnnrtuv" => ["underachievement"],
      "aaaceghinnoprtty" => ["acanthopterygian"],
      "bceehiilmnnoprsy" => ["incomprehensibly"],
      "aeeinnoosssstttu" => ["ostentatiousness"],
      "acdeeiilnpprrtuy" => ["perpendicularity"],
      "acceelnnoopssttv" => ["postconvalescent"],
      "aciiilmnnooopstt" => ["antimonopolistic"],
      "ceehilmoorssssst" => ["schoolmistresses"],
      "acceehillnnortty" => ["ethnocentrically"],
      "aceiilmnnnoosstv" => ["conventionalisms"],
      "aceeeiilnnnqsstu" => ["sesquicentennial"],
      "aaeeiilnnoprrttt" => ["interpretational"],
      "abeeiiiilrrrttvy" => ["irretrievability"],
      "aaeeeilrrrrstttx" => ["extraterrestrial"],
      "aceghhiilllopryy" => ["hieroglyphically"],
      "cciinnoorssstttu" => ["constructionists"],
      "eeeinnnoprssssuv" => ["unresponsiveness"],
      "aaccehhhilnnopry" => ["rhynchocephalian"],
      "acdeefinnoprstuu" => ["superfecundation"],
      "aaeeeilnnoprrstt" => ["representational"],
      "abcegiiillmooost" => ["bioclimatologies"],
      "ceeehmoorrrtttyy" => ["erythrocytometer"],
      "aaccffgiiknnorrt" => ["narcotrafficking"],
      "acdeeeeffnnssstu" => ["unaffectednesses"],
      "aeeeiinnoprrrttt" => ["reinterpretation"],
      "cdeeeeiinnrsssst" => ["indiscreetnesses"],
      "aeehiimnoprsstvy" => ["hypervitaminoses"],
      "cceehimoprrsstty" => ["spectrochemistry"],
      "aeeimnnorrrstttu" => ["neurotransmitter"],
      "acdeehiilmnoprty" => ["diacetylmorphine"],
      "aacdehhiilmoprrt" => ["hermaphroditical"],
      "aaaacghilmnoprst" => ["phantasmagorical"],
      "aeiiiiinnrsstttv" => ["intransitivities"],
      "aeeehiilmmnnopps" => ["epiphenomenalism"],
      "aabiiilnnnnotttu" => ["tintinnabulation"],
      "aaeeeiillnrssttv" => ["alliterativeness"],
      "abeiiiiillmpsstu" => ["implausibilities"],
      "bceeeeijnsssstuv" => ["subjectivenesses"],
      "aabeeelnnnorsssu" => ["unreasonableness"],
      "aaccdgiiinnnortt" => ["contraindicating"],
      "bdddeeilmnnoossy" => ["bloodymindedness"],
      "aaacchilloprstty" => ["catastrophically"],
      "abeeeeilmnnprsst" => ["impenetrableness"],
      "ccddeeeinnnossst" => ["disconnectedness"],
      "cciimnnoorsssttu" => ["misconstructions"],
      "cceeiilnnnosssuv" => ["inconclusiveness"],
      "aacghhillooprrty" => ["orthographically"],
      "accdegiinnnnostu" => ["discountenancing"],
      "beeiiiiilmprssst" => ["permissibilities"],
      "ceeiinoopprrrstv" => ["overprescription"],
      "aceiinnorrrstttu" => ["counterirritants"],
      "bceiilnnoorrttvy" => ["incontrovertibly"],
      "abeeghiiilnnstux" => ["inextinguishable"],
      "aaciijlllnorstuy" => ["journalistically"],
      "abehiloorrssstty" => ["erythroblastosis"],
      "aacghhiillloprty" => ["lithographically"],
      "abceimnnorssstuu" => ["rambunctiousness"],
      "aacccehiinrrsttu" => ["uncharacteristic"],
      "aacehiillpprrsty" => ["periphrastically"],
      "aceeghlmooprrtyy" => ["electromyography"],
      "aacdeeghiiloprrt" => ["radiotelegraphic"],
      "aacdeeeefhmnssss" => ["shamefacednesses"],
      "adeeeggiinorsstt" => ["desegregationist"],
      "ddeeeelmnnoprtuv" => ["underdevelopment"],
      "aefilnnnoooprsss" => ["nonprofessionals"],
      "abccefiiijnoostt" => ["objectifications"],
      "aaccgiillllmooty" => ["climatologically"],
      "eeeehinnpprrrstu" => ["entrepreneurship"],
      "aadeiiilmnrsttvy" => ["administratively"],
      "ceeeiinpprrssstv" => ["prescriptiveness"],
      "aaccdeiimnrstttu" => ["circumstantiated"],
      "aeeiinoprrsssttv" => ["preservationists"],
      "aaeiiilnnnorsttt" => ["internationalist"],
      "aaaaeiilmnnprrst" => ["parliamentarians"],
      "ccceeiilmnoorrst" => ["microelectronics"],
      "aabdeeghinorrstw" => ["weatherboardings"],
      "abeeeiilmnnnrsst" => ["interminableness"],
      "abcehimnnnooopru" => ["bronchopneumonia"],
      "acdgiiiimnnnrstu" => ["undiscriminating"],
      "abehiiiilnsttuxy" => ["inexhaustibility"],
      "bceeiiiilpsssttu" => ["susceptibilities"],
      "aaceegiilnrrsttu" => ["rectangularities"],
      "aaccdeehhlooprst" => ["cephalochordates"],
      "aefillnnooprssuy" => ["unprofessionally"],
      "aacghhilllmooopt" => ["ophthalmological"],
      "eeiiimmnnooprsss" => ["neoimpressionism"],
      "aaceghlloprrrsty" => ["crystallographer"],
      "aabbhiiiilnnttuy" => ["uninhabitability"],
      "aeeegiinnnprrttt" => ["interpenetrating"],
      "aaabeellnnrssstt" => ["translatableness"],
      "adeeeiimnnorrstt" => ["redeterminations"],
      "aeegimnnnsssssuu" => ["unassumingnesses"],
      "acceeillllorttyy" => ["electrolytically"],
      "deehillnoorrsstw" => ["otherworldliness"],
      "acgiiiimnnnnnort" => ["nonincriminating"],
      "aacciillmnrsttuy" => ["circumstantially"],
      "cghhiloooppssyyy" => ["psychophysiology"],
      "cdeegilmnnorssuu" => ["curmudgeonliness"],
      "accceeiloorssttu" => ["electroacoustics"],
      "accefiiillnnstuy" => ["unscientifically"],
      "abciilorrrssttuu" => ["arboriculturists"],
      "aeeiillnnqssttuy" => ["quintessentially"],
      "aceeiiiilnsstttx" => ["existentialistic"],
      "aaacdeilllmmorty" => ["melodramatically"],
      "abbcdgiilmnoostu" => ["discombobulating"],
      "acceeillooprssty" => ["stereoscopically"],
      "aabceiloprrsstuu" => ["paratuberculosis"],
      "acehhiopprssstty" => ["psychotherapists"],
      "aacefiinorsssstt" => ["satisfactoriness"],
      "bcciiinoorsstttu" => ["obstructionistic"],
      "acelnooopprrsstu" => ["counterproposals"],
      "aaceeinnrsstttuv" => ["unattractiveness"],
      "ceeehlooopprttty" => ["photoelectrotype"],
      "bbehilmmmooorsst" => ["thromboembolisms"],
      "aceefiiilmnopstx" => ["exemplifications"],
      "aaaaacgillmmnrty" => ["anagrammatically"],
      "aeeiinnorrsssstt" => ["transitorinesses"],
      "cceghhlnooopstyy" => ["psychotechnology"],
      "aabeeeillnnsssuv" => ["invaluablenesses"],
      "abdeeiilnnpssstu" => ["indisputableness"],
      "aeeghmmmnooprsty" => ["sphygmomanometer"],
      "aaceefillnossssu" => ["fallaciousnesses"],
      "aaceeiiimnnrssst" => ["necessitarianism"],
      "deeehiilnopprsty" => ["pyelonephritides"],
      "accciilmooprrstu" => ["ultramicroscopic"],
      "acdeeiinnorsstuu" => ["consuetudinaries"],
      "aaceilnnnnorsttt" => ["transcontinental"],
      "adeeegiknnprrrst" => ["prekindergartens"],
      "adeeeinnnrrssstu" => ["unrestrainedness"],
      "aaggiiilnnoosttu" => ["isoagglutination"],
      "adeiinooopprrstt" => ["disproportionate"],
      "aaceiiilllrsttvy" => ["relativistically"],
      "ahhmnoooopprrstu" => ["anthropomorphous"],
      "acdeeiiiilnorstt" => ["directionalities"],
      "adeeeeimmnorssst" => ["immoderatenesses"],
      "accegiinnnooprrt" => ["nonreciprocating"],
      "bbbbeefgiiilrstt" => ["flibbertigibbets"],
      "cdeehiinorrssttw" => ["creditworthiness"],
      "ahijlnoooprssttu" => ["photojournalists"],
      "aaccdiimmmnooost" => ["accommodationism"],
      "eeiiinnnorsstttv" => ["interventionists"],
      "acdeiiillmnorttu" => ["multidirectional"],
      "accgiillmmooorty" => ["microclimatology"],
      "aeeiillnnossssuv" => ["villainousnesses"],
      "abceehhlmnnooprs" => ["rhombencephalons"],
      "abcdeiiilnprttuy" => ["unpredictability"],
      "abefgiilnortttuy" => ["unforgettability"],
      "aacfiilnorssttuy" => ["unsatisfactorily"],
      "acghiillmnoopsyy" => ["physiognomically"],
      "ceeehhmmoooorrst" => ["heterochromosome"],
      "aceeilmmnnorstuy" => ["incommensurately"],
      "deeflnooprsssstu" => ["dessertspoonfuls"],
      "aceeginnorrsttuu" => ["countersignature"],
      "bcceinnoosssssuu" => ["subconsciousness"],
      "cceeehiimoprttvy" => ["chemoreceptivity"],
      "aceeiinnosssstuu" => ["incautiousnesses"],
      "aaeegiilmnnosttz" => ["segmentalization"],
      "ceeiilnoprssssuu" => ["superciliousness"],
      "ccgiiiilnoossstu" => ["sociolinguistics"],
      "accdeeeiimnoppst" => ["appendicectomies"],
      "bceeeiiiilpprstt" => ["perceptibilities"],
      "aggiilmmmnoprrtu" => ["multiprogramming"],
      "aaeeilmnprrrsttu" => ["preternaturalism"],
      "aadeiilmnnnnootu" => ["undenominational"],
      "aaghhooopprrstty" => ["astrophotography"],
      "aacdeeiilnnnqrtu" => ["quadricentennial"],
      "accceeehilmnorst" => ["electromechanics"],
      "aaccefiiilnorsst" => ["reclassification"],
      "beeeiiilnrrsssst" => ["irresistibleness"],
      "ceeeiimnorrssstu" => ["meretriciousness"],
      "abefilnooprssssu" => ["subprofessionals"],
      "cceehiilooprttty" => ["photoelectricity"],
      "aceeimnnnooprstu" => ["pronunciamentoes"],
      "aaacehilllmnpruy" => ["alphanumerically"],
      "beiiiiilmmprssty" => ["impermissibility"],
      "ceeiilmnnoopttvy" => ["noncompetitively"],
      "beeiinoqsssstuuu" => ["ubiquitousnesses"],
      "aceehillnooprsty" => ["stereophonically"],
      "aghhhilooopprtty" => ["photolithography"],
      "adeehhiilmooppsu" => ["pseudohemophilia"],
      "cehiinnooprssssu" => ["connoisseurships"],
      "aaaccehiinnpqstu" => ["acquaintanceship"],
      "aeeeghnnooprrtty" => ["roentgenotherapy"],
      "aaceeiilnnrssttu" => ["inarticulateness"],
      "aaceiilllrrsstuy" => ["surrealistically"],
      "aabccgiilmmnrtuu" => ["circumambulating"],
      "adeeeghhilnrsstt" => ["lightheartedness"],
      "acghhinooopprtyz" => ["photozincography"],
      "ceeginnnorrsttuu" => ["counterinsurgent"],
      "aeeiiinnnrsssttv" => ["intransitiveness"],
      "aceeeinnoorsstvv" => ["neoconservatives"],
      "aehhiiopprssstty" => ["physiotherapists"],
      "bdehiilnoorssstt" => ["bloodthirstiness"],
      "aabceehilnnrsstu" => ["uncharitableness"],
      "aabbddegiiilorty" => ["biodegradability"],
      "ceegilmmoooorrty" => ["micrometeorology"],
      "ceeiinopssssssuu" => ["suspiciousnesses"],
      "acghhimooopprrty" => ["photomicrography"],
      "accdegiillnnooor" => ["endocrinological"],
      "achiillorrstttuu" => ["horticulturalist"],
      "bciiiilnoprrttuy" => ["incorruptibility"],
      "aeeeiinnnoprrttt" => ["interpenetration"],
      "ceehhiimooprsstt" => ["photochemistries"],
      "addeeeffiinnrttu" => ["undifferentiated"],
      "aacceeilmnoprstu" => ["microencapsulate"],
      "aaiiimnooppprrst" => ["misappropriation"],
      "aceeemnnorsttttu" => ["counterstatement"],
      "aehiiimpprrsttuy" => ["hyperpituitarism"],
      "abceiilmmnorstuy" => ["commensurability"],
      "accehillmnoorrty" => ["chronometrically"],
      "aabiiilnnsstttuy" => ["insubstantiality"],
      "cceeeefgilnnnort" => ["teleconferencing"],
      "abeeiiilnoprrtty" => ["interoperability"],
      "aaacchillnopstyy" => ["psychoanalytical"],
      "aghhnoooopprrssu" => ["organophosphorus"],
      "bceiinooprrsstuv" => ["oversubscription"],
      "eiinooppssssstuu" => ["suppositiousness"],
      "aaaccghilloprrty" => ["cartographically"],
      "aaacehiiillmmnsv" => ["machiavellianism"],
      "acefiiinnooprsst" => ["personifications"],
      "aaceeehioprrsttu" => ["aerotherapeutics"],
      "aabeeiiillnrsttu" => ["unalterabilities"],
      "aceeiilnnoqsttuy" => ["consequentiality"],
      "aacceiimnrsstttu" => ["circumstantiates"],
      "aaccegiknnortttu" => ["counterattacking"],
      "acceilnnoorrsttu" => ["reconstructional"],
      "acghhhilmoooprrt" => ["chromolithograph"],
      "ceeehimnnnooprsv" => ["noncomprehensive"],
      "aaceghhillnoprty" => ["ethnographically"],
      "beeiiiilnprsstxy" => ["inexpressibility"],
      "cceeehiilmmnnstu" => ["chemiluminescent"],
      "aeeeiilmnprssttx" => ["experimentalists"],
      "aeggillnoooorsty" => ["otolaryngologies"],
      "aacghhilloopprty" => ["photographically"],
      "cceeinnorsssttuv" => ["constructiveness"],
      "aciilnnnoostttuu" => ["unconstitutional"],
      "abceiiilnnosttty" => ["incontestability"],
      "aaeilmnprrssstuu" => ["supernaturalisms"],
      "adeeeehhlnorsstw" => ["wholeheartedness"],
      "acdiiiiimnnnorst" => ["indiscrimination"],
      "aceegmnnorrsttuu" => ["counterarguments"],
      "acceeiiloorrrstt" => ["arteriosclerotic"],
      "cceeinnooprssssu" => ["preconsciousness"],
      "acceiillmnorrsty" => ["microcrystalline"],
      "ahhimmnooopprrst" => ["anthropomorphism"],
      "adehhiimmoprrsst" => ["hermaphroditisms"],
      "aaceeiinorssssuv" => ["avariciousnesses"],
      "aaceeghimnoprrst" => ["cinematographers"],
      "aaacceeiilnopssu" => ["caesalpiniaceous"],
      "aaccciilllnoosty" => ["iconoclastically"],
      "aaccdeghiiloorss" => ["oligosaccharides"],
      "adeeiiimnnnorstt" => ["indeterminations"],
      "aeeelmnooprstuxy" => ["extemporaneously"],
      "adeelmnooorssssu" => ["malodorousnesses"],
      "abeeeelnnoprssss" => ["personablenesses"],
      "aaaiillmnnorsttu" => ["ultranationalism"],
      "abeeegiilnnnssst" => ["intangiblenesses"],
      "aeeghiinpprrsttw" => ["weatherstripping"],
      "acehhilmoopprsxy" => ["chemoprophylaxis"],
      "acghhhnoooopprrt" => ["photochronograph"],
      "aaeiilnnorrssttt" => ["transliterations"],
      "aacehiillnssttuy" => ["enthusiastically"],
      "aabciillnooorstt" => ["collaborationist"],
      "aeeehiinnprsttvy" => ["antihypertensive"],
      "aaceillnnoorstvy" => ["conversationally"],
      "acgiinnoooprsstt" => ["prognostications"],
      "accceeiiilmsssst" => ["ecclesiasticisms"],
      "cdelmnnooooostuy" => ["monocotyledonous"],
      "aaaccillloopprsy" => ["laparoscopically"],
      "aaceiilnorrrttuv" => ["atrioventricular"],
      "acdgiiiilmnnrsty" => ["discriminatingly"],
      "aaccdefiiilnosst" => ["declassification"],
      "aaciiiiilmnrsttt" => ["antimilitaristic"],
      "aacghilnooprrstu" => ["ultrasonographic"],
      "acdeeeeinrrrsstu" => ["undersecretaries"],
      "abccghiillooopsy" => ["psychobiological"],
      "acdeiiiilnnoostt" => ["conditionalities"],
      "aeeeennorsssstux" => ["extraneousnesses"],
      "deegiinnnossssuu" => ["disingenuousness"],
      "cdeeeinnoorssssu" => ["indecorousnesses"],
      "aaccggiiimnnrtuv" => ["circumnavigating"],
      "aabeeeilmmnrsssu" => ["immeasurableness"],
      "accehhillmnooprs" => ["chloramphenicols"],
      "aabeiiiilnsssttu" => ["sustainabilities"],
      "abchlmnnoooprruy" => ["bronchopulmonary"],
      "cddeeeinnnossstt" => ["discontentedness"],
      "aaeeiilmnnpsstuv" => ["manipulativeness"],
      "aceehillmmorrtty" => ["thermometrically"],
      "cegiiilnnorrrtty" => ["trinitroglycerin"],
      "ddeeeeennprrrstu" => ["underrepresented"],
      "aachiillmnoprsty" => ["misanthropically"],
      "aaadeinnoprrrstt" => ["radiotransparent"],
      "aeehiinoprrssstw" => ["praiseworthiness"],
      "eeegimnooprrsttu" => ["postremogeniture"],
      "adegiiiinoprsttt" => ["prestidigitation"],
      "aaacdghiilloprry" => ["radiographically"],
      "abbceiiijlnootty" => ["objectionability"],
      "aceeiiloorrrssst" => ["arteriosclerosis"],
      "acdeghilllmoooty" => ["methodologically"],
      "bceegiiilnnorrss" => ["incorrigibleness"],
      "aeeeehinopprrsvv" => ["overapprehensive"],
      "adeeehnorssstttu" => ["stoutheartedness"],
      "abeeeiiilmmprsty" => ["semipermeability"],
      "ceghlnnooorssuyy" => ["geosynchronously"],
      "ceiiinnorrsssttu" => ["insurrectionists"],
      "aaccdeiiinnorttv" => ["contraindicative"],
      "aeeegnoorsssstuu" => ["outrageousnesses"],
      "aceeimnnoooprstv" => ["overcompensation"],
      "aceeghimmnorstty" => ["magnetochemistry"],
      "aceeehhilnnprsty" => ["chryselephantine"],
      "aceegilllmooorty" => ["meteorologically"],
      "aaaaccehhlnnopst" => ["acanthocephalans"],
      "bceeiilnnoorrttv" => ["incontrovertible"],
      "acfgiiimnnoorstu" => ["configurationism"],
      "aaabcghiilooprtu" => ["autobiographical"],
      "eefghiilnnsssstu" => ["insightfulnesses"],
      "aeeilmnnosssstuu" => ["simultaneousness"],
      "abdeehiilmnssstt" => ["disestablishment"],
      "acceilmooprrsstu" => ["ultramicroscopes"],
      "aaeeeghmoooprrrt" => ["aerometeorograph"],
      "acceeiimmnnorttu" => ["intercommunicate"],
      "aaacgiillnnostty" => ["antagonistically"],
      "cceeiinnnnoorstt" => ["interconnections"],
      "aaacciillorrstty" => ["aristocratically"],
      "ceeeffinnoorstuv" => ["counteroffensive"],
      "acciiimmmnnoostu" => ["miscommunication"],
      "aacdghhilloprryy" => ["hydrographically"],
      "bcceeiiilorrttty" => ["triboelectricity"],
      "acceiimmnnoostux" => ["excommunications"],
      "acceeilnorsttxyy" => ["oxytetracyclines"],
      "aceilnnnooorrstv" => ["noncontroversial"],
      "acdehiimmnorstty" => ["thermodynamicist"],
      "aabcillllmnoosyy" => ["monosyllabically"],
      "aaaacdgiillmmrty" => ["diagrammatically"],
      "aaceeknnnorssstu" => ["cantankerousness"],
      "ceeimnnnoorssstu" => ["conterminousness"],
      "aceeeinoorrstvvv" => ["overconservative"],
      "abeeilnorsssssuu" => ["salubriousnesses"],
      "aeeeehinnpprsssv" => ["apprehensiveness"],
      "aeeeillnnrsssstt" => ["slatternlinesses"],
      "eeenoopprrsssstu" => ["preposterousness"],
      "aacgiillrrssttuu" => ["agriculturalists"],
      "acegiimnnoorsttt" => ["magnetostriction"],
      "adegiiioprrssttt" => ["prestidigitators"],
      "ccceeiklnoorstuw" => ["counterclockwise"],
      "achiiinnoopssttu" => ["unsophistication"],
      "chiimnoooooppstt" => ["photocomposition"],
      "aaccdeillmnortuy" => ["undemocratically"],
      "ceeefiilnosssstu" => ["felicitousnesses"],
      "aciiinnoprrssttt" => ["transcriptionist"],
      "acghhimooopprrst" => ["photomicrographs"],
      "aegghhhmooprrrty" => ["hygrothermograph"],
      "aceiinnoorsssttv" => ["conservationists"],
      "eelmnossssttuuuu" => ["tumultuousnesses"],
      "acdeiiiilmnnrsty" => ["indiscriminately"],
      "celnnoprssssuuuu" => ["unscrupulousness"],
      "aaeghhinoopprstt" => ["anthropophagites"],
      "aeeilnooprrrtuvy" => ["prerevolutionary"],
      "aceeiiilnooprrst" => ["incorporealities"],
      "addegiimnnnrsstu" => ["misunderstanding"],
      "aghhillmooopsstt" => ["ophthalmologists"],
      "aaciillnooprrsty" => ["conspiratorially"],
      "aaeeiilorrrrtttx" => ["extraterritorial"],
      "beeiiiilprrrssty" => ["irrepressibility"],
      "accegghillnoooor" => ["geochronological"],
      "eeeiimnoprssssuv" => ["imperviousnesses"],
      "aaciiimmmnnorstu" => ["communitarianism"],
      "ceehimnnnnoooprs" => ["noncomprehension"],
      "abehilmnooorrstt" => ["tribromoethanols"],
      "aaabeinnrssttttu" => ["transubstantiate"],
      "accghhiloooppsty" => ["psychopathologic"],
      "acegilnnnoossuuy" => ["consanguineously"],
      "adeeiiiilmnnosst" => ["dimensionalities"],
      "aaegiilnnorssttt" => ["gastrointestinal"],
      "ddeeeiiinprsssst" => ["dispiritednesses"],
      "acddefhiiiimnotu" => ["dehumidification"],
      "aaciiinnoootttux" => ["autointoxication"],
      "aceehiinorssttuv" => ["overenthusiastic"],
      "acceehiilllnorty" => ["heliocentrically"],
      "aaafilmnnoorrstt" => ["transformational"],
      "aceeefinorrrssst" => ["refractorinesses"],
      "aaaefilnoopprrss" => ["paraprofessional"],
      "aabdeeeegilnrsss" => ["disagreeableness"],
      "cceeeiiiloprttyz" => ["piezoelectricity"],
      "ceeeeiimnpprsstv" => ["imperceptiveness"],
      "aaabeiiillnpsttu" => ["unpalatabilities"],
      "ccdeehiilorrttyy" => ["hydroelectricity"],
      "eemnopprsssstuuu" => ["presumptuousness"],
      "ccciiimnoprrsstu" => ["circumscriptions"],
      "aceginooprrsssty" => ["crossopterygians"],
      "abcceiiiilnnotvy" => ["inconceivability"],
      "aeiilmnnrssstttu" => ["instrumentalists"],
      "aceehhilmnoorrtt" => ["trichloromethane"],
      "aabccegilnnnortu" => ["counterbalancing"],
      "aaceghillnoprsty" => ["stenographically"],
      "aaaacchhillmsttw" => ["whatchamacallits"],
      "aaccghilloprrsty" => ["crystallographic"],
      "bceeiilmnnorsttu" => ["triboluminescent"],
      "aceeeehimnorstvv" => ["overachievements"],
      "ccdeefiiimmnnouy" => ["immunodeficiency"],
      "acccdeeilllnopyy" => ["encyclopedically"],
      "ddeeeeilnnnprtty" => ["interdependently"],
      "aefiilmnorssstuu" => ["multifariousness"],
      "aceeeginnooprstu" => ["counterespionage"],
      "aceeegilmmnorstt" => ["electromagnetism"],
      "adeeehiilnooprst" => ["radiotelephonies"],
      "abdeeegiiprrrrst" => ["partridgeberries"],
      "aeeiiiilnnnosttt" => ["intentionalities"],
      "aabiilnoprrsttty" => ["transportability"],
      "aeefiilmnooprsss" => ["semiprofessional"],
      "aaahiiimnorrsttu" => ["authoritarianism"],
      "aeehiimnnopprsss" => ["misapprehensions"],
      "aaabcceillrrtuuy" => ["bureaucratically"],
      "aeilnoooprrrtuvy" => ["prorevolutionary"],
      "bdhiiioprrsssttu" => ["distributorships"],
      "aeeiilmnnnorsttv" => ["environmentalist"],
      "aaacillmmopsttyy" => ["asymptomatically"],
      "cdegiilnnooorsst" => ["endocrinologists"],
      "ceemnnoopsssttuu" => ["contemptuousness"],
      "acciinnooorssttv" => ["vasoconstriction"],
      "aaccgiiimnnortuv" => ["circumnavigation"],
      "acdiiinnnoossttu" => ["discontinuations"],
      "eehiiinprssttvyy" => ["hypersensitivity"],
      "aceeeilllnorttuv" => ["overintellectual"],
      "abcdeeeeilnpssss" => ["despicablenesses"],
      "aceiiinnopssssuu" => ["inauspiciousness"],
      "eeghiiilnoopprtv" => ["philoprogenitive"],
      "cgiilmmnnooprsuy" => ["uncompromisingly"],
      "aacciiillnrsssty" => ["narcissistically"],
      "aeiimopprrsssttu" => ["superpatriotisms"],
      "aceeilllnnnosttu" => ["nonintellectuals"],
      "aaceiiilnnossstt" => ["sensationalistic"],
      "eeeillnoprssssxy" => ["expressionlessly"],
      "aadfghiorrrssttw" => ["straightforwards"],
      "adeiinopssssttuu" => ["disputatiousness"],
      "aaceillmnoooopty" => ["onomatopoeically"],
      "ceiinnopssssttuu" => ["intussusceptions"],
      "aceeginnorssssuu" => ["ungraciousnesses"],
      "aabeiiiillmnpstu" => ["manipulabilities"],
      "ccchlnnooorrstyy" => ["synchrocyclotron"],
      "aacchhilloppstyy" => ["psychopathically"],
      "adeeffiiinnorstt" => ["differentiations"],
      "aacceiiiilmprstt" => ["impracticalities"],
      "beiiiilnoprrssty" => ["irresponsibility"],
      "adeeeeilnnrrsstt" => ["interrelatedness"],
      "abbeiiilmprrttuy" => ["imperturbability"],
      "aaeghlnooprrrstu" => ["ultrasonographer"],
      "acdeehinnooprrty" => ["endocrinotherapy"],
      "acdeeehiinnopstt" => ["acetophenetidins"],
      "aaacciiilllpstty" => ["capitalistically"],
      "cddeghlnnoooorry" => ["dendrochronology"],
      "aaaddeefhlmoprry" => ["paraformaldehyde"],
      "aabeeeiilnnrsssv" => ["invariablenesses"],
      "abddeeeeelnnpsss" => ["dependablenesses"],
      "ceeginnoosssstuu" => ["contiguousnesses"],
      "aaeeeilmnnpstttu" => ["antepenultimates"],
      "cceeiilnoorrsttt" => ["electrostriction"],
      "aceegimnnooprstv" => ["overcompensating"],
      "aehiiimnoprsstvy" => ["hypervitaminosis"],
      "acdeefhiimnnrsst" => ["disfranchisement"],
      "aceillnnnnootuvy" => ["unconventionally"],
      "acceiiilnnoorsst" => ["conciliatoriness"],
      "aaagiinnoorssttv" => ["astronavigations"],
      "aeghhiiooprrrsst" => ["historiographers"],
      "aaceegiilllnstvy" => ["evangelistically"],
      "cdeeimmnooossssu" => ["commodiousnesses"],
      "aacceehinorrstvv" => ["archconservative"],
      "bcceeeiilmnnossu" => ["bioluminescences"],
      "aabcciilnnottuuy" => ["unaccountability"],
      "aaciiinnnoopprtt" => ["nonparticipation"],
      "ceeiiinnortttuuv" => ["counterintuitive"],
      "aaacceghillloory" => ["archaeologically"],
      "aceeiinnoprssstu" => ["pertinaciousness"],
      "aabdefgiiiilntty" => ["indefatigability"],
      "aeeeiilmmnprsstx" => ["experimentalisms"],
      "cgghllnooooortty" => ["glottochronology"],
      "aaaciilllnrsttuy" => ["naturalistically"],
      "acdhiilnoooppttu" => ["photoduplication"],
      "aaciinnooprrsstt" => ["procrastinations"],
      "aaccdiiinnnoortt" => ["contraindication"],
      "cceeeeloopprsstt" => ["telespectroscope"],
      "aggillnoooorstty" => ["otolaryngologist"],
      "aabcciiiilmprtty" => ["impracticability"],
      "aceeeefinrrssstv" => ["refractivenesses"],
      "aacghiloopprssty" => ["parapsychologist"],
      "aacchiiillnstuvy" => ["chauvinistically"],
      "aaabeeeeglmnnsss" => ["manageablenesses"],
      "aceeghhiloopprtt" => ["telephotographic"],
      "aaccdiimmnooostt" => ["accommodationist"],
      "aceefgilnrrsttuu" => ["ultracentrifuges"],
      "aciiiillopssttvy" => ["positivistically"],
      "abbcdiilmnooostu" => ["discombobulation"],
      "acdefghiiinnnrss" => ["disenfranchising"],
      "aaacehimpprsstty" => ["parasympathetics"],
      "aceeiijllnnortty" => ["interjectionally"],
      "aciillnnoooprsst" => ["crosspollination"],
      "aabcceiiiilprstt" => ["practicabilities"],
      "aaceghhimooprrst" => ["chromatographies"],
      "eeghinooppstttty" => ["phototypesetting"],
      "aacceghillloosty" => ["eschatologically"],
      "aciillnnoostttuy" => ["constitutionally"],
      "bceeiiiilmpprtty" => ["imperceptibility"],
      "aeeiiiilorrrsttt" => ["territorialities"],
      "aabceeilmnnoprss" => ["incomparableness"],
      "aeeiilmmnnnorstv" => ["environmentalism"],
      "aefgiiinnrrsttty" => ["interstratifying"],
      "accinooorrsssttv" => ["vasoconstrictors"],
      "aceiillllmrttuuy" => ["multicellularity"],
      "acdeehiiimorrsst" => ["radiochemistries"],
      "aadeeeeinnqssstu" => ["inadequatenesses"],
      "cehiiimmnooprsss" => ["commissionership"],
      "aeeeeiimnprssstv" => ["imperativenesses"],
      "aacghillnoopprry" => ["pornographically"],
      "aceeeinnorssstvv" => ["conservativeness"],
      "abcceeiiiilnostv" => ["conceivabilities"],
      "ehiiinoopsstttvy" => ["photosensitivity"],
      "aaaceehhllmnnopt" => ["thalamencephalon"],
      "aaceillmnssttuyy" => ["unsystematically"],
      "aacdeellnnnrstty" => ["transcendentally"],
      "deeegiinnnossssu" => ["indigenousnesses"],
      "aaccceeiilllssty" => ["ecclesiastically"],
      "deeghhinorsssstt" => ["shortsightedness"],
      "aaccehllooprsuyy" => ["caryophyllaceous"],
      "aeeeeinnprrsttuv" => ["unrepresentative"],
      "abdeiiiiilmnostt" => ["indomitabilities"],
      "aaeiiilmnnnorstt" => ["internationalism"],
      "aceeghillmnnooop" => ["phenomenological"],
      "bceeehiilmnnoprs" => ["incomprehensible"],
      "aefiilnnnoooprrt" => ["nonproliferation"],
      "ceeefilmnnrsssuu" => ["unmercifulnesses"],
      "acehimnnooprrstt" => ["anthropocentrism"],
      "aciilllmmrsttuuu" => ["multiculturalism"],
      "aeehiilnnoprttvy" => ["hyperventilation"],
      "abddeeeimnnnssst" => ["absentmindedness"],
      "aiiiilmnnosstttu" => ["institutionalism"],
      "abcceghiillnooot" => ["biotechnological"],
      "bddeeeeefilmnnss" => ["feeblemindedness"],
      "aabeeeelnnosssss" => ["seasonablenesses"],
      "acceiimmnnnootuv" => ["noncommunicative"],
      "aaeiiilnnnorttty" => ["internationality"],
      "acceiiilossstttx" => ["lexicostatistics"],
      "adeiiillmmnnostu" => ["multidimensional"],
      "eeiinoopprsssstu" => ["propitiousnesses"],
      "abbdeiiiiilnsttu" => ["indubitabilities"],
      "adeeeeiimnsssttv" => ["meditativenesses"],
      "acceeehhimoprttu" => ["chemotherapeutic"],
      "ceeinnnoosssstuu" => ["continuousnesses"],
      "accgiiilllmnoory" => ["criminologically"],
      "deeeiiimnnssstuv" => ["diminutivenesses"],
      "ceehhlnoopprssty" => ["phosphorescently"],
      "cdeeghimnnnnoopr" => ["noncomprehending"],
      "aeiiiilllmmnortu" => ["multimillionaire"],
      "aacchilllopprtyy" => ["prophylactically"],
      "aacgiiinnnopprtt" => ["nonparticipating"],
      "aagiiimnoppprrst" => ["misappropriating"],
      "aeeinoorrssssttu" => ["traitorousnesses"],
      "aacdfiiiilnoqstu" => ["disqualification"],
      "acegiilllmnoorty" => ["terminologically"],
      "aeegglnooorrstty" => ["gastroenterology"],
      "bbciiiilmnosttuy" => ["incombustibility"],
      "aabiiinnoorssttt" => ["antiabortionists"],
      "addeeghnoprrstuu" => ["superdreadnought"],
      "abdeiiiilnnpssty" => ["indispensability"],
      "beeehiiilnprrsty" => ["reprehensibility"],
      "ccdiinooprttuvyy" => ["pyroconductivity"],
      "beeiiiilnoprssst" => ["responsibilities"],
      "bbehhiilmooprstt" => ["thrombophlebitis"],
      "beeenooprrsssstu" => ["obstreperousness"],
      "ccghiiilnopsstuy" => ["psycholinguistic"],
      "aciiimnnnooprstu" => ["mispronunciation"],
      "adeeeiimnnoprrtt" => ["predetermination"],
      "aabiilnnsstttuuy" => ["unsubstantiality"]}
    |> Map.get(string_id)
  end

  def valid_ids do
    ["aabcgiilnorsstuu", "aeeghiilnnprttvy", "acciimnnoorrsttu", "acefgiinnoorrstu",
     "deehimnnnorrstuu", "aegiilnnoorsssuv", "abeehiilnnopssst", "aceeeffiiilnsttu",
     "aacdeeeinrrrsttu", "cceeehilmorrstty", "aceeiilnnnnorttt", "bcdeeeeiilnnrsss",
     "acghiilllnooorty", "ceeiilooppprrtvy", "acdeeilnnoosssst", "aeeeeilnprrsttvy",
     "aeiimnnooprssssu", "adeeiimnnorssttu", "aeeiiilllmmnnprs", "aacehillmorsttty",
     "acdefiiiimnnnost", "cdeegiillnooostu", "acdeeeehimnnrtuv", "aaaceghinnoprtty",
     "bceehiilmnnoprsy", "aeeinnoosssstttu", "acdeeiilnpprrtuy", "acceelnnoopssttv",
     "aciiilmnnooopstt", "ceehilmoorssssst", "acceehillnnortty", "aceiilmnnnoosstv",
     "aceeeiilnnnqsstu", "aaeeiilnnoprrttt", "abeeiiiilrrrttvy", "aaeeeilrrrrstttx",
     "aceghhiilllopryy", "cciinnoorssstttu", "eeeinnnoprssssuv", "aaccehhhilnnopry",
     "acdeefinnoprstuu", "aaeeeilnnoprrstt", "abcegiiillmooost", "ceeehmoorrrtttyy",
     "aaccffgiiknnorrt", "acdeeeeffnnssstu", "aeeeiinnoprrrttt", "cdeeeeiinnrsssst",
     "aeehiimnoprsstvy", "cceehimoprrsstty", "aeeimnnorrrstttu", "acdeehiilmnoprty",
     "aacdehhiilmoprrt", "aaaacghilmnoprst", "aeiiiiinnrsstttv", "aeeehiilmmnnopps",
     "aabiiilnnnnotttu", "aaeeeiillnrssttv", "abeiiiiillmpsstu", "bceeeeijnsssstuv",
     "aabeeelnnnorsssu", "aaccdgiiinnnortt", "bdddeeilmnnoossy", "aaacchilloprstty",
     "abeeeeilmnnprsst", "ccddeeeinnnossst", "cciimnnoorsssttu", "cceeiilnnnosssuv",
     "aacghhillooprrty", "accdegiinnnnostu", "beeiiiiilmprssst", "ceeiinoopprrrstv",
     "aceiinnorrrstttu", "bceiilnnoorrttvy", "abeeghiiilnnstux", "aaciijlllnorstuy",
     "abehiloorrssstty", "aacghhiillloprty", "abceimnnorssstuu", "aacccehiinrrsttu",
     "aacehiillpprrsty", "aceeghlmooprrtyy", "aacdeeghiiloprrt", "aacdeeeefhmnssss",
     "adeeeggiinorsstt", "ddeeeelmnnoprtuv", "aefilnnnoooprsss", "abccefiiijnoostt",
     "aaccgiillllmooty", "eeeehinnpprrrstu", "aadeiiilmnrsttvy", "ceeeiinpprrssstv",
     "aaccdeiimnrstttu", "aeeiinoprrsssttv", "aaeiiilnnnorsttt", "aaaaeiilmnnprrst",
     "ccceeiilmnoorrst", "aabdeeghinorrstw", "abeeeiilmnnnrsst", "abcehimnnnooopru",
     "acdgiiiimnnnrstu", "abehiiiilnsttuxy", "bceeiiiilpsssttu", "aaceegiilnrrsttu",
     "aaccdeehhlooprst", "aefillnnooprssuy", "aacghhilllmooopt", "eeiiimmnnooprsss",
     "aaceghlloprrrsty", "aabbhiiiilnnttuy", "aeeegiinnnprrttt", "aaabeellnnrssstt",
     "adeeeiimnnorrstt", "aeegimnnnsssssuu", "acceeillllorttyy", "deehillnoorrsstw",
     "acgiiiimnnnnnort", "aacciillmnrsttuy", "cghhiloooppssyyy", "cdeegilmnnorssuu",
     "accceeiloorssttu", "accefiiillnnstuy", "abciilorrrssttuu", "aeeiillnnqssttuy",
     "aceeiiiilnsstttx", "aaacdeilllmmorty", "abbcdgiilmnoostu", "acceeillooprssty",
     "aabceiloprrsstuu", "acehhiopprssstty", "aacefiinorsssstt", "bcciiinoorsstttu",
     "acelnooopprrsstu", "aaceeinnrsstttuv", "ceeehlooopprttty", "bbehilmmmooorsst",
     "aceefiiilmnopstx", "aaaaacgillmmnrty", "aeeiinnorrsssstt", "cceghhlnooopstyy",
     "aabeeeillnnsssuv", "abdeeiilnnpssstu", "aeeghmmmnooprsty", "aaceefillnossssu",
     "aaceeiiimnnrssst", "deeehiilnopprsty", "accciilmooprrstu", "acdeeiinnorsstuu",
     "aaceilnnnnorsttt", "adeeegiknnprrrst", "adeeeinnnrrssstu", "aaggiiilnnoosttu",
     "adeiinooopprrstt", "aaceiiilllrsttvy", "ahhmnoooopprrstu", "acdeeiiiilnorstt",
     "adeeeeimmnorssst", "accegiinnnooprrt", "bbbbeefgiiilrstt", "cdeehiinorrssttw",
     "ahijlnoooprssttu", "aaccdiimmmnooost", "eeiiinnnorsstttv", "acdeiiillmnorttu",
     "accgiillmmooorty", "aeeiillnnossssuv", "abceehhlmnnooprs", "abcdeiiilnprttuy",
     "abefgiilnortttuy", "aacfiilnorssttuy", "acghiillmnoopsyy", "ceeehhmmoooorrst",
     "aceeilmmnnorstuy", "deeflnooprsssstu", "aceeginnorrsttuu", "bcceinnoosssssuu",
     "cceeehiimoprttvy", "aceeiinnosssstuu", "aaeegiilmnnosttz", "ceeiilnoprssssuu",
     "ccgiiiilnoossstu", "accdeeeiimnoppst", "bceeeiiiilpprstt", "aggiilmmmnoprrtu",
     "aaeeilmnprrrsttu", "aadeiilmnnnnootu", "aaghhooopprrstty", "aacdeeiilnnnqrtu",
     "accceeehilmnorst", "aaccefiiilnorsst", "beeeiiilnrrsssst", "ceeeiimnorrssstu",
     "abefilnooprssssu", "cceehiilooprttty", "aceeimnnnooprstu", "aaacehilllmnpruy",
     "beiiiiilmmprssty", "ceeiilmnnoopttvy", "beeiinoqsssstuuu", "aceehillnooprsty",
     "aghhhilooopprtty", "adeehhiilmooppsu", "cehiinnooprssssu", "aaaccehiinnpqstu",
     "aeeeghnnooprrtty", "aaceeiilnnrssttu", "aaceiilllrrsstuy", "aabccgiilmmnrtuu",
     "adeeeghhilnrsstt", "acghhinooopprtyz", "ceeginnnorrsttuu", "aeeiiinnnrsssttv",
     "aceeeinnoorsstvv", "aehhiiopprssstty", "bdehiilnoorssstt", "aabceehilnnrsstu",
     "aabbddegiiilorty", "ceegilmmoooorrty", "ceeiinopssssssuu", "acghhimooopprrty",
     "accdegiillnnooor", "achiillorrstttuu", "bciiiilnoprrttuy", "aeeeiinnnoprrttt",
     "ceehhiimooprsstt", "addeeeffiinnrttu", "aacceeilmnoprstu", "aaiiimnooppprrst",
     "aceeemnnorsttttu", "aehiiimpprrsttuy", "abceiilmmnorstuy", "accehillmnoorrty",
     "aabiiilnnsstttuy", "cceeeefgilnnnort", "abeeiiilnoprrtty", "aaacchillnopstyy",
     "aghhnoooopprrssu", "bceiinooprrsstuv", "eiinooppssssstuu", "aaaccghilloprrty",
     "aaacehiiillmmnsv", "acefiiinnooprsst", "aaceeehioprrsttu", "aabeeiiillnrsttu",
     "aceeiilnnoqsttuy", "aacceiimnrsstttu", "aaccegiknnortttu", "acceilnnoorrsttu",
     "acghhhilmoooprrt", "ceeehimnnnooprsv", "aaceghhillnoprty", "beeiiiilnprsstxy",
     "cceeehiilmmnnstu", "aeeeiilmnprssttx", "aeggillnoooorsty", "aacghhilloopprty",
     "cceeinnorsssttuv", "aciilnnnoostttuu", "abceiiilnnosttty", "aaeilmnprrssstuu",
     "adeeeehhlnorsstw", "acdiiiiimnnnorst", "aceegmnnorrsttuu", "acceeiiloorrrstt",
     "cceeinnooprssssu", "acceiillmnorrsty", "ahhimmnooopprrst", "adehhiimmoprrsst",
     "aaceeiinorssssuv", "aaceeghimnoprrst", "aaacceeiilnopssu", "aaccciilllnoosty",
     "aaccdeghiiloorss", "adeeiiimnnnorstt", "aeeelmnooprstuxy", "adeelmnooorssssu",
     "abeeeelnnoprssss", "aaaiillmnnorsttu", "abeeegiilnnnssst", "aeeghiinpprrsttw",
     "acehhilmoopprsxy", "acghhhnoooopprrt", "aaeiilnnorrssttt", "aacehiillnssttuy",
     "aabciillnooorstt", "aeeehiinnprsttvy", "aaceillnnoorstvy", "acgiinnoooprsstt",
     "accceeiiilmsssst", "cdelmnnooooostuy", "aaaccillloopprsy", "aaceiilnorrrttuv",
     "acdgiiiilmnnrsty", "aaccdefiiilnosst", "aaciiiiilmnrsttt", "aacghilnooprrstu",
     "acdeeeeinrrrsstu", "abccghiillooopsy", "acdeiiiilnnoostt", "aeeeennorsssstux",
     "deegiinnnossssuu", "cdeeeinnoorssssu", "aaccggiiimnnrtuv", "aabeeeilmmnrsssu",
     "accehhillmnooprs", "aabeiiiilnsssttu", "abchlmnnoooprruy", "cddeeeinnnossstt",
     "aaeeiilmnnpsstuv", "aceehillmmorrtty", "cegiiilnnorrrtty", "ddeeeeennprrrstu",
     "aachiillmnoprsty", "aaadeinnoprrrstt", "aeehiinoprrssstw", "eeegimnooprrsttu",
     "adegiiiinoprsttt", "aaacdghiilloprry", "abbceiiijlnootty", "aceeiiloorrrssst",
     "acdeghilllmoooty", "bceegiiilnnorrss", "aeeeehinopprrsvv", "adeeehnorssstttu",
     "abeeeiiilmmprsty", "ceghlnnooorssuyy", "ceiiinnorrsssttu", "aaccdeiiinnorttv",
     "aeeegnoorsssstuu", "aceeimnnoooprstv", "aceeghimmnorstty", "aceeehhilnnprsty",
     "aceegilllmooorty", "aaaaccehhlnnopst", "bceeiilnnoorrttv", "acfgiiimnnoorstu",
     "aaabcghiilooprtu", "eefghiilnnsssstu", "aeeilmnnosssstuu", "abdeehiilmnssstt",
     "acceilmooprrsstu", "aaeeeghmoooprrrt", "acceeiimmnnorttu", "aaacgiillnnostty",
     "cceeiinnnnoorstt", "aaacciillorrstty", "ceeeffinnoorstuv", "acciiimmmnnoostu",
     "aacdghhilloprryy", "bcceeiiilorrttty", "acceiimmnnoostux", "acceeilnorsttxyy",
     "aceilnnnooorrstv", "acdehiimmnorstty", "aabcillllmnoosyy", "aaaacdgiillmmrty",
     "aaceeknnnorssstu", "ceeimnnnoorssstu", "aceeeinoorrstvvv", "abeeilnorsssssuu",
     "aeeeehinnpprsssv", "aeeeillnnrsssstt", "eeenoopprrsssstu", "aacgiillrrssttuu",
     "acegiimnnoorsttt", "adegiiioprrssttt", "ccceeiklnoorstuw", "achiiinnoopssttu",
     "chiimnoooooppstt", "aaccdeillmnortuy", "ceeefiilnosssstu", "aciiinnoprrssttt",
     "acghhimooopprrst", "aegghhhmooprrrty", "aceiinnoorsssttv", "eelmnossssttuuuu",
     "acdeiiiilmnnrsty", "celnnoprssssuuuu", "aaeghhinoopprstt", "aeeilnooprrrtuvy",
     "aceeiiilnooprrst", "addegiimnnnrsstu", "aghhillmooopsstt", "aaciillnooprrsty",
     "aaeeiilorrrrtttx", "beeiiiilprrrssty", "accegghillnoooor", "eeeiimnoprssssuv",
     "aaciiimmmnnorstu", "ceehimnnnnoooprs", "abehilmnooorrstt", "aaabeinnrssttttu",
     "accghhiloooppsty", "acegilnnnoossuuy", "adeeiiiilmnnosst", "aaegiilnnorssttt",
     "ddeeeiiinprsssst", "acddefhiiiimnotu", "aaciiinnoootttux", "aceehiinorssttuv",
     "acceehiilllnorty", "aaafilmnnoorrstt", "aceeefinorrrssst", "aaaefilnoopprrss",
     "aabdeeeegilnrsss", "cceeeiiiloprttyz", "ceeeeiimnpprsstv", "aaabeiiillnpsttu",
     "ccdeehiilorrttyy", "eemnopprsssstuuu", "ccciiimnoprrsstu", "aceginooprrsssty",
     "abcceiiiilnnotvy", "aeiilmnnrssstttu", "aceehhilmnoorrtt", "aabccegilnnnortu",
     "aaceghillnoprsty", "aaaacchhillmsttw", "aaccghilloprrsty", "bceeiilmnnorsttu",
     "aceeeehimnorstvv", "ccdeefiiimmnnouy", "acccdeeilllnopyy", "ddeeeeilnnnprtty",
     "aefiilmnorssstuu", "aceeeginnooprstu", "aceeegilmmnorstt", "adeeehiilnooprst",
     "abdeeegiiprrrrst", "aeeiiiilnnnosttt", "aabiilnoprrsttty", "aeefiilmnooprsss",
     "aaahiiimnorrsttu", "aeehiimnnopprsss", "aaabcceillrrtuuy", "aeilnoooprrrtuvy",
     "bdhiiioprrsssttu", "aeeiilmnnnorsttv", "aaacillmmopsttyy", "cdegiilnnooorsst",
     "ceemnnoopsssttuu", "acciinnooorssttv", "aaccgiiimnnortuv", "acdiiinnnoossttu",
     "eehiiinprssttvyy", "aceeeilllnorttuv", "abcdeeeeilnpssss", "aceiiinnopssssuu",
     "eeghiiilnoopprtv", "cgiilmmnnooprsuy", "aacciiillnrsssty", "aeiimopprrsssttu",
     "aceeilllnnnosttu", "aaceiiilnnossstt", "eeeillnoprssssxy", "aadfghiorrrssttw",
     "adeiinopssssttuu", "aaceillmnoooopty", "ceiinnopssssttuu", "aceeginnorssssuu",
     "aabeiiiillmnpstu", "ccchlnnooorrstyy", "aacchhilloppstyy", "adeeffiiinnorstt",
     "aacceiiiilmprstt", "beiiiilnoprrssty", "adeeeeilnnrrsstt", "abbeiiilmprrttuy",
     "aaeghlnooprrrstu", "acdeehinnooprrty", "acdeeehiinnopstt", "aaacciiilllpstty",
     "cddeghlnnoooorry", "aaaddeefhlmoprry", "aabeeeiilnnrsssv", "abddeeeeelnnpsss",
     "ceeginnoosssstuu", "aaeeeilmnnpstttu", "cceeiilnoorrsttt", "aceegimnnooprstv",
     "aehiiimnoprsstvy", "acdeefhiimnnrsst", "aceillnnnnootuvy", "acceiiilnnoorsst",
     "aaagiinnoorssttv", "aeghhiiooprrrsst", "aaceegiilllnstvy", "cdeeimmnooossssu",
     "aacceehinorrstvv", "bcceeeiilmnnossu", "aabcciilnnottuuy", "aaciiinnnoopprtt",
     "ceeiiinnortttuuv", "aaacceghillloory", "aceeiinnoprssstu", "aabdefgiiiilntty",
     "aeeeiilmmnprsstx", "cgghllnooooortty", "aaaciilllnrsttuy", "acdhiilnoooppttu",
     "aaciinnooprrsstt", "aaccdiiinnnoortt", "cceeeeloopprsstt", "aggillnoooorstty",
     "aabcciiiilmprtty", "aceeeefinrrssstv", "aacghiloopprssty", "aacchiiillnstuvy",
     "aaabeeeeglmnnsss", "aceeghhiloopprtt", "aaccdiimmnooostt", "aceefgilnrrsttuu",
     "aciiiillopssttvy", "abbcdiilmnooostu", "acdefghiiinnnrss", "aaacehimpprsstty",
     "aceeiijllnnortty", "aciillnnoooprsst", "aabcceiiiilprstt", "aaceghhimooprrst",
     "eeghinooppstttty", "aacceghillloosty", "aciillnnoostttuy", "bceeiiiilmpprtty",
     "aeeiiiilorrrsttt", "aabceeilmnnoprss", "aeeiilmmnnnorstv", "aefgiiinnrrsttty",
     "accinooorrsssttv", "aceiillllmrttuuy", "acdeehiiimorrsst", "aadeeeeinnqssstu",
     "cehiiimmnooprsss", "aeeeeiimnprssstv", "aacghillnoopprry", "aceeeinnorssstvv",
     "abcceeiiiilnostv", "ehiiinoopsstttvy", "aaaceehhllmnnopt", "aaceillmnssttuyy",
     "aacdeellnnnrstty", "deeegiinnnossssu", "aaccceeiilllssty", "deeghhinorsssstt",
     "aaccehllooprsuyy", "aeeeeinnprrsttuv", "abdeiiiiilmnostt", "aaeiiilmnnnorstt",
     "aceeghillmnnooop", "bceeehiilmnnoprs", "aefiilnnnoooprrt", "ceeefilmnnrsssuu",
     "acehimnnooprrstt", "aciilllmmrsttuuu", "aeehiilnnoprttvy", "abddeeeimnnnssst",
     "aiiiilmnnosstttu", "abcceghiillnooot", "bddeeeeefilmnnss", "aabeeeelnnosssss",
     "acceiimmnnnootuv", "aaeiiilnnnorttty", "acceiiilossstttx", "adeiiillmmnnostu",
     "eeiinoopprsssstu", "abbdeiiiiilnsttu", "adeeeeiimnsssttv", "acceeehhimoprttu",
     "ceeinnnoosssstuu", "accgiiilllmnoory", "deeeiiimnnssstuv", "ceehhlnoopprssty",
     "cdeeghimnnnnoopr", "aeiiiilllmmnortu", "aacchilllopprtyy", "aacgiiinnnopprtt",
     "aagiiimnoppprrst", "aeeinoorrssssttu", "aacdfiiiilnoqstu", "acegiilllmnoorty",
     "aeegglnooorrstty", "bbciiiilmnosttuy", "aabiiinnoorssttt", "addeeghnoprrstuu",
     "abdeiiiilnnpssty", "beeehiiilnprrsty", "ccdiinooprttuvyy", "beeiiiilnoprssst",
     "bbehhiilmooprstt", "beeenooprrsssstu", "ccghiiilnopsstuy", "aciiimnnnooprstu",
     "adeeeiimnnoprrtt", "aabiilnnsstttuuy"]
    |> Enum.into(HashSet.new)
  end
end
