defmodule Jumble.ScowlDict.Size70.Length3 do
  def get(string_id) do
    %{"abo" => ["boa"], "aek" => ["kea"], "hot" => ["tho", "hot"], "oow" => ["woo"],
      "ctu" => ["cut"], "afr" => ["far"], "dgu" => ["dug"], "abd" => ["dab", "bad"],
      "hip" => ["phi", "hip"], "elu" => ["leu"], "inu" => ["uni"],
      "bgi" => ["gib", "big"], "osy" => ["soy"], "imx" => ["mix"], "abf" => ["fab"],
      "ikl" => ["ilk"], "nru" => ["urn", "run"], "gmy" => ["gym"],
      "bde" => ["deb", "bed"], "dsu" => ["sud"], "lot" => ["lot"], "agj" => ["jag"],
      "muy" => ["yum"], "ehu" => ["hue"], "ehi" => ["hie"], "hnt" => ["nth"],
      "eov" => ["voe"], "ajy" => ["jay"], "aey" => ["yea", "aye"],
      "eil" => ["lei", "lie"], "deu" => ["due"], "bil" => ["lib"], "ooz" => ["zoo"],
      "hop" => ["hop"], "nno" => ["non"], "ggi" => ["gig"], "acy" => ["cay"],
      "npw" => ["pwn"], "ahp" => ["hap", "pah"], "ivy" => ["ivy"], "aes" => ["sea"],
      "mmo" => ["mom"], "fnu" => ["fun"], "ewy" => ["yew"], "afn" => ["fan"],
      "ott" => ["tot"], "doy" => ["yod"], "cgo" => ["cog"], "abl" => ["alb", "lab"],
      "aft" => ["aft", "fat"], "dop" => ["pod"], "bdo" => ["bod", "dob"],
      "imn" => ["nim"], "imm" => ["mim"], "cgi" => ["cig"], "cox" => ["cox"],
      "chi" => ["hic", "chi"], "flu" => ["flu"], "ops" => ["ops", "sop"],
      "epy" => ["pye", "yep"], "tux" => ["tux"], "eit" => ["tie"], "ehr" => ["her"],
      "efk" => ["kef"], "now" => ["now", "own", "won"], "app" => ["pap"],
      "hoy" => ["hoy"], "acm" => ["mac", "cam"], "ovw" => ["vow"], "bfi" => ["fib"],
      "amy" => ["yam", "may"], "atx" => ["tax"], "ept" => ["pet"], "psy" => ["spy"],
      "amt" => ["tam", "mat"], "fik" => ["kif"],
      "aps" => ["asp", "pas", "sap", "spa"], "itt" => ["tit"], "aly" => ["lay"],
      "bow" => ["bow"], "aoz" => ["azo", "zoa"], "ddo" => ["odd"], "akr" => ["ark"],
      "alx" => ["lax"], "ell" => ["ell"], "dkl" => ["dkl"], "diy" => ["yid"],
      "eny" => ["yen"], "dim" => ["mid", "dim"], "beg" => ["beg"], "cno" => ["con"],
      "ajw" => ["jaw"], "opp" => ["pop"], "eeg" => ["gee"], "kop" => ["kop"],
      "aot" => ["oat"], "est" => ["set"], "aet" => ["eta", "ate", "eat", "tea"],
      "deh" => ["edh"], "imo" => ["moi"], "mru" => ["rum"], "orw" => ["row"],
      "dos" => ["dos", "sod"], "inn" => ["inn"], "etw" => ["wet"], "aqu" => ["qua"],
      "ill" => ["ill"], "dei" => ["die"], "oty" => ["toy"], "bio" => ["obi"],
      "fop" => ["fop"], "hmm" => ["hmm"], "hor" => ["rho"], "den" => ["den", "end"],
      "cit" => ["tic"], "aim" => ["ami", "aim"], "itz" => ["zit"], "iko" => ["oik"],
      "ilo" => ["oil"], "gim" => ["mig"], "fgo" => ["fog"], "emn" => ["men"],
      "bbu" => ["bub"], "nsu" => ["nus", "sun"], "ilp" => ["lip"], "hss" => ["ssh"],
      "rty" => ["try"], "coo" => ["coo"], "oru" => ["our"], "fot" => ["oft"],
      "ipt" => ["pit", "tip"], "los" => ["sol"], "emu" => ["emu"],
      "ben" => ["ben", "neb"], "egv" => ["veg"], "enp" => ["pen"],
      "alw" => ["awl", "law"], "bir" => ["rib"], "cei" => ["ice"],
      "ent" => ["net", "ten"], "eez" => ["zee"], "mmu" => ["mum"], "eey" => ["eye"],
      "ekx" => ["kex"], "add" => ["dad", "add"], "pry" => ["pry"], "ady" => ["day"],
      "acp" => ["cap"], "ems" => ["ems", "mes"], "def" => ["fed"], "blo" => ["lob"],
      "ary" => ["rya", "ray"], "mow" => ["mow"], "bet" => ["bet"], "dit" => ["dit"],
      "ads" => ["ads", "sad"], "ego" => ["ego"], "eht" => ["the"], "abp" => ["bap"],
      "esu" => ["sue", "use"], "eop" => ["ope"], "bfo" => ["fob"],
      "ahy" => ["yah", "hay"], "ast" => ["sat"], "abc" => ["cab"], "eru" => ["rue"],
      "gno" => ["nog"], "guy" => ["guy"], "efo" => ["foe"], "anr" => ["ran"],
      "ipr" => ["rip"], "ekp" => ["kep"], "adw" => ["daw", "wad"], "iwz" => ["wiz"],
      "agr" => ["gar", "rag"], "cho" => ["och"], "abb" => ["abb"], "dir" => ["rid"],
      "dpu" => ["pud"], "atu" => ["tau"], "efi" => ["fie"], "aor" => ["ora", "oar"],
      "egm" => ["meg", "gem"], "anv" => ["van"], "dis" => ["ids", "dis"],
      "del" => ["eld", "led"], "guv" => ["guv"], "ens" => ["ens"], "htu" => ["hut"],
      "acl" => ["lac"], "ehp" => ["hep"], "gju" => ["jug"],
      "aer" => ["ear", "era", "are"], "bjo" => ["job"], "ilt" => ["til", "lit"],
      "ffo" => ["off"], "aep" => ["ape", "pea"], "aal" => ["ala"], "dry" => ["dry"],
      "ino" => ["ion"], "oww" => ["wow"], "efr" => ["fer", "ref"], "bmo" => ["mob"],
      "efu" => ["feu"], "det" => ["ted"], "egg" => ["egg"], "bbi" => ["bib"],
      "boy" => ["yob", "boy"], "act" => ["act", "cat"], "dot" => ["tod", "dot"],
      "ahj" => ["haj"], "deo" => ["ode", "doe"], "bhu" => ["hub"], "glu" => ["lug"],
      "stu" => ["uts"], "eno" => ["one"], "eip" => ["pie"], "lsy" => ["sly"],
      "eev" => ["eve"], "eps" => ["pes"], "amp" => ["amp", "map"],
      "eow" => ["woe", "owe"], "bey" => ["bey", "bye"], "moo" => ["moo"],
      "adt" => ["tad"], "bdu" => ["bud", "dub"], "dnu" => ["dun"], "asv" => ["vas"],
      "cop" => ["cop"], "ail" => ["ail"], "ekn" => ["ken"],
      "psu" => ["pus", "sup", "ups"], "dor" => ["dor", "rod"], "msy" => ["mys"],
      "ant" => ["ant", "tan"], "ajr" => ["raj", "jar"], "ikt" => ["kit"],
      "gjo" => ["jog"], "adl" => ["lad"], "lru" => ["lur"], "dmo" => ["mod"],
      "bis" => ["sib", "bis"], "hos" => ["hos", "ohs"], "als" => ["sal"],
      "bor" => ["orb", "rob"], "cep" => ["pec"], "avv" => ["vav"],
      "bgo" => ["gob", "bog"], "apx" => ["pax"], "epp" => ["pep"], "itu" => ["tui"],
      "ehm" => ["meh", "hem"], "ils" => ["lis"], "bcu" => ["cub"], "goy" => ["goy"],
      "mpu" => ["ump"], "iss" => ["sis"], "lux" => ["lux"], "enw" => ["wen", "new"],
      "aht" => ["hat"], "ist" => ["its", "sit"], "dno" => ["nod", "don"],
      "eho" => ["hoe"], "ams" => ["mas"], "hsy" => ["shy"], "anp" => ["nap", "pan"],
      "ahs" => ["ash", "has"], "osw" => ["sow"], "iou" => ["oui"],
      "bru" => ["bur", "rub"], "gmo" => ["mog"], "ehs" => ["hes", "she"],
      "acr" => ["arc", "car"], "adh" => ["dah", "had"], "etv" => ["vet"],
      "cis" => ["sic"], "foo" => ["oof"], "amm" => ["mam"], "dip" => ["dip"],
      "ako" => ["koa", "oka", "oak"], "ado" => ["ado"], "esy" => ["yes"],
      "ehx" => ["hex"], "imr" => ["mir", "rim"], "kuy" => ["yuk"], "emw" => ["mew"],
      "imv" => ["vim"], "aku" => ["auk"], "cip" => ["pic"], "adf" => ["fad"],
      "aby" => ["aby", "bay"], "abg" => ["gab", "bag"], "agw" => ["wag"],
      "bit" => ["bit"], "hoo" => ["hoo", "ooh", "oho"], "noy" => ["yon"],
      "bnu" => ["nub", "bun"], "hhu" => ["huh"], "cdu" => ["cud"],
      "apy" => ["pya", "yap", "pay"], "abr" => ["arb", "bra", "bar"],
      "bbe" => ["ebb"], "ikn" => ["kin", "ink"], "git" => ["git"], "ain" => ["ain"],
      "hnu" => ["hun"], "dlo" => ["old"], "all" => ["all"], "eet" => ["tee"],
      "coy" => ["coy"], "giw" => ["wig"], "mot" => ["mot", "tom"], "biz" => ["biz"],
      "eef" => ["fee"], "gru" => ["rug"], "efz" => ["fez"], "eky" => ["key"],
      "fix" => ["fix"], "gin" => ["gin"], "buy" => ["buy"], "ipz" => ["zip"],
      "bos" => ["sob"], "iks" => ["ski"], "hmu" => ["hum"], "got" => ["tog", "got"],
      "ach" => ["cha"], "aeg" => ["age"], "imp" => ["imp"], "eor" => ["ore", "roe"],
      "ees" => ["see"], "ikp" => ["kip"], "eft" => ["eft"], "adi" => ["aid"],
      "his" => ["his"], "eir" => ["ire"], "dez" => ["zed"], "dmu" => ["mud"],
      "ipy" => ["yip"], "agm" => ["gam"], "bho" => ["hob"], "bbo" => ["bob"],
      "fir" => ["fir"], "iln" => ["nil"], "ost" => ["sot"], "agg" => ["gag"],
      "iny" => ["yin"], "puy" => ["yup"], "ael" => ["lea", "ale"], "emo" => ["emo"],
      "pxy" => ["pyx"], "giz" => ["zig"], "dfi" => ["fid"], "fly" => ["fly"],
      "goo" => ["goo"], "int" => ["nit", "tin"], "air" => ["ria", "air"],
      "elm" => ["mel", "elm"], "cru" => ["cru", "cur"], "lop" => ["pol", "lop"],
      "kow" => ["wok"], "afo" => ["oaf"], "oop" => ["poo"], "not" => ["ton", "not"],
      "sty" => ["sty"], "any" => ["nay", "any"], "gij" => ["jig"],
      "ely" => ["ley", "lye"], "adk" => ["dak"], "brr" => ["brr"],
      "atw" => ["taw", "wat"], "abj" => ["jab"], "ehn" => ["hen"], "abh" => ["bah"],
      "cim" => ["mic"], "els" => ["els"], "opr" => ["pro"], "lpu" => ["pul"],
      "fry" => ["fry"], "ekl" => ["lek", "elk"], "aks" => ["ska", "ask"],
      "apt" => ["apt", "pat", "tap"], "cor" => ["roc", "orc"], "egi" => ["gie"],
      "alp" => ["alp", "lap", "pal"], "dhi" => ["hid"], "npu" => ["pun"],
      "art" => ["tar", "rat", "art"], "ekr" => ["erk"], "asy" => ["say"],
      "ceu" => ["ecu", "cue"], "ghu" => ["hug", "ugh"], "bew" => ["web"],
      "ips" => ["pis", "sip"], "cot" => ["cot"], "eot" => ["toe"], "aww" => ["waw"],
      "loo" => ["loo"], "egk" => ["keg"], "agl" => ["gal", "lag"], "ait" => ["ait"],
      "aab" => ["aba", "baa"], "efy" => ["fey"], "dow" => ["dow"], "hty" => ["thy"],
      "ptu" => ["put"], "rwy" => ["wry"], "emt" => ["met"], "agh" => ["hag"],
      "ipx" => ["pix"], "asx" => ["sax"], "kor" => ["kor"], "adn" => ["and"],
      "joy" => ["joy"], "aan" => ["ana"], "low" => ["owl", "low"],
      "isx" => ["xis", "six"], "elt" => ["let"], "abt" => ["bat", "tab"],
      "fin" => ["fin"], "aew" => ["awe"], "ipp" => ["pip"], "hwy" => ["why"],
      "ddi" => ["did"], "ahr" => ["rah"], "opt" => ["opt", "pot", "top"],
      "itw" => ["wit"], "hit" => ["hit"], "bdi" => ["dib", "bid"],
      "agn" => ["gan", "nag"], "ins" => ["ins", "sin"], "efw" => ["few"],
      "irs" => ["sri", "sir"], "bpu" => ["pub"], "aeh" => ["hae"], "agy" => ["gay"],
      "jot" => ["jot"], "afg" => ["fag"], "att" => ["tat"], "rtu" => ["rut"],
      "otu" => ["out"], "awx" => ["wax"], "egl" => ["gel", "leg"], "fis" => ["ifs"],
      "acw" => ["caw"], "asw" => ["saw", "was"], "acd" => ["cad"], "fou" => ["fou"],
      "fgu" => ["fug"], "aah" => ["aah", "aha"], "inx" => ["nix"], "oor" => ["roo"],
      "dew" => ["dew", "wed"], "eer" => ["ere"], "nnu" => ["nun"],
      "mos" => ["som", "oms"], "egr" => ["erg"], "dil" => ["lid"], "gho" => ["hog"],
      "afy" => ["fay"], "ouy" => ["you"], "din" => ["din"], "lpy" => ["ply"],
      "how" => ["how", "who"], "ery" => ["yer", "rye"], "ags" => ["sag", "gas"],
      "hmo" => ["mho", "ohm"], "ikr" => ["irk"], "akt" => ["kat"], "egt" => ["get"],
      "dhh" => ["hhd"], "coz" => ["coz"], "amr" => ["mar", "ram", "arm"],
      "inp" => ["nip", "pin"], "dgo" => ["god", "dog"], "nos" => ["son"],
      "adp" => ["dap", "pad"], "elv" => ["lev"], "ilm" => ["mil"], "der" => ["red"],
      "ehw" => ["hew"], "ccs" => ["csc"], "amw" => ["maw"], "bee" => ["bee"],
      "oot" => ["too"], "fit" => ["fit"], "apw" => ["paw"], "gir" => ["rig"],
      "gip" => ["pig"], "acv" => ["vac"], "ntu" => ["tun", "nut"],
      "abn" => ["nab", "ban"], "ort" => ["ort", "tor", "rot"], "ddu" => ["dud"],
      "cdo" => ["doc", "cod"], "ahn" => ["nah"], "dux" => ["dux"], "amn" => ["man"],
      "cry" => ["cry"], "gmu" => ["gum", "mug"], "hhs" => ["shh"], "erv" => ["rev"],
      "eew" => ["ewe", "wee"], "cow" => ["cow"], "ciy" => ["icy"], "ttu" => ["tut"],
      "bij" => ["jib"], "arw" => ["raw", "war"], "aag" => ["aga"],
      "mop" => ["pom", "mop"], "alm" => ["lam"], "esx" => ["sex"], "eep" => ["pee"],
      "egp" => ["peg"], "box" => ["box"], "aov" => ["avo", "ova"], "agp" => ["gap"],
      "amu" => ["amu"], "mtu" => ["mut", "tum"], "cpu" => ["cup"], "osu" => ["sou"],
      "dho" => ["hod"], "opx" => ["pox"], "bmu" => ["bum"], "amo" => ["moa"],
      "ago" => ["goa", "ago"], "adm" => ["dam", "mad"], "acn" => ["can"],
      "msu" => ["sum"], "dey" => ["dey", "dye"], "ais" => ["ais"], "eko" => ["oke"],
      "dgi" => ["gid", "dig"], "esw" => ["sew"], "epr" => ["rep", "per"],
      "lox" => ["lox"], "gow" => ["wog"], "awy" => ["yaw", "way"],
      "btu" => ["tub", "but"], "bno" => ["nob"], "dhu" => ["duh"], "aky" => ["yak"],
      "gpy" => ["gyp"], "acs" => ["sac"], "gty" => ["tyg"], "ety" => ["yet"],
      "gtu" => ["tug", "gut"], "eel" => ["eel", "lee"], "eiv" => ["vie"],
      "evx" => ["vex"], "ajm" => ["jam"], "aen" => ["ane", "nae"], "ksy" => ["sky"],
      "bop" => ["bop"], "hin" => ["hin"], "ahm" => ["ham"], "iop" => ["poi"],
      "glo" => ["log"], "ejt" => ["jet"], "dik" => ["kid"], "gnu" => ["gnu", "gun"],
      "ppu" => ["pup"], "bgu" => ["bug"], "atv" => ["vat"], "ahw" => ["haw"],
      "nor" => ["nor"], "dou" => ["oud", "udo", "duo"], "bko" => ["kob"],
      "apr" => ["rap", "par"], "fox" => ["fox"], "otw" => ["tow", "wot", "two"],
      "inw" => ["win"], "fgi" => ["fig"], "for" => ["fro", "for"], "jtu" => ["jut"],
      "cmw" => ["cwm"], "eek" => ["eek", "eke"], "ass" => ["ass"], "alr" => ["lar"],
      "bco" => ["cob"], "owy" => ["yow"], "ehy" => ["hey"], "fru" => ["fur"],
      "bin" => ["nib", "bin"], "opw" => ["pow", "wop"], "bsu" => ["sub", "bus"],
      "him" => ["him"], "aeu" => ["eau"], "apz" => ["zap"], "aiv" => ["via"],
      "efl" => ["elf"], "efn" => ["fen"], "err" => ["err"], "ims" => ["ism", "sim"],
      "ace" => ["ace"], "boo" => ["boo"], "gpu" => ["pug"], "adg" => ["gad"],
      "anw" => ["awn", "wan"], "afx" => ["fax"], "agt" => ["gat", "tag"],
      "kos" => ["kos"], "epw" => ["pew"], "abk" => ["kab"]}
    |> Map.get(string_id)
  end

  def valid_ids do
    ["abo", "aek", "hot", "oow", "ctu", "afr", "dgu", "abd", "hip", "elu", "inu",
     "bgi", "osy", "imx", "abf", "ikl", "nru", "gmy", "bde", "dsu", "lot", "agj",
     "muy", "ehu", "ehi", "hnt", "eov", "ajy", "aey", "eil", "deu", "bil", "ooz",
     "hop", "nno", "ggi", "acy", "npw", "ahp", "ivy", "aes", "mmo", "fnu", "ewy",
     "afn", "ott", "doy", "cgo", "abl", "aft", "dop", "bdo", "imn", "imm", "cgi",
     "cox", "chi", "flu", "ops", "epy", "tux", "eit", "ehr", "efk", "now", "app",
     "hoy", "acm", "ovw", "bfi", "amy", "atx", "ept", "psy", "amt", "fik", "aps",
     "itt", "aly", "bow", "aoz", "ddo", "akr", "alx", "ell", "dkl", "diy", "eny",
     "dim", "beg", "cno", "ajw", "opp", "eeg", "kop", "aot", "est", "aet", "deh",
     "imo", "mru", "orw", "dos", "inn", "etw", "aqu", "ill", "dei", "oty", "bio",
     "fop", "hmm", "hor", "den", "cit", "aim", "itz", "iko", "ilo", "gim", "fgo",
     "emn", "bbu", "nsu", "ilp", "hss", "rty", "coo", "oru", "fot", "ipt", "los",
     "emu", "ben", "egv", "enp", "alw", "bir", "cei", "ent", "eez", "mmu", "eey",
     "ekx", "add", "pry", "ady", "acp", "ems", "def", "blo", "ary", "mow", "bet",
     "dit", "ads", "ego", "eht", "abp", "esu", "eop", "bfo", "ahy", "ast", "abc",
     "eru", "gno", "guy", "efo", "anr", "ipr", "ekp", "adw", "iwz", "agr", "cho",
     "abb", "dir", "dpu", "atu", "efi", "aor", "egm", "anv", "dis", "del", "guv",
     "ens", "htu", "acl", "ehp", "gju", "aer", "bjo", "ilt", "ffo", "aep", "aal",
     "dry", "ino", "oww", "efr", "bmo", "efu", "det", "egg", "bbi", "boy", "act",
     "dot", "ahj", "deo", "bhu", "glu", "stu", "eno", "eip", "lsy", "eev", "eps",
     "amp", "eow", "bey", "moo", "adt", "bdu", "dnu", "asv", "cop", "ail", "ekn",
     "psu", "dor", "msy", "ant", "ajr", "ikt", "gjo", "adl", "lru", "dmo", "bis",
     "hos", "als", "bor", "cep", "avv", "bgo", "apx", "epp", "itu", "ehm", "ils",
     "bcu", "goy", "mpu", "iss", "lux", "enw", "aht", "ist", "dno", "eho", "ams",
     "hsy", "anp", "ahs", "osw", "iou", "bru", "gmo", "ehs", "acr", "adh", "etv",
     "cis", "foo", "amm", "dip", "ako", "ado", "esy", "ehx", "imr", "kuy", "emw",
     "imv", "aku", "cip", "adf", "aby", "abg", "agw", "bit", "hoo", "noy", "bnu",
     "hhu", "cdu", "apy", "abr", "bbe", "ikn", "git", "ain", "hnu", "dlo", "all",
     "eet", "coy", "giw", "mot", "biz", "eef", "gru", "efz", "eky", "fix", "gin",
     "buy", "ipz", "bos", "iks", "hmu", "got", "ach", "aeg", "imp", "eor", "ees",
     "ikp", "eft", "adi", "his", "eir", "dez", "dmu", "ipy", "agm", "bho", "bbo",
     "fir", "iln", "ost", "agg", "iny", "puy", "ael", "emo", "pxy", "giz", "dfi",
     "fly", "goo", "int", "air", "elm", "cru", "lop", "kow", "afo", "oop", "not",
     "sty", "any", "gij", "ely", "adk", "brr", "atw", "abj", "ehn", "abh", "cim",
     "els", "opr", "lpu", "fry", "ekl", "aks", "apt", "cor", "egi", "alp", "dhi",
     "npu", "art", "ekr", "asy", "ceu", "ghu", "bew", "ips", "cot", "eot", "aww",
     "loo", "egk", "agl", "ait", "aab", "efy", "dow", "hty", "ptu", "rwy", "emt",
     "agh", "ipx", "asx", "kor", "adn", "joy", "aan", "low", "isx", "elt", "abt",
     "fin", "aew", "ipp", "hwy", "ddi", "ahr", "opt", "itw", "hit", "bdi", "agn",
     "ins", "efw", "irs", "bpu", "aeh", "agy", "jot", "afg", "att", "rtu", "otu",
     "awx", "egl", "fis", "acw", "asw", "acd", "fou", "fgu", "aah", "inx", "oor",
     "dew", "eer", "nnu", "mos", "egr", "dil", "gho", "afy", "ouy", "din", "lpy",
     "how", "ery", "ags", "hmo", "ikr", "akt", "egt", "dhh", "coz", "amr", "inp",
     "dgo", "nos", "adp", "elv", "ilm", "der", "ehw", "ccs", "amw", "bee", "oot",
     "fit", "apw", "gir", "gip", "acv", "ntu", "abn", "ort", "ddu", "cdo", "ahn",
     "dux", "amn", "cry", "gmu", "hhs", "erv", "eew", "cow", "ciy", "ttu", "bij",
     "arw", "aag", "mop", "alm", "esx", "eep", "egp", "box", "aov", "agp", "amu",
     "mtu", "cpu", "osu", "dho", "opx", "bmu", "amo", "ago", "adm", "acn", "msu",
     "dey", "ais", "eko", "dgi", "esw", "epr", "lox", "gow", "awy", "btu", "bno",
     "dhu", "aky", "gpy", "acs", "gty", "ety", "gtu", "eel", "eiv", "evx", "ajm",
     "aen", "ksy", "bop", "hin", "ahm", "iop", "glo", "ejt", "dik", "gnu", "ppu",
     "bgu", "atv", "ahw", "nor", "dou", "bko", "apr", "fox", "otw", "inw", "fgi",
     "for", "jtu", "cmw", "eek", "ass", "alr", "bco", "owy", "ehy", "fru", "bin",
     "opw", "bsu", "him", "aeu", "apz", "aiv", "efl", "efn", "err", "ims", "ace",
     "boo", "gpu", "adg", "anw", "afx", "agt", "kos", "epw", "abk"]
    |> Enum.into(HashSet.new)
  end
end
