defmodule Jumble.ScowlDict.Size95.Length23 do
  def get(string_id) do
    %{"acceeghhilmoooopprrrtty" => ["electrophotomicrography"],
      "aacdehhiilllnooppprstuy" => ["pseudophilanthropically"],
      "aacddeiiiiilllnorstuvvy" => ["overindividualistically"],
      "deeeeeffgiiinnnpprrrrrr" => ["preinferredpreinferring"],
      "aeehhhhilllmnnooppsttuy" => ["thymolsulphonephthalein"],
      "aaacddeghillmmnnoortyyy" => ["magnetohydrodynamically"],
      "aaabcdeeehiilllmnoprstu" => ["pseudolamellibranchiate"],
      "aaaaccchhhiimnnorrrssty" => ["macracanthrorhynchiasis"],
      "aaaabiiilnnnorssstttttu" => ["transubstantiationalist"],
      "aaabdeeiiiilmmnnrsssstt" => ["disestablismentarianism"],
      "acceghhhiiillloooooppst" => ["philosophicotheological"],
      "aeeehhhhilllnnnoopppstu" => ["phenolsulphonephthalein"],
      "abcceeehllllmoorsstuxyy" => ["carboxymethylcelluloses"],
      "aaccddeeimnnooooprsttuy" => ["pancreaticoduodenostomy"],
      "aaeeeeeehhilmmnnrstttxy" => ["hexamethylenetetramines"],
      "abdeeeghiiilnnnssssstuu" => ["undistinguishablenesses"],
      "ceghiilmmnnooooprsstuuy" => ["psychoneuroimmunologist"],
      "aacddeeiiiiiimnoprrsstt" => ["pericardiomediastinitis"],
      "aaeeeiilmnnnnooprrssstt" => ["nonrepresentationalisms"],
      "aaaeegimnnoooorrssssttt" => ["gastroenteroanastomosis"],
      "abdeeeiilnnooopprrsssst" => ["disproportionablenesses"],
      "aaceeegghilmnooprrsstty" => ["electronystagmographies"],
      "acccddeefhhiilllooorrxy" => ["dihdroxycholecalciferol"],
      "aacceeeeeghhllnoopprrrt" => ["electroencephalographer"],
      "acddeefhhilllmooprsuxyy" => ["formaldehydesulphoxylic"],
      "abbeeiiiiilnrssstttttuu" => ["intersubstitutabilities"],
      "aacghhilllmnooooopprrty" => ["anthropomorphologically"],
      "aaccgghhiiilllooooopstt" => ["pathologicohistological"],
      "cdddeeeeefiimmnooprttyy" => ["epididymodeferentectomy"],
      "aabeeehiiilmnoooppprtty" => ["hypobetalipoproteinemia"],
      "abccdfhhllnoooooorrrruy" => ["hydrochlorofluorocarbon"],
      "abcceeehhilmnoopprrstty" => ["blepharosphincterectomy"],
      "aceeeehhmmoooopprrstttt" => ["hematospectrophotometer"],
      "aadeiiiiilnnnoossttttuz" => ["deinstitutionalizations"],
      "abdeeeghiiiilnnnssssstu" => ["indistinguishablenesses"],
      "aaccceefgghiiiilnooprst" => ["scientificogeographical"],
      "ceeghiilmmnnooooprssuuy" => ["psychoneuroimmunologies"],
      "cceeehimmoooopprrrssttt" => ["microspectrophotometers"],
      "aaccceeeeghhillnoopprrt" => ["electroencephalographic"],
      "ccceehiimmoooopprrrsttt" => ["microspectrophotometric"],
      "ceeefhhilllnoooorrrttuy" => ["chlorotrifluoroethylene"],
      "aaaabeehiiilmnnnrsssttt" => ["antiestablishmentarians"],
      "aaeiiiiilnnnoorssttttuz" => ["reinstitutionalizations"],
      "acddeefhhiillmnoooorrtu" => ["dichlorodifluoromethane"],
      "bcdeeeiilnnooooprrstuxy" => ["desoxyribonucleoprotein"],
      "ccdeeeeinnooprrsssttuuv" => ["counterproductivenesses"],
      "aaceeeiiilllnnoortttuvz" => ["overintellectualization"]}
    |> Map.get(string_id)
  end

  def valid_ids do
    ["acceeghhilmoooopprrrtty", "aacdehhiilllnooppprstuy",
     "aacddeiiiiilllnorstuvvy", "deeeeeffgiiinnnpprrrrrr",
     "aeehhhhilllmnnooppsttuy", "aaacddeghillmmnnoortyyy",
     "aaabcdeeehiilllmnoprstu", "aaaaccchhhiimnnorrrssty",
     "aaaabiiilnnnorssstttttu", "aaabdeeiiiilmmnnrsssstt",
     "acceghhhiiillloooooppst", "aeeehhhhilllnnnoopppstu",
     "abcceeehllllmoorsstuxyy", "aaccddeeimnnooooprsttuy",
     "aaeeeeeehhilmmnnrstttxy", "abdeeeghiiilnnnssssstuu",
     "ceghiilmmnnooooprsstuuy", "aacddeeiiiiiimnoprrsstt",
     "aaeeeiilmnnnnooprrssstt", "aaaeegimnnoooorrssssttt",
     "abdeeeiilnnooopprrsssst", "aaceeegghilmnooprrsstty",
     "acccddeefhhiilllooorrxy", "aacceeeeeghhllnoopprrrt",
     "acddeefhhilllmooprsuxyy", "abbeeiiiiilnrssstttttuu",
     "aacghhilllmnooooopprrty", "aaccgghhiiilllooooopstt",
     "cdddeeeeefiimmnooprttyy", "aabeeehiiilmnoooppprtty",
     "abccdfhhllnoooooorrrruy", "abcceeehhilmnoopprrstty",
     "aceeeehhmmoooopprrstttt", "aadeiiiiilnnnoossttttuz",
     "abdeeeghiiiilnnnssssstu", "aaccceefgghiiiilnooprst",
     "ceeghiilmmnnooooprssuuy", "cceeehimmoooopprrrssttt",
     "aaccceeeeghhillnoopprrt", "ccceehiimmoooopprrrsttt",
     "ceeefhhilllnoooorrrttuy", "aaaabeehiiilmnnnrsssttt",
     "aaeiiiiilnnnoorssttttuz", "acddeefhhiillmnoooorrtu",
     "bcdeeeiilnnooooprrstuxy", "ccdeeeeinnooprrsssttuuv",
     "aaceeeiiilllnnoortttuvz"]
    |> Enum.into(HashSet.new)
  end
end
