defmodule Jumble.ScowlDict.Length3 do
  def get(string_id) do
    %{"bez" => [["bez"]], "loy" => [["loy"]], "abo" => [["boa"], ["abo", "oba"]],
      "aek" => [["kea"], ["ake", "kae"]], "fgk" => [["kgf"]], "imz" => [["miz"]],
      "hot" => [["hot"], ["tho"]], "aem" => [["mae"], ["ame", "eam", "mea"]],
      "oow" => [["woo"]], "ctu" => [["cut"], ["utc"]],
      "afr" => [["far"], ["arf", "fra"], ["raf"]], "mux" => [["mux"]],
      "zzz" => [["zzz"]], "eoy" => [["oye"], ["yeo", "yoe"]],
      "ahk" => [["hak", "kha"]], "dgu" => [["dug"], ["gud"]],
      "abd" => [["bad"], ["dab"], ["abd"]], "lor" => [["lor"], ["orl"]],
      "hip" => [["hip"], ["phi"], ["iph"]], "afp" => [["afp", "fap"]],
      "elu" => [["leu"], ["ule"], ["lue"]], "swy" => [["swy"]], "inu" => [["uni"]],
      "bgi" => [["big"], ["gib"]], "osy" => [["soy"], ["oys", "yos"]],
      "pru" => [["pur", "urp"]], "imx" => [["mix"]], "bms" => [["msb"]],
      "abf" => [["fab"], ["afb"]], "ikl" => [["ilk"], ["kil"]],
      "nru" => [["run"], ["urn"], ["nur"]], "gmy" => [["gym"], ["myg"]],
      "bde" => [["bed"], ["deb"], ["bde"]], "dsu" => [["sud"], ["uds"]],
      "gox" => [["gox"]], "lot" => [["lot"], ["tlo", "tol"]],
      "bnw" => [["nbw", "wbn"]], "agj" => [["jag"], ["gaj"]], "muy" => [["yum"]],
      "cly" => [["cly"], ["lyc"]], "ehu" => [["hue"]], "elp" => [["lep"], ["pel"]],
      "bgl" => [["glb"]], "ehi" => [["hie"], ["hei"]], "egu" => [["gue"]],
      "hnt" => [["nth"]], "eov" => [["voe"]], "bel" => [["elb"]],
      "ajy" => [["jay"]], "frt" => [["tfr", "trf"]], "htw" => [["hwt"]],
      "gry" => [["gry"]], "ano" => [["noa", "ona"]], "aat" => [["taa"]],
      "aey" => [["aye"], ["yea"]], "eil" => [["lie"], ["lei"], ["eli", "ile"]],
      "deu" => [["due"]], "bil" => [["lib"]], "iqu" => [["qui"]],
      "ooz" => [["zoo"]], "hop" => [["hop"], ["pho", "poh"]], "nno" => [["non"]],
      "ggi" => [["gig"], ["igg"]], "cfm" => [["mcf"]], "acy" => [["cay"], ["acy"]],
      "npw" => [["pwn"]], "ahp" => [["pah"], ["hap"], ["aph"]],
      "apu" => [["pau", "pua"]], "ivy" => [["ivy"]],
      "aes" => [["sea"], ["eas"], ["aes", "ase"]], "ekw" => [["ewk"]],
      "mmo" => [["mom"]], "fnu" => [["fun"]], "ewy" => [["yew"], ["wey", "wye"]],
      "afn" => [["fan"], ["naf"]], "gkr" => [["kgr"]], "ott" => [["tot"]],
      "psw" => [["psw"]], "hlo" => [["hol"]], "doy" => [["yod"]],
      "clt" => [["tlc"]], "iju" => [["uji"]], "cgo" => [["cog"]],
      "abl" => [["lab"], ["alb"]], "aft" => [["fat"], ["aft"]],
      "dop" => [["pod"], ["dop"]], "bdo" => [["bod", "dob"]], "imn" => [["nim"]],
      "imm" => [["mim"]], "sst" => [["tss"]], "crs" => [["crs"]],
      "cgi" => [["cig"]], "cox" => [["cox"]], "fno" => [["fon"]],
      "mps" => [["pms"]], "fll" => [["fll"]], "crt" => [["crt"]],
      "eej" => [["jee"]], "chi" => [["chi"], ["hic"], ["ich"]], "flu" => [["flu"]],
      "aln" => [["aln", "lan"]], "ops" => [["sop"], ["ops"]],
      "epy" => [["yep"], ["pye"]], "tux" => [["tux"]], "lnp" => [["lpn"]],
      "eit" => [["tie"]], "otv" => [["tov"]], "ehr" => [["her"], ["reh"], ["rhe"]],
      "efk" => [["kef"]], "hny" => [["hny"]], "ior" => [["rio", "roi"]],
      "fil" => [["fil"], ["lif"]], "now" => [["now", "own", "won"]],
      "app" => [["pap"], ["ppa"]], "lnt" => [["tln"]], "lnr" => [["lnr"]],
      "hoy" => [["hoy"]], "oos" => [["oos"]], "acm" => [["cam"], ["mac"]],
      "hku" => [["khu"]], "ovw" => [["vow"]], "gmt" => [["gmt"]],
      "bfi" => [["fib"], ["fbi"]], "amy" => [["may"], ["yam"], ["mya"], ["amy"]],
      "ajn" => [["jan"]], "atx" => [["tax"], ["xat"]], "frs" => [["rfs"]],
      "ikm" => [["kim"]], "ept" => [["pet"]], "psy" => [["spy"]],
      "amt" => [["mat"], ["tam"]], "clu" => [["cul"]], "fik" => [["kif"]],
      "aps" => [["pas", "sap", "spa"], ["asp"]], "itt" => [["tit"]],
      "rsy" => [["syr"]], "aly" => [["lay"], ["aly"]], "bow" => [["bow"], ["wob"]],
      "prt" => [["trp"]], "aoz" => [["azo", "zoa"]], "ddo" => [["odd"], ["dod"]],
      "akr" => [["ark"], ["kra"]], "alx" => [["lax"]], "cht" => [["tch"]],
      "mpv" => [["mvp"]], "ell" => [["ell"]], "euy" => [["uey"], ["yue"]],
      "foy" => [["foy"]], "dkl" => [["dkl"]], "diy" => [["yid"]],
      "esz" => [["sez"]], "ors" => [["ors"], ["ros"]], "dix" => [["dix"]],
      "eny" => [["yen"], ["nye"], ["eyn"]], "enn" => [["nne"]],
      "dim" => [["dim"], ["mid"]], "beg" => [["beg"], ["geb"]],
      "cno" => [["con"], ["nco"]], "fio" => [["iof"]], "bsw" => [["sbw", "wbs"]],
      "ajw" => [["jaw"]], "opp" => [["pop"]], "eeg" => [["gee"], ["eeg"]],
      "dqt" => [["qtd"]], "lou" => [["luo"]], "kop" => [["kop"]],
      "aot" => [["oat"], ["tao"], ["toa"]], "ddm" => [["dmd"]], "est" => [["set"]],
      "aet" => [["ate", "eat", "tea"], ["eta"]], "iio" => [["oii"]],
      "auv" => [["uva", "vau"]], "flo" => [["flo", "lof"]],
      "bch" => [["bch", "hcb"]], "ilr" => [["lir"]], "deh" => [["edh"]],
      "cpt" => [["cpt", "tcp"]], "imo" => [["moi"], ["imo"]], "mru" => [["rum"]],
      "ssw" => [["ssw"]], "orw" => [["row"], ["wro"]],
      "dos" => [["sod"], ["dos"], ["dso", "ods"]], "inn" => [["inn"]],
      "bfr" => [["rfb"]], "etw" => [["wet"], ["tew"], ["ewt"]], "aqu" => [["qua"]],
      "kou" => [["kou", "ouk"]], "dht" => [["thd"]], "ill" => [["ill"]],
      "dei" => [["die"], ["ide"], ["dei"]], "oty" => [["toy"], ["yot"]],
      "kno" => [["kon"]], "bcc" => [["cbc"]], "hpp" => [["pph"]],
      "bio" => [["obi"]], "fop" => [["fop"]], "cju" => [["cuj"]],
      "hmm" => [["hmm"]], "ipv" => [["vip"]], "lmo" => [["olm"]],
      "hor" => [["rho"]], "ein" => [["nei", "nie"]],
      "den" => [["end"], ["den"], ["ned"]], "bpy" => [["byp"]], "cit" => [["tic"]],
      "aim" => [["aim"], ["ami"], ["mia"]], "bgn" => [["nbg"]], "ekz" => [["zek"]],
      "itz" => [["zit"]], "uzz" => [["zuz"]], "iko" => [["oik"], ["koi"], ["oki"]],
      "ilo" => [["oil"], ["ilo"]], "gim" => [["mig"], ["gim"]], "fgo" => [["fog"]],
      "emn" => [["men"]], "rsu" => [["urs"], ["sur"]], "avx" => [["vax"]],
      "eik" => [["eik", "ike", "kie"]], "www" => [["www"]], "cfh" => [["cfh"]],
      "bbu" => [["bub"]], "nsu" => [["sun"], ["nus"], ["uns"]], "imu" => [["imu"]],
      "acu" => [["uca"]], "elr" => [["ler", "rle"]], "afm" => [["mfa"]],
      "ilp" => [["lip"], ["ipl", "pil", "pli"]], "hss" => [["ssh"]],
      "jnr" => [["jnr"]], "duw" => [["wud"]], "rty" => [["try"], ["tyr"]],
      "abe" => [["bae"]], "opu" => [["upo"], ["oup"]], "coo" => [["coo"]],
      "oru" => [["our"]], "fot" => [["oft"], ["fot"]], "orx" => [["rox"]],
      "etz" => [["tez"]], "ipt" => [["pit", "tip"], ["tpi"]],
      "ahi" => [["ahi", "hia"]], "los" => [["sol"], ["los"]],
      "nov" => [["von"], ["nov"]], "cpy" => [["cyp"]], "dll" => [["ldl", "lld"]],
      "emu" => [["emu"], ["meu"], ["ume"]], "iiv" => [["vii"]],
      "ben" => [["ben", "neb"], ["ebn", "nbe"]], "egv" => [["veg"]],
      "lno" => [["nol"]], "mst" => [["mst", "mts", "stm"]], "ccm" => [["ccm"]],
      "enp" => [["pen"], ["nep"]], "alw" => [["law"], ["awl"], ["alw"]],
      "bir" => [["rib"]], "cei" => [["ice"]], "ent" => [["net", "ten"]],
      "bll" => [["llb"]], "iii" => [["iii"]], "grx" => [["grx"]],
      "ajk" => [["jak"]], "eez" => [["zee"]], "mmu" => [["mum"], ["umm"]],
      "aix" => [["aix"]], "eey" => [["eye"], ["yee"]], "ekx" => [["kex"]],
      "add" => [["add"], ["dad"]], "ppt" => [["ptp"]], "ccf" => [["cfc"]],
      "pry" => [["pry"], ["pyr"]], "ady" => [["day"], ["ady", "yad"]],
      "aru" => [["aru", "ura"]], "acp" => [["cap"], ["pac"], ["apc", "cpa"]],
      "ems" => [["mes"], ["ems"], ["esm"]], "def" => [["fed"]], "suy" => [["yus"]],
      "blo" => [["lob"], ["blo", "bol"]],
      "ary" => [["ray"], ["rya"], ["ary", "yar"], ["ayr"]], "ckw" => [["ckw"]],
      "hps" => [["shp"]], "nuw" => [["wun"]], "isu" => [["sui"]],
      "mow" => [["mow"], ["wmo"]], "ddt" => [["ddt", "dtd"]],
      "alu" => [["aul", "ula"]], "opy" => [["poy"]], "bet" => [["bet"]],
      "dit" => [["dit"], ["tid"], ["itd"]], "ads" => [["sad"], ["ads"], ["das"]],
      "ego" => [["ego"], ["geo"]], "cls" => [["lsc"]], "drt" => [["tdr"]],
      "eht" => [["the"], ["eth"]], "een" => [["een", "ene"]], "abp" => [["bap"]],
      "esu" => [["use"], ["sue"]], "eop" => [["ope"]], "bfo" => [["fob"]],
      "mrs" => [["mrs"]], "afk" => [["kaf"]], "ahy" => [["hay"], ["yah"]],
      "ast" => [["sat"], ["tas"], ["ast"]], "ceh" => [["che"], ["ech"]],
      "lmy" => [["lym"]], "isy" => [["yis"]], "kkk" => [["kkk"]],
      "abc" => [["cab"], ["abc", "bac"]], "bht" => [["thb"]],
      "eru" => [["rue"], ["ure"]], "gno" => [["nog"], ["gon"]],
      "guy" => [["guy"], ["yug"]], "efo" => [["foe"], ["eof"]], "giu" => [["gui"]],
      "hox" => [["hox"]], "anr" => [["ran"], ["arn", "nar", "rna"]],
      "ceo" => [["ceo", "eco"]], "ipr" => [["rip"], ["ipr", "pir"]],
      "ekp" => [["kep"]], "adw" => [["wad"], ["daw"], ["awd"]], "iwz" => [["wiz"]],
      "agr" => [["rag"], ["gar"], ["arg", "gra"]],
      "cho" => [["och"], ["hoc"], ["cho"]], "abb" => [["abb"], ["bab"]],
      "cik" => [["ick"]], "cce" => [["ecc"]], "dir" => [["rid"]],
      "dpu" => [["pud"]], "atu" => [["tau"], ["uta"], ["tua"]],
      "efi" => [["fie"], ["fei", "ife"]], "aor" => [["oar"], ["ora"], ["aor"]],
      "egm" => [["gem"], ["meg"]], "ewx" => [["wex"]], "anv" => [["van"]],
      "flp" => [["plf"]], "dis" => [["dis"], ["ids"]], "owx" => [["wox"]],
      "del" => [["led"], ["eld"], ["dle"]], "ruw" => [["wur"]], "clo" => [["loc"]],
      "iqs" => [["qis"], ["iqs"]], "guv" => [["guv"], ["vug"]], "ens" => [["ens"]],
      "htu" => [["hut"]], "bes" => [["bes"], ["ebs", "sbe"]], "fvw" => [["vfw"]],
      "acl" => [["lac"], ["lca"]], "ehp" => [["hep"], ["peh"]],
      "gju" => [["jug"], ["gju"]], "biu" => [["ubi"]], "agv" => [["vag"]],
      "nop" => [["pon"]], "fms" => [["sfm"]],
      "aer" => [["are"], ["ear", "era"], ["aer", "rea"]], "kly" => [["kyl"]],
      "bjo" => [["job"]], "ilt" => [["lit"], ["til"]], "orv" => [["vor"]],
      "tuy" => [["tuy"]], "ffo" => [["off"]], "aep" => [["ape", "pea"], ["epa"]],
      "aal" => [["ala"], ["aal", "laa"]], "dry" => [["dry"]],
      "ino" => [["ion"], ["oni"]], "cnu" => [["cun", "unc"]], "oww" => [["wow"]],
      "ajs" => [["saj"]], "fgr" => [["frg", "grf"]],
      "efr" => [["fer", "ref"], ["erf"]], "bmo" => [["mob"], ["bom", "omb"]],
      "efu" => [["feu"]], "agu" => [["gau"]], "agz" => [["zag"]],
      "det" => [["ted"]], "egg" => [["egg"]], "bbi" => [["bib"]],
      "boy" => [["boy"], ["yob"]], "hio" => [["hoi"]], "eio" => [["oie"]],
      "act" => [["act", "cat"]], "dot" => [["dot"], ["tod"]], "deq" => [["qed"]],
      "afl" => [["alf"]], "ahj" => [["haj"], ["jah"]],
      "deo" => [["doe"], ["ode"], ["edo"]], "bcd" => [["bcd", "dcb"]],
      "bhu" => [["hub"]], "aco" => [["oca"]], "glu" => [["lug"], ["gul"]],
      "stu" => [["uts"], ["ust"]], "hmz" => [["mhz"]], "eno" => [["one"], ["neo"]],
      "eip" => [["pie"], ["epi"]], "suz" => [["suz"]], "lsy" => [["sly"], ["lys"]],
      "cst" => [["cst", "sct"]], "ijt" => [["tji"]], "eev" => [["eve"], ["vee"]],
      "eps" => [["pes"]], "tuu" => [["utu"]], "amp" => [["map"], ["amp"]],
      "eow" => [["owe"], ["woe"]], "cfp" => [["fcp", "pcf", "pfc"]],
      "dtt" => [["tdt"]], "suw" => [["wus"], ["usw"]], "bey" => [["bye"], ["bey"]],
      "abs" => [["bas", "sab"], ["asb"]], "dgm" => [["mgd"]],
      "moo" => [["moo"], ["oom"]], "opv" => [["opv"]], "adt" => [["tad"]],
      "exz" => [["zex"]], "qrs" => [["qrs"]], "aai" => [["aia"], ["iaa"]],
      "fpx" => [["pfx"]], "gps" => [["gps"]], "dhy" => [["hyd"]],
      "avw" => [["vaw"]], "ovx" => [["vox"]], "bdu" => [["bud", "dub"]],
      "dnu" => [["dun"]], "asv" => [["vas"], ["sav"]], "axz" => [["zax"]],
      "cop" => [["cop"], ["cpo"]], "mqu" => [["qum"]], "bhl" => [["lhb"]],
      "bls" => [["bls"]], "cdr" => [["cdr"]], "fmt" => [["fmt"]],
      "ail" => [["ail"], ["lai"]], "elw" => [["lew"]], "dgk" => [["dkg"]],
      "ekn" => [["ken"], ["nek"]], "psu" => [["ups"], ["pus", "sup"]],
      "cil" => [["cli"]], "dor" => [["rod"], ["dor"]], "msy" => [["mys"]],
      "ant" => [["ant", "tan"]], "ajr" => [["jar"], ["raj"]], "dfo" => [["fod"]],
      "ikt" => [["kit"]], "gjo" => [["jog"]], "mrt" => [["trm"]],
      "ntt" => [["tnt"]], "bcf" => [["bcf"]], "adl" => [["lad"]],
      "lru" => [["lur"]], "dmo" => [["mod"]], "exy" => [["yex"]],
      "ejo" => [["joe"]], "bis" => [["bis"], ["sib"]],
      "hos" => [["ohs"], ["hos"], ["sho"]], "gtt" => [["gtt", "tgt"]],
      "als" => [["sal"], ["als", "las"], ["asl", "sla"]], "ckt" => [["tck"]],
      "irz" => [["riz"]], "iku" => [["kui"]], "fiz" => [["fiz"]],
      "dex" => [["dex", "xed"]], "bhr" => [["rhb"]], "emq" => [["meq"]],
      "ejn" => [["jen"]], "bor" => [["rob"], ["orb"]], "cep" => [["pec"], ["cep"]],
      "avv" => [["vav"]], "ghz" => [["ghz"]], "bgo" => [["bog"], ["gob"]],
      "abi" => [["bai", "iba"]], "apx" => [["pax"], ["apx"]], "puw" => [["wup"]],
      "epp" => [["pep"]], "inv" => [["vin"]], "eem" => [["eme"], ["mee"]],
      "itu" => [["tui"], ["tiu", "uit", "uti"]], "ehm" => [["hem"], ["meh"]],
      "ber" => [["reb"], ["ber"]], "ixx" => [["xix", "xxi"]],
      "ils" => [["lis"], ["sil"]], "giv" => [["vig"]], "bcu" => [["cub"], ["ubc"]],
      "hir" => [["hir"]], "goy" => [["goy"], ["ygo"]], "cpr" => [["cpr", "prc"]],
      "mpu" => [["ump"]], "iss" => [["sis"]], "lux" => [["lux"]],
      "muv" => [["vum"]], "enw" => [["new"], ["wen"]], "aht" => [["hat"], ["tha"]],
      "pss" => [["sps"]], "ist" => [["its", "sit"], ["tis"], ["ist", "tsi"]],
      "dno" => [["don"], ["nod"]], "alt" => [["tal"]], "eho" => [["hoe"], ["heo"]],
      "ams" => [["mas"], ["sam"], ["sma"]], "hsy" => [["shy"]],
      "anp" => [["pan"], ["nap"]], "lmw" => [["lwm"]],
      "ahs" => [["has"], ["ash"], ["ahs", "sha"], ["sah"]],
      "cgt" => [["ctg", "gtc"]], "bsy" => [["bys"]], "bdh" => [["bhd"]],
      "osw" => [["sow"], ["ows", "wos"]], "eeh" => [["hee"]],
      "iou" => [["oui"], ["iou"]], "bru" => [["rub"], ["bur"], ["urb"]],
      "stt" => [["tst"]], "gmo" => [["mog"]], "mtv" => [["tmv"]],
      "cfs" => [["fcs", "scf"]], "ehs" => [["hes", "she"], ["ehs"]],
      "acr" => [["car"], ["arc"]], "acz" => [["zac"]], "gis" => [["gis"]],
      "adh" => [["had"], ["dah"], ["adh", "dha"]], "dmx" => [["mxd"]],
      "etv" => [["vet"]], "dky" => [["kyd"]], "cis" => [["sic"], ["cis"], ["csi"]],
      "foo" => [["oof"], ["foo"], ["ofo"]], "amm" => [["mam"]],
      "dip" => [["dip"], ["idp", "pid"]],
      "ako" => [["oak"], ["koa", "oka"], ["ako"]], "eim" => [["mei"]],
      "dru" => [["rud", "urd"], ["dur"]],
      "ado" => [["ado"], ["oda"], ["dao", "doa", "oad"]], "rst" => [["trs"]],
      "bef" => [["bef", "feb"]], "cko" => [["ock"]],
      "esy" => [["yes"], ["sey", "sye"]], "dnp" => [["pdn"]],
      "pst" => [["pst"], ["tps"]], "dsy" => [["dys", "yds"]], "ehx" => [["hex"]],
      "imr" => [["rim"], ["mir"], ["mri"]], "abw" => [["wab"], ["baw"]],
      "beo" => [["obe"], ["boe"]], "aev" => [["vae"]], "fow" => [["fow"]],
      "adu" => [["dau"]], "ekv" => [["kev"]], "kuy" => [["yuk"], ["kyu"]],
      "ggr" => [["ggr"]], "imt" => [["mit", "tim"]], "emw" => [["mew"], ["wem"]],
      "imv" => [["vim"]], "aku" => [["auk"], ["aku"]], "moz" => [["moz"]],
      "cip" => [["pic"], ["cpi", "pci"]], "adf" => [["fad"], ["afd"]],
      "aas" => [["aas"], ["saa"]], "aby" => [["bay"], ["aby"]], "ijz" => [["jiz"]],
      "aam" => [["ama", "maa"], ["aam"]], "aaw" => [["awa"]],
      "abg" => [["bag"], ["gab"]], "agw" => [["wag"], ["gaw"]],
      "bit" => [["bit"], ["tib"]], "dmr" => [["mrd"]], "eqs" => [["esq"]],
      "fgp" => [["pfg"]], "hoo" => [["oho"], ["ooh"], ["hoo"]],
      "aho" => [["hao", "hoa"], ["aho"]], "ayy" => [["yay"]], "cgm" => [["mcg"]],
      "cdf" => [["cdf", "cfd"]], "frz" => [["rfz"]],
      "noy" => [["yon"], ["noy"], ["ony"]], "bnu" => [["bun"], ["nub"]],
      "hms" => [["msh"]], "hhu" => [["huh"]], "cdu" => [["cud"], ["duc"]],
      "apy" => [["pay"], ["yap"], ["pya"]],
      "abr" => [["bar"], ["bra"], ["arb"], ["rab"]], "iix" => [["xii"]],
      "bbe" => [["ebb"]], "ikn" => [["ink"], ["kin"]], "tuw" => [["wut"]],
      "aow" => [["woa"]], "ett" => [["tet"]], "akm" => [["kam", "mak"]],
      "ars" => [["ars", "ras", "sar"]], "aaa" => [["aaa"]],
      "git" => [["git"], ["tig"]], "ain" => [["ain"]], "hnu" => [["hun"], ["unh"]],
      "mtx" => [["mtx"]], "lvy" => [["vly"]], "dlo" => [["old"], ["lod"]],
      "bim" => [["mib"], ["bim", "ibm"]], "all" => [["all"]], "eet" => [["tee"]],
      "coy" => [["coy"]], "nox" => [["nox"]], "clx" => [["xcl"]],
      "giw" => [["wig"]], "dss" => [["sds"]], "erz" => [["rez"], ["zer"]],
      "mot" => [["tom"], ["mot"]], "biz" => [["biz"]], "ehl" => [["hel"]],
      "qsu" => [["suq"]], "eef" => [["fee"]], "gru" => [["rug"], ["gur"]],
      "dpt" => [["tpd"]], "asz" => [["saz", "zas"]], "fim" => [["imf"]],
      "efz" => [["fez"]], "afu" => [["auf"], ["ufa"]], "eky" => [["key"], ["kye"]],
      "dds" => [["dds"]], "cmy" => [["myc"]], "fix" => [["fix"]],
      "gin" => [["gin"], ["ing", "nig"]], "ade" => [["dae"], ["ade", "dea", "ead"]],
      "jms" => [["jms"]], "bmp" => [["mpb"]], "iim" => [["imi"]],
      "abu" => [["abu"]], "qrt" => [["qtr"]], "ghq" => [["ghq"]],
      "aci" => [["cai"]], "buy" => [["buy"]], "bot" => [["tob"]],
      "dls" => [["lsd"]], "ipz" => [["zip"]], "lny" => [["lyn"]],
      "bos" => [["sob"], ["bos"]], "lmt" => [["ltm"]], "elo" => [["leo", "loe"]],
      "egs" => [["seg"]], "iks" => [["ski"], ["ksi"]], "acf" => [["caf"]],
      "hmu" => [["hum"]], "got" => [["got"], ["tog"]], "ach" => [["cha"], ["ach"]],
      "aeg" => [["age"]], "nww" => [["wnw"]], "imp" => [["imp"], ["ipm"]],
      "gos" => [["gos", "sog"]], "eor" => [["ore", "roe"], ["oer"]],
      "epz" => [["zep"]], "aar" => [["ara"]], "ees" => [["see"], ["ese"]],
      "enz" => [["zen"]], "ikp" => [["kip"], ["pik"]], "lpw" => [["lwp"]],
      "eft" => [["eft"], ["fet", "tef"]], "adi" => [["aid"], ["ida"]],
      "llu" => [["ull"]], "his" => [["his"], ["ish"], ["ihs", "shi"]],
      "eir" => [["ire"], ["rei"], ["eir", "rie"]], "dez" => [["zed"]],
      "ajp" => [["jap"]], "dmu" => [["mud"], ["dum"]], "ipy" => [["yip"]],
      "agm" => [["gam"]], "bho" => [["hob"], ["boh"]], "bbo" => [["bob"]],
      "fir" => [["fir"], ["rif"], ["fri"]], "iln" => [["nil"]], "nwy" => [["wyn"]],
      "doz" => [["dzo"]], "ijm" => [["jim"]], "ost" => [["sot"], ["tos"]],
      "bfu" => [["fub"]], "agg" => [["gag"]], "irx" => [["rix"]],
      "iny" => [["yin"]], "isw" => [["wis"]], "cns" => [["cns"]],
      "oxy" => [["oxy"], ["yox"]], "izz" => [["ziz"]], "egj" => [["jeg"]],
      "puy" => [["yup"], ["puy"]], "ael" => [["ale"], ["lea"], ["ela"]],
      "emo" => [["emo"], ["moe"]], "cem" => [["ecm"]], "dhp" => [["dph", "phd"]],
      "gnt" => [["tgn"]], "sww" => [["wsw"]], "cdi" => [["cid"]],
      "ory" => [["ory", "yor"]], "opz" => [["poz"]], "huy" => [["yuh"]],
      "ijn" => [["jin"]], "pxy" => [["pyx"]], "giz" => [["zig"]],
      "dfi" => [["fid"]], "fly" => [["fly"]], "cjl" => [["jcl"]],
      "anu" => [["anu"], ["una"]], "goo" => [["goo"]], "gor" => [["rog"]],
      "akl" => [["kal", "lak"]], "int" => [["tin"], ["nit"]],
      "air" => [["air"], ["ria"], ["rai"], ["ira"]], "gou" => [["gou"]],
      "elm" => [["elm"], ["mel"], ["lem"]], "cru" => [["cur"], ["cru"], ["ruc"]],
      "afw" => [["faw"], ["waf"]], "ios" => [["ios", "ois"], ["iso", "osi"]],
      "lop" => [["lop"], ["pol"], ["olp"]], "inz" => [["zin"]],
      "diu" => [["dui"], ["iud"]], "kow" => [["wok"], ["kow", "owk"]],
      "ggo" => [["gog"]], "bdm" => [["mbd"]], "etu" => [["ute"], ["tue"]],
      "ptt" => [["ptt"]], "dej" => [["jed"]], "aap" => [["apa"]],
      "bns" => [["bns"]], "blr" => [["brl"]], "lxx" => [["lxx"]],
      "iot" => [["toi"]], "afo" => [["oaf"], ["fao"]], "oop" => [["poo"], ["oop"]],
      "osz" => [["zos"], ["ozs"]], "not" => [["not"], ["ton"], ["ont"]],
      "ttx" => [["txt"]], "sty" => [["sty"]], "dee" => [["dee"]],
      "any" => [["any"], ["nay"], ["yan"]], "gij" => [["jig"]], "imw" => [["wim"]],
      "csw" => [["csw"]], "ely" => [["lye"], ["ley"], ["eyl"]], "ffi" => [["iff"]],
      "ejw" => [["jew"]], "adk" => [["dak"]], "ghp" => [["gph"]],
      "adz" => [["zad"]], "aop" => [["poa"], ["opa"]], "crv" => [["vcr"]],
      "dgp" => [["gdp", "gpd"]], "luz" => [["luz"]], "brr" => [["brr"]],
      "luu" => [["ulu"]], "ssu" => [["sus"], ["ssu"]],
      "atw" => [["taw", "wat"], ["twa"]], "abj" => [["jab"]], "nqu" => [["unq"]],
      "ehn" => [["hen"]], "hoz" => [["zho"]], "abh" => [["bah"], ["hab"]],
      "ahu" => [["ahu", "auh", "hau"]], "cim" => [["mic"]],
      "els" => [["els"], ["les"]], "opr" => [["pro"], ["por"]],
      "lpu" => [["pul"], ["plu"]], "fry" => [["fry"]], "ekl" => [["elk"], ["lek"]],
      "aks" => [["ask"], ["ska"], ["kas"]],
      "apt" => [["apt", "pat", "tap"], ["atp"]],
      "cor" => [["orc"], ["roc"], ["cro"]], "egi" => [["gie"]],
      "alp" => [["lap", "pal"], ["alp"], ["apl"]], "bbs" => [["bbs"]],
      "dhi" => [["hid"]], "adr" => [["ard"], ["dar"]], "npu" => [["pun"], ["unp"]],
      "art" => [["art"], ["rat"], ["tar"], ["tra"]], "bfs" => [["bsf", "fsb"]],
      "cps" => [["csp"]], "cfi" => [["ifc"]], "ekr" => [["erk"]],
      "asy" => [["say"], ["ays"], ["yas"]], "dde" => [["ded", "edd"]],
      "ceu" => [["cue"], ["ecu"]], "brw" => [["bwr"]], "ghu" => [["ugh"], ["hug"]],
      "dfu" => [["fud"]], "bew" => [["web"]], "ips" => [["pis", "sip"]],
      "cot" => [["cot"], ["toc"], ["cto", "otc"]], "eot" => [["toe"]],
      "aww" => [["waw"]], "lnu" => [["nul", "unl"]], "bfn" => [["bnf"]],
      "loo" => [["loo"]], "egk" => [["keg"], ["ekg"]], "arz" => [["zar"]],
      "agl" => [["lag"], ["gal"]], "bmr" => [["bmr"]], "cel" => [["cel"]],
      "atz" => [["azt", "zat"]], "ait" => [["ait"], ["tai"]], "oqu" => [["quo"]],
      "gmp" => [["gpm"]], "aab" => [["baa"], ["aba"]], "efy" => [["fey"]],
      "dow" => [["dow"], ["owd", "wod"]], "hty" => [["thy"]],
      "eos" => [["oes", "ose"], ["eos"]], "dmt" => [["mtd"]], "eju" => [["jeu"]],
      "ptu" => [["put"], ["tup"]], "rwy" => [["wry"]], "hho" => [["hoh"]],
      "egz" => [["gez"]], "emt" => [["met"], ["tem"]], "aqt" => [["qat"]],
      "agh" => [["hag"]], "ipx" => [["pix"]], "asx" => [["sax"]],
      "dlr" => [["rld"]], "kor" => [["kor"], ["rok"]], "lps" => [["spl"]],
      "adn" => [["and"], ["dan"], ["dna", "nad"]], "joy" => [["joy"]],
      "aan" => [["ana"], ["naa"]], "low" => [["low"], ["owl"]],
      "isx" => [["six"], ["xis"]], "fmu" => [["fum"]], "elt" => [["let"], ["elt"]],
      "muu" => [["umu"]], "abt" => [["bat", "tab"], ["abt"]],
      "nsy" => [["sny"], ["nys"]], "alo" => [["alo", "lao", "loa", "ola"]],
      "lrt" => [["tlr"]], "ckp" => [["kpc"]], "auy" => [["ayu"]],
      "fhs" => [["fsh", "shf"]], "fin" => [["fin"]], "moy" => [["moy", "yom"]],
      "kst" => [["tsk"]], "hii" => [["ihi"]], "aew" => [["awe"], ["wae"]],
      "ipp" => [["pip"], ["ppi"]], "xxx" => [["xxx"]], "hwy" => [["why"]],
      "mou" => [["mou"]], "efh" => [["feh"], ["ehf"]], "ddi" => [["did"]],
      "cee" => [["cee"], ["eec"]], "ahr" => [["rah"], ["rha"]],
      "gsu" => [["gus", "ugs"]], "opt" => [["top"], ["opt", "pot"]],
      "itw" => [["wit"], ["twi"]], "hit" => [["hit"]], "bdi" => [["bid"], ["dib"]],
      "agn" => [["nag"], ["gan"]], "bpx" => [["pbx"]],
      "ins" => [["sin"], ["ins"], ["nis"], ["isn"]], "fho" => [["foh"]],
      "cpp" => [["pcp"]], "doo" => [["doo"]], "efw" => [["few"]],
      "irs" => [["sir"], ["sri"], ["irs"]], "akz" => [["zak"]], "bpu" => [["pub"]],
      "aeh" => [["hae"]], "agy" => [["gay"], ["yag"], ["agy"]], "fsu" => [["ufs"]],
      "jot" => [["jot"]], "afg" => [["fag"]], "gov" => [["vog"]],
      "att" => [["tat"]], "rtu" => [["rut"], ["tur"]], "bpp" => [["ppb"]],
      "otu" => [["out"], ["tou"]], "awx" => [["wax"]], "egl" => [["leg"], ["gel"]],
      "fis" => [["ifs"], ["sif"]], "dks" => [["dks"]], "clr" => [["crl"]],
      "acw" => [["caw"], ["wac"]], "oox" => [["oxo"]],
      "asw" => [["saw", "was"], ["aws"], ["swa"]], "acd" => [["cad"], ["dca"]],
      "fou" => [["fou"], ["ufo"], ["ouf"]], "fgu" => [["fug"]],
      "aah" => [["aha"], ["aah"]], "hry" => [["rhy"]], "inx" => [["nix"]],
      "lmu" => [["lum"]], "oor" => [["roo"], ["oor"]], "dew" => [["wed"], ["dew"]],
      "eer" => [["ere"], ["ree"], ["eer"]], "mmy" => [["mym"]],
      "nnu" => [["nun"], ["unn"]], "dny" => [["dyn"]], "ioy" => [["iyo", "yoi"]],
      "mos" => [["oms"], ["som"]], "egr" => [["erg"]], "rux" => [["rux"]],
      "dil" => [["lid"]], "mpt" => [["tpm"]], "hmt" => [["thm", "tmh"]],
      "gho" => [["hog"]], "irt" => [["rti", "tri"]], "afy" => [["fay"]],
      "cft" => [["ctf"]], "ouy" => [["you"]], "din" => [["din"], ["nid"]],
      "lpy" => [["ply"]], "hiu" => [["hui"]], "gil" => [["lig"]],
      "how" => [["how", "who"]], "ery" => [["rye"], ["yer"], ["eyr"]],
      "elz" => [["lez", "zel"]], "ags" => [["gas"], ["sag"], ["ags"], ["asg"]],
      "nnw" => [["nnw"]], "hmo" => [["ohm"], ["mho"], ["hmo", "hom"]],
      "ikr" => [["irk"], ["kir"]], "inr" => [["rin"]],
      "eis" => [["sei"], ["ise", "sie"]], "btv" => [["bvt"]],
      "akt" => [["kat"], ["tak"]], "egt" => [["get"], ["teg"], ["gte"]],
      "acg" => [["cag"]], "dhh" => [["hhd"]], "coz" => [["coz"]],
      "amr" => [["arm"], ["ram"], ["mar"]], "isz" => [["isz"]],
      "lms" => [["mls", "sml"]], "inp" => [["pin"], ["nip"]],
      "dgo" => [["dog"], ["god"]], "xyz" => [["xyz"]], "osv" => [["sov"]],
      "bek" => [["keb"]], "nos" => [["son"], ["ons"]], "ers" => [["ers"], ["esr"]],
      "adp" => [["pad"], ["dap"]], "jow" => [["jow"]], "koy" => [["yok"]],
      "elv" => [["lev"]], "ilm" => [["mil"], ["lim"]], "grs" => [["grs"]],
      "afq" => [["qaf"]], "dlu" => [["lud"]], "ess" => [["ess"], ["sse"]],
      "der" => [["red"], ["erd"]], "fip" => [["fip"]], "chn" => [["chn"]],
      "ehw" => [["hew"]], "cdm" => [["cmd"]], "ccs" => [["csc"]],
      "amw" => [["maw"], ["awm"]], "bee" => [["bee"]],
      "oot" => [["too"], ["oot"], ["oto"]], "fit" => [["fit"]],
      "aik" => [["kai"], ["aik"]], "ans" => [["nas", "san"]], "dio" => [["ido"]],
      "apw" => [["paw"], ["wap"]], "tvw" => [["wtv"]], "dju" => [["jud"]],
      "lst" => [["lst", "slt"]], "gir" => [["rig"]], "gip" => [["pig"]],
      "acv" => [["vac"], ["cva"]], "ntu" => [["nut"], ["tun"]],
      "abn" => [["ban"], ["nab"], ["abn"]], "aiw" => [["iwa"]],
      "dhl" => [["hdl", "hld"]], "ort" => [["rot"], ["tor"], ["ort"]],
      "des" => [["sed"], ["des", "esd"]], "ddu" => [["dud"]],
      "cdo" => [["cod"], ["doc"]], "bce" => [["bec", "ecb"]],
      "ahn" => [["nah"], ["han"]], "ahh" => [["ahh"]], "ahv" => [["hav"]],
      "dux" => [["dux"]], "rtw" => [["rtw"]], "amn" => [["man"], ["mna", "nam"]],
      "ajt" => [["taj"], ["jat"]], "cry" => [["cry"]], "bfl" => [["flb"]],
      "gmu" => [["gum", "mug"]], "hhs" => [["shh"]], "iow" => [["iwo"]],
      "pps" => [["pps"]], "ehh" => [["heh"]], "hrw" => [["whr"]],
      "ppr" => [["prp"]], "erv" => [["rev"]], "aip" => [["pia"]],
      "eew" => [["wee"], ["ewe"]], "ghm" => [["mhg"]], "cow" => [["cow"]],
      "kps" => [["pks"]], "ciy" => [["icy"]], "ttu" => [["tut"]],
      "bij" => [["jib"]], "arw" => [["raw", "war"]], "ivx" => [["xiv", "xvi"]],
      "div" => [["vid"]], "hpt" => [["pht"], ["tph"]], "ksu" => [["suk"]],
      "aag" => [["aga"]], "cmo" => [["moc"]], "mop" => [["mop"], ["pom"]],
      "ejr" => [["jer"]], "alm" => [["lam"], ["mal"]], "dkm" => [["dkm"]],
      "esx" => [["sex"]], "rtt" => [["trt"]], "eep" => [["pee"]],
      "egp" => [["peg"]], "cfy" => [["fcy"]], "box" => [["box"]],
      "ltu" => [["lut"]], "bdl" => [["bld"]], "aov" => [["ova"], ["avo"]],
      "gnp" => [["gnp"]], "erw" => [["rew"]], "cmp" => [["cpm"]],
      "agp" => [["gap"]], "amu" => [["amu"], ["aum", "mau", "uma"]],
      "cdg" => [["cdg", "gcd"]], "mtu" => [["tum"], ["mut"]], "cpu" => [["cup"]],
      "ceg" => [["ecg"]], "arx" => [["rax"], ["arx"]], "osu" => [["sou"], ["ous"]],
      "dho" => [["hod"]], "opx" => [["pox"]], "vxx" => [["xxv"]],
      "ahl" => [["lah"]], "etx" => [["tex"]], "grr" => [["grr"]],
      "dem" => [["dem"]], "bmu" => [["bum"]], "amo" => [["moa"], ["mao", "oam"]],
      "ago" => [["ago"], ["goa"]], "dfr" => [["fdr"]], "adm" => [["mad"], ["dam"]],
      "acn" => [["can"]], "msu" => [["sum"], ["ums"]], "aav" => [["ava"]],
      "dey" => [["dye"], ["dey"], ["yed"]], "noo" => [["noo", "oon"]],
      "cpv" => [["pvc"]], "ccy" => [["cyc"]], "gio" => [["gio"], ["goi"]],
      "ais" => [["ais"], ["sai"]], "eko" => [["oke"]], "hno" => [["noh"]],
      "dgi" => [["dig"], ["gid"]], "hiv" => [["hiv"]],
      "akw" => [["kaw"], ["awk", "kwa"]], "abv" => [["abv"]], "cds" => [["scd"]],
      "ccr" => [["crc"]], "esw" => [["sew"]], "epr" => [["per"], ["rep"], ["pre"]],
      "lox" => [["lox"]], "gow" => [["wog"]], "awy" => [["way"], ["yaw"]],
      "chl" => [["hcl"]], "btu" => [["but"], ["tub"]],
      "hpu" => [["hup"], ["phu", "puh"]], "lpp" => [["ppl"]],
      "bno" => [["nob"], ["bon"]], "dhu" => [["duh"], ["dhu", "hud"]],
      "oyy" => [["yoy"]], "asu" => [["sau"], ["usa"]], "aky" => [["yak"], ["kay"]],
      "gpy" => [["gyp"]], "drs" => [["dsr"]], "buz" => [["buz"]],
      "acs" => [["sac"]], "bps" => [["pbs"]], "gty" => [["tyg"]],
      "ety" => [["yet"], ["tye"]], "aty" => [["tay"], ["yat"]],
      "gtu" => [["gut"], ["tug"], ["ugt"]], "aos" => [["oas", "sao"]],
      "krs" => [["krs"]], "eel" => [["eel", "lee"]], "apv" => [["pav", "pva"]],
      "eiv" => [["vie"], ["ive", "vei"]], "evx" => [["vex"]], "ajm" => [["jam"]],
      "aen" => [["nae"], ["ane"], ["ean"], ["nea"]], "hik" => [["khi"]],
      "ksy" => [["sky"]], "bop" => [["bop"], ["pob"]], "hin" => [["hin"]],
      "ahm" => [["ham"]], "iop" => [["poi"], ["ipo"]], "glo" => [["log"], ["gol"]],
      "aio" => [["iao"]], "hkz" => [["khz"]], "ejt" => [["jet"]],
      "cks" => [["csk"]], "afh" => [["fah"], ["fha", "haf"]], "dik" => [["kid"]],
      "gnu" => [["gun"], ["gnu"], ["ung"]], "ppu" => [["pup"]], "dqs" => [["sqd"]],
      "hsu" => [["uhs", "ush"]], "bgu" => [["bug"], ["gub"]], "fgn" => [["fgn"]],
      "hst" => [["hts", "sht", "tsh"]], "atv" => [["vat"], ["tav"]],
      "ahw" => [["haw"], ["wha"], ["wah"]], "nor" => [["nor"], ["ron"]],
      "dou" => [["duo"], ["oud", "udo"]], "diq" => [["qid"]],
      "bko" => [["kob"], ["bok"]], "aij" => [["jai"]],
      "apr" => [["par"], ["rap"], ["apr"]], "tty" => [["tty", "tyt"]],
      "llm" => [["llm"]], "fox" => [["fox"]],
      "otw" => [["two"], ["tow", "wot"], ["owt"]], "eku" => [["euk", "kue", "uke"]],
      "inw" => [["win"]], "fgi" => [["fig"], ["gif"]],
      "abm" => [["bam"], ["abm", "mab", "mba"]],
      "for" => [["for"], ["fro"], ["orf"]], "jtu" => [["jut"]], "cmw" => [["cwm"]],
      "eek" => [["eke"], ["eek"]], "ass" => [["ass"]], "blt" => [["blt"]],
      "dft" => [["dft"]], "akn" => [["kan", "nak"]], "egy" => [["gye"]],
      "iuz" => [["uzi"]], "efs" => [["efs", "fes"]], "alr" => [["lar"]],
      "cuz" => [["cuz"]], "bco" => [["cob"], ["boc"]], "ekt" => [["ket"]],
      "owy" => [["yow"], ["woy"]], "ehy" => [["hey"], ["hye", "yeh"]],
      "fru" => [["fur"], ["urf"]], "bin" => [["bin"], ["nib"]],
      "cet" => [["cte", "ect", "tec"]], "opw" => [["pow", "wop"]],
      "bsu" => [["bus"], ["sub"]], "him" => [["him"]], "aeu" => [["eau"]],
      "apz" => [["zap"]], "aiv" => [["via"], ["iva"]], "efl" => [["elf"], ["efl"]],
      "eoz" => [["ezo"]], "irw" => [["wir"]], "efn" => [["fen"], ["nef"]],
      "adj" => [["jad"]], "err" => [["err"]], "ims" => [["ism", "sim"], ["mis"]],
      "ace" => [["ace"]], "boo" => [["boo"], ["obo"]], "gpu" => [["pug"], ["gup"]],
      "adg" => [["gad"]], "anw" => [["wan"], ["awn"], ["naw"]], "cjw" => [["wjc"]],
      "afx" => [["fax"]], "erx" => [["rex"]], "gop" => [["gop"]],
      "agt" => [["tag"], ["gat"]], "fsz" => [["sfz"]], "kln" => [["kln"]],
      "lmx" => [["mlx"]], "fsy" => [["fys"]], "kos" => [["kos"], ["sok"]],
      "epw" => [["pew"]], "abk" => [["kab"]], "guz" => [["guz"]]}
    |> Map.get(string_id)
  end
end
