defmodule Jumble.ScowlDict.Size20.Length3.Dict do
  def get do
    %{"hot" => ["hot"], "ctu" => ["cut"], "afr" => ["far"], "dgu" => ["dug"],
      "abd" => ["bad"], "hip" => ["hip"], "bgi" => ["big"], "imx" => ["mix"],
      "nru" => ["run"], "bde" => ["bed"], "lot" => ["lot"], "eil" => ["lie"],
      "deu" => ["due"], "ggi" => ["gig"], "aes" => ["sea"], "fnu" => ["fun"],
      "afn" => ["fan"], "abl" => ["lab"], "aft" => ["fat"], "eit" => ["tie"],
      "ehr" => ["her"], "now" => ["now", "own", "won"], "acm" => ["cam"],
      "amy" => ["may"], "atx" => ["tax"], "ept" => ["pet"], "psy" => ["spy"],
      "aly" => ["lay"], "bow" => ["bow"], "ddo" => ["odd"], "dim" => ["dim"],
      "beg" => ["beg"], "cno" => ["con"], "opp" => ["pop"], "est" => ["set"],
      "aet" => ["ate", "eat", "tea"], "orw" => ["row"], "dos" => ["sod"],
      "etw" => ["wet"], "ill" => ["ill"], "dei" => ["die"], "oty" => ["toy"],
      "den" => ["end"], "aim" => ["aim"], "ilo" => ["oil"], "fgo" => ["fog"],
      "emn" => ["men"], "nsu" => ["sun"], "ilp" => ["lip"], "rty" => ["try"],
      "oru" => ["our"], "ipt" => ["pit", "tip"], "enp" => ["pen"], "alw" => ["law"],
      "cei" => ["ice"], "ent" => ["net", "ten"], "mmu" => ["mum"], "eey" => ["eye"],
      "add" => ["add"], "ady" => ["day"], "acp" => ["cap"], "def" => ["fed"],
      "ary" => ["ray"], "bet" => ["bet"], "ads" => ["sad"], "ego" => ["ego"],
      "eht" => ["the"], "esu" => ["sue", "use"], "ahy" => ["hay"], "ast" => ["sat"],
      "guy" => ["guy"], "anr" => ["ran"], "ipr" => ["rip"], "agr" => ["rag"],
      "dir" => ["rid"], "aor" => ["oar"], "anv" => ["van"], "del" => ["led"],
      "htu" => ["hut"], "aer" => ["ear", "era", "are"], "bjo" => ["job"],
      "ilt" => ["lit"], "ffo" => ["off"], "dry" => ["dry"], "ino" => ["ion"],
      "oww" => ["wow"], "bmo" => ["mob"], "egg" => ["egg"], "boy" => ["boy"],
      "act" => ["act", "cat"], "dot" => ["dot"], "deo" => ["doe"], "eno" => ["one"],
      "eip" => ["pie"], "amp" => ["amp", "map"], "eow" => ["owe"], "bey" => ["bye"],
      "ekn" => ["ken"], "psu" => ["ups"], "dor" => ["rod"], "ikt" => ["kit"],
      "adl" => ["lad"], "dmo" => ["mod"], "bgo" => ["bog"], "enw" => ["new"],
      "aht" => ["hat"], "ist" => ["its", "sit"], "dno" => ["don"], "hsy" => ["shy"],
      "anp" => ["pan"], "ahs" => ["ash", "has"], "bru" => ["rub"],
      "ehs" => ["hes", "she"], "acr" => ["arc", "car"], "adh" => ["had"],
      "etv" => ["vet"], "cis" => ["sic"], "dip" => ["dip"], "esy" => ["yes"],
      "aby" => ["bay"], "abg" => ["bag"], "bit" => ["bit"], "hhu" => ["huh"],
      "apy" => ["pay"], "abr" => ["bar"], "ikn" => ["ink"], "dlo" => ["old"],
      "all" => ["all"], "eef" => ["fee"], "eky" => ["key"], "fix" => ["fix"],
      "gin" => ["gin"], "buy" => ["buy"], "hmu" => ["hum"], "got" => ["got"],
      "aeg" => ["age"], "ees" => ["see"], "adi" => ["aid"], "his" => ["his"],
      "dmu" => ["mud"], "bbo" => ["bob"], "iln" => ["nil"], "fly" => ["fly"],
      "int" => ["tin"], "air" => ["air"], "not" => ["ton", "not"],
      "any" => ["nay", "any"], "opr" => ["pro"], "fry" => ["fry"], "aks" => ["ask"],
      "apt" => ["apt", "pat", "tap"], "dhi" => ["hid"], "npu" => ["pun"],
      "art" => ["rat", "art"], "asy" => ["say"], "ceu" => ["cue"], "ghu" => ["ugh"],
      "eot" => ["toe"], "agl" => ["lag"], "hty" => ["thy"], "ptu" => ["put"],
      "emt" => ["met"], "adn" => ["and"], "joy" => ["joy"], "low" => ["low"],
      "isx" => ["six"], "elt" => ["let"], "abt" => ["bat", "tab"], "hwy" => ["why"],
      "ddi" => ["did"], "opt" => ["opt", "pot", "top"], "itw" => ["wit"],
      "hit" => ["hit"], "bdi" => ["bid"], "ins" => ["sin"], "efw" => ["few"],
      "irs" => ["sir"], "bpu" => ["pub"], "agy" => ["gay"], "otu" => ["out"],
      "egl" => ["leg"], "asw" => ["saw", "was"], "dew" => ["wed"], "nnu" => ["nun"],
      "dil" => ["lid"], "gho" => ["hog"], "ouy" => ["you"], "how" => ["how", "who"],
      "ags" => ["gas"], "egt" => ["get"], "amr" => ["ram", "arm"], "inp" => ["pin"],
      "dgo" => ["god", "dog"], "nos" => ["son"], "adp" => ["pad"], "der" => ["red"],
      "oot" => ["too"], "fit" => ["fit"], "gip" => ["pig"], "ntu" => ["nut"],
      "abn" => ["ban"], "ort" => ["rot"], "amn" => ["man"], "cry" => ["cry"],
      "gmu" => ["gum", "mug"], "eew" => ["wee"], "cow" => ["cow"],
      "arw" => ["raw", "war"], "esx" => ["sex"], "box" => ["box"], "agp" => ["gap"],
      "cpu" => ["cup"], "ago" => ["ago"], "adm" => ["mad"], "acn" => ["can"],
      "msu" => ["sum"], "dgi" => ["dig"], "epr" => ["per"], "awy" => ["way"],
      "btu" => ["but"], "ety" => ["yet"], "gtu" => ["gut"], "ajm" => ["jam"],
      "ksy" => ["sky"], "ahm" => ["ham"], "glo" => ["log"], "ejt" => ["jet"],
      "dik" => ["kid"], "gnu" => ["gun"], "bgu" => ["bug"], "atv" => ["vat"],
      "nor" => ["nor"], "apr" => ["par"], "otw" => ["two"], "inw" => ["win"],
      "for" => ["for"], "ass" => ["ass"], "ehy" => ["hey"], "fru" => ["fur"],
      "bin" => ["bin"], "bsu" => ["bus"], "him" => ["him"], "aiv" => ["via"],
      "err" => ["err"], "ace" => ["ace"], "agt" => ["tag"]}
  end
end
