defmodule Jumble.ScowlDict.Size20.Length6.Dict do
  def get do
    %{"agimnn" => ["naming"], "demppu" => ["pumped"], "ghiinr" => ["hiring"],
      "aefhrt" => ["father"], "adeirv" => ["varied"], "eorstv" => ["voters"],
      "begins" => ["beings", "begins"], "aginvw" => ["waving"],
      "eilopt" => ["polite"], "aaemsz" => ["amazes"], "ailprs" => ["spiral"],
      "deikny" => ["kidney"], "gilnos" => ["losing"], "denrtu" => ["turned"],
      "adeelv" => ["leaved"], "adertv" => ["advert"], "aefmrr" => ["farmer"],
      "abgikn" => ["baking"], "mnoors" => ["morons"], "aeeflm" => ["female"],
      "ailrst" => ["trails", "trials"], "bcilpu" => ["public"],
      "eghluy" => ["hugely"], "eehlsv" => ["shelve"], "acdesu" => ["caused"],
      "adegrs" => ["grades"], "aeirrv" => ["arrive"], "dennou" => ["undone"],
      "eirstv" => ["strive"], "deffir" => ["differ"], "egnott" => ["gotten"],
      "cefint" => ["infect"], "ghiknt" => ["knight"], "acgins" => ["casing"],
      "egjlnu" => ["jungle"], "accitt" => ["tactic"], "adlnou" => ["unload"],
      "abessu" => ["abuses"], "borstu" => ["robust"], "ciinor" => ["ironic"],
      "giopst" => ["spigot"], "aceert" => ["create"], "cgiint" => ["citing"],
      "inoopt" => ["option"], "adeers" => ["erased"], "dehrsu" => ["rushed"],
      "abelms" => ["blames"], "abeilt" => ["albeit"], "adenot" => ["donate"],
      "acckrs" => ["cracks"], "abckls" => ["blacks"], "adirsu" => ["radius"],
      "bdilsu" => ["builds"], "aeiprs" => ["praise"], "fimnor" => ["inform"],
      "ceorst" => ["sector"], "cdeikn" => ["nicked"],
      "agilns" => ["aligns", "signal"], "adirwz" => ["wizard"],
      "degjsu" => ["judges"], "aeilrs" => ["serial"], "cdgino" => ["coding"],
      "aelsux" => ["sexual"], "ceffio" => ["office"], "ellmsy" => ["smelly"],
      "enrrtu" => ["return"], "acgint" => ["acting"], "dehiss" => ["dishes"],
      "aelmny" => ["namely"], "deemrt" => ["termed"], "abdenn" => ["banned"],
      "iilnov" => ["violin"], "hnortw" => ["thrown"], "aeeggn" => ["engage"],
      "adiosv" => ["avoids"], "deilrv" => ["drivel"],
      "adegnr" => ["ranged", "danger", "garden"], "deiist" => ["tidies"],
      "lloswy" => ["slowly"], "adeprw" => ["warped"], "bdeilo" => ["boiled"],
      "cdekoo" => ["cooked"], "dfnosu" => ["founds"], "cilopy" => ["policy"],
      "ellmss" => ["smells"], "eopprr" => ["proper"],
      "aeelps" => ["asleep", "please"], "beirsu" => ["buries"],
      "adeelr" => ["dealer", "leader"], "ddeilm" => ["middle"],
      "cdeils" => ["sliced"], "adffor" => ["afford"], "ablrtu" => ["brutal"],
      "elostw" => ["lowest"], "deglno" => ["golden"], "dllouy" => ["loudly"],
      "giinpw" => ["wiping"], "aeestt" => ["estate"], "ooprst" => ["troops"],
      "adeflw" => ["flawed"], "eiklnu" => ["unlike"], "acorss" => ["across"],
      "ciimtv" => ["victim"], "efgiru" => ["figure"], "ijnruy" => ["injury"],
      "deeeln" => ["needle"], "ceknor" => ["reckon"], "fgiinx" => ["fixing"],
      "abceem" => ["became"], "aeiknt" => ["intake"], "demrru" => ["murder"],
      "ehorty" => ["theory"], "firstu" => ["fruits"], "ceilss" => ["slices"],
      "aelpst" => ["plates"], "cckoou" => ["cuckoo"], "aehnpp" => ["happen"],
      "aeintv" => ["native"], "ceiotx" => ["exotic"], "bbdemo" => ["bombed"],
      "eeopsx" => ["expose"], "ehhnpy" => ["hyphen"], "bdnooy" => ["nobody"],
      "corrsu" => ["cursor"], "ahinsv" => ["vanish"], "aehkns" => ["shaken"],
      "deeils" => ["diesel"], "ceejrt" => ["reject"], "alprty" => ["partly"],
      "ddehin" => ["hidden"], "deirrv" => ["driver"], "adempp" => ["mapped"],
      "ekmnoy" => ["monkey"], "eerrtv" => ["revert"], "abefhl" => ["behalf"],
      "eefprr" => ["prefer"], "aeenrr" => ["nearer"], "ackrst" => ["tracks"],
      "abehss" => ["bashes"], "abinry" => ["binary"], "eisssu" => ["issues"],
      "einntv" => ["invent"], "beilmo" => ["mobile"], "ekorrw" => ["worker"],
      "aegint" => ["eating"], "eimotv" => ["motive"], "aginsy" => ["saying"],
      "accept" => ["accept"], "acekrt" => ["racket"], "celoss" => ["closes"],
      "dhlosu" => ["should"], "alstvy" => ["vastly"], "besstu" => ["subset"],
      "aacltu" => ["actual"], "amntuu" => ["autumn"], "aaeppr" => ["appear"],
      "abeeln" => ["enable"], "ciprst" => ["script"], "begilo" => ["oblige"],
      "aglnos" => ["slogan"], "aehlss" => ["hassle"], "degglo" => ["logged"],
      "aghint" => ["hating"], "adeprs" => ["parsed", "spread"],
      "elpuzz" => ["puzzle"], "einnst" => ["tennis"], "dnossu" => ["sounds"],
      "addens" => ["sadden"], "erssuv" => ["versus"], "abdehs" => ["bashed"],
      "deilms" => ["smiled", "misled"], "aissst" => ["assist"],
      "aerstx" => ["extras"], "celmsu" => ["muscle"], "cdekmu" => ["mucked"],
      "ceikns" => ["sicken"], "delosw" => ["slowed"], "ghimty" => ["mighty"],
      "aertty" => ["treaty"], "abekrs" => ["brakes", "breaks"],
      "acdels" => ["scaled"], "beeerz" => ["breeze"], "beggir" => ["bigger"],
      "adepry" => ["prayed"], "adenrt" => ["ranted"], "ablsst" => ["blasts"],
      "horstw" => ["throws"], "acilms" => ["claims"], "acdeps" => ["spaced"],
      "cgimno" => ["coming"], "blmosy" => ["symbol"], "defill" => ["filled"],
      "aehlsv" => ["halves"], "ceefft" => ["effect"], "abbirt" => ["rabbit"],
      "eipqsu" => ["equips"], "moorst" => ["motors"], "eegrrt" => ["regret"],
      "dillwy" => ["wildly"], "ddeenv" => ["vended"], "diknrs" => ["drinks"],
      "deeivw" => ["viewed"], "ehpssu" => ["pushes"], "dnorsu" => ["rounds"],
      "deglow" => ["glowed"], "anstxy" => ["syntax"], "allosw" => ["allows"],
      "aenrtu" => ["nature"], "ehllss" => ["shells"], "eeflrx" => ["reflex"],
      "cilrsy" => ["lyrics"], "airstt" => ["artist"], "acepst" => ["aspect"],
      "ehmort" => ["mother"], "eorstu" => ["routes"], "effost" => ["offset"],
      "ceimrt" => ["metric"], "cciiln" => ["clinic"], "ddeefn" => ["defend"],
      "fhiins" => ["finish"], "abenst" => ["absent"], "floppy" => ["floppy"],
      "behlmu" => ["humble"], "efiprx" => ["prefix"], "deistw" => ["widest"],
      "iprtuy" => ["purity"], "deoprt" => ["ported"], "abekst" => ["basket"],
      "ijnoru" => ["junior"], "eginrs" => ["resign", "singer"],
      "airsst" => ["stairs"], "denorv" => ["vendor"], "aacelp" => ["palace"],
      "agimnr" => ["arming", "margin"], "cchhru" => ["church"],
      "aadhrz" => ["hazard"], "aerstv" => ["starve"], "ioprst" => ["tripos"],
      "eemorv" => ["remove"], "ginpty" => ["typing"], "elrsuy" => ["surely"],
      "deginr" => ["ringed"], "adehln" => ["handle"], "aelsuv" => ["values"],
      "abdesu" => ["abused"], "eegimr" => ["regime"], "deinru" => ["ruined"],
      "ainnot" => ["nation"], "deeems" => ["seemed"], "aenprt" => ["parent"],
      "enrtuu" => ["untrue"], "hirstt" => ["thirst"],
      "bdenru" => ["burden", "burned"], "ceilop" => ["police"],
      "eeklwy" => ["weekly"], "aghprs" => ["graphs"], "cdeloo" => ["cooled"],
      "aeflms" => ["flames"], "efiint" => ["finite"], "eglops" => ["gospel"],
      "ailsuv" => ["visual"], "adekpr" => ["parked"], "aehltw" => ["wealth"],
      "adeels" => ["sealed"], "adenpp" => ["append"], "bdehin" => ["behind"],
      "aderrw" => ["reward"], "eehors" => ["heroes"], "ggiinv" => ["giving"],
      "eirrsv" => ["rivers"], "ghhotu" => ["though"], "addeln" => ["landed"],
      "aaeilr" => ["aerial"], "gnorsw" => ["wrongs"], "ceeffo" => ["coffee"],
      "hilops" => ["polish"], "aelssv" => ["slaves"], "degisu" => ["guides"],
      "bdegtu" => ["budget"], "cehint" => ["ethnic"], "eeirrt" => ["retire"],
      "adeitw" => ["waited"], "ddeenp" => ["pended", "depend"],
      "eilnst" => ["silent", "listen"], "eeklnr" => ["kernel"],
      "adhlry" => ["hardly"], "ddelmu" => ["muddle"], "acekpt" => ["packet"],
      "ddeflo" => ["folded"], "eorrst" => ["resort"], "inpstu" => ["inputs"],
      "egnrtu" => ["urgent"], "adeluv" => ["valued"], "aelrtv" => ["travel"],
      "deopsu" => ["pseudo"], "chipsy" => ["physic"], "acehss" => ["chases"],
      "adllor" => ["dollar"], "eerssv" => ["verses", "serves"],
      "bmoott" => ["bottom"], "eflmsy" => ["myself"], "adpruw" => ["upward"],
      "elnntu" => ["tunnel"], "ceefir" => ["fierce"], "ceijnt" => ["inject"],
      "dnorsw" => ["drowns"], "belstu" => ["subtle"], "giimnx" => ["mixing"],
      "ccopuy" => ["occupy"], "eefrrs" => ["refers"], "cdmnoo" => ["condom"],
      "emrttu" => ["mutter"], "abelnu" => ["unable"], "eemort" => ["remote"],
      "adepss" => ["passed"], "afilry" => ["fairly"], "acehpr" => ["preach"],
      "deoppp" => ["popped"], "acelsu" => ["clause"], "adeisv" => ["advise"],
      "delosv" => ["solved"], "annosy" => ["annoys"], "dinoww" => ["window"],
      "dekloo" => ["looked"], "aelmrs" => ["realms"], "adimno" => ["domain"],
      "horsst" => ["shorts"], "adiknp" => ["kidnap"], "aefflw" => ["waffle"],
      "deiort" => ["editor"], "deenrs" => ["sender"], "ehnost" => ["honest"],
      "inoops" => ["poison"], "abdnrs" => ["brands"], "acerss" => ["scares"],
      "fhortu" => ["fourth"], "ainsty" => ["sanity"], "agiimn" => ["aiming"],
      "efilst" => ["itself"], "iinsst" => ["insist"], "aceors" => ["coarse"],
      "adiors" => ["radios"], "adeefr" => ["feared"],
      "aekmrr" => ["marker", "remark"], "aadepr" => ["parade"],
      "aginrv" => ["raving"], "deefnr" => ["fender"], "eefstw" => ["fewest"],
      "emssty" => ["system"], "gnorst" => ["strong"], "cersuv" => ["curves"],
      "abcfir" => ["fabric"], "epsstu" => ["upsets"], "beffru" => ["buffer"],
      "cimmot" => ["commit"], "adnsst" => ["stands"], "giinrt" => ["tiring"],
      "ademrs" => ["dreams"], "demmsu" => ["summed"], "aeoprs" => ["operas"],
      "eeorst" => ["stereo"], "ccorsu" => ["occurs"], "almort" => ["mortal"],
      "cdeeiv" => ["device"], "cddeeu" => ["deduce"], "eeelnv" => ["eleven"],
      "aeglmn" => ["mangle"], "aceprt" => ["carpet"], "chorsu" => ["chorus"],
      "eeginn" => ["engine"], "ceeehs" => ["cheese"], "eensuv" => ["venues"],
      "ceiosv" => ["voices"], "aelrwy" => ["lawyer"], "beprsu" => ["superb"],
      "ceilny" => ["nicely"], "elosss" => ["losses"], "abellt" => ["ballet"],
      "adeilm" => ["mailed"], "eeefrz" => ["freeze"], "bdekoo" => ["booked"],
      "lmosty" => ["mostly"], "bdegsu" => ["debugs"], "abcmot" => ["combat"],
      "deinrv" => ["driven"], "cddluy" => ["cuddly"], "dddeik" => ["kidded"],
      "aipszz" => ["pizzas"], "aefmrs" => ["frames"], "hoorrr" => ["horror"],
      "aeeirs" => ["easier"], "aeghrt" => ["gather"], "aelltw" => ["wallet"],
      "eginop" => ["pigeon"], "deeelt" => ["delete"], "deenst" => ["nested"],
      "celopu" => ["couple"], "chistw" => ["switch"], "acmprs" => ["cramps"],
      "eehrsy" => ["heresy"], "aegnor" => ["orange"], "aefirr" => ["fairer"],
      "eghnou" => ["enough"], "eirsst" => ["resist", "sister"],
      "aelpry" => ["player"], "aeeglu" => ["league"], "aehprs" => ["phrase"],
      "deptuy" => ["deputy"], "deeims" => ["demise"], "eeimpr" => ["empire"],
      "acdden" => ["danced"], "afmort" => ["format"], "cefors" => ["forces"],
      "aelntt" => ["talent"], "depttu" => ["putted"], "fgoort" => ["forgot"],
      "ersuvy" => ["survey"], "cikrty" => ["tricky"], "acelst" => ["castle"],
      "aelrry" => ["rarely"], "eirrtw" => ["writer"], "arsstt" => ["starts"],
      "acdekl" => ["lacked"], "adilns" => ["island"], "eiprxy" => ["expiry"],
      "cenovy" => ["convey"], "oprsst" => ["sports"], "agilny" => ["laying"],
      "bdelnu" => ["bundle"], "bcektu" => ["bucket"], "ehisst" => ["thesis"],
      "innoot" => ["notion"], "dgiinv" => ["diving"], "elorsv" => ["lovers"],
      "ceiops" => ["copies"], "finoty" => ["notify"], "acelps" => ["places"],
      "aeglrr" => ["larger"], "adeilt" => ["detail"], "giikln" => ["liking"],
      "ehinor" => ["heroin"], "beertt" => ["better"], "acddit" => ["addict"],
      "cehnos" => ["chosen"], "aeeqtu" => ["equate"], "denosu" => ["undoes"],
      "aaistw" => ["awaits"], "eimprs" => ["primes"], "aegnst" => ["agents"],
      "aaglxy" => ["galaxy"], "filoss" => ["fossil"], "ccehks" => ["checks"],
      "acmmos" => ["commas"], "ceersu" => ["rescue", "secure"],
      "aekpss" => ["speaks"], "aginrt" => ["rating"], "aeinns" => ["insane"],
      "aceess" => ["ceases"], "celnos" => ["clones"], "eijnru" => ["injure"],
      "goprsu" => ["groups"], "aerstw" => ["waters"], "acdees" => ["ceased"],
      "acdeht" => ["detach"], "cerssw" => ["screws"], "acinot" => ["action"],
      "acmuuv" => ["vacuum"], "abennr" => ["banner"], "aelrsy" => ["layers"],
      "abeehv" => ["behave"], "adestt" => ["tasted", "stated"],
      "defnru" => ["refund"], "defmor" => ["formed"], "eeltvw" => ["twelve"],
      "eknops" => ["spoken"], "blstuy" => ["subtly"], "aenptt" => ["patent"],
      "addely" => ["deadly"], "aceeps" => ["escape"], "ginnow" => ["owning"],
      "eisstx" => ["sexist", "exists"], "eflsuu" => ["useful"],
      "aeginr" => ["regain"], "ceorsu" => ["course", "source"],
      "eelovv" => ["evolve"], "giltuy" => ["guilty"],
      "acellr" => ["caller", "recall"], "abcehr" => ["breach"],
      "aehlsw" => ["whales"], "dehkoo" => ["hooked"], "deeotv" => ["devote"],
      "aginsv" => ["saving"], "abetuy" => ["beauty"], "dehntu" => ["hunted"],
      "hoopst" => ["photos"], "giimnn" => ["mining"], "cmmnoo" => ["common"],
      "iloqru" => ["liquor"], "acfgin" => ["facing"], "einstv" => ["invest"],
      "aeglns" => ["angels", "angles", "gleans"], "eoprtx" => ["export"],
      "deorst" => ["sorted", "stored"], "aceghr" => ["charge"],
      "aarrsy" => ["arrays"], "aefsty" => ["safety"], "deoqtu" => ["quoted"],
      "cenorr" => ["corner"], "hllowy" => ["wholly"], "cchost" => ["scotch"],
      "beirtt" => ["bitter"], "aegrtt" => ["target"],
      "acerst" => ["caters", "reacts", "traces"], "ddeiiv" => ["divide"],
      "eeirsv" => ["revise"], "hortwy" => ["worthy"], "aessst" => ["assets"],
      "ilppsu" => ["pupils"], "filnsu" => ["sinful"], "aeelrv" => ["reveal"],
      "efirvy" => ["verify"], "beehry" => ["hereby"], "abcels" => ["cables"],
      "eerstt" => ["street"], "ceilnp" => ["pencil"], "ceilqu" => ["clique"],
      "enttwy" => ["twenty"], "acghtu" => ["caught"], "ehinss" => ["shines"],
      "deenrr" => ["render"], "dehmot" => ["method"], "celors" => ["closer"],
      "eelssv" => ["vessel"], "ccdely" => ["cycled"], "eeflry" => ["freely"],
      "ceortv" => ["vector"], "adehsw" => ["washed"], "aceghn" => ["change"],
      "eimprt" => ["permit"], "efrtuu" => ["future"], "aelnrs" => ["learns"],
      "aegrsy" => ["greasy"], "ginrty" => ["trying"], "bemnru" => ["number"],
      "ginotv" => ["voting"], "acprss" => ["scraps"], "aceftu" => ["faucet"],
      "cdorsw" => ["crowds"], "eopssu" => ["opuses"], "clmopy" => ["comply"],
      "deeins" => ["denies"], "dnopsu" => ["pounds"], "acelot" => ["locate"],
      "ehrssu" => ["rushes"], "aeglpu" => ["plague"], "acdell" => ["called"],
      "cdeeno" => ["encode"], "acirst" => ["racist"], "beeefl" => ["feeble"],
      "eilrsv" => ["silver"], "glossy" => ["glossy"], "abbors" => ["absorb"],
      "ejnosy" => ["enjoys"], "eeirvw" => ["viewer", "review"],
      "ablmsu" => ["albums"], "aalswy" => ["always"], "bhlmuy" => ["humbly"],
      "aenopw" => ["weapon"], "aaclsu" => ["casual", "causal"],
      "aegnrs" => ["ranges"], "ceeipr" => ["recipe"], "amnotu" => ["amount"],
      "aeilnr" => ["linear"], "einoss" => ["noises"], "deopst" => ["posted"],
      "bdeers" => ["breeds"], "aceitv" => ["active"], "bbinor" => ["ribbon"],
      "eflntu" => ["fluent"], "eelpss" => ["sleeps"], "alopst" => ["postal"],
      "adeils" => ["ideals", "sailed", "ladies"], "hlloow" => ["hollow"],
      "ahknst" => ["thanks"], "einrtw" => ["winter"], "dehlor" => ["holder"],
      "eelrss" => ["lesser"], "eeirss" => ["series"], "acehrs" => ["search"],
      "bdeggo" => ["bogged"], "abehrt" => ["breath"], "gilnru" => ["ruling"],
      "ddeent" => ["tended"], "eelqsu" => ["sequel"], "adeenr" => ["earned"],
      "bdenoy" => ["beyond"], "dellor" => ["rolled"], "deflow" => ["flowed"],
      "eforst" => ["forest"], "deikrs" => ["risked"], "ghortw" => ["growth"],
      "eoqstu" => ["quotes"], "ailrtu" => ["ritual"], "agikmn" => ["making"],
      "dehisw" => ["wished"], "aeilsy" => ["easily"], "ciprss" => ["crisps"],
      "aoqstu" => ["quotas"], "aeiprr" => ["repair"], "ceiktt" => ["ticket"],
      "aeelsv" => ["leaves"], "dgiins" => ["siding"], "adeimr" => ["admire"],
      "cdlosu" => ["clouds"], "enoors" => ["sooner"], "aeflsy" => ["safely"],
      "eimmnu" => ["immune"], "ceessx" => ["excess"], "eglnty" => ["gently"],
      "deequu" => ["queued"], "eoopps" => ["oppose"], "dnrsuy" => ["sundry"],
      "eglosv" => ["gloves"], "achlnu" => ["launch"], "aeflln" => ["fallen"],
      "ainpst" => ["paints"], "ceimrs" => ["crimes"], "dehosw" => ["showed"],
      "dhiorr" => ["horrid"], "aeinrt" => ["retain"], "ceeips" => ["pieces"],
      "dddeew" => ["wedded"], "elpssu" => ["pulses"], "eirtuv" => ["virtue"],
      "adeerr" => ["reread", "reader"], "agjnor" => ["jargon"],
      "dfloos" => ["floods"], "ceehms" => ["scheme"], "ahmnsu" => ["humans"],
      "abcdel" => ["cabled"], "fgilny" => ["flying"], "aelnpt" => ["planet"],
      "eekltt" => ["kettle"], "deissu" => ["issued"], "ademns" => ["amends"],
      "eorsst" => ["stores"], "dekorw" => ["worked"], "adestw" => ["wasted"],
      "afinnt" => ["infant"], "eenstw" => ["newest"], "allpru" => ["plural"],
      "eorrrs" => ["errors"], "cginry" => ["crying"], "eegmrs" => ["merges"],
      "defitt" => ["fitted"], "bcilms" => ["climbs"], "cefhnr" => ["french"],
      "acejkt" => ["jacket"], "clmnou" => ["column"], "adenpt" => ["pedant"],
      "abhist" => ["habits"], "elortv" => ["revolt"], "aorrsw" => ["arrows"],
      "eillvy" => ["lively"], "elpruy" => ["purely"], "aegsst" => ["stages"],
      "dlorsw" => ["worlds"], "effrsu" => ["suffer"], "aehmnu" => ["humane"],
      "inoprs" => ["prison"], "deimnr" => ["remind"], "fghist" => ["fights"],
      "ilnstu" => ["insult"], "abeglr" => ["garble"], "acgirt" => ["tragic"],
      "adeptu" => ["update"], "cdeors" => ["scored"], "ellosy" => ["solely"],
      "deipsu" => ["upside"], "eimosv" => ["movies"], "accehn" => ["chance"],
      "loopry" => ["poorly"], "ckknos" => ["knocks"], "ccelsy" => ["cycles"],
      "accesu" => ["accuse"], "abgins" => ["basing"], "cdeinu" => ["induce"],
      "einrtv" => ["invert"], "aalmrs" => ["alarms"], "deiins" => ["inside"],
      "cenors" => ["censor"], "aelmps" => ["sample"], "ehnops" => ["phones"],
      "acimrs" => ["racism"], "eenrsv" => ["nerves"], "bcejot" => ["object"],
      "berttu" => ["butter"], "abinot" => ["obtain"], "ellpss" => ["spells"],
      "accent" => ["accent"], "adgnrs" => ["grands"], "fnorsw" => ["frowns"],
      "adeinr" => ["rained"], "deeirv" => ["derive"], "fgiiln" => ["filing"],
      "bceemo" => ["become"], "aenttx" => ["extant"], "closty" => ["costly"],
      "afinru" => ["unfair"], "cceilr" => ["circle"], "agnprs" => ["sprang"],
      "aeprss" => ["parses", "spares"], "aehrss" => ["shares"],
      "efllru" => ["fuller"], "eghhit" => ["eighth", "height"],
      "dginru" => ["during"], "diklny" => ["kindly"], "cdeorr" => ["record"],
      "elmopy" => ["employ"], "deefin" => ["define"], "deikln" => ["linked"],
      "ddeein" => ["denied", "indeed"], "issttw" => ["twists"],
      "efnorz" => ["frozen"], "ddeeem" => ["deemed"], "cortuy" => ["outcry"],
      "cmostu" => ["custom"], "einstu" => ["unites"], "giilnv" => ["living"],
      "eemrst" => ["meters"], "eeersv" => ["severe"], "eirstw" => ["writes"],
      "efgort" => ["forget"], "acelns" => ["cleans"], "anorrw" => ["narrow"],
      "belltu" => ["bullet"], "deilst" => ["listed"], "abdrsu" => ["absurd"],
      "abdors" => ["boards"], "achins" => ["chains"], "abelrr" => ["barrel"],
      "adeert" => ["teared"], "aeilns" => ["aliens"], "mnostu" => ["mounts"],
      "beglno" => ["belong"], "imoprt" => ["import"], "clmsuy" => ["clumsy"],
      "dehint" => ["hinted"], "ademno" => ["moaned"], "eimrsy" => ["misery"],
      "denoow" => ["wooden"], "abdeis" => ["biased"], "giinrw" => ["wiring"],
      "ddeinr" => ["ridden"], "definr" => ["friend"], "deeitx" => ["exited"],
      "ikllss" => ["skills"], "cdeino" => ["coined"], "aekmrt" => ["market"],
      "adenpx" => ["expand"], "efinst" => ["finest"], "iinosv" => ["vision"],
      "abdelm" => ["blamed"], "begglo" => ["boggle"], "adeeft" => ["defeat"],
      "cehlot" => ["clothe"], "ehossu" => ["houses"], "deegmr" => ["merged"],
      "ddegju" => ["judged"], "aceimn" => ["cinema"], "aadegn" => ["agenda"],
      "aelstt" => ["latest"], "beosss" => ["obsess"], "deorrs" => ["orders"],
      "aemsss" => ["masses"], "afmosu" => ["famous"], "acdehk" => ["hacked"],
      "bdnosu" => ["bounds"], "adnoru" => ["around"], "ceinpr" => ["prince"],
      "addehn" => ["handed"], "bginuy" => ["buying"], "eilmss" => ["smiles"],
      "ghirst" => ["rights"], "ehorss" => ["horses"], "cddeei" => ["decide"],
      "ciopst" => ["topics"], "abders" => ["beards"], "bdeorr" => ["border"],
      "deegry" => ["greedy"], "aehpss" => ["phases", "shapes"],
      "ddemoo" => ["doomed"], "ceesux" => ["excuse"], "acdert" => ["traced"],
      "acilos" => ["social"], "dehpst" => ["depths"], "gimnov" => ["moving"],
      "ceirsu" => ["cruise"], "abimpt" => ["bitmap"], "eefilr" => ["relief"],
      "aflost" => ["floats"], "access" => ["access"], "eiprsz" => ["prizes"],
      "afltuy" => ["faulty"], "acdekt" => ["tacked"], "fooprs" => ["proofs"],
      "abgllo" => ["global"], "ceenss" => ["scenes"], "aesssy" => ["essays"],
      "abklns" => ["blanks"], "cehins" => ["inches"], "cdeklo" => ["locked"],
      "accers" => ["scarce"], "eemptx" => ["exempt"], "deffno" => ["offend"],
      "aesstw" => ["sweats", "wastes"], "abeent" => ["beaten"],
      "cdefor" => ["forced"], "eknost" => ["tokens"], "giinsz" => ["sizing"],
      "cdeipr" => ["priced"], "deelpy" => ["deeply"], "eenqsu" => ["queens"],
      "ekorst" => ["stroke"], "delmou" => ["module"], "ddensu" => ["sudden"],
      "aabdor" => ["abroad"], "achlor" => ["choral"], "inopst" => ["points"],
      "ceelst" => ["elects", "select"], "aerstt" => ["treats"],
      "cdeent" => ["decent"], "acdekp" => ["packed"], "aeirst" => ["satire"],
      "acdehs" => ["chased"], "enrsuu" => ["unsure"], "eglnor" => ["longer"],
      "acfort" => ["factor"], "deemry" => ["remedy"], "diilqu" => ["liquid"],
      "deippr" => ["ripped"], "eginsu" => ["genius"], "bdostu" => ["doubts"],
      "addimy" => ["midday"], "aghinv" => ["having"], "amoott" => ["tomato"],
      "erssst" => ["stress"], "acehst" => ["cheats"],
      "deeirs" => ["reside", "desire"], "adehlt" => ["halted"],
      "defils" => ["fields"], "deestt" => ["tested"], "eprsuu" => ["pursue"],
      "aeknsy" => ["sneaky"], "aelmnt" => ["mental"], "eilmps" => ["simple"],
      "aersst" => ["assert", "stares"], "deepss" => ["speeds"],
      "ckosst" => ["stocks"], "aepprs" => ["papers"],
      "aesstt" => ["tastes", "states"], "deimnp" => ["impend"],
      "adeiln" => ["nailed"], "aorsst" => ["assort"], "eoprsv" => ["proves"],
      "ampssw" => ["swamps"], "ddeemn" => ["mended"], "aeimnr" => ["remain"],
      "adortw" => ["toward"], "clnooy" => ["colony"], "defilt" => ["lifted"],
      "ghostu" => ["sought"], "cchnru" => ["crunch"], "dgiinn" => ["dining"],
      "aessss" => ["assess"], "giinor" => ["origin"], "aeerrs" => ["eraser"],
      "adelsy" => ["delays"], "acllor" => ["collar"], "adgrsu" => ["guards"],
      "eenprt" => ["repent"], "aennoy" => ["anyone"], "cdeett" => ["detect"],
      "ailmny" => ["mainly"], "addehs" => ["dashed"], "aeegnt" => ["negate"],
      "cdeeru" => ["reduce"], "ginprs" => ["spring"], "ddeeen" => ["needed"],
      "aelryy" => ["yearly"], "aeemnr" => ["rename"], "demost" => ["modest"],
      "aehkss" => ["shakes"], "ccnoru" => ["concur"], "ceenrt" => ["recent"],
      "fioprt" => ["profit"], "eilstt" => ["titles"], "egsstu" => ["guests"],
      "ellnoy" => ["lonely"], "adehrt" => ["hatred", "thread"],
      "eehirt" => ["either"], "ellowy" => ["yellow"], "eeinrt" => ["entire"],
      "ddeinw" => ["winded"], "adders" => ["dreads"], "cdeeho" => ["echoed"],
      "dehors" => ["hordes"], "aaelpp" => ["appeal"], "eelnss" => ["lenses"],
      "ahortt" => ["throat"], "ijnost" => ["joints"], "achirs" => ["chairs"],
      "eeekpr" => ["keeper"], "ceehnw" => ["whence"], "deemss" => ["messed"],
      "iiprst" => ["spirit"], "eilott" => ["toilet"], "aellty" => ["lately"],
      "eehlmt" => ["helmet"], "iprsst" => ["strips"], "hoosst" => ["shoots"],
      "beintt" => ["bitten"], "cginru" => ["curing"],
      "adesty" => ["steady", "stayed"], "eeprtx" => ["expert"],
      "eiklly" => ["likely"], "beemmr" => ["member"], "gilnov" => ["loving"],
      "aghlsu" => ["laughs"], "efhiss" => ["fishes"], "almtuu" => ["mutual"],
      "deerst" => ["desert", "rested"], "deimmu" => ["medium"],
      "ekmors" => ["smoker"], "aadfir" => ["afraid"], "deoprv" => ["proved"],
      "einrst" => ["insert"], "eilltt" => ["little"], "fhisst" => ["shifts"],
      "gnprsu" => ["sprung"], "ceorss" => ["scores"], "bghotu" => ["bought"],
      "acfils" => ["fiscal"], "aeills" => ["allies"], "morsst" => ["storms"],
      "lppsuy" => ["supply"], "cchksu" => ["chucks"], "eeilrs" => ["relies"],
      "inprst" => ["prints"], "bginor" => ["boring"], "egikny" => ["keying"],
      "hirtty" => ["thirty"], "abderr" => ["barred"], "aeknss" => ["sneaks"],
      "ddeott" => ["dotted"], "deintu" => ["united"], "opttuu" => ["output"],
      "aehrst" => ["hearts"], "emmsuu" => ["museum"], "ceimno" => ["income"],
      "aginss" => ["assign"], "deenop" => ["opened"], "gginru" => ["urging"],
      "abeilv" => ["viable"], "ceiprs" => ["prices"], "abciss" => ["basics"],
      "agnors" => ["organs"], "lruuxy" => ["luxury"], "eemsss" => ["messes"],
      "ailort" => ["tailor"], "acistt" => ["static"], "bcenou" => ["bounce"],
      "aanwyy" => ["anyway"], "fgiinr" => ["firing"], "denrty" => ["trendy"],
      "acepss" => ["spaces"], "eelopp" => ["people"], "ghnruy" => ["hungry"],
      "deillw" => ["willed"], "eimssu" => ["misuse"], "hiintw" => ["within"],
      "bcklos" => ["blocks"], "almnor" => ["normal"], "deersv" => ["served"],
      "deflor" => ["folder"], "aacktt" => ["attack"], "aeirsv" => ["varies"],
      "eikrst" => ["strike"], "boorrw" => ["borrow"], "eelmry" => ["merely"],
      "cekrsw" => ["wrecks"], "eorrrt" => ["terror"],
      "adehps" => ["phased", "shaped"], "eenttx" => ["extent"],
      "ceoppr" => ["copper"], "ginnot" => ["noting"], "bimstu" => ["submit"],
      "eenstv" => ["events"], "fhilty" => ["filthy"],
      "aelrtt" => ["rattle", "latter"], "cdeost" => ["costed"],
      "aailmn" => ["animal"], "abmotw" => ["wombat"], "eeqsuu" => ["queues"],
      "eefinr" => ["refine"], "giinrs" => ["rising"],
      "eoprrt" => ["porter", "report"], "agginp" => ["paging"],
      "adeinv" => ["invade"], "eeegmr" => ["emerge"], "adglly" => ["gladly"],
      "deeisv" => ["devise"], "efginr" => ["fringe", "finger"],
      "abeltt" => ["battle"], "eeglnt" => ["gentle"], "eefrsu" => ["refuse"],
      "acdeks" => ["sacked"], "eoprty" => ["poetry"],
      "acders" => ["sacred", "scared"], "adeegr" => ["geared", "agreed"],
      "aalnnu" => ["annual"], "rssttu" => ["trusts"], "cikrst" => ["tricks"],
      "addgin" => ["adding"], "eghitw" => ["weight"], "aensuy" => ["uneasy"],
      "floors" => ["floors"], "imnoot" => ["motion"], "egglot" => ["toggle"],
      "eelnvy" => ["evenly"], "addelr" => ["ladder"], "agirtu" => ["guitar"],
      "deiopr" => ["period"], "aooptt" => ["potato"],
      "cdeirt" => ["credit", "direct"], "adfrst" => ["drafts"],
      "aehrtt" => ["threat"], "elnpty" => ["plenty"], "belott" => ["bottle"],
      "deoprw" => ["powder"], "eikllr" => ["killer"], "adimst" => ["admits"],
      "elssty" => ["styles"], "bdeeoy" => ["obeyed"], "ddegiu" => ["guided"],
      "ahqssu" => ["squash"], "eprtty" => ["pretty"], "loppsy" => ["sloppy"],
      "dghiin" => ["hiding"], "aeqrsu" => ["square"], "deenrt" => ["tender"],
      "emnors" => ["sermon"], "aacilr" => ["racial"],
      "ccimos" => ["comics", "cosmic"], "cdeehw" => ["chewed"],
      "eehmst" => ["themes"], "einsuw" => ["unwise"], "aeegll" => ["allege"],
      "cekopt" => ["pocket"], "eellsv" => ["levels"], "eimsss" => ["misses"],
      "degist" => ["digest"], "ahnowy" => ["anyhow"], "aadrsw" => ["awards"],
      "ceinot" => ["notice"], "abdeet" => ["debate"], "adefil" => ["failed"],
      "cekort" => ["rocket"], "bcikrs" => ["bricks"], "ghisst" => ["sights"],
      "denorw" => ["wonder"], "ilmpsy" => ["simply"], "adentv" => ["advent"],
      "eennsu" => ["unseen"], "elnost" => ["stolen"], "cehior" => ["heroic"],
      "bghirt" => ["bright"], "fffluy" => ["fluffy"], "eorstw" => ["towers"],
      "adepsu" => ["paused"], "aegims" => ["images"], "agiknt" => ["taking"],
      "cdoort" => ["doctor"], "ghinst" => ["nights", "things"],
      "einort" => ["orient"], "addelo" => ["loaded"], "ginopt" => ["opting"],
      "acenst" => ["stance"], "abesst" => ["beasts"], "dlnuuy" => ["unduly"],
      "aachns" => ["ashcan"], "elorsw" => ["lowers", "slower"],
      "adeehr" => ["adhere", "header"], "adegru" => ["argued"],
      "cnotuy" => ["county"], "adnopr" => ["pardon"], "adilms" => ["dismal"],
      "deistu" => ["duties", "suited"], "ademsu" => ["amused"],
      "dgnoru" => ["ground"], "aceerr" => ["career"], "aeeprt" => ["repeat"],
      "ghhily" => ["highly"], "giinrv" => ["virgin"], "chkoss" => ["shocks"],
      "deenot" => ["denote"], "eginor" => ["ignore", "region"],
      "bdeems" => ["embeds"], "adentw" => ["wanted"], "elnosv" => ["novels"],
      "ceelrv" => ["clever"], "einquu" => ["unique"], "defloo" => ["fooled"],
      "agnrst" => ["grants"], "beefil" => ["belief"], "ceiist" => ["cities"],
      "aademz" => ["amazed"], "hnopty" => ["python"], "rsttuy" => ["trusty"],
      "deinnr" => ["dinner"], "imorrr" => ["mirror"], "aelnry" => ["nearly"],
      "cehkst" => ["sketch"], "adehrr" => ["harder"], "acorrt" => ["carrot"],
      "ilpsst" => ["splits"], "hosstu" => ["shouts"], "bdeiru" => ["buried"],
      "cdeiop" => ["copied"], "filmry" => ["firmly"], "aadegm" => ["damage"],
      "effort" => ["effort"], "aacetv" => ["caveat"], "adeklw" => ["walked"],
      "hmoost" => ["smooth"], "enoprs" => ["person"], "adddep" => ["padded"],
      "bhiops" => ["bishop"], "ddiors" => ["sordid"], "ellovy" => ["lovely"],
      "aborst" => ["aborts"], "eloprt" => ["petrol"], "aeegrs" => ["agrees"],
      "abcnor" => ["carbon"], "cehirr" => ["richer"], "eflorw" => ["flower"],
      "cdeeft" => ["defect"], "delmos" => ["seldom", "models"],
      "ceehrs" => ["cheers"], "almors" => ["morals"], "ceehps" => ["speech"],
      "aenptu" => ["peanut"], "giimnt" => ["timing"], "cnoott" => ["cotton"],
      "acddee" => ["decade"], "egnorv" => ["govern"], "egnoxy" => ["oxygen"],
      "abbeis" => ["babies"], "bersuy" => ["buyers"], "chloos" => ["school"],
      "eintty" => ["entity"], "aadpst" => ["adapts"], "celost" => ["closet"],
      "adgnor" => ["dragon"], "aehnst" => ["hasten"], "agiknw" => ["waking"],
      "dintuy" => ["untidy"], "aiorst" => ["ratios"], "ceorsv" => ["covers"],
      "ceilnt" => ["client"], "dfimoy" => ["modify"], "adekmr" => ["marked"],
      "eersst" => ["resets", "steers"], "elossv" => ["solves"],
      "chknsu" => ["chunks"], "aaffir" => ["affair"], "adinrs" => ["drains"],
      "cdenos" => ["second"], "aelnps" => ["panels", "planes"],
      "ceikoo" => ["cookie"], "bginrs" => ["brings"], "deginn" => ["ending"],
      "elrstu" => ["result"], "cinrsu" => ["incurs"], "agikns" => ["asking"],
      "acegln" => ["glance"], "eenrst" => ["resent", "enters"],
      "eoprst" => ["poster"], "ceeptx" => ["except", "expect"],
      "ehorsw" => ["shower"], "dellpu" => ["pulled"],
      "abelst" => ["stable", "tables"], "boorst" => ["robots"],
      "ciirss" => ["crisis"], "aefsst" => ["safest"], "bdelou" => ["double"],
      "aehmmr" => ["hammer"], "addemn" => ["damned", "demand"],
      "adgiin" => ["aiding"], "abelsu" => ["usable"], "bdfior" => ["forbid"],
      "aerssu" => ["assure"], "cklnou" => ["unlock"], "adelst" => ["lasted"],
      "adhosw" => ["shadow"], "acdelp" => ["placed"], "egnotu" => ["tongue"],
      "fgiinn" => ["fining"], "dehnop" => ["phoned"], "defhis" => ["fished"],
      "eisstw" => ["wisest"], "acmpsu" => ["campus"], "aeginu" => ["guinea"],
      "enrssu" => ["nurses"], "alotuy" => ["layout"], "ffsstu" => ["stuffs"],
      "aderry" => ["dreary"], "eiprst" => ["priest"], "elorvy" => ["overly"],
      "cnostu" => ["counts"], "bdegir" => ["bridge"], "addeeh" => ["headed"],
      "abdels" => ["blades"], "ddeorw" => ["worded"], "cdemoy" => ["comedy"],
      "aalrsy" => ["salary"], "achmrs" => ["charms"], "aehhlt" => ["health"],
      "assttu" => ["status"], "adopry" => ["parody"], "enoprv" => ["proven"],
      "bdlooy" => ["bloody"], "eiknov" => ["invoke"], "aaegmn" => ["manage"],
      "hilstw" => ["whilst"], "acorst" => ["actors"], "ginrst" => ["string"],
      "ceiopt" => ["poetic"], "effors" => ["offers"], "eilprt" => ["triple"],
      "behort" => ["bother"], "aerssw" => ["swears"], "abeill" => ["liable"],
      "iilmst" => ["limits"], "acintt" => ["intact"], "cehist" => ["ethics"],
      "aehssw" => ["washes"], "ciksst" => ["sticks"], "aellry" => ["really"],
      "aeerss" => ["erases"], "efmorr" => ["reform", "former"],
      "aefimn" => ["famine"], "efllow" => ["fellow"], "aclrsw" => ["crawls"],
      "cirstt" => ["strict"], "deirtv" => ["divert"], "abllot" => ["ballot"],
      "deeilr" => ["relied"], "adehst" => ["deaths"], "adeirs" => ["raised"],
      "acdens" => ["ascend", "dances"], "adlstu" => ["adults"],
      "cinosu" => ["cousin"], "beknor" => ["broken"], "aachtt" => ["attach"],
      "ddefnu" => ["funded"], "acksst" => ["stacks"], "elnopy" => ["openly"],
      "beorsw" => ["browse"], "eosttu" => ["outset"], "aefnsu" => ["unsafe"],
      "deijno" => ["joined"], "ddefil" => ["fiddle"], "ciksty" => ["sticky"],
      "abelry" => ["barely"], "aeinrs" => ["arisen"], "aiirtv" => ["trivia"],
      "empstt" => ["tempts"], "aefrst" => ["faster"], "eimntu" => ["minute"],
      "acginr" => ["caring", "racing"], "ccklos" => ["clocks"],
      "aeelrt" => ["relate"], "abpssy" => ["bypass"], "adginr" => ["daring"],
      "aoprrt" => ["parrot"], "ginntu" => ["tuning"], "deimss" => ["missed"],
      "enortt" => ["rotten"], "eiintv" => ["invite"], "fginry" => ["frying"],
      "aelsvv" => ["valves"], "aelrss" => ["lasers"], "deilsy" => ["yields"],
      "aehllt" => ["lethal"], "abeerw" => ["beware"], "eehitv" => ["thieve"],
      "deloru" => ["louder"], "eepssw" => ["sweeps"], "abesss" => ["basses"],
      "dehpsu" => ["pushed"], "emmrsu" => ["summer"], "eefrtu" => ["refute"],
      "abchnr" => ["branch"], "deinnt" => ["indent", "intend"],
      "dimosw" => ["wisdom"], "bgiint" => ["biting"], "aaintt" => ["attain"],
      "adelpy" => ["played"], "fghilt" => ["flight"], "addeel" => ["leaded"],
      "ccehio" => ["choice"], "ehistw" => ["whites"],
      "ckrstu" => ["struck", "trucks"], "elnssu" => ["unless"],
      "deiinv" => ["divine"], "corstu" => ["courts"], "deklru" => ["lurked"],
      "demnor" => ["modern"], "adentt" => ["attend"], "aegrsu" => ["argues"],
      "denosz" => ["dozens"], "eehlsw" => ["wheels"], "eimrst" => ["merits"],
      "deeepr" => ["deeper"], "bbbelu" => ["bubble"], "deikll" => ["killed"],
      "aellvy" => ["valley"], "acelss" => ["scales"], "iisstv" => ["visits"],
      "eenrsw" => ["renews"], "abells" => ["labels"], "aimosx" => ["axioms"],
      "innosu" => ["unions"], "elrrsu" => ["rulers"], "ddeiov" => ["devoid"],
      "adehnr" => ["harden"], "aiprty" => ["parity"], "dehins" => ["shined"],
      "deeegr" => ["degree"], "aefkrs" => ["freaks"], "eensss" => ["senses"],
      "adelor" => ["loader"], "aemssu" => ["amuses", "assume"],
      "adeeln" => ["leaned"], "emmnot" => ["moment"], "acehkr" => ["hacker"],
      "emmory" => ["memory"], "eeiprx" => ["expire"], "ehissw" => ["wishes"],
      "ginops" => ["posing"], "ehirst" => ["theirs"], "eemprt" => ["temper"],
      "adeeht" => ["heated"], "ceerst" => ["secret"], "abelrv" => ["verbal"],
      "ceinst" => ["insect", "nicest"], "acessu" => ["causes"],
      "adegin" => ["gained"], "acefft" => ["affect"], "egrttu" => ["gutter"],
      "abdekr" => ["barked"], "adgint" => ["dating"], "bberru" => ["rubber"],
      "acimot" => ["atomic"], "eghlnt" => ["length"], "adeghn" => ["hanged"],
      "deortu" => ["routed"], "absuwy" => ["subway"], "hoopsw" => ["whoops"],
      "abcdek" => ["backed"], "efilrt" => ["filter", "trifle"],
      "aghttu" => ["taught"], "ffisux" => ["suffix"], "eegnry" => ["energy"],
      "admnor" => ["random"], "cdeikw" => ["wicked"], "cddeeo" => ["decode"],
      "aelqsu" => ["equals"], "abeffl" => ["baffle"], "eelstt" => ["settle"],
      "bdeios" => ["bodies"], "ghilst" => ["lights", "slight"],
      "acnnot" => ["cannot"], "aeirss" => ["arises", "raises"],
      "delmoy" => ["melody"], "elnoss" => ["lesson"], "ahortu" => ["author"],
      "adehrs" => ["shared"], "aenors" => ["reason"], "ailrsv" => ["rivals"],
      "aemrtt" => ["matter"], "hiknst" => ["thinks"], "celmop" => ["compel"],
      "gijkno" => ["joking"], "hhmrty" => ["rhythm"], "aepsss" => ["passes"],
      "ceoprs" => ["corpse"], "aehrrt" => ["rather"], "ddeiit" => ["tidied"],
      "dgiist" => ["digits"], "eelmpt" => ["temple"],
      "adehss" => ["dashes", "shades"], "belmmu" => ["mumble"],
      "hrsttu" => ["thrust", "truths"], "aflmor" => ["formal"],
      "einnrw" => ["winner"], "aaknor" => ["anorak"],
      "ainrst" => ["strain", "trains"], "acdeiv" => ["advice"],
      "aalmnu" => ["manual"], "accenr" => ["cancer"], "adginw" => ["wading"],
      "eilrtt" => ["litter"], "eghhir" => ["higher"], "abeiss" => ["biases"],
      "enorsw" => ["owners"], "eerrsv" => ["server"], "aceltt" => ["cattle"],
      "deegln" => ["legend"], "aceklt" => ["tackle"], "egilns" => ["single"],
      "ehorst" => ["others"], "ekmoss" => ["smokes"], "afilns" => ["finals"],
      "deeenv" => ["evened"], "acllos" => ["locals"], "aacemr" => ["camera"],
      "dejmpu" => ["jumped"], "almost" => ["almost"], "aemnnr" => ["manner"],
      "elmouv" => ["volume"], "aenoss" => ["season"], "aacder" => ["arcade"],
      "aeoptt" => ["teapot"], "elppru" => ["purple"], "aelrst" => ["alters"],
      "enosst" => ["stones"], "aenrsw" => ["answer"], "eilstv" => ["livest"],
      "hmnost" => ["months"], "cekost" => ["socket"], "dehosu" => ["housed"],
      "einntt" => ["intent"], "denpss" => ["spends"], "dgiinr" => ["riding"],
      "delost" => ["oldest"], "cllors" => ["scroll"], "mopprt" => ["prompt"],
      "dekmos" => ["smoked"], "ampsst" => ["stamps"], "denrst" => ["trends"],
      "aeilrt" => ["retail"], "einors" => ["senior"], "aelnru" => ["neural"],
      "eegins" => ["seeing"], "adenru" => ["unread"], "aelnty" => ["neatly"],
      "ceinov" => ["novice"], "aacenr" => ["arcane"], "abenry" => ["nearby"],
      "cginop" => ["coping"], "acimpt" => ["impact"], "ddempu" => ["dumped"],
      "ceeitx" => ["excite"], "aaeggr" => ["garage"], "aelsst" => ["steals"],
      "brsstu" => ["bursts"], "ademrw" => ["warmed"], "aeprry" => ["prayer"],
      "deegnr" => ["gender"], "aaabnn" => ["banana"], "deilwy" => ["widely"],
      "ilopss" => ["spoils"], "alnpst" => ["plants"], "giilnn" => ["lining"],
      "aemrst" => ["master", "stream"], "beefor" => ["before"],
      "ademnn" => ["manned"], "giopss" => ["gossip"], "adopst" => ["adopts"],
      "eimops" => ["impose"], "adegrr" => ["regard"], "deentx" => ["extend"],
      "aeortt" => ["rotate"], "finosu" => ["fusion"], "aeelsw" => ["weasel"],
      "knrstu" => ["trunks"], "dillmy" => ["mildly"], "acehlp" => ["chapel"],
      "dipstu" => ["stupid"], "dginry" => ["drying"], "flloow" => ["follow"],
      "achrst" => ["charts"], "densuu" => ["unused"], "adjstu" => ["adjust"],
      "aekmrs" => ["makers"], "bnottu" => ["button"],
      "aderst" => ["stared", "trades"], "cdeikk" => ["kicked"],
      "cdeikp" => ["picked"], "adeklt" => ["talked"], "cehoos" => ["choose"],
      "aepssu" => ["pauses"], "beggru" => ["bugger"], "bdeeis" => ["beside"],
      "dginrs" => ["grinds"], "deopru" => ["poured"], "aginpy" => ["paying"],
      "adenrw" => ["wander", "warned"], "ddeimn" => ["minded"],
      "eoprsw" => ["powers"], "aeilnt" => ["entail"], "ghinop" => ["hoping"],
      "beirst" => ["tribes"], "diostu" => ["studio"], "acceln" => ["cancel"],
      "ddeeit" => ["edited"], "defilm" => ["filmed"], "fghotu" => ["fought"],
      "cciirt" => ["critic"], "aiimpr" => ["impair"], "accdor" => ["accord"],
      "ceehos" => ["echoes"], "eelrtt" => ["letter"], "cimsty" => ["mystic"],
      "abinrs" => ["brains"], "eenrsu" => ["ensure"], "eehprs" => ["sphere"],
      "eemrsu" => ["resume"], "aeehnv" => ["heaven"], "ceenrs" => ["screen"],
      "degins" => ["design", "signed"], "emorst" => ["metros"],
      "diiost" => ["idiots"], "aerrst" => ["arrest", "rarest"],
      "aekrst" => ["takers"], "acemrs" => ["scream"], "deirsv" => ["drives"],
      "afilmy" => ["family"], "acelrs" => ["clears"],
      "eehsst" => ["sheets", "theses"], "cdelos" => ["closed"],
      "aemrtu" => ["mature"], "aflstu" => ["faults"], "acegny" => ["agency"],
      "aahpty" => ["apathy"], "deehlp" => ["helped"], "eooprr" => ["poorer"],
      "aimrtx" => ["matrix"], "hinpsu" => ["punish"], "efiltu" => ["futile"],
      "cdeeex" => ["exceed"], "deilss" => ["slides"], "adejmm" => ["jammed"],
      "addert" => ["traded"]}
  end
end
