defmodule Jumble.ScowlDict.Size80.Length3 do
  def get(string_id) do
    %{"bez" => ["bez"], "loy" => ["loy"], "abo" => ["abo", "oba", "boa"],
      "aek" => ["ake", "kae", "kea"], "imz" => ["miz"], "hot" => ["tho", "hot"],
      "aem" => ["mae"], "oow" => ["woo"], "ctu" => ["cut"],
      "afr" => ["arf", "fra", "far"], "mux" => ["mux"], "zzz" => ["zzz"],
      "eoy" => ["oye"], "dgu" => ["dug"], "abd" => ["dab", "bad"], "lor" => ["lor"],
      "hip" => ["phi", "hip"], "elu" => ["ule", "leu"], "swy" => ["swy"],
      "inu" => ["uni"], "bgi" => ["gib", "big"], "osy" => ["oys", "yos", "soy"],
      "pru" => ["pur", "urp"], "imx" => ["mix"], "abf" => ["fab"], "ikl" => ["ilk"],
      "nru" => ["nur", "urn", "run"], "gmy" => ["gym"], "bde" => ["deb", "bed"],
      "dsu" => ["uds", "sud"], "gox" => ["gox"], "lot" => ["lot"], "agj" => ["jag"],
      "muy" => ["yum"], "cly" => ["cly"], "ehu" => ["hue"], "elp" => ["lep"],
      "ehi" => ["hie"], "egu" => ["gue"], "hnt" => ["nth"], "eov" => ["voe"],
      "ajy" => ["jay"], "aey" => ["yea", "aye"], "eil" => ["lei", "lie"],
      "deu" => ["due"], "bil" => ["lib"], "ooz" => ["zoo"],
      "hop" => ["pho", "poh", "hop"], "nno" => ["non"], "ggi" => ["igg", "gig"],
      "acy" => ["cay"], "npw" => ["pwn"], "ahp" => ["hap", "pah"], "ivy" => ["ivy"],
      "aes" => ["eas", "sea"], "ekw" => ["ewk"], "mmo" => ["mom"], "fnu" => ["fun"],
      "ewy" => ["wey", "wye", "yew"], "afn" => ["fan"], "ott" => ["tot"],
      "doy" => ["yod"], "cgo" => ["cog"], "abl" => ["alb", "lab"],
      "aft" => ["aft", "fat"], "dop" => ["dop", "pod"], "bdo" => ["bod", "dob"],
      "imn" => ["nim"], "imm" => ["mim"], "cgi" => ["cig"], "cox" => ["cox"],
      "fno" => ["fon"], "eej" => ["jee"], "chi" => ["ich", "hic", "chi"],
      "flu" => ["flu"], "ops" => ["ops", "sop"], "epy" => ["pye", "yep"],
      "tux" => ["tux"], "eit" => ["tie"], "ehr" => ["reh", "her"], "efk" => ["kef"],
      "fil" => ["fil"], "now" => ["now", "own", "won"], "app" => ["pap"],
      "hoy" => ["hoy"], "oos" => ["oos"], "acm" => ["mac", "cam"], "ovw" => ["vow"],
      "bfi" => ["fib"], "amy" => ["mya", "yam", "may"], "atx" => ["tax"],
      "ept" => ["pet"], "psy" => ["spy"], "amt" => ["tam", "mat"], "fik" => ["kif"],
      "aps" => ["asp", "pas", "sap", "spa"], "itt" => ["tit"], "aly" => ["lay"],
      "bow" => ["bow"], "aoz" => ["azo", "zoa"], "ddo" => ["dod", "odd"],
      "akr" => ["ark"], "alx" => ["lax"], "ell" => ["ell"], "euy" => ["uey"],
      "foy" => ["foy"], "dkl" => ["dkl"], "diy" => ["yid"], "esz" => ["sez"],
      "ors" => ["ors"], "eny" => ["nye", "yen"], "dim" => ["mid", "dim"],
      "beg" => ["beg"], "cno" => ["con"], "ajw" => ["jaw"], "opp" => ["pop"],
      "eeg" => ["gee"], "kop" => ["kop"], "aot" => ["tao", "oat"], "est" => ["set"],
      "aet" => ["eta", "ate", "eat", "tea"], "auv" => ["uva", "vau"],
      "deh" => ["edh"], "imo" => ["moi"], "mru" => ["rum"], "orw" => ["row"],
      "dos" => ["dso", "ods", "dos", "sod"], "inn" => ["inn"],
      "etw" => ["tew", "wet"], "aqu" => ["qua"], "ill" => ["ill"],
      "dei" => ["ide", "die"], "oty" => ["toy"], "kno" => ["kon"], "bio" => ["obi"],
      "fop" => ["fop"], "hmm" => ["hmm"], "lmo" => ["olm"], "hor" => ["rho"],
      "den" => ["ned", "den", "end"], "cit" => ["tic"], "aim" => ["ami", "aim"],
      "ekz" => ["zek"], "itz" => ["zit"], "uzz" => ["zuz"], "iko" => ["koi", "oik"],
      "ilo" => ["oil"], "gim" => ["mig"], "fgo" => ["fog"], "emn" => ["men"],
      "rsu" => ["urs"], "bbu" => ["bub"], "nsu" => ["uns", "nus", "sun"],
      "ilp" => ["lip"], "hss" => ["ssh"], "duw" => ["wud"], "rty" => ["try"],
      "opu" => ["upo"], "coo" => ["coo"], "oru" => ["our"], "fot" => ["oft"],
      "ipt" => ["pit", "tip"], "los" => ["los", "sol"], "nov" => ["von"],
      "emu" => ["meu", "emu"], "ben" => ["ben", "neb"], "egv" => ["veg"],
      "enp" => ["nep", "pen"], "alw" => ["awl", "law"], "bir" => ["rib"],
      "cei" => ["ice"], "ent" => ["net", "ten"], "ajk" => ["jak"], "eez" => ["zee"],
      "mmu" => ["umm", "mum"], "eey" => ["eye"], "ekx" => ["kex"],
      "add" => ["dad", "add"], "pry" => ["pry"], "ady" => ["day"],
      "acp" => ["pac", "cap"], "ems" => ["ems", "mes"], "def" => ["fed"],
      "suy" => ["yus"], "blo" => ["lob"], "ary" => ["ary", "yar", "rya", "ray"],
      "isu" => ["sui"], "mow" => ["mow"], "bet" => ["bet"], "dit" => ["tid", "dit"],
      "ads" => ["das", "ads", "sad"], "ego" => ["geo", "ego"],
      "eht" => ["eth", "the"], "een" => ["een", "ene"], "abp" => ["bap"],
      "esu" => ["sue", "use"], "eop" => ["ope"], "bfo" => ["fob"], "afk" => ["kaf"],
      "ahy" => ["yah", "hay"], "ast" => ["tas", "sat"], "ceh" => ["che"],
      "lmy" => ["lym"], "abc" => ["cab"], "eru" => ["ure", "rue"], "gno" => ["nog"],
      "guy" => ["yug", "guy"], "efo" => ["foe"], "hox" => ["hox"], "anr" => ["ran"],
      "ipr" => ["rip"], "ekp" => ["kep"], "adw" => ["daw", "wad"], "iwz" => ["wiz"],
      "agr" => ["gar", "rag"], "cho" => ["hoc", "och"], "abb" => ["abb"],
      "cik" => ["ick"], "dir" => ["rid"], "dpu" => ["pud"], "atu" => ["uta", "tau"],
      "efi" => ["fie"], "aor" => ["ora", "oar"], "egm" => ["meg", "gem"],
      "anv" => ["van"], "dis" => ["ids", "dis"], "del" => ["eld", "led"],
      "iqs" => ["qis"], "guv" => ["vug", "guv"], "ens" => ["ens"], "htu" => ["hut"],
      "bes" => ["bes"], "acl" => ["lac"], "ehp" => ["peh", "hep"],
      "gju" => ["gju", "jug"], "aer" => ["ear", "era", "are"], "bjo" => ["job"],
      "ilt" => ["til", "lit"], "ffo" => ["off"], "aep" => ["ape", "pea"],
      "aal" => ["aal", "laa", "ala"], "dry" => ["dry"], "ino" => ["ion"],
      "oww" => ["wow"], "efr" => ["erf", "fer", "ref"], "bmo" => ["mob"],
      "efu" => ["feu"], "agu" => ["gau"], "agz" => ["zag"], "det" => ["ted"],
      "egg" => ["egg"], "bbi" => ["bib"], "boy" => ["yob", "boy"], "hio" => ["hoi"],
      "act" => ["act", "cat"], "dot" => ["tod", "dot"], "ahj" => ["haj"],
      "deo" => ["ode", "doe"], "bhu" => ["hub"], "aco" => ["oca"],
      "glu" => ["gul", "lug"], "stu" => ["uts"], "eno" => ["one"], "eip" => ["pie"],
      "lsy" => ["sly"], "eev" => ["vee", "eve"], "eps" => ["pes"], "tuu" => ["utu"],
      "amp" => ["amp", "map"], "eow" => ["woe", "owe"], "suw" => ["wus"],
      "bey" => ["bey", "bye"], "abs" => ["bas", "sab"], "moo" => ["oom", "moo"],
      "adt" => ["tad"], "aai" => ["aia"], "avw" => ["vaw"], "ovx" => ["vox"],
      "bdu" => ["bud", "dub"], "dnu" => ["dun"], "asv" => ["vas"], "axz" => ["zax"],
      "cop" => ["cop"], "ail" => ["ail"], "elw" => ["lew"], "ekn" => ["nek", "ken"],
      "psu" => ["pus", "sup", "ups"], "dor" => ["dor", "rod"], "msy" => ["mys"],
      "ant" => ["ant", "tan"], "ajr" => ["raj", "jar"], "ikt" => ["kit"],
      "gjo" => ["jog"], "adl" => ["lad"], "lru" => ["lur"], "dmo" => ["mod"],
      "exy" => ["yex"], "ejo" => ["joe"], "bis" => ["sib", "bis"],
      "hos" => ["hos", "ohs"], "als" => ["als", "las", "sal"], "irz" => ["riz"],
      "fiz" => ["fiz"], "dex" => ["dex", "xed"], "bor" => ["orb", "rob"],
      "cep" => ["cep", "pec"], "avv" => ["vav"], "bgo" => ["gob", "bog"],
      "apx" => ["pax"], "epp" => ["pep"], "inv" => ["vin"], "eem" => ["eme"],
      "itu" => ["tui"], "ehm" => ["meh", "hem"], "ber" => ["reb"], "ils" => ["lis"],
      "giv" => ["vig"], "bcu" => ["cub"], "goy" => ["ygo", "goy"], "mpu" => ["ump"],
      "iss" => ["sis"], "lux" => ["lux"], "muv" => ["vum"], "enw" => ["wen", "new"],
      "aht" => ["hat"], "ist" => ["tis", "its", "sit"], "dno" => ["nod", "don"],
      "eho" => ["hoe"], "ams" => ["sam", "mas"], "hsy" => ["shy"],
      "anp" => ["nap", "pan"], "ahs" => ["ahs", "sha", "ash", "has"],
      "bsy" => ["bys"], "osw" => ["ows", "wos", "sow"], "iou" => ["oui"],
      "bru" => ["urb", "bur", "rub"], "gmo" => ["mog"],
      "ehs" => ["ehs", "hes", "she"], "acr" => ["arc", "car"], "gis" => ["gis"],
      "adh" => ["dah", "had"], "etv" => ["vet"], "cis" => ["cis", "sic"],
      "foo" => ["foo", "oof"], "amm" => ["mam"], "dip" => ["dip"],
      "ako" => ["koa", "oka", "oak"], "dru" => ["rud", "urd"],
      "ado" => ["oda", "ado"], "esy" => ["sey", "sye", "yes"], "pst" => ["pst"],
      "ehx" => ["hex"], "imr" => ["mir", "rim"], "abw" => ["wab"], "beo" => ["obe"],
      "aev" => ["vae"], "kuy" => ["kyu", "yuk"], "emw" => ["wem", "mew"],
      "imv" => ["vim"], "aku" => ["auk"], "moz" => ["moz"], "cip" => ["pic"],
      "adf" => ["fad"], "aas" => ["aas"], "aby" => ["aby", "bay"],
      "aam" => ["ama", "maa"], "aaw" => ["awa"], "abg" => ["gab", "bag"],
      "agw" => ["wag"], "bit" => ["bit"], "hoo" => ["hoo", "ooh", "oho"],
      "aho" => ["hao", "hoa"], "ayy" => ["yay"], "noy" => ["noy", "yon"],
      "bnu" => ["nub", "bun"], "hhu" => ["huh"], "cdu" => ["cud"],
      "apy" => ["pya", "yap", "pay"], "abr" => ["arb", "bra", "bar"],
      "bbe" => ["ebb"], "ikn" => ["kin", "ink"], "ett" => ["tet"],
      "akm" => ["kam", "mak"], "ars" => ["ars", "ras", "sar"],
      "git" => ["tig", "git"], "ain" => ["ain"], "hnu" => ["hun"], "lvy" => ["vly"],
      "dlo" => ["old"], "bim" => ["mib"], "all" => ["all"], "eet" => ["tee"],
      "coy" => ["coy"], "giw" => ["wig"], "erz" => ["rez"], "mot" => ["mot", "tom"],
      "biz" => ["biz"], "qsu" => ["suq"], "eef" => ["fee"], "gru" => ["gur", "rug"],
      "asz" => ["saz", "zas"], "efz" => ["fez"], "afu" => ["auf"],
      "eky" => ["kye", "key"], "cmy" => ["myc"], "fix" => ["fix"], "gin" => ["gin"],
      "ade" => ["dae"], "buy" => ["buy"], "ipz" => ["zip"], "bos" => ["bos", "sob"],
      "egs" => ["seg"], "iks" => ["ski"], "hmu" => ["hum"], "got" => ["tog", "got"],
      "ach" => ["cha"], "aeg" => ["age"], "imp" => ["imp"], "gos" => ["gos", "sog"],
      "eor" => ["ore", "roe"], "epz" => ["zep"], "ees" => ["see"], "enz" => ["zen"],
      "ikp" => ["kip"], "eft" => ["fet", "tef", "eft"], "adi" => ["aid"],
      "his" => ["ish", "his"], "eir" => ["rei", "ire"], "dez" => ["zed"],
      "ajp" => ["jap"], "dmu" => ["mud"], "ipy" => ["yip"], "agm" => ["gam"],
      "bho" => ["boh", "hob"], "bbo" => ["bob"], "fir" => ["rif", "fir"],
      "iln" => ["nil"], "nwy" => ["wyn"], "doz" => ["dzo"], "ost" => ["sot"],
      "bfu" => ["fub"], "agg" => ["gag"], "iny" => ["yin"], "isw" => ["wis"],
      "oxy" => ["oxy"], "izz" => ["ziz"], "puy" => ["puy", "yup"],
      "ael" => ["ela", "lea", "ale"], "emo" => ["moe", "emo"], "opz" => ["poz"],
      "ijn" => ["jin"], "pxy" => ["pyx"], "giz" => ["zig"], "dfi" => ["fid"],
      "fly" => ["fly"], "anu" => ["anu"], "goo" => ["goo"], "int" => ["nit", "tin"],
      "air" => ["rai", "ria", "air"], "elm" => ["lem", "mel", "elm"],
      "cru" => ["ruc", "cru", "cur"], "afw" => ["faw"], "ios" => ["ios", "ois"],
      "lop" => ["pol", "lop"], "inz" => ["zin"], "diu" => ["dui"], "kow" => ["wok"],
      "etu" => ["ute"], "afo" => ["oaf"], "oop" => ["poo"], "osz" => ["zos"],
      "not" => ["ton", "not"], "sty" => ["sty"], "dee" => ["dee"],
      "any" => ["nay", "any"], "gij" => ["jig"], "ely" => ["ley", "lye"],
      "ffi" => ["iff"], "ejw" => ["jew"], "adk" => ["dak"], "aop" => ["poa"],
      "luz" => ["luz"], "brr" => ["brr"], "luu" => ["ulu"], "ssu" => ["sus"],
      "atw" => ["twa", "taw", "wat"], "abj" => ["jab"], "ehn" => ["hen"],
      "hoz" => ["zho"], "abh" => ["bah"], "cim" => ["mic"], "els" => ["les", "els"],
      "opr" => ["pro"], "lpu" => ["pul"], "fry" => ["fry"], "ekl" => ["lek", "elk"],
      "aks" => ["kas", "ska", "ask"], "apt" => ["apt", "pat", "tap"],
      "cor" => ["roc", "orc"], "egi" => ["gie"], "alp" => ["alp", "lap", "pal"],
      "dhi" => ["hid"], "adr" => ["ard"], "npu" => ["pun"],
      "art" => ["tar", "rat", "art"], "ekr" => ["erk"], "asy" => ["ays", "say"],
      "ceu" => ["ecu", "cue"], "ghu" => ["hug", "ugh"], "dfu" => ["fud"],
      "bew" => ["web"], "ips" => ["pis", "sip"], "cot" => ["toc", "cot"],
      "eot" => ["toe"], "aww" => ["waw"], "loo" => ["loo"], "egk" => ["keg"],
      "agl" => ["gal", "lag"], "cel" => ["cel"], "ait" => ["tai", "ait"],
      "aab" => ["aba", "baa"], "efy" => ["fey"], "dow" => ["dow"], "hty" => ["thy"],
      "eos" => ["oes", "ose"], "eju" => ["jeu"], "ptu" => ["tup", "put"],
      "rwy" => ["wry"], "hho" => ["hoh"], "emt" => ["met"], "aqt" => ["qat"],
      "agh" => ["hag"], "ipx" => ["pix"], "asx" => ["sax"], "kor" => ["rok", "kor"],
      "adn" => ["dan", "and"], "joy" => ["joy"], "aan" => ["ana"],
      "low" => ["owl", "low"], "isx" => ["xis", "six"], "fmu" => ["fum"],
      "elt" => ["elt", "let"], "abt" => ["bat", "tab"], "nsy" => ["sny"],
      "auy" => ["ayu"], "fin" => ["fin"], "moy" => ["moy", "yom"], "kst" => ["tsk"],
      "aew" => ["wae", "awe"], "ipp" => ["pip"], "hwy" => ["why"], "mou" => ["mou"],
      "efh" => ["feh"], "ddi" => ["did"], "cee" => ["cee"], "ahr" => ["rah"],
      "gsu" => ["gus", "ugs"], "opt" => ["opt", "pot", "top"], "itw" => ["wit"],
      "hit" => ["hit"], "bdi" => ["dib", "bid"], "agn" => ["gan", "nag"],
      "ins" => ["nis", "ins", "sin"], "fho" => ["foh"], "doo" => ["doo"],
      "efw" => ["few"], "irs" => ["sri", "sir"], "bpu" => ["pub"], "aeh" => ["hae"],
      "agy" => ["yag", "gay"], "jot" => ["jot"], "afg" => ["fag"], "att" => ["tat"],
      "rtu" => ["rut"], "otu" => ["out"], "awx" => ["wax"], "egl" => ["gel", "leg"],
      "fis" => ["ifs"], "acw" => ["caw"], "oox" => ["oxo"],
      "asw" => ["aws", "saw", "was"], "acd" => ["cad"], "fou" => ["ufo", "fou"],
      "fgu" => ["fug"], "aah" => ["aah", "aha"], "inx" => ["nix"], "lmu" => ["lum"],
      "oor" => ["roo"], "dew" => ["dew", "wed"], "eer" => ["ree", "ere"],
      "nnu" => ["nun"], "mos" => ["som", "oms"], "egr" => ["erg"], "dil" => ["lid"],
      "gho" => ["hog"], "afy" => ["fay"], "ouy" => ["you"], "din" => ["nid", "din"],
      "lpy" => ["ply"], "hiu" => ["hui"], "gil" => ["lig"], "how" => ["how", "who"],
      "ery" => ["yer", "rye"], "elz" => ["lez", "zel"],
      "ags" => ["ags", "sag", "gas"], "hmo" => ["mho", "ohm"],
      "ikr" => ["kir", "irk"], "inr" => ["rin"], "eis" => ["sei"], "akt" => ["kat"],
      "egt" => ["teg", "get"], "dhh" => ["hhd"], "coz" => ["coz"],
      "amr" => ["mar", "ram", "arm"], "inp" => ["nip", "pin"],
      "dgo" => ["god", "dog"], "osv" => ["sov"], "nos" => ["ons", "son"],
      "ers" => ["ers"], "adp" => ["dap", "pad"], "jow" => ["jow"], "koy" => ["yok"],
      "elv" => ["lev"], "ilm" => ["mil"], "dlu" => ["lud"], "ess" => ["ess"],
      "der" => ["red"], "ehw" => ["hew"], "ccs" => ["csc"], "amw" => ["maw"],
      "bee" => ["bee"], "oot" => ["oot", "too"], "fit" => ["fit"], "aik" => ["kai"],
      "ans" => ["nas", "san"], "apw" => ["wap", "paw"], "dju" => ["jud"],
      "gir" => ["rig"], "gip" => ["pig"], "acv" => ["vac"], "ntu" => ["tun", "nut"],
      "abn" => ["nab", "ban"], "ort" => ["ort", "tor", "rot"], "des" => ["sed"],
      "ddu" => ["dud"], "cdo" => ["doc", "cod"], "ahn" => ["han", "nah"],
      "ahh" => ["ahh"], "dux" => ["dux"], "amn" => ["mna", "nam", "man"],
      "ajt" => ["taj"], "cry" => ["cry"], "gmu" => ["gum", "mug"], "hhs" => ["shh"],
      "ehh" => ["heh"], "erv" => ["rev"], "aip" => ["pia"], "eew" => ["ewe", "wee"],
      "cow" => ["cow"], "ciy" => ["icy"], "ttu" => ["tut"], "bij" => ["jib"],
      "arw" => ["raw", "war"], "div" => ["vid"], "hpt" => ["pht"], "ksu" => ["suk"],
      "aag" => ["aga"], "cmo" => ["moc"], "mop" => ["pom", "mop"],
      "alm" => ["mal", "lam"], "esx" => ["sex"], "eep" => ["pee"], "egp" => ["peg"],
      "box" => ["box"], "aov" => ["avo", "ova"], "erw" => ["rew"], "agp" => ["gap"],
      "amu" => ["amu"], "mtu" => ["mut", "tum"], "cpu" => ["cup"], "arx" => ["rax"],
      "osu" => ["ous", "sou"], "dho" => ["hod"], "opx" => ["pox"], "ahl" => ["lah"],
      "bmu" => ["bum"], "amo" => ["moa"], "ago" => ["goa", "ago"],
      "adm" => ["dam", "mad"], "acn" => ["can"], "msu" => ["ums", "sum"],
      "aav" => ["ava"], "dey" => ["dey", "dye"], "noo" => ["noo", "oon"],
      "gio" => ["gio"], "ais" => ["sai", "ais"], "eko" => ["oke"], "hno" => ["noh"],
      "dgi" => ["gid", "dig"], "akw" => ["kaw"], "esw" => ["sew"],
      "epr" => ["pre", "rep", "per"], "lox" => ["lox"], "gow" => ["wog"],
      "awy" => ["yaw", "way"], "btu" => ["tub", "but"], "hpu" => ["hup"],
      "bno" => ["nob"], "dhu" => ["duh"], "asu" => ["sau"], "aky" => ["kay", "yak"],
      "gpy" => ["gyp"], "acs" => ["sac"], "gty" => ["tyg"], "ety" => ["tye", "yet"],
      "aty" => ["tay"], "gtu" => ["tug", "gut"], "eel" => ["eel", "lee"],
      "eiv" => ["vie"], "evx" => ["vex"], "ajm" => ["jam"],
      "aen" => ["ean", "ane", "nae"], "hik" => ["khi"], "ksy" => ["sky"],
      "bop" => ["bop"], "hin" => ["hin"], "ahm" => ["ham"], "iop" => ["poi"],
      "glo" => ["log"], "ejt" => ["jet"], "afh" => ["fah"], "dik" => ["kid"],
      "gnu" => ["gnu", "gun"], "ppu" => ["pup"], "bgu" => ["gub", "bug"],
      "atv" => ["tav", "vat"], "ahw" => ["wha", "haw"], "nor" => ["nor"],
      "dou" => ["oud", "udo", "duo"], "bko" => ["bok", "kob"],
      "apr" => ["rap", "par"], "fox" => ["fox"],
      "otw" => ["owt", "tow", "wot", "two"], "eku" => ["euk", "kue", "uke"],
      "inw" => ["win"], "fgi" => ["gif", "fig"], "abm" => ["bam"],
      "for" => ["orf", "fro", "for"], "jtu" => ["jut"], "cmw" => ["cwm"],
      "eek" => ["eek", "eke"], "ass" => ["ass"], "efs" => ["efs", "fes"],
      "alr" => ["lar"], "cuz" => ["cuz"], "bco" => ["cob"], "ekt" => ["ket"],
      "owy" => ["yow"], "ehy" => ["hye", "yeh", "hey"], "fru" => ["fur"],
      "bin" => ["nib", "bin"], "opw" => ["pow", "wop"], "bsu" => ["sub", "bus"],
      "him" => ["him"], "aeu" => ["eau"], "apz" => ["zap"], "aiv" => ["via"],
      "efl" => ["elf"], "efn" => ["nef", "fen"], "err" => ["err"],
      "ims" => ["mis", "ism", "sim"], "ace" => ["ace"], "boo" => ["obo", "boo"],
      "gpu" => ["gup", "pug"], "adg" => ["gad"], "anw" => ["naw", "awn", "wan"],
      "afx" => ["fax"], "erx" => ["rex"], "agt" => ["gat", "tag"], "fsy" => ["fys"],
      "kos" => ["kos"], "epw" => ["pew"], "abk" => ["kab"]}
    |> Map.get(string_id)
  end

  def valid_ids do
    ["bez", "loy", "abo", "aek", "imz", "hot", "aem", "oow", "ctu", "afr", "mux",
     "zzz", "eoy", "dgu", "abd", "lor", "hip", "elu", "swy", "inu", "bgi", "osy",
     "pru", "imx", "abf", "ikl", "nru", "gmy", "bde", "dsu", "gox", "lot", "agj",
     "muy", "cly", "ehu", "elp", "ehi", "egu", "hnt", "eov", "ajy", "aey", "eil",
     "deu", "bil", "ooz", "hop", "nno", "ggi", "acy", "npw", "ahp", "ivy", "aes",
     "ekw", "mmo", "fnu", "ewy", "afn", "ott", "doy", "cgo", "abl", "aft", "dop",
     "bdo", "imn", "imm", "cgi", "cox", "fno", "eej", "chi", "flu", "ops", "epy",
     "tux", "eit", "ehr", "efk", "fil", "now", "app", "hoy", "oos", "acm", "ovw",
     "bfi", "amy", "atx", "ept", "psy", "amt", "fik", "aps", "itt", "aly", "bow",
     "aoz", "ddo", "akr", "alx", "ell", "euy", "foy", "dkl", "diy", "esz", "ors",
     "eny", "dim", "beg", "cno", "ajw", "opp", "eeg", "kop", "aot", "est", "aet",
     "auv", "deh", "imo", "mru", "orw", "dos", "inn", "etw", "aqu", "ill", "dei",
     "oty", "kno", "bio", "fop", "hmm", "lmo", "hor", "den", "cit", "aim", "ekz",
     "itz", "uzz", "iko", "ilo", "gim", "fgo", "emn", "rsu", "bbu", "nsu", "ilp",
     "hss", "duw", "rty", "opu", "coo", "oru", "fot", "ipt", "los", "nov", "emu",
     "ben", "egv", "enp", "alw", "bir", "cei", "ent", "ajk", "eez", "mmu", "eey",
     "ekx", "add", "pry", "ady", "acp", "ems", "def", "suy", "blo", "ary", "isu",
     "mow", "bet", "dit", "ads", "ego", "eht", "een", "abp", "esu", "eop", "bfo",
     "afk", "ahy", "ast", "ceh", "lmy", "abc", "eru", "gno", "guy", "efo", "hox",
     "anr", "ipr", "ekp", "adw", "iwz", "agr", "cho", "abb", "cik", "dir", "dpu",
     "atu", "efi", "aor", "egm", "anv", "dis", "del", "iqs", "guv", "ens", "htu",
     "bes", "acl", "ehp", "gju", "aer", "bjo", "ilt", "ffo", "aep", "aal", "dry",
     "ino", "oww", "efr", "bmo", "efu", "agu", "agz", "det", "egg", "bbi", "boy",
     "hio", "act", "dot", "ahj", "deo", "bhu", "aco", "glu", "stu", "eno", "eip",
     "lsy", "eev", "eps", "tuu", "amp", "eow", "suw", "bey", "abs", "moo", "adt",
     "aai", "avw", "ovx", "bdu", "dnu", "asv", "axz", "cop", "ail", "elw", "ekn",
     "psu", "dor", "msy", "ant", "ajr", "ikt", "gjo", "adl", "lru", "dmo", "exy",
     "ejo", "bis", "hos", "als", "irz", "fiz", "dex", "bor", "cep", "avv", "bgo",
     "apx", "epp", "inv", "eem", "itu", "ehm", "ber", "ils", "giv", "bcu", "goy",
     "mpu", "iss", "lux", "muv", "enw", "aht", "ist", "dno", "eho", "ams", "hsy",
     "anp", "ahs", "bsy", "osw", "iou", "bru", "gmo", "ehs", "acr", "gis", "adh",
     "etv", "cis", "foo", "amm", "dip", "ako", "dru", "ado", "esy", "pst", "ehx",
     "imr", "abw", "beo", "aev", "kuy", "emw", "imv", "aku", "moz", "cip", "adf",
     "aas", "aby", "aam", "aaw", "abg", "agw", "bit", "hoo", "aho", "ayy", "noy",
     "bnu", "hhu", "cdu", "apy", "abr", "bbe", "ikn", "ett", "akm", "ars", "git",
     "ain", "hnu", "lvy", "dlo", "bim", "all", "eet", "coy", "giw", "erz", "mot",
     "biz", "qsu", "eef", "gru", "asz", "efz", "afu", "eky", "cmy", "fix", "gin",
     "ade", "buy", "ipz", "bos", "egs", "iks", "hmu", "got", "ach", "aeg", "imp",
     "gos", "eor", "epz", "ees", "enz", "ikp", "eft", "adi", "his", "eir", "dez",
     "ajp", "dmu", "ipy", "agm", "bho", "bbo", "fir", "iln", "nwy", "doz", "ost",
     "bfu", "agg", "iny", "isw", "oxy", "izz", "puy", "ael", "emo", "opz", "ijn",
     "pxy", "giz", "dfi", "fly", "anu", "goo", "int", "air", "elm", "cru", "afw",
     "ios", "lop", "inz", "diu", "kow", "etu", "afo", "oop", "osz", "not", "sty",
     "dee", "any", "gij", "ely", "ffi", "ejw", "adk", "aop", "luz", "brr", "luu",
     "ssu", "atw", "abj", "ehn", "hoz", "abh", "cim", "els", "opr", "lpu", "fry",
     "ekl", "aks", "apt", "cor", "egi", "alp", "dhi", "adr", "npu", "art", "ekr",
     "asy", "ceu", "ghu", "dfu", "bew", "ips", "cot", "eot", "aww", "loo", "egk",
     "agl", "cel", "ait", "aab", "efy", "dow", "hty", "eos", "eju", "ptu", "rwy",
     "hho", "emt", "aqt", "agh", "ipx", "asx", "kor", "adn", "joy", "aan", "low",
     "isx", "fmu", "elt", "abt", "nsy", "auy", "fin", "moy", "kst", "aew", "ipp",
     "hwy", "mou", "efh", "ddi", "cee", "ahr", "gsu", "opt", "itw", "hit", "bdi",
     "agn", "ins", "fho", "doo", "efw", "irs", "bpu", "aeh", "agy", "jot", "afg",
     "att", "rtu", "otu", "awx", "egl", "fis", "acw", "oox", "asw", "acd", "fou",
     "fgu", "aah", "inx", "lmu", "oor", "dew", "eer", "nnu", "mos", "egr", "dil",
     "gho", "afy", "ouy", "din", "lpy", "hiu", "gil", "how", "ery", "elz", "ags",
     "hmo", "ikr", "inr", "eis", "akt", "egt", "dhh", "coz", "amr", "inp", "dgo",
     "osv", "nos", "ers", "adp", "jow", "koy", "elv", "ilm", "dlu", "ess", "der",
     "ehw", "ccs", "amw", "bee", "oot", "fit", "aik", "ans", "apw", "dju", "gir",
     "gip", "acv", "ntu", "abn", "ort", "des", "ddu", "cdo", "ahn", "ahh", "dux",
     "amn", "ajt", "cry", "gmu", "hhs", "ehh", "erv", "aip", "eew", "cow", "ciy",
     "ttu", "bij", "arw", "div", "hpt", "ksu", "aag", "cmo", "mop", "alm", "esx",
     "eep", "egp", "box", "aov", "erw", "agp", "amu", "mtu", "cpu", "arx", "osu",
     "dho", "opx", "ahl", "bmu", "amo", "ago", "adm", "acn", "msu", "aav", "dey",
     "noo", "gio", "ais", "eko", "hno", "dgi", "akw", "esw", "epr", "lox", "gow",
     "awy", "btu", "hpu", "bno", "dhu", "asu", "aky", "gpy", "acs", "gty", "ety",
     "aty", "gtu", "eel", "eiv", "evx", "ajm", "aen", "hik", "ksy", "bop", "hin",
     "ahm", "iop", "glo", "ejt", "afh", "dik", "gnu", "ppu", "bgu", "atv", "ahw",
     "nor", "dou", "bko", "apr", "fox", "otw", "eku", "inw", "fgi", "abm", "for",
     "jtu", "cmw", "eek", "ass", "efs", "alr", "cuz", "bco", "ekt", "owy", "ehy",
     "fru", "bin", "opw", "bsu", "him", "aeu", "apz", "aiv", "efl", "efn", "err",
     "ims", "ace", "boo", "gpu", "adg", "anw", "afx", "erx", "agt", "fsy", "kos",
     "epw", "abk"]
    |> Enum.into(HashSet.new)
  end
end
