defmodule Jumble.ScowlDict.Small.Length5 do
  def get(string_id) do
    %{"alnru" => ["lunar"], "ademn" => ["amend", "named"], "aeopr" => ["opera"],
      "agnow" => ["wagon"], "fhisy" => ["fishy"], "bgrsu" => ["grubs"],
      "acnor" => ["acorn"], "enrty" => ["entry"], "aadrr" => ["radar"],
      "doowy" => ["woody"], "aeglz" => ["glaze"], "first" => ["rifts", "first"],
      "eoprw" => ["power"], "beegi" => ["beige"], "aeltx" => ["exalt", "latex"],
      "addez" => ["dazed"], "ehlov" => ["hovel"], "prssu" => ["spurs"],
      "elmno" => ["melon", "lemon"], "aclms" => ["calms", "clams"],
      "amnnu" => ["unman"], "ittwy" => ["witty"], "aelqu" => ["equal"],
      "klssu" => ["sulks"], "agnoy" => ["agony"], "aafnu" => ["fauna"],
      "bclsu" => ["clubs"], "ddeoz" => ["dozed"], "eegrv" => ["verge"],
      "deoow" => ["wooed"], "enpst" => ["spent"], "adilv" => ["valid"],
      "ehntt" => ["tenth"], "afint" => ["faint"], "eenrt" => ["enter"],
      "anory" => ["rayon"], "lopsy" => ["ploys"], "eimpr" => ["prime"],
      "acgin" => ["acing"], "inrsu" => ["ruins"], "afiry" => ["fairy"],
      "aipzz" => ["pizza"], "afirs" => ["fairs"], "bcmos" => ["combs"],
      "hnstu" => ["shunt", "hunts"], "adhny" => ["handy"], "aflls" => ["falls"],
      "alrru" => ["rural"], "dehss" => ["sheds"], "blntu" => ["blunt"],
      "alnps" => ["plans"], "aprty" => ["party"], "ckssu" => ["sucks"],
      "aosvw" => ["avows"], "ellps" => ["spell"], "glnos" => ["longs"],
      "asvvy" => ["savvy"], "abist" => ["baits"], "ikmrs" => ["smirk"],
      "eistu" => ["suite"], "lppsu" => ["pulps"], "acehp" => ["peach", "cheap"],
      "aeksw" => ["askew", "wakes"], "adgmo" => ["dogma"], "lmppu" => ["plump"],
      "dehik" => ["hiked"], "ejnoy" => ["enjoy"], "acems" => ["maces"],
      "aelms" => ["lames", "males", "meals"], "gnouy" => ["young"],
      "fisst" => ["fists", "sifts"], "cehss" => ["chess"], "bdest" => ["debts"],
      "iloss" => ["silos", "soils"], "aghpr" => ["graph"], "chipr" => ["chirp"],
      "dglos" => ["golds"], "ackls" => ["slack", "lacks"], "abnot" => ["baton"],
      "hloty" => ["hotly"], "aacln" => ["canal"], "enrsw" => ["wrens"],
      "eelrs" => ["leers", "reels"], "cehst" => ["chest"],
      "deefr" => ["defer", "freed"], "eelop" => ["elope"], "gnrtu" => ["grunt"],
      "aalns" => ["nasal"], "deesu" => ["suede"], "aeegr" => ["eager", "agree"],
      "addew" => ["waded"], "empty" => ["empty"], "eorrs" => ["sorer"],
      "ejkos" => ["jokes"], "agint" => ["giant"], "anssw" => ["swans"],
      "denot" => ["toned", "noted"], "eejlw" => ["jewel"], "eilnn" => ["linen"],
      "gnstu" => ["stung"], "afilr" => ["flair", "frail"], "cdeiv" => ["viced"],
      "demsu" => ["mused"], "adirs" => ["raids"], "ehllo" => ["hello"],
      "hilrw" => ["whirl"], "alost" => ["altos"], "mosuy" => ["mousy"],
      "elors" => ["loser", "roles"], "deoor" => ["rodeo"], "eprru" => ["purer"],
      "eintw" => ["twine"], "imppr" => ["primp"], "eessx" => ["sexes"],
      "egpru" => ["purge"], "acdey" => ["decay"], "rsstu" => ["rusts"],
      "dehpt" => ["depth"], "efmsu" => ["fumes"], "acdef" => ["faced"],
      "aelsx" => ["axles"], "ademt" => ["mated", "tamed"], "egnsu" => ["genus"],
      "afluw" => ["awful"], "chhiw" => ["which"], "acden" => ["caned", "dance"],
      "aggns" => ["gangs"], "doors" => ["doors"], "hnory" => ["horny"],
      "iorsv" => ["visor"], "achin" => ["china", "chain"], "copsu" => ["coups"],
      "aoptz" => ["topaz"], "cemot" => ["comet"], "agksw" => ["gawks"],
      "abelm" => ["amble", "blame"], "adrst" => ["darts"], "eppru" => ["upper"],
      "eimrx" => ["mixer"], "blrsu" => ["blurs"], "aksst" => ["tasks"],
      "answy" => ["yawns"], "celru" => ["ulcer", "cruel"], "fklnu" => ["flunk"],
      "emosu" => ["mouse"], "ekloy" => ["yokel"], "arsty" => ["trays", "stray"],
      "dootu" => ["outdo"], "hsstu" => ["shuts"], "affix" => ["affix"],
      "agnry" => ["angry"], "moort" => ["motor"], "eimsx" => ["mixes"],
      "bettu" => ["butte"], "deekn" => ["kneed"], "prstu" => ["spurt"],
      "ekpsu" => ["pukes"], "agrss" => ["grass"], "eikss" => ["skies"],
      "deinx" => ["index"], "aclot" => ["octal"], "hksuy" => ["husky"],
      "agnor" => ["groan", "organ"], "adfrt" => ["draft"], "aaenr" => ["arena"],
      "eekov" => ["evoke"], "eprss" => ["press"], "egnor" => ["goner"],
      "berry" => ["berry"], "bcdeu" => ["cubed"], "cikks" => ["kicks"],
      "defox" => ["foxed"], "inopt" => ["point"], "bdduy" => ["buddy"],
      "adefm" => ["famed"], "aerss" => ["sears"], "acort" => ["actor"],
      "abdir" => ["braid", "rabid"], "elorw" => ["lower"], "oopsw" => ["swoop"],
      "deegw" => ["wedge"], "dorsw" => ["sword", "words"], "ilstw" => ["wilts"],
      "knoos" => ["nooks"], "achps" => ["chaps"], "kloos" => ["looks"],
      "abwyy" => ["byway"], "ahlsw" => ["shawl"], "deikl" => ["liked"],
      "abssw" => ["swabs"], "elpst" => ["pelts", "slept"], "foors" => ["roofs"],
      "bhoot" => ["booth"], "ejkor" => ["joker"], "ailov" => ["viola"],
      "acsuy" => ["saucy"], "aeelv" => ["leave"], "ddesu" => ["dudes"],
      "lostv" => ["volts"], "addpy" => ["paddy"], "ehlow" => ["whole"],
      "aadeh" => ["ahead"], "cgiin" => ["icing"], "iklms" => ["milks"],
      "cckoy" => ["cocky"], "aensv" => ["vanes"], "acdis" => ["acids"],
      "gilny" => ["lying"], "abess" => ["bases"], "aefrw" => ["wafer"],
      "adesw" => ["sawed", "wades"], "anrsy" => ["yarns"],
      "denst" => ["dents", "tends"], "akmss" => ["masks"], "efint" => ["feint"],
      "cloos" => ["cools"], "achlt" => ["latch"], "cenou" => ["ounce"],
      "agprs" => ["grasp"], "adesz" => ["dazes"], "ilrtw" => ["twirl"],
      "pttuy" => ["putty"], "ccikl" => ["click"], "deilt" => ["tilde", "tiled"],
      "agmny" => ["mangy"], "esstt" => ["tests"], "fsttu" => ["tufts"],
      "aaimr" => ["maria"], "bdeij" => ["jibed"], "esstw" => ["stews"],
      "aistv" => ["vista"], "ehilw" => ["while"], "cciiv" => ["civic"],
      "elrru" => ["ruler"], "amnow" => ["woman"], "bchnu" => ["bunch"],
      "hmnsy" => ["hymns"], "cfikl" => ["flick"], "afkly" => ["flaky"],
      "gnost" => ["tongs"], "acpst" => ["pacts"],
      "defil" => ["field", "filed", "flied"], "cikln" => ["clink"],
      "gmmuy" => ["gummy"], "orsty" => ["story"], "eikms" => ["mikes"],
      "eimms" => ["mimes"], "chkos" => ["hocks", "shock"], "dgilu" => ["guild"],
      "abnrs" => ["barns"], "ehins" => ["shine"], "adoss" => ["sodas"],
      "innoo" => ["onion"], "ampsu" => ["pumas"],
      "almps" => ["lamps", "palms", "psalm"], "agnps" => ["pangs"],
      "abbir" => ["rabbi"], "chlru" => ["lurch"], "afoot" => ["afoot"],
      "efgin" => ["feign"], "emopt" => ["tempo"], "eglos" => ["ogles"],
      "aeesv" => ["eaves"], "aairt" => ["tiara"], "cikns" => ["nicks"],
      "aersz" => ["razes"], "aelmr" => ["lamer", "realm"], "beooz" => ["booze"],
      "chhit" => ["hitch"], "beeos" => ["obese"], "acrsy" => ["scary"],
      "cehko" => ["choke"], "emosv" => ["moves"], "alsty" => ["salty"],
      "adnsy" => ["sandy"], "cikst" => ["ticks", "stick"], "aekmr" => ["maker"],
      "mrstu" => ["strum"], "aijls" => ["jails"], "adnor" => ["adorn"],
      "afirr" => ["friar"], "deeft" => ["feted"], "degrs" => ["dregs"],
      "abelt" => ["bleat", "table"], "elmsu" => ["mules"], "flosu" => ["fouls"],
      "ioprr" => ["prior"], "afnsw" => ["fawns"], "ikqru" => ["quirk"],
      "amost" => ["moats", "atoms"], "orstu" => ["tours", "routs"],
      "belly" => ["belly"], "amprs" => ["ramps"], "ailnp" => ["plain"],
      "bdeel" => ["bleed"], "bdeox" => ["boxed"], "aabln" => ["banal"],
      "aesty" => ["yeast"], "elost" => ["stole"], "aadmm" => ["madam"],
      "chikt" => ["thick"], "dgloy" => ["godly"], "elmst" => ["melts", "smelt"],
      "hipss" => ["ships"], "celnu" => ["uncle"], "ejkry" => ["jerky"],
      "ckost" => ["stock"], "einru" => ["urine"], "esstv" => ["vests"],
      "epsst" => ["pests", "steps"], "dkosu" => ["kudos"], "bmpsu" => ["bumps"],
      "egilu" => ["guile"], "glluy" => ["gully"], "cchik" => ["chick"],
      "cioru" => ["curio"], "aeikl" => ["alike"], "dekoy" => ["yoked"],
      "ghhis" => ["highs"], "abdly" => ["badly"], "aistw" => ["waist", "waits"],
      "deosu" => ["douse"], "adisy" => ["daisy"], "adist" => ["staid"],
      "aannw" => ["wanna"], "aessy" => ["essay"], "ahlsu" => ["hauls"],
      "alrtw" => ["trawl"], "gmoor" => ["groom"],
      "adepr" => ["drape", "pared", "raped"], "iqstu" => ["quits"],
      "illrt" => ["trill"], "mossy" => ["mossy"], "eiipx" => ["pixie"],
      "achkw" => ["whack"], "ghotu" => ["tough", "ought"],
      "eiqtu" => ["quiet", "quite"], "adhor" => ["hoard"], "afils" => ["fails"],
      "lllos" => ["lolls"], "aimns" => ["mains"], "bdeno" => ["boned"],
      "eelps" => ["peels", "sleep"], "aftty" => ["fatty"], "boors" => ["boors"],
      "abdln" => ["bland"], "allsy" => ["sally"], "elstu" => ["lutes"],
      "bkluy" => ["bulky"], "ehosw" => ["whose"], "densv" => ["vends"],
      "eirsw" => ["wires", "wiser"], "aektw" => ["tweak"],
      "eefls" => ["flees", "feels"], "gilnt" => ["glint"],
      "coops" => ["coops", "scoop"], "deorv" => ["drove"], "ejlls" => ["jells"],
      "alosv" => ["ovals"], "addei" => ["aided"], "cehit" => ["ethic"],
      "adiov" => ["avoid"], "iopsu" => ["pious"], "ersst" => ["rests"],
      "adlns" => ["lands"], "deost" => ["dotes"], "almss" => ["slams"],
      "besty" => ["bytes"], "foops" => ["spoof"], "foost" => ["foots"],
      "abegn" => ["began"], "frssu" => ["surfs"], "aelpp" => ["apple"],
      "afhrw" => ["wharf"], "aeknw" => ["waken"], "girst" => ["grits"],
      "mmmuy" => ["mummy"], "beefy" => ["beefy"], "egisv" => ["gives"],
      "bdlno" => ["blond"], "aglot" => ["gloat"], "aberr" => ["barer"],
      "eentt" => ["tenet"], "fglnu" => ["flung"], "eipqu" => ["pique", "equip"],
      "ffhiw" => ["whiff"], "eeilt" => ["elite"], "ejlly" => ["jelly"],
      "abekl" => ["bleak"], "loprw" => ["prowl"], "adegw" => ["waged"],
      "cdery" => ["decry"], "msstu" => ["musts", "smuts"], "deorw" => ["rowed"],
      "hooss" => ["shoos"], "eiprv" => ["viper"], "adgru" => ["guard"],
      "adert" => ["rated", "trade", "tread"], "cfklo" => ["flock"],
      "imopu" => ["opium"], "fnost" => ["fonts"], "acllo" => ["local"],
      "dehmo" => ["homed"], "abbot" => ["abbot"], "nosst" => ["snots"],
      "elpry" => ["reply"], "acehl" => ["leach"], "ckory" => ["rocky"],
      "adnsw" => ["dawns", "wands"], "acsst" => ["casts"], "bmnsu" => ["numbs"],
      "egstu" => ["guest"], "efins" => ["fines"], "inosy" => ["noisy"],
      "aekls" => ["lakes", "leaks", "slake"], "ghstu" => ["thugs"],
      "enrsu" => ["runes", "nurse"], "aginr" => ["grain"], "aerrr" => ["rarer"],
      "fgiln" => ["fling"], "gnopr" => ["prong"], "deesx" => ["sexed"],
      "iklls" => ["kills", "skill"], "ehops" => ["hopes"], "aepsu" => ["pause"],
      "deisz" => ["sized"], "ceefn" => ["fence"], "acmos" => ["comas"],
      "aefsz" => ["fazes"], "npstu" => ["punts"], "ellsy" => ["yells"],
      "bcehl" => ["belch"], "ejkrs" => ["jerks"], "cdenu" => ["dunce"],
      "belos" => ["lobes"], "acerv" => ["carve", "crave"], "cikss" => ["sicks"],
      "depty" => ["typed"], "ginru" => ["ruing"], "coprs" => ["corps", "crops"],
      "chmnu" => ["munch"], "aginx" => ["axing"], "hinss" => ["shins"],
      "fhist" => ["shift"], "dfirt" => ["drift"], "aerrw" => ["rawer"],
      "dlops" => ["plods"], "aberz" => ["zebra"], "censt" => ["cents", "scent"],
      "aakky" => ["kayak"], "hmsuy" => ["mushy"], "denos" => ["nosed", "nodes"],
      "orttu" => ["trout", "tutor"], "egins" => ["singe"],
      "densu" => ["dunes", "nudes"], "aeilm" => ["email"], "dgiit" => ["digit"],
      "nsttu" => ["stunt"], "abegl" => ["bagel", "gable"], "aorrs" => ["roars"],
      "eptty" => ["petty"], "afmoy" => ["foamy"], "erstu" => ["trues"],
      "hoops" => ["hoops"], "aehlv" => ["halve"], "oopps" => ["poops"],
      "egoru" => ["rogue", "rouge"], "hmptu" => ["thump"],
      "aelsv" => ["salve", "slave"], "cdeko" => ["coked"],
      "ehirs" => ["heirs", "shire", "hires"], "knnow" => ["known"],
      "dopru" => ["proud"], "deors" => ["doers"], "aenry" => ["yearn"],
      "ginsu" => ["suing", "using"], "iklst" => ["kilts"], "ceins" => ["since"],
      "ahiry" => ["hairy"], "aailv" => ["avail"], "ffhsu" => ["huffs"],
      "allty" => ["tally"], "admno" => ["nomad"], "dgrsu" => ["drugs"],
      "einos" => ["noise"], "acdev" => ["caved"], "ckluy" => ["lucky"],
      "corss" => ["cross"], "aehlz" => ["hazel"], "ilpss" => ["lisps", "slips"],
      "aadeg" => ["adage"], "adetx" => ["taxed"], "bdeit" => ["debit"],
      "ahntu" => ["haunt"], "ampst" => ["stamp"], "beefs" => ["beefs"],
      "agist" => ["gaits"], "eelrv" => ["lever", "revel"], "degju" => ["judge"],
      "dginy" => ["dingy", "dying"], "agnst" => ["angst", "gnats", "tangs"],
      "abeov" => ["above"], "bcehn" => ["bench"], "aepsv" => ["paves"],
      "flops" => ["flops"], "ckmsu" => ["mucks"], "abotu" => ["about"],
      "efltu" => ["flute"], "abdns" => ["bands"], "eikls" => ["likes"],
      "deinw" => ["widen", "wined"], "demno" => ["demon"], "cdilu" => ["lucid"],
      "eeegs" => ["geese"], "adept" => ["adept", "taped"], "afmrs" => ["farms"],
      "opprs" => ["props"], "aertx" => ["extra"], "ehnoy" => ["honey"],
      "alnsw" => ["lawns"], "ehrtw" => ["threw"], "aerwy" => ["weary"],
      "bbooy" => ["booby"], "deoww" => ["wowed"], "aclos" => ["coals"],
      "aehsz" => ["hazes"], "demns" => ["mends"], "crstu" => ["crust"],
      "ddgiy" => ["giddy"], "nossw" => ["snows"], "ccely" => ["cycle"],
      "dmoos" => ["moods", "dooms"], "elmos" => ["moles"], "ikmss" => ["skims"],
      "ainop" => ["piano"], "denow" => ["endow", "owned"],
      "aesst" => ["asset", "seats"], "adims" => ["maids"], "illqu" => ["quill"],
      "aacrt" => ["carat"], "lrsuy" => ["surly"], "elnwy" => ["newly"],
      "bffsu" => ["buffs"], "allry" => ["rally"], "ackor" => ["croak"],
      "delns" => ["lends"], "deffo" => ["offed"], "allst" => ["stall"],
      "clmpu" => ["clump"], "agins" => ["gains"], "abems" => ["beams"],
      "ddeiv" => ["dived"], "deooz" => ["oozed"], "illss" => ["sills"],
      "aprsw" => ["warps", "wraps"], "deins" => ["snide", "dines"],
      "ceops" => ["copes", "scope"], "acefh" => ["chafe"], "cffos" => ["scoff"],
      "aqstu" => ["squat"], "alors" => ["orals", "solar"], "emorw" => ["mower"],
      "ipswy" => ["wispy"], "bekor" => ["broke"], "lopst" => ["plots"],
      "deirr" => ["direr", "drier", "rider"], "aostu" => ["autos"],
      "acfrs" => ["scarf"], "ceflt" => ["cleft"], "fiinx" => ["infix"],
      "aklrs" => ["larks"], "dimst" => ["midst"],
      "cinos" => ["sonic", "coins", "icons"], "chill" => ["chill"],
      "eikln" => ["liken"], "ilnos" => ["lions", "loins"], "bghou" => ["bough"],
      "cfhin" => ["finch"], "egisu" => ["guise"], "aflps" => ["flaps"],
      "ceekr" => ["creek"], "ckpsu" => ["pucks"], "aefrt" => ["after"],
      "imost" => ["moist", "omits"], "costu" => ["scout"], "ceilr" => ["relic"],
      "abdsu" => ["daubs"], "aorvy" => ["ovary"], "abnor" => ["baron"],
      "ekrst" => ["treks"], "hiknt" => ["think"], "cersu" => ["cures", "curse"],
      "adenw" => ["waned"], "aglls" => ["galls"], "ahstw" => ["thaws", "whats"],
      "aeevw" => ["weave"], "adehz" => ["hazed"], "acrst" => ["carts"],
      "agnot" => ["tango"], "ddeir" => ["redid", "dried"], "inptu" => ["input"],
      "eissv" => ["vises"], "gissw" => ["swigs"], "alnos" => ["salon", "loans"],
      "aeivw" => ["waive"], "deikn" => ["inked"], "bchir" => ["birch"],
      "abers" => ["bares", "baser", "bears"], "emssu" => ["muses"],
      "llnsu" => ["nulls"], "beors" => ["robes", "bores", "sober"],
      "chnot" => ["notch"], "aeemn" => ["enema"], "ilrsw" => ["swirl"],
      "ilnvy" => ["vinyl"], "eiklr" => ["liker"], "ainry" => ["rainy"],
      "dhnou" => ["hound"], "binry" => ["briny"], "ackrt" => ["track"],
      "eenqu" => ["queen"], "illms" => ["mills"], "deevx" => ["vexed"],
      "celno" => ["clone"], "fimrs" => ["firms"], "adils" => ["dials"],
      "alopr" => ["polar"], "deltw" => ["dwelt"],
      "ainst" => ["satin", "stain", "saint"], "rstuy" => ["rusty"],
      "kllsu" => ["skull"], "cikps" => ["picks"], "giltu" => ["guilt"],
      "adeim" => ["aimed", "media"], "ehrsu" => ["usher"], "ffpuy" => ["puffy"],
      "corsw" => ["crows"], "acfrt" => ["craft"], "ksstu" => ["tusks"],
      "chouv" => ["vouch"], "cdorw" => ["crowd"],
      "aefls" => ["fleas", "leafs", "false"], "ablls" => ["balls"],
      "acmps" => ["camps"], "aegru" => ["argue"], "anopr" => ["apron"],
      "abnrw" => ["brawn"], "llops" => ["polls"], "egouv" => ["vogue"],
      "artty" => ["ratty"], "aelnp" => ["penal", "panel", "plane"],
      "hinsy" => ["shiny"], "achmp" => ["champ"], "achtw" => ["watch"],
      "ddeen" => ["ended"], "ceeip" => ["piece"], "eelmm" => ["lemme"],
      "assty" => ["stays"], "adehl" => ["haled"], "aistx" => ["taxis"],
      "adilt" => ["tidal"], "dekss" => ["desks"], "norst" => ["snort"],
      "ailst" => ["tails"], "acepr" => ["caper", "recap"],
      "cefhi" => ["fiche", "chief"], "beosy" => ["obeys"], "adqsu" => ["squad"],
      "innny" => ["ninny"], "epssw" => ["spews"], "hmnot" => ["month"],
      "cddeo" => ["coded"], "ijlst" => ["jilts"], "ahmnu" => ["human"],
      "hinor" => ["rhino"], "deimx" => ["mixed"], "eensv" => ["evens", "seven"],
      "acdep" => ["caped", "paced"], "aeirs" => ["arise", "raise"],
      "ahmss" => ["shams", "smash"], "aflsw" => ["flaws"], "binos" => ["bison"],
      "adguy" => ["gaudy"], "deikm" => ["miked"], "adfrw" => ["dwarf"],
      "cemry" => ["mercy"], "ahqsu" => ["quash"], "fhort" => ["froth", "forth"],
      "dloor" => ["drool"], "dhirt" => ["third"], "aaemz" => ["amaze"],
      "borru" => ["burro"], "iprvy" => ["privy"], "knpsu" => ["punks", "spunk"],
      "ghhit" => ["thigh"], "cikpy" => ["picky"], "aarry" => ["array"],
      "ipsty" => ["tipsy"], "eilnr" => ["liner"], "anpsw" => ["pawns", "spawn"],
      "eiprt" => ["tripe"], "noops" => ["snoop", "spoon"], "aeluv" => ["value"],
      "aaekw" => ["awake"], "eemst" => ["metes", "teems", "meets"],
      "eissx" => ["sixes"], "denss" => ["sends"],
      "adels" => ["lades", "deals", "leads"], "eorss" => ["roses", "sores"],
      "instu" => ["units"], "hknos" => ["honks"], "opppy" => ["poppy"],
      "ehosu" => ["house"], "egimr" => ["grime"], "acent" => ["enact"],
      "korst" => ["stork"], "bdoor" => ["brood"], "ablsw" => ["bawls"],
      "achmt" => ["match"], "doprs" => ["prods", "drops"],
      "acesu" => ["sauce", "cause"], "ahhrs" => ["harsh"], "ghoru" => ["rough"],
      "cdhil" => ["child"], "aglno" => ["along"], "celsu" => ["clues"],
      "lmpsu" => ["plums", "slump", "lumps"], "gilst" => ["gilts"],
      "dllor" => ["droll"], "emott" => ["totem"], "agily" => ["gaily"],
      "dllsu" => ["dulls"], "flrsu" => ["furls"], "aillv" => ["villa"],
      "acnno" => ["canon"], "ailtv" => ["vital"], "bhoos" => ["hobos"],
      "deorr" => ["order"], "adess" => ["sades"], "cehpr" => ["perch"],
      "aagin" => ["again"], "eglsu" => ["glues"], "abdeo" => ["abode", "adobe"],
      "ginst" => ["sting", "tings"], "deksu" => ["dukes"],
      "egrsu" => ["surge", "urges"], "aptty" => ["patty"], "dksuy" => ["dusky"],
      "abjms" => ["jambs"], "emmos" => ["memos"], "aagnp" => ["pagan"],
      "bnssu" => ["snubs"], "eilst" => ["tiles"], "bgosu" => ["bogus"],
      "asswy" => ["sways"], "eeisz" => ["seize"], "accoo" => ["cocoa"],
      "aagls" => ["galas"], "aboot" => ["taboo"], "aemss" => ["sames", "seams"],
      "gnosw" => ["gowns"], "hpsuy" => ["pushy"], "ahprs" => ["harps", "sharp"],
      "abcel" => ["cable"], "cfosu" => ["focus"], "aalpz" => ["plaza"],
      "aemsx" => ["exams"], "aioss" => ["oasis"], "bdirs" => ["birds"],
      "abceh" => ["beach"], "hipty" => ["pithy"], "deemw" => ["mewed"],
      "bestu" => ["tubes"], "adlrw" => ["drawl"], "brstu" => ["burst"],
      "hknsu" => ["hunks"], "orsst" => ["sorts"],
      "illst" => ["lilts", "tills", "still"], "deesw" => ["sewed", "weeds"],
      "fintu" => ["unfit"], "ddego" => ["dodge"], "eknot" => ["token"],
      "acgir" => ["cigar"], "ffflu" => ["fluff"], "accir" => ["circa"],
      "efirs" => ["fires", "fries"], "cdeos" => ["codes"], "abemy" => ["maybe"],
      "deist" => ["diets", "sited", "tides", "edits"], "agnsw" => ["gnaws"],
      "arstt" => ["tarts", "start"], "hlosw" => ["howls"], "deilm" => ["limed"],
      "achov" => ["havoc"], "eipss" => ["spies"], "adgls" => ["glads"],
      "aennx" => ["annex"], "ckoor" => ["crook"], "einpr" => ["ripen"],
      "aegrw" => ["wager"], "inppy" => ["nippy"], "deelr" => ["elder"],
      "dorss" => ["dross"], "chior" => ["choir"], "alott" => ["total"],
      "abouy" => ["bayou"], "illsw" => ["swill", "wills"], "abkss" => ["basks"],
      "accht" => ["catch"], "adoty" => ["today"], "aorst" => ["roast", "sorta"],
      "eegis" => ["siege"], "adest" => ["dates"], "adfru" => ["fraud"],
      "aeert" => ["eater"], "gnoos" => ["goons"], "aclor" => ["carol", "coral"],
      "aehps" => ["heaps", "phase", "shape"], "aemuv" => ["mauve"],
      "emnsu" => ["menus"], "acert" => ["crate", "cater", "react", "trace"],
      "deimr" => ["dimer", "mired"], "demos" => ["domes", "modes"],
      "aemnt" => ["meant"], "aeors" => ["arose"], "eissu" => ["issue"],
      "aefkl" => ["flake"], "aaklo" => ["koala"], "bdeer" => ["breed"],
      "aeiln" => ["alien"], "cilps" => ["clips"], "aelpr" => ["paler", "pearl"],
      "aervw" => ["waver"], "eirtt" => ["trite"],
      "abest" => ["abets", "baste", "beast", "beats"], "cprty" => ["crypt"],
      "aeswx" => ["waxes"], "fgoor" => ["forgo"], "akqru" => ["quark"],
      "ablmy" => ["balmy"], "enooz" => ["ozone"], "bersv" => ["verbs"],
      "abhit" => ["habit"], "fghit" => ["fight"], "adeft" => ["fated"],
      "deikp" => ["piked"], "aally" => ["allay"], "deopr" => ["pored", "roped"],
      "clrsu" => ["curls"], "chpsy" => ["psych"], "ackps" => ["packs"],
      "eilmp" => ["impel"], "chosw" => ["chows"], "amrry" => ["marry"],
      "emnov" => ["venom"], "ilppu" => ["pupil"], "bblos" => ["blobs"],
      "adipr" => ["rapid"], "illps" => ["pills", "spill"], "aqsuy" => ["quays"],
      "adeks" => ["asked"], "dfilu" => ["fluid"], "cekrw" => ["wreck"],
      "aghns" => ["gnash", "hangs"], "asssy" => ["sassy"], "ekpsy" => ["pesky"],
      "ailrv" => ["viral", "rival"], "cnory" => ["corny", "crony"],
      "aginp" => ["aping"], "almru" => ["mural"], "aaprt" => ["apart"],
      "bgguy" => ["buggy"], "inors" => ["irons"], "dlluy" => ["dully"],
      "eenss" => ["sense"], "ginsw" => ["swing", "wings"], "ffstu" => ["stuff"],
      "orstt" => ["trots"], "begnu" => ["begun"], "bkoor" => ["brook"],
      "instt" => ["stint", "tints"], "addde" => ["added"], "films" => ["films"],
      "acknr" => ["crank"], "astty" => ["tasty"], "emost" => ["smote", "tomes"],
      "aimss" => ["amiss"], "llort" => ["troll"], "eistx" => ["exits", "exist"],
      "bikln" => ["blink"], "aglns" => ["slang"], "blnoy" => ["nobly"],
      "acegy" => ["cagey"], "ciimm" => ["mimic"], "clnoo" => ["colon"],
      "aceps" => ["capes", "paces", "space"], "ceitw" => ["twice"],
      "anstw" => ["wants"], "ackqu" => ["quack"], "ginow" => ["owing"],
      "aglnr" => ["gnarl"], "moott" => ["motto"], "adopt" => ["adopt"],
      "deims" => ["dimes"], "bdeln" => ["blend"],
      "eoprs" => ["pores", "ropes", "spore", "prose"], "ahppy" => ["happy"],
      "aehst" => ["haste", "hates", "heats"], "fllsu" => ["fulls"],
      "ailny" => ["inlay"], "aalmr" => ["alarm"], "cijuy" => ["juicy"],
      "lopss" => ["slops"], "morsw" => ["worms"], "deips" => ["spied"],
      "adlly" => ["dally"], "bprsu" => ["burps"], "adegp" => ["gaped", "paged"],
      "adnss" => ["sands"], "abiss" => ["basis"], "anpst" => ["pants"],
      "emptt" => ["tempt"], "dhoos" => ["hoods"], "epsty" => ["types"],
      "eehls" => ["heels"], "mppsu" => ["pumps"], "ffijy" => ["jiffy"],
      "denrt" => ["trend"], "aehlt" => ["lathe"], "ghnot" => ["thong"],
      "bchit" => ["bitch"], "acrtt" => ["tract"], "aglos" => ["goals"],
      "agkwy" => ["gawky"], "gilno" => ["lingo"], "achop" => ["poach"],
      "dmpuy" => ["dumpy"], "fglos" => ["flogs", "golfs"], "cello" => ["cello"],
      "kklsu" => ["skulk"], "ehlms" => ["helms"], "ceiov" => ["voice"],
      "alpss" => ["slaps"], "oopst" => ["stoop"], "ailms" => ["mails"],
      "ccimo" => ["comic"], "amnor" => ["manor", "roman"],
      "abekr" => ["baker", "brake", "break"], "aersy" => ["years"],
      "acegs" => ["cages"], "eflsu" => ["flues", "fuels"],
      "beest" => ["beets", "beset"], "deens" => ["dense", "needs"],
      "eiltt" => ["title"], "aehsv" => ["haves", "shave"], "fkors" => ["forks"],
      "chinw" => ["winch"], "deguy" => ["guyed"], "ikmps" => ["skimp"],
      "imrst" => ["trims"], "achmo" => ["macho"], "acelm" => ["camel"],
      "alnnu" => ["annul"], "lmssu" => ["slums"], "adegz" => ["gazed"],
      "ddemo" => ["domed"], "chmsu" => ["chums"], "defix" => ["fixed"],
      "ckstu" => ["tucks", "stuck"], "enopy" => ["peony"], "eeksw" => ["weeks"],
      "eesvx" => ["vexes"], "akors" => ["okras"], "eforz" => ["froze"],
      "dgino" => ["doing"], "biknr" => ["brink"], "almqu" => ["qualm"],
      "fhlsu" => ["flush"], "adeps" => ["spade"], "ehmos" => ["homes"],
      "glosw" => ["glows"], "imsst" => ["mists"], "afmos" => ["foams"],
      "hinnt" => ["ninth"], "ciprs" => ["crisp"], "ipssw" => ["wisps"],
      "prsuy" => ["syrup"], "orstw" => ["worst"], "ehiss" => ["shies"],
      "enswy" => ["newsy"], "eiisv" => ["ivies"], "besst" => ["bests"],
      "acgor" => ["cargo"], "abcis" => ["basic"], "aostt" => ["toast"],
      "cerru" => ["recur"], "npsuu" => ["sunup"], "oorrt" => ["rotor"],
      "derry" => ["dryer"], "flosw" => ["fowls", "wolfs", "flows"],
      "bertu" => ["brute", "rebut"], "acess" => ["cases"], "eqruy" => ["query"],
      "efnrs" => ["ferns"], "borsw" => ["brows"], "ehrsy" => ["shyer"],
      "dnosu" => ["sound"], "prrsu" => ["purrs"], "blruy" => ["burly"],
      "elorv" => ["lover"], "eiprr" => ["riper"], "aadrw" => ["award"],
      "bknos" => ["knobs"], "bddeo" => ["boded"], "bglos" => ["blogs"],
      "adlsy" => ["sadly"], "cefhs" => ["chefs"], "deemt" => ["meted"],
      "dfors" => ["fords"], "cchku" => ["chuck"], "afhls" => ["flash"],
      "denpu" => ["upend"], "beeil" => ["belie"], "ceklr" => ["clerk"],
      "aclls" => ["calls"], "hikrs" => ["shirk"], "denru" => ["nuder", "under"],
      "emrsu" => ["serum"], "adost" => ["toads"], "ahost" => ["oaths"],
      "adeis" => ["aides", "aside", "ideas"], "eirtv" => ["rivet"],
      "abrst" => ["brats"], "befit" => ["befit"], "acfst" => ["facts"],
      "abeks" => ["beaks", "bakes"], "hmotu" => ["mouth"], "psttu" => ["putts"],
      "adely" => ["delay"], "kllno" => ["knoll"], "ehost" => ["ethos", "those"],
      "delor" => ["older"], "aflst" => ["flats"], "abdor" => ["broad", "board"],
      "ffity" => ["fifty"], "abgrs" => ["brags", "garbs", "grabs"],
      "instw" => ["twins"], "dehir" => ["hired"], "hrstu" => ["hurts"],
      "aegsu" => ["usage"], "adiir" => ["radii"], "achnr" => ["ranch"],
      "gimry" => ["grimy"], "bcesu" => ["cubes"], "effor" => ["offer"],
      "ceisv" => ["vices"], "eepru" => ["puree"], "dhstu" => ["thuds"],
      "aefss" => ["safes"], "adekr" => ["raked"], "bllsu" => ["bulls"],
      "deilp" => ["piled", "plied"], "dnosw" => ["downs"], "glstu" => ["gluts"],
      "enovy" => ["envoy"], "eefrv" => ["fever"], "jmpuy" => ["jumpy"],
      "pssuy" => ["pussy"], "aclns" => ["clans"], "adrty" => ["tardy"],
      "bdelu" => ["blued"], "efhrs" => ["fresh"], "ffhit" => ["fifth"],
      "achls" => ["clash"], "forty" => ["forty"], "deelv" => ["delve"],
      "inpss" => ["snips", "spins"], "aclss" => ["class"], "deesy" => ["seedy"],
      "adinr" => ["drain"], "aeknt" => ["taken"], "cmsuu" => ["mucus"],
      "cdhor" => ["chord"], "aprss" => ["rasps", "spars"], "eequu" => ["queue"],
      "einps" => ["penis", "pines", "snipe", "spine"], "ehlos" => ["holes"],
      "aegnt" => ["agent"], "cckos" => ["cocks"], "ceorv" => ["cover"],
      "gilns" => ["sling"], "aaort" => ["aorta"], "oprxy" => ["proxy"],
      "adehy" => ["hayed", "heady"], "eegmr" => ["merge"], "dills" => ["dills"],
      "bdens" => ["bends"], "ckoss" => ["socks"], "eoosz" => ["oozes"],
      "irstw" => ["writs", "wrist"], "chhnu" => ["hunch"], "ablmu" => ["album"],
      "arsst" => ["stars"], "chknu" => ["chunk"], "clnow" => ["clown"],
      "abder" => ["bared", "beard", "bread"], "ehirt" => ["their"],
      "filos" => ["foils"], "eirtw" => ["write"], "aehms" => ["shame"],
      "deilv" => ["devil", "lived"], "ahrst" => ["harts", "trash"],
      "mnoor" => ["moron"], "aflot" => ["aloft", "float"], "ampsw" => ["swamp"],
      "einsw" => ["sinew", "swine", "wines"],
      "deirs" => ["sired", "dries", "rides"], "dmrsu" => ["drums"],
      "bmoos" => ["booms", "bosom"], "beiks" => ["bikes"], "hloss" => ["slosh"],
      "enovw" => ["woven"], "aacco" => ["cacao"], "cdehi" => ["chide"],
      "ccehk" => ["check"], "eelst" => ["sleet", "steel"], "chops" => ["chops"],
      "alnst" => ["slant"], "alpsy" => ["plays"], "dhlos" => ["holds"],
      "eipsw" => ["swipe", "wipes"], "chimp" => ["chimp"], "destu" => ["duets"],
      "dnopu" => ["pound"], "dilos" => ["idols", "solid"], "dertu" => ["trued"],
      "aopss" => ["soaps"], "allot" => ["allot"], "achpt" => ["patch"],
      "agnss" => ["sangs", "snags"], "bknsu" => ["bunks"], "aeguv" => ["vague"],
      "ehors" => ["shore", "horse"], "aegmn" => ["mange"], "ddeor" => ["odder"],
      "cdrsu" => ["curds"], "adeir" => ["aired"], "afisw" => ["waifs"],
      "aehlr" => ["haler"], "imnor" => ["minor"], "bnoos" => ["boons"],
      "agnrt" => ["grant"], "ehosv" => ["shove"], "cdeor" => ["cored"],
      "illsy" => ["silly"], "aails" => ["alias"], "einsv" => ["veins", "vines"],
      "aeprt" => ["apter", "taper"], "eprsy" => ["preys", "pyres"],
      "hills" => ["hills"], "acmmo" => ["comma"], "efils" => ["files", "flies"],
      "aglow" => ["aglow"], "aemrs" => ["mares", "reams", "smear"],
      "efilt" => ["filet"], "abcss" => ["scabs"], "ekssw" => ["skews"],
      "dillr" => ["drill"], "bossy" => ["bossy"], "iklss" => ["silks"],
      "chikn" => ["chink"], "bersw" => ["brews"], "beelr" => ["rebel"],
      "eestw" => ["weest", "sweet"], "horsu" => ["hours"], "eemrt" => ["meter"],
      "achkl" => ["chalk"], "aeess" => ["eases"], "osstw" => ["stows"],
      "efirv" => ["fiver"], "eenrv" => ["nerve", "never"], "cchou" => ["couch"],
      "achor" => ["roach"], "efikn" => ["knife"], "admps" => ["damps"],
      "adefr" => ["fared"], "korsw" => ["works"], "aekly" => ["leaky"],
      "aginw" => ["awing"], "dghou" => ["dough"], "ggino" => ["going"],
      "aamms" => ["mamas"], "floor" => ["floor"], "apsst" => ["pasts", "spats"],
      "aakrt" => ["karat"], "agrsu" => ["sugar"], "deegr" => ["edger", "greed"],
      "acffh" => ["chaff"], "imnst" => ["mints"], "agiln" => ["align"],
      "diqsu" => ["squid"], "irsuv" => ["virus"], "aopsy" => ["soapy"],
      "aeehv" => ["heave"], "deloy" => ["yodel"], "deirt" => ["tired", "tried"],
      "ddloy" => ["oddly"], "eirss" => ["sires", "rises"], "ffpsu" => ["puffs"],
      "kmnos" => ["monks"], "gppuy" => ["guppy"], "acitt" => ["attic", "tacit"],
      "acimn" => ["manic"], "eilnv" => ["liven"], "achms" => ["chasm"],
      "acost" => ["tacos", "coast", "coats"], "errsu" => ["surer"],
      "deers" => ["reeds"], "loost" => ["loots", "stool", "tools"],
      "emstu" => ["mutes"], "chnpu" => ["punch"], "bgruy" => ["rugby"],
      "adesv" => ["saved"], "aagmm" => ["gamma"], "dginr" => ["grind"],
      "delru" => ["lured", "ruled"], "enors" => ["snore"], "lnoos" => ["loons"],
      "acemo" => ["cameo"], "denrs" => ["rends"], "aissv" => ["visas"],
      "benoy" => ["ebony"], "adikn" => ["kinda"], "adddy" => ["daddy"],
      "akprs" => ["spark", "parks"], "adevw" => ["waved"], "acjks" => ["jacks"],
      "cekns" => ["necks"], "chins" => ["chins"], "acdel" => ["laced"],
      "cnotu" => ["count"], "erstw" => ["strew", "wrest"], "cfkor" => ["frock"],
      "aehns" => ["ashen"], "aclmp" => ["clamp"], "flotu" => ["flout"],
      "biltu" => ["built"], "eirtu" => ["uteri"], "orrsy" => ["sorry"],
      "ditty" => ["ditty"], "adknr" => ["drank"], "deimm" => ["mimed"],
      "aaegl" => ["algae"], "ilopt" => ["pilot"], "aclov" => ["vocal"],
      "aekqu" => ["quake"], "fgooy" => ["goofy"], "dmmuy" => ["dummy"],
      "cckor" => ["crock"], "elptu" => ["letup"], "ceinw" => ["wince"],
      "afknr" => ["frank"], "aehlw" => ["whale"], "dgnsu" => ["dungs"],
      "dehop" => ["hoped"], "deity" => ["deity"], "cekos" => ["cokes"],
      "cefls" => ["clefs"], "giilv" => ["vigil"], "eopss" => ["poses"],
      "emort" => ["metro"], "afgls" => ["flags"], "blosw" => ["bowls", "blows"],
      "efirr" => ["rifer"], "ceert" => ["erect"], "imssw" => ["swims"],
      "deeps" => ["deeps", "speed"], "amsst" => ["masts"], "eekln" => ["kneel"],
      "bdegu" => ["budge", "debug"], "ceepr" => ["crepe", "creep"],
      "cchin" => ["cinch"], "cdios" => ["disco"], "deipp" => ["piped"],
      "almny" => ["manly"], "lossw" => ["slows"], "emrtu" => ["muter"],
      "abegr" => ["barge"], "adimt" => ["admit"], "hmsty" => ["myths"],
      "cells" => ["cells"], "acnst" => ["scant"], "ehinw" => ["whine"],
      "acprs" => ["carps", "scrap"], "abdnr" => ["brand"],
      "adeor" => ["adore", "oared"], "ahirs" => ["hairs"],
      "cekps" => ["pecks", "speck"], "deotv" => ["voted"], "ikpss" => ["skips"],
      "ceilm" => ["clime"], "cdors" => ["cords"], "finty" => ["nifty"],
      "cikls" => ["licks", "slick"], "amnos" => ["mason", "moans"],
      "koors" => ["rooks"], "deilr" => ["idler", "riled"], "aefmr" => ["frame"],
      "efklu" => ["fluke"], "ciopt" => ["optic", "topic"], "moost" => ["moots"],
      "lsstu" => ["lusts", "sluts"], "gnorw" => ["grown", "wrong"],
      "acerr" => ["racer"], "bilps" => ["blips"], "enoos" => ["noose"],
      "hoopw" => ["whoop"], "aelno" => ["alone"], "aimox" => ["axiom"],
      "chort" => ["torch"], "efssu" => ["fuses"], "cinot" => ["tonic"],
      "lostu" => ["lotus"], "dnouw" => ["wound"], "emoos" => ["moose"],
      "ffnsu" => ["snuff"], "bdeir" => ["bride"], "eehmt" => ["theme"],
      "acdek" => ["caked"], "bnosu" => ["bonus"], "ipsst" => ["spits"],
      "aejns" => ["jeans"], "ddeis" => ["sided"], "cfhil" => ["filch"],
      "anprw" => ["prawn"], "aertt" => ["treat"], "eorsw" => ["swore", "worse"],
      "gnrsu" => ["rungs"], "dnops" => ["ponds"], "abbty" => ["tabby"],
      "ikrst" => ["skirt"], "erssu" => ["ruses", "users"], "ccilo" => ["colic"],
      "adees" => ["eased"], "adgnr" => ["grand"], "ehmty" => ["thyme"],
      "blluy" => ["bully"], "inssu" => ["sinus"], "egopr" => ["grope"],
      "aderv" => ["raved"], "efhls" => ["flesh", "shelf"], "eenrs" => ["sneer"],
      "eervv" => ["verve"], "aeglv" => ["gavel"], "errwy" => ["wryer"],
      "cnoor" => ["croon"], "aelnv" => ["navel"], "deirv" => ["diver", "drive"],
      "alsuu" => ["usual"], "hklsu" => ["hulks"], "bsttu" => ["butts"],
      "eortw" => ["tower", "wrote"],
      "aelps" => ["lapse", "leaps", "pales", "peals", "pleas"],
      "elosu" => ["louse"], "abcor" => ["cobra"],
      "eersv" => ["sever", "veers", "verse", "serve"], "ilops" => ["spoil"],
      "elnov" => ["novel"], "adlou" => ["aloud"], "bloss" => ["slobs"],
      "deiks" => ["skied"], "flnow" => ["flown"], "ikkos" => ["kiosk"],
      "adepw" => ["pawed"], "boost" => ["boost", "boots"], "filps" => ["flips"],
      "bells" => ["bells"], "aorss" => ["soars"], "fggoy" => ["foggy"],
      "adiry" => ["dairy", "diary"], "cilos" => ["coils"], "ggosy" => ["soggy"],
      "eipty" => ["piety"], "bdotu" => ["doubt"], "clruy" => ["curly"],
      "eggou" => ["gouge"], "deott" => ["toted"], "diknr" => ["drink"],
      "dehrs" => ["herds", "shred"], "erttu" => ["utter"], "afgrt" => ["graft"],
      "acerz" => ["craze"], "nostu" => ["snout"], "abkrs" => ["barks"],
      "aakpr" => ["parka"], "hiksw" => ["whisk"], "aeils" => ["aisle"],
      "acehr" => ["reach"], "deems" => ["deems"], "aemtt" => ["matte"],
      "hlssu" => ["slush"], "eirst" => ["rites", "tiers", "tires", "tries"],
      "ceory" => ["coyer"], "adlrs" => ["lards"], "eprtu" => ["erupt"],
      "efgor" => ["forge"], "admns" => ["damns"], "diloy" => ["doily"],
      "cglnu" => ["clung"], "eegly" => ["elegy"], "gilrs" => ["girls"],
      "arstw" => ["warts", "straw"], "deiln" => ["lined"], "bfflu" => ["bluff"],
      "knstu" => ["stunk"], "aenrv" => ["raven"], "aehnv" => ["haven"],
      "bcmru" => ["crumb"], "aefst" => ["fates", "feast", "feats"],
      "adntu" => ["daunt"], "filnt" => ["flint"], "aimmx" => ["maxim"],
      "abbey" => ["abbey"], "dejko" => ["joked"], "defsu" => ["feuds", "fused"],
      "hossw" => ["shows"], "bikrs" => ["brisk"], "dnnou" => ["dunno"],
      "hilly" => ["hilly"], "ackln" => ["clank"], "ikrsy" => ["risky"],
      "eenst" => ["teens", "tense"], "eilss" => ["isles"], "ilmtu" => ["multi"],
      "abdrs" => ["bards", "drabs"], "cffsu" => ["cuffs", "scuff"],
      "aiopt" => ["patio"], "agntu" => ["gaunt"], "enstt" => ["tents"],
      "eehrt" => ["ether", "there", "three"], "aegsz" => ["gazes"],
      "nrstu" => ["runts", "turns"], "deipw" => ["wiped"], "glmoo" => ["gloom"],
      "horst" => ["short"], "addef" => ["faded"], "anpsy" => ["pansy"],
      "filst" => ["flits", "lifts"], "abdls" => ["balds"], "amory" => ["mayor"],
      "frstu" => ["turfs"], "aeglm" => ["gleam"], "bmoux" => ["buxom"],
      "afiln" => ["final"], "eegrt" => ["greet"], "giloo" => ["igloo"],
      "enoss" => ["noses"], "aefly" => ["leafy"], "gnruw" => ["wrung"],
      "hoswy" => ["showy"], "fssuy" => ["fussy"], "eefrr" => ["freer", "refer"],
      "eehps" => ["sheep"], "altwz" => ["waltz"],
      "eerst" => ["reset", "steer", "terse", "trees"], "deinr" => ["diner"],
      "ainrs" => ["rains"],
      "aeprs" => ["pares", "pears", "rapes", "reaps", "spear", "parse", "spare"],
      "hinst" => ["thins", "hints"], "aceks" => ["cakes"], "filrt" => ["flirt"],
      "lrssu" => ["slurs"], "aegrz" => ["graze"], "imsty" => ["misty"],
      "afhst" => ["shaft"], "aegnr" => ["anger", "range"], "ceejt" => ["eject"],
      "afsst" => ["fasts"], "abggy" => ["baggy"], "eepps" => ["peeps"],
      "eeflt" => ["fleet"], "beers" => ["beers"], "aelns" => ["lanes", "leans"],
      "bilmp" => ["blimp"], "klsuy" => ["sulky"], "degls" => ["gelds"],
      "ahikk" => ["khaki"], "filly" => ["filly"], "eejrs" => ["jeers"],
      "enstv" => ["vents"], "aeppr" => ["paper"],
      "elops" => ["lopes", "poles", "slope"], "aegmo" => ["omega"],
      "aallm" => ["llama"], "allsw" => ["walls"], "addny" => ["dandy"],
      "ooprt" => ["troop"], "dgooy" => ["goody"], "rsttu" => ["strut", "trust"],
      "emorv" => ["mover"], "aelrv" => ["ravel"], "gnsuw" => ["swung"],
      "eehns" => ["sheen"], "loswy" => ["yowls"], "ainrt" => ["train"],
      "deopy" => ["dopey"], "fgors" => ["frogs"], "deglu" => ["glued"],
      "klnsu" => ["slunk"], "egooy" => ["gooey"], "ceelt" => ["elect"],
      "ekopr" => ["poker"], "aerst" => ["stare", "tears", "rates"],
      "alops" => ["opals"], "abdny" => ["bandy"], "eloss" => ["soles", "loses"],
      "oostt" => ["toots"], "delmo" => ["model"], "deipr" => ["pried", "pride"],
      "agntw" => ["twang"], "inory" => ["irony"], "acirv" => ["vicar"],
      "acmrs" => ["crams", "scram"], "dehor" => ["horde"],
      "delop" => ["loped", "poled"], "aekps" => ["peaks", "speak"],
      "asstw" => ["swats"], "glory" => ["glory"], "klrsu" => ["lurks"],
      "alnot" => ["talon", "tonal"], "clotu" => ["clout"],
      "almor" => ["molar", "moral"], "jlost" => ["jolts"], "delno" => ["olden"],
      "enstu" => ["tunes", "unset"], "cllsu" => ["culls"], "ceehl" => ["leech"],
      "mmruy" => ["rummy"], "dknsu" => ["dunks"], "ehlps" => ["helps"],
      "ceils" => ["slice"], "flluy" => ["fully"], "floru" => ["flour"],
      "bcilm" => ["climb"], "amrst" => ["marts", "smart"], "aesuv" => ["suave"],
      "denuu" => ["undue"], "cnors" => ["corns", "scorn"], "bbdee" => ["ebbed"],
      "degnu" => ["nudge"], "llowy" => ["lowly"],
      "aegln" => ["angel", "glean", "angle"], "aintt" => ["taint"],
      "inpst" => ["pints"], "ggmuy" => ["muggy"], "aestx" => ["taxes"],
      "ginrs" => ["grins", "rings"], "aefks" => ["fakes"], "aalru" => ["aural"],
      "dmnou" => ["mound"], "diosv" => ["voids"], "egors" => ["gores", "ogres"],
      "ackty" => ["tacky"], "dfins" => ["finds"], "benor" => ["borne"],
      "elotw" => ["towel"], "aadls" => ["salad"], "dfoos" => ["foods"],
      "beglo" => ["globe"], "dinrs" => ["rinds"], "afkln" => ["flank"],
      "ellst" => ["tells"], "cdksu" => ["ducks"], "hosst" => ["hosts", "shots"],
      "aehss" => ["ashes"], "acdeh" => ["ached"],
      "aelry" => ["layer", "relay", "early"], "cssty" => ["cysts"],
      "deily" => ["yield"], "delow" => ["lowed"], "aefhs" => ["sheaf"],
      "fillr" => ["frill"], "acgln" => ["clang"], "eisst" => ["sites"],
      "aadpt" => ["adapt"], "cdeoo" => ["cooed"], "eeilx" => ["exile"],
      "adrsw" => ["wards", "draws"], "dorwy" => ["dowry", "rowdy", "wordy"],
      "ckoos" => ["cooks"], "aabck" => ["aback"], "eghin" => ["hinge", "neigh"],
      "abrsy" => ["brays"], "bgiot" => ["bigot"], "chlmu" => ["mulch"],
      "elpsy" => ["yelps"], "achst" => ["chats"], "eostt" => ["totes"],
      "jmpsu" => ["jumps"], "aarsu" => ["auras"], "beoos" => ["oboes"],
      "llmsu" => ["mulls"], "ckors" => ["corks", "rocks"], "almst" => ["malts"],
      "ehorv" => ["hover"], "eervy" => ["every"], "eekss" => ["seeks"],
      "aelss" => ["seals", "sales"], "adeev" => ["evade"], "eepss" => ["seeps"],
      "degru" => ["urged"], "acrss" => ["scars", "crass"], "delov" => ["loved"],
      "einns" => ["nines"], "befir" => ["brief"],
      "adehs" => ["ashed", "shade", "heads"], "ablss" => ["slabs"],
      "forsu" => ["fours"], "ceprt" => ["crept"], "ahlos" => ["halos", "shoal"],
      "aeent" => ["eaten"], "aammm" => ["mamma"], "acels" => ["laces", "scale"],
      "chnru" => ["churn"], "ddinu" => ["undid"], "egoos" => ["goose"],
      "lstuy" => ["lusty"], "ahlot" => ["loath"], "abefl" => ["fable"],
      "ehmry" => ["rhyme"], "eensu" => ["ensue"], "acdrs" => ["cards"],
      "ailsw" => ["wails"], "bjmou" => ["jumbo"], "clstu" => ["cults"],
      "acest" => ["caste"], "apssy" => ["spays"], "mnors" => ["morns", "norms"],
      "aknpr" => ["prank"], "aeltv" => ["valet"], "demoo" => ["mooed"],
      "adejw" => ["jawed"], "efinr" => ["finer", "infer"], "chips" => ["chips"],
      "gorss" => ["gross"], "eelpx" => ["expel"], "ikkny" => ["kinky"],
      "afstw" => ["wafts"], "deikr" => ["irked"], "ilost" => ["toils"],
      "isssy" => ["sissy"], "ffins" => ["sniff"], "apsty" => ["pasty"],
      "beglu" => ["bugle", "bulge"], "achrs" => ["chars", "crash"],
      "bcirs" => ["cribs"], "ekost" => ["stoke"], "ahils" => ["hails"],
      "cdeit" => ["edict", "cited"], "acdny" => ["candy"], "gopru" => ["group"],
      "ggnos" => ["gongs"], "abbrs" => ["barbs"], "aeels" => ["easel", "lease"],
      "ghiss" => ["sighs"], "eopst" => ["poets"], "aeegl" => ["eagle"],
      "alsst" => ["salts", "slats", "lasts"], "bimrs" => ["brims"],
      "knrtu" => ["trunk"], "aerrs" => ["rares", "rears"], "bostu" => ["bouts"],
      "dikns" => ["kinds"], "aegss" => ["gases", "sages"], "aekms" => ["makes"],
      "dgils" => ["gilds"], "flost" => ["lofts"],
      "cdlos" => ["clods", "colds", "scold"], "adepy" => ["payed"],
      "oprst" => ["ports", "sport"], "ceein" => ["niece"], "defns" => ["fends"],
      "acder" => ["arced", "cedar", "cared", "raced"], "ddepu" => ["duped"],
      "ginty" => ["tying"], "eehrw" => ["where"], "abdel" => ["baled", "blade"],
      "aaitw" => ["await"], "eghit" => ["eight"], "abstu" => ["tubas"],
      "aellp" => ["lapel"], "deilo" => ["oiled"], "dsstu" => ["dusts", "studs"],
      "esttx" => ["texts"], "demov" => ["moved"], "forst" => ["forts", "frost"],
      "efhit" => ["thief"], "fnorw" => ["frown"], "abors" => ["boars"],
      "bilmo" => ["limbo"], "osstu" => ["ousts"], "degiu" => ["guide"],
      "eekrs" => ["reeks"], "fmoru" => ["forum"], "abhor" => ["abhor"],
      "ackss" => ["casks", "sacks"], "biort" => ["orbit"], "eemny" => ["enemy"],
      "ginvy" => ["vying"], "deert" => ["treed", "deter"], "errtu" => ["truer"],
      "beist" => ["bites"], "deewy" => ["weedy"], "himrt" => ["mirth"],
      "alpst" => ["splat"], "abjno" => ["banjo"], "eeprt" => ["peter"],
      "ekmos" => ["smoke"], "aapps" => ["papas"], "dimns" => ["minds"],
      "bsstu" => ["busts", "stubs"], "cilry" => ["lyric"], "dilsw" => ["wilds"],
      "bklsu" => ["bulks"], "adily" => ["daily"], "eehtt" => ["teeth"],
      "enopr" => ["prone"], "celos" => ["close"], "ailps" => ["pails"],
      "ekosy" => ["yokes"], "bcikr" => ["brick"], "orsuy" => ["yours"],
      "ffrsu" => ["ruffs"], "achos" => ["chaos"], "dhimu" => ["humid"],
      "elrsu" => ["lures", "rules"], "ccklu" => ["cluck"],
      "anpss" => ["snaps", "spans"], "eggor" => ["gorge"], "anppy" => ["nappy"],
      "enpru" => ["prune"], "ainpt" => ["paint"], "hopss" => ["shops"],
      "cehtu" => ["chute"], "cdeer" => ["creed"], "afkls" => ["flask"],
      "corsu" => ["scour"], "achmr" => ["charm", "march"],
      "anstu" => ["aunts", "tunas"], "eemrs" => ["meres"], "dhins" => ["hinds"],
      "dehlo" => ["holed"], "ilpst" => ["split"], "aeflr" => ["flare"],
      "cerst" => ["crest"], "boort" => ["robot"], "efrry" => ["ferry"],
      "adejs" => ["jades"], "aamor" => ["aroma"], "aelrx" => ["laxer", "relax"],
      "prsuu" => ["usurp"], "dfnsu" => ["funds"], "imnsu" => ["minus"],
      "diiot" => ["idiot"], "dhitw" => ["width"], "mnoos" => ["moons"],
      "histx" => ["sixth"], "aagss" => ["sagas"], "denor" => ["drone"],
      "delos" => ["doles", "soled"], "aknsy" => ["yanks"], "dpssu" => ["spuds"],
      "acgrs" => ["crags"], "cefkl" => ["fleck"], "cehop" => ["epoch"],
      "bbhoy" => ["hobby"], "losuy" => ["lousy"], "acetx" => ["exact"],
      "bnorw" => ["brown"], "emnoy" => ["money"], "diott" => ["ditto"],
      "hnort" => ["thorn", "north"], "benos" => ["bones"], "efgir" => ["grief"],
      "bnrtu" => ["brunt", "burnt"],
      "aenrs" => ["nears", "saner", "snare", "earns"], "aekrw" => ["wreak"],
      "adnrw" => ["drawn"], "bblsu" => ["bulbs"], "beinr" => ["brine"],
      "ffhuy" => ["huffy"], "ddmuy" => ["muddy"], "aeruz" => ["azure"],
      "floss" => ["floss"], "ehstw" => ["whets"], "abort" => ["abort"],
      "eilns" => ["lines"], "innty" => ["tinny"], "eessy" => ["yeses"],
      "cikqu" => ["quick"], "adiou" => ["audio"], "aehny" => ["hyena"],
      "abelr" => ["abler", "blare"], "aegms" => ["games"],
      "ekops" => ["pokes", "spoke"], "agost" => ["goats", "togas"],
      "iknsw" => ["winks"], "blost" => ["blots", "bolts"], "eilrs" => ["riles"],
      "eirsz" => ["sizer"], "delsw" => ["welds"], "ghint" => ["night", "thing"],
      "aapst" => ["pasta"], "egorv" => ["grove"], "abiil" => ["alibi"],
      "fhilt" => ["filth"], "enosv" => ["ovens"], "ddeeg" => ["edged"],
      "delsu" => ["duels"], "cehrt" => ["retch"], "adhns" => ["hands"],
      "llost" => ["tolls"], "chinp" => ["pinch"], "ghrsu" => ["shrug"],
      "nostw" => ["towns"], "aclsy" => ["scaly"], "cinru" => ["incur"],
      "hlloy" => ["holly"], "defin" => ["fiend", "fined"], "jlloy" => ["jolly"],
      "deosz" => ["dozes"], "aegsw" => ["wages"], "acceh" => ["cache"],
      "acckr" => ["crack"], "cosst" => ["costs"], "aimms" => ["maims"],
      "adgos" => ["goads"], "egnst" => ["gents"], "bdeow" => ["bowed"],
      "mstuy" => ["musty"], "ceorw" => ["cower"], "accit" => ["cacti"],
      "aegpr" => ["grape", "pager"], "lllsu" => ["lulls"], "aklnp" => ["plank"],
      "deelu" => ["elude"], "eoqtu" => ["quote"], "efhty" => ["hefty"],
      "ennpy" => ["penny"], "cdeks" => ["decks"], "dlors" => ["lords"],
      "acflo" => ["focal"], "elrsy" => ["lyres"], "bdeis" => ["bides"],
      "diprs" => ["drips"], "dlorw" => ["world"], "aansu" => ["sauna"],
      "dgpuy" => ["pudgy"], "ehmoy" => ["homey"], "ackkn" => ["knack"],
      "adelp" => ["paled", "plead", "pedal"], "dellw" => ["dwell"],
      "eirrv" => ["river"], "bchot" => ["botch"], "koops" => ["spook"],
      "epstw" => ["swept"], "ahlls" => ["halls", "shall"], "diyzz" => ["dizzy"],
      "aborv" => ["bravo"], "bdilu" => ["build"], "dehiv" => ["hived"],
      "asttw" => ["watts"], "aelrs" => ["earls", "reals", "laser"],
      "deglo" => ["ogled", "lodge"], "enorw" => ["owner"], "cdkos" => ["docks"],
      "eeepv" => ["peeve"], "cdlou" => ["cloud", "could"], "hlmpy" => ["lymph"],
      "attty" => ["tatty"], "blmpu" => ["plumb"], "dehno" => ["honed"],
      "eissw" => ["wises"], "ekpry" => ["perky"], "nnruy" => ["runny"],
      "glpsu" => ["gulps", "plugs"], "ffmsu" => ["muffs"], "agpss" => ["gasps"],
      "adlmo" => ["modal"], "aditu" => ["audit"], "aestw" => ["sweat", "waste"],
      "aelmp" => ["maple", "ample"], "iknps" => ["pinks"], "elmot" => ["motel"],
      "hnosw" => ["shown"], "ahsty" => ["hasty"], "aegil" => ["agile"],
      "adilp" => ["plaid"], "eginr" => ["reign"], "deiov" => ["video"],
      "eilrv" => ["viler", "liver"], "aegst" => ["gates", "stage"],
      "aelvv" => ["valve"], "eefrs" => ["reefs", "frees"], "eellv" => ["level"],
      "errty" => ["retry"], "bdetu" => ["debut", "tubed"], "egimm" => ["gimme"],
      "acefs" => ["faces"], "bnnuy" => ["bunny"], "aehtw" => ["wheat"],
      "chksu" => ["shuck"], "cehwy" => ["chewy"], "bginr" => ["bring"],
      "efhtt" => ["theft"], "hnssu" => ["shuns"], "afloo" => ["aloof"],
      "achpr" => ["parch"], "deotw" => ["towed"], "hissw" => ["swish"],
      "adnst" => ["stand"], "ghist" => ["sight"], "noosw" => ["swoon"],
      "lossu" => ["souls"], "abdei" => ["abide"], "bbeir" => ["bribe"],
      "belsu" => ["blues"], "belss" => ["bless"], "aekrt" => ["taker"],
      "iknss" => ["skins", "sinks"], "ailns" => ["slain", "nails", "snail"],
      "ghimt" => ["might"], "deeux" => ["exude"], "dilmy" => ["dimly"],
      "cehsw" => ["chews"], "aceep" => ["peace"], "abhst" => ["baths"],
      "ioptv" => ["pivot"], "elovw" => ["vowel"], "deiox" => ["oxide"],
      "ilsst" => ["silts", "slits", "lists"], "egipr" => ["gripe"],
      "hoopt" => ["photo"], "adhry" => ["hardy"], "blmoo" => ["bloom"],
      "abkns" => ["banks"], "allow" => ["allow"], "aertv" => ["avert"],
      "antwy" => ["tawny"], "aekln" => ["ankle"], "deops" => ["dopes", "posed"],
      "ahrtw" => ["wrath"], "acenp" => ["pecan"], "mmtuy" => ["tummy"],
      "aadnp" => ["panda"], "bceeh" => ["beech"], "dioww" => ["widow"],
      "ellsw" => ["swell", "wells"], "efiry" => ["fiery"], "moory" => ["roomy"],
      "bcklo" => ["block"], "afgns" => ["fangs"], "ellms" => ["smell"],
      "aoqtu" => ["quota"], "demow" => ["mowed"], "adepv" => ["paved"],
      "bcrsu" => ["curbs", "scrub"], "aiost" => ["iotas"], "dgiir" => ["rigid"],
      "chiks" => ["hicks"], "fgoos" => ["goofs"], "diimo" => ["idiom"],
      "beijs" => ["jibes"], "ijnot" => ["joint"],
      "eekls" => ["keels", "leeks", "sleek"], "aeers" => ["erase"],
      "eorsz" => ["zeros"], "efort" => ["forte"], "looss" => ["solos"],
      "mopst" => ["stomp"], "eettw" => ["tweet"], "eeruv" => ["revue"],
      "deosv" => ["doves"], "derss" => ["dress"], "ceenp" => ["pence"],
      "enort" => ["tenor"], "aefrs" => ["fares", "fears", "safer"],
      "abnru" => ["urban"], "abemr" => ["amber"], "akoss" => ["soaks"],
      "eimrt" => ["remit", "timer", "merit"], "acnss" => ["scans"],
      "adehr" => ["hared", "heard"], "ccoru" => ["occur"], "dddeu" => ["duded"],
      "ahpst" => ["paths"], "crruy" => ["curry"], "hmpsu" => ["humps"],
      "adems" => ["dames"], "beert" => ["beret"],
      "cdeir" => ["riced", "cider", "cried"], "afoss" => ["sofas"],
      "achht" => ["hatch"], "agmtu" => ["gamut"], "giprs" => ["sprig", "grips"],
      "demtu" => ["muted"], "aberv" => ["brave"], "emsst" => ["stems"],
      "bdeip" => ["biped"], "belru" => ["bluer"], "aqrtu" => ["quart"],
      "cemos" => ["comes"], "ablms" => ["balms", "lambs"], "addel" => ["laded"],
      "adell" => ["ladle"], "cciny" => ["cynic"], "bclos" => ["blocs"],
      "gorsw" => ["grows"], "afhit" => ["faith"],
      "eilsv" => ["veils", "evils", "lives"], "hilst" => ["hilts"],
      "akmrs" => ["marks"], "beirt" => ["tribe"], "iiksw" => ["kiwis"],
      "clost" => ["clots", "colts"], "amors" => ["roams"], "himsw" => ["whims"],
      "imprs" => ["prism"], "bcciu" => ["cubic"], "ddowy" => ["dowdy"],
      "elosv" => ["loves", "solve"], "himst" => ["smith"], "aeirt" => ["irate"],
      "aehks" => ["shake"], "ejtty" => ["jetty"], "cefht" => ["fetch"],
      "eglnu" => ["lunge"], "acill" => ["lilac"], "abcht" => ["batch"],
      "eorrr" => ["error"], "eimov" => ["movie"], "bbeil" => ["bible"],
      "acdew" => ["cawed"], "abdek" => ["baked"], "deeor" => ["erode"],
      "innou" => ["union"], "arrty" => ["tarry"], "detuv" => ["duvet"],
      "efory" => ["foyer"], "deoty" => ["toyed"], "apssw" => ["wasps", "swaps"],
      "ehort" => ["other"], "aelly" => ["alley"], "ahknt" => ["thank"],
      "abens" => ["beans"], "hnors" => ["horns"], "eelry" => ["leery"],
      "eekns" => ["keens", "knees"], "foopr" => ["proof"], "aeilv" => ["alive"],
      "aahlp" => ["alpha"], "abcrs" => ["crabs"], "iilmt" => ["limit"],
      "eepst" => ["steep"], "osttu" => ["stout", "touts"],
      "ailrt" => ["trail", "trial"], "ipqsu" => ["quips"], "afill" => ["flail"],
      "ekprs" => ["perks"], "cdeis" => ["dices"], "gsstu" => ["gusts"],
      "bhsuy" => ["bushy"], "eefrw" => ["fewer"], "nosty" => ["stony"],
      "dmooy" => ["moody"], "ilqtu" => ["quilt"], "fgist" => ["gifts"],
      "adegm" => ["gamed"], "cddee" => ["ceded"], "aairs" => ["arias"],
      "oprsw" => ["prows"],
      "einrs" => ["reins", "resin", "rinse", "siren", "risen"],
      "enosz" => ["zones"], "biltz" => ["blitz"], "acenr" => ["crane"],
      "below" => ["bowel", "elbow", "below"], "dinwy" => ["windy"],
      "filmy" => ["filmy"], "ghilt" => ["light"], "ceosv" => ["coves"],
      "chotu" => ["touch"], "amrsw" => ["swarm", "warms"], "cdstu" => ["ducts"],
      "foosw" => ["woofs"], "deeny" => ["needy"], "egmno" => ["gnome"],
      "eeeir" => ["eerie"], "ampss" => ["spasm"], "hlpsu" => ["plush"],
      "abost" => ["boast", "boats"], "acklo" => ["cloak"], "aegll" => ["legal"],
      "hlrsu" => ["hurls"], "egmrs" => ["germs"], "aelmt" => ["metal"],
      "beosx" => ["boxes"], "dehis" => ["shied", "hides"], "deetw" => ["tweed"],
      "adors" => ["roads"], "dnowy" => ["downy"], "aknrs" => ["ranks"],
      "ceinr" => ["nicer"], "cesst" => ["sects"], "elotx" => ["extol"],
      "depsu" => ["dupes"], "ddeop" => ["doped"], "ehiks" => ["hikes"],
      "ddelo" => ["doled"], "aabet" => ["abate"], "afory" => ["foray"],
      "eprsu" => ["purse", "super"], "iorvy" => ["ivory"], "cehor" => ["chore"],
      "eostv" => ["stove", "votes"],
      "deils" => ["delis", "idles", "sidle", "slide"], "dehos" => ["hosed"],
      "aehtt" => ["theta"], "aaflt" => ["fatal"], "bdeoo" => ["booed"],
      "cgilo" => ["logic"], "dknru" => ["drunk"], "emrst" => ["terms"],
      "anrsw" => ["warns"], "acemr" => ["cream"], "nnosu" => ["nouns"],
      "losst" => ["slots"], "lnnoy" => ["nylon"], "almpy" => ["amply"],
      "beruy" => ["buyer"], "hrttu" => ["truth"], "bblru" => ["blurb"],
      "aemsu" => ["amuse"], "aestv" => ["stave"], "chopu" => ["pouch"],
      "deirw" => ["wired", "weird", "wider"], "aceft" => ["facet"],
      "adrsy" => ["yards"], "eortu" => ["outer", "route"], "adior" => ["radio"],
      "alppy" => ["apply"], "emops" => ["mopes", "poems"], "chity" => ["itchy"],
      "aaers" => ["areas"], "grsuu" => ["gurus"], "orssu" => ["sours"],
      "abils" => ["bails", "basil"], "glnsu" => ["slung", "lungs"],
      "cddei" => ["diced"], "gikns" => ["kings"], "aderz" => ["razed"],
      "agnno" => ["gonna"], "cimsu" => ["music"], "eersw" => ["sewer"],
      "ceehp" => ["cheep"], "ddeil" => ["idled"], "aeinv" => ["naive"],
      "hoott" => ["tooth"], "eiprw" => ["wiper"], "deerr" => ["erred"],
      "jknsu" => ["junks"], "aestt" => ["teats", "state", "taste"],
      "achrt" => ["chart"], "acdls" => ["scald"], "bdeor" => ["robed", "bored"],
      "eepsw" => ["weeps", "sweep"], "begin" => ["begin", "being"],
      "eehrs" => ["sheer"], "kmruy" => ["murky"], "fiyzz" => ["fizzy"],
      "gistw" => ["twigs"], "eilms" => ["limes", "slime", "miles", "smile"],
      "egikn" => ["eking"], "ckmos" => ["mocks", "smock"], "dflos" => ["folds"],
      "loops" => ["pools", "loops", "spool"], "eeisv" => ["sieve"],
      "delss" => ["sleds"], "ailrs" => ["lairs", "liars", "rails"],
      "cenos" => ["cones"], "deehw" => ["hewed"], "deegs" => ["edges"],
      "degir" => ["dirge", "ridge"], "fklos" => ["folks"], "ansuy" => ["unsay"],
      "bilss" => ["bliss"], "enost" => ["onset", "tones", "notes", "stone"],
      "deefs" => ["feeds"], "floos" => ["fools"], "blnow" => ["blown"],
      "defgu" => ["fudge"], "mnotu" => ["mount"], "acklu" => ["caulk"],
      "achks" => ["shack", "hacks"], "ahlss" => ["slash"], "abkln" => ["blank"],
      "aalrv" => ["larva"], "fistw" => ["swift"], "acees" => ["cease"],
      "chopr" => ["porch"], "aepst" => ["pates", "spate", "paste", "tapes"],
      "afrsy" => ["frays"], "cdees" => ["cedes"], "aklny" => ["lanky"],
      "adewx" => ["waxed"], "acnny" => ["canny"], "cffil" => ["cliff"],
      "firtu" => ["fruit"], "cglos" => ["clogs"], "eimns" => ["miens", "mines"],
      "ejsst" => ["jests"], "ackns" => ["snack"], "abdwy" => ["bawdy"],
      "ciksw" => ["wicks"], "eilnt" => ["inlet"], "airtt" => ["trait"],
      "ckrtu" => ["truck"], "eklnt" => ["knelt"], "deikt" => ["kited"],
      "eflst" => ["felts", "lefts"], "deppu" => ["upped"], "efisv" => ["fives"],
      "ddein" => ["dined"], "dderu" => ["udder"], "abcno" => ["bacon"],
      "cersw" => ["crews", "screw"], "aceht" => ["cheat", "teach"],
      "llors" => ["rolls"], "anors" => ["arson"], "mmpsu" => ["mumps"],
      "dekpu" => ["puked"], "adery" => ["ready"], "airss" => ["saris"],
      "ccklo" => ["clock"], "deipt" => ["tepid"], "eenrw" => ["newer", "renew"],
      "ceelx" => ["excel"], "achir" => ["chair"],
      "eiprs" => ["piers", "pries", "spire"], "ilmpy" => ["imply"],
      "eeelv" => ["levee"], "ehikr" => ["hiker"], "fglsu" => ["gulfs"],
      "morst" => ["storm"], "iprst" => ["strip", "trips"], "abrss" => ["brass"],
      "agmno" => ["mango"], "amprt" => ["tramp"], "moosz" => ["zooms"],
      "cdeow" => ["cowed"], "akrst" => ["stark"],
      "aemst" => ["mates", "meats", "tames", "steam", "teams"],
      "ciotx" => ["toxic"], "abels" => ["bales"], "ademr" => ["armed", "dream"],
      "eiprz" => ["prize"], "aehmr" => ["harem"], "deeky" => ["keyed"],
      "eimst" => ["emits", "mites", "smite", "items", "times"],
      "enops" => ["peons", "opens"], "isstu" => ["suits"], "ceipr" => ["price"],
      "ginss" => ["sings", "signs"], "ceotv" => ["covet"], "deilw" => ["wield"],
      "deess" => ["seeds"], "afrst" => ["rafts"], "adefk" => ["faked"],
      "aprst" => ["strap", "parts", "traps"], "celov" => ["clove"],
      "fnort" => ["front"], "eglns" => ["glens"], "loppy" => ["polyp"],
      "dentu" => ["tuned"], "aadmr" => ["drama"], "alnrs" => ["snarl"],
      "aceno" => ["canoe", "ocean"], "chlny" => ["lynch"], "aklsw" => ["walks"],
      "bhlsu" => ["blush"], "ackrs" => ["racks"], "mprsu" => ["rumps"],
      "degil" => ["glide"], "certu" => ["cuter", "truce"], "addet" => ["dated"],
      "acrry" => ["carry"], "adekw" => ["waked"], "ailsv" => ["vials"],
      "acdet" => ["cadet", "acted"], "aknps" => ["spank"],
      "adelm" => ["lamed", "medal"], "bgino" => ["bingo"], "adeln" => ["laden"],
      "acelr" => ["clear"], "aalrt" => ["altar"], "afltu" => ["fault"],
      "agmrs" => ["grams"], "dfnou" => ["found"], "chhtu" => ["hutch"],
      "adeht" => ["hated", "death"], "ghirt" => ["girth", "right"],
      "ahlst" => ["laths", "halts"], "eehlw" => ["wheel"], "alory" => ["royal"],
      "aeglr" => ["glare", "regal", "lager", "large"], "dilru" => ["lurid"],
      "elpsu" => ["pulse"], "eehst" => ["sheet", "these"], "emnow" => ["women"],
      "abeht" => ["bathe"], "abesu" => ["abuse"], "orrwy" => ["worry"],
      "epstu" => ["upset"], "eorst" => ["store"], "depru" => ["prude"],
      "bmoor" => ["broom"], "beill" => ["libel"], "finuy" => ["unify"],
      "aiort" => ["ratio"], "ilmsy" => ["slimy"], "acekr" => ["creak"],
      "acint" => ["antic"], "cortu" => ["court"], "eoprv" => ["prove"],
      "defmu" => ["fumed"], "hkssu" => ["husks"], "adgln" => ["gland"],
      "ghost" => ["ghost"], "cefor" => ["force"], "cnorw" => ["crown"],
      "inotx" => ["toxin"], "hipsw" => ["whips"], "iklos" => ["kilos"],
      "aghlu" => ["laugh"], "kmosy" => ["smoky"], "acgim" => ["magic"],
      "bbloy" => ["lobby"], "eelsv" => ["elves"], "degor" => ["gored"],
      "mnoru" => ["mourn"], "nsstu" => ["stuns"], "ceens" => ["scene"],
      "bilms" => ["limbs"], "achnt" => ["chant"], "bnoss" => ["snobs"],
      "aesvw" => ["waves"], "eeqru" => ["queer"], "adefs" => ["fades"],
      "egiin" => ["genii"], "abell" => ["label"], "dejoy" => ["joyed"],
      "ailnv" => ["anvil"], "abgns" => ["bangs"],
      "acers" => ["acres", "races", "scare", "cares"], "bdnos" => ["bonds"],
      "ahmrs" => ["harms", "marsh"], "aeoss" => ["oases"], "cmssu" => ["scums"],
      "nttuy" => ["nutty"], "deegl" => ["ledge"], "cehim" => ["chime"],
      "cdeoy" => ["decoy"], "eissz" => ["sizes"], "bhort" => ["broth", "throb"],
      "knost" => ["knots"], "aceln" => ["lance", "clean"], "nprsu" => ["spurn"],
      "acehs" => ["aches", "chase"], "enrtu" => ["tuner"], "fiost" => ["foist"],
      "aehls" => ["hales", "heals", "leash"], "fnotu" => ["fount"],
      "eipst" => ["spite"], "acryz" => ["crazy"], "ajmor" => ["major"],
      "eortt" => ["otter"], "noswy" => ["snowy"], "ceist" => ["cites"],
      "behrt" => ["berth"], "acfny" => ["fancy"], "behrs" => ["herbs"],
      "allms" => ["malls", "small"], "opsst" => ["posts", "spots", "stops"],
      "ijnos" => ["joins"], "ehlls" => ["shell"], "acens" => ["canes"],
      "ackst" => ["stack", "tacks"], "brrsu" => ["burrs"], "eertx" => ["exert"],
      "eeept" => ["tepee"], "eintu" => ["untie", "unite"], "eegin" => ["genie"],
      "dgoru" => ["gourd"], "bhmtu" => ["thumb"], "knosw" => ["knows"],
      "acckl" => ["clack"], "adder" => ["dared", "dread"],
      "aklst" => ["stalk", "talks"], "defiy" => ["deify"], "aeflm" => ["flame"],
      "aeinn" => ["inane"], "eemns" => ["semen"], "asstv" => ["vasts"],
      "deimn" => ["denim", "mined"], "ehnor" => ["heron"], "irsst" => ["stirs"],
      "acdeg" => ["caged"], "fmors" => ["forms"], "aepry" => ["payer", "repay"],
      "ddeik" => ["diked"], "ensst" => ["nests"], "aglss" => ["glass"],
      "lmpuy" => ["lumpy"], "ceimn" => ["mince"], "aclsw" => ["claws"],
      "cghsu" => ["chugs"], "aelmy" => ["mealy"], "ddees" => ["deeds"],
      "eilov" => ["olive"], "efors" => ["fores"], "dinsw" => ["winds"],
      "einrt" => ["inert", "inter"], "acetu" => ["acute"], "ailss" => ["sails"],
      "aclps" => ["claps", "clasp", "scalp"], "aertw" => ["water"],
      "aehvy" => ["heavy"], "doost" => ["stood"], "efrst" => ["frets"],
      "ckkno" => ["knock"], "dnoru" => ["round"], "ceips" => ["epics", "spice"],
      "aesss" => ["asses"], "cghlu" => ["gulch"], "cntuu" => ["uncut"],
      "efstu" => ["fetus"], "aprsy" => ["prays", "spray"], "dfloo" => ["flood"],
      "adelt" => ["delta", "dealt"], "aehrt" => ["earth", "heart"],
      "alnpt" => ["plant"], "altuv" => ["vault"], "oprsu" => ["pours"],
      "eorsv" => ["overs"], "ehoss" => ["hoses", "shoes"],
      "eegnr" => ["genre", "green"], "fnnuy" => ["funny"], "bkoos" => ["books"],
      "doosw" => ["woods"], "ehnos" => ["hones", "shone"], "bbmos" => ["bombs"],
      "egirt" => ["tiger"], "aehrs" => ["hares", "shear", "hears", "share"],
      "acelp" => ["place"], "dlouw" => ["would"], "beopr" => ["probe"],
      "abckl" => ["black"], "ceimr" => ["crime"], "bdins" => ["binds"],
      "eghiw" => ["weigh"], "frruy" => ["furry"], "eghru" => ["huger"],
      "ehitw" => ["white"], "abssy" => ["abyss"], "bnrsu" => ["burns"],
      "cdelu" => ["clued"], "mprtu" => ["trump"], "cipsy" => ["spicy"],
      "eortv" => ["overt", "voter"], "gstuy" => ["gusty"], "ceiir" => ["icier"],
      "aorrw" => ["arrow"], "aemns" => ["manes", "means", "names"],
      "ddehi" => ["hided"], "aelpt" => ["petal", "pleat", "plate"],
      "iknst" => ["knits", "stink"], "hotuy" => ["youth"], "eenpr" => ["preen"],
      "aalst" => ["atlas"], "einpt" => ["inept"], "cehin" => ["niche"],
      "fills" => ["fills"], "adkov" => ["vodka"], "aflos" => ["foals", "loafs"],
      "chlot" => ["cloth"], "eqstu" => ["quest"], "abbes" => ["babes"],
      "defit" => ["fetid"], "hkoos" => ["hooks", "shook"], "dgirs" => ["grids"],
      "adlos" => ["loads"], "ehnop" => ["phone"], "ahrry" => ["harry"],
      "glorw" => ["growl"], "eglov" => ["glove"], "aemsz" => ["mazes"],
      "cdeop" => ["coped"], "aersw" => ["swear", "wears"], "aefkr" => ["freak"],
      "adlmy" => ["madly"], "ehnsw" => ["whens"], "eltux" => ["exult"],
      "deinp" => ["pined"], "ceors" => ["cores", "score"], "acdes" => ["cased"],
      "aeimz" => ["maize"], "aeggu" => ["gauge"], "ceehr" => ["cheer"],
      "ddruy" => ["ruddy"], "deehs" => ["heeds"], "aaerw" => ["aware"],
      "dekop" => ["poked"], "cdhit" => ["ditch"], "ffist" => ["tiffs", "stiff"],
      "gnoss" => ["songs"], "elmpu" => ["plume"], "einnr" => ["inner"],
      "acdem" => ["maced"], "aelrt" => ["alert", "alter", "later"],
      "ceitv" => ["evict"], "eiops" => ["poise"], "eikst" => ["kites"],
      "alssy" => ["slays"], "deovw" => ["vowed"], "fimot" => ["motif"],
      "iloop" => ["polio"], "gloss" => ["gloss", "slogs"], "cintu" => ["tunic"],
      "gillr" => ["grill"], "ddeos" => ["dosed"], "ciilv" => ["civil"],
      "eeprs" => ["spree", "peers"], "eirrs" => ["riser"],
      "iorst" => ["riots", "trios"], "deotu" => ["outed"], "esstz" => ["zests"],
      "gills" => ["gills"], "abelz" => ["blaze"], "bdeem" => ["embed"],
      "klosy" => ["yolks"], "aalnv" => ["naval"], "elsty" => ["style"],
      "eikps" => ["pikes", "spike"], "ackms" => ["smack"], "gllsu" => ["gulls"],
      "lrtuy" => ["truly"], "bcksu" => ["bucks"], "benst" => ["bents"],
      "cikpr" => ["prick"], "cikrt" => ["trick"], "aersv" => ["saver", "raves"],
      "aclrw" => ["crawl"], "lnooy" => ["loony"], "bills" => ["bills"],
      "adefz" => ["fazed"], "ghitt" => ["tight"], "isttw" => ["twist"],
      "ilmps" => ["limps"], "imotv" => ["vomit"], "achty" => ["yacht"],
      "iklns" => ["kilns", "slink", "links"], "dikss" => ["disks", "skids"],
      "chipt" => ["pitch"], "ikmns" => ["minks"], "hortw" => ["throw", "worth"],
      "dgoos" => ["goods"], "ceiju" => ["juice"], "acfnr" => ["franc"],
      "bhirt" => ["birth"], "hippy" => ["hippy"], "anrst" => ["rants"],
      "eorsu" => ["rouse"], "abinr" => ["brain"], "efosx" => ["foxes"],
      "bdeik" => ["biked"], "gnssu" => ["snugs"], "hiost" => ["hoist"],
      "beemr" => ["ember"], "degin" => ["deign"], "hoost" => ["hoots", "shoot"],
      "aehht" => ["heath"], "aalpp" => ["papal"], "booty" => ["booty"],
      "adens" => ["deans", "sedan"], "abcks" => ["backs"], "dlloy" => ["dolly"],
      "airst" => ["stair"], "abcer" => ["brace"], "alloy" => ["alloy", "loyal"],
      "lorry" => ["lorry"], "ahksw" => ["hawks"], "ablrw" => ["brawl"],
      "acdir" => ["acrid"], "ajntu" => ["jaunt", "junta"], "norsw" => ["sworn"],
      "chrsu" => ["crush"], "imstt" => ["mitts"], "cinsz" => ["zincs"],
      "aegry" => ["gayer"], "ceruv" => ["curve"], "oosty" => ["sooty"],
      "msttu" => ["mutts"], "hlost" => ["sloth"], "efnot" => ["often"],
      "oorst" => ["roost", "torso", "roots"], "defir" => ["fired", "fried"],
      "ddeit" => ["tided"], "ennot" => ["tonne"], "ekopy" => ["pokey"],
      "eenuv" => ["venue"], "eegns" => ["genes"], "affst" => ["staff"],
      "aekrs" => ["rakes"], "cklsu" => ["lucks"], "acelt" => ["cleat"],
      "llpsu" => ["pulls"], "ghlou" => ["ghoul"], "aklop" => ["polka"],
      "cginu" => ["cuing"], "aorrz" => ["razor"], "agims" => ["sigma"],
      "acefr" => ["farce"], "jorru" => ["juror"], "iknrs" => ["rinks"],
      "nnsuy" => ["sunny"], "belno" => ["noble"], "pppuy" => ["puppy"],
      "eginv" => ["given"], "eimnr" => ["miner"], "fginu" => ["fungi"],
      "hmost" => ["moths"], "ginor" => ["groin"], "agsst" => ["stags"],
      "floty" => ["lofty"], "mpstu" => ["stump"], "binor" => ["robin"],
      "aders" => ["dears", "dares", "reads"], "abdey" => ["bayed", "beady"],
      "bmosw" => ["wombs"], "ilntu" => ["until"], "egint" => ["tinge"],
      "abdes" => ["beads", "based"], "moprs" => ["proms", "romps"],
      "adegt" => ["gated"], "elstw" => ["welts"], "lopps" => ["plops"],
      "kknsu" => ["skunk"], "deegh" => ["hedge"], "aegrv" => ["grave"],
      "accho" => ["coach"], "hmnpy" => ["nymph"], "dllos" => ["dolls"],
      "bdloo" => ["blood"], "bdeos" => ["bodes"], "cderu" => ["crude", "cured"],
      "agrvy" => ["gravy"], "aekns" => ["snake", "sneak"],
      "dstuy" => ["dusty", "study"], "eersu" => ["reuse"], "deegg" => ["egged"],
      "bhrsu" => ["shrub", "brush"], "iksst" => ["skits"], "aegls" => ["gales"],
      "eimrs" => ["emirs", "mires", "miser"], "deimt" => ["timed"],
      "aiprs" => ["pairs"], "ablst" => ["blast"], "addej" => ["jaded"],
      "adeil" => ["ailed", "ideal"], "chitw" => ["witch"], "fikrs" => ["frisk"],
      "acelv" => ["calve"], "aaimn" => ["mania"], "aegim" => ["image"],
      "elssw" => ["slews"], "fuyzz" => ["fuzzy"], "ailqu" => ["quail"],
      "dnoor" => ["donor"], "alrtu" => ["ultra"], "ansty" => ["nasty"],
      "diimt" => ["timid"], "ikkns" => ["kinks"], "abhrs" => ["brash"],
      "ceehn" => ["hence"], "almsu" => ["mauls"], "ahlno" => ["halon"],
      "ehilt" => ["lithe"], "enstw" => ["newts"], "diilv" => ["livid"],
      "aelnr" => ["learn"], "aamss" => ["amass"], "intuy" => ["unity"],
      "dirty" => ["dirty"], "adlsu" => ["lauds"], "ellqu" => ["quell"],
      "glssu" => ["slugs"], "ffgru" => ["gruff"], "emnos" => ["omens"],
      "aensw" => ["wanes", "weans"], "ddeot" => ["doted"], "anttu" => ["taunt"],
      "beorx" => ["boxer"], "hllsu" => ["hulls"], "abcin" => ["cabin"],
      "aflor" => ["flora"], "acmpr" => ["cramp"], "fhoos" => ["hoofs"],
      "ehorw" => ["whore"], "ilptu" => ["tulip"], "bdnou" => ["bound"],
      "iktty" => ["kitty"], "doopr" => ["droop"], "ehlot" => ["hotel"],
      "moors" => ["moors", "rooms"], "eemss" => ["seems"], "cklpu" => ["pluck"],
      "hostu" => ["shout", "thous", "south"], "ellss" => ["sells"],
      "abbls" => ["blabs"], "cghou" => ["cough"], "eisvw" => ["wives", "views"],
      "adekn" => ["knead", "naked"], "aegps" => ["gapes", "pages"],
      "adltu" => ["adult"], "ainps" => ["pains"],
      "aekst" => ["skate", "steak", "teaks", "stake", "takes"],
      "adegl" => ["glade"], "cdiss" => ["discs"], "ahksy" => ["shaky"],
      "aeest" => ["tease"], "aegmr" => ["gamer"], "eflno" => ["felon"],
      "denoz" => ["zoned", "dozen"], "ehrsw" => ["shrew"], "diivv" => ["vivid"],
      "acilm" => ["claim"], "flloy" => ["folly"], "abins" => ["basin"],
      "dfnor" => ["frond"], "eipps" => ["pipes"], "emrry" => ["merry"],
      "bilor" => ["broil"], "eilps" => ["plies", "piles"], "cklos" => ["locks"],
      "eilpr" => ["peril"], "cehos" => ["chose"], "eflls" => ["fells"],
      "closw" => ["scowl"], "opstu" => ["pouts", "spout"], "cgiln" => ["cling"],
      "aenot" => ["atone"], "aemrt" => ["tamer"], "blrtu" => ["blurt"],
      "eloos" => ["loose"], "coost" => ["scoot"], "ahkrs" => ["harks", "shark"],
      "eelpr" => ["leper", "repel"], "bmost" => ["tombs"], "admtu" => ["datum"],
      "demop" => ["moped"], "alpty" => ["aptly"], "abdeg" => ["badge"],
      "aekow" => ["awoke"], "ehisv" => ["hives"], "lmoos" => ["looms"],
      "dmpsu" => ["dumps"], "aenps" => ["aspen", "napes", "panes"],
      "adegr" => ["raged", "grade"], "iklmy" => ["milky"], "bilos" => ["boils"],
      "deisv" => ["vised", "dives"], "derru" => ["ruder"],
      "ceirs" => ["rices", "cries"], "deopt" => ["depot", "opted"],
      "eikns" => ["skein"], "aegrs" => ["rages", "sager", "gears"],
      "efisx" => ["fixes"], "chlnu" => ["lunch"], "inprt" => ["print"],
      "adnrs" => ["darns"], "annoy" => ["annoy"], "egssu" => ["guess"],
      "eglru" => ["gruel"], "ikrss" => ["risks"], "aknst" => ["stank", "tanks"],
      "eknow" => ["woken"], "belst" => ["belts"], "bdiln" => ["blind"],
      "deosw" => ["sowed"], "opssu" => ["soups"], "dnorw" => ["drown"],
      "enrst" => ["rents", "stern"], "ceehk" => ["cheek"], "antty" => ["natty"],
      "efilr" => ["rifle"], "eekps" => ["peeks", "keeps"], "emssy" => ["messy"],
      "acegr" => ["grace"], "adhsy" => ["shady"], "aegrt" => ["grate", "great"],
      "istxy" => ["sixty"], "ginrw" => ["wring"], "absst" => ["stabs"],
      "deoss" => ["doses"], "bmpuy" => ["bumpy"], "iistv" => ["visit"],
      "deiss" => ["sides"], "aessv" => ["vases", "saves"], "adgrs" => ["drags"],
      "hrruy" => ["hurry"], "ilmss" => ["slims"], "acesv" => ["caves"],
      "eentv" => ["event"], "aderr" => ["rared"], "emprs" => ["sperm"],
      "aeguz" => ["gauze"], "acinp" => ["panic"], "hirst" => ["shirt"],
      "denps" => ["pends", "spend"], "allps" => ["palls"],
      "aelst" => ["slate", "stale", "tales", "least", "steal"],
      "bosuy" => ["buoys"], "ilstt" => ["tilts"]}
    |> Map.get(string_id)
  end
end
