defmodule Jumble.ScowlDict.Size35.Length3 do
  def get(string_id) do
    %{"abo" => ["boa"], "hot" => ["hot"], "oow" => ["woo"], "ctu" => ["cut"],
      "afr" => ["far"], "dgu" => ["dug"], "abd" => ["dab", "bad"], "hip" => ["hip"],
      "bgi" => ["big"], "imx" => ["mix"], "ikl" => ["ilk"], "nru" => ["urn", "run"],
      "gmy" => ["gym"], "bde" => ["bed"], "lot" => ["lot"], "ehu" => ["hue"],
      "ajy" => ["jay"], "aey" => ["aye"], "eil" => ["lie"], "deu" => ["due"],
      "ooz" => ["zoo"], "hop" => ["hop"], "nno" => ["non"], "ggi" => ["gig"],
      "ivy" => ["ivy"], "aes" => ["sea"], "mmo" => ["mom"], "fnu" => ["fun"],
      "ewy" => ["yew"], "afn" => ["fan"], "ott" => ["tot"], "cgo" => ["cog"],
      "abl" => ["lab"], "aft" => ["fat"], "dop" => ["pod"], "cox" => ["cox"],
      "chi" => ["chi"], "flu" => ["flu"], "ops" => ["sop"], "eit" => ["tie"],
      "ehr" => ["her"], "now" => ["now", "own", "won"], "app" => ["pap"],
      "acm" => ["cam"], "ovw" => ["vow"], "bfi" => ["fib"], "amy" => ["yam", "may"],
      "atx" => ["tax"], "ept" => ["pet"], "psy" => ["spy"], "amt" => ["mat"],
      "aps" => ["pas", "sap", "spa"], "itt" => ["tit"], "aly" => ["lay"],
      "bow" => ["bow"], "ddo" => ["odd"], "akr" => ["ark"], "alx" => ["lax"],
      "eny" => ["yen"], "dim" => ["dim"], "beg" => ["beg"], "cno" => ["con"],
      "ajw" => ["jaw"], "opp" => ["pop"], "eeg" => ["gee"], "est" => ["set"],
      "aet" => ["ate", "eat", "tea"], "mru" => ["rum"], "orw" => ["row"],
      "dos" => ["dos", "sod"], "inn" => ["inn"], "etw" => ["wet"], "aqu" => ["qua"],
      "ill" => ["ill"], "dei" => ["die"], "oty" => ["toy"], "den" => ["den", "end"],
      "aim" => ["aim"], "ilo" => ["oil"], "fgo" => ["fog"], "emn" => ["men"],
      "nsu" => ["sun"], "ilp" => ["lip"], "rty" => ["try"], "coo" => ["coo"],
      "oru" => ["our"], "ipt" => ["pit", "tip"], "enp" => ["pen"], "alw" => ["law"],
      "bir" => ["rib"], "cei" => ["ice"], "ent" => ["net", "ten"], "mmu" => ["mum"],
      "eey" => ["eye"], "add" => ["dad", "add"], "pry" => ["pry"], "ady" => ["day"],
      "acp" => ["cap"], "ems" => ["mes"], "def" => ["fed"], "blo" => ["lob"],
      "ary" => ["ray"], "mow" => ["mow"], "bet" => ["bet"], "ads" => ["ads", "sad"],
      "ego" => ["ego"], "eht" => ["the"], "esu" => ["sue", "use"], "ahy" => ["hay"],
      "ast" => ["sat"], "abc" => ["cab"], "eru" => ["rue"], "guy" => ["guy"],
      "efo" => ["foe"], "anr" => ["ran"], "ipr" => ["rip"], "adw" => ["wad"],
      "iwz" => ["wiz"], "agr" => ["rag"], "dir" => ["rid"], "aor" => ["oar"],
      "egm" => ["gem"], "anv" => ["van"], "del" => ["led"], "htu" => ["hut"],
      "gju" => ["jug"], "aer" => ["ear", "era", "are"], "bjo" => ["job"],
      "ilt" => ["lit"], "ffo" => ["off"], "aep" => ["ape", "pea"], "dry" => ["dry"],
      "ino" => ["ion"], "oww" => ["wow"], "bmo" => ["mob"], "egg" => ["egg"],
      "bbi" => ["bib"], "boy" => ["boy"], "act" => ["act", "cat"], "dot" => ["dot"],
      "deo" => ["ode", "doe"], "bhu" => ["hub"], "glu" => ["lug"], "eno" => ["one"],
      "eip" => ["pie"], "lsy" => ["sly"], "eev" => ["eve"], "amp" => ["amp", "map"],
      "eow" => ["woe", "owe"], "bey" => ["bye"], "moo" => ["moo"],
      "bdu" => ["bud", "dub"], "cop" => ["cop"], "ail" => ["ail"], "ekn" => ["ken"],
      "psu" => ["pus", "sup", "ups"], "dor" => ["rod"], "msy" => ["mys"],
      "ant" => ["ant", "tan"], "ajr" => ["jar"], "ikt" => ["kit"], "gjo" => ["jog"],
      "adl" => ["lad"], "dmo" => ["mod"], "hos" => ["ohs"], "bor" => ["rob"],
      "bgo" => ["gob", "bog"], "epp" => ["pep"], "ehm" => ["hem"], "bcu" => ["cub"],
      "enw" => ["new"], "aht" => ["hat"], "ist" => ["its", "sit"],
      "dno" => ["nod", "don"], "eho" => ["hoe"], "ams" => ["mas"], "hsy" => ["shy"],
      "anp" => ["nap", "pan"], "ahs" => ["ash", "has"], "osw" => ["sow"],
      "bru" => ["rub"], "ehs" => ["hes", "she"], "acr" => ["arc", "car"],
      "adh" => ["had"], "etv" => ["vet"], "cis" => ["sic"], "dip" => ["dip"],
      "ako" => ["oak"], "ado" => ["ado"], "esy" => ["yes"], "imr" => ["rim"],
      "emw" => ["mew"], "adf" => ["fad"], "aby" => ["bay"], "abg" => ["gab", "bag"],
      "agw" => ["wag"], "bit" => ["bit"], "bnu" => ["bun"], "hhu" => ["huh"],
      "apy" => ["yap", "pay"], "abr" => ["bra", "bar"], "bbe" => ["ebb"],
      "ikn" => ["kin", "ink"], "dlo" => ["old"], "all" => ["all"], "eet" => ["tee"],
      "coy" => ["coy"], "giw" => ["wig"], "eef" => ["fee"], "gru" => ["rug"],
      "efz" => ["fez"], "eky" => ["key"], "fix" => ["fix"], "gin" => ["gin"],
      "buy" => ["buy"], "ipz" => ["zip"], "bos" => ["sob"], "iks" => ["ski"],
      "hmu" => ["hum"], "got" => ["got"], "aeg" => ["age"], "imp" => ["imp"],
      "eor" => ["ore", "roe"], "ees" => ["see"], "adi" => ["aid"], "his" => ["his"],
      "eir" => ["ire"], "dmu" => ["mud"], "bbo" => ["bob"], "fir" => ["fir"],
      "iln" => ["nil"], "agg" => ["gag"], "ael" => ["ale"], "fly" => ["fly"],
      "goo" => ["goo"], "int" => ["nit", "tin"], "air" => ["air"], "elm" => ["elm"],
      "cru" => ["cur"], "lop" => ["lop"], "kow" => ["wok"], "afo" => ["oaf"],
      "not" => ["ton", "not"], "any" => ["nay", "any"], "gij" => ["jig"],
      "ely" => ["lye"], "abj" => ["jab"], "ehn" => ["hen"], "opr" => ["pro"],
      "fry" => ["fry"], "ekl" => ["elk"], "aks" => ["ask"],
      "apt" => ["apt", "pat", "tap"], "alp" => ["lap", "pal"], "dhi" => ["hid"],
      "npu" => ["pun"], "art" => ["tar", "rat", "art"], "asy" => ["say"],
      "ceu" => ["cue"], "ghu" => ["hug", "ugh"], "bew" => ["web"],
      "ips" => ["pis", "sip"], "cot" => ["cot"], "eot" => ["toe"], "egk" => ["keg"],
      "agl" => ["gal", "lag"], "hty" => ["thy"], "ptu" => ["put"], "rwy" => ["wry"],
      "emt" => ["met"], "agh" => ["hag"], "adn" => ["and"], "joy" => ["joy"],
      "low" => ["owl", "low"], "isx" => ["six"], "elt" => ["let"],
      "abt" => ["bat", "tab"], "fin" => ["fin"], "aew" => ["awe"], "hwy" => ["why"],
      "ddi" => ["did"], "opt" => ["opt", "pot", "top"], "itw" => ["wit"],
      "hit" => ["hit"], "bdi" => ["bid"], "agn" => ["nag"], "ins" => ["ins", "sin"],
      "efw" => ["few"], "irs" => ["sir"], "bpu" => ["pub"], "agy" => ["gay"],
      "jot" => ["jot"], "rtu" => ["rut"], "otu" => ["out"], "awx" => ["wax"],
      "egl" => ["gel", "leg"], "fis" => ["ifs"], "acw" => ["caw"],
      "asw" => ["saw", "was"], "acd" => ["cad"], "dew" => ["dew", "wed"],
      "nnu" => ["nun"], "dil" => ["lid"], "gho" => ["hog"], "ouy" => ["you"],
      "din" => ["din"], "lpy" => ["ply"], "how" => ["how", "who"], "ery" => ["rye"],
      "ags" => ["sag", "gas"], "hmo" => ["ohm"], "ikr" => ["irk"], "egt" => ["get"],
      "amr" => ["mar", "ram", "arm"], "inp" => ["nip", "pin"],
      "dgo" => ["god", "dog"], "nos" => ["son"], "adp" => ["pad"], "der" => ["red"],
      "ehw" => ["hew"], "bee" => ["bee"], "oot" => ["too"], "fit" => ["fit"],
      "apw" => ["paw"], "gir" => ["rig"], "gip" => ["pig"], "ntu" => ["nut"],
      "abn" => ["nab", "ban"], "ort" => ["rot"], "ddu" => ["dud"], "cdo" => ["cod"],
      "amn" => ["man"], "cry" => ["cry"], "gmu" => ["gum", "mug"], "erv" => ["rev"],
      "eew" => ["ewe", "wee"], "cow" => ["cow"], "ciy" => ["icy"],
      "arw" => ["raw", "war"], "mop" => ["mop"], "esx" => ["sex"], "egp" => ["peg"],
      "box" => ["box"], "aov" => ["ova"], "agp" => ["gap"], "cpu" => ["cup"],
      "bmu" => ["bum"], "ago" => ["ago"], "adm" => ["dam", "mad"], "acn" => ["can"],
      "msu" => ["sum"], "dey" => ["dye"], "dgi" => ["dig"], "esw" => ["sew"],
      "epr" => ["per"], "awy" => ["way"], "btu" => ["tub", "but"], "aky" => ["yak"],
      "acs" => ["sac"], "ety" => ["yet"], "gtu" => ["tug", "gut"],
      "eel" => ["eel", "lee"], "eiv" => ["vie"], "evx" => ["vex"], "ajm" => ["jam"],
      "ksy" => ["sky"], "bop" => ["bop"], "ahm" => ["ham"], "glo" => ["log"],
      "ejt" => ["jet"], "dik" => ["kid"], "gnu" => ["gnu", "gun"], "ppu" => ["pup"],
      "bgu" => ["bug"], "atv" => ["vat"], "nor" => ["nor"], "dou" => ["duo"],
      "apr" => ["rap", "par"], "fox" => ["fox"], "otw" => ["tow", "wot", "two"],
      "inw" => ["win"], "fgi" => ["fig"], "for" => ["fro", "for"], "jtu" => ["jut"],
      "eek" => ["eke"], "ass" => ["ass"], "bco" => ["cob"], "ehy" => ["hey"],
      "fru" => ["fur"], "bin" => ["bin"], "bsu" => ["sub", "bus"], "him" => ["him"],
      "aiv" => ["via"], "efl" => ["elf"], "efn" => ["fen"], "err" => ["err"],
      "ace" => ["ace"], "boo" => ["boo"], "anw" => ["wan"], "agt" => ["tag"],
      "epw" => ["pew"]}
    |> Map.get(string_id)
  end

  def valid_ids do
    ["abo", "hot", "oow", "ctu", "afr", "dgu", "abd", "hip", "bgi", "imx", "ikl",
     "nru", "gmy", "bde", "lot", "ehu", "ajy", "aey", "eil", "deu", "ooz", "hop",
     "nno", "ggi", "ivy", "aes", "mmo", "fnu", "ewy", "afn", "ott", "cgo", "abl",
     "aft", "dop", "cox", "chi", "flu", "ops", "eit", "ehr", "now", "app", "acm",
     "ovw", "bfi", "amy", "atx", "ept", "psy", "amt", "aps", "itt", "aly", "bow",
     "ddo", "akr", "alx", "eny", "dim", "beg", "cno", "ajw", "opp", "eeg", "est",
     "aet", "mru", "orw", "dos", "inn", "etw", "aqu", "ill", "dei", "oty", "den",
     "aim", "ilo", "fgo", "emn", "nsu", "ilp", "rty", "coo", "oru", "ipt", "enp",
     "alw", "bir", "cei", "ent", "mmu", "eey", "add", "pry", "ady", "acp", "ems",
     "def", "blo", "ary", "mow", "bet", "ads", "ego", "eht", "esu", "ahy", "ast",
     "abc", "eru", "guy", "efo", "anr", "ipr", "adw", "iwz", "agr", "dir", "aor",
     "egm", "anv", "del", "htu", "gju", "aer", "bjo", "ilt", "ffo", "aep", "dry",
     "ino", "oww", "bmo", "egg", "bbi", "boy", "act", "dot", "deo", "bhu", "glu",
     "eno", "eip", "lsy", "eev", "amp", "eow", "bey", "moo", "bdu", "cop", "ail",
     "ekn", "psu", "dor", "msy", "ant", "ajr", "ikt", "gjo", "adl", "dmo", "hos",
     "bor", "bgo", "epp", "ehm", "bcu", "enw", "aht", "ist", "dno", "eho", "ams",
     "hsy", "anp", "ahs", "osw", "bru", "ehs", "acr", "adh", "etv", "cis", "dip",
     "ako", "ado", "esy", "imr", "emw", "adf", "aby", "abg", "agw", "bit", "bnu",
     "hhu", "apy", "abr", "bbe", "ikn", "dlo", "all", "eet", "coy", "giw", "eef",
     "gru", "efz", "eky", "fix", "gin", "buy", "ipz", "bos", "iks", "hmu", "got",
     "aeg", "imp", "eor", "ees", "adi", "his", "eir", "dmu", "bbo", "fir", "iln",
     "agg", "ael", "fly", "goo", "int", "air", "elm", "cru", "lop", "kow", "afo",
     "not", "any", "gij", "ely", "abj", "ehn", "opr", "fry", "ekl", "aks", "apt",
     "alp", "dhi", "npu", "art", "asy", "ceu", "ghu", "bew", "ips", "cot", "eot",
     "egk", "agl", "hty", "ptu", "rwy", "emt", "agh", "adn", "joy", "low", "isx",
     "elt", "abt", "fin", "aew", "hwy", "ddi", "opt", "itw", "hit", "bdi", "agn",
     "ins", "efw", "irs", "bpu", "agy", "jot", "rtu", "otu", "awx", "egl", "fis",
     "acw", "asw", "acd", "dew", "nnu", "dil", "gho", "ouy", "din", "lpy", "how",
     "ery", "ags", "hmo", "ikr", "egt", "amr", "inp", "dgo", "nos", "adp", "der",
     "ehw", "bee", "oot", "fit", "apw", "gir", "gip", "ntu", "abn", "ort", "ddu",
     "cdo", "amn", "cry", "gmu", "erv", "eew", "cow", "ciy", "arw", "mop", "esx",
     "egp", "box", "aov", "agp", "cpu", "bmu", "ago", "adm", "acn", "msu", "dey",
     "dgi", "esw", "epr", "awy", "btu", "aky", "acs", "ety", "gtu", "eel", "eiv",
     "evx", "ajm", "ksy", "bop", "ahm", "glo", "ejt", "dik", "gnu", "ppu", "bgu",
     "atv", "nor", "dou", "apr", "fox", "otw", "inw", "fgi", "for", "jtu", "eek",
     "ass", "bco", "ehy", "fru", "bin", "bsu", "him", "aiv", "efl", "efn", "err",
     "ace", "boo", "anw", "agt", "epw"]
    |> Enum.into(HashSet.new)
  end
end
