defmodule Jumble.ScowlDict.Size35.Length12 do
  def get(string_id) do
    %{"aaiillnnostt" => ["installation"], "abciimnnoost" => ["combinations"],
      "aacilmnooprt" => ["proclamation"], "cilnnoostuuy" => ["continuously"],
      "aeehllmnnopy" => ["phenomenally"], "aabefgiknrst" => ["breakfasting"],
      "abcgiikllnst" => ["blacklisting"], "eeginopprstv" => ["overstepping"],
      "deeginnrrrsu" => ["surrendering"], "ceerrrssttuu" => ["restructures"],
      "bcinoorrsttu" => ["contributors"], "aaccehhiilrr" => ["hierarchical"],
      "acceilmnnoou" => ["uneconomical"], "abcdeooorrrt" => ["corroborated"],
      "ceelnnoqstuy" => ["consequently"], "adeeimnrstuv" => ["misadventure"],
      "acdegiiknrst" => ["sidetracking"], "ccdeeelorttu" => ["electrocuted"],
      "adeiinorsstt" => ["dissertation"], "aefnnorsttuu" => ["unfortunates"],
      "abcdeilnorsy" => ["considerably"], "adeghmnorrst" => ["grandmothers"],
      "accceimnrstu" => ["circumstance"], "aeeemrssssst" => ["seamstresses"],
      "acdeeiiinnrs" => ["incendiaries"], "aacehoprsstt" => ["catastrophes"],
      "eehlnrsssstu" => ["ruthlessness"], "aeeinorrsstv" => ["reservations"],
      "acceimmnostu" => ["communicates"], "abeinoorsstv" => ["observations"],
      "aaceijllmsty" => ["majestically"], "acdeiinnnotu" => ["denunciation"],
      "aceiinoprrtt" => ["practitioner"], "aefmnorrrsst" => ["transformers"],
      "cdeginoorrvw" => ["overcrowding"], "aegiilrrrtuy" => ["irregularity"],
      "aacegiinnrst" => ["ascertaining"], "cdeiinoprsst" => ["descriptions"],
      "efgiinnoprsy" => ["personifying"], "eeginoprstty" => ["stereotyping"],
      "bdeeefiilnns" => ["indefensible"], "ccdeehilpssy" => ["psychedelics"],
      "ceinnosstttu" => ["constituents"], "aabeeelnprtu" => ["unrepeatable"],
      "aacdeilmrttu" => ["matriculated"], "deefiiinnort" => ["redefinition"],
      "acdeegiinprt" => ["depreciating"], "cdefhlmooorr" => ["chloroformed"],
      "aaccdemmoost" => ["accommodates"], "aaceghiloprs" => ["archipelagos"],
      "begiiilllnty" => ["intelligibly"], "ccddeimnostu" => ["misconducted"],
      "aceilnnnootv" => ["conventional"], "adeeersssstw" => ["stewardesses"],
      "ahimoopppstu" => ["hippopotamus"], "ceehinoorrss" => ["rhinoceroses"],
      "aaceinrtttuv" => ["unattractive"], "accgiillooos" => ["sociological"],
      "cceeennoqssu" => ["consequences"], "acehiinssttu" => ["enthusiastic"],
      "adeeffiilnrt" => ["differential"], "aabcghiilopr" => ["biographical"],
      "abdegiikmnrs" => ["disembarking"], "aeefgiorrrrt" => ["refrigerator"],
      "aegiilmnnrst" => ["streamlining"], "aehimnnosstt" => ["astonishment"],
      "aiillnorsttu" => ["illustration"], "aaeeiinnrrtv" => ["veterinarian"],
      "deeeinprrsst" => ["interspersed"], "accdeeinnnst" => ["incandescent"],
      "accceeeinqsu" => ["acquiescence"], "eiinoprssttu" => ["superstition"],
      "aacceilnrrtt" => ["recalcitrant"], "accfiinnoost" => ["confiscation"],
      "adeeimnoprst" => ["impersonated", "predominates"],
      "achiiprsstty" => ["psychiatrist"], "cddeeinnostt" => ["discontented"],
      "addeeiimnsst" => ["disseminated"], "aginnoprrstt" => ["transporting"],
      "eeilmooprsst" => ["metropolises"], "aeeillnqtuvy" => ["equivalently"],
      "aceemmmoorst" => ["commemorates"],
      "aceinnoorstv" => ["conservation", "conversation"],
      "ccgiinnnnouv" => ["unconvincing"], "ddeeeinnnpst" => ["independents"],
      "ccegijnnortu" => ["conjecturing"], "aaiilnnorstt" => ["transitional"],
      "aaabeiilmnnt" => ["maintainable"], "abcdeeilnors" => ["considerable"],
      "adeehhlorrss" => ["shareholders"], "aciiinopssuu" => ["inauspicious"],
      "aabeeksssttw" => ["wastebaskets"], "aaeehimmnpst" => ["amphetamines"],
      "aceginorsssu" => ["graciousness"], "cdeeeoprrsss" => ["predecessors"],
      "aceghhooprry" => ["choreography"], "acceeilllrty" => ["electrically"],
      "aacillmnorty" => ["romantically"], "aeehnnorrstt" => ["northeastern"],
      "cceeffiinost" => ["coefficients"], "aciilmnoopst" => ["compilations"],
      "deeeghnnrstt" => ["strengthened"], "deefiiilnnty" => ["indefinitely"],
      "bceeeelnnosv" => ["benevolences"], "aceeimmorsst" => ["commiserates"],
      "acilmnooopst" => ["cosmopolitan"], "aaeeemnppsst" => ["appeasements"],
      "ceinooprsstu" => ["prosecutions"], "aeeilprssuvy" => ["persuasively"],
      "acdeelmnoptt" => ["contemplated"], "aeimnrrssttt" => ["transmitters"],
      "aacceeilnort" => ["acceleration"], "aefghhoorrtu" => ["thoroughfare"],
      "cdeennrrrtuu" => ["undercurrent"], "aadefghnrrst" => ["grandfathers"],
      "deeelmnopstv" => ["developments"], "eghinoorrtvw" => ["overthrowing"],
      "eiiimnnorsst" => ["intermission"], "bcceeelnooss" => ["obsolescence"],
      "abdeeeerrrtv" => ["reverberated"], "adeeghimnost" => ["homesteading"],
      "aaceijlnostu" => ["ejaculations"], "deeeilnrsssw" => ["wildernesses"],
      "cdeeilmnoopx" => ["complexioned"], "abeeffilnrsu" => ["insufferable"],
      "deeeinprstux" => ["expenditures"], "aceehimnsstt" => ["chastisement"],
      "adeeefgirrrt" => ["refrigerated"], "aaceillprrst" => ["caterpillars"],
      "agghiimnnrst" => ["hamstringing"], "dggiilnnrstu" => ["disgruntling"],
      "acdiilnnoost" => ["conditionals"], "aagghinoprtu" => ["autographing"],
      "aefgimnorrtt" => ["reformatting"], "ccdddeeennos" => ["condescended"],
      "eelmmnnoptuy" => ["unemployment"], "aabegimnrrss" => ["embarrassing"],
      "acegimnnopss" => ["encompassing"], "ccelnnorrtuy" => ["concurrently"],
      "abefgilnoruv" => ["unforgivable"], "adeiinnnostt" => ["indentations"],
      "bhiiinooprst" => ["prohibitions"], "aaghiiilnnnt" => ["annihilating"],
      "ceeeefinnrrt" => ["interference"], "aabeglmmoprr" => ["programmable"],
      "befgilnrttuy" => ["butterflying"], "adefiiisssst" => ["dissatisfies"],
      "aainnnoprsst" => ["nonpartisans"], "ddefghilloot" => ["floodlighted"],
      "aaceijkrsttt" => ["straitjacket"], "abdelmnorsty" => ["demonstrably"],
      "acgiiilnprtt" => ["triplicating"], "ceefgiilnrty" => ["electrifying"],
      "bdeeeilmnrtw" => ["bewilderment"], "aaggiinnrtuu" => ["inaugurating"],
      "accgiiilnnot" => ["conciliating"], "aabefllmmnno" => ["nonflammable"],
      "aadegikmnrrt" => ["trademarking"], "aeffhilnsstu" => ["faithfulness"],
      "deeeeimnprtx" => ["experimented"], "adeeeiimnrtt" => ["intermediate"],
      "aeeopprrrstt" => ["perpetrators"], "aaceeggillno" => ["genealogical"],
      "acehinoprrss" => ["chairpersons"], "achiillorsty" => ["historically"],
      "ccdeiorrssss" => ["crisscrossed"], "aaeilnopssty" => ["passionately"],
      "cghinoooppty" => ["photocopying"], "ccefiiinnstu" => ["unscientific"],
      "ceilnnosstty" => ["consistently"], "aaccilmnotuu" => ["accumulation"],
      "aeghlmnnoors" => ["longshoreman"], "deeelmnppstu" => ["supplemented"],
      "abcdeeehirsu" => ["debaucheries"], "ccgiinnorstt" => ["constricting"],
      "aaccilnooptu" => ["occupational"], "abceeelmnrss" => ["resemblances"],
      "aceeillnrsuv" => ["surveillance"], "cceeelorsttu" => ["electrocutes"],
      "aacceillnnot" => ["cancellation"], "aaeilmnprstu" => ["planetariums"],
      "eegiiinnrtvw" => ["interviewing"], "aciiilnpprty" => ["principality"],
      "adeeiilnprst" => ["presidential"], "adgiillnnotu" => ["longitudinal"],
      "aaeegmnnrrst" => ["arrangements"], "abeeeinrrttv" => ["invertebrate"],
      "abdeeilprstu" => ["disreputable"], "aegiinorrstt" => ["registration"],
      "aaacceiinptt" => ["incapacitate"], "diiillnosssu" => ["disillusions"],
      "beeeiilrrrsv" => ["irreversible"], "aeilmnosstuu" => ["simultaneous"],
      "cgiilooossst" => ["sociologists"], "aggimmmnnoor" => ["monogramming"],
      "acddeeefnort" => ["confederated"], "clnoprssuuuu" => ["unscrupulous"],
      "abceiilnrtxy" => ["inextricably"], "aacdeilnorst" => ["declarations"],
      "aeeeinnrrstt" => ["entertainers"], "aacegiimrrss" => ["miscarriages"],
      "eeelllnrssty" => ["relentlessly"], "cddegiiinrst" => ["discrediting"],
      "abbghiilopry" => ["bibliography"], "accegiinrtux" => ["excruciating"],
      "achhiloprsss" => ["scholarships"], "aabeghiknrtt" => ["breathtaking"],
      "abdeeeilmnrt" => ["determinable"], "afinorrssttu" => ["frustrations"],
      "acddeilnoost" => ["consolidated"], "eeimopprsssu" => ["superimposes"],
      "aabeelnnorsu" => ["unreasonable"], "ceeehiknsttt" => ["kitchenettes"],
      "eeegilnoprsv" => ["oversleeping"], "cceeilllotvy" => ["collectively"],
      "cdefgiiinnst" => ["disinfecting"], "accegilnnosv" => ["convalescing"],
      "adeegmmoprrr" => ["reprogrammed"], "cccdeeiinnos" => ["coincidences"],
      "eiinnoprrttu" => ["interruption"], "cceiorrsssss" => ["crisscrosses"],
      "abeiilmnnrty" => ["interminably"], "eegilnnortuv" => ["volunteering"],
      "acceelnnostv" => ["convalescent"], "acehhiloptty" => ["hypothetical"],
      "bdeegiimmnrs" => ["dismembering"], "aciinnoopstt" => ["constipation"],
      "abiilnorsttu" => ["tribulations"], "aabeilmmrsuy" => ["immeasurably"],
      "acemmnoprstt" => ["compartments"], "aeiiiilmrsst" => ["similarities"],
      "aeegimnnostt" => ["segmentation"], "acdiinorssyy" => ["idiosyncrasy"],
      "aaegillnpprw" => ["wallpapering"], "cceeinnnortt" => ["interconnect"],
      "accdeennnotu" => ["countenanced"], "aiimnnorssst" => ["transmission"],
      "aaffiiilnost" => ["affiliations"], "ceghilnooors" => ["chronologies"],
      "eiinoprsssuv" => ["supervisions"], "adegiknnrstu" => ["undertakings"],
      "cceeemmmnnot" => ["commencement"], "adghilnnopry" => ["hydroplaning"],
      "abcinorssttu" => ["subtractions"], "cceeeiimnnrs" => ["reminiscence"],
      "aacdeeiinqsu" => ["inadequacies"], "acceehirrttu" => ["architecture"],
      "aaeilmnnostt" => ["lamentations"], "ceeeinnqsstu" => ["quintessence"],
      "ailnopprtuuy" => ["unpopularity"], "adeiinorsttx" => ["extraditions"],
      "aggiiinnortv" => ["invigorating"], "aadeelllnpru" => ["unparalleled"],
      "cdeegimmnnor" => ["recommending"], "aiiinnnosstu" => ["insinuations"],
      "cceeeinoprsv" => ["preconceives"], "aaccehillmny" => ["mechanically"],
      "ddeefgnoorru" => ["foregrounded"], "cdeeiiinnstv" => ["disincentive"],
      "aeeilrrrsstt" => ["terrestrials"], "cddeiinnostu" => ["discontinued"],
      "aabceiiilpst" => ["capabilities"], "adeeiimnssst" => ["disseminates"],
      "aaggiiinnrtt" => ["ingratiating"], "iinooopprsst" => ["propositions"],
      "aaacdillmrty" => ["dramatically"], "abddeinorstu" => ["subordinated"],
      "aeehnorssttu" => ["southeastern"], "aabcgiikllmn" => ["blackmailing"],
      "acdefiinnstt" => ["disinfectant"], "aabdeeegilrs" => ["disagreeable"],
      "adejmnnorstu" => ["adjournments"], "aceiloprrsuy" => ["precariously"],
      "abceeilnorst" => ["celebrations"], "aceeirsssttu" => ["resuscitates"],
      "accdehilmops" => ["accomplished"], "acdgiinnoort" => ["coordinating"],
      "ccdeeimnrtuv" => ["circumvented"], "aaceimoprstv" => ["comparatives"],
      "aeegilnrsstv" => ["everlastings"], "acegiilorssu" => ["sacrilegious"],
      "aabeeilnprss" => ["inseparables"], "ccgiilnnnovy" => ["convincingly"],
      "cdiinnoorttu" => ["introduction"], "ceeeeiinnprx" => ["inexperience"],
      "aaceilmnostx" => ["exclamations"], "aabceinrrstt" => ["scatterbrain"],
      "abehiilnopst" => ["inhospitable"], "bceilorsstuu" => ["tuberculosis"],
      "aaacceinnqtu" => ["acquaintance"], "aabiklmnstuy" => ["unmistakably"],
      "aciiinoqsstu" => ["acquisitions"], "aehiinoprrss" => ["parishioners"],
      "adefhiloorst" => ["foolhardiest"], "cdeeinrrsttu" => ["unrestricted"],
      "ceeegiinnprx" => ["experiencing"], "ceginnpsstuu" => ["unsuspecting"],
      "eeiilmprssvy" => ["impressively"], "adefiiilqssu" => ["disqualifies"],
      "aeeemmnrsstu" => ["measurements"], "adeeehprssst" => ["spreadsheets"],
      "ceiimmnoprtu" => ["minicomputer"], "bdghiimmnrsu" => ["hummingbirds"],
      "adiiiimnnott" => ["intimidation"], "aacegiilmnns" => ["malignancies"],
      "aeehoprrsstt" => ["stratosphere"], "ccimnnoopstu" => ["compunctions"],
      "beiinorrsttu" => ["retributions"], "acegiilnnrsy" => ["increasingly"],
      "ceeinoprsstu" => ["persecutions"], "aabbegiinrtv" => ["abbreviating"],
      "acfiimnnoort" => ["confirmation"], "aaeegginnrtu" => ["guaranteeing"],
      "ceeiiinrsstu" => ["insecurities"], "acdeeghinnrt" => ["interchanged"],
      "egiinnoprrtv" => ["overprinting"], "aeeginorrstt" => ["interrogates"],
      "aacceegilnrt" => ["accelerating"], "iinooprstttu" => ["prostitution"],
      "eghimnnnoooy" => ["honeymooning"], "aeegillrsstu" => ["legislatures"],
      "befghiinrrsu" => ["refurbishing"], "aceeeilmnpst" => ["mantelpieces"],
      "aceehorrsstt" => ["orchestrates"], "bddfgiillnno" => ["blindfolding"],
      "degiinnrrtuw" => ["underwriting"], "aeimnoprsttu" => ["permutations"],
      "aaeegginortx" => ["exaggeration"], "cceiinnottvy" => ["connectivity"],
      "addefiiilqsu" => ["disqualified"], "aacceeghosst" => ["stagecoaches"],
      "eeghiinrstux" => ["extinguisher"], "abceillnnoos" => ["inconsolable"],
      "aeeemprrsttu" => ["temperatures"], "aaghiinpstxy" => ["asphyxiating"],
      "acefiiinortv" => ["verification"], "eefgiilmnpxy" => ["exemplifying"],
      "aabdeegilrsy" => ["disagreeably"], "aadefgginrsu" => ["safeguarding"],
      "bddeeenorruv" => ["overburdened"], "abdeeilnrssu" => ["undesirables"],
      "acenoorrstvy" => ["conservatory"], "afiiilnnortt" => ["infiltration"],
      "aafiinnosttu" => ["infatuations"], "aeiinnoorstt" => ["orientations"],
      "bdgiiinrsttu" => ["distributing"], "bcinoorrttuy" => ["contributory"],
      "aacgiinnostt" => ["antagonistic"], "deeiiillrsst" => ["distilleries"],
      "aeghhiinstww" => ["whitewashing"], "ciilopsssuuy" => ["suspiciously"],
      "adeeginorrtt" => ["interrogated"], "abeeillnnruv" => ["invulnerable"],
      "eefillpssttu" => ["spitefullest"], "eeginooprrvw" => ["overpowering"],
      "ccdeeeinoprv" => ["preconceived"], "aabbeilrtttu" => ["attributable"],
      "aeehinnopprs" => ["apprehension"], "aacdeelnpstu" => ["encapsulated"],
      "aceefmnoprrs" => ["performances"], "cceeginnnort" => ["reconnecting"],
      "acfillnnotuy" => ["functionally"], "adeiinnorstt" => ["transitioned"],
      "ceeelmnopsst" => ["completeness"], "acdeeeilnsst" => ["delicatessen"],
      "aabcdelloort" => ["collaborated"], "addeegilnnst" => ["disentangled"],
      "acdeehimnrss" => ["merchandises"], "aacfiiinortt" => ["ratification"],
      "acccegiinnor" => ["carcinogenic"], "ceeiinnorstt" => ["intersection"],
      "cefiilnoprty" => ["proficiently"], "ceehilnnorty" => ["incoherently"],
      "aaegikmnrrtw" => ["watermarking"], "cdiimmnnoosu" => ["condominiums"],
      "acdeegklnosw" => ["acknowledges"], "aceiiilrsttv" => ["relativistic"],
      "aacehilmpsty" => ["metaphysical"], "dddehnnooorr" => ["rhododendron"],
      "cdeeelmmnopt" => ["complemented"], "acegimnnopst" => ["compensating"],
      "cdehkloorsst" => ["stockholders"], "deeelnrrsuvy" => ["unreservedly"],
      "abdfginorrsu" => ["surfboarding"], "aeegiinnnrtt" => ["entertaining"],
      "eeeilprssvxy" => ["expressively"], "eehloprrsstu" => ["upholsterers"],
      "aceiinnorrst" => ["incinerators"], "ceinnoorsssu" => ["connoisseurs"],
      "abdeiilnpstu" => ["indisputable"], "cdeeelnptuxy" => ["unexpectedly"],
      "cceillnosuvy" => ["conclusively"], "aacdeeinnrrt" => ["reincarnated"],
      "aeegiinnrtvw" => ["interweaving"], "adeegiinrstt" => ["disintegrate"],
      "aeeehinpprsv" => ["apprehensive"], "aeeimnnorstu" => ["mountaineers"],
      "aceehiinnrst" => ["inheritances"], "aeghioopprst" => ["topographies"],
      "aaciinpprstt" => ["participants"], "abdeiiiilsst" => ["disabilities"],
      "aaaceegnrtvx" => ["extravagance"], "aeinoorrsstt" => ["restorations"],
      "fghhllottuuy" => ["thoughtfully"], "ddeeenorsuvz" => ["rendezvoused"],
      "acciilnorstu" => ["circulations"], "deeimnnrsttu" => ["instrumented"],
      "bbceilmosstu" => ["combustibles"], "aacehillmpty" => ["emphatically"],
      "bceeilmnoptt" => ["contemptible"], "adeeeghlmmrs" => ["sledgehammer"],
      "fgiiimmnnors" => ["misinforming"], "cdellnnoortu" => ["uncontrolled"],
      "aaceffinostt" => ["affectations"], "cdeeiiimorst" => ["mediocrities"],
      "aeefiinrrstt" => ["fraternities"], "aeeegmnnrstt" => ["estrangement"],
      "acehillrstyy" => ["hysterically"], "acefillorsuw" => ["cauliflowers"],
      "aaiiilmprtty" => ["impartiality"], "accdeenorttu" => ["counteracted"],
      "aaciinoossst" => ["associations"], "cdeeirrrssvw" => ["screwdrivers"],
      "aeeinnoprstt" => ["penetrations", "presentation"],
      "deeghiinstux" => ["extinguished"], "cdeinorsstuy" => ["countrysides"],
      "deehiilnqrsu" => ["relinquished"], "acdeeghllnnu" => ["unchallenged"],
      "eeffghiirrst" => ["firefighters"], "aabceiillnpp" => ["inapplicable"],
      "aaeeillqrstu" => ["equilaterals"], "bcgiilmooory" => ["microbiology"],
      "aacceeinrrst" => ["incarcerates"], "acinoooprstv" => ["provocations"],
      "ceiimmnoorss" => ["commissioner"], "aacfgiiilntt" => ["facilitating"],
      "acgiiinnottx" => ["intoxicating"], "aaccgiinrrtu" => ["caricaturing"],
      "ceiiprrrsttw" => ["scriptwriter"], "aefgiilrtuvy" => ["figuratively"],
      "aabceikllmrs" => ["blackmailers"], "aeefiloprrst" => ["proliferates"],
      "cccgiiimnrsu" => ["circumcising"], "bdhiloorstty" => ["bloodthirsty"],
      "begiilnnprtu" => ["blueprinting"], "eehinrssstyz" => ["synthesizers"],
      "ceffiilnstuy" => ["sufficiently"], "abciilnopstu" => ["publications"],
      "bcekkoorrsst" => ["stockbrokers"], "aeeggilrssvy" => ["aggressively"],
      "bdeegiiilnst" => ["indigestible"], "aceeegiknrrt" => ["racketeering"],
      "aginooprsstt" => ["protagonists"], "deeeinnrsttu" => ["uninterested"],
      "accdeennortt" => ["concentrated"], "deegiilmnnrt" => ["intermingled"],
      "aabfllmnotyy" => ["flamboyantly"], "aeggiiilmntt" => ["legitimating"],
      "aadeilnorttu" => ["adulteration"], "aaeimnoooopt" => ["onomatopoeia"],
      "defgiiinrsvy" => ["diversifying"], "aeeghnoprrst" => ["stenographer"],
      "bdehhooorrst" => ["brotherhoods"], "acceeiilnrst" => ["electricians"],
      "aaaccdeillmy" => ["academically"], "aceeelnrssss" => ["carelessness"],
      "adgiiiimnntt" => ["intimidating"], "acdeginnnrst" => ["transcending"],
      "acdeiiimnrst" => ["discriminate"], "accehilmopss" => ["accomplishes"],
      "afinnorssstu" => ["transfusions"], "aefgggilnopr" => ["leapfrogging"],
      "addeemnorstt" => ["demonstrated"], "cdeeeiinprss" => ["presidencies"],
      "aacegiimnnpt" => ["emancipating"], "aeeillnqstuy" => ["sequentially"],
      "aceggginnort" => ["congregating"], "aaddiillnoty" => ["additionally"],
      "deefiilnnrru" => ["unfriendlier"], "aaggiillnntv" => ["gallivanting"],
      "deefiiiilnst" => ["infidelities"], "aceeginorrtv" => ["overreacting"],
      "ceehikmnosss" => ["homesickness"], "aceeinoprrtu" => ["recuperation"],
      "aeeinoprrstv" => ["preservation"], "aacegiinpprt" => ["appreciating"],
      "deeinnnorsst" => ["nonresidents"], "aaciinnnorst" => ["incarnations"],
      "aefilnooprss" => ["professional"], "aabelnnorsuy" => ["unreasonably"],
      "ceefiimnoprt" => ["imperfection"], "abcdeinoorst" => ["noticeboards"],
      "aaabcehloppr" => ["approachable"], "aeeillnrrstt" => ["interstellar"],
      "acdeeimmorst" => ["commiserated"], "aaccillnoosy" => ["occasionally"],
      "achhiimnopps" => ["championship"], "ceeiijnnortt" => ["interjection"],
      "ehiilmrssstv" => ["silversmiths"], "ceeiinnnnotv" => ["inconvenient"],
      "aabcelloorst" => ["collaborates"], "aceeginprrtu" => ["recuperating"],
      "aceinooprrst" => ["incorporates"], "aciiilmnptuy" => ["municipality"],
      "aaabcehillpt" => ["alphabetical"], "aeegiinssttv" => ["investigates"],
      "aaccceiinrsu" => ["inaccuracies"], "aceemnnnnotu" => ["announcement"],
      "ceeeeffnrstv" => ["effervescent"], "aefgillnorst" => ["forestalling"],
      "aceeghilnrtw" => ["cartwheeling"], "aaceeklmprst" => ["marketplaces"],
      "aaceilmrsttu" => ["matriculates"], "cdeginnorrsu" => ["underscoring"],
      "egiiinnnrttw" => ["intertwining"], "aacilnorstvy" => ["clairvoyants"],
      "cdeeeeiinpsx" => ["expediencies"], "aehioprrstwy" => ["praiseworthy"],
      "eilmorsstuyy" => ["mysteriously"], "aaeimopprstx" => ["approximates"],
      "aabdegiimstu" => ["disambiguate"], "aciilnnoostu" => ["inoculations"],
      "deeenorssuvz" => ["rendezvouses"], "aacgiilnpttu" => ["capitulating"],
      "abcceilmmnou" => ["communicable"], "aeeimnnorrtu" => ["remuneration"],
      "aceimnorsstv" => ["conservatism"], "aadeflmnnstu" => ["fundamentals"],
      "eemnnooppstt" => ["postponement"], "cddeeehmnopr" => ["comprehended"],
      "aaccillnostu" => ["calculations"], "eeeinprrrstt" => ["interpreters"],
      "acdeimmnnoot" => ["commendation"], "ciimnooopsst" => ["compositions"],
      "aabeehiilrtt" => ["rehabilitate"], "ceeghilnoost" => ["technologies"],
      "aeeeglmnnntt" => ["entanglement"], "cegimnnnosst" => ["consignments"],
      "abiiillpstuy" => ["plausibility"], "abdegiiilntt" => ["debilitating"],
      "adeeiinprsss" => ["dispensaries"], "aaccgimnnopy" => ["accompanying"],
      "aaeilllnrtuy" => ["unilaterally"], "aaeghiilnrtx" => ["exhilarating"],
      "acdeeikloops" => ["kaleidoscope"], "abdeefiiilnt" => ["identifiable"],
      "ceilmooprssu" => ["compulsories"], "achnnoorssuy" => ["asynchronous"],
      "acddeinosttu" => ["outdistanced"], "bdeghhoorrtu" => ["thoroughbred"],
      "aadeeghinprs" => ["spearheading"], "abceeiilnnnt" => ["bicentennial"],
      "emopprsstuuu" => ["presumptuous"], "bdeeiirrsttu" => ["redistribute"],
      "accimmnoortu" => ["communicator"], "aacceelorrst" => ["accelerators"],
      "aeghimnorsuw" => ["housewarming"], "aafiilmmnnot" => ["inflammation"],
      "aadegnnprrst" => ["grandparents"], "aaadegnostuv" => ["advantageous"],
      "eeoopprrsstu" => ["preposterous"], "acghhioopprt" => ["photographic"],
      "aadegoprsttu" => ["postgraduate"], "cdeginnrttuu" => ["undercutting"],
      "abcdeinrsstu" => ["disturbances"], "ceiinnorrstu" => ["insurrection"],
      "behhoorssttu" => ["toothbrushes"], "eegghiilnnnt" => ["enlightening"],
      "acceginnorst" => ["consecrating"], "acilnnoosttu" => ["consultation"],
      "ceegiijnnrtt" => ["interjecting"], "ceghiinnrsst" => ["christenings"],
      "ceiinnnosstt" => ["inconsistent"], "acfiiinoprtu" => ["purification"],
      "cceiilnnosuv" => ["inconclusive"], "aiilmnnorttu" => ["malnutrition"],
      "cdeffiiilstu" => ["difficulties"], "aaceillmmtuy" => ["immaculately"],
      "bcdgiikmnors" => ["mockingbirds"], "diiinoopssst" => ["dispositions"],
      "acilmmnnoott" => ["noncommittal"], "ceeeiiprrstv" => ["irrespective"],
      "clloprssuuuy" => ["scrupulously"], "abdeinorsstu" => ["subordinates"],
      "aaccdeillnty" => ["accidentally"], "eginooprrsss" => ["progressions"],
      "aabceeeghlrr" => ["rechargeable"], "egiinnnortvy" => ["inventorying"],
      "aeeeilmnprtx" => ["experimental"], "cgiinnostttu" => ["constituting"],
      "aaeoopprrrst" => ["paratroopers"], "inoopprssttu" => ["opportunists"],
      "abcgiklnoppt" => ["blacktopping"], "aabeilnoorst" => ["elaborations"],
      "aciiilnnnost" => ["inclinations"], "ahhilnopprty" => ["philanthropy"],
      "eimnopprsstu" => ["presumptions"], "ciiillmpttuy" => ["multiplicity"],
      "aacegginopst" => ["scapegoating"], "ceefimnnnost" => ["confinements"],
      "aeiiilmnnost" => ["eliminations"], "addeeiimnrst" => ["administered"],
      "aeeijnnortuv" => ["rejuvenation"], "aaadeinsssst" => ["assassinated"],
      "accdeeelnoss" => ["adolescences"], "aeeeimnrsttx" => ["exterminates"],
      "acemnooprrty" => ["contemporary"], "ceeeinorstux" => ["executioners"],
      "acciiilnnoot" => ["conciliation"], "abeeeilmnprt" => ["impenetrable"],
      "aacciiorrstt" => ["aristocratic"], "eeeehnnssttv" => ["seventeenths"],
      "aehinpprrsst" => ["partnerships"], "ahiiilmnostu" => ["humiliations"],
      "eeghlmnnoors" => ["longshoremen"], "agiillnrsttu" => ["illustrating"],
      "agiiklmnsttu" => ["multitasking"], "abeeeerrrstv" => ["reverberates"],
      "aeiiimnorsss" => ["missionaries"], "iiinnosstttu" => ["institutions"],
      "aeeiinnprtty" => ["penitentiary"], "acdemmmnnost" => ["commandments"],
      "aceeefffrstt" => ["aftereffects"], "aacegghilopr" => ["geographical"],
      "cdiiinnosstt" => ["distinctions"], "adeinooprstt" => ["deportations"],
      "beeeirsstttw" => ["bittersweets"], "aadegilnrttu" => ["adulterating"],
      "abeghhkorrtu" => ["breakthrough"], "aegghilnrstu" => ["slaughtering"],
      "aciiilmnopst" => ["implications"], "bcehiimorsty" => ["biochemistry"],
      "eeeimnprrsst" => ["misrepresent"], "aeeeginnorrt" => ["regeneration"],
      "adeiinnosstt" => ["destinations"], "cdiioprttuvy" => ["productivity"],
      "cdgiiinnnoot" => ["conditioning"], "acdeemmmoort" => ["commemorated"],
      "aceiinnnortu" => ["renunciation"], "ccceeiinrtty" => ["eccentricity"],
      "aeginoorrrtt" => ["interrogator"], "aeghopprrsss" => ["grasshoppers"],
      "aabcceirrtuu" => ["bureaucratic"], "aceegilssttu" => ["gesticulates"],
      "cceinorsttuv" => ["constructive"], "aacciilprtty" => ["practicality"],
      "acgiinnnorst" => ["constraining"], "aiimnooprstt" => ["importations"],
      "adegiimnnprr" => ["reprimanding"], "aacefmnrrtuu" => ["manufacturer"],
      "aeiiillmnors" => ["millionaires"], "abcgiinnrrst" => ["transcribing"],
      "bdiiorrssttu" => ["distributors"], "ceefllprstuy" => ["respectfully"],
      "aacehilmoprt" => ["metaphorical"], "adefginooprr" => ["proofreading"],
      "aacillprrtuy" => ["particularly"], "aeeinoortttx" => ["extortionate"],
      "acehiintttuy" => ["authenticity"], "acgijnnoostu" => ["conjugations"],
      "aabeiloorrst" => ["laboratories"], "cdeiinnoorst" => ["reconditions"],
      "aeeggirrsttu" => ["regurgitates"], "aceghhilrsst" => ["searchlights"],
      "ceiinopprrst" => ["prescription"], "aabbeilnnotu" => ["unobtainable"],
      "aaceimnnostt" => ["contaminates"], "acceefiirstt" => ["certificates"],
      "bdiiinorsttu" => ["distribution"], "bgiinsstttuu" => ["substituting"],
      "accdeimnortu" => ["undemocratic"], "aabbeirrsttu" => ["barbiturates"],
      "iiiinnoqsstu" => ["inquisitions"], "aceiiimnnrst" => ["incriminates"],
      "beeeelmmntzz" => ["embezzlement"], "aacgiilnrttu" => ["articulating"],
      "aaceiipprstt" => ["participates"], "aadeehqrrstu" => ["headquarters"],
      "aeggiimnnprt" => ["impregnating"], "aacinnorsstt" => ["transactions"],
      "ceeeklnrssss" => ["recklessness"], "aeegijnnrtuv" => ["rejuvenating"],
      "ailnooopprrt" => ["proportional"], "aaccgilmntuu" => ["accumulating"],
      "cddeeeinorrs" => ["reconsidered"], "aaceiinopprt" => ["appreciation"],
      "aacdeemnnstv" => ["advancements"], "eeelnrssssst" => ["restlessness"],
      "aadegiinpprs" => ["disappearing"], "ceeiinnoprtt" => ["interception"],
      "abcelllnoort" => ["controllable"], "ceiimnoopstt" => ["competitions"],
      "cceeeinnnosv" => ["conveniences"], "aacdeiipprtt" => ["participated"],
      "aaahiimnnrtu" => ["humanitarian"], "degiinnossuu" => ["disingenuous"],
      "addeefhoorsw" => ["foreshadowed"], "deegiinppsst" => ["sidestepping"],
      "abceiilmnopt" => ["incompatible"], "eiimmnnoprst" => ["imprisonment"],
      "bdeegiimnorr" => ["embroidering"], "abeeiilmnnrt" => ["interminable"],
      "aefimnoorrst" => ["reformations"], "abciilmnopty" => ["incompatibly"],
      "cemnoopsttuu" => ["contemptuous"], "aaeghlmnrstu" => ["manslaughter"],
      "aaeilnoprrst" => ["proletarians"], "eeeginnprrst" => ["representing"],
      "cceflnsssuuu" => ["unsuccessful"], "ccceennorrsu" => ["concurrences"],
      "aaabiiilltvy" => ["availability"], "aciinnnoottu" => ["continuation"],
      "ceeimnnopstt" => ["incompetents"], "agiimnnrsttt" => ["transmitting"],
      "acdeeeinsstt" => ["necessitated"], "cgiimmnooprs" => ["compromising"],
      "adeiimnnnoot" => ["denomination"], "giinoprstttu" => ["prostituting"],
      "ccegiknorrsw" => ["corkscrewing"], "aaeiimnnostx" => ["examinations"],
      "aeilmnnrsttu" => ["instrumental"], "adgiinopprsv" => ["disapproving"],
      "adeeegimnrst" => ["disagreement"], "accegiiknrsw" => ["wisecracking"],
      "ceehklnossuy" => ["honeysuckles"], "aeeghipprstw" => ["paperweights"],
      "efgiinnprrst" => ["fingerprints"], "eegiilmmnnpt" => ["implementing"],
      "cfgiiilmmnor" => ["microfilming"], "aceeehimnstv" => ["achievements"],
      "eginoppprssu" => ["presupposing"], "ciiinnoprsst" => ["inscriptions"],
      "ccddeeinorst" => ["disconcerted"], "begimnnortuu" => ["outnumbering"],
      "aadeelmnprtt" => ["departmental"], "aaccdeeinrrt" => ["incarcerated"],
      "ccciiimnorsu" => ["circumcision"], "aabceilmnopr" => ["incomparable"],
      "eeiinopprsst" => ["propensities"], "aacceilmprst" => ["malpractices"],
      "acdeinooprrt" => ["incorporated"], "abcdhiorsstw" => ["switchboards"],
      "abcceemnnrsu" => ["encumbrances"], "aaciillrstty" => ["artistically"],
      "aabccelnptuy" => ["unacceptably"], "acceillmnooy" => ["economically"],
      "cddeeeeinnnp" => ["independence"], "eeekloopppss" => ["spokespeople"],
      "egilnoorsstu" => ["neurologists"], "acinoooprrst" => ["corporations"],
      "abcdgiklnoor" => ["roadblocking"], "gghhinoorsuu" => ["roughhousing"],
      "accdeefiirtt" => ["certificated"], "deinooopprrt" => ["proportioned"],
      "aegimnnrsttu" => ["menstruating"], "cdeeilmmnopt" => ["complimented"],
      "adeehirrrsss" => ["hairdressers"], "acegillmooty" => ["etymological"],
      "adeefooprrtw" => ["waterproofed"], "aacegillnort" => ["reallocating"],
      "gghiilmnnoot" => ["moonlighting"], "aagiilmnnptu" => ["manipulating"],
      "adeelmorsstu" => ["somersaulted"], "agiiinnoprtt" => ["partitioning"],
      "aceffghinruu" => ["chauffeuring"], "eghilnoprstu" => ["upholstering"],
      "bcegiiilnorr" => ["incorrigible"], "aaceillrttuy" => ["articulately"],
      "ddeehiiinrst" => ["disinherited"], "gghiilnopstt" => ["spotlighting"],
      "cdeeioprrtuv" => ["reproductive"], "bceghimnnooy" => ["honeycombing"],
      "acceeioprrst" => ["reciprocates"], "eehiilnqrssu" => ["relinquishes"],
      "acinnnooostt" => ["connotations"], "acceiinoprss" => ["conspiracies"],
      "adeegnrrssst" => ["transgressed"], "ceefinorsttu" => ["counterfeits"],
      "aabeennrrstu" => ["subterranean"], "aegilmnoprsv" => ["oversampling"],
      "eeknoopprsss" => ["spokesperson"], "giilnprrssuy" => ["surprisingly"],
      "acchiiloprty" => ["hypocritical"], "defhinprsstt" => ["spendthrifts"],
      "eeghiilnnprs" => ["replenishing"], "ccdeeefiiins" => ["deficiencies"],
      "abdeeinnrrsw" => ["breadwinners"], "accellnoptuy" => ["conceptually"],
      "aeeeglmnnrst" => ["enlargements"], "acceillmmory" => ["commercially"],
      "cdgiiiilnnps" => ["disciplining"], "eeghiinsstux" => ["extinguishes"],
      "acdeeirssttu" => ["resuscitated"], "aaiillnorrty" => ["irrationally"],
      "aacgiiinnptt" => ["anticipating"], "aceilnoorrst" => ["correlations"],
      "acdeegilsttu" => ["gesticulated"], "acdhhinoopry" => ["hypochondria"],
      "ggiiillnnotu" => ["guillotining"], "aaceiimnnopt" => ["emancipation"],
      "ceegiinnrstt" => ["intersecting"], "eegiilmnnrst" => ["intermingles"],
      "ceeiklmnppru" => ["pumpernickel"], "adeegiknnrrt" => ["kindergarten"],
      "acehlmmnootw" => ["commonwealth"], "ceeillorssty" => ["electrolysis"],
      "aaegiinprrtt" => ["repatriating"], "abbeeeillnuv" => ["unbelievable"],
      "aaciilnorttu" => ["articulation"], "adeiinoprstu" => ["repudiations"],
      "acdeeefnorst" => ["confederates"], "adeegiinsttv" => ["investigated"],
      "aadeeloprttx" => ["extrapolated"], "aaehiilnortx" => ["exhilaration"],
      "aabeeklmnrru" => ["unremarkable"], "ahillnoortyz" => ["horizontally"],
      "cdeeeffiinnr" => ["indifference"], "agilorsttuuy" => ["gratuitously"],
      "bbceklorsstu" => ["blockbusters"], "aacfiinnosst" => ["fascinations"],
      "aefghhortttu" => ["afterthought"], "eiinoopprsst" => ["prepositions"],
      "aafiilnnorty" => ["inflationary"], "ceeeipprsstv" => ["perspectives"],
      "aeilnoortuvy" => ["evolutionary"], "aaceknnorstu" => ["cantankerous"],
      "acdiiinoosst" => ["dissociation"], "aaceiilnrttu" => ["inarticulate"],
      "acdfiiimnoot" => ["modification"], "aeiilmnosstt" => ["testimonials"],
      "cceillooopss" => ["oscilloscope"], "acddeeinnrsu" => ["redundancies"],
      "cdeeehiloprt" => ["helicoptered"], "abdeeeillrty" => ["deliberately"],
      "ccddeeinnost" => ["disconnected"], "aacfggilmnou" => ["camouflaging"],
      "egghhiilsttw" => ["lightweights"], "acehiiopsstt" => ["sophisticate"],
      "eeimnnnorstv" => ["environments"], "acdeiinnortt" => ["indoctrinate"],
      "aagiinnortuu" => ["inauguration"], "aeeglmnnortv" => ["governmental"],
      "eiimnnooprst" => ["premonitions"], "aeiilorrrstt" => ["territorials"],
      "aachimnnorss" => ["anachronisms"], "dggiilnsstuy" => ["disgustingly"],
      "aagiiilmnsst" => ["assimilating"], "egilmnooostt" => ["entomologist"],
      "acfiiinnoott" => ["notification"], "ddeefiiinntu" => ["unidentified"],
      "acegiinnpprt" => ["apprenticing"], "abdeiiirsssu" => ["subsidiaries"],
      "aeegiillmtty" => ["legitimately"], "aaagghinpprr" => ["paragraphing"],
      "cdegiiimnrst" => ["misdirecting"], "accegilllooy" => ["ecologically"],
      "aacdeilmmort" => ["melodramatic"], "aghiloopsstt" => ["pathologists"],
      "cegiiklnnort" => ["interlocking"], "aacehillptty" => ["pathetically"],
      "acegloorsuuy" => ["courageously"], "aaccimnopsst" => ["accompanists"],
      "acdeeiipprtt" => ["precipitated"], "abdginoprrss" => ["springboards"],
      "adeeeiorrstt" => ["deteriorates"],
      "acdeilnoosst" => ["consolidates", "disconsolate"],
      "aaeiilmrsstt" => ["materialists"], "aaceeilnorrt" => ["recreational"],
      "hlmoopsstuuy" => ["posthumously"], "ccdeimnoorss" => ["microseconds"],
      "aaagginorstv" => ["aggravations"], "aabeinsstttu" => ["substantiate"],
      "beeegillnrst" => ["belligerents"], "aeilnooprstx" => ["explorations"],
      "aaacegilmmno" => ["megalomaniac"], "aceeglmnoort" => ["conglomerate"],
      "ddefnoooprsu" => ["soundproofed"], "eeefhmnrrsst" => ["refreshments"],
      "aciilmnnostu" => ["culminations"], "accdeeioprrt" => ["reciprocated"],
      "abeeklmorrtu" => ["troublemaker"], "aacdegiinptt" => ["decapitating"],
      "aacceginnttu" => ["accentuating"], "cdeioorsstuu" => ["discourteous"],
      "adiiilnoqstu" => ["liquidations"], "acdeeimnnopr" => ["predominance"],
      "eefgiimnnnrt" => ["infringement"], "bcgiinnorttu" => ["contributing"],
      "acceefikrrrs" => ["firecrackers"], "aagiiimnnost" => ["imaginations"],
      "acceennorstt" => ["concentrates"], "abdeimnorrst" => ["brainstormed"],
      "addeeeiorrtt" => ["deteriorated"], "acddeehimnrs" => ["merchandised"],
      "aacceennostt" => ["concatenates"], "aeegioprrstv" => ["prerogatives"],
      "abbdemmnorst" => ["bombardments"], "adefllnrtuuy" => ["fraudulently"],
      "aaceiilmnstx" => ["anticlimaxes"], "aegiinnorsst" => ["resignations"],
      "aaaeinssssst" => ["assassinates"], "abegiilnortt" => ["obliterating"],
      "acddeegklnow" => ["acknowledged"], "accdeiklnsst" => ["candlesticks"],
      "aacdghiinnpp" => ["handicapping"], "aeegghilnprt" => ["telegraphing"],
      "acegginnoort" => ["congregation"], "acdeeiinoprt" => ["depreciation"],
      "cceeilsssuvy" => ["successively"], "acillmorsuuy" => ["miraculously"],
      "deeemnnorsst" => ["endorsements"], "abeeilnoqstu" => ["questionable"],
      "acdeiiimnnrt" => ["incriminated"], "aaciiinssttt" => ["statistician"],
      "eeeiilpprstx" => ["perplexities"], "efhlnrssttuu" => ["truthfulness"],
      "aaaghinpprrs" => ["paraphrasing"], "aacfiiillrty" => ["artificially"],
      "aaaiilnorttt" => ["totalitarian"], "accgiilmnopt" => ["complicating"],
      "aafilmmnorty" => ["inflammatory"], "aabcinorsstt" => ["abstractions"],
      "deegiilnpruv" => ["unprivileged"], "cceegillnort" => ["recollecting"],
      "aaeeggginrtx" => ["exaggerating"], "aaabeilnnttu" => ["unattainable"],
      "accefgiiinns" => ["significance"], "aaciilnoppst" => ["applications"],
      "acdgiiinosst" => ["dissociating"], "eegioprrsssv" => ["progressives"],
      "ciinnorssttu" => ["instructions"], "eeehmmorrstt" => ["thermometers"],
      "ceghiiknprsw" => ["shipwrecking"], "acdiiilnprsy" => ["disciplinary"],
      "aeeimnoprsst" => ["impersonates"], "eehiimoprssv" => ["impoverishes"],
      "aeegiiillmtt" => ["illegitimate"], "aeeehlorstux" => ["heterosexual"],
      "eeghhinoorss" => ["horseshoeing"], "aceeeenprrsv" => ["perseverance"],
      "aceeilllnttu" => ["intellectual"], "abceiillnpxy" => ["inexplicably"],
      "accinnoorstt" => ["contractions"], "ceeeiimnnprt" => ["impertinence"],
      "ceeegiillnnt" => ["intelligence"], "acdeehorrstt" => ["orchestrated"],
      "ceeilnnnotvy" => ["conveniently"], "aaacehilmmtt" => ["mathematical"],
      "aghlnoooprty" => ["anthropology"], "ceeinoprrssu" => ["repercussion"],
      "eghiilnosttu" => ["silhouetting"], "abdeefillstt" => ["battlefields"],
      "aaeegmnoprst" => ["pomegranates"], "aeeghhistvwy" => ["heavyweights"],
      "cdeiillmnoss" => ["milliseconds"], "ccinnoorsttu" => ["construction"],
      "aaeeklnrsstt" => ["rattlesnakes"], "cceeefhiknrs" => ["neckerchiefs"],
      "accefiillpsy" => ["specifically"], "deehiimoprsv" => ["impoverished"],
      "eeeiipqrrstu" => ["prerequisite"], "acdiilnoosst" => ["dislocations"],
      "ccgilmnoorty" => ["motorcycling"], "aaeilnnopstx" => ["explanations"],
      "aeeilprsstuv" => ["superlatives"], "adeeggirrttu" => ["regurgitated"],
      "cdeinooprrtu" => ["reproduction"], "abcgggiiknpy" => ["piggybacking"],
      "cgghiinoprty" => ["copyrighting"], "cdeiilnnppru" => ["unprincipled"],
      "abeeirrrsstw" => ["strawberries"], "aacfiorsstty" => ["satisfactory"],
      "eehnorssttuw" => ["southwestern"], "aaegiinprttx" => ["expatriating"],
      "aceilnnnostt" => ["continentals"], "cceginoppruy" => ["preoccupying"],
      "acddeeimostt" => ["domesticated"], "aeeiiilnqstu" => ["inequalities"],
      "dddeeinrstuu" => ["understudied"], "addeeimmnrst" => ["masterminded"],
      "aceeeinssstt" => ["necessitates"], "aiiinnoprsst" => ["inspirations"],
      "ceffiiinnstu" => ["insufficient"], "aabeeflnrrst" => ["transferable"],
      "ggghhhiiilnt" => ["highlighting"], "aaiilmnnoptu" => ["manipulation"],
      "eehinnoprsty" => ["hypertension"], "defiinoprstu" => ["profundities"],
      "egiillmnpsss" => ["misspellings"], "aacchioprstt" => ["catastrophic"],
      "aaeeginprstx" => ["exasperating"], "aacgillrrtuu" => ["agricultural"],
      "aegiinorsttv" => ["investigator"], "ceipprrssstu" => ["superscripts"],
      "aaeeilnrsttv" => ["alternatives"], "eeiiooprrsst" => ["repositories"],
      "abdeegiilnrt" => ["deliberating"], "acceefgiimnn" => ["magnificence"],
      "aadeioppprrt" => ["appropriated"], "eeeimnqrrstu" => ["requirements"],
      "aehiilnoprst" => ["relationship"], "eeghilmnorvw" => ["overwhelming"],
      "aciiinnoottx" => ["intoxication"], "aacciinnostv" => ["vaccinations"],
      "abceiknprstu" => ["bankruptcies"], "aefiinnosstt" => ["infestations"],
      "bddfgimnnouu" => ["dumbfounding"], "aabceeginrtx" => ["exacerbating"],
      "cdiillorsuuy" => ["ridiculously"], "agiiillmnntu" => ["illuminating"],
      "ceegimnnoprs" => ["recompensing"], "aceeinorstvv" => ["conservative"],
      "ccenorrssttu" => ["reconstructs"], "abeeeemnrstv" => ["bereavements"],
      "afgiiilnnrtt" => ["infiltrating"], "abceeemmnrrs" => ["remembrances"],
      "adeemnorsstt" => ["demonstrates"], "aabceilorsuv" => ["vocabularies"],
      "aeilmnooprtt" => ["metropolitan"], "cghiloopssty" => ["psychologist"],
      "aabccgijkkln" => ["blackjacking"], "aacefmnrstuu" => ["manufactures"],
      "dehlnoorrsuy" => ["horrendously"], "eeiiinrsstuv" => ["universities"],
      "adeegilnnsst" => ["disentangles"], "adeeegginnrt" => ["degenerating"],
      "bdeeeiimorrs" => ["embroideries"], "aeiiinnrsttv" => ["intransitive"],
      "bcddeeeiinos" => ["disobedience"], "aacilmnoorst" => ["astronomical"],
      "acdeiiinorst" => ["dictionaries"], "acdeeilmnpst" => ["displacement"],
      "abceeiillnpx" => ["inexplicable"], "abeiilnoortt" => ["obliteration"],
      "eeegiinorsst" => ["generosities"], "eeeinprrssst" => ["intersperses"],
      "aehinoorsttx" => ["exhortations"], "aacennprrsty" => ["transparency"],
      "aabcfiinorst" => ["fabrications"], "ceghiloopssy" => ["psychologies"],
      "giinopprsttu" => ["outstripping"], "eghinooorstv" => ["overshooting"],
      "cdeiimmnooss" => ["commissioned"], "abiiiilrrtty" => ["irritability"],
      "aceeghinnrst" => ["interchanges"], "adeegmnnrrtu" => ["undergarment"],
      "aabcekqrrstu" => ["quarterbacks"], "addeeehinrst" => ["disheartened"],
      "afilmnoorstu" => ["formulations"], "acdefiilnnot" => ["confidential"],
      "aacgilloorst" => ["astrological"], "ceeginnnortu" => ["encountering"],
      "eefgiinoprrt" => ["profiteering"], "aceeginnprrt" => ["carpentering"],
      "aeimnnorsttu" => ["menstruation"], "cddeeeiorrsv" => ["rediscovered"],
      "adeeiimnrrty" => ["intermediary"], "acemmnoorstt" => ["commentators"],
      "acdeiiinppst" => ["appendicitis"], "acceennnostu" => ["countenances"],
      "aacdeimnorsy" => ["aerodynamics"], "eefilnnqrtuy" => ["infrequently"],
      "abbceeiklrrs" => ["blackberries"], "cddefimoorst" => ["discomforted"],
      "aaceglnorttu" => ["congratulate"], "aaceeinnrrst" => ["reincarnates"],
      "acegghinorrv" => ["overcharging"], "aabcceilllnu" => ["incalculable"],
      "aceeiooprstv" => ["cooperatives"], "aabddeekorst" => ["skateboarded"],
      "afgimnnorrst" => ["transforming"], "aceegiilnstv" => ["evangelistic"],
      "abcgiilllooy" => ["biologically"], "ceimnorssstu" => ["misconstrues"],
      "acefgiiilmns" => ["facsimileing"], "adegiinnosst" => ["designations"],
      "bdeeimnrsstu" => ["disbursement"], "aaccelprsstu" => ["spectaculars"],
      "acdeeimnprst" => ["predicaments"], "acegiiinnnrt" => ["incinerating"],
      "aeefimnnortt" => ["fermentation"], "ademnoorrstt" => ["demonstrator"],
      "bciinoprsstu" => ["subscription"], "eiiinoqrsstu" => ["requisitions"],
      "eeeiinrrstvw" => ["interviewers"], "ceeiinoprstt" => ["receptionist"],
      "beelnqsstuuy" => ["subsequently"], "aeehhilnsttu" => ["unhealthiest"],
      "cddeemnnotuu" => ["undocumented"], "aahiiilnnnot" => ["annihilation"],
      "ceegiinnprtt" => ["intercepting"], "aabeiklmnstu" => ["unmistakable"],
      "aabimnorsttu" => ["masturbation"], "acdhiioprstt" => ["dictatorship"],
      "aeffknrrrstu" => ["frankfurters"], "begiimnrsttu" => ["resubmitting"],
      "effgiinooprr" => ["fireproofing"], "aeeginpprttu" => ["perpetuating"],
      "abdeimorstux" => ["ambidextrous"], "abeghiilnsst" => ["establishing"],
      "aceeiipprstt" => ["precipitates"], "aadddegnnrst" => ["grandstanded"],
      "ccefllsssuuy" => ["successfully"], "aaceelnpsstu" => ["encapsulates"],
      "aaceillmnsty" => ["semantically"], "aeiillrsttuv" => ["illustrative"],
      "addeeimnoprt" => ["predominated"], "aacdeimnnott" => ["contaminated"],
      "cefiloorsuvy" => ["vociferously"], "beeiiilrrsst" => ["irresistible"],
      "adiiillnostt" => ["distillation"], "cceeffiiinny" => ["inefficiency"],
      "bceeilnorstv" => ["convertibles"], "adeimnnoorst" => ["denominators"],
      "efgiiinnnsty" => ["intensifying"], "aegloorstuuy" => ["outrageously"],
      "aaceenrrsssu" => ["reassurances"], "acdeiillnnty" => ["incidentally"],
      "aceeelmnprst" => ["replacements"], "ceghhiilopry" => ["hieroglyphic"],
      "aaaddeginstv" => ["disadvantage"], "deelmnorstuy" => ["tremendously"],
      "aadeginnpprs" => ["sandpapering"], "aabcceelnptu" => ["unacceptable"],
      "aeiilnoopttx" => ["exploitation"], "aefginnrrrst" => ["transferring"],
      "ccijnnnoostu" => ["conjunctions"], "addefiiissst" => ["dissatisfied"],
      "deeeemoprsst" => ["speedometers"], "aiilnopssttu" => ["stipulations"],
      "aaeeilnprsst" => ["pleasantries"], "aaeeloprsttx" => ["extrapolates"],
      "aaceeiipprtv" => ["appreciative"], "eeiinnnorttv" => ["intervention"],
      "aabcehilnrtu" => ["uncharitable"], "aadeeilnqtuy" => ["inadequately"],
      "ceginnorsstu" => ["countersigns"], "aahiinopstxy" => ["asphyxiation"],
      "aaeiinqtttuv" => ["quantitative"], "abdeiiilmnss" => ["inadmissible"],
      "aeeginpprrtt" => ["perpetrating"], "adghiinnsttw" => ["withstanding"],
      "abcceeiilnss" => ["inaccessible"], "aaceegillnsv" => ["evangelicals"],
      "aeiinopprrst" => ["perspiration"], "bccehorstttu" => ["butterscotch"],
      "aacfiiimnort" => ["ramification"], "addeehoorsvw" => ["overshadowed"],
      "aaciinnnostt" => ["incantations"], "dginnorrssuu" => ["surroundings"],
      "aabeelnnossu" => ["unseasonable"], "abeehlorrsww" => ["wheelbarrows"],
      "acdhhioprrss" => ["harpsichords"], "aceilnopsstu" => ["speculations"],
      "cghimnoorsst" => ["shortcomings"], "aabeelnnrsuw" => ["unanswerable"],
      "acfilnosttuu" => ["fluctuations"], "aachllnnnoty" => ["nonchalantly"],
      "accfgiinnost" => ["confiscating"], "bghilnnoottu" => ["buttonholing"],
      "aehiiimnnstu" => ["inhumanities"], "ddeeiopsssss" => ["dispossessed"],
      "ceehoopssstt" => ["stethoscopes"], "adeiinoprstv" => ["deprivations"],
      "cciinnoorstt" => ["constriction"], "eimooprssttt" => ["optometrists"],
      "ccghhinoopst" => ["hopscotching"], "addeeeopprsv" => ["eavesdropped"],
      "adeeehhlortw" => ["wholehearted"], "cdeimnorsstu" => ["misconstrued"],
      "aacfiinosstt" => ["satisfaction"], "addeiinoppst" => ["disappointed"],
      "ceeopprssstu" => ["prospectuses"], "aacchiimrsst" => ["charismatics"],
      "eimnoooprrst" => ["promontories"], "deeimopprssu" => ["superimposed"],
      "eegiinnprrtt" => ["interpreting"], "aeeefgirrrst" => ["refrigerates"],
      "aeegimnnrrtu" => ["remunerating"], "bciinnoorttu" => ["contribution"],
      "deefiilnnrss" => ["friendliness"], "aaceehintttu" => ["authenticate"],
      "abdeiiilrsty" => ["desirability"], "cdinoorrttuy" => ["introductory"],
      "cddeenooprrs" => ["corresponded"], "abdeeiilnort" => ["deliberation"],
      "abceehorsttx" => ["chatterboxes"], "bccinoosssuu" => ["subconscious"],
      "aabeeilmmrsu" => ["immeasurable"], "aeeegginnrrt" => ["regenerating"],
      "accelmmnoops" => ["commonplaces"], "abeellmnopuy" => ["unemployable"],
      "cceinnosttuy" => ["constituency"], "acgimmnnostu" => ["consummating"],
      "bcinoorssttu" => ["obstructions"], "ccdeeiiinsst" => ["insecticides"],
      "aaeioppprrst" => ["appropriates"], "aeiiilmmorst" => ["immoralities"],
      "abbeeillnuvy" => ["unbelievably"], "cehiooopprst" => ["photocopiers"],
      "cdeiiimnorst" => ["misdirection"], "cdeefginorru" => ["reconfigured"],
      "aaceghoprrrt" => ["cartographer"], "acdeeimosstt" => ["domesticates"],
      "adeeghinrstt" => ["straightened"], "acciiloprsuy" => ["capriciously"],
      "aeeiinorrstt" => ["reiterations"], "acdggiinorsu" => ["discouraging"],
      "aahllmmorssw" => ["marshmallows"], "aciillnoosst" => ["oscillations"],
      "aceeeimprsst" => ["masterpieces"], "adeiinnopsst" => ["dispensation"],
      "eeeehlnrsstv" => ["nevertheless"], "aabccgikknrt" => ["backtracking"],
      "aaiilnnosstt" => ["nationalists"], "cddeeeeinnps" => ["dependencies"],
      "acchiooprrrt" => ["chiropractor"], "aeimnnoppstt" => ["appointments"],
      "acinooprrsst" => ["conspirators"], "accddeinortt" => ["contradicted"],
      "ciinnoostttu" => ["constitution"], "ddeeinrsstuu" => ["understudies"],
      "cfghiiknoprt" => ["pitchforking"], "aeeemmnprstt" => ["temperaments"],
      "aeeeiprrstvv" => ["preservative"], "eehnnorrsttw" => ["northwestern"],
      "aeelnoprssss" => ["salespersons"], "acenoprrsttu" => ["counterparts"],
      "addeggiinrrs" => ["disregarding"], "ceeefhlnrssu" => ["cheerfulness"],
      "aillorrssttu" => ["illustrators"], "aaffiimnorst" => ["affirmations"],
      "aceimnnoopst" => ["compensation"], "aiiillmnnotu" => ["illumination"],
      "aeegnrrsssst" => ["transgresses"], "ceeefhllrstu" => ["cheerfullest"],
      "abelllmnoosy" => ["monosyllable"], "cdiiijnorstu" => ["jurisdiction"],
      "aadgiiilnntv" => ["invalidating"], "aaeiilnorstt" => ["retaliations"],
      "befghillrstu" => ["bullfighters"], "aceilnooprss" => ["processional"],
      "cdeeghilnrsu" => ["rescheduling"], "ceiinorrsstt" => ["restrictions"],
      "egghiilnnoop" => ["pigeonholing"], "ehhiloopprss" => ["philosophers"],
      "aaccdeennott" => ["concatenated"], "aceelmnopstt" => ["contemplates"],
      "aaaaggilmmnt" => ["amalgamating"], "aeillmnoprsy" => ["impersonally"],
      "eeimmnoprstv" => ["improvements"], "aeeeimorsttv" => ["overestimate"],
      "eeiimnnrtttt" => ["intermittent"], "acciilmnoopt" => ["complication"],
      "bdiiinosssuv" => ["subdivisions"], "addiiillnuvy" => ["individually"],
      "bbcdeghilntu" => ["nightclubbed"], "giiinnooprsv" => ["provisioning"],
      "aegiinnoostt" => ["negotiations"], "aceiinnorstt" => ["interactions"],
      "egiinnprrttu" => ["interrupting"], "eeiimnprrstt" => ["misinterpret"],
      "aeehmmooprst" => ["metamorphose"], "cdeiiinnorst" => ["indiscretion"],
      "biinosstttuu" => ["substitution"], "aailnnorsstt" => ["translations"],
      "acdeefhhiknr" => ["handkerchief"], "aeeiimnrrrst" => ["intermarries"],
      "ceeiilmopstx" => ["complexities"], "acdeinnnoost" => ["condensation"],
      "adeekloprssu" => ["loudspeakers"], "bceeimmosttu" => ["subcommittee"],
      "cceeillnoort" => ["recollection"], "deegilnprssy" => ["depressingly"],
      "aabcllooorrt" => ["collaborator"], "adeeghinnppr" => ["apprehending"],
      "aeinoosstttu" => ["ostentatious"], "aaeffiimrstv" => ["affirmatives"],
      "dehmnorrsttu" => ["thunderstorm"], "acinnooprstt" => ["contraptions"],
      "adeefiloprrt" => ["proliferated"], "accdeiilnnot" => ["coincidental"],
      "bdehlnorsttu" => ["thunderbolts"], "egimnoorrtty" => ["trigonometry"],
      "aadeimopprtx" => ["approximated"], "acdeiillopry" => ["periodically"],
      "aaaagilmmnot" => ["amalgamation"], "aabcdehorrty" => ["carbohydrate"],
      "aceeehmnnnst" => ["enhancements"], "cddeeeiprsst" => ["disrespected"],
      "aefinooprrst" => ["perforations"], "biiiiilnstvy" => ["invisibility"],
      "cdeeinooprss" => ["processioned"], "acghinoopprr" => ["pornographic"],
      "aabghiinnrsw" => ["brainwashing"], "deeinnrrttuw" => ["underwritten"],
      "ddegnnorrsuu" => ["undergrounds"], "eeilnprsstty" => ["persistently"],
      "aacghilloopt" => ["pathological"], "aeekmprrsstu" => ["supermarkets"],
      "eeeeinssstwy" => ["eyewitnesses"], "deeiopssssss" => ["dispossesses"],
      "aeellmorrsst" => ["steamrollers"], "aaceghnoopry" => ["oceanography"],
      "bdegiillnnps" => ["spellbinding"], "ceeeilprstvy" => ["respectively"],
      "aceeinopsttx" => ["expectations"], "aceelmnnortu" => ["nomenclature"],
      "aggilmnoprtu" => ["promulgating"], "aceehmnnnstt" => ["enchantments"],
      "abcefgilnoru" => ["configurable"], "aaeinopprrst" => ["preparations"],
      "accdeimmnotu" => ["communicated"], "aeeeiinrrstv" => ["veterinaries"],
      "cegikknorsty" => ["skyrocketing"], "dhinooorsttt" => ["orthodontist"],
      "cehilorrttuu" => ["horticulture"], "bdeegiiilnsv" => ["disbelieving"],
      "ceeginrrrstu" => ["resurrecting"], "eegiinnprrst" => ["enterprising"],
      "beeghiillmns" => ["embellishing"], "aaccddemmoot" => ["accommodated"],
      "acdiinnooort" => ["coordination"], "ccginnorsttu" => ["constructing"],
      "acdiinorsstt" => ["distractions"], "ccfiiinorsux" => ["crucifixions"],
      "abeggimnnoor" => ["boomeranging"], "aceeeilnrrsv" => ["irrelevances"],
      "cdeerrrsttuu" => ["restructured"], "cceeeimnnopt" => ["incompetence"],
      "cdenrrsttuuu" => ["unstructured"], "aagiinnnqrtu" => ["quarantining"],
      "aadegimnqrsu" => ["masquerading"], "cdeeeoprrstt" => ["retrospected"],
      "acdeimnnnoot" => ["condemnation"], "adeeiimnrrrt" => ["intermarried"],
      "abgiilmnootu" => ["automobiling"], "accehiilntty" => ["technicality"],
      "adeginnrsttu" => ["understating"], "adeghhoopprt" => ["photographed"],
      "aabciilnorst" => ["calibrations"], "acddeeemmnor" => ["commandeered"],
      "aeeefilnprrt" => ["preferential"], "acilnnooosst" => ["consolations"],
      "aeghhoopprrt" => ["photographer"], "acehirssttww" => ["wristwatches"],
      "eeilmnnostvv" => ["involvements"], "acimnoopsttu" => ["computations"],
      "acdeinossttu" => ["outdistances"], "iinooppssstu" => ["suppositions"],
      "ceefiiiilnst" => ["infelicities"], "eghiilnssttu" => ["unsightliest"],
      "accdeeilnopy" => ["encyclopedia"], "adeeeimnrttx" => ["exterminated"],
      "aacceilnorvy" => ["clairvoyance"], "aceeimmnorst" => ["commentaries"],
      "aaceeffinott" => ["affectionate"], "aadelnnprstt" => ["transplanted"],
      "aaeeinoprstx" => ["exasperation"], "cdeiinnosstu" => ["discontinues"],
      "abceooorrrst" => ["corroborates"], "aabbeiinortv" => ["abbreviation"],
      "aaellnnpstuy" => ["unpleasantly"], "eeeehkoprssu" => ["housekeepers"],
      "eeeekoprrsst" => ["storekeepers"], "beegiiilllnt" => ["intelligible"],
      "ehhiilooppss" => ["philosophies"], "eeffllorssty" => ["effortlessly"],
      "aacehilmnpru" => ["alphanumeric"], "aacdefmnrtuu" => ["manufactured"],
      "aaiiilmnosst" => ["assimilation"], "acghillmooty" => ["mythological"],
      "bcdeeiinnost" => ["benedictions"], "abceiinorstt" => ["obstetrician"],
      "ceeinorrrstu" => ["resurrection"], "aaciiinnoptt" => ["anticipation"],
      "aiknoorssttw" => ["workstations"], "aaelnprrstuu" => ["supernatural"],
      "aegghiilnnst" => ["nightingales"], "aabcdginorst" => ["broadcasting"]}
    |> Map.get(string_id)
  end

  def valid_ids do
    ["aaiillnnostt", "abciimnnoost", "aacilmnooprt", "cilnnoostuuy", "aeehllmnnopy",
     "aabefgiknrst", "abcgiikllnst", "eeginopprstv", "deeginnrrrsu", "ceerrrssttuu",
     "bcinoorrsttu", "aaccehhiilrr", "acceilmnnoou", "abcdeooorrrt", "ceelnnoqstuy",
     "adeeimnrstuv", "acdegiiknrst", "ccdeeelorttu", "adeiinorsstt", "aefnnorsttuu",
     "abcdeilnorsy", "adeghmnorrst", "accceimnrstu", "aeeemrssssst", "acdeeiiinnrs",
     "aacehoprsstt", "eehlnrsssstu", "aeeinorrsstv", "acceimmnostu", "abeinoorsstv",
     "aaceijllmsty", "acdeiinnnotu", "aceiinoprrtt", "aefmnorrrsst", "cdeginoorrvw",
     "aegiilrrrtuy", "aacegiinnrst", "cdeiinoprsst", "efgiinnoprsy", "eeginoprstty",
     "bdeeefiilnns", "ccdeehilpssy", "ceinnosstttu", "aabeeelnprtu", "aacdeilmrttu",
     "deefiiinnort", "acdeegiinprt", "cdefhlmooorr", "aaccdemmoost", "aaceghiloprs",
     "begiiilllnty", "ccddeimnostu", "aceilnnnootv", "adeeersssstw", "ahimoopppstu",
     "ceehinoorrss", "aaceinrtttuv", "accgiillooos", "cceeennoqssu", "acehiinssttu",
     "adeeffiilnrt", "aabcghiilopr", "abdegiikmnrs", "aeefgiorrrrt", "aegiilmnnrst",
     "aehimnnosstt", "aiillnorsttu", "aaeeiinnrrtv", "deeeinprrsst", "accdeeinnnst",
     "accceeeinqsu", "eiinoprssttu", "aacceilnrrtt", "accfiinnoost", "adeeimnoprst",
     "achiiprsstty", "cddeeinnostt", "addeeiimnsst", "aginnoprrstt", "eeilmooprsst",
     "aeeillnqtuvy", "aceemmmoorst", "aceinnoorstv", "ccgiinnnnouv", "ddeeeinnnpst",
     "ccegijnnortu", "aaiilnnorstt", "aaabeiilmnnt", "abcdeeilnors", "adeehhlorrss",
     "aciiinopssuu", "aabeeksssttw", "aaeehimmnpst", "aceginorsssu", "cdeeeoprrsss",
     "aceghhooprry", "acceeilllrty", "aacillmnorty", "aeehnnorrstt", "cceeffiinost",
     "aciilmnoopst", "deeeghnnrstt", "deefiiilnnty", "bceeeelnnosv", "aceeimmorsst",
     "acilmnooopst", "aaeeemnppsst", "ceinooprsstu", "aeeilprssuvy", "acdeelmnoptt",
     "aeimnrrssttt", "aacceeilnort", "aefghhoorrtu", "cdeennrrrtuu", "aadefghnrrst",
     "deeelmnopstv", "eghinoorrtvw", "eiiimnnorsst", "bcceeelnooss", "abdeeeerrrtv",
     "adeeghimnost", "aaceijlnostu", "deeeilnrsssw", "cdeeilmnoopx", "abeeffilnrsu",
     "deeeinprstux", "aceehimnsstt", "adeeefgirrrt", "aaceillprrst", "agghiimnnrst",
     "dggiilnnrstu", "acdiilnnoost", "aagghinoprtu", "aefgimnorrtt", "ccdddeeennos",
     "eelmmnnoptuy", "aabegimnrrss", "acegimnnopss", "ccelnnorrtuy", "abefgilnoruv",
     "adeiinnnostt", "bhiiinooprst", "aaghiiilnnnt", "ceeeefinnrrt", "aabeglmmoprr",
     "befgilnrttuy", "adefiiisssst", "aainnnoprsst", "ddefghilloot", "aaceijkrsttt",
     "abdelmnorsty", "acgiiilnprtt", "ceefgiilnrty", "bdeeeilmnrtw", "aaggiinnrtuu",
     "accgiiilnnot", "aabefllmmnno", "aadegikmnrrt", "aeffhilnsstu", "deeeeimnprtx",
     "adeeeiimnrtt", "aeeopprrrstt", "aaceeggillno", "acehinoprrss", "achiillorsty",
     "ccdeiorrssss", "aaeilnopssty", "cghinoooppty", "ccefiiinnstu", "ceilnnosstty",
     "aaccilmnotuu", "aeghlmnnoors", "deeelmnppstu", "abcdeeehirsu", "ccgiinnorstt",
     "aaccilnooptu", "abceeelmnrss", "aceeillnrsuv", "cceeelorsttu", "aacceillnnot",
     "aaeilmnprstu", "eegiiinnrtvw", "aciiilnpprty", "adeeiilnprst", "adgiillnnotu",
     "aaeegmnnrrst", "abeeeinrrttv", "abdeeilprstu", "aegiinorrstt", "aaacceiinptt",
     "diiillnosssu", "beeeiilrrrsv", "aeilmnosstuu", "cgiilooossst", "aggimmmnnoor",
     "acddeeefnort", "clnoprssuuuu", "abceiilnrtxy", "aacdeilnorst", "aeeeinnrrstt",
     "aacegiimrrss", "eeelllnrssty", "cddegiiinrst", "abbghiilopry", "accegiinrtux",
     "achhiloprsss", "aabeghiknrtt", "abdeeeilmnrt", "afinorrssttu", "acddeilnoost",
     "eeimopprsssu", "aabeelnnorsu", "ceeehiknsttt", "eeegilnoprsv", "cceeilllotvy",
     "cdefgiiinnst", "accegilnnosv", "adeegmmoprrr", "cccdeeiinnos", "eiinnoprrttu",
     "cceiorrsssss", "abeiilmnnrty", "eegilnnortuv", "acceelnnostv", "acehhiloptty",
     "bdeegiimmnrs", "aciinnoopstt", "abiilnorsttu", "aabeilmmrsuy", "acemmnoprstt",
     "aeiiiilmrsst", "aeegimnnostt", "acdiinorssyy", "aaegillnpprw", "cceeinnnortt",
     "accdeennnotu", "aiimnnorssst", "aaffiiilnost", "ceghilnooors", "eiinoprsssuv",
     "adegiknnrstu", "cceeemmmnnot", "adghilnnopry", "abcinorssttu", "cceeeiimnnrs",
     "aacdeeiinqsu", "acceehirrttu", "aaeilmnnostt", "ceeeinnqsstu", "ailnopprtuuy",
     "adeiinorsttx", "aggiiinnortv", "aadeelllnpru", "cdeegimmnnor", "aiiinnnosstu",
     "cceeeinoprsv", "aaccehillmny", "ddeefgnoorru", "cdeeiiinnstv", "aeeilrrrsstt",
     "cddeiinnostu", "aabceiiilpst", "adeeiimnssst", "aaggiiinnrtt", "iinooopprsst",
     "aaacdillmrty", "abddeinorstu", "aeehnorssttu", "aabcgiikllmn", "acdefiinnstt",
     "aabdeeegilrs", "adejmnnorstu", "aceiloprrsuy", "abceeilnorst", "aceeirsssttu",
     "accdehilmops", "acdgiinnoort", "ccdeeimnrtuv", "aaceimoprstv", "aeegilnrsstv",
     "acegiilorssu", "aabeeilnprss", "ccgiilnnnovy", "cdiinnoorttu", "ceeeeiinnprx",
     "aaceilmnostx", "aabceinrrstt", "abehiilnopst", "bceilorsstuu", "aaacceinnqtu",
     "aabiklmnstuy", "aciiinoqsstu", "aehiinoprrss", "adefhiloorst", "cdeeinrrsttu",
     "ceeegiinnprx", "ceginnpsstuu", "eeiilmprssvy", "adefiiilqssu", "aeeemmnrsstu",
     "adeeehprssst", "ceiimmnoprtu", "bdghiimmnrsu", "adiiiimnnott", "aacegiilmnns",
     "aeehoprrsstt", "ccimnnoopstu", "beiinorrsttu", "acegiilnnrsy", "ceeinoprsstu",
     "aabbegiinrtv", "acfiimnnoort", "aaeegginnrtu", "ceeiiinrsstu", "acdeeghinnrt",
     "egiinnoprrtv", "aeeginorrstt", "aacceegilnrt", "iinooprstttu", "eghimnnnoooy",
     "aeegillrsstu", "befghiinrrsu", "aceeeilmnpst", "aceehorrsstt", "bddfgiillnno",
     "degiinnrrtuw", "aeimnoprsttu", "aaeegginortx", "cceiinnottvy", "addefiiilqsu",
     "aacceeghosst", "eeghiinrstux", "abceillnnoos", "aeeemprrsttu", "aaghiinpstxy",
     "acefiiinortv", "eefgiilmnpxy", "aabdeegilrsy", "aadefgginrsu", "bddeeenorruv",
     "abdeeilnrssu", "acenoorrstvy", "afiiilnnortt", "aafiinnosttu", "aeiinnoorstt",
     "bdgiiinrsttu", "bcinoorrttuy", "aacgiinnostt", "deeiiillrsst", "aeghhiinstww",
     "ciilopsssuuy", "adeeginorrtt", "abeeillnnruv", "eefillpssttu", "eeginooprrvw",
     "ccdeeeinoprv", "aabbeilrtttu", "aeehinnopprs", "aacdeelnpstu", "aceefmnoprrs",
     "cceeginnnort", "acfillnnotuy", "adeiinnorstt", "ceeelmnopsst", "acdeeeilnsst",
     "aabcdelloort", "addeegilnnst", "acdeehimnrss", "aacfiiinortt", "acccegiinnor",
     "ceeiinnorstt", "cefiilnoprty", "ceehilnnorty", "aaegikmnrrtw", "cdiimmnnoosu",
     "acdeegklnosw", "aceiiilrsttv", "aacehilmpsty", "dddehnnooorr", "cdeeelmmnopt",
     "acegimnnopst", "cdehkloorsst", "deeelnrrsuvy", "abdfginorrsu", "aeegiinnnrtt",
     "eeeilprssvxy", "eehloprrsstu", "aceiinnorrst", "ceinnoorsssu", "abdeiilnpstu",
     "cdeeelnptuxy", "cceillnosuvy", "aacdeeinnrrt", "aeegiinnrtvw", "adeegiinrstt",
     "aeeehinpprsv", "aeeimnnorstu", "aceehiinnrst", "aeghioopprst", "aaciinpprstt",
     "abdeiiiilsst", "aaaceegnrtvx", "aeinoorrsstt", "fghhllottuuy", "ddeeenorsuvz",
     "acciilnorstu", "deeimnnrsttu", "bbceilmosstu", "aacehillmpty", "bceeilmnoptt",
     "adeeeghlmmrs", "fgiiimmnnors", "cdellnnoortu", "aaceffinostt", "cdeeiiimorst",
     "aeefiinrrstt", "aeeegmnnrstt", "acehillrstyy", "acefillorsuw", "aaiiilmprtty",
     "accdeenorttu", "aaciinoossst", "cdeeirrrssvw", "aeeinnoprstt", "deeghiinstux",
     "cdeinorsstuy", "deehiilnqrsu", "acdeeghllnnu", "eeffghiirrst", "aabceiillnpp",
     "aaeeillqrstu", "bcgiilmooory", "aacceeinrrst", "acinoooprstv", "ceiimmnoorss",
     "aacfgiiilntt", "acgiiinnottx", "aaccgiinrrtu", "ceiiprrrsttw", "aefgiilrtuvy",
     "aabceikllmrs", "aeefiloprrst", "cccgiiimnrsu", "bdhiloorstty", "begiilnnprtu",
     "eehinrssstyz", "ceffiilnstuy", "abciilnopstu", "bcekkoorrsst", "aeeggilrssvy",
     "bdeegiiilnst", "aceeegiknrrt", "aginooprsstt", "deeeinnrsttu", "accdeennortt",
     "deegiilmnnrt", "aabfllmnotyy", "aeggiiilmntt", "aadeilnorttu", "aaeimnoooopt",
     "defgiiinrsvy", "aeeghnoprrst", "bdehhooorrst", "acceeiilnrst", "aaaccdeillmy",
     "aceeelnrssss", "adgiiiimnntt", "acdeginnnrst", "acdeiiimnrst", "accehilmopss",
     "afinnorssstu", "aefgggilnopr", "addeemnorstt", "cdeeeiinprss", "aacegiimnnpt",
     "aeeillnqstuy", "aceggginnort", "aaddiillnoty", "deefiilnnrru", "aaggiillnntv",
     "deefiiiilnst", "aceeginorrtv", "ceehikmnosss", "aceeinoprrtu", "aeeinoprrstv",
     "aacegiinpprt", "deeinnnorsst", "aaciinnnorst", "aefilnooprss", "aabelnnorsuy",
     "ceefiimnoprt", "abcdeinoorst", "aaabcehloppr", "aeeillnrrstt", "acdeeimmorst",
     "aaccillnoosy", "achhiimnopps", "ceeiijnnortt", "ehiilmrssstv", "ceeiinnnnotv",
     "aabcelloorst", "aceeginprrtu", "aceinooprrst", "aciiilmnptuy", "aaabcehillpt",
     "aeegiinssttv", "aaccceiinrsu", "aceemnnnnotu", "ceeeeffnrstv", "aefgillnorst",
     "aceeghilnrtw", "aaceeklmprst", "aaceilmrsttu", "cdeginnorrsu", "egiiinnnrttw",
     "aacilnorstvy", "cdeeeeiinpsx", "aehioprrstwy", "eilmorsstuyy", "aaeimopprstx",
     "aabdegiimstu", "aciilnnoostu", "deeenorssuvz", "aacgiilnpttu", "abcceilmmnou",
     "aeeimnnorrtu", "aceimnorsstv", "aadeflmnnstu", "eemnnooppstt", "cddeeehmnopr",
     "aaccillnostu", "eeeinprrrstt", "acdeimmnnoot", "ciimnooopsst", "aabeehiilrtt",
     "ceeghilnoost", "aeeeglmnnntt", "cegimnnnosst", "abiiillpstuy", "abdegiiilntt",
     "adeeiinprsss", "aaccgimnnopy", "aaeilllnrtuy", "aaeghiilnrtx", "acdeeikloops",
     "abdeefiiilnt", "ceilmooprssu", "achnnoorssuy", "acddeinosttu", "bdeghhoorrtu",
     "aadeeghinprs", "abceeiilnnnt", "emopprsstuuu", "bdeeiirrsttu", "accimmnoortu",
     "aacceelorrst", "aeghimnorsuw", "aafiilmmnnot", "aadegnnprrst", "aaadegnostuv",
     "eeoopprrsstu", "acghhioopprt", "aadegoprsttu", "cdeginnrttuu", "abcdeinrsstu",
     "ceiinnorrstu", "behhoorssttu", "eegghiilnnnt", "acceginnorst", "acilnnoosttu",
     "ceegiijnnrtt", "ceghiinnrsst", "ceiinnnosstt", "acfiiinoprtu", "cceiilnnosuv",
     "aiilmnnorttu", "cdeffiiilstu", "aaceillmmtuy", "bcdgiikmnors", "diiinoopssst",
     "acilmmnnoott", "ceeeiiprrstv", "clloprssuuuy", "abdeinorsstu", "aaccdeillnty",
     "eginooprrsss", "aabceeeghlrr", "egiinnnortvy", "aeeeilmnprtx", "cgiinnostttu",
     "aaeoopprrrst", "inoopprssttu", "abcgiklnoppt", "aabeilnoorst", "aciiilnnnost",
     "ahhilnopprty", "eimnopprsstu", "ciiillmpttuy", "aacegginopst", "ceefimnnnost",
     "aeiiilmnnost", "addeeiimnrst", "aeeijnnortuv", "aaadeinsssst", "accdeeelnoss",
     "aeeeimnrsttx", "acemnooprrty", "ceeeinorstux", "acciiilnnoot", "abeeeilmnprt",
     "aacciiorrstt", "eeeehnnssttv", "aehinpprrsst", "ahiiilmnostu", "eeghlmnnoors",
     "agiillnrsttu", "agiiklmnsttu", "abeeeerrrstv", "aeiiimnorsss", "iiinnosstttu",
     "aeeiinnprtty", "acdemmmnnost", "aceeefffrstt", "aacegghilopr", "cdiiinnosstt",
     "adeinooprstt", "beeeirsstttw", "aadegilnrttu", "abeghhkorrtu", "aegghilnrstu",
     "aciiilmnopst", "bcehiimorsty", "eeeimnprrsst", "aeeeginnorrt", "adeiinnosstt",
     "cdiioprttuvy", "cdgiiinnnoot", "acdeemmmoort", "aceiinnnortu", "ccceeiinrtty",
     "aeginoorrrtt", "aeghopprrsss", "aabcceirrtuu", "aceegilssttu", "cceinorsttuv",
     "aacciilprtty", "acgiinnnorst", "aiimnooprstt", "adegiimnnprr", "aacefmnrrtuu",
     "aeiiillmnors", "abcgiinnrrst", "bdiiorrssttu", "ceefllprstuy", "aacehilmoprt",
     "adefginooprr", "aacillprrtuy", "aeeinoortttx", "acehiintttuy", "acgijnnoostu",
     "aabeiloorrst", "cdeiinnoorst", "aeeggirrsttu", "aceghhilrsst", "ceiinopprrst",
     "aabbeilnnotu", "aaceimnnostt", "acceefiirstt", "bdiiinorsttu", "bgiinsstttuu",
     "accdeimnortu", "aabbeirrsttu", "iiiinnoqsstu", "aceiiimnnrst", "beeeelmmntzz",
     "aacgiilnrttu", "aaceiipprstt", "aadeehqrrstu", "aeggiimnnprt", "aacinnorsstt",
     "ceeeklnrssss", "aeegijnnrtuv", "ailnooopprrt", "aaccgilmntuu", "cddeeeinorrs",
     "aaceiinopprt", "aacdeemnnstv", "eeelnrssssst", "aadegiinpprs", "ceeiinnoprtt",
     "abcelllnoort", "ceiimnoopstt", "cceeeinnnosv", "aacdeiipprtt", "aaahiimnnrtu",
     "degiinnossuu", "addeefhoorsw", "deegiinppsst", "abceiilmnopt", "eiimmnnoprst",
     "bdeegiimnorr", "abeeiilmnnrt", "aefimnoorrst", "abciilmnopty", "cemnoopsttuu",
     "aaeghlmnrstu", "aaeilnoprrst", "eeeginnprrst", "cceflnsssuuu", "ccceennorrsu",
     "aaabiiilltvy", "aciinnnoottu", "ceeimnnopstt", "agiimnnrsttt", "acdeeeinsstt",
     "cgiimmnooprs", "adeiimnnnoot", "giinoprstttu", "ccegiknorrsw", "aaeiimnnostx",
     "aeilmnnrsttu", "adgiinopprsv", "adeeegimnrst", "accegiiknrsw", "ceehklnossuy",
     "aeeghipprstw", "efgiinnprrst", "eegiilmmnnpt", "cfgiiilmmnor", "aceeehimnstv",
     "eginoppprssu", "ciiinnoprsst", "ccddeeinorst", "begimnnortuu", "aadeelmnprtt",
     "aaccdeeinrrt", "ccciiimnorsu", "aabceilmnopr", "eeiinopprsst", "aacceilmprst",
     "acdeinooprrt", "abcdhiorsstw", "abcceemnnrsu", "aaciillrstty", "aabccelnptuy",
     "acceillmnooy", "cddeeeeinnnp", "eeekloopppss", "egilnoorsstu", "acinoooprrst",
     "abcdgiklnoor", "gghhinoorsuu", "accdeefiirtt", "deinooopprrt", "aegimnnrsttu",
     "cdeeilmmnopt", "adeehirrrsss", "acegillmooty", "adeefooprrtw", "aacegillnort",
     "gghiilmnnoot", "aagiilmnnptu", "adeelmorsstu", "agiiinnoprtt", "aceffghinruu",
     "eghilnoprstu", "bcegiiilnorr", "aaceillrttuy", "ddeehiiinrst", "gghiilnopstt",
     "cdeeioprrtuv", "bceghimnnooy", "acceeioprrst", "eehiilnqrssu", "acinnnooostt",
     "acceiinoprss", "adeegnrrssst", "ceefinorsttu", "aabeennrrstu", "aegilmnoprsv",
     "eeknoopprsss", "giilnprrssuy", "acchiiloprty", "defhinprsstt", "eeghiilnnprs",
     "ccdeeefiiins", "abdeeinnrrsw", "accellnoptuy", "aeeeglmnnrst", "acceillmmory",
     "cdgiiiilnnps", "eeghiinsstux", "acdeeirssttu", "aaiillnorrty", "aacgiiinnptt",
     "aceilnoorrst", "acdeegilsttu", "acdhhinoopry", "ggiiillnnotu", "aaceiimnnopt",
     "ceegiinnrstt", "eegiilmnnrst", "ceeiklmnppru", "adeegiknnrrt", "acehlmmnootw",
     "ceeillorssty", "aaegiinprrtt", "abbeeeillnuv", "aaciilnorttu", "adeiinoprstu",
     "acdeeefnorst", "adeegiinsttv", "aadeeloprttx", "aaehiilnortx", "aabeeklmnrru",
     "ahillnoortyz", "cdeeeffiinnr", "agilorsttuuy", "bbceklorsstu", "aacfiinnosst",
     "aefghhortttu", "eiinoopprsst", "aafiilnnorty", "ceeeipprsstv", "aeilnoortuvy",
     "aaceknnorstu", "acdiiinoosst", "aaceiilnrttu", "acdfiiimnoot", "aeiilmnosstt",
     "cceillooopss", "acddeeinnrsu", "cdeeehiloprt", "abdeeeillrty", "ccddeeinnost",
     "aacfggilmnou", "egghhiilsttw", "acehiiopsstt", "eeimnnnorstv", "acdeiinnortt",
     "aagiinnortuu", "aeeglmnnortv", "eiimnnooprst", "aeiilorrrstt", "aachimnnorss",
     "dggiilnsstuy", "aagiiilmnsst", "egilmnooostt", "acfiiinnoott", "ddeefiiinntu",
     "acegiinnpprt", "abdeiiirsssu", "aeegiillmtty", "aaagghinpprr", "cdegiiimnrst",
     "accegilllooy", "aacdeilmmort", "aghiloopsstt", "cegiiklnnort", "aacehillptty",
     "acegloorsuuy", "aaccimnopsst", "acdeeiipprtt", "abdginoprrss", "adeeeiorrstt",
     "acdeilnoosst", "aaeiilmrsstt", "aaceeilnorrt", "hlmoopsstuuy", "ccdeimnoorss",
     "aaagginorstv", "aabeinsstttu", "beeegillnrst", "aeilnooprstx", "aaacegilmmno",
     "aceeglmnoort", "ddefnoooprsu", "eeefhmnrrsst", "aciilmnnostu", "accdeeioprrt",
     "abeeklmorrtu", "aacdegiinptt", "aacceginnttu", "cdeioorsstuu", "adiiilnoqstu",
     "acdeeimnnopr", "eefgiimnnnrt", "bcgiinnorttu", "acceefikrrrs", "aagiiimnnost",
     "acceennorstt", "abdeimnorrst", "addeeeiorrtt", "acddeehimnrs", "aacceennostt",
     "aeegioprrstv", "abbdemmnorst", "adefllnrtuuy", "aaceiilmnstx", "aegiinnorsst",
     "aaaeinssssst", "abegiilnortt", "acddeegklnow", "accdeiklnsst", "aacdghiinnpp",
     "aeegghilnprt", "acegginnoort", "acdeeiinoprt", "cceeilsssuvy", "acillmorsuuy",
     "deeemnnorsst", "abeeilnoqstu", "acdeiiimnnrt", "aaciiinssttt", "eeeiilpprstx",
     "efhlnrssttuu", "aaaghinpprrs", "aacfiiillrty", "aaaiilnorttt", "accgiilmnopt",
     "aafilmmnorty", "aabcinorsstt", "deegiilnpruv", "cceegillnort", "aaeeggginrtx",
     "aaabeilnnttu", "accefgiiinns", "aaciilnoppst", "acdgiiinosst", "eegioprrsssv",
     "ciinnorssttu", "eeehmmorrstt", "ceghiiknprsw", "acdiiilnprsy", "aeeimnoprsst",
     "eehiimoprssv", "aeegiiillmtt", "aeeehlorstux", "eeghhinoorss", "aceeeenprrsv",
     "aceeilllnttu", "abceiillnpxy", "accinnoorstt", "ceeeiimnnprt", "ceeegiillnnt",
     "acdeehorrstt", "ceeilnnnotvy", "aaacehilmmtt", "aghlnoooprty", "ceeinoprrssu",
     "eghiilnosttu", "abdeefillstt", "aaeegmnoprst", "aeeghhistvwy", "cdeiillmnoss",
     "ccinnoorsttu", "aaeeklnrsstt", "cceeefhiknrs", "accefiillpsy", "deehiimoprsv",
     "eeeiipqrrstu", "acdiilnoosst", "ccgilmnoorty", "aaeilnnopstx", "aeeilprsstuv",
     "adeeggirrttu", "cdeinooprrtu", "abcgggiiknpy", "cgghiinoprty", "cdeiilnnppru",
     "abeeirrrsstw", "aacfiorsstty", "eehnorssttuw", "aaegiinprttx", "aceilnnnostt",
     "cceginoppruy", "acddeeimostt", "aeeiiilnqstu", "dddeeinrstuu", "addeeimmnrst",
     "aceeeinssstt", "aiiinnoprsst", "ceffiiinnstu", "aabeeflnrrst", "ggghhhiiilnt",
     "aaiilmnnoptu", "eehinnoprsty", "defiinoprstu", "egiillmnpsss", "aacchioprstt",
     "aaeeginprstx", "aacgillrrtuu", "aegiinorsttv", "ceipprrssstu", "aaeeilnrsttv",
     "eeiiooprrsst", "abdeegiilnrt", "acceefgiimnn", "aadeioppprrt", "eeeimnqrrstu",
     "aehiilnoprst", "eeghilmnorvw", "aciiinnoottx", "aacciinnostv", "abceiknprstu",
     "aefiinnosstt", "bddfgimnnouu", "aabceeginrtx", "cdiillorsuuy", "agiiillmnntu",
     "ceegimnnoprs", "aceeinorstvv", "ccenorrssttu", "abeeeemnrstv", "afgiiilnnrtt",
     "abceeemmnrrs", "adeemnorsstt", "aabceilorsuv", "aeilmnooprtt", "cghiloopssty",
     "aabccgijkkln", "aacefmnrstuu", "dehlnoorrsuy", "eeiiinrsstuv", "adeegilnnsst",
     "adeeegginnrt", "bdeeeiimorrs", "aeiiinnrsttv", "bcddeeeiinos", "aacilmnoorst",
     "acdeiiinorst", "acdeeilmnpst", "abceeiillnpx", "abeiilnoortt", "eeegiinorsst",
     "eeeinprrssst", "aehinoorsttx", "aacennprrsty", "aabcfiinorst", "ceghiloopssy",
     "giinopprsttu", "eghinooorstv", "cdeiimmnooss", "abiiiilrrtty", "aceeghinnrst",
     "adeegmnnrrtu", "aabcekqrrstu", "addeeehinrst", "afilmnoorstu", "acdefiilnnot",
     "aacgilloorst", "ceeginnnortu", "eefgiinoprrt", "aceeginnprrt", "aeimnnorsttu",
     "cddeeeiorrsv", "adeeiimnrrty", "acemmnoorstt", "acdeiiinppst", "acceennnostu",
     "aacdeimnorsy", "eefilnnqrtuy", "abbceeiklrrs", "cddefimoorst", "aaceglnorttu",
     "aaceeinnrrst", "acegghinorrv", "aabcceilllnu", "aceeiooprstv", "aabddeekorst",
     "afgimnnorrst", "aceegiilnstv", "abcgiilllooy", "ceimnorssstu", "acefgiiilmns",
     "adegiinnosst", "bdeeimnrsstu", "aaccelprsstu", "acdeeimnprst", "acegiiinnnrt",
     "aeefimnnortt", "ademnoorrstt", "bciinoprsstu", "eiiinoqrsstu", "eeeiinrrstvw",
     "ceeiinoprstt", "beelnqsstuuy", "aeehhilnsttu", "cddeemnnotuu", "aahiiilnnnot",
     "ceegiinnprtt", "aabeiklmnstu", "aabimnorsttu", "acdhiioprstt", "aeffknrrrstu",
     "begiimnrsttu", "effgiinooprr", "aeeginpprttu", "abdeimorstux", "abeghiilnsst",
     "aceeiipprstt", "aadddegnnrst", "ccefllsssuuy", "aaceelnpsstu", "aaceillmnsty",
     "aeiillrsttuv", "addeeimnoprt", "aacdeimnnott", "cefiloorsuvy", "beeiiilrrsst",
     "adiiillnostt", "cceeffiiinny", "bceeilnorstv", "adeimnnoorst", "efgiiinnnsty",
     "aegloorstuuy", "aaceenrrsssu", "acdeiillnnty", "aceeelmnprst", "ceghhiilopry",
     "aaaddeginstv", "deelmnorstuy", "aadeginnpprs", "aabcceelnptu", "aeiilnoopttx",
     "aefginnrrrst", "ccijnnnoostu", "addefiiissst", "deeeemoprsst", "aiilnopssttu",
     "aaeeilnprsst", "aaeeloprsttx", "aaceeiipprtv", "eeiinnnorttv", "aabcehilnrtu",
     "aadeeilnqtuy", "ceginnorsstu", "aahiinopstxy", "aaeiinqtttuv", "abdeiiilmnss",
     "aeeginpprrtt", "adghiinnsttw", "abcceeiilnss", "aaceegillnsv", "aeiinopprrst",
     "bccehorstttu", "aacfiiimnort", "addeehoorsvw", "aaciinnnostt", "dginnorrssuu",
     "aabeelnnossu", "abeehlorrsww", "acdhhioprrss", "aceilnopsstu", "cghimnoorsst",
     "aabeelnnrsuw", "acfilnosttuu", "aachllnnnoty", "accfgiinnost", "bghilnnoottu",
     "aehiiimnnstu", "ddeeiopsssss", "ceehoopssstt", "adeiinoprstv", "cciinnoorstt",
     "eimooprssttt", "ccghhinoopst", "addeeeopprsv", "adeeehhlortw", "cdeimnorsstu",
     "aacfiinosstt", "addeiinoppst", "ceeopprssstu", "aacchiimrsst", "eimnoooprrst",
     "deeimopprssu", "eegiinnprrtt", "aeeefgirrrst", "aeegimnnrrtu", "bciinnoorttu",
     "deefiilnnrss", "aaceehintttu", "abdeiiilrsty", "cdinoorrttuy", "cddeenooprrs",
     "abdeeiilnort", "abceehorsttx", "bccinoosssuu", "aabeeilmmrsu", "aeeegginnrrt",
     "accelmmnoops", "abeellmnopuy", "cceinnosttuy", "acgimmnnostu", "bcinoorssttu",
     "ccdeeiiinsst", "aaeioppprrst", "aeiiilmmorst", "abbeeillnuvy", "cehiooopprst",
     "cdeiiimnorst", "cdeefginorru", "aaceghoprrrt", "acdeeimosstt", "adeeghinrstt",
     "acciiloprsuy", "aeeiinorrstt", "acdggiinorsu", "aahllmmorssw", "aciillnoosst",
     "aceeeimprsst", "adeiinnopsst", "eeeehlnrsstv", "aabccgikknrt", "aaiilnnosstt",
     "cddeeeeinnps", "acchiooprrrt", "aeimnnoppstt", "acinooprrsst", "accddeinortt",
     "ciinnoostttu", "ddeeinrsstuu", "cfghiiknoprt", "aeeemmnprstt", "aeeeiprrstvv",
     "eehnnorrsttw", "aeelnoprssss", "acenoprrsttu", "addeggiinrrs", "ceeefhlnrssu",
     "aillorrssttu", "aaffiimnorst", "aceimnnoopst", "aiiillmnnotu", "aeegnrrsssst",
     "ceeefhllrstu", "abelllmnoosy", "cdiiijnorstu", "aadgiiilnntv", "aaeiilnorstt",
     "befghillrstu", "aceilnooprss", "cdeeghilnrsu", "ceiinorrsstt", "egghiilnnoop",
     "ehhiloopprss", "aaccdeennott", "aceelmnopstt", "aaaaggilmmnt", "aeillmnoprsy",
     "eeimmnoprstv", "aeeeimorsttv", "eeiimnnrtttt", "acciilmnoopt", "bdiiinosssuv",
     "addiiillnuvy", "bbcdeghilntu", "giiinnooprsv", "aegiinnoostt", "aceiinnorstt",
     "egiinnprrttu", "eeiimnprrstt", "aeehmmooprst", "cdeiiinnorst", "biinosstttuu",
     "aailnnorsstt", "acdeefhhiknr", "aeeiimnrrrst", "ceeiilmopstx", "acdeinnnoost",
     "adeekloprssu", "bceeimmosttu", "cceeillnoort", "deegilnprssy", "aabcllooorrt",
     "adeeghinnppr", "aeinoosstttu", "aaeffiimrstv", "dehmnorrsttu", "acinnooprstt",
     "adeefiloprrt", "accdeiilnnot", "bdehlnorsttu", "egimnoorrtty", "aadeimopprtx",
     "acdeiillopry", "aaaagilmmnot", "aabcdehorrty", "aceeehmnnnst", "cddeeeiprsst",
     "aefinooprrst", "biiiiilnstvy", "cdeeinooprss", "acghinoopprr", "aabghiinnrsw",
     "deeinnrrttuw", "ddegnnorrsuu", "eeilnprsstty", "aacghilloopt", "aeekmprrsstu",
     "eeeeinssstwy", "deeiopssssss", "aeellmorrsst", "aaceghnoopry", "bdegiillnnps",
     "ceeeilprstvy", "aceeinopsttx", "aceelmnnortu", "aggilmnoprtu", "aceehmnnnstt",
     "abcefgilnoru", "aaeinopprrst", "accdeimmnotu", "aeeeiinrrstv", "cegikknorsty",
     "dhinooorsttt", "cehilorrttuu", "bdeegiiilnsv", "ceeginrrrstu", "eegiinnprrst",
     "beeghiillmns", "aaccddemmoot", "acdiinnooort", "ccginnorsttu", "acdiinorsstt",
     "ccfiiinorsux", "abeggimnnoor", "aceeeilnrrsv", "cdeerrrsttuu", "cceeeimnnopt",
     "cdenrrsttuuu", "aagiinnnqrtu", "aadegimnqrsu", "cdeeeoprrstt", "acdeimnnnoot",
     "adeeiimnrrrt", "abgiilmnootu", "accehiilntty", "adeginnrsttu", "adeghhoopprt",
     "aabciilnorst", "acddeeemmnor", "aeeefilnprrt", "acilnnooosst", "aeghhoopprrt",
     "acehirssttww", "eeilmnnostvv", "acimnoopsttu", "acdeinossttu", "iinooppssstu",
     "ceefiiiilnst", "eghiilnssttu", "accdeeilnopy", "adeeeimnrttx", "aacceilnorvy",
     "aceeimmnorst", "aaceeffinott", "aadelnnprstt", "aaeeinoprstx", "cdeiinnosstu",
     "abceooorrrst", "aabbeiinortv", "aaellnnpstuy", "eeeehkoprssu", "eeeekoprrsst",
     "beegiiilllnt", "ehhiilooppss", "eeffllorssty", "aacehilmnpru", "aacdefmnrtuu",
     "aaiiilmnosst", "acghillmooty", "bcdeeiinnost", "abceiinorstt", "ceeinorrrstu",
     "aaciiinnoptt", "aiknoorssttw", "aaelnprrstuu", "aegghiilnnst", "aabcdginorst"]
    |> Enum.into(HashSet.new)
  end
end
