defmodule Jumble.ScowlDict.Size35.Length15 do
  def get(string_id) do
    %{"cceeehhnoopprss" => ["phosphorescence"],
      "aadeiimoppprrst" => ["misappropriated"],
      "ccdeeennooprrss" => ["correspondences"],
      "aacceilrrrrtuux" => ["extracurricular"],
      "aacghillnoooprt" => ["anthropological"],
      "aeehiimnnopprss" => ["misapprehension"],
      "aeeiilnoorrstuv" => ["revolutionaries"],
      "aadiiimnnorsstt" => ["administrations"],
      "aaehiilortttuvy" => ["authoritatively"],
      "acdefiiilnnotty" => ["confidentiality"],
      "aiilnooopprrtty" => ["proportionality"],
      "aceilnnoorrstuv" => ["uncontroversial"],
      "aaeiilnnorrsttt" => ["transliteration"],
      "eegiiimnnprrstt" => ["misinterpreting"],
      "adeeeghinnrssst" => ["nearsightedness"],
      "aaeiimoppprrsst" => ["misappropriates"],
      "aaeilnnnossttuy" => ["instantaneously"],
      "aabdeinnsstttuu" => ["unsubstantiated"],
      "cceegiiinnnnnov" => ["inconveniencing"],
      "abeeiiillnrstuv" => ["vulnerabilities"],
      "acefiiinnooprst" => ["personification"],
      "aeeiinnoprrsttt" => ["interpretations"],
      "adghiinnnostttw" => ["notwithstanding"],
      "aadeiilnopsssty" => ["dispassionately"],
      "cegiilmnoprsstu" => ["multiprocessing"],
      "aeiillnnnnottuy" => ["unintentionally"],
      "deiiinoopprssst" => ["predispositions"],
      "acdiillnnnootuy" => ["unconditionally"],
      "aaaccehilmprstu" => ["pharmaceuticals"],
      "cddeeeeeinnnprt" => ["interdependence"],
      "aeeehilorsttuxy" => ["heterosexuality"],
      "acdeegimnorsstu" => ["discouragements"],
      "adeeemnnrsstttu" => ["understatements"],
      "adeeffiiinnortt" => ["differentiation"],
      "aceehhiopprssty" => ["psychotherapies"],
      "accehilmmnopsst" => ["accomplishments"],
      "aacccehiirrsstt" => ["characteristics"],
      "abdiiinnnoorstu" => ["insubordination"],
      "cdegilnnooprrsy" => ["correspondingly"],
      "aacehillmpsttyy" => ["sympathetically"],
      "accghilllnooory" => ["chronologically"],
      "acceeegilmnortt" => ["electromagnetic"],
      "acceiiilnnoorst" => ["reconciliations"],
      "aeeiilmmnnopstt" => ["implementations"],
      "acceiimmnnootux" => ["excommunication"],
      "aceeiilnnnoqstu" => ["inconsequential"],
      "ceeeflnorrsssuu" => ["resourcefulness"],
      "aciiillmnopsttu" => ["multiplications"],
      "aghhillmooopstt" => ["ophthalmologist"],
      "bdehiiloorssttt" => ["bloodthirstiest"],
      "aafimnnoorrsstt" => ["transformations"],
      "abbeiiiilmoprst" => ["improbabilities"],
      "beiiiiilmopssst" => ["impossibilities"],
      "ceeehilmnoprsvy" => ["comprehensively"],
      "aeeeinnoprrsstt" => ["representations"],
      "cceeinnoosssssu" => ["consciousnesses"],
      "aabeghiiooprstu" => ["autobiographies"],
      "aadeiilnorrrtxy" => ["extraordinarily"],
      "cceeiiinnnossst" => ["inconsistencies"],
      "eeehoopprstttty" => ["phototypesetter"],
      "aacdiiiilnnprss" => ["disciplinarians"],
      "acceghilllnooty" => ["technologically"],
      "adeiimnnoppsstt" => ["disappointments"],
      "aaciinnooprrstt" => ["procrastination"],
      "aabcceelnnorstu" => ["counterbalances"],
      "accegiimmnnotux" => ["excommunicating"],
      "cceinnoorrssttu" => ["reconstructions"],
      "aacgiinnoprrstt" => ["procrastinating"],
      "aceehiinppprsst" => ["apprenticeships"],
      "acdehiinopssttu" => ["unsophisticated"],
      "aaccdeeknortttu" => ["counterattacked"],
      "deiiillmnnosstu" => ["disillusionment"],
      "aabccdeelnnortu" => ["counterbalanced"],
      "aabceeeghilnnrt" => ["interchangeable"],
      "abdeghiiilnsstu" => ["distinguishable"],
      "aacgilnnoorsttu" => ["congratulations"],
      "aeeillmnnnortvy" => ["environmentally"],
      "eeeinnoprsssttu" => ["pretentiousness"],
      "ddeeegiilnprruv" => ["underprivileged"],
      "aeeeeinprrssttv" => ["representatives"],
      "aacdfiiinossstt" => ["dissatisfaction"],
      "aadfghiorrrsttw" => ["straightforward"],
      "abciiiilmnoptty" => ["incompatibility"],
      "adeeffgiiinnrtt" => ["differentiating"],
      "accghillloopsyy" => ["psychologically"],
      "aaabiiiilmnntty" => ["maintainability"],
      "ceeeiloprrsttvy" => ["retrospectively"],
      "eeegiimnnprrsst" => ["misrepresenting"],
      "ceeprrrsssttuuu" => ["superstructures"],
      "aacceeinnnorsss" => ["reconnaissances"],
      "acdeeimmnnoorst" => ["recommendations"],
      "adeiiiiilmrssst" => ["dissimilarities"],
      "aacegiijknrsttt" => ["straitjacketing"],
      "aaccfiiilnossst" => ["classifications"],
      "adeegiimnnrsttu" => ["underestimating"],
      "aaeiillnnnortty" => ["internationally"],
      "aaaddeginosstuv" => ["disadvantageous"],
      "ahhiilnopprsstt" => ["philanthropists"],
      "aghilnoooprsstt" => ["anthropologists"],
      "aadefilmnnssttu" => ["fundamentalists"],
      "aeeeiimnnoprttx" => ["experimentation"],
      "deeeinnnprssttu" => ["superintendents"],
      "aciilnnoosstttu" => ["constitutionals"],
      "aaaiiilmnorsttt" => ["totalitarianism"]}
    |> Map.get(string_id)
  end

  def valid_ids do
    ["cceeehhnoopprss", "aadeiimoppprrst", "ccdeeennooprrss", "aacceilrrrrtuux",
     "aacghillnoooprt", "aeehiimnnopprss", "aeeiilnoorrstuv", "aadiiimnnorsstt",
     "aaehiilortttuvy", "acdefiiilnnotty", "aiilnooopprrtty", "aceilnnoorrstuv",
     "aaeiilnnorrsttt", "eegiiimnnprrstt", "adeeeghinnrssst", "aaeiimoppprrsst",
     "aaeilnnnossttuy", "aabdeinnsstttuu", "cceegiiinnnnnov", "abeeiiillnrstuv",
     "acefiiinnooprst", "aeeiinnoprrsttt", "adghiinnnostttw", "aadeiilnopsssty",
     "cegiilmnoprsstu", "aeiillnnnnottuy", "deiiinoopprssst", "acdiillnnnootuy",
     "aaaccehilmprstu", "cddeeeeeinnnprt", "aeeehilorsttuxy", "acdeegimnorsstu",
     "adeeemnnrsstttu", "adeeffiiinnortt", "aceehhiopprssty", "accehilmmnopsst",
     "aacccehiirrsstt", "abdiiinnnoorstu", "cdegilnnooprrsy", "aacehillmpsttyy",
     "accghilllnooory", "acceeegilmnortt", "acceiiilnnoorst", "aeeiilmmnnopstt",
     "acceiimmnnootux", "aceeiilnnnoqstu", "ceeeflnorrsssuu", "aciiillmnopsttu",
     "aghhillmooopstt", "bdehiiloorssttt", "aafimnnoorrsstt", "abbeiiiilmoprst",
     "beiiiiilmopssst", "ceeehilmnoprsvy", "aeeeinnoprrsstt", "cceeinnoosssssu",
     "aabeghiiooprstu", "aadeiilnorrrtxy", "cceeiiinnnossst", "eeehoopprstttty",
     "aacdiiiilnnprss", "acceghilllnooty", "adeiimnnoppsstt", "aaciinnooprrstt",
     "aabcceelnnorstu", "accegiimmnnotux", "cceinnoorrssttu", "aacgiinnoprrstt",
     "aceehiinppprsst", "acdehiinopssttu", "aaccdeeknortttu", "deiiillmnnosstu",
     "aabccdeelnnortu", "aabceeeghilnnrt", "abdeghiiilnsstu", "aacgilnnoorsttu",
     "aeeillmnnnortvy", "eeeinnoprsssttu", "ddeeegiilnprruv", "aeeeeinprrssttv",
     "aacdfiiinossstt", "aadfghiorrrsttw", "abciiiilmnoptty", "adeeffgiiinnrtt",
     "accghillloopsyy", "aaabiiiilmnntty", "ceeeiloprrsttvy", "eeegiimnnprrsst",
     "ceeprrrsssttuuu", "aacceeinnnorsss", "acdeeimmnnoorst", "adeiiiiilmrssst",
     "aacegiijknrsttt", "aaccfiiilnossst", "adeegiimnnrsttu", "aaeiillnnnortty",
     "aaaddeginosstuv", "ahhiilnopprsstt", "aghilnoooprsstt", "aadefilmnnssttu",
     "aeeeiimnnoprttx", "deeeinnnprssttu", "aciilnnoosstttu", "aaaiiilmnorsttt"]
    |> Enum.into(HashSet.new)
  end
end
