defmodule Jumble.ScowlDict.Size20.Length4 do
  def get(string_id) do
    %{"ekow" => ["woke"], "hstu" => ["shut", "thus"], "eilm" => ["mile"],
      "hloy" => ["holy"], "gimr" => ["grim"], "intw" => ["twin"],
      "gnos" => ["song"], "adip" => ["paid"], "dehs" => ["shed"],
      "aegv" => ["gave"], "aees" => ["ease"], "iquz" => ["quiz"],
      "blow" => ["bowl", "blow"], "aept" => ["tape"], "gstu" => ["guts"],
      "eilt" => ["tile"], "best" => ["best", "bets"], "aesy" => ["easy"],
      "bill" => ["bill"], "afir" => ["fair"], "aeht" => ["hate", "heat"],
      "achp" => ["chap"], "elos" => ["sole", "lose"], "eert" => ["tree"],
      "aikn" => ["akin"], "diks" => ["kids", "disk"], "ceir" => ["rice"],
      "emos" => ["some"], "agot" => ["goat"], "ceor" => ["core"],
      "ahst" => ["hats"], "cikp" => ["pick"], "iqtu" => ["quit"],
      "egst" => ["gets"], "aelt" => ["tale", "late"], "amps" => ["maps"],
      "antw" => ["want"], "aitx" => ["taxi"], "eils" => ["lies"],
      "ehlp" => ["help"], "deln" => ["lend"], "arsw" => ["wars"],
      "foor" => ["roof"], "aemx" => ["exam"], "eekw" => ["week"],
      "adhr" => ["hard"], "amss" => ["mass"], "afhl" => ["half"],
      "adds" => ["adds"], "fssu" => ["fuss"], "loot" => ["tool"],
      "deeg" => ["edge"], "ackp" => ["pack"], "ahtw" => ["what"],
      "beit" => ["bite"], "aklr" => ["lark"], "elru" => ["rule"],
      "ikss" => ["kiss"], "dnos" => ["dons"], "elns" => ["lens"],
      "hosw" => ["show"], "deem" => ["deem"], "arwy" => ["wary"],
      "eorw" => ["wore"], "pttu" => ["putt"], "bllu" => ["bull"],
      "akmr" => ["mark"], "chop" => ["chop"], "hrtu" => ["hurt"],
      "dorw" => ["word"], "agns" => ["sang", "snag"], "hntu" => ["hunt"],
      "acev" => ["cave"], "pstu" => ["puts"], "eipp" => ["pipe"],
      "noos" => ["soon"], "fgit" => ["gift"], "cmsu" => ["scum", "cums"],
      "aehr" => ["hear"], "cdeo" => ["code"], "loos" => ["solo"],
      "adry" => ["yard"], "diov" => ["void"], "dmru" => ["drum"],
      "deis" => ["dies", "side"], "iklm" => ["milk"], "delo" => ["dole"],
      "dilw" => ["wild"], "imot" => ["omit"], "hist" => ["hits", "this"],
      "nort" => ["torn"], "irst" => ["stir"], "admn" => ["damn"],
      "mstu" => ["must"], "cdlo" => ["cold"], "fnot" => ["font"],
      "afmo" => ["foam"], "aceg" => ["cage"], "entu" => ["tune"],
      "imnt" => ["mint"], "acht" => ["chat"], "bety" => ["byte"],
      "aegs" => ["ages"], "ilps" => ["lips", "lisp", "slip"], "eopp" => ["pope"],
      "know" => ["know"], "fglu" => ["gulf"], "essu" => ["sues", "uses"],
      "elry" => ["rely"], "emop" => ["poem"], "aknt" => ["tank"],
      "aelm" => ["male", "meal"], "ehmt" => ["them"], "hmow" => ["whom"],
      "dlou" => ["loud"], "eirs" => ["rise"], "ilos" => ["soil"],
      "losw" => ["slow"], "ejko" => ["joke"], "ehmo" => ["home"],
      "einv" => ["vein"], "ailn" => ["nail", "lain"], "eorz" => ["zero"],
      "mnor" => ["norm"], "gips" => ["pigs"], "aegw" => ["wage"],
      "ipst" => ["spit", "tips"], "ainr" => ["rain"], "assy" => ["says"],
      "illp" => ["pill"], "adis" => ["aids", "said"], "aclo" => ["coal"],
      "acst" => ["cast", "cats", "acts"], "arty" => ["tray"], "imsw" => ["swim"],
      "agin" => ["gain"], "aefl" => ["leaf"], "efls" => ["self"],
      "amot" => ["atom"], "cikk" => ["kick"], "lnoy" => ["only"],
      "knsu" => ["sunk"], "flou" => ["foul"], "bgos" => ["bogs"],
      "aehv" => ["have"], "osst" => ["toss"], "bkoo" => ["book"],
      "belu" => ["blue"], "aerr" => ["rear", "rare"], "acdr" => ["card"],
      "cltu" => ["cult"], "efiw" => ["wife"], "astv" => ["vast"],
      "bhot" => ["both"], "ilms" => ["slim"], "acer" => ["care", "race"],
      "dfnu" => ["fund"], "desu" => ["sued", "used"], "alor" => ["oral"],
      "ader" => ["dare", "dear", "read"], "iort" => ["riot"], "bdes" => ["beds"],
      "foot" => ["foot"], "denv" => ["vend"], "admp" => ["damp"],
      "aegr" => ["gear", "rage"], "lopt" => ["plot"], "adlo" => ["load"],
      "egls" => ["legs"], "adot" => ["toad"], "bblu" => ["bulb"],
      "bdis" => ["bids"], "dehr" => ["herd"], "mnoo" => ["moon"],
      "aehp" => ["heap"], "apry" => ["pray"], "alpy" => ["play"],
      "hisw" => ["wish"], "ahrs" => ["rash"], "elmo" => ["mole"],
      "cehw" => ["chew"], "adps" => ["pads"], "dluy" => ["duly"],
      "allt" => ["tall"], "aims" => ["aims"], "afmr" => ["farm"],
      "ainp" => ["pain"], "jmpu" => ["jump"], "estw" => ["wets", "west"],
      "abes" => ["base"], "asty" => ["stay"], "bent" => ["bent"],
      "adns" => ["sand"], "aben" => ["bean"], "belt" => ["belt"],
      "dgru" => ["drug"], "ekrt" => ["trek"], "bjos" => ["jobs"],
      "amny" => ["many"], "bclu" => ["club"], "ghhi" => ["high"],
      "egru" => ["urge"], "chir" => ["rich"], "adet" => ["date"],
      "inot" => ["into"], "aert" => ["tear", "rate"], "ehty" => ["they"],
      "cein" => ["nice"], "beer" => ["beer"], "eekp" => ["keep"],
      "illm" => ["mill"], "abot" => ["boat"], "bceu" => ["cube"],
      "dees" => ["seed"], "emrt" => ["term"], "cpsu" => ["cups"],
      "aflt" => ["flat"], "aesv" => ["save"], "been" => ["been"],
      "dimn" => ["mind"], "adhs" => ["dash"], "hkoo" => ["hook"],
      "cell" => ["cell"], "aeft" => ["feat", "fate"], "abem" => ["beam"],
      "loop" => ["loop", "pool"], "eemr" => ["mere"], "anps" => ["span"],
      "eost" => ["toes"], "adsy" => ["days"], "ghis" => ["sigh"],
      "abdu" => ["baud"], "cetu" => ["cute"], "nost" => ["tons"],
      "bdoy" => ["body"], "glpu" => ["plug"], "eilp" => ["pile"],
      "acpr" => ["crap"], "ghnu" => ["hung"], "agps" => ["gaps", "gasp"],
      "deos" => ["dose", "does"], "dllu" => ["dull"], "aels" => ["seal", "sale"],
      "opsu" => ["opus", "soup"], "film" => ["film"], "bmnu" => ["numb"],
      "enno" => ["none"], "nosw" => ["owns", "snow"], "apsw" => ["swap"],
      "alos" => ["also"], "ejkr" => ["jerk"], "adft" => ["daft"],
      "nnoo" => ["noon"], "acrs" => ["cars"], "alst" => ["salt", "last"],
      "llop" => ["poll"], "eflw" => ["flew"], "bdet" => ["debt"],
      "imss" => ["miss"], "efir" => ["fire"], "ikll" => ["kill"],
      "hips" => ["ship"], "bgsu" => ["bugs"], "eekn" => ["knee", "keen"],
      "aekw" => ["wake", "weak"], "aekl" => ["lake", "leak"],
      "deno" => ["node", "done"], "ejst" => ["jest"], "bmoo" => ["boom"],
      "acft" => ["fact"], "ddei" => ["died"], "acek" => ["cake"],
      "hnor" => ["horn"], "bklu" => ["bulk"], "ceop" => ["cope"],
      "ahpt" => ["path"], "dirt" => ["dirt"], "beef" => ["beef"],
      "llpu" => ["pull"], "eghu" => ["huge"], "afil" => ["fail"],
      "dlot" => ["told"], "bder" => ["bred"], "abel" => ["able"],
      "lpsu" => ["plus"], "betu" => ["tube"], "jstu" => ["just"],
      "bnor" => ["born"], "bdmu" => ["dumb"], "abdn" => ["band"],
      "aekm" => ["make"], "ikps" => ["skip"], "eeks" => ["seek"],
      "egor" => ["ergo"], "eorv" => ["over"], "ahmr" => ["harm"],
      "ehlo" => ["hole"], "notw" => ["wont", "town"], "ertu" => ["true"],
      "abst" => ["tabs"], "dhis" => ["dish"], "belw" => ["blew"],
      "adln" => ["land"], "ally" => ["ally"], "bilm" => ["limb"],
      "gsuy" => ["guys"], "abkn" => ["bank"], "eflt" => ["felt", "left"],
      "oruy" => ["your"], "mooz" => ["zoom"], "eimt" => ["emit", "item", "time"],
      "eels" => ["else"], "nrtu" => ["turn"], "prsu" => ["spur"],
      "intu" => ["unit"], "oort" => ["root"], "dnow" => ["down"],
      "npsu" => ["puns"], "ortu" => ["rout", "tour"], "afst" => ["fast"],
      "dity" => ["tidy"], "aest" => ["seat", "east", "eats"], "cdek" => ["deck"],
      "beno" => ["bone"], "dstu" => ["dust"], "aijl" => ["jail"],
      "acks" => ["sack"], "emov" => ["move"], "mppu" => ["pump"],
      "berv" => ["verb"], "derw" => ["drew"], "hmty" => ["myth"],
      "eenv" => ["even"], "ikns" => ["sink", "skin"], "ajms" => ["jams"],
      "msuw" => ["swum"], "aces" => ["case"], "bilo" => ["boil"],
      "agls" => ["slag"], "ceiv" => ["vice"], "elnt" => ["lent"],
      "chmu" => ["much"], "eins" => ["sine"], "cnor" => ["corn"],
      "deef" => ["feed"], "aipr" => ["pair"], "eesy" => ["eyes"],
      "ahtt" => ["that"], "elor" => ["role"], "aefr" => ["fare", "fear"],
      "eirw" => ["wire"], "nstu" => ["nuts", "stun"], "bosy" => ["boys"],
      "aefs" => ["safe"], "bden" => ["bend"], "deks" => ["desk"],
      "deep" => ["deep"], "ehll" => ["hell"], "adgr" => ["drag"],
      "envy" => ["envy"], "acem" => ["came"], "elop" => ["pole"],
      "abet" => ["beat", "beta"], "nrsu" => ["runs"], "antu" => ["aunt"],
      "dfoo" => ["food"], "aent" => ["neat"], "eotv" => ["vote"],
      "afgl" => ["flag"], "lost" => ["slot", "lost", "lots"], "eens" => ["seen"],
      "enot" => ["tone", "note"], "ijno" => ["join"], "aals" => ["alas"],
      "door" => ["door"], "emor" => ["more"], "bhsu" => ["bush"],
      "aklw" => ["walk"], "bblo" => ["blob"], "illw" => ["will"],
      "inpt" => ["pint"], "eerw" => ["were"], "ails" => ["sail"],
      "aemt" => ["mate", "meat", "tame", "team"], "inor" => ["iron"],
      "fost" => ["soft"], "aegp" => ["page"], "arst" => ["arts", "rats", "star"],
      "amrw" => ["warm"], "bssu" => ["buss"], "bdlo" => ["bold"],
      "boot" => ["boot"], "alsw" => ["laws"], "dikn" => ["kind"],
      "aimn" => ["main"], "aerv" => ["rave"], "cstu" => ["cuts"],
      "aops" => ["soap"], "acot" => ["coat"], "fglo" => ["golf"],
      "abht" => ["bath"], "cosw" => ["cows"], "elss" => ["less"],
      "cdei" => ["dice"], "adeg" => ["aged"], "eisw" => ["wise"],
      "copy" => ["copy"], "ciks" => ["sick"], "noot" => ["onto"],
      "eiln" => ["line"], "aags" => ["saga"], "bdno" => ["bond"],
      "nptu" => ["punt"], "alsy" => ["lays"], "ailr" => ["rail"],
      "gilr" => ["girl"], "aenr" => ["earn", "near"], "aegm" => ["game"],
      "efil" => ["file", "life"], "kloo" => ["look"], "emst" => ["stem"],
      "deil" => ["idle", "lied"], "adeh" => ["head"], "deor" => ["rode"],
      "dost" => ["dots"], "lopy" => ["ploy"], "ahlt" => ["halt"],
      "ceit" => ["cite"], "enos" => ["nose", "ones"], "cikn" => ["nick"],
      "gipr" => ["grip"], "abgr" => ["grab"], "adil" => ["dial", "laid"],
      "ehor" => ["hero"], "glos" => ["logs"], "cloo" => ["cool"],
      "aelp" => ["leap", "pale", "plea"], "dffu" => ["duff"], "chin" => ["inch"],
      "notu" => ["unto"], "eefr" => ["free"], "ipty" => ["pity"],
      "dtuy" => ["duty"], "efiv" => ["five"], "moor" => ["room"],
      "akpr" => ["park"], "bnru" => ["burn"], "esst" => ["sets"],
      "opru" => ["pour"], "oopr" => ["poor"], "acnt" => ["cant"],
      "aflw" => ["flaw"], "bcku" => ["buck"], "fist" => ["fits"],
      "aprw" => ["warp", "wrap"], "eerv" => ["ever"], "horu" => ["hour"],
      "aawy" => ["away"], "ckmo" => ["mock"], "ddee" => ["deed"],
      "aefm" => ["fame"], "floo" => ["fool"], "enop" => ["open"],
      "aems" => ["same"], "afns" => ["fans"], "efsu" => ["fuse"],
      "eitx" => ["exit"], "efmu" => ["fume"], "egiv" => ["give"],
      "eegn" => ["gene"], "demn" => ["mend"], "opps" => ["pops"],
      "hpsu" => ["push"], "dein" => ["dine"], "aclm" => ["calm"],
      "eirt" => ["tire"], "inss" => ["sins"], "dfin" => ["find"],
      "korw" => ["work"], "fimr" => ["firm"], "host" => ["shot", "host"],
      "cest" => ["sect"], "orsu" => ["ours"], "eflu" => ["fuel"],
      "osty" => ["toys"], "aens" => ["sane"], "ahsw" => ["wash"],
      "elmt" => ["melt"], "jruy" => ["jury"], "abrs" => ["bars"],
      "aswy" => ["ways"], "boss" => ["boss"], "koot" => ["took"],
      "entx" => ["next"], "ceip" => ["epic"], "abek" => ["bake"],
      "nnou" => ["noun"], "aevw" => ["wave"], "cklo" => ["lock"],
      "eist" => ["site", "ties"], "eors" => ["rose", "sore"],
      "bsuy" => ["busy", "buys"], "efin" => ["fine"], "aery" => ["year"],
      "hill" => ["hill"], "acmp" => ["camp"], "ckmu" => ["muck"],
      "allw" => ["wall"], "elov" => ["love"], "eops" => ["pose"],
      "egrw" => ["grew"], "ackl" => ["lack"], "copr" => ["crop"],
      "kopr" => ["pork"], "cemo" => ["come"], "bbos" => ["bobs"],
      "nosu" => ["onus"], "bstu" => ["bust"], "aitw" => ["wait"],
      "adel" => ["deal", "lead"], "aerw" => ["wear"],
      "opst" => ["opts", "tops", "post", "spot", "stop"], "abis" => ["bias"],
      "ensw" => ["news"], "llnu" => ["null"], "llor" => ["roll"],
      "deit" => ["diet", "edit", "tied"], "eimn" => ["mine"], "amns" => ["mans"],
      "dent" => ["tend"], "ahyz" => ["hazy"], "dmpu" => ["dump"],
      "apst" => ["past"], "noss" => ["sons"], "deiw" => ["wide"],
      "cdis" => ["disc"], "gluy" => ["ugly"], "orsw" => ["rows"],
      "dgir" => ["grid"], "erst" => ["rest"], "lmpu" => ["lump"],
      "aadt" => ["data"], "ahhs" => ["hash"], "aekt" => ["take"],
      "dehi" => ["hide"], "alnw" => ["lawn"], "eepr" => ["peer"],
      "defy" => ["defy"], "fllu" => ["full"], "eems" => ["seem"],
      "ilst" => ["list"], "einw" => ["wine"], "cglo" => ["clog"],
      "alyz" => ["lazy"], "eglu" => ["glue"], "bist" => ["bits"],
      "acns" => ["cans", "scan"], "amry" => ["army"], "acep" => ["pace"],
      "aaer" => ["area"], "fgor" => ["frog"], "afll" => ["fall"],
      "beor" => ["bore"], "dgoo" => ["good"], "eikl" => ["like"],
      "efll" => ["fell"], "aggn" => ["gang"], "ceru" => ["cure"],
      "emnu" => ["menu"], "cilp" => ["clip"], "anrt" => ["rant"],
      "celu" => ["clue"], "anrw" => ["warn"], "egos" => ["egos", "goes"],
      "abkr" => ["bark"], "egno" => ["gone"], "aers" => ["ears"],
      "glno" => ["long"], "insw" => ["wins"], "norw" => ["worn"],
      "aglo" => ["goal"], "achk" => ["hack"], "nopu" => ["upon"],
      "ahll" => ["hall"], "amrs" => ["arms"], "city" => ["city"],
      "eksy" => ["keys"], "acll" => ["call"], "eipw" => ["wipe"],
      "anpt" => ["pant"], "epst" => ["step"], "denr" => ["rend"],
      "botu" => ["bout"], "inps" => ["pins", "spin"], "bdin" => ["bind"],
      "doow" => ["wood"], "aisx" => ["axis"], "deen" => ["need"],
      "chsu" => ["such"], "imst" => ["mist"], "enoz" => ["zone"],
      "ahir" => ["hair"], "almp" => ["lamp"], "aprt" => ["part", "trap"],
      "ervy" => ["very"], "cklu" => ["luck"], "eosw" => ["owes"],
      "akst" => ["task"], "abck" => ["back"], "eeft" => ["feet"],
      "istu" => ["suit"], "eeht" => ["thee"], "llot" => ["toll"],
      "akss" => ["asks"], "aemn" => ["mean", "name"], "fill" => ["fill"],
      "emot" => ["tome"], "dinw" => ["wind"], "gloo" => ["logo"],
      "eemt" => ["meet"], "eefl" => ["feel"], "ikrs" => ["risk"],
      "cikt" => ["tick"], "esxy" => ["sexy"], "aefk" => ["fake"],
      "dfno" => ["fond"], "epty" => ["type"], "aekp" => ["peak"],
      "adkr" => ["dark"], "glnu" => ["lung"], "adde" => ["dead"],
      "adew" => ["wade"], "achs" => ["cash"], "gnow" => ["gown"],
      "eisz" => ["size"], "iprs" => ["rips"], "achr" => ["arch", "char"],
      "klru" => ["lurk"], "ckor" => ["rock"], "dnou" => ["undo"],
      "ettx" => ["text"], "ehnw" => ["when"], "loss" => ["loss"],
      "dgis" => ["digs"], "adnw" => ["dawn"], "mssu" => ["sums"],
      "inst" => ["tins"], "bbmo" => ["bomb"], "bmpu" => ["bump"],
      "cent" => ["cent"], "adly" => ["lady"], "ginw" => ["wing"],
      "eilv" => ["evil", "vile", "live"], "akns" => ["sank"], "dilm" => ["mild"],
      "gorw" => ["grow"], "adgl" => ["glad"], "glow" => ["glow"],
      "dhlo" => ["hold"], "ikln" => ["link"], "aepr" => ["rape"],
      "ehop" => ["hope"], "desw" => ["weds"], "acjk" => ["jack"],
      "ekpt" => ["kept"], "aeln" => ["lane", "lean"], "most" => ["most"],
      "filp" => ["flip"], "cdku" => ["duck"], "adem" => ["made"],
      "alnp" => ["plan"], "ahnt" => ["than"], "gnsu" => ["guns", "sung"],
      "deow" => ["owed"], "isst" => ["sits"], "deiv" => ["dive"],
      "ajzz" => ["jazz"], "ikst" => ["kits"], "eopr" => ["rope"],
      "fmor" => ["form", "from"], "enps" => ["pens"], "ackr" => ["rack"],
      "abns" => ["bans"], "eort" => ["tore"], "abss" => ["bass"],
      "eity" => ["yeti"], "inty" => ["tiny"], "eopt" => ["poet"],
      "ckoo" => ["cook"], "bell" => ["bell"], "abby" => ["baby"],
      "aelr" => ["real"], "deir" => ["dire", "ride"], "morw" => ["worm"],
      "himw" => ["whim"], "dens" => ["ends", "send"], "deru" => ["rude"],
      "acdi" => ["acid"], "ansv" => ["vans"], "ehos" => ["shoe"],
      "enst" => ["nest", "nets", "tens", "sent"], "ellt" => ["tell"],
      "emss" => ["mess"], "fino" => ["info"], "ehnt" => ["then"],
      "eefs" => ["fees"], "adef" => ["deaf"], "hrsu" => ["rush"],
      "dipr" => ["drip"], "alno" => ["loan"], "cost" => ["cost"],
      "ceho" => ["echo"], "dlos" => ["sold"], "eggs" => ["eggs"],
      "abhs" => ["bash"], "flow" => ["wolf", "flow"], "ackt" => ["tack"],
      "elst" => ["lest", "lets"], "lppu" => ["pulp"], "acps" => ["caps"],
      "dopr" => ["drop"], "filt" => ["lift"], "adhn" => ["hand"],
      "iprt" => ["trip"], "dirs" => ["rids"], "beoy" => ["obey"],
      "blot" => ["bolt"], "bruy" => ["bury"], "enrw" => ["wren"],
      "dflo" => ["fold"], "ador" => ["road"], "aemz" => ["maze"],
      "oprt" => ["port"], "ceim" => ["mice"], "ginr" => ["ring"],
      "eivw" => ["wive", "view"], "ckos" => ["sock"], "adlu" => ["dual"],
      "ddos" => ["odds"], "acef" => ["face"], "abgn" => ["bang"],
      "ekop" => ["poke"], "bdir" => ["bird"], "amsw" => ["swam"],
      "ainv" => ["vain"], "ceko" => ["coke"], "hitw" => ["with"],
      "abll" => ["ball"], "illt" => ["till"], "estt" => ["test"],
      "lstu" => ["lust"], "ilno" => ["lion"], "deny" => ["deny"],
      "ailt" => ["tail"], "foru" => ["four"], "deps" => ["sped"],
      "nnsu" => ["nuns"], "gmsu" => ["mugs", "smug"], "ailm" => ["mail"],
      "ells" => ["sell"], "ellw" => ["well"], "adei" => ["idea"],
      "aesx" => ["axes"], "eess" => ["sees"], "apsy" => ["pays"],
      "adir" => ["raid"], "dmoo" => ["doom", "mood"], "aeks" => ["sake"],
      "epru" => ["pure"], "aghn" => ["hang"], "einn" => ["nine"],
      "anwy" => ["yawn"], "agnr" => ["rang"], "gins" => ["sing", "sign"],
      "apss" => ["pass"], "abgs" => ["bags"], "jknu" => ["junk"],
      "losu" => ["soul"], "aknr" => ["rank"], "eknw" => ["knew"],
      "iknp" => ["pink"], "aceh" => ["each"], "akms" => ["mask"],
      "ehir" => ["hire"], "inru" => ["ruin"], "orst" => ["sort"],
      "dlor" => ["lord"], "gnru" => ["rung"], "eehl" => ["heel"],
      "demo" => ["mode"], "ersu" => ["sure", "user"], "ahil" => ["hail"],
      "hint" => ["hint", "thin"], "aber" => ["bare", "bear"], "cekn" => ["neck"],
      "gikn" => ["king"], "cerw" => ["crew"], "chip" => ["chip"],
      "aklt" => ["talk"], "abls" => ["labs"], "arvy" => ["vary"],
      "fhis" => ["fish"], "hotu" => ["thou"], "hops" => ["shop"],
      "dgos" => ["dogs", "gods"], "enrt" => ["rent"], "fkor" => ["fork"],
      "aegt" => ["gate"], "dehl" => ["held"], "fklo" => ["folk"],
      "cino" => ["coin", "icon"], "amno" => ["moan"], "entw" => ["went"],
      "ceno" => ["once"], "eehr" => ["here"], "dils" => ["slid"],
      "dglo" => ["gold"], "adrw" => ["ward", "draw"]}
    |> Map.get(string_id)
  end

  def valid_ids do
    ["ekow", "hstu", "eilm", "hloy", "gimr", "intw", "gnos", "adip", "dehs", "aegv",
     "aees", "iquz", "blow", "aept", "gstu", "eilt", "best", "aesy", "bill", "afir",
     "aeht", "achp", "elos", "eert", "aikn", "diks", "ceir", "emos", "agot", "ceor",
     "ahst", "cikp", "iqtu", "egst", "aelt", "amps", "antw", "aitx", "eils", "ehlp",
     "deln", "arsw", "foor", "aemx", "eekw", "adhr", "amss", "afhl", "adds", "fssu",
     "loot", "deeg", "ackp", "ahtw", "beit", "aklr", "elru", "ikss", "dnos", "elns",
     "hosw", "deem", "arwy", "eorw", "pttu", "bllu", "akmr", "chop", "hrtu", "dorw",
     "agns", "hntu", "acev", "pstu", "eipp", "noos", "fgit", "cmsu", "aehr", "cdeo",
     "loos", "adry", "diov", "dmru", "deis", "iklm", "delo", "dilw", "imot", "hist",
     "nort", "irst", "admn", "mstu", "cdlo", "fnot", "afmo", "aceg", "entu", "imnt",
     "acht", "bety", "aegs", "ilps", "eopp", "know", "fglu", "essu", "elry", "emop",
     "aknt", "aelm", "ehmt", "hmow", "dlou", "eirs", "ilos", "losw", "ejko", "ehmo",
     "einv", "ailn", "eorz", "mnor", "gips", "aegw", "ipst", "ainr", "assy", "illp",
     "adis", "aclo", "acst", "arty", "imsw", "agin", "aefl", "efls", "amot", "cikk",
     "lnoy", "knsu", "flou", "bgos", "aehv", "osst", "bkoo", "belu", "aerr", "acdr",
     "cltu", "efiw", "astv", "bhot", "ilms", "acer", "dfnu", "desu", "alor", "ader",
     "iort", "bdes", "foot", "denv", "admp", "aegr", "lopt", "adlo", "egls", "adot",
     "bblu", "bdis", "dehr", "mnoo", "aehp", "apry", "alpy", "hisw", "ahrs", "elmo",
     "cehw", "adps", "dluy", "allt", "aims", "afmr", "ainp", "jmpu", "estw", "abes",
     "asty", "bent", "adns", "aben", "belt", "dgru", "ekrt", "bjos", "amny", "bclu",
     "ghhi", "egru", "chir", "adet", "inot", "aert", "ehty", "cein", "beer", "eekp",
     "illm", "abot", "bceu", "dees", "emrt", "cpsu", "aflt", "aesv", "been", "dimn",
     "adhs", "hkoo", "cell", "aeft", "abem", "loop", "eemr", "anps", "eost", "adsy",
     "ghis", "abdu", "cetu", "nost", "bdoy", "glpu", "eilp", "acpr", "ghnu", "agps",
     "deos", "dllu", "aels", "opsu", "film", "bmnu", "enno", "nosw", "apsw", "alos",
     "ejkr", "adft", "nnoo", "acrs", "alst", "llop", "eflw", "bdet", "imss", "efir",
     "ikll", "hips", "bgsu", "eekn", "aekw", "aekl", "deno", "ejst", "bmoo", "acft",
     "ddei", "acek", "hnor", "bklu", "ceop", "ahpt", "dirt", "beef", "llpu", "eghu",
     "afil", "dlot", "bder", "abel", "lpsu", "betu", "jstu", "bnor", "bdmu", "abdn",
     "aekm", "ikps", "eeks", "egor", "eorv", "ahmr", "ehlo", "notw", "ertu", "abst",
     "dhis", "belw", "adln", "ally", "bilm", "gsuy", "abkn", "eflt", "oruy", "mooz",
     "eimt", "eels", "nrtu", "prsu", "intu", "oort", "dnow", "npsu", "ortu", "afst",
     "dity", "aest", "cdek", "beno", "dstu", "aijl", "acks", "emov", "mppu", "berv",
     "derw", "hmty", "eenv", "ikns", "ajms", "msuw", "aces", "bilo", "agls", "ceiv",
     "elnt", "chmu", "eins", "cnor", "deef", "aipr", "eesy", "ahtt", "elor", "aefr",
     "eirw", "nstu", "bosy", "aefs", "bden", "deks", "deep", "ehll", "adgr", "envy",
     "acem", "elop", "abet", "nrsu", "antu", "dfoo", "aent", "eotv", "afgl", "lost",
     "eens", "enot", "ijno", "aals", "door", "emor", "bhsu", "aklw", "bblo", "illw",
     "inpt", "eerw", "ails", "aemt", "inor", "fost", "aegp", "arst", "amrw", "bssu",
     "bdlo", "boot", "alsw", "dikn", "aimn", "aerv", "cstu", "aops", "acot", "fglo",
     "abht", "cosw", "elss", "cdei", "adeg", "eisw", "copy", "ciks", "noot", "eiln",
     "aags", "bdno", "nptu", "alsy", "ailr", "gilr", "aenr", "aegm", "efil", "kloo",
     "emst", "deil", "adeh", "deor", "dost", "lopy", "ahlt", "ceit", "enos", "cikn",
     "gipr", "abgr", "adil", "ehor", "glos", "cloo", "aelp", "dffu", "chin", "notu",
     "eefr", "ipty", "dtuy", "efiv", "moor", "akpr", "bnru", "esst", "opru", "oopr",
     "acnt", "aflw", "bcku", "fist", "aprw", "eerv", "horu", "aawy", "ckmo", "ddee",
     "aefm", "floo", "enop", "aems", "afns", "efsu", "eitx", "efmu", "egiv", "eegn",
     "demn", "opps", "hpsu", "dein", "aclm", "eirt", "inss", "dfin", "korw", "fimr",
     "host", "cest", "orsu", "eflu", "osty", "aens", "ahsw", "elmt", "jruy", "abrs",
     "aswy", "boss", "koot", "entx", "ceip", "abek", "nnou", "aevw", "cklo", "eist",
     "eors", "bsuy", "efin", "aery", "hill", "acmp", "ckmu", "allw", "elov", "eops",
     "egrw", "ackl", "copr", "kopr", "cemo", "bbos", "nosu", "bstu", "aitw", "adel",
     "aerw", "opst", "abis", "ensw", "llnu", "llor", "deit", "eimn", "amns", "dent",
     "ahyz", "dmpu", "apst", "noss", "deiw", "cdis", "gluy", "orsw", "dgir", "erst",
     "lmpu", "aadt", "ahhs", "aekt", "dehi", "alnw", "eepr", "defy", "fllu", "eems",
     "ilst", "einw", "cglo", "alyz", "eglu", "bist", "acns", "amry", "acep", "aaer",
     "fgor", "afll", "beor", "dgoo", "eikl", "efll", "aggn", "ceru", "emnu", "cilp",
     "anrt", "celu", "anrw", "egos", "abkr", "egno", "aers", "glno", "insw", "norw",
     "aglo", "achk", "nopu", "ahll", "amrs", "city", "eksy", "acll", "eipw", "anpt",
     "epst", "denr", "botu", "inps", "bdin", "doow", "aisx", "deen", "chsu", "imst",
     "enoz", "ahir", "almp", "aprt", "ervy", "cklu", "eosw", "akst", "abck", "eeft",
     "istu", "eeht", "llot", "akss", "aemn", "fill", "emot", "dinw", "gloo", "eemt",
     "eefl", "ikrs", "cikt", "esxy", "aefk", "dfno", "epty", "aekp", "adkr", "glnu",
     "adde", "adew", "achs", "gnow", "eisz", "iprs", "achr", "klru", "ckor", "dnou",
     "ettx", "ehnw", "loss", "dgis", "adnw", "mssu", "inst", "bbmo", "bmpu", "cent",
     "adly", "ginw", "eilv", "akns", "dilm", "gorw", "adgl", "glow", "dhlo", "ikln",
     "aepr", "ehop", "desw", "acjk", "ekpt", "aeln", "most", "filp", "cdku", "adem",
     "alnp", "ahnt", "gnsu", "deow", "isst", "deiv", "ajzz", "ikst", "eopr", "fmor",
     "enps", "ackr", "abns", "eort", "abss", "eity", "inty", "eopt", "ckoo", "bell",
     "abby", "aelr", "deir", "morw", "himw", "dens", "deru", "acdi", "ansv", "ehos",
     "enst", "ellt", "emss", "fino", "ehnt", "eefs", "adef", "hrsu", "dipr", "alno",
     "cost", "ceho", "dlos", "eggs", "abhs", "flow", "ackt", "elst", "lppu", "acps",
     "dopr", "filt", "adhn", "iprt", "dirs", "beoy", "blot", "bruy", "enrw", "dflo",
     "ador", "aemz", "oprt", "ceim", "ginr", "eivw", "ckos", "adlu", "ddos", "acef",
     "abgn", "ekop", "bdir", "amsw", "ainv", "ceko", "hitw", "abll", "illt", "estt",
     "lstu", "ilno", "deny", "ailt", "foru", "deps", "nnsu", "gmsu", "ailm", "ells",
     "ellw", "adei", "aesx", "eess", "apsy", "adir", "dmoo", "aeks", "epru", "aghn",
     "einn", "anwy", "agnr", "gins", "apss", "abgs", "jknu", "losu", "aknr", "eknw",
     "iknp", "aceh", "akms", "ehir", "inru", "orst", "dlor", "gnru", "eehl", "demo",
     "ersu", "ahil", "hint", "aber", "cekn", "gikn", "cerw", "chip", "aklt", "abls",
     "arvy", "fhis", "hotu", "hops", "dgos", "enrt", "fkor", "aegt", "dehl", "fklo",
     "cino", "amno", "entw", "ceno", "eehr", "dils", "dglo", "adrw"]
    |> Enum.into(HashSet.new)
  end
end
