defmodule Jumble.ScowlDict.Size20.Length7 do
  def get(string_id) do
    %{"ceiprtu" => ["picture"], "deellry" => ["elderly"], "aelnpty" => ["penalty"],
      "abeoqru" => ["baroque"], "bgiknoo" => ["booking"], "ddeeirs" => ["desired"],
      "aegintv" => ["vintage"], "afgiiln" => ["failing"], "aflluwy" => ["awfully"],
      "deemorv" => ["removed"], "ciprsst" => ["scripts"], "cgiiknn" => ["nicking"],
      "abeehsv" => ["behaves"], "adepstu" => ["updates"],
      "adeelrt" => ["altered", "related"],
      "adegiln" => ["aligned", "dealing", "leading"], "aaenruw" => ["unaware"],
      "einnrsw" => ["winners"], "ginoprv" => ["proving"], "giillnw" => ["willing"],
      "cceeins" => ["science"], "ghinnop" => ["phoning"], "hlorsty" => ["shortly"],
      "aegorst" => ["storage"], "cgiknoo" => ["cooking"], "dggijnu" => ["judging"],
      "aeeelrs" => ["release"], "dgisstu" => ["disgust"], "adeefst" => ["defeats"],
      "mmopsty" => ["symptom"], "deloptt" => ["plotted"], "cdeenos" => ["encodes"],
      "aeiprtv" => ["private"], "ddeeinx" => ["indexed"], "elmosuv" => ["volumes"],
      "ehilost" => ["hostile"], "eiorrsw" => ["worries"], "cdeilpp" => ["clipped"],
      "accelno" => ["conceal"], "adilpry" => ["rapidly"], "aeginnr" => ["earning"],
      "acekpst" => ["packets"], "eghilnp" => ["helping"], "ddeippr" => ["dripped"],
      "cemootu" => ["outcome"], "eeefrsz" => ["freezes"], "enrrstu" => ["returns"],
      "ahilppy" => ["happily"], "aginprs" => ["parsing"], "adenpst" => ["pedants"],
      "eegikns" => ["seeking"], "deeirss" => ["resides", "desires"],
      "eorrttu" => ["torture"], "dginnou" => ["undoing"], "adegpru" => ["upgrade"],
      "addeopt" => ["adopted"], "celnoos" => ["console"], "eiorsst" => ["stories"],
      "dfgiinn" => ["finding"], "deioprs" => ["periods"], "aefgilr" => ["fragile"],
      "ainopss" => ["passion"], "defhist" => ["shifted"], "cemnooy" => ["economy"],
      "abborss" => ["absorbs"], "aeilrty" => ["reality"], "aceefpr" => ["preface"],
      "ginoppp" => ["popping"], "adiilnv" => ["invalid"], "eefinrs" => ["refines"],
      "degilnn" => ["lending"], "ailqtuy" => ["quality"], "aeinptt" => ["patient"],
      "aademnt" => ["mandate"], "abginsu" => ["abusing"], "cddeens" => ["descend"],
      "eginnop" => ["opening"], "eoopprs" => ["propose"], "eiknosv" => ["invokes"],
      "eelrstt" => ["letters"], "aaginst" => ["against"], "acejkst" => ["jackets"],
      "cgiklno" => ["locking"], "cdennoo" => ["condone"], "adeimrs" => ["misread"],
      "ceiosty" => ["society"], "ceegint" => ["genetic"], "ainrsst" => ["strains"],
      "acdeeln" => ["cleaned"], "aefginr" => ["fearing"], "beeentw" => ["between"],
      "eknortw" => ["network"], "aailmrt" => ["marital"], "aiorsuv" => ["various"],
      "egimnss" => ["messing"], "eefginr" => ["freeing"], "ceefnor" => ["enforce"],
      "adjsstu" => ["adjusts"], "deiilmp" => ["implied"], "afilquy" => ["qualify"],
      "agiilns" => ["sailing"], "abddenr" => ["branded"], "achmost" => ["stomach"],
      "imorrrs" => ["mirrors"], "addeemn" => ["amended"], "deelorw" => ["lowered"],
      "addegru" => ["guarded"], "gilnosw" => ["slowing"], "eggintt" => ["getting"],
      "gillnor" => ["rolling"], "adikmnn" => ["mankind"], "hiottuw" => ["without"],
      "einrssu" => ["sunrise"], "adilpsy" => ["display"],
      "aeeglnr" => ["enlarge", "general"], "deffnos" => ["offends"],
      "adeersv" => ["adverse"], "ddgiikn" => ["kidding"], "acffirt" => ["traffic"],
      "ginrsst" => ["strings"], "cdeeorv" => ["covered"], "deeeknw" => ["weekend"],
      "adenpps" => ["appends"], "giinnnw" => ["winning"], "deeiops" => ["episode"],
      "acgiknt" => ["tacking"], "cgiikkn" => ["kicking"], "efhilss" => ["selfish"],
      "adehknt" => ["thanked"], "eeirrtw" => ["rewrite"], "giinstu" => ["suiting"],
      "diprstu" => ["disrupt"], "ccesssu" => ["success"], "eeiqrru" => ["require"],
      "aerrstt" => ["starter", "restart"], "behorrt" => ["brother"],
      "aeilnst" => ["entails"], "aelttux" => ["textual"], "eegsssu" => ["guesses"],
      "eehhrtw" => ["whether"], "afissty" => ["satisfy"], "deisttw" => ["twisted"],
      "aadglru" => ["gradual"], "adeflot" => ["floated"], "cdeeitx" => ["excited"],
      "adegnrt" => ["granted"], "deelstt" => ["settled"], "abddeer" => ["bearded"],
      "dginorw" => ["wording"], "acforty" => ["factory"], "ccehios" => ["choices"],
      "ceglooy" => ["ecology"], "cehlost" => ["clothes"], "giiklnn" => ["linking"],
      "bginruy" => ["burying"], "ceeetux" => ["execute"], "aemrstt" => ["matters"],
      "adenstt" => ["attends"], "aeehrtw" => ["weather"], "ceiintz" => ["citizen"],
      "ceelrtu" => ["lecture"], "aderssu" => ["assured"], "ademnss" => ["madness"],
      "cdehkos" => ["shocked"], "bddelou" => ["doubled"], "aeiprrs" => ["repairs"],
      "aflmoru" => ["formula"], "acorrst" => ["carrots"], "eopprsu" => ["purpose"],
      "eilorrs" => ["lorries"], "adeirsv" => ["adviser"], "accehns" => ["chances"],
      "deeegmr" => ["emerged"], "cgilnoo" => ["cooling"], "deegimn" => ["deeming"],
      "egilntt" => ["letting"], "abssuwy" => ["subways"], "addeely" => ["delayed"],
      "ceinsst" => ["insects"], "addenot" => ["donated"], "allsuuy" => ["usually"],
      "defiinu" => ["unified"], "fgilnoo" => ["fooling"], "agmoprr" => ["program"],
      "aginrvy" => ["varying"], "aegilnv" => ["leaving"], "ceikoos" => ["cookies"],
      "aaagmnr" => ["anagram"], "eefhrrs" => ["refresh"], "ablnoty" => ["notably"],
      "einoprt" => ["pointer", "protein"], "adeeiss" => ["disease"],
      "ghhottu" => ["thought"], "eeginnu" => ["genuine"], "adeinst" => ["instead"],
      "ccilsty" => ["cyclist"], "belortu" => ["trouble"], "eeginrt" => ["integer"],
      "eilostt" => ["toilets"], "addefrt" => ["drafted"], "emmssuu" => ["museums"],
      "eghhist" => ["heights", "highest"], "aehnort" => ["another"],
      "deefrsu" => ["refused"], "aabdrst" => ["bastard"], "beefils" => ["beliefs"],
      "deiinot" => ["edition"], "adefhls" => ["flashed"], "erssuvy" => ["surveys"],
      "aelmnru" => ["numeral"], "dgiimnn" => ["minding"], "eloprtt" => ["plotter"],
      "cgiilns" => ["slicing"], "ginorst" => ["sorting", "storing"],
      "ceefprt" => ["perfect"], "acddees" => ["decades"], "agirtvy" => ["gravity"],
      "ehmorst" => ["mothers"], "elmopsy" => ["employs"], "glnoopr" => ["prolong"],
      "acinnot" => ["contain"], "dginott" => ["dotting"], "cginttu" => ["cutting"],
      "abceesu" => ["because"], "accdors" => ["accords"], "giklnoo" => ["looking"],
      "aamnprt" => ["rampant"], "emprttu" => ["trumpet"], "aeisttu" => ["situate"],
      "accistt" => ["tactics"], "eeginnv" => ["evening"], "efgorst" => ["forgets"],
      "giinnru" => ["ruining"], "iinrtty" => ["trinity"], "cdeeopr" => ["proceed"],
      "acdempr" => ["cramped"], "aeggglu" => ["luggage"], "ddeefns" => ["defends"],
      "allotty" => ["totally"], "agloopy" => ["apology"], "aegnntt" => ["tangent"],
      "cdehotu" => ["touched"], "aeelrsx" => ["relaxes"], "ainostt" => ["station"],
      "efilopr" => ["profile"], "ceiilnn" => ["incline"], "adehlnr" => ["handler"],
      "bdegirs" => ["bridges"], "ddginpu" => ["pudding"], "behiitx" => ["exhibit"],
      "aailrwy" => ["railway"], "ccehikn" => ["chicken"], "degopru" => ["grouped"],
      "abginnn" => ["banning"], "ceijstu" => ["justice"], "fgiilln" => ["filling"],
      "cginnnu" => ["cunning"], "eeemrtx" => ["extreme"], "adiknps" => ["kidnaps"],
      "belmopr" => ["problem"], "acforst" => ["factors"], "bbeilqu" => ["quibble"],
      "efhilms" => ["himself"], "gilnosv" => ["solving"], "eimnnot" => ["mention"],
      "inoopst" => ["options"], "ceilnst" => ["clients"], "abelnot" => ["notable"],
      "ceiorru" => ["courier"], "adehlns" => ["handles"], "eimprst" => ["permits"],
      "abeffls" => ["baffles"], "ccgilny" => ["cycling"], "aeinstv" => ["natives"],
      "cenrrtu" => ["current"], "efginrs" => ["fingers"], "aegnrst" => ["strange"],
      "gijmnpu" => ["jumping"], "bemnrsu" => ["numbers"], "delmosu" => ["modules"],
      "emrstyy" => ["mystery"], "cennott" => ["content"], "eeimnnt" => ["eminent"],
      "ahllosw" => ["shallow"], "deersss" => ["dresses"], "aehilvy" => ["heavily"],
      "iimnoss" => ["mission"], "egnoruy" => ["younger"], "giklnru" => ["lurking"],
      "acginst" => ["casting"], "aginstt" => ["tasting", "stating"],
      "aeglmns" => ["mangles"], "ceelmow" => ["welcome"], "acdimny" => ["dynamic"],
      "abcekrt" => ["bracket"], "deginnt" => ["tending"], "beggist" => ["biggest"],
      "eeopssx" => ["exposes"], "chipssy" => ["physics"], "adeprss" => ["spreads"],
      "adhiloy" => ["holiday"], "aiilmrs" => ["similar"], "adeilrt" => ["trailed"],
      "deghilt" => ["delight", "lighted"], "degglpu" => ["plugged"],
      "aclrsty" => ["crystal"], "beilrty" => ["liberty"], "ajlnoru" => ["journal"],
      "aehpprs" => ["perhaps"], "aeilprv" => ["prevail"], "cegnost" => ["congest"],
      "eeimprs" => ["premise"], "acdehmt" => ["matched"], "eilnovv" => ["involve"],
      "eeenpsx" => ["expense"], "bceorsu" => ["obscure"], "adehprs" => ["phrased"],
      "aegopst" => ["postage"], "deegssu" => ["guessed"], "ccilnou" => ["council"],
      "adeginr" => ["reading"], "adeekwy" => ["weekday"], "ceeenss" => ["essence"],
      "ilnsstu" => ["insults"], "ggiinnr" => ["ringing"], "adgiilt" => ["digital"],
      "cgiinpr" => ["pricing"], "addemns" => ["demands"], "hiorsty" => ["history"],
      "cfginor" => ["forcing"], "ccdnotu" => ["conduct"], "aegllly" => ["legally"],
      "abdnoyy" => ["anybody"], "cdeiprt" => ["predict"], "aefgorv" => ["forgave"],
      "acdehrs" => ["crashed"], "deefins" => ["defines"], "deimops" => ["imposed"],
      "accdesu" => ["accused"], "ggilnow" => ["glowing"], "ijlnoty" => ["jointly"],
      "dekopst" => ["desktop"], "cehrssu" => ["crushes"], "acgillo" => ["logical"],
      "agimnrs" => ["margins"], "cceinos" => ["concise"], "bgggino" => ["bogging"],
      "ddelmsu" => ["muddles"], "acinotu" => ["caution"], "aablmsy" => ["abysmal"],
      "ceessux" => ["excuses"], "ehnosty" => ["honesty"], "ddeiisv" => ["divides"],
      "aceiqru" => ["acquire"], "aadkrww" => ["awkward"], "acgikns" => ["sacking"],
      "aeirrsv" => ["arrives"], "ceiknss" => ["sickens"], "abdeglr" => ["garbled"],
      "aeilotv" => ["violate"], "agiilnn" => ["nailing"], "acehrrt" => ["charter"],
      "ainnost" => ["nations"], "eoppssu" => ["suppose"], "acfilry" => ["clarify"],
      "ginopst" => ["posting"], "adennoy" => ["annoyed"], "aeghrst" => ["gathers"],
      "eeiprsx" => ["expires"], "acelnru" => ["nuclear", "unclear"],
      "ainoppt" => ["appoint"], "eeeimns" => ["enemies"], "einosss" => ["session"],
      "cdeelux" => ["exclude"], "begilos" => ["obliges"], "dfginnu" => ["funding"],
      "accilru" => ["crucial"], "eglnost" => ["longest"], "cdeorrs" => ["records"],
      "acdenns" => ["scanned"], "agiintw" => ["waiting"], "ceekrrw" => ["wrecker"],
      "glorssy" => ["grossly"], "aghntuy" => ["naughty"], "fimnors" => ["informs"],
      "aeiprst" => ["parties"], "efhlssu" => ["flushes"], "adehmss" => ["smashed"],
      "eemrssu" => ["resumes"], "abdeffl" => ["baffled"], "ekooprv" => ["provoke"],
      "cemrruy" => ["mercury"], "eilqtuy" => ["quietly"], "afilnpu" => ["painful"],
      "bgiorty" => ["bigotry"], "aafnsty" => ["fantasy"], "ehmoosw" => ["somehow"],
      "abgiins" => ["biasing"], "ccdeesu" => ["succeed"], "adffhno" => ["offhand"],
      "acehstw" => ["watches"], "aeginrw" => ["wearing"], "beorssw" => ["browses"],
      "deeintv" => ["evident"], "deknnru" => ["drunken"], "ailorst" => ["tailors"],
      "dgimnoo" => ["dooming"], "acilpst" => ["plastic"], "ceeffst" => ["effects"],
      "cenrtuy" => ["century"], "deiostu" => ["outside", "tedious"],
      "cepsstu" => ["suspect"], "deeistx" => ["existed"], "addeptu" => ["updated"],
      "eginors" => ["regions", "ignores"], "iiprsst" => ["spirits"],
      "acelrsu" => ["secular"], "aginnrw" => ["warning"], "acehkrs" => ["hackers"],
      "ghinnot" => ["nothing"], "adeqrsu" => ["squared"], "cdehopp" => ["chopped"],
      "acllloy" => ["locally"], "abceens" => ["absence"], "degnoru" => ["undergo"],
      "beginoy" => ["obeying"], "eilmpsu" => ["impulse"], "achlloo" => ["alcohol"],
      "aeemnrs" => ["renames"], "gimmnsu" => ["summing"], "iprstuu" => ["pursuit"],
      "ceffisu" => ["suffice"], "agilnst" => ["lasting"], "deelovv" => ["evolved"],
      "deeppst" => ["stepped"], "ghinott" => ["tonight"], "abcehmr" => ["chamber"],
      "eilnotv" => ["violent"], "enoosst" => ["soonest"], "eefprrs" => ["prefers"],
      "dehmost" => ["methods"], "eeiqrtu" => ["quieter"], "aacegkp" => ["package"],
      "addeiov" => ["avoided"], "ceeipss" => ["species"], "ddenoru" => ["rounded"],
      "ddeoppr" => ["dropped"], "adginrt" => ["trading"], "deoppst" => ["stopped"],
      "abeglrs" => ["garbles"], "effosst" => ["offsets"], "afgilnw" => ["flawing"],
      "aeilpps" => ["applies"], "aefmrrs" => ["farmers"], "eghlnst" => ["lengths"],
      "eelsstt" => ["settles"], "adellow" => ["allowed"], "acchrst" => ["scratch"],
      "aemsssu" => ["assumes"], "eefhort" => ["thereof"], "begintt" => ["betting"],
      "deenost" => ["denotes"], "aacgilm" => ["magical"], "aehippr" => ["happier"],
      "deiistv" => ["visited"], "adeegnr" => ["derange"], "bdillny" => ["blindly"],
      "delpuzz" => ["puzzled"], "eelosvv" => ["evolves"], "aachnry" => ["anarchy"],
      "aelnpst" => ["planets"], "deemrsu" => ["resumed"], "adelmps" => ["sampled"],
      "acddist" => ["addicts"], "abinorw" => ["rainbow"], "deeelst" => ["deletes"],
      "deeiprv" => ["deprive"], "abdefor" => ["forbade"], "aegrstt" => ["targets"],
      "ceenrss" => ["screens"], "cdiiiot" => ["idiotic"], "eefrssu" => ["refuses"],
      "aehprss" => ["phrases"], "aenrssw" => ["answers"], "egorsss" => ["grosses"],
      "cdeestt" => ["detects"], "aeeoprt" => ["operate"], "aefilru" => ["failure"],
      "beggrsu" => ["buggers"], "aaffirs" => ["affairs"], "giinstt" => ["sitting"],
      "einsstw" => ["witness"], "diorstt" => ["distort"], "eirstuv" => ["virtues"],
      "aceffst" => ["affects"], "abdelst" => ["blasted"], "addeehr" => ["adhered"],
      "eehorvw" => ["however", "whoever"], "aeimnrs" => ["remains", "seminar"],
      "adgilno" => ["loading"], "aegimnn" => ["meaning"], "bgilooy" => ["biology"],
      "acdeirr" => ["carried"], "ceeglnt" => ["neglect"], "aeilost" => ["isolate"],
      "efiinsu" => ["unifies"], "eoprtvy" => ["poverty"], "ceeeirv" => ["receive"],
      "adeghin" => ["heading"], "eijnrsu" => ["injures"], "bdeeiss" => ["besides"],
      "acegoru" => ["courage"], "acefinn" => ["finance"], "hinoorz" => ["horizon"],
      "deffstu" => ["stuffed"], "aeeglls" => ["alleges"], "aginprw" => ["warping"],
      "eeilnnt" => ["lenient"], "einprrt" => ["printer"], "aceehiv" => ["achieve"],
      "elloosy" => ["loosely"], "agginnr" => ["ranging"], "abdeils" => ["disable"],
      "accilny" => ["cynical"], "aehrstt" => ["threats"], "adeghlu" => ["laughed"],
      "aceerrs" => ["careers"], "abghins" => ["bashing"], "ainsstu" => ["sustain"],
      "giknorw" => ["working"], "deipstt" => ["spitted"], "eghlnty" => ["lengthy"],
      "adepprw" => ["wrapped"], "amnqtuu" => ["quantum"], "abbirst" => ["rabbits"],
      "eefhlrs" => ["herself"], "aefsstt" => ["fastest"], "cenorrs" => ["corners"],
      "aloppru" => ["popular"], "celopsu" => ["couples"], "adepprt" => ["trapped"],
      "aerssst" => ["asserts"], "achmnor" => ["monarch"], "bbcelor" => ["cobbler"],
      "ceeistx" => ["excites"], "aeegilm" => ["mileage"], "eimoprv" => ["improve"],
      "ehorrst" => ["shorter"], "acemnor" => ["romance"], "bdegilo" => ["obliged"],
      "eginttw" => ["wetting"], "bioosuv" => ["obvious"], "ehorssw" => ["showers"],
      "cekopst" => ["pockets"], "aceklst" => ["tackles"], "cdeinsu" => ["induces"],
      "aorssst" => ["assorts"], "aiiilnt" => ["initial"], "aaegnrr" => ["arrange"],
      "adinstt" => ["distant"], "cnortuy" => ["country"], "beefint" => ["benefit"],
      "bgilnow" => ["blowing"], "eenrtuv" => ["venture"], "egrrsuy" => ["surgery"],
      "cdeeelt" => ["elected"], "acdekrt" => ["tracked"], "cdeeiln" => ["decline"],
      "abdeest" => ["debates"], "giiklln" => ["killing"], "deprsuu" => ["pursued"],
      "beelsss" => ["blesses"], "acehilt" => ["ethical"],
      "ceepstx" => ["excepts", "expects"], "ceeilns" => ["license", "silence"],
      "amnostu" => ["amounts"], "giinntu" => ["uniting"], "aadegms" => ["damages"],
      "aeelpss" => ["pleases"], "acinrtu" => ["curtain"], "aeqrssu" => ["squares"],
      "adghinn" => ["handing"], "aerrsst" => ["arrests"], "bceimno" => ["combine"],
      "aekmrrs" => ["markers", "remarks"], "defnorw" => ["frowned"],
      "aegilns" => ["sealing"], "cddeeru" => ["reduced"], "acfisst" => ["fascist"],
      "eehmort" => ["theorem"], "cdeersw" => ["screwed"], "deefinr" => ["refined"],
      "aaglnoy" => ["analogy"], "aghinrs" => ["sharing"], "dddefil" => ["fiddled"],
      "addeinv" => ["invaded"], "agilnss" => ["signals"], "deiikls" => ["dislike"],
      "aginsss" => ["assigns"], "abertty" => ["battery"], "eilnsst" => ["listens"],
      "aeopprv" => ["approve"], "ghilrty" => ["rightly"], "bdeelss" => ["blessed"],
      "deiopst" => ["deposit"], "acdeilm" => ["decimal", "claimed", "medical"],
      "cceelry" => ["recycle"], "cdeilnu" => ["include"], "cdoorst" => ["doctors"],
      "aeefllt" => ["leaflet"], "cegiiln" => ["ceiling"], "ceimnru" => ["numeric"],
      "aelmpss" => ["samples"], "cemoptu" => ["compute"], "efmoprr" => ["perform"],
      "acehirv" => ["archive"], "aailprt" => ["partial"], "aeghint" => ["heating"],
      "acgilns" => ["scaling"], "aefhlss" => ["flashes"], "eginnpu" => ["penguin"],
      "opprstu" => ["support"], "emmnost" => ["moments"], "ghiinns" => ["shining"],
      "ddeistu" => ["studied"], "eehlrst" => ["shelter"], "fghiins" => ["fishing"],
      "eeorrst" => ["restore"], "eiilmss" => ["missile"], "alnsuuu" => ["unusual"],
      "ccellot" => ["collect"], "acdelot" => ["located"], "acellry" => ["clearly"],
      "eegiknp" => ["keeping"], "dgimnpu" => ["dumping"], "deeiprx" => ["expired"],
      "acemopr" => ["compare"], "aghikns" => ["shaking"], "aemnpty" => ["payment"],
      "fhiorry" => ["horrify"], "egillnt" => ["telling"], "efginor" => ["foreign"],
      "deelopx" => ["explode"], "aginntw" => ["wanting"],
      "ceeiprs" => ["recipes", "precise"], "ddeginw" => ["wedding"],
      "emooprt" => ["promote"], "ehilstw" => ["whistle"], "aeeilrr" => ["earlier"],
      "acelsss" => ["classes"], "aginstw" => ["wasting"], "abdeehv" => ["behaved"],
      "egillns" => ["selling"], "efirrty" => ["terrify"], "ghinrsu" => ["rushing"],
      "eeiqrsu" => ["queries"], "celnosu" => ["counsel"], "aeloprv" => ["overlap"],
      "accelns" => ["cancels"], "deeirsv" => ["diverse", "revised", "derives"],
      "beeorsv" => ["verbose", "observe"], "deiosuv" => ["devious"],
      "bciistu" => ["biscuit"], "ghiltty" => ["tightly"], "eiisstx" => ["sixties"],
      "aaepprs" => ["appears"], "adeilry" => ["readily"],
      "eginstt" => ["setting", "testing"], "acdeetu" => ["educate"],
      "eenprst" => ["present"], "aaddept" => ["adapted"], "acdeeps" => ["escaped"],
      "abhilos" => ["abolish"], "adeelrs" => ["dealers", "leaders"],
      "agilnuv" => ["valuing"], "aeefrtu" => ["feature"], "adilnss" => ["islands"],
      "acdehtw" => ["watched"], "fijstuy" => ["justify"],
      "aderstv" => ["adverts", "starved"], "eehinrt" => ["therein", "neither"],
      "adegrrs" => ["regards"], "afillny" => ["finally"], "eehnstv" => ["seventh"],
      "aalsstu" => ["assault"], "aciprvy" => ["privacy"], "ademnnu" => ["mundane"],
      "aadeitw" => ["awaited"], "afgilln" => ["falling"], "ceffios" => ["offices"],
      "deghist" => ["sighted"], "eeinnst" => ["intense"], "eegrrst" => ["regrets"],
      "aeemrsu" => ["measure"], "cefipsy" => ["specify"], "ddeerss" => ["dressed"],
      "adfhlnu" => ["handful"], "adeeggn" => ["engaged"], "aeeglry" => ["eagerly"],
      "aefinrt" => ["fainter"], "acginps" => ["spacing"], "accehst" => ["catches"],
      "degiint" => ["editing"], "celmopx" => ["complex"], "aeeprst" => ["repeats"],
      "ehiinrt" => ["inherit"], "acdeelr" => ["cleared", "declare"],
      "adegnrs" => ["dangers", "gardens"], "deijnru" => ["injured"],
      "ceinpst" => ["inspect"], "aceghrs" => ["charges"], "dnnosuu" => ["unsound"],
      "aempttt" => ["attempt"], "cklnosu" => ["unlocks"], "aeiinrt" => ["inertia"],
      "aderrst" => ["starred"], "agimnnn" => ["manning"], "ghiprtu" => ["upright"],
      "aadelmr" => ["alarmed"], "cddeinu" => ["induced"], "ccdeehk" => ["checked"],
      "aersstv" => ["starves"], "eginnst" => ["nesting"], "allosww" => ["swallow"],
      "aaknors" => ["anoraks"], "adeelps" => ["pleased"], "aegginr" => ["gearing"],
      "eirsuvv" => ["survive"], "ahnppuy" => ["unhappy"], "aenrstv" => ["servant"],
      "abeilns" => ["lesbian"], "bceenos" => ["obscene"], "acehprt" => ["chapter"],
      "ceghinw" => ["chewing"], "aeehnsv" => ["heavens"], "aderrsw" => ["rewards"],
      "cdennot" => ["contend"], "ghinosw" => ["showing"], "aeggrst" => ["stagger"],
      "bcejost" => ["objects"], "beemmrs" => ["members"], "aellorv" => ["overall"],
      "deirrsv" => ["drivers"], "eimostv" => ["motives"], "nooprss" => ["sponsor"],
      "eeorrtw" => ["rewrote"], "aegillv" => ["village"], "dgnorsu" => ["grounds"],
      "bdfiors" => ["forbids"], "elnnstu" => ["tunnels"], "ahorstt" => ["throats"],
      "adeinrt" => ["trained"], "adderss" => ["address"], "afillpt" => ["pitfall"],
      "ceorstv" => ["vectors"], "befilry" => ["briefly"], "eeflnos" => ["oneself"],
      "egglooy" => ["geology"], "cehiknt" => ["kitchen"], "aacdlns" => ["scandal"],
      "cefnosu" => ["confuse"], "ceeorrv" => ["recover"], "aabbceg" => ["cabbage"],
      "aeirtvy" => ["variety"], "aenprtt" => ["pattern"], "beehrty" => ["thereby"],
      "abgilmn" => ["blaming"], "eeinrsv" => ["inverse"], "abdeilu" => ["audible"],
      "acefrsu" => ["surface"], "ghinntu" => ["hunting"],
      "adeerrs" => ["rereads", "readers"], "adgilnr" => ["darling"],
      "eimmpru" => ["premium"], "ddehnru" => ["hundred"], "eelopps" => ["peoples"],
      "defgiru" => ["figured"], "eirssuv" => ["viruses"], "dehopps" => ["shopped"],
      "achirtu" => ["haircut"], "aabeglr" => ["algebra"], "ceinosv" => ["novices"],
      "acdelrw" => ["crawled"], "giilnst" => ["listing"], "eillnss" => ["illness"],
      "emrsttu" => ["mutters"], "ccenopt" => ["concept"], "imnoort" => ["monitor"],
      "ceegllo" => ["college"], "adenost" => ["donates"],
      "ggiinns" => ["singing", "signing"], "cenottx" => ["context"],
      "bdemoor" => ["bedroom", "boredom"], "aelrstv" => ["travels"],
      "ekmnosy" => ["monkeys"], "ghinrtu" => ["hurting"], "gginorw" => ["growing"],
      "aceehrt" => ["teacher"], "cdoprtu" => ["product"], "cdenotu" => ["counted"],
      "eginrsv" => ["serving"], "aceehpr" => ["cheaper"], "inooprt" => ["portion"],
      "ciorsuu" => ["curious"], "deelnss" => ["endless"], "deirstv" => ["diverts"],
      "aaegmns" => ["manages"], "abiilty" => ["ability"], "beegill" => ["legible"],
      "accdekr" => ["cracked"], "acehlpy" => ["cheaply"], "abdhnsu" => ["husband"],
      "giknnow" => ["knowing"], "bdeorsw" => ["browsed"], "eegimnt" => ["meeting"],
      "adeimty" => ["daytime"], "acelssu" => ["clauses"], "beiilsv" => ["visible"],
      "ceenrsy" => ["scenery"], "aaemrtu" => ["amateur"], "ainnstt" => ["instant"],
      "eirrstw" => ["writers"], "acdeghn" => ["changed"], "eeilrst" => ["sterile"],
      "ginprss" => ["springs"], "eginrst" => ["resting"], "aeelnrt" => ["eternal"],
      "deeinsx" => ["indexes"], "cegnruy" => ["urgency"], "aghlsty" => ["ghastly"],
      "aegluvy" => ["vaguely"], "aeillrt" => ["literal"], "efllstu" => ["fullest"],
      "aacdenv" => ["advance"], "deenstx" => ["extends"], "abhiint" => ["inhabit"],
      "definrs" => ["friends"], "acelnrt" => ["central"], "deioprv" => ["provide"],
      "aadehms" => ["ashamed"], "deeersv" => ["deserve"],
      "deginns" => ["endings", "sending"], "acginor" => ["organic"],
      "cdisssu" => ["discuss"], "denoprs" => ["respond"], "deeenrt" => ["entered"],
      "egilnry" => ["relying"], "aillnst" => ["install"], "aanrrtw" => ["warrant"],
      "deginnp" => ["pending"], "bdegiot" => ["bigoted"], "cejoprt" => ["project"],
      "ccennor" => ["concern"], "eooppss" => ["opposes"], "acghipr" => ["graphic"],
      "adeortt" => ["rotated"], "deeinst" => ["destine"], "giiknns" => ["sinking"],
      "cehimst" => ["chemist"], "aiilrtv" => ["trivial"], "aehstux" => ["exhaust"],
      "deimott" => ["omitted"], "abeehrt" => ["breathe"], "deiilmt" => ["limited"],
      "elpsuzz" => ["puzzles"], "afhlmru" => ["harmful"], "abceint" => ["cabinet"],
      "ciklluy" => ["luckily"], "ghinosu" => ["housing"], "ceeirsv" => ["service"],
      "aagimnz" => ["amazing"], "adeelrx" => ["relaxed"], "cdehlot" => ["clothed"],
      "deirrst" => ["stirred"], "aelprsy" => ["players"], "aaabnns" => ["bananas"],
      "defilpp" => ["flipped"], "emsssty" => ["systems"], "accnotu" => ["account"],
      "beilrtu" => ["rebuilt"], "deeerst" => ["steered"], "deginor" => ["ignored"],
      "ddeeotv" => ["devoted"], "eeeqsuz" => ["squeeze"], "dennstu" => ["stunned"],
      "cdddeeu" => ["deduced"], "ceoprss" => ["corpses", "process"],
      "cdeiorv" => ["divorce"], "iinssst" => ["insists"], "abeisuv" => ["abusive"],
      "aefinrr" => ["refrain"], "aeeflrw" => ["welfare"], "abdegir" => ["brigade"],
      "acehpst" => ["patches"], "aginrst" => ["staring"], "aefhrst" => ["fathers"],
      "adenrsw" => ["wanders"], "afinors" => ["insofar"], "acellot" => ["collate"],
      "aiilnos" => ["liaison"], "cimmost" => ["commits"], "aginsty" => ["staying"],
      "cddeeis" => ["decides"], "aekmrst" => ["markets"], "aeghinr" => ["hearing"],
      "adeppsw" => ["swapped"], "bceemos" => ["becomes"], "eimrtux" => ["mixture"],
      "ddeeelt" => ["deleted"], "cdeiisu" => ["suicide"],
      "aceilmr" => ["miracle", "reclaim"], "eeimmns" => ["immense"],
      "cmmnoos" => ["commons"], "deeirrt" => ["retired"], "agimnno" => ["moaning"],
      "aeeisst" => ["easiest"], "eeilrsu" => ["leisure"], "accilss" => ["classic"],
      "abdeeln" => ["enabled"], "aalnrtu" => ["natural"], "eeegmrs" => ["emerges"],
      "demnotu" => ["mounted"], "agikmnr" => ["marking"], "ceilmop" => ["compile"],
      "acgiknp" => ["packing"], "acnoort" => ["cartoon"], "deipstu" => ["dispute"],
      "adeertt" => ["treated"], "eerrssv" => ["servers"], "celorsu" => ["closure"],
      "ccennot" => ["connect"], "abegint" => ["beating"],
      "eemprsu" => ["supreme", "presume"], "hioprsw" => ["worship"],
      "aeeimnx" => ["examine"], "acilntu" => ["lunatic"], "ceikqru" => ["quicker"],
      "bcdeilm" => ["climbed"], "aginpsu" => ["pausing"], "acdeitt" => ["dictate"],
      "ceinost" => ["notices", "section"], "efllosw" => ["fellows"],
      "abeehnt" => ["beneath"], "aaddegm" => ["damaged"], "aceinrt" => ["certain"],
      "acegins" => ["ceasing"], "bdirstu" => ["disturb"], "eimnstu" => ["minutes"],
      "bgiilno" => ["boiling"], "aadgimr" => ["diagram"], "aenopsw" => ["weapons"],
      "cginors" => ["scoring"], "mooppsu" => ["pompous"], "aceilmt" => ["climate"],
      "acelost" => ["locates"], "aggiinn" => ["gaining"], "ciilnos" => ["silicon"],
      "deeissv" => ["devises"], "adghins" => ["dashing"], "ddenorw" => ["drowned"],
      "eeinstx" => ["sixteen"], "aderstt" => ["started"], "accenst" => ["accents"],
      "aeipssv" => ["passive"], "bekloot" => ["booklet"], "cefinno" => ["confine"],
      "afmorst" => ["formats"], "aehprty" => ["therapy"], "adelrtt" => ["rattled"],
      "efghirt" => ["fighter"], "acemrss" => ["screams"], "adefltu" => ["default"],
      "aceghns" => ["changes"], "acddirs" => ["discard"], "acdehtt" => ["chatted"],
      "eehlssv" => ["shelves"], "acdrstu" => ["custard"], "clmnosu" => ["columns"],
      "acelrst" => ["scarlet"], "deflors" => ["folders"], "deopstt" => ["spotted"],
      "aelnrtu" => ["neutral"], "dddelmu" => ["muddled"], "cdeersu" => ["reduces"],
      "eemnoos" => ["someone"], "nnoopru" => ["pronoun"], "aailrrv" => ["arrival"],
      "clnostu" => ["consult"], "deersst" => ["deserts"], "ddenosu" => ["sounded"],
      "almorst" => ["mortals"], "aalmnsu" => ["manuals"], "aelmorv" => ["removal"],
      "ehinopx" => ["phoenix"], "aeikmst" => ["mistake"], "cdenoss" => ["seconds"],
      "elrsstu" => ["results"], "aceltxy" => ["exactly"], "adprsuw" => ["upwards"],
      "eeforrv" => ["forever"], "aeelmpx" => ["example"], "cehostu" => ["touches"],
      "eeprssx" => ["express"], "cenortu" => ["counter"], "aadhrsz" => ["hazards"],
      "aeeglnt" => ["elegant"], "aceelpr" => ["replace"], "aabceln" => ["balance"],
      "aeglrty" => ["greatly"], "cdeeisv" => ["devices"], "acdirst" => ["drastic"],
      "abeirrr" => ["barrier"], "dfgilno" => ["folding"], "ekorrsw" => ["workers"],
      "iorsttu" => ["tourist"], "agginru" => ["arguing"], "gikmnos" => ["smoking"],
      "cdeorss" => ["crossed"], "ceejrst" => ["rejects"], "efilrst" => ["filters"],
      "cehinps" => ["pinches"], "ghillty" => ["lightly"], "efgirsu" => ["figures"],
      "cddeesu" => ["deduces"], "aeflnru" => ["funeral"], "dersttu" => ["trusted"],
      "eiinprs" => ["inspire"], "aegortu" => ["outrage"], "deenrrs" => ["renders"],
      "eopprss" => ["oppress"], "lprssuu" => ["surplus"], "cdeinot" => ["noticed"],
      "aegimrt" => ["migrate"], "aadderw" => ["awarded"], "aoprrty" => ["portray"],
      "ahlprsy" => ["sharply"], "degioos" => ["goodies"], "eorrsst" => ["resorts"],
      "adgimnn" => ["damning"], "accmopt" => ["compact"], "acilmsu" => ["musical"],
      "adforrw" => ["forward"], "acdeilt" => ["dialect"], "bddgiin" => ["bidding"],
      "elnosss" => ["lessons"], "degilnu" => ["indulge"], "aabeggg" => ["baggage"],
      "adginrw" => ["drawing"], "ailrstu" => ["rituals"], "acellrs" => ["recalls"],
      "ginoprt" => ["porting"], "giiknrs" => ["risking"], "adefggl" => ["flagged"],
      "dgiinrv" => ["driving"], "eensttx" => ["extents"], "eoprsst" => ["posters"],
      "deeepst" => ["deepest"], "acerstt" => ["scatter"], "deeenrw" => ["renewed"],
      "aceprtu" => ["capture"], "aemrsst" => ["masters", "streams"],
      "ccenort" => ["concert"], "boorrsw" => ["borrows"], "chlooss" => ["schools"],
      "ainosux" => ["anxious"], "biillno" => ["billion"], "eeprsss" => ["presses"],
      "fgiilmn" => ["filming"], "addginp" => ["padding"], "ddeeorr" => ["ordered"],
      "emnorst" => ["monster"], "fimnoru" => ["uniform"], "ailrtuv" => ["virtual"],
      "aacfltu" => ["factual"], "aginnrt" => ["ranting"], "eeloprx" => ["explore"],
      "ceelnos" => ["enclose"], "eimnoot" => ["emotion"], "cefinst" => ["infects"],
      "adeegln" => ["gleaned"], "ddeefin" => ["defined"], "beglnos" => ["belongs"],
      "deoopps" => ["opposed"], "aersssu" => ["assures"], "deilors" => ["soldier"],
      "cenorss" => ["censors"], "cddeeno" => ["encoded"], "aamnoty" => ["anatomy"],
      "eoprstt" => ["protest"], "ahmnory" => ["harmony"], "deeimpt" => ["emptied"],
      "deeipst" => ["despite"], "abdlory" => ["broadly"], "aeglrst" => ["largest"],
      "abddeet" => ["debated"], "ceghino" => ["echoing"], "ceeflrt" => ["reflect"],
      "agimnrw" => ["warming"], "imnoost" => ["motions"], "eeenruv" => ["revenue"],
      "adelnnp" => ["planned"], "abeklnt" => ["blanket"], "acehrss" => ["crashes"],
      "acehlss" => ["clashes"], "cdehrsu" => ["crushed"], "abcgikn" => ["backing"],
      "gimnnor" => ["morning"], "ceikstt" => ["tickets"], "knnnouw" => ["unknown"],
      "deefnrs" => ["fenders"], "aacmrss" => ["sarcasm"], "cdekkno" => ["knocked"],
      "bcdeklo" => ["blocked"], "cenostt" => ["contest"], "cinosst" => ["consist"],
      "deimmsu" => ["mediums"], "iiorstv" => ["visitor"], "cciirtu" => ["circuit"],
      "eelsssu" => ["useless"], "aioprrt" => ["airport"], "deiintv" => ["invited"],
      "aceelnr" => ["cleaner"], "aceirrs" => ["carries"], "egnorsv" => ["governs"],
      "eimopss" => ["imposes"], "acdeehr" => ["reached"], "aeilnpx" => ["explain"],
      "bginnru" => ["burning"], "eflorsw" => ["flowers"], "eimoprs" => ["promise"],
      "abilmox" => ["mailbox"], "aejlosu" => ["jealous"], "gginnoo" => ["ongoing"],
      "bnosttu" => ["buttons"], "cnoortu" => ["contour"], "deeginn" => ["needing"],
      "eeprstx" => ["experts"], "eforsst" => ["forests"], "einnost" => ["tension"],
      "cginost" => ["costing"], "eiloptx" => ["exploit"], "acghins" => ["chasing"],
      "ginortu" => ["routing"], "ceirssu" => ["cruises"], "adempsw" => ["swamped"],
      "adgilnn" => ["landing"], "cmosstu" => ["customs"], "agiklnt" => ["talking"],
      "iimmmnu" => ["minimum"], "cfiilnt" => ["inflict"], "giinssu" => ["issuing"],
      "gggilno" => ["logging"], "ceeprst" => ["respect"], "ekmorss" => ["smokers"],
      "acdelss" => ["classed"], "cenortv" => ["convert"], "elrttuy" => ["utterly"],
      "aeorstt" => ["rotates"], "delostu" => ["loudest"], "cefnoss" => ["confess"],
      "aelprst" => ["plaster"], "ddefloo" => ["flooded"], "adeglpu" => ["plagued"],
      "cdeeesx" => ["exceeds"], "aeelrst" => ["relates"],
      "aghinps" => ["phasing", "shaping"], "deefmor" => ["freedom"],
      "cfmnoor" => ["conform"], "adeeflr" => ["federal"], "aehltwy" => ["wealthy"],
      "acginrs" => ["scaring"], "deimnrs" => ["reminds"], "cdddeeo" => ["decoded"],
      "bdeginn" => ["bending"], "enoprss" => ["persons"], "adeimrr" => ["married"],
      "beffrsu" => ["buffers"], "aablntt" => ["blatant"], "ginpttu" => ["putting"],
      "egiinvw" => ["viewing"], "acerrtt" => ["retract"], "gimnppu" => ["pumping"],
      "cefirty" => ["rectify"], "eeqrstu" => ["request"], "clnoort" => ["control"],
      "gillnpu" => ["pulling"], "eikrsst" => ["strikes"], "agiknpr" => ["parking"],
      "aeglotv" => ["voltage"], "agimnpp" => ["mapping"], "ghiinnt" => ["hinting"],
      "adeekns" => ["sneaked"], "belostt" => ["bottles"], "aadoprx" => ["paradox"],
      "addeggr" => ["dragged"], "deikpps" => ["skipped"], "ceeginr" => ["generic"],
      "aaegmnr" => ["manager"], "dinosww" => ["windows"], "deorsty" => ["destroy"],
      "cdeefst" => ["defects"], "bimsstu" => ["submits"],
      "eginrss" => ["resigns", "singers"], "ceknors" => ["reckons"],
      "addeegr" => ["degrade"], "ceenprt" => ["percent"], "aainrtv" => ["variant"],
      "aeeflms" => ["females"], "aenprrt" => ["partner"], "adeegll" => ["alleged"],
      "aeeggns" => ["engages"], "addeisv" => ["advised"], "ddeenps" => ["depends"],
      "eorrstu" => ["trouser"], "eenrssu" => ["ensures"],
      "aelrstt" => ["rattles", "startle"], "ailmnno" => ["nominal"],
      "eopssss" => ["possess"], "aeegrrt" => ["greater"], "bemnstu" => ["numbest"],
      "ginnrtu" => ["turning"], "deefgin" => ["feeding"], "deejnoy" => ["enjoyed"],
      "efgiorv" => ["forgive"], "eeilntt" => ["entitle"], "acfinrt" => ["frantic"],
      "giinors" => ["origins"], "ddgiinr" => ["ridding"], "airsstt" => ["artists"],
      "deeilrv" => ["deliver"], "ciiosuv" => ["vicious"], "filrsty" => ["firstly"],
      "aabcelp" => ["capable"], "aemnrsu" => ["surname"], "ddefnou" => ["founded"],
      "gilorty" => ["trilogy"], "cfmoort" => ["comfort"], "ikmoost" => ["mistook"],
      "adeinsv" => ["invades"], "giimnss" => ["missing"], "enorsuv" => ["nervous"],
      "agiinrs" => ["arising", "raising"], "aiilmmn" => ["minimal"],
      "aaccnvy" => ["vacancy"], "cfimnor" => ["confirm"], "aeqrrtu" => ["quarter"],
      "acennrs" => ["scanner"], "aalnsty" => ["analyst"], "ghiknoo" => ["hooking"],
      "abccoot" => ["tobacco"], "hlmnoty" => ["monthly"], "deiknov" => ["invoked"],
      "agimnsu" => ["amusing"], "acehlnn" => ["channel"], "mopprst" => ["prompts"],
      "cehirst" => ["richest"], "fgiintt" => ["fitting"], "eegrstu" => ["gesture"],
      "cennost" => ["consent"], "eegmnst" => ["segment"], "eiillrs" => ["sillier"],
      "cdeirsu" => ["cruised"], "eeeilrv" => ["relieve"], "ciimstv" => ["victims"],
      "giinrtw" => ["writing"], "aellmrs" => ["smaller"], "deeffor" => ["offered"],
      "acfltuy" => ["faculty"], "celrtuy" => ["cruelty"], "giilmns" => ["smiling"],
      "deeipss" => ["despise"], "dehlors" => ["holders"], "egimnrt" => ["terming"],
      "efhrrtu" => ["further"], "aeegmss" => ["message"], "ginopru" => ["pouring"],
      "aehhlty" => ["healthy"], "eeelmnt" => ["element"], "aeglrru" => ["regular"],
      "acdehpt" => ["patched"], "bcceily" => ["bicycle"], "aeehrsw" => ["whereas"],
      "bdgiinn" => ["binding"], "dgiinty" => ["dignity", "tidying"],
      "hrssttu" => ["thrusts"], "eeffint" => ["fifteen"], "eginquu" => ["queuing"],
      "acerttx" => ["extract"], "abeillr" => ["liberal"], "aabeggr" => ["garbage"],
      "aginssv" => ["savings"], "aceehnn" => ["enhance"], "deeelns" => ["needles"],
      "acellny" => ["cleanly"], "acehmst" => ["matches"], "deinsty" => ["density"],
      "aeefrwy" => ["freeway"], "aacflly" => ["fallacy"], "adllors" => ["dollars"],
      "aghilnt" => ["halting"], "aailpst" => ["spatial"], "celosst" => ["closest"],
      "agiilmn" => ["mailing"], "cceikrt" => ["cricket"], "abbdegr" => ["grabbed"],
      "cgilnos" => ["closing"], "ccdehku" => ["chucked"], "abginrr" => ["barring"],
      "eggimnr" => ["merging"], "innoost" => ["notions"], "elorstv" => ["revolts"],
      "adeinpt" => ["painted"], "aeelrsv" => ["reveals", "several"],
      "acdeert" => ["catered", "reacted", "created"], "agilnpy" => ["playing"],
      "adeiprs" => ["despair"], "aaegtwy" => ["gateway"], "aaeilss" => ["aliases"],
      "acdeeht" => ["cheated"], "afostuu" => ["fatuous"], "eeinnps" => ["pennies"],
      "einrsst" => ["inserts"], "flloosw" => ["follows"], "eeirssv" => ["revises"],
      "abeelns" => ["enables"], "cdehinp" => ["pinched"], "acdginn" => ["dancing"],
      "cemoops" => ["compose"], "afklnry" => ["frankly"], "aiimprs" => ["impairs"],
      "ghloruy" => ["roughly"], "effrssu" => ["suffers"], "deeoprw" => ["powered"],
      "adehnrs" => ["hardens"], "aabdnno" => ["abandon"], "ghiinst" => ["insight"],
      "efnortu" => ["fortune"], "coprrtu" => ["corrupt"], "eiimnrt" => ["interim"],
      "bellstu" => ["bullets"], "aeelssw" => ["weasels"], "dgikmno" => ["kingdom"],
      "dgiilns" => ["sliding"], "eeiprvw" => ["preview"], "aceelrr" => ["clearer"],
      "deinprt" => ["printed"], "adeilpp" => ["applied"], "bhiiint" => ["inhibit"],
      "acilpty" => ["typical"], "demrrsu" => ["murders"], "eggsstu" => ["suggest"],
      "imoprst" => ["imports"], "dehipps" => ["shipped"], "bdelosu" => ["doubles"],
      "aghinsw" => ["washing"], "ddeeisv" => ["devised"], "begglos" => ["boggles"],
      "cdelopu" => ["coupled"], "aceepss" => ["escapes"], "deeopsx" => ["exposed"],
      "aceirrr" => ["carrier"], "aceilrt" => ["article"], "agiklnw" => ["walking"],
      "ceirrtu" => ["recruit"], "cdeeepr" => ["precede"],
      "aeinrst" => ["nastier", "retains"], "iillmno" => ["million"],
      "aegikln" => ["linkage"], "bdinstu" => ["dustbin"], "bdegooy" => ["goodbye"],
      "egilnss" => ["singles"], "aaelpps" => ["appeals"],
      "cdeirst" => ["credits", "directs"], "cehooss" => ["chooses"],
      "aeeegnt" => ["teenage"], "adeilms" => ["mislead"], "aadelry" => ["already"],
      "eeerrsv" => ["reserve", "reverse"], "eenrstw" => ["western"],
      "ehnorst" => ["shorten"], "ceeinrs" => ["sincere"], "dgiinnw" => ["winding"],
      "cemnosu" => ["consume"], "acinost" => ["actions"], "aegilnn" => ["leaning"],
      "cfiinot" => ["fiction"], "giijnno" => ["joining"], "aeehirv" => ["heavier"],
      "acmnory" => ["acronym"], "adempst" => ["stamped"], "aadegmn" => ["managed"],
      "adehrst" => ["hardest"], "aceflru" => ["careful"], "deginnr" => ["rending"],
      "cgimmnu" => ["cumming"], "eimprss" => ["impress"], "cllorss" => ["scrolls"],
      "aeprrsy" => ["prayers"], "adegrty" => ["tragedy"], "fhiloos" => ["foolish"],
      "dehiosu" => ["hideous"], "fgiilnt" => ["lifting"], "aegllry" => ["largely"],
      "adeilst" => ["details"], "cginopy" => ["copying"], "aefhrrt" => ["farther"],
      "aceehst" => ["teaches"], "aabginr" => ["bargain"], "behorst" => ["bothers"],
      "dgggiin" => ["digging"], "bdeelov" => ["beloved"], "ailmopt" => ["optimal"],
      "einorsv" => ["version"], "adeglmn" => ["mangled"], "ghinpsu" => ["pushing"],
      "aeglsss" => ["glasses"], "aimprry" => ["primary"], "aeepprr" => ["prepare"],
      "eghinrr" => ["herring"], "accepst" => ["accepts"], "eooprst" => ["poorest"],
      "adelnpt" => ["planted"], "aenprst" => ["parents"], "aelrswy" => ["lawyers"],
      "celmops" => ["compels"], "denpssu" => ["suspend"], "ccdeeno" => ["concede"],
      "abilrry" => ["library"], "opsttuu" => ["outputs"], "aeehlrt" => ["leather"],
      "aeelmtu" => ["emulate"], "dddeiiv" => ["divided"], "eefgiln" => ["feeling"],
      "deisstu" => ["studies"], "cehnpsu" => ["punches"],
      "deeprss" => ["depress", "pressed"], "aacdilr" => ["radical"],
      "addenss" => ["saddens"], "abeginr" => ["bearing"], "deiopss" => ["dispose"],
      "aeginrs" => ["erasing"], "deeoruv" => ["overdue"], "deginss" => ["designs"],
      "deinopt" => ["pointed"], "aacchir" => ["archaic"], "ademssu" => ["assumed"],
      "denorsw" => ["wonders"], "addeinr" => ["drained"], "aaenpst" => ["peasant"],
      "acmnopy" => ["company"], "allmory" => ["morally"], "cdeekrw" => ["wrecked"],
      "aegilll" => ["illegal"], "abeimnt" => ["ambient"], "elnotvy" => ["novelty"],
      "afhinos" => ["fashion"], "aehimst" => ["atheism"], "acdmmno" => ["command"],
      "deimnps" => ["impends"], "ainrstt" => ["transit"], "eeilprs" => ["replies"],
      "beehrwy" => ["whereby"], "beeeilv" => ["believe"], "aeinqtu" => ["antique"],
      "aepprrw" => ["wrapper"], "eeijlls" => ["jellies"], "deeostv" => ["devotes"],
      "deiorrw" => ["worried"], "inoopss" => ["poisons"], "adorstw" => ["towards"],
      "fgimnor" => ["forming"], "aeglpsu" => ["plagues"], "densttu" => ["student"],
      "cddeorw" => ["crowded"], "deilpps" => ["slipped"], "acghikn" => ["hacking"],
      "einortu" => ["routine"], "einorst" => ["orients"], "cilprtu" => ["culprit"],
      "aceerst" => ["creates"], "efinnru" => ["funnier"], "cdemnno" => ["condemn"],
      "eenprtv" => ["prevent"], "eiprsst" => ["persist", "priests"],
      "cgikmnu" => ["mucking"], "aghinsu" => ["anguish"], "ammrsuy" => ["summary"],
      "eemorsv" => ["removes"], "einnstv" => ["invents"], "aaeegrv" => ["average"],
      "abgiknr" => ["barking"], "eiorssu" => ["serious"], "aefirst" => ["fairest"],
      "eeinrst" => ["entries"], "eoprrst" => ["porters", "reports"],
      "aacemrs" => ["cameras"], "acdertt" => ["detract"], "ailmmor" => ["immoral"],
      "acgilnp" => ["placing"], "eeirsvw" => ["reviews"], "aelnstt" => ["talents"],
      "aeginrt" => ["tearing"], "deelopv" => ["develop"], "agijmmn" => ["jamming"],
      "ellorty" => ["trolley"], "aacrttt" => ["attract"], "eprssuu" => ["pursues"],
      "achlors" => ["scholar"], "blmossy" => ["symbols"], "acgilln" => ["calling"],
      "adenpsx" => ["expands"], "aeenrst" => ["eastern", "nearest"],
      "aimmmux" => ["maximum"], "eehistv" => ["thieves"], "einrttw" => ["written"],
      "deenrsu" => ["ensured"], "achirty" => ["charity"], "deginny" => ["denying"],
      "glnorwy" => ["wrongly"], "egiintx" => ["exiting"], "aehmsss" => ["smashes"],
      "eilnotu" => ["outline"], "cciprty" => ["cryptic"], "acepsst" => ["aspects"],
      "cceilrs" => ["circles"], "adeemnr" => ["renamed"], "ddeeirv" => ["derived"],
      "ceersst" => ["secrets"], "fgilnow" => ["flowing"], "ghhortu" => ["through"],
      "dekorwy" => ["keyword"], "eeimpst" => ["empties"], "aceehrs" => ["reaches"],
      "aeimrtw" => ["wartime"], "aceilps" => ["special"], "einrstv" => ["inverts"],
      "adeehrs" => ["adheres", "headers"], "deffirs" => ["differs"],
      "aisssst" => ["assists"], "eiilstt" => ["elitist"], "dggiinu" => ["guiding"],
      "ccinotv" => ["convict"], "cellosy" => ["closely"], "eeginns" => ["engines"],
      "acdeghr" => ["charged"], "kloootu" => ["outlook"], "aacilpt" => ["capital"],
      "celmssu" => ["muscles"], "ceffior" => ["officer"], "bcejstu" => ["subject"],
      "efhllpu" => ["helpful"], "cdddeei" => ["decided"], "diimsss" => ["dismiss"],
      "deeilpr" => ["replied"], "acdehmr" => ["charmed"], "addehln" => ["handled"],
      "aellquy" => ["equally"], "cdeopru" => ["produce"], "aehnpps" => ["happens"],
      "aehistt" => ["atheist"], "celrtuu" => ["culture"], "accessu" => ["accuses"],
      "efforst" => ["efforts"], "eggirrt" => ["trigger"], "cklnuuy" => ["unlucky"],
      "cdeirtv" => ["verdict"], "acdenss" => ["ascends"], "acchiot" => ["chaotic"],
      "ceehmss" => ["schemes"], "degimnn" => ["mending"], "aeimrrs" => ["marries"],
      "bhilpsu" => ["publish"], "ceorssu" => ["courses", "sources"],
      "eehnorw" => ["nowhere"], "eelorsv" => ["resolve"], "adeilly" => ["ideally"],
      "cgiinno" => ["coining"], "abilort" => ["orbital"], "aegiimn" => ["imagine"],
      "bdeilru" => ["rebuild"], "aalmnoy" => ["anomaly"], "ciklquy" => ["quickly"],
      "abeirrz" => ["bizarre"], "abcgklo" => ["backlog"], "aenpstu" => ["peanuts"],
      "ahorstu" => ["authors"], "efhlopu" => ["hopeful"], "cdehnpu" => ["punched"],
      "adddeer" => ["dreaded"], "deinnst" => ["intends"], "eepstty" => ["typeset"],
      "ceemopt" => ["compete"], "aginpry" => ["praying"], "agghinn" => ["hanging"],
      "ceorsss" => ["crosses"], "ceeiprt" => ["receipt"], "aeimssv" => ["massive"],
      "dghilno" => ["holding"], "aeflrsu" => ["refusal"], "abinost" => ["obtains"],
      "agiinnr" => ["raining"], "deinstt" => ["dentist"], "bbhirsu" => ["rubbish"],
      "ghiinsw" => ["wishing"], "adeilmm" => ["dilemma"], "cekosst" => ["sockets"],
      "adeissv" => ["advises"], "fioprst" => ["profits"], "deemptt" => ["tempted"],
      "efmorrs" => ["reforms"], "eiilmps" => ["implies"], "aaegpss" => ["passage"],
      "dehostu" => ["shouted"], "ciortvy" => ["victory"], "cehrstt" => ["stretch"],
      "acdeklt" => ["tackled"], "acginrt" => ["tracing"], "aeekprs" => ["speaker"],
      "cgiiknp" => ["picking"], "elosstw" => ["slowest"], "defhlsu" => ["flushed"],
      "aailmns" => ["animals"], "bbgimno" => ["bombing"], "acehimn" => ["machine"],
      "iilttuy" => ["utility"], "ceelsst" => ["selects"], "ddefils" => ["fiddles"],
      "deeegrs" => ["degrees"], "ehopprt" => ["prophet"], "acgikln" => ["lacking"],
      "ginoqtu" => ["quoting"], "belmstu" => ["stumble"], "ejnoruy" => ["journey"],
      "cceehkr" => ["checker"], "deiklls" => ["skilled"], "giinppr" => ["ripping"],
      "aceinnt" => ["ancient"], "eghilrt" => ["lighter"], "bdiosuu" => ["dubious"],
      "adeirrv" => ["arrived"], "aacinpt" => ["captain"], "bghortu" => ["brought"],
      "eersstt" => ["streets"], "aillnpy" => ["plainly"], "ginnnru" => ["running"],
      "eilmprs" => ["simpler"], "immoptu" => ["optimum"], "iinnoop" => ["opinion"],
      "acginsu" => ["causing"], "abcgiln" => ["cabling"], "mnnosyy" => ["synonym"],
      "cddeeos" => ["decodes"], "ceoprtt" => ["protect"], "abdeort" => ["aborted"],
      "aghhiwy" => ["highway"], "deginnv" => ["vending"], "celrstu" => ["cluster"],
      "aginpss" => ["passing"], "eeirrst" => ["retires"], "himprtu" => ["triumph"],
      "ghiintt" => ["hitting"], "aackstt" => ["attacks"], "deiorst" => ["editors"],
      "cciirst" => ["critics"], "aceorrt" => ["creator", "reactor"],
      "cceorrt" => ["correct"], "accnott" => ["contact"], "eiinstv" => ["invites"],
      "acilrty" => ["clarity"], "aenorss" => ["reasons"], "deenprt" => ["pretend"],
      "acilopt" => ["optical", "topical"], "eegimns" => ["seeming"],
      "cemmnot" => ["comment"], "ceehilv" => ["vehicle"], "aagmmrr" => ["grammar"],
      "eeegnrv" => ["revenge"]}
    |> Map.get(string_id)
  end

  def valid_ids do
    ["ceiprtu", "deellry", "aelnpty", "abeoqru", "bgiknoo", "ddeeirs", "aegintv",
     "afgiiln", "aflluwy", "deemorv", "ciprsst", "cgiiknn", "abeehsv", "adepstu",
     "adeelrt", "adegiln", "aaenruw", "einnrsw", "ginoprv", "giillnw", "cceeins",
     "ghinnop", "hlorsty", "aegorst", "cgiknoo", "dggijnu", "aeeelrs", "dgisstu",
     "adeefst", "mmopsty", "deloptt", "cdeenos", "aeiprtv", "ddeeinx", "elmosuv",
     "ehilost", "eiorrsw", "cdeilpp", "accelno", "adilpry", "aeginnr", "acekpst",
     "eghilnp", "ddeippr", "cemootu", "eeefrsz", "enrrstu", "ahilppy", "aginprs",
     "adenpst", "eegikns", "deeirss", "eorrttu", "dginnou", "adegpru", "addeopt",
     "celnoos", "eiorsst", "dfgiinn", "deioprs", "aefgilr", "ainopss", "defhist",
     "cemnooy", "abborss", "aeilrty", "aceefpr", "ginoppp", "adiilnv", "eefinrs",
     "degilnn", "ailqtuy", "aeinptt", "aademnt", "abginsu", "cddeens", "eginnop",
     "eoopprs", "eiknosv", "eelrstt", "aaginst", "acejkst", "cgiklno", "cdennoo",
     "adeimrs", "ceiosty", "ceegint", "ainrsst", "acdeeln", "aefginr", "beeentw",
     "eknortw", "aailmrt", "aiorsuv", "egimnss", "eefginr", "ceefnor", "adjsstu",
     "deiilmp", "afilquy", "agiilns", "abddenr", "achmost", "imorrrs", "addeemn",
     "deelorw", "addegru", "gilnosw", "eggintt", "gillnor", "adikmnn", "hiottuw",
     "einrssu", "adilpsy", "aeeglnr", "deffnos", "adeersv", "ddgiikn", "acffirt",
     "ginrsst", "cdeeorv", "deeeknw", "adenpps", "giinnnw", "deeiops", "acgiknt",
     "cgiikkn", "efhilss", "adehknt", "eeirrtw", "giinstu", "diprstu", "ccesssu",
     "eeiqrru", "aerrstt", "behorrt", "aeilnst", "aelttux", "eegsssu", "eehhrtw",
     "afissty", "deisttw", "aadglru", "adeflot", "cdeeitx", "adegnrt", "deelstt",
     "abddeer", "dginorw", "acforty", "ccehios", "ceglooy", "cehlost", "giiklnn",
     "bginruy", "ceeetux", "aemrstt", "adenstt", "aeehrtw", "ceiintz", "ceelrtu",
     "aderssu", "ademnss", "cdehkos", "bddelou", "aeiprrs", "aflmoru", "acorrst",
     "eopprsu", "eilorrs", "adeirsv", "accehns", "deeegmr", "cgilnoo", "deegimn",
     "egilntt", "abssuwy", "addeely", "ceinsst", "addenot", "allsuuy", "defiinu",
     "fgilnoo", "agmoprr", "aginrvy", "aegilnv", "ceikoos", "aaagmnr", "eefhrrs",
     "ablnoty", "einoprt", "adeeiss", "ghhottu", "eeginnu", "adeinst", "ccilsty",
     "belortu", "eeginrt", "eilostt", "addefrt", "emmssuu", "eghhist", "aehnort",
     "deefrsu", "aabdrst", "beefils", "deiinot", "adefhls", "erssuvy", "aelmnru",
     "dgiimnn", "eloprtt", "cgiilns", "ginorst", "ceefprt", "acddees", "agirtvy",
     "ehmorst", "elmopsy", "glnoopr", "acinnot", "dginott", "cginttu", "abceesu",
     "accdors", "giklnoo", "aamnprt", "emprttu", "aeisttu", "accistt", "eeginnv",
     "efgorst", "giinnru", "iinrtty", "cdeeopr", "acdempr", "aeggglu", "ddeefns",
     "allotty", "agloopy", "aegnntt", "cdehotu", "aeelrsx", "ainostt", "efilopr",
     "ceiilnn", "adehlnr", "bdegirs", "ddginpu", "behiitx", "aailrwy", "ccehikn",
     "degopru", "abginnn", "ceijstu", "fgiilln", "cginnnu", "eeemrtx", "adiknps",
     "belmopr", "acforst", "bbeilqu", "efhilms", "gilnosv", "eimnnot", "inoopst",
     "ceilnst", "abelnot", "ceiorru", "adehlns", "eimprst", "abeffls", "ccgilny",
     "aeinstv", "cenrrtu", "efginrs", "aegnrst", "gijmnpu", "bemnrsu", "delmosu",
     "emrstyy", "cennott", "eeimnnt", "ahllosw", "deersss", "aehilvy", "iimnoss",
     "egnoruy", "giklnru", "acginst", "aginstt", "aeglmns", "ceelmow", "acdimny",
     "abcekrt", "deginnt", "beggist", "eeopssx", "chipssy", "adeprss", "adhiloy",
     "aiilmrs", "adeilrt", "deghilt", "degglpu", "aclrsty", "beilrty", "ajlnoru",
     "aehpprs", "aeilprv", "cegnost", "eeimprs", "acdehmt", "eilnovv", "eeenpsx",
     "bceorsu", "adehprs", "aegopst", "deegssu", "ccilnou", "adeginr", "adeekwy",
     "ceeenss", "ilnsstu", "ggiinnr", "adgiilt", "cgiinpr", "addemns", "hiorsty",
     "cfginor", "ccdnotu", "aegllly", "abdnoyy", "cdeiprt", "aefgorv", "acdehrs",
     "deefins", "deimops", "accdesu", "ggilnow", "ijlnoty", "dekopst", "cehrssu",
     "acgillo", "agimnrs", "cceinos", "bgggino", "ddelmsu", "acinotu", "aablmsy",
     "ceessux", "ehnosty", "ddeiisv", "aceiqru", "aadkrww", "acgikns", "aeirrsv",
     "ceiknss", "abdeglr", "aeilotv", "agiilnn", "acehrrt", "ainnost", "eoppssu",
     "acfilry", "ginopst", "adennoy", "aeghrst", "eeiprsx", "acelnru", "ainoppt",
     "eeeimns", "einosss", "cdeelux", "begilos", "dfginnu", "accilru", "eglnost",
     "cdeorrs", "acdenns", "agiintw", "ceekrrw", "glorssy", "aghntuy", "fimnors",
     "aeiprst", "efhlssu", "adehmss", "eemrssu", "abdeffl", "ekooprv", "cemrruy",
     "eilqtuy", "afilnpu", "bgiorty", "aafnsty", "ehmoosw", "abgiins", "ccdeesu",
     "adffhno", "acehstw", "aeginrw", "beorssw", "deeintv", "deknnru", "ailorst",
     "dgimnoo", "acilpst", "ceeffst", "cenrtuy", "deiostu", "cepsstu", "deeistx",
     "addeptu", "eginors", "iiprsst", "acelrsu", "aginnrw", "acehkrs", "ghinnot",
     "adeqrsu", "cdehopp", "acllloy", "abceens", "degnoru", "beginoy", "eilmpsu",
     "achlloo", "aeemnrs", "gimmnsu", "iprstuu", "ceffisu", "agilnst", "deelovv",
     "deeppst", "ghinott", "abcehmr", "eilnotv", "enoosst", "eefprrs", "dehmost",
     "eeiqrtu", "aacegkp", "addeiov", "ceeipss", "ddenoru", "ddeoppr", "adginrt",
     "deoppst", "abeglrs", "effosst", "afgilnw", "aeilpps", "aefmrrs", "eghlnst",
     "eelsstt", "adellow", "acchrst", "aemsssu", "eefhort", "begintt", "deenost",
     "aacgilm", "aehippr", "deiistv", "adeegnr", "bdillny", "delpuzz", "eelosvv",
     "aachnry", "aelnpst", "deemrsu", "adelmps", "acddist", "abinorw", "deeelst",
     "deeiprv", "abdefor", "aegrstt", "ceenrss", "cdiiiot", "eefrssu", "aehprss",
     "aenrssw", "egorsss", "cdeestt", "aeeoprt", "aefilru", "beggrsu", "aaffirs",
     "giinstt", "einsstw", "diorstt", "eirstuv", "aceffst", "abdelst", "addeehr",
     "eehorvw", "aeimnrs", "adgilno", "aegimnn", "bgilooy", "acdeirr", "ceeglnt",
     "aeilost", "efiinsu", "eoprtvy", "ceeeirv", "adeghin", "eijnrsu", "bdeeiss",
     "acegoru", "acefinn", "hinoorz", "deffstu", "aeeglls", "aginprw", "eeilnnt",
     "einprrt", "aceehiv", "elloosy", "agginnr", "abdeils", "accilny", "aehrstt",
     "adeghlu", "aceerrs", "abghins", "ainsstu", "giknorw", "deipstt", "eghlnty",
     "adepprw", "amnqtuu", "abbirst", "eefhlrs", "aefsstt", "cenorrs", "aloppru",
     "celopsu", "adepprt", "aerssst", "achmnor", "bbcelor", "ceeistx", "aeegilm",
     "eimoprv", "ehorrst", "acemnor", "bdegilo", "eginttw", "bioosuv", "ehorssw",
     "cekopst", "aceklst", "cdeinsu", "aorssst", "aiiilnt", "aaegnrr", "adinstt",
     "cnortuy", "beefint", "bgilnow", "eenrtuv", "egrrsuy", "cdeeelt", "acdekrt",
     "cdeeiln", "abdeest", "giiklln", "deprsuu", "beelsss", "acehilt", "ceepstx",
     "ceeilns", "amnostu", "giinntu", "aadegms", "aeelpss", "acinrtu", "aeqrssu",
     "adghinn", "aerrsst", "bceimno", "aekmrrs", "defnorw", "aegilns", "cddeeru",
     "acfisst", "eehmort", "cdeersw", "deefinr", "aaglnoy", "aghinrs", "dddefil",
     "addeinv", "agilnss", "deiikls", "aginsss", "abertty", "eilnsst", "aeopprv",
     "ghilrty", "bdeelss", "deiopst", "acdeilm", "cceelry", "cdeilnu", "cdoorst",
     "aeefllt", "cegiiln", "ceimnru", "aelmpss", "cemoptu", "efmoprr", "acehirv",
     "aailprt", "aeghint", "acgilns", "aefhlss", "eginnpu", "opprstu", "emmnost",
     "ghiinns", "ddeistu", "eehlrst", "fghiins", "eeorrst", "eiilmss", "alnsuuu",
     "ccellot", "acdelot", "acellry", "eegiknp", "dgimnpu", "deeiprx", "acemopr",
     "aghikns", "aemnpty", "fhiorry", "egillnt", "efginor", "deelopx", "aginntw",
     "ceeiprs", "ddeginw", "emooprt", "ehilstw", "aeeilrr", "acelsss", "aginstw",
     "abdeehv", "egillns", "efirrty", "ghinrsu", "eeiqrsu", "celnosu", "aeloprv",
     "accelns", "deeirsv", "beeorsv", "deiosuv", "bciistu", "ghiltty", "eiisstx",
     "aaepprs", "adeilry", "eginstt", "acdeetu", "eenprst", "aaddept", "acdeeps",
     "abhilos", "adeelrs", "agilnuv", "aeefrtu", "adilnss", "acdehtw", "fijstuy",
     "aderstv", "eehinrt", "adegrrs", "afillny", "eehnstv", "aalsstu", "aciprvy",
     "ademnnu", "aadeitw", "afgilln", "ceffios", "deghist", "eeinnst", "eegrrst",
     "aeemrsu", "cefipsy", "ddeerss", "adfhlnu", "adeeggn", "aeeglry", "aefinrt",
     "acginps", "accehst", "degiint", "celmopx", "aeeprst", "ehiinrt", "acdeelr",
     "adegnrs", "deijnru", "ceinpst", "aceghrs", "dnnosuu", "aempttt", "cklnosu",
     "aeiinrt", "aderrst", "agimnnn", "ghiprtu", "aadelmr", "cddeinu", "ccdeehk",
     "aersstv", "eginnst", "allosww", "aaknors", "adeelps", "aegginr", "eirsuvv",
     "ahnppuy", "aenrstv", "abeilns", "bceenos", "acehprt", "ceghinw", "aeehnsv",
     "aderrsw", "cdennot", "ghinosw", "aeggrst", "bcejost", "beemmrs", "aellorv",
     "deirrsv", "eimostv", "nooprss", "eeorrtw", "aegillv", "dgnorsu", "bdfiors",
     "elnnstu", "ahorstt", "adeinrt", "adderss", "afillpt", "ceorstv", "befilry",
     "eeflnos", "egglooy", "cehiknt", "aacdlns", "cefnosu", "ceeorrv", "aabbceg",
     "aeirtvy", "aenprtt", "beehrty", "abgilmn", "eeinrsv", "abdeilu", "acefrsu",
     "ghinntu", "adeerrs", "adgilnr", "eimmpru", "ddehnru", "eelopps", "defgiru",
     "eirssuv", "dehopps", "achirtu", "aabeglr", "ceinosv", "acdelrw", "giilnst",
     "eillnss", "emrsttu", "ccenopt", "imnoort", "ceegllo", "adenost", "ggiinns",
     "cenottx", "bdemoor", "aelrstv", "ekmnosy", "ghinrtu", "gginorw", "aceehrt",
     "cdoprtu", "cdenotu", "eginrsv", "aceehpr", "inooprt", "ciorsuu", "deelnss",
     "deirstv", "aaegmns", "abiilty", "beegill", "accdekr", "acehlpy", "abdhnsu",
     "giknnow", "bdeorsw", "eegimnt", "adeimty", "acelssu", "beiilsv", "ceenrsy",
     "aaemrtu", "ainnstt", "eirrstw", "acdeghn", "eeilrst", "ginprss", "eginrst",
     "aeelnrt", "deeinsx", "cegnruy", "aghlsty", "aegluvy", "aeillrt", "efllstu",
     "aacdenv", "deenstx", "abhiint", "definrs", "acelnrt", "deioprv", "aadehms",
     "deeersv", "deginns", "acginor", "cdisssu", "denoprs", "deeenrt", "egilnry",
     "aillnst", "aanrrtw", "deginnp", "bdegiot", "cejoprt", "ccennor", "eooppss",
     "acghipr", "adeortt", "deeinst", "giiknns", "cehimst", "aiilrtv", "aehstux",
     "deimott", "abeehrt", "deiilmt", "elpsuzz", "afhlmru", "abceint", "ciklluy",
     "ghinosu", "ceeirsv", "aagimnz", "adeelrx", "cdehlot", "deirrst", "aelprsy",
     "aaabnns", "defilpp", "emsssty", "accnotu", "beilrtu", "deeerst", "deginor",
     "ddeeotv", "eeeqsuz", "dennstu", "cdddeeu", "ceoprss", "cdeiorv", "iinssst",
     "abeisuv", "aefinrr", "aeeflrw", "abdegir", "acehpst", "aginrst", "aefhrst",
     "adenrsw", "afinors", "acellot", "aiilnos", "cimmost", "aginsty", "cddeeis",
     "aekmrst", "aeghinr", "adeppsw", "bceemos", "eimrtux", "ddeeelt", "cdeiisu",
     "aceilmr", "eeimmns", "cmmnoos", "deeirrt", "agimnno", "aeeisst", "eeilrsu",
     "accilss", "abdeeln", "aalnrtu", "eeegmrs", "demnotu", "agikmnr", "ceilmop",
     "acgiknp", "acnoort", "deipstu", "adeertt", "eerrssv", "celorsu", "ccennot",
     "abegint", "eemprsu", "hioprsw", "aeeimnx", "acilntu", "ceikqru", "bcdeilm",
     "aginpsu", "acdeitt", "ceinost", "efllosw", "abeehnt", "aaddegm", "aceinrt",
     "acegins", "bdirstu", "eimnstu", "bgiilno", "aadgimr", "aenopsw", "cginors",
     "mooppsu", "aceilmt", "acelost", "aggiinn", "ciilnos", "deeissv", "adghins",
     "ddenorw", "eeinstx", "aderstt", "accenst", "aeipssv", "bekloot", "cefinno",
     "afmorst", "aehprty", "adelrtt", "efghirt", "acemrss", "adefltu", "aceghns",
     "acddirs", "acdehtt", "eehlssv", "acdrstu", "clmnosu", "acelrst", "deflors",
     "deopstt", "aelnrtu", "dddelmu", "cdeersu", "eemnoos", "nnoopru", "aailrrv",
     "clnostu", "deersst", "ddenosu", "almorst", "aalmnsu", "aelmorv", "ehinopx",
     "aeikmst", "cdenoss", "elrsstu", "aceltxy", "adprsuw", "eeforrv", "aeelmpx",
     "cehostu", "eeprssx", "cenortu", "aadhrsz", "aeeglnt", "aceelpr", "aabceln",
     "aeglrty", "cdeeisv", "acdirst", "abeirrr", "dfgilno", "ekorrsw", "iorsttu",
     "agginru", "gikmnos", "cdeorss", "ceejrst", "efilrst", "cehinps", "ghillty",
     "efgirsu", "cddeesu", "aeflnru", "dersttu", "eiinprs", "aegortu", "deenrrs",
     "eopprss", "lprssuu", "cdeinot", "aegimrt", "aadderw", "aoprrty", "ahlprsy",
     "degioos", "eorrsst", "adgimnn", "accmopt", "acilmsu", "adforrw", "acdeilt",
     "bddgiin", "elnosss", "degilnu", "aabeggg", "adginrw", "ailrstu", "acellrs",
     "ginoprt", "giiknrs", "adefggl", "dgiinrv", "eensttx", "eoprsst", "deeepst",
     "acerstt", "deeenrw", "aceprtu", "aemrsst", "ccenort", "boorrsw", "chlooss",
     "ainosux", "biillno", "eeprsss", "fgiilmn", "addginp", "ddeeorr", "emnorst",
     "fimnoru", "ailrtuv", "aacfltu", "aginnrt", "eeloprx", "ceelnos", "eimnoot",
     "cefinst", "adeegln", "ddeefin", "beglnos", "deoopps", "aersssu", "deilors",
     "cenorss", "cddeeno", "aamnoty", "eoprstt", "ahmnory", "deeimpt", "deeipst",
     "abdlory", "aeglrst", "abddeet", "ceghino", "ceeflrt", "agimnrw", "imnoost",
     "eeenruv", "adelnnp", "abeklnt", "acehrss", "acehlss", "cdehrsu", "abcgikn",
     "gimnnor", "ceikstt", "knnnouw", "deefnrs", "aacmrss", "cdekkno", "bcdeklo",
     "cenostt", "cinosst", "deimmsu", "iiorstv", "cciirtu", "eelsssu", "aioprrt",
     "deiintv", "aceelnr", "aceirrs", "egnorsv", "eimopss", "acdeehr", "aeilnpx",
     "bginnru", "eflorsw", "eimoprs", "abilmox", "aejlosu", "gginnoo", "bnosttu",
     "cnoortu", "deeginn", "eeprstx", "eforsst", "einnost", "cginost", "eiloptx",
     "acghins", "ginortu", "ceirssu", "adempsw", "adgilnn", "cmosstu", "agiklnt",
     "iimmmnu", "cfiilnt", "giinssu", "gggilno", "ceeprst", "ekmorss", "acdelss",
     "cenortv", "elrttuy", "aeorstt", "delostu", "cefnoss", "aelprst", "ddefloo",
     "adeglpu", "cdeeesx", "aeelrst", "aghinps", "deefmor", "cfmnoor", "adeeflr",
     "aehltwy", "acginrs", "deimnrs", "cdddeeo", "bdeginn", "enoprss", "adeimrr",
     "beffrsu", "aablntt", "ginpttu", "egiinvw", "acerrtt", "gimnppu", "cefirty",
     "eeqrstu", "clnoort", "gillnpu", "eikrsst", "agiknpr", "aeglotv", "agimnpp",
     "ghiinnt", "adeekns", "belostt", "aadoprx", "addeggr", "deikpps", "ceeginr",
     "aaegmnr", "dinosww", "deorsty", "cdeefst", "bimsstu", "eginrss", "ceknors",
     "addeegr", "ceenprt", "aainrtv", "aeeflms", "aenprrt", "adeegll", "aeeggns",
     "addeisv", "ddeenps", "eorrstu", "eenrssu", "aelrstt", "ailmnno", "eopssss",
     "aeegrrt", "bemnstu", "ginnrtu", "deefgin", "deejnoy", "efgiorv", "eeilntt",
     "acfinrt", "giinors", "ddgiinr", "airsstt", "deeilrv", "ciiosuv", "filrsty",
     "aabcelp", "aemnrsu", "ddefnou", "gilorty", "cfmoort", "ikmoost", "adeinsv",
     "giimnss", "enorsuv", "agiinrs", "aiilmmn", "aaccnvy", "cfimnor", "aeqrrtu",
     "acennrs", "aalnsty", "ghiknoo", "abccoot", "hlmnoty", "deiknov", "agimnsu",
     "acehlnn", "mopprst", "cehirst", "fgiintt", "eegrstu", "cennost", "eegmnst",
     "eiillrs", "cdeirsu", "eeeilrv", "ciimstv", "giinrtw", "aellmrs", "deeffor",
     "acfltuy", "celrtuy", "giilmns", "deeipss", "dehlors", "egimnrt", "efhrrtu",
     "aeegmss", "ginopru", "aehhlty", "eeelmnt", "aeglrru", "acdehpt", "bcceily",
     "aeehrsw", "bdgiinn", "dgiinty", "hrssttu", "eeffint", "eginquu", "acerttx",
     "abeillr", "aabeggr", "aginssv", "aceehnn", "deeelns", "acellny", "acehmst",
     "deinsty", "aeefrwy", "aacflly", "adllors", "aghilnt", "aailpst", "celosst",
     "agiilmn", "cceikrt", "abbdegr", "cgilnos", "ccdehku", "abginrr", "eggimnr",
     "innoost", "elorstv", "adeinpt", "aeelrsv", "acdeert", "agilnpy", "adeiprs",
     "aaegtwy", "aaeilss", "acdeeht", "afostuu", "eeinnps", "einrsst", "flloosw",
     "eeirssv", "abeelns", "cdehinp", "acdginn", "cemoops", "afklnry", "aiimprs",
     "ghloruy", "effrssu", "deeoprw", "adehnrs", "aabdnno", "ghiinst", "efnortu",
     "coprrtu", "eiimnrt", "bellstu", "aeelssw", "dgikmno", "dgiilns", "eeiprvw",
     "aceelrr", "deinprt", "adeilpp", "bhiiint", "acilpty", "demrrsu", "eggsstu",
     "imoprst", "dehipps", "bdelosu", "aghinsw", "ddeeisv", "begglos", "cdelopu",
     "aceepss", "deeopsx", "aceirrr", "aceilrt", "agiklnw", "ceirrtu", "cdeeepr",
     "aeinrst", "iillmno", "aegikln", "bdinstu", "bdegooy", "egilnss", "aaelpps",
     "cdeirst", "cehooss", "aeeegnt", "adeilms", "aadelry", "eeerrsv", "eenrstw",
     "ehnorst", "ceeinrs", "dgiinnw", "cemnosu", "acinost", "aegilnn", "cfiinot",
     "giijnno", "aeehirv", "acmnory", "adempst", "aadegmn", "adehrst", "aceflru",
     "deginnr", "cgimmnu", "eimprss", "cllorss", "aeprrsy", "adegrty", "fhiloos",
     "dehiosu", "fgiilnt", "aegllry", "adeilst", "cginopy", "aefhrrt", "aceehst",
     "aabginr", "behorst", "dgggiin", "bdeelov", "ailmopt", "einorsv", "adeglmn",
     "ghinpsu", "aeglsss", "aimprry", "aeepprr", "eghinrr", "accepst", "eooprst",
     "adelnpt", "aenprst", "aelrswy", "celmops", "denpssu", "ccdeeno", "abilrry",
     "opsttuu", "aeehlrt", "aeelmtu", "dddeiiv", "eefgiln", "deisstu", "cehnpsu",
     "deeprss", "aacdilr", "addenss", "abeginr", "deiopss", "aeginrs", "deeoruv",
     "deginss", "deinopt", "aacchir", "ademssu", "denorsw", "addeinr", "aaenpst",
     "acmnopy", "allmory", "cdeekrw", "aegilll", "abeimnt", "elnotvy", "afhinos",
     "aehimst", "acdmmno", "deimnps", "ainrstt", "eeilprs", "beehrwy", "beeeilv",
     "aeinqtu", "aepprrw", "eeijlls", "deeostv", "deiorrw", "inoopss", "adorstw",
     "fgimnor", "aeglpsu", "densttu", "cddeorw", "deilpps", "acghikn", "einortu",
     "einorst", "cilprtu", "aceerst", "efinnru", "cdemnno", "eenprtv", "eiprsst",
     "cgikmnu", "aghinsu", "ammrsuy", "eemorsv", "einnstv", "aaeegrv", "abgiknr",
     "eiorssu", "aefirst", "eeinrst", "eoprrst", "aacemrs", "acdertt", "ailmmor",
     "acgilnp", "eeirsvw", "aelnstt", "aeginrt", "deelopv", "agijmmn", "ellorty",
     "aacrttt", "eprssuu", "achlors", "blmossy", "acgilln", "adenpsx", "aeenrst",
     "aimmmux", "eehistv", "einrttw", "deenrsu", "achirty", "deginny", "glnorwy",
     "egiintx", "aehmsss", "eilnotu", "cciprty", "acepsst", "cceilrs", "adeemnr",
     "ddeeirv", "ceersst", "fgilnow", "ghhortu", "dekorwy", "eeimpst", "aceehrs",
     "aeimrtw", "aceilps", "einrstv", "adeehrs", "deffirs", "aisssst", "eiilstt",
     "dggiinu", "ccinotv", "cellosy", "eeginns", "acdeghr", "kloootu", "aacilpt",
     "celmssu", "ceffior", "bcejstu", "efhllpu", "cdddeei", "diimsss", "deeilpr",
     "acdehmr", "addehln", "aellquy", "cdeopru", "aehnpps", "aehistt", "celrtuu",
     "accessu", "efforst", "eggirrt", "cklnuuy", "cdeirtv", "acdenss", "acchiot",
     "ceehmss", "degimnn", "aeimrrs", "bhilpsu", "ceorssu", "eehnorw", "eelorsv",
     "adeilly", "cgiinno", "abilort", "aegiimn", "bdeilru", "aalmnoy", "ciklquy",
     "abeirrz", "abcgklo", "aenpstu", "ahorstu", "efhlopu", "cdehnpu", "adddeer",
     "deinnst", "eepstty", "ceemopt", "aginpry", "agghinn", "ceorsss", "ceeiprt",
     "aeimssv", "dghilno", "aeflrsu", "abinost", "agiinnr", "deinstt", "bbhirsu",
     "ghiinsw", "adeilmm", "cekosst", "adeissv", "fioprst", "deemptt", "efmorrs",
     "eiilmps", "aaegpss", "dehostu", "ciortvy", "cehrstt", "acdeklt", "acginrt",
     "aeekprs", "cgiiknp", "elosstw", "defhlsu", "aailmns", "bbgimno", "acehimn",
     "iilttuy", "ceelsst", "ddefils", "deeegrs", "ehopprt", "acgikln", "ginoqtu",
     "belmstu", "ejnoruy", "cceehkr", "deiklls", "giinppr", "aceinnt", "eghilrt",
     "bdiosuu", "adeirrv", "aacinpt", "bghortu", "eersstt", "aillnpy", "ginnnru",
     "eilmprs", "immoptu", "iinnoop", "acginsu", "abcgiln", "mnnosyy", "cddeeos",
     "ceoprtt", "abdeort", "aghhiwy", "deginnv", "celrstu", "aginpss", "eeirrst",
     "himprtu", "ghiintt", "aackstt", "deiorst", "cciirst", "aceorrt", "cceorrt",
     "accnott", "eiinstv", "acilrty", "aenorss", "deenprt", "acilopt", "eegimns",
     "cemmnot", "ceehilv", "aagmmrr", "eeegnrv"]
    |> Enum.into(HashSet.new)
  end
end
