defmodule Jumble.ScowlDict.Size20.Length10 do
  def get(string_id) do
    %{"addeeirstv" => ["advertised"], "ceennorstu" => ["encounters"],
      "aeellntuvy" => ["eventually"], "aadefrrstw" => ["afterwards"],
      "eeehlnopst" => ["telephones"], "ceelmmnopt" => ["complement"],
      "aeeilnqtuv" => ["equivalent"], "aacddeinst" => ["candidates"],
      "acdiinorst" => ["indicators"], "eeinnosstx" => ["extensions"],
      "adinorsstw" => ["downstairs"], "addeeloorv" => ["overloaded"],
      "aadeelqtuy" => ["adequately"], "aeeillrtvy" => ["relatively"],
      "cdefnnoort" => ["confronted"], "eehmnnnoop" => ["phenomenon"],
      "abelmprsuy" => ["presumably"], "eimorsstuy" => ["mysterious"],
      "aeginrsstu" => ["signatures"], "acdefiilss" => ["classified"],
      "deelmnopuy" => ["unemployed"], "bdeeeemmrr" => ["remembered"],
      "aabelnorsy" => ["reasonably"], "cdennoopru" => ["pronounced"],
      "adglnopruy" => ["playground"], "accdemostu" => ["accustomed"],
      "deeefmnrru" => ["referendum"], "aiinossttu" => ["situations"],
      "accginnott" => ["contacting"], "acdeiilmrs" => ["disclaimer"],
      "acddeirstt" => ["distracted"], "acdeeffntu" => ["unaffected"],
      "mnnoossuyy" => ["synonymous"], "deefiiinrt" => ["identifier"],
      "cefiiilnty" => ["infelicity"], "aeimnorrtt" => ["terminator"],
      "acdeilmnop" => ["complained"], "abeirstttu" => ["attributes"],
      "acdiilmopt" => ["diplomatic"], "gggilnrstu" => ["struggling"],
      "eeiinoprtt" => ["repetition"], "aaillnnoty" => ["nationally"],
      "aegiimnstt" => ["estimating"], "aceimsstty" => ["systematic"],
      "acinnorsst" => ["constrains"], "deiimnoprs" => ["imprisoned"],
      "eeilnopsst" => ["politeness"], "eiinrstuvy" => ["university"],
      "effginostt" => ["offsetting"], "aceeinrsst" => ["resistance"],
      "aceilmtuuv" => ["cumulative"], "abbeeeillv" => ["believable"],
      "deefghinrt" => ["frightened"], "cdffiiltuy" => ["difficulty"],
      "ccdginnotu" => ["conducting"], "dggiiinssu" => ["disguising"],
      "aceemnopst" => ["compensate"], "addeilmtty" => ["admittedly"],
      "eeiimprssv" => ["impressive"], "adeeinprst" => ["pedestrian"],
      "aeehmoprst" => ["atmosphere"], "ceeeefnrrs" => ["references"],
      "eekkorssty" => ["keystrokes"], "aaceirtttv" => ["attractive"],
      "cdeeginopr" => ["proceeding"], "ceinnoorsv" => ["conversion"],
      "ciopprsstt" => ["postscript"], "dgiinorstt" => ["distorting"],
      "ceginnortv" => ["converting"], "acilmorsuu" => ["miraculous"],
      "ceiinnopst" => ["inspection"], "aijlnorstu" => ["journalist"],
      "ainooqsttu" => ["quotations"], "abefiillln" => ["infallible"],
      "beisstttuu" => ["substitute"], "afillmnory" => ["informally"],
      "deeklooorv" => ["overlooked"], "aceiiorstt" => ["atrocities"],
      "adeimnoort" => ["moderation"], "eiillmpstu" => ["multiplies"],
      "aehimnsstu" => ["enthusiasm"], "deeiilmrst" => ["delimiters"],
      "ceelnorsvy" => ["conversely"], "acfgiilnry" => ["clarifying"],
      "cceeilnort" => ["electronic"], "ceefilnnsu" => ["influences"],
      "cinooprrtu" => ["corruption"], "efgimnoprr" => ["performing"],
      "aaccilprst" => ["practicals"], "deeinoqstu" => ["questioned"],
      "cegiinrrtu" => ["recruiting"], "acehilorrt" => ["rhetorical"],
      "ghiloopsyy" => ["physiology"], "aaceinssst" => ["assistance"],
      "ddeeirssst" => ["distressed"], "defhiinprs" => ["friendship"],
      "bceeiprrss" => ["prescribes"], "bceeijstuv" => ["subjective"],
      "agiimnottv" => ["motivating"], "aaadgnoppr" => ["propaganda"],
      "cennooprsu" => ["pronounces"], "aabeillnuv" => ["invaluable"],
      "eginopprss" => ["oppressing"], "cdeinorstu" => ["reductions", "introduces"],
      "bggiinnpru" => ["upbringing"], "aeeiimprtv" => ["imperative"],
      "aabbeilnot" => ["obtainable"], "aaeeeggrtx" => ["exaggerate"],
      "deeginnprt" => ["pretending"], "agiillnory" => ["originally"],
      "ceennoqstu" => ["consequent"], "ceiillptxy" => ["explicitly"],
      "deefiilnty" => ["definitely"], "abefiloprt" => ["profitable"],
      "cegilmnopt" => ["completing"], "aceginrstt" => ["scattering"],
      "diinoprstu" => ["disruption"], "aadeegnrrr" => ["rearranged"],
      "abcceeilss" => ["accessible"], "cceillnoot" => ["collection"],
      "cehinoprss" => ["censorship"], "aeeillsstt" => ["satellites"],
      "eefginorrs" => ["foreigners"], "aaciilmpst" => ["capitalism"],
      "aegimnnsst" => ["assignment"], "deehilmoss" => ["demolishes"],
      "aeeilnortv" => ["revelation"], "aabbeelnru" => ["unbearable"],
      "accinoprsy" => ["conspiracy"], "abcgiilloo" => ["biological"],
      "eghiiinnrt" => ["inheriting"], "cdeeiirstv" => ["directives"],
      "cceinnoopt" => ["conception"], "cdeinrsttu" => ["instructed"],
      "abeilnstuu" => ["unsuitable"], "cdinooprtu" => ["production"],
      "bghiilnpsu" => ["publishing"], "aeillrsttu" => ["illustrate"],
      "deeiprssuv" => ["supervised"], "chiipsssty" => ["physicists"],
      "ddeeeimnrt" => ["determined"], "abeegilnot" => ["negotiable"],
      "degilnnruy" => ["underlying"], "aeiinnotvv" => ["innovative"],
      "abcdeeeltt" => ["detectable"], "eeilmmnpst" => ["implements"],
      "eeginprrsv" => ["preserving"], "aceinorttx" => ["extraction"],
      "acginnnnou" => ["announcing"], "aiiinnottv" => ["invitation"],
      "aabcehilpt" => ["alphabetic"], "efgiinrrty" => ["terrifying"],
      "abeklnoruw" => ["unworkable"], "deeinoprss" => ["depression"],
      "aacdegimnp" => ["campaigned"], "inooopprrt" => ["proportion"],
      "ceinooprtt" => ["protection"], "cdeeenptux" => ["unexpected"],
      "eeimnnsstt" => ["sentiments"], "cdegiinprt" => ["predicting"],
      "ceinostttu" => ["constitute"], "aaciilnost" => ["antisocial"],
      "cceflsssuu" => ["successful"], "aabbeeirtv" => ["abbreviate"],
      "defiiinnot" => ["definition"], "cceeisssuv" => ["successive"],
      "aalnorrstt" => ["translator"], "agiilmnstu" => ["simulating"],
      "ceefinoprt" => ["perfection"], "aabeelnors" => ["reasonable"],
      "deeeimnrst" => ["determines"], "deginnoprs" => ["responding"],
      "acdeiiintv" => ["indicative"], "aaaceenppr" => ["appearance"],
      "aeellnrtxy" => ["externally"], "aeehorstvw" => ["whatsoever"],
      "ceefhhnort" => ["henceforth"], "aaaghpprrs" => ["paragraphs"],
      "adeeglrrss" => ["regardless"], "aclrrsttuu" => ["structural"],
      "eeehlmsstv" => ["themselves"], "aacilprrtu" => ["particular"],
      "aadginortu" => ["graduation"], "bgiimnsttu" => ["submitting"],
      "ceeinnnotv" => ["convenient"], "deeiinoptx" => ["expedition"],
      "aeeinorstt" => ["orientates"], "eghinnorst" => ["shortening"],
      "aceeegnprt" => ["percentage"], "adegoorrty" => ["derogatory"],
      "aaaehpprrs" => ["paraphrase"], "adefrrsttu" => ["frustrated"],
      "aacinorttt" => ["attraction"], "abcdgknoru" => ["background"],
      "defgiilnrr" => ["girlfriend"], "ddeeilnnru" => ["underlined"],
      "eeeiiprttv" => ["repetitive"], "abceeeltux" => ["executable"],
      "cdeeinorrs" => ["reconsider"], "eiilopstvy" => ["positively"],
      "acceeillrt" => ["electrical"], "aadeeinqtu" => ["inadequate"],
      "abceefiiln" => ["beneficial"], "aiiilmmnst" => ["minimalist"],
      "adeelmorty" => ["moderately"], "deeefinrrt" => ["interfered"],
      "adeehilprs" => ["leadership"], "aellnoprsy" => ["personally"],
      "accginnotu" => ["accounting"], "aabbcdklor" => ["blackboard"],
      "ceghinrstt" => ["stretching"], "ciiillmpty" => ["implicitly"],
      "aghilmorst" => ["algorithms"], "abeeeflprr" => ["preferable"],
      "adeeelprty" => ["repeatedly"], "aaeimmnrst" => ["mainstream"],
      "dggiiimnsu" => ["misguiding"], "abcegiknrt" => ["bracketing"],
      "aabeeklmrr" => ["remarkable"], "abgiilnoot" => ["obligation"],
      "acehimmnss" => ["mechanisms"], "abceeelrst" => ["celebrates"],
      "aagillmnry" => ["marginally"], "cgiimmnott" => ["committing"],
      "eegmnnortv" => ["government"], "cddeinortu" => ["introduced"],
      "ccdeefiiny" => ["deficiency"], "ceehinnort" => ["incoherent"],
      "ccdgilnnou" => ["concluding"], "adeehnnrtu" => ["underneath"],
      "ahilnoortz" => ["horizontal"], "aeilmnoprs" => ["impersonal"],
      "eegiilprsv" => ["privileges"], "ccgiinnnov" => ["convincing"],
      "ceinnosstt" => ["consistent"], "acgiilmnps" => ["misplacing"],
      "aacillnoot" => ["allocation"], "efinooprss" => ["profession"],
      "abeeiilntv" => ["inevitable"], "bcdeeiilnr" => ["incredible"],
      "aaelnpprty" => ["apparently"], "adeeinrstt" => ["reinstated"],
      "acgillnops" => ["collapsing"], "cefgiinpsy" => ["specifying"],
      "egiimnnnot" => ["mentioning"], "aiinnorstt" => ["transition"],
      "eiinnnostv" => ["inventions"], "aacehopprs" => ["approaches"],
      "defiiilmps" => ["simplified"], "cciinnootv" => ["conviction"],
      "addeeginst" => ["designated"], "acddgiinrs" => ["discarding"],
      "deiinoopst" => ["positioned"], "ceegiinprv" => ["perceiving"],
      "acdeeginrs" => ["decreasing"], "eeiilnostv" => ["television"],
      "aeiilnqtuy" => ["inequality"], "agiiiinntt" => ["initiating"],
      "aceeghllns" => ["challenges"], "behilprssu" => ["publishers"],
      "ginnooppst" => ["postponing"], "eioprrssuv" => ["supervisor"],
      "acchilmops" => ["accomplish"], "cceeefnnor" => ["conference"],
      "eelnorstuv" => ["volunteers"], "ccefiiinst" => ["scientific"],
      "cddeeoprru" => ["reproduced"], "cdeeirrstt" => ["restricted"],
      "aefrrssttu" => ["frustrates"], "efgginortt" => ["forgetting"],
      "degginnoru" => ["undergoing"], "aeginrrssu" => ["reassuring"],
      "adiinoppst" => ["disappoint"], "eeenprrsst" => ["represents"],
      "iinoooppst" => ["opposition"], "aaeegnrstu" => ["guarantees"],
      "deeeinrstt" => ["interested"], "aillmnoopy" => ["polynomial"],
      "aeimnopttt" => ["temptation"], "deefiiintv" => ["definitive"],
      "afghiinnos" => ["fashioning"], "abdeilopss" => ["disposable"],
      "aeeilrrttu" => ["literature"], "aabceillpp" => ["applicable"],
      "agiinnsstu" => ["sustaining"], "adiiilmrss" => ["dissimilar"],
      "gghiilnnst" => ["lightnings"], "acddegiint" => ["dedicating"],
      "accefiirss" => ["sacrifices"], "accdenortt" => ["contracted"],
      "achiilorst" => ["historical"], "aceegllosu" => ["colleagues"],
      "acinnorstt" => ["constraint"], "acceilmmor" => ["commercial"],
      "ciiilmpsst" => ["simplistic"], "adfinnootu" => ["foundation"],
      "cdeeeffinr" => ["difference"], "aacgillnot" => ["allocating"],
      "aeemnsssst" => ["assessment"], "adgiiknnpp" => ["kidnapping"],
      "aeegginnrt" => ["generating"], "cegiinnpst" => ["inspecting"],
      "cdeemoprss" => ["compressed"], "ailnoopptu" => ["population"],
      "cceejnortu" => ["conjecture"], "aaeelprsty" => ["separately"],
      "abdeinorsu" => ["boundaries"], "acegghinnx" => ["exchanging"],
      "aegilnortu" => ["regulation"], "aiiilmnott" => ["limitation"],
      "aiinoprstt" => ["partitions"], "aabloorrty" => ["laboratory"],
      "aaenrrsttu" => ["restaurant"], "cgilnnostu" => ["consulting"],
      "adiilnrstu" => ["industrial"], "accelnoptu" => ["conceptual"],
      "ceeiinnsst" => ["insistence"], "ehimnnpstu" => ["punishment"],
      "aiinnnootv" => ["innovation"], "adiorssstu" => ["disastrous"],
      "afgiilnquy" => ["qualifying"], "eeghnnrstt" => ["strengthen"],
      "aeeghlortt" => ["altogether"], "aaccellstu" => ["calculates"],
      "cdeemmnors" => ["recommends"], "cgiinnnotu" => ["continuing"],
      "adeeinrrst" => ["restrained"], "bdegiilnru" => ["rebuilding"],
      "egiimnprss" => ["impressing"], "aacfillosu" => ["fallacious"],
      "deiimnnoss" => ["dimensions"], "agiinoorrt" => ["originator"],
      "aefilmnsty" => ["manifestly"], "eefginprrr" => ["preferring"],
      "aeeprsswxy" => ["expressway"], "adeeinortt" => ["orientated"],
      "ceeginorrv" => ["recovering"], "beefiillnx" => ["inflexible"],
      "aaccilnoos" => ["occasional"], "acehiimrtt" => ["arithmetic"],
      "aadhilrtww" => ["withdrawal"], "agillnosww" => ["swallowing"],
      "deeegirrst" => ["registered"], "beenqsstuu" => ["subsequent"],
      "addeginrss" => ["addressing"], "aeinooprst" => ["operations"],
      "aabhiinntt" => ["inhabitant"], "adeiimnrst" => ["administer"],
      "aaegillnot" => ["allegation"], "acdeinoort" => ["coordinate"],
      "aaeinoprst" => ["separation"], "ccdeeeenpr" => ["precedence"],
      "aeillnnrty" => ["internally"], "abdnoortuu" => ["roundabout"],
      "bdeiirsttu" => ["distribute"], "deeilnnrsu" => ["underlines"],
      "deiillmptu" => ["multiplied"], "ceeilmnopt" => ["incomplete"],
      "einnopsssu" => ["suspension"], "degghiilnt" => ["delighting"],
      "aaccllortu" => ["calculator"], "ceginoprss" => ["processing"],
      "ccegillnot" => ["collecting"], "ccilnnoosu" => ["conclusion"],
      "ceiinssstt" => ["scientists"], "egiimnprtt" => ["permitting"],
      "eeeimnprtx" => ["experiment"], "cceeffiiny" => ["efficiency"],
      "efimnorstu" => ["misfortune"], "aeggginrst" => ["staggering"],
      "dehiiklloo" => ["likelihood"], "defhiinnsu" => ["unfinished"],
      "eefghinrrs" => ["refreshing"], "ceiilnpprs" => ["principles"],
      "ceeeimnttx" => ["excitement"], "cegillmnop" => ["compelling"],
      "efiiilmpss" => ["simplifies"], "ceginnoost" => ["congestion"],
      "aacilnppst" => ["applicants"], "cddeeginns" => ["descending"],
      "cdeginorrs" => ["recordings"], "ciiloorsst" => ["solicitors"],
      "afgimnortt" => ["formatting"], "eilnoortuv" => ["revolution"],
      "bcdegiinrs" => ["describing"], "aciisssttt" => ["statistics"],
      "acdeeinrtt" => ["interacted"], "aaeilmnprt" => ["parliament"],
      "ceilmmnopt" => ["compliment"], "eeginprssx" => ["expressing"],
      "accegilnno" => ["concealing"], "abeilmootu" => ["automobile"],
      "beghinrsst" => ["brightness"], "acdgiiinnt" => ["indicating"],
      "deeeloprsv" => ["developers"], "adeginprsu" => ["persuading"],
      "efiiilnnty" => ["infinitely"], "aehlmoosux" => ["homosexual"],
      "ceemoprsss" => ["compresses"], "ceeeefnprr" => ["preference"],
      "adiinorstt" => ["traditions"], "ccceeinnos" => ["conscience"],
      "aeillmnrty" => ["terminally"], "cdiinosssu" => ["discussion"],
      "cdeeioprrv" => ["overpriced"], "adeilmsttu" => ["stimulated"],
      "cdiilorsuu" => ["ridiculous"], "aeegiilmtt" => ["legitimate"],
      "abcenssstu" => ["substances"], "agiillnnst" => ["installing"],
      "aceegiorst" => ["categories"], "acdeiiilst" => ["idealistic"],
      "aaddeesttv" => ["devastated"], "eeginnprtv" => ["preventing"],
      "adegmmoprr" => ["programmed"], "cdeghilnsu" => ["scheduling"],
      "aeenpprssw" => ["newspapers"], "aaelnnpstu" => ["unpleasant"],
      "abeeillnru" => ["unreliable"], "giloorsuvy" => ["vigorously"],
      "eeelnrsttw" => ["newsletter"], "acdeegnoru" => ["encouraged"],
      "cgiiilnstu" => ["linguistic"], "aeeiilmnst" => ["eliminates"],
      "aacefinsst" => ["fascinates"], "aaiinorstv" => ["variations"],
      "beiilmopss" => ["impossible"], "aeeiillrtt" => ["illiterate"],
      "aaccdelltu" => ["calculated"], "cddeemnotu" => ["documented"],
      "elmnoorsuy" => ["enormously"], "acddeilptu" => ["duplicated"],
      "bcdeeiprrs" => ["prescribed"], "ciimmnooss" => ["commission"],
      "aiimnoottv" => ["motivation"], "aacceeelrt" => ["accelerate"],
      "aacfiiilrt" => ["artificial"], "acfilnnotu" => ["functional"],
      "ccgiinnotv" => ["convicting"], "afhkllntuy" => ["thankfully"],
      "aegimnpttt" => ["attempting"], "aefnnoorst" => ["afternoons"],
      "bghiiiinnt" => ["inhibiting"], "cdeeeprstu" => ["persecuted"],
      "adeeeegnrt" => ["degenerate"], "aabdginnno" => ["abandoning"],
      "ceginoprtt" => ["protecting"], "ghhoorttuu" => ["throughout"],
      "acehlorrst" => ["orchestral"], "cdellnoort" => ["controlled"],
      "acefiiilst" => ["facilities"], "abghiiinnt" => ["inhabiting"],
      "aemoprsstt" => ["postmaster"], "aeeginostt" => ["negotiates"],
      "abceilmopt" => ["compatible"], "bcegijnstu" => ["subjecting"],
      "cgiinnosst" => ["consisting"], "ddeefiiint" => ["identified"],
      "bddfgiinor" => ["forbidding"], "aceegnorsu" => ["encourages"],
      "aadeipprss" => ["disappears"], "adeeirsstv" => ["advertises"],
      "aeinoprttu" => ["reputation"], "abdeefhnor" => ["beforehand"],
      "aaeegmmnnt" => ["management"], "acegiinnrs" => ["increasing"],
      "acimnoopss" => ["compassion"], "aadgginrtu" => ["graduating"],
      "anoprrsstt" => ["transports"], "adegiimnrs" => ["misreading"],
      "adeeiirtvv" => ["derivative"], "eegginrrtt" => ["regretting"],
      "eeiprrttwy" => ["typewriter"], "eepprssssu" => ["suppresses"],
      "adegiinort" => ["originated"], "abdeeeilrt" => ["deliberate"],
      "agiiinrrtt" => ["irritating"], "ddenoorstu" => ["understood"],
      "aefgllrtuy" => ["gratefully"], "aiiinorrtt" => ["irritation"],
      "adgiilnpsy" => ["displaying"], "aacehmnttt" => ["attachment"],
      "cdeeoprrsu" => ["procedures", "reproduces"], "achillpsyy" => ["physically"],
      "aiilmnostu" => ["simulation"], "ceegiinrsx" => ["exercising"],
      "aaccelrtuy" => ["accurately"], "egginosstu" => ["suggestion"],
      "acddennruy" => ["redundancy"], "einprrsttu" => ["interrupts"],
      "aacdginotv" => ["advocating"], "fghiinorry" => ["horrifying"],
      "cddeeinors" => ["considered"], "defilnnruy" => ["unfriendly"],
      "agiimnnnot" => ["nominating"], "cceginorrt" => ["correcting"],
      "cdeiimrsst" => ["misdirects"], "cdefginoru" => ["configured"],
      "deginorsty" => ["destroying"], "ceefgilnrt" => ["reflecting"],
      "deefiiinst" => ["identifies"], "cemnnoopst" => ["components"],
      "aabcdorsst" => ["broadcasts"], "bdeeilnorr" => ["borderline"],
      "aeillmttuy" => ["ultimately"], "ceeggilnnt" => ["neglecting"],
      "aacdefinst" => ["fascinated"], "ehimnopssy" => ["symphonies"],
      "aaillnorty" => ["rationally"], "cehmmnooor" => ["monochrome"],
      "clmooprsuy" => ["compulsory"], "acdknorstu" => ["soundtrack"],
      "giinprrssu" => ["surprising"], "defghilltu" => ["delightful"],
      "ciinnottuy" => ["continuity"], "aeghinstux" => ["exhausting"],
      "eeeimnrrtt" => ["retirement"], "accdeimort" => ["democratic"],
      "acdgiinost" => ["diagnostic"], "ddeeinorrv" => ["overridden"],
      "cceinnnoot" => ["connection"], "adeeginsst" => ["designates"],
      "abgiloorty" => ["obligatory"], "abeeeglstv" => ["vegetables"],
      "cdenooprrs" => ["correspond"], "aeeelmnrty" => ["elementary"],
      "acdeeghlln" => ["challenged"], "hhilooppsy" => ["philosophy"],
      "adgiimnnot" => ["dominating"], "ceinnnootv" => ["convention"],
      "cfgiimnnor" => ["confirming"], "cdeeijprsu" => ["prejudices"],
      "eeiprsssuv" => ["supervises"], "aaeginprst" => ["separating"],
      "aeiimnostt" => ["estimation"], "aainorstty" => ["stationary"],
      "cdiinnoost" => ["conditions"], "eilnoopssx" => ["explosions"],
      "aginoprrty" => ["portraying"], "aeinoprssu" => ["persuasion"],
      "aceeillpsy" => ["especially"], "egggiinrrt" => ["triggering"],
      "aaddiilnot" => ["additional"], "ceeeprsstu" => ["persecutes"],
      "einoopssss" => ["possession"], "aeinnosttt" => ["attentions"],
      "aacdehoppr" => ["approached"], "acdiiinnot" => ["indication"],
      "egiinnsstw" => ["witnessing"], "eopprrsstu" => ["supporters"],
      "acdeilpstu" => ["duplicates"], "aagimnottu" => ["automating"],
      "aacgiinttv" => ["activating"], "aimnopsstu" => ["assumption"],
      "cdeeeefnrr" => ["referenced"], "aeeilnrrtv" => ["irrelevant"],
      "cdeiimnntt" => ["indictment"], "abeeflprry" => ["preferably"],
      "aeiklmnsty" => ["mistakenly"], "eiiimprstv" => ["primitives"],
      "abdeirtttu" => ["attributed"], "addeennttu" => ["unattended"],
      "aacceinrtu" => ["inaccurate"], "adinnopstt" => ["standpoint"],
      "eeghinrtvy" => ["everything"], "ccdeeginsu" => ["succeeding"],
      "bhiiiinnot" => ["inhibition"], "aceilnoort" => ["relocation"],
      "aaadinoptt" => ["adaptation"], "abbeilmopr" => ["improbable"],
      "eelmmnopty" => ["employment"], "aaeilnortt" => ["alteration"],
      "deegiinnrt" => ["ingredient"], "cegimnoorv" => ["overcoming"],
      "aceimnoprt" => ["importance"], "accdinortt" => ["contradict"],
      "aacginrttt" => ["attracting"], "acffiilloy" => ["officially"],
      "aabiilnrvy" => ["invariably"], "cilmnoopsu" => ["compulsion"],
      "ddeehilmos" => ["demolished"], "adeeginrtt" => ["integrated"],
      "accdefiirs" => ["sacrificed"], "ceeiinprst" => ["recipients"],
      "aadefgrssu" => ["safeguards"], "aaciilpstt" => ["capitalist"],
      "eehilnnrty" => ["inherently"], "eeflnsssuu" => ["usefulness"],
      "dggiinsstu" => ["disgusting"], "eeimnnsttv" => ["investment"],
      "beeilssttu" => ["subtleties"], "cdgiinsssu" => ["discussing"],
      "eegiinrrtv" => ["retrieving"], "aadeiimnnt" => ["maintained"],
      "ceeginnnst" => ["sentencing"], "agillnrsuy" => ["singularly"],
      "acdeiilnnt" => ["incidental"], "ceimmooprs" => ["compromise"],
      "accehllnor" => ["chancellor"], "cerrssttuu" => ["structures"],
      "eeiinrstvw" => ["interviews"], "aabeeelprt" => ["repeatable"],
      "aaccceenpt" => ["acceptance"], "ceimmmnott" => ["commitment"],
      "ceghlnooty" => ["technology"], "aaceeipprt" => ["appreciate"],
      "aaeinopsst" => ["passionate"], "abghiilnos" => ["abolishing"],
      "aeilmssttu" => ["stimulates"], "eeflnqrtuy" => ["frequently"],
      "aabllmnory" => ["abnormally"], "beehimmprs" => ["membership"],
      "addeeiprsw" => ["widespread"], "abceeilnot" => ["noticeable"],
      "adeeginott" => ["negotiated"], "aegiilnnpx" => ["explaining"],
      "deeellnssy" => ["needlessly"], "eeeioprrrt" => ["repertoire"],
      "adeehiprrs" => ["readership"], "aceeehrrrs" => ["researcher"],
      "eefinnqrtu" => ["infrequent"], "ahiinorsst" => ["historians"],
      "ceeinopstx" => ["exceptions"], "ceellmopty" => ["completely"],
      "ceijnooprt" => ["projection"], "aeeeknsssw" => ["weaknesses"],
      "cceinosssu" => ["succession"], "aaeegnrrrs" => ["rearranges"],
      "eeinprrstt" => ["interprets"], "acehilrsty" => ["hysterical"],
      "eeginqrstu" => ["requesting"], "aacellnosw" => ["allowances"],
      "aeginrrstt" => ["restarting"], "ddenorrsuu" => ["surrounded"],
      "aeeinnrstt" => ["entertains"], "ceginnnost" => ["consenting"],
      "cimmnosstu" => ["communists"], "accdeilrtu" => ["circulated"],
      "dehnoorrsu" => ["horrendous"], "aaccehrrst" => ["characters"],
      "cdeiilnrty" => ["indirectly"], "aaceiossst" => ["associates"],
      "eeinoprssx" => ["expression"], "aceeghnorv" => ["changeover"],
      "ccegiinnov" => ["conceiving"], "eiinopstvw" => ["viewpoints"],
      "eehllopssy" => ["hopelessly"], "bcdeorsttu" => ["obstructed"],
      "aadeiilntv" => ["invalidate"], "addiiilnuv" => ["individual"],
      "aclnnosttu" => ["consultant"], "deeirsssst" => ["distresses"],
      "aaefimmnrs" => ["mainframes"], "aeemnssttt" => ["statements"],
      "cceginnnot" => ["connecting"], "deginnpssu" => ["suspending"],
      "aeeegmnrst" => ["agreements"], "eelmnppstu" => ["supplement"],
      "aceginrttx" => ["extracting"], "aaccehilmn" => ["mechanical"],
      "aegoorstuu" => ["outrageous"], "cegijnoprt" => ["projecting"],
      "beegilmnrs" => ["resembling"], "aeiiiinttv" => ["initiative"],
      "ceimooprtt" => ["competitor"], "ciiimopstt" => ["optimistic"],
      "eelorssuvy" => ["yourselves"], "ceilmnoopt" => ["completion"],
      "cdegimnnno" => ["condemning"], "agiinnoppt" => ["appointing"],
      "acginnrttu" => ["truncating"], "cddeeiorsv" => ["discovered"],
      "aceeelortt" => ["electorate"], "ciiopsssuu" => ["suspicious"],
      "eiinnnostt" => ["intentions"], "abellostuy" => ["absolutely"],
      "adeeehnrtt" => ["threatened"], "abegilmnss" => ["assembling"],
      "aabcloruvy" => ["vocabulary"], "eeinnoprtv" => ["prevention"],
      "acceilmnoo" => ["economical"], "ceginpsstu" => ["suspecting"],
      "cginoprrtu" => ["corrupting"], "abdiirssuy" => ["subsidiary"],
      "cegginnost" => ["congesting"], "aaabdmorss" => ["ambassador"],
      "aacdeenntt" => ["attendance"], "acceilmopt" => ["complicate"],
      "adegiilmns" => ["misleading"], "deegiilnrv" => ["delivering"],
      "abeirrrsst" => ["barristers"], "aabcdelnnu" => ["unbalanced"],
      "deeginprss" => ["depressing"], "aehimpssty" => ["sympathies"],
      "agilnopptu" => ["populating"], "abcdeeelrt" => ["celebrated"],
      "aeeggirssv" => ["aggressive"], "cdiilnstty" => ["distinctly"],
      "aeeefhrrtt" => ["thereafter"], "cddeeijpru" => ["prejudiced"],
      "accinooptu" => ["occupation"], "aeegirsstt" => ["strategies"],
      "eimnnrsttu" => ["instrument"], "aabcceelpt" => ["acceptable"],
      "eiimnoprss" => ["impression", "permission"], "eeefinrrst" => ["interferes"],
      "ccdefilnot" => ["conflicted"], "bcdeiilnry" => ["incredibly"],
      "acimnooprs" => ["comparison"], "cdeehmnopr" => ["comprehend"],
      "degiinorrv" => ["overriding"], "ceeinopprt" => ["perception"],
      "acdehinssw" => ["sandwiches"], "deeeinnrtv" => ["intervened"],
      "cceinoorrt" => ["correction"], "aacccinruy" => ["inaccuracy"],
      "eioprstttu" => ["prostitute"], "abeellnruv" => ["vulnerable"],
      "deefiiinnt" => ["indefinite"], "aegilnortt" => ["tolerating"],
      "ccilmrruuu" => ["curriculum"], "bceijnoost" => ["objections"],
      "aacccdenor" => ["accordance"], "ghhloortuy" => ["thoroughly"],
      "ghhoprttuu" => ["throughput"], "cghloopsyy" => ["psychology"],
      "eeginnprst" => ["presenting"], "aceefinrst" => ["interfaces"],
      "aadeessttv" => ["devastates"], "aehoopprst" => ["apostrophe"],
      "acinprrstt" => ["transcript"], "aaccelmtuu" => ["accumulate"],
      "cdeiiilnps" => ["discipline"], "deefgiinnr" => ["redefining"],
      "defghiloss" => ["goldfishes"], "egiilnoptx" => ["exploiting"],
      "eeiopprrst" => ["properties"], "aaccnnottu" => ["accountant"],
      "gghhhiilst" => ["highlights"], "eeeinnrstv" => ["intervenes"],
      "abeiilntvy" => ["inevitably"], "dgiiimnsss" => ["dismissing"],
      "ailopprtuy" => ["popularity"], "acgiinnnot" => ["containing"],
      "aabdeelnru" => ["unreadable"], "aiiilmrsty" => ["similarity"],
      "cgiimnoprs" => ["comprising"], "aegilnprst" => ["plastering"],
      "beinorstuu" => ["subroutine"], "eiiioprrst" => ["priorities"],
      "cciiimrsst" => ["criticisms"], "cdeeeinnst" => ["tendencies"],
      "cderrsttuu" => ["structured"], "ceeeeinprx" => ["experience"],
      "aclnnostty" => ["constantly"], "acdeefinrt" => ["interfaced"],
      "aefiilqrsu" => ["qualifiers"], "aaelnrsstt" => ["translates"],
      "ciiilmpsty" => ["simplicity"], "ceeimmostt" => ["committees"],
      "eeeinprrst" => ["enterprise"], "eiiimnorst" => ["minorities"],
      "agiorsttuu" => ["gratuitous"], "aaceiinptt" => ["anticipate"],
      "egiknnortw" => ["networking"], "aeeimnrstt" => ["terminates"],
      "abceilnoty" => ["noticeably"], "iinooprssv" => ["provisions"],
      "aadiimnort" => ["admiration"], "aaccdeilnt" => ["accidental"],
      "aceiiisttv" => ["activities"], "aeeilnqstu" => ["sequential"],
      "aabcehilrt" => ["charitable"], "ceefilnort" => ["reflection"],
      "ggilnnoopr" => ["prolonging"], "aceinoprtu" => ["precaution"],
      "aeehilpprr" => ["peripheral"], "eehlmorsvw" => ["overwhelms"],
      "cegimmnnot" => ["commenting"], "ehhiopssty" => ["hypothesis"],
      "acdegiorsu" => ["discourage"], "bceinorttu" => ["contribute"],
      "ccdeinnost" => ["disconnect"], "aabciilpty" => ["capability"],
      "ceilmoptxy" => ["complexity"], "ceooprrsss" => ["processors"],
      "cdeiinorst" => ["discretion", "directions"], "aaeemprrst" => ["parameters"],
      "adfginorrw" => ["forwarding"], "acdiinorty" => ["dictionary"],
      "aceiilpsst" => ["specialist"], "bdgiinrstu" => ["disturbing"],
      "acdoorrsss" => ["crossroads"], "beeinssssu" => ["businesses"],
      "beeggiilln" => ["negligible"], "ceinnnoott" => ["contention"],
      "acceilrstu" => ["circulates"], "aafiilmnru" => ["unfamiliar"],
      "aciiilnopt" => ["politician"], "eiloprsuvy" => ["previously"],
      "acffiilnou" => ["unofficial"], "aghhoopprt" => ["photograph"],
      "cellnoorrt" => ["controller"], "bceemmorsu" => ["cumbersome"],
      "aeegnorrst" => ["generators"], "deiinrsstu" => ["industries"],
      "eeinprsstt" => ["persistent"], "eeeehrrvwy" => ["everywhere"],
      "afmnorrsst" => ["transforms"], "deegoprrss" => ["progressed"],
      "ceeoprsstu" => ["prosecutes"], "cefgiinrty" => ["rectifying"],
      "deegilnopv" => ["developing"], "eeeoprstty" => ["stereotype"],
      "aaiilnorrt" => ["irrational"], "aillnoopty" => ["optionally"],
      "cgiinnortv" => ["contriving"], "aacefiiltt" => ["facilitate"],
      "diinoorstt" => ["distortion"], "cddeinostu" => ["deductions"],
      "fgiijnstuy" => ["justifying"], "behiiinotx" => ["exhibition"],
      "aeeginnort" => ["generation"], "acefiilsss" => ["classifies"],
      "ginopprstu" => ["supporting"], "accelmnopt" => ["complacent"],
      "bdehiioprt" => ["prohibited"], "ffgiilllnu" => ["fulfilling"],
      "aeggiinnsv" => ["envisaging"], "deloppssuy" => ["supposedly"],
      "eiorrrsstt" => ["terrorists"], "accegilloo" => ["ecological"],
      "einoopprss" => ["oppression"], "acilmnopst" => ["complaints"],
      "adeeknrstu" => ["undertakes"], "acdegirrst" => ["cartridges"],
      "aaadegnstv" => ["advantages"], "aeegnprsss" => ["passengers"],
      "ceehiloprt" => ["helicopter"], "cdeginnnos" => ["condensing"],
      "aeenorstux" => ["extraneous"], "adeemnprtt" => ["department"],
      "acceelnrtu" => ["reluctance"], "aegiinorst" => ["originates"],
      "aaeoprrsst" => ["separators"], "biimnosssu" => ["submission"],
      "adeenrstuv" => ["adventures"], "cddeeeennp" => ["dependence"],
      "aaeeginrtv" => ["vegetarian"], "ccdeefinno" => ["confidence"],
      "aadelnrstt" => ["translated"], "accghinrst" => ["scratching"],
      "bgiiloosst" => ["biologists"], "aeeginrstt" => ["integrates"],
      "cdeioprtuv" => ["productive"], "deepprsssu" => ["suppressed"],
      "aacdeiosst" => ["associated"], "ceffiinstu" => ["sufficient"],
      "cdeefilnnu" => ["influenced"], "adeeknnrtu" => ["undertaken"],
      "aacehimprs" => ["pharmacies"], "giimnnoort" => ["monitoring"],
      "aegmmoprrr" => ["programmer"], "aaeilnotuv" => ["evaluation"],
      "aaellnpsty" => ["pleasantly"], "ehhilortww" => ["worthwhile"],
      "cdeiinoprt" => ["prediction"], "addennrstu" => ["understand"],
      "aemnoorrst" => ["astronomer"], "aeiilrttvy" => ["relativity"],
      "aabeklmrry" => ["remarkably"], "aaeilmnptu" => ["manipulate"],
      "cceeillotv" => ["collective"], "cdeeoprstu" => ["prosecuted"],
      "eeghilnnst" => ["enlightens"], "eegoprrsss" => ["progresses"],
      "deeeeginnr" => ["engineered"], "cinnoostuu" => ["continuous"],
      "adeeiilmnt" => ["eliminated"], "aceillrtvy" => ["vertically"],
      "ceehinqstu" => ["techniques"], "eginopssss" => ["possessing"],
      "deemnorstu" => ["tremendous"], "ccceenorru" => ["occurrence"],
      "aadeegnrtu" => ["guaranteed"], "cdefinnotu" => ["functioned"],
      "ginnooprss" => ["sponsoring"], "aeehistuvx" => ["exhaustive"],
      "deegiilnsu" => ["guidelines"], "acghinprsu" => ["purchasing"],
      "aeeinrsstt" => ["reinstates"], "acemmnorty" => ["commentary"],
      "eilnoorstu" => ["resolution"], "ceiinnottx" => ["extinction"],
      "ceeeiprstv" => ["respective"], "adejmnsttu" => ["adjustment"],
      "ceeioprrsv" => ["overprices"], "aaegilntuv" => ["evaluating"],
      "aefgilmnnu" => ["meaningful"], "ceeginprst" => ["respecting"],
      "aabcelmopr" => ["comparable"], "cceginnnor" => ["concerning"],
      "adeeimnrtt" => ["terminated"], "ccnorssttu" => ["constructs"],
      "afgiinssty" => ["satisfying"], "cceeemnopt" => ["competence"],
      "cefginorsu" => ["configures"], "aeiinqsttu" => ["quantities"],
      "aaccinostu" => ["accusation"], "deegiilprv" => ["privileged"],
      "eggginsstu" => ["suggesting"]}
    |> Map.get(string_id)
  end

  def valid_ids do
    ["addeeirstv", "ceennorstu", "aeellntuvy", "aadefrrstw", "eeehlnopst",
     "ceelmmnopt", "aeeilnqtuv", "aacddeinst", "acdiinorst", "eeinnosstx",
     "adinorsstw", "addeeloorv", "aadeelqtuy", "aeeillrtvy", "cdefnnoort",
     "eehmnnnoop", "abelmprsuy", "eimorsstuy", "aeginrsstu", "acdefiilss",
     "deelmnopuy", "bdeeeemmrr", "aabelnorsy", "cdennoopru", "adglnopruy",
     "accdemostu", "deeefmnrru", "aiinossttu", "accginnott", "acdeiilmrs",
     "acddeirstt", "acdeeffntu", "mnnoossuyy", "deefiiinrt", "cefiiilnty",
     "aeimnorrtt", "acdeilmnop", "abeirstttu", "acdiilmopt", "gggilnrstu",
     "eeiinoprtt", "aaillnnoty", "aegiimnstt", "aceimsstty", "acinnorsst",
     "deiimnoprs", "eeilnopsst", "eiinrstuvy", "effginostt", "aceeinrsst",
     "aceilmtuuv", "abbeeeillv", "deefghinrt", "cdffiiltuy", "ccdginnotu",
     "dggiiinssu", "aceemnopst", "addeilmtty", "eeiimprssv", "adeeinprst",
     "aeehmoprst", "ceeeefnrrs", "eekkorssty", "aaceirtttv", "cdeeginopr",
     "ceinnoorsv", "ciopprsstt", "dgiinorstt", "ceginnortv", "acilmorsuu",
     "ceiinnopst", "aijlnorstu", "ainooqsttu", "abefiillln", "beisstttuu",
     "afillmnory", "deeklooorv", "aceiiorstt", "adeimnoort", "eiillmpstu",
     "aehimnsstu", "deeiilmrst", "ceelnorsvy", "acfgiilnry", "cceeilnort",
     "ceefilnnsu", "cinooprrtu", "efgimnoprr", "aaccilprst", "deeinoqstu",
     "cegiinrrtu", "acehilorrt", "ghiloopsyy", "aaceinssst", "ddeeirssst",
     "defhiinprs", "bceeiprrss", "bceeijstuv", "agiimnottv", "aaadgnoppr",
     "cennooprsu", "aabeillnuv", "eginopprss", "cdeinorstu", "bggiinnpru",
     "aeeiimprtv", "aabbeilnot", "aaeeeggrtx", "deeginnprt", "agiillnory",
     "ceennoqstu", "ceiillptxy", "deefiilnty", "abefiloprt", "cegilmnopt",
     "aceginrstt", "diinoprstu", "aadeegnrrr", "abcceeilss", "cceillnoot",
     "cehinoprss", "aeeillsstt", "eefginorrs", "aaciilmpst", "aegimnnsst",
     "deehilmoss", "aeeilnortv", "aabbeelnru", "accinoprsy", "abcgiilloo",
     "eghiiinnrt", "cdeeiirstv", "cceinnoopt", "cdeinrsttu", "abeilnstuu",
     "cdinooprtu", "bghiilnpsu", "aeillrsttu", "deeiprssuv", "chiipsssty",
     "ddeeeimnrt", "abeegilnot", "degilnnruy", "aeiinnotvv", "abcdeeeltt",
     "eeilmmnpst", "eeginprrsv", "aceinorttx", "acginnnnou", "aiiinnottv",
     "aabcehilpt", "efgiinrrty", "abeklnoruw", "deeinoprss", "aacdegimnp",
     "inooopprrt", "ceinooprtt", "cdeeenptux", "eeimnnsstt", "cdegiinprt",
     "ceinostttu", "aaciilnost", "cceflsssuu", "aabbeeirtv", "defiiinnot",
     "cceeisssuv", "aalnorrstt", "agiilmnstu", "ceefinoprt", "aabeelnors",
     "deeeimnrst", "deginnoprs", "acdeiiintv", "aaaceenppr", "aeellnrtxy",
     "aeehorstvw", "ceefhhnort", "aaaghpprrs", "adeeglrrss", "aclrrsttuu",
     "eeehlmsstv", "aacilprrtu", "aadginortu", "bgiimnsttu", "ceeinnnotv",
     "deeiinoptx", "aeeinorstt", "eghinnorst", "aceeegnprt", "adegoorrty",
     "aaaehpprrs", "adefrrsttu", "aacinorttt", "abcdgknoru", "defgiilnrr",
     "ddeeilnnru", "eeeiiprttv", "abceeeltux", "cdeeinorrs", "eiilopstvy",
     "acceeillrt", "aadeeinqtu", "abceefiiln", "aiiilmmnst", "adeelmorty",
     "deeefinrrt", "adeehilprs", "aellnoprsy", "accginnotu", "aabbcdklor",
     "ceghinrstt", "ciiillmpty", "aghilmorst", "abeeeflprr", "adeeelprty",
     "aaeimmnrst", "dggiiimnsu", "abcegiknrt", "aabeeklmrr", "abgiilnoot",
     "acehimmnss", "abceeelrst", "aagillmnry", "cgiimmnott", "eegmnnortv",
     "cddeinortu", "ccdeefiiny", "ceehinnort", "ccdgilnnou", "adeehnnrtu",
     "ahilnoortz", "aeilmnoprs", "eegiilprsv", "ccgiinnnov", "ceinnosstt",
     "acgiilmnps", "aacillnoot", "efinooprss", "abeeiilntv", "bcdeeiilnr",
     "aaelnpprty", "adeeinrstt", "acgillnops", "cefgiinpsy", "egiimnnnot",
     "aiinnorstt", "eiinnnostv", "aacehopprs", "defiiilmps", "cciinnootv",
     "addeeginst", "acddgiinrs", "deiinoopst", "ceegiinprv", "acdeeginrs",
     "eeiilnostv", "aeiilnqtuy", "agiiiinntt", "aceeghllns", "behilprssu",
     "ginnooppst", "eioprrssuv", "acchilmops", "cceeefnnor", "eelnorstuv",
     "ccefiiinst", "cddeeoprru", "cdeeirrstt", "aefrrssttu", "efgginortt",
     "degginnoru", "aeginrrssu", "adiinoppst", "eeenprrsst", "iinoooppst",
     "aaeegnrstu", "deeeinrstt", "aillmnoopy", "aeimnopttt", "deefiiintv",
     "afghiinnos", "abdeilopss", "aeeilrrttu", "aabceillpp", "agiinnsstu",
     "adiiilmrss", "gghiilnnst", "acddegiint", "accefiirss", "accdenortt",
     "achiilorst", "aceegllosu", "acinnorstt", "acceilmmor", "ciiilmpsst",
     "adfinnootu", "cdeeeffinr", "aacgillnot", "aeemnsssst", "adgiiknnpp",
     "aeegginnrt", "cegiinnpst", "cdeemoprss", "ailnoopptu", "cceejnortu",
     "aaeelprsty", "abdeinorsu", "acegghinnx", "aegilnortu", "aiiilmnott",
     "aiinoprstt", "aabloorrty", "aaenrrsttu", "cgilnnostu", "adiilnrstu",
     "accelnoptu", "ceeiinnsst", "ehimnnpstu", "aiinnnootv", "adiorssstu",
     "afgiilnquy", "eeghnnrstt", "aeeghlortt", "aaccellstu", "cdeemmnors",
     "cgiinnnotu", "adeeinrrst", "bdegiilnru", "egiimnprss", "aacfillosu",
     "deiimnnoss", "agiinoorrt", "aefilmnsty", "eefginprrr", "aeeprsswxy",
     "adeeinortt", "ceeginorrv", "beefiillnx", "aaccilnoos", "acehiimrtt",
     "aadhilrtww", "agillnosww", "deeegirrst", "beenqsstuu", "addeginrss",
     "aeinooprst", "aabhiinntt", "adeiimnrst", "aaegillnot", "acdeinoort",
     "aaeinoprst", "ccdeeeenpr", "aeillnnrty", "abdnoortuu", "bdeiirsttu",
     "deeilnnrsu", "deiillmptu", "ceeilmnopt", "einnopsssu", "degghiilnt",
     "aaccllortu", "ceginoprss", "ccegillnot", "ccilnnoosu", "ceiinssstt",
     "egiimnprtt", "eeeimnprtx", "cceeffiiny", "efimnorstu", "aeggginrst",
     "dehiiklloo", "defhiinnsu", "eefghinrrs", "ceiilnpprs", "ceeeimnttx",
     "cegillmnop", "efiiilmpss", "ceginnoost", "aacilnppst", "cddeeginns",
     "cdeginorrs", "ciiloorsst", "afgimnortt", "eilnoortuv", "bcdegiinrs",
     "aciisssttt", "acdeeinrtt", "aaeilmnprt", "ceilmmnopt", "eeginprssx",
     "accegilnno", "abeilmootu", "beghinrsst", "acdgiiinnt", "deeeloprsv",
     "adeginprsu", "efiiilnnty", "aehlmoosux", "ceemoprsss", "ceeeefnprr",
     "adiinorstt", "ccceeinnos", "aeillmnrty", "cdiinosssu", "cdeeioprrv",
     "adeilmsttu", "cdiilorsuu", "aeegiilmtt", "abcenssstu", "agiillnnst",
     "aceegiorst", "acdeiiilst", "aaddeesttv", "eeginnprtv", "adegmmoprr",
     "cdeghilnsu", "aeenpprssw", "aaelnnpstu", "abeeillnru", "giloorsuvy",
     "eeelnrsttw", "acdeegnoru", "cgiiilnstu", "aeeiilmnst", "aacefinsst",
     "aaiinorstv", "beiilmopss", "aeeiillrtt", "aaccdelltu", "cddeemnotu",
     "elmnoorsuy", "acddeilptu", "bcdeeiprrs", "ciimmnooss", "aiimnoottv",
     "aacceeelrt", "aacfiiilrt", "acfilnnotu", "ccgiinnotv", "afhkllntuy",
     "aegimnpttt", "aefnnoorst", "bghiiiinnt", "cdeeeprstu", "adeeeegnrt",
     "aabdginnno", "ceginoprtt", "ghhoorttuu", "acehlorrst", "cdellnoort",
     "acefiiilst", "abghiiinnt", "aemoprsstt", "aeeginostt", "abceilmopt",
     "bcegijnstu", "cgiinnosst", "ddeefiiint", "bddfgiinor", "aceegnorsu",
     "aadeipprss", "adeeirsstv", "aeinoprttu", "abdeefhnor", "aaeegmmnnt",
     "acegiinnrs", "acimnoopss", "aadgginrtu", "anoprrsstt", "adegiimnrs",
     "adeeiirtvv", "eegginrrtt", "eeiprrttwy", "eepprssssu", "adegiinort",
     "abdeeeilrt", "agiiinrrtt", "ddenoorstu", "aefgllrtuy", "aiiinorrtt",
     "adgiilnpsy", "aacehmnttt", "cdeeoprrsu", "achillpsyy", "aiilmnostu",
     "ceegiinrsx", "aaccelrtuy", "egginosstu", "acddennruy", "einprrsttu",
     "aacdginotv", "fghiinorry", "cddeeinors", "defilnnruy", "agiimnnnot",
     "cceginorrt", "cdeiimrsst", "cdefginoru", "deginorsty", "ceefgilnrt",
     "deefiiinst", "cemnnoopst", "aabcdorsst", "bdeeilnorr", "aeillmttuy",
     "ceeggilnnt", "aacdefinst", "ehimnopssy", "aaillnorty", "cehmmnooor",
     "clmooprsuy", "acdknorstu", "giinprrssu", "defghilltu", "ciinnottuy",
     "aeghinstux", "eeeimnrrtt", "accdeimort", "acdgiinost", "ddeeinorrv",
     "cceinnnoot", "adeeginsst", "abgiloorty", "abeeeglstv", "cdenooprrs",
     "aeeelmnrty", "acdeeghlln", "hhilooppsy", "adgiimnnot", "ceinnnootv",
     "cfgiimnnor", "cdeeijprsu", "eeiprsssuv", "aaeginprst", "aeiimnostt",
     "aainorstty", "cdiinnoost", "eilnoopssx", "aginoprrty", "aeinoprssu",
     "aceeillpsy", "egggiinrrt", "aaddiilnot", "ceeeprsstu", "einoopssss",
     "aeinnosttt", "aacdehoppr", "acdiiinnot", "egiinnsstw", "eopprrsstu",
     "acdeilpstu", "aagimnottu", "aacgiinttv", "aimnopsstu", "cdeeeefnrr",
     "aeeilnrrtv", "cdeiimnntt", "abeeflprry", "aeiklmnsty", "eiiimprstv",
     "abdeirtttu", "addeennttu", "aacceinrtu", "adinnopstt", "eeghinrtvy",
     "ccdeeginsu", "bhiiiinnot", "aceilnoort", "aaadinoptt", "abbeilmopr",
     "eelmmnopty", "aaeilnortt", "deegiinnrt", "cegimnoorv", "aceimnoprt",
     "accdinortt", "aacginrttt", "acffiilloy", "aabiilnrvy", "cilmnoopsu",
     "ddeehilmos", "adeeginrtt", "accdefiirs", "ceeiinprst", "aadefgrssu",
     "aaciilpstt", "eehilnnrty", "eeflnsssuu", "dggiinsstu", "eeimnnsttv",
     "beeilssttu", "cdgiinsssu", "eegiinrrtv", "aadeiimnnt", "ceeginnnst",
     "agillnrsuy", "acdeiilnnt", "ceimmooprs", "accehllnor", "cerrssttuu",
     "eeiinrstvw", "aabeeelprt", "aaccceenpt", "ceimmmnott", "ceghlnooty",
     "aaceeipprt", "aaeinopsst", "abghiilnos", "aeilmssttu", "eeflnqrtuy",
     "aabllmnory", "beehimmprs", "addeeiprsw", "abceeilnot", "adeeginott",
     "aegiilnnpx", "deeellnssy", "eeeioprrrt", "adeehiprrs", "aceeehrrrs",
     "eefinnqrtu", "ahiinorsst", "ceeinopstx", "ceellmopty", "ceijnooprt",
     "aeeeknsssw", "cceinosssu", "aaeegnrrrs", "eeinprrstt", "acehilrsty",
     "eeginqrstu", "aacellnosw", "aeginrrstt", "ddenorrsuu", "aeeinnrstt",
     "ceginnnost", "cimmnosstu", "accdeilrtu", "dehnoorrsu", "aaccehrrst",
     "cdeiilnrty", "aaceiossst", "eeinoprssx", "aceeghnorv", "ccegiinnov",
     "eiinopstvw", "eehllopssy", "bcdeorsttu", "aadeiilntv", "addiiilnuv",
     "aclnnosttu", "deeirsssst", "aaefimmnrs", "aeemnssttt", "cceginnnot",
     "deginnpssu", "aeeegmnrst", "eelmnppstu", "aceginrttx", "aaccehilmn",
     "aegoorstuu", "cegijnoprt", "beegilmnrs", "aeiiiinttv", "ceimooprtt",
     "ciiimopstt", "eelorssuvy", "ceilmnoopt", "cdegimnnno", "agiinnoppt",
     "acginnrttu", "cddeeiorsv", "aceeelortt", "ciiopsssuu", "eiinnnostt",
     "abellostuy", "adeeehnrtt", "abegilmnss", "aabcloruvy", "eeinnoprtv",
     "acceilmnoo", "ceginpsstu", "cginoprrtu", "abdiirssuy", "cegginnost",
     "aaabdmorss", "aacdeenntt", "acceilmopt", "adegiilmns", "deegiilnrv",
     "abeirrrsst", "aabcdelnnu", "deeginprss", "aehimpssty", "agilnopptu",
     "abcdeeelrt", "aeeggirssv", "cdiilnstty", "aeeefhrrtt", "cddeeijpru",
     "accinooptu", "aeegirsstt", "eimnnrsttu", "aabcceelpt", "eiimnoprss",
     "eeefinrrst", "ccdefilnot", "bcdeiilnry", "acimnooprs", "cdeehmnopr",
     "degiinorrv", "ceeinopprt", "acdehinssw", "deeeinnrtv", "cceinoorrt",
     "aacccinruy", "eioprstttu", "abeellnruv", "deefiiinnt", "aegilnortt",
     "ccilmrruuu", "bceijnoost", "aacccdenor", "ghhloortuy", "ghhoprttuu",
     "cghloopsyy", "eeginnprst", "aceefinrst", "aadeessttv", "aehoopprst",
     "acinprrstt", "aaccelmtuu", "cdeiiilnps", "deefgiinnr", "defghiloss",
     "egiilnoptx", "eeiopprrst", "aaccnnottu", "gghhhiilst", "eeeinnrstv",
     "abeiilntvy", "dgiiimnsss", "ailopprtuy", "acgiinnnot", "aabdeelnru",
     "aiiilmrsty", "cgiimnoprs", "aegilnprst", "beinorstuu", "eiiioprrst",
     "cciiimrsst", "cdeeeinnst", "cderrsttuu", "ceeeeinprx", "aclnnostty",
     "acdeefinrt", "aefiilqrsu", "aaelnrsstt", "ciiilmpsty", "ceeimmostt",
     "eeeinprrst", "eiiimnorst", "agiorsttuu", "aaceiinptt", "egiknnortw",
     "aeeimnrstt", "abceilnoty", "iinooprssv", "aadiimnort", "aaccdeilnt",
     "aceiiisttv", "aeeilnqstu", "aabcehilrt", "ceefilnort", "ggilnnoopr",
     "aceinoprtu", "aeehilpprr", "eehlmorsvw", "cegimmnnot", "ehhiopssty",
     "acdegiorsu", "bceinorttu", "ccdeinnost", "aabciilpty", "ceilmoptxy",
     "ceooprrsss", "cdeiinorst", "aaeemprrst", "adfginorrw", "acdiinorty",
     "aceiilpsst", "bdgiinrstu", "acdoorrsss", "beeinssssu", "beeggiilln",
     "ceinnnoott", "acceilrstu", "aafiilmnru", "aciiilnopt", "eiloprsuvy",
     "acffiilnou", "aghhoopprt", "cellnoorrt", "bceemmorsu", "aeegnorrst",
     "deiinrsstu", "eeinprsstt", "eeeehrrvwy", "afmnorrsst", "deegoprrss",
     "ceeoprsstu", "cefgiinrty", "deegilnopv", "eeeoprstty", "aaiilnorrt",
     "aillnoopty", "cgiinnortv", "aacefiiltt", "diinoorstt", "cddeinostu",
     "fgiijnstuy", "behiiinotx", "aeeginnort", "acefiilsss", "ginopprstu",
     "accelmnopt", "bdehiioprt", "ffgiilllnu", "aeggiinnsv", "deloppssuy",
     "eiorrrsstt", "accegilloo", "einoopprss", "acilmnopst", "adeeknrstu",
     "acdegirrst", "aaadegnstv", "aeegnprsss", "ceehiloprt", "cdeginnnos",
     "aeenorstux", "adeemnprtt", "acceelnrtu", "aegiinorst", "aaeoprrsst",
     "biimnosssu", "adeenrstuv", "cddeeeennp", "aaeeginrtv", "ccdeefinno",
     "aadelnrstt", "accghinrst", "bgiiloosst", "aeeginrstt", "cdeioprtuv",
     "deepprsssu", "aacdeiosst", "ceffiinstu", "cdeefilnnu", "adeeknnrtu",
     "aacehimprs", "giimnnoort", "aegmmoprrr", "aaeilnotuv", "aaellnpsty",
     "ehhilortww", "cdeiinoprt", "addennrstu", "aemnoorrst", "aeiilrttvy",
     "aabeklmrry", "aaeilmnptu", "cceeillotv", "cdeeoprstu", "eeghilnnst",
     "eegoprrsss", "deeeeginnr", "cinnoostuu", "adeeiilmnt", "aceillrtvy",
     "ceehinqstu", "eginopssss", "deemnorstu", "ccceenorru", "aadeegnrtu",
     "cdefinnotu", "ginnooprss", "aeehistuvx", "deegiilnsu", "acghinprsu",
     "aeeinrsstt", "acemmnorty", "eilnoorstu", "ceiinnottx", "ceeeiprstv",
     "adejmnsttu", "ceeioprrsv", "aaegilntuv", "aefgilmnnu", "ceeginprst",
     "aabcelmopr", "cceginnnor", "adeeimnrtt", "ccnorssttu", "afgiinssty",
     "cceeemnopt", "cefginorsu", "aeiinqsttu", "aaccinostu", "deegiilprv",
     "eggginsstu"]
    |> Enum.into(HashSet.new)
  end
end
