defmodule Jumble.ScowlDict.Size20.Length13 do
  def get(string_id) do
    %{"aaccdimmnooot" => ["accommodation"], "aceeinorsstvv" => ["conservatives"],
      "aaagiilnorttv" => ["gravitational"], "aehilmoostuxy" => ["homosexuality"],
      "eegiinnnrsttu" => ["uninteresting"], "aaiimnoopprtx" => ["approximation"],
      "cceiinnnossty" => ["inconsistency"], "ccdegiinnnost" => ["disconnecting"],
      "adeeeiimnnrtt" => ["indeterminate"], "aadefllmnntuy" => ["fundamentally"],
      "aadeinorrrtxy" => ["extraordinary"], "acfgiiiinnnst" => ["insignificant"],
      "ddeghiiinsstu" => ["distinguished"], "acfgiiilnnsty" => ["significantly"],
      "aacceginnnott" => ["concatenating"], "aiimnnorsssst" => ["transmissions"],
      "cdeennooprrst" => ["correspondent"], "cgiiimmnnooss" => ["commissioning"],
      "acfiiijnosttu" => ["justification"], "accdgiinnortt" => ["contradicting"],
      "aceilnoorrstv" => ["controversial"], "accdiinnoortt" => ["contradiction"],
      "achhiilloopps" => ["philosophical"], "aaccegillorty" => ["categorically"],
      "eeegiimnnprtx" => ["experimenting"], "adeeeffiinrtt" => ["differentiate"],
      "eegiilnnrstty" => ["interestingly"], "aabcillnooort" => ["collaboration"],
      "deghiiinssstu" => ["distinguishes"], "aeilnoorrtuvy" => ["revolutionary"],
      "aaeilmopprtxy" => ["approximately"], "adeeeimnrsttv" => ["advertisement"],
      "aegiiinnosttv" => ["investigation"], "abbceeijlnoot" => ["objectionable"],
      "acceinnooprtt" => ["contraception"], "accghiilmnops" => ["accomplishing"],
      "ceeeeffinsstv" => ["effectiveness"], "aaccfiiilnort" => ["clarification"],
      "adeimnnoorstt" => ["demonstration"], "acceinnnoortt" => ["concentration"],
      "abciiilmoptty" => ["compatibility"], "aaeiloppprrty" => ["appropriately"],
      "cdeginnooprrs" => ["corresponding"], "aaacehiimmntt" => ["mathematician"],
      "aabghiooprtuy" => ["autobiography"], "aaiillnnosstt" => ["installations"],
      "adeeeimnrsttu" => ["underestimate"], "eeeimnprrssst" => ["misrepresents"],
      "aceelmmnoprty" => ["complementary"], "aaacillmottuy" => ["automatically"],
      "accgiimmnnotu" => ["communicating"], "aadiillnortty" => ["traditionally"],
      "accdinoorrtty" => ["contradictory"], "accefiiinopst" => ["specification"],
      "aacefmnrrstuu" => ["manufacturers"], "acciimmnnootu" => ["communication"],
      "cdeeeeiinnprx" => ["inexperienced"], "aceeiilnrttvy" => ["interactively"],
      "aeeiilnoprsst" => ["personalities"], "aceehillortty" => ["theoretically"],
      "aabbeiinorstv" => ["abbreviations"], "aiillnorssttu" => ["illustrations"],
      "ddeeeilnnnpty" => ["independently"], "aceeegmnnortu" => ["encouragement"],
      "adeilmnnoprty" => ["predominantly"], "aaefiimnnostt" => ["manifestation"],
      "acdeggiklnnow" => ["acknowledging"], "adgiiinnoppst" => ["disappointing"],
      "addeimnnrsstu" => ["misunderstand"], "ceehimnnooprs" => ["comprehension"],
      "aceinnoorsstv" => ["conversations"], "eeeghilmnnntt" => ["enlightenment"],
      "acddeiiimnrst" => ["discriminated"], "aacfgimnnrtuu" => ["manufacturing"],
      "adegimnnorstt" => ["demonstrating"], "acceghillnoot" => ["technological"],
      "aciinnnooprtu" => ["pronunciation"], "acdeiinnoorst" => ["consideration"],
      "aacgiiinpprtt" => ["participating"], "beeiilnoprrss" => ["irresponsible"],
      "ceeehimnoprsv" => ["comprehensive"], "acdeimnnoottu" => ["documentation"],
      "aaddeegnrrtuu" => ["undergraduate"], "acehiiopssstt" => ["sophisticates"],
      "aeiillnnnotty" => ["intentionally"], "aefiilnooprrt" => ["proliferation"],
      "adeeilnnrttvy" => ["inadvertently"], "bciinnoorsttu" => ["contributions"],
      "aeeeimnnnrttt" => ["entertainment"], "aefilnooprsss" => ["professionals"],
      "aabeemmnrrsst" => ["embarrassment"], "cghiloopsssty" => ["psychologists"],
      "acfgiinnoortu" => ["configuration"], "aaceilmoprtvy" => ["comparatively"],
      "cdgiiinnnostu" => ["discontinuing"], "aaeeillnrttvy" => ["alternatively"],
      "ddeimnoorsstu" => ["misunderstood"], "accghilloopsy" => ["psychological"],
      "aelnnoopsstuy" => ["spontaneously"], "aeeiinnoqrstu" => ["questionnaire"],
      "acegilmnnoptt" => ["contemplating"], "aeelmnpprstuy" => ["supplementary"],
      "aaceehillstty" => ["aesthetically"], "adeeiimnnortt" => ["determination"],
      "aceeilnnrssuy" => ["unnecessarily"], "aacilmnoopttu" => ["computational"],
      "adegiiimnnrst" => ["administering"], "acceginnnortt" => ["concentrating"],
      "acefiillprsuy" => ["superficially"], "ceeiinnorsstt" => ["intersections"],
      "acgiinnooprrt" => ["incorporating"], "aaccillnsttyy" => ["syntactically"],
      "aeggiiinnsttv" => ["investigating"], "aciinnnoosttu" => ["continuations"],
      "abceflmnoortu" => ["uncomfortable"], "ccinnoorssttu" => ["constructions"],
      "eiinnoprrsttu" => ["interruptions"], "eeiimnprrsstt" => ["misinterprets"],
      "aefghhoorrstu" => ["thoroughfares"], "aaeiilnnnortt" => ["international"],
      "aceeillnoptxy" => ["exceptionally"], "cceeeiinnnnov" => ["inconvenience"],
      "aaaddeginsstv" => ["disadvantages"], "acdehiiopsstt" => ["sophisticated"],
      "aehiilnoprsst" => ["relationships"], "aceeillmnossu" => ["miscellaneous"],
      "aaeiinoppprrt" => ["inappropriate"], "acdfiiimnoost" => ["modifications"],
      "aacfiiilnoqtu" => ["qualification"], "accdiiinorsty" => ["idiosyncratic"],
      "aeeilmnnnortv" => ["environmental"], "beiiiilopssst" => ["possibilities"],
      "aceinnnoorttv" => ["contravention"], "aabillnssttuy" => ["substantially"],
      "abeehilmnsstt" => ["establishment"], "acfiilnnottuy" => ["functionality"],
      "accceimnrsstu" => ["circumstances"], "aceemnnnnostu" => ["announcements"],
      "aeflnnorttuuy" => ["unfortunately"], "cceinnoossssu" => ["consciousness"],
      "acdeiiimnrsst" => ["discriminates"], "aciiillnnrsty" => ["intrinsically"],
      "addeginnnrstu" => ["understanding"], "eiinoopprsttu" => ["opportunities"],
      "abbeiiiloprst" => ["probabilities"], "cceimmooprrtu" => ["microcomputer"],
      "acciilmnoopst" => ["complications"], "abcdeeilnprtu" => ["unpredictable"]}
    |> Map.get(string_id)
  end

  def valid_ids do
    ["aaccdimmnooot", "aceeinorsstvv", "aaagiilnorttv", "aehilmoostuxy",
     "eegiinnnrsttu", "aaiimnoopprtx", "cceiinnnossty", "ccdegiinnnost",
     "adeeeiimnnrtt", "aadefllmnntuy", "aadeinorrrtxy", "acfgiiiinnnst",
     "ddeghiiinsstu", "acfgiiilnnsty", "aacceginnnott", "aiimnnorsssst",
     "cdeennooprrst", "cgiiimmnnooss", "acfiiijnosttu", "accdgiinnortt",
     "aceilnoorrstv", "accdiinnoortt", "achhiilloopps", "aaccegillorty",
     "eeegiimnnprtx", "adeeeffiinrtt", "eegiilnnrstty", "aabcillnooort",
     "deghiiinssstu", "aeilnoorrtuvy", "aaeilmopprtxy", "adeeeimnrsttv",
     "aegiiinnosttv", "abbceeijlnoot", "acceinnooprtt", "accghiilmnops",
     "ceeeeffinsstv", "aaccfiiilnort", "adeimnnoorstt", "acceinnnoortt",
     "abciiilmoptty", "aaeiloppprrty", "cdeginnooprrs", "aaacehiimmntt",
     "aabghiooprtuy", "aaiillnnosstt", "adeeeimnrsttu", "eeeimnprrssst",
     "aceelmmnoprty", "aaacillmottuy", "accgiimmnnotu", "aadiillnortty",
     "accdinoorrtty", "accefiiinopst", "aacefmnrrstuu", "acciimmnnootu",
     "cdeeeeiinnprx", "aceeiilnrttvy", "aeeiilnoprsst", "aceehillortty",
     "aabbeiinorstv", "aiillnorssttu", "ddeeeilnnnpty", "aceeegmnnortu",
     "adeilmnnoprty", "aaefiimnnostt", "acdeggiklnnow", "adgiiinnoppst",
     "addeimnnrsstu", "ceehimnnooprs", "aceinnoorsstv", "eeeghilmnnntt",
     "acddeiiimnrst", "aacfgimnnrtuu", "adegimnnorstt", "acceghillnoot",
     "aciinnnooprtu", "acdeiinnoorst", "aacgiiinpprtt", "beeiilnoprrss",
     "ceeehimnoprsv", "acdeimnnoottu", "aaddeegnrrtuu", "acehiiopssstt",
     "aeiillnnnotty", "aefiilnooprrt", "adeeilnnrttvy", "bciinnoorsttu",
     "aeeeimnnnrttt", "aefilnooprsss", "aabeemmnrrsst", "cghiloopsssty",
     "acfgiinnoortu", "aaceilmoprtvy", "cdgiiinnnostu", "aaeeillnrttvy",
     "ddeimnoorsstu", "accghilloopsy", "aelnnoopsstuy", "aeeiinnoqrstu",
     "acegilmnnoptt", "aeelmnpprstuy", "aaceehillstty", "adeeiimnnortt",
     "aceeilnnrssuy", "aacilmnoopttu", "adegiiimnnrst", "acceginnnortt",
     "acefiillprsuy", "ceeiinnorsstt", "acgiinnooprrt", "aaccillnsttyy",
     "aeggiiinnsttv", "aciinnnoosttu", "abceflmnoortu", "ccinnoorssttu",
     "eiinnoprrsttu", "eeiimnprrsstt", "aefghhoorrstu", "aaeiilnnnortt",
     "aceeillnoptxy", "cceeeiinnnnov", "aaaddeginsstv", "acdehiiopsstt",
     "aehiilnoprsst", "aceeillmnossu", "aaeiinoppprrt", "acdfiiimnoost",
     "aacfiiilnoqtu", "accdiiinorsty", "aeeilmnnnortv", "beiiiilopssst",
     "aceinnnoorttv", "aabillnssttuy", "abeehilmnsstt", "acfiilnnottuy",
     "accceimnrsstu", "aceemnnnnostu", "aeflnnorttuuy", "cceinnoossssu",
     "acdeiiimnrsst", "aciiillnnrsty", "addeginnnrstu", "eiinoopprsttu",
     "abbeiiiloprst", "cceimmooprrtu", "acciilmnoopst", "abcdeeilnprtu"]
    |> Enum.into(HashSet.new)
  end
end
