defmodule Jumble.ScowlDict.Size20.Length12 do
  def get(string_id) do
    %{"aaiillnnostt" => ["installation"], "abciimnnoost" => ["combinations"],
      "cilnnoostuuy" => ["continuously"], "bcinoorrsttu" => ["contributors"],
      "aaccehhiilrr" => ["hierarchical"], "ceelnnoqstuy" => ["consequently"],
      "adeiinorsstt" => ["dissertation"], "abcdeilnorsy" => ["considerably"],
      "accceimnrstu" => ["circumstance"], "aeeinorrsstv" => ["reservations"],
      "acceimmnostu" => ["communicates"], "abeinoorsstv" => ["observations"],
      "cdeiinoprsst" => ["descriptions"], "bdeeefiilnns" => ["indefensible"],
      "ceinnosstttu" => ["constituents"], "aceilnnnootv" => ["conventional"],
      "cceeennoqssu" => ["consequences"], "acehiinssttu" => ["enthusiastic"],
      "adeeffiilnrt" => ["differential"], "aiillnorsttu" => ["illustration"],
      "aginnoprrstt" => ["transporting"],
      "aceinnoorstv" => ["conservation", "conversation"],
      "ccgiinnnnouv" => ["unconvincing"], "abcdeeilnors" => ["considerable"],
      "adeehhlorrss" => ["shareholders"], "cdeeeoprrsss" => ["predecessors"],
      "deefiiilnnty" => ["indefinitely"], "acdeelmnoptt" => ["contemplated"],
      "aeimnrrssttt" => ["transmitters"], "aefghhoorrtu" => ["thoroughfare"],
      "deeelmnopstv" => ["developments"], "eelmmnnoptuy" => ["unemployment"],
      "aabegimnrrss" => ["embarrassing"], "ccelnnorrtuy" => ["concurrently"],
      "ceeeefinnrrt" => ["interference"], "aabeglmmoprr" => ["programmable"],
      "deeeeimnprtx" => ["experimented"], "adeeeiimnrtt" => ["intermediate"],
      "achiillorsty" => ["historically"], "ceilnnosstty" => ["consistently"],
      "eegiiinnrtvw" => ["interviewing"], "aaeegmnnrrst" => ["arrangements"],
      "aegiinorrstt" => ["registration"], "aeilmnosstuu" => ["simultaneous"],
      "aacdeilnorst" => ["declarations"], "aabeelnnorsu" => ["unreasonable"],
      "eiinnoprrttu" => ["interruption"], "eegilnnortuv" => ["volunteering"],
      "acehhiloptty" => ["hypothetical"], "aeiiiilmrsst" => ["similarities"],
      "aiimnnorssst" => ["transmission"], "eiinoprsssuv" => ["supervisions"],
      "acceehirrttu" => ["architecture"], "cdeegimmnnor" => ["recommending"],
      "cddeiinnostu" => ["discontinued"], "aabceiiilpst" => ["capabilities"],
      "aaacdillmrty" => ["dramatically"], "accdehilmops" => ["accomplished"],
      "ccgiilnnnovy" => ["convincingly"], "cdiinnoorttu" => ["introduction"],
      "aaacceinnqtu" => ["acquaintance"], "ceeegiinnprx" => ["experiencing"],
      "ceginnpsstuu" => ["unsuspecting"], "aeeemmnrsstu" => ["measurements"],
      "acegiilnnrsy" => ["increasingly"], "aabbegiinrtv" => ["abbreviating"],
      "acfiimnnoort" => ["confirmation"], "aaeegginnrtu" => ["guaranteeing"],
      "aeeemprrsttu" => ["temperatures"], "acefiiinortv" => ["verification"],
      "bdgiiinrsttu" => ["distributing"], "ciilopsssuuy" => ["suspiciously"],
      "aceefmnoprrs" => ["performances"], "ceeelmnopsst" => ["completeness"],
      "ceeiinnorstt" => ["intersection"], "acdeegklnosw" => ["acknowledges"],
      "aeegiinnnrtt" => ["entertaining"], "cdeeelnptuxy" => ["unexpectedly"],
      "aaciinpprstt" => ["participants"], "aaciinoossst" => ["associations"],
      "aeeinnoprstt" => ["presentation"], "ceffiilnstuy" => ["sufficiently"],
      "abciilnopstu" => ["publications"], "accdeennortt" => ["concentrated"],
      "acdeiiimnrst" => ["discriminate"], "accehilmopss" => ["accomplishes"],
      "addeemnorstt" => ["demonstrated"], "aaddiillnoty" => ["additionally"],
      "aacegiinpprt" => ["appreciating"], "aefilnooprss" => ["professional"],
      "aaccillnoosy" => ["occasionally"], "ceeiinnnnotv" => ["inconvenient"],
      "aceinooprrst" => ["incorporates"], "aaabcehillpt" => ["alphabetical"],
      "aeegiinssttv" => ["investigates"], "aaccceiinrsu" => ["inaccuracies"],
      "aceemnnnnotu" => ["announcement"], "eilmorsstuyy" => ["mysteriously"],
      "aaccillnostu" => ["calculations"], "aaccgimnnopy" => ["accompanying"],
      "achnnoorssuy" => ["asynchronous"], "aaadegnostuv" => ["advantageous"],
      "acghhioopprt" => ["photographic"], "eegghiilnnnt" => ["enlightening"],
      "acilnnoosttu" => ["consultation"], "ceiinnnosstt" => ["inconsistent"],
      "cdeffiiilstu" => ["difficulties"], "ceeeiiprrstv" => ["irrespective"],
      "aaccdeillnty" => ["accidentally"], "aeeeilmnprtx" => ["experimental"],
      "addeeiimnrst" => ["administered"], "acemnooprrty" => ["contemporary"],
      "agiillnrsttu" => ["illustrating"], "iiinnosstttu" => ["institutions"],
      "acdemmmnnost" => ["commandments"], "aacegghilopr" => ["geographical"],
      "cdiiinnosstt" => ["distinctions"], "aciiilmnopst" => ["implications"],
      "bcehiimorsty" => ["biochemistry"], "eeeimnprrsst" => ["misrepresent"],
      "cdiioprttuvy" => ["productivity"], "cdgiiinnnoot" => ["conditioning"],
      "cceinorsttuv" => ["constructive"], "acgiinnnorst" => ["constraining"],
      "aacefmnrrtuu" => ["manufacturer"], "aacillprrtuy" => ["particularly"],
      "ceiinopprrst" => ["prescription"], "aabbeilnnotu" => ["unobtainable"],
      "bdiiinorsttu" => ["distribution"], "bgiinsstttuu" => ["substituting"],
      "aaceiipprstt" => ["participates"], "aacinnorsstt" => ["transactions"],
      "ailnooopprrt" => ["proportional"], "aaccgilmntuu" => ["accumulating"],
      "aaceiinopprt" => ["appreciation"], "aadegiinpprs" => ["disappearing"],
      "aacdeiipprtt" => ["participated"], "abceiilmnopt" => ["incompatible"],
      "eeeginnprrst" => ["representing"], "cceflnsssuuu" => ["unsuccessful"],
      "aaabiiilltvy" => ["availability"], "aciinnnoottu" => ["continuation"],
      "agiimnnrsttt" => ["transmitting"], "aeilmnnrsttu" => ["instrumental"],
      "adeeegimnrst" => ["disagreement"], "eegiilmmnnpt" => ["implementing"],
      "aceeehimnstv" => ["achievements"], "aadeelmnprtt" => ["departmental"],
      "acdeinooprrt" => ["incorporated"], "acceillmnooy" => ["economically"],
      "cddeeeeinnnp" => ["independence"], "aagiilmnnptu" => ["manipulating"],
      "agiiinnoprtt" => ["partitioning"], "acinnnooostt" => ["connotations"],
      "giilnprrssuy" => ["surprisingly"], "acchiiloprty" => ["hypocritical"],
      "ccdeeefiiins" => ["deficiencies"], "acceillmmory" => ["commercially"],
      "aacgiiinnptt" => ["anticipating"], "abbeeeillnuv" => ["unbelievable"],
      "adeegiinsttv" => ["investigated"], "ahillnoortyz" => ["horizontally"],
      "agilorsttuuy" => ["gratuitously"], "aeilnoortuvy" => ["evolutionary"],
      "acdfiiimnoot" => ["modification"], "abdeeeillrty" => ["deliberately"],
      "ccddeeinnost" => ["disconnected"], "acehiiopsstt" => ["sophisticate"],
      "eeimnnnorstv" => ["environments"], "acfiiinnoott" => ["notification"],
      "aeegiillmtty" => ["legitimately"], "cdegiiimnrst" => ["misdirecting"],
      "aaceeilnorrt" => ["recreational"], "eefgiimnnnrt" => ["infringement"],
      "bcgiinnorttu" => ["contributing"], "acceennorstt" => ["concentrates"],
      "aacceennostt" => ["concatenates"], "acddeegklnow" => ["acknowledged"],
      "abeeilnoqstu" => ["questionable"], "aacfiiillrty" => ["artificially"],
      "accgiilmnopt" => ["complicating"], "aaeeggginrtx" => ["exaggerating"],
      "accefgiiinns" => ["significance"], "aaciilnoppst" => ["applications"],
      "ciinnorssttu" => ["instructions"], "acdiiilnprsy" => ["disciplinary"],
      "aeeehlorstux" => ["heterosexual"], "aceeilllnttu" => ["intellectual"],
      "ceeegiillnnt" => ["intelligence"], "ceeilnnnotvy" => ["conveniently"],
      "aaacehilmmtt" => ["mathematical"], "ccinnoorsttu" => ["construction"],
      "accefiillpsy" => ["specifically"], "eeeiipqrrstu" => ["prerequisite"],
      "aaeilnnopstx" => ["explanations"], "cdeinooprrtu" => ["reproduction"],
      "aacfiorsstty" => ["satisfactory"], "ceffiiinnstu" => ["insufficient"],
      "ggghhhiiilnt" => ["highlighting"], "aaiilmnnoptu" => ["manipulation"],
      "aacchioprstt" => ["catastrophic"], "aacgillrrtuu" => ["agricultural"],
      "aaeeilnrsttv" => ["alternatives"], "eeeimnqrrstu" => ["requirements"],
      "aehiilnoprst" => ["relationship"], "eeghilmnorvw" => ["overwhelming"],
      "cdiillorsuuy" => ["ridiculously"], "aceeinorstvv" => ["conservative"],
      "adeemnorsstt" => ["demonstrates"], "cghiloopssty" => ["psychologist"],
      "aacefmnrstuu" => ["manufactures"], "dehlnoorrsuy" => ["horrendously"],
      "eeiiinrsstuv" => ["universities"], "acdeiiinorst" => ["dictionaries"],
      "cdeiimmnooss" => ["commissioned"], "acdefiilnnot" => ["confidential"],
      "ceeginnnortu" => ["encountering"], "acemmnoorstt" => ["commentators"],
      "aaceglnorttu" => ["congratulate"], "afgimnnorrst" => ["transforming"],
      "bciinoprsstu" => ["subscription"], "beelnqsstuuy" => ["subsequently"],
      "cddeemnnotuu" => ["undocumented"], "acdhiioprstt" => ["dictatorship"],
      "abeghiilnsst" => ["establishing"], "ccefllsssuuy" => ["successfully"],
      "cceeffiiinny" => ["inefficiency"], "acdeiillnnty" => ["incidentally"],
      "aceeelmnprst" => ["replacements"], "aaaddeginstv" => ["disadvantage"],
      "deelmnorstuy" => ["tremendously"], "aabcceelnptu" => ["unacceptable"],
      "aeiilnoopttx" => ["exploitation"], "aefginnrrrst" => ["transferring"],
      "eeiinnnorttv" => ["intervention"], "abcceeiilnss" => ["inaccessible"],
      "dginnorrssuu" => ["surroundings"], "acfilnosttuu" => ["fluctuations"],
      "aacfiinosstt" => ["satisfaction"], "addeiinoppst" => ["disappointed"],
      "eegiinnprrtt" => ["interpreting"], "bciinnoorttu" => ["contribution"],
      "cdinoorrttuy" => ["introductory"], "cddeenooprrs" => ["corresponded"],
      "cceinnosttuy" => ["constituency"], "abbeeillnuvy" => ["unbelievably"],
      "acdggiinorsu" => ["discouraging"], "eeeehlnrsstv" => ["nevertheless"],
      "aeimnnoppstt" => ["appointments"], "accddeinortt" => ["contradicted"],
      "ciinnoostttu" => ["constitution"], "acenoprrsttu" => ["counterparts"],
      "aceimnnoopst" => ["compensation"], "ceiinorrsstt" => ["restrictions"],
      "ehhiloopprss" => ["philosophers"], "aaccdeennott" => ["concatenated"],
      "aceelmnopstt" => ["contemplates"], "eeimmnoprstv" => ["improvements"],
      "eeiimnnrtttt" => ["intermittent"], "acciilmnoopt" => ["complication"],
      "addiiillnuvy" => ["individually"], "aegiinnoostt" => ["negotiations"],
      "aceiinnorstt" => ["interactions"], "egiinnprrttu" => ["interrupting"],
      "eeiimnprrstt" => ["misinterpret"], "biinosstttuu" => ["substitution"],
      "aailnnorsstt" => ["translations"], "cceeillnoort" => ["recollection"],
      "acdeiillopry" => ["periodically"], "ddegnnorrsuu" => ["undergrounds"],
      "ceeeilprstvy" => ["respectively"], "aceeinopsttx" => ["expectations"],
      "accdeimmnotu" => ["communicated"], "acdiinnooort" => ["coordination"],
      "ccginnorsttu" => ["constructing"], "cceeeimnnopt" => ["incompetence"],
      "acdeimnnnoot" => ["condemnation"], "cdeiinnosstu" => ["discontinues"],
      "aabbeiinortv" => ["abbreviation"], "ehhiilooppss" => ["philosophies"],
      "aacdefmnrtuu" => ["manufactured"], "ceeinorrrstu" => ["resurrection"],
      "aaciiinnoptt" => ["anticipation"], "aiknoorssttw" => ["workstations"],
      "aaelnprrstuu" => ["supernatural"], "aabcdginorst" => ["broadcasting"]}
    |> Map.get(string_id)
  end

  def valid_ids do
    ["aaiillnnostt", "abciimnnoost", "cilnnoostuuy", "bcinoorrsttu", "aaccehhiilrr",
     "ceelnnoqstuy", "adeiinorsstt", "abcdeilnorsy", "accceimnrstu", "aeeinorrsstv",
     "acceimmnostu", "abeinoorsstv", "cdeiinoprsst", "bdeeefiilnns", "ceinnosstttu",
     "aceilnnnootv", "cceeennoqssu", "acehiinssttu", "adeeffiilnrt", "aiillnorsttu",
     "aginnoprrstt", "aceinnoorstv", "ccgiinnnnouv", "abcdeeilnors", "adeehhlorrss",
     "cdeeeoprrsss", "deefiiilnnty", "acdeelmnoptt", "aeimnrrssttt", "aefghhoorrtu",
     "deeelmnopstv", "eelmmnnoptuy", "aabegimnrrss", "ccelnnorrtuy", "ceeeefinnrrt",
     "aabeglmmoprr", "deeeeimnprtx", "adeeeiimnrtt", "achiillorsty", "ceilnnosstty",
     "eegiiinnrtvw", "aaeegmnnrrst", "aegiinorrstt", "aeilmnosstuu", "aacdeilnorst",
     "aabeelnnorsu", "eiinnoprrttu", "eegilnnortuv", "acehhiloptty", "aeiiiilmrsst",
     "aiimnnorssst", "eiinoprsssuv", "acceehirrttu", "cdeegimmnnor", "cddeiinnostu",
     "aabceiiilpst", "aaacdillmrty", "accdehilmops", "ccgiilnnnovy", "cdiinnoorttu",
     "aaacceinnqtu", "ceeegiinnprx", "ceginnpsstuu", "aeeemmnrsstu", "acegiilnnrsy",
     "aabbegiinrtv", "acfiimnnoort", "aaeegginnrtu", "aeeemprrsttu", "acefiiinortv",
     "bdgiiinrsttu", "ciilopsssuuy", "aceefmnoprrs", "ceeelmnopsst", "ceeiinnorstt",
     "acdeegklnosw", "aeegiinnnrtt", "cdeeelnptuxy", "aaciinpprstt", "aaciinoossst",
     "aeeinnoprstt", "ceffiilnstuy", "abciilnopstu", "accdeennortt", "acdeiiimnrst",
     "accehilmopss", "addeemnorstt", "aaddiillnoty", "aacegiinpprt", "aefilnooprss",
     "aaccillnoosy", "ceeiinnnnotv", "aceinooprrst", "aaabcehillpt", "aeegiinssttv",
     "aaccceiinrsu", "aceemnnnnotu", "eilmorsstuyy", "aaccillnostu", "aaccgimnnopy",
     "achnnoorssuy", "aaadegnostuv", "acghhioopprt", "eegghiilnnnt", "acilnnoosttu",
     "ceiinnnosstt", "cdeffiiilstu", "ceeeiiprrstv", "aaccdeillnty", "aeeeilmnprtx",
     "addeeiimnrst", "acemnooprrty", "agiillnrsttu", "iiinnosstttu", "acdemmmnnost",
     "aacegghilopr", "cdiiinnosstt", "aciiilmnopst", "bcehiimorsty", "eeeimnprrsst",
     "cdiioprttuvy", "cdgiiinnnoot", "cceinorsttuv", "acgiinnnorst", "aacefmnrrtuu",
     "aacillprrtuy", "ceiinopprrst", "aabbeilnnotu", "bdiiinorsttu", "bgiinsstttuu",
     "aaceiipprstt", "aacinnorsstt", "ailnooopprrt", "aaccgilmntuu", "aaceiinopprt",
     "aadegiinpprs", "aacdeiipprtt", "abceiilmnopt", "eeeginnprrst", "cceflnsssuuu",
     "aaabiiilltvy", "aciinnnoottu", "agiimnnrsttt", "aeilmnnrsttu", "adeeegimnrst",
     "eegiilmmnnpt", "aceeehimnstv", "aadeelmnprtt", "acdeinooprrt", "acceillmnooy",
     "cddeeeeinnnp", "aagiilmnnptu", "agiiinnoprtt", "acinnnooostt", "giilnprrssuy",
     "acchiiloprty", "ccdeeefiiins", "acceillmmory", "aacgiiinnptt", "abbeeeillnuv",
     "adeegiinsttv", "ahillnoortyz", "agilorsttuuy", "aeilnoortuvy", "acdfiiimnoot",
     "abdeeeillrty", "ccddeeinnost", "acehiiopsstt", "eeimnnnorstv", "acfiiinnoott",
     "aeegiillmtty", "cdegiiimnrst", "aaceeilnorrt", "eefgiimnnnrt", "bcgiinnorttu",
     "acceennorstt", "aacceennostt", "acddeegklnow", "abeeilnoqstu", "aacfiiillrty",
     "accgiilmnopt", "aaeeggginrtx", "accefgiiinns", "aaciilnoppst", "ciinnorssttu",
     "acdiiilnprsy", "aeeehlorstux", "aceeilllnttu", "ceeegiillnnt", "ceeilnnnotvy",
     "aaacehilmmtt", "ccinnoorsttu", "accefiillpsy", "eeeiipqrrstu", "aaeilnnopstx",
     "cdeinooprrtu", "aacfiorsstty", "ceffiiinnstu", "ggghhhiiilnt", "aaiilmnnoptu",
     "aacchioprstt", "aacgillrrtuu", "aaeeilnrsttv", "eeeimnqrrstu", "aehiilnoprst",
     "eeghilmnorvw", "cdiillorsuuy", "aceeinorstvv", "adeemnorsstt", "cghiloopssty",
     "aacefmnrstuu", "dehlnoorrsuy", "eeiiinrsstuv", "acdeiiinorst", "cdeiimmnooss",
     "acdefiilnnot", "ceeginnnortu", "acemmnoorstt", "aaceglnorttu", "afgimnnorrst",
     "bciinoprsstu", "beelnqsstuuy", "cddeemnnotuu", "acdhiioprstt", "abeghiilnsst",
     "ccefllsssuuy", "cceeffiiinny", "acdeiillnnty", "aceeelmnprst", "aaaddeginstv",
     "deelmnorstuy", "aabcceelnptu", "aeiilnoopttx", "aefginnrrrst", "eeiinnnorttv",
     "abcceeiilnss", "dginnorrssuu", "acfilnosttuu", "aacfiinosstt", "addeiinoppst",
     "eegiinnprrtt", "bciinnoorttu", "cdinoorrttuy", "cddeenooprrs", "cceinnosttuy",
     "abbeeillnuvy", "acdggiinorsu", "eeeehlnrsstv", "aeimnnoppstt", "accddeinortt",
     "ciinnoostttu", "acenoprrsttu", "aceimnnoopst", "ceiinorrsstt", "ehhiloopprss",
     "aaccdeennott", "aceelmnopstt", "eeimmnoprstv", "eeiimnnrtttt", "acciilmnoopt",
     "addiiillnuvy", "aegiinnoostt", "aceiinnorstt", "egiinnprrttu", "eeiimnprrstt",
     "biinosstttuu", "aailnnorsstt", "cceeillnoort", "acdeiillopry", "ddegnnorrsuu",
     "ceeeilprstvy", "aceeinopsttx", "accdeimmnotu", "acdiinnooort", "ccginnorsttu",
     "cceeeimnnopt", "acdeimnnnoot", "cdeiinnosstu", "aabbeiinortv", "ehhiilooppss",
     "aacdefmnrtuu", "ceeinorrrstu", "aaciiinnoptt", "aiknoorssttw", "aaelnprrstuu",
     "aabcdginorst"]
    |> Enum.into(HashSet.new)
  end
end
