defmodule Jumble.ScowlDict.Size20.Length11 do
  def get(string_id) do
    %{"aaacgilmmrt" => ["grammatical"], "abcdeinrstu" => ["disturbance"],
      "eehmnnnoops" => ["phenomenons"], "cceeiilrtty" => ["electricity"],
      "aaabeillnuv" => ["unavailable"], "abeiillmpsu" => ["implausible"],
      "ehhiloopprs" => ["philosopher"], "cefgiilnnnu" => ["influencing"],
      "abgimnosuuu" => ["unambiguous"], "aadeginsttv" => ["devastating"],
      "giillmnptuy" => ["multiplying"], "aacghinoppr" => ["approaching"],
      "eegiinnrstt" => ["interesting"], "abceeelprst" => ["respectable"],
      "ceinooprstu" => ["prosecution"], "eeinoprsssx" => ["expressions"],
      "abefiijlstu" => ["justifiable"], "diiinoopsst" => ["disposition"],
      "ceimooprstt" => ["competitors"], "aceeilnrssy" => ["necessarily"],
      "abciimnnoot" => ["combination"], "accehillnty" => ["technically"],
      "aciillnppry" => ["principally"], "deeelnortuv" => ["volunteered"],
      "aegiinnortt" => ["integration", "orientating"],
      "cdeefiinpsu" => ["unspecified"], "aeggiinnrtt" => ["integrating"],
      "aeeinorrstv" => ["reservation"], "ceiinorrstt" => ["restriction"],
      "befiiilltxy" => ["flexibility"], "degiilnnnru" => ["underlining"],
      "cfggiinnoru" => ["configuring"], "biiilopssty" => ["possibility"],
      "aabdeilnouv" => ["unavoidable"], "degghiilnnt" => ["lightninged"],
      "acegghillnn" => ["challenging"], "eeinoprsttu" => ["pretentious"],
      "abdeehilsst" => ["established"], "cdeiiinsttv" => ["distinctive"],
      "abgiinrtttu" => ["attributing"], "aailnnorstt" => ["translation"],
      "eeggiinrrst" => ["registering"], "acinoooprrt" => ["corporation"],
      "cdeiinnostu" => ["discontinue"], "egginossstu" => ["suggestions"],
      "abceeelmnrs" => ["resemblance"], "bcdeinorttu" => ["contributed"],
      "beissstttuu" => ["substitutes"], "ceeffiilnty" => ["efficiently"],
      "aaccillprty" => ["practically"], "acehimpstty" => ["sympathetic"],
      "ceeeefnprrs" => ["preferences"], "aeeginorrtt" => ["interrogate"],
      "aabiilrrrty" => ["arbitrarily"], "aeiimnnortt" => ["termination"],
      "acdeiillnty" => ["identically"], "aeeilnnoptx" => ["exponential"],
      "abcdgknorsu" => ["backgrounds"], "acfgiilnssy" => ["classifying"],
      "adiinoppsst" => ["disappoints"], "cceeefnnors" => ["conferences"],
      "aceinooprrt" => ["incorporate"], "cdeiilnostu" => ["unsolicited"],
      "aeeghinnrtt" => ["threatening"], "eiinoprssuv" => ["supervision"],
      "ceiimnooptt" => ["competition"], "aeeilntttvy" => ["tentatively"],
      "deeehlmorvw" => ["overwhelmed"], "ccdeennnotu" => ["unconnected"],
      "cdeeginoprs" => ["proceedings"], "cdeeeffinrs" => ["differences"],
      "aabdeemrrss" => ["embarrassed"], "einopprsssu" => ["suppression"],
      "acceilmopst" => ["complicates"], "abeilmoostu" => ["automobiles"],
      "aegiiilmnnt" => ["eliminating"], "aadeeeggrtx" => ["exaggerated"],
      "cceinoorrst" => ["corrections"], "aaddeginort" => ["degradation"],
      "afilmnoortu" => ["formulation"], "aacdeeipprt" => ["appreciated"],
      "aaceilmnotx" => ["exclamation"], "cdenooprrss" => ["corresponds"],
      "eeeimnqrrtu" => ["requirement"], "abeehilssst" => ["establishes"],
      "acenoprrttu" => ["counterpart"], "abiilllnrty" => ["brilliantly"],
      "aabbeeirstv" => ["abbreviates"], "aaceglnrrtu" => ["rectangular"],
      "abiiloprtty" => ["portability"], "aaceimoprtv" => ["comparative"],
      "abbiiloprty" => ["probability"], "aaccelmstuu" => ["accumulates"],
      "eehinrsstyz" => ["synthesizer"], "addennrsstu" => ["understands"],
      "aceeehrrrss" => ["researchers"], "cdegiinnors" => ["considering"],
      "cdeeeeinprx" => ["experienced"], "eioprsstttu" => ["prostitutes"],
      "aceeiinrttv" => ["interactive"], "aabbdeeirtv" => ["abbreviated"],
      "ceeiopprstv" => ["prospective"], "aaccdemmoot" => ["accommodate"],
      "ceeimnrrttu" => ["recruitment"], "inoopprttuy" => ["opportunity"],
      "acgiilmnnop" => ["complaining"], "aaciinpprtt" => ["participant"],
      "adeiinoprtt" => ["partitioned"], "cdeeirsttuv" => ["destructive"],
      "aiilmnosttu" => ["stimulation"], "deeelmnoptv" => ["development"],
      "cegimnoprss" => ["compressing"], "aennoopsstu" => ["spontaneous"],
      "cdegimnnotu" => ["documenting"], "aadefghnrrt" => ["grandfather"],
      "acimnooprss" => ["comparisons"], "abcceilnovy" => ["conceivably"],
      "aaelnoprtxy" => ["explanatory"], "deeeiinrtvw" => ["interviewed"],
      "egiinprssuv" => ["supervising"], "acilnnooost" => ["consolation"],
      "aiiinnoprst" => ["inspiration"], "aaennprrstt" => ["transparent"],
      "deeinprrttu" => ["interrupted"], "aimnopssstu" => ["assumptions"],
      "bcegiinprrs" => ["prescribing"], "aefnnorttuu" => ["unfortunate"],
      "aaceiipprtt" => ["participate"], "acegiinnrtt" => ["interacting"],
      "aciiilmnopt" => ["implication"], "aacdillmnyy" => ["dynamically"],
      "aehiiorsttu" => ["authorities"], "eioprrsssuv" => ["supervisors"],
      "aiilnooprsv" => ["provisional"], "aijlnorsstu" => ["journalists"],
      "abciilnoptu" => ["publication"], "abcceeilnov" => ["conceivable"],
      "aaccinosstu" => ["accusations"], "eginpprsssu" => ["suppressing"],
      "aegiinnoott" => ["negotiation"], "aeeehnprsst" => ["parentheses"],
      "aaccdelmtuu" => ["accumulated"], "beinorsstuu" => ["subroutines"],
      "aegiimnnrtt" => ["terminating"], "adefmnorrst" => ["transformed"],
      "adfinnoostu" => ["foundations"], "aacehimmstt" => ["mathematics"],
      "ailnooppstu" => ["populations"], "efiiinorrty" => ["inferiority"],
      "cceillnoost" => ["collections"], "eeiiinnsstv" => ["insensitive"],
      "aacceennott" => ["concatenate"], "aadeflmnntu" => ["fundamental"],
      "aacefmnrtuu" => ["manufacture"], "acdiiinnost" => ["indications"],
      "adginnosttu" => ["outstanding"], "ceeiimopttv" => ["competitive"],
      "adegiknnrtu" => ["undertaking"], "eefhmorrrtu" => ["furthermore"],
      "aceelmnoptt" => ["contemplate"], "cginrrsttuu" => ["structuring"],
      "acefgiimnnt" => ["magnificent"], "adeeggiinrs" => ["disagreeing"],
      "aeillmnooty" => ["emotionally"], "acellnrttuy" => ["reluctantly"],
      "acdgiinrstt" => ["distracting"], "acceefiirtt" => ["certificate"],
      "cdeeegilnxy" => ["exceedingly"], "ceeeffiintv" => ["ineffective"],
      "dghiiinsstu" => ["distinguish"], "afinorrsttu" => ["frustration"],
      "cdeinorsttu" => ["destruction"], "aaeilmnpstu" => ["manipulates"],
      "adeimnnoort" => ["denominator"], "aagilllnppy" => ["appallingly"],
      "aeiilmnprry" => ["preliminary"], "bcdeiiilrty" => ["credibility"],
      "deeeilmmnpt" => ["implemented"], "ceeimnnoptt" => ["incompetent"],
      "abeinoorstv" => ["observation"], "aacdeiinptt" => ["anticipated"],
      "eeinorssssu" => ["seriousness"], "aacdeehilmx" => ["hexadecimal"],
      "adeeelprsty" => ["desperately"], "aghnoopprry" => ["pornography"],
      "aaeinnrrsvy" => ["anniversary"], "ceimnooprss" => ["compression"],
      "ccinoopssuu" => ["conspicuous"], "bceeilpsstu" => ["susceptible"],
      "aaeimopprtx" => ["approximate"], "acdegiilloo" => ["ideological"],
      "cdegiijnpru" => ["prejudicing"], "aggiiinnort" => ["originating"],
      "aceilnoorrt" => ["correlation"], "ceeefinqrsu" => ["frequencies"],
      "adeggiinnst" => ["designating"], "ceeiirrsttv" => ["restrictive"],
      "cceeinostuv" => ["consecutive"], "eeginpsttty" => ["typesetting"],
      "aaaepprsstu" => ["apparatuses"], "egiinorrtvw" => ["overwriting"],
      "eegmnnorstv" => ["governments"], "adenoprrstt" => ["transported"],
      "adeghmnorrt" => ["grandmother"], "aegiinnorst" => ["resignation"],
      "aagilnnrstt" => ["translating"], "accdeinprsy" => ["discrepancy"],
      "acdemmmnnot" => ["commandment"], "aceeilnoptx" => ["exceptional"],
      "aceghilloot" => ["theological"], "egilmnoorty" => ["terminology"],
      "aaeeeggrstx" => ["exaggerates"], "abeiiillrty" => ["reliability"],
      "ceeeillstvy" => ["selectively"], "abdeeilnrsu" => ["undesirable"],
      "adegiinrstv" => ["advertising"], "cddeeemmnor" => ["recommended"],
      "acinnnooott" => ["connotation"], "eiioprrstuy" => ["superiority"],
      "aeilmmnorty" => ["momentarily"], "denopprstuu" => ["unsupported"],
      "aclnnossttu" => ["consultants"], "aceinoooprt" => ["cooperation"],
      "ceeiimnnrst" => ["reminiscent"], "aeehinprsst" => ["parenthesis"],
      "egginoprrss" => ["progressing"], "cceilnorrty" => ["incorrectly"],
      "beiiilmqruu" => ["equilibrium"], "acddegiorsu" => ["discouraged"],
      "acdegiorssu" => ["discourages"], "giiimnnoprs" => ["imprisoning"],
      "cegiinoprrv" => ["overpricing"], "afiimnnoort" => ["information"],
      "aaceeipprst" => ["appreciates"], "acillnnotuy" => ["continually"],
      "aacfiillnny" => ["financially"], "aaaceenpprs" => ["appearances"],
      "acciilnortu" => ["circulation"], "cimnnoopstu" => ["consumption"],
      "deghiilmnos" => ["demolishing"], "cdegiinorsv" => ["discovering"],
      "aaccdeimnop" => ["accompanied"], "eeelnrssttw" => ["newsletters"],
      "degiinrssst" => ["distressing"], "acefgiinnrt" => ["interfacing"],
      "abcflmoorty" => ["comfortably"], "deegiinnrst" => ["ingredients"],
      "cdeginoprru" => ["reproducing"], "eimnnrssttu" => ["instruments"],
      "acdemnortuy" => ["documentary"], "aaeiimnnotx" => ["examination"],
      "giiinnoopst" => ["positioning"], "abcdeeilprt" => ["predictable"],
      "aacceimnops" => ["accompanies"], "acefiilprsu" => ["superficial"],
      "aeillnoptty" => ["potentially"], "aeiinnoortt" => ["orientation"],
      "aaccgillntu" => ["calculating"], "aaeioppprrt" => ["appropriate"],
      "ddegnnorruu" => ["underground"], "efgghiinnrt" => ["frightening"],
      "ceeeffiltvy" => ["effectively"], "defllnoruwy" => ["wonderfully"],
      "acdgiinosst" => ["diagnostics"], "ciimmnoosss" => ["commissions"],
      "aegilnorstu" => ["regulations"], "egiklnooorv" => ["overlooking"],
      "deefiiinrst" => ["identifiers"], "beeegimmnrr" => ["remembering"],
      "adeiimnrsst" => ["administers"], "aacinnorstt" => ["transaction"],
      "abefiiilsty" => ["feasibility"], "eggiiilnprv" => ["privileging"],
      "efloprssuuu" => ["superfluous"], "iiinnostttu" => ["institution"],
      "ddeeeinnnpt" => ["independent"], "adejmnssttu" => ["adjustments"],
      "aghhoopprst" => ["photographs"], "ceeginprstu" => ["persecuting"],
      "aceehilortt" => ["theoretical"], "cdillorsuuy" => ["ludicrously"],
      "adegilnoorv" => ["overloading"], "aceeelmnprt" => ["replacement"],
      "eeeinprrrtt" => ["interpreter"], "defiiinnost" => ["definitions"],
      "ceeffiiinnt" => ["inefficient"], "aeflnorttuy" => ["fortunately"],
      "cdiiinnostt" => ["distinction"], "ceeeipprstv" => ["perspective"],
      "aeeprssswxy" => ["expressways"], "abiiilsttuy" => ["suitability"],
      "deeffilnrty" => ["differently"], "aciilllopty" => ["politically"],
      "cceinnossty" => ["consistency"], "bcinoorrttu" => ["contributor"],
      "aceehiinnrt" => ["inheritance"], "cdeeiiorrst" => ["directories"],
      "ccilnnoossu" => ["conclusions"], "ceinosstttu" => ["constitutes"],
      "accdgilnory" => ["accordingly"], "aceennrssuy" => ["unnecessary"],
      "eeilmnnotvv" => ["involvement"], "adghiinrtww" => ["withdrawing"],
      "acimnoopttu" => ["computation"], "aeegiinsttv" => ["investigate"],
      "abegiiimstu" => ["ambiguities"], "aeelmprrtuy" => ["prematurely"],
      "adeglnorsuy" => ["dangerously"], "aaegginnrrr" => ["rearranging"],
      "acinnorsstt" => ["constraints"], "aeggiinnott" => ["negotiating"],
      "adeiilmnnos" => ["dimensional"], "acefginorst" => ["forecasting"],
      "ceeillsuvxy" => ["exclusively"], "accgiilnrtu" => ["circulating"],
      "aagiiimnnot" => ["imagination"], "acemmnoortt" => ["commentator"],
      "aaciilnoppt" => ["application"], "aacdillrsty" => ["drastically"],
      "eiiinssttvy" => ["sensitivity"], "deeeinprtux" => ["expenditure"],
      "ccijnnnootu" => ["conjunction"], "aabefhilnos" => ["fashionable"],
      "ceimmmnostt" => ["commitments"], "ccilnoossuy" => ["consciously"],
      "ceeinorrstu" => ["intercourse"], "adeemnprstt" => ["departments"],
      "acfgiiinnst" => ["significant"], "addiiilnsuv" => ["individuals"],
      "aciiilnnnot" => ["inclination"], "ceinnnoostv" => ["conventions"],
      "cceinnnoost" => ["connections"], "eeimmnoprtv" => ["improvement"],
      "defgiiinnty" => ["identifying"], "acceimmnotu" => ["communicate"],
      "adeeinprsst" => ["pedestrians"], "aaciilssttt" => ["statistical"],
      "aeeillnssty" => ["essentially"], "cdeeeoprrss" => ["predecessor"],
      "adenorstuuv" => ["adventurous"], "eeeggiinnnr" => ["engineering"],
      "aegiinnrrst" => ["restraining"], "aaceiinpstt" => ["anticipates"],
      "cccdeeiinno" => ["coincidence"],
      "cdeiinoprst" => ["predictions", "description"],
      "cegiinnoort" => ["recognition"], "aeiilnnnott" => ["intentional"],
      "ceinnoorssv" => ["conversions"], "fgiiilmnpsy" => ["simplifying"],
      "cdeeiiprstv" => ["descriptive"], "aciiilnopst" => ["politicians"],
      "aceefmnoprr" => ["performance"], "abceeilnort" => ["celebration"],
      "cdeiiinnort" => ["indirection"], "cegiinrrstt" => ["restricting"],
      "aiknoorsttw" => ["workstation"], "abceegilnrt" => ["celebrating"],
      "aaceinorrty" => ["reactionary"], "aegimnnssst" => ["assignments"],
      "aacgiinosst" => ["associating"], "accfgiiinrs" => ["sacrificing"],
      "aaeegmnnrrt" => ["arrangement"], "aceeeirrsst" => ["secretaries"],
      "aacggiimnnp" => ["campaigning"], "aadeilmnptu" => ["manipulated"],
      "aceiooprtvv" => ["provocative"], "aceeehmnnnt" => ["enhancement"],
      "aaccillnotu" => ["calculation"], "aaciinoosst" => ["association"],
      "cenoorrstvy" => ["controversy"], "cciinnoostv" => ["convictions"],
      "eiimnoprsss" => ["impressions"], "cddeeiimrst" => ["misdirected"],
      "acclnnostuy" => ["consultancy"], "dginnorrsuu" => ["surrounding"],
      "aegiillnost" => ["legislation"], "abfiijlstuy" => ["justifiably"],
      "bghiiinoprt" => ["prohibiting"], "acdeinnorst" => ["constrained"],
      "abeehorsttu" => ["thereabouts"], "aeeemprrttu" => ["temperature"],
      "aaceeimnnnt" => ["maintenance"], "abefilltuuy" => ["beautifully"],
      "aabccerruuy" => ["bureaucracy"], "cdiinossssu" => ["discussions"],
      "aafiiilmrty" => ["familiarity"], "adeeeinnrtt" => ["entertained"],
      "aeilnoprsty" => ["personality"], "cddeiinnoot" => ["conditioned"],
      "aaenrrssttu" => ["restaurants"], "ceginoprstu" => ["prosecuting"],
      "adeefnrrrst" => ["transferred"], "cgillnnoort" => ["controlling"],
      "acfilmnnotu" => ["malfunction"], "aeilmoprrty" => ["temporarily"],
      "aacdeilnotu" => ["educational"], "acdeinoorst" => ["coordinates"],
      "deeeghilnnt" => ["enlightened"], "bdeisstttuu" => ["substituted"],
      "aaegiiimntv" => ["imaginative"], "aaeilnorstt" => ["alterations"],
      "degghhhiilt" => ["highlighted"], "ccdeinnosst" => ["disconnects"],
      "aabeemrrsss" => ["embarrasses"], "aaddeeipprs" => ["disappeared"],
      "eegiillnntt" => ["intelligent"], "aceinnrttuy" => ["uncertainty"],
      "eeinorrttvw" => ["overwritten"], "cceeeinnnov" => ["convenience"],
      "aefiillnntu" => ["influential"], "ceinnoosttu" => ["contentious"],
      "ccceenorrsu" => ["occurrences"], "aceegillnty" => ["genetically"],
      "acehimoprst" => ["atmospheric"], "aacfgiinnst" => ["fascinating"],
      "bddeiirsttu" => ["distributed"], "aacillnoost" => ["allocations"],
      "eeimnnnortv" => ["environment"], "cceeennoqsu" => ["consequence"],
      "aimnnoprttu" => ["unimportant"], "acdeeinorst" => ["considerate"],
      "bddelnotuuy" => ["undoubtedly"], "acdgiilnptu" => ["duplicating"],
      "aceeilnnort" => ["intolerance"], "aemnoorrsst" => ["astronomers"],
      "ceeeilssvxy" => ["excessively"], "aeeemmnrstu" => ["measurement"],
      "cfgiinnnotu" => ["functioning"], "aciilmnoopt" => ["compilation"],
      "beeilnoprss" => ["responsible"], "eefgiinnrrt" => ["interfering"],
      "aacciilmprt" => ["impractical"], "eeeimnprstx" => ["experiments"],
      "adeillrsttu" => ["illustrated"], "cginnnoopru" => ["pronouncing"],
      "aeeilmnnstt" => ["sentimental"], "cfghimnoort" => ["forthcoming"],
      "aeeilnqstuv" => ["equivalents"], "aabcceilprt" => ["practicable"],
      "agiilmnsttu" => ["stimulating"], "cfginnnoort" => ["confronting"],
      "cdeinorstuy" => ["countryside"], "aiiilmnostt" => ["limitations"],
      "aillnortuvy" => ["voluntarily"], "adeehhlorrs" => ["shareholder"],
      "acdiilnoptu" => ["duplication"], "aggimmnoprr" => ["programming"],
      "bcginorsttu" => ["obstructing"], "aceiilnrstu" => ["unrealistic"],
      "deeeinprrtt" => ["interpreted"], "aceinoprstu" => ["precautions"],
      "aaccnnosttu" => ["accountants"], "aaeilnooprt" => ["operational"],
      "aceilnopstu" => ["speculation"], "aeegilmnnss" => ["meaningless"],
      "accdinorstt" => ["contradicts"], "ceeefginnrr" => ["referencing"],
      "accginnortt" => ["contracting"], "bceinorsttu" => ["contributes"],
      "ailmnoprtty" => ["importantly"], "aeekmprrstu" => ["supermarket"],
      "adeeiilmmty" => ["immediately"], "aabilnssttu" => ["substantial"],
      "cgiinnrsttu" => ["instructing"], "aeelmnnprty" => ["permanently"],
      "acceennortt" => ["concentrate"], "iinooopprst" => ["proposition"],
      "aceilnnnott" => ["continental"], "abeeeeflors" => ["foreseeable"],
      "eeeoprsstty" => ["stereotypes"], "ciimnooopst" => ["composition"],
      "ceinnostttu" => ["constituent"], "aeiopprrrty" => ["proprietary"],
      "aefiimnortv" => ["informative"], "beeiilmprss" => ["permissible"],
      "cdgiinnortu" => ["introducing"], "cceeilnorst" => ["electronics"],
      "ccinnoossuu" => ["unconscious"], "aeeginnorst" => ["generations"],
      "deeeenprrst" => ["represented"], "egiinnoqstu" => ["questioning"],
      "aaeinopprrt" => ["preparation"], "aaeeilnrttv" => ["alternative"],
      "aegiinnrstt" => ["reinstating"], "aagiiimnnnt" => ["maintaining"],
      "aceeinopttx" => ["expectation"], "adefilssttu" => ["distasteful"],
      "eegiinnnrtv" => ["intervening"], "abceflmoort" => ["comfortable"],
      "aaciinnnort" => ["incarnation"], "afginrrsttu" => ["frustrating"],
      "aeehilpprrs" => ["peripherals"], "aaeilnnoptx" => ["explanation"],
      "cellnoorrst" => ["controllers"], "aciiinoqstu" => ["acquisition"],
      "aabhiinnstt" => ["inhabitants"], "cdeeiiorssv" => ["discoveries"],
      "aaegillnost" => ["allegations"], "accgimnostu" => ["accustoming"],
      "accdeilmopt" => ["complicated"], "bdeiirssttu" => ["distributes"],
      "aeillrssttu" => ["illustrates"], "adeiinnostt" => ["destination"],
      "ceiimmnostu" => ["communities"], "aaccelprstu" => ["spectacular"],
      "ccdenorsttu" => ["constructed"], "cdeeennortu" => ["encountered"],
      "inooopprrst" => ["proportions"], "deegiimnnrt" => ["determining"],
      "aabcinorstt" => ["abstraction"], "acegginnoru" => ["encouraging"],
      "acfilnottuu" => ["fluctuation"], "aceiinnortt" => ["interaction"],
      "aadiilnortt" => ["traditional"], "adeemnorstt" => ["demonstrate"],
      "defiijnstuu" => ["unjustified"], "aceeehimntv" => ["achievement"],
      "aeimnnopptt" => ["appointment"], "adeeilnnpux" => ["unexplained"],
      "aeilnooprtx" => ["exploration"], "acdeegklnow" => ["acknowledge"],
      "ciinnorsttu" => ["instruction"], "eeehlnnosst" => ["nonetheless"],
      "acinnopttuu" => ["punctuation"], "eeeilnstvxy" => ["extensively"],
      "adeimnrsttt" => ["transmitted"], "abeeglrrtty" => ["regrettably"],
      "aeillnrsuvy" => ["universally"], "ceeeeinprsx" => ["experiences"],
      "acdiilnnoot" => ["conditional"], "aegmmoprrrs" => ["programmers"],
      "aeimnrrsttt" => ["transmitter"], "ccfgiilnnot" => ["conflicting"],
      "aacdeilnort" => ["declaration"]}
    |> Map.get(string_id)
  end

  def valid_ids do
    ["aaacgilmmrt", "abcdeinrstu", "eehmnnnoops", "cceeiilrtty", "aaabeillnuv",
     "abeiillmpsu", "ehhiloopprs", "cefgiilnnnu", "abgimnosuuu", "aadeginsttv",
     "giillmnptuy", "aacghinoppr", "eegiinnrstt", "abceeelprst", "ceinooprstu",
     "eeinoprsssx", "abefiijlstu", "diiinoopsst", "ceimooprstt", "aceeilnrssy",
     "abciimnnoot", "accehillnty", "aciillnppry", "deeelnortuv", "aegiinnortt",
     "cdeefiinpsu", "aeggiinnrtt", "aeeinorrstv", "ceiinorrstt", "befiiilltxy",
     "degiilnnnru", "cfggiinnoru", "biiilopssty", "aabdeilnouv", "degghiilnnt",
     "acegghillnn", "eeinoprsttu", "abdeehilsst", "cdeiiinsttv", "abgiinrtttu",
     "aailnnorstt", "eeggiinrrst", "acinoooprrt", "cdeiinnostu", "egginossstu",
     "abceeelmnrs", "bcdeinorttu", "beissstttuu", "ceeffiilnty", "aaccillprty",
     "acehimpstty", "ceeeefnprrs", "aeeginorrtt", "aabiilrrrty", "aeiimnnortt",
     "acdeiillnty", "aeeilnnoptx", "abcdgknorsu", "acfgiilnssy", "adiinoppsst",
     "cceeefnnors", "aceinooprrt", "cdeiilnostu", "aeeghinnrtt", "eiinoprssuv",
     "ceiimnooptt", "aeeilntttvy", "deeehlmorvw", "ccdeennnotu", "cdeeginoprs",
     "cdeeeffinrs", "aabdeemrrss", "einopprsssu", "acceilmopst", "abeilmoostu",
     "aegiiilmnnt", "aadeeeggrtx", "cceinoorrst", "aaddeginort", "afilmnoortu",
     "aacdeeipprt", "aaceilmnotx", "cdenooprrss", "eeeimnqrrtu", "abeehilssst",
     "acenoprrttu", "abiilllnrty", "aabbeeirstv", "aaceglnrrtu", "abiiloprtty",
     "aaceimoprtv", "abbiiloprty", "aaccelmstuu", "eehinrsstyz", "addennrsstu",
     "aceeehrrrss", "cdegiinnors", "cdeeeeinprx", "eioprsstttu", "aceeiinrttv",
     "aabbdeeirtv", "ceeiopprstv", "aaccdemmoot", "ceeimnrrttu", "inoopprttuy",
     "acgiilmnnop", "aaciinpprtt", "adeiinoprtt", "cdeeirsttuv", "aiilmnosttu",
     "deeelmnoptv", "cegimnoprss", "aennoopsstu", "cdegimnnotu", "aadefghnrrt",
     "acimnooprss", "abcceilnovy", "aaelnoprtxy", "deeeiinrtvw", "egiinprssuv",
     "acilnnooost", "aiiinnoprst", "aaennprrstt", "deeinprrttu", "aimnopssstu",
     "bcegiinprrs", "aefnnorttuu", "aaceiipprtt", "acegiinnrtt", "aciiilmnopt",
     "aacdillmnyy", "aehiiorsttu", "eioprrsssuv", "aiilnooprsv", "aijlnorsstu",
     "abciilnoptu", "abcceeilnov", "aaccinosstu", "eginpprsssu", "aegiinnoott",
     "aeeehnprsst", "aaccdelmtuu", "beinorsstuu", "aegiimnnrtt", "adefmnorrst",
     "adfinnoostu", "aacehimmstt", "ailnooppstu", "efiiinorrty", "cceillnoost",
     "eeiiinnsstv", "aacceennott", "aadeflmnntu", "aacefmnrtuu", "acdiiinnost",
     "adginnosttu", "ceeiimopttv", "adegiknnrtu", "eefhmorrrtu", "aceelmnoptt",
     "cginrrsttuu", "acefgiimnnt", "adeeggiinrs", "aeillmnooty", "acellnrttuy",
     "acdgiinrstt", "acceefiirtt", "cdeeegilnxy", "ceeeffiintv", "dghiiinsstu",
     "afinorrsttu", "cdeinorsttu", "aaeilmnpstu", "adeimnnoort", "aagilllnppy",
     "aeiilmnprry", "bcdeiiilrty", "deeeilmmnpt", "ceeimnnoptt", "abeinoorstv",
     "aacdeiinptt", "eeinorssssu", "aacdeehilmx", "adeeelprsty", "aghnoopprry",
     "aaeinnrrsvy", "ceimnooprss", "ccinoopssuu", "bceeilpsstu", "aaeimopprtx",
     "acdegiilloo", "cdegiijnpru", "aggiiinnort", "aceilnoorrt", "ceeefinqrsu",
     "adeggiinnst", "ceeiirrsttv", "cceeinostuv", "eeginpsttty", "aaaepprsstu",
     "egiinorrtvw", "eegmnnorstv", "adenoprrstt", "adeghmnorrt", "aegiinnorst",
     "aagilnnrstt", "accdeinprsy", "acdemmmnnot", "aceeilnoptx", "aceghilloot",
     "egilmnoorty", "aaeeeggrstx", "abeiiillrty", "ceeeillstvy", "abdeeilnrsu",
     "adegiinrstv", "cddeeemmnor", "acinnnooott", "eiioprrstuy", "aeilmmnorty",
     "denopprstuu", "aclnnossttu", "aceinoooprt", "ceeiimnnrst", "aeehinprsst",
     "egginoprrss", "cceilnorrty", "beiiilmqruu", "acddegiorsu", "acdegiorssu",
     "giiimnnoprs", "cegiinoprrv", "afiimnnoort", "aaceeipprst", "acillnnotuy",
     "aacfiillnny", "aaaceenpprs", "acciilnortu", "cimnnoopstu", "deghiilmnos",
     "cdegiinorsv", "aaccdeimnop", "eeelnrssttw", "degiinrssst", "acefgiinnrt",
     "abcflmoorty", "deegiinnrst", "cdeginoprru", "eimnnrssttu", "acdemnortuy",
     "aaeiimnnotx", "giiinnoopst", "abcdeeilprt", "aacceimnops", "acefiilprsu",
     "aeillnoptty", "aeiinnoortt", "aaccgillntu", "aaeioppprrt", "ddegnnorruu",
     "efgghiinnrt", "ceeeffiltvy", "defllnoruwy", "acdgiinosst", "ciimmnoosss",
     "aegilnorstu", "egiklnooorv", "deefiiinrst", "beeegimmnrr", "adeiimnrsst",
     "aacinnorstt", "abefiiilsty", "eggiiilnprv", "efloprssuuu", "iiinnostttu",
     "ddeeeinnnpt", "adejmnssttu", "aghhoopprst", "ceeginprstu", "aceehilortt",
     "cdillorsuuy", "adegilnoorv", "aceeelmnprt", "eeeinprrrtt", "defiiinnost",
     "ceeffiiinnt", "aeflnorttuy", "cdiiinnostt", "ceeeipprstv", "aeeprssswxy",
     "abiiilsttuy", "deeffilnrty", "aciilllopty", "cceinnossty", "bcinoorrttu",
     "aceehiinnrt", "cdeeiiorrst", "ccilnnoossu", "ceinosstttu", "accdgilnory",
     "aceennrssuy", "eeilmnnotvv", "adghiinrtww", "acimnoopttu", "aeegiinsttv",
     "abegiiimstu", "aeelmprrtuy", "adeglnorsuy", "aaegginnrrr", "acinnorsstt",
     "aeggiinnott", "adeiilmnnos", "acefginorst", "ceeillsuvxy", "accgiilnrtu",
     "aagiiimnnot", "acemmnoortt", "aaciilnoppt", "aacdillrsty", "eiiinssttvy",
     "deeeinprtux", "ccijnnnootu", "aabefhilnos", "ceimmmnostt", "ccilnoossuy",
     "ceeinorrstu", "adeemnprstt", "acfgiiinnst", "addiiilnsuv", "aciiilnnnot",
     "ceinnnoostv", "cceinnnoost", "eeimmnoprtv", "defgiiinnty", "acceimmnotu",
     "adeeinprsst", "aaciilssttt", "aeeillnssty", "cdeeeoprrss", "adenorstuuv",
     "eeeggiinnnr", "aegiinnrrst", "aaceiinpstt", "cccdeeiinno", "cdeiinoprst",
     "cegiinnoort", "aeiilnnnott", "ceinnoorssv", "fgiiilmnpsy", "cdeeiiprstv",
     "aciiilnopst", "aceefmnoprr", "abceeilnort", "cdeiiinnort", "cegiinrrstt",
     "aiknoorsttw", "abceegilnrt", "aaceinorrty", "aegimnnssst", "aacgiinosst",
     "accfgiiinrs", "aaeegmnnrrt", "aceeeirrsst", "aacggiimnnp", "aadeilmnptu",
     "aceiooprtvv", "aceeehmnnnt", "aaccillnotu", "aaciinoosst", "cenoorrstvy",
     "cciinnoostv", "eiimnoprsss", "cddeeiimrst", "acclnnostuy", "dginnorrsuu",
     "aegiillnost", "abfiijlstuy", "bghiiinoprt", "acdeinnorst", "abeehorsttu",
     "aeeemprrttu", "aaceeimnnnt", "abefilltuuy", "aabccerruuy", "cdiinossssu",
     "aafiiilmrty", "adeeeinnrtt", "aeilnoprsty", "cddeiinnoot", "aaenrrssttu",
     "ceginoprstu", "adeefnrrrst", "cgillnnoort", "acfilmnnotu", "aeilmoprrty",
     "aacdeilnotu", "acdeinoorst", "deeeghilnnt", "bdeisstttuu", "aaegiiimntv",
     "aaeilnorstt", "degghhhiilt", "ccdeinnosst", "aabeemrrsss", "aaddeeipprs",
     "eegiillnntt", "aceinnrttuy", "eeinorrttvw", "cceeeinnnov", "aefiillnntu",
     "ceinnoosttu", "ccceenorrsu", "aceegillnty", "acehimoprst", "aacfgiinnst",
     "bddeiirsttu", "aacillnoost", "eeimnnnortv", "cceeennoqsu", "aimnnoprttu",
     "acdeeinorst", "bddelnotuuy", "acdgiilnptu", "aceeilnnort", "aemnoorrsst",
     "ceeeilssvxy", "aeeemmnrstu", "cfgiinnnotu", "aciilmnoopt", "beeilnoprss",
     "eefgiinnrrt", "aacciilmprt", "eeeimnprstx", "adeillrsttu", "cginnnoopru",
     "aeeilmnnstt", "cfghimnoort", "aeeilnqstuv", "aabcceilprt", "agiilmnsttu",
     "cfginnnoort", "cdeinorstuy", "aiiilmnostt", "aillnortuvy", "adeehhlorrs",
     "acdiilnoptu", "aggimmnoprr", "bcginorsttu", "aceiilnrstu", "deeeinprrtt",
     "aceinoprstu", "aaccnnosttu", "aaeilnooprt", "aceilnopstu", "aeegilmnnss",
     "accdinorstt", "ceeefginnrr", "accginnortt", "bceinorsttu", "ailmnoprtty",
     "aeekmprrstu", "adeeiilmmty", "aabilnssttu", "cgiinnrsttu", "aeelmnnprty",
     "acceennortt", "iinooopprst", "aceilnnnott", "abeeeeflors", "eeeoprsstty",
     "ciimnooopst", "ceinnostttu", "aeiopprrrty", "aefiimnortv", "beeiilmprss",
     "cdgiinnortu", "cceeilnorst", "ccinnoossuu", "aeeginnorst", "deeeenprrst",
     "egiinnoqstu", "aaeinopprrt", "aaeeilnrttv", "aegiinnrstt", "aagiiimnnnt",
     "aceeinopttx", "adefilssttu", "eegiinnnrtv", "abceflmoort", "aaciinnnort",
     "afginrrsttu", "aeehilpprrs", "aaeilnnoptx", "cellnoorrst", "aciiinoqstu",
     "aabhiinnstt", "cdeeiiorssv", "aaegillnost", "accgimnostu", "accdeilmopt",
     "bdeiirssttu", "aeillrssttu", "adeiinnostt", "ceiimmnostu", "aaccelprstu",
     "ccdenorsttu", "cdeeennortu", "inooopprrst", "deegiimnnrt", "aabcinorstt",
     "acegginnoru", "acfilnottuu", "aceiinnortt", "aadiilnortt", "adeemnorstt",
     "defiijnstuu", "aceeehimntv", "aeimnnopptt", "adeeilnnpux", "aeilnooprtx",
     "acdeegklnow", "ciinnorsttu", "eeehlnnosst", "acinnopttuu", "eeeilnstvxy",
     "adeimnrsttt", "abeeglrrtty", "aeillnrsuvy", "ceeeeinprsx", "acdiilnnoot",
     "aegmmoprrrs", "aeimnrrsttt", "ccfgiilnnot", "aacdeilnort"]
    |> Enum.into(HashSet.new)
  end
end
