defmodule Jumble.ScowlDict.Size20.Length5 do
  def get(string_id) do
    %{"ademn" => ["amend", "named"], "aeopr" => ["opera"], "acnor" => ["acorn"],
      "enrty" => ["entry"], "aadrr" => ["radar"], "first" => ["first"],
      "eoprw" => ["power"], "elmno" => ["lemon"], "ittwy" => ["witty"],
      "aelqu" => ["equal"], "agnoy" => ["agony"], "bclsu" => ["clubs"],
      "enpst" => ["spent"], "adilv" => ["valid"], "ehntt" => ["tenth"],
      "afint" => ["faint"], "eenrt" => ["enter"], "eimpr" => ["prime"],
      "inrsu" => ["ruins"], "afiry" => ["fairy"], "aipzz" => ["pizza"],
      "hnstu" => ["hunts"], "adhny" => ["handy"], "aflls" => ["falls"],
      "alrru" => ["rural"], "dehss" => ["sheds"], "alnps" => ["plans"],
      "aprty" => ["party"], "ellps" => ["spell"], "eistu" => ["suite"],
      "acehp" => ["cheap"], "aeksw" => ["wakes"], "adgmo" => ["dogma"],
      "ejnoy" => ["enjoy"], "aelms" => ["males", "meals"], "gnouy" => ["young"],
      "cehss" => ["chess"], "aghpr" => ["graph"], "ackls" => ["lacks"],
      "cehst" => ["chest"], "deefr" => ["freed"], "aeegr" => ["eager", "agree"],
      "addew" => ["waded"], "empty" => ["empty"], "ejkos" => ["jokes"],
      "agint" => ["giant"], "denot" => ["noted"], "adirs" => ["raids"],
      "ehllo" => ["hello"], "elors" => ["roles"], "eessx" => ["sexes"],
      "egpru" => ["purge"], "acdey" => ["decay"], "dehpt" => ["depth"],
      "efmsu" => ["fumes"], "acdef" => ["faced"], "afluw" => ["awful"],
      "chhiw" => ["which"], "acden" => ["dance"], "doors" => ["doors"],
      "achin" => ["chain"], "abelm" => ["blame"], "eppru" => ["upper"],
      "aksst" => ["tasks"], "celru" => ["cruel"], "emosu" => ["mouse"],
      "arsty" => ["stray"], "hsstu" => ["shuts"], "agnry" => ["angry"],
      "moort" => ["motor"], "eimsx" => ["mixes"], "agrss" => ["grass"],
      "deinx" => ["index"], "agnor" => ["groan", "organ"], "adfrt" => ["draft"],
      "aaenr" => ["arena"], "eprss" => ["press"], "cikks" => ["kicks"],
      "inopt" => ["point"], "acort" => ["actor"], "abdir" => ["rabid"],
      "elorw" => ["lower"], "dorsw" => ["sword", "words"], "achps" => ["chaps"],
      "kloos" => ["looks"], "deikl" => ["liked"], "elpst" => ["slept"],
      "aeelv" => ["leave"], "ehlow" => ["whole"], "aadeh" => ["ahead"],
      "gilny" => ["lying"], "abess" => ["bases"], "adesw" => ["wades"],
      "denst" => ["tends"], "cloos" => ["cools"], "agprs" => ["grasp"],
      "ccikl" => ["click"], "esstt" => ["tests"], "ehilw" => ["while"],
      "elrru" => ["ruler"], "amnow" => ["woman"], "bchnu" => ["bunch"],
      "defil" => ["field", "filed", "flied"], "orsty" => ["story"],
      "chkos" => ["shock"], "ehins" => ["shine"], "innoo" => ["onion"],
      "cikns" => ["nicks"], "aelmr" => ["realm"], "emosv" => ["moves"],
      "cikst" => ["stick"], "aekmr" => ["maker"], "abelt" => ["table"],
      "ioprr" => ["prior"], "amost" => ["atoms"], "orstu" => ["routs"],
      "ailnp" => ["plain"], "aabln" => ["banal"], "elost" => ["stole"],
      "chikt" => ["thick"], "hipss" => ["ships"], "celnu" => ["uncle"],
      "ckost" => ["stock"], "epsst" => ["steps"], "aeikl" => ["alike"],
      "abdly" => ["badly"], "aistw" => ["waits"], "aessy" => ["essay"],
      "iqstu" => ["quits"], "ghotu" => ["tough", "ought"],
      "eiqtu" => ["quiet", "quite"], "afils" => ["fails"], "aimns" => ["mains"],
      "eelps" => ["sleep"], "ehosw" => ["whose"], "densv" => ["vends"],
      "eirsw" => ["wires", "wiser"], "eefls" => ["feels"], "deorv" => ["drove"],
      "addei" => ["aided"], "cehit" => ["ethic"], "adiov" => ["avoid"],
      "ersst" => ["rests"], "adlns" => ["lands"], "besty" => ["bytes"],
      "foops" => ["spoof"], "abegn" => ["began"], "aelpp" => ["apple"],
      "mmmuy" => ["mummy"], "egisv" => ["gives"], "eipqu" => ["equip"],
      "eeilt" => ["elite"], "ejlly" => ["jelly"], "adgru" => ["guard"],
      "adert" => ["rated", "trade", "tread"], "fnost" => ["fonts"],
      "acllo" => ["local"], "elpry" => ["reply"], "acehl" => ["leach"],
      "acsst" => ["casts"], "egstu" => ["guest"], "efins" => ["fines"],
      "inosy" => ["noisy"], "enrsu" => ["nurse"], "aginr" => ["grain"],
      "aerrr" => ["rarer"], "iklls" => ["kills", "skill"], "ehops" => ["hopes"],
      "aepsu" => ["pause"], "deisz" => ["sized"], "ceefn" => ["fence"],
      "npstu" => ["punts"], "depty" => ["typed"], "coprs" => ["crops"],
      "fhist" => ["shift"], "dfirt" => ["drift"], "denos" => ["nodes"],
      "orttu" => ["tutor"], "dgiit" => ["digit"], "nsttu" => ["stunt"],
      "eptty" => ["petty"], "aehlv" => ["halve"], "aelsv" => ["slave"],
      "ehirs" => ["hires"], "knnow" => ["known"], "dopru" => ["proud"],
      "ginsu" => ["suing", "using"], "ceins" => ["since"], "ahiry" => ["hairy"],
      "dgrsu" => ["drugs"], "einos" => ["noise"], "ckluy" => ["lucky"],
      "corss" => ["cross"], "ilpss" => ["slips"], "ampst" => ["stamp"],
      "degju" => ["judge"], "dginy" => ["dying"], "abeov" => ["above"],
      "bcehn" => ["bench"], "ckmsu" => ["mucks"], "abotu" => ["about"],
      "efltu" => ["flute"], "abdns" => ["bands"], "eikls" => ["likes"],
      "aertx" => ["extra"], "ehnoy" => ["honey"], "ehrtw" => ["threw"],
      "aerwy" => ["weary"], "demns" => ["mends"], "ccely" => ["cycle"],
      "dmoos" => ["dooms"], "ainop" => ["piano"], "denow" => ["owned"],
      "aesst" => ["asset", "seats"], "elnwy" => ["newly"], "delns" => ["lends"],
      "allst" => ["stall"], "agins" => ["gains"], "ddeiv" => ["dived"],
      "aprsw" => ["warps", "wraps"], "deins" => ["dines"],
      "ceops" => ["copes", "scope"], "alors" => ["solar"], "bekor" => ["broke"],
      "lopst" => ["plots"], "acfrs" => ["scarf"], "cinos" => ["coins", "icons"],
      "aefrt" => ["after"], "imost" => ["omits"], "hiknt" => ["think"],
      "cersu" => ["cures", "curse"], "ddeir" => ["dried"], "inptu" => ["input"],
      "alnos" => ["loans"], "abers" => ["bears"], "beors" => ["bores", "sober"],
      "ilnvy" => ["vinyl"], "ackrt" => ["track"], "eenqu" => ["queen"],
      "celno" => ["clone"], "fimrs" => ["firms"], "adils" => ["dials"],
      "alopr" => ["polar"], "ainst" => ["saint"], "rstuy" => ["rusty"],
      "kllsu" => ["skull"], "cikps" => ["picks"], "giltu" => ["guilt"],
      "adeim" => ["aimed", "media"], "acfrt" => ["craft"], "chouv" => ["vouch"],
      "cdorw" => ["crowd"], "aefls" => ["false"], "ablls" => ["balls"],
      "acmps" => ["camps"], "aegru" => ["argue"], "llops" => ["polls"],
      "aelnp" => ["panel", "plane"], "hinsy" => ["shiny"], "achtw" => ["watch"],
      "ddeen" => ["ended"], "ceeip" => ["piece"], "assty" => ["stays"],
      "ailst" => ["tails"], "cefhi" => ["chief"], "beosy" => ["obeys"],
      "adqsu" => ["squad"], "hmnot" => ["month"], "cddeo" => ["coded"],
      "ahmnu" => ["human"], "deimx" => ["mixed"], "eensv" => ["evens", "seven"],
      "aeirs" => ["arise", "raise"], "ahmss" => ["smash"], "aflsw" => ["flaws"],
      "cemry" => ["mercy"], "fhort" => ["forth"], "dhirt" => ["third"],
      "aaemz" => ["amaze"], "aarry" => ["array"], "aeluv" => ["value"],
      "aaekw" => ["awake"], "eemst" => ["meets"], "denss" => ["sends"],
      "adels" => ["deals", "leads"], "instu" => ["units"], "ehosu" => ["house"],
      "achmt" => ["match"], "doprs" => ["drops"], "acesu" => ["sauce", "cause"],
      "ahhrs" => ["harsh"], "ghoru" => ["rough"], "cdhil" => ["child"],
      "aglno" => ["along"], "celsu" => ["clues"], "lmpsu" => ["lumps"],
      "ailtv" => ["vital"], "deorr" => ["order"], "aagin" => ["again"],
      "egrsu" => ["urges"], "eilst" => ["tiles"], "bgosu" => ["bogus"],
      "ahprs" => ["sharp"], "abcel" => ["cable"], "cfosu" => ["focus"],
      "aemsx" => ["exams"], "bdirs" => ["birds"], "abceh" => ["beach"],
      "bestu" => ["tubes"], "brstu" => ["burst"], "orsst" => ["sorts"],
      "illst" => ["still"], "ddego" => ["dodge"], "eknot" => ["token"],
      "accir" => ["circa"], "efirs" => ["fires", "fries"], "cdeos" => ["codes"],
      "abemy" => ["maybe"], "deist" => ["edits"], "arstt" => ["start"],
      "achov" => ["havoc"], "eipss" => ["spies"], "chior" => ["choir"],
      "alott" => ["total"], "illsw" => ["wills"], "accht" => ["catch"],
      "adoty" => ["today"], "adest" => ["dates"], "adfru" => ["fraud"],
      "aeert" => ["eater"], "aehps" => ["phase", "shape"], "emnsu" => ["menus"],
      "acert" => ["cater", "react", "trace"], "demos" => ["modes"],
      "aemnt" => ["meant"], "aeors" => ["arose"], "eissu" => ["issue"],
      "bdeer" => ["breed"], "aeiln" => ["alien"], "cilps" => ["clips"],
      "abest" => ["beast", "beats"], "enooz" => ["ozone"], "bersv" => ["verbs"],
      "abhit" => ["habit"], "fghit" => ["fight"], "ackps" => ["packs"],
      "amrry" => ["marry"], "ilppu" => ["pupil"], "adipr" => ["rapid"],
      "illps" => ["pills", "spill"], "adeks" => ["asked"], "dfilu" => ["fluid"],
      "cekrw" => ["wreck"], "aghns" => ["hangs"], "ailrv" => ["rival"],
      "aaprt" => ["apart"], "eenss" => ["sense"], "ginsw" => ["swing", "wings"],
      "ffstu" => ["stuff"], "begnu" => ["begun"], "addde" => ["added"],
      "films" => ["films"], "eistx" => ["exits", "exist"], "bikln" => ["blink"],
      "aglns" => ["slang"], "ciimm" => ["mimic"], "clnoo" => ["colon"],
      "aceps" => ["space"], "ceitw" => ["twice"], "anstw" => ["wants"],
      "ginow" => ["owing"], "moott" => ["motto"], "adopt" => ["adopt"],
      "eoprs" => ["prose"], "ahppy" => ["happy"], "aehst" => ["hates", "heats"],
      "aalmr" => ["alarm"], "morsw" => ["worms"], "adegp" => ["paged"],
      "abiss" => ["basis"], "anpst" => ["pants"], "emptt" => ["tempt"],
      "epsty" => ["types"], "eehls" => ["heels"], "mppsu" => ["pumps"],
      "denrt" => ["trend"], "aglos" => ["goals"], "ceiov" => ["voice"],
      "ailms" => ["mails"], "ccimo" => ["comic"], "amnor" => ["roman"],
      "abekr" => ["brake", "break"], "aersy" => ["years"],
      "deens" => ["dense", "needs"], "eiltt" => ["title"], "defix" => ["fixed"],
      "ckstu" => ["stuck"], "eeksw" => ["weeks"], "eforz" => ["froze"],
      "dgino" => ["doing"], "fhlsu" => ["flush"], "ehmos" => ["homes"],
      "glosw" => ["glows"], "imsst" => ["mists"], "ciprs" => ["crisp"],
      "orstw" => ["worst"], "abcis" => ["basic"], "aostt" => ["toast"],
      "flosw" => ["flows"], "acess" => ["cases"], "eqruy" => ["query"],
      "dnosu" => ["sound"], "elorv" => ["lover"], "aadrw" => ["award"],
      "adlsy" => ["sadly"], "cchku" => ["chuck"], "afhls" => ["flash"],
      "aclls" => ["calls"], "denru" => ["under"], "adeis" => ["aside", "ideas"],
      "acfst" => ["facts"], "abeks" => ["bakes"], "hmotu" => ["mouth"],
      "psttu" => ["putts"], "adely" => ["delay"], "ehost" => ["those"],
      "delor" => ["older"], "abdor" => ["broad", "board"], "ffity" => ["fifty"],
      "abgrs" => ["grabs"], "instw" => ["twins"], "dehir" => ["hired"],
      "hrstu" => ["hurts"], "aegsu" => ["usage"], "effor" => ["offer"],
      "eefrv" => ["fever"], "efhrs" => ["fresh"], "ffhit" => ["fifth"],
      "achls" => ["clash"], "forty" => ["forty"], "aclss" => ["class"],
      "adinr" => ["drain"], "aeknt" => ["taken"], "cdhor" => ["chord"],
      "eequu" => ["queue"], "ehlos" => ["holes"], "aegnt" => ["agent"],
      "ceorv" => ["cover"], "eegmr" => ["merge"], "bdens" => ["bends"],
      "ckoss" => ["socks"], "irstw" => ["wrist"], "ablmu" => ["album"],
      "arsst" => ["stars"], "chknu" => ["chunk"], "abder" => ["beard", "bread"],
      "ehirt" => ["their"], "eirtw" => ["write"], "aehms" => ["shame"],
      "deilv" => ["devil", "lived"], "ahrst" => ["trash"], "mnoor" => ["moron"],
      "aflot" => ["float"], "ampsw" => ["swamp"], "einsw" => ["wines"],
      "deirs" => ["dries", "rides"], "dmrsu" => ["drums"], "ccehk" => ["check"],
      "eelst" => ["steel"], "chops" => ["chops"], "alpsy" => ["plays"],
      "dhlos" => ["holds"], "eipsw" => ["wipes"], "dnopu" => ["pound"],
      "dilos" => ["solid"], "achpt" => ["patch"], "aeguv" => ["vague"],
      "ehors" => ["horse"], "imnor" => ["minor"], "agnrt" => ["grant"],
      "ehosv" => ["shove"], "illsy" => ["silly"], "aails" => ["alias"],
      "hills" => ["hills"], "acmmo" => ["comma"], "efils" => ["files", "flies"],
      "dillr" => ["drill"], "eestw" => ["sweet"], "horsu" => ["hours"],
      "eemrt" => ["meter"], "achkl" => ["chalk"], "efirv" => ["fiver"],
      "eenrv" => ["nerve", "never"], "efikn" => ["knife"], "korsw" => ["works"],
      "ggino" => ["going"], "floor" => ["floor"], "agrsu" => ["sugar"],
      "deegr" => ["greed"], "agiln" => ["align"], "irsuv" => ["virus"],
      "deirt" => ["tired", "tried"], "ddloy" => ["oddly"], "eirss" => ["rises"],
      "acost" => ["coast", "coats"], "loost" => ["tools"], "chnpu" => ["punch"],
      "adesv" => ["saved"], "dginr" => ["grind"], "delru" => ["ruled"],
      "denrs" => ["rends"], "akprs" => ["parks"], "adevw" => ["waved"],
      "cnotu" => ["count"], "biltu" => ["built"], "orrsy" => ["sorry"],
      "adknr" => ["drank"], "ilopt" => ["pilot"], "aclov" => ["vocal"],
      "dmmuy" => ["dummy"], "afknr" => ["frank"], "aehlw" => ["whale"],
      "dehop" => ["hoped"], "deity" => ["deity"], "eopss" => ["poses"],
      "emort" => ["metro"], "afgls" => ["flags"], "blosw" => ["blows"],
      "imssw" => ["swims"], "deeps" => ["speed"], "bdegu" => ["debug"],
      "ceepr" => ["creep"], "cdios" => ["disco"], "lossw" => ["slows"],
      "adimt" => ["admit"], "hmsty" => ["myths"], "cells" => ["cells"],
      "acprs" => ["scrap"], "abdnr" => ["brand"], "ahirs" => ["hairs"],
      "deotv" => ["voted"], "ikpss" => ["skips"], "amnos" => ["moans"],
      "aefmr" => ["frame"], "ciopt" => ["optic", "topic"],
      "gnorw" => ["grown", "wrong"], "hoopw" => ["whoop"], "aelno" => ["alone"],
      "aimox" => ["axiom"], "dnouw" => ["wound"], "eehmt" => ["theme"],
      "bnosu" => ["bonus"], "ipsst" => ["spits"], "aejns" => ["jeans"],
      "ddeis" => ["sided"], "aertt" => ["treat"], "eorsw" => ["swore", "worse"],
      "ikrst" => ["skirt"], "erssu" => ["users"], "adgnr" => ["grand"],
      "aderv" => ["raved"], "efhls" => ["flesh", "shelf"], "deirv" => ["drive"],
      "alsuu" => ["usual"], "eortw" => ["tower", "wrote"],
      "eersv" => ["verse", "serve"], "ilops" => ["spoil"], "elnov" => ["novel"],
      "adlou" => ["aloud"], "flnow" => ["flown"], "boost" => ["boost", "boots"],
      "filps" => ["flips"], "bells" => ["bells"], "adiry" => ["diary"],
      "bdotu" => ["doubt"], "clruy" => ["curly"], "diknr" => ["drink"],
      "erttu" => ["utter"], "abkrs" => ["barks"], "acehr" => ["reach"],
      "deems" => ["deems"], "eirst" => ["tires", "tries"], "admns" => ["damns"],
      "gilrs" => ["girls"], "arstw" => ["straw"], "deiln" => ["lined"],
      "dejko" => ["joked"], "hossw" => ["shows"], "ikrsy" => ["risky"],
      "eenst" => ["tense"], "eehrt" => ["there", "three"], "nrstu" => ["turns"],
      "deipw" => ["wiped"], "horst" => ["short"], "filst" => ["lifts"],
      "amory" => ["mayor"], "afiln" => ["final"], "enoss" => ["noses"],
      "fssuy" => ["fussy"], "eefrr" => ["refer"], "eehps" => ["sheep"],
      "eerst" => ["reset", "steer", "terse", "trees"], "deinr" => ["diner"],
      "ainrs" => ["rains"], "aeprs" => ["parse", "spare"], "hinst" => ["hints"],
      "aceks" => ["cakes"], "aegnr" => ["anger", "range"], "eeflt" => ["fleet"],
      "beers" => ["beers"], "aelns" => ["leans"], "aeppr" => ["paper"],
      "elops" => ["slope"], "allsw" => ["walls"], "ooprt" => ["troop"],
      "dgooy" => ["goody"], "rsttu" => ["trust"], "ainrt" => ["train"],
      "fgors" => ["frogs"], "ceelt" => ["elect"],
      "aerst" => ["stare", "tears", "rates"], "eloss" => ["soles", "loses"],
      "delmo" => ["model"], "deipr" => ["pride"], "inory" => ["irony"],
      "acirv" => ["vicar"], "dehor" => ["horde"], "aekps" => ["peaks", "speak"],
      "glory" => ["glory"], "klrsu" => ["lurks"], "almor" => ["moral"],
      "enstu" => ["tunes", "unset"], "ehlps" => ["helps"], "ceils" => ["slice"],
      "flluy" => ["fully"], "floru" => ["flour"], "bcilm" => ["climb"],
      "amrst" => ["smart"], "aegln" => ["angel", "glean", "angle"],
      "inpst" => ["pints"], "aestx" => ["taxes"], "ginrs" => ["rings"],
      "dfins" => ["finds"], "benor" => ["borne"], "dfoos" => ["foods"],
      "ellst" => ["tells"], "cdksu" => ["ducks"], "hosst" => ["hosts", "shots"],
      "aehss" => ["ashes"], "aelry" => ["layer", "relay", "early"],
      "deily" => ["yield"], "eisst" => ["sites"], "aadpt" => ["adapt"],
      "adrsw" => ["draws"], "ckoos" => ["cooks"], "bgiot" => ["bigot"],
      "achst" => ["chats"], "jmpsu" => ["jumps"], "ckors" => ["rocks"],
      "eervy" => ["every"], "eekss" => ["seeks"], "aelss" => ["seals", "sales"],
      "degru" => ["urged"], "acrss" => ["crass"], "delov" => ["loved"],
      "befir" => ["brief"], "adehs" => ["shade", "heads"], "aeent" => ["eaten"],
      "acels" => ["scale"], "ddinu" => ["undid"], "ehmry" => ["rhyme"],
      "acdrs" => ["cards"], "efinr" => ["finer", "infer"], "chips" => ["chips"],
      "gorss" => ["gross"], "ffins" => ["sniff"], "achrs" => ["chars", "crash"],
      "cdeit" => ["cited"], "gopru" => ["group"], "eopst" => ["poets"],
      "aeegl" => ["eagle"], "alsst" => ["lasts"], "knrtu" => ["trunk"],
      "dikns" => ["kinds"], "aekms" => ["makes"], "adepy" => ["payed"],
      "oprst" => ["ports", "sport"], "acder" => ["cared", "raced"],
      "ginty" => ["tying"], "eehrw" => ["where"], "abdel" => ["blade"],
      "aaitw" => ["await"], "eghit" => ["eight"], "esttx" => ["texts"],
      "demov" => ["moved"], "efhit" => ["thief"], "fnorw" => ["frown"],
      "degiu" => ["guide"], "fmoru" => ["forum"], "ackss" => ["sacks"],
      "biort" => ["orbit"], "eemny" => ["enemy"], "deert" => ["deter"],
      "beist" => ["bites"], "ekmos" => ["smoke"], "dimns" => ["minds"],
      "cilry" => ["lyric"], "adily" => ["daily"], "eehtt" => ["teeth"],
      "enopr" => ["prone"], "celos" => ["close"], "bcikr" => ["brick"],
      "orsuy" => ["yours"], "achos" => ["chaos"], "elrsu" => ["rules"],
      "ainpt" => ["paint"], "hopss" => ["shops"], "cdeer" => ["creed"],
      "achmr" => ["charm", "march"], "ilpst" => ["split"], "boort" => ["robot"],
      "aelrx" => ["relax"], "dfnsu" => ["funds"], "imnsu" => ["minus"],
      "diiot" => ["idiot"], "dhitw" => ["width"], "mnoos" => ["moons"],
      "histx" => ["sixth"], "bbhoy" => ["hobby"], "losuy" => ["lousy"],
      "acetx" => ["exact"], "bnorw" => ["brown"], "emnoy" => ["money"],
      "diott" => ["ditto"], "hnort" => ["north"], "benos" => ["bones"],
      "efgir" => ["grief"], "bnrtu" => ["burnt"], "aenrs" => ["earns"],
      "adnrw" => ["drawn"], "bblsu" => ["bulbs"], "abort" => ["abort"],
      "eilns" => ["lines"], "cikqu" => ["quick"], "adiou" => ["audio"],
      "aegms" => ["games"], "ekops" => ["spoke"], "ghint" => ["night", "thing"],
      "adhns" => ["hands"], "chinp" => ["pinch"], "nostw" => ["towns"],
      "cinru" => ["incur"], "defin" => ["fined"], "jlloy" => ["jolly"],
      "aegsw" => ["wages"], "acckr" => ["crack"], "cosst" => ["costs"],
      "eoqtu" => ["quote"], "ennpy" => ["penny"], "dlors" => ["lords"],
      "diprs" => ["drips"], "dlorw" => ["world"], "adelp" => ["pedal"],
      "eirrv" => ["river"], "epstw" => ["swept"], "ahlls" => ["halls", "shall"],
      "bdilu" => ["build"], "aelrs" => ["laser"], "deglo" => ["lodge"],
      "enorw" => ["owner"], "cdlou" => ["cloud", "could"], "glpsu" => ["plugs"],
      "aestw" => ["sweat", "waste"], "aelmp" => ["ample"], "hnosw" => ["shown"],
      "ahsty" => ["hasty"], "eginr" => ["reign"], "deiov" => ["video"],
      "eilrv" => ["liver"], "aegst" => ["gates", "stage"], "aelvv" => ["valve"],
      "eefrs" => ["frees"], "eellv" => ["level"], "acefs" => ["faces"],
      "bginr" => ["bring"], "efhtt" => ["theft"], "adnst" => ["stand"],
      "ghist" => ["sight"], "lossu" => ["souls"], "abdei" => ["abide"],
      "belsu" => ["blues"], "belss" => ["bless"], "aekrt" => ["taker"],
      "iknss" => ["sinks"], "ailns" => ["nails", "snail"], "ghimt" => ["might"],
      "cehsw" => ["chews"], "aceep" => ["peace"], "abhst" => ["baths"],
      "elovw" => ["vowel"], "ilsst" => ["lists"], "hoopt" => ["photo"],
      "adhry" => ["hardy"], "abkns" => ["banks"], "allow" => ["allow"],
      "deops" => ["posed"], "ahrtw" => ["wrath"], "bcklo" => ["block"],
      "ellms" => ["smell"], "aoqtu" => ["quota"], "dgiir" => ["rigid"],
      "diimo" => ["idiom"], "ijnot" => ["joint"], "aeers" => ["erase"],
      "eorsz" => ["zeros"], "derss" => ["dress"], "ceenp" => ["pence"],
      "aefrs" => ["fears", "safer"], "abnru" => ["urban"], "abemr" => ["amber"],
      "eimrt" => ["timer", "merit"], "acnss" => ["scans"], "adehr" => ["heard"],
      "ccoru" => ["occur"], "ahpst" => ["paths"], "crruy" => ["curry"],
      "cdeir" => ["cider", "cried"], "giprs" => ["grips"], "aberv" => ["brave"],
      "emsst" => ["stems"], "cemos" => ["comes"], "cciny" => ["cynic"],
      "gorsw" => ["grows"], "afhit" => ["faith"], "eilsv" => ["evils", "lives"],
      "akmrs" => ["marks"], "beirt" => ["tribe"], "bcciu" => ["cubic"],
      "elosv" => ["loves", "solve"], "himst" => ["smith"], "aeirt" => ["irate"],
      "aehks" => ["shake"], "cefht" => ["fetch"], "abcht" => ["batch"],
      "eorrr" => ["error"], "eimov" => ["movie"], "bbeil" => ["bible"],
      "abdek" => ["baked"], "innou" => ["union"], "apssw" => ["swaps"],
      "ehort" => ["other"], "ahknt" => ["thank"], "abens" => ["beans"],
      "eekns" => ["knees"], "foopr" => ["proof"], "aeilv" => ["alive"],
      "aahlp" => ["alpha"], "iilmt" => ["limit"], "eepst" => ["steep"],
      "ailrt" => ["trail", "trial"], "eefrw" => ["fewer"], "fgist" => ["gifts"],
      "einrs" => ["risen"], "enosz" => ["zones"], "below" => ["below"],
      "ghilt" => ["light"], "chotu" => ["touch"], "amrsw" => ["warms"],
      "egmno" => ["gnome"], "abost" => ["boats"], "aegll" => ["legal"],
      "aelmt" => ["metal"], "beosx" => ["boxes"], "dehis" => ["hides"],
      "adors" => ["roads"], "aknrs" => ["ranks"], "ceinr" => ["nicer"],
      "cesst" => ["sects"], "eprsu" => ["super"], "eostv" => ["votes"],
      "deils" => ["slide"], "aaflt" => ["fatal"], "cgilo" => ["logic"],
      "dknru" => ["drunk"], "emrst" => ["terms"], "anrsw" => ["warns"],
      "acemr" => ["cream"], "nnosu" => ["nouns"], "losst" => ["slots"],
      "beruy" => ["buyer"], "hrttu" => ["truth"], "bblru" => ["blurb"],
      "aemsu" => ["amuse"], "deirw" => ["wired", "weird", "wider"],
      "adrsy" => ["yards"], "eortu" => ["outer", "route"], "adior" => ["radio"],
      "alppy" => ["apply"], "emops" => ["poems"], "aaers" => ["areas"],
      "glnsu" => ["lungs"], "gikns" => ["kings"], "cimsu" => ["music"],
      "aeinv" => ["naive"], "hoott" => ["tooth"], "aestt" => ["state", "taste"],
      "achrt" => ["chart"], "bdeor" => ["bored"], "eepsw" => ["sweep"],
      "begin" => ["begin", "being"], "eehrs" => ["sheer"], "fiyzz" => ["fizzy"],
      "eilms" => ["miles", "smile"], "dflos" => ["folds"],
      "loops" => ["loops", "spool"], "ailrs" => ["rails"], "deegs" => ["edges"],
      "fklos" => ["folks"], "bilss" => ["bliss"],
      "enost" => ["tones", "notes", "stone"], "deefs" => ["feeds"],
      "floos" => ["fools"], "blnow" => ["blown"], "defgu" => ["fudge"],
      "mnotu" => ["mount"], "achks" => ["hacks"], "ahlss" => ["slash"],
      "abkln" => ["blank"], "acees" => ["cease"], "aepst" => ["paste", "tapes"],
      "cffil" => ["cliff"], "firtu" => ["fruit"], "eimns" => ["mines"],
      "ackns" => ["snack"], "ckrtu" => ["truck"], "ddein" => ["dined"],
      "cersw" => ["screw"], "aceht" => ["cheat", "teach"], "llors" => ["rolls"],
      "adery" => ["ready"], "ccklo" => ["clock"], "eenrw" => ["newer", "renew"],
      "achir" => ["chair"], "ilmpy" => ["imply"], "morst" => ["storm"],
      "iprst" => ["strip", "trips"], "abrss" => ["brass"], "akrst" => ["stark"],
      "aemst" => ["steam", "teams"], "ademr" => ["armed", "dream"],
      "eiprz" => ["prize"], "deeky" => ["keyed"], "eimst" => ["items", "times"],
      "enops" => ["opens"], "isstu" => ["suits"], "ceipr" => ["price"],
      "ginss" => ["sings", "signs"], "aprst" => ["parts", "traps"],
      "fnort" => ["front"], "dentu" => ["tuned"], "aadmr" => ["drama"],
      "aceno" => ["ocean"], "aklsw" => ["walks"], "ackrs" => ["racks"],
      "addet" => ["dated"], "acrry" => ["carry"], "adekw" => ["waked"],
      "acdet" => ["acted"], "acelr" => ["clear"], "afltu" => ["fault"],
      "dfnou" => ["found"], "adeht" => ["hated", "death"], "ghirt" => ["right"],
      "ahlst" => ["halts"], "eehlw" => ["wheel"], "alory" => ["royal"],
      "aeglr" => ["lager", "large"], "elpsu" => ["pulse"],
      "eehst" => ["sheet", "these"], "emnow" => ["women"], "abesu" => ["abuse"],
      "orrwy" => ["worry"], "epstu" => ["upset"], "eorst" => ["store"],
      "beill" => ["libel"], "finuy" => ["unify"], "aiort" => ["ratio"],
      "cortu" => ["court"], "eoprv" => ["prove"], "ghost" => ["ghost"],
      "cefor" => ["force"], "cnorw" => ["crown"], "aghlu" => ["laugh"],
      "acgim" => ["magic"], "bbloy" => ["lobby"], "nsstu" => ["stuns"],
      "ceens" => ["scene"], "bilms" => ["limbs"], "aesvw" => ["waves"],
      "abell" => ["label"], "acers" => ["races", "scare", "cares"],
      "eissz" => ["sizes"], "aceln" => ["clean"], "acehs" => ["chase"],
      "eipst" => ["spite"], "acryz" => ["crazy"], "ajmor" => ["major"],
      "ceist" => ["cites"], "acfny" => ["fancy"], "allms" => ["small"],
      "opsst" => ["posts", "spots", "stops"], "ijnos" => ["joins"],
      "ehlls" => ["shell"], "ackst" => ["stack", "tacks"], "eintu" => ["unite"],
      "bhmtu" => ["thumb"], "knosw" => ["knows"], "adder" => ["dared", "dread"],
      "aklst" => ["talks"], "aeflm" => ["flame"], "aeinn" => ["inane"],
      "deimn" => ["mined"], "irsst" => ["stirs"], "fmors" => ["forms"],
      "ensst" => ["nests"], "aglss" => ["glass"], "ddees" => ["deeds"],
      "dinsw" => ["winds"], "einrt" => ["inter"], "acetu" => ["acute"],
      "ailss" => ["sails"], "aertw" => ["water"], "aehvy" => ["heavy"],
      "doost" => ["stood"], "ckkno" => ["knock"], "dnoru" => ["round"],
      "aprsy" => ["prays", "spray"], "dfloo" => ["flood"],
      "adelt" => ["delta", "dealt"], "aehrt" => ["earth", "heart"],
      "alnpt" => ["plant"], "oprsu" => ["pours"], "ehoss" => ["shoes"],
      "eegnr" => ["genre", "green"], "fnnuy" => ["funny"], "bkoos" => ["books"],
      "doosw" => ["woods"], "ehnos" => ["shone"], "bbmos" => ["bombs"],
      "egirt" => ["tiger"], "aehrs" => ["hears", "share"], "acelp" => ["place"],
      "dlouw" => ["would"], "abckl" => ["black"], "ceimr" => ["crime"],
      "bdins" => ["binds"], "eghiw" => ["weigh"], "frruy" => ["furry"],
      "ehitw" => ["white"], "bnrsu" => ["burns"], "eortv" => ["voter"],
      "aorrw" => ["arrow"], "aemns" => ["means", "names"], "ddehi" => ["hided"],
      "aelpt" => ["plate"], "hotuy" => ["youth"], "aalst" => ["atlas"],
      "fills" => ["fills"], "chlot" => ["cloth"], "eqstu" => ["quest"],
      "hkoos" => ["hooks", "shook"], "adlos" => ["loads"], "ehnop" => ["phone"],
      "eglov" => ["glove"], "cdeop" => ["coped"], "aersw" => ["swear", "wears"],
      "aefkr" => ["freak"], "ceors" => ["score"], "acdes" => ["cased"],
      "aeimz" => ["maize"], "ceehr" => ["cheer"], "aaerw" => ["aware"],
      "cdhit" => ["ditch"], "ffist" => ["stiff"], "gnoss" => ["songs"],
      "einnr" => ["inner"], "aelrt" => ["alert", "alter", "later"],
      "ciilv" => ["civil"], "eeprs" => ["peers"], "bdeem" => ["embed"],
      "elsty" => ["style"], "eikps" => ["spike"], "lrtuy" => ["truly"],
      "bcksu" => ["bucks"], "cikrt" => ["trick"], "aersv" => ["raves"],
      "aclrw" => ["crawl"], "bills" => ["bills"], "ghitt" => ["tight"],
      "isttw" => ["twist"], "imotv" => ["vomit"], "iklns" => ["links"],
      "chipt" => ["pitch"], "hortw" => ["throw", "worth"], "dgoos" => ["goods"],
      "ceiju" => ["juice"], "bhirt" => ["birth"], "anrst" => ["rants"],
      "abinr" => ["brain"], "hoost" => ["shoot"], "abcks" => ["backs"],
      "airst" => ["stair"], "alloy" => ["loyal"], "lorry" => ["lorry"],
      "norsw" => ["sworn"], "chrsu" => ["crush"], "ceruv" => ["curve"],
      "efnot" => ["often"], "oorst" => ["roots"], "defir" => ["fired", "fried"],
      "eenuv" => ["venue"], "eegns" => ["genes"], "affst" => ["staff"],
      "llpsu" => ["pulls"], "aorrz" => ["razor"], "agims" => ["sigma"],
      "acefr" => ["farce"], "nnsuy" => ["sunny"], "belno" => ["noble"],
      "eginv" => ["given"], "aders" => ["dares", "reads"], "ilntu" => ["until"],
      "abdes" => ["based"], "aegrv" => ["grave"], "accho" => ["coach"],
      "bdloo" => ["blood"], "cderu" => ["crude", "cured"], "aekns" => ["sneak"],
      "dstuy" => ["dusty", "study"], "eersu" => ["reuse"], "bhrsu" => ["brush"],
      "deimt" => ["timed"], "aiprs" => ["pairs"], "ablst" => ["blast"],
      "adeil" => ["ideal"], "chitw" => ["witch"], "aaimn" => ["mania"],
      "aegim" => ["image"], "fuyzz" => ["fuzzy"], "ansty" => ["nasty"],
      "ceehn" => ["hence"], "aelnr" => ["learn"], "intuy" => ["unity"],
      "dirty" => ["dirty"], "acmpr" => ["cramp"], "bdnou" => ["bound"],
      "ehlot" => ["hotel"], "moors" => ["rooms"], "eemss" => ["seems"],
      "hostu" => ["shout", "thous", "south"], "ellss" => ["sells"],
      "cghou" => ["cough"], "eisvw" => ["wives", "views"], "adekn" => ["naked"],
      "aegps" => ["pages"], "adltu" => ["adult"], "ainps" => ["pains"],
      "aekst" => ["stake", "takes"], "cdiss" => ["discs"], "ahksy" => ["shaky"],
      "denoz" => ["dozen"], "acilm" => ["claim"], "eipps" => ["pipes"],
      "emrry" => ["merry"], "eilps" => ["piles"], "cklos" => ["locks"],
      "cehos" => ["chose"], "opstu" => ["spout"], "eloos" => ["loose"],
      "admtu" => ["datum"], "abdeg" => ["badge"], "dmpsu" => ["dumps"],
      "adegr" => ["grade"], "bilos" => ["boils"], "deisv" => ["dives"],
      "ceirs" => ["cries"], "deopt" => ["opted"], "aegrs" => ["gears"],
      "efisx" => ["fixes"], "chlnu" => ["lunch"], "inprt" => ["print"],
      "annoy" => ["annoy"], "egssu" => ["guess"], "ikrss" => ["risks"],
      "aknst" => ["tanks"], "eknow" => ["woken"], "bdiln" => ["blind"],
      "dnorw" => ["drown"], "ceehk" => ["cheek"], "eekps" => ["keeps"],
      "emssy" => ["messy"], "acegr" => ["grace"], "aegrt" => ["great"],
      "istxy" => ["sixty"], "deoss" => ["doses"], "iistv" => ["visit"],
      "deiss" => ["sides"], "aessv" => ["saves"], "adgrs" => ["drags"],
      "hrruy" => ["hurry"], "eentv" => ["event"], "acinp" => ["panic"],
      "hirst" => ["shirt"], "denps" => ["pends", "spend"],
      "aelst" => ["stale", "tales", "least", "steal"]}
    |> Map.get(string_id)
  end

  def valid_ids do
    ["ademn", "aeopr", "acnor", "enrty", "aadrr", "first", "eoprw", "elmno",
     "ittwy", "aelqu", "agnoy", "bclsu", "enpst", "adilv", "ehntt", "afint",
     "eenrt", "eimpr", "inrsu", "afiry", "aipzz", "hnstu", "adhny", "aflls",
     "alrru", "dehss", "alnps", "aprty", "ellps", "eistu", "acehp", "aeksw",
     "adgmo", "ejnoy", "aelms", "gnouy", "cehss", "aghpr", "ackls", "cehst",
     "deefr", "aeegr", "addew", "empty", "ejkos", "agint", "denot", "adirs",
     "ehllo", "elors", "eessx", "egpru", "acdey", "dehpt", "efmsu", "acdef",
     "afluw", "chhiw", "acden", "doors", "achin", "abelm", "eppru", "aksst",
     "celru", "emosu", "arsty", "hsstu", "agnry", "moort", "eimsx", "agrss",
     "deinx", "agnor", "adfrt", "aaenr", "eprss", "cikks", "inopt", "acort",
     "abdir", "elorw", "dorsw", "achps", "kloos", "deikl", "elpst", "aeelv",
     "ehlow", "aadeh", "gilny", "abess", "adesw", "denst", "cloos", "agprs",
     "ccikl", "esstt", "ehilw", "elrru", "amnow", "bchnu", "defil", "orsty",
     "chkos", "ehins", "innoo", "cikns", "aelmr", "emosv", "cikst", "aekmr",
     "abelt", "ioprr", "amost", "orstu", "ailnp", "aabln", "elost", "chikt",
     "hipss", "celnu", "ckost", "epsst", "aeikl", "abdly", "aistw", "aessy",
     "iqstu", "ghotu", "eiqtu", "afils", "aimns", "eelps", "ehosw", "densv",
     "eirsw", "eefls", "deorv", "addei", "cehit", "adiov", "ersst", "adlns",
     "besty", "foops", "abegn", "aelpp", "mmmuy", "egisv", "eipqu", "eeilt",
     "ejlly", "adgru", "adert", "fnost", "acllo", "elpry", "acehl", "acsst",
     "egstu", "efins", "inosy", "enrsu", "aginr", "aerrr", "iklls", "ehops",
     "aepsu", "deisz", "ceefn", "npstu", "depty", "coprs", "fhist", "dfirt",
     "denos", "orttu", "dgiit", "nsttu", "eptty", "aehlv", "aelsv", "ehirs",
     "knnow", "dopru", "ginsu", "ceins", "ahiry", "dgrsu", "einos", "ckluy",
     "corss", "ilpss", "ampst", "degju", "dginy", "abeov", "bcehn", "ckmsu",
     "abotu", "efltu", "abdns", "eikls", "aertx", "ehnoy", "ehrtw", "aerwy",
     "demns", "ccely", "dmoos", "ainop", "denow", "aesst", "elnwy", "delns",
     "allst", "agins", "ddeiv", "aprsw", "deins", "ceops", "alors", "bekor",
     "lopst", "acfrs", "cinos", "aefrt", "imost", "hiknt", "cersu", "ddeir",
     "inptu", "alnos", "abers", "beors", "ilnvy", "ackrt", "eenqu", "celno",
     "fimrs", "adils", "alopr", "ainst", "rstuy", "kllsu", "cikps", "giltu",
     "adeim", "acfrt", "chouv", "cdorw", "aefls", "ablls", "acmps", "aegru",
     "llops", "aelnp", "hinsy", "achtw", "ddeen", "ceeip", "assty", "ailst",
     "cefhi", "beosy", "adqsu", "hmnot", "cddeo", "ahmnu", "deimx", "eensv",
     "aeirs", "ahmss", "aflsw", "cemry", "fhort", "dhirt", "aaemz", "aarry",
     "aeluv", "aaekw", "eemst", "denss", "adels", "instu", "ehosu", "achmt",
     "doprs", "acesu", "ahhrs", "ghoru", "cdhil", "aglno", "celsu", "lmpsu",
     "ailtv", "deorr", "aagin", "egrsu", "eilst", "bgosu", "ahprs", "abcel",
     "cfosu", "aemsx", "bdirs", "abceh", "bestu", "brstu", "orsst", "illst",
     "ddego", "eknot", "accir", "efirs", "cdeos", "abemy", "deist", "arstt",
     "achov", "eipss", "chior", "alott", "illsw", "accht", "adoty", "adest",
     "adfru", "aeert", "aehps", "emnsu", "acert", "demos", "aemnt", "aeors",
     "eissu", "bdeer", "aeiln", "cilps", "abest", "enooz", "bersv", "abhit",
     "fghit", "ackps", "amrry", "ilppu", "adipr", "illps", "adeks", "dfilu",
     "cekrw", "aghns", "ailrv", "aaprt", "eenss", "ginsw", "ffstu", "begnu",
     "addde", "films", "eistx", "bikln", "aglns", "ciimm", "clnoo", "aceps",
     "ceitw", "anstw", "ginow", "moott", "adopt", "eoprs", "ahppy", "aehst",
     "aalmr", "morsw", "adegp", "abiss", "anpst", "emptt", "epsty", "eehls",
     "mppsu", "denrt", "aglos", "ceiov", "ailms", "ccimo", "amnor", "abekr",
     "aersy", "deens", "eiltt", "defix", "ckstu", "eeksw", "eforz", "dgino",
     "fhlsu", "ehmos", "glosw", "imsst", "ciprs", "orstw", "abcis", "aostt",
     "flosw", "acess", "eqruy", "dnosu", "elorv", "aadrw", "adlsy", "cchku",
     "afhls", "aclls", "denru", "adeis", "acfst", "abeks", "hmotu", "psttu",
     "adely", "ehost", "delor", "abdor", "ffity", "abgrs", "instw", "dehir",
     "hrstu", "aegsu", "effor", "eefrv", "efhrs", "ffhit", "achls", "forty",
     "aclss", "adinr", "aeknt", "cdhor", "eequu", "ehlos", "aegnt", "ceorv",
     "eegmr", "bdens", "ckoss", "irstw", "ablmu", "arsst", "chknu", "abder",
     "ehirt", "eirtw", "aehms", "deilv", "ahrst", "mnoor", "aflot", "ampsw",
     "einsw", "deirs", "dmrsu", "ccehk", "eelst", "chops", "alpsy", "dhlos",
     "eipsw", "dnopu", "dilos", "achpt", "aeguv", "ehors", "imnor", "agnrt",
     "ehosv", "illsy", "aails", "hills", "acmmo", "efils", "dillr", "eestw",
     "horsu", "eemrt", "achkl", "efirv", "eenrv", "efikn", "korsw", "ggino",
     "floor", "agrsu", "deegr", "agiln", "irsuv", "deirt", "ddloy", "eirss",
     "acost", "loost", "chnpu", "adesv", "dginr", "delru", "denrs", "akprs",
     "adevw", "cnotu", "biltu", "orrsy", "adknr", "ilopt", "aclov", "dmmuy",
     "afknr", "aehlw", "dehop", "deity", "eopss", "emort", "afgls", "blosw",
     "imssw", "deeps", "bdegu", "ceepr", "cdios", "lossw", "adimt", "hmsty",
     "cells", "acprs", "abdnr", "ahirs", "deotv", "ikpss", "amnos", "aefmr",
     "ciopt", "gnorw", "hoopw", "aelno", "aimox", "dnouw", "eehmt", "bnosu",
     "ipsst", "aejns", "ddeis", "aertt", "eorsw", "ikrst", "erssu", "adgnr",
     "aderv", "efhls", "deirv", "alsuu", "eortw", "eersv", "ilops", "elnov",
     "adlou", "flnow", "boost", "filps", "bells", "adiry", "bdotu", "clruy",
     "diknr", "erttu", "abkrs", "acehr", "deems", "eirst", "admns", "gilrs",
     "arstw", "deiln", "dejko", "hossw", "ikrsy", "eenst", "eehrt", "nrstu",
     "deipw", "horst", "filst", "amory", "afiln", "enoss", "fssuy", "eefrr",
     "eehps", "eerst", "deinr", "ainrs", "aeprs", "hinst", "aceks", "aegnr",
     "eeflt", "beers", "aelns", "aeppr", "elops", "allsw", "ooprt", "dgooy",
     "rsttu", "ainrt", "fgors", "ceelt", "aerst", "eloss", "delmo", "deipr",
     "inory", "acirv", "dehor", "aekps", "glory", "klrsu", "almor", "enstu",
     "ehlps", "ceils", "flluy", "floru", "bcilm", "amrst", "aegln", "inpst",
     "aestx", "ginrs", "dfins", "benor", "dfoos", "ellst", "cdksu", "hosst",
     "aehss", "aelry", "deily", "eisst", "aadpt", "adrsw", "ckoos", "bgiot",
     "achst", "jmpsu", "ckors", "eervy", "eekss", "aelss", "degru", "acrss",
     "delov", "befir", "adehs", "aeent", "acels", "ddinu", "ehmry", "acdrs",
     "efinr", "chips", "gorss", "ffins", "achrs", "cdeit", "gopru", "eopst",
     "aeegl", "alsst", "knrtu", "dikns", "aekms", "adepy", "oprst", "acder",
     "ginty", "eehrw", "abdel", "aaitw", "eghit", "esttx", "demov", "efhit",
     "fnorw", "degiu", "fmoru", "ackss", "biort", "eemny", "deert", "beist",
     "ekmos", "dimns", "cilry", "adily", "eehtt", "enopr", "celos", "bcikr",
     "orsuy", "achos", "elrsu", "ainpt", "hopss", "cdeer", "achmr", "ilpst",
     "boort", "aelrx", "dfnsu", "imnsu", "diiot", "dhitw", "mnoos", "histx",
     "bbhoy", "losuy", "acetx", "bnorw", "emnoy", "diott", "hnort", "benos",
     "efgir", "bnrtu", "aenrs", "adnrw", "bblsu", "abort", "eilns", "cikqu",
     "adiou", "aegms", "ekops", "ghint", "adhns", "chinp", "nostw", "cinru",
     "defin", "jlloy", "aegsw", "acckr", "cosst", "eoqtu", "ennpy", "dlors",
     "diprs", "dlorw", "adelp", "eirrv", "epstw", "ahlls", "bdilu", "aelrs",
     "deglo", "enorw", "cdlou", "glpsu", "aestw", "aelmp", "hnosw", "ahsty",
     "eginr", "deiov", "eilrv", "aegst", "aelvv", "eefrs", "eellv", "acefs",
     "bginr", "efhtt", "adnst", "ghist", "lossu", "abdei", "belsu", "belss",
     "aekrt", "iknss", "ailns", "ghimt", "cehsw", "aceep", "abhst", "elovw",
     "ilsst", "hoopt", "adhry", "abkns", "allow", "deops", "ahrtw", "bcklo",
     "ellms", "aoqtu", "dgiir", "diimo", "ijnot", "aeers", "eorsz", "derss",
     "ceenp", "aefrs", "abnru", "abemr", "eimrt", "acnss", "adehr", "ccoru",
     "ahpst", "crruy", "cdeir", "giprs", "aberv", "emsst", "cemos", "cciny",
     "gorsw", "afhit", "eilsv", "akmrs", "beirt", "bcciu", "elosv", "himst",
     "aeirt", "aehks", "cefht", "abcht", "eorrr", "eimov", "bbeil", "abdek",
     "innou", "apssw", "ehort", "ahknt", "abens", "eekns", "foopr", "aeilv",
     "aahlp", "iilmt", "eepst", "ailrt", "eefrw", "fgist", "einrs", "enosz",
     "below", "ghilt", "chotu", "amrsw", "egmno", "abost", "aegll", "aelmt",
     "beosx", "dehis", "adors", "aknrs", "ceinr", "cesst", "eprsu", "eostv",
     "deils", "aaflt", "cgilo", "dknru", "emrst", "anrsw", "acemr", "nnosu",
     "losst", "beruy", "hrttu", "bblru", "aemsu", "deirw", "adrsy", "eortu",
     "adior", "alppy", "emops", "aaers", "glnsu", "gikns", "cimsu", "aeinv",
     "hoott", "aestt", "achrt", "bdeor", "eepsw", "begin", "eehrs", "fiyzz",
     "eilms", "dflos", "loops", "ailrs", "deegs", "fklos", "bilss", "enost",
     "deefs", "floos", "blnow", "defgu", "mnotu", "achks", "ahlss", "abkln",
     "acees", "aepst", "cffil", "firtu", "eimns", "ackns", "ckrtu", "ddein",
     "cersw", "aceht", "llors", "adery", "ccklo", "eenrw", "achir", "ilmpy",
     "morst", "iprst", "abrss", "akrst", "aemst", "ademr", "eiprz", "deeky",
     "eimst", "enops", "isstu", "ceipr", "ginss", "aprst", "fnort", "dentu",
     "aadmr", "aceno", "aklsw", "ackrs", "addet", "acrry", "adekw", "acdet",
     "acelr", "afltu", "dfnou", "adeht", "ghirt", "ahlst", "eehlw", "alory",
     "aeglr", "elpsu", "eehst", "emnow", "abesu", "orrwy", "epstu", "eorst",
     "beill", "finuy", "aiort", "cortu", "eoprv", "ghost", "cefor", "cnorw",
     "aghlu", "acgim", "bbloy", "nsstu", "ceens", "bilms", "aesvw", "abell",
     "acers", "eissz", "aceln", "acehs", "eipst", "acryz", "ajmor", "ceist",
     "acfny", "allms", "opsst", "ijnos", "ehlls", "ackst", "eintu", "bhmtu",
     "knosw", "adder", "aklst", "aeflm", "aeinn", "deimn", "irsst", "fmors",
     "ensst", "aglss", "ddees", "dinsw", "einrt", "acetu", "ailss", "aertw",
     "aehvy", "doost", "ckkno", "dnoru", "aprsy", "dfloo", "adelt", "aehrt",
     "alnpt", "oprsu", "ehoss", "eegnr", "fnnuy", "bkoos", "doosw", "ehnos",
     "bbmos", "egirt", "aehrs", "acelp", "dlouw", "abckl", "ceimr", "bdins",
     "eghiw", "frruy", "ehitw", "bnrsu", "eortv", "aorrw", "aemns", "ddehi",
     "aelpt", "hotuy", "aalst", "fills", "chlot", "eqstu", "hkoos", "adlos",
     "ehnop", "eglov", "cdeop", "aersw", "aefkr", "ceors", "acdes", "aeimz",
     "ceehr", "aaerw", "cdhit", "ffist", "gnoss", "einnr", "aelrt", "ciilv",
     "eeprs", "bdeem", "elsty", "eikps", "lrtuy", "bcksu", "cikrt", "aersv",
     "aclrw", "bills", "ghitt", "isttw", "imotv", "iklns", "chipt", "hortw",
     "dgoos", "ceiju", "bhirt", "anrst", "abinr", "hoost", "abcks", "airst",
     "alloy", "lorry", "norsw", "chrsu", "ceruv", "efnot", "oorst", "defir",
     "eenuv", "eegns", "affst", "llpsu", "aorrz", "agims", "acefr", "nnsuy",
     "belno", "eginv", "aders", "ilntu", "abdes", "aegrv", "accho", "bdloo",
     "cderu", "aekns", "dstuy", "eersu", "bhrsu", "deimt", "aiprs", "ablst",
     "adeil", "chitw", "aaimn", "aegim", "fuyzz", "ansty", "ceehn", "aelnr",
     "intuy", "dirty", "acmpr", "bdnou", "ehlot", "moors", "eemss", "hostu",
     "ellss", "cghou", "eisvw", "adekn", "aegps", "adltu", "ainps", "aekst",
     "cdiss", "ahksy", "denoz", "acilm", "eipps", "emrry", "eilps", "cklos",
     "cehos", "opstu", "eloos", "admtu", "abdeg", "dmpsu", "adegr", "bilos",
     "deisv", "ceirs", "deopt", "aegrs", "efisx", "chlnu", "inprt", "annoy",
     "egssu", "ikrss", "aknst", "eknow", "bdiln", "dnorw", "ceehk", "eekps",
     "emssy", "acegr", "aegrt", "istxy", "deoss", "iistv", "deiss", "aessv",
     "adgrs", "hrruy", "eentv", "acinp", "hirst", "denps", "aelst"]
    |> Enum.into(HashSet.new)
  end
end
