defmodule Jumble.ScowlDict.Size50.Length5.Dict do
  def get do
    %{"alnru" => ["lunar"], "ademn" => ["admen", "amend", "named"],
      "aeopr" => ["opera"], "agnow" => ["wagon"], "fhisy" => ["fishy"],
      "bgrsu" => ["burgs", "grubs"], "cchno" => ["conch"], "acnor" => ["acorn"],
      "enrty" => ["entry"], "aadrr" => ["radar"], "ilmos" => ["limos"],
      "doowy" => ["woody"], "eknor" => ["krone"], "aeglz" => ["glaze"],
      "denuw" => ["unwed"], "first" => ["rifts", "first"], "insst" => ["snits"],
      "eoprw" => ["power"], "beegi" => ["beige"], "filty" => ["fitly"],
      "aeltx" => ["exalt", "latex"], "addez" => ["dazed"], "ehlov" => ["hovel"],
      "prssu" => ["spurs"], "cdiks" => ["dicks"], "elmno" => ["melon", "lemon"],
      "aemty" => ["meaty"], "aclms" => ["calms", "clams"], "amnnu" => ["unman"],
      "ittwy" => ["witty"], "aelqu" => ["equal"], "deego" => ["geode"],
      "aelmm" => ["lemma"], "klssu" => ["sulks"], "agnoy" => ["agony"],
      "aafnu" => ["fauna"], "bclsu" => ["clubs"], "ddeoz" => ["dozed"],
      "fiins" => ["finis"], "eegrv" => ["verge"], "fmpru" => ["frump"],
      "deoow" => ["wooed"], "enpst" => ["spent"], "ehpry" => ["hyper"],
      "adilv" => ["valid"], "ehntt" => ["tenth"], "afint" => ["faint"],
      "eenrt" => ["enter"], "anory" => ["rayon"], "lopsy" => ["ploys"],
      "eijmo" => ["emoji"], "eimpr" => ["prime"], "acgin" => ["acing"],
      "emors" => ["mores"], "inrsu" => ["ruins"], "afiry" => ["fairy"],
      "aipzz" => ["pizza"], "afirs" => ["fairs"], "bcmos" => ["combs"],
      "hnstu" => ["shunt", "hunts"], "adhny" => ["handy"], "aflls" => ["falls"],
      "alrru" => ["rural"], "belry" => ["beryl"], "dehss" => ["sheds"],
      "blntu" => ["blunt"], "alnps" => ["plans"], "ejlou" => ["joule"],
      "aprty" => ["party"], "ahssw" => ["swash"], "ckssu" => ["sucks"],
      "aosvw" => ["avows"], "ellps" => ["spell"], "glnos" => ["longs"],
      "aailx" => ["axial"], "asvvy" => ["savvy"], "abist" => ["baits"],
      "ikmrs" => ["smirk"], "eistu" => ["suite"], "lppsu" => ["pulps"],
      "acehp" => ["peach", "cheap"], "aeksw" => ["askew", "wakes"],
      "adgmo" => ["dogma"], "lmppu" => ["plump"], "dehik" => ["hiked"],
      "ejnoy" => ["enjoy"], "ehist" => ["heist"], "acems" => ["acmes", "maces"],
      "aelms" => ["lames", "males", "meals"], "gnouy" => ["young"],
      "fisst" => ["fists", "sifts"], "bgirs" => ["brigs"], "cehss" => ["chess"],
      "bdest" => ["debts"], "iloss" => ["silos", "soils"], "aghpr" => ["graph"],
      "chipr" => ["chirp"], "dglos" => ["golds"], "ackls" => ["slack", "lacks"],
      "allxy" => ["laxly"], "abnot" => ["baton"], "elnos" => ["noels"],
      "hloty" => ["hotly"], "aacln" => ["canal"], "affqu" => ["quaff"],
      "lnopy" => ["pylon"], "enrsw" => ["wrens"], "eelrs" => ["leers", "reels"],
      "cehst" => ["techs", "chest"], "ddoty" => ["toddy"],
      "deefr" => ["defer", "freed"], "eelop" => ["elope"], "ghsuy" => ["gushy"],
      "cdssu" => ["scuds"], "gnrtu" => ["grunt"], "aalns" => ["nasal"],
      "deesu" => ["suede"], "aeegr" => ["eager", "agree"], "addew" => ["waded"],
      "empty" => ["empty"], "eorrs" => ["sorer"], "ejkos" => ["jokes"],
      "aderw" => ["wader"], "fstuy" => ["fusty"], "agint" => ["giant"],
      "anssw" => ["swans"], "denot" => ["toned", "noted"], "eejlw" => ["jewel"],
      "eilnn" => ["linen"], "gnstu" => ["stung"], "afilr" => ["flair", "frail"],
      "cdeiv" => ["viced"], "demsu" => ["mused"], "cdeim" => ["medic"],
      "adirs" => ["raids"], "abehr" => ["rehab"], "ehllo" => ["hello"],
      "hilrw" => ["whirl"], "alost" => ["altos"], "mosuy" => ["mousy"],
      "elors" => ["loser", "roles"], "deoor" => ["rodeo"], "eprru" => ["purer"],
      "eintw" => ["twine"], "imppr" => ["primp"], "eessx" => ["sexes"],
      "egpru" => ["purge"], "acdey" => ["decay"], "rsstu" => ["truss", "rusts"],
      "dehpt" => ["depth"], "efmsu" => ["fumes"], "acdef" => ["decaf", "faced"],
      "aelsx" => ["axles"], "ademt" => ["mated", "tamed"], "egnsu" => ["genus"],
      "afluw" => ["awful"], "chhiw" => ["which"], "acden" => ["caned", "dance"],
      "bbtuy" => ["tubby"], "acips" => ["aspic"], "aggns" => ["gangs"],
      "doors" => ["roods", "doors"], "deery" => ["reedy"], "eemry" => ["emery"],
      "hnory" => ["horny"], "iorsv" => ["visor"], "achin" => ["china", "chain"],
      "copsu" => ["coups"], "aoptz" => ["topaz"], "abkly" => ["balky"],
      "cemot" => ["comet"], "agksw" => ["gawks"], "abelm" => ["amble", "blame"],
      "adrst" => ["darts"], "eppru" => ["upper"], "eimrx" => ["mixer"],
      "blrsu" => ["blurs"], "aksst" => ["tasks"], "answy" => ["yawns"],
      "celru" => ["lucre", "ulcer", "cruel"], "fklnu" => ["flunk"],
      "emosu" => ["mouse"], "aeort" => ["orate"], "abbek" => ["kebab"],
      "adent" => ["anted"], "ekloy" => ["yokel"],
      "arsty" => ["satyr", "artsy", "trays", "stray"], "ahory" => ["hoary"],
      "dioov" => ["ovoid"], "eoorw" => ["wooer"], "dootu" => ["outdo"],
      "hsstu" => ["shuts"], "affix" => ["affix"], "agnry" => ["rangy", "angry"],
      "moort" => ["motor"], "eimsx" => ["mixes"], "bettu" => ["butte"],
      "deekn" => ["kneed"], "prstu" => ["spurt"], "ekpsu" => ["pukes"],
      "agrss" => ["grass"], "eikss" => ["skies"], "aainv" => ["avian"],
      "anowy" => ["noway"], "deinx" => ["nixed", "index"], "aclot" => ["octal"],
      "hksuy" => ["husky"], "giosy" => ["yogis"],
      "agnor" => ["argon", "groan", "organ"], "adfrt" => ["draft"],
      "ciilt" => ["licit"], "aaenr" => ["arena"], "eekov" => ["evoke"],
      "eprss" => ["press"], "egnor" => ["goner"], "berry" => ["berry"],
      "enrvy" => ["nervy"], "bcdeu" => ["cubed"], "cikks" => ["kicks"],
      "deeil" => ["elide"], "defox" => ["foxed"],
      "inopt" => ["pinto", "piton", "point"], "cehiv" => ["chive"],
      "bdduy" => ["buddy"], "adefm" => ["famed"], "aerss" => ["sears"],
      "acort" => ["actor"], "abdir" => ["braid", "rabid"],
      "elorw" => ["rowel", "lower"], "oopsw" => ["swoop"], "achry" => ["chary"],
      "deegw" => ["wedge"], "dorsw" => ["sword", "words"], "ilstw" => ["wilts"],
      "cikky" => ["kicky"], "begoy" => ["bogey"], "knoos" => ["nooks"],
      "ijmmy" => ["jimmy"], "achps" => ["chaps"], "kloos" => ["looks"],
      "abwyy" => ["byway"], "ahlsw" => ["shawl"], "deikl" => ["liked"],
      "abssw" => ["swabs"], "elpst" => ["pelts", "slept"], "foors" => ["roofs"],
      "bhoot" => ["booth"], "ejkor" => ["joker"], "ailov" => ["viola"],
      "gloos" => ["logos"], "acsuy" => ["saucy"], "aeelv" => ["leave"],
      "deijv" => ["jived"], "ddesu" => ["dudes"], "lostv" => ["volts"],
      "addpy" => ["paddy"], "ehlow" => ["whole"], "aadeh" => ["ahead"],
      "cgiin" => ["icing"], "iklms" => ["milks"], "deeir" => ["eider"],
      "cckoy" => ["cocky"], "aensv" => ["naves", "vanes"], "acdis" => ["acids"],
      "achlr" => ["larch"], "gilny" => ["lying"], "abess" => ["bases"],
      "aefrw" => ["wafer"], "gotuy" => ["gouty"], "adesw" => ["sawed", "wades"],
      "anrsy" => ["yarns"], "oppsy" => ["soppy"], "denst" => ["dents", "tends"],
      "akmss" => ["masks"], "efint" => ["feint"], "ilors" => ["roils"],
      "abtty" => ["batty"], "hlsyy" => ["shyly"], "cloos" => ["cools"],
      "achlt" => ["latch"], "cenou" => ["ounce"], "agprs" => ["grasp"],
      "adesz" => ["adzes", "dazes"], "ilrtw" => ["twirl"], "admrs" => ["drams"],
      "pttuy" => ["putty"], "adnry" => ["randy"], "ccikl" => ["click"],
      "deilt" => ["tilde", "tiled"], "agmny" => ["mangy"], "esstt" => ["tests"],
      "beelv" => ["bevel"], "fsttu" => ["tufts"], "aaimr" => ["maria"],
      "bdeij" => ["jibed"], "esstw" => ["stews"], "aistv" => ["vista"],
      "ehilw" => ["while"], "abbel" => ["babel"], "cciiv" => ["civic"],
      "elrru" => ["ruler"], "amnow" => ["woman"], "bchnu" => ["bunch"],
      "hmnsy" => ["hymns"], "cfikl" => ["flick"], "afkly" => ["flaky"],
      "gnost" => ["tongs"], "acpst" => ["pacts"],
      "defil" => ["field", "filed", "flied"], "cikln" => ["clink"],
      "gmmuy" => ["gummy"], "orsty" => ["troys", "tyros", "story"],
      "ddoos" => ["dodos"], "eikms" => ["mikes"], "eimms" => ["mimes"],
      "aabes" => ["abase"], "chkos" => ["hocks", "shock"], "dgilu" => ["guild"],
      "abnrs" => ["barns"], "ehins" => ["shine"], "eegsu" => ["segue"],
      "adoss" => ["sodas"], "innoo" => ["onion"], "ampsu" => ["pumas"],
      "almps" => ["lamps", "palms", "psalm"], "agnps" => ["pangs"],
      "abbir" => ["rabbi"], "chlru" => ["churl", "lurch"], "afoot" => ["afoot"],
      "efgin" => ["feign"], "emopt" => ["tempo"], "eglos" => ["loges", "ogles"],
      "aeesv" => ["eaves"], "aahps" => ["pasha"], "aairt" => ["atria", "tiara"],
      "cikns" => ["nicks"], "aersz" => ["razes"], "aelmr" => ["lamer", "realm"],
      "eossu" => ["souse"], "eikrs" => ["skier"], "beooz" => ["booze"],
      "chhit" => ["hitch"], "aeepy" => ["payee"], "beeos" => ["obese"],
      "adhss" => ["shads"], "acrsy" => ["scary"], "cehko" => ["choke"],
      "emosv" => ["moves"], "alsty" => ["salty"], "adnsy" => ["sandy"],
      "cikst" => ["ticks", "stick"], "aekmr" => ["maker"], "mrstu" => ["strum"],
      "aijls" => ["jails"], "adnor" => ["radon", "adorn"], "afirr" => ["friar"],
      "deeft" => ["feted"], "degrs" => ["dregs"], "abelt" => ["bleat", "table"],
      "eltwy" => ["wetly"], "chmpu" => ["chump"], "elmsu" => ["mules"],
      "flosu" => ["fouls"], "ioprr" => ["prior"], "rsuuy" => ["usury"],
      "adhip" => ["aphid"], "afnsw" => ["fawns"], "ikqru" => ["quirk"],
      "lrwyy" => ["wryly"], "amost" => ["moats", "atoms"],
      "orstu" => ["torus", "tours", "routs"], "belly" => ["belly"],
      "amprs" => ["ramps"], "ailnp" => ["plain"], "efguu" => ["fugue"],
      "bdeel" => ["bleed"], "bdeox" => ["boxed"], "aabln" => ["banal"],
      "einst" => ["inset", "stein", "tines"], "aesty" => ["yeast"],
      "elost" => ["stole"], "aadmm" => ["madam"], "elnor" => ["loner"],
      "chikt" => ["thick"], "dgloy" => ["godly"], "densw" => ["wends"],
      "elmst" => ["melts", "smelt"], "ackrw" => ["wrack"], "lppuy" => ["pulpy"],
      "hipss" => ["ships"], "celnu" => ["uncle"], "ehitt" => ["tithe"],
      "ejkry" => ["jerky"], "ckost" => ["stock"], "einru" => ["inure", "urine"],
      "esstv" => ["vests"], "epsst" => ["pests", "steps"], "dkosu" => ["kudos"],
      "bmpsu" => ["bumps"], "egilu" => ["guile"], "glluy" => ["gully"],
      "cchik" => ["chick"], "cioru" => ["curio"], "aeikl" => ["alike"],
      "dekoy" => ["yoked"], "chino" => ["chino"], "ghhis" => ["highs"],
      "ceost" => ["cotes"], "abdly" => ["badly"], "aistw" => ["waist", "waits"],
      "deosu" => ["douse"], "adisy" => ["daisy"], "adist" => ["staid"],
      "aannw" => ["wanna"], "aessy" => ["essay"], "ahlsu" => ["hulas", "hauls"],
      "alrtw" => ["trawl"], "gmoor" => ["groom"], "beikr" => ["biker"],
      "adepr" => ["padre", "drape", "pared", "raped"], "iqstu" => ["quits"],
      "illrt" => ["trill"], "ackwy" => ["wacky"], "mossy" => ["mossy"],
      "eiipx" => ["pixie"], "achkw" => ["whack"], "ghotu" => ["tough", "ought"],
      "eiqtu" => ["quiet", "quite"], "adhor" => ["hoard"], "afils" => ["fails"],
      "lllos" => ["lolls"], "aimns" => ["mains"], "bdeno" => ["boned"],
      "eelps" => ["peels", "sleep"], "aftty" => ["fatty"], "boors" => ["boors"],
      "abdln" => ["bland"], "allsy" => ["sally"], "elstu" => ["lutes"],
      "bkluy" => ["bulky"], "ehosw" => ["whose"], "densv" => ["vends"],
      "eirsw" => ["weirs", "wires", "wiser"], "bflsu" => ["flubs"],
      "ehpsy" => ["hypes"], "aektw" => ["tweak"], "eefls" => ["flees", "feels"],
      "gilnt" => ["glint"], "coops" => ["coops", "scoop"],
      "deorv" => ["roved", "drove"], "ejlls" => ["jells"],
      "alosv" => ["salvo", "ovals"], "addei" => ["aided"], "cehit" => ["ethic"],
      "adiov" => ["avoid"], "iopsu" => ["pious"], "ersst" => ["tress", "rests"],
      "aefir" => ["afire"], "adlns" => ["lands"], "deost" => ["dotes"],
      "almss" => ["slams"], "eijsv" => ["jives"], "besty" => ["bytes"],
      "foops" => ["spoof"], "foost" => ["foots"], "abegn" => ["began"],
      "frssu" => ["surfs"], "aelpp" => ["apple"], "afhrw" => ["wharf"],
      "dotty" => ["dotty"], "ademx" => ["maxed"], "aeknw" => ["waken"],
      "girst" => ["girts", "grist", "grits"], "aisvv" => ["vivas"],
      "mmmuy" => ["mummy"], "beefy" => ["beefy"], "egisv" => ["gives"],
      "bdlno" => ["blond"], "aglot" => ["gloat"], "aberr" => ["barer"],
      "eentt" => ["tenet"], "fglnu" => ["flung"], "eipqu" => ["pique", "equip"],
      "eflmu" => ["flume"], "ffhiw" => ["whiff"], "eeilt" => ["elite"],
      "ejlly" => ["jelly"], "abekl" => ["bleak"], "ceesx" => ["execs"],
      "loprw" => ["prowl"], "adegw" => ["waged"], "cdery" => ["decry"],
      "msstu" => ["musts", "smuts"], "deorw" => ["rowed"], "morwy" => ["wormy"],
      "ailpt" => ["plait"], "hooss" => ["shoos"], "eiprv" => ["viper"],
      "adgru" => ["guard"], "adert" => ["tared", "rated", "trade", "tread"],
      "cfklo" => ["flock"], "imopu" => ["opium"], "fnost" => ["fonts"],
      "acllo" => ["local"], "dehmo" => ["homed"], "abbot" => ["abbot"],
      "nosst" => ["snots"], "elpry" => ["reply"], "acehl" => ["leach"],
      "ckory" => ["rocky"], "ggipy" => ["piggy"], "adnsw" => ["dawns", "wands"],
      "acsst" => ["scats", "casts"], "bmnsu" => ["numbs"], "egstu" => ["guest"],
      "acdss" => ["scads"], "efins" => ["fines"], "inosy" => ["noisy"],
      "aekls" => ["lakes", "leaks", "slake"], "ghstu" => ["thugs"],
      "enrsu" => ["runes", "nurse"], "ainsw" => ["swain"], "aginr" => ["grain"],
      "aerrr" => ["rarer"], "fgiln" => ["fling"], "illrs" => ["rills"],
      "gnopr" => ["prong"], "beorr" => ["borer"], "eeltx" => ["telex"],
      "deesx" => ["sexed"], "aacdh" => ["dacha"], "iklls" => ["kills", "skill"],
      "einop" => ["opine"], "ehops" => ["hopes"], "aepsu" => ["pause"],
      "deisz" => ["sized"], "empst" => ["temps"], "ceefn" => ["fence"],
      "acmos" => ["comas"], "eprtw" => ["twerp"], "epppy" => ["peppy"],
      "aluuv" => ["uvula"], "aefsz" => ["fazes"], "iijnn" => ["jinni"],
      "cjkos" => ["jocks"], "npstu" => ["punts"], "ellsy" => ["yells"],
      "bcehl" => ["belch"], "ejkrs" => ["jerks"], "acmpy" => ["campy"],
      "cdenu" => ["dunce"], "belos" => ["boles", "lobes"],
      "acerv" => ["carve", "crave"], "cikss" => ["sicks"], "booyz" => ["boozy"],
      "dells" => ["dells"], "depty" => ["typed"], "ginru" => ["ruing"],
      "coprs" => ["corps", "crops"], "chmnu" => ["munch"], "aginx" => ["axing"],
      "hinss" => ["shins"], "fhist" => ["shift"], "dfirt" => ["drift"],
      "ilosv" => ["viols"], "aerrw" => ["rawer"], "dlops" => ["plods"],
      "aberz" => ["zebra"], "censt" => ["cents", "scent"], "aeins" => ["anise"],
      "aakky" => ["kayak"], "hmsuy" => ["mushy"], "denos" => ["nosed", "nodes"],
      "orttu" => ["trout", "tutor"], "egins" => ["singe"],
      "densu" => ["dunes", "nudes"], "aeilm" => ["email"], "dgiit" => ["digit"],
      "nsttu" => ["stunt"], "abegl" => ["bagel", "gable"], "aorrs" => ["roars"],
      "eptty" => ["petty"], "afmoy" => ["foamy"], "erstu" => ["trues"],
      "hoops" => ["poohs", "hoops"], "aehlv" => ["halve"], "oopps" => ["poops"],
      "egoru" => ["rogue", "rouge"], "hmptu" => ["thump"],
      "aelsv" => ["vales", "salve", "slave"], "cdeko" => ["coked"],
      "ehirs" => ["heirs", "shire", "hires"], "knnow" => ["known"],
      "dopru" => ["proud"], "deors" => ["doers"], "aenry" => ["yearn"],
      "ginsu" => ["suing", "using"], "iklst" => ["kilts"], "ceins" => ["since"],
      "ahiry" => ["hairy"], "aailv" => ["avail"], "ffhsu" => ["huffs"],
      "allty" => ["tally"], "admno" => ["nomad"], "dgrsu" => ["drugs"],
      "einos" => ["noise"], "acdev" => ["caved"], "ckluy" => ["lucky"],
      "corss" => ["cross"], "aehlz" => ["hazel"], "ilpss" => ["lisps", "slips"],
      "aadeg" => ["adage"], "adetx" => ["taxed"], "bdeit" => ["bidet", "debit"],
      "bgnsu" => ["bungs"], "ahntu" => ["haunt"], "ampst" => ["tamps", "stamp"],
      "cfksu" => ["fucks"], "beefs" => ["beefs"], "agist" => ["gaits"],
      "eelrv" => ["lever", "revel"], "moopr" => ["promo"], "degju" => ["judge"],
      "dginy" => ["dingy", "dying"], "agnst" => ["angst", "gnats", "tangs"],
      "abeov" => ["above"], "bcehn" => ["bench"], "bcitu" => ["cubit"],
      "aepsv" => ["vapes", "paves"], "flops" => ["flops"], "ckmsu" => ["mucks"],
      "abotu" => ["about"], "efltu" => ["flute"], "abdns" => ["bands"],
      "eikls" => ["likes"], "deinw" => ["widen", "wined"], "demno" => ["demon"],
      "cdilu" => ["lucid"], "eeegs" => ["geese"], "artwy" => ["warty"],
      "adept" => ["adept", "taped"], "afmrs" => ["farms"], "opprs" => ["props"],
      "aertx" => ["extra"], "ehnoy" => ["honey"], "alnsw" => ["lawns"],
      "ehrtw" => ["threw"], "aerwy" => ["weary"], "bbooy" => ["booby"],
      "deoww" => ["wowed"], "aclos" => ["colas", "coals"], "aehsz" => ["hazes"],
      "demns" => ["mends"], "crstu" => ["crust"], "besuz" => ["zebus"],
      "ddgiy" => ["giddy"], "nossw" => ["snows"], "ccely" => ["cycle"],
      "gootu" => ["outgo"], "dmoos" => ["moods", "dooms"], "ekrtw" => ["twerk"],
      "elmos" => ["moles"], "ikmss" => ["skims"], "ainop" => ["piano"],
      "denow" => ["endow", "owned"], "aesst" => ["sates", "asset", "seats"],
      "adims" => ["maids"], "illqu" => ["quill"], "aacrt" => ["carat"],
      "lrsuy" => ["surly"], "ehooy" => ["hooey"], "elnwy" => ["newly"],
      "hkooy" => ["hooky"], "bffsu" => ["buffs"], "allry" => ["rally"],
      "ackor" => ["croak"], "delns" => ["lends"], "agssw" => ["swags"],
      "drstu" => ["turds"], "deffo" => ["offed"], "allst" => ["stall"],
      "clmpu" => ["clump"], "agins" => ["gains"], "abems" => ["beams"],
      "ddeiv" => ["dived"], "deooz" => ["oozed"], "cfios" => ["coifs"],
      "illss" => ["sills"], "aprsw" => ["warps", "wraps"],
      "deins" => ["snide", "dines"], "ceops" => ["copse", "copes", "scope"],
      "acefh" => ["chafe"], "cffos" => ["scoff"], "aqstu" => ["squat"],
      "aalnt" => ["natal"], "dkuuz" => ["kudzu"], "cloyy" => ["coyly"],
      "billy" => ["billy"], "alors" => ["orals", "solar"], "emorw" => ["mower"],
      "ipswy" => ["wispy"], "bekor" => ["broke"], "lopst" => ["plots"],
      "dgins" => ["dings"], "deirr" => ["direr", "drier", "rider"],
      "aostu" => ["autos"], "acmss" => ["scams"], "acfrs" => ["scarf"],
      "ceflt" => ["cleft"], "fiinx" => ["infix"], "aklrs" => ["larks"],
      "dimst" => ["midst"], "cinos" => ["scion", "sonic", "coins", "icons"],
      "chill" => ["chill"], "eikln" => ["liken"], "ilnos" => ["lions", "loins"],
      "aknsw" => ["swank"], "eegrs" => ["serge"], "bghou" => ["bough"],
      "cfhin" => ["finch"], "egisu" => ["guise"], "aflps" => ["flaps"],
      "aelnu" => ["ulnae"], "ceekr" => ["creek"], "ckpsu" => ["pucks"],
      "abdet" => ["bated"], "aefrt" => ["after"], "imost" => ["moist", "omits"],
      "costu" => ["scout"], "ceilr" => ["relic"], "abdsu" => ["daubs"],
      "ilsty" => ["styli"], "aorvy" => ["ovary"], "abnor" => ["baron"],
      "ekrst" => ["treks"], "hiknt" => ["think"], "cersu" => ["cures", "curse"],
      "adenw" => ["waned"], "aglls" => ["galls"],
      "ahstw" => ["swath", "thaws", "whats"], "aeevw" => ["weave"],
      "adehz" => ["hazed"], "akptu" => ["kaput"], "acrst" => ["carts"],
      "agnot" => ["tango"], "ddeir" => ["redid", "dried"], "inptu" => ["input"],
      "eissv" => ["vises"], "gissw" => ["swigs"], "alnos" => ["salon", "loans"],
      "aeivw" => ["waive"], "deikn" => ["inked"], "bchir" => ["birch"],
      "abers" => ["bares", "baser", "bears"], "giltz" => ["glitz"],
      "emssu" => ["muses"], "llnsu" => ["nulls"],
      "beors" => ["robes", "bores", "sober"], "chnot" => ["notch"],
      "afikr" => ["fakir"], "aeemn" => ["enema"], "ilrsw" => ["swirl"],
      "ilnvy" => ["vinyl"], "abmmo" => ["mambo"], "eiklr" => ["liker"],
      "ainry" => ["rainy"], "cikrs" => ["ricks"], "dhnou" => ["hound"],
      "binry" => ["briny"], "ackrt" => ["track"], "opsty" => ["typos"],
      "eenqu" => ["queen"], "illms" => ["mills"], "hortt" => ["troth"],
      "deevx" => ["vexed"], "celno" => ["clone"], "fimrs" => ["firms"],
      "adils" => ["dials"], "alopr" => ["polar"], "deltw" => ["dwelt"],
      "ainst" => ["antis", "satin", "stain", "saint"], "rstuy" => ["rusty"],
      "kllsu" => ["skull"], "eemms" => ["memes"], "cikps" => ["picks"],
      "cptuu" => ["cutup"], "aejps" => ["japes"], "giltu" => ["guilt"],
      "adhij" => ["jihad"], "adeim" => ["aimed", "media"], "ehrsu" => ["usher"],
      "abcrt" => ["bract"], "gimpy" => ["gimpy"], "ffpuy" => ["puffy"],
      "bdery" => ["derby"], "corsw" => ["crows"], "acfrt" => ["craft"],
      "ksstu" => ["tusks"], "chouv" => ["vouch"], "cdorw" => ["crowd"],
      "alppu" => ["pupal"], "aefls" => ["fleas", "leafs", "false"],
      "ablls" => ["balls"], "akkop" => ["kapok"], "acmps" => ["scamp", "camps"],
      "aegru" => ["auger", "argue"], "anopr" => ["apron"], "alswy" => ["yawls"],
      "abnrw" => ["brawn"], "llops" => ["polls"], "egouv" => ["vogue"],
      "artty" => ["ratty"], "aelnp" => ["penal", "panel", "plane"],
      "hinsy" => ["shiny"], "achmp" => ["champ"], "ajyzz" => ["jazzy"],
      "achtw" => ["watch"], "aelos" => ["aloes"], "adinv" => ["divan", "viand"],
      "ddeen" => ["ended"], "ceeip" => ["piece"], "eelmm" => ["lemme"],
      "assty" => ["stays"], "adehl" => ["haled"], "aistx" => ["taxis"],
      "adilt" => ["tidal"], "filoo" => ["folio"], "dekss" => ["desks"],
      "norst" => ["snort"], "ailst" => ["tails"], "effis" => ["fiefs", "fifes"],
      "acepr" => ["crape", "caper", "recap"], "cefhi" => ["fiche", "chief"],
      "beosy" => ["obeys"], "adqsu" => ["quads", "squad"], "innny" => ["ninny"],
      "epssw" => ["spews"], "hmnot" => ["month"], "cddeo" => ["coded"],
      "ijlst" => ["jilts"], "ahmnu" => ["human"], "hinor" => ["rhino"],
      "deimx" => ["mixed"], "eensv" => ["evens", "seven"],
      "acdep" => ["caped", "paced"], "aeirs" => ["arise", "raise"],
      "ahmss" => ["shams", "smash"], "aflsw" => ["flaws"], "aborx" => ["borax"],
      "binos" => ["bison"], "adguy" => ["gaudy"], "deikm" => ["miked"],
      "glloy" => ["golly"], "adfrw" => ["dwarf"], "kkooy" => ["kooky"],
      "cemry" => ["mercy"], "ahqsu" => ["quash"], "fhort" => ["froth", "forth"],
      "acnop" => ["capon"], "aqsuw" => ["squaw"], "cfmoy" => ["comfy"],
      "dloor" => ["drool"], "dempu" => ["umped"], "dhirt" => ["third"],
      "aaemz" => ["amaze"], "borru" => ["burro"], "iprvy" => ["privy"],
      "knpsu" => ["punks", "spunk"], "ghhit" => ["thigh"], "cikpy" => ["picky"],
      "aarry" => ["array"], "ipsty" => ["tipsy"], "aimno" => ["amino"],
      "eilnr" => ["liner"], "eggly" => ["leggy"], "anpsw" => ["pawns", "spawn"],
      "eiprt" => ["tripe"], "noops" => ["snoop", "spoon"], "aeluv" => ["value"],
      "aaekw" => ["awake"], "eemst" => ["metes", "teems", "meets"],
      "hiopp" => ["hippo"], "eissx" => ["sixes"], "denss" => ["sends"],
      "adels" => ["dales", "lades", "deals", "leads"],
      "eorss" => ["roses", "sores"], "aenns" => ["senna"], "instu" => ["units"],
      "hknos" => ["honks"], "aeimn" => ["anime"], "opppy" => ["poppy"],
      "ehosu" => ["house"], "aasty" => ["satay"], "egimr" => ["grime"],
      "acent" => ["enact"], "korst" => ["stork"], "bdoor" => ["brood"],
      "ablsw" => ["bawls"], "achmt" => ["match"], "doprs" => ["prods", "drops"],
      "eorrv" => ["rover"], "ahiku" => ["haiku"], "ceopu" => ["coupe"],
      "eknsu" => ["nukes"], "acesu" => ["sauce", "cause"], "ciily" => ["icily"],
      "ahhrs" => ["harsh"], "ghoru" => ["rough"], "cdhil" => ["child"],
      "aglno" => ["along"], "dimtu" => ["tumid"], "celsu" => ["clues"],
      "lmpsu" => ["plums", "slump", "lumps"], "gilst" => ["gilts"],
      "dllor" => ["droll"], "emott" => ["totem"], "agily" => ["gaily"],
      "dllsu" => ["dulls"], "eenty" => ["teeny"], "flrsu" => ["furls"],
      "aillv" => ["villa"], "acnno" => ["canon"], "aemnv" => ["maven"],
      "ailtv" => ["vital"], "oowyz" => ["woozy"], "bhoos" => ["hobos"],
      "deorr" => ["order"], "adess" => ["sades"], "optty" => ["potty"],
      "bnstu" => ["bunts"], "cehpr" => ["perch"], "aagin" => ["again"],
      "eglsu" => ["glues"], "abdeo" => ["abode", "adobe"],
      "ginst" => ["sting", "tings"], "deksu" => ["dukes"], "aadin" => ["naiad"],
      "egrsu" => ["surge", "urges"], "gkoos" => ["gooks"], "aptty" => ["patty"],
      "eopxy" => ["epoxy"], "dksuy" => ["dusky"], "abjms" => ["jambs"],
      "emmos" => ["memos"], "aagnp" => ["pagan"], "bnssu" => ["snubs"],
      "eilst" => ["islet", "stile", "tiles"], "bgosu" => ["bogus"],
      "asswy" => ["sways"], "eeisz" => ["seize"], "accoo" => ["cocoa"],
      "aagls" => ["galas"], "choop" => ["pooch"], "aboot" => ["taboo"],
      "aemss" => ["mesas", "sames", "seams"], "gnosw" => ["gowns"],
      "hpsuy" => ["pushy"], "ahprs" => ["harps", "sharp"], "abcel" => ["cable"],
      "cfosu" => ["focus"], "adeiu" => ["adieu"], "aalpz" => ["plaza"],
      "aemsx" => ["maxes", "exams"], "aioss" => ["oasis"], "bdirs" => ["birds"],
      "abceh" => ["beach"], "acinr" => ["cairn"], "hipty" => ["pithy"],
      "sttuu" => ["tutus"], "deemw" => ["mewed"], "bestu" => ["tubes"],
      "adlrw" => ["drawl"], "brstu" => ["burst"], "hknsu" => ["hunks"],
      "impsw" => ["wimps"], "orsst" => ["sorts"],
      "illst" => ["lilts", "tills", "still"], "acipr" => ["carpi"],
      "deesw" => ["sewed", "weeds"], "fintu" => ["unfit"], "ddego" => ["dodge"],
      "eknot" => ["token"], "acgir" => ["cigar"], "ffflu" => ["fluff"],
      "accir" => ["circa"], "efirs" => ["fires", "fries"],
      "cdeos" => ["coeds", "codes"], "adffy" => ["daffy"], "abemy" => ["maybe"],
      "cdhuy" => ["duchy"], "deist" => ["diets", "sited", "tides", "edits"],
      "agnsw" => ["gnaws"], "bgmou" => ["gumbo"], "arstt" => ["tarts", "start"],
      "hlosw" => ["howls"], "deilm" => ["limed"], "achov" => ["havoc"],
      "eipss" => ["spies"], "bilsy" => ["sibyl"], "acksw" => ["wacks"],
      "adgls" => ["glads"], "aennx" => ["annex"], "acdos" => ["codas"],
      "ckoor" => ["crook"], "einpr" => ["ripen"], "aegrw" => ["wager"],
      "inppy" => ["nippy"], "deelr" => ["elder"], "dorss" => ["dross"],
      "chior" => ["choir"], "alott" => ["total"], "abouy" => ["bayou"],
      "estty" => ["testy"], "illsw" => ["swill", "wills"], "acilv" => ["cavil"],
      "abkss" => ["basks"], "efsst" => ["fests"], "accht" => ["catch"],
      "adoty" => ["toady", "today"], "aorst" => ["taros", "roast", "sorta"],
      "iimmn" => ["minim"], "eegis" => ["siege"],
      "adest" => ["sated", "stead", "dates"], "adfru" => ["fraud"],
      "aeert" => ["eater"], "gnoos" => ["goons"], "aclor" => ["carol", "coral"],
      "aehps" => ["heaps", "phase", "shape"], "aemuv" => ["mauve"],
      "emnsu" => ["menus"],
      "acert" => ["caret", "crate", "cater", "react", "trace"],
      "deimr" => ["rimed", "dimer", "mired"],
      "demos" => ["demos", "domes", "modes"], "deest" => ["steed"],
      "aemnt" => ["meant"], "aeors" => ["arose"], "eissu" => ["issue"],
      "cemor" => ["comer"], "aefkl" => ["flake"], "aaklo" => ["koala"],
      "bdeer" => ["breed"], "aeiln" => ["alien"], "cilps" => ["clips"],
      "aelpr" => ["paler", "pearl"], "aervw" => ["waver"], "eirtt" => ["trite"],
      "adeno" => ["anode"],
      "abest" => ["betas", "bates", "abets", "baste", "beast", "beats"],
      "cprty" => ["crypt"], "aeswx" => ["waxes"], "fgoor" => ["forgo"],
      "ooprs" => ["spoor"], "bersu" => ["rebus", "rubes"], "akqru" => ["quark"],
      "ablmy" => ["balmy"], "enooz" => ["ozone"], "noost" => ["snoot"],
      "bersv" => ["verbs"], "abhit" => ["habit"], "fghit" => ["fight"],
      "adeft" => ["fated"], "deikp" => ["piked"], "aally" => ["allay"],
      "deopr" => ["pored", "roped"], "clrsu" => ["curls"], "chpsy" => ["psych"],
      "ackps" => ["packs"], "eilmp" => ["impel"], "chosw" => ["chows"],
      "amrry" => ["marry"], "emnov" => ["venom"], "ilppu" => ["pupil"],
      "achno" => ["nacho"], "bblos" => ["blobs"], "efirx" => ["fixer"],
      "adipr" => ["rapid"], "illps" => ["pills", "spill"], "aqsuy" => ["quays"],
      "adeks" => ["asked"], "dfilu" => ["fluid"], "cekrw" => ["wreck"],
      "aghns" => ["gnash", "hangs"], "ainno" => ["anion"], "asssy" => ["sassy"],
      "loopy" => ["loopy"], "ekpsy" => ["pesky"], "ailrv" => ["viral", "rival"],
      "cnory" => ["corny", "crony"], "aginp" => ["aping"], "ahsst" => ["stash"],
      "agimn" => ["gamin"], "almru" => ["mural"], "aboss" => ["basso"],
      "aaprt" => ["apart"], "bgguy" => ["buggy"], "inors" => ["rosin", "irons"],
      "dlluy" => ["dully"], "eenss" => ["sense"], "ginsw" => ["swing", "wings"],
      "ffstu" => ["stuff"], "orstt" => ["torts", "trots"], "begnu" => ["begun"],
      "affty" => ["taffy"], "bkoor" => ["brook"], "instt" => ["stint", "tints"],
      "addde" => ["added"], "hhips" => ["phish"], "films" => ["milfs", "films"],
      "bbeop" => ["bebop"], "acknr" => ["crank"], "elssu" => ["slues"],
      "astty" => ["tasty"], "agimo" => ["amigo"],
      "emost" => ["motes", "smote", "tomes"], "aimss" => ["amiss"],
      "llort" => ["troll"], "eistx" => ["exits", "exist"], "bikln" => ["blink"],
      "aglns" => ["slang"], "blnoy" => ["nobly"], "acegy" => ["cagey"],
      "ciimm" => ["mimic"], "clnoo" => ["colon"],
      "aceps" => ["capes", "paces", "space"], "ceitw" => ["twice"],
      "epsxy" => ["pyxes"], "aabls" => ["balsa", "basal"], "anstw" => ["wants"],
      "ackqu" => ["quack"], "ginow" => ["owing"], "aglnr" => ["gnarl"],
      "moott" => ["motto"], "adopt" => ["adopt"], "aegnv" => ["vegan"],
      "deims" => ["deism", "dimes"], "bdeln" => ["blend"],
      "eoprs" => ["poser", "pores", "ropes", "spore", "prose"],
      "adisv" => ["divas"], "ahppy" => ["happy"], "eiors" => ["osier"],
      "aehst" => ["haste", "hates", "heats"], "aflsy" => ["flays"],
      "fllsu" => ["fulls"], "ailny" => ["inlay"], "aijnn" => ["ninja"],
      "aalmr" => ["alarm"], "cijuy" => ["juicy"], "boowx" => ["oxbow"],
      "afnsu" => ["fauns", "snafu"], "lopss" => ["slops"], "morsw" => ["worms"],
      "cklnu" => ["clunk"], "deips" => ["spied"], "adlly" => ["dally"],
      "bprsu" => ["burps"], "adegp" => ["gaped", "paged"], "befgo" => ["befog"],
      "adnss" => ["sands"], "abiss" => ["basis"], "anpst" => ["pants"],
      "efiln" => ["elfin"], "emptt" => ["tempt"], "dhoos" => ["hoods"],
      "epsty" => ["types"], "eehls" => ["heels"], "mppsu" => ["pumps"],
      "ffijy" => ["jiffy"], "denrt" => ["trend"], "aehlt" => ["lathe"],
      "ghnot" => ["thong"], "fknsu" => ["funks"], "bchit" => ["bitch"],
      "acrtt" => ["tract"], "aglos" => ["goals"], "agkwy" => ["gawky"],
      "gilno" => ["login", "lingo"], "achop" => ["poach"], "dmpuy" => ["dumpy"],
      "fglos" => ["flogs", "golfs"], "cello" => ["cello"], "kklsu" => ["skulk"],
      "ehlms" => ["helms"], "abnns" => ["banns"], "ceiov" => ["voice"],
      "alpss" => ["slaps"], "oopst" => ["stoop"], "ailms" => ["mails"],
      "ccimo" => ["comic"], "amnor" => ["manor", "roman"],
      "abekr" => ["baker", "brake", "break"], "aersy" => ["years"],
      "acegs" => ["cages"], "eflsu" => ["flues", "fuels"],
      "beest" => ["beets", "beset"], "deens" => ["dense", "needs"],
      "cepss" => ["specs"], "abeiz" => ["baize"], "eiltt" => ["title"],
      "aehsv" => ["haves", "shave"], "fkors" => ["forks"], "chinw" => ["winch"],
      "dffos" => ["doffs"], "deguy" => ["guyed"], "ikmps" => ["skimp"],
      "imrst" => ["trims"], "achmo" => ["mocha", "macho"], "aaguv" => ["guava"],
      "afflo" => ["offal"], "acelm" => ["camel"], "alnnu" => ["annul"],
      "lmssu" => ["slums"], "adegz" => ["gazed"], "ddemo" => ["domed"],
      "chmsu" => ["chums"], "defix" => ["fixed"], "ckstu" => ["tucks", "stuck"],
      "enopy" => ["peony"], "eeksw" => ["weeks"], "acdit" => ["dicta"],
      "eesvx" => ["vexes"], "akors" => ["okras"], "eforz" => ["froze"],
      "dgino" => ["dingo", "doing"], "biknr" => ["brink"], "aefsx" => ["faxes"],
      "almqu" => ["qualm"], "fhlsu" => ["flush"], "adeps" => ["spade"],
      "ghosu" => ["sough"], "ehmos" => ["homes"], "glosw" => ["glows"],
      "deemn" => ["emend"], "imsst" => ["mists"], "afmos" => ["foams"],
      "hinnt" => ["ninth"], "ahpss" => ["hasps"], "aenov" => ["novae"],
      "ciprs" => ["scrip", "crisp"], "ipssw" => ["wisps"], "ehilx" => ["helix"],
      "prsuy" => ["syrup"], "noopr" => ["porno"], "orstw" => ["worst"],
      "ehiss" => ["shies"], "opsuy" => ["soupy"], "enswy" => ["newsy"],
      "eiisv" => ["ivies"], "besst" => ["bests"], "acgor" => ["cargo"],
      "abcis" => ["basic"], "aostt" => ["stoat", "toast"], "aabms" => ["samba"],
      "cerru" => ["curer", "recur"], "bllos" => ["bolls"], "npsuu" => ["sunup"],
      "oorrt" => ["rotor"], "derry" => ["dryer"],
      "flosw" => ["fowls", "wolfs", "flows"],
      "bertu" => ["tuber", "brute", "rebut"], "acess" => ["cases"],
      "eqruy" => ["query"], "efnrs" => ["ferns"], "borsw" => ["brows"],
      "ehrsy" => ["shyer"], "dnosu" => ["sound"], "prrsu" => ["purrs"],
      "blruy" => ["burly"], "elorv" => ["lover"], "eiprr" => ["riper"],
      "aoppp" => ["poppa"], "aadrw" => ["award"], "bknos" => ["knobs"],
      "bddeo" => ["boded"], "bglos" => ["globs", "blogs"], "adlsy" => ["sadly"],
      "cefhs" => ["chefs"], "deemt" => ["meted"], "dfors" => ["fords"],
      "cchku" => ["chuck"], "aalms" => ["lamas"], "afhls" => ["flash"],
      "denpu" => ["upend"], "beeil" => ["belie"], "ceklr" => ["clerk"],
      "aclls" => ["calls"], "hikrs" => ["shirk"], "denru" => ["nuder", "under"],
      "ehmor" => ["homer"], "acnrs" => ["narcs"], "emrsu" => ["serum"],
      "adost" => ["toads"], "abegt" => ["begat"], "ahost" => ["oaths"],
      "adeis" => ["aides", "aside", "ideas"], "eirtv" => ["rivet"],
      "abrst" => ["brats"], "empsu" => ["spume"], "befit" => ["befit"],
      "efirt" => ["refit"], "acfst" => ["facts"], "abeks" => ["beaks", "bakes"],
      "asstt" => ["stats"], "hmotu" => ["mouth"], "psttu" => ["putts"],
      "adely" => ["delay"], "kllno" => ["knoll"], "ehost" => ["ethos", "those"],
      "delor" => ["older"], "aflst" => ["flats"], "eflos" => ["floes"],
      "abdor" => ["broad", "board"], "ffity" => ["fifty"],
      "abgrs" => ["brags", "garbs", "grabs"], "instw" => ["twins"],
      "dehir" => ["hired"], "hrstu" => ["hurts"], "aegsu" => ["usage"],
      "adiir" => ["radii"], "achnr" => ["ranch"], "gimry" => ["grimy"],
      "bcesu" => ["cubes"], "iklsy" => ["silky"], "effor" => ["offer"],
      "aeips" => ["sepia"], "ceisv" => ["vices"], "eepru" => ["rupee", "puree"],
      "fknuy" => ["funky"], "dhstu" => ["thuds"], "aefss" => ["safes"],
      "adekr" => ["drake", "raked"], "bllsu" => ["bulls"],
      "deilp" => ["piled", "plied"], "eippr" => ["piper"], "dnosw" => ["downs"],
      "glstu" => ["gluts"], "enovy" => ["envoy"], "eefrv" => ["fever"],
      "jmpuy" => ["jumpy"], "pssuy" => ["pussy"], "aclns" => ["clans"],
      "adrty" => ["tardy"], "bdelu" => ["lubed", "blued"], "efhrs" => ["fresh"],
      "ffhit" => ["fifth"], "achls" => ["clash"], "forty" => ["forty"],
      "deelv" => ["delve"], "inpss" => ["snips", "spins"], "ehrtz" => ["hertz"],
      "hssuy" => ["hussy"], "aclss" => ["class"], "deesy" => ["seedy"],
      "adinr" => ["nadir", "drain"], "aeknt" => ["taken"], "cmsuu" => ["mucus"],
      "adefx" => ["faxed"], "cdhor" => ["chord"], "hinwy" => ["whiny"],
      "ahpsw" => ["pshaw"], "aprss" => ["rasps", "spars"], "eequu" => ["queue"],
      "einps" => ["penis", "pines", "snipe", "spine"], "ablwy" => ["bylaw"],
      "ehlos" => ["holes"], "aegnt" => ["agent"], "cehtv" => ["vetch"],
      "cckos" => ["cocks"], "gimoz" => ["gizmo"], "ceorv" => ["cover"],
      "gilns" => ["sling"], "aaort" => ["aorta"], "oprxy" => ["proxy"],
      "adehy" => ["hayed", "heady"], "eegmr" => ["merge"], "dills" => ["dills"],
      "bdens" => ["bends"], "ckoss" => ["socks"], "acnot" => ["canto"],
      "eoosz" => ["oozes"], "irstw" => ["writs", "wrist"], "chhnu" => ["hunch"],
      "ablmu" => ["album"], "arsst" => ["stars"], "chknu" => ["chunk"],
      "clnow" => ["clown"], "abder" => ["debar", "bared", "beard", "bread"],
      "ehirt" => ["their"], "accuy" => ["yucca"], "filos" => ["foils"],
      "eirtw" => ["write"], "aehms" => ["shame"], "deilv" => ["devil", "lived"],
      "ahrst" => ["harts", "trash"], "mnoor" => ["moron"],
      "aflot" => ["aloft", "float"], "ampsw" => ["swamp"],
      "einsw" => ["sinew", "swine", "wines"],
      "deirs" => ["sired", "dries", "rides"], "bceks" => ["becks"],
      "dmrsu" => ["drums"], "bmoos" => ["booms", "bosom"], "beiks" => ["bikes"],
      "hloss" => ["slosh"], "enovw" => ["woven"], "aacco" => ["cacao"],
      "cdehi" => ["chide"], "ccehk" => ["check"], "eelst" => ["sleet", "steel"],
      "chops" => ["chops"], "alnst" => ["slant"], "acrsw" => ["craws"],
      "alpsy" => ["palsy", "splay", "plays"], "fimtu" => ["mufti"],
      "dhlos" => ["holds"], "eipsw" => ["swipe", "wipes"], "chimp" => ["chimp"],
      "destu" => ["duets"], "dggoy" => ["doggy"], "dnopu" => ["pound"],
      "abiit" => ["tibia"], "dilos" => ["idols", "solid"], "eisss" => ["sises"],
      "dertu" => ["trued"], "aopss" => ["soaps"], "allot" => ["atoll", "allot"],
      "achpt" => ["patch"], "agnss" => ["sangs", "snags"], "bknsu" => ["bunks"],
      "aeguv" => ["vague"], "ilmns" => ["limns"], "ehors" => ["shore", "horse"],
      "aegmn" => ["mange"], "ddeor" => ["odder"], "cdrsu" => ["curds"],
      "adeir" => ["aired"], "afisw" => ["waifs"], "aehlr" => ["haler"],
      "imnor" => ["minor"], "eiqru" => ["quire"], "bnoos" => ["boons"],
      "agnrt" => ["grant"], "ehosv" => ["shove"], "beell" => ["belle"],
      "eklln" => ["knell"], "cdeor" => ["credo", "decor", "cored"],
      "illsy" => ["silly"], "aails" => ["alias"], "einsv" => ["veins", "vines"],
      "aeprt" => ["prate", "apter", "taper"], "eprsy" => ["preys", "pyres"],
      "hills" => ["shill", "hills"], "acmmo" => ["comma"],
      "efils" => ["files", "flies"], "aglow" => ["aglow"],
      "aemrs" => ["mares", "reams", "smear"], "ginps" => ["pings"],
      "efilt" => ["filet"], "abcss" => ["scabs"], "ekssw" => ["skews"],
      "dillr" => ["drill"], "aciil" => ["cilia"], "bossy" => ["bossy"],
      "iklss" => ["silks"], "chikn" => ["chink"], "bersw" => ["brews"],
      "beelr" => ["rebel"], "eestw" => ["weest", "sweet"], "emosy" => ["mosey"],
      "horsu" => ["hours"], "eemrt" => ["meter"], "nntuy" => ["tunny"],
      "achkl" => ["chalk"], "aeess" => ["eases"], "osstw" => ["stows"],
      "efirv" => ["fiver"], "eenrv" => ["nerve", "never"], "cchou" => ["couch"],
      "closy" => ["cloys"], "achor" => ["roach"], "efikn" => ["knife"],
      "ehklw" => ["whelk"], "oprsy" => ["prosy"], "admps" => ["damps"],
      "abfrs" => ["barfs"], "adefr" => ["fared"], "korsw" => ["works"],
      "gpsyy" => ["gypsy"], "cmors" => ["corms"], "aekly" => ["leaky"],
      "aginw" => ["awing"], "lprsu" => ["purls", "slurp"], "cegko" => ["gecko"],
      "dghou" => ["dough"], "ffirs" => ["riffs"], "bgnoo" => ["bongo"],
      "ggino" => ["going"], "aamms" => ["mamas"], "floor" => ["floor"],
      "apsst" => ["pasts", "spats"], "aakrt" => ["karat"], "agrsu" => ["sugar"],
      "aaegt" => ["agate"], "deegr" => ["edger", "greed"], "acffh" => ["chaff"],
      "imnst" => ["mints"], "agiln" => ["align"], "diqsu" => ["quids", "squid"],
      "irsuv" => ["virus"], "aopsy" => ["soapy"], "aeehv" => ["heave"],
      "eehsx" => ["hexes"], "deloy" => ["yodel"], "deirt" => ["tired", "tried"],
      "ddloy" => ["oddly"], "ddeio" => ["diode"], "elltu" => ["tulle"],
      "eirss" => ["sires", "rises"], "ffpsu" => ["puffs"], "kmnos" => ["monks"],
      "gppuy" => ["guppy"], "acitt" => ["attic", "tacit"], "acimn" => ["manic"],
      "eilnv" => ["liven"], "achms" => ["chasm"],
      "acost" => ["ascot", "tacos", "coast", "coats"], "errsu" => ["surer"],
      "deers" => ["reeds"], "aabcl" => ["cabal"],
      "loost" => ["loots", "stool", "tools"], "emstu" => ["mutes"],
      "chnpu" => ["punch"], "ikpsy" => ["spiky"], "bgruy" => ["rugby"],
      "adesv" => ["saved"], "cruvy" => ["curvy"], "aagmm" => ["magma", "gamma"],
      "dginr" => ["grind"], "delru" => ["lured", "ruled"], "enors" => ["snore"],
      "lnoos" => ["loons"], "acemo" => ["cameo"], "denrs" => ["nerds", "rends"],
      "aissv" => ["visas"], "cenov" => ["coven"], "benoy" => ["ebony"],
      "adikn" => ["kinda"], "degim" => ["midge"], "adddy" => ["daddy"],
      "akprs" => ["spark", "parks"], "adevw" => ["waved"], "acjks" => ["jacks"],
      "cekns" => ["necks"], "chins" => ["chins"], "acdel" => ["decal", "laced"],
      "cnotu" => ["count"], "erstw" => ["strew", "wrest"], "cfkor" => ["frock"],
      "aehns" => ["ashen"], "aclmp" => ["clamp"], "flotu" => ["flout"],
      "biltu" => ["built"], "eirtu" => ["uteri"], "orrsy" => ["sorry"],
      "ditty" => ["ditty"], "adknr" => ["drank"], "deimm" => ["mimed"],
      "hlorw" => ["whorl"], "aaegl" => ["algae"], "ilopt" => ["pilot"],
      "aclov" => ["vocal"], "belmu" => ["umbel"], "aekqu" => ["quake"],
      "fgooy" => ["goofy"], "dmmuy" => ["dummy"], "cckor" => ["crock"],
      "elptu" => ["letup"], "diilp" => ["lipid"], "ceinw" => ["wince"],
      "afknr" => ["frank"], "impwy" => ["wimpy"], "aehlw" => ["wheal", "whale"],
      "dgnsu" => ["dungs"], "dehop" => ["hoped"], "deity" => ["deity"],
      "cekos" => ["cokes"], "cefls" => ["clefs"], "giilv" => ["vigil"],
      "eopss" => ["pesos", "posse", "poses"], "emort" => ["metro"],
      "afgls" => ["flags"], "blosw" => ["bowls", "blows"], "efirr" => ["rifer"],
      "ceert" => ["erect"], "imssw" => ["swims"], "deeps" => ["deeps", "speed"],
      "ckops" => ["pocks"], "amsst" => ["masts"], "eekln" => ["kneel"],
      "cimpr" => ["crimp"], "bdegu" => ["budge", "debug"],
      "ceepr" => ["crepe", "creep"], "bdelo" => ["lobed"], "cchin" => ["cinch"],
      "cdios" => ["disco"], "deipp" => ["piped"], "almny" => ["manly"],
      "lossw" => ["slows"], "cdeiy" => ["dicey"], "emrtu" => ["muter"],
      "abegr" => ["barge"], "deksy" => ["dykes"], "aahjr" => ["rajah"],
      "eilpx" => ["pixel"], "adimt" => ["admit"], "hmsty" => ["myths"],
      "nnosy" => ["sonny"], "cells" => ["cells"], "abkru" => ["burka"],
      "bnnoy" => ["bonny"], "acnst" => ["cants", "scant"], "ehinw" => ["whine"],
      "acprs" => ["craps", "carps", "scrap"], "abdnr" => ["brand"],
      "adeor" => ["adore", "oared"], "ahirs" => ["hairs"],
      "cekps" => ["pecks", "speck"], "deotv" => ["voted"], "ikpss" => ["skips"],
      "ceilm" => ["clime"], "cdors" => ["scrod", "cords"], "enrru" => ["rerun"],
      "agnou" => ["guano"], "finty" => ["nifty"], "cikls" => ["licks", "slick"],
      "amnos" => ["mason", "moans"], "koors" => ["rooks"],
      "deilr" => ["idler", "riled"], "aefmr" => ["frame"], "efklu" => ["fluke"],
      "ciopt" => ["optic", "topic"], "moost" => ["moots"], "aabil" => ["labia"],
      "lsstu" => ["lusts", "sluts"], "gnorw" => ["grown", "wrong"],
      "acerr" => ["racer"], "beorw" => ["bower"], "cjnou" => ["junco"],
      "demru" => ["demur"], "bilps" => ["blips"], "enoos" => ["noose"],
      "hoopw" => ["whoop"], "aelno" => ["alone"], "aimox" => ["axiom"],
      "chort" => ["torch"], "efssu" => ["fuses"], "cinot" => ["tonic"],
      "lostu" => ["louts", "lotus"], "dnouw" => ["wound"], "emoos" => ["moose"],
      "ffnsu" => ["snuff"], "bdeir" => ["bride"], "eehmt" => ["theme"],
      "aluvv" => ["vulva"], "acdek" => ["caked"], "bnosu" => ["bonus"],
      "ipsst" => ["spits"], "eerss" => ["seers"], "affgs" => ["gaffs"],
      "aejns" => ["jeans"], "ddeis" => ["sided"], "cfhil" => ["filch"],
      "anprw" => ["prawn"], "aertt" => ["treat"],
      "eorsw" => ["sower", "swore", "worse"], "gnrsu" => ["rungs"],
      "dnops" => ["ponds"], "abbty" => ["tabby"], "ikrst" => ["skirt"],
      "denoy" => ["doyen"], "bbboy" => ["bobby"], "erssu" => ["ruses", "users"],
      "ccilo" => ["colic"], "adees" => ["eased"], "adgnr" => ["grand"],
      "ehmty" => ["thyme"], "ablos" => ["bolas"], "blluy" => ["bully"],
      "inssu" => ["sinus"], "egopr" => ["grope"], "aderv" => ["raved"],
      "eimss" => ["semis"], "inpuz" => ["unzip"], "aaqsu" => ["aquas"],
      "efhls" => ["flesh", "shelf"], "aadmn" => ["adman"], "einvx" => ["vixen"],
      "eenrs" => ["sneer"], "eervv" => ["verve"], "aeglv" => ["gavel"],
      "errwy" => ["wryer"], "accem" => ["mecca"], "cnoor" => ["croon"],
      "aelnv" => ["venal", "navel"], "deirv" => ["diver", "drive"],
      "alsuu" => ["luaus", "usual"], "aehnt" => ["neath"], "hklsu" => ["hulks"],
      "bsttu" => ["butts"], "eortw" => ["tower", "wrote"],
      "aelps" => ["sepal", "lapse", "leaps", "pales", "peals", "pleas"],
      "elosu" => ["louse"], "abcor" => ["cobra"],
      "eersv" => ["sever", "veers", "verse", "serve"], "ilops" => ["spoil"],
      "elnov" => ["novel"], "denry" => ["nerdy"], "adlou" => ["aloud"],
      "bloss" => ["slobs"], "chhoo" => ["hooch"], "deiks" => ["skied"],
      "flnow" => ["flown"], "ikkos" => ["kiosk"], "adepw" => ["pawed"],
      "boost" => ["boost", "boots"], "filps" => ["flips"], "egilt" => ["legit"],
      "himss" => ["shims"], "ccino" => ["conic"], "bells" => ["bells"],
      "aorss" => ["soars"], "fggoy" => ["foggy"], "adiry" => ["dairy", "diary"],
      "cilos" => ["coils"], "ggosy" => ["soggy"], "hmrry" => ["myrrh"],
      "eipty" => ["piety"], "bdotu" => ["doubt"], "clruy" => ["curly"],
      "eggou" => ["gouge"], "deott" => ["toted"], "hlpsy" => ["sylph"],
      "diknr" => ["drink"], "dehrs" => ["herds", "shred"], "erttu" => ["utter"],
      "afgrt" => ["graft"], "eekst" => ["skeet"], "acerz" => ["craze"],
      "nostu" => ["snout"], "abkrs" => ["barks"], "ceovy" => ["covey"],
      "aakpr" => ["parka"], "hiksw" => ["whisk"], "ahpry" => ["harpy"],
      "aeils" => ["aisle"], "ityzz" => ["tizzy"], "acehr" => ["reach"],
      "deems" => ["deems"], "aemtt" => ["matte"], "hlssu" => ["slush"],
      "eirst" => ["rites", "tiers", "tires", "tries"], "ceory" => ["coyer"],
      "adlrs" => ["lards"], "eprtu" => ["erupt"], "aikmu" => ["umiak"],
      "efgor" => ["gofer", "forge"], "admns" => ["damns"], "llmos" => ["molls"],
      "begio" => ["bogie"], "diloy" => ["doily"], "ckmuy" => ["mucky"],
      "adewy" => ["yawed"], "cglnu" => ["clung"], "eegly" => ["elegy"],
      "bggoy" => ["boggy"], "gilrs" => ["girls"], "arstw" => ["warts", "straw"],
      "deiln" => ["lined"], "bfflu" => ["bluff"], "knstu" => ["stunk"],
      "aenrv" => ["raven"], "aehnv" => ["haven"], "bcmru" => ["crumb"],
      "aefst" => ["fates", "feast", "feats"], "adntu" => ["daunt"],
      "filnt" => ["flint"], "aimmx" => ["maxim"], "alpsw" => ["pawls"],
      "abbey" => ["abbey"], "dejko" => ["joked"], "lpsuu" => ["lupus"],
      "defsu" => ["feuds", "fused"], "hossw" => ["shows"], "bikrs" => ["brisk"],
      "dnnou" => ["dunno"], "hilly" => ["hilly"], "ackln" => ["clank"],
      "ikrsy" => ["risky"], "eenst" => ["teens", "tense"], "eilss" => ["isles"],
      "ilmtu" => ["multi"], "eoprt" => ["trope"], "dilly" => ["dilly", "idyll"],
      "abdrs" => ["brads", "bards", "drabs"], "cffsu" => ["cuffs", "scuff"],
      "aiopt" => ["patio"], "agntu" => ["gaunt"], "enstt" => ["tents"],
      "eehrt" => ["ether", "there", "three"], "aegsz" => ["gazes"],
      "nrstu" => ["runts", "turns"], "deipw" => ["wiped"], "glmoo" => ["gloom"],
      "horst" => ["short"], "addef" => ["faded"], "anpsy" => ["pansy"],
      "filst" => ["flits", "lifts"], "abdls" => ["balds"],
      "amory" => ["moray", "mayor"], "ackow" => ["wacko"], "frstu" => ["turfs"],
      "aeglm" => ["gleam"], "bmoux" => ["buxom"], "ffims" => ["miffs"],
      "afiln" => ["final"], "ahkns" => ["ankhs", "hanks", "khans", "shank"],
      "eegrt" => ["egret", "greet"], "giloo" => ["igloo"], "enoss" => ["noses"],
      "aefly" => ["leafy"], "efstw" => ["wefts"], "gnruw" => ["wrung"],
      "hoswy" => ["showy"], "fssuy" => ["fussy"], "adisw" => ["wadis"],
      "eefrr" => ["freer", "refer"], "eehps" => ["sheep"], "altwz" => ["waltz"],
      "bemrs" => ["berms"], "hissu" => ["sushi"],
      "eerst" => ["ester", "reset", "steer", "terse", "trees"],
      "deinr" => ["diner"], "ainrs" => ["rains"],
      "aeprs" => ["pares", "pears", "rapes", "reaps", "spear", "parse", "spare"],
      "hinst" => ["thins", "hints"], "aceks" => ["cakes"], "filrt" => ["flirt"],
      "acopr" => ["copra"], "lrssu" => ["slurs"], "aegrz" => ["gazer", "graze"],
      "imsty" => ["misty"], "afhst" => ["hafts", "shaft"],
      "aegnr" => ["anger", "range"], "ceejt" => ["eject"], "afsst" => ["fasts"],
      "abggy" => ["baggy"], "aerty" => ["teary"], "eepps" => ["peeps"],
      "eeflt" => ["fleet"], "beers" => ["beers"], "aelns" => ["lanes", "leans"],
      "bilmp" => ["blimp"], "klsuy" => ["sulky"], "degls" => ["gelds"],
      "ahikk" => ["khaki"], "filly" => ["filly"], "eopsx" => ["poxes", "expos"],
      "eejrs" => ["jeers"], "enstv" => ["vents"], "aeppr" => ["paper"],
      "elops" => ["lopes", "poles", "slope"], "aegmo" => ["omega"],
      "aallm" => ["llama"], "allsw" => ["walls"], "addny" => ["dandy"],
      "ooprt" => ["troop"], "dgooy" => ["goody"], "rsttu" => ["strut", "trust"],
      "emorv" => ["mover"], "aelrv" => ["ravel"], "gnsuw" => ["swung"],
      "eehns" => ["sheen"], "loswy" => ["yowls"], "ainrt" => ["train"],
      "deopy" => ["dopey"], "fgors" => ["frogs"], "acmor" => ["carom", "macro"],
      "deglu" => ["glued"], "irtyz" => ["ritzy"], "klnsu" => ["slunk"],
      "binru" => ["bruin"], "allno" => ["llano"], "egooy" => ["gooey"],
      "ceelt" => ["elect"], "ekopr" => ["poker"], "egorr" => ["reorg", "roger"],
      "aerst" => ["aster", "tares", "taser", "stare", "tears", "rates"],
      "alops" => ["opals"], "abdny" => ["bandy"], "aalss" => ["salsa"],
      "eloss" => ["sloes", "soles", "loses"], "moprt" => ["tromp"],
      "oostt" => ["toots"], "delmo" => ["model"], "deipr" => ["pried", "pride"],
      "agntw" => ["twang"], "inory" => ["irony"], "acirv" => ["vicar"],
      "ddimy" => ["middy"], "acmrs" => ["crams", "scram"], "dehor" => ["horde"],
      "delop" => ["loped", "poled"], "deehx" => ["hexed"],
      "aekps" => ["spake", "peaks", "speak"], "eopsy" => ["poesy"],
      "asstw" => ["swats"], "glory" => ["glory"], "klrsu" => ["lurks"],
      "alnot" => ["talon", "tonal"], "clotu" => ["clout"],
      "almor" => ["molar", "moral"], "jlost" => ["jolts"], "delno" => ["olden"],
      "alnoz" => ["zonal"], "enstu" => ["tunes", "unset"],
      "cllsu" => ["scull", "culls"], "ceehl" => ["leech"], "mmruy" => ["rummy"],
      "dknsu" => ["dunks"], "ehlps" => ["helps"], "ceils" => ["slice"],
      "flluy" => ["fully"], "floru" => ["flour"], "bcilm" => ["climb"],
      "amrst" => ["trams", "marts", "smart"], "aesuv" => ["suave"],
      "denuu" => ["undue"], "eelnw" => ["newel"], "cnors" => ["corns", "scorn"],
      "bbdee" => ["ebbed"], "degnu" => ["nudge"], "llowy" => ["lowly"],
      "aegln" => ["angel", "glean", "angle"], "aintt" => ["titan", "taint"],
      "inpst" => ["pints"], "ggmuy" => ["muggy"], "aestx" => ["taxes"],
      "ginrs" => ["grins", "rings"], "aefks" => ["fakes"], "aalru" => ["aural"],
      "dmnou" => ["mound"], "diosv" => ["voids"],
      "egors" => ["gorse", "gores", "ogres"], "bdrsu" => ["drubs"],
      "imnty" => ["minty"], "ackty" => ["tacky"], "aeffg" => ["gaffe"],
      "dfins" => ["finds"], "chmop" => ["chomp"], "benor" => ["boner", "borne"],
      "elotw" => ["owlet", "towel"], "actty" => ["catty"], "aadls" => ["salad"],
      "dfoos" => ["foods"], "mmmoy" => ["mommy"], "beglo" => ["globe"],
      "dinrs" => ["rinds"], "afkln" => ["flank"], "ellst" => ["tells"],
      "cdksu" => ["ducks"], "hosst" => ["hosts", "shots"], "kkoos" => ["kooks"],
      "aehss" => ["ashes"], "acdeh" => ["ached"],
      "aelry" => ["layer", "relay", "early"], "cssty" => ["cysts"],
      "deily" => ["yield"], "delow" => ["dowel", "lowed"], "jlosw" => ["jowls"],
      "aefhs" => ["sheaf"], "dhowy" => ["howdy"], "fillr" => ["frill"],
      "acgln" => ["clang"], "cenno" => ["nonce"], "eisst" => ["sties", "sites"],
      "aadpt" => ["adapt"], "cdeoo" => ["cooed"], "aaegp" => ["agape"],
      "eeilx" => ["exile"], "adrsw" => ["sward", "wards", "draws"],
      "dorwy" => ["dowry", "rowdy", "wordy"], "ckoos" => ["cooks"],
      "aabck" => ["aback"], "eghin" => ["hinge", "neigh"], "abrsy" => ["brays"],
      "bgiot" => ["bigot"], "chlmu" => ["mulch"], "elpsy" => ["yelps"],
      "achst" => ["chats"], "eostt" => ["totes"], "jmpsu" => ["jumps"],
      "aarsu" => ["auras"], "beoos" => ["oboes"], "ennox" => ["xenon"],
      "aastv" => ["avast"], "llmsu" => ["mulls"], "ckors" => ["corks", "rocks"],
      "almst" => ["malts"], "ehorv" => ["hover"], "eervy" => ["every"],
      "eekss" => ["seeks"], "aelss" => ["seals", "sales"], "adeev" => ["evade"],
      "eepss" => ["seeps"], "aiprt" => ["tapir"], "degru" => ["urged"],
      "acrss" => ["scars", "crass"], "delov" => ["loved"], "einns" => ["nines"],
      "befir" => ["brief"], "adehs" => ["ashed", "shade", "heads"],
      "ablss" => ["slabs"], "ehint" => ["thine"], "forsu" => ["fours"],
      "ceprt" => ["crept"], "ahlos" => ["halos", "shoal"], "aeent" => ["eaten"],
      "dikny" => ["dinky"], "aammm" => ["mamma"], "ioqtu" => ["quoit"],
      "acels" => ["laces", "scale"], "chnru" => ["churn"], "dssuy" => ["sudsy"],
      "aclxy" => ["calyx"], "eegky" => ["geeky"], "ddinu" => ["undid"],
      "egoos" => ["goose"], "lstuy" => ["lusty"], "ahlot" => ["loath"],
      "abefl" => ["fable"], "aprry" => ["parry"], "aelsw" => ["wales", "weals"],
      "aemrr" => ["rearm"], "ehmry" => ["rhyme"], "eensu" => ["ensue"],
      "annos" => ["anons"], "acdrs" => ["cards"], "ailsw" => ["wails"],
      "bjmou" => ["jumbo"], "clstu" => ["cults"], "acest" => ["caste"],
      "apssy" => ["spays"], "mnors" => ["morns", "norms"], "aknpr" => ["prank"],
      "hkmou" => ["hokum"], "aeltv" => ["valet"], "demoo" => ["mooed"],
      "adejw" => ["jawed"], "aimsw" => ["swami"], "efinr" => ["finer", "infer"],
      "kmrsu" => ["murks"], "chips" => ["chips"], "gorss" => ["gross"],
      "eelpx" => ["expel"], "ikkny" => ["kinky"], "afstw" => ["wafts"],
      "deikr" => ["irked"], "ilost" => ["toils"], "isssy" => ["sissy"],
      "ffins" => ["sniff"], "apsty" => ["patsy", "pasty"],
      "beglu" => ["bugle", "bulge"], "addry" => ["dryad"],
      "achrs" => ["chars", "crash"], "bcirs" => ["cribs"], "ensux" => ["nexus"],
      "ekost" => ["tokes", "stoke"], "ahils" => ["hails"],
      "cdeit" => ["edict", "cited"], "acdny" => ["candy"], "gopru" => ["group"],
      "ggnos" => ["gongs"], "abbrs" => ["barbs"], "aeels" => ["easel", "lease"],
      "ghiss" => ["sighs"], "eopst" => ["poets"], "aeegl" => ["eagle"],
      "alsst" => ["salts", "slats", "lasts"], "bimrs" => ["brims"],
      "hopsy" => ["hypos"], "knrtu" => ["trunk"], "aerrs" => ["rares", "rears"],
      "eemot" => ["emote"], "bostu" => ["bouts"], "dikns" => ["kinds"],
      "bcmoo" => ["combo"], "aegss" => ["gases", "sages"], "aekms" => ["makes"],
      "dgils" => ["gilds"], "flost" => ["lofts"],
      "cdlos" => ["clods", "colds", "scold"], "inosw" => ["winos"],
      "adepy" => ["payed"], "oprst" => ["strop", "ports", "sport"],
      "copru" => ["croup"], "eeerv" => ["reeve"], "ceein" => ["niece"],
      "defns" => ["fends"],
      "acder" => ["cadre", "arced", "cedar", "cared", "raced"],
      "ddepu" => ["duped"], "achsw" => ["schwa"], "ginty" => ["tying"],
      "cccio" => ["cocci"], "eehrw" => ["hewer", "where"],
      "abdel" => ["baled", "blade"], "aaitw" => ["await"], "eghit" => ["eight"],
      "abstu" => ["abuts", "tubas"], "aellp" => ["lapel"],
      "deilo" => ["oldie", "oiled"], "dsstu" => ["dusts", "studs"],
      "esttx" => ["texts"], "demov" => ["moved"], "forst" => ["forts", "frost"],
      "efhit" => ["thief"], "fnorw" => ["frown"], "abors" => ["boars"],
      "bilmo" => ["limbo"], "osstu" => ["ousts"], "degiu" => ["guide"],
      "eekrs" => ["reeks"], "fmoru" => ["forum"], "abhor" => ["abhor"],
      "ackss" => ["casks", "sacks"], "biort" => ["orbit"], "eemny" => ["enemy"],
      "ginvy" => ["vying"], "deert" => ["treed", "deter"], "errtu" => ["truer"],
      "aggin" => ["nigga"], "beist" => ["bites"], "deewy" => ["weedy"],
      "himrt" => ["mirth"], "alpst" => ["splat"], "bflyy" => ["flyby"],
      "abjno" => ["banjo"], "eeprt" => ["peter"], "ekmos" => ["smoke"],
      "aapps" => ["papas"], "aeeir" => ["aerie"], "dimns" => ["minds"],
      "ehmny" => ["hymen"], "bsstu" => ["busts", "stubs"], "cilry" => ["lyric"],
      "dilsw" => ["wilds"], "bklsu" => ["bulks"], "adily" => ["daily"],
      "einsx" => ["nixes"], "biost" => ["obits"], "eehtt" => ["teeth"],
      "enopr" => ["prone"], "acdlu" => ["ducal"], "agruu" => ["augur"],
      "celos" => ["close"], "ailps" => ["pails"], "ekosy" => ["yokes"],
      "bcikr" => ["brick"], "orsuy" => ["yours"], "ffrsu" => ["ruffs"],
      "achos" => ["chaos"], "dhimu" => ["humid"], "elrsu" => ["lures", "rules"],
      "ccklu" => ["cluck"], "anpss" => ["snaps", "spans"], "deenu" => ["endue"],
      "eggor" => ["gorge"], "anppy" => ["nappy"], "enpru" => ["prune"],
      "ainpt" => ["inapt", "paint"], "hopss" => ["shops"], "cehtu" => ["chute"],
      "aeppu" => ["pupae"], "cdeer" => ["creed"], "afkls" => ["flask"],
      "corsu" => ["scour"], "achmr" => ["charm", "march"],
      "anstu" => ["aunts", "tunas"], "eemrs" => ["meres"], "fikns" => ["finks"],
      "dhins" => ["hinds"], "dehlo" => ["holed"], "aguyz" => ["gauzy"],
      "ilpst" => ["split"], "aeflr" => ["feral", "flare"], "cerst" => ["crest"],
      "cknos" => ["conks"], "aeltt" => ["latte"], "boort" => ["robot"],
      "efrry" => ["fryer", "ferry"], "adejs" => ["jades"], "aamor" => ["aroma"],
      "cdeei" => ["deice"], "aelrx" => ["laxer", "relax"], "prsuu" => ["usurp"],
      "dfnsu" => ["funds"], "imnsu" => ["minus"], "dersy" => ["dyers"],
      "diiot" => ["idiot"], "dhitw" => ["width"], "mnoos" => ["moons"],
      "histx" => ["sixth"], "aagss" => ["sagas"], "denor" => ["drone"],
      "delos" => ["lodes", "doles", "soled"], "aahlo" => ["aloha"],
      "aknsy" => ["snaky", "yanks"], "dpssu" => ["spuds"], "acgrs" => ["crags"],
      "bghit" => ["bight"], "cefkl" => ["fleck"], "cehop" => ["epoch"],
      "bbhoy" => ["hobby"], "ahlpy" => ["phyla"], "losuy" => ["lousy"],
      "abqru" => ["burqa"], "acetx" => ["exact"], "bnorw" => ["brown"],
      "emnoy" => ["money"], "diott" => ["ditto"], "aartt" => ["attar"],
      "hnort" => ["thorn", "north"], "benos" => ["bones"], "efgir" => ["grief"],
      "bnrtu" => ["brunt", "burnt"],
      "aenrs" => ["nears", "saner", "snare", "earns"], "aekrw" => ["wreak"],
      "adnrw" => ["drawn"], "bblsu" => ["bulbs"], "beinr" => ["brine"],
      "ffhuy" => ["huffy"], "ddmuy" => ["muddy"], "aeruz" => ["azure"],
      "floss" => ["floss"], "ehstw" => ["whets"], "kltuz" => ["klutz"],
      "abort" => ["abort"], "eilns" => ["liens", "lines"], "innty" => ["tinny"],
      "eessy" => ["yeses"], "cikqu" => ["quick"], "fosty" => ["softy"],
      "adiou" => ["audio"], "aehny" => ["hyena"], "abelr" => ["abler", "blare"],
      "aegms" => ["games"], "ekops" => ["pokes", "spoke"],
      "agost" => ["goats", "togas"], "iknsw" => ["winks"],
      "blost" => ["blots", "bolts"], "eopps" => ["popes"], "eilrs" => ["riles"],
      "dmors" => ["dorms"], "eirsz" => ["sizer"], "delsw" => ["welds"],
      "ghint" => ["night", "thing"], "aapst" => ["pasta"], "beost" => ["besot"],
      "egorv" => ["grove"], "adelz" => ["lazed"], "firzz" => ["frizz"],
      "abiil" => ["alibi"], "fhilt" => ["filth"], "enosv" => ["ovens"],
      "ddeeg" => ["edged"], "delsu" => ["slued", "duels"], "cehrt" => ["retch"],
      "adhns" => ["hands"], "eorrw" => ["rower"], "llost" => ["tolls"],
      "chinp" => ["pinch"], "ghrsu" => ["shrug"], "nostw" => ["towns"],
      "aclsy" => ["scaly"], "cinru" => ["incur"], "hlloy" => ["holly"],
      "defin" => ["fiend", "fined"], "jlloy" => ["jolly"], "deosz" => ["dozes"],
      "beimu" => ["imbue"], "adhrs" => ["shard"], "cdeeu" => ["deuce"],
      "almoy" => ["loamy"], "acfkl" => ["flack"], "aegsw" => ["wages"],
      "innpu" => ["unpin"], "binox" => ["inbox"], "acceh" => ["cache"],
      "acckr" => ["crack"], "cosst" => ["costs"], "aimms" => ["imams", "maims"],
      "adgos" => ["goads"], "biimn" => ["nimbi"], "egnst" => ["gents"],
      "bdeow" => ["bowed"], "mstuy" => ["musty"], "ceorw" => ["cower"],
      "accit" => ["cacti"], "aegpr" => ["grape", "pager"], "eksty" => ["tykes"],
      "lllsu" => ["lulls"], "aklnp" => ["plank"], "deelu" => ["elude"],
      "eoqtu" => ["toque", "quote"], "efhty" => ["hefty"], "aacmw" => ["macaw"],
      "iopst" => ["posit"], "ennpy" => ["penny"], "cdeks" => ["decks"],
      "dlors" => ["lords"], "acflo" => ["focal"], "elrsy" => ["lyres"],
      "bdeis" => ["bides"], "diprs" => ["drips"], "adelr" => ["alder"],
      "dlorw" => ["world"], "aansu" => ["sauna"], "dgpuy" => ["pudgy"],
      "ehmoy" => ["homey"], "ddiko" => ["kiddo"], "ackkn" => ["knack"],
      "adelp" => ["paled", "plead", "pedal"], "loott" => ["lotto"],
      "dellw" => ["dwell"], "eirrv" => ["river"], "appsy" => ["sappy"],
      "bchot" => ["botch"], "koops" => ["spook"], "epstw" => ["swept"],
      "efhst" => ["hefts"], "ahlls" => ["halls", "shall"], "diyzz" => ["dizzy"],
      "aborv" => ["bravo"], "bdilu" => ["build"], "dehiv" => ["hived"],
      "asttw" => ["watts"], "aelrs" => ["earls", "reals", "laser"],
      "deglo" => ["ogled", "lodge"], "enorw" => ["owner"], "cdkos" => ["docks"],
      "eeepv" => ["peeve"], "cdlou" => ["cloud", "could"], "hlmpy" => ["lymph"],
      "attty" => ["tatty"], "blmpu" => ["plumb"], "dehno" => ["honed"],
      "finny" => ["finny"], "eissw" => ["wises"], "hmsuu" => ["humus"],
      "ekpry" => ["perky"], "bikls" => ["bilks"], "eiorv" => ["vireo"],
      "nnruy" => ["runny"], "glpsu" => ["gulps", "plugs"], "ffmsu" => ["muffs"],
      "agpss" => ["gasps"], "adlmo" => ["modal"], "cnoos" => ["coons"],
      "aditu" => ["audit"], "ddnoy" => ["noddy"], "ciost" => ["stoic"],
      "aestw" => ["sweat", "waste"], "anosx" => ["axons"],
      "aelmp" => ["maple", "ample"], "iknps" => ["pinks"], "elmot" => ["motel"],
      "hnosw" => ["shown"], "ahsty" => ["hasty"], "aegil" => ["agile"],
      "adilp" => ["plaid"], "eginr" => ["reign"], "deiov" => ["video"],
      "eilrv" => ["viler", "liver"], "aegst" => ["gates", "stage"],
      "aelvv" => ["valve"], "cdeox" => ["codex"], "eefrs" => ["reefs", "frees"],
      "eellv" => ["level"], "errty" => ["terry", "retry"],
      "bdetu" => ["debut", "tubed"], "egimm" => ["gimme"], "acefs" => ["faces"],
      "bnnuy" => ["bunny"], "degio" => ["dogie"], "aehtw" => ["wheat"],
      "chksu" => ["shuck"], "cehwy" => ["chewy"], "bginr" => ["bring"],
      "efhtt" => ["theft"], "hnssu" => ["shuns"], "afloo" => ["aloof"],
      "achpr" => ["parch"], "deotw" => ["towed"], "abely" => ["belay"],
      "hissw" => ["swish"], "adnst" => ["stand"], "ghist" => ["sight"],
      "noosw" => ["swoon"], "acgno" => ["conga"], "lossu" => ["souls"],
      "abdei" => ["abide"], "bbeir" => ["bribe"], "belsu" => ["lubes", "blues"],
      "adlno" => ["nodal"], "belss" => ["bless"], "abbcy" => ["cabby"],
      "aekrt" => ["taker"], "iknss" => ["skins", "sinks"],
      "ailns" => ["slain", "nails", "snail"], "ghimt" => ["might"],
      "deeux" => ["exude"], "dilmy" => ["dimly"], "fkluy" => ["fluky"],
      "cehsw" => ["chews"], "aceep" => ["peace"], "abhst" => ["baths"],
      "ioptv" => ["pivot"], "elovw" => ["vowel"], "deiox" => ["oxide"],
      "ilsst" => ["silts", "slits", "lists"], "egipr" => ["gripe"],
      "hoopt" => ["photo"], "adhry" => ["hydra", "hardy"], "delms" => ["melds"],
      "blmoo" => ["bloom"], "dekot" => ["toked"], "abkns" => ["banks"],
      "allow" => ["allow"], "abbgy" => ["gabby"], "aertv" => ["avert"],
      "antwy" => ["tawny"], "aekln" => ["ankle"], "adelw" => ["waled"],
      "deops" => ["dopes", "posed"], "ahrtw" => ["wrath"], "acenp" => ["pecan"],
      "mmtuy" => ["tummy"], "aadnp" => ["panda"], "bceeh" => ["beech"],
      "dioww" => ["widow"], "ellsw" => ["swell", "wells"], "efiry" => ["fiery"],
      "chilm" => ["milch"], "moory" => ["roomy"], "bcklo" => ["block"],
      "afgns" => ["fangs"], "ellms" => ["smell"], "aoqtu" => ["quota"],
      "demow" => ["mowed"], "adgno" => ["gonad"], "adepv" => ["vaped", "paved"],
      "hjnos" => ["johns"], "bcrsu" => ["curbs", "scrub"], "aiost" => ["iotas"],
      "dgiir" => ["rigid"], "beegt" => ["beget"], "chiks" => ["hicks"],
      "fgoos" => ["goofs"], "diimo" => ["idiom"], "afnny" => ["fanny"],
      "beijs" => ["jibes"], "ijnot" => ["joint"],
      "eekls" => ["keels", "leeks", "sleek"], "aeers" => ["erase"],
      "amoru" => ["amour"], "eorsz" => ["zeros"], "efort" => ["forte"],
      "dnosy" => ["synod"], "looss" => ["solos"], "mopst" => ["stomp"],
      "eettw" => ["tweet"], "eeruv" => ["revue"], "aelsz" => ["lazes"],
      "deosv" => ["doves"], "derss" => ["dress"], "eegil" => ["liege"],
      "ceenp" => ["pence"], "enort" => ["toner", "tenor"],
      "aefrs" => ["fares", "fears", "safer"], "abnru" => ["unbar", "urban"],
      "abemr" => ["amber"], "akoss" => ["soaks"],
      "eimrt" => ["remit", "timer", "merit"], "acnss" => ["scans"],
      "adehr" => ["hared", "heard"], "ejlpu" => ["julep"], "gnnuy" => ["gunny"],
      "ccoru" => ["occur"], "dddeu" => ["duded"], "krssu" => ["rusks"],
      "ahpst" => ["staph", "paths"], "crruy" => ["curry"], "hmpsu" => ["humps"],
      "adems" => ["dames"], "aflou" => ["afoul"], "beert" => ["beret"],
      "cdeir" => ["riced", "cider", "cried"], "afoss" => ["sofas"],
      "illtw" => ["twill"], "achht" => ["hatch"], "agmtu" => ["gamut"],
      "elouv" => ["ovule"], "giprs" => ["prigs", "sprig", "grips"],
      "demtu" => ["muted"], "aberv" => ["brave"], "emsst" => ["stems"],
      "bdeip" => ["biped"], "belru" => ["bluer"], "aqrtu" => ["quart"],
      "estux" => ["tuxes"], "egptu" => ["getup"], "cemos" => ["comes"],
      "ablms" => ["balms", "lambs"], "addel" => ["addle", "laded"],
      "adell" => ["ladle"], "aenwx" => ["waxen"], "cciny" => ["cynic"],
      "bclos" => ["blocs"], "gorsw" => ["grows"], "ehkoy" => ["hokey"],
      "aemsy" => ["seamy"], "afhit" => ["faith"], "cchko" => ["chock"],
      "eilsv" => ["veils", "evils", "lives"], "hilst" => ["hilts"],
      "akmrs" => ["marks"], "beirt" => ["tribe"], "akooz" => ["kazoo"],
      "iiksw" => ["wikis", "kiwis"], "clost" => ["clots", "colts"],
      "amors" => ["roams"], "inpsy" => ["spiny"], "himsw" => ["whims"],
      "imprs" => ["prism"], "bcciu" => ["cubic"], "ddowy" => ["dowdy"],
      "elosv" => ["voles", "loves", "solve"], "efruz" => ["furze"],
      "himst" => ["smith"], "aeirt" => ["irate"], "aehks" => ["hakes", "shake"],
      "ejtty" => ["jetty"], "cefht" => ["fetch"], "eglnu" => ["lunge"],
      "acill" => ["lilac"], "gmpyy" => ["pygmy"], "ceeem" => ["emcee"],
      "abcht" => ["batch"], "eorrr" => ["error"], "eimov" => ["movie"],
      "bbeil" => ["bible"], "acdew" => ["cawed"], "abdek" => ["baked"],
      "deeor" => ["erode"], "innou" => ["union"], "arrty" => ["tarry"],
      "detuv" => ["duvet"], "efory" => ["foyer"], "deoty" => ["toyed"],
      "aamnn" => ["manna"], "apssw" => ["wasps", "swaps"],
      "ehort" => ["throe", "other"], "aelly" => ["alley"], "ahknt" => ["thank"],
      "abens" => ["banes", "beans"], "hnors" => ["horns"], "ablot" => ["bloat"],
      "eelry" => ["leery"], "hmrtu" => ["thrum"], "ijost" => ["joist"],
      "eekns" => ["keens", "knees"], "foopr" => ["proof"], "aeilv" => ["alive"],
      "aahlp" => ["alpha"], "abcrs" => ["carbs", "crabs"], "iilmt" => ["limit"],
      "eepst" => ["steep"], "osttu" => ["stout", "touts"],
      "ailrt" => ["trail", "trial"], "ipqsu" => ["quips"], "afill" => ["flail"],
      "ekprs" => ["perks"], "cdeis" => ["dices"], "gsstu" => ["gusts"],
      "bhsuy" => ["bushy"], "eefrw" => ["fewer"], "nosty" => ["stony"],
      "dmooy" => ["moody"], "bboos" => ["boobs"], "ilqtu" => ["quilt"],
      "fgist" => ["gifts"], "adegm" => ["gamed"], "cddee" => ["ceded"],
      "aairs" => ["arias"], "oprsw" => ["prows"],
      "einrs" => ["reins", "resin", "rinse", "siren", "risen"],
      "enosz" => ["zones"], "biltz" => ["blitz"], "acenr" => ["nacre", "crane"],
      "below" => ["bowel", "elbow", "below"], "dinwy" => ["windy"],
      "filmy" => ["filmy"], "ghilt" => ["light"], "agssy" => ["gassy"],
      "ceosv" => ["coves"], "aortt" => ["tarot"], "chmoo" => ["mooch"],
      "chotu" => ["touch"], "divvy" => ["divvy"], "amrsw" => ["swarm", "warms"],
      "abjot" => ["jabot"], "cdstu" => ["ducts"], "foosw" => ["woofs"],
      "bbsuy" => ["busby"], "deeny" => ["needy"], "jostu" => ["joust"],
      "egmno" => ["gnome"], "cerss" => ["cress"], "agnty" => ["tangy"],
      "eeeir" => ["eerie"], "aimty" => ["amity"], "ampss" => ["spams", "spasm"],
      "hlpsu" => ["plush"], "abost" => ["boast", "boats"], "acklo" => ["cloak"],
      "aegll" => ["legal"], "delsv" => ["velds"], "ffiks" => ["skiff"],
      "hlrsu" => ["hurls"], "eimor" => ["moire"], "egmrs" => ["germs"],
      "aghtu" => ["aught"], "aelmt" => ["metal"], "beosx" => ["boxes"],
      "dehis" => ["shied", "hides"], "deetw" => ["tweed"], "adors" => ["roads"],
      "dnowy" => ["downy"], "aknrs" => ["ranks"], "ceinr" => ["nicer"],
      "cesst" => ["sects"], "annny" => ["nanny"], "elotx" => ["extol"],
      "depsu" => ["dupes"], "ddeop" => ["doped"], "agilr" => ["grail"],
      "ehiks" => ["hikes"], "ddelo" => ["doled"], "aabet" => ["abate"],
      "afory" => ["foray"], "chsuy" => ["cushy"], "bemru" => ["umber"],
      "eprsu" => ["purse", "super"], "iorvy" => ["ivory"], "cehor" => ["chore"],
      "eostv" => ["stove", "votes"],
      "deils" => ["delis", "idles", "sidle", "slide"], "dehos" => ["hosed"],
      "aehtt" => ["theta"], "aaflt" => ["fatal"], "bdeoo" => ["booed"],
      "cgilo" => ["logic"], "dknru" => ["drunk"], "aenrr" => ["reran"],
      "emrst" => ["terms"], "anrsw" => ["warns"], "acemr" => ["cream"],
      "nnosu" => ["nouns"], "aepss" => ["apses"], "beelp" => ["bleep"],
      "eegks" => ["geeks"], "losst" => ["slots"], "lnnoy" => ["nylon"],
      "bddiy" => ["biddy"], "almpy" => ["palmy", "amply"], "glmou" => ["mogul"],
      "beruy" => ["buyer"], "hrttu" => ["truth"], "bblru" => ["blurb"],
      "ghitw" => ["wight"], "aemsu" => ["amuse"], "aestv" => ["stave"],
      "klnpu" => ["plunk"], "chopu" => ["pouch"],
      "deirw" => ["wired", "weird", "wider"], "aceft" => ["facet"],
      "adrsy" => ["drays", "yards"], "eortu" => ["outer", "route"],
      "adior" => ["radio"], "alppy" => ["apply"], "acmsu" => ["sumac"],
      "llsyy" => ["slyly"], "emops" => ["mopes", "poems"], "chity" => ["itchy"],
      "aaers" => ["areas"], "grsuu" => ["gurus"], "orssu" => ["sours"],
      "abils" => ["bails", "basil"], "glnsu" => ["slung", "lungs"],
      "cddei" => ["diced"], "gikns" => ["kings"], "aderz" => ["razed"],
      "cpssu" => ["cusps"], "agnno" => ["gonna"], "cimsu" => ["music"],
      "eersw" => ["ewers", "sewer"], "ceehp" => ["cheep"], "ddeil" => ["idled"],
      "aeinv" => ["naive"], "aaegv" => ["agave"], "hoott" => ["tooth"],
      "eiprw" => ["wiper"], "ahmsw" => ["whams"], "deerr" => ["erred"],
      "jknsu" => ["junks"], "aestt" => ["teats", "state", "taste"],
      "achrt" => ["chart"], "acdls" => ["scald"], "bdeor" => ["robed", "bored"],
      "eepsw" => ["weeps", "sweep"], "begin" => ["binge", "begin", "being"],
      "eehrs" => ["sheer"], "kmruy" => ["murky"], "fiyzz" => ["fizzy"],
      "gistw" => ["twigs"], "eilms" => ["limes", "slime", "miles", "smile"],
      "egikn" => ["eking"], "ckmos" => ["mocks", "smock"], "dflos" => ["folds"],
      "loops" => ["sloop", "pools", "loops", "spool"], "eeisv" => ["sieve"],
      "delss" => ["sleds"], "ailrs" => ["lairs", "liars", "rails"],
      "cenos" => ["scone", "cones"], "deehw" => ["hewed"],
      "deegs" => ["sedge", "edges"], "degir" => ["dirge", "ridge"],
      "fklos" => ["folks"], "ansuy" => ["unsay"], "bilss" => ["bliss"],
      "enost" => ["onset", "tones", "notes", "stone"], "deefs" => ["feeds"],
      "aabem" => ["abeam"], "floos" => ["fools"], "blnow" => ["blown"],
      "impps" => ["pimps"], "defgu" => ["fudge"], "mnotu" => ["mount"],
      "acklu" => ["caulk"], "begrs" => ["bergs"], "achks" => ["shack", "hacks"],
      "ahlss" => ["slash"], "abkln" => ["blank"], "aalrv" => ["larva"],
      "fistw" => ["swift"], "acees" => ["cease"], "fhirt" => ["firth"],
      "chopr" => ["porch"],
      "aepst" => ["septa", "pates", "spate", "paste", "tapes"],
      "ahhss" => ["shahs"], "afrsy" => ["frays"], "eekop" => ["pekoe"],
      "ddiru" => ["druid"], "aloss" => ["lasso"], "cdees" => ["cedes"],
      "aklny" => ["lanky"], "adewx" => ["waxed"], "acnny" => ["canny"],
      "cffil" => ["cliff"], "firtu" => ["fruit"], "cglos" => ["clogs"],
      "eimns" => ["miens", "mines"], "ejsst" => ["jests"], "ceiru" => ["curie"],
      "amotz" => ["matzo"], "ackns" => ["snack"], "abdwy" => ["bawdy"],
      "ciksw" => ["wicks"], "eilnt" => ["inlet"], "airtt" => ["trait"],
      "ckrtu" => ["truck"], "eklnt" => ["knelt"], "deikt" => ["kited"],
      "eflst" => ["felts", "lefts"], "deppu" => ["upped"], "efisv" => ["fives"],
      "ddein" => ["dined"], "dderu" => ["udder"], "abcno" => ["bacon"],
      "cersw" => ["crews", "screw"], "adirt" => ["triad"],
      "aceht" => ["cheat", "teach"], "llors" => ["rolls"],
      "anors" => ["roans", "sonar", "arson"], "mmpsu" => ["mumps"],
      "begil" => ["bilge"], "dekpu" => ["puked"], "adery" => ["ready"],
      "airss" => ["saris"], "adehw" => ["hawed"], "ccklo" => ["clock"],
      "deipt" => ["tepid"], "eenrw" => ["newer", "renew"], "ceelx" => ["excel"],
      "ghiny" => ["hying"], "achir" => ["chair"],
      "eiprs" => ["piers", "pries", "spire"], "ilmpy" => ["imply"],
      "eeelv" => ["levee"], "ehikr" => ["hiker"], "ehlsw" => ["welsh"],
      "fglsu" => ["gulfs"], "morst" => ["storm"], "iprst" => ["strip", "trips"],
      "abrss" => ["brass"], "agmno" => ["mango"], "ccikr" => ["crick"],
      "amprt" => ["tramp"], "moosz" => ["zooms"], "ahooy" => ["yahoo"],
      "cdeow" => ["cowed"], "akrst" => ["stark"], "deotx" => ["detox"],
      "aemst" => ["mates", "meats", "tames", "steam", "teams"],
      "ciotx" => ["toxic"], "aegis" => ["aegis"], "abels" => ["sable", "bales"],
      "ademr" => ["armed", "dream"], "eiprz" => ["prize"], "aehmr" => ["harem"],
      "deeky" => ["keyed"],
      "eimst" => ["emits", "mites", "smite", "items", "times"],
      "enops" => ["pones", "peons", "opens"], "isstu" => ["suits"],
      "ceipr" => ["price"], "bgnos" => ["bongs"], "ginss" => ["sings", "signs"],
      "ceotv" => ["covet"], "deilw" => ["wiled", "wield"], "deess" => ["seeds"],
      "afrst" => ["farts", "frats", "rafts"], "ampsv" => ["vamps"],
      "adefk" => ["faked"],
      "aprst" => ["sprat", "tarps", "strap", "parts", "traps"],
      "eprst" => ["strep"], "bgluy" => ["bulgy"], "celov" => ["clove"],
      "fnort" => ["front"], "eglns" => ["glens"], "loppy" => ["polyp"],
      "dentu" => ["tuned"], "aadmr" => ["drama"], "alnrs" => ["snarl"],
      "kmsuy" => ["musky"], "aakmr" => ["karma"], "ghlpy" => ["glyph"],
      "aceno" => ["canoe", "ocean"], "eilmr" => ["miler"], "chlny" => ["lynch"],
      "llsuy" => ["sully"], "bcipu" => ["pubic"], "aklsw" => ["walks"],
      "aagmn" => ["manga"], "bhlsu" => ["blush"], "ackrs" => ["racks"],
      "mprsu" => ["rumps"], "aiqsu" => ["quasi"], "degil" => ["gelid", "glide"],
      "certu" => ["cruet", "cuter", "truce"], "addet" => ["dated"],
      "acrry" => ["carry"], "adekw" => ["waked"], "diotv" => ["divot"],
      "ailsv" => ["vials"], "acdet" => ["cadet", "acted"], "aditv" => ["davit"],
      "aknps" => ["spank"], "elmsw" => ["mewls"], "adelm" => ["lamed", "medal"],
      "bdeew" => ["dweeb"], "bgino" => ["bingo"], "adeln" => ["laden"],
      "acelr" => ["clear"], "gortu" => ["grout"], "aalrt" => ["altar"],
      "afltu" => ["fault"], "agmrs" => ["grams"], "dfnou" => ["found"],
      "chhtu" => ["hutch"], "adeht" => ["hated", "death"],
      "ghirt" => ["girth", "right"], "ahlst" => ["shalt", "laths", "halts"],
      "aeelt" => ["elate"], "boosz" => ["bozos"], "eehlw" => ["wheel"],
      "alory" => ["royal"], "aeglr" => ["glare", "regal", "lager", "large"],
      "dilru" => ["lurid"], "elpsu" => ["pulse"], "gorsy" => ["gyros"],
      "eehst" => ["thees", "sheet", "these"], "emnow" => ["women"],
      "mmuyy" => ["yummy"], "abeht" => ["bathe"], "abesu" => ["beaus", "abuse"],
      "orrwy" => ["worry"], "aabde" => ["baaed"], "epstu" => ["setup", "upset"],
      "eorst" => ["store"], "depru" => ["prude"], "bmoor" => ["broom"],
      "beill" => ["libel"], "finuy" => ["unify"], "aiort" => ["ratio"],
      "ilmsy" => ["slimy"], "acekr" => ["creak"], "acint" => ["antic"],
      "epprs" => ["preps"], "cortu" => ["court"], "eoprv" => ["prove"],
      "inppu" => ["pinup"], "dhiot" => ["dhoti"], "defmu" => ["fumed"],
      "hkssu" => ["husks"], "cfrsu" => ["scurf"], "adgln" => ["gland"],
      "ghost" => ["ghost"], "cefor" => ["force"], "cnorw" => ["crown"],
      "inotx" => ["toxin"], "hipsw" => ["whips"], "beeps" => ["beeps"],
      "iklos" => ["kilos"], "aghlu" => ["laugh"], "kmosy" => ["smoky"],
      "acgim" => ["magic"], "bbloy" => ["lobby"], "eelsv" => ["elves"],
      "degor" => ["gored"], "ceelr" => ["creel"], "mnoru" => ["mourn"],
      "nsstu" => ["stuns"], "ceens" => ["scene"], "bilms" => ["limbs"],
      "achnt" => ["chant"], "bnoss" => ["snobs"], "aahsw" => ["awash"],
      "aesvw" => ["waves"], "eeqru" => ["queer"], "adefs" => ["fades"],
      "egiin" => ["genii"], "ehmru" => ["rheum"], "abell" => ["label"],
      "dejoy" => ["joyed"], "ailnv" => ["anvil"], "abgns" => ["bangs"],
      "iimns" => ["minis"], "acers" => ["acres", "races", "scare", "cares"],
      "bdnos" => ["bonds"], "ahmrs" => ["harms", "marsh"], "aeoss" => ["oases"],
      "cmssu" => ["scums"], "aintw" => ["twain"], "ceirt" => ["trice"],
      "hirrs" => ["shirr"], "nttuy" => ["nutty"], "deegl" => ["ledge"],
      "cehim" => ["chime"], "cdeoy" => ["decoy"], "alnwy" => ["wanly"],
      "eissz" => ["sizes"], "bhort" => ["broth", "throb"], "knost" => ["knots"],
      "aceln" => ["lance", "clean"], "nprsu" => ["spurn"],
      "acehs" => ["aches", "chase"], "enrtu" => ["tuner"], "fiost" => ["foist"],
      "beirs" => ["biers"], "aehls" => ["shale", "hales", "heals", "leash"],
      "fnotu" => ["futon", "fount"], "cilst" => ["clits"], "eipst" => ["spite"],
      "acryz" => ["crazy"], "ajmor" => ["major"], "eortt" => ["torte", "otter"],
      "noswy" => ["snowy"], "ceist" => ["cites"], "behrt" => ["berth"],
      "acfny" => ["fancy"], "eikpr" => ["piker"], "behrs" => ["herbs"],
      "allms" => ["malls", "small"], "glnoo" => ["logon"],
      "opsst" => ["posts", "spots", "stops"], "achoo" => ["achoo"],
      "ijnos" => ["joins"], "cehkt" => ["ketch"], "eflty" => ["lefty"],
      "ehlls" => ["shell"], "aglor" => ["largo"], "acens" => ["canes"],
      "dikrs" => ["dirks"], "ackst" => ["stack", "tacks"], "brrsu" => ["burrs"],
      "adejp" => ["japed"], "eertx" => ["exert"], "aaenp" => ["paean"],
      "eeept" => ["tepee"], "eintu" => ["untie", "unite"], "abcsu" => ["scuba"],
      "eegin" => ["genie"], "dgoru" => ["gourd"], "bhmtu" => ["thumb"],
      "knosw" => ["knows"], "acckl" => ["clack"], "bbimo" => ["bimbo"],
      "adder" => ["adder", "dared", "dread"], "bchtu" => ["butch"],
      "aklst" => ["stalk", "talks"], "defiy" => ["edify", "deify"],
      "aeflm" => ["flame"], "mssuy" => ["mussy"], "deknu" => ["nuked"],
      "aeinn" => ["inane"], "eemns" => ["semen"], "asstv" => ["vasts"],
      "begot" => ["begot"], "deimn" => ["denim", "mined"], "ehnor" => ["heron"],
      "irsst" => ["stirs"], "acdeg" => ["cadge", "caged"], "fmors" => ["forms"],
      "aepry" => ["payer", "repay"], "ddeik" => ["diked"], "bceip" => ["bicep"],
      "ensst" => ["nests"], "aglss" => ["slags", "glass"], "lmpuy" => ["lumpy"],
      "ceimn" => ["mince"], "aclsw" => ["claws"], "cghsu" => ["chugs"],
      "aelmy" => ["mealy"], "ddees" => ["deeds"], "eilov" => ["voile", "olive"],
      "efors" => ["fores"], "dinsw" => ["winds"], "einrt" => ["inert", "inter"],
      "acetu" => ["acute"], "ailss" => ["sisal", "sails"],
      "aclps" => ["claps", "clasp", "scalp"], "aertw" => ["water"],
      "aehvy" => ["heavy"], "doost" => ["stood"], "efrst" => ["frets"],
      "ckkno" => ["knock"], "dnoru" => ["round"], "ceips" => ["epics", "spice"],
      "aesss" => ["asses"], "cghlu" => ["gulch"], "cntuu" => ["uncut"],
      "efstu" => ["fetus"], "afilp" => ["pilaf"],
      "aprsy" => ["raspy", "prays", "spray"], "dfloo" => ["flood"],
      "ahist" => ["saith"], "adelt" => ["delta", "dealt"],
      "aehrt" => ["hater", "earth", "heart"], "aajnp" => ["japan"],
      "alnpt" => ["plant"], "altuv" => ["vault"], "afist" => ["fiats"],
      "abqsu" => ["squab"], "oprsu" => ["pours"],
      "eorsv" => ["servo", "roves", "overs"], "aehnn" => ["henna"],
      "ckuyy" => ["yucky"], "ehoss" => ["hoses", "shoes"],
      "eegnr" => ["genre", "green"], "fnnuy" => ["funny"], "bkoos" => ["books"],
      "doosw" => ["woods"], "ehnos" => ["hones", "shone"], "iippt" => ["pipit"],
      "bbmos" => ["bombs"], "egirt" => ["tiger"], "aenst" => ["antes"],
      "aehrs" => ["rheas", "hares", "shear", "hears", "share"],
      "acelp" => ["place"], "dlouw" => ["would"], "beopr" => ["probe"],
      "abckl" => ["black"], "aagrs" => ["ragas"], "ceimr" => ["crime"],
      "bdins" => ["binds"], "eghiw" => ["weigh"], "beegr" => ["grebe"],
      "frruy" => ["furry"], "eghru" => ["huger"], "ehitw" => ["white"],
      "abssy" => ["abyss"], "bnrsu" => ["burns"], "cdelu" => ["clued"],
      "mprtu" => ["trump"], "cipsy" => ["spicy"], "eortv" => ["overt", "voter"],
      "gstuy" => ["gutsy", "gusty"], "ceiir" => ["icier"], "aorrw" => ["arrow"],
      "aemns" => ["manse", "manes", "means", "names"], "ddehi" => ["hided"],
      "aelpt" => ["petal", "pleat", "plate"], "iknst" => ["knits", "stink"],
      "hotuy" => ["youth"], "eenpr" => ["preen"], "aalst" => ["atlas"],
      "einpt" => ["inept"], "cehin" => ["niche"], "fills" => ["fills"],
      "adkov" => ["vodka"], "aflos" => ["foals", "loafs"], "chlot" => ["cloth"],
      "eqstu" => ["quest"], "abbes" => ["babes"], "defit" => ["fetid"],
      "hkoos" => ["hooks", "shook"], "dgirs" => ["girds", "grids"],
      "adipv" => ["vapid"], "adlos" => ["loads"], "ehnop" => ["phone"],
      "clops" => ["clops"], "ahilp" => ["phial"], "ahrry" => ["harry"],
      "glorw" => ["growl"], "eglov" => ["glove"], "aemsz" => ["mazes"],
      "ceirr" => ["crier"], "cdeop" => ["coped"],
      "aersw" => ["wares", "swear", "wears"], "aefkr" => ["faker", "freak"],
      "adlmy" => ["madly"], "ehnsw" => ["whens"], "eltux" => ["exult"],
      "deinp" => ["pined"], "ceors" => ["cores", "score"], "acdes" => ["cased"],
      "aeimz" => ["maize"], "aeggu" => ["gauge"], "ceehr" => ["cheer"],
      "ddruy" => ["ruddy"], "einrv" => ["riven"], "deehs" => ["heeds"],
      "aaerw" => ["aware"], "denpw" => ["pwned"], "dekop" => ["poked"],
      "cdhit" => ["ditch"], "aehsy" => ["yeahs"], "ffist" => ["tiffs", "stiff"],
      "gnoss" => ["songs"], "elmpu" => ["plume"], "einnr" => ["inner"],
      "acdem" => ["maced"], "aelrt" => ["alert", "alter", "later"],
      "ceitv" => ["civet", "evict"], "eilsw" => ["wiles"], "eiops" => ["poise"],
      "eikst" => ["kites"], "cdnoo" => ["condo"], "alssy" => ["slays"],
      "deovw" => ["vowed"], "fimot" => ["motif"], "iloop" => ["polio"],
      "gloss" => ["gloss", "slogs"], "cimnu" => ["cumin"], "cintu" => ["tunic"],
      "gillr" => ["grill"], "ddeos" => ["dosed"], "cenor" => ["crone"],
      "ciilv" => ["civil"], "eeprs" => ["spree", "peers"], "cenoz" => ["cozen"],
      "eirrs" => ["riser"], "iorst" => ["riots", "trios"], "aeptu" => ["taupe"],
      "deotu" => ["outed"], "esstz" => ["zests"], "gills" => ["gills"],
      "abelz" => ["blaze"], "bdeem" => ["embed"], "klosy" => ["yolks"],
      "aalnv" => ["naval"], "elsty" => ["style"], "eikps" => ["pikes", "spike"],
      "ceott" => ["octet"], "ackms" => ["smack"], "gllsu" => ["gulls"],
      "efmru" => ["femur"], "lrtuy" => ["truly"], "bcksu" => ["bucks"],
      "benst" => ["bents"], "cikpr" => ["prick"], "dehpy" => ["hyped"],
      "cikrt" => ["trick"], "abikt" => ["batik"],
      "aersv" => ["avers", "saver", "raves"], "aclrw" => ["crawl"],
      "closu" => ["locus"], "lnooy" => ["loony"], "bills" => ["bills"],
      "adefz" => ["fazed"], "ghitt" => ["tight"], "isttw" => ["twits", "twist"],
      "ilmps" => ["limps"], "dimos" => ["misdo"], "imotv" => ["vomit"],
      "achty" => ["yacht"], "iklns" => ["kilns", "slink", "links"],
      "eeepw" => ["pewee"], "einnu" => ["ennui"], "acfkr" => ["frack"],
      "dikss" => ["disks", "skids"], "chipt" => ["pitch"], "ailty" => ["laity"],
      "ikmns" => ["minks"], "hortw" => ["wroth", "throw", "worth"],
      "dgoos" => ["goods"], "bemos" => ["besom"], "eills" => ["lisle"],
      "ceiju" => ["juice"], "acfnr" => ["franc"], "bhirt" => ["birth"],
      "hippy" => ["hippy"], "anrst" => ["rants"], "eorsu" => ["euros", "rouse"],
      "abinr" => ["brain"], "efosx" => ["foxes"], "bdeik" => ["biked"],
      "chilz" => ["zilch"], "beisv" => ["vibes"], "gnssu" => ["snugs"],
      "hiost" => ["hoist"], "beemr" => ["ember"], "degin" => ["deign"],
      "hoost" => ["sooth", "hoots", "shoot"], "aehht" => ["heath"],
      "aalpp" => ["papal"], "booty" => ["booty"], "adens" => ["deans", "sedan"],
      "abcks" => ["backs"], "dlloy" => ["dolly"],
      "airst" => ["astir", "sitar", "stair"], "dfjor" => ["fjord"],
      "abcer" => ["brace"], "eepwy" => ["weepy"], "alloy" => ["alloy", "loyal"],
      "lorry" => ["lorry"], "ahksw" => ["hawks"], "ablrw" => ["brawl"],
      "acdir" => ["acrid"], "ajntu" => ["jaunt", "junta"], "bnoor" => ["boron"],
      "eerrs" => ["serer"], "norsw" => ["sworn"], "chrsu" => ["crush"],
      "imstt" => ["mitts"], "cinsz" => ["zincs"], "aegry" => ["gayer"],
      "ceruv" => ["curve"], "agglu" => ["gulag"], "oosty" => ["sooty"],
      "msttu" => ["mutts"], "hlost" => ["sloth"], "efnot" => ["often"],
      "oorst" => ["roost", "torso", "roots"], "defir" => ["fired", "fried"],
      "demmo" => ["modem"], "ddeit" => ["tided"], "ennot" => ["tenon", "tonne"],
      "ekopy" => ["pokey"], "eenuv" => ["venue"], "abims" => ["iambs"],
      "eejps" => ["jeeps"], "gostu" => ["gusto"], "eegns" => ["genes"],
      "affst" => ["staff"], "aekrs" => ["rakes"], "cklsu" => ["lucks"],
      "acelt" => ["cleat"], "llpsu" => ["pulls"], "ghlou" => ["ghoul"],
      "acdtu" => ["ducat"], "aklop" => ["polka"], "cginu" => ["cuing"],
      "aorrz" => ["razor"], "agims" => ["sigma"], "elmru" => ["lemur"],
      "acefr" => ["farce"], "jorru" => ["juror"], "iknrs" => ["rinks"],
      "bbhuy" => ["hubby"], "nnsuy" => ["sunny"], "belno" => ["noble"],
      "pppuy" => ["puppy"], "eginv" => ["given"], "eimnr" => ["miner"],
      "fginu" => ["fungi"], "hmost" => ["moths"], "ginor" => ["groin"],
      "cossw" => ["scows"], "clmop" => ["clomp"], "agsst" => ["stags"],
      "ippyz" => ["zippy"], "floty" => ["lofty"], "akmou" => ["oakum"],
      "mpstu" => ["stump"], "chist" => ["chits"], "binor" => ["robin"],
      "aders" => ["dears", "dares", "reads"], "abdey" => ["bayed", "beady"],
      "bmosw" => ["wombs"], "ilntu" => ["until"], "hoqtu" => ["quoth"],
      "egint" => ["tinge"], "abdes" => ["beads", "based"],
      "moprs" => ["proms", "romps"], "adegt" => ["gated"], "elstw" => ["welts"],
      "lopps" => ["plops"], "kknsu" => ["skunk"], "deegh" => ["hedge"],
      "aegrv" => ["grave"], "antuv" => ["vaunt"], "dkory" => ["dorky"],
      "accho" => ["coach"], "hmnpy" => ["nymph"], "dllos" => ["dolls"],
      "aessx" => ["saxes"], "bdloo" => ["blood"], "bdeos" => ["bodes"],
      "cderu" => ["crude", "cured"], "agrvy" => ["gravy"], "abhis" => ["sahib"],
      "ginot" => ["ingot"], "egluy" => ["gluey"], "abmru" => ["rumba"],
      "aekns" => ["snake", "sneak"], "dstuy" => ["dusty", "study"],
      "giinp" => ["piing"], "eersu" => ["reuse"], "deegg" => ["egged"],
      "rstty" => ["tryst"], "bhrsu" => ["shrub", "brush"], "iksst" => ["skits"],
      "cnstu" => ["cunts"], "aegls" => ["gales"],
      "eimrs" => ["rimes", "emirs", "mires", "miser"], "deimt" => ["timed"],
      "aiprs" => ["pairs"], "ablst" => ["blast"], "addej" => ["jaded"],
      "adeil" => ["ailed", "ideal"], "agort" => ["argot"], "chitw" => ["witch"],
      "fikrs" => ["frisk"], "acelv" => ["calve"], "aaimn" => ["mania"],
      "ginsz" => ["zings"], "aegim" => ["image"], "hhssu" => ["shush"],
      "elssw" => ["slews"], "fuyzz" => ["fuzzy"], "ailqu" => ["quail"],
      "dnoor" => ["donor"], "alrtu" => ["ultra"], "ansty" => ["tansy", "nasty"],
      "diimt" => ["timid"], "ikkns" => ["kinks"], "foprs" => ["profs"],
      "abhrs" => ["brash"], "ceehn" => ["hence"], "almsu" => ["alums", "mauls"],
      "ahlno" => ["halon"], "ehilt" => ["lithe"], "enstw" => ["newts"],
      "aghno" => ["hogan"], "diilv" => ["livid"], "aelnr" => ["renal", "learn"],
      "aamss" => ["amass"], "intuy" => ["unity"], "dirty" => ["dirty"],
      "adlsu" => ["lauds"], "ellqu" => ["quell"], "glssu" => ["slugs"],
      "ffgru" => ["gruff"], "aekno" => ["oaken"], "emnos" => ["omens"],
      "aensw" => ["wanes", "weans"], "hisst" => ["shits"], "ddeot" => ["doted"],
      "anttu" => ["taunt"], "beorx" => ["boxer"], "hllsu" => ["hulls"],
      "abcin" => ["cabin"], "aflor" => ["flora"], "acmpr" => ["cramp"],
      "anosv" => ["novas"], "ehlpw" => ["whelp"], "dkors" => ["dorks"],
      "fhoos" => ["hoofs"], "ehorw" => ["whore"], "ilptu" => ["tulip"],
      "abbno" => ["nabob"], "bdnou" => ["bound"], "aacep" => ["apace"],
      "iktty" => ["kitty"], "doopr" => ["droop"], "ehlot" => ["helot", "hotel"],
      "moors" => ["moors", "rooms"], "eemss" => ["seems"], "cklpu" => ["pluck"],
      "hostu" => ["shout", "thous", "south"], "celsw" => ["clews"],
      "ellss" => ["sells"], "abbls" => ["blabs"], "cghou" => ["cough"],
      "eisvw" => ["wives", "views"], "aghss" => ["shags"],
      "adekn" => ["knead", "naked"], "aegps" => ["gapes", "pages"],
      "adltu" => ["adult"], "ainps" => ["pains"],
      "aekst" => ["skate", "steak", "teaks", "stake", "takes"],
      "adegl" => ["glade"], "cdiss" => ["discs"], "ahksy" => ["shaky"],
      "aeest" => ["tease"], "aegmr" => ["gamer"], "eflno" => ["felon"],
      "denoz" => ["zoned", "dozen"], "ehrsw" => ["shrew"], "diivv" => ["vivid"],
      "histw" => ["whist", "whits"], "acilm" => ["claim"], "flloy" => ["folly"],
      "abins" => ["basin"], "dfnor" => ["frond"], "eipps" => ["pipes"],
      "emrry" => ["merry"], "bilor" => ["broil"],
      "eilps" => ["spiel", "plies", "piles"], "cklos" => ["locks"],
      "agott" => ["gotta"], "eilpr" => ["peril"], "cehos" => ["chose"],
      "mpssu" => ["sumps"], "aabft" => ["abaft"], "eflls" => ["fells"],
      "closw" => ["cowls", "scowl"], "opstu" => ["pouts", "spout"],
      "cgiln" => ["cling"], "aenot" => ["oaten", "atone"], "aemrt" => ["tamer"],
      "blrtu" => ["blurt"], "eloos" => ["loose"], "coost" => ["coots", "scoot"],
      "ahkrs" => ["harks", "shark"], "dlost" => ["dolts"],
      "eelpr" => ["leper", "repel"], "bmost" => ["tombs"], "admtu" => ["datum"],
      "aabhs" => ["abash"], "demop" => ["moped"], "alpty" => ["aptly"],
      "abdeg" => ["badge"], "aekow" => ["awoke"], "ehisv" => ["hives"],
      "cehnw" => ["wench"], "lmoos" => ["looms"], "dmpsu" => ["dumps"],
      "aenps" => ["aspen", "napes", "panes"], "adegr" => ["raged", "grade"],
      "iklmy" => ["milky"], "bilos" => ["boils"], "deisv" => ["vised", "dives"],
      "derru" => ["ruder"], "ceirs" => ["rices", "cries"],
      "deopt" => ["depot", "opted"], "eikrt" => ["trike"], "eikns" => ["skein"],
      "aegrs" => ["rages", "sager", "gears"], "efisx" => ["fixes"],
      "chlnu" => ["lunch"], "eepsv" => ["veeps"], "inprt" => ["print"],
      "adnrs" => ["darns"], "hlopx" => ["phlox"], "annoy" => ["annoy"],
      "abuzz" => ["abuzz"], "egssu" => ["guess"], "eglru" => ["gruel"],
      "ikrss" => ["risks"], "aknst" => ["stank", "tanks"], "eknow" => ["woken"],
      "belst" => ["belts"], "bdiln" => ["blind"], "deosw" => ["dowse", "sowed"],
      "opssu" => ["soups"], "dnorw" => ["drown"],
      "enrst" => ["terns", "rents", "stern"], "ceehk" => ["cheek"],
      "antty" => ["natty"], "efilr" => ["lifer", "rifle"], "elmxy" => ["xylem"],
      "iknos" => ["oinks"], "eekps" => ["peeks", "keeps"], "dimou" => ["odium"],
      "emssy" => ["messy"], "acegr" => ["grace"], "adhsy" => ["shady"],
      "aegrt" => ["grate", "great"], "istxy" => ["sixty"], "ginrw" => ["wring"],
      "absst" => ["stabs"], "deoss" => ["doses"], "bmpuy" => ["bumpy"],
      "cnssy" => ["syncs"], "iistv" => ["visit"], "deiss" => ["sides"],
      "aessv" => ["vases", "saves"], "bgiln" => ["bling"],
      "adgrs" => ["grads", "drags"], "hrruy" => ["hurry"], "ilmss" => ["slims"],
      "acesv" => ["caves"], "eentv" => ["event"], "aeknv" => ["knave"],
      "aderr" => ["rared"], "efrss" => ["serfs"], "emprs" => ["perms", "sperm"],
      "aeguz" => ["gauze"], "acinp" => ["panic"], "hirst" => ["shirt"],
      "denps" => ["pends", "spend"], "allps" => ["palls"], "aassy" => ["assay"],
      "aelst" => ["teals", "slate", "stale", "tales", "least", "steal"],
      "bosuy" => ["buoys"], "ilstt" => ["stilt", "tilts"]}
  end
end
