defmodule Jumble.ScowlDict.Size95.Length3.Dict do
  def get do
    %{"bez" => ["bez"], "loy" => ["loy"], "abo" => ["abo", "oba", "boa"],
      "aek" => ["ake", "kae", "kea"], "fgk" => ["kgf"], "imz" => ["miz"],
      "hot" => ["tho", "hot"], "aem" => ["ame", "eam", "mea", "mae"],
      "oow" => ["woo"], "ctu" => ["utc", "cut"],
      "afr" => ["raf", "arf", "fra", "far"], "mux" => ["mux"], "zzz" => ["zzz"],
      "eoy" => ["yeo", "yoe", "oye"], "ahk" => ["hak", "kha"],
      "dgu" => ["gud", "dug"], "abd" => ["abd", "dab", "bad"],
      "lor" => ["orl", "lor"], "hip" => ["iph", "phi", "hip"],
      "afp" => ["afp", "fap"], "elu" => ["lue", "ule", "leu"], "swy" => ["swy"],
      "inu" => ["uni"], "bgi" => ["gib", "big"], "osy" => ["oys", "yos", "soy"],
      "pru" => ["pur", "urp"], "imx" => ["mix"], "bms" => ["msb"],
      "abf" => ["afb", "fab"], "ikl" => ["kil", "ilk"],
      "nru" => ["nur", "urn", "run"], "gmy" => ["myg", "gym"],
      "bde" => ["bde", "deb", "bed"], "dsu" => ["uds", "sud"], "gox" => ["gox"],
      "lot" => ["tlo", "tol", "lot"], "bnw" => ["nbw", "wbn"],
      "agj" => ["gaj", "jag"], "muy" => ["yum"], "cly" => ["lyc", "cly"],
      "ehu" => ["hue"], "elp" => ["pel", "lep"], "bgl" => ["glb"],
      "ehi" => ["hei", "hie"], "egu" => ["gue"], "hnt" => ["nth"], "eov" => ["voe"],
      "bel" => ["elb"], "ajy" => ["jay"], "frt" => ["tfr", "trf"], "htw" => ["hwt"],
      "gry" => ["gry"], "ano" => ["noa", "ona"], "aat" => ["taa"],
      "aey" => ["yea", "aye"], "eil" => ["eli", "ile", "lei", "lie"],
      "deu" => ["due"], "bil" => ["lib"], "iqu" => ["qui"], "ooz" => ["zoo"],
      "hop" => ["pho", "poh", "hop"], "nno" => ["non"], "ggi" => ["igg", "gig"],
      "cfm" => ["mcf"], "acy" => ["acy", "cay"], "npw" => ["pwn"],
      "ahp" => ["aph", "hap", "pah"], "apu" => ["pau", "pua"], "ivy" => ["ivy"],
      "aes" => ["aes", "ase", "eas", "sea"], "ekw" => ["ewk"], "mmo" => ["mom"],
      "fnu" => ["fun"], "ewy" => ["wey", "wye", "yew"], "afn" => ["naf", "fan"],
      "gkr" => ["kgr"], "ott" => ["tot"], "psw" => ["psw"], "hlo" => ["hol"],
      "doy" => ["yod"], "clt" => ["tlc"], "iju" => ["uji"], "cgo" => ["cog"],
      "abl" => ["alb", "lab"], "aft" => ["aft", "fat"], "dop" => ["dop", "pod"],
      "bdo" => ["bod", "dob"], "imn" => ["nim"], "imm" => ["mim"], "sst" => ["tss"],
      "crs" => ["crs"], "cgi" => ["cig"], "cox" => ["cox"], "fno" => ["fon"],
      "mps" => ["pms"], "fll" => ["fll"], "crt" => ["crt"], "eej" => ["jee"],
      "chi" => ["ich", "hic", "chi"], "flu" => ["flu"], "aln" => ["aln", "lan"],
      "ops" => ["ops", "sop"], "epy" => ["pye", "yep"], "tux" => ["tux"],
      "lnp" => ["lpn"], "eit" => ["tie"], "otv" => ["tov"],
      "ehr" => ["rhe", "reh", "her"], "efk" => ["kef"], "hny" => ["hny"],
      "ior" => ["rio", "roi"], "fil" => ["lif", "fil"],
      "now" => ["now", "own", "won"], "app" => ["ppa", "pap"], "lnt" => ["tln"],
      "lnr" => ["lnr"], "hoy" => ["hoy"], "oos" => ["oos"], "acm" => ["mac", "cam"],
      "hku" => ["khu"], "ovw" => ["vow"], "gmt" => ["gmt"], "bfi" => ["fbi", "fib"],
      "amy" => ["amy", "mya", "yam", "may"], "ajn" => ["jan"],
      "atx" => ["xat", "tax"], "frs" => ["rfs"], "ikm" => ["kim"], "ept" => ["pet"],
      "psy" => ["spy"], "amt" => ["tam", "mat"], "clu" => ["cul"], "fik" => ["kif"],
      "aps" => ["asp", "pas", "sap", "spa"], "itt" => ["tit"], "rsy" => ["syr"],
      "aly" => ["aly", "lay"], "bow" => ["wob", "bow"], "prt" => ["trp"],
      "aoz" => ["azo", "zoa"], "ddo" => ["dod", "odd"], "akr" => ["kra", "ark"],
      "alx" => ["lax"], "cht" => ["tch"], "mpv" => ["mvp"], "ell" => ["ell"],
      "euy" => ["yue", "uey"], "foy" => ["foy"], "dkl" => ["dkl"], "diy" => ["yid"],
      "esz" => ["sez"], "ors" => ["ros", "ors"], "dix" => ["dix"],
      "eny" => ["eyn", "nye", "yen"], "enn" => ["nne"], "dim" => ["mid", "dim"],
      "beg" => ["geb", "beg"], "cno" => ["nco", "con"], "fio" => ["iof"],
      "bsw" => ["sbw", "wbs"], "ajw" => ["jaw"], "opp" => ["pop"],
      "eeg" => ["eeg", "gee"], "dqt" => ["qtd"], "lou" => ["luo"], "kop" => ["kop"],
      "aot" => ["toa", "tao", "oat"], "ddm" => ["dmd"], "est" => ["set"],
      "aet" => ["eta", "ate", "eat", "tea"], "iio" => ["oii"],
      "auv" => ["uva", "vau"], "flo" => ["flo", "lof"], "bch" => ["bch", "hcb"],
      "ilr" => ["lir"], "deh" => ["edh"], "cpt" => ["cpt", "tcp"],
      "imo" => ["imo", "moi"], "mru" => ["rum"], "ssw" => ["ssw"],
      "orw" => ["wro", "row"], "dos" => ["dso", "ods", "dos", "sod"],
      "inn" => ["inn"], "bfr" => ["rfb"], "etw" => ["ewt", "tew", "wet"],
      "aqu" => ["qua"], "kou" => ["kou", "ouk"], "dht" => ["thd"], "ill" => ["ill"],
      "dei" => ["dei", "ide", "die"], "oty" => ["yot", "toy"], "kno" => ["kon"],
      "bcc" => ["cbc"], "hpp" => ["pph"], "bio" => ["obi"], "fop" => ["fop"],
      "cju" => ["cuj"], "hmm" => ["hmm"], "ipv" => ["vip"], "lmo" => ["olm"],
      "hor" => ["rho"], "ein" => ["nei", "nie"], "den" => ["ned", "den", "end"],
      "bpy" => ["byp"], "cit" => ["tic"], "aim" => ["mia", "ami", "aim"],
      "bgn" => ["nbg"], "ekz" => ["zek"], "itz" => ["zit"], "uzz" => ["zuz"],
      "iko" => ["oki", "koi", "oik"], "ilo" => ["ilo", "oil"],
      "gim" => ["gim", "mig"], "fgo" => ["fog"], "emn" => ["men"],
      "rsu" => ["sur", "urs"], "avx" => ["vax"], "eik" => ["eik", "ike", "kie"],
      "www" => ["www"], "cfh" => ["cfh"], "bbu" => ["bub"],
      "nsu" => ["uns", "nus", "sun"], "imu" => ["imu"], "acu" => ["uca"],
      "elr" => ["ler", "rle"], "afm" => ["mfa"],
      "ilp" => ["ipl", "pil", "pli", "lip"], "hss" => ["ssh"], "jnr" => ["jnr"],
      "duw" => ["wud"], "rty" => ["tyr", "try"], "abe" => ["bae"],
      "opu" => ["oup", "upo"], "coo" => ["coo"], "oru" => ["our"],
      "fot" => ["fot", "oft"], "orx" => ["rox"], "etz" => ["tez"],
      "ipt" => ["tpi", "pit", "tip"], "ahi" => ["ahi", "hia"],
      "los" => ["los", "sol"], "nov" => ["nov", "von"], "cpy" => ["cyp"],
      "dll" => ["ldl", "lld"], "emu" => ["ume", "meu", "emu"], "iiv" => ["vii"],
      "ben" => ["ebn", "nbe", "ben", "neb"], "egv" => ["veg"], "lno" => ["nol"],
      "mst" => ["mst", "mts", "stm"], "ccm" => ["ccm"], "enp" => ["nep", "pen"],
      "alw" => ["alw", "awl", "law"], "bir" => ["rib"], "cei" => ["ice"],
      "ent" => ["net", "ten"], "bll" => ["llb"], "iii" => ["iii"], "grx" => ["grx"],
      "ajk" => ["jak"], "eez" => ["zee"], "mmu" => ["umm", "mum"], "aix" => ["aix"],
      "eey" => ["yee", "eye"], "ekx" => ["kex"], "add" => ["dad", "add"],
      "ppt" => ["ptp"], "ccf" => ["cfc"], "pry" => ["pyr", "pry"],
      "ady" => ["ady", "yad", "day"], "aru" => ["aru", "ura"],
      "acp" => ["apc", "cpa", "pac", "cap"], "ems" => ["esm", "ems", "mes"],
      "def" => ["fed"], "suy" => ["yus"], "blo" => ["blo", "bol", "lob"],
      "ary" => ["ayr", "ary", "yar", "rya", "ray"], "ckw" => ["ckw"],
      "hps" => ["shp"], "nuw" => ["wun"], "isu" => ["sui"], "mow" => ["wmo", "mow"],
      "ddt" => ["ddt", "dtd"], "alu" => ["aul", "ula"], "opy" => ["poy"],
      "bet" => ["bet"], "dit" => ["itd", "tid", "dit"],
      "ads" => ["das", "ads", "sad"], "ego" => ["geo", "ego"], "cls" => ["lsc"],
      "drt" => ["tdr"], "eht" => ["eth", "the"], "een" => ["een", "ene"],
      "abp" => ["bap"], "esu" => ["sue", "use"], "eop" => ["ope"], "bfo" => ["fob"],
      "mrs" => ["mrs"], "afk" => ["kaf"], "ahy" => ["yah", "hay"],
      "ast" => ["ast", "tas", "sat"], "ceh" => ["ech", "che"], "lmy" => ["lym"],
      "isy" => ["yis"], "kkk" => ["kkk"], "abc" => ["abc", "bac", "cab"],
      "bht" => ["thb"], "eru" => ["ure", "rue"], "gno" => ["gon", "nog"],
      "guy" => ["yug", "guy"], "efo" => ["eof", "foe"], "giu" => ["gui"],
      "hox" => ["hox"], "anr" => ["arn", "nar", "rna", "ran"],
      "ceo" => ["ceo", "eco"], "ipr" => ["ipr", "pir", "rip"], "ekp" => ["kep"],
      "adw" => ["awd", "daw", "wad"], "iwz" => ["wiz"],
      "agr" => ["arg", "gra", "gar", "rag"], "cho" => ["cho", "hoc", "och"],
      "abb" => ["bab", "abb"], "cik" => ["ick"], "cce" => ["ecc"], "dir" => ["rid"],
      "dpu" => ["pud"], "atu" => ["tua", "uta", "tau"],
      "efi" => ["fei", "ife", "fie"], "aor" => ["aor", "ora", "oar"],
      "egm" => ["meg", "gem"], "ewx" => ["wex"], "anv" => ["van"], "flp" => ["plf"],
      "dis" => ["ids", "dis"], "owx" => ["wox"], "del" => ["dle", "eld", "led"],
      "ruw" => ["wur"], "clo" => ["loc"], "iqs" => ["iqs", "qis"],
      "guv" => ["vug", "guv"], "ens" => ["ens"], "htu" => ["hut"],
      "bes" => ["ebs", "sbe", "bes"], "fvw" => ["vfw"], "acl" => ["lca", "lac"],
      "ehp" => ["peh", "hep"], "gju" => ["gju", "jug"], "biu" => ["ubi"],
      "agv" => ["vag"], "nop" => ["pon"], "fms" => ["sfm"],
      "aer" => ["aer", "rea", "ear", "era", "are"], "kly" => ["kyl"],
      "bjo" => ["job"], "ilt" => ["til", "lit"], "orv" => ["vor"], "tuy" => ["tuy"],
      "ffo" => ["off"], "aep" => ["epa", "ape", "pea"],
      "aal" => ["aal", "laa", "ala"], "dry" => ["dry"], "ino" => ["oni", "ion"],
      "cnu" => ["cun", "unc"], "oww" => ["wow"], "ajs" => ["saj"],
      "fgr" => ["frg", "grf"], "efr" => ["erf", "fer", "ref"],
      "bmo" => ["bom", "omb", "mob"], "efu" => ["feu"], "agu" => ["gau"],
      "agz" => ["zag"], "det" => ["ted"], "egg" => ["egg"], "bbi" => ["bib"],
      "boy" => ["yob", "boy"], "hio" => ["hoi"], "eio" => ["oie"],
      "act" => ["act", "cat"], "dot" => ["tod", "dot"], "deq" => ["qed"],
      "afl" => ["alf"], "ahj" => ["jah", "haj"], "deo" => ["edo", "ode", "doe"],
      "bcd" => ["bcd", "dcb"], "bhu" => ["hub"], "aco" => ["oca"],
      "glu" => ["gul", "lug"], "stu" => ["ust", "uts"], "hmz" => ["mhz"],
      "eno" => ["neo", "one"], "eip" => ["epi", "pie"], "suz" => ["suz"],
      "lsy" => ["lys", "sly"], "cst" => ["cst", "sct"], "ijt" => ["tji"],
      "eev" => ["vee", "eve"], "eps" => ["pes"], "tuu" => ["utu"],
      "amp" => ["amp", "map"], "eow" => ["woe", "owe"],
      "cfp" => ["fcp", "pcf", "pfc"], "dtt" => ["tdt"], "suw" => ["usw", "wus"],
      "bey" => ["bey", "bye"], "abs" => ["asb", "bas", "sab"], "dgm" => ["mgd"],
      "moo" => ["oom", "moo"], "opv" => ["opv"], "adt" => ["tad"], "exz" => ["zex"],
      "qrs" => ["qrs"], "aai" => ["iaa", "aia"], "fpx" => ["pfx"], "gps" => ["gps"],
      "dhy" => ["hyd"], "avw" => ["vaw"], "ovx" => ["vox"], "bdu" => ["bud", "dub"],
      "dnu" => ["dun"], "asv" => ["sav", "vas"], "axz" => ["zax"],
      "cop" => ["cpo", "cop"], "mqu" => ["qum"], "bhl" => ["lhb"], "bls" => ["bls"],
      "cdr" => ["cdr"], "fmt" => ["fmt"], "ail" => ["lai", "ail"], "elw" => ["lew"],
      "dgk" => ["dkg"], "ekn" => ["nek", "ken"], "psu" => ["pus", "sup", "ups"],
      "cil" => ["cli"], "dor" => ["dor", "rod"], "msy" => ["mys"],
      "ant" => ["ant", "tan"], "ajr" => ["raj", "jar"], "dfo" => ["fod"],
      "ikt" => ["kit"], "gjo" => ["jog"], "mrt" => ["trm"], "ntt" => ["tnt"],
      "bcf" => ["bcf"], "adl" => ["lad"], "lru" => ["lur"], "dmo" => ["mod"],
      "exy" => ["yex"], "ejo" => ["joe"], "bis" => ["sib", "bis"],
      "hos" => ["sho", "hos", "ohs"], "gtt" => ["gtt", "tgt"],
      "als" => ["asl", "sla", "als", "las", "sal"], "ckt" => ["tck"],
      "irz" => ["riz"], "iku" => ["kui"], "fiz" => ["fiz"], "dex" => ["dex", "xed"],
      "bhr" => ["rhb"], "emq" => ["meq"], "ejn" => ["jen"], "bor" => ["orb", "rob"],
      "cep" => ["cep", "pec"], "avv" => ["vav"], "ghz" => ["ghz"],
      "bgo" => ["gob", "bog"], "abi" => ["bai", "iba"], "apx" => ["apx", "pax"],
      "puw" => ["wup"], "epp" => ["pep"], "inv" => ["vin"], "eem" => ["mee", "eme"],
      "itu" => ["tiu", "uit", "uti", "tui"], "ehm" => ["meh", "hem"],
      "ber" => ["ber", "reb"], "ixx" => ["xix", "xxi"], "ils" => ["sil", "lis"],
      "giv" => ["vig"], "bcu" => ["ubc", "cub"], "hir" => ["hir"],
      "goy" => ["ygo", "goy"], "cpr" => ["cpr", "prc"], "mpu" => ["ump"],
      "iss" => ["sis"], "lux" => ["lux"], "muv" => ["vum"], "enw" => ["wen", "new"],
      "aht" => ["tha", "hat"], "pss" => ["sps"],
      "ist" => ["ist", "tsi", "tis", "its", "sit"], "dno" => ["nod", "don"],
      "alt" => ["tal"], "eho" => ["heo", "hoe"], "ams" => ["sma", "sam", "mas"],
      "hsy" => ["shy"], "anp" => ["nap", "pan"], "lmw" => ["lwm"],
      "ahs" => ["sah", "ahs", "sha", "ash", "has"], "cgt" => ["ctg", "gtc"],
      "bsy" => ["bys"], "bdh" => ["bhd"], "osw" => ["ows", "wos", "sow"],
      "eeh" => ["hee"], "iou" => ["iou", "oui"], "bru" => ["urb", "bur", "rub"],
      "stt" => ["tst"], "gmo" => ["mog"], "mtv" => ["tmv"], "cfs" => ["fcs", "scf"],
      "ehs" => ["ehs", "hes", "she"], "acr" => ["arc", "car"], "acz" => ["zac"],
      "gis" => ["gis"], "adh" => ["adh", "dha", "dah", "had"], "dmx" => ["mxd"],
      "etv" => ["vet"], "dky" => ["kyd"], "cis" => ["csi", "cis", "sic"],
      "foo" => ["ofo", "foo", "oof"], "amm" => ["mam"],
      "dip" => ["idp", "pid", "dip"], "ako" => ["ako", "koa", "oka", "oak"],
      "eim" => ["mei"], "dru" => ["dur", "rud", "urd"],
      "ado" => ["dao", "doa", "oad", "oda", "ado"], "rst" => ["trs"],
      "bef" => ["bef", "feb"], "cko" => ["ock"], "esy" => ["sey", "sye", "yes"],
      "dnp" => ["pdn"], "pst" => ["tps", "pst"], "dsy" => ["dys", "yds"],
      "ehx" => ["hex"], "imr" => ["mri", "mir", "rim"], "abw" => ["baw", "wab"],
      "beo" => ["boe", "obe"], "aev" => ["vae"], "fow" => ["fow"], "adu" => ["dau"],
      "ekv" => ["kev"], "kuy" => ["kyu", "yuk"], "ggr" => ["ggr"],
      "imt" => ["mit", "tim"], "emw" => ["wem", "mew"], "imv" => ["vim"],
      "aku" => ["aku", "auk"], "moz" => ["moz"], "cip" => ["cpi", "pci", "pic"],
      "adf" => ["afd", "fad"], "aas" => ["saa", "aas"], "aby" => ["aby", "bay"],
      "ijz" => ["jiz"], "aam" => ["aam", "ama", "maa"], "aaw" => ["awa"],
      "abg" => ["gab", "bag"], "agw" => ["gaw", "wag"], "bit" => ["tib", "bit"],
      "dmr" => ["mrd"], "eqs" => ["esq"], "fgp" => ["pfg"],
      "hoo" => ["hoo", "ooh", "oho"], "aho" => ["aho", "hao", "hoa"],
      "ayy" => ["yay"], "cgm" => ["mcg"], "cdf" => ["cdf", "cfd"], "frz" => ["rfz"],
      "noy" => ["ony", "noy", "yon"], "bnu" => ["nub", "bun"], "hms" => ["msh"],
      "hhu" => ["huh"], "cdu" => ["duc", "cud"], "apy" => ["pya", "yap", "pay"],
      "abr" => ["rab", "arb", "bra", "bar"], "iix" => ["xii"], "bbe" => ["ebb"],
      "ikn" => ["kin", "ink"], "tuw" => ["wut"], "aow" => ["woa"], "ett" => ["tet"],
      "akm" => ["kam", "mak"], "ars" => ["ars", "ras", "sar"], "aaa" => ["aaa"],
      "git" => ["tig", "git"], "ain" => ["ain"], "hnu" => ["unh", "hun"],
      "mtx" => ["mtx"], "lvy" => ["vly"], "dlo" => ["lod", "old"],
      "bim" => ["bim", "ibm", "mib"], "all" => ["all"], "eet" => ["tee"],
      "coy" => ["coy"], "nox" => ["nox"], "clx" => ["xcl"], "giw" => ["wig"],
      "dss" => ["sds"], "erz" => ["zer", "rez"], "mot" => ["mot", "tom"],
      "biz" => ["biz"], "ehl" => ["hel"], "qsu" => ["suq"], "eef" => ["fee"],
      "gru" => ["gur", "rug"], "dpt" => ["tpd"], "asz" => ["saz", "zas"],
      "fim" => ["imf"], "efz" => ["fez"], "afu" => ["ufa", "auf"],
      "eky" => ["kye", "key"], "dds" => ["dds"], "cmy" => ["myc"], "fix" => ["fix"],
      "gin" => ["ing", "nig", "gin"], "ade" => ["ade", "dea", "ead", "dae"],
      "jms" => ["jms"], "bmp" => ["mpb"], "iim" => ["imi"], "abu" => ["abu"],
      "qrt" => ["qtr"], "ghq" => ["ghq"], "aci" => ["cai"], "buy" => ["buy"],
      "bot" => ["tob"], "dls" => ["lsd"], "ipz" => ["zip"], "lny" => ["lyn"],
      "bos" => ["bos", "sob"], "lmt" => ["ltm"], "elo" => ["leo", "loe"],
      "egs" => ["seg"], "iks" => ["ksi", "ski"], "acf" => ["caf"], "hmu" => ["hum"],
      "got" => ["tog", "got"], "ach" => ["ach", "cha"], "aeg" => ["age"],
      "nww" => ["wnw"], "imp" => ["ipm", "imp"], "gos" => ["gos", "sog"],
      "eor" => ["oer", "ore", "roe"], "epz" => ["zep"], "aar" => ["ara"],
      "ees" => ["ese", "see"], "enz" => ["zen"], "ikp" => ["pik", "kip"],
      "lpw" => ["lwp"], "eft" => ["fet", "tef", "eft"], "adi" => ["ida", "aid"],
      "llu" => ["ull"], "his" => ["ihs", "shi", "ish", "his"],
      "eir" => ["eir", "rie", "rei", "ire"], "dez" => ["zed"], "ajp" => ["jap"],
      "dmu" => ["dum", "mud"], "ipy" => ["yip"], "agm" => ["gam"],
      "bho" => ["boh", "hob"], "bbo" => ["bob"], "fir" => ["fri", "rif", "fir"],
      "iln" => ["nil"], "nwy" => ["wyn"], "doz" => ["dzo"], "ijm" => ["jim"],
      "ost" => ["tos", "sot"], "bfu" => ["fub"], "agg" => ["gag"], "irx" => ["rix"],
      "iny" => ["yin"], "isw" => ["wis"], "cns" => ["cns"], "oxy" => ["yox", "oxy"],
      "izz" => ["ziz"], "egj" => ["jeg"], "puy" => ["puy", "yup"],
      "ael" => ["ela", "lea", "ale"], "emo" => ["moe", "emo"], "cem" => ["ecm"],
      "dhp" => ["dph", "phd"], "gnt" => ["tgn"], "sww" => ["wsw"], "cdi" => ["cid"],
      "ory" => ["ory", "yor"], "opz" => ["poz"], "huy" => ["yuh"], "ijn" => ["jin"],
      "pxy" => ["pyx"], "giz" => ["zig"], "dfi" => ["fid"], "fly" => ["fly"],
      "cjl" => ["jcl"], "anu" => ["una", "anu"], "goo" => ["goo"], "gor" => ["rog"],
      "akl" => ["kal", "lak"], "int" => ["nit", "tin"],
      "air" => ["ira", "rai", "ria", "air"], "gou" => ["gou"],
      "elm" => ["lem", "mel", "elm"], "cru" => ["ruc", "cru", "cur"],
      "afw" => ["waf", "faw"], "ios" => ["iso", "osi", "ios", "ois"],
      "lop" => ["olp", "pol", "lop"], "inz" => ["zin"], "diu" => ["iud", "dui"],
      "kow" => ["kow", "owk", "wok"], "ggo" => ["gog"], "bdm" => ["mbd"],
      "etu" => ["tue", "ute"], "ptt" => ["ptt"], "dej" => ["jed"], "aap" => ["apa"],
      "bns" => ["bns"], "blr" => ["brl"], "lxx" => ["lxx"], "iot" => ["toi"],
      "afo" => ["fao", "oaf"], "oop" => ["oop", "poo"], "osz" => ["ozs", "zos"],
      "not" => ["ont", "ton", "not"], "ttx" => ["txt"], "sty" => ["sty"],
      "dee" => ["dee"], "any" => ["yan", "nay", "any"], "gij" => ["jig"],
      "imw" => ["wim"], "csw" => ["csw"], "ely" => ["eyl", "ley", "lye"],
      "ffi" => ["iff"], "ejw" => ["jew"], "adk" => ["dak"], "ghp" => ["gph"],
      "adz" => ["zad"], "aop" => ["opa", "poa"], "crv" => ["vcr"],
      "dgp" => ["gdp", "gpd"], "luz" => ["luz"], "brr" => ["brr"], "luu" => ["ulu"],
      "ssu" => ["ssu", "sus"], "atw" => ["twa", "taw", "wat"], "abj" => ["jab"],
      "nqu" => ["unq"], "ehn" => ["hen"], "hoz" => ["zho"], "abh" => ["hab", "bah"],
      "ahu" => ["ahu", "auh", "hau"], "cim" => ["mic"], "els" => ["les", "els"],
      "opr" => ["por", "pro"], "lpu" => ["plu", "pul"], "fry" => ["fry"],
      "ekl" => ["lek", "elk"], "aks" => ["kas", "ska", "ask"],
      "apt" => ["atp", "apt", "pat", "tap"], "cor" => ["cro", "roc", "orc"],
      "egi" => ["gie"], "alp" => ["apl", "alp", "lap", "pal"], "bbs" => ["bbs"],
      "dhi" => ["hid"], "adr" => ["dar", "ard"], "npu" => ["unp", "pun"],
      "art" => ["tra", "tar", "rat", "art"], "bfs" => ["bsf", "fsb"],
      "cps" => ["csp"], "cfi" => ["ifc"], "ekr" => ["erk"],
      "asy" => ["yas", "ays", "say"], "dde" => ["ded", "edd"],
      "ceu" => ["ecu", "cue"], "brw" => ["bwr"], "ghu" => ["hug", "ugh"],
      "dfu" => ["fud"], "bew" => ["web"], "ips" => ["pis", "sip"],
      "cot" => ["cto", "otc", "toc", "cot"], "eot" => ["toe"], "aww" => ["waw"],
      "lnu" => ["nul", "unl"], "bfn" => ["bnf"], "loo" => ["loo"],
      "egk" => ["ekg", "keg"], "arz" => ["zar"], "agl" => ["gal", "lag"],
      "bmr" => ["bmr"], "cel" => ["cel"], "atz" => ["azt", "zat"],
      "ait" => ["tai", "ait"], "oqu" => ["quo"], "gmp" => ["gpm"],
      "aab" => ["aba", "baa"], "efy" => ["fey"], "dow" => ["owd", "wod", "dow"],
      "hty" => ["thy"], "eos" => ["eos", "oes", "ose"], "dmt" => ["mtd"],
      "eju" => ["jeu"], "ptu" => ["tup", "put"], "rwy" => ["wry"], "hho" => ["hoh"],
      "egz" => ["gez"], "emt" => ["tem", "met"], "aqt" => ["qat"], "agh" => ["hag"],
      "ipx" => ["pix"], "asx" => ["sax"], "dlr" => ["rld"], "kor" => ["rok", "kor"],
      "lps" => ["spl"], "adn" => ["dna", "nad", "dan", "and"], "joy" => ["joy"],
      "aan" => ["naa", "ana"], "low" => ["owl", "low"], "isx" => ["xis", "six"],
      "fmu" => ["fum"], "elt" => ["elt", "let"], "muu" => ["umu"],
      "abt" => ["abt", "bat", "tab"], "nsy" => ["nys", "sny"],
      "alo" => ["alo", "lao", "loa", "ola"], "lrt" => ["tlr"], "ckp" => ["kpc"],
      "auy" => ["ayu"], "fhs" => ["fsh", "shf"], "fin" => ["fin"],
      "moy" => ["moy", "yom"], "kst" => ["tsk"], "hii" => ["ihi"],
      "aew" => ["wae", "awe"], "ipp" => ["ppi", "pip"], "xxx" => ["xxx"],
      "hwy" => ["why"], "mou" => ["mou"], "efh" => ["ehf", "feh"], "ddi" => ["did"],
      "cee" => ["eec", "cee"], "ahr" => ["rha", "rah"], "gsu" => ["gus", "ugs"],
      "opt" => ["opt", "pot", "top"], "itw" => ["twi", "wit"], "hit" => ["hit"],
      "bdi" => ["dib", "bid"], "agn" => ["gan", "nag"], "bpx" => ["pbx"],
      "ins" => ["isn", "nis", "ins", "sin"], "fho" => ["foh"], "cpp" => ["pcp"],
      "doo" => ["doo"], "efw" => ["few"], "irs" => ["irs", "sri", "sir"],
      "akz" => ["zak"], "bpu" => ["pub"], "aeh" => ["hae"],
      "agy" => ["agy", "yag", "gay"], "fsu" => ["ufs"], "jot" => ["jot"],
      "afg" => ["fag"], "gov" => ["vog"], "att" => ["tat"], "rtu" => ["tur", "rut"],
      "bpp" => ["ppb"], "otu" => ["tou", "out"], "awx" => ["wax"],
      "egl" => ["gel", "leg"], "fis" => ["sif", "ifs"], "dks" => ["dks"],
      "clr" => ["crl"], "acw" => ["wac", "caw"], "oox" => ["oxo"],
      "asw" => ["swa", "aws", "saw", "was"], "acd" => ["dca", "cad"],
      "fou" => ["ouf", "ufo", "fou"], "fgu" => ["fug"], "aah" => ["aah", "aha"],
      "hry" => ["rhy"], "inx" => ["nix"], "lmu" => ["lum"], "oor" => ["oor", "roo"],
      "dew" => ["dew", "wed"], "eer" => ["eer", "ree", "ere"], "mmy" => ["mym"],
      "nnu" => ["unn", "nun"], "dny" => ["dyn"], "ioy" => ["iyo", "yoi"],
      "mos" => ["som", "oms"], "egr" => ["erg"], "rux" => ["rux"], "dil" => ["lid"],
      "mpt" => ["tpm"], "hmt" => ["thm", "tmh"], "gho" => ["hog"],
      "irt" => ["rti", "tri"], "afy" => ["fay"], "cft" => ["ctf"], "ouy" => ["you"],
      "din" => ["nid", "din"], "lpy" => ["ply"], "hiu" => ["hui"], "gil" => ["lig"],
      "how" => ["how", "who"], "ery" => ["eyr", "yer", "rye"],
      "elz" => ["lez", "zel"], "ags" => ["asg", "ags", "sag", "gas"],
      "nnw" => ["nnw"], "hmo" => ["hmo", "hom", "mho", "ohm"],
      "ikr" => ["kir", "irk"], "inr" => ["rin"], "eis" => ["ise", "sie", "sei"],
      "btv" => ["bvt"], "akt" => ["tak", "kat"], "egt" => ["gte", "teg", "get"],
      "acg" => ["cag"], "dhh" => ["hhd"], "coz" => ["coz"],
      "amr" => ["mar", "ram", "arm"], "isz" => ["isz"], "lms" => ["mls", "sml"],
      "inp" => ["nip", "pin"], "dgo" => ["god", "dog"], "xyz" => ["xyz"],
      "osv" => ["sov"], "bek" => ["keb"], "nos" => ["ons", "son"],
      "ers" => ["esr", "ers"], "adp" => ["dap", "pad"], "jow" => ["jow"],
      "koy" => ["yok"], "elv" => ["lev"], "ilm" => ["lim", "mil"], "grs" => ["grs"],
      "afq" => ["qaf"], "dlu" => ["lud"], "ess" => ["sse", "ess"],
      "der" => ["erd", "red"], "fip" => ["fip"], "chn" => ["chn"], "ehw" => ["hew"],
      "cdm" => ["cmd"], "ccs" => ["csc"], "amw" => ["awm", "maw"], "bee" => ["bee"],
      "oot" => ["oto", "oot", "too"], "fit" => ["fit"], "aik" => ["aik", "kai"],
      "ans" => ["nas", "san"], "dio" => ["ido"], "apw" => ["wap", "paw"],
      "tvw" => ["wtv"], "dju" => ["jud"], "lst" => ["lst", "slt"], "gir" => ["rig"],
      "gip" => ["pig"], "acv" => ["cva", "vac"], "ntu" => ["tun", "nut"],
      "abn" => ["abn", "nab", "ban"], "aiw" => ["iwa"], "dhl" => ["hdl", "hld"],
      "ort" => ["ort", "tor", "rot"], "des" => ["des", "esd", "sed"],
      "ddu" => ["dud"], "cdo" => ["doc", "cod"], "bce" => ["bec", "ecb"],
      "ahn" => ["han", "nah"], "ahh" => ["ahh"], "ahv" => ["hav"], "dux" => ["dux"],
      "rtw" => ["rtw"], "amn" => ["mna", "nam", "man"], "ajt" => ["jat", "taj"],
      "cry" => ["cry"], "bfl" => ["flb"], "gmu" => ["gum", "mug"], "hhs" => ["shh"],
      "iow" => ["iwo"], "pps" => ["pps"], "ehh" => ["heh"], "hrw" => ["whr"],
      "ppr" => ["prp"], "erv" => ["rev"], "aip" => ["pia"], "eew" => ["ewe", "wee"],
      "ghm" => ["mhg"], "cow" => ["cow"], "kps" => ["pks"], "ciy" => ["icy"],
      "ttu" => ["tut"], "bij" => ["jib"], "arw" => ["raw", "war"],
      "ivx" => ["xiv", "xvi"], "div" => ["vid"], "hpt" => ["tph", "pht"],
      "ksu" => ["suk"], "aag" => ["aga"], "cmo" => ["moc"], "mop" => ["pom", "mop"],
      "ejr" => ["jer"], "alm" => ["mal", "lam"], "dkm" => ["dkm"], "esx" => ["sex"],
      "rtt" => ["trt"], "eep" => ["pee"], "egp" => ["peg"], "cfy" => ["fcy"],
      "box" => ["box"], "ltu" => ["lut"], "bdl" => ["bld"], "aov" => ["avo", "ova"],
      "gnp" => ["gnp"], "erw" => ["rew"], "cmp" => ["cpm"], "agp" => ["gap"],
      "amu" => ["aum", "mau", "uma", "amu"], "cdg" => ["cdg", "gcd"],
      "mtu" => ["mut", "tum"], "cpu" => ["cup"], "ceg" => ["ecg"],
      "arx" => ["arx", "rax"], "osu" => ["ous", "sou"], "dho" => ["hod"],
      "opx" => ["pox"], "vxx" => ["xxv"], "ahl" => ["lah"], "etx" => ["tex"],
      "grr" => ["grr"], "dem" => ["dem"], "bmu" => ["bum"],
      "amo" => ["mao", "oam", "moa"], "ago" => ["goa", "ago"], "dfr" => ["fdr"],
      "adm" => ["dam", "mad"], "acn" => ["can"], "msu" => ["ums", "sum"],
      "aav" => ["ava"], "dey" => ["yed", "dey", "dye"], "noo" => ["noo", "oon"],
      "cpv" => ["pvc"], "ccy" => ["cyc"], "gio" => ["goi", "gio"],
      "ais" => ["sai", "ais"], "eko" => ["oke"], "hno" => ["noh"],
      "dgi" => ["gid", "dig"], "hiv" => ["hiv"], "akw" => ["awk", "kwa", "kaw"],
      "abv" => ["abv"], "cds" => ["scd"], "ccr" => ["crc"], "esw" => ["sew"],
      "epr" => ["pre", "rep", "per"], "lox" => ["lox"], "gow" => ["wog"],
      "awy" => ["yaw", "way"], "chl" => ["hcl"], "btu" => ["tub", "but"],
      "hpu" => ["phu", "puh", "hup"], "lpp" => ["ppl"], "bno" => ["bon", "nob"],
      "dhu" => ["dhu", "hud", "duh"], "oyy" => ["yoy"], "asu" => ["usa", "sau"],
      "aky" => ["kay", "yak"], "gpy" => ["gyp"], "drs" => ["dsr"], "buz" => ["buz"],
      "acs" => ["sac"], "bps" => ["pbs"], "gty" => ["tyg"], "ety" => ["tye", "yet"],
      "aty" => ["yat", "tay"], "gtu" => ["ugt", "tug", "gut"],
      "aos" => ["oas", "sao"], "krs" => ["krs"], "eel" => ["eel", "lee"],
      "apv" => ["pav", "pva"], "eiv" => ["ive", "vei", "vie"], "evx" => ["vex"],
      "ajm" => ["jam"], "aen" => ["nea", "ean", "ane", "nae"], "hik" => ["khi"],
      "ksy" => ["sky"], "bop" => ["pob", "bop"], "hin" => ["hin"], "ahm" => ["ham"],
      "iop" => ["ipo", "poi"], "glo" => ["gol", "log"], "aio" => ["iao"],
      "hkz" => ["khz"], "ejt" => ["jet"], "cks" => ["csk"],
      "afh" => ["fha", "haf", "fah"], "dik" => ["kid"],
      "gnu" => ["ung", "gnu", "gun"], "ppu" => ["pup"], "dqs" => ["sqd"],
      "hsu" => ["uhs", "ush"], "bgu" => ["gub", "bug"], "fgn" => ["fgn"],
      "hst" => ["hts", "sht", "tsh"], "atv" => ["tav", "vat"],
      "ahw" => ["wah", "wha", "haw"], "nor" => ["ron", "nor"],
      "dou" => ["oud", "udo", "duo"], "diq" => ["qid"], "bko" => ["bok", "kob"],
      "aij" => ["jai"], "apr" => ["apr", "rap", "par"], "tty" => ["tty", "tyt"],
      "llm" => ["llm"], "fox" => ["fox"], "otw" => ["owt", "tow", "wot", "two"],
      "eku" => ["euk", "kue", "uke"], "inw" => ["win"], "fgi" => ["gif", "fig"],
      "abm" => ["abm", "mab", "mba", "bam"], "for" => ["orf", "fro", "for"],
      "jtu" => ["jut"], "cmw" => ["cwm"], "eek" => ["eek", "eke"], "ass" => ["ass"],
      "blt" => ["blt"], "dft" => ["dft"], "akn" => ["kan", "nak"], "egy" => ["gye"],
      "iuz" => ["uzi"], "efs" => ["efs", "fes"], "alr" => ["lar"], "cuz" => ["cuz"],
      "bco" => ["boc", "cob"], "ekt" => ["ket"], "owy" => ["woy", "yow"],
      "ehy" => ["hye", "yeh", "hey"], "fru" => ["urf", "fur"],
      "bin" => ["nib", "bin"], "cet" => ["cte", "ect", "tec"],
      "opw" => ["pow", "wop"], "bsu" => ["sub", "bus"], "him" => ["him"],
      "aeu" => ["eau"], "apz" => ["zap"], "aiv" => ["iva", "via"],
      "efl" => ["efl", "elf"], "eoz" => ["ezo"], "irw" => ["wir"],
      "efn" => ["nef", "fen"], "adj" => ["jad"], "err" => ["err"],
      "ims" => ["mis", "ism", "sim"], "ace" => ["ace"], "boo" => ["obo", "boo"],
      "gpu" => ["gup", "pug"], "adg" => ["gad"], "anw" => ["naw", "awn", "wan"],
      "cjw" => ["wjc"], "afx" => ["fax"], "erx" => ["rex"], "gop" => ["gop"],
      "agt" => ["gat", "tag"], "fsz" => ["sfz"], "kln" => ["kln"], "lmx" => ["mlx"],
      "fsy" => ["fys"], "kos" => ["sok", "kos"], "epw" => ["pew"], "abk" => ["kab"],
      "guz" => ["guz"]}
  end
end
